Paparazzi UAS: sw/airborne/subsystems/actuators/actuators_mkk_v2.c File Reference
actuators_mkk_v2.c File Reference
Actuators driver for Mikrokopter motor controllers.
#include "subsystems/actuators.h"
#include "subsystems/actuators/actuators_mkk_v2.h"
#include "mcu_periph/i2c.h"
#include "mcu_periph/sys_time.h"
Functions
void actuators_mkk_v2_init (void)
static void actuators_mkk_v2_read (void)
void actuators_mkk_v2_set (void)
Variables
struct actuators_mkk_v2_struct actuators_mkk_v2
Detailed Description
Actuators driver for Mikrokopter motor controllers.
Definition in file actuators_mkk_v2.c.
Function Documentation
void actuators_mkk_v2_init (void)
Definition at line 36 of file actuators_mkk_v2.c.
References actuators_mkk_v2_telemetry_struct::Current, actuators_mkk_v2_struct::data, I2CTransSuccess, I2CTransTx, i2c_transaction::len_w, actuators_mkk_v2_telemetry_struct::MaxPWM, actuators_mkk_v2_struct::read_number, i2c_transaction::slave_addr, i2c_transaction::status, actuators_mkk_v2_telemetry_struct::Temperature, actuators_mkk_v2_struct::trans, i2c_transaction::type, and actuators_mkk_v2_telemetry_struct::Version.
static void actuators_mkk_v2_read (void) inline static
Definition at line 56 of file actuators_mkk_v2.c.
References actuators_mkk_v2, I2CTransTxRx, i2c_transaction::len_r, actuators_mkk_v2_struct::read_number, actuators_mkk_v2_struct::trans, and i2c_transaction::type.
Referenced by actuators_mkk_v2_set().
void actuators_mkk_v2_set (void)
Definition at line 67 of file actuators_mkk_v2.c.
References actuators_mkk_v2, actuators_mkk_v2_read(), i2c_transaction::buf, actuators_mkk_v2_telemetry_struct::Current, actuators_mkk_v2_struct::data, i2c_submit(), I2CTransTx, actuators_mkk_v2_telemetry_struct::MaxPWM, actuators_mkk_v2_struct::setpoint, SysTimeTimer, actuators_mkk_v2_telemetry_struct::Temperature, actuators_mkk_v2_struct::trans, i2c_transaction::type, and USEC_OF_SEC.
Variable Documentation
struct actuators_mkk_v2_struct actuators_mkk_v2
Definition at line 34 of file actuators_mkk_v2.c.
Referenced by actuators_mkk_v2_read(), actuators_mkk_v2_set(), and config_mkk_v2_periodic_telemetry().