Paparazzi UAS: sw/airborne/subsystems/actuators/actuators_sbus.h File Reference
actuators_sbus.h File Reference
Sbus actuator driver, which can output as 7 sbus channels at ~11ms.
#include "std.h"
Data Structures
struct ActuatorsSbus
Macros
#define ACTUATORS_SBUS_MAX_NB 16
#define ActuatorSbusSet(_i, _v) { actuators_sbus.cmds[_i] = _v; }
#define ActuatorsSbusInit() actuators_sbus_init()
#define ActuatorsSbusCommit() actuators_sbus_set()
Functions
void actuators_sbus_init (void)
void actuators_sbus_set (void)
Variables
struct ActuatorsSbus actuators_sbus
Detailed Description
Sbus actuator driver, which can output as 7 sbus channels at ~11ms.
Channels min, average and maximum should be: min 0 neutral 1023 max 2047
Definition in file actuators_sbus.h.
Data Structure Documentation
struct ActuatorsSbus
Definition at line 36 of file actuators_sbus.h.
Data Fields
int32_t cmds[ACTUATORS_SBUS_MAX_NB]
struct link_device * device
Macro Definition Documentation
#define ACTUATORS_SBUS_MAX_NB 16
Definition at line 33 of file actuators_sbus.h.
Referenced by actuators_sbus_send().
#define ActuatorSbusSet (_i, _v) { actuators_sbus.cmds[_i] = _v; }
Definition at line 47 of file actuators_sbus.h.
#define ActuatorsSbusCommit () actuators_sbus_set()
Definition at line 49 of file actuators_sbus.h.
#define ActuatorsSbusInit () actuators_sbus_init()
Definition at line 48 of file actuators_sbus.h.
Function Documentation
void actuators_sbus_init (void)
Definition at line 51 of file actuators_sbus.c.
References actuators_sbus, B100000, ActuatorsSbus::device, uart_periph_set_baudrate(), uart_periph_set_bits_stop_parity(), UBITS_8, UPARITY_EVEN, and USTOP_2.
void actuators_sbus_set (void)
Definition at line 62 of file actuators_sbus.c.
References actuators_sbus, actuators_sbus_send(), and ActuatorsSbus::device.
Variable Documentation
struct ActuatorsSbus actuators_sbus
Definition at line 45 of file actuators_sbus.c.
Referenced by actuators_sbus_init(), actuators_sbus_send(), and actuators_sbus_set().