Paparazzi UAS: sw/airborne/subsystems/actuators/actuators_asctec_v2_new.c File Reference
actuators_asctec_v2_new.c File Reference
Actuators driver for Asctec v2 motor controllers with the new I2C protocol.
#include "subsystems/actuators.h"
#include "subsystems/actuators/actuators_asctec_v2_new.h"
#include "mcu_periph/i2c.h"
#include "mcu_periph/sys_time.h"
Macros
#define ACTUATORS_ASCTEC_V2_SLAVE_ADDR 0x00
Functions
static uint16_t crc_update (uint16_t crc, uint8_t data)
void actuators_asctec_v2_init (void)
void actuators_asctec_v2_set (void)
Variables
struct ActuatorsAsctecV2 actuators_asctec_v2
Detailed Description
Actuators driver for Asctec v2 motor controllers with the new I2C protocol.
Definition in file actuators_asctec_v2_new.c.
Macro Definition Documentation
#define ACTUATORS_ASCTEC_V2_SLAVE_ADDR 0x00
Definition at line 32 of file actuators_asctec_v2_new.c.
Referenced by actuators_asctec_v2_init(), and actuators_asctec_v2_set().
Function Documentation
void actuators_asctec_v2_init (void)
Definition at line 40 of file actuators_asctec_v2_new.c.
References ACTUATORS_ASCTEC_V2_SLAVE_ADDR, ActuatorsAsctecV2::cmd, ActuatorsAsctecV2::cur_addr, FRONT, ActuatorsAsctecV2::i2c_trans, I2CTransSuccess, I2CTransTx, i2c_transaction::len_w, ActuatorsAsctecV2::nb_err, ActuatorsAsctecV2::new_addr, NONE, i2c_transaction::slave_addr, i2c_transaction::status, and i2c_transaction::type.
void actuators_asctec_v2_set (void)
Definition at line 53 of file actuators_asctec_v2_new.c.
References actuators_asctec_v2, ACTUATORS_ASCTEC_V2_SLAVE_ADDR, i2c_transaction::buf, ActuatorsAsctecV2::cmd, ActuatorsAsctecV2::cmds, crc, crc_update(), ActuatorsAsctecV2::cur_addr, i2c_receive(), i2c_submit(), ActuatorsAsctecV2::i2c_trans, i2c_transmit(), I2CTransDone, I2CTransFailed, I2CTransSuccess, I2CTransTx, i2c_transaction::len_w, ActuatorsAsctecV2::nb_err, ActuatorsAsctecV2::new_addr, NONE, REVERSE, SET_ADDR, i2c_transaction::status, SysTimeTimer, TEST, i2c_transaction::type, and USEC_OF_SEC.
static uint16_t crc_update (uint16_t crc, uint8_t data) static
Definition at line 183 of file actuators_asctec_v2_new.c.
Referenced by actuators_asctec_v2_set().
Variable Documentation
struct ActuatorsAsctecV2 actuators_asctec_v2
Definition at line 36 of file actuators_asctec_v2_new.c.
Referenced by actuators_asctec_v2_set().