Paparazzi UAS: sw/airborne/arch/chibios/subsystems/actuators/actuators_xvert.h File Reference
actuators_xvert.h File Reference
#include "subsystems/actuators/actuators_pwm_arch.h"
Data Structures
struct EscData
Macros
#define ESCS_START_BYTE 0xFE
#define ESCS_DATA_FLIPBIT 16384
#define ESCS_DATA_MYSTERYBIT 32768
#define ActuatorsXvertInit actuators_xvert_init
#define ActuatorXvertSet(_i, _v) { actuators_xvert_values[_i] = _v; }
#define ActuatorsXvertCommit actuators_xvert_commit
Functions
void actuators_xvert_commit (void)
void actuators_xvert_init (void)
Variables
int32_t actuators_xvert_values [ACTUATORS_PWM_NB]
Detailed Description
Author
Kevin van Hecke Actuators driver for X-vert VTOL motor controllers. Contains two normal pwm servos, and two custom driven escs through a propriety uart protocol.
Definition in file actuators_xvert.h.
Data Structure Documentation
struct EscData
Definition at line 35 of file actuators_xvert.h.
Data Fields
unsigned char crc
uint32_t d1
uint32_t d2
unsigned char id
unsigned char len
unsigned char start
Macro Definition Documentation
#define ActuatorsXvertCommit actuators_xvert_commit
Definition at line 57 of file actuators_xvert.h.
#define ActuatorsXvertInit actuators_xvert_init
Definition at line 55 of file actuators_xvert.h.
#define ActuatorXvertSet (_i, _v) { actuators_xvert_values[_i] = _v; }
Definition at line 56 of file actuators_xvert.h.
#define ESCS_DATA_FLIPBIT 16384
Definition at line 32 of file actuators_xvert.h.
Referenced by actuators_xvert_commit().
#define ESCS_DATA_MYSTERYBIT 32768
Definition at line 33 of file actuators_xvert.h.
Referenced by actuators_xvert_commit().
#define ESCS_START_BYTE 0xFE
Definition at line 31 of file actuators_xvert.h.
Referenced by actuators_xvert_commit().
Function Documentation
void actuators_xvert_commit (void)
Definition at line 91 of file actuators_xvert.c.
References actuators_pwm_commit(), actuators_pwm_values, actuators_xvert_values, crc, EscData::crc, crc8(), EscData::d1, EscData::d2, ESCS_DATA_FLIPBIT, ESCS_DATA_MYSTERYBIT, ESCS_PORT, ESCS_START_BYTE, EscData::id, EscData::len, PWM_SERVO_2, PWM_SERVO_3, EscData::start, XVERT_ESC_0, and XVERT_ESC_1.
void actuators_xvert_init (void)
Definition at line 84 of file actuators_xvert.c.
References actuators_pwm_arch_init().
Variable Documentation
int32_t actuators_xvert_values[ACTUATORS_PWM_NB]
Definition at line 37 of file actuators_xvert.c.
Referenced by actuators_xvert_commit().