Paparazzi UAS: sw/airborne/arch/chibios/subsystems/actuators/actuators_xvert.c File Reference
actuators_xvert.c File Reference
#include "actuators_xvert.h"
#include "subsystems/actuators/actuators_pwm_arch.h"
#include "subsystems/actuators/actuators_pwm.h"
#include "mcu_periph/uart.h"
Macros
#define ESCS_PORT (&((ESCS_UART).device))
#define GP 0x107 /* x^8 + x^2 + x + 1 */
#define DI 0xE7
Functions
static void init_crc8 (void)
void crc8 (unsigned char *crc, unsigned char m)
void actuators_xvert_init (void)
void actuators_xvert_commit (void)
Variables
int32_t actuators_xvert_values [ACTUATORS_PWM_NB]
static unsigned char crc8_table [256]
static int made_table = 0
Detailed Description
Author
Kevin van Hecke Actuators driver for X-vert VTOL motor controllers. Contains two normal pwm servos, and two custom driven escs through a propriety uart protocol.
Definition in file actuators_xvert.c.
Macro Definition Documentation
#define DI 0xE7
Definition at line 41 of file actuators_xvert.c.
Referenced by init_crc8().
#define ESCS_PORT (&((ESCS_UART).device))
Definition at line 33 of file actuators_xvert.c.
Referenced by actuators_xvert_commit().
#define GP 0x107 /* x^8 + x^2 + x + 1 */
Definition at line 40 of file actuators_xvert.c.
Function Documentation
void actuators_xvert_commit (void)
Definition at line 91 of file actuators_xvert.c.
References actuators_pwm_commit(), actuators_pwm_values, actuators_xvert_values, crc, EscData::crc, crc8(), EscData::d1, EscData::d2, ESCS_DATA_FLIPBIT, ESCS_DATA_MYSTERYBIT, ESCS_PORT, ESCS_START_BYTE, EscData::id, EscData::len, PWM_SERVO_2, PWM_SERVO_3, EscData::start, XVERT_ESC_0, and XVERT_ESC_1.
void actuators_xvert_init (void)
Definition at line 84 of file actuators_xvert.c.
References actuators_pwm_arch_init().
void crc8 (unsigned char * crc, unsigned char m)
Definition at line 69 of file actuators_xvert.c.
References crc8_table, init_crc8(), and made_table.
Referenced by actuators_xvert_commit().
static void init_crc8 (void) static
Definition at line 47 of file actuators_xvert.c.
References crc, crc8_table, DI, and made_table.
Referenced by crc8().
Variable Documentation
int32_t actuators_xvert_values[ACTUATORS_PWM_NB]
Definition at line 37 of file actuators_xvert.c.
Referenced by actuators_xvert_commit().
unsigned char crc8_table[256] static
Definition at line 44 of file actuators_xvert.c.
Referenced by crc8(), and init_crc8().
int made_table = 0 static
Definition at line 45 of file actuators_xvert.c.
Referenced by crc8(), and init_crc8().