Paparazzi UAS: sw/airborne/arch/lpc21/ADS8344.h File Reference
ADS8344.h File Reference
#include "std.h"
Macros
#define NB_CHANNELS 8
Functions
void ADS8344_init (void)
void ADS8344_start (void)
Variables
uint16_t ADS8344_values [NB_CHANNELS]
bool ADS8344_available
Macro Definition Documentation
#define NB_CHANNELS 8
Definition at line 28 of file ADS8344.h.
Function Documentation
void ADS8344_init (void)
Definition at line 88 of file ADS8344.c.
References _VIC_CNTL, ADS8344_available, ADS8344_SS_IODIR, ADS8344_SS_PIN, ADS8344Unselect, PINSEL1, SPI1_ISR(), SPI1_VIC_SLOT, SSP_CPHA, SSP_CPOL, SSP_DSS, SSP_FRF, SSP_LBM, SSP_MS, SSP_SCR, SSP_SOD, SSPCPSR, SSPCR0, SSPCR1, VIC_BIT, VIC_ENABLE, VIC_SPI1, VICIntEnable, and VICIntSelect.
void ADS8344_start (void)
Definition at line 132 of file ADS8344.c.
References ADS8344Select, send_request(), SpiClearRti(), SpiEnable, and SpiEnableRti().
Variable Documentation
bool ADS8344_available
Definition at line 38 of file ADS8344.c.
Referenced by ADS8344_init(), and SPI1_ISR().
uint16_t ADS8344_values[NB_CHANNELS]
Definition at line 39 of file ADS8344.c.
Referenced by read_values().