Paparazzi UAS: sw/airborne/subsystems/ahrs.c File Reference
ahrs.c File Reference
Dispatcher to register actual AHRS implementations.
#include "subsystems/ahrs.h"
#include "subsystems/ahrs/ahrs_aligner.h"
Data Structures
struct AhrsImpl
references a registered AHRS implementation
Macros
#define __RegisterAhrs(_x) _x ## _register()
#define _RegisterAhrs(_x) __RegisterAhrs(_x)
#define RegisterAhrs(_x) _RegisterAhrs(_x)
#define AHRS_NB_IMPL 2
maximum number of AHRS implementations that can register
Functions
void ahrs_register_impl (AhrsEnableOutput enable)
Register an AHRS implementation.
void ahrs_init (void)
AHRS initialization.
int ahrs_switch (uint8_t idx)
Switch to the output of another AHRS impl.
Variables
struct AhrsImpl ahrs_impls [AHRS_NB_IMPL]
uint8_t ahrs_output_idx
Detailed Description
Dispatcher to register actual AHRS implementations.
Definition in file ahrs.c.
Data Structure Documentation
struct AhrsImpl
references a registered AHRS implementation
Definition at line 55 of file ahrs.c.
Data Fields
AhrsEnableOutput enable
Macro Definition Documentation
#define __RegisterAhrs (_x) _x ## _register()
Definition at line 45 of file ahrs.c.
#define _RegisterAhrs (_x) __RegisterAhrs(_x)
Definition at line 46 of file ahrs.c.
#define AHRS_NB_IMPL 2
maximum number of AHRS implementations that can register
Definition at line 51 of file ahrs.c.
Referenced by ahrs_init(), ahrs_register_impl(), and ahrs_switch().
#define RegisterAhrs (_x) _RegisterAhrs(_x)
Definition at line 47 of file ahrs.c.
Referenced by ahrs_init().
Function Documentation
void ahrs_init (void)
AHRS initialization.
Called at startup. Registers/initializes the default AHRS.
Definition at line 73 of file ahrs.c.
References ahrs_aligner_init(), ahrs_impls, AHRS_NB_IMPL, ahrs_switch(), AhrsImpl::enable, PRIMARY_AHRS, and RegisterAhrs.
Referenced by init_ap(), and main_init().
void ahrs_register_impl (AhrsEnableOutput enable)
Register an AHRS implementation.
Adds it to an internal list.
Parameters
enable pointer to function to enable/disable the output of registering AHRS
Definition at line 62 of file ahrs.c.
References ahrs_impls, AHRS_NB_IMPL, and AhrsImpl::enable.
Referenced by ahrs_chimu_register(), ahrs_dcm_register(), ahrs_fc_register(), ahrs_float_invariant_register(), ahrs_gx3_register(), ahrs_ice_register(), ahrs_icq_register(), ahrs_madgwick_register(), ahrs_mlkf_register(), ahrs_sim_register(), and ahrs_vectornav_register().
int ahrs_switch (uint8_t idx)
Switch to the output of another AHRS impl.
Parameters
idx index of the AHRS impl (0 = PRIMARY_AHRS, 1 = SECONDARY_AHRS).
Definition at line 93 of file ahrs.c.
References ahrs_impls, AHRS_NB_IMPL, ahrs_output_idx, AhrsImpl::enable, FALSE, idx, and TRUE.
Referenced by ahrs_init().
Variable Documentation
struct AhrsImpl ahrs_impls[AHRS_NB_IMPL]
Definition at line 59 of file ahrs.c.
Referenced by ahrs_init(), ahrs_register_impl(), and ahrs_switch().
uint8_t ahrs_output_idx
Definition at line 60 of file ahrs.c.
Referenced by ahrs_switch().