Paparazzi UAS: sw/airborne/subsystems/ahrs/ahrs_int_cmpl_euler_wrapper.h File Reference
ahrs_int_cmpl_euler_wrapper.h File Reference
Paparazzi specific wrapper to run floating point DCM filter.
#include "subsystems/ahrs/ahrs_int_cmpl_euler.h"
Macros
#define PRIMARY_AHRS ahrs_ice
Functions
void ahrs_ice_register (void)
Detailed Description
Paparazzi specific wrapper to run floating point DCM filter.
Definition in file ahrs_int_cmpl_euler_wrapper.h.
Macro Definition Documentation
#define PRIMARY_AHRS ahrs_ice
Definition at line 33 of file ahrs_int_cmpl_euler_wrapper.h.
Function Documentation
void ahrs_ice_register (void)
Definition at line 196 of file ahrs_int_cmpl_euler_wrapper.c.
References ABI_BROADCAST, accel_cb(), accel_ev, ahrs_ice_enable_output(), AHRS_ICE_IMU_ID, ahrs_ice_init(), AHRS_ICE_MAG_ID, AHRS_ICE_OUTPUT_ENABLED, ahrs_register_impl(), aligner_cb(), aligner_ev, body_to_imu_cb(), body_to_imu_ev, DefaultPeriodic, gyro_cb(), gyro_ev, mag_cb(), mag_ev, register_periodic_telemetry(), send_bias(), send_euler(), send_filter(), and send_filter_status().