Paparazzi UAS: sw/airborne/subsystems/ahrs/ahrs_vectornav_wrapper.c File Reference
ahrs_vectornav_wrapper.c File Reference
Vectornav VN-200 as AHRS.
#include "subsystems/ahrs/ahrs_vectornav_wrapper.h"
#include "subsystems/ahrs.h"
#include "subsystems/abi.h"
#include "state.h"
#include "subsystems/datalink/telemetry.h"
Macros
#define AHRS_VECTORNAV_OUTPUT_ENABLED TRUE
Functions
static void send_euler (struct transport_tx *trans, struct link_device *dev)
static bool ahrs_vectornav_enable_output (bool enable)
bool ahrs_vectornav_is_enabled (void)
void ahrs_vectornav_register (void)
Variables
static bool ahrs_vectornav_output_enabled
if TRUE with push the estimation results to the state interface
static uint8_t ahrs_vectornav_id = AHRS_COMP_ID_VECTORNAV
Detailed Description
Vectornav VN-200 as AHRS.
Author
Michal Podhradsky micha.nosp@m.l.po.nosp@m.dhrad.nosp@m.sky@.nosp@m.aggie.nosp@m.mail.nosp@m..usu..nosp@m.edu
Definition in file ahrs_vectornav_wrapper.c.
Macro Definition Documentation
#define AHRS_VECTORNAV_OUTPUT_ENABLED TRUE
Definition at line 34 of file ahrs_vectornav_wrapper.c.
Referenced by ahrs_vectornav_register().
Function Documentation
static bool ahrs_vectornav_enable_output (bool enable) static
Definition at line 56 of file ahrs_vectornav_wrapper.c.
References ahrs_vectornav_output_enabled.
Referenced by ahrs_vectornav_register().
bool ahrs_vectornav_is_enabled (void)
Definition at line 62 of file ahrs_vectornav_wrapper.c.
References ahrs_vectornav_output_enabled.
Referenced by ahrs_vectornav_event().
void ahrs_vectornav_register (void)
Definition at line 66 of file ahrs_vectornav_wrapper.c.
References ahrs_register_impl(), ahrs_vectornav_enable_output(), ahrs_vectornav_init(), AHRS_VECTORNAV_OUTPUT_ENABLED, DefaultPeriodic, register_periodic_telemetry(), and send_euler().
static void send_euler (struct transport_tx * trans, struct link_device * dev) static
Definition at line 45 of file ahrs_vectornav_wrapper.c.
References ahrs_vectornav_id, ahrs_vn, VNData::attitude, FloatEulers::phi, FloatEulers::psi, FloatEulers::theta, and AhrsVectornav::vn_data.
Referenced by ahrs_vectornav_register().
Variable Documentation
uint8_t ahrs_vectornav_id = AHRS_COMP_ID_VECTORNAV static
Definition at line 40 of file ahrs_vectornav_wrapper.c.
Referenced by send_euler().
bool ahrs_vectornav_output_enabled static
if TRUE with push the estimation results to the state interface
Definition at line 39 of file ahrs_vectornav_wrapper.c.
Referenced by ahrs_vectornav_enable_output(), and ahrs_vectornav_is_enabled().