Paparazzi UAS: sw/airborne/firmwares/rotorcraft/stabilization/attitude_ref_saturate_naive.h File Reference
attitude_ref_saturate_naive.h File Reference
Naive attitude reference saturation.
#include "math/pprz_algebra_float.h"
#include "math/pprz_algebra_int.h"
Data Structures
struct FloatRefSat
struct Int32RefSat
Macros
#define SATURATE_SPEED_TRIM_ACCEL(_rate, _accel, _max_rate)
saturate angular speed and trim accel accordingly
Functions
static void attitude_ref_float_saturate_naive (struct FloatRates *rate, struct FloatRates *accel, struct FloatRefSat *sat)
static void attitude_ref_int_saturate_naive (struct Int32Rates *rate, struct Int32Rates *accel, struct Int32RefSat *sat)
Detailed Description
Naive attitude reference saturation.
Definition in file attitude_ref_saturate_naive.h.
Data Structure Documentation
struct FloatRefSat
Definition at line 32 of file attitude_ref_saturate_naive.h.
Data Fields
struct FloatRates max_accel
struct FloatRates max_rate
struct Int32RefSat
Definition at line 37 of file attitude_ref_saturate_naive.h.
Data Fields
struct Int32Rates max_accel
struct Int32Rates max_rate
Macro Definition Documentation
#define SATURATE_SPEED_TRIM_ACCEL (_rate, _accel, _max_rate)
Value:
{   \
    if ((_rate) >= (_max_rate)) {                               \
      (_rate) = (_max_rate);                                    \
      if ((_accel) > 0) {                                       \
        (_accel) = 0;                                           \
      }                                                         \
    }                                                           \
    else if ((_rate) <= -(_max_rate)) {                         \
      (_rate) = -(_max_rate);                                   \
      if ((_accel) < 0) {                                       \
        (_accel) = 0;                                           \
      }                                                         \
    }                                                           \
  }
saturate angular speed and trim accel accordingly
Definition at line 43 of file attitude_ref_saturate_naive.h.
Referenced by attitude_ref_float_saturate_naive(), and attitude_ref_int_saturate_naive().
Function Documentation
static void attitude_ref_float_saturate_naive (struct FloatRates * rate, struct FloatRates * accel, struct FloatRefSat * sat) inline static
Definition at line 58 of file attitude_ref_saturate_naive.h.
References FloatRefSat::max_accel, FloatRefSat::max_rate, FloatRates::p, FloatRates::q, FloatRates::r, RATES_BOUND_BOX_ABS, and SATURATE_SPEED_TRIM_ACCEL.
Referenced by attitude_ref_euler_float_update(), and attitude_ref_quat_float_update().
static void attitude_ref_int_saturate_naive (struct Int32Rates * rate, struct Int32Rates * accel, struct Int32RefSat * sat) inline static
Definition at line 71 of file attitude_ref_saturate_naive.h.
References Int32RefSat::max_accel, Int32RefSat::max_rate, Int32Rates::p, Int32Rates::q, Int32Rates::r, RATES_BOUND_BOX_ABS, and SATURATE_SPEED_TRIM_ACCEL.
Referenced by attitude_ref_quat_int_update().