Paparazzi UAS: sw/airborne/modules/e_identification_fr/e_identification_fr.h File Reference
e_identification_fr.h File Reference
Macros
#define E_Identification_Fr_Start() (e_identification_fr_e_identification_fr_periodic_status = MODULES_START)
#define E_Identification_Fr_Stop() (e_identification_fr_e_identification_fr_periodic_status = MODULES_STOP)
Enumerations
enum e_id_type {
E_ID_PROTOCOL_VERSION = 1, E_ID_ID_FR = 2, E_ID_ID_ANSI_UAS = 3, E_ID_LAT = 4,
E_ID_LON = 5, E_ID_HMSL = 6, E_ID_HAGL = 7, E_ID_LAT_TO = 8,
E_ID_LON_TO = 9, E_ID_H_SPEED = 10, E_ID_ROUTE = 11
}
Functions
void e_identification_fr_init (void)
void e_identification_fr_periodic (void)
Detailed Description
Author
Fabien Bonneval Format and send via UART tracking data according to French law.
Definition in file e_identification_fr.h.
Macro Definition Documentation
#define E_Identification_Fr_Start () (e_identification_fr_e_identification_fr_periodic_status = MODULES_START)
Definition at line 48 of file e_identification_fr.h.
#define E_Identification_Fr_Stop () (e_identification_fr_e_identification_fr_periodic_status = MODULES_STOP)
Definition at line 49 of file e_identification_fr.h.
Enumeration Type Documentation
enum e_id_type
Enumerator
E_ID_PROTOCOL_VERSION
E_ID_ID_FR
E_ID_ID_ANSI_UAS
E_ID_LAT
E_ID_LON
E_ID_HMSL
E_ID_HAGL
E_ID_LAT_TO
E_ID_LON_TO
E_ID_H_SPEED
E_ID_ROUTE
Definition at line 29 of file e_identification_fr.h.
Function Documentation
void e_identification_fr_init (void)
Definition at line 145 of file e_identification_fr.c.
References id_fr, LEN_ID_FR, LEN_ID_SERIAL, and Min.
void e_identification_fr_periodic (void)
Definition at line 158 of file e_identification_fr.c.
References ck_a, ck_b, GpsState::fix, gps, MAX_BUF_LEN, offset, put_alt(), put_horizontal_speed(), put_ID(), put_lat(), put_lat_lon_home(), put_lon(), put_route(), and uart_put_buffer().