Paparazzi UAS: sw/airborne/peripherals/eeprom25AA256.c File Reference
eeprom25AA256.c File Reference
#include "peripherals/eeprom25AA256.h"
Enumerations
enum Eeprom25AA256InstructionSet {
EEPROM_READ = 0x3, EEPROM_WRITE = 0x2, EEPROM_WRDI = 0x4, EEPROM_WREN = 0x6,
EEPROM_RDSR = 0x5, EEPROM_WRSR = 0x1
}
Instruction set.
Functions
void eeprom25AA256_init (struct Eeprom25AA256 *eeprom, struct spi_periph *spi_p, uint8_t slave_idx)
Init function.
void eeprom25AA256_read (struct Eeprom25AA256 *eeprom, uint16_t addr, uint16_t length)
Read function.
void eeprom25AA256_event (struct Eeprom25AA256 *eeprom)
Event function.
Enumeration Type Documentation
enum Eeprom25AA256InstructionSet
Instruction set.
Enumerator
EEPROM_READ
EEPROM_WRITE
EEPROM_WRDI
EEPROM_WREN
EEPROM_RDSR
EEPROM_WRSR
Definition at line 35 of file eeprom25AA256.c.
Function Documentation
void eeprom25AA256_event (struct Eeprom25AA256 * eeprom)
Event function.
Parameters
[in] eeprom pointer to 25AA256 eeprom struture
Definition at line 89 of file eeprom25AA256.c.
References Eeprom25AA256::data_available, Eeprom25AA256::spi_trans, SPITransDone, SPITransFailed, SPITransSuccess, and spi_transaction::status.
Referenced by meteo_stick_event().
void eeprom25AA256_init (struct Eeprom25AA256 * eeprom, struct spi_periph * spi_p, uint8_t slave_idx)
Init function.
Parameters
[in] eeprom pointer to 25AA256 eeprom struture
[in] spi_p pointer to spi device
[in] slave_idx SPI slive index
Definition at line 45 of file eeprom25AA256.c.
References spi_transaction::after_cb, spi_transaction::before_cb, spi_transaction::bitorder, spi_transaction::cdiv, spi_transaction::cpha, spi_transaction::cpol, spi_transaction::dss, spi_transaction::input_buf, spi_transaction::input_length, spi_transaction::output_buf, spi_transaction::output_length, Eeprom25AA256::rx_buf, spi_transaction::select, spi_transaction::slave_idx, Eeprom25AA256::spi_p, Eeprom25AA256::spi_trans, SPICphaEdge1, SPICpolIdleLow, SPIDiv128, SPIDss8bit, SPIMSBFirst, SPISelectUnselect, SPITransDone, spi_transaction::status, and Eeprom25AA256::tx_buf.
Referenced by meteo_stick_init().
void eeprom25AA256_read (struct Eeprom25AA256 * eeprom, uint16_t addr, uint16_t length)
Read function.
Parameters
[in] eeprom pointer to 25AA256 eeprom struture
[in] addr 16-bit start read address
[in] length number of bytes to read
Definition at line 72 of file eeprom25AA256.c.
References E25_IN_BUFFER_LEN, E25_OUT_BUFFER_LEN, EEPROM_READ, spi_transaction::input_length, spi_transaction::output_length, Eeprom25AA256::spi_p, spi_submit(), Eeprom25AA256::spi_trans, SPITransDone, spi_transaction::status, and Eeprom25AA256::tx_buf.
Referenced by meteo_stick_periodic().