Paparazzi UAS: sw/airborne/firmwares/fixedwing/main_chibios.c File Reference
main_chibios.c File Reference
#include "mcu_periph/sys_time.h"
#include "mcu.h"
#include <ch.h>
Macros
#define Fbw(f)
#define Ap(f)
#define AP_THREAD_STACK_SIZE 8192
#define FBW_THREAD_STACK_SIZE 1024
Functions
static void thd_ap (void *arg)
static THD_WORKING_AREA (wa_thd_ap, AP_THREAD_STACK_SIZE)
static void thd_fbw (void *arg)
static THD_WORKING_AREA (wa_thd_fbw, FBW_THREAD_STACK_SIZE)
int main (void)
Main function.
void pprz_terminate_autopilot_threads (void)
Terminate all autopilot threads Wait until proper stop.
Variables
static thread_t * apThdPtr = NULL
static thread_t * fbwThdPtr = NULL
Macro Definition Documentation
#define Ap (f)
Definition at line 49 of file main_chibios.c.
Referenced by main(), and thd_ap().
#define AP_THREAD_STACK_SIZE 8192
Definition at line 60 of file main_chibios.c.
#define Fbw (f)
Definition at line 42 of file main_chibios.c.
Referenced by main(), and thd_fbw().
#define FBW_THREAD_STACK_SIZE 1024
Definition at line 74 of file main_chibios.c.
Function Documentation
int main (void)
Main function.
Definition at line 87 of file main_chibios.c.
References Ap, apThdPtr, downlink_init(), Fbw, fbwThdPtr, init, thd_ap(), and thd_fbw().
void pprz_terminate_autopilot_threads (void)
Terminate all autopilot threads Wait until proper stop.
Definition at line 178 of file main_chibios.c.
Referenced by thdUsbStorage().
static void thd_ap (void * arg) static
Definition at line 127 of file main_chibios.c.
References Ap, CH_CFG_ST_FREQUENCY, and handle_periodic_tasks().
Referenced by main().
static void thd_fbw (void * arg) static
Definition at line 153 of file main_chibios.c.
References CH_CFG_ST_FREQUENCY, Fbw, and handle_periodic_tasks().
Referenced by main().
static THD_WORKING_AREA (wa_thd_ap , AP_THREAD_STACK_SIZE) static
static THD_WORKING_AREA (wa_thd_fbw , FBW_THREAD_STACK_SIZE) static
Variable Documentation
thread_t* apThdPtr = NULL static
Definition at line 68 of file main_chibios.c.
Referenced by main(), and pprz_terminate_autopilot_threads().
thread_t* fbwThdPtr = NULL static
Definition at line 82 of file main_chibios.c.
Referenced by main(), and pprz_terminate_autopilot_threads().