Paparazzi UAS: International Standard Atmosphere utilities
International Standard Atmosphere utilities
Math
Macros
#define PPRZ_ISA_SEA_LEVEL_PRESSURE 101325.0
ISA sea level standard atmospheric pressure in Pascal.
#define PPRZ_ISA_SEA_LEVEL_TEMP 288.15
ISA sea level standard temperature in Kelvin.
#define PPRZ_ISA_TEMP_LAPS_RATE 0.0065
temperature laps rate in K/m
#define PPRZ_ISA_GRAVITY 9.80665
earth-surface gravitational acceleration in m/s^2
#define PPRZ_ISA_GAS_CONSTANT 8.31447
universal gas constant in J/(mol*K)
#define PPRZ_ISA_MOLAR_MASS 0.0289644
molar mass of dry air in kg/mol
#define PPRZ_ISA_AIR_GAS_CONSTANT (PPRZ_ISA_GAS_CONSTANT/PPRZ_ISA_MOLAR_MASS)
universal gas constant / molar mass of dry air in J*kg/K
#define PPRZ_ISA_AIR_DENSITY 1.225
standard air density in kg/m^3
#define PPRZ_ISA_ABS_NULL -273.15
absolute null in celcius
#define CelsiusOfKelvin(_t) (_t - 274.15f)
Convert temperature from Kelvin to Celsius.
#define KelvinOfCelsius(_t) (_t + 274.15f)
Convert temperature from Celsius to Kelvin.
Functions
static float pprz_isa_altitude_of_pressure (float pressure)
Get absolute altitude from pressure (using simplified equation).
static float pprz_isa_height_of_pressure (float pressure, float ref_p)
Get relative altitude from pressure (using simplified equation).
static float pprz_isa_pressure_of_altitude (float altitude)
Get pressure in Pa from absolute altitude (using simplified equation).
static float pprz_isa_pressure_of_height (float height, float ref_p)
Get pressure in Pa from height (using simplified equation).
static float pprz_isa_height_of_pressure_full (float pressure, float ref_p)
Get relative altitude from pressure (using full equation).
static float pprz_isa_ref_pressure_of_height_full (float pressure, float height)
Get reference pressure (QFE or QNH) from current pressure and height.
static float pprz_isa_temperature_of_altitude (float alt)
Get ISA temperature from a MSL altitude.
static float pprz_isa_density_of_pressure (float pressure, float temp)
Get the air density (rho) from a given pressure and temperature.
Variables
static const float PPRZ_ISA_M_OF_P_CONST = (PPRZ_ISA_AIR_GAS_CONSTANT *PPRZ_ISA_SEA_LEVEL_TEMP / PPRZ_ISA_GRAVITY)
Detailed Description
Macro Definition Documentation
#define CelsiusOfKelvin (_t) (_t - 274.15f)
Convert temperature from Kelvin to Celsius.
Definition at line 71 of file pprz_isa.h.
Referenced by tas_from_eas().
#define KelvinOfCelsius (_t) (_t + 274.15f)
Convert temperature from Celsius to Kelvin.
Definition at line 73 of file pprz_isa.h.
Referenced by get_tas_factor().
#define PPRZ_ISA_ABS_NULL -273.15
absolute null in celcius
Definition at line 66 of file pprz_isa.h.
Referenced by pprz_isa_density_of_pressure().
#define PPRZ_ISA_AIR_DENSITY 1.225
standard air density in kg/m^3
Definition at line 64 of file pprz_isa.h.
Referenced by eas_from_dynamic_pressure().
#define PPRZ_ISA_AIR_GAS_CONSTANT (PPRZ_ISA_GAS_CONSTANT/PPRZ_ISA_MOLAR_MASS)
universal gas constant / molar mass of dry air in J*kg/K
Definition at line 62 of file pprz_isa.h.
Referenced by pprz_isa_density_of_pressure().
#define PPRZ_ISA_GAS_CONSTANT 8.31447
universal gas constant in J/(mol*K)
Definition at line 58 of file pprz_isa.h.
Referenced by pprz_isa_height_of_pressure_full(), and pprz_isa_ref_pressure_of_height_full().
#define PPRZ_ISA_GRAVITY 9.80665
earth-surface gravitational acceleration in m/s^2
Definition at line 56 of file pprz_isa.h.
Referenced by pprz_isa_height_of_pressure_full(), and pprz_isa_ref_pressure_of_height_full().
#define PPRZ_ISA_MOLAR_MASS 0.0289644
molar mass of dry air in kg/mol
Definition at line 60 of file pprz_isa.h.
Referenced by pprz_isa_height_of_pressure_full(), and pprz_isa_ref_pressure_of_height_full().
#define PPRZ_ISA_SEA_LEVEL_PRESSURE 101325.0
ISA sea level standard atmospheric pressure in Pascal.
Definition at line 50 of file pprz_isa.h.
Referenced by baro_cb(), get_tas_factor(), ins_float_invariant_update_baro(), nps_fdm_init(), pprz_isa_altitude_of_pressure(), and pprz_isa_pressure_of_altitude().
#define PPRZ_ISA_SEA_LEVEL_TEMP 288.15
ISA sea level standard temperature in Kelvin.
Definition at line 52 of file pprz_isa.h.
Referenced by get_tas_factor(), pprz_isa_height_of_pressure_full(), pprz_isa_ref_pressure_of_height_full(), and pprz_isa_temperature_of_altitude().
#define PPRZ_ISA_TEMP_LAPS_RATE 0.0065
temperature laps rate in K/m
Definition at line 54 of file pprz_isa.h.
Referenced by pprz_isa_height_of_pressure_full(), pprz_isa_ref_pressure_of_height_full(), and pprz_isa_temperature_of_altitude().
Function Documentation
static float pprz_isa_altitude_of_pressure (float pressure) inline static
Get absolute altitude from pressure (using simplified equation).
Referrence pressure is standard pressure at sea level
Parameters
pressure current pressure in Pascal (Pa)
Returns
altitude in m in ISA conditions
Definition at line 82 of file pprz_isa.h.
References PPRZ_ISA_SEA_LEVEL_PRESSURE.
Referenced by baro_ms5611_event().
static float pprz_isa_density_of_pressure (float pressure, float temp) inline static
Get the air density (rho) from a given pressure and temperature.
Parameters
pressure current pressure in Pascal (Pa)
temp temperature in celcius
Returns
air density rho
Definition at line 193 of file pprz_isa.h.
References PPRZ_ISA_ABS_NULL, and PPRZ_ISA_AIR_GAS_CONSTANT.
Referenced by baro_cb().
static float pprz_isa_height_of_pressure (float pressure, float ref_p) inline static
Get relative altitude from pressure (using simplified equation).
Given the current pressure and a reference pressure (at height=0), calculate the height above the reference in meters. If you pass QNH as reference pressure, you get the height above sea level. Using QFE as reference pressure, you get height above the airfield.
Parameters
pressure current pressure in Pascal (Pa)
ref_p reference pressure (QFE) when height=0 or QNH at sea level
Returns
height in m above reference in ISA conditions
Definition at line 102 of file pprz_isa.h.
Referenced by baro_cb(), ins_alt_float_update_baro(), and ins_float_invariant_update_baro().
static float pprz_isa_height_of_pressure_full (float pressure, float ref_p) inline static
Get relative altitude from pressure (using full equation).
Given the current pressure and a reference pressure (at height=0), calculate the height above the reference in meters. If you pass QNH as reference pressure, you get the height above sea level. Using QFE as reference pressure, you get height above the airfield.
Parameters
pressure current pressure in Pascal (Pa)
ref_p reference pressure (QFE or QNH) in Pa
Returns
height above reference in m in ISA conditions
Definition at line 146 of file pprz_isa.h.
References PPRZ_ISA_GAS_CONSTANT, PPRZ_ISA_GRAVITY, PPRZ_ISA_MOLAR_MASS, PPRZ_ISA_SEA_LEVEL_TEMP, and PPRZ_ISA_TEMP_LAPS_RATE.
Referenced by baro_cb(), and pressure_abs_cb().
static float pprz_isa_pressure_of_altitude (float altitude) inline static
Get pressure in Pa from absolute altitude (using simplified equation).
Parameters
altitude current absolute altitude in meters
Returns
static pressure in Pa at given altitude in ISA conditions
Definition at line 117 of file pprz_isa.h.
References PPRZ_ISA_SEA_LEVEL_PRESSURE.
Referenced by baro_sim_periodic(), decode_gpspacket(), and tas_from_eas().
static float pprz_isa_pressure_of_height (float height, float ref_p) inline static
Get pressure in Pa from height (using simplified equation).
Parameters
height current height over reference (relative altitude) in meters
ref_p reference pressure (QFE or QNH) when height = 0
Returns
static pressure in Pa at given height in ISA conditions
Definition at line 129 of file pprz_isa.h.
Referenced by gazebo_read().
static float pprz_isa_ref_pressure_of_height_full (float pressure, float height) inline static
Get reference pressure (QFE or QNH) from current pressure and height.
(using full equation)
Parameters
pressure current pressure in Pascal (Pa)
height height above referece (sea level for QNH, airfield alt for QFE) in m
Returns
reference pressure at height=0 in Pa
Definition at line 166 of file pprz_isa.h.
References PPRZ_ISA_GAS_CONSTANT, PPRZ_ISA_GRAVITY, PPRZ_ISA_MOLAR_MASS, PPRZ_ISA_SEA_LEVEL_TEMP, and PPRZ_ISA_TEMP_LAPS_RATE.
Referenced by pressure_abs_cb().
static float pprz_isa_temperature_of_altitude (float alt) inline static
Get ISA temperature from a MSL altitude.
Parameters
alt AMSL altitude
Returns
temperature in ISA condition
Definition at line 181 of file pprz_isa.h.
References PPRZ_ISA_SEA_LEVEL_TEMP, and PPRZ_ISA_TEMP_LAPS_RATE.
Referenced by tas_from_eas().
Variable Documentation
const float PPRZ_ISA_M_OF_P_CONST = (PPRZ_ISA_AIR_GAS_CONSTANT *PPRZ_ISA_SEA_LEVEL_TEMP / PPRZ_ISA_GRAVITY) static
Definition at line 68 of file pprz_isa.h.