Paparazzi UAS: sw/airborne/modules/hott/hott_eam.h File Reference
hott_eam.h File Reference
Graupner HOTT electric air module description.
#include "subsystems/electrical.h"
#include "subsystems/imu.h"
#include "autopilot.h"
#include "state.h"
Data Structures
struct HOTT_EAM_MSG
Macros
#define HOTT_TELEMETRY_EAM_SENSOR_ID 0x8E
Functions
static void hott_init_eam_msg (struct HOTT_EAM_MSG *hott_eam_msg)
static void hott_update_eam_msg (struct HOTT_EAM_MSG *hott_eam_msg)
Detailed Description
Graupner HOTT electric air module description.
Graupner HOTT general air module description.
Definition in file hott_eam.h.
Data Structure Documentation
struct HOTT_EAM_MSG
Definition at line 38 of file hott_eam.h.
Data Fields
int8_t alarm_invers1
int8_t alarm_invers2
uint16_t altitude
uint16_t batt1_voltage
uint16_t batt2_voltage
uint16_t batt_cap
int8_t cell1_H
int8_t cell1_L
int8_t cell2_H
int8_t cell2_L
int8_t cell3_H
int8_t cell3_L
int8_t cell4_H
int8_t cell4_L
int8_t cell5_H
int8_t cell5_L
int8_t cell6_H
int8_t cell6_L
int8_t cell7_H
int8_t cell7_L
uint16_t climbrate
uint8_t climbrate3s
uint16_t current
int8_t eam_sensor_id
int8_t electric_min
int8_t electric_sec
uint16_t main_voltage
int8_t rpm_H
int8_t rpm_L
int8_t sensor_id
int8_t speed_H
int8_t speed_L
int8_t start_byte
int8_t stop_byte
int8_t temp1
int8_t temp2
int8_t warning_beeps
Macro Definition Documentation
#define HOTT_TELEMETRY_EAM_SENSOR_ID 0x8E
Definition at line 36 of file hott_eam.h.
Referenced by hott_check_serial_data(), hott_init_eam_msg(), and hott_periodic().
Function Documentation
static void hott_init_eam_msg (struct HOTT_EAM_MSG * hott_eam_msg) static
Definition at line 131 of file hott_eam.h.
References HOTT_EAM_MSG::eam_sensor_id, HOTT_TELEMETRY_EAM_SENSOR_ID, HOTT_EAM_MSG::sensor_id, HOTT_EAM_MSG::start_byte, and HOTT_EAM_MSG::stop_byte.
Referenced by hott_msgs_init().
static void hott_update_eam_msg (struct HOTT_EAM_MSG * hott_eam_msg) static
Definition at line 140 of file hott_eam.h.
References HOTT_EAM_MSG::alarm_invers2, HOTT_EAM_MSG::altitude, autopilot_get_motors_on(), HOTT_EAM_MSG::batt1_voltage, HOTT_EAM_MSG::batt2_voltage, HOTT_EAM_MSG::batt_cap, HOTT_EAM_MSG::climbrate, HOTT_EAM_MSG::climbrate3s, Electrical::current, HOTT_EAM_MSG::current, electrical, INT32_POS_FRAC, INT32_SPEED_FRAC, HOTT_EAM_MSG::main_voltage, HOTT_EAM_MSG::speed_H, HOTT_EAM_MSG::speed_L, stateGetHorizontalSpeedNorm_i(), stateGetPositionEnu_i(), stateGetSpeedEnu_i(), Electrical::vsupply, and EnuCoor_i::z.
Referenced by hott_periodic().