Paparazzi UAS: sw/airborne/boards/hbmini/imu_hbmini.c File Reference
imu_hbmini.c File Reference
Driver for the IMU on the Hbmini board.
#include <math.h>
#include "imu_hbmini.h"
#include "mcu_periph/i2c.h"
#include "led.h"
#include "subsystems/abi.h"
#include "mcu_periph/uart.h"
#include "pprzlink/messages.h"
#include "subsystems/datalink/downlink.h"
Macros
#define IMU_GYRO_P_CHAN 3
#define IMU_GYRO_Q_CHAN 4
#define IMU_GYRO_R_CHAN 5
#define IMU_ACCEL_X_CHAN 0
#define IMU_ACCEL_Y_CHAN 1
#define IMU_ACCEL_Z_CHAN 2
#define IMU_MAG_X_CHAN 2
#define IMU_MAG_Y_CHAN 0
#define IMU_MAG_Z_CHAN 1
Functions
void imu_hbmini_init (void)
void imu_hbmini_periodic (void)
void imu_hbmini_downlink_raw (void)
void imu_hbmini_event (void)
Variables
struct ImuHbmini imu_hbmini
Detailed Description
Driver for the IMU on the Hbmini board.
Gyroscope: IDG 500 and ISZ 500, MAX1168
Accelerometer: Analog Devices ADXL320
Magnetometer: Honeywell HMC5883L
Definition in file imu_hbmini.c.
Macro Definition Documentation
#define IMU_ACCEL_X_CHAN 0
Definition at line 51 of file imu_hbmini.c.
Referenced by imu_b2_event(), and imu_hbmini_event().
#define IMU_ACCEL_Y_CHAN 1
Definition at line 52 of file imu_hbmini.c.
Referenced by imu_b2_event(), and imu_hbmini_event().
#define IMU_ACCEL_Z_CHAN 2
Definition at line 53 of file imu_hbmini.c.
Referenced by imu_b2_event(), and imu_hbmini_event().
#define IMU_GYRO_P_CHAN 3
Definition at line 46 of file imu_hbmini.c.
Referenced by imu_b2_event(), and imu_hbmini_event().
#define IMU_GYRO_Q_CHAN 4
Definition at line 47 of file imu_hbmini.c.
Referenced by imu_b2_event(), and imu_hbmini_event().
#define IMU_GYRO_R_CHAN 5
Definition at line 48 of file imu_hbmini.c.
Referenced by imu_b2_event(), and imu_hbmini_event().
#define IMU_MAG_X_CHAN 2
Definition at line 56 of file imu_hbmini.c.
Referenced by imu_hbmini_event().
#define IMU_MAG_Y_CHAN 0
Definition at line 57 of file imu_hbmini.c.
Referenced by imu_hbmini_event().
#define IMU_MAG_Z_CHAN 1
Definition at line 58 of file imu_hbmini.c.
Referenced by imu_hbmini_event().
Function Documentation
void imu_hbmini_downlink_raw (void)
Definition at line 84 of file imu_hbmini.c.
References Imu::accel_unscaled, DefaultChannel, DefaultDevice, Imu::gyro_unscaled, imu, Imu::mag_unscaled, Int32Rates::p, Int32Rates::q, Int32Rates::r, Int32Vect3::x, Int32Vect3::y, and Int32Vect3::z.
void imu_hbmini_event (void)
Definition at line 93 of file imu_hbmini.c.
References Imu::accel, Imu::accel_unscaled, Hmc58xx::data, Hmc58xx::data_available, get_sys_time_usec(), Imu::gyro, Imu::gyro_unscaled, ImuHbmini::hmc, hmc58xx_event(), imu, IMU_ACCEL_X_CHAN, IMU_ACCEL_Y_CHAN, IMU_ACCEL_Z_CHAN, IMU_BOARD_ID, IMU_GYRO_P_CHAN, IMU_GYRO_Q_CHAN, IMU_GYRO_R_CHAN, imu_hbmini, IMU_MAG_X_CHAN, IMU_MAG_Y_CHAN, IMU_MAG_Z_CHAN, imu_scale_accel(), imu_scale_gyro(), imu_scale_mag(), Imu::mag, Imu::mag_unscaled, MAX1168_DATA_AVAILABLE, max1168_event(), MAX1168_IDLE, max1168_status, max1168_values, Int32Rates::p, Int32Rates::q, Int32Rates::r, Int32Vect3::x, Int32Vect3::y, and Int32Vect3::z.
void imu_hbmini_init (void)
Definition at line 63 of file imu_hbmini.c.
References ImuHbmini::hmc, HMC58XX_ADDR, hmc58xx_init(), imu_hbmini, and max1168_init().
void imu_hbmini_periodic (void)
Definition at line 72 of file imu_hbmini.c.
References ImuHbmini::hmc, hmc58xx_periodic(), imu_hbmini, and Max1168Periodic.
Variable Documentation
struct ImuHbmini imu_hbmini
Definition at line 61 of file imu_hbmini.c.
Referenced by imu_hbmini_event(), imu_hbmini_init(), and imu_hbmini_periodic().