Paparazzi UAS: sw/airborne/subsystems/imu/imu_analog.c File Reference
imu_analog.c File Reference
#include "imu_analog.h"
#include "mcu_periph/adc.h"
#include "subsystems/abi.h"
Functions
void imu_analog_init (void)
void imu_analog_periodic (void)
void imu_scale_accel (struct Imu *_imu)
Variables
int imu_overrun
static struct adc_buf analog_imu_adc_buf [NB_ANALOG_IMU_ADC]
Function Documentation
void imu_analog_init (void)
Definition at line 30 of file imu_analog.c.
References adc_buf_channel(), analog_imu_adc_buf, and imu_overrun.
void imu_analog_periodic (void)
Definition at line 56 of file imu_analog.c.
References Imu::accel, Imu::accel_unscaled, analog_imu_adc_buf, get_sys_time_usec(), Imu::gyro, Imu::gyro_unscaled, adc_buf::head, imu, IMU_ANALOG_ID, imu_overrun, imu_scale_accel(), imu_scale_gyro(), Int32Rates::p, Int32Rates::q, Int32Rates::r, adc_buf::sum, Int32Vect3::x, Int32Vect3::y, and Int32Vect3::z.
void imu_scale_accel (struct Imu * _imu)
Definition at line 118 of file imu_analog.c.
Referenced by imu_analog_periodic().
Variable Documentation
struct adc_buf analog_imu_adc_buf[NB_ANALOG_IMU_ADC] static
Definition at line 28 of file imu_analog.c.
Referenced by imu_analog_init(), and imu_analog_periodic().
int imu_overrun
Definition at line 26 of file imu_analog.c.
Referenced by imu_analog_init(), and imu_analog_periodic().