Paparazzi UAS: sw/airborne/subsystems/imu/imu_b2.c File Reference
imu_b2.c File Reference
Driver for the Booz2 IMUs.
#include "subsystems/imu.h"
#include "led.h"
#include "subsystems/abi.h"
#include "mcu_periph/sys_time.h"
Macros
#define ImuMagEvent() {}
Event functions for imu_b2.
Functions
void imu_b2_init (void)
void imu_b2_periodic (void)
void imu_b2_event (void)
Variables
struct ImuBooz2 imu_b2
Detailed Description
Driver for the Booz2 IMUs.
Analog gyros and accelerometers are read via MAX1168 16-bit SPI ADC. Depending on version, different I2C or SPI magnetometers are used.
Definition in file imu_b2.c.
Macro Definition Documentation
#define ImuMagEvent () {}
Event functions for imu_b2.
Definition at line 148 of file imu_b2.c.
Referenced by imu_b2_event().
Function Documentation
void imu_b2_event (void)
Definition at line 152 of file imu_b2.c.
References Imu::accel, Imu::accel_unscaled, get_sys_time_usec(), Imu::gyro, Imu::gyro_unscaled, imu, IMU_ACCEL_X_CHAN, IMU_ACCEL_Y_CHAN, IMU_ACCEL_Z_CHAN, IMU_ASPIRIN2_ID, IMU_GYRO_P_CHAN, IMU_GYRO_Q_CHAN, IMU_GYRO_R_CHAN, imu_scale_accel(), imu_scale_gyro(), ImuMagEvent, MAX1168_DATA_AVAILABLE, max1168_event(), MAX1168_IDLE, max1168_status, max1168_values, Int32Rates::p, Int32Rates::q, Int32Rates::r, Int32Vect3::x, Int32Vect3::y, and Int32Vect3::z.
void imu_b2_init (void)
Definition at line 38 of file imu_b2.c.
References ami601_init(), hmc5843_init(), HMC58XX_ADDR, hmc58xx_init(), HMC_TYPE_5843, imu_b2, max1168_init(), ms2100, and ms2100_init().
void imu_b2_periodic (void)
Definition at line 57 of file imu_b2.c.
References ami601_read(), hmc58xx_periodic(), imu_b2, Max1168Periodic, ms2100, and ms2100_periodic().
Variable Documentation
struct ImuBooz2 imu_b2
Definition at line 34 of file imu_b2.c.
Referenced by imu_b2_init(), and imu_b2_periodic().