Paparazzi UAS: sw/airborne/modules/imu/imu_vectornav.h File Reference
imu_vectornav.h File Reference
Vectornav VN-200 IMU subsystems, to be used with other AHRS/INS algorithms.
#include "subsystems/imu.h"
#include "peripherals/vn200_serial.h"
Data Structures
struct ImuVectornav
Macros
#define IMU_GYRO_P_SENS_NUM 1
#define IMU_GYRO_P_SENS_DEN 1
#define IMU_GYRO_Q_SENS_NUM 1
#define IMU_GYRO_Q_SENS_DEN 1
#define IMU_GYRO_R_SENS_NUM 1
#define IMU_GYRO_R_SENS_DEN 1
Functions
void imu_vectornav_init (void)
Init IMU struct and set up ABI messages.
void imu_vectornav_event (void)
Event function to read and parse data from the serial port.
void imu_vectornav_periodic (void)
Periodic function checks for the frequency of packets, triggers warning in case the IMU stops sending data and performs initial configuration if needed.
void imu_vectornav_propagate (void)
Send ABI messages.
Variables
struct ImuVectornav imu_vn
Detailed Description
Vectornav VN-200 IMU subsystems, to be used with other AHRS/INS algorithms.
Definition in file imu_vectornav.h.
Data Structure Documentation
struct ImuVectornav
Definition at line 39 of file imu_vectornav.h.
Data Fields
struct VNData vn_data Data struct.
float vn_freq data frequency
struct VNPacket vn_packet Packet struct.
enum VNStatus vn_status VN status.
Macro Definition Documentation
#define IMU_GYRO_P_SENS_DEN 1
Definition at line 61 of file imu_vectornav.h.
#define IMU_GYRO_P_SENS_NUM 1
Definition at line 57 of file imu_vectornav.h.
#define IMU_GYRO_Q_SENS_DEN 1
Definition at line 69 of file imu_vectornav.h.
#define IMU_GYRO_Q_SENS_NUM 1
Definition at line 65 of file imu_vectornav.h.
#define IMU_GYRO_R_SENS_DEN 1
Definition at line 77 of file imu_vectornav.h.
#define IMU_GYRO_R_SENS_NUM 1
Definition at line 73 of file imu_vectornav.h.
Function Documentation
void imu_vectornav_event (void)
Event function to read and parse data from the serial port.
Definition at line 109 of file imu_vectornav.c.
References imu_vectornav_propagate(), imu_vn, VNPacket::msg_available, vn200_event(), vn200_read_message(), ImuVectornav::vn_data, and ImuVectornav::vn_packet.
void imu_vectornav_init (void)
Init IMU struct and set up ABI messages.
Definition at line 80 of file imu_vectornav.c.
References VNPacket::chksm_error, DefaultPeriodic, VNPacket::framing_error, VNPacket::hdr_error, imu_vn, VNPacket::msg_available, VNPacket::msg_idx, VNPacket::noise_error, VNPacket::overrun_error, register_periodic_telemetry(), send_vn_info(), VNPacket::status, ImuVectornav::vn_data, ImuVectornav::vn_freq, ImuVectornav::vn_packet, ImuVectornav::vn_status, VNMsgSync, and VNNotTracking.
void imu_vectornav_periodic (void)
Periodic function checks for the frequency of packets, triggers warning in case the IMU stops sending data and performs initial configuration if needed.
Definition at line 128 of file imu_vectornav.c.
References VNPacket::counter, imu_vn, ImuVectornav::vn_freq, ImuVectornav::vn_packet, ImuVectornav::vn_status, VNNotTracking, and VNOK.
void imu_vectornav_propagate (void)
Send ABI messages.
Definition at line 149 of file imu_vectornav.c.
References Imu::accel, VNData::accel, ACCELS_BFP_OF_REAL, Imu::gyro, VNData::gyro, imu, IMU_VECTORNAV_ID, imu_vn, VNData::nanostamp, RATES_BFP_OF_REAL, and ImuVectornav::vn_data.
Referenced by imu_vectornav_event().
Variable Documentation
struct ImuVectornav imu_vn
Definition at line 40 of file imu_vectornav.c.
Referenced by imu_vectornav_event(), imu_vectornav_init(), imu_vectornav_periodic(), imu_vectornav_propagate(), and send_vn_info().