Paparazzi UAS: sw/airborne/subsystems/imu/imu_mpu60x0_i2c.h File Reference
imu_mpu60x0_i2c.h File Reference
Driver for IMU with only MPU60x0 via I2C.
#include "std.h"
#include "generated/airframe.h"
#include "subsystems/imu.h"
#include "peripherals/mpu60x0_i2c.h"
Data Structures
struct ImuMpu60x0
Macros
#define IMU_MPU60X0_GYRO_RANGE MPU60X0_GYRO_RANGE_2000
#define IMU_MPU60X0_ACCEL_RANGE MPU60X0_ACCEL_RANGE_16G
#define IMU_GYRO_P_SENS MPU60X0_GYRO_SENS[IMU_MPU60X0_GYRO_RANGE]
#define IMU_GYRO_P_SENS_NUM MPU60X0_GYRO_SENS_FRAC[IMU_MPU60X0_GYRO_RANGE][0]
#define IMU_GYRO_P_SENS_DEN MPU60X0_GYRO_SENS_FRAC[IMU_MPU60X0_GYRO_RANGE][1]
#define IMU_GYRO_Q_SENS MPU60X0_GYRO_SENS[IMU_MPU60X0_GYRO_RANGE]
#define IMU_GYRO_Q_SENS_NUM MPU60X0_GYRO_SENS_FRAC[IMU_MPU60X0_GYRO_RANGE][0]
#define IMU_GYRO_Q_SENS_DEN MPU60X0_GYRO_SENS_FRAC[IMU_MPU60X0_GYRO_RANGE][1]
#define IMU_GYRO_R_SENS MPU60X0_GYRO_SENS[IMU_MPU60X0_GYRO_RANGE]
#define IMU_GYRO_R_SENS_NUM MPU60X0_GYRO_SENS_FRAC[IMU_MPU60X0_GYRO_RANGE][0]
#define IMU_GYRO_R_SENS_DEN MPU60X0_GYRO_SENS_FRAC[IMU_MPU60X0_GYRO_RANGE][1]
#define IMU_ACCEL_X_SENS MPU60X0_ACCEL_SENS[IMU_MPU60X0_ACCEL_RANGE]
#define IMU_ACCEL_X_SENS_NUM MPU60X0_ACCEL_SENS_FRAC[IMU_MPU60X0_ACCEL_RANGE][0]
#define IMU_ACCEL_X_SENS_DEN MPU60X0_ACCEL_SENS_FRAC[IMU_MPU60X0_ACCEL_RANGE][1]
#define IMU_ACCEL_Y_SENS MPU60X0_ACCEL_SENS[IMU_MPU60X0_ACCEL_RANGE]
#define IMU_ACCEL_Y_SENS_NUM MPU60X0_ACCEL_SENS_FRAC[IMU_MPU60X0_ACCEL_RANGE][0]
#define IMU_ACCEL_Y_SENS_DEN MPU60X0_ACCEL_SENS_FRAC[IMU_MPU60X0_ACCEL_RANGE][1]
#define IMU_ACCEL_Z_SENS MPU60X0_ACCEL_SENS[IMU_MPU60X0_ACCEL_RANGE]
#define IMU_ACCEL_Z_SENS_NUM MPU60X0_ACCEL_SENS_FRAC[IMU_MPU60X0_ACCEL_RANGE][0]
#define IMU_ACCEL_Z_SENS_DEN MPU60X0_ACCEL_SENS_FRAC[IMU_MPU60X0_ACCEL_RANGE][1]
Functions
void imu_mpu_i2c_init (void)
void imu_mpu_i2c_periodic (void)
void imu_mpu_i2c_event (void)
Variables
struct ImuMpu60x0 imu_mpu_i2c
Detailed Description
Driver for IMU with only MPU60x0 via I2C.
Definition in file imu_mpu60x0_i2c.h.
Data Structure Documentation
struct ImuMpu60x0
Definition at line 70 of file imu_mpu60x0_i2c.h.
Data Fields
struct Mpu60x0_I2c mpu
Macro Definition Documentation
#define IMU_ACCEL_X_SENS MPU60X0_ACCEL_SENS[IMU_MPU60X0_ACCEL_RANGE]
Definition at line 59 of file imu_mpu60x0_i2c.h.
#define IMU_ACCEL_X_SENS_DEN MPU60X0_ACCEL_SENS_FRAC[IMU_MPU60X0_ACCEL_RANGE][1]
Definition at line 61 of file imu_mpu60x0_i2c.h.
#define IMU_ACCEL_X_SENS_NUM MPU60X0_ACCEL_SENS_FRAC[IMU_MPU60X0_ACCEL_RANGE][0]
Definition at line 60 of file imu_mpu60x0_i2c.h.
#define IMU_ACCEL_Y_SENS MPU60X0_ACCEL_SENS[IMU_MPU60X0_ACCEL_RANGE]
Definition at line 62 of file imu_mpu60x0_i2c.h.
#define IMU_ACCEL_Y_SENS_DEN MPU60X0_ACCEL_SENS_FRAC[IMU_MPU60X0_ACCEL_RANGE][1]
Definition at line 64 of file imu_mpu60x0_i2c.h.
#define IMU_ACCEL_Y_SENS_NUM MPU60X0_ACCEL_SENS_FRAC[IMU_MPU60X0_ACCEL_RANGE][0]
Definition at line 63 of file imu_mpu60x0_i2c.h.
#define IMU_ACCEL_Z_SENS MPU60X0_ACCEL_SENS[IMU_MPU60X0_ACCEL_RANGE]
Definition at line 65 of file imu_mpu60x0_i2c.h.
#define IMU_ACCEL_Z_SENS_DEN MPU60X0_ACCEL_SENS_FRAC[IMU_MPU60X0_ACCEL_RANGE][1]
Definition at line 67 of file imu_mpu60x0_i2c.h.
#define IMU_ACCEL_Z_SENS_NUM MPU60X0_ACCEL_SENS_FRAC[IMU_MPU60X0_ACCEL_RANGE][0]
Definition at line 66 of file imu_mpu60x0_i2c.h.
#define IMU_GYRO_P_SENS MPU60X0_GYRO_SENS[IMU_MPU60X0_GYRO_RANGE]
Definition at line 46 of file imu_mpu60x0_i2c.h.
#define IMU_GYRO_P_SENS_DEN MPU60X0_GYRO_SENS_FRAC[IMU_MPU60X0_GYRO_RANGE][1]
Definition at line 48 of file imu_mpu60x0_i2c.h.
#define IMU_GYRO_P_SENS_NUM MPU60X0_GYRO_SENS_FRAC[IMU_MPU60X0_GYRO_RANGE][0]
Definition at line 47 of file imu_mpu60x0_i2c.h.
#define IMU_GYRO_Q_SENS MPU60X0_GYRO_SENS[IMU_MPU60X0_GYRO_RANGE]
Definition at line 49 of file imu_mpu60x0_i2c.h.
#define IMU_GYRO_Q_SENS_DEN MPU60X0_GYRO_SENS_FRAC[IMU_MPU60X0_GYRO_RANGE][1]
Definition at line 51 of file imu_mpu60x0_i2c.h.
#define IMU_GYRO_Q_SENS_NUM MPU60X0_GYRO_SENS_FRAC[IMU_MPU60X0_GYRO_RANGE][0]
Definition at line 50 of file imu_mpu60x0_i2c.h.
#define IMU_GYRO_R_SENS MPU60X0_GYRO_SENS[IMU_MPU60X0_GYRO_RANGE]
Definition at line 52 of file imu_mpu60x0_i2c.h.
#define IMU_GYRO_R_SENS_DEN MPU60X0_GYRO_SENS_FRAC[IMU_MPU60X0_GYRO_RANGE][1]
Definition at line 54 of file imu_mpu60x0_i2c.h.
#define IMU_GYRO_R_SENS_NUM MPU60X0_GYRO_SENS_FRAC[IMU_MPU60X0_GYRO_RANGE][0]
Definition at line 53 of file imu_mpu60x0_i2c.h.
#define IMU_MPU60X0_ACCEL_RANGE MPU60X0_ACCEL_RANGE_16G
Definition at line 41 of file imu_mpu60x0_i2c.h.
Referenced by imu_mpu_i2c_init().
#define IMU_MPU60X0_GYRO_RANGE MPU60X0_GYRO_RANGE_2000
Definition at line 37 of file imu_mpu60x0_i2c.h.
Referenced by imu_mpu_i2c_init().
Function Documentation
void imu_mpu_i2c_event (void)
Definition at line 80 of file imu_mpu60x0_i2c.c.
References Imu::accel, Imu::accel_unscaled, Mpu60x0_I2c::data_accel, Mpu60x0_I2c::data_available, Mpu60x0_I2c::data_rates, get_sys_time_usec(), Imu::gyro, Imu::gyro_unscaled, imu, IMU_MPU60X0_ID, imu_mpu_i2c, imu_scale_accel(), imu_scale_gyro(), ImuMpu60x0::mpu, mpu60x0_i2c_event(), RATES_COPY, and VECT3_COPY.
void imu_mpu_i2c_init (void)
Definition at line 65 of file imu_mpu60x0_i2c.c.
References Mpu60x0Config::accel_range, Mpu60x0_I2c::config, Mpu60x0Config::dlpf_cfg, Mpu60x0Config::gyro_range, IMU_MPU60X0_ACCEL_RANGE, IMU_MPU60X0_GYRO_RANGE, IMU_MPU60X0_I2C_ADDR, imu_mpu_i2c, ImuMpu60x0::mpu, mpu60x0_i2c_init(), and Mpu60x0Config::smplrt_div.
void imu_mpu_i2c_periodic (void)
Definition at line 75 of file imu_mpu60x0_i2c.c.
References imu_mpu_i2c, ImuMpu60x0::mpu, and mpu60x0_i2c_periodic().
Variable Documentation
struct ImuMpu60x0 imu_mpu_i2c
Definition at line 63 of file imu_mpu60x0_i2c.c.
Referenced by imu_mpu_i2c_event(), imu_mpu_i2c_init(), and imu_mpu_i2c_periodic().