Paparazzi UAS: sw/airborne/subsystems/imu/imu_gl1.c File Reference
imu_gl1.c File Reference
Driver for I2C IMU using L3G4200, ADXL345, HMC5883 and BMP085.
#include "subsystems/imu.h"
#include "subsystems/abi.h"
#include "mcu_periph/i2c.h"
Macros
#define GL1_ACCEL_RATE ADXL345_RATE_50HZ
adxl345 accelerometer output rate, lowpass is set to half of rate
#define GL1_GYRO_LOWPASS L3G4200_DLPF_1
gyro internal lowpass frequency
#define GL1_GYRO_SMPLRT L3G4200_DR_100Hz
gyro sample rate divider
#define L3G4200_SCALE L3G4200_SCALE_2000
Functions
void imu_gl1_init (void)
void imu_gl1_periodic (void)
void imu_gl1_event (void)
Variables
struct ImuGL1I2c imu_gl1
Detailed Description
Driver for I2C IMU using L3G4200, ADXL345, HMC5883 and BMP085.
Definition in file imu_gl1.c.
Macro Definition Documentation
#define GL1_ACCEL_RATE ADXL345_RATE_50HZ
adxl345 accelerometer output rate, lowpass is set to half of rate
Definition at line 38 of file imu_gl1.c.
Referenced by imu_gl1_init().
#define GL1_GYRO_LOWPASS L3G4200_DLPF_1
gyro internal lowpass frequency
Definition at line 50 of file imu_gl1.c.
Referenced by imu_gl1_init().
#define GL1_GYRO_SMPLRT L3G4200_DR_100Hz
gyro sample rate divider
Definition at line 62 of file imu_gl1.c.
Referenced by imu_gl1_init().
#define L3G4200_SCALE L3G4200_SCALE_2000
Definition at line 74 of file imu_gl1.c.
Referenced by imu_gl1_init().
Function Documentation
void imu_gl1_event (void)
Definition at line 118 of file imu_gl1.c.
References ImuGL1I2c::acc_adxl, Imu::accel, Imu::accel_unscaled, adxl345_i2c_event(), Adxl345_I2c::data, Hmc58xx::data, L3g4200::data, Adxl345_I2c::data_available, Hmc58xx::data_available, L3g4200::data_available, get_sys_time_usec(), Imu::gyro, ImuGL1I2c::gyro_l3g, Imu::gyro_unscaled, hmc58xx_event(), imu, imu_gl1, IMU_GL1_ID, imu_scale_accel(), imu_scale_gyro(), imu_scale_mag(), l3g4200_event(), Imu::mag, ImuGL1I2c::mag_hmc, Imu::mag_unscaled, Int32Rates::p, Int32Rates::q, Int32Rates::r, RATES_COPY, VECT3_COPY, Int32Vect3::x, Int32Vect3::y, and Int32Vect3::z.
void imu_gl1_init (void)
Todo:
drdy int handling for adxl345
Definition at line 80 of file imu_gl1.c.
References ImuGL1I2c::acc_adxl, ADXL345_ADDR, adxl345_i2c_init(), Adxl345_I2c::config, L3g4200::config, L3g4200Config::ctrl_reg1, L3g4200Config::ctrl_reg4, L3g4200Config::ctrl_reg5, GL1_ACCEL_RATE, GL1_GYRO_LOWPASS, GL1_GYRO_SMPLRT, ImuGL1I2c::gyro_l3g, HMC58XX_ADDR, hmc58xx_init(), HMC_TYPE_5883, L3G4200_ADDR_ALT, l3g4200_init(), L3G4200_SCALE, ImuGL1I2c::mag_hmc, Adxl345Config::rate, and Hmc58xx::type.
void imu_gl1_periodic (void)
Definition at line 107 of file imu_gl1.c.
References ImuGL1I2c::acc_adxl, adxl345_i2c_periodic(), ImuGL1I2c::gyro_l3g, hmc58xx_periodic(), imu_gl1, l3g4200_periodic(), and ImuGL1I2c::mag_hmc.
Variable Documentation
struct ImuGL1I2c imu_gl1
Definition at line 78 of file imu_gl1.c.
Referenced by imu_gl1_event(), and imu_gl1_periodic().