Paparazzi UAS: sw/airborne/subsystems/imu/imu_bebop.h File Reference
imu_bebop.h File Reference
Interface for the Bebop magnetometer, accelerometer and gyroscope.
#include "generated/airframe.h"
#include "subsystems/imu.h"
#include "peripherals/ak8963.h"
#include "peripherals/mpu60x0_i2c.h"
Data Structures
struct ImuBebop
Everything that is in the bebop IMU.
Macros
#define BEBOP_GYRO_RANGE MPU60X0_GYRO_RANGE_1000
#define BEBOP_ACCEL_RANGE MPU60X0_ACCEL_RANGE_8G
#define IMU_GYRO_P_SENS MPU60X0_GYRO_SENS[BEBOP_GYRO_RANGE]
#define IMU_GYRO_P_SENS_NUM MPU60X0_GYRO_SENS_FRAC[BEBOP_GYRO_RANGE][0]
#define IMU_GYRO_P_SENS_DEN MPU60X0_GYRO_SENS_FRAC[BEBOP_GYRO_RANGE][1]
#define IMU_GYRO_Q_SENS MPU60X0_GYRO_SENS[BEBOP_GYRO_RANGE]
#define IMU_GYRO_Q_SENS_NUM MPU60X0_GYRO_SENS_FRAC[BEBOP_GYRO_RANGE][0]
#define IMU_GYRO_Q_SENS_DEN MPU60X0_GYRO_SENS_FRAC[BEBOP_GYRO_RANGE][1]
#define IMU_GYRO_R_SENS MPU60X0_GYRO_SENS[BEBOP_GYRO_RANGE]
#define IMU_GYRO_R_SENS_NUM MPU60X0_GYRO_SENS_FRAC[BEBOP_GYRO_RANGE][0]
#define IMU_GYRO_R_SENS_DEN MPU60X0_GYRO_SENS_FRAC[BEBOP_GYRO_RANGE][1]
#define IMU_ACCEL_X_SENS MPU60X0_ACCEL_SENS[BEBOP_ACCEL_RANGE]
#define IMU_ACCEL_X_SENS_NUM MPU60X0_ACCEL_SENS_FRAC[BEBOP_ACCEL_RANGE][0]
#define IMU_ACCEL_X_SENS_DEN MPU60X0_ACCEL_SENS_FRAC[BEBOP_ACCEL_RANGE][1]
#define IMU_ACCEL_Y_SENS MPU60X0_ACCEL_SENS[BEBOP_ACCEL_RANGE]
#define IMU_ACCEL_Y_SENS_NUM MPU60X0_ACCEL_SENS_FRAC[BEBOP_ACCEL_RANGE][0]
#define IMU_ACCEL_Y_SENS_DEN MPU60X0_ACCEL_SENS_FRAC[BEBOP_ACCEL_RANGE][1]
#define IMU_ACCEL_Z_SENS MPU60X0_ACCEL_SENS[BEBOP_ACCEL_RANGE]
#define IMU_ACCEL_Z_SENS_NUM MPU60X0_ACCEL_SENS_FRAC[BEBOP_ACCEL_RANGE][0]
#define IMU_ACCEL_Z_SENS_DEN MPU60X0_ACCEL_SENS_FRAC[BEBOP_ACCEL_RANGE][1]
Functions
void imu_bebop_init (void)
Navstik IMU initializtion of the MPU-60x0 and HMC58xx.
void imu_bebop_periodic (void)
Handle all the periodic tasks of the Navstik IMU components.
void imu_bebop_event (void)
Handle all the events of the Navstik IMU components.
Variables
struct ImuBebop imu_bebop
Basic Navstik IMU data.
Detailed Description
Interface for the Bebop magnetometer, accelerometer and gyroscope.
Definition in file imu_bebop.h.
Data Structure Documentation
struct ImuBebop
Everything that is in the bebop IMU.
Definition at line 73 of file imu_bebop.h.
Data Fields
struct Ak8963 ak The AK8963 mag.
struct Mpu60x0_I2c mpu The MPU gyro/accel device.
Macro Definition Documentation
#define BEBOP_ACCEL_RANGE MPU60X0_ACCEL_RANGE_8G
Definition at line 42 of file imu_bebop.h.
Referenced by imu_bebop_init().
#define BEBOP_GYRO_RANGE MPU60X0_GYRO_RANGE_1000
Definition at line 38 of file imu_bebop.h.
Referenced by imu_bebop_init().
#define IMU_ACCEL_X_SENS MPU60X0_ACCEL_SENS[BEBOP_ACCEL_RANGE]
Definition at line 60 of file imu_bebop.h.
#define IMU_ACCEL_X_SENS_DEN MPU60X0_ACCEL_SENS_FRAC[BEBOP_ACCEL_RANGE][1]
Definition at line 62 of file imu_bebop.h.
#define IMU_ACCEL_X_SENS_NUM MPU60X0_ACCEL_SENS_FRAC[BEBOP_ACCEL_RANGE][0]
Definition at line 61 of file imu_bebop.h.
#define IMU_ACCEL_Y_SENS MPU60X0_ACCEL_SENS[BEBOP_ACCEL_RANGE]
Definition at line 63 of file imu_bebop.h.
#define IMU_ACCEL_Y_SENS_DEN MPU60X0_ACCEL_SENS_FRAC[BEBOP_ACCEL_RANGE][1]
Definition at line 65 of file imu_bebop.h.
#define IMU_ACCEL_Y_SENS_NUM MPU60X0_ACCEL_SENS_FRAC[BEBOP_ACCEL_RANGE][0]
Definition at line 64 of file imu_bebop.h.
#define IMU_ACCEL_Z_SENS MPU60X0_ACCEL_SENS[BEBOP_ACCEL_RANGE]
Definition at line 66 of file imu_bebop.h.
#define IMU_ACCEL_Z_SENS_DEN MPU60X0_ACCEL_SENS_FRAC[BEBOP_ACCEL_RANGE][1]
Definition at line 68 of file imu_bebop.h.
#define IMU_ACCEL_Z_SENS_NUM MPU60X0_ACCEL_SENS_FRAC[BEBOP_ACCEL_RANGE][0]
Definition at line 67 of file imu_bebop.h.
#define IMU_GYRO_P_SENS MPU60X0_GYRO_SENS[BEBOP_GYRO_RANGE]
Definition at line 47 of file imu_bebop.h.
#define IMU_GYRO_P_SENS_DEN MPU60X0_GYRO_SENS_FRAC[BEBOP_GYRO_RANGE][1]
Definition at line 49 of file imu_bebop.h.
#define IMU_GYRO_P_SENS_NUM MPU60X0_GYRO_SENS_FRAC[BEBOP_GYRO_RANGE][0]
Definition at line 48 of file imu_bebop.h.
#define IMU_GYRO_Q_SENS MPU60X0_GYRO_SENS[BEBOP_GYRO_RANGE]
Definition at line 50 of file imu_bebop.h.
#define IMU_GYRO_Q_SENS_DEN MPU60X0_GYRO_SENS_FRAC[BEBOP_GYRO_RANGE][1]
Definition at line 52 of file imu_bebop.h.
#define IMU_GYRO_Q_SENS_NUM MPU60X0_GYRO_SENS_FRAC[BEBOP_GYRO_RANGE][0]
Definition at line 51 of file imu_bebop.h.
#define IMU_GYRO_R_SENS MPU60X0_GYRO_SENS[BEBOP_GYRO_RANGE]
Definition at line 53 of file imu_bebop.h.
#define IMU_GYRO_R_SENS_DEN MPU60X0_GYRO_SENS_FRAC[BEBOP_GYRO_RANGE][1]
Definition at line 55 of file imu_bebop.h.
#define IMU_GYRO_R_SENS_NUM MPU60X0_GYRO_SENS_FRAC[BEBOP_GYRO_RANGE][0]
Definition at line 54 of file imu_bebop.h.
Function Documentation
void imu_bebop_event (void)
Handle all the events of the Navstik IMU components.
When there is data available convert it to the correct axis and save it in the imu structure.
Definition at line 112 of file imu_bebop.c.
References Imu::accel, Imu::accel_unscaled, ImuBebop::ak, ak8963_event(), Ak8963::data, Mpu60x0_I2c::data_accel, Mpu60x0_I2c::data_available, Ak8963::data_available, Mpu60x0_I2c::data_rates, get_sys_time_usec(), Imu::gyro, Imu::gyro_unscaled, imu, imu_bebop, IMU_BOARD_ID, imu_scale_accel(), imu_scale_gyro(), imu_scale_mag(), imu_to_mag_bebop, int32_rmat_vmult(), Imu::mag, Imu::mag_unscaled, ImuBebop::mpu, mpu60x0_i2c_event(), orientationGetRMat_i(), RATES_ASSIGN, and VECT3_ASSIGN.
void imu_bebop_init (void)
Navstik IMU initializtion of the MPU-60x0 and HMC58xx.
Definition at line 74 of file imu_bebop.c.
References Mpu60x0Config::accel_range, ImuBebop::ak, AK8963_ADDR, ak8963_init(), BEBOP_ACCEL_RANGE, BEBOP_GYRO_RANGE, BEBOP_MAG_I2C_DEV, BEBOP_MPU_I2C_DEV, Mpu60x0_I2c::config, Mpu60x0Config::dlpf_cfg, Mpu60x0Config::gyro_range, ImuBebop::mpu, MPU60X0_ADDR, mpu60x0_i2c_init(), orientationSetEulers_f(), and Mpu60x0Config::smplrt_div.
void imu_bebop_periodic (void)
Handle all the periodic tasks of the Navstik IMU components.
Read the MPU60x0 every periodic call and the HMC58XX every 10th call.
Definition at line 99 of file imu_bebop.c.
References ImuBebop::ak, ak8963_periodic(), imu_bebop, ImuBebop::mpu, and mpu60x0_i2c_periodic().
Variable Documentation
struct ImuBebop imu_bebop
Basic Navstik IMU data.
Definition at line 69 of file imu_bebop.c.
Referenced by imu_bebop_event(), imu_bebop_periodic(), and imu_temp_ctrl_periodic().