Paparazzi UAS: sw/airborne/subsystems/imu/imu_navstik.h File Reference
imu_navstik.h File Reference
Interface for the Navstik magnetometer, accelerometer and gyroscope.
#include "generated/airframe.h"
#include "subsystems/imu.h"
#include "peripherals/hmc58xx.h"
#include "peripherals/mpu60x0_i2c.h"
Data Structures
struct ImuNavstik
Macros
#define NAVSTIK_GYRO_RANGE MPU60X0_GYRO_RANGE_1000
#define NAVSTIK_ACCEL_RANGE MPU60X0_ACCEL_RANGE_8G
#define IMU_GYRO_P_SENS MPU60X0_GYRO_SENS[NAVSTIK_GYRO_RANGE]
#define IMU_GYRO_P_SENS_NUM MPU60X0_GYRO_SENS_FRAC[NAVSTIK_GYRO_RANGE][0]
#define IMU_GYRO_P_SENS_DEN MPU60X0_GYRO_SENS_FRAC[NAVSTIK_GYRO_RANGE][1]
#define IMU_GYRO_Q_SENS MPU60X0_GYRO_SENS[NAVSTIK_GYRO_RANGE]
#define IMU_GYRO_Q_SENS_NUM MPU60X0_GYRO_SENS_FRAC[NAVSTIK_GYRO_RANGE][0]
#define IMU_GYRO_Q_SENS_DEN MPU60X0_GYRO_SENS_FRAC[NAVSTIK_GYRO_RANGE][1]
#define IMU_GYRO_R_SENS MPU60X0_GYRO_SENS[NAVSTIK_GYRO_RANGE]
#define IMU_GYRO_R_SENS_NUM MPU60X0_GYRO_SENS_FRAC[NAVSTIK_GYRO_RANGE][0]
#define IMU_GYRO_R_SENS_DEN MPU60X0_GYRO_SENS_FRAC[NAVSTIK_GYRO_RANGE][1]
#define IMU_ACCEL_X_SENS MPU60X0_ACCEL_SENS[NAVSTIK_ACCEL_RANGE]
#define IMU_ACCEL_X_SENS_NUM MPU60X0_ACCEL_SENS_FRAC[NAVSTIK_ACCEL_RANGE][0]
#define IMU_ACCEL_X_SENS_DEN MPU60X0_ACCEL_SENS_FRAC[NAVSTIK_ACCEL_RANGE][1]
#define IMU_ACCEL_Y_SENS MPU60X0_ACCEL_SENS[NAVSTIK_ACCEL_RANGE]
#define IMU_ACCEL_Y_SENS_NUM MPU60X0_ACCEL_SENS_FRAC[NAVSTIK_ACCEL_RANGE][0]
#define IMU_ACCEL_Y_SENS_DEN MPU60X0_ACCEL_SENS_FRAC[NAVSTIK_ACCEL_RANGE][1]
#define IMU_ACCEL_Z_SENS MPU60X0_ACCEL_SENS[NAVSTIK_ACCEL_RANGE]
#define IMU_ACCEL_Z_SENS_NUM MPU60X0_ACCEL_SENS_FRAC[NAVSTIK_ACCEL_RANGE][0]
#define IMU_ACCEL_Z_SENS_DEN MPU60X0_ACCEL_SENS_FRAC[NAVSTIK_ACCEL_RANGE][1]
Functions
void imu_navstik_init (void)
Navstik IMU initializtion of the MPU-60x0 and HMC58xx.
void imu_navstik_periodic (void)
Handle all the periodic tasks of the Navstik IMU components.
void imu_navstik_event (void)
Handle all the events of the Navstik IMU components.
Variables
struct ImuNavstik imu_navstik
Basic Navstik IMU data.
Detailed Description
Interface for the Navstik magnetometer, accelerometer and gyroscope.
Definition in file imu_navstik.h.
Data Structure Documentation
struct ImuNavstik
Definition at line 72 of file imu_navstik.h.
Data Fields
struct Hmc58xx hmc
struct Mpu60x0_I2c mpu
Macro Definition Documentation
#define IMU_ACCEL_X_SENS MPU60X0_ACCEL_SENS[NAVSTIK_ACCEL_RANGE]
Definition at line 60 of file imu_navstik.h.
#define IMU_ACCEL_X_SENS_DEN MPU60X0_ACCEL_SENS_FRAC[NAVSTIK_ACCEL_RANGE][1]
Definition at line 62 of file imu_navstik.h.
#define IMU_ACCEL_X_SENS_NUM MPU60X0_ACCEL_SENS_FRAC[NAVSTIK_ACCEL_RANGE][0]
Definition at line 61 of file imu_navstik.h.
#define IMU_ACCEL_Y_SENS MPU60X0_ACCEL_SENS[NAVSTIK_ACCEL_RANGE]
Definition at line 63 of file imu_navstik.h.
#define IMU_ACCEL_Y_SENS_DEN MPU60X0_ACCEL_SENS_FRAC[NAVSTIK_ACCEL_RANGE][1]
Definition at line 65 of file imu_navstik.h.
#define IMU_ACCEL_Y_SENS_NUM MPU60X0_ACCEL_SENS_FRAC[NAVSTIK_ACCEL_RANGE][0]
Definition at line 64 of file imu_navstik.h.
#define IMU_ACCEL_Z_SENS MPU60X0_ACCEL_SENS[NAVSTIK_ACCEL_RANGE]
Definition at line 66 of file imu_navstik.h.
#define IMU_ACCEL_Z_SENS_DEN MPU60X0_ACCEL_SENS_FRAC[NAVSTIK_ACCEL_RANGE][1]
Definition at line 68 of file imu_navstik.h.
#define IMU_ACCEL_Z_SENS_NUM MPU60X0_ACCEL_SENS_FRAC[NAVSTIK_ACCEL_RANGE][0]
Definition at line 67 of file imu_navstik.h.
#define IMU_GYRO_P_SENS MPU60X0_GYRO_SENS[NAVSTIK_GYRO_RANGE]
Definition at line 47 of file imu_navstik.h.
#define IMU_GYRO_P_SENS_DEN MPU60X0_GYRO_SENS_FRAC[NAVSTIK_GYRO_RANGE][1]
Definition at line 49 of file imu_navstik.h.
#define IMU_GYRO_P_SENS_NUM MPU60X0_GYRO_SENS_FRAC[NAVSTIK_GYRO_RANGE][0]
Definition at line 48 of file imu_navstik.h.
#define IMU_GYRO_Q_SENS MPU60X0_GYRO_SENS[NAVSTIK_GYRO_RANGE]
Definition at line 50 of file imu_navstik.h.
#define IMU_GYRO_Q_SENS_DEN MPU60X0_GYRO_SENS_FRAC[NAVSTIK_GYRO_RANGE][1]
Definition at line 52 of file imu_navstik.h.
#define IMU_GYRO_Q_SENS_NUM MPU60X0_GYRO_SENS_FRAC[NAVSTIK_GYRO_RANGE][0]
Definition at line 51 of file imu_navstik.h.
#define IMU_GYRO_R_SENS MPU60X0_GYRO_SENS[NAVSTIK_GYRO_RANGE]
Definition at line 53 of file imu_navstik.h.
#define IMU_GYRO_R_SENS_DEN MPU60X0_GYRO_SENS_FRAC[NAVSTIK_GYRO_RANGE][1]
Definition at line 55 of file imu_navstik.h.
#define IMU_GYRO_R_SENS_NUM MPU60X0_GYRO_SENS_FRAC[NAVSTIK_GYRO_RANGE][0]
Definition at line 54 of file imu_navstik.h.
#define NAVSTIK_ACCEL_RANGE MPU60X0_ACCEL_RANGE_8G
Definition at line 42 of file imu_navstik.h.
Referenced by imu_navstik_init().
#define NAVSTIK_GYRO_RANGE MPU60X0_GYRO_RANGE_1000
Definition at line 38 of file imu_navstik.h.
Referenced by imu_navstik_init().
Function Documentation
void imu_navstik_event (void)
Handle all the events of the Navstik IMU components.
When there is data available convert it to the correct axis and save it in the imu structure.
Definition at line 102 of file imu_navstik.c.
References Imu::accel, Imu::accel_unscaled, Hmc58xx::data, Mpu60x0_I2c::data_accel, Mpu60x0_I2c::data_available, Hmc58xx::data_available, Mpu60x0_I2c::data_rates, get_sys_time_usec(), Imu::gyro, Imu::gyro_unscaled, ImuNavstik::hmc, hmc58xx_event(), imu, IMU_BOARD_ID, imu_navstik, imu_scale_accel(), imu_scale_gyro(), imu_scale_mag(), Imu::mag, Imu::mag_unscaled, ImuNavstik::mpu, mpu60x0_i2c_event(), RATES_COPY, VECT3_COPY, Int32Vect3::x, Int32Vect3::y, and Int32Vect3::z.
void imu_navstik_init (void)
Navstik IMU initializtion of the MPU-60x0 and HMC58xx.
Definition at line 72 of file imu_navstik.c.
References Mpu60x0Config::accel_range, Mpu60x0_I2c::config, Mpu60x0Config::dlpf_cfg, Mpu60x0Config::gyro_range, ImuNavstik::hmc, HMC58XX_ADDR, hmc58xx_init(), ImuNavstik::mpu, MPU60X0_ADDR_ALT, mpu60x0_i2c_init(), NAVSTIK_ACCEL_RANGE, NAVSTIK_GYRO_RANGE, NAVSTIK_MAG_I2C_DEV, NAVSTIK_MPU_I2C_DEV, and Mpu60x0Config::smplrt_div.
void imu_navstik_periodic (void)
Handle all the periodic tasks of the Navstik IMU components.
Read the MPU60x0 every periodic call and the HMC58XX every 10th call.
Definition at line 89 of file imu_navstik.c.
References ImuNavstik::hmc, hmc58xx_periodic(), imu_navstik, ImuNavstik::mpu, and mpu60x0_i2c_periodic().
Variable Documentation
struct ImuNavstik imu_navstik
Basic Navstik IMU data.
Definition at line 67 of file imu_navstik.c.
Referenced by imu_navstik_event(), and imu_navstik_periodic().