Paparazzi UAS: sw/airborne/modules/ins/ins_xsens700.h File Reference
ins_xsens700.h File Reference
Xsens700 as a full INS solution.
#include "std.h"
#include "xsens700.h"
Functions
void ins_xsens700_init (void)
void ins_xsens700_event (void)
Variables
float ins_pitch_neutral
float ins_roll_neutral
Detailed Description
Xsens700 as a full INS solution.
Definition in file ins_xsens700.h.
Function Documentation
void ins_xsens700_event (void)
Definition at line 80 of file ins_xsens700.c.
References handle_ins_msg(), XsensParser::msg_received, parse_xsens700_msg(), Xsens::parser, xsens700, and xsens_parser_event().
void ins_xsens700_init (void)
Definition at line 66 of file ins_xsens700.c.
References gps_cb(), INS_PITCH_NEUTRAL_DEFAULT, INS_ROLL_NEUTRAL_DEFAULT, INS_XSENS700_GPS_ID, nav_utm_east0, nav_utm_north0, nav_utm_zone0, stateSetLocalUtmOrigin_f(), stateSetPositionUtm_f(), and xsens700_init().
Variable Documentation
float ins_pitch_neutral
Definition at line 15 of file ins_arduimu.c.
float ins_roll_neutral
Definition at line 14 of file ins_arduimu.c.