Paparazzi UAS: sw/airborne/modules/ins/ins_mekf_wind_wrapper.h File Reference
ins_mekf_wind_wrapper.h File Reference
Paparazzi specific wrapper to run MEKF-Wind INS filter.
#include "std.h"
#include "math/pprz_orientation_conversion.h"
Data Structures
struct InsMekfWind
filter structure
Macros
#define ins_mekf_wind_wrapper_Reset(_v)
Functions
void ins_mekf_wind_wrapper_init (void)
Init function.
Variables
struct InsMekfWind ins_mekf_wind
Detailed Description
Paparazzi specific wrapper to run MEKF-Wind INS filter.
Definition in file ins_mekf_wind_wrapper.h.
Data Structure Documentation
struct InsMekfWind
filter structure
Definition at line 35 of file ins_mekf_wind_wrapper.h.
Data Fields
bool baro_initialized
struct OrientationReps body_to_imu
bool gps_initialized
bool is_aligned
bool reset
Macro Definition Documentation
#define ins_mekf_wind_wrapper_Reset (_v)
Value:
{ \
  ins_mekf_wind.reset = false;            \
  ins_mekf_wind.baro_initialized = false; \
  ins_mekf_wind.gps_initialized = false;     \
  ins_mekf_wind_reset();                  \
}
Definition at line 47 of file ins_mekf_wind_wrapper.h.
Referenced by ins_reset_local_origin().
Function Documentation
void ins_mekf_wind_wrapper_init (void)
Init function.
Definition at line 546 of file ins_mekf_wind_wrapper.c.
References ABI_BROADCAST, accel_cb(), accel_ev, ahrs_aligner_init(), airspeed_cb(), airspeed_ev, aligner_cb(), aligner_ev, LlaCoor_i::alt, UtmCoor_f::alt, baro_cb(), baro_ev, InsMekfWind::baro_initialized, body_to_imu_cb(), body_to_imu_ev, counter, DefaultPeriodic, UtmCoor_f::east, ecef_of_lla_i(), geo_mag_cb(), geo_mag_ev, gps_cb(), gps_ev, InsMekfWind::gps_initialized, gyro_cb(), gyro_ev, LtpDef_i::hmsl, incidence_cb(), incidence_ev, ins_mekf_wind, INS_MEKF_WIND_AIRSPEED_ID, INS_MEKF_WIND_BARO_ID, INS_MEKF_WIND_GPS_ID, INS_MEKF_WIND_IMU_ID, INS_MEKF_WIND_INCIDENCE_ID, ins_mekf_wind_init(), INS_MEKF_WIND_MAG_ID, ins_mekf_wind_set_mag_h(), InsMekfWind::is_aligned, LlaCoor_i::lat, LlaCoor_i::lon, ltp_def_from_ecef_i(), mag_cb(), mag_ev, nav_utm_east0, nav_utm_north0, nav_utm_zone0, UtmCoor_f::north, pprzLogFile, pressure_diff_cb(), pressure_diff_ev, register_periodic_telemetry(), InsMekfWind::reset, send_euler(), send_filter_status(), send_inv_filter(), send_wind(), stateSetLocalOrigin_i(), stateSetLocalUtmOrigin_f(), stateSetPositionUtm_f(), and UtmCoor_f::zone.
Variable Documentation
struct InsMekfWind ins_mekf_wind
Definition at line 50 of file ins_mekf_wind_wrapper.c.
Referenced by accel_cb(), airspeed_cb(), aligner_cb(), baro_cb(), body_to_imu_cb(), gps_cb(), gyro_cb(), incidence_cb(), ins_mekf_wind_wrapper_init(), mag_cb(), pressure_diff_cb(), and send_filter_status().