Paparazzi UAS: sw/airborne/modules/range_finder/laser_range_array.c File Reference
laser_range_array.c File Reference
#include "modules/range_finder/laser_range_array.h"
#include "generated/airframe.h"
#include "pprzlink/pprz_transport.h"
#include "pprzlink/intermcu_msg.h"
#include "mcu_periph/uart.h"
#include "subsystems/abi.h"
#include "message_pragmas.h"
#include "pprzlink/messages.h"
#include "subsystems/datalink/downlink.h"
Data Structures
struct laser_range_array_t
Macros
#define VL53L0_MAX_VAL 8.191f
Functions
void laser_range_array_init (void)
static void laser_range_array_parse_msg (void)
void laser_range_array_event (void)
Variables
static struct laser_range_array_t laser_range_array
static uint8_t lra_msg_buf [128]
The message buffer.
static float laser_range_array_orientations [] = LASER_RANGE_ARRAY_ORIENTATIONS
static uint8_t agl_id = 255
Data Structure Documentation
struct laser_range_array_t
Definition at line 43 of file laser_range_array.c.
Data Fields
struct link_device * device The device which is uses for communication.
bool msg_available If we received a message.
struct pprz_transport transport The transport layer (PPRZ)
Macro Definition Documentation
#define VL53L0_MAX_VAL 8.191f
Definition at line 60 of file laser_range_array.c.
Referenced by laser_range_array_parse_msg().
Function Documentation
void laser_range_array_event (void)
Definition at line 106 of file laser_range_array.c.
References laser_range_array_t::device, laser_range_array_parse_msg(), lra_msg_buf, laser_range_array_t::msg_available, and laser_range_array_t::transport.
void laser_range_array_init (void)
Definition at line 62 of file laser_range_array.c.
References laser_range_array_orientations, and laser_range_array_t::transport.
static void laser_range_array_parse_msg (void) static
Definition at line 79 of file laser_range_array.c.
References AGL_VL53L0_LASER_ARRAY_ID, get_sys_time_usec(), laser_range_array_orientations, lra_msg_buf, OBS_DETECTION_RANGE_ARRAY_ID, and VL53L0_MAX_VAL.
Referenced by laser_range_array_event().
Variable Documentation
uint8_t agl_id = 255 static
Definition at line 58 of file laser_range_array.c.
struct laser_range_array_t laser_range_array static
Initial value:
= {
  .device = (&((LASER_RANGE_ARRAY_PORT).device)),
  .msg_available = false
}
Definition at line 49 of file laser_range_array.c.
float laser_range_array_orientations[] = LASER_RANGE_ARRAY_ORIENTATIONS static
Definition at line 57 of file laser_range_array.c.
Referenced by laser_range_array_init(), and laser_range_array_parse_msg().
uint8_t lra_msg_buf[128] static
The message buffer.
Definition at line 54 of file laser_range_array.c.
Referenced by laser_range_array_event(), and laser_range_array_parse_msg().