Paparazzi UAS: sw/airborne/arch/lpc21/peripherals/ms2100_arch.c File Reference
ms2100_arch.c File Reference
LPC21xx specific functions for the ms2100 magnetic sensor from PNI.
#include "peripherals/ms2100.h"
#include "LPC21xx.h"
#include "armVIC.h"
#include "mcu_periph/sys_time.h"
#include <BOARD_CONFIG>
Functions
static void EXTINT_ISR (void)
void ms2100_arch_init (void)
void ms2100_reset_cb (struct spi_transaction *t)
Reset callback.
Detailed Description
LPC21xx specific functions for the ms2100 magnetic sensor from PNI.
Definition in file ms2100_arch.c.
Function Documentation
void EXTINT_ISR (void) static
Definition at line 60 of file ms2100_arch.c.
References EXTINT, ISR_ENTRY, ISR_EXIT, ms2100, MS2100_DRDY_EINT, MS2100_GOT_EOC, Ms2100::status, and VICVectAddr.
Referenced by ms2100_arch_init().
void ms2100_arch_init (void)
Definition at line 38 of file ms2100_arch.c.
Referenced by ms2100_init().
void ms2100_reset_cb (struct spi_transaction * t)
Reset callback.
called before spi transaction and after slave select
Definition at line 71 of file ms2100_arch.c.
Referenced by ms2100_init().