Paparazzi UAS: sw/airborne/arch/lpc21/mcu_periph/uart_arch.c File Reference
uart_arch.c File Reference
LPC21 architecture
Handling of UART hardware for lpc21xx.
#include "mcu_periph/uart.h"
#include "armVIC.h"
Functions
static void uart_disable_interrupts (struct uart_periph *p)
static void uart_enable_interrupts (struct uart_periph *p)
static void uart_set_baudrate (struct uart_periph *p, uint32_t baud)
void uart_periph_set_baudrate (struct uart_periph *p, uint32_t baud)
Set baudrate.
void uart_periph_set_bits_stop_parity (struct uart_periph *p, uint8_t bits, uint8_t stop, uint8_t parity)
Set parity and stop bits.
void uart_put_byte (struct uart_periph *p, long fd, uint8_t data)
Uart transmit implementation.
static void uart_ISR (struct uart_periph *p)
Detailed Description
Handling of UART hardware for lpc21xx.
Definition in file uart_arch.c.
Function Documentation
static void uart_disable_interrupts (struct uart_periph * p) inline static
Definition at line 34 of file uart_arch.c.
References uart_periph::reg_addr.
Referenced by uart_periph_set_baudrate().
static void uart_enable_interrupts (struct uart_periph * p) inline static
Definition at line 43 of file uart_arch.c.
References uart_periph::reg_addr, and UIER_ERBFI.
Referenced by uart_periph_set_baudrate().
static void uart_ISR (struct uart_periph * p) inline static
Definition at line 114 of file uart_arch.c.
References uart_periph::reg_addr, uart_periph::rx_buf, uart_periph::rx_extract_idx, uart_periph::rx_insert_idx, uart_periph::tx_buf, uart_periph::tx_extract_idx, uart_periph::tx_insert_idx, uart_periph::tx_running, UART_RX_BUFFER_SIZE, UART_TX_BUFFER_SIZE, UIIR_CTI_INT, UIIR_ID_MASK, UIIR_NO_INT, UIIR_RDA_INT, UIIR_RLS_INT, UIIR_THRE_INT, ULSR_RDR, and ULSR_THRE.
void uart_periph_set_baudrate (struct uart_periph * p, uint32_t baud)
Set baudrate.
Definition at line 70 of file uart_arch.c.
References uart_disable_interrupts(), uart_enable_interrupts(), and uart_set_baudrate().
void uart_periph_set_bits_stop_parity (struct uart_periph * p, uint8_t bits, uint8_t stop, uint8_t parity)
Set parity and stop bits.
Definition at line 77 of file uart_arch.c.
void uart_put_byte (struct uart_periph * p, long fd, uint8_t data)
Uart transmit implementation.
Definition at line 83 of file uart_arch.c.
References disableIRQ(), uart_periph::reg_addr, restoreIRQ(), uart_periph::tx_buf, uart_periph::tx_extract_idx, uart_periph::tx_insert_idx, uart_periph::tx_running, UART_TX_BUFFER_SIZE, and UIER_ETBEI.
static void uart_set_baudrate (struct uart_periph * p, uint32_t baud) inline static
Definition at line 49 of file uart_arch.c.
References uart_periph::baudrate, PCLK, uart_periph::reg_addr, UART_8N1, UART_FIFO_8, and ULCR_DLAB_ENABLE.
Referenced by uart_periph_set_baudrate().