Paparazzi UAS: sw/airborne/modules/sensors/mag_hmc58xx.c File Reference
mag_hmc58xx.c File Reference
Module wrapper for Honeywell HMC5843 and HMC5883 magnetometers.
#include "modules/sensors/mag_hmc58xx.h"
#include "mcu_periph/uart.h"
#include "pprzlink/messages.h"
#include "subsystems/datalink/downlink.h"
#include "generated/airframe.h"
Macros
#define HMC58XX_CHAN_X 0
#define HMC58XX_CHAN_Y 1
#define HMC58XX_CHAN_Z 2
#define HMC58XX_CHAN_X_SIGN +
#define HMC58XX_CHAN_Y_SIGN +
#define HMC58XX_CHAN_Z_SIGN +
Functions
void mag_hmc58xx_module_init (void)
void mag_hmc58xx_module_periodic (void)
void mag_hmc58xx_module_event (void)
void mag_hmc58xx_report (void)
Variables
struct Hmc58xx mag_hmc58xx
Detailed Description
Module wrapper for Honeywell HMC5843 and HMC5883 magnetometers.
Definition in file mag_hmc58xx.c.
Macro Definition Documentation
#define HMC58XX_CHAN_X 0
Definition at line 35 of file mag_hmc58xx.c.
Referenced by mag_hmc58xx_module_event(), and mag_hmc58xx_report().
#define HMC58XX_CHAN_X_SIGN +
Definition at line 44 of file mag_hmc58xx.c.
Referenced by mag_hmc58xx_module_event(), and mag_hmc58xx_report().
#define HMC58XX_CHAN_Y 1
Definition at line 38 of file mag_hmc58xx.c.
Referenced by mag_hmc58xx_module_event(), and mag_hmc58xx_report().
#define HMC58XX_CHAN_Y_SIGN +
Definition at line 47 of file mag_hmc58xx.c.
Referenced by mag_hmc58xx_module_event(), and mag_hmc58xx_report().
#define HMC58XX_CHAN_Z 2
Definition at line 41 of file mag_hmc58xx.c.
Referenced by mag_hmc58xx_module_event(), and mag_hmc58xx_report().
#define HMC58XX_CHAN_Z_SIGN +
Definition at line 50 of file mag_hmc58xx.c.
Referenced by mag_hmc58xx_module_event(), and mag_hmc58xx_report().
Function Documentation
void mag_hmc58xx_module_event (void)
Definition at line 86 of file mag_hmc58xx.c.
References Hmc58xx::data, Hmc58xx::data_available, get_sys_time_usec(), HMC58XX_CHAN_X, HMC58XX_CHAN_X_SIGN, HMC58XX_CHAN_Y, HMC58XX_CHAN_Y_SIGN, HMC58XX_CHAN_Z, HMC58XX_CHAN_Z_SIGN, hmc58xx_event(), imu, imu_scale_mag(), int32_rmat_vmult(), Imu::mag, mag_hmc58xx, mag_hmc58xx_report(), MAG_HMC58XX_SENDER_ID, Imu::mag_unscaled, and VECT3_COPY.
void mag_hmc58xx_module_init (void)
Definition at line 67 of file mag_hmc58xx.c.
References ANGLE_BFP_OF_REAL, HMC58XX_ADDR, hmc58xx_init(), int32_rmat_of_eulers, and mag_hmc58xx.
void mag_hmc58xx_module_periodic (void)
Definition at line 81 of file mag_hmc58xx.c.
References hmc58xx_periodic(), and mag_hmc58xx.
void mag_hmc58xx_report (void)
Definition at line 126 of file mag_hmc58xx.c.
References Hmc58xx::data, DefaultChannel, DefaultDevice, HMC58XX_CHAN_X, HMC58XX_CHAN_X_SIGN, HMC58XX_CHAN_Y, HMC58XX_CHAN_Y_SIGN, HMC58XX_CHAN_Z, HMC58XX_CHAN_Z_SIGN, mag_hmc58xx, Int32Vect3::x, Int32Vect3::y, and Int32Vect3::z.
Referenced by mag_hmc58xx_module_event().
Variable Documentation
struct Hmc58xx mag_hmc58xx
Definition at line 65 of file mag_hmc58xx.c.
Referenced by mag_hmc58xx_module_event(), mag_hmc58xx_module_init(), mag_hmc58xx_module_periodic(), and mag_hmc58xx_report().