Paparazzi UAS: sw/airborne/modules/sensors/mag_lis3mdl.c File Reference
mag_lis3mdl.c File Reference
Module wrapper for ST LIS3MDL magnetometers.
#include "modules/sensors/mag_lis3mdl.h"
#include "mcu_periph/uart.h"
#include "pprzlink/messages.h"
#include "subsystems/datalink/downlink.h"
#include "generated/airframe.h"
Macros
#define LIS3MDL_CHAN_X 0
#define LIS3MDL_CHAN_Y 1
#define LIS3MDL_CHAN_Z 2
#define LIS3MDL_CHAN_X_SIGN +
#define LIS3MDL_CHAN_Y_SIGN +
#define LIS3MDL_CHAN_Z_SIGN +
Functions
void mag_lis3mdl_module_init (void)
void mag_lis3mdl_module_periodic (void)
void mag_lis3mdl_module_event (void)
void mag_lis3mdl_report (void)
Variables
struct Lis3mdl mag_lis3mdl
Detailed Description
Module wrapper for ST LIS3MDL magnetometers.
Definition in file mag_lis3mdl.c.
Macro Definition Documentation
#define LIS3MDL_CHAN_X 0
Definition at line 34 of file mag_lis3mdl.c.
Referenced by mag_lis3mdl_module_event(), and mag_lis3mdl_report().
#define LIS3MDL_CHAN_X_SIGN +
Definition at line 43 of file mag_lis3mdl.c.
Referenced by mag_lis3mdl_module_event(), and mag_lis3mdl_report().
#define LIS3MDL_CHAN_Y 1
Definition at line 37 of file mag_lis3mdl.c.
Referenced by mag_lis3mdl_module_event(), and mag_lis3mdl_report().
#define LIS3MDL_CHAN_Y_SIGN +
Definition at line 46 of file mag_lis3mdl.c.
Referenced by mag_lis3mdl_module_event(), and mag_lis3mdl_report().
#define LIS3MDL_CHAN_Z 2
Definition at line 40 of file mag_lis3mdl.c.
Referenced by mag_lis3mdl_module_event(), and mag_lis3mdl_report().
#define LIS3MDL_CHAN_Z_SIGN +
Definition at line 49 of file mag_lis3mdl.c.
Referenced by mag_lis3mdl_module_event(), and mag_lis3mdl_report().
Function Documentation
void mag_lis3mdl_module_event (void)
Definition at line 89 of file mag_lis3mdl.c.
References Lis3mdl::data, Lis3mdl::data_available, get_sys_time_usec(), imu, imu_scale_mag(), int32_rmat_vmult(), LIS3MDL_CHAN_X, LIS3MDL_CHAN_X_SIGN, LIS3MDL_CHAN_Y, LIS3MDL_CHAN_Y_SIGN, LIS3MDL_CHAN_Z, LIS3MDL_CHAN_Z_SIGN, lis3mdl_event(), Imu::mag, mag_lis3mdl, mag_lis3mdl_report(), MAG_LIS3MDL_SENDER_ID, Imu::mag_unscaled, and VECT3_COPY.
void mag_lis3mdl_module_init (void)
Definition at line 66 of file mag_lis3mdl.c.
References ANGLE_BFP_OF_REAL, int32_rmat_of_eulers, LIS3MDL_ADDR1, LIS3MDL_DATA_RATE_80_HZ, lis3mdl_init(), LIS3MDL_MODE_CONTINUOUS, LIS3MDL_PERFORMANCE_ULTRA_HIGH, LIS3MDL_SCALE_4_GAUSS, and mag_lis3mdl.
void mag_lis3mdl_module_periodic (void)
Definition at line 84 of file mag_lis3mdl.c.
References lis3mdl_periodic(), and mag_lis3mdl.
void mag_lis3mdl_report (void)
Definition at line 129 of file mag_lis3mdl.c.
References Lis3mdl::data, DefaultChannel, DefaultDevice, LIS3MDL_CHAN_X, LIS3MDL_CHAN_X_SIGN, LIS3MDL_CHAN_Y, LIS3MDL_CHAN_Y_SIGN, LIS3MDL_CHAN_Z, LIS3MDL_CHAN_Z_SIGN, mag_lis3mdl, Int32Vect3::x, Int32Vect3::y, and Int32Vect3::z.
Referenced by mag_lis3mdl_module_event().
Variable Documentation
struct Lis3mdl mag_lis3mdl
Definition at line 64 of file mag_lis3mdl.c.
Referenced by mag_lis3mdl_module_event(), mag_lis3mdl_module_init(), mag_lis3mdl_module_periodic(), and mag_lis3mdl_report().