Paparazzi UAS: sw/airborne/modules/actuators/actuators_ostrich.h File Reference
actuators_ostrich.h File Reference
#include "std.h"
Data Structures
struct ActuatorsOstrich
Macros
#define ActuatorOSTRICHSet(_i, _v) { actuators_ostrich.cmds[_i] = _v; }
#define ActuatorsOSTRICHInit() actuators_ostrich_init()
#define ActuatorsOSTRICHCommit() {}
Functions
void actuators_ostrich_init (void)
void actuators_ostrich_periodic (void)
Variables
struct ActuatorsOstrich actuators_ostrich
Detailed Description
Author
Fabien Bonneval Driver for the Ostrich rover controller board
Definition in file actuators_ostrich.h.
Data Structure Documentation
struct ActuatorsOstrich
Definition at line 32 of file actuators_ostrich.h.
Data Fields
uint16_t cmds[3] commands
Macro Definition Documentation
#define ActuatorOSTRICHSet (_i, _v) { actuators_ostrich.cmds[_i] = _v; }
Definition at line 44 of file actuators_ostrich.h.
#define ActuatorsOSTRICHCommit () {}
Definition at line 46 of file actuators_ostrich.h.
#define ActuatorsOSTRICHInit () actuators_ostrich_init()
Definition at line 45 of file actuators_ostrich.h.
Function Documentation
void actuators_ostrich_init (void)
Definition at line 88 of file actuators_ostrich.c.
References actuators_ostrich, ActuatorsOstrich::cmds, SPEED_NEUTRAL, and TURN_NEUTRAL.
void actuators_ostrich_periodic (void)
Definition at line 96 of file actuators_ostrich.c.
References actuators_ostrich, rawData::bytes, RawMessage::bytes, SpeedMessage::checksum, ActuatorsOstrich::cmds, compute_checksum(), rawData::data, SpeedMessage::msg_type, SpeedMessage::raw_data, speed_cmd_to_msg(), RawMessage::speed_message, START_BYTE, SpeedMessage::start_byte, turn_cmd_to_msg(), uart_put_buffer(), SpeedMessagePayload::vtheta, SpeedMessagePayload::vx, and SpeedMessagePayload::vy.
Variable Documentation
struct ActuatorsOstrich actuators_ostrich
Definition at line 38 of file actuators_ostrich.c.
Referenced by actuators_ostrich_init(), and actuators_ostrich_periodic().