Paparazzi UAS: sw/airborne/modules/actuators/actuators_md25.h File Reference
actuators_md25.h File Reference
#include "std.h"
#include "mcu_periph/i2c.h"
Data Structures
struct ActuatorsMD25
Macros
#define ActuatorMD25Set(_i, _v) { actuators_md25.cmds[_i] = _v; }
#define ActuatorsMD25Init() actuators_md25_init()
#define ActuatorsMD25Commit() actuators_md25_set()
Functions
void actuators_md25_init (void)
void actuators_md25_periodic (void)
void actuators_md25_event (void)
void actuators_md25_set (void)
Variables
struct ActuatorsMD25 actuators_md25
Detailed Description
Author
Gautier Hattenberger Driver for the MD25 rover controller board
Definition in file actuators_md25.h.
Data Structure Documentation
struct ActuatorsMD25
Definition at line 34 of file actuators_md25.h.
Data Fields
uint8_t accel_rate accel rate (from 1 to 10)
uint8_t bat batterie voltage (in decivolt)
uint8_t cmds[2] commands
uint8_t current[2] current in motors (in deciamp)
int32_t encoders[2] encoder values
bool initialized init flag
uint8_t mode control mode
struct i2c_transaction trans_cmd i2c struct for command
struct i2c_transaction trans_sensors i2c struct for sensors
Macro Definition Documentation
#define ActuatorMD25Set (_i, _v) { actuators_md25.cmds[_i] = _v; }
Definition at line 54 of file actuators_md25.h.
#define ActuatorsMD25Commit () actuators_md25_set()
Definition at line 56 of file actuators_md25.h.
#define ActuatorsMD25Init () actuators_md25_init()
Definition at line 55 of file actuators_md25.h.
Function Documentation
void actuators_md25_event (void)
Definition at line 120 of file actuators_md25.c.
References actuators_md25, ActuatorsMD25::bat, i2c_transaction::buf, ActuatorsMD25::current, ActuatorsMD25::encoders, I2CTransDone, I2CTransFailed, I2CTransSuccess, ActuatorsMD25::initialized, Int32FromBuf, i2c_transaction::status, ActuatorsMD25::trans_cmd, and ActuatorsMD25::trans_sensors.
void actuators_md25_init (void)
Definition at line 75 of file actuators_md25.c.
References ActuatorsMD25::accel_rate, ACTUATORS_MD25_ACCEL_RATE, ACTUATORS_MD25_MODE, ActuatorsMD25::bat, ActuatorsMD25::cmds, ActuatorsMD25::encoders, I2CTransDone, ActuatorsMD25::initialized, ActuatorsMD25::mode, i2c_transaction::status, ActuatorsMD25::trans_cmd, and ActuatorsMD25::trans_sensors.
void actuators_md25_periodic (void)
Definition at line 90 of file actuators_md25.c.
References ActuatorsMD25::accel_rate, actuators_md25, ACTUATORS_MD25_I2C_ADDR, i2c_transaction::buf, i2c_transceive(), i2c_transmit(), I2CTransDone, ActuatorsMD25::initialized, MD25_REG_ACCEL_RATE, MD25_REG_ENCODER1, ActuatorsMD25::mode, i2c_transaction::status, and ActuatorsMD25::trans_sensors.
void actuators_md25_set (void)
Definition at line 108 of file actuators_md25.c.
References actuators_md25, ACTUATORS_MD25_I2C_ADDR, i2c_transaction::buf, ActuatorsMD25::cmds, i2c_transmit(), I2CTransDone, ActuatorsMD25::initialized, MD25_REG_SPEED1, i2c_transaction::status, and ActuatorsMD25::trans_cmd.
Variable Documentation
struct ActuatorsMD25 actuators_md25
Definition at line 73 of file actuators_md25.c.
Referenced by actuators_md25_event(), actuators_md25_periodic(), and actuators_md25_set().