Paparazzi UAS: sw/airborne/peripherals/ms2100.c File Reference
ms2100.c File Reference
Driver for the ms2100 magnetic sensor from PNI.
#include "peripherals/ms2100.h"
#include "mcu_periph/spi.h"
#include <stdlib.h>
Macros
#define MS2100_DIVISOR_128 2
#define MS2100_DIVISOR_256 3
#define MS2100_DIVISOR_512 4
#define MS2100_DIVISOR_1024 5
#define MS2100_DIVISOR MS2100_DIVISOR_1024
#define Int16FromBuf(_buf, _idx) ((int16_t)((_buf[_idx]<<8) | _buf[_idx+1]))
Functions
void ms2100_init (struct Ms2100 *ms, struct spi_periph *spi_p, uint8_t slave_idx)
void ms2100_read (struct Ms2100 *ms)
send request to read next axis
void ms2100_event (struct Ms2100 *ms)
Variables
struct Ms2100 ms2100
Detailed Description
Driver for the ms2100 magnetic sensor from PNI.
Definition in file ms2100.c.
Macro Definition Documentation
#define Int16FromBuf (_buf, _idx) ((int16_t)((_buf[_idx]<<8) | _buf[_idx+1]))
Definition at line 103 of file ms2100.c.
Referenced by ms2100_event().
#define MS2100_DIVISOR MS2100_DIVISOR_1024
Definition at line 40 of file ms2100.c.
Referenced by ms2100_read().
#define MS2100_DIVISOR_1024 5
Definition at line 37 of file ms2100.c.
#define MS2100_DIVISOR_128 2
Definition at line 34 of file ms2100.c.
#define MS2100_DIVISOR_256 3
Definition at line 35 of file ms2100.c.
#define MS2100_DIVISOR_512 4
Definition at line 36 of file ms2100.c.
Function Documentation
void ms2100_event (struct Ms2100 * ms)
Definition at line 105 of file ms2100.c.
References Ms2100::cur_axe, Ms2100::data, Int16FromBuf, MS2100_DATA_AVAILABLE, MS2100_GOT_EOC, MS2100_IDLE, MS2100_READING_RES, Ms2100::read_buf, Ms2100::read_trans, Ms2100::req_trans, Ms2100::spi_p, spi_submit(), SPITransDone, SPITransFailed, SPITransSuccess, Ms2100::status, and spi_transaction::status.
void ms2100_init (struct Ms2100 * ms, struct spi_periph * spi_p, uint8_t slave_idx)
Definition at line 47 of file ms2100.c.
References spi_transaction::after_cb, spi_transaction::before_cb, spi_transaction::bitorder, spi_transaction::cdiv, spi_transaction::cpha, spi_transaction::cpol, Ms2100::cur_axe, Ms2100::data, spi_transaction::dss, spi_transaction::input_buf, spi_transaction::input_length, INT_VECT3_ZERO, ms2100_arch_init(), MS2100_IDLE, ms2100_reset_cb(), spi_transaction::output_buf, spi_transaction::output_length, Ms2100::read_buf, Ms2100::read_trans, Ms2100::req_buf, Ms2100::req_trans, spi_transaction::select, spi_transaction::slave_idx, Ms2100::spi_p, SPICphaEdge1, SPICpolIdleLow, SPIDiv64, SPIDss8bit, SPIMSBFirst, SPISelectUnselect, SPITransDone, Ms2100::status, and spi_transaction::status.
Referenced by imu_b2_init().
void ms2100_read (struct Ms2100 * ms)
send request to read next axis
Definition at line 96 of file ms2100.c.
References Ms2100::cur_axe, MS2100_DIVISOR, MS2100_SENDING_REQ, Ms2100::req_buf, Ms2100::req_trans, Ms2100::spi_p, spi_submit(), and Ms2100::status.
Referenced by ms2100_periodic().
Variable Documentation
struct Ms2100 ms2100
Definition at line 44 of file ms2100.c.
Referenced by exti9_5_isr(), EXTINT_ISR(), imu_b2_init(), and imu_b2_periodic().