Paparazzi UAS: sw/airborne/peripherals/ms5611.c File Reference
ms5611.c File Reference
MS5611 and MS5607 barometer driver common functions (I2C and SPI).
#include "peripherals/ms5611.h"
#include "std.h"
Functions
bool ms5611_prom_crc_ok (uint16_t *prom)
Check if CRC of PROM data is OK.
bool ms5611_calc (struct Ms5611Data *ms)
Calculate temperature and compensated pressure for MS5611.
bool ms5607_calc (struct Ms5611Data *ms)
Calculate temperature and compensated pressure for MS5607.
Detailed Description
MS5611 and MS5607 barometer driver common functions (I2C and SPI).
Definition in file ms5611.c.
Function Documentation
bool ms5607_calc (struct Ms5611Data * ms)
Calculate temperature and compensated pressure for MS5607.
MS5607 basically has half the resolution of the MS5611.
Returns
TRUE if measurement was valid, FALSE otherwise
Definition at line 124 of file ms5611.c.
References Ms5611Data::c, Ms5611Data::d1, Ms5611Data::d2, p, Ms5611Data::pressure, and Ms5611Data::temperature.
Referenced by ms5611_i2c_event(), and ms5611_spi_event().
bool ms5611_calc (struct Ms5611Data * ms)
Calculate temperature and compensated pressure for MS5611.
Returns
TRUE if measurement was valid, FALSE otherwise
Definition at line 81 of file ms5611.c.
References Ms5611Data::c, Ms5611Data::d1, Ms5611Data::d2, p, Ms5611Data::pressure, and Ms5611Data::temperature.
Referenced by ms5611_i2c_event(), and ms5611_spi_event().
bool ms5611_prom_crc_ok (uint16_t * prom)
Check if CRC of PROM data is OK.
Returns
TRUE if OK, FALSE otherwise
Definition at line 36 of file ms5611.c.
References crc.
Referenced by ms5611_i2c_event(), and ms5611_spi_event().