Paparazzi UAS: sw/airborne/modules/guidance/gvf/nav/nav_survey_polygon_gvf.c File Reference
nav_survey_polygon_gvf.c File Reference
#include "nav_survey_polygon_gvf.h"
#include "firmwares/fixedwing/nav.h"
#include "state.h"
#include "autopilot.h"
#include "generated/flight_plan.h"
#include "modules/guidance/gvf/gvf.h"
Functions
static void gvf_nav_points (struct FloatVect2 start, struct FloatVect2 end)
static bool gvf_intercept_two_lines (struct FloatVect2 *p, struct FloatVect2 x, struct FloatVect2 y, float a1, float a2, float b1, float b2)
intercept two lines and give back the point of intersection
static bool gvf_get_two_intersects (struct FloatVect2 *x, struct FloatVect2 *y, struct FloatVect2 a, struct FloatVect2 b)
intersects a line with the polygon and gives back the two intersection points
void gvf_nav_survey_polygon_setup (uint8_t first_wp, uint8_t size, float angle, float sweep_width, float shot_dist, float min_rad, float altitude)
initializes the variables needed for the survey to start
void gvf_nav_direction_circle (float rad)
main navigation routine.
bool gvf_nav_survey_polygon_run (void)
Variables
float gvf_nav_survey_sweep = 100.f
struct gvf_SurveyPolyAdv gvf_survey
Function Documentation
static bool gvf_get_two_intersects (struct FloatVect2 * x, struct FloatVect2 * y, struct FloatVect2 a, struct FloatVect2 b) static
intersects a line with the polygon and gives back the two intersection points
Returns
TRUE if two intersection can be found, else FALSE
Parameters
x,y intersection points
a,b define the line to intersection
Definition at line 82 of file nav_survey_polygon_gvf.c.
References gvf_SurveyPolyAdv::dir_vec, gvf_intercept_two_lines(), gvf_survey, gvf_SurveyPolyAdv::poly_count, gvf_SurveyPolyAdv::poly_first, waypoints, point::x, FloatVect2::x, point::y, and FloatVect2::y.
Referenced by gvf_nav_survey_polygon_run(), and gvf_nav_survey_polygon_setup().
static bool gvf_intercept_two_lines (struct FloatVect2 * p, struct FloatVect2 x, struct FloatVect2 y, float a1, float a2, float b1, float b2) static
intercept two lines and give back the point of intersection
Returns
FALSE if no intersection can be found or intersection does not lie between points a and b else TRUE
Parameters
p returns intersection
x,y first line is defined by point x and y (goes through this points)
a1,a2,b1,b2 second line by coordinates a1/a2, b1/b2
Definition at line 59 of file nav_survey_polygon_gvf.c.
References FloatVect2::x, and FloatVect2::y.
Referenced by gvf_get_two_intersects().
void gvf_nav_direction_circle (float rad)
main navigation routine.
This is called periodically evaluates the current Position and stage and navigates accordingly.
Returns
True until the survey is finished
Definition at line 241 of file nav_survey_polygon_gvf.c.
References gvf_set_direction().
Referenced by gvf_nav_survey_polygon_run().
static void gvf_nav_points (struct FloatVect2 start, struct FloatVect2 end) static
Definition at line 46 of file nav_survey_polygon_gvf.c.
References gvf_segment_XY1_XY2(), FloatVect2::x, and FloatVect2::y.
Referenced by gvf_nav_survey_polygon_run().
bool gvf_nav_survey_polygon_run (void)
Definition at line 250 of file nav_survey_polygon_gvf.c.
References CARROT, dc_stop(), dc_survey(), gvf_SurveyPolyAdv::dir_vec, gvf_SurveyPolyAdv::entry_center, gENTRY, gRET, gSEG, gTURN1, gTURN2, gvf_ellipse_XY(), gvf_get_two_intersects(), gvf_nav_direction_circle(), gvf_nav_points(), gvf_nav_survey_sweep, gvf_survey, last_x, last_y, nav_approaching_xy(), nav_init_stage(), nav_survey_shift, NavCourseCloseTo, NavVerticalAltitudeMode, NavVerticalAutoThrottleMode, gvf_SurveyPolyAdv::psa_altitude, gvf_SurveyPolyAdv::psa_min_rad, gvf_SurveyPolyAdv::psa_shot_dist, gvf_SurveyPolyAdv::psa_sweep_width, gvf_SurveyPolyAdv::rad_vec, gvf_SurveyPolyAdv::ret_end, gvf_SurveyPolyAdv::ret_start, gvf_SurveyPolyAdv::return_angle, gvf_SurveyPolyAdv::seg_center1, gvf_SurveyPolyAdv::seg_center2, gvf_SurveyPolyAdv::seg_end, gvf_SurveyPolyAdv::seg_start, gvf_SurveyPolyAdv::segment_angle, gvf_SurveyPolyAdv::stage, stateGetPositionUtm_f(), gvf_SurveyPolyAdv::sweep_vec, VECT2_DIFF, VECT2_SUM, FloatVect2::x, and FloatVect2::y.
void gvf_nav_survey_polygon_setup (uint8_t first_wp, uint8_t size, float angle, float sweep_width, float shot_dist, float min_rad, float altitude)
initializes the variables needed for the survey to start
Parameters
first_wp the first Waypoint of the polygon
size the number of points that make up the polygon
angle angle in which to do the flyovers
sweep_width distance between the sweeps
shot_dist distance between the shots
min_rad minimal radius when navigating
altitude the altitude that must be reached before the flyover starts
Definition at line 139 of file nav_survey_polygon_gvf.c.
References altitude, gvf_SurveyPolyAdv::dir_vec, gvf_SurveyPolyAdv::entry_center, FLOAT_VECT2_NORMALIZE, gENTRY, gERR, gvf_get_two_intersects(), gvf_nav_survey_sweep, gvf_survey, NavVerticalAltitudeMode, NavVerticalAutoThrottleMode, gvf_SurveyPolyAdv::poly_count, gvf_SurveyPolyAdv::poly_first, gvf_SurveyPolyAdv::psa_altitude, gvf_SurveyPolyAdv::psa_min_rad, gvf_SurveyPolyAdv::psa_shot_dist, gvf_SurveyPolyAdv::psa_sweep_width, gvf_SurveyPolyAdv::rad_vec, gvf_SurveyPolyAdv::return_angle, gvf_SurveyPolyAdv::seg_end, gvf_SurveyPolyAdv::seg_start, gvf_SurveyPolyAdv::segment_angle, gvf_SurveyPolyAdv::stage, gvf_SurveyPolyAdv::sweep_vec, VECT2_COPY, VECT2_DIFF, VECT2_SMUL, VECT2_SUM, waypoints, point::x, FloatVect2::x, point::y, and FloatVect2::y.
Variable Documentation
float gvf_nav_survey_sweep = 100.f
Definition at line 42 of file nav_survey_polygon_gvf.c.
Referenced by gvf_nav_survey_polygon_run(), and gvf_nav_survey_polygon_setup().
struct gvf_SurveyPolyAdv gvf_survey
Definition at line 44 of file nav_survey_polygon_gvf.c.
Referenced by gvf_get_two_intersects(), gvf_nav_survey_polygon_run(), and gvf_nav_survey_polygon_setup().