Paparazzi UAS: sw/airborne/modules/nav/nav_flower.c File Reference
nav_flower.c File Reference
from OSAM advanced navigation routines
#include "modules/nav/nav_flower.h"
#include "firmwares/fixedwing/nav.h"
#include "state.h"
#include "autopilot.h"
#include "generated/flight_plan.h"
Enumerations
enum FlowerStatus { Outside, FlowerLine, Circle }
Makes a flower pattern.
Functions
void nav_flower_init (void)
void nav_flower_setup (uint8_t CenterWP, uint8_t EdgeWP)
bool nav_flower_run (void)
Variables
static enum FlowerStatus CFlowerStatus
static float CircleX
static float CircleY
static float Fly2X
static float Fly2Y
static float FlyFromX
static float FlyFromY
static float TransCurrentX
static float TransCurrentY
static float EdgeCurrentX
static float EdgeCurrentY
static float DistanceFromCenter
static float FlowerTheta
static float Flowerradius
static uint8_t Center
static uint8_t Edge
Detailed Description
from OSAM advanced navigation routines
Definition in file nav_flower.c.
Enumeration Type Documentation
enum FlowerStatus
Makes a flower pattern.
CenterWP is the center of the flower. The Navigation Height is taken from this waypoint. EdgeWP defines the radius of the flower (distance from CenterWP to EdgeWP)
Enumerator
Outside
FlowerLine
Circle
Definition at line 67 of file nav_flower.c.
Function Documentation
void nav_flower_init (void)
Definition at line 53 of file nav_flower.c.
References mission_register().
bool nav_flower_run (void)
Definition at line 115 of file nav_flower.c.
References Circle, FlowerLine, Flowerradius, nav_circle_XY(), nav_init_stage(), nav_radius, nav_route_xy(), NavVerticalAltitudeMode, NavVerticalAutoThrottleMode, Outside, stateGetPositionEnu_f(), waypoints, WaypointX, WaypointY, EnuCoor_f::x, and EnuCoor_f::y.
void nav_flower_setup (uint8_t CenterWP, uint8_t EdgeWP)
Definition at line 85 of file nav_flower.c.
References FlowerLine, Outside, stateGetPositionEnu_f(), WaypointX, WaypointY, EnuCoor_f::x, and EnuCoor_f::y.
Variable Documentation
uint8_t Center static
Definition at line 82 of file nav_flower.c.
enum FlowerStatus CFlowerStatus static
Definition at line 68 of file nav_flower.c.
float CircleX static
Definition at line 69 of file nav_flower.c.
float CircleY static
Definition at line 70 of file nav_flower.c.
float DistanceFromCenter static
Definition at line 79 of file nav_flower.c.
uint8_t Edge static
Definition at line 83 of file nav_flower.c.
float EdgeCurrentX static
Definition at line 77 of file nav_flower.c.
float EdgeCurrentY static
Definition at line 78 of file nav_flower.c.
float Flowerradius static
Definition at line 81 of file nav_flower.c.
Referenced by nav_flower_run().
float FlowerTheta static
Definition at line 80 of file nav_flower.c.
float Fly2X static
Definition at line 71 of file nav_flower.c.
float Fly2Y static
Definition at line 72 of file nav_flower.c.
float FlyFromX static
Definition at line 73 of file nav_flower.c.
float FlyFromY static
Definition at line 74 of file nav_flower.c.
float TransCurrentX static
Definition at line 75 of file nav_flower.c.
float TransCurrentY static
Definition at line 76 of file nav_flower.c.