Paparazzi UAS: sw/simulator/nps/nps_sensor_gps.h File Reference
nps_sensor_gps.h File Reference
#include <glib.h>
#include "math/pprz_algebra.h"
#include "math/pprz_algebra_double.h"
#include "math/pprz_algebra_float.h"
#include "math/pprz_geodetic_double.h"
#include "std.h"
Data Structures
struct NpsSensorGps
Functions
void nps_sensor_gps_init (struct NpsSensorGps *gps, double time)
void nps_sensor_gps_run_step (struct NpsSensorGps *gps, double time)
Data Structure Documentation
struct NpsSensorGps
Definition at line 13 of file nps_sensor_gps.h.
Data Fields
bool data_available
struct EcefCoor_d ecef_pos
struct EcefCoor_d ecef_vel
double hmsl
GSList * hmsl_history
GSList * lla_history
struct LlaCoor_d lla_pos
double next_update
struct DoubleVect3 pos_bias_initial
struct DoubleVect3 pos_bias_random_walk_std_dev
struct DoubleVect3 pos_bias_random_walk_value
GSList * pos_history
double pos_latency
struct DoubleVect3 pos_noise_std_dev
GSList * speed_history
double speed_latency
struct DoubleVect3 speed_noise_std_dev
Function Documentation
void nps_sensor_gps_init (struct NpsSensorGps * gps, double time)
Definition at line 10 of file nps_sensor_gps.c.
References NpsSensorGps::data_available, NpsSensorGps::ecef_pos, NpsSensorGps::ecef_vel, FALSE, FLOAT_VECT3_ZERO, NpsSensorGps::hmsl, NpsSensorGps::next_update, NpsSensorGps::pos_bias_initial, NpsSensorGps::pos_bias_random_walk_std_dev, NpsSensorGps::pos_bias_random_walk_value, NpsSensorGps::pos_latency, NpsSensorGps::pos_noise_std_dev, NpsSensorGps::speed_latency, NpsSensorGps::speed_noise_std_dev, and VECT3_ASSIGN.
Referenced by nps_sensors_init().
void nps_sensor_gps_run_step (struct NpsSensorGps * gps, double time)
Definition at line 39 of file nps_sensor_gps.c.
References NpsSensorGps::data_available, double_vect3_add_gaussian_noise(), double_vect3_update_random_walk(), NpsFdm::ecef_ecef_vel, NpsSensorGps::ecef_pos, NpsFdm::ecef_pos, NpsSensorGps::ecef_vel, fdm, NpsSensorGps::hmsl, NpsFdm::hmsl, NpsSensorGps::hmsl_history, NpsSensorGps::lla_history, lla_of_ecef_d(), NpsSensorGps::lla_pos, NpsSensorGps::next_update, NpsSensorGps::pos_bias_initial, NpsSensorGps::pos_bias_random_walk_std_dev, NpsSensorGps::pos_bias_random_walk_value, NpsSensorGps::pos_history, NpsSensorGps::pos_latency, NpsSensorGps::pos_noise_std_dev, NpsSensorGps::speed_history, NpsSensorGps::speed_latency, NpsSensorGps::speed_noise_std_dev, TRUE, UpdateSensorLatency(), UpdateSensorLatency_Single(), VECT3_ADD, and VECT3_COPY.
Referenced by nps_sensors_run_step().