Paparazzi UAS: sw/simulator/nps/nps_sensor_aoa.c File Reference
nps_sensor_aoa.c File Reference
Simulated Angle of Attack of the Wind for NPS simulator.
#include "nps_sensor_aoa.h"
#include "generated/airframe.h"
#include "std.h"
#include "nps_fdm.h"
#include "nps_random.h"
#include <NPS_SENSORS_PARAMS>
Macros
#define NPS_AOA_DT 0.01
10Hz default
#define NPS_AOA_NOISE_STD_DEV 0.001
standard deviation in radian (default 0.001 rad)
#define NPS_AOA_OFFSET 0
Functions
void nps_sensor_aoa_init (struct NpsSensorAngleOfAttack *aoa, double time)
void nps_sensor_aoa_run_step (struct NpsSensorAngleOfAttack *aoa, double time)
Detailed Description
Simulated Angle of Attack of the Wind for NPS simulator.
Definition in file nps_sensor_aoa.c.
Macro Definition Documentation
#define NPS_AOA_DT 0.01
10Hz default
Definition at line 39 of file nps_sensor_aoa.c.
Referenced by nps_sensor_aoa_run_step().
#define NPS_AOA_NOISE_STD_DEV 0.001
standard deviation in radian (default 0.001 rad)
Definition at line 44 of file nps_sensor_aoa.c.
Referenced by nps_sensor_aoa_init().
#define NPS_AOA_OFFSET 0
Definition at line 48 of file nps_sensor_aoa.c.
Referenced by nps_sensor_aoa_init().
Function Documentation
void nps_sensor_aoa_init (struct NpsSensorAngleOfAttack * aoa, double time)
Definition at line 52 of file nps_sensor_aoa.c.
References NpsSensorAngleOfAttack::data_available, FALSE, NpsSensorAngleOfAttack::next_update, NpsSensorAngleOfAttack::noise_std_dev, NPS_AOA_NOISE_STD_DEV, NPS_AOA_OFFSET, NpsSensorAngleOfAttack::offset, and NpsSensorAngleOfAttack::value.
Referenced by nps_sensors_init().
void nps_sensor_aoa_run_step (struct NpsSensorAngleOfAttack * aoa, double time)
Definition at line 62 of file nps_sensor_aoa.c.
References NpsFdm::aoa, NpsSensorAngleOfAttack::data_available, fdm, get_gaussian_noise(), NpsSensorAngleOfAttack::next_update, NpsSensorAngleOfAttack::noise_std_dev, NPS_AOA_DT, NpsSensorAngleOfAttack::offset, TRUE, and NpsSensorAngleOfAttack::value.
Referenced by nps_sensors_run_step().