Paparazzi UAS: sw/simulator/nps/nps_autopilot_fixedwing.c File Reference
nps_autopilot_fixedwing.c File Reference
#include "nps_autopilot.h"
#include "nps_sensors.h"
#include "nps_radio_control.h"
#include "nps_electrical.h"
#include "nps_fdm.h"
#include "subsystems/radio_control.h"
#include "subsystems/imu.h"
#include "mcu_periph/sys_time.h"
#include "state.h"
#include "subsystems/commands.h"
#include "subsystems/abi.h"
#include "autopilot.h"
#include "subsystems/datalink/datalink.h"
#include <stdio.h>
#include "subsystems/gps.h"
Macros
#define Fbw(f)
#define Ap(f)
#define NPS_BYPASS_AHRS FALSE
#define NPS_BYPASS_INS FALSE
Functions
void nps_autopilot_init (enum NpsRadioControlType type_rc, int num_rc_script, char *rc_dev)
void nps_autopilot_run_systime_step (void)
void nps_autopilot_run_step (double time)
void sim_overwrite_ahrs (void)
void sim_overwrite_ins (void)
Variables
struct NpsAutopilot nps_autopilot
bool nps_bypass_ahrs
bool nps_bypass_ins
Macro Definition Documentation
#define Ap (f)
Definition at line 36 of file nps_autopilot_fixedwing.c.
Referenced by nps_autopilot_init(), and nps_autopilot_run_step().
#define Fbw (f)
Definition at line 29 of file nps_autopilot_fixedwing.c.
Referenced by nps_autopilot_init(), and nps_autopilot_run_step().
#define NPS_BYPASS_AHRS FALSE
Definition at line 68 of file nps_autopilot_fixedwing.c.
Referenced by nps_autopilot_init().
#define NPS_BYPASS_INS FALSE
Definition at line 72 of file nps_autopilot_fixedwing.c.
Referenced by nps_autopilot_init().
Function Documentation
void nps_autopilot_init (enum NpsRadioControlType type_rc, int num_rc_script, char * rc_dev)
Definition at line 80 of file nps_autopilot_fixedwing.c.
References Ap, FALSE, Fbw, init, NpsAutopilot::launch, nps_autopilot, nps_bypass_ahrs, NPS_BYPASS_AHRS, nps_bypass_ins, NPS_BYPASS_INS, nps_electrical_init(), and nps_radio_control_init().
void nps_autopilot_run_step (double time)
Definition at line 106 of file nps_autopilot_fixedwing.c.
References AGL_SONAR_NPS_ID, NpsSensors::airspeed, AIRSPEED_NPS_ID, NpsSensors::aoa, Ap, autopilot, NpsSensors::baro, BARO_SIM_SENDER_ID, commands, NpsAutopilot::commands, DefaultChannel, DefaultDevice, Fbw, foo, get_sys_time_usec(), gps_feed_value(), handle_periodic_tasks(), imu_feed_gyro_accel(), imu_feed_mag(), INCIDENCE_NPS_ID, pprz_autopilot::kill_throttle, NpsAutopilot::launch, pprz_autopilot::launch, MAX_PPRZ, nps_autopilot, nps_bypass_ahrs, nps_bypass_ins, NPS_COMMANDS_NB, nps_electrical_run_step(), nps_radio_control_available(), nps_sensors_airspeed_available(), nps_sensors_aoa_available(), nps_sensors_baro_available(), nps_sensors_gps_available(), nps_sensors_gyro_available(), nps_sensors_mag_available(), nps_sensors_sideslip_available(), nps_sensors_sonar_available(), nps_sensors_temperature_available(), PRINT_CONFIG_MSG(), sensors, NpsSensors::sideslip, sim_overwrite_ahrs(), sim_overwrite_ins(), NpsSensors::sonar, NpsSensors::temp, NpsSensorTemperature::value, NpsSensorBaro::value, NpsSensorSideSlip::value, NpsSensorAngleOfAttack::value, NpsSensorAirspeed::value, and NpsSensorSonar::value.
void nps_autopilot_run_systime_step (void)
Definition at line 98 of file nps_autopilot_fixedwing.c.
References sys_tick_handler().
void sim_overwrite_ahrs (void)
Definition at line 255 of file nps_autopilot_fixedwing.c.
References NpsFdm::body_ecef_rotvel, fdm, NpsFdm::ltp_to_body_quat, QUAT_COPY, RATES_COPY, stateSetBodyRates_f(), and stateSetNedToBodyQuat_f().
Referenced by nps_autopilot_run_step().
void sim_overwrite_ins (void)
Definition at line 268 of file nps_autopilot_fixedwing.c.
References fdm, LLA_COPY, NpsFdm::lla_pos, LlaCoor_f::lon, NpsFdm::ltpprz_ecef_accel, NpsFdm::ltpprz_ecef_vel, NpsFdm::ltpprz_pos, State::ned_initialized_f, State::ned_initialized_i, state, stateSetAccelNed_f(), stateSetPositionNed_f(), stateSetPositionUtm_f(), stateSetSpeedNed_f(), State::utm_initialized_f, utm_of_lla_f(), VECT3_COPY, and UtmCoor_f::zone.
Referenced by nps_autopilot_run_step().
Variable Documentation
struct NpsAutopilot nps_autopilot
Definition at line 63 of file nps_autopilot_fixedwing.c.
Referenced by nps_autopilot_init(), and nps_autopilot_run_step().
bool nps_bypass_ahrs
Definition at line 64 of file nps_autopilot_fixedwing.c.
Referenced by nps_autopilot_init(), and nps_autopilot_run_step().
bool nps_bypass_ins
Definition at line 65 of file nps_autopilot_fixedwing.c.
Referenced by nps_autopilot_init(), and nps_autopilot_run_step().