Paparazzi UAS: sw/simulator/nps/nps_autopilot_rotorcraft.c File Reference
nps_autopilot_rotorcraft.c File Reference
#include "nps_autopilot.h"
#include "firmwares/rotorcraft/main.h"
#include "nps_sensors.h"
#include "nps_radio_control.h"
#include "nps_electrical.h"
#include "nps_fdm.h"
#include "subsystems/radio_control.h"
#include "subsystems/imu.h"
#include "mcu_periph/sys_time.h"
#include "state.h"
#include "subsystems/ahrs.h"
#include "subsystems/ins.h"
#include "math/pprz_algebra.h"
#include "subsystems/actuators/motor_mixing.h"
#include "subsystems/abi.h"
#include "pprzlink/messages.h"
#include "subsystems/datalink/downlink.h"
#include "subsystems/datalink/datalink.h"
#include "subsystems/actuators.h"
#include <stdio.h>
#include "subsystems/gps.h"
Macros
#define NPS_BYPASS_AHRS FALSE
#define NPS_BYPASS_INS FALSE
Functions
void nps_autopilot_init (enum NpsRadioControlType type_rc, int num_rc_script, char *rc_dev)
void nps_autopilot_run_systime_step (void)
void nps_autopilot_run_step (double time)
void sim_overwrite_ahrs (void)
void sim_overwrite_ins (void)
Variables
struct NpsAutopilot nps_autopilot
bool nps_bypass_ahrs
bool nps_bypass_ins
Macro Definition Documentation
#define NPS_BYPASS_AHRS FALSE
Definition at line 60 of file nps_autopilot_rotorcraft.c.
Referenced by nps_autopilot_init().
#define NPS_BYPASS_INS FALSE
Definition at line 64 of file nps_autopilot_rotorcraft.c.
Referenced by nps_autopilot_init().
Function Documentation
void nps_autopilot_init (enum NpsRadioControlType type_rc, int num_rc_script, char * rc_dev)
Definition at line 71 of file nps_autopilot_rotorcraft.c.
References NpsAutopilot::launch, main_init(), nps_autopilot, nps_bypass_ahrs, NPS_BYPASS_AHRS, nps_bypass_ins, NPS_BYPASS_INS, nps_electrical_init(), nps_radio_control_init(), and TRUE.
Referenced by nps_radio_and_autopilot_init().
void nps_autopilot_run_step (double time)
Definition at line 93 of file nps_autopilot_rotorcraft.c.
References AGL_SONAR_NPS_ID, NpsSensors::airspeed, autopilot_get_motors_on(), NpsSensors::baro, BARO_SIM_SENDER_ID, MotorMixing::commands, NpsAutopilot::commands, DefaultChannel, DefaultDevice, foo, get_sys_time_usec(), gps_feed_value(), handle_periodic_tasks(), imu_feed_gyro_accel(), imu_feed_mag(), main_event(), MAX_PPRZ, motor_mixing, nps_autopilot, nps_bypass_ahrs, nps_bypass_ins, NPS_COMMANDS_NB, nps_electrical_run_step(), nps_radio_control_available(), nps_sensors_airspeed_available(), nps_sensors_baro_available(), nps_sensors_gps_available(), nps_sensors_gyro_available(), nps_sensors_mag_available(), nps_sensors_sonar_available(), nps_sensors_temperature_available(), sensors, sim_overwrite_ahrs(), sim_overwrite_ins(), NpsSensors::sonar, stateSetAirspeed_f(), NpsSensors::temp, NpsSensorBaro::value, NpsSensorTemperature::value, NpsSensorAirspeed::value, and NpsSensorSonar::value.
Referenced by nps_main_run_sim_step().
void nps_autopilot_run_systime_step (void)
Definition at line 85 of file nps_autopilot_rotorcraft.c.
References sys_tick_handler().
Referenced by nps_main_run_sim_step().
void sim_overwrite_ahrs (void)
Definition at line 178 of file nps_autopilot_rotorcraft.c.
References NpsFdm::body_ecef_rotvel, fdm, NpsFdm::ltp_to_body_quat, QUAT_COPY, RATES_COPY, stateSetBodyRates_f(), and stateSetNedToBodyQuat_f().
Referenced by nps_autopilot_run_step().
void sim_overwrite_ins (void)
Definition at line 191 of file nps_autopilot_rotorcraft.c.
References fdm, NpsFdm::ltpprz_ecef_accel, NpsFdm::ltpprz_ecef_vel, NpsFdm::ltpprz_pos, stateSetAccelNed_f(), stateSetPositionNed_f(), stateSetSpeedNed_f(), and VECT3_COPY.
Referenced by ins_ekf2_update(), ins_ned_to_state(), and nps_autopilot_run_step().
Variable Documentation
struct NpsAutopilot nps_autopilot
Definition at line 55 of file nps_autopilot_rotorcraft.c.
Referenced by nps_ap_data_loop(), nps_autopilot_init(), nps_autopilot_run_step(), nps_main_run_sim_step(), and nps_update_launch_from_dl().
bool nps_bypass_ahrs
Definition at line 56 of file nps_autopilot_rotorcraft.c.
Referenced by nps_autopilot_init(), and nps_autopilot_run_step().
bool nps_bypass_ins
Definition at line 57 of file nps_autopilot_rotorcraft.c.
Referenced by ins_ekf2_update(), ins_ned_to_state(), nps_autopilot_init(), and nps_autopilot_run_step().