Paparazzi UAS: sw/simulator/nps/nps_ins.h File Reference
nps_ins.h File Reference
#include "std.h"
#include "nps_fdm.h"
Macros
#define INS_FREQUENCY PERIODIC_FREQUENCY
Functions
void nps_ins_init (void)
void nps_ins_fetch_data (struct NpsFdm *fdm_ins)
Fetch data from FDM and store them into vectornav packet NOTE: some noise is being added, see Vectornav specifications for details about the precision: http://www.vectornav.com/products/vn-200/specifications.
uint16_t nps_ins_fill_buffer (void)
Variables
uint8_t * ins_buffer
Macro Definition Documentation
#define INS_FREQUENCY PERIODIC_FREQUENCY
Definition at line 34 of file nps_ins.h.
Referenced by nps_ins_data_loop().
Function Documentation
void nps_ins_fetch_data (struct NpsFdm * fdm_ins)
Fetch data from FDM and store them into vectornav packet NOTE: some noise is being added, see Vectornav specifications for details about the precision: http://www.vectornav.com/products/vn-200/specifications.
Definition at line 125 of file nps_ins_vectornav.c.
References VectornavData::Accel, LlaCoor_d::alt, VectornavData::AngularRate, NpsFdm::body_accel, NpsFdm::body_ecef_accel, NpsFdm::body_ecef_rotvel, VectornavData::Fix, NpsSensors::gps, VectornavData::InsStatus, LlaCoor_d::lat, VectornavData::LinearAccelBody, NpsSensorGps::lla_pos, LlaCoor_d::lon, NpsFdm::ltp_ecef_vel, NpsFdm::ltp_to_body_eulers, VectornavData::NumSats, DoubleRates::p, DoubleEulers::phi, VectornavData::Position, VectornavData::PosU, DoubleEulers::psi, DoubleRates::q, DoubleRates::r, sensors, DoubleEulers::theta, NpsFdm::time, VectornavData::TimeStartup, VectornavData::Tow, VectornavData::VelBody, VectornavData::Velocity, VectornavData::VelU, vn_data, vn_get_time_of_week(), DoubleVect3::x, NedCoor_d::x, DoubleVect3::y, NedCoor_d::y, VectornavData::YawPitchRoll, VectornavData::YprU, DoubleVect3::z, and NedCoor_d::z.
Referenced by nps_ins_data_loop().
uint16_t nps_ins_fill_buffer (void)
Definition at line 202 of file nps_ins_vectornav.c.
References VectornavData::Accel, VectornavData::AngularRate, VectornavData::Fix, idx, VectornavData::InsStatus, VectornavData::LinearAccelBody, VectornavData::NumSats, VectornavData::Position, VectornavData::PosU, VectornavData::TimeStartup, VectornavData::Tow, VectornavData::VelBody, VectornavData::Velocity, VectornavData::VelU, vn_buffer, vn_calculate_crc(), vn_data, VN_DATA_START, VN_GROUP_FIELD_1, VN_GROUP_FIELD_2, VN_GROUP_FIELD_3, VN_GROUP_FIELD_4, VN_OUTPUT_GROUP, VN_SYNC, VectornavData::YawPitchRoll, and VectornavData::YprU.
Referenced by nps_ins_data_loop().
void nps_ins_init (void)
Definition at line 94 of file nps_ins_vectornav.c.
References ins_buffer, and vn_buffer.
Referenced by nps_ins_data_loop().
Variable Documentation
uint8_t* ins_buffer
Definition at line 48 of file nps_ins_vectornav.c.
Referenced by nps_ins_data_loop(), and nps_ins_init().