Paparazzi UAS: sw/simulator/nps/nps_sensor_sideslip.c File Reference
nps_sensor_sideslip.c File Reference
Simulated Angle of Attack of the Wind for NPS simulator.
#include "nps_sensor_sideslip.h"
#include "generated/airframe.h"
#include <math.h>
#include "std.h"
#include "nps_fdm.h"
#include "nps_random.h"
#include <NPS_SENSORS_PARAMS>
Macros
#define NPS_SIDESLIP_DT 0.01
10Hz default
#define NPS_SIDESLIP_NOISE_STD_DEV 0.001
standard deviation in radian (default 0.001 rad)
#define NPS_SIDESLIP_OFFSET 0
Functions
void nps_sensor_sideslip_init (struct NpsSensorSideSlip *sideslip, double time)
void nps_sensor_sideslip_run_step (struct NpsSensorSideSlip *sideslip, double time)
Detailed Description
Simulated Angle of Attack of the Wind for NPS simulator.
Definition in file nps_sensor_sideslip.c.
Macro Definition Documentation
#define NPS_SIDESLIP_DT 0.01
10Hz default
Definition at line 40 of file nps_sensor_sideslip.c.
Referenced by nps_sensor_sideslip_run_step().
#define NPS_SIDESLIP_NOISE_STD_DEV 0.001
standard deviation in radian (default 0.001 rad)
Definition at line 45 of file nps_sensor_sideslip.c.
Referenced by nps_sensor_sideslip_init().
#define NPS_SIDESLIP_OFFSET 0
Definition at line 49 of file nps_sensor_sideslip.c.
Referenced by nps_sensor_sideslip_init().
Function Documentation
void nps_sensor_sideslip_init (struct NpsSensorSideSlip * sideslip, double time)
Definition at line 53 of file nps_sensor_sideslip.c.
References NpsSensorSideSlip::data_available, FALSE, NpsSensorSideSlip::next_update, NpsSensorSideSlip::noise_std_dev, NPS_SIDESLIP_NOISE_STD_DEV, NPS_SIDESLIP_OFFSET, NpsSensorSideSlip::offset, and NpsSensorSideSlip::value.
Referenced by nps_sensors_init().
void nps_sensor_sideslip_run_step (struct NpsSensorSideSlip * sideslip, double time)
Definition at line 63 of file nps_sensor_sideslip.c.
References NpsSensorSideSlip::data_available, fdm, get_gaussian_noise(), NpsSensorSideSlip::next_update, NpsSensorSideSlip::noise_std_dev, NPS_SIDESLIP_DT, NpsSensorSideSlip::offset, NpsFdm::sideslip, TRUE, and NpsSensorSideSlip::value.
Referenced by nps_sensors_run_step().