Paparazzi UAS: sw/airborne/mcu_periph/pipe.c File Reference
pipe.c File Reference
arch independent PIPE API
#include "mcu_periph/pipe.h"
#include <string.h>
Functions
void pipe_periph_init (struct pipe_periph *p, char *read_name, char *write_name)
Initialize the PIPE peripheral.
int WEAK pipe_check_free_space (struct pipe_periph *p, long *fd, uint16_t len)
Check if there is enough free space in the transmit buffer.
void WEAK pipe_put_byte (struct pipe_periph *p, long fd, uint8_t data)
Add one data byte to the tx buffer.
void WEAK pipe_put_buffer (struct pipe_periph *p, long fd, const uint8_t *data, uint16_t len)
Detailed Description
arch independent PIPE API
Definition in file pipe.c.
Function Documentation
int WEAK pipe_check_free_space (struct pipe_periph * p, long * fd, uint16_t len)
Check if there is enough free space in the transmit buffer.
Parameters
p pointer to PIPE peripheral
len how many bytes of free space to check for
Returns
number of bytes available or 0 if not enough
Definition at line 94 of file pipe.c.
References PIPE_TX_BUFFER_SIZE, and pipe_periph::tx_insert_idx.
Referenced by pipe_periph_init().
void pipe_periph_init (struct pipe_periph * p, char * read_name, char * write_name)
Initialize the PIPE peripheral.
Definition at line 72 of file pipe.c.
References pipe_periph::device, pipe_arch_periph_init(), pipe_char_available(), pipe_check_free_space(), pipe_getch(), pipe_put_buffer(), pipe_put_byte(), pipe_send_message(), pipe_periph::rx_extract_idx, pipe_periph::rx_insert_idx, and pipe_periph::tx_insert_idx.
void WEAK pipe_put_buffer (struct pipe_periph * p, long fd, const uint8_t * data, uint16_t len)
Definition at line 115 of file pipe.c.
References PIPE_TX_BUFFER_SIZE, pipe_periph::tx_buf, and pipe_periph::tx_insert_idx.
Referenced by pipe_periph_init().
void WEAK pipe_put_byte (struct pipe_periph * p, long fd, uint8_t data)
Add one data byte to the tx buffer.
Parameters
p pointer to PIPE peripheral
data byte to add to tx buffer
Definition at line 105 of file pipe.c.
References PIPE_TX_BUFFER_SIZE, pipe_periph::tx_buf, and pipe_periph::tx_insert_idx.
Referenced by pipe_periph_init().