Paparazzi UAS: sw/airborne/firmwares/rotorcraft/main.c File Reference
main.c File Reference
Program main function AP + FBW on single MCU AP or FBW on dual MCU None on SITL.
#include "firmwares/rotorcraft/main_ap.h"
#include "mcu_periph/sys_time.h"
#include <stdio.h>
Macros
#define POLLING_PERIOD (500000/PERIODIC_FREQUENCY)
Functions
int main (void)
Detailed Description
Program main function AP + FBW on single MCU AP or FBW on dual MCU None on SITL.
Definition in file main.c.
Macro Definition Documentation
#define POLLING_PERIOD (500000/PERIODIC_FREQUENCY)
Definition at line 39 of file main.c.
Referenced by main().
Function Documentation
int main (void)
Definition at line 42 of file main.c.
References get_sys_time_usec(), handle_periodic_tasks(), main_event(), main_init(), POLLING_PERIOD, and sys_time_usleep().