Paparazzi UAS: sw/airborne/firmwares/rotorcraft/rotorcraft_datalink.c File Reference
rotorcraft_datalink.c File Reference
Handling of messages coming from ground and other A/Cs.
#include "subsystems/datalink/datalink.h"
#include "pprzlink/dl_protocol.h"
#include "autopilot.h"
#include "firmwares/rotorcraft/autopilot_guided.h"
Functions
void firmware_parse_msg (struct link_device *dev, struct transport_tx *trans, uint8_t *buf)
Firmware specfic msg handler.
Detailed Description
Handling of messages coming from ground and other A/Cs.
Definition in file rotorcraft_datalink.c.
Function Documentation
void firmware_parse_msg (struct link_device * dev, struct transport_tx * trans, uint8_t * buf)
Firmware specfic msg handler.
NAV
WIND_INFO
Definition at line 40 of file rotorcraft_datalink.c.
References ac_id, LlaCoor_i::alt, autopilot_guided_update(), LtpDef_i::hmsl, LlaCoor_i::lat, LtpDef_i::lla, LlaCoor_i::lon, nav_goto_block(), State::ned_origin_i, state, stateIsLocalCoordinateValid(), and waypoint_move_lla().