Paparazzi UAS: sw/airborne/firmwares/rotorcraft/main_fbw.c File Reference
main_fbw.c File Reference
Rotorcraft FBW main loop.
#include <inttypes.h>
#include "mcu.h"
#include "led.h"
#include "mcu_periph/sys_time.h"
#include "subsystems/commands.h"
#include "subsystems/actuators.h"
#include "subsystems/electrical.h"
#include "subsystems/radio_control.h"
#include "subsystems/intermcu/intermcu_fbw.h"
#include "firmwares/rotorcraft/main_fbw.h"
#include "firmwares/rotorcraft/autopilot_rc_helpers.h"
#include "generated/modules.h"
Macros
#define MODULES_C
#define And(x, y) ((x) && (y))
#define Or(x, y) ((x) || (y))
#define Min(x, y) (x < y ? x : y)
#define Max(x, y) (x > y ? x : y)
#define LessThan(_x, _y) ((_x) < (_y))
#define MoreThan(_x, _y) ((_x) > (_y))
Functions
void main_init (void)
Main initialization.
void handle_periodic_tasks (void)
void telemetry_periodic (void)
static void fbw_safety_check (void)
void main_periodic (void)
static void fbw_on_rc_frame (void)
Callback when we received an RC frame.
static void fbw_on_ap_command (void)
Callback when receive commands from the AP.
void main_event (void)
Variables
fbw_mode_enum fbw_mode
Fly by wire modes.
bool fbw_motors_on = false
tid_t main_periodic_tid
id for main_periodic() timer
tid_t modules_tid
id for modules_periodic_task() timer
tid_t radio_control_tid
id for radio_control_periodic_task() timer
tid_t electrical_tid
id for electrical_periodic() timer
tid_t telemetry_tid
id for telemetry_periodic() timer
Detailed Description
Rotorcraft FBW main loop.
Definition in file main_fbw.c.
Macro Definition Documentation
#define And (x, y) ((x) && (y))
Definition at line 50 of file main_fbw.c.
#define LessThan (_x, _y) ((_x) < (_y))
Definition at line 54 of file main_fbw.c.
#define Max (x, y) (x > y ? x : y)
Definition at line 53 of file main_fbw.c.
Referenced by airspeed_adc_update(), Drift_correction(), eas_from_dynamic_pressure(), float_mat_exp(), float_mat_norm_li(), formation_flight(), gls_run(), h_ctl_course_loop(), h_ctl_pitch_loop(), h_ctl_roll_loop(), jevois_report(), ms45xx_i2c_event(), mt9f002_calc_resolution(), mt9f002_set_blanking(), mt9f002_set_resolution(), mt9f002_setting_update_resolution(), nav_approaching_xy(), nav_circle(), nav_circle_XY(), nav_eight(), nav_route(), nav_route_xy(), nav_survey_rectangle(), nav_survey_rectangle_init(), nav_survey_rectangle_rotorcraft_run(), nav_survey_rectangle_rotorcraft_setup(), periodic_report_sysmon(), potential_task(), sdp3x_event(), spi_submit(), SpiTransmit(), and tcas_periodic_task_4Hz().
#define Min (x, y) (x < y ? x : y)
Definition at line 52 of file main_fbw.c.
#define MODULES_C
Definition at line 46 of file main_fbw.c.
#define MoreThan (_x, _y) ((_x) > (_y))
Definition at line 55 of file main_fbw.c.
#define Or (x, y) ((x) || (y))
Definition at line 51 of file main_fbw.c.
Function Documentation
static void fbw_on_ap_command (void) static
Callback when receive commands from the AP.
Definition at line 277 of file main_fbw.c.
References fbw_mode, FBW_MODE_AUTO, intermcu_commands, and SetCommands.
Referenced by main_event().
static void fbw_on_rc_frame (void) static
Callback when we received an RC frame.
Definition at line 231 of file main_fbw.c.
References AP_LOST_FBW_MODE, commands, commands_failsafe, fbw_mode, FBW_MODE_AUTO, FBW_MODE_AUTO_ONLY, FBW_MODE_FAILSAFE, FBW_MODE_MANUAL, fbw_motors_on, intermcu, INTERMCU_LOST, intermcu_on_rc_frame(), MIN_PPRZ, radio_control, RADIO_FBW_MODE, RADIO_KILL_SWITCH, SetCommands, intermcu_t::status, and RadioControl::values.
Referenced by main_event().
static void fbw_safety_check (void) static
Definition at line 139 of file main_fbw.c.
References AP_LOST_FBW_MODE, fbw_mode, FBW_MODE_AUTO, FBW_MODE_FAILSAFE, FBW_MODE_MANUAL, intermcu, INTERMCU_LOST, radio_control, RC_LOST_FBW_MODE, RC_LOST_IN_AUTO_FBW_MODE, RC_REALLY_LOST, RadioControl::status, and intermcu_t::status.
Referenced by main_periodic().
void handle_periodic_tasks (void)
Definition at line 110 of file main_fbw.c.
References electrical_periodic(), electrical_tid, main_periodic(), main_periodic_tid, modules_tid, radio_control_periodic_task(), radio_control_tid, sys_time_check_and_ack_timer(), telemetry_periodic(), and telemetry_tid.
void main_event (void) inline
Definition at line 285 of file main_fbw.c.
References fbw_on_ap_command(), fbw_on_rc_frame(), InterMcuEvent(), mcu_event(), and RadioControlEvent.
void main_init (void) inline
Main initialization.
Definition at line 75 of file main_fbw.c.
References electrical_init(), fbw_mode, FBW_MODE_FAILSAFE, intermcu_init(), mcu_init(), mcu_int_enable, motor_mixing_init(), radio_control_init(), and sys_time_register_timer().
void main_periodic (void) inline
Definition at line 175 of file main_fbw.c.
References autopilot_get_mode(), autopilot_motors_on, commands, commands_failsafe, fbw_mode, FBW_MODE_AUTO, FBW_MODE_FAILSAFE, FBW_MODE_MANUAL, fbw_motors_on, fbw_safety_check(), intermcu, intermcu_periodic(), LED_OFF, LED_ON, LED_PERIODIC, LED_TOGGLE, PPRZ_BAUD, and SetCommands.
Referenced by handle_periodic_tasks().
void telemetry_periodic (void)
Definition at line 129 of file main_fbw.c.
References fbw_mode, and intermcu_send_status().
Referenced by handle_periodic_tasks().
Variable Documentation
tid_t electrical_tid
id for electrical_periodic() timer
Definition at line 70 of file main_fbw.c.
fbw_mode_enum fbw_mode
Fly by wire modes.
Definition at line 59 of file main_fbw.c.
Referenced by telemetry_intermcu_event().
bool fbw_motors_on = false
Definition at line 60 of file main_fbw.c.
Referenced by fbw_on_rc_frame(), and main_periodic().
tid_t main_periodic_tid
id for main_periodic() timer
Definition at line 67 of file main_fbw.c.
Referenced by handle_periodic_tasks().
tid_t modules_tid
id for modules_periodic_task() timer
Definition at line 68 of file main_fbw.c.
Referenced by handle_periodic_tasks().
tid_t radio_control_tid
id for radio_control_periodic_task() timer
Definition at line 69 of file main_fbw.c.
Referenced by handle_periodic_tasks().
tid_t telemetry_tid
id for telemetry_periodic() timer
Definition at line 71 of file main_fbw.c.
Referenced by handle_periodic_tasks().