Paparazzi UAS: sw/airborne/modules/computer_vision/lib/encoding/rtp.h File Reference
rtp.h File Reference
Encodes a video stream with RTP Format 26 (Motion JPEG)
#include "std.h"
#include "lib/vision/image.h"
#include "udp_socket.h"
Functions
void rtp_frame_send (struct UdpSocket *udp, struct image_t *img, uint8_t format_code, uint8_t quality_code, uint8_t has_dri_header, float average_frame_rate, uint16_t *packet_number, uint32_t *rtp_time_counter)
Send an RTP frame.
void rtp_frame_test (struct UdpSocket *udp)
Send a test RTP frame.
Detailed Description
Encodes a video stream with RTP Format 26 (Motion JPEG)
Definition in file rtp.h.
Function Documentation
void rtp_frame_send (struct UdpSocket * udp, struct image_t * img, uint8_t format_code, uint8_t quality_code, uint8_t has_dri_header, float average_frame_rate, uint16_t * packet_number, uint32_t * rtp_time_counter)
Send an RTP frame.
Parameters
[in] *udp The UDP connection to send the frame over
[in] *img The image to send over the RTP connection
[in] format_code 0 for YUV422 and 1 for YUV421
[in] quality_code The JPEG encoding quality
[in] has_dri_header Whether we have an DRI header or not
[in] frame_time Time image was taken in usec (if set to 0 or less it is calculated)
[out] packet_number The frame number of the rtp stream
[out] rtp_time_counter The frame time counter of the rtp stream
Definition at line 127 of file rtp.c.
References image_t::buf, image_t::buf_size, image_t::h, MAX_PACKET_SIZE, offset, rtp_packet_send(), and image_t::w.
Referenced by viewvideo_function().
void rtp_frame_test (struct UdpSocket * udp)
Send a test RTP frame.
Parameters
[in] *udp The udp connection to send the test frame over
Definition at line 95 of file rtp.c.
References JpegScanDataCh2A, JpegScanDataCh2B, KJpegCh2ScanDataLen, and rtp_packet_send().