Paparazzi UAS: sw/airborne/modules/sensors/trigger_ext.h File Reference
trigger_ext.h File Reference
Measure external trigger pulse at PPM input.
Functions
void trigger_ext_init (void)
void trigger_ext_periodic (void)
Detailed Description
Measure external trigger pulse at PPM input.
This measures a trigger pulse length (e.g. duration of a wind turbine rotation) and sends a message with the info.
Definition in file trigger_ext.h.
Function Documentation
void trigger_ext_init (void)
Definition at line 43 of file trigger_ext_hw.c.
References T0CCR, trig_ext_init(), TRIG_EXT_PINSEL, TRIG_EXT_PINSEL_BIT, TRIG_EXT_PINSEL_VAL, TRIGGER_CRF, TRIGGER_CRI, TRIGGER_CRR, and trigger_ext_valid.
void trigger_ext_periodic (void)
Definition at line 46 of file trigger_ext.c.
References ac_id, DefaultChannel, DefaultDevice, delta_t0, gps_tow_from_sys_ticks(), msec_of_sys_time_ticks(), trig_ext_valid, trigger_t0, and TRUE.