Paparazzi UAS: sw/airborne/modules/digital_cam/servo_cam_ctrl.h File Reference
servo_cam_ctrl.h File Reference
Digital Camera Control.
#include "dc.h"
Functions
void servo_cam_ctrl_init (void)
void servo_cam_ctrl_periodic (void)
Detailed Description
Digital Camera Control.
Provides the control of the shutter and the zoom of a digital camera via servos.
Configuration in airframe file (DC_SHUTTER is mandatory, others optional):
 {.xml]
<define name="DC_SHUTTER_SERVO" value="10"/>
<define name="DC_ZOOM_IN_SERVO" value="7"/>
<define name="DC_ZOOM_OUT_SERVO" value="8"/>
<define name="DC_POWER_SERVO" value="9"/>
Provides the required initialization (dc_init()) and periodic process.
Definition in file servo_cam_ctrl.h.
Function Documentation
void servo_cam_ctrl_init (void)
Definition at line 56 of file servo_cam_ctrl.c.
References dc_init(), and dc_timer.
void servo_cam_ctrl_periodic (void)
Definition at line 67 of file servo_cam_ctrl.c.
References dc_periodic(), DC_RELEASE, dc_send_shot_position(), and dc_timer.