Paparazzi UAS: sw/airborne/firmwares/rotorcraft/stabilization/stabilization_attitude_ref_euler_float.c File Reference
stabilization_attitude_ref_euler_float.c File Reference
Rotorcraft attitude reference generation in euler float version.
#include "generated/airframe.h"
#include "firmwares/rotorcraft/stabilization/stabilization_attitude_ref_euler_float.h"
#include "firmwares/rotorcraft/stabilization/stabilization_attitude_ref_defaults.h"
Functions
static void reset_psi_ref (struct AttRefEulerFloat *ref, float psi)
void attitude_ref_euler_float_init (struct AttRefEulerFloat *ref)
void attitude_ref_euler_float_enter (struct AttRefEulerFloat *ref, float psi)
void attitude_ref_euler_float_update (struct AttRefEulerFloat *ref, struct FloatEulers *sp_eulers, float dt)
Detailed Description
Rotorcraft attitude reference generation in euler float version.
Definition in file stabilization_attitude_ref_euler_float.c.
Function Documentation
void attitude_ref_euler_float_enter (struct AttRefEulerFloat * ref, float psi)
Definition at line 62 of file stabilization_attitude_ref_euler_float.c.
References reset_psi_ref().
Referenced by stabilization_attitude_enter().
void attitude_ref_euler_float_init (struct AttRefEulerFloat * ref)
Definition at line 41 of file stabilization_attitude_ref_euler_float.c.
References AttRefEulerFloat::accel, AttRefEulerFloat::euler, FLOAT_EULERS_ZERO, FLOAT_RATES_ZERO, FloatRefSat::max_accel, FloatRefSat::max_rate, AttRefEulerFloat::model, FloatRefModel::omega, FloatRates::p, FloatRates::q, FloatRates::r, AttRefEulerFloat::rate, AttRefEulerFloat::saturation, STABILIZATION_ATTITUDE_REF_MAX_P, STABILIZATION_ATTITUDE_REF_MAX_PDOT, STABILIZATION_ATTITUDE_REF_MAX_Q, STABILIZATION_ATTITUDE_REF_MAX_QDOT, STABILIZATION_ATTITUDE_REF_MAX_R, STABILIZATION_ATTITUDE_REF_MAX_RDOT, and FloatRefModel::zeta.
Referenced by stabilization_attitude_init().
void attitude_ref_euler_float_update (struct AttRefEulerFloat * ref, struct FloatEulers * sp_eulers, float dt)
Definition at line 67 of file stabilization_attitude_ref_euler_float.c.
References AttRefEulerFloat::accel, attitude_ref_float_saturate_naive(), AttRefEulerFloat::euler, EULERS_ADD, EULERS_ASSIGN, EULERS_DIFF, FLOAT_ANGLE_NORMALIZE, AttRefEulerFloat::model, FloatRefModel::omega, FloatRates::p, FloatEulers::phi, FloatEulers::psi, FloatRates::q, FloatRates::r, AttRefEulerFloat::rate, RATES_ADD, RATES_SMUL, AttRefEulerFloat::saturation, FloatEulers::theta, and FloatRefModel::zeta.
Referenced by stabilization_attitude_run().
static void reset_psi_ref (struct AttRefEulerFloat * ref, float psi) inline static
Definition at line 106 of file stabilization_attitude_ref_euler_float.c.
References AttRefEulerFloat::accel, AttRefEulerFloat::euler, FloatEulers::psi, FloatRates::r, and AttRefEulerFloat::rate.
Referenced by attitude_ref_euler_float_enter().