Paparazzi UAS: sw/airborne/firmwares/rotorcraft/stabilization/stabilization_attitude_passthrough.c File Reference
stabilization_attitude_passthrough.c File Reference
passthrough attitude stabilization
#include "state.h"
#include "firmwares/rotorcraft/stabilization.h"
#include "firmwares/rotorcraft/stabilization/stabilization_attitude.h"
#include "firmwares/rotorcraft/stabilization/stabilization_attitude_rc_setpoint.h"
#include "paparazzi.h"
#include "generated/airframe.h"
Macros
#define TRAJ_MAX_BANK (int32_t)ANGLE_BFP_OF_REAL(GUIDANCE_H_MAX_BANK)
Functions
void stabilization_attitude_init (void)
stabilization_attitude_init
void stabilization_attitude_read_rc (bool in_flight, bool in_carefree, bool coordinated_turn)
void stabilization_attitude_enter (void)
void stabilization_attitude_run (bool in_flight)
void stabilization_attitude_set_failsafe_setpoint (void)
void stabilization_attitude_set_rpy_setpoint_i (struct Int32Eulers *rpy)
void stabilization_attitude_set_earth_cmd_i (struct Int32Vect2 *cmd, int32_t heading)
Variables
struct Int32Eulers stab_att_sp_euler
with INT32_ANGLE_FRAC
Detailed Description
passthrough attitude stabilization
This is useful for instance when having an AC that has needs no stabilization because it is already been done by other stabilization software onboard or just does not need it at all.
Definition in file stabilization_attitude_passthrough.c.
Macro Definition Documentation
#define TRAJ_MAX_BANK (int32_t)ANGLE_BFP_OF_REAL(GUIDANCE_H_MAX_BANK)
Definition at line 39 of file stabilization_attitude_passthrough.c.
Referenced by stabilization_attitude_run().
Function Documentation
void stabilization_attitude_enter (void)
Definition at line 55 of file stabilization_attitude_passthrough.c.
void stabilization_attitude_init (void)
stabilization_attitude_init
Initialize the heli indi attitude controller.
Definition at line 44 of file stabilization_attitude_passthrough.c.
References INT_EULERS_ZERO, and stab_att_sp_euler.
void stabilization_attitude_read_rc (bool in_flight, bool in_carefree, bool coordinated_turn)
Definition at line 49 of file stabilization_attitude_passthrough.c.
References stab_att_sp_euler, and stabilization_attitude_read_rc_setpoint_eulers().
void stabilization_attitude_run (bool in_flight)
Definition at line 60 of file stabilization_attitude_passthrough.c.
References INT32_ANGLE_NORMALIZE, MAX_PPRZ, Int32Eulers::phi, Int32Eulers::psi, stab_att_sp_euler, stabilization_cmd, stateGetNedToBodyEulers_i(), Int32Eulers::theta, and TRAJ_MAX_BANK.
void stabilization_attitude_set_earth_cmd_i (struct Int32Vect2 * cmd, int32_t heading)
Definition at line 91 of file stabilization_attitude_passthrough.c.
References heading, INT32_TRIG_FRAC, Int32Eulers::phi, PPRZ_ITRIG_COS, PPRZ_ITRIG_SIN, Int32Eulers::psi, stab_att_sp_euler, stateGetNedToBodyEulers_i(), Int32Eulers::theta, Int32Vect2::x, and Int32Vect2::y.
void stabilization_attitude_set_failsafe_setpoint (void)
Definition at line 79 of file stabilization_attitude_passthrough.c.
References Int32Eulers::phi, Int32Eulers::psi, stab_att_sp_euler, stateGetNedToBodyEulers_i(), and Int32Eulers::theta.
void stabilization_attitude_set_rpy_setpoint_i (struct Int32Eulers * rpy)
Definition at line 86 of file stabilization_attitude_passthrough.c.
References stab_att_sp_euler.
Variable Documentation
struct Int32Eulers stab_att_sp_euler
with INT32_ANGLE_FRAC
Definition at line 41 of file stabilization_attitude_passthrough.c.
Referenced by stabilization_attitude_init(), stabilization_attitude_read_rc(), stabilization_attitude_run(), stabilization_attitude_set_earth_cmd_i(), stabilization_attitude_set_failsafe_setpoint(), and stabilization_attitude_set_rpy_setpoint_i().