Paparazzi UAS: sw/airborne/modules/datalink/bitcraze/syslink.c File Reference
syslink.c File Reference
Syslink protocol for communication with bitcraze/crazyflie NRF mcu.
#include "syslink.h"
Functions
void syslink_parse_init (syslink_parse_state *state)
Init syslink parser.
bool syslink_parse_char (syslink_parse_state *state, uint8_t c, syslink_message_t *msg)
Parse one byte.
void syslink_compute_cksum (syslink_message_t *msg)
Compute syslink checksum.
Variables
const char * syslink_stx = "\xbc\xcf"
Detailed Description
Syslink protocol for communication with bitcraze/crazyflie NRF mcu.
based on PX4 implementation
Definition in file syslink.c.
Function Documentation
void syslink_compute_cksum (syslink_message_t * msg)
Compute syslink checksum.
Parameters
msg pointer to message structure
Definition at line 112 of file syslink.c.
References syslink_message_t::cksum, and syslink_message_t::length.
Referenced by send_message(), and syslink_parse_char().
bool syslink_parse_char (syslink_parse_state * state, uint8_t c, syslink_message_t * msg)
Parse one byte.
Parameters
state pointer to state structure
c next byte to parse
msg pointer to message structure
Returns
true if a full message was parsed
Definition at line 39 of file syslink.c.
References syslink_message_t::cksum, syslink_message_t::data, syslink_parse_state::index, syslink_message_t::length, syslink_parse_state::state, syslink_compute_cksum(), SYSLINK_MAX_DATA_LEN, SYSLINK_STATE_CKSUM, SYSLINK_STATE_DATA, SYSLINK_STATE_LENGTH, SYSLINK_STATE_START, SYSLINK_STATE_TYPE, syslink_stx, and syslink_message_t::type.
Referenced by syslink_dl_event().
void syslink_parse_init (syslink_parse_state * state)
Init syslink parser.
Parameters
state pointer to state structure
Definition at line 33 of file syslink.c.
References syslink_parse_state::index, syslink_parse_state::state, and SYSLINK_STATE_START.
Referenced by syslink_dl_init().
Variable Documentation
const char* syslink_stx = "\xbc\xcf"
Definition at line 31 of file syslink.c.
Referenced by send_message(), and syslink_parse_char().