Paparazzi UAS: sw/airborne/modules/datalink/bitcraze/syslink_dl.h File Reference
syslink_dl.h File Reference
Syslink protocol handling and functionalities.
#include "modules/datalink/bitcraze/syslink.h"
#include "modules/datalink/bitcraze/crtp.h"
#include "pprzlink/pprzlink_device.h"
Data Structures
struct syslink_dl
Macros
#define CRTP_BUF_LEN 16
#define SYSLINK_RX_BUF_LEN 256
Functions
void syslink_dl_init (void)
Init function.
void syslink_dl_periodic (void)
Periodic function.
void syslink_dl_event (void)
Datalink event.
Variables
struct syslink_dl syslink
Detailed Description
Syslink protocol handling and functionalities.
Definition in file syslink_dl.h.
Data Structure Documentation
struct syslink_dl
Definition at line 38 of file syslink_dl.h.
Data Fields
bool charging battery charging
struct link_device device
syslink_message_t msg_rx last received syslink message
crtp_message_t msg_tx[CRTP_BUF_LEN] queued crtp packets to be send
bool powered USB powered.
uint8_t rssi
uint8_t rx_buf[SYSLINK_RX_BUF_LEN] received pprzlink bytes from syslink/crtp
uint8_t rx_extract_idx rx extract index
uint8_t rx_insert_idx rx insert index
syslink_parse_state state syslink parser state
uint8_t tx_extract_idx tx extract index
uint8_t tx_insert_idx tx insert index
Macro Definition Documentation
#define CRTP_BUF_LEN 16
Definition at line 35 of file syslink_dl.h.
Referenced by handle_raw(), syslink_check_free_space(), syslink_dl_init(), and syslink_put_buffer().
#define SYSLINK_RX_BUF_LEN 256
Definition at line 36 of file syslink_dl.h.
Referenced by handle_raw(), syslink_char_available(), and syslink_getch().
Function Documentation
void syslink_dl_event (void)
Datalink event.
Definition at line 413 of file syslink_dl.c.
References handle_new_msg(), syslink_dl::msg_rx, syslink_dl::state, syslink, syslink_parse_char(), uart_char_available(), and uart_getch().
void syslink_dl_init (void)
Init function.
Definition at line 366 of file syslink_dl.c.
References syslink_dl::charging, CRTP_BUF_LEN, CRTP_PORT_PPRZLINK, syslink_dl::device, syslink_dl::msg_tx, syslink_dl::powered, PPRZ_MUTEX_INIT, syslink_dl::rssi, crtp_message_t::size, syslink_dl::state, syslink, syslink_char_available(), syslink_check_free_space(), syslink_getch(), syslink_parse_init(), syslink_put_buffer(), syslink_put_byte(), syslink_send_message(), syslink_dl::tx_extract_idx, and syslink_dl::tx_insert_idx.
void syslink_dl_periodic (void)
Periodic function.
Definition at line 397 of file syslink_dl.c.
References syslink_dl::charging, LED_OFF, LED_ON, LED_TOGGLE, syslink_dl::powered, and syslink.
Variable Documentation
struct syslink_dl syslink
Definition at line 34 of file syslink_dl.c.
Referenced by handle_battery(), handle_radio(), handle_raw(), syslink_dl_event(), syslink_dl_init(), and syslink_dl_periodic().