Paparazzi UAS: sw/airborne/modules/sensors/temp_adc.h File Reference
temp_adc.h File Reference
temperature driver for LM35 and 100k NTC analog sensores
#include "std.h"
Functions
void temp_adc_init (void)
Temperature ADC initialize channels.
void temp_adc_periodic (void)
float get_temp (uint8_t nr)
Variables
bool temp_adc_sync_send
Detailed Description
temperature driver for LM35 and 100k NTC analog sensores
Definition in file temp_adc.h.
Function Documentation
float get_temp (uint8_t nr)
Definition at line 37 of file temp_adc.c.
References temp_c1, temp_c2, and temp_c3.
void temp_adc_init (void)
Temperature ADC initialize channels.
Definition at line 129 of file temp_adc.c.
References adc_buf_channel(), DefaultPeriodic, register_periodic_telemetry(), TEMP_ADC_CHANNEL1, TEMP_ADC_CHANNEL2, temp_adc_downlink(), TEMP_ADC_NB_SAMPLES, temp_adc_sync_send, and TEMP_ADC_SYNC_SEND.
void temp_adc_periodic (void)
Definition at line 151 of file temp_adc.c.
References calc_lm35(), calc_ntc(), DefaultChannel, DefaultDevice, TEMP_ADC_CHANNEL1_A, TEMP_ADC_CHANNEL1_B, TEMP_ADC_CHANNEL1_C, TEMP_ADC_CHANNEL1_PU_R, TEMP_ADC_CHANNEL2_A, TEMP_ADC_CHANNEL2_B, TEMP_ADC_CHANNEL2_C, TEMP_ADC_CHANNEL2_PU_R, temp_adc_downlink(), temp_adc_sync_send, temp_c1, temp_c2, and temp_c3.
Variable Documentation
bool temp_adc_sync_send
Definition at line 34 of file temp_adc.c.
Referenced by temp_adc_init(), and temp_adc_periodic().