Paparazzi UAS: sw/airborne/mcu_periph/uart.c File Reference
uart.c File Reference
#include "mcu_periph/uart.h"
#include "subsystems/datalink/telemetry.h"
Functions
static void send_uart_err (struct transport_tx *trans, struct link_device *dev)
void uart_periph_init (struct uart_periph *p)
int WEAK uart_check_free_space (struct uart_periph *p, long *fd, uint16_t len)
void WEAK uart_put_buffer (struct uart_periph *p, long fd, const uint8_t *data, uint16_t len)
Uart transmit buffer implementation.
void WEAK uart_send_message (struct uart_periph *p, long fd)
uint8_t WEAK uart_getch (struct uart_periph *p)
int WEAK uart_char_available (struct uart_periph *p)
Check UART for available chars in receive buffer.
void WEAK uart_arch_init (void)
void WEAK uart_periph_invert_data_logic (struct uart_periph *p, bool invert_rx, bool invert_tx)
Function Documentation
static void send_uart_err (struct transport_tx * trans, struct link_device * dev) static
Definition at line 181 of file uart.c.
References dev.
Referenced by uart_periph_init().
void WEAK uart_arch_init (void)
Definition at line 295 of file uart.c.
References uart_thread().
int WEAK uart_char_available (struct uart_periph * p)
Check UART for available chars in receive buffer.
Returns
number of chars in the buffer
Definition at line 286 of file uart.c.
References uart_periph::rx_extract_idx, uart_periph::rx_insert_idx, and UART_RX_BUFFER_SIZE.
Referenced by uart_periph_init().
int WEAK uart_check_free_space (struct uart_periph * p, long * fd, uint16_t len)
Definition at line 256 of file uart.c.
References uart_periph::init_struct, uart_periph::tx_extract_idx, uart_periph::tx_insert_idx, SerialInit::tx_mtx, and UART_TX_BUFFER_SIZE.
Referenced by uart_periph_init().
uint8_t WEAK uart_getch (struct uart_periph * p)
Definition at line 279 of file uart.c.
References uart_periph::init_struct, uart_periph::rx_buf, uart_periph::rx_extract_idx, SerialInit::rx_mtx, and UART_RX_BUFFER_SIZE.
Referenced by uart_periph_init().
void uart_periph_init (struct uart_periph * p)
Definition at line 231 of file uart.c.
References DefaultPeriodic, uart_periph::device, uart_periph::fe_err, uart_periph::ne_err, uart_periph::ore, register_periodic_telemetry(), uart_periph::rx_extract_idx, uart_periph::rx_insert_idx, send_uart_err(), uart_periph::tx_extract_idx, uart_periph::tx_insert_idx, uart_periph::tx_running, uart_char_available(), uart_check_free_space(), uart_getch(), uart_periph_set_baudrate(), uart_put_buffer(), uart_put_byte(), and uart_send_message().
Referenced by high_speed_logger_direct_memory_init().
void WEAK uart_periph_invert_data_logic (struct uart_periph * p, bool invert_rx, bool invert_tx)
Definition at line 299 of file uart.c.
Referenced by sbus_common_init().
void WEAK uart_put_buffer (struct uart_periph * p, long fd, const uint8_t * data, uint16_t len)
Uart transmit buffer implementation.
Definition at line 266 of file uart.c.
References uart_periph::init_struct, uart_periph::tx_buf, uart_periph::tx_extract_idx, uart_periph::tx_insert_idx, SerialInit::tx_mtx, SerialInit::tx_sem, uart_put_byte(), and UART_TX_BUFFER_SIZE.
Referenced by uart_periph_init().
void WEAK uart_send_message (struct uart_periph * p, long fd)
Definition at line 275 of file uart.c.
References uart_periph::init_struct, SerialInit::tx_mtx, and SerialInit::tx_sem.
Referenced by uart_periph_init().