Paparazzi UAS: sw/airborne/mcu_periph/udp.h File Reference
udp.h File Reference
arch independent UDP API
#include "std.h"
#include "mcu_periph/udp_arch.h"
#include "pprzlink/pprzlink_device.h"
Data Structures
struct udp_periph
Macros
#define UDP_RX_BUFFER_SIZE 256
#define UDP_TX_BUFFER_SIZE 256
Functions
void udp_periph_init (struct udp_periph *p, char *host, int port_out, int port_in, bool broadcast)
Initialize the UDP peripheral.
int udp_check_free_space (struct udp_periph *p, long *fd, uint16_t len)
Check if there is enough free space in the transmit buffer.
void udp_put_byte (struct udp_periph *p, long fd, uint8_t data)
Add one data byte to the tx buffer.
int udp_char_available (struct udp_periph *p)
Get number of bytes available in receive buffer.
uint8_t udp_getch (struct udp_periph *p)
Get the last character from the receive buffer.
void udp_arch_periph_init (struct udp_periph *p, char *host, int port_out, int port_in, bool broadcast)
Initialize the UDP peripheral.
void udp_send_message (struct udp_periph *p, long fd)
Send a message.
void udp_send_raw (struct udp_periph *p, long fd, uint8_t *buffer, uint16_t size)
Send a packet from another buffer.
void udp_receive (struct udp_periph *p)
Read bytes from UDP.
void udp_put_buffer (struct udp_periph *p, long fd, const uint8_t *data, uint16_t len)
Detailed Description
arch independent UDP API
Definition in file udp.h.
Data Structure Documentation
struct udp_periph
Definition at line 38 of file udp.h.
Data Fields
struct link_device device Generic device interface.
void * network UDP network.
uint8_t rx_buf[UDP_RX_BUFFER_SIZE] Receive buffer.
uint16_t rx_extract_idx
uint16_t rx_insert_idx
uint8_t tx_buf[UDP_TX_BUFFER_SIZE] Transmit buffer.
uint16_t tx_insert_idx
Macro Definition Documentation
#define UDP_RX_BUFFER_SIZE 256
Definition at line 35 of file udp.h.
Referenced by udp_char_available(), udp_getch(), and udp_receive().
#define UDP_TX_BUFFER_SIZE 256
Definition at line 36 of file udp.h.
Referenced by udp_check_free_space(), udp_put_buffer(), and udp_put_byte().
Function Documentation
void udp_arch_periph_init (struct udp_periph * p, char * host, int port_out, int port_in, bool broadcast)
Initialize the UDP peripheral.
Allocate UdpSocket struct and create and bind the UDP socket.
Definition at line 71 of file udp_arch.c.
References udp_periph::network, and udp_socket_create().
Referenced by udp_periph_init().
int udp_char_available (struct udp_periph * p)
Get number of bytes available in receive buffer.
Parameters
p pointer to UDP peripheral
Returns
number of bytes available in receive buffer
Definition at line 83 of file udp_arch.c.
References udp_periph::rx_extract_idx, udp_periph::rx_insert_idx, and UDP_RX_BUFFER_SIZE.
Referenced by udp_periph_init(), and udp_receive().
int udp_check_free_space (struct udp_periph * p, long * fd, uint16_t len)
Check if there is enough free space in the transmit buffer.
Parameters
p pointer to UDP peripheral
len how many bytes of free space to check for
Returns
number of bytes available or 0 if not enough
Definition at line 83 of file udp.c.
References udp_periph::tx_insert_idx, and UDP_TX_BUFFER_SIZE.
Referenced by udp_periph_init().
uint8_t udp_getch (struct udp_periph * p)
Get the last character from the receive buffer.
Parameters
p pointer to UDP peripheral
Returns
last byte
Definition at line 99 of file udp_arch.c.
References udp_periph::rx_buf, udp_periph::rx_extract_idx, and UDP_RX_BUFFER_SIZE.
Referenced by udp_periph_init().
void udp_periph_init (struct udp_periph * p, char * host, int port_out, int port_in, bool broadcast)
Initialize the UDP peripheral.
Definition at line 60 of file udp.c.
References udp_periph::device, udp_periph::rx_extract_idx, udp_periph::rx_insert_idx, udp_periph::tx_insert_idx, udp_arch_periph_init(), udp_char_available(), udp_check_free_space(), udp_getch(), udp_put_buffer(), udp_put_byte(), and udp_send_message().
void udp_put_buffer (struct udp_periph * p, long fd, const uint8_t * data, uint16_t len)
Definition at line 104 of file udp.c.
References udp_periph::tx_buf, udp_periph::tx_insert_idx, and UDP_TX_BUFFER_SIZE.
Referenced by udp_periph_init().
void udp_put_byte (struct udp_periph * p, long fd, uint8_t data)
Add one data byte to the tx buffer.
Parameters
p pointer to UDP peripheral
data byte to add to tx buffer
Definition at line 94 of file udp.c.
References udp_periph::tx_buf, udp_periph::tx_insert_idx, and UDP_TX_BUFFER_SIZE.
Referenced by udp_periph_init().
void udp_receive (struct udp_periph * p)
Read bytes from UDP.
Definition at line 111 of file udp_arch.c.
References UdpSocket::addr_in, udp_periph::network, udp_periph::rx_buf, udp_periph::rx_insert_idx, UdpSocket::sockfd, udp_char_available(), and UDP_RX_BUFFER_SIZE.
Referenced by udp_thread().
void udp_send_message (struct udp_periph * p, long fd)
Send a message.
Definition at line 144 of file udp_arch.c.
References UdpSocket::addr_out, udp_periph::network, UdpSocket::sockfd, udp_periph::tx_buf, and udp_periph::tx_insert_idx.
Referenced by udp_periph_init().
void udp_send_raw (struct udp_periph * p, long fd, uint8_t * buffer, uint16_t size)
Send a packet from another buffer.
Definition at line 169 of file udp_arch.c.
References UdpSocket::addr_out, udp_periph::network, and UdpSocket::sockfd.