Paparazzi UAS: sw/airborne/modules/ctrl/vertical_ctrl_module_demo.h File Reference
vertical_ctrl_module_demo.h File Reference
example vertical
#include "std.h"
Data Structures
struct VerticalCtrlDemo
Macros
#define GUIDANCE_H_MODE_MODULE_SETTING GUIDANCE_H_MODE_HOVER
#define GUIDANCE_V_MODE_MODULE_SETTING GUIDANCE_V_MODE_MODULE
Functions
void guidance_v_module_init (void)
void guidance_v_module_enter (void)
Entering the vertical module (user switched to module)
void guidance_v_module_run (bool in_flight)
Variables
struct VerticalCtrlDemo v_ctrl
Detailed Description
example vertical
Implements an example vertical controller in a module.
Definition in file vertical_ctrl_module_demo.h.
Data Structure Documentation
struct VerticalCtrlDemo
Definition at line 33 of file vertical_ctrl_module_demo.h.
Data Fields
float agl
float igain
float pgain
float setpoint
float sum_err
Macro Definition Documentation
#define GUIDANCE_H_MODE_MODULE_SETTING GUIDANCE_H_MODE_HOVER
Definition at line 44 of file vertical_ctrl_module_demo.h.
#define GUIDANCE_V_MODE_MODULE_SETTING GUIDANCE_V_MODE_MODULE
Definition at line 47 of file vertical_ctrl_module_demo.h.
Function Documentation
void guidance_v_module_enter (void)
Entering the vertical module (user switched to module)
Entering the vertical module (user switched to module)
Definition at line 111 of file ctrl_module_innerloop_demo.c.
References des_inputs, MAX_PPRZ, OpticalFlowLanding::nominal_thrust, OpticalFlowHoverControl::nominal_value, of_hover_ctrl_Z, of_landing_ctrl, reset_all_vars(), reset_vertical_vars(), stabilization_cmd, VerticalCtrlDemo::sum_err, DesiredInputs::thrust, and v_ctrl.
Referenced by guidance_v_mode_changed().
void guidance_v_module_init (void)
Definition at line 105 of file ctrl_module_innerloop_demo.c.
References vertical_ctrl_module_init().
Referenced by guidance_v_init().
void guidance_v_module_run (bool in_flight)
Definition at line 656 of file optical_flow_hover.c.
References AP_MODE_NAV, autopilot_static_set_mode(), Electrical::bat_low, electrical, and vertical_ctrl_module_run().
Variable Documentation
struct VerticalCtrlDemo v_ctrl
Definition at line 53 of file vertical_ctrl_module_demo.c.
Referenced by guidance_v_module_enter(), vertical_ctrl_agl_cb(), vertical_ctrl_module_init(), and vertical_ctrl_module_run().