Paparazzi UAS: sw/airborne/modules/ins/xsens_parser.c File Reference
xsens_parser.c File Reference
#include "xsens_parser.h"
#include "pprzlink/pprzlink_device.h"
#include "mcu_periph/uart.h"
Functions
void xsens_parser_func (struct XsensParser *xsens, uint8_t c)
void xsens_parser_event (struct XsensParser *xsensparser)
Variables
uint8_t send_ck
Function Documentation
void xsens_parser_event (struct XsensParser * xsensparser)
Definition at line 35 of file xsens_parser.c.
References dev, XsensParser::msg_received, and xsens_parser_func().
Referenced by imu_xsens_event(), ins_xsens700_event(), and ins_xsens_event().
void xsens_parser_func (struct XsensParser * xsens, uint8_t c)
Definition at line 45 of file xsens_parser.c.
References XsensParser::ck, GOT_BID, GOT_DATA, GOT_LEN, GOT_MID, GOT_START, XsensParser::id, XsensParser::len, XsensParser::msg_buf, XsensParser::msg_idx, XsensParser::msg_received, XsensParser::status, TRUE, UNINIT, and XSENS_MAX_PAYLOAD.
Referenced by xsens_parser_event().
Variable Documentation
uint8_t send_ck
Definition at line 31 of file xsens_parser.c.