Paparazzi UAS: sw/airborne/boards/xvert/baro_board.h File Reference
baro_board.h File Reference
Macros
#define BARO_BOARD BARO_MS5611_I2C
#define BB_MS5611_TYPE_MS5607 TRUE
#define BaroEvent baro_event
Functions
void baro_event (void)
Macro Definition Documentation
#define BARO_BOARD BARO_MS5611_I2C
Definition at line 12 of file baro_board.h.
#define BaroEvent baro_event
Definition at line 18 of file baro_board.h.
#define BB_MS5611_TYPE_MS5607 TRUE
Definition at line 15 of file baro_board.h.
Function Documentation
void baro_event (void)
Definition at line 103 of file baro_board_ms5611_i2c.c.
References baro_bmp085, BARO_BOARD_SENDER_ID, baro_swing_available, baro_swing_mutex, baro_swing_raw, bb_ms5611, bb_ms5611_filt, bmp085_event(), Ms5611Data::d1, Ms5611Data::d2, Ms5611_I2c::data, Ms5611_Spi::data, Ms5611_I2c::data_available, Ms5611_Spi::data_available, Bmp085::data_available, DefaultChannel, DefaultDevice, fbaroms, get_sys_time_usec(), LED_TOGGLE, ms5611_i2c_event(), ms5611_spi_event(), sys_time::nb_sec, Ms5611Data::pressure, Bmp085::pressure, Ms5611Data::temperature, Bmp085::temperature, and update_median_filter_f().