Paparazzi UAS: sw/airborne/modules/actuators/actuators_uavcan.h File Reference
actuators_uavcan.h File Reference
#include "modules/uavcan/uavcan.h"
#include <BOARD_CONFIG>
Macros
#define ACTUATORS_UAVCAN_RAW_DIV 1
#define ACTUATORS_UAVCAN_CMD_DIV 1
Functions
void actuators_uavcan_init (struct uavcan_iface_t *iface)
Initialize an uavcan interface.
void actuators_uavcan_commit (struct uavcan_iface_t *iface, int16_t *values, uint8_t nb)
Commit actuator values to the uavcan interface (EQUIPMENT_ESC_RAWCOMMAND)
void actuators_uavcan_cmd_commit (struct uavcan_iface_t *iface, int16_t *values, uint8_t nb)
Commit actuator values to the uavcan interface (EQUIPMENT_ACTUATOR_ARRAYCOMMAND)
Macro Definition Documentation
ACTUATORS_UAVCAN_CMD_DIV
#define ACTUATORS_UAVCAN_CMD_DIV 1
Definition at line 36 of file actuators_uavcan.h.
ACTUATORS_UAVCAN_RAW_DIV
#define ACTUATORS_UAVCAN_RAW_DIV 1
Definition at line 31 of file actuators_uavcan.h.
Function Documentation
actuators_uavcan_cmd_commit()
void actuators_uavcan_cmd_commit (struct uavcan_iface_t * iface, int16_t * values, uint8_t nb) extern
Commit actuator values to the uavcan interface (EQUIPMENT_ACTUATOR_ARRAYCOMMAND)
Definition at line 409 of file actuators_uavcan.c.
References foo, MAX_PPRZ, MIN_PPRZ, msg, uavcan_broadcast(), and UAVCAN_CMD_UNUSED.
actuators_uavcan_commit()
void actuators_uavcan_commit (struct uavcan_iface_t * iface, int16_t * values, uint8_t nb) extern
Commit actuator values to the uavcan interface (EQUIPMENT_ESC_RAWCOMMAND)
Definition at line 388 of file actuators_uavcan.c.
References foo, msg, and uavcan_broadcast().
actuators_uavcan_init()
void actuators_uavcan_init (struct uavcan_iface_t * iface) extern
Initialize an uavcan interface.
Definition at line 348 of file actuators_uavcan.c.
References actuator_status_ev, actuators_uavcan1cmd_values, actuators_uavcan2cmd_values, actuators_uavcan_actuator_status_cb(), actuators_uavcan_device_temperature_cb(), actuators_uavcan_esc_status_cb(), actuators_uavcan_initialized, actuators_uavcan_send_esc(), DefaultPeriodic, device_temperature_ev, esc_status_ev, foo, init_random(), register_periodic_telemetry(), uavcan_bind(), and UAVCAN_CMD_UNUSED.