Paparazzi UAS: sw/airborne/modules/actuators/actuators_t4_uart.h File Reference
actuators_t4_uart.h File Reference
Uses a T4 Actuators Board as fly by wire system. This Board can control serial bus servos, ESC's and PWM servos, with as big benefir providing real time telemetry in return into the autopilot state. Read more on how to create your own T4 Board here: https://github.com/tudelft/t4_actuators_board/.
#include "std.h"
#include <stdbool.h>
#include <stdlib.h>
#include "generated/airframe.h"
#include "pprzlink/pprz_transport.h"
Data Structures
struct ActuatorsT4In
struct ActuatorsT4Out
Macros
#define START_BYTE_ACTUATORS_T4 0x9A
Functions
void actuators_t4_uart_init (void)
void actuators_t4_uart_parse_msg_in (void)
void actuators_t4_uart_event (void)
Detailed Description
Uses a T4 Actuators Board as fly by wire system. This Board can control serial bus servos, ESC's and PWM servos, with as big benefir providing real time telemetry in return into the autopilot state. Read more on how to create your own T4 Board here: https://github.com/tudelft/t4_actuators_board/.
Author
Alessandro Mancinelli, Sunyou Hwang, OpenUAS
Definition in file actuators_t4_uart.h.
Data Structure Documentation
ActuatorsT4In
struct ActuatorsT4In
Definition at line 39 of file actuators_t4_uart.h.
Data Fields
uint16_t bitmask_servo_health
uint8_t checksum_in
int16_t esc_1_current
int16_t esc_1_error_code
int16_t esc_1_rpm
int16_t esc_1_voltage
int16_t esc_2_current
int16_t esc_2_error_code
int16_t esc_2_rpm
int16_t esc_2_voltage
int16_t esc_3_current
int16_t esc_3_error_code
int16_t esc_3_rpm
int16_t esc_3_voltage
int16_t esc_4_current
int16_t esc_4_error_code
int16_t esc_4_rpm
int16_t esc_4_voltage
float rolling_msg_in
uint8_t rolling_msg_in_id
int16_t servo_10_angle
int16_t servo_10_load
int16_t servo_11_angle
int16_t servo_12_angle
int16_t servo_1_angle
int16_t servo_1_load
int16_t servo_2_angle
int16_t servo_2_load
int16_t servo_3_angle
int16_t servo_3_load
int16_t servo_4_angle
int16_t servo_4_load
int16_t servo_5_angle
int16_t servo_5_load
int16_t servo_6_angle
int16_t servo_6_load
int16_t servo_7_angle
int16_t servo_7_load
int16_t servo_8_angle
int16_t servo_8_load
int16_t servo_9_angle
int16_t servo_9_load
ActuatorsT4Out
struct ActuatorsT4Out
Definition at line 112 of file actuators_t4_uart.h.
Data Fields
uint8_t checksum_out
int16_t esc_1_dshot_cmd
int16_t esc_2_dshot_cmd
int16_t esc_3_dshot_cmd
int16_t esc_4_dshot_cmd
uint8_t esc_arm
float rolling_msg_out
uint8_t rolling_msg_out_id
int16_t servo_10_cmd
int16_t servo_11_cmd
int16_t servo_12_cmd
int16_t servo_1_cmd
int16_t servo_2_cmd
int16_t servo_3_cmd
int16_t servo_4_cmd
int16_t servo_5_cmd
int16_t servo_6_cmd
int16_t servo_7_cmd
int16_t servo_8_cmd
int16_t servo_9_cmd
uint16_t servo_arm
Macro Definition Documentation
START_BYTE_ACTUATORS_T4
#define START_BYTE_ACTUATORS_T4 0x9A
Definition at line 31 of file actuators_t4_uart.h.
Function Documentation
actuators_t4_uart_event()
void actuators_t4_uart_event (void) extern
Definition at line 226 of file actuators_t4_uart.c.
References actuators_t4_buf_in_cnt, actuators_t4_last_ts, actuators_t4_message_frequency_in, actuators_t4_missed_packets_in, actuators_t4_msg_buf_in, actuators_t4_received_packets, actuators_t4_uart_parse_msg_in(), foo, get_sys_time_float(), START_BYTE_ACTUATORS_T4, uart_char_available(), and uart_getch().
actuators_t4_uart_init()
void actuators_t4_uart_init (void) extern
Definition at line 201 of file actuators_t4_uart.c.
References ABI_BROADCAST, actuators_t4_buf_in_cnt, actuators_t4_downlink(), ACTUATORS_T4_OUT, actuators_t4_out_msg_id, actuators_t4_uplink(), data_actuators_t4_out(), DefaultPeriodic, foo, and register_periodic_telemetry().
actuators_t4_uart_parse_msg_in()
void actuators_t4_uart_parse_msg_in (void) extern
Definition at line 216 of file actuators_t4_uart.c.
References actuators_t4_extra_data_in, actuators_t4_in, actuators_t4_msg_buf_in, foo, ActuatorsT4In::rolling_msg_in, and ActuatorsT4In::rolling_msg_in_id.
Referenced by actuators_t4_uart_event().