Paparazzi UAS: sw/airborne/modules/actuators/actuators_sbus.c File Reference
actuators_sbus.c File Reference
Sbus actuator driver, which can output as 7 sbus channels at ~11ms.
#include "modules/actuators/actuators.h"
#include "modules/actuators/actuators_sbus.h"
#include "generated/airframe.h"
#include "mcu_periph/uart.h"
Macros
#define SBUS_START_BYTE 0x0f
#define SBUS_END_BYTE 0x00
#define SBUS_BIT_PER_CHANNEL 11
Functions
static void actuators_sbus_send (struct link_device *dev)
void actuators_sbus_init (void)
void actuators_sbus_commit (void)
void actuators_sbus_set (uint8_t idx, int16_t value)
Variables
struct ActuatorsSbus actuators_sbus
Detailed Description
Sbus actuator driver, which can output as 7 sbus channels at ~11ms.
Channels min, averga and maximum should be: 172, 992, 1811
Definition in file actuators_sbus.c.
Macro Definition Documentation
SBUS_BIT_PER_CHANNEL
#define SBUS_BIT_PER_CHANNEL 11
Definition at line 96 of file actuators_sbus.c.
SBUS_END_BYTE
#define SBUS_END_BYTE 0x00
Definition at line 94 of file actuators_sbus.c.
SBUS_START_BYTE
#define SBUS_START_BYTE 0x0f
Definition at line 93 of file actuators_sbus.c.
Function Documentation
actuators_sbus_commit()
void actuators_sbus_commit (void)
Definition at line 64 of file actuators_sbus.c.
References actuators_sbus, actuators_sbus_send(), ActuatorsSbus::device, and foo.
actuators_sbus_init()
void actuators_sbus_init (void)
Definition at line 51 of file actuators_sbus.c.
References actuators_sbus, B100000, ActuatorsSbus::device, foo, uart_periph_invert_data_logic(), uart_periph_set_baudrate(), uart_periph_set_bits_stop_parity(), UBITS_8, UPARITY_EVEN, and USTOP_2.
actuators_sbus_send()
static void actuators_sbus_send (struct link_device * dev) inline static
Definition at line 98 of file actuators_sbus.c.
References actuators_sbus, ActuatorsSbus::cmds, dev, frame, SBUS_END_BYTE, and SBUS_START_BYTE.
Referenced by actuators_sbus_commit().
actuators_sbus_set()
void actuators_sbus_set (uint8_t idx, int16_t value)
Definition at line 76 of file actuators_sbus.c.
References actuators_sbus, ActuatorsSbus::cmds, and idx.
Variable Documentation
actuators_sbus
struct ActuatorsSbus actuators_sbus
Definition at line 45 of file actuators_sbus.c.
Referenced by actuators_sbus_commit(), actuators_sbus_init(), actuators_sbus_send(), and actuators_sbus_set().