Paparazzi UAS: sw/airborne/modules/actuators/actuators_ostrich.h File Reference
actuators_ostrich.h File Reference
#include "std.h"
Data Structures
struct ActuatorsOstrich
Macros
#define ActuatorOSTRICHSet actuators_ostrich_set
#define ActuatorsOSTRICHInit() actuators_ostrich_init()
#define ActuatorsOSTRICHCommit() {}
Functions
void actuators_ostrich_init (void)
void actuators_ostrich_periodic (void)
void actuators_ostrich_set (uint8_t idx, int16_t value)
Variables
struct ActuatorsOstrich actuators_ostrich
Detailed Description
Author
Fabien Bonneval Driver for the Ostrich rover controller board
Definition in file actuators_ostrich.h.
Data Structure Documentation
ActuatorsOstrich
struct ActuatorsOstrich
Definition at line 32 of file actuators_ostrich.h.
Data Fields
uint16_t cmds[3] commands
Macro Definition Documentation
ActuatorOSTRICHSet
#define ActuatorOSTRICHSet actuators_ostrich_set
Definition at line 45 of file actuators_ostrich.h.
ActuatorsOSTRICHCommit
#define ActuatorsOSTRICHCommit () {}
Definition at line 47 of file actuators_ostrich.h.
ActuatorsOSTRICHInit
#define ActuatorsOSTRICHInit () actuators_ostrich_init()
Definition at line 46 of file actuators_ostrich.h.
Function Documentation
actuators_ostrich_init()
void actuators_ostrich_init (void) extern
Definition at line 88 of file actuators_ostrich.c.
References actuators_ostrich, ActuatorsOstrich::cmds, foo, ostrich_dev, SPEED_NEUTRAL, and TURN_NEUTRAL.
actuators_ostrich_periodic()
void actuators_ostrich_periodic (void) extern
Definition at line 96 of file actuators_ostrich.c.
References actuators_ostrich, ActuatorsOstrich::cmds, compute_checksum(), foo, ostrich_dev, speed_cmd_to_msg(), RawMessage::speed_message, START_BYTE, SpeedMessage::start_byte, turn_cmd_to_msg(), and uart_put_buffer().
actuators_ostrich_set()
void actuators_ostrich_set (uint8_t idx, int16_t value) extern
Definition at line 115 of file actuators_ostrich.c.
References actuators_ostrich, ActuatorsOstrich::cmds, and idx.
Variable Documentation
actuators_ostrich
struct ActuatorsOstrich actuators_ostrich extern
Definition at line 38 of file actuators_ostrich.c.
Referenced by actuators_ostrich_init(), actuators_ostrich_periodic(), and actuators_ostrich_set().