Paparazzi UAS: sw/airborne/arch/stm32/modules/actuators/actuators_shared_arch.c File Reference
actuators_shared_arch.c File Reference
STM32 PWM and dualPWM servos shared functions.
#include "arch/stm32/modules/actuators/actuators_shared_arch.h"
#include <libopencm3/stm32/timer.h>
#include "arch/stm32/mcu_arch.h"
Functions
void actuators_pwm_arch_channel_init (uint32_t timer_peripheral, enum tim_oc_id oc_id)
Set PWM channel configuration.
void set_servo_timer (uint32_t timer, uint32_t freq, uint8_t channels_mask)
Set Timer configuration.
Detailed Description
STM32 PWM and dualPWM servos shared functions.
Definition in file actuators_shared_arch.c.
Function Documentation
actuators_pwm_arch_channel_init()
void actuators_pwm_arch_channel_init (uint32_t timer_peripheral, enum tim_oc_id oc_id)
Set PWM channel configuration.
Definition at line 35 of file actuators_shared_arch.c.
References foo.
Referenced by set_servo_timer().
set_servo_timer()
void set_servo_timer (uint32_t timer, uint32_t freq, uint8_t channels_mask)
Set Timer configuration.
Parameters
[in] timer Timer register address base
[in] freq PWM frequency in Hz (1 / auto-reload period)
[in] channels_mask output compare channels to enable
Definition at line 59 of file actuators_shared_arch.c.
References actuators_pwm_arch_channel_init(), foo, PWM_BASE_FREQ, and timer_get_frequency().
Referenced by actuators_dualpwm_arch_init(), and actuators_pwm_arch_init().