Paparazzi UAS: sw/airborne/modules/actuators/actuators_dshot.h File Reference
actuators_dshot.h File Reference
#include "std.h"
Data Structures
struct dshot
Macros
#define ACTUATORS_DSHOT_OFFSET 48
In normal DSHOT, first 48 values are special commands this offset allow to use 0 as the no-throttle command This should not be changed unless you know what you are doing.
#define ACTUATORS_DSHOT_NB (8+1)
Maxnum number of DSHOT commands This should be large enough for max applications: 8 motors +1 in case motor count starts at 1 and not 0.
#define ActuatorDShotSet actuators_dshot_set
#define ActuatorsDShotInit actuators_dshot_arch_init
#define ActuatorsDShotCommit actuators_dshot_arch_commit
Functions
void actuators_dshot_arch_init (void)
Arch dependent init.
void actuators_dshot_arch_commit (void)
void actuators_dshot_set (uint8_t idx, int16_t value)
Variables
struct dshot actuators_dshot_values [ACTUATORS_DSHOT_NB]
Detailed Description
Author
Gautier Hattenberger Driver for DSHOT speed controller protocol
Definition in file actuators_dshot.h.
Data Structure Documentation
dshot
struct dshot
Definition at line 48 of file actuators_dshot.h.
Data Fields
bool activated current dshot channel is activated
float cmd command
float current current
float energy energy (from dshot telemetry)
float rpm rpm
float temp temperature
float voltage motor current
Macro Definition Documentation
ActuatorDShotSet
#define ActuatorDShotSet actuators_dshot_set
Definition at line 67 of file actuators_dshot.h.
ACTUATORS_DSHOT_NB
#define ACTUATORS_DSHOT_NB (8+1)
Maxnum number of DSHOT commands This should be large enough for max applications: 8 motors +1 in case motor count starts at 1 and not 0.
Definition at line 45 of file actuators_dshot.h.
ACTUATORS_DSHOT_OFFSET
#define ACTUATORS_DSHOT_OFFSET 48
In normal DSHOT, first 48 values are special commands this offset allow to use 0 as the no-throttle command This should not be changed unless you know what you are doing.
Definition at line 37 of file actuators_dshot.h.
ActuatorsDShotCommit
#define ActuatorsDShotCommit actuators_dshot_arch_commit
Definition at line 69 of file actuators_dshot.h.
ActuatorsDShotInit
#define ActuatorsDShotInit actuators_dshot_arch_init
Definition at line 68 of file actuators_dshot.h.
Function Documentation
actuators_dshot_arch_commit()
void actuators_dshot_arch_commit (void) extern
Definition at line 291 of file actuators_dshot_arch.c.
References ACT_FEEDBACK_DSHOT_ID, ACTUATORS_DSHOT_NB, actuators_dshot_private, actuators_dshot_values, dshot::current, DSHOT_BIDIR_ERR_CRC, DSHOT_BIDIR_TLM_EDT, DSHOT_MOTOR_POLES, dshotGetTelemetry(), dshotSendFrame(), dshotSetThrottle(), dshot::energy, foo, act_feedback_t::idx, act_feedback_t::act_feedback_set_t::rpm, act_feedback_t::rpm, dshot::rpm, rpm, act_feedback_t::set, dshot::temp, and dshot::voltage.
actuators_dshot_arch_init()
void actuators_dshot_arch_init (void) extern
Arch dependent init.
Definition at line 153 of file actuators_dshot_arch.c.
References ACTUATORS_DSHOT_NB, actuators_dshot_private, actuators_dshot_values, CONCAT_GPIO, DefaultPeriodic, dshot_init_struct(), dshot_set_struct(), dshotStart(), esc_msg_send(), FALSE, foo, gpio_setup_pin_af(), gpio_setup_pin_af_pullup(), PRINT_CONFIG_VAR(), and register_periodic_telemetry().
actuators_dshot_set()
void actuators_dshot_set (uint8_t idx, int16_t value) extern
Definition at line 30 of file actuators_dshot.c.
References ACTUATORS_DSHOT_OFFSET, actuators_dshot_values, dshot::cmd, and idx.
Variable Documentation
actuators_dshot_values
struct dshot actuators_dshot_values[ACTUATORS_DSHOT_NB] extern
Definition at line 28 of file actuators_dshot.c.
Referenced by actuators_dshot_arch_commit(), actuators_dshot_arch_init(), actuators_dshot_set(), and esc_msg_send().