Paparazzi UAS: sw/airborne/filters/adaptive_notch_filter.h File Reference
adaptive_notch_filter.h File Reference
Adaptive notch filter.
#include "std.h"
#include "filters/low_pass_filter.h"
#include "filters/notch_filter_float.h"
Data Structures
struct AdaptiveNotchFilter
Functions
static void adaptive_notch_filter_init (struct AdaptiveNotchFilter *filter, float sample_time, float low_freq_bound, float high_freq_bound, float bandwidth, float lambda, float a_ini, float value)
Init a adaptive notch filter.
static void adaptive_notch_filter_update (struct AdaptiveNotchFilter *filter, float value, float *output_signal)
Update a second order adaptive notch filter.
static float adaptive_notch_filter_get_output (struct AdaptiveNotchFilter *filter)
Return the latest second order adaptive notch filter output.
Detailed Description
Adaptive notch filter.
Definition in file adaptive_notch_filter.h.
Data Structure Documentation
AdaptiveNotchFilter
struct AdaptiveNotchFilter
Definition at line 35 of file adaptive_notch_filter.h.
Data Fields
float a_est
float hp_cutoff_f
Butterworth2LowPass hp_filter
float lambda
float lp_cutoff_f
Butterworth2LowPass lp_filter
struct SecondOrderNotchFilter output_n_filter
float r
float r2
float Ts
float xband[3]
float y[2]
float y_est[2]
Function Documentation
adaptive_notch_filter_get_output()
static float adaptive_notch_filter_get_output (struct AdaptiveNotchFilter * filter) inline static
Return the latest second order adaptive notch filter output.
Parameters
filter adaptive notch filter structure
Returns
latest filtered value
Definition at line 138 of file adaptive_notch_filter.h.
References AdaptiveNotchFilter::y_est.
adaptive_notch_filter_init()
static void adaptive_notch_filter_init (struct AdaptiveNotchFilter * filter, float sample_time, float low_freq_bound, float high_freq_bound, float bandwidth, float lambda, float a_ini, float value) inline static
Init a adaptive notch filter.
Parameters
filter adaptive notch filter structure
sample_time sampling period of the signal
low_freq_bound lower frequency bound of the adaptive notch filter
high_freq_bound higher frequency bound of the adaptive notch filter
bandwidth bandwidth of the adaptive notch filter
lambda learning rate of the adaptive notch filter
a_ini initial band-stop frequency of the adaptive notch filter
value initial value of the filter
Definition at line 65 of file adaptive_notch_filter.h.
References AdaptiveNotchFilter::a_est, foo, AdaptiveNotchFilter::hp_cutoff_f, AdaptiveNotchFilter::hp_filter, init_butterworth_2_low_pass(), AdaptiveNotchFilter::lambda, lambda, AdaptiveNotchFilter::lp_cutoff_f, AdaptiveNotchFilter::lp_filter, notch_filter_init(), AdaptiveNotchFilter::output_n_filter, AdaptiveNotchFilter::r, AdaptiveNotchFilter::Ts, AdaptiveNotchFilter::xband, AdaptiveNotchFilter::y, and AdaptiveNotchFilter::y_est.
adaptive_notch_filter_update()
static void adaptive_notch_filter_update (struct AdaptiveNotchFilter * filter, float value, float * output_signal) inline static
Update a second order adaptive notch filter.
Parameters
filter adaptive notch filter structure
value new input value of the filter
output pointer to float for output
Returns
new filtered value
Definition at line 102 of file adaptive_notch_filter.h.
References AdaptiveNotchFilter::a_est, foo, AdaptiveNotchFilter::hp_cutoff_f, AdaptiveNotchFilter::hp_filter, AdaptiveNotchFilter::lambda, AdaptiveNotchFilter::lp_cutoff_f, AdaptiveNotchFilter::lp_filter, notch_filter_set_filter_frequency(), notch_filter_update(), SecondOrderLowPass::o, AdaptiveNotchFilter::output_n_filter, AdaptiveNotchFilter::r, AdaptiveNotchFilter::r2, AdaptiveNotchFilter::Ts, update_butterworth_2_low_pass(), AdaptiveNotchFilter::xband, AdaptiveNotchFilter::y, and AdaptiveNotchFilter::y_est.