Paparazzi UAS: sw/airborne/modules/adcs/adc_generic.h File Reference
adc_generic.h File Reference
This module can be used to read one or two values from the ADC channels in a generic way.
#include "std.h"
Functions
void adc_generic_init (void)
void adc_generic_periodic (void)
Variables
uint16_t adc_generic_val1
uint16_t adc_generic_val2
Detailed Description
This module can be used to read one or two values from the ADC channels in a generic way.
Data is reported through the default telemetry channel (by default) or can be redirected to an other one (alternate telemetry, datalogger) at a frequency defined in the telemetry xml file.
Definition in file adc_generic.h.
Function Documentation
adc_generic_init()
void adc_generic_init (void)
Definition at line 77 of file adc_generic.c.
References adc_buf_channel(), ADC_CHANNEL_GENERIC_NB_SAMPLES, adc_generic_val1, adc_generic_val2, adc_msg_send(), DefaultPeriodic, foo, and register_periodic_telemetry().
adc_generic_periodic()
void adc_generic_periodic (void)
Definition at line 94 of file adc_generic.c.
References adc_msg_send(), DefaultChannel, and DefaultDevice.
Variable Documentation
adc_generic_val1
uint16_t adc_generic_val1 extern
Definition at line 38 of file adc_generic.c.
Referenced by adc_generic_init(), and adc_msg_send().
adc_generic_val2
uint16_t adc_generic_val2 extern
Definition at line 39 of file adc_generic.c.
Referenced by adc_generic_init(), and adc_msg_send().