Paparazzi UAS: sw/airborne/modules/ahrs/ahrs_float_dcm_algebra.h File Reference
ahrs_float_dcm_algebra.h File Reference
Algebra helper functions for DCM.
Functions
static float Vector_Dot_Product (float vector1[3], float vector2[3])
static void Vector_Cross_Product (float vectorOut[3], float v1[3], float v2[3])
static void Vector_Scale (float vectorOut[3], float vectorIn[3], float scale2)
static void Vector_Add (float vectorOut[3], float vectorIn1[3], float vectorIn2[3])
static void Matrix_Multiply (float a[3][3], float b[3][3], float mat[3][3])
Detailed Description
Algebra helper functions for DCM.
Todo:
get rid of this and use pprz math lib.
Definition in file ahrs_float_dcm_algebra.h.
Function Documentation
Matrix_Multiply()
static void Matrix_Multiply (float a[3][3], float b[3][3], float mat[3][3]) inline static
Definition at line 64 of file ahrs_float_dcm_algebra.h.
References b, and foo.
Referenced by Matrix_update().
Vector_Add()
static void Vector_Add (float vectorOut[3], float vectorIn1[3], float vectorIn2[3]) inline static
Definition at line 43 of file ahrs_float_dcm_algebra.h.
References foo.
Referenced by Drift_correction(), Matrix_update(), and Normalize().
Vector_Cross_Product()
static void Vector_Cross_Product (float vectorOut[3], float v1[3], float v2[3]) inline static
Definition at line 29 of file ahrs_float_dcm_algebra.h.
References foo, v1, and v2.
Referenced by Drift_correction(), and Normalize().
Vector_Dot_Product()
static float Vector_Dot_Product (float vector1[3], float vector2[3]) inline static
Definition at line 24 of file ahrs_float_dcm_algebra.h.
References foo.
Referenced by Drift_correction(), and Normalize().
Vector_Scale()
static void Vector_Scale (float vectorOut[3], float vectorIn[3], float scale2) inline static
Definition at line 36 of file ahrs_float_dcm_algebra.h.
References foo.
Referenced by Drift_correction(), and Normalize().