Paparazzi UAS: sw/airborne/modules/ahrs/ahrs_vectornav_wrapper.h File Reference
ahrs_vectornav_wrapper.h File Reference
Vectornav VN-200 as AHRS.
#include "modules/ahrs/ahrs_vectornav.h"
Functions
void ahrs_vectornav_wrapper_init (void)
void ahrs_vectornav_wrapper_enable (uint8_t enable)
Variables
uint8_t ahrs_vectornav_enable
Detailed Description
Vectornav VN-200 as AHRS.
Author
Michal Podhradsky micha.nosp@m.l.po.nosp@m.dhrad.nosp@m.sky@.nosp@m.aggie.nosp@m.mail.nosp@m..usu..nosp@m.edu
Definition in file ahrs_vectornav_wrapper.h.
Function Documentation
ahrs_vectornav_wrapper_enable()
void ahrs_vectornav_wrapper_enable (uint8_t enable) extern
Definition at line 65 of file ahrs_vectornav_wrapper.c.
References ahrs_vectornav_enable, foo, STATE_INPUT_ATTITUDE, STATE_INPUT_RATES, and stateSetInputFilter().
Referenced by ahrs_vectornav_wrapper_init().
ahrs_vectornav_wrapper_init()
void ahrs_vectornav_wrapper_init (void) extern
Definition at line 51 of file ahrs_vectornav_wrapper.c.
References AHRS_PRIMARY, ahrs_vectornav_init(), ahrs_vectornav_wrapper_enable(), DefaultPeriodic, foo, register_periodic_telemetry(), and send_euler().
Variable Documentation
ahrs_vectornav_enable
uint8_t ahrs_vectornav_enable extern
Definition at line 35 of file ahrs_vectornav_wrapper.c.
Referenced by ahrs_vectornav_wrapper_enable().