Paparazzi UAS: sw/airborne/modules/ahrs/ahrs_float_cmpl_wrapper.h File Reference
ahrs_float_cmpl_wrapper.h File Reference
Paparazzi specific wrapper to run floating point complementary filter.
#include "modules/ahrs/ahrs_float_cmpl.h"
Functions
void ahrs_fc_wrapper_init (void)
void ahrs_float_cmpl_wrapper_enable (uint8_t enable)
Variables
uint8_t ahrs_fc_enable
if TRUE with push the estimation results to the state interface
Detailed Description
Paparazzi specific wrapper to run floating point complementary filter.
Definition in file ahrs_float_cmpl_wrapper.h.
Function Documentation
ahrs_fc_wrapper_init()
void ahrs_fc_wrapper_init (void) extern
Definition at line 260 of file ahrs_float_cmpl_wrapper.c.
References ABI_BROADCAST, accel_cb(), accel_ev, AHRS_FC_GPS_ID, AHRS_FC_IMU_ID, ahrs_fc_init(), AHRS_FC_MAG_ID, ahrs_float_cmpl_wrapper_enable(), AHRS_PRIMARY, aligner_cb(), aligner_ev, DefaultPeriodic, foo, geo_mag_cb(), geo_mag_ev, gps_cb(), gps_ev, gyro_cb(), gyro_ev, mag_cb(), mag_ev, register_periodic_telemetry(), send_bias(), send_euler(), send_euler_int(), send_filter_status(), and send_geo_mag().
ahrs_float_cmpl_wrapper_enable()
void ahrs_float_cmpl_wrapper_enable (uint8_t enable) extern
Definition at line 288 of file ahrs_float_cmpl_wrapper.c.
References ahrs_fc_enable, foo, STATE_INPUT_ATTITUDE, STATE_INPUT_RATES, and stateSetInputFilter().
Referenced by ahrs_fc_wrapper_init().
Variable Documentation
ahrs_fc_enable
uint8_t ahrs_fc_enable extern
if TRUE with push the estimation results to the state interface
Definition at line 35 of file ahrs_float_cmpl_wrapper.c.
Referenced by ahrs_float_cmpl_wrapper_enable().