Paparazzi UAS: sw/airborne/modules/ahrs/ahrs_float_mlkf_wrapper.h File Reference
ahrs_float_mlkf_wrapper.h File Reference
Paparazzi specific wrapper to run MLKF filter.
#include "modules/ahrs/ahrs_float_mlkf.h"
Functions
void ahrs_mlkf_wrapper_init (void)
void ahrs_float_mlkf_wrapper_enable (uint8_t enable)
Variables
uint8_t ahrs_mlkf_enable
Detailed Description
Paparazzi specific wrapper to run MLKF filter.
Definition in file ahrs_float_mlkf_wrapper.h.
Function Documentation
ahrs_float_mlkf_wrapper_enable()
void ahrs_float_mlkf_wrapper_enable (uint8_t enable) extern
Definition at line 218 of file ahrs_float_mlkf_wrapper.c.
References ahrs_mlkf_enable, foo, STATE_INPUT_ATTITUDE, STATE_INPUT_RATES, and stateSetInputFilter().
Referenced by ahrs_mlkf_wrapper_init().
ahrs_mlkf_wrapper_init()
void ahrs_mlkf_wrapper_init (void) extern
Definition at line 192 of file ahrs_float_mlkf_wrapper.c.
References ABI_BROADCAST, accel_cb(), accel_ev, ahrs_float_mlkf_wrapper_enable(), AHRS_MLKF_IMU_ID, ahrs_mlkf_init(), AHRS_MLKF_MAG_ID, AHRS_PRIMARY, aligner_cb(), aligner_ev, DefaultPeriodic, foo, geo_mag_cb(), geo_mag_ev, gyro_cb(), gyro_ev, mag_cb(), mag_ev, register_periodic_telemetry(), send_bias(), send_euler(), send_filter_status(), and send_geo_mag().
Variable Documentation
ahrs_mlkf_enable
uint8_t ahrs_mlkf_enable extern
Definition at line 35 of file ahrs_float_mlkf_wrapper.c.
Referenced by ahrs_float_mlkf_wrapper_enable().