Paparazzi UAS: sw/airborne/modules/ahrs/ahrs_aligner.h File Reference
ahrs_aligner.h File Reference
Interface to align the AHRS via low-passed measurements at startup.
#include "std.h"
#include "math/pprz_algebra_int.h"
Data Structures
struct AhrsAligner
Macros
#define AHRS_ALIGNER_UNINIT 0
#define AHRS_ALIGNER_RUNNING 1
#define AHRS_ALIGNER_LOCKED 2
Functions
void ahrs_aligner_init (void)
void ahrs_aligner_restart (void)
void ahrs_aligner_run (void)
Variables
struct AhrsAligner ahrs_aligner
Detailed Description
Interface to align the AHRS via low-passed measurements at startup.
Definition in file ahrs_aligner.h.
Data Structure Documentation
AhrsAligner
struct AhrsAligner
Definition at line 39 of file ahrs_aligner.h.
Data Fields
int32_t low_noise_cnt
struct Int32Vect3 lp_accel
struct Int32Rates lp_gyro
struct Int32Vect3 lp_mag
int32_t noise
uint8_t status
Macro Definition Documentation
AHRS_ALIGNER_LOCKED
#define AHRS_ALIGNER_LOCKED 2
Definition at line 37 of file ahrs_aligner.h.
AHRS_ALIGNER_RUNNING
#define AHRS_ALIGNER_RUNNING 1
Definition at line 36 of file ahrs_aligner.h.
AHRS_ALIGNER_UNINIT
#define AHRS_ALIGNER_UNINIT 0
Definition at line 35 of file ahrs_aligner.h.
Function Documentation
ahrs_aligner_init()
void ahrs_aligner_init (void) extern
Definition at line 84 of file ahrs_aligner.c.
References AHRS_ALIGNER_IMU_ID, ahrs_aligner_restart(), DefaultPeriodic, foo, gyro_cb(), gyro_ev, register_periodic_telemetry(), and send_aligner().
Referenced by ahrs_init(), ins_float_invariant_wrapper_init(), ins_flow_init(), and ins_mekf_wind_wrapper_init().
ahrs_aligner_restart()
void ahrs_aligner_restart (void) extern
Definition at line 96 of file ahrs_aligner.c.
References accel_sum, ahrs_aligner, AHRS_ALIGNER_RUNNING, gyro_sum, INT_RATES_ZERO, INT_VECT3_ZERO, AhrsAligner::low_noise_cnt, mag_sum, AhrsAligner::noise, samples_idx, and AhrsAligner::status.
Referenced by ahrs_aligner_init(), and gyro_cb().
ahrs_aligner_run()
void ahrs_aligner_run (void) extern
Definition at line 115 of file ahrs_aligner.c.
References accel_sum, ahrs_aligner, AHRS_ALIGNER_ID, AHRS_ALIGNER_IMU_ID, AHRS_ALIGNER_LOCKED, AHRS_ALIGNER_SAMPLES_NB, foo, get_sys_time_usec(), gyro_sum, imu_get_accel(), imu_get_gyro(), imu_get_mag(), INT_RATES_ZERO, INT_VECT3_ZERO, LED_ON, LED_TOGGLE, AhrsAligner::low_noise_cnt, LOW_NOISE_THRESHOLD, LOW_NOISE_TIME, AhrsAligner::lp_accel, AhrsAligner::lp_gyro, AhrsAligner::lp_mag, mag_sum, AhrsAligner::noise, RATES_ADD, RATES_SDIV, ref_sensor_samples, samples_idx, imu_gyro_t::scaled, imu_accel_t::scaled, imu_mag_t::scaled, AhrsAligner::status, VECT3_ADD, VECT3_SDIV, and Int32Vect3::z.
Referenced by gyro_cb().
Variable Documentation
ahrs_aligner
struct AhrsAligner ahrs_aligner extern
Definition at line 37 of file ahrs_aligner.c.
Referenced by ahrs_aligner_restart(), ahrs_aligner_run(), gyro_cb(), and send_aligner().