Paparazzi UAS: sw/airborne/modules/ahrs/ahrs_vectornav.h File Reference
ahrs_vectornav.h File Reference
Vectornav VN-200 as AHRS.
#include "peripherals/vn200_serial.h"
#include "mcu_periph/sys_time.h"
#include "math/pprz_algebra.h"
#include "math/pprz_geodetic_float.h"
#include "math/pprz_algebra_float.h"
#include "math/pprz_geodetic_int.h"
#include "math/pprz_orientation_conversion.h"
Data Structures
struct AhrsVectornav
Functions
void ahrs_vectornav_init (void)
Initialize Vectornav struct.
void ahrs_vectornav_event (void)
Event handling for Vectornav.
void ahrs_vectornav_propagate (void)
Read received data.
Variables
struct AhrsVectornav ahrs_vn
Detailed Description
Vectornav VN-200 as AHRS.
Author
Michal Podhradsky micha.nosp@m.l.po.nosp@m.dhrad.nosp@m.sky@.nosp@m.aggie.nosp@m.mail.nosp@m..usu..nosp@m.edu
Definition in file ahrs_vectornav.h.
Data Structure Documentation
AhrsVectornav
struct AhrsVectornav
Definition at line 47 of file ahrs_vectornav.h.
Data Fields
struct Int32Vect3 accel_i
struct OrientationReps body_to_imu body_to_imu rotation
struct Int32Rates gyro_i
uint16_t vn_chksm aux variable for checksum
struct VNData vn_data Data struct.
float vn_freq data frequency
struct VNPacket vn_packet Packet struct.
enum VNStatus vn_status VN status.
Function Documentation
ahrs_vectornav_event()
void ahrs_vectornav_event (void) extern
Event handling for Vectornav.
Definition at line 68 of file ahrs_vectornav.c.
References VNData::accel, AhrsVectornav::accel_i, ACCELS_BFP_OF_REAL, ahrs_vectornav_propagate(), ahrs_vn, foo, get_sys_time_usec(), VNData::gyro, AhrsVectornav::gyro_i, IMU_VECTORNAV_ID, VNPacket::msg_available, RATES_BFP_OF_REAL, vn200_event(), vn200_read_message(), AhrsVectornav::vn_data, AhrsVectornav::vn_freq, and AhrsVectornav::vn_packet.
ahrs_vectornav_init()
void ahrs_vectornav_init (void) extern
Initialize Vectornav struct.
Definition at line 94 of file ahrs_vectornav.c.
References AhrsVectornav::accel_i, ahrs_vn, VNPacket::chksm_error, DefaultPeriodic, foo, VNPacket::framing_error, VNPacket::hdr_error, INT32_VECT3_ZERO, VNPacket::msg_available, VNPacket::msg_idx, VNPacket::noise_error, VNPacket::overrun_error, register_periodic_telemetry(), send_vn_info(), VNPacket::status, AhrsVectornav::vn_data, AhrsVectornav::vn_freq, AhrsVectornav::vn_packet, AhrsVectornav::vn_status, VNMsgSync, and VNNotTracking.
Referenced by ahrs_vectornav_wrapper_init().
ahrs_vectornav_propagate()
void ahrs_vectornav_propagate (void) extern
Read received data.
Definition at line 123 of file ahrs_vectornav.c.
References ahrs_vn, VNData::attitude, AhrsVectornav::body_to_imu, float_quat_of_eulers(), float_rmat_ratemult(), foo, VNData::gyro, orientationGetRMat_f(), stateSetBodyRates_f(), stateSetNedToBodyQuat_f(), and AhrsVectornav::vn_data.
Referenced by ahrs_vectornav_event().
Variable Documentation
ahrs_vn
struct AhrsVectornav ahrs_vn extern
Definition at line 33 of file ahrs_vectornav.c.
Referenced by ahrs_vectornav_event(), ahrs_vectornav_init(), ahrs_vectornav_propagate(), send_euler(), and send_vn_info().