Paparazzi UAS: sw/airborne/modules/ahrs/ahrs_int_utils.h File Reference
ahrs_int_utils.h File Reference
Utility functions for fixed point AHRS implementations.
#include "math/pprz_algebra_int.h"
#include "modules/ahrs/ahrs_magnetic_field_model.h"
#include "modules/ahrs/ahrs_float_utils.h"
Functions
static void ahrs_int_get_euler_from_accel_mag (struct Int32Eulers *e, struct Int32Vect3 *accel, struct Int32Vect3 *mag)
static void ahrs_int_get_quat_from_accel (struct Int32Quat *q, struct Int32Vect3 *accel)
static void ahrs_int_get_quat_from_accel_mag (struct Int32Quat *q, struct Int32Vect3 *accel, struct Int32Vect3 *mag)
Detailed Description
Utility functions for fixed point AHRS implementations.
Definition in file ahrs_int_utils.h.
Function Documentation
ahrs_int_get_euler_from_accel_mag()
static void ahrs_int_get_euler_from_accel_mag (struct Int32Eulers * e, struct Int32Vect3 * accel, struct Int32Vect3 * mag) inline static
Definition at line 40 of file ahrs_int_utils.h.
References ANGLE_BFP_OF_REAL, foo, INT32_ANGLE_NORMALIZE, INT32_TRIG_FRAC, INT_MULT_RSHIFT, Int32Eulers::phi, PPRZ_ITRIG_COS, PPRZ_ITRIG_SIN, Int32Eulers::psi, Int32Eulers::theta, Int32Vect3::x, Int32Vect3::y, and Int32Vect3::z.
ahrs_int_get_quat_from_accel()
static void ahrs_int_get_quat_from_accel (struct Int32Quat * q, struct Int32Vect3 * accel) inline static
Definition at line 80 of file ahrs_int_utils.h.
References ACCELS_FLOAT_OF_BFP, ahrs_float_get_quat_from_accel(), foo, and QUAT_BFP_OF_REAL.
Referenced by ahrs_icq_align().
ahrs_int_get_quat_from_accel_mag()
static void ahrs_int_get_quat_from_accel_mag (struct Int32Quat * q, struct Int32Vect3 * accel, struct Int32Vect3 * mag) inline static
Definition at line 89 of file ahrs_int_utils.h.
References ACCELS_FLOAT_OF_BFP, ahrs_float_get_quat_from_accel_mag(), foo, MAGS_FLOAT_OF_BFP, and QUAT_BFP_OF_REAL.
Referenced by ahrs_icq_align().