Paparazzi UAS: sw/airborne/modules/ahrs/ahrs_int_cmpl_quat_wrapper.h File Reference
ahrs_int_cmpl_quat_wrapper.h File Reference
Paparazzi specific wrapper to run floating point complementary filter.
#include "modules/ahrs/ahrs_int_cmpl_quat.h"
Functions
void ahrs_icq_wrapper_init (void)
void ahrs_int_cmpl_quat_wrapper_enable (uint8_t enable)
Variables
uint8_t ahrs_icq_enable
Detailed Description
Paparazzi specific wrapper to run floating point complementary filter.
Definition in file ahrs_int_cmpl_quat_wrapper.h.
Function Documentation
ahrs_icq_wrapper_init()
void ahrs_icq_wrapper_init (void) extern
Definition at line 242 of file ahrs_int_cmpl_quat_wrapper.c.
References ABI_BROADCAST, accel_cb(), accel_ev, AHRS_ICQ_GPS_ID, AHRS_ICQ_IMU_ID, ahrs_icq_init(), AHRS_ICQ_MAG_ID, ahrs_int_cmpl_quat_wrapper_enable(), AHRS_PRIMARY, aligner_cb(), aligner_ev, DefaultPeriodic, foo, geo_mag_cb(), geo_mag_ev, gps_cb(), gps_ev, gyro_cb(), gyro_ev, mag_cb(), mag_ev, register_periodic_telemetry(), send_bias(), send_euler(), send_filter_status(), send_geo_mag(), and send_quat().
ahrs_int_cmpl_quat_wrapper_enable()
void ahrs_int_cmpl_quat_wrapper_enable (uint8_t enable) extern
Definition at line 270 of file ahrs_int_cmpl_quat_wrapper.c.
References ahrs_icq_enable, foo, STATE_INPUT_ATTITUDE, STATE_INPUT_RATES, and stateSetInputFilter().
Referenced by ahrs_icq_wrapper_init().
Variable Documentation
ahrs_icq_enable
uint8_t ahrs_icq_enable extern
Definition at line 34 of file ahrs_int_cmpl_quat_wrapper.c.
Referenced by ahrs_int_cmpl_quat_wrapper_enable().