Paparazzi UAS: sw/airborne/modules/ahrs/ahrs_madgwick_wrapper.h File Reference
ahrs_madgwick_wrapper.h File Reference
Paparazzi specific wrapper to run Madgwick ahrs filter.
#include "modules/ahrs/ahrs_madgwick.h"
Functions
void ahrs_madgwick_wrapper_init (void)
void ahrs_madgwick_wrapper_enable (uint8_t enable)
Variables
uint8_t ahrs_madgwick_enable
Detailed Description
Paparazzi specific wrapper to run Madgwick ahrs filter.
Definition in file ahrs_madgwick_wrapper.h.
Function Documentation
ahrs_madgwick_wrapper_enable()
void ahrs_madgwick_wrapper_enable (uint8_t enable) extern
Definition at line 199 of file ahrs_madgwick_wrapper.c.
References ahrs_madgwick_enable, foo, STATE_INPUT_ATTITUDE, STATE_INPUT_RATES, and stateSetInputFilter().
Referenced by ahrs_madgwick_wrapper_init().
ahrs_madgwick_wrapper_init()
void ahrs_madgwick_wrapper_init (void) extern
Definition at line 177 of file ahrs_madgwick_wrapper.c.
References ABI_BROADCAST, accel_cb(), accel_ev, AHRS_MADGWICK_IMU_ID, ahrs_madgwick_init(), ahrs_madgwick_wrapper_enable(), AHRS_PRIMARY, aligner_cb(), aligner_ev, DefaultPeriodic, foo, gyro_cb(), gyro_ev, register_periodic_telemetry(), send_att(), and send_filter_status().
Variable Documentation
ahrs_madgwick_enable
uint8_t ahrs_madgwick_enable extern
Definition at line 36 of file ahrs_madgwick_wrapper.c.
Referenced by ahrs_madgwick_wrapper_enable().