Paparazzi UAS: sw/airborne/modules/ahrs/ahrs_float_dcm_wrapper.h File Reference
ahrs_float_dcm_wrapper.h File Reference
Paparazzi specific wrapper to run floating point DCM filter.
#include "modules/ahrs/ahrs_float_dcm.h"
Functions
void ahrs_dcm_wrapper_init (void)
void ahrs_float_dcm_wrapper_enable (uint8_t enable)
Variables
uint8_t ahrs_dcm_enable
Detailed Description
Paparazzi specific wrapper to run floating point DCM filter.
Definition in file ahrs_float_dcm_wrapper.h.
Function Documentation
ahrs_dcm_wrapper_init()
void ahrs_dcm_wrapper_init (void) extern
Definition at line 175 of file ahrs_float_dcm_wrapper.c.
References ABI_BROADCAST, accel_cb(), accel_ev, AHRS_DCM_GPS_ID, AHRS_DCM_IMU_ID, ahrs_dcm_init(), AHRS_DCM_MAG_ID, ahrs_float_dcm_wrapper_enable(), AHRS_PRIMARY, aligner_cb(), aligner_ev, DefaultPeriodic, foo, gps_cb(), gps_ev, gyro_cb(), gyro_ev, mag_cb(), mag_ev, register_periodic_telemetry(), and send_filter_status().
ahrs_float_dcm_wrapper_enable()
void ahrs_float_dcm_wrapper_enable (uint8_t enable) extern
Definition at line 198 of file ahrs_float_dcm_wrapper.c.
References ahrs_dcm_enable, foo, STATE_INPUT_ATTITUDE, STATE_INPUT_RATES, and stateSetInputFilter().
Referenced by ahrs_dcm_wrapper_init().
Variable Documentation
ahrs_dcm_enable
uint8_t ahrs_dcm_enable extern
Definition at line 34 of file ahrs_float_dcm_wrapper.c.
Referenced by ahrs_float_dcm_wrapper_enable().