Paparazzi UAS: sw/airborne/modules/ahrs/ahrs_float_invariant_wrapper.h File Reference
ahrs_float_invariant_wrapper.h File Reference
Paparazzi specific wrapper to run INVARIANT ahrs filter.
#include "modules/ahrs/ahrs_float_invariant.h"
Functions
void ahrs_finv_wrapper_init (void)
void ahrs_float_invariant_wrapper_enable (uint8_t enable)
Variables
uint8_t ahrs_finv_enable
Detailed Description
Paparazzi specific wrapper to run INVARIANT ahrs filter.
Definition in file ahrs_float_invariant_wrapper.h.
Function Documentation
ahrs_finv_wrapper_init()
void ahrs_finv_wrapper_init (void) extern
Definition at line 202 of file ahrs_float_invariant_wrapper.c.
References ABI_BROADCAST, accel_cb(), accel_ev, AHRS_FINV_IMU_ID, AHRS_FINV_MAG_ID, ahrs_float_invariant_init(), ahrs_float_invariant_wrapper_enable(), AHRS_PRIMARY, aligner_cb(), aligner_ev, DefaultPeriodic, foo, geo_mag_cb(), geo_mag_ev, gyro_cb(), gyro_ev, mag_cb(), mag_ev, register_periodic_telemetry(), send_att(), send_filter_status(), and send_geo_mag().
ahrs_float_invariant_wrapper_enable()
void ahrs_float_invariant_wrapper_enable (uint8_t enable) extern
Definition at line 227 of file ahrs_float_invariant_wrapper.c.
References ahrs_finv_enable, foo, STATE_INPUT_ATTITUDE, STATE_INPUT_RATES, and stateSetInputFilter().
Referenced by ahrs_finv_wrapper_init().
Variable Documentation
ahrs_finv_enable
uint8_t ahrs_finv_enable extern
Definition at line 37 of file ahrs_float_invariant_wrapper.c.
Referenced by ahrs_float_invariant_wrapper_enable().