Paparazzi UAS: sw/airborne/modules/ahrs/ahrs_vectornav.c File Reference
ahrs_vectornav.c File Reference
#include "modules/ahrs/ahrs_vectornav.h"
#include "modules/ahrs/ahrs_vectornav_wrapper.h"
#include "modules/core/abi.h"
#include "state.h"
#include "modules/datalink/telemetry.h"
Functions
static void send_vn_info (struct transport_tx *trans, struct link_device *dev)
void ahrs_vectornav_event (void)
Event handling for Vectornav.
void ahrs_vectornav_init (void)
Initialize Vectornav struct.
void ahrs_vectornav_propagate (void)
Read received data.
Variables
struct AhrsVectornav ahrs_vn
Function Documentation
ahrs_vectornav_event()
void ahrs_vectornav_event (void)
Event handling for Vectornav.
Definition at line 68 of file ahrs_vectornav.c.
References VNData::accel, AhrsVectornav::accel_i, ACCELS_BFP_OF_REAL, ahrs_vectornav_propagate(), ahrs_vn, foo, get_sys_time_usec(), VNData::gyro, AhrsVectornav::gyro_i, IMU_VECTORNAV_ID, VNPacket::msg_available, RATES_BFP_OF_REAL, vn200_event(), vn200_read_message(), AhrsVectornav::vn_data, AhrsVectornav::vn_freq, and AhrsVectornav::vn_packet.
ahrs_vectornav_init()
void ahrs_vectornav_init (void)
Initialize Vectornav struct.
Definition at line 94 of file ahrs_vectornav.c.
References AhrsVectornav::accel_i, ahrs_vn, VNPacket::chksm_error, DefaultPeriodic, foo, VNPacket::framing_error, VNPacket::hdr_error, INT32_VECT3_ZERO, VNPacket::msg_available, VNPacket::msg_idx, VNPacket::noise_error, VNPacket::overrun_error, register_periodic_telemetry(), send_vn_info(), VNPacket::status, AhrsVectornav::vn_data, AhrsVectornav::vn_freq, AhrsVectornav::vn_packet, AhrsVectornav::vn_status, VNMsgSync, and VNNotTracking.
Referenced by ahrs_vectornav_wrapper_init().
ahrs_vectornav_propagate()
void ahrs_vectornav_propagate (void)
Read received data.
Definition at line 123 of file ahrs_vectornav.c.
References ahrs_vn, VNData::attitude, AhrsVectornav::body_to_imu, float_quat_of_eulers(), float_rmat_ratemult(), foo, VNData::gyro, orientationGetRMat_f(), stateSetBodyRates_f(), stateSetNedToBodyQuat_f(), and AhrsVectornav::vn_data.
Referenced by ahrs_vectornav_event().
send_vn_info()
static void send_vn_info (struct transport_tx * trans, struct link_device * dev) static
Definition at line 39 of file ahrs_vectornav.c.
References ahrs_vn, VNPacket::chksm_error, VNPacket::counter, dev, VNData::err, foo, VNPacket::hdr_error, VNData::mode, FloatEulers::phi, FloatEulers::psi, FloatEulers::theta, VNData::timestamp, AhrsVectornav::vn_data, AhrsVectornav::vn_freq, AhrsVectornav::vn_packet, and VNData::ypr_u.
Referenced by ahrs_vectornav_init().
Variable Documentation
ahrs_vn
struct AhrsVectornav ahrs_vn
Definition at line 33 of file ahrs_vectornav.c.
Referenced by ahrs_vectornav_event(), ahrs_vectornav_init(), ahrs_vectornav_propagate(), send_euler(), and send_vn_info().