Paparazzi UAS: sw/airborne/modules/air_data/air_data.c File Reference
air_data.c File Reference
Air Data interface.
#include "modules/air_data/air_data.h"
#include "modules/core/abi.h"
#include "math/pprz_isa.h"
#include "state.h"
#include "generated/airframe.h"
#include "generated/modules.h"
#include "pprzlink/dl_protocol.h"
#include "modules/datalink/telemetry.h"
Macros
#define AIR_DATA_BARO_ABS_ID ABI_BROADCAST
ABI binding for absolute pressure.
#define AIR_DATA_BARO_DIFF_ID ABI_BROADCAST
ABI binding for differential pressure.
#define AIR_DATA_TEMPERATURE_ID ABI_BROADCAST
ABI binding for temperature.
#define AIR_DATA_AIRSPEED_ID ABI_BROADCAST
ABI binding for airspeed.
#define AIR_DATA_INCIDENCE_ID ABI_BROADCAST
ABI binding for incidence angles.
#define AIR_DATA_TAS_FACTOR 1.0
Default factor to convert estimated airspeed (EAS) to true airspeed (TAS)
#define AIR_DATA_CALC_AIRSPEED TRUE
Calculate Airspeed from differential pressure by default.
#define AIR_DATA_CALC_TAS_FACTOR TRUE
Calculate tas_factor from temp and pressure by default.
#define AIR_DATA_CALC_AMSL_BARO FALSE
Don't calculate AMSL from baro and QNH by default.
Functions
static void pressure_abs_cb (uint8_t sender_id, uint32_t stamp, float pressure)
static void pressure_diff_cb (uint8_t sender_id, float pressure)
static void temperature_cb (uint8_t sender_id, float temp)
static void airspeed_cb (uint8_t sender_id, float eas)
static void incidence_cb (uint8_t sender_id, uint8_t flag, float aoa, float sideslip)
static void send_baro_raw (struct transport_tx *trans, struct link_device *dev)
static void send_air_data (struct transport_tx *trans, struct link_device *dev)
static void send_amsl (struct transport_tx *trans, struct link_device *dev)
void air_data_init (void)
AirData initialization.
float air_data_get_amsl (void)
Return AMSL (altitude AboveSeaLevel).
void air_data_periodic (void)
Check health.
void air_data_parse_WIND_INFO (struct link_device *dev, struct transport_tx *trans, uint8_t *buf)
Parse datalink wind info message.
float eas_from_dynamic_pressure (float q)
Calculate equivalent airspeed from dynamic pressure.
float get_tas_factor (float p, float t)
Calculate true airspeed (TAS) factor.
static void compute_tas_factor (void)
Internal utility function to compute current tas factor if needed.
float tas_from_eas (float eas)
Calculate true airspeed from equivalent airspeed.
float eas_from_tas (float tas)
Calculate equivalent airspeed from true airspeed.
float tas_from_dynamic_pressure (float q)
Calculate true airspeed from dynamic pressure.
Variables
struct AirData air_data
global AirData state
static abi_event pressure_abs_ev
static abi_event pressure_diff_ev
static abi_event temperature_ev
static abi_event airspeed_ev
static abi_event incidence_ev
static uint8_t baro_health_counter
counter to check baro health
Detailed Description
Air Data interface.
pressures
airspeed
angle of attack and sideslip
wind
Definition in file air_data.c.
Macro Definition Documentation
AIR_DATA_AIRSPEED_ID
#define AIR_DATA_AIRSPEED_ID ABI_BROADCAST
ABI binding for airspeed.
Definition at line 67 of file air_data.c.
AIR_DATA_BARO_ABS_ID
#define AIR_DATA_BARO_ABS_ID ABI_BROADCAST
ABI binding for absolute pressure.
Definition at line 46 of file air_data.c.
AIR_DATA_BARO_DIFF_ID
#define AIR_DATA_BARO_DIFF_ID ABI_BROADCAST
ABI binding for differential pressure.
Definition at line 53 of file air_data.c.
AIR_DATA_CALC_AIRSPEED
#define AIR_DATA_CALC_AIRSPEED TRUE
Calculate Airspeed from differential pressure by default.
Definition at line 85 of file air_data.c.
AIR_DATA_CALC_AMSL_BARO
#define AIR_DATA_CALC_AMSL_BARO FALSE
Don't calculate AMSL from baro and QNH by default.
Definition at line 95 of file air_data.c.
AIR_DATA_CALC_TAS_FACTOR
#define AIR_DATA_CALC_TAS_FACTOR TRUE
Calculate tas_factor from temp and pressure by default.
Definition at line 90 of file air_data.c.
AIR_DATA_INCIDENCE_ID
#define AIR_DATA_INCIDENCE_ID ABI_BROADCAST
ABI binding for incidence angles.
Definition at line 74 of file air_data.c.
AIR_DATA_TAS_FACTOR
#define AIR_DATA_TAS_FACTOR 1.0
Default factor to convert estimated airspeed (EAS) to true airspeed (TAS)
Definition at line 80 of file air_data.c.
AIR_DATA_TEMPERATURE_ID
#define AIR_DATA_TEMPERATURE_ID ABI_BROADCAST
ABI binding for temperature.
Definition at line 60 of file air_data.c.
Function Documentation
air_data_get_amsl()
float air_data_get_amsl (void)
Return AMSL (altitude AboveSeaLevel).
If AMSL from baro is valid, return that, otherwise from gps.
Definition at line 259 of file air_data.c.
References air_data, LlaCoor_f::alt, AirData::amsl_baro, AirData::amsl_baro_valid, and stateGetPositionLla_f().
Referenced by compute_tas_factor().
air_data_init()
void air_data_init (void)
AirData initialization.
Called at startup. Bind ABI messages
Definition at line 218 of file air_data.c.
References air_data, AIR_DATA_AIRSPEED_ID, AIR_DATA_BARO_ABS_ID, AIR_DATA_BARO_DIFF_ID, AIR_DATA_CALC_AIRSPEED, AIR_DATA_CALC_AMSL_BARO, AIR_DATA_CALC_TAS_FACTOR, AIR_DATA_INCIDENCE_ID, AIR_DATA_TAS_FACTOR, AIR_DATA_TEMPERATURE_ID, AirData::airspeed, airspeed_cb(), airspeed_ev, AirData::amsl_baro, AirData::amsl_baro_valid, AirData::aoa, baro_health_counter, AirData::calc_airspeed, AirData::calc_amsl_baro, AirData::calc_qnh_once, AirData::calc_tas_factor, DefaultPeriodic, AirData::differential, foo, incidence_cb(), incidence_ev, AirData::pressure, pressure_abs_cb(), pressure_abs_ev, pressure_diff_cb(), pressure_diff_ev, AirData::qnh, register_periodic_telemetry(), send_air_data(), send_amsl(), send_baro_raw(), AirData::sideslip, AirData::tas, AirData::tas_factor, AirData::temperature, temperature_cb(), temperature_ev, AirData::wind_dir, and AirData::wind_speed.
air_data_parse_WIND_INFO()
void air_data_parse_WIND_INFO (struct link_device * dev, struct transport_tx * trans, uint8_t * buf)
Parse datalink wind info message.
Definition at line 279 of file air_data.c.
References air_data, AirData::airspeed, dev, eas_from_tas(), float_vect2_norm(), foo, stateGetAirspeed_f(), stateSetAirspeed_f(), stateSetHorizontalWindspeed_f(), stateSetVerticalWindspeed_f(), AirData::tas, AirData::wind_dir, AirData::wind_speed, FloatVect2::x, and FloatVect2::y.
air_data_periodic()
void air_data_periodic (void)
Check health.
Needs to be called periodically.
Definition at line 269 of file air_data.c.
References air_data, AirData::amsl_baro_valid, and baro_health_counter.
airspeed_cb()
static void airspeed_cb (uint8_t sender_id, float eas) static
Definition at line 163 of file air_data.c.
References air_data, AirData::airspeed, AirData::calc_airspeed, foo, stateSetAirspeed_f(), AirData::tas, and tas_from_eas().
Referenced by air_data_init().
compute_tas_factor()
static void compute_tas_factor (void) static
Internal utility function to compute current tas factor if needed.
Definition at line 368 of file air_data.c.
References air_data, air_data_get_amsl(), AirData::calc_tas_factor, CelsiusOfKelvin, foo, get_tas_factor(), p, pprz_isa_pressure_of_altitude(), pprz_isa_temperature_of_altitude(), AirData::pressure, AirData::tas_factor, and AirData::temperature.
Referenced by eas_from_tas(), and tas_from_eas().
eas_from_dynamic_pressure()
float eas_from_dynamic_pressure (float q)
Calculate equivalent airspeed from dynamic pressure.
Dynamic pressure (also called impact pressure) is the difference between total(pitot) and static pressure.
Airspeed from dynamic pressure:
with as air density. Using standard sea level air density gives you equivalent airspeed (EAS).
Parameters
q dynamic pressure in Pa
Returns
equivalent airspeed in m/s
Definition at line 322 of file air_data.c.
References foo, PPRZ_ISA_AIR_DENSITY, and sign().
Referenced by pressure_diff_cb(), and tas_from_dynamic_pressure().
eas_from_tas()
float eas_from_tas (float tas)
Calculate equivalent airspeed from true airspeed.
EAS from True airspeed (TAS): EAS = TAS / air_data.tas_factor
Parameters
tas true airspeed (TAS) in m/s
Returns
equivalent airspeed in m/s
Definition at line 410 of file air_data.c.
References air_data, compute_tas_factor(), and AirData::tas_factor.
Referenced by air_data_parse_WIND_INFO(), and wind_estimation_quadrotor_periodic().
get_tas_factor()
float get_tas_factor (float p, float t)
Calculate true airspeed (TAS) factor.
TAS = tas_factor * EAS
True airspeed (TAS) from equivalent airspeed (EAS):
and where
is the air pressure at the flight condition
is the air pressure at sea level = 101325 Pa
is the air temperature at the flight condition
is the air temperature at sea level = 288.15 K
Parameters
p current air pressure in Pa
t current air temperature in degrees Celcius
Returns
tas factor
Definition at line 355 of file air_data.c.
References foo, KelvinOfCelsius, p, PPRZ_ISA_SEA_LEVEL_PRESSURE, and PPRZ_ISA_SEA_LEVEL_TEMP.
Referenced by compute_tas_factor(), and temperature_cb().
incidence_cb()
static void incidence_cb (uint8_t sender_id, uint8_t flag, float aoa, float sideslip) static
Definition at line 174 of file air_data.c.
References air_data, AirData::aoa, foo, AirData::sideslip, stateSetAngleOfAttack_f(), and stateSetSideslip_f().
Referenced by air_data_init().
pressure_abs_cb()
static void pressure_abs_cb (uint8_t sender_id, uint32_t stamp, float pressure) static
FIXME: use height above MSL (geoid) and not WGS84 ellipsoid here
Definition at line 114 of file air_data.c.
References air_data, LlaCoor_f::alt, AirData::amsl_baro, AirData::amsl_baro_valid, baro_health_counter, AirData::calc_amsl_baro, AirData::calc_qnh_once, foo, h(), State::ned_initialized_f, pprz_isa_height_of_pressure_full(), pprz_isa_ref_pressure_of_height_full(), AirData::pressure, AirData::qnh, state, stateGetHmslOrigin_f(), stateGetLlaOrigin_f(), stateGetPositionLla_f(), and stateIsGlobalCoordinateValid().
Referenced by air_data_init().
pressure_diff_cb()
static void pressure_diff_cb (uint8_t sender_id, float pressure) static
Definition at line 141 of file air_data.c.
References air_data, AirData::airspeed, AirData::calc_airspeed, AirData::differential, eas_from_dynamic_pressure(), foo, AirData::pressure, stateSetAirspeed_f(), AirData::tas, and tas_from_eas().
Referenced by air_data_init().
send_air_data()
static void send_air_data (struct transport_tx * trans, struct link_device * dev) static
Definition at line 197 of file air_data.c.
References air_data, AirData::airspeed, AirData::amsl_baro, dev, AirData::differential, foo, AirData::pressure, AirData::qnh, AirData::tas, and AirData::temperature.
Referenced by air_data_init().
send_amsl()
static void send_amsl (struct transport_tx * trans, struct link_device * dev) static
Definition at line 206 of file air_data.c.
References air_data, LlaCoor_f::alt, AirData::amsl_baro, dev, foo, and stateGetPositionLla_f().
Referenced by air_data_init().
send_baro_raw()
static void send_baro_raw (struct transport_tx * trans, struct link_device * dev) static
Definition at line 191 of file air_data.c.
References air_data, dev, AirData::differential, foo, and AirData::pressure.
Referenced by air_data_init().
tas_from_dynamic_pressure()
float tas_from_dynamic_pressure (float q)
Calculate true airspeed from dynamic pressure.
Dynamic pressure (also called impact pressure) is the difference between total(pitot) and static pressure.
Parameters
q dynamic pressure in Pa
Returns
true airspeed in m/s
Definition at line 424 of file air_data.c.
References eas_from_dynamic_pressure(), and tas_from_eas().
Referenced by pressure_diff_cb().
tas_from_eas()
float tas_from_eas (float eas)
Calculate true airspeed from equivalent airspeed.
True airspeed (TAS) from EAS: TAS = air_data.tas_factor * EAS
Parameters
eas equivalent airspeed (EAS) in m/s
Returns
true airspeed in m/s
Definition at line 395 of file air_data.c.
References air_data, compute_tas_factor(), foo, and AirData::tas_factor.
Referenced by airspeed_cb(), airspeed_cb(), pressure_diff_cb(), and tas_from_dynamic_pressure().
temperature_cb()
static void temperature_cb (uint8_t sender_id, float temp) static
Definition at line 153 of file air_data.c.
References air_data, AirData::airspeed, baro_health_counter, AirData::calc_tas_factor, get_tas_factor(), AirData::pressure, AirData::tas_factor, and AirData::temperature.
Referenced by air_data_init().
Variable Documentation
air_data
struct AirData air_data
global AirData state
Definition at line 41 of file air_data.c.
Referenced by air_data_get_amsl(), air_data_init(), air_data_parse_WIND_INFO(), air_data_periodic(), airspeed_cb(), compute_tas_factor(), eas_from_tas(), incidence_cb(), pressure_abs_cb(), pressure_diff_cb(), save_speeds(), send_air_data(), send_amsl(), send_baro_raw(), send_windtunnel_meas(), tas_from_eas(), and temperature_cb().
airspeed_ev
abi_event airspeed_ev static
Definition at line 69 of file air_data.c.
Referenced by air_data_init().
baro_health_counter
uint8_t baro_health_counter static
counter to check baro health
Definition at line 111 of file air_data.c.
Referenced by air_data_init(), air_data_periodic(), pressure_abs_cb(), and temperature_cb().
incidence_ev
abi_event incidence_ev static
Definition at line 76 of file air_data.c.
Referenced by air_data_init().
pressure_abs_ev
abi_event pressure_abs_ev static
Definition at line 48 of file air_data.c.
Referenced by air_data_init().
pressure_diff_ev
abi_event pressure_diff_ev static
Definition at line 55 of file air_data.c.
Referenced by air_data_init().
temperature_ev
abi_event temperature_ev static
Definition at line 62 of file air_data.c.
Referenced by air_data_init().