Paparazzi UAS: sw/airborne/modules/sensors/airspeed_ets.h File Reference
airspeed_ets.h File Reference
Driver for the EagleTree Systems Airspeed Sensor.
#include "std.h"
#include "mcu_periph/i2c.h"
Functions
void airspeed_ets_init (void)
void airspeed_ets_read_periodic (void)
void airspeed_ets_read_event (void)
static void AirspeedEtsEvent (void)
Variables
uint16_t airspeed_ets_raw
uint16_t airspeed_ets_offset
bool airspeed_ets_valid
float airspeed_ets
struct i2c_transaction airspeed_ets_i2c_trans
Detailed Description
Driver for the EagleTree Systems Airspeed Sensor.
Has only been tested with V3 of the sensor hardware.
Notes: Connect directly to TWOG/Tiny I2C port. Multiple sensors can be chained together. Sensor should be in the proprietary mode (default) and not in 3rd party mode.
Sensor module wire assignments: Red wire: 5V White wire: Ground Yellow wire: SDA Brown wire: SCL
Definition in file airspeed_ets.h.
Function Documentation
airspeed_ets_init()
void airspeed_ets_init (void) extern
Definition at line 159 of file airspeed_ets.c.
References airspeed_ets, airspeed_ets_buffer, airspeed_ets_buffer_idx, airspeed_ets_cnt, airspeed_ets_delay_done, airspeed_ets_delay_time, airspeed_ets_downlink(), airspeed_ets_i2c_done, airspeed_ets_i2c_trans, AIRSPEED_ETS_LOWPASS_TAU, AIRSPEED_ETS_NBSAMPLES_AVRG, airspeed_ets_offset, airspeed_ets_offset_init, AIRSPEED_ETS_OFFSET_NBSAMPLES_AVRG, AIRSPEED_ETS_OFFSET_NBSAMPLES_INIT, airspeed_ets_offset_tmp, airspeed_ets_raw, airspeed_ets_valid, airspeed_filter, DefaultPeriodic, foo, I2CTransDone, init_butterworth_2_low_pass(), register_periodic_telemetry(), i2c_transaction::status, and SysTimeTimerStart.
airspeed_ets_read_event()
void airspeed_ets_read_event (void) extern
Definition at line 214 of file airspeed_ets.c.
References airspeed_ets, airspeed_ets_buffer, airspeed_ets_buffer_idx, airspeed_ets_cnt, airspeed_ets_i2c_trans, AIRSPEED_ETS_ID, AIRSPEED_ETS_NBSAMPLES_AVRG, AIRSPEED_ETS_OFFSET, airspeed_ets_offset, airspeed_ets_offset_init, AIRSPEED_ETS_OFFSET_MAX, AIRSPEED_ETS_OFFSET_MIN, AIRSPEED_ETS_OFFSET_NBSAMPLES_AVRG, airspeed_ets_offset_tmp, airspeed_ets_raw, AIRSPEED_ETS_SCALE, airspeed_ets_valid, airspeed_filter, i2c_transaction::buf, GpsState::course, GpsState::fix, foo, gps, GpsState::gspeed, GpsState::hmsl, I2CTransDone, LlaCoor_i::lat, GpsState::lla_pos, LlaCoor_i::lon, GpsState::ned_vel, pprzLogFile, stateSetAirspeed_f(), i2c_transaction::status, GpsState::tow, update_butterworth_2_low_pass(), GpsState::week, and NedCoor_i::z.
Referenced by AirspeedEtsEvent().
airspeed_ets_read_periodic()
void airspeed_ets_read_periodic (void) extern
Definition at line 198 of file airspeed_ets.c.
References AIRSPEED_ETS_ADDR, airspeed_ets_delay_done, airspeed_ets_delay_time, AIRSPEED_ETS_I2C_DEV, airspeed_ets_i2c_trans, AIRSPEED_ETS_START_DELAY, foo, i2c_receive(), I2CTransDone, stateSetAirspeed_f(), i2c_transaction::status, SysTimeTimer, and USEC_OF_SEC.
AirspeedEtsEvent()
static void AirspeedEtsEvent (void) inline static
Definition at line 58 of file airspeed_ets.h.
References airspeed_ets_i2c_trans, airspeed_ets_read_event(), I2CTransDone, I2CTransFailed, I2CTransSuccess, and i2c_transaction::status.
Variable Documentation
airspeed_ets
float airspeed_ets extern
Definition at line 126 of file airspeed_ets.c.
Referenced by airspeed_ets_downlink(), airspeed_ets_init(), and airspeed_ets_read_event().
airspeed_ets_i2c_trans
struct i2c_transaction airspeed_ets_i2c_trans extern
Definition at line 130 of file airspeed_ets.c.
Referenced by airspeed_ets_init(), airspeed_ets_read_event(), airspeed_ets_read_periodic(), and AirspeedEtsEvent().
airspeed_ets_offset
uint16_t airspeed_ets_offset extern
Definition at line 124 of file airspeed_ets.c.
Referenced by airspeed_ets_downlink(), airspeed_ets_init(), and airspeed_ets_read_event().
airspeed_ets_raw
uint16_t airspeed_ets_raw extern
Definition at line 123 of file airspeed_ets.c.
Referenced by airspeed_ets_downlink(), airspeed_ets_init(), and airspeed_ets_read_event().
airspeed_ets_valid
bool airspeed_ets_valid extern
Definition at line 125 of file airspeed_ets.c.
Referenced by airspeed_ets_init(), and airspeed_ets_read_event().