Paparazzi UAS: sw/airborne/modules/sensors/airspeed_uADC.h File Reference
airspeed_uADC.h File Reference
UART interface for Aeroprobe uADC air data computer.
#include "std.h"
Functions
void airspeed_uADC_init (void)
void airspeed_uADC_event (void)
void airspeed_uADC_periodic (void)
Detailed Description
UART interface for Aeroprobe uADC air data computer.
Definition in file airspeed_uADC.h.
Function Documentation
airspeed_uADC_event()
void airspeed_uADC_event (void) extern
Definition at line 197 of file airspeed_uADC.c.
References airspeed_uadc_parse(), foo, uart_char_available(), and uart_getch().
airspeed_uADC_init()
void airspeed_uADC_init (void) extern
Definition at line 193 of file airspeed_uADC.c.
airspeed_uADC_periodic()
void airspeed_uADC_periodic (void) extern
Definition at line 205 of file airspeed_uADC.c.
References altitude, checksum, counter, course, DefaultChannel, DefaultDevice, foo, and pressures.