Paparazzi UAS: sw/airborne/modules/checks/airspeed_consistency.h File Reference
airspeed_consistency.h File Reference
#include <std.h>
#include "math/pprz_circfit_float.h"
#include "filters/low_pass_filter.h"
Data Structures
struct asc_t
Macros
#define AIRSPEED_CONSISTENCY_BUFFER_SIZE 255
Functions
void airspeed_consistency_init (void)
void airspeed_consistency_periodic (void)
void airspeed_consistency_reset (bool reset)
Variables
bool asc_reset
Detailed Description
Author
Noah Wechtler noahw.nosp@m.echt.nosp@m.ler@t.nosp@m.udel.nosp@m.ft.nl Check the consistency of airspeed measurements while flying circles
Definition in file airspeed_consistency.h.
Data Structure Documentation
asc_t
struct asc_t
Definition at line 40 of file airspeed_consistency.h.
Data Fields
struct circle_t as
enum CircFitStatus_t as_circ_status
float as_E[AIRSPEED_CONSISTENCY_BUFFER_SIZE]
float as_N[AIRSPEED_CONSISTENCY_BUFFER_SIZE]
bool filled
struct circle_t gs
enum CircFitStatus_t gs_circ_status
float gs_E[AIRSPEED_CONSISTENCY_BUFFER_SIZE]
float gs_N[AIRSPEED_CONSISTENCY_BUFFER_SIZE]
uint16_t i
float ratio
Macro Definition Documentation
AIRSPEED_CONSISTENCY_BUFFER_SIZE
#define AIRSPEED_CONSISTENCY_BUFFER_SIZE 255
Definition at line 31 of file airspeed_consistency.h.
Function Documentation
airspeed_consistency_init()
void airspeed_consistency_init (void) extern
Definition at line 62 of file airspeed_consistency.c.
References foo, init_butterworth_2_low_pass(), NAVIGATION_FREQUENCY, reset_speeds(), and tas_filt.
airspeed_consistency_periodic()
void airspeed_consistency_periodic (void) extern
Definition at line 68 of file airspeed_consistency.c.
References AIRSPEED_CONSISTENCY_INTERVAL, AIRSPEED_CONSISTENCY_MIN_SAMPLES, ARRIVED_AT_WAYPOINT, asc_t::as, asc_t::as_circ_status, asc, NavCircle_t::center, CIRC_FIT_OK, NavBase_t::circle, asc_t::filled, float_vect2_norm(), foo, asc_t::gs_circ_status, RotorcraftNavigation::horizontal_mode, asc_t::i, if(), nav, NAV_HORIZONTAL_MODE_CIRCLE, nav_rotorcraft_base, circle_t::r, NavCircle_t::radius, reset_speeds(), save_speeds(), stateGetPositionEnu_f(), and VECT2_DIFF.
airspeed_consistency_reset()
void airspeed_consistency_reset (bool reset) extern
Definition at line 139 of file airspeed_consistency.c.
References reset_speeds().
Variable Documentation
asc_reset
bool asc_reset extern
Definition at line 53 of file airspeed_consistency.c.