Paparazzi UAS: sw/airborne/modules/sensors/airspeed_uavcan.h File Reference
airspeed_uavcan.h File Reference
Airspeed sensor on the uavcan bus.
#include "std.h"
Data Structures
struct airspeed_uavcan_t
Functions
void airspeed_uavcan_init (void)
void airspeed_uavcan_autoset_offset (bool set)
Variables
struct airspeed_uavcan_t airspeed_uavcan
Detailed Description
Airspeed sensor on the uavcan bus.
Definition in file airspeed_uavcan.h.
Data Structure Documentation
airspeed_uavcan_t
struct airspeed_uavcan_t
Definition at line 32 of file airspeed_uavcan.h.
Data Fields
float diff_p Differential pressure.
float diff_p_offset Differential pressure offset.
float diff_p_scale Differential pressure scale.
float temperature Temperature in Celsius.
Function Documentation
airspeed_uavcan_autoset_offset()
void airspeed_uavcan_autoset_offset (bool set) extern
Definition at line 140 of file airspeed_uavcan.c.
References airspeed_uavcan, airspeed_uavcan_t::diff_p, and airspeed_uavcan_t::diff_p_offset.
airspeed_uavcan_init()
void airspeed_uavcan_init (void) extern
Definition at line 122 of file airspeed_uavcan.c.
References airspeed_filter, airspeed_uavcan, airspeed_uavcan_cb(), AIRSPEED_UAVCAN_DIFF_P_SCALE, airspeed_uavcan_downlink(), airspeed_uavcan_ev, DefaultPeriodic, airspeed_uavcan_t::diff_p_scale, foo, init_butterworth_2_low_pass(), register_periodic_telemetry(), and uavcan_bind().
Variable Documentation
airspeed_uavcan
struct airspeed_uavcan_t airspeed_uavcan extern
Definition at line 57 of file airspeed_uavcan.c.
Referenced by airspeed_uavcan_autoset_offset(), airspeed_uavcan_cb(), airspeed_uavcan_downlink(), and airspeed_uavcan_init().