Paparazzi UAS: sw/airborne/modules/sensors/airspeed_ms45xx_i2c.h File Reference
airspeed_ms45xx_i2c.h File Reference
Airspeed driver for the MS45xx pressure sensor via I2C.
#include "std.h"
Data Structures
struct AirspeedMs45xx
Functions
void airspeed_ms45xx_i2c_change_tau (float new_tau)
void ms45xx_i2c_init (void)
void ms45xx_i2c_periodic (void)
void ms45xx_i2c_event (void)
Variables
struct AirspeedMs45xx ms45xx
Detailed Description
Airspeed driver for the MS45xx pressure sensor via I2C.
Definition in file airspeed_ms45xx_i2c.h.
Data Structure Documentation
AirspeedMs45xx
struct AirspeedMs45xx
Definition at line 31 of file airspeed_ms45xx_i2c.h.
Data Fields
float airspeed Airspeed in m/s estimated from (differential) pressure.
bool autoset_offset Set offset value from current filtered value.
float lowpass_tau Time constant for low pass filter.
bool offset_set Offset is set once.
float pressure (differential) pressure in Pascal
float pressure_offset Offset in Pascal.
float pressure_scale Scaling factor from raw measurement to Pascal.
bool pressure_type Pressure type Differential of Gauge.
uint16_t raw_p Raw pressure.
int16_t temperature Temperature in 0.1 deg Celcius.
Function Documentation
airspeed_ms45xx_i2c_change_tau()
void airspeed_ms45xx_i2c_change_tau (float new_tau) extern
Definition at line 224 of file airspeed_ms45xx_i2c.c.
References foo, get_butterworth_2_low_pass(), init_butterworth_2_low_pass(), AirspeedMs45xx::lowpass_tau, ms45xx, and ms45xx_filter.
ms45xx_i2c_event()
void ms45xx_i2c_event (void) extern
Definition at line 244 of file airspeed_ms45xx_i2c.c.
References AirspeedMs45xx::airspeed, AUTOSET_NB_MAX, AirspeedMs45xx::autoset_offset, i2c_transaction::buf, foo, I2CTransDone, I2CTransFailed, I2CTransSuccess, ms45xx, ms45xx_filter, MS45XX_RHO_DIV_2, MS45XX_SENDER_ID, ms45xx_trans, AirspeedMs45xx::offset_set, AirspeedMs45xx::pressure, AirspeedMs45xx::pressure_offset, AirspeedMs45xx::pressure_scale, AirspeedMs45xx::raw_p, sign(), i2c_transaction::status, status, AirspeedMs45xx::temperature, and update_butterworth_2_low_pass().
ms45xx_i2c_init()
void ms45xx_i2c_init (void) extern
Definition at line 194 of file airspeed_ms45xx_i2c.c.
References AirspeedMs45xx::airspeed, DefaultPeriodic, foo, I2CTransDone, init_butterworth_2_low_pass(), AirspeedMs45xx::lowpass_tau, ms45xx, ms45xx_downlink(), ms45xx_filter, MS45XX_LOWPASS_TAU, MS45XX_PRESSURE_OFFSET, MS45XX_PRESSURE_SCALE, MS45XX_PRESSURE_TYPE, ms45xx_trans, AirspeedMs45xx::offset_set, preflight_check_register(), AirspeedMs45xx::pressure, AirspeedMs45xx::pressure_offset, AirspeedMs45xx::pressure_scale, AirspeedMs45xx::pressure_type, AirspeedMs45xx::raw_p, register_periodic_telemetry(), i2c_transaction::status, and AirspeedMs45xx::temperature.
ms45xx_i2c_periodic()
void ms45xx_i2c_periodic (void) extern
Definition at line 234 of file airspeed_ms45xx_i2c.c.
References i2c_receive(), I2CTransDone, MS45XX_I2C_ADDR, MS45XX_I2C_DEV, ms45xx_trans, and i2c_transaction::status.
Variable Documentation
ms45xx
struct AirspeedMs45xx ms45xx extern
Definition at line 161 of file airspeed_ms45xx_i2c.c.
Referenced by airspeed_ms45xx_i2c_change_tau(), ms45xx_downlink(), ms45xx_i2c_event(), and ms45xx_i2c_init().