Paparazzi UAS: sw/airborne/modules/sensors/airspeed_sdp3x.h File Reference
airspeed_sdp3x.h File Reference
Airspeed driver for the SDP3X pressure sensor via I2C.
#include "std.h"
Data Structures
struct AirspeedSdp3x
Functions
void sdp3x_init (void)
void sdp3x_periodic (void)
void sdp3x_event (void)
Variables
struct AirspeedSdp3x sdp3x
Detailed Description
Airspeed driver for the SDP3X pressure sensor via I2C.
Definition in file airspeed_sdp3x.h.
Data Structure Documentation
AirspeedSdp3x
struct AirspeedSdp3x
Definition at line 30 of file airspeed_sdp3x.h.
Data Fields
float airspeed Airspeed in m/s estimated from (differential) pressure.
float airspeed_scale Quadratic scale factor to convert (differential) pressure to airspeed.
bool autoset_offset Set offset value from current filtered value.
bool initialized init flag
float pressure (differential) pressure in Pascal
float pressure_offset Offset in Pascal.
float pressure_scale Scaling factor from raw measurement to Pascal.
uint16_t raw_p raw value from chip
bool sync_send Flag to enable sending every new measurement via telemetry for debugging purpose.
float temperature Temperature in deg Celcius.
Function Documentation
sdp3x_event()
void sdp3x_event (void) extern
Definition at line 201 of file airspeed_sdp3x.c.
References AirspeedSdp3x::airspeed, AirspeedSdp3x::airspeed_scale, AIRSPEED_SDP3X_ID, AUTOSET_NB_MAX, AirspeedSdp3x::autoset_offset, i2c_transaction::buf, DefaultChannel, DefaultDevice, foo, I2CTransDone, I2CTransFailed, I2CTransSuccess, AirspeedSdp3x::initialized, AirspeedSdp3x::pressure, AirspeedSdp3x::pressure_offset, AirspeedSdp3x::pressure_scale, AirspeedSdp3x::raw_p, sdp3x, sdp3x_crc(), sdp3x_downlink(), sdp3x_filter, SDP3X_SCALE_TEMPERATURE, SDP3X_SENDER_ID, sdp3x_trans, i2c_transaction::status, AirspeedSdp3x::sync_send, AirspeedSdp3x::temperature, and update_butterworth_2_low_pass().
sdp3x_init()
void sdp3x_init (void) extern
Definition at line 156 of file airspeed_sdp3x.c.
References AirspeedSdp3x::airspeed, AirspeedSdp3x::airspeed_scale, AirspeedSdp3x::autoset_offset, DefaultPeriodic, foo, I2CTransDone, init_butterworth_2_low_pass(), AirspeedSdp3x::initialized, AirspeedSdp3x::pressure, AirspeedSdp3x::pressure_offset, AirspeedSdp3x::pressure_scale, register_periodic_telemetry(), sdp3x, SDP3X_AIRSPEED_SCALE, sdp3x_downlink(), sdp3x_filter, SDP3X_LOWPASS_TAU, SDP3X_PRESSURE_OFFSET, SDP3X_PRESSURE_SCALE, SDP3X_SYNC_SEND, sdp3x_trans, i2c_transaction::status, AirspeedSdp3x::sync_send, and AirspeedSdp3x::temperature.
sdp3x_periodic()
void sdp3x_periodic (void) extern
Definition at line 180 of file airspeed_sdp3x.c.
References i2c_transaction::buf, foo, i2c_receive(), i2c_transmit(), I2CTransDone, AirspeedSdp3x::initialized, sdp3x, SDP3X_I2C_ADDR, SDP3X_MODE, sdp3x_trans, and i2c_transaction::status.
Variable Documentation
sdp3x
struct AirspeedSdp3x sdp3x extern
Definition at line 115 of file airspeed_sdp3x.c.
Referenced by sdp3x_downlink(), sdp3x_event(), sdp3x_init(), and sdp3x_periodic().