Paparazzi UAS: sw/airborne/modules/checks/airspeed_consistency.c File Reference
airspeed_consistency.c File Reference
#include <stdio.h>
#include "modules/checks/airspeed_consistency.h"
#include "navigation.h"
#include "state.h"
#include "filters/low_pass_filter.h"
#include "generated/modules.h"
#include "modules/core/abi.h"
#include "modules/datalink/telemetry.h"
#include "modules/nav/nav_rotorcraft_base.h"
Macros
#define AIRSPEED_CONSISTENCY_MIN_SAMPLES 20
#define AIRSPEED_CONSISTENCY_INTERVAL 10
Functions
static void save_speeds (void)
static void reset_speeds (void)
static enum CircFitStatus_t get_circle_from_speeds (struct circle_t *c, float *N, float *E)
void airspeed_consistency_init (void)
void airspeed_consistency_periodic (void)
void airspeed_consistency_reset (bool reset)
Variables
bool asc_reset = false
static struct asc_t asc = {0}
static Butterworth2LowPass tas_filt
Detailed Description
Author
Noah Wechtler noahw.nosp@m.echt.nosp@m.ler@t.nosp@m.udel.nosp@m.ft.nl Simple consistency check for airspeed measurements while flying circles
Definition in file airspeed_consistency.c.
Macro Definition Documentation
AIRSPEED_CONSISTENCY_INTERVAL
#define AIRSPEED_CONSISTENCY_INTERVAL 10
Definition at line 42 of file airspeed_consistency.c.
AIRSPEED_CONSISTENCY_MIN_SAMPLES
#define AIRSPEED_CONSISTENCY_MIN_SAMPLES 20
Definition at line 38 of file airspeed_consistency.c.
Function Documentation
airspeed_consistency_init()
void airspeed_consistency_init (void)
Definition at line 62 of file airspeed_consistency.c.
References foo, init_butterworth_2_low_pass(), NAVIGATION_FREQUENCY, reset_speeds(), and tas_filt.
airspeed_consistency_periodic()
void airspeed_consistency_periodic (void)
Definition at line 68 of file airspeed_consistency.c.
References AIRSPEED_CONSISTENCY_INTERVAL, AIRSPEED_CONSISTENCY_MIN_SAMPLES, ARRIVED_AT_WAYPOINT, asc_t::as, asc_t::as_circ_status, asc, NavCircle_t::center, CIRC_FIT_OK, NavBase_t::circle, asc_t::filled, float_vect2_norm(), foo, asc_t::gs_circ_status, RotorcraftNavigation::horizontal_mode, asc_t::i, if(), nav, NAV_HORIZONTAL_MODE_CIRCLE, nav_rotorcraft_base, circle_t::r, NavCircle_t::radius, reset_speeds(), save_speeds(), stateGetPositionEnu_f(), and VECT2_DIFF.
airspeed_consistency_reset()
void airspeed_consistency_reset (bool reset)
Definition at line 139 of file airspeed_consistency.c.
References reset_speeds().
get_circle_from_speeds()
static enum CircFitStatus_t get_circle_from_speeds (struct circle_t * c, float * N, float * E) static
Definition at line 133 of file airspeed_consistency.c.
References AIRSPEED_CONSISTENCY_BUFFER_SIZE, asc, asc_t::filled, foo, asc_t::i, N, pprz_circfit_wei_float(), and status.
reset_speeds()
static void reset_speeds (void) static
Definition at line 119 of file airspeed_consistency.c.
References AIRSPEED_CONSISTENCY_BUFFER_SIZE, asc_t::as_circ_status, asc_t::as_E, asc_t::as_N, asc, CIRC_FIT_ERROR, asc_t::filled, foo, asc_t::gs_circ_status, asc_t::gs_E, asc_t::gs_N, and asc_t::i.
Referenced by airspeed_consistency_init(), airspeed_consistency_periodic(), and airspeed_consistency_reset().
save_speeds()
static void save_speeds (void) static
Definition at line 103 of file airspeed_consistency.c.
References air_data, AIRSPEED_CONSISTENCY_BUFFER_SIZE, asc_t::as_E, asc_t::as_N, asc, asc_t::filled, foo, asc_t::gs_E, asc_t::gs_N, asc_t::i, SecondOrderLowPass::o, FloatEulers::psi, stateGetNedToBodyEulers_f(), stateGetSpeedNed_f(), AirData::tas, tas_filt, update_butterworth_2_low_pass(), NedCoor_f::x, and NedCoor_f::y.
Referenced by airspeed_consistency_periodic().
Variable Documentation
asc
struct asc_t asc = {0} static
Definition at line 59 of file airspeed_consistency.c.
Referenced by airspeed_consistency_periodic(), get_circle_from_speeds(), reset_speeds(), and save_speeds().
asc_reset
bool asc_reset = false
Definition at line 53 of file airspeed_consistency.c.
tas_filt
Butterworth2LowPass tas_filt static
Definition at line 60 of file airspeed_consistency.c.
Referenced by airspeed_consistency_init(), and save_speeds().