Paparazzi UAS: sw/airborne/modules/sensors/airspeed_amsys.h File Reference
airspeed_amsys.h File Reference
#include "std.h"
#include "mcu_periph/i2c.h"
Macros
#define AirspeedAmsysEvent() { if (airspeed_amsys_i2c_trans.status == I2CTransSuccess) airspeed_amsys_read_event(); }
Functions
void airspeed_amsys_init (void)
void airspeed_amsys_read_periodic (void)
void airspeed_amsys_read_event (void)
Variables
float airspeed_scale
float airspeed_filter
struct i2c_transaction airspeed_amsys_i2c_trans
Macro Definition Documentation
AirspeedAmsysEvent
#define AirspeedAmsysEvent () { if (airspeed_amsys_i2c_trans.status == I2CTransSuccess) airspeed_amsys_read_event(); }
Definition at line 41 of file airspeed_amsys.h.
Function Documentation
airspeed_amsys_init()
void airspeed_amsys_init (void) extern
Definition at line 92 of file airspeed_amsys.c.
References airspeed_amsys, airspeed_amsys_cnt, AIRSPEED_AMSYS_FILTER, airspeed_amsys_i2c_done, airspeed_amsys_i2c_trans, airspeed_amsys_offset, airspeed_amsys_offset_init, AIRSPEED_AMSYS_OFFSET_NBSAMPLES_AVRG, AIRSPEED_AMSYS_OFFSET_NBSAMPLES_INIT, airspeed_amsys_offset_tmp, airspeed_amsys_p, airspeed_amsys_raw, AIRSPEED_AMSYS_SCALE, airspeed_amsys_valid, airspeed_filter, airspeed_scale, I2CTransDone, and i2c_transaction::status.
airspeed_amsys_read_event()
void airspeed_amsys_read_event (void) extern
Definition at line 143 of file airspeed_amsys.c.
References airspeed_amsys, airspeed_amsys_cnt, airspeed_amsys_downlink(), airspeed_amsys_i2c_trans, AIRSPEED_AMSYS_MAXPRESURE, airspeed_amsys_offset, airspeed_amsys_offset_init, AIRSPEED_AMSYS_OFFSET_MAX, AIRSPEED_AMSYS_OFFSET_MIN, AIRSPEED_AMSYS_OFFSET_NBSAMPLES_AVRG, airspeed_amsys_offset_tmp, airspeed_amsys_p, airspeed_amsys_raw, airspeed_amsys_tmp, airspeed_amsys_valid, airspeed_filter, airspeed_old, airspeed_scale, airspeed_temperature, i2c_transaction::buf, foo, I2CTransDone, stateSetAirspeed_f(), i2c_transaction::status, and tempAS_amsys_raw.
airspeed_amsys_read_periodic()
void airspeed_amsys_read_periodic (void) extern
Definition at line 109 of file airspeed_amsys.c.
References airspeed_amsys, AIRSPEED_AMSYS_ADDR, airspeed_amsys_downlink(), AIRSPEED_AMSYS_I2C_DEV, airspeed_amsys_i2c_trans, foo, i2c_receive(), I2CTransDone, stateSetAirspeed_f(), and i2c_transaction::status.
Variable Documentation
airspeed_amsys_i2c_trans
struct i2c_transaction airspeed_amsys_i2c_trans extern
Definition at line 80 of file airspeed_amsys.c.
Referenced by airspeed_amsys_init(), airspeed_amsys_read_event(), and airspeed_amsys_read_periodic().
airspeed_filter
float airspeed_filter extern
Definition at line 79 of file airspeed_amsys.c.
Referenced by airspeed_amsys_init(), airspeed_amsys_read_event(), airspeed_uavcan_cb(), and airspeed_uavcan_init().
airspeed_scale
float airspeed_scale extern
Definition at line 78 of file airspeed_amsys.c.
Referenced by airspeed_amsys_init(), and airspeed_amsys_read_event().