Paparazzi UAS: sw/airborne/modules/ins/alt_filter.c File Reference
alt_filter.c File Reference
#include "modules/ins/alt_filter.h"
#include "modules/gps/gps.h"
#include "modules/sensors/baro_ets.h"
#include "mcu_periph/uart.h"
#include "pprzlink/messages.h"
#include "modules/datalink/downlink.h"
Functions
void kalmanInit (TypeKalman *k)
void kalmanEstimation (TypeKalman *k, float accVert)
void kalmanCorrectionGPS (TypeKalman *k, float altitude_gps)
void kalmanCorrectionAltimetre (TypeKalman *k, float altitude_altimetre)
void alt_filter_init (void)
void alt_filter_periodic (void)
Variables
TypeKalman alt_filter
float SigAltiGPS
float SigAltiAltimetre
float MarcheAleaBiaisAltimetre
float MarcheAleaAccelerometre
float last_gps_alt
float last_baro_alt
Function Documentation
alt_filter_init()
void alt_filter_init (void)
Definition at line 49 of file alt_filter.c.
References alt_filter, kalmanInit(), last_baro_alt, last_gps_alt, MarcheAleaAccelerometre, MarcheAleaBiaisAltimetre, SigAltiAltimetre, and SigAltiGPS.
alt_filter_periodic()
void alt_filter_periodic (void)
Definition at line 61 of file alt_filter.c.
References alt_filter, baro_ets_altitude, DefaultChannel, DefaultDevice, foo, gps, GpsFixValid, GpsState::hmsl, kalmanCorrectionAltimetre(), kalmanCorrectionGPS(), kalmanEstimation(), last_baro_alt, last_gps_alt, TypeKalman::P, and TypeKalman::X.
kalmanCorrectionAltimetre()
void kalmanCorrectionAltimetre (TypeKalman * k, float altitude_altimetre)
Definition at line 226 of file alt_filter.c.
References foo, TypeKalman::P, SigAltiAltimetre, and TypeKalman::X.
Referenced by alt_filter_periodic().
kalmanCorrectionGPS()
void kalmanCorrectionGPS (TypeKalman * k, float altitude_gps)
Definition at line 178 of file alt_filter.c.
References foo, TypeKalman::P, SigAltiGPS, and TypeKalman::X.
Referenced by alt_filter_periodic().
kalmanEstimation()
void kalmanEstimation (TypeKalman * k, float accVert)
Definition at line 130 of file alt_filter.c.
References TypeKalman::Ad, TypeKalman::Bd, foo, J, TypeKalman::Md, TypeKalman::P, TypeKalman::W, and TypeKalman::X.
Referenced by alt_filter_periodic().
kalmanInit()
void kalmanInit (TypeKalman * k)
Definition at line 91 of file alt_filter.c.
References TypeKalman::Ad, TypeKalman::Bd, foo, MarcheAleaAccelerometre, MarcheAleaBiaisAltimetre, TypeKalman::Md, TypeKalman::P, TypeKalman::Te, TypeKalman::W, and TypeKalman::X.
Referenced by alt_filter_init().
Variable Documentation
alt_filter
TypeKalman alt_filter
Definition at line 31 of file alt_filter.c.
Referenced by alt_filter_init(), and alt_filter_periodic().
last_baro_alt
float last_baro_alt
Definition at line 47 of file alt_filter.c.
Referenced by alt_filter_init(), and alt_filter_periodic().
last_gps_alt
float last_gps_alt
Definition at line 46 of file alt_filter.c.
Referenced by alt_filter_init(), and alt_filter_periodic().
MarcheAleaAccelerometre
float MarcheAleaAccelerometre
Definition at line 37 of file alt_filter.c.
Referenced by alt_filter_init(), and kalmanInit().
MarcheAleaBiaisAltimetre
float MarcheAleaBiaisAltimetre
Definition at line 36 of file alt_filter.c.
Referenced by alt_filter_init(), and kalmanInit().
SigAltiAltimetre
float SigAltiAltimetre
Definition at line 35 of file alt_filter.c.
Referenced by alt_filter_init(), and kalmanCorrectionAltimetre().
SigAltiGPS
float SigAltiGPS
Definition at line 34 of file alt_filter.c.
Referenced by alt_filter_init(), and kalmanCorrectionGPS().