Paparazzi UAS: sw/airborne/modules/ins/alt_filter.h File Reference
alt_filter.h File Reference
Data Structures
struct TypeKalman
Macros
#define KALT_N_ETAT 3
Functions
void alt_filter_init (void)
void alt_filter_periodic (void)
Variables
TypeKalman alt_filter
Data Structure Documentation
TypeKalman
struct TypeKalman
Definition at line 38 of file alt_filter.h.
Data Fields
float Ad[KALT_N_ETAT][KALT_N_ETAT]
float Bd[KALT_N_ETAT]
float Md[KALT_N_ETAT][KALT_N_ETAT - 1]
float P[KALT_N_ETAT][KALT_N_ETAT]
float Te
float W[KALT_N_ETAT - 1][KALT_N_ETAT - 1]
float X[KALT_N_ETAT]
Macro Definition Documentation
KALT_N_ETAT
#define KALT_N_ETAT 3
Definition at line 36 of file alt_filter.h.
Function Documentation
alt_filter_init()
void alt_filter_init (void) extern
Definition at line 49 of file alt_filter.c.
References alt_filter, kalmanInit(), last_baro_alt, last_gps_alt, MarcheAleaAccelerometre, MarcheAleaBiaisAltimetre, SigAltiAltimetre, and SigAltiGPS.
alt_filter_periodic()
void alt_filter_periodic (void) extern
Definition at line 61 of file alt_filter.c.
References alt_filter, baro_ets_altitude, DefaultChannel, DefaultDevice, foo, gps, GpsFixValid, GpsState::hmsl, kalmanCorrectionAltimetre(), kalmanCorrectionGPS(), kalmanEstimation(), last_baro_alt, last_gps_alt, TypeKalman::P, and TypeKalman::X.
Variable Documentation
alt_filter
TypeKalman alt_filter extern
Definition at line 31 of file alt_filter.c.
Referenced by alt_filter_init(), and alt_filter_periodic().