Paparazzi UAS: sw/airborne/modules/sensors/aoa_pwm.h File Reference
aoa_pwm.h File Reference
Angle of Attack sensor on PWM.
#include "std.h"
Data Structures
struct Aoa_Pwm
Enumerations
enum Aoa_Type { SEND_TYPE_AOA , SEND_TYPE_SIDESLIP }
Selection of sensor type to be send over telemetry.
Functions
void aoa_pwm_init (void)
void aoa_pwm_update (void)
Variables
struct Aoa_Pwm aoa_pwm
struct Aoa_Pwm ssa_pwm
enum Aoa_Type aoa_send_type
Detailed Description
Angle of Attack sensor on PWM.
Author
Jean-François Erdelyi
Driver for a PWM based angle of attack sensor A second sensor can be defined for the sideslip angle It is assumed that both sensors are the same, only sensitivity, offset and direction can differ.
SENSOR, example : US DIGITAL MA3-P12-125-B
Definition in file aoa_pwm.h.
Data Structure Documentation
Aoa_Pwm
struct Aoa_Pwm
Definition at line 39 of file aoa_pwm.h.
Data Fields
float angle Angle of attack in radians.
float filter Filtering value [0-1] 0: no filtering 1: output is a constant value.
float offset Angle of attack offset in radians.
uint32_t raw raw PWM value
float sens sensitiviy, i.e. scale to conver raw to angle
Enumeration Type Documentation
Aoa_Type
enum Aoa_Type
Selection of sensor type to be send over telemetry.
Enumerator
SEND_TYPE_AOA
SEND_TYPE_SIDESLIP
Definition at line 57 of file aoa_pwm.h.
Function Documentation
aoa_pwm_init()
void aoa_pwm_init (void) extern
Definition at line 145 of file aoa_pwm.c.
References Aoa_Pwm::angle, AOA_FILTER, AOA_OFFSET, aoa_pwm, aoa_send_type, AOA_SENS, DefaultPeriodic, Aoa_Pwm::filter, foo, log_started, Aoa_Pwm::offset, Aoa_Pwm::raw, register_periodic_telemetry(), send_aoa(), SEND_TYPE_AOA, Aoa_Pwm::sens, SSA_FILTER, SSA_OFFSET, ssa_pwm, and SSA_SENS.
aoa_pwm_update()
void aoa_pwm_update (void) extern
Definition at line 167 of file aoa_pwm.c.
References Aoa_Pwm::angle, AOA_ANGLE_OFFSET, aoa_pwm, AOA_PWM_ID, AOA_PWM_OFFSET, AOA_SIGN, DefaultChannel, DefaultDevice, Aoa_Pwm::filter, foo, get_pwm_input_duty_in_usec(), log_started, Aoa_Pwm::offset, pprzLogFile, Aoa_Pwm::raw, send_aoa(), Aoa_Pwm::sens, ssa_pwm, and SSA_SIGN.
Variable Documentation
aoa_pwm
struct Aoa_Pwm aoa_pwm extern
Definition at line 92 of file aoa_pwm.c.
Referenced by aoa_pwm_init(), aoa_pwm_update(), and send_aoa().
aoa_send_type
enum Aoa_Type aoa_send_type extern
Definition at line 123 of file aoa_pwm.c.
ssa_pwm
struct Aoa_Pwm ssa_pwm extern
Definition at line 119 of file aoa_pwm.c.
Referenced by aoa_pwm_init(), aoa_pwm_update(), and send_aoa().