Paparazzi UAS: sw/airborne/modules/sensors/aoa_t4.h File Reference
aoa_t4.h File Reference
Angle of Attack and optionally Sideslip Angle sensor using T4 Actuators Board and a modified serial bus servo The servo as AOA sensor must be of hall effect type and have motor and gears removed to minimize friction and this solution to work.
#include "std.h"
Data Structures
struct Aoa_T4
Enumerations
enum Aoa_Type { SEND_TYPE_AOA , SEND_TYPE_SIDESLIP }
Selection of sensor type to be send over telemetry for debugging or online logging.
Functions
void aoa_t4_init (void)
void aoa_t4_update (void)
void aoa_t4_init_filters (void)
Variables
struct Aoa_T4 aoa_t4
struct Aoa_T4 ssa_t4
enum Aoa_Type aoa_send_type
float aoa_t4_a1
float aoa_t4_b1
float aoa_t4_a2
float aoa_t4_b2
Detailed Description
Angle of Attack and optionally Sideslip Angle sensor using T4 Actuators Board and a modified serial bus servo The servo as AOA sensor must be of hall effect type and have motor and gears removed to minimize friction and this solution to work.
Author
Sunyou Hwang, OpenUAS
Read more on how to create your own T4 Board here: https://github.com/tudelft/t4_actuators_board/
SENSOR, example : Feetech 3032 Serial Bus Servo
Definition in file aoa_t4.h.
Data Structure Documentation
Aoa_T4
struct Aoa_T4
Definition at line 39 of file aoa_t4.h.
Data Fields
float angle Angle of attack in radians after applying direction and offset.
float filter Filter level for sensor output, where 0.0 is no filtering and 0.95 for extreme filtering, were 1.0 would output an (useless) constant value.
float offset Angle of attack offset in radians.
uint32_t raw Measurement in degrees times 100 from the sensor before applying direction and offset and unit scale conversion.
Enumeration Type Documentation
Aoa_Type
enum Aoa_Type
Selection of sensor type to be send over telemetry for debugging or online logging.
Enumerator
SEND_TYPE_AOA
SEND_TYPE_SIDESLIP
Definition at line 52 of file aoa_t4.h.
Function Documentation
aoa_t4_init()
void aoa_t4_init (void)
Definition at line 299 of file aoa_t4.c.
References ABI_BROADCAST, actuators_t4_abi_in(), ACTUATORS_T4_IN, Aoa_T4::angle, aoa_send_type, aoa_t4, AOA_T4_FILTER, aoa_t4_init_filters(), AOA_T4_OFFSET, DefaultPeriodic, Aoa_T4::filter, foo, Aoa_T4::offset, Aoa_T4::raw, register_periodic_telemetry(), send_aoa(), SEND_TYPE_AOA, ssa_t4, SSA_T4_FILTER, ssa_t4_init_filters(), and SSA_T4_OFFSET.
aoa_t4_init_filters()
void aoa_t4_init_filters (void)
Definition at line 287 of file aoa_t4.c.
References AOA_T4_FILTER, AOA_T4_FILTER_SAMPLING_TIME, aoa_t4_lowpass_filter, and init_butterworth_2_low_pass().
Referenced by aoa_t4_init().
aoa_t4_update()
void aoa_t4_update (void)
Definition at line 329 of file aoa_t4.c.
References Aoa_T4::angle, AOA_ANGLE_OFFSET, AOA_PWM_ID, aoa_t4, aoa_t4_a1, aoa_t4_a2, aoa_t4_b1, aoa_t4_b2, aoa_t4_lowpass_filter, AOA_T4_SIGN, DefaultChannel, DefaultDevice, eulers_t4, float_eulers_of_quat_zxy(), foo, Aoa_T4::offset, Aoa_T4::raw, send_aoa(), SSA_ANGLE_OFFSET, ssa_t4, SSA_T4_SIGN, stateGetNedToBodyQuat_f(), FloatEulers::theta, and update_butterworth_2_low_pass().
Variable Documentation
aoa_send_type
enum Aoa_Type aoa_send_type extern
Definition at line 123 of file aoa_pwm.c.
Referenced by aoa_pwm_init(), aoa_t4_init(), send_aoa(), and send_aoa().
aoa_t4
struct Aoa_T4 aoa_t4 extern
Definition at line 87 of file aoa_t4.c.
Referenced by actuators_t4_abi_in(), aoa_t4_init(), aoa_t4_update(), and send_aoa().
aoa_t4_a1
float aoa_t4_a1 extern
Definition at line 152 of file aoa_t4.c.
Referenced by aoa_t4_update().
aoa_t4_a2
float aoa_t4_a2 extern
Definition at line 154 of file aoa_t4.c.
Referenced by aoa_t4_update().
aoa_t4_b1
float aoa_t4_b1 extern
Definition at line 153 of file aoa_t4.c.
Referenced by aoa_t4_update().
aoa_t4_b2
float aoa_t4_b2 extern
Definition at line 155 of file aoa_t4.c.
Referenced by aoa_t4_update().
ssa_t4
struct Aoa_T4 ssa_t4 extern
Definition at line 145 of file aoa_t4.c.
Referenced by actuators_t4_abi_in(), aoa_t4_init(), aoa_t4_update(), and send_aoa().