Paparazzi UAS: sw/airborne/modules/ctrl/approach_moving_target.h File Reference
approach_moving_target.h File Reference
#include "std.h"
#include "math/pprz_algebra_float.h"
Data Structures
struct Amt
Functions
void approach_moving_target_init (void)
void follow_diagonal_approach (void)
Generates a velocity reference from a diagonal approach path.
void approach_moving_target_enable (uint8_t wp_id)
void approach_moving_target_set_low_pass_freq (float filter_freq)
Variables
struct Amt amt
Detailed Description
Author
Ewoud Smeur e.j.j.nosp@m..sme.nosp@m.ur@tu.nosp@m.delf.nosp@m.t.nl Approach a moving target (e.g. ship)
Definition in file approach_moving_target.h.
Data Structure Documentation
Amt
struct Amt
Definition at line 33 of file approach_moving_target.h.
Data Fields
float cutoff_freq_filters_hz
float distance
int32_t enabled_time
float err_slowdown_gain
float pos_gain
float psi_ref
struct FloatVect3 rel_unit_vec
float relvel_gain
float slope_ref
float speed
float speed_gain
uint8_t wp_id
Function Documentation
approach_moving_target_enable()
void approach_moving_target_enable (uint8_t wp_id) extern
Definition at line 161 of file approach_moving_target.c.
References amt, Amt::enabled_time, get_sys_time_msec(), and Amt::wp_id.
approach_moving_target_init()
void approach_moving_target_init (void) extern
Definition at line 119 of file approach_moving_target.c.
References amt, approach_moving_target_set_low_pass_freq(), Amt::cutoff_freq_filters_hz, DefaultPeriodic, foo, register_periodic_telemetry(), and send_approach_moving_target().
approach_moving_target_set_low_pass_freq()
void approach_moving_target_set_low_pass_freq (float filter_freq) extern
Definition at line 127 of file approach_moving_target.c.
References amt, Amt::cutoff_freq_filters_hz, foo, init_butterworth_2_low_pass(), target_heading_filt, target_pos_filt, and target_vel_filt.
Referenced by approach_moving_target_init().
follow_diagonal_approach()
void follow_diagonal_approach (void) extern
Generates a velocity reference from a diagonal approach path.
Definition at line 171 of file approach_moving_target.c.
References amt, amt_telem, RotorcraftNavigation::climb_vspeed, AmtTelem::des_pos, AmtTelem::des_vel, RotorcraftNavigation::descend_vspeed, Amt::distance, Amt::enabled_time, Amt::err_slowdown_gain, FLOAT_ANGLE_NORMALIZE, float_vect3_bound_in_3d(), foo, get_sys_time_msec(), nav, NAVIGATION_FREQUENCY, SecondOrderLowPass::o, Amt::pos_gain, Amt::psi_ref, Amt::rel_unit_vec, Amt::relvel_gain, Amt::slope_ref, Amt::speed, Amt::speed_gain, stateGetAirspeed_f(), stateGetPositionNed_f(), target_get_pos(), target_get_vel(), target_heading_filt, target_pos_filt, target_vel_filt, update_butterworth_2_low_pass(), update_waypoint(), VECT3_COPY, VECT3_DIFF, VECT3_NORM2, VECT3_SMUL, VECT3_SUM, VEL_SP_FCR_ID, Amt::wp_id, FloatVect3::x, NedCoor_f::x, FloatVect3::y, NedCoor_f::y, FloatVect3::z, and NedCoor_f::z.
Variable Documentation
amt
struct Amt amt extern
Definition at line 79 of file approach_moving_target.c.
Referenced by amt22_get_position(), amt22_get_turns(), amt22_init(), amt22_periodic(), amt22_read(), amt22_thd(), approach_moving_target_enable(), approach_moving_target_init(), approach_moving_target_set_low_pass_freq(), follow_diagonal_approach(), and send_approach_moving_target().