Paparazzi UAS: sw/airborne/arch/chibios/board.c File Reference
board.c File Reference
#include "hal.h"
#include "stm32_gpio.h"
Data Structures
struct gpio_setup_t
Type of STM32 GPIO port setup.
struct gpio_config_t
Type of STM32 GPIO initialization data.
Functions
static void gpio_init (stm32_gpio_t *gpiop, const gpio_setup_t *config)
static void stm32_gpio_init (void)
void __early_init (void)
Early initialization code.
void boardInit (void)
Board-specific initialization code.
Variables
static const gpio_config_t gpio_default_config
STM32 GPIO static initialization data.
Data Structure Documentation
gpio_setup_t
struct gpio_setup_t
Type of STM32 GPIO port setup.
Definition at line 55 of file board.c.
Data Fields
uint32_t afrh
uint32_t afrl
uint32_t moder
uint32_t odr
uint32_t ospeedr
uint32_t otyper
uint32_t pupdr
gpio_config_t
struct gpio_config_t
Type of STM32 GPIO initialization data.
Definition at line 68 of file board.c.
Function Documentation
__early_init()
void __early_init (void)
Early initialization code.
GPIO ports and system clocks are initialized before everything else.
Definition at line 259 of file board.c.
References foo, and stm32_gpio_init().
boardInit()
void boardInit (void)
Board-specific initialization code.
Todo:
Add your board-specific code, if any.
Definition at line 317 of file board.c.
References AFIO_MAPR_VAL, and foo.
gpio_init()
static void gpio_init (stm32_gpio_t * gpiop, const gpio_setup_t * config) static
Definition at line 180 of file board.c.
References gpio_setup_t::afrh, gpio_setup_t::afrl, foo, gpio_setup_t::moder, gpio_setup_t::odr, gpio_setup_t::ospeedr, gpio_setup_t::otyper, and gpio_setup_t::pupdr.
Referenced by stm32_gpio_init().
stm32_gpio_init()
static void stm32_gpio_init (void) static
Definition at line 192 of file board.c.
References foo, gpio_default_config, gpio_init(), GPIOA, GPIOB, GPIOC, GPIOD, GPIOE, GPIOF, GPIOG, and GPIOH.
Referenced by __early_init().
Variable Documentation
gpio_default_config
const gpio_config_t gpio_default_config static
STM32 GPIO static initialization data.
Definition at line 107 of file board.c.
Referenced by stm32_gpio_init().