Paparazzi UAS: sw/airborne/boards/ardrone/baro_board.h File Reference
baro_board.h File Reference
Paparazzi AR Drone 2 Baro Sensor implementation:.
Macros
#define BaroEvent ardrone_baro_event
Functions
void ardrone_baro_event (void)
Detailed Description
Paparazzi AR Drone 2 Baro Sensor implementation:.
These functions are mostly empty because of the calibration and calculations done by the Parrot Navigation board.
Definition in file baro_board.h.
Macro Definition Documentation
BaroEvent
#define BaroEvent ardrone_baro_event
Definition at line 34 of file baro_board.h.
Function Documentation
ardrone_baro_event()
void ardrone_baro_event (void) extern
Definition at line 92 of file baro_board.c.
References baro_apply_calibration(), baro_apply_calibration_temp(), navdata_t::baro_available, BARO_BOARD_SENDER_ID, navdata_t::baro_calibrated, foo, get_sys_time_usec(), navdata_t::measure, navdata, navdata_measure_t::pressure, navdata_measure_t::temperature_pressure, and update_median_filter_i().