Paparazzi UAS: sw/airborne/boards/ardrone/baro_board.c File Reference
baro_board.c File Reference
Paparazzi AR Drone 2 Baro Sensor implementation:.
#include "modules/sensors/baro.h"
#include "modules/core/abi.h"
#include "baro_board.h"
#include "navdata.h"
Macros
#define BMP180_OSS 0
Use an extra median filter to filter baro data.
Functions
void baro_init (void)
void baro_periodic (void)
static int32_t baro_apply_calibration (int32_t raw)
Apply temperature and sensor calibration to get pressure in Pa.
static int32_t baro_apply_calibration_temp (int32_t tmp_raw)
Apply temperature calibration.
void ardrone_baro_event (void)
Detailed Description
Paparazzi AR Drone 2 Baro Sensor implementation:.
Based on BMP180 implementation by C. de Wagter.
Definition in file baro_board.c.
Macro Definition Documentation
BMP180_OSS
#define BMP180_OSS 0
Use an extra median filter to filter baro data.
Definition at line 42 of file baro_board.c.
Function Documentation
ardrone_baro_event()
void ardrone_baro_event (void)
Definition at line 92 of file baro_board.c.
References baro_apply_calibration(), baro_apply_calibration_temp(), navdata_t::baro_available, BARO_BOARD_SENDER_ID, navdata_t::baro_calibrated, foo, get_sys_time_usec(), navdata_t::measure, navdata, navdata_measure_t::pressure, navdata_measure_t::temperature_pressure, and update_median_filter_i().
baro_apply_calibration()
static int32_t baro_apply_calibration (int32_t raw) inline static
Apply temperature and sensor calibration to get pressure in Pa.
Parameters
raw uncompensated raw pressure reading
Returns
compensated pressure in Pascal
Definition at line 58 of file baro_board.c.
References bmp180_calib_t::ac1, bmp180_calib_t::ac2, bmp180_calib_t::ac3, bmp180_calib_t::ac4, bmp180_calib_t::b1, bmp180_calib_t::b2, bmp180_calib_t::b5, navdata_t::bmp180_calib, BMP180_OSS, foo, navdata, and p.
Referenced by ardrone_baro_event().
baro_apply_calibration_temp()
static int32_t baro_apply_calibration_temp (int32_t tmp_raw) inline static
Apply temperature calibration.
Parameters
tmp_raw uncompensated raw temperature reading
Returns
compensated temperature in 0.1 deg Celcius
Definition at line 84 of file baro_board.c.
References bmp180_calib_t::ac5, bmp180_calib_t::ac6, bmp180_calib_t::b5, navdata_t::bmp180_calib, foo, bmp180_calib_t::mc, bmp180_calib_t::md, and navdata.
Referenced by ardrone_baro_event().
baro_init()
void baro_init (void)
Definition at line 44 of file baro_board.c.
References foo, init_median_filter_i(), and MEDIAN_DEFAULT_SIZE.
baro_periodic()
void baro_periodic (void)
Definition at line 51 of file baro_board.c.