Paparazzi UAS: sw/airborne/modules/digital_cam/atmega_i2c_cam_ctrl.c File Reference
atmega_i2c_cam_ctrl.c File Reference
Interface with digital camera though AVR AtMega chip.
#include "atmega_i2c_cam_ctrl.h"
#include "mcu_periph/i2c.h"
#include "led.h"
#include "mcu_periph/uart.h"
#include "pprzlink/messages.h"
#include "modules/datalink/downlink.h"
Macros
#define ATMEGA_I2C_DEV i2c0
#define ATMEGA_SLAVE_ADDR 0x68
Functions
void dc_send_command (uint8_t cmd)
Send Command To Camera.
void atmega_i2c_cam_ctrl_init (void)
void atmega_i2c_cam_ctrl_periodic (void)
void atmega_i2c_cam_ctrl_send (uint8_t cmd)
void atmega_i2c_cam_ctrl_event (void)
Variables
static struct i2c_transaction atmega_i2c_cam_ctrl_trans
uint8_t atmega_i2c_cam_ctrl_just_sent_command = 0
Detailed Description
Interface with digital camera though AVR AtMega chip.
Send Commands over I2C
Definition in file atmega_i2c_cam_ctrl.c.
Macro Definition Documentation
ATMEGA_I2C_DEV
#define ATMEGA_I2C_DEV i2c0
Definition at line 52 of file atmega_i2c_cam_ctrl.c.
ATMEGA_SLAVE_ADDR
#define ATMEGA_SLAVE_ADDR 0x68
Definition at line 57 of file atmega_i2c_cam_ctrl.c.
Function Documentation
atmega_i2c_cam_ctrl_event()
void atmega_i2c_cam_ctrl_event (void)
Definition at line 93 of file atmega_i2c_cam_ctrl.c.
References atmega_i2c_cam_ctrl_trans, i2c_transaction::buf, DefaultChannel, DefaultDevice, foo, I2CTransDone, I2CTransSuccess, and i2c_transaction::status.
atmega_i2c_cam_ctrl_init()
void atmega_i2c_cam_ctrl_init (void)
Definition at line 62 of file atmega_i2c_cam_ctrl.c.
References atmega_i2c_cam_ctrl_trans, I2CTransDone, and i2c_transaction::status.
atmega_i2c_cam_ctrl_periodic()
void atmega_i2c_cam_ctrl_periodic (void)
Definition at line 67 of file atmega_i2c_cam_ctrl.c.
References atmega_i2c_cam_ctrl_just_sent_command, atmega_i2c_cam_ctrl_send(), DC_GET_STATUS, and dc_periodic().
atmega_i2c_cam_ctrl_send()
void atmega_i2c_cam_ctrl_send (uint8_t cmd)
Definition at line 80 of file atmega_i2c_cam_ctrl.c.
References atmega_i2c_cam_ctrl_just_sent_command, atmega_i2c_cam_ctrl_trans, ATMEGA_I2C_DEV, ATMEGA_SLAVE_ADDR, i2c_transaction::buf, dc_send_shot_position(), DC_SHOOT, and i2c_transceive().
Referenced by atmega_i2c_cam_ctrl_periodic(), and dc_send_command().
dc_send_command()
void dc_send_command (uint8_t cmd)
Send Command To Camera.
Definition at line 41 of file atmega_i2c_cam_ctrl.c.
References atmega_i2c_cam_ctrl_send(), and dc_send_command_common().
Referenced by atmega_i2c_cam_ctrl_periodic(), dc_periodic(), dc_shoot_rc_periodic(), nav_spiral_run(), nav_survey_hybrid_run(), nav_survey_poly_run(), and nav_survey_rectangle_rotorcraft_run().
Variable Documentation
atmega_i2c_cam_ctrl_just_sent_command
uint8_t atmega_i2c_cam_ctrl_just_sent_command = 0
Definition at line 60 of file atmega_i2c_cam_ctrl.c.
Referenced by atmega_i2c_cam_ctrl_periodic(), and atmega_i2c_cam_ctrl_send().
atmega_i2c_cam_ctrl_trans
struct i2c_transaction atmega_i2c_cam_ctrl_trans static
Definition at line 49 of file atmega_i2c_cam_ctrl.c.
Referenced by atmega_i2c_cam_ctrl_event(), atmega_i2c_cam_ctrl_init(), and atmega_i2c_cam_ctrl_send().