Paparazzi UAS: sw/airborne/firmwares/rotorcraft/autopilot_guided.h File Reference
autopilot_guided.h File Reference
Autopilot guided mode interface.
#include "std.h"
Macros
#define GUIDED_FLAG_XY_OFFSET (1<<0)
Bitmask for setting the flags attribute in autopilot_guided_update function See function description for more details.
#define GUIDED_FLAG_XY_BODY (1<<1)
#define GUIDED_FLAG_Z_OFFSET (1<<2)
#define GUIDED_FLAG_YAW_OFFSET (1<<3)
#define GUIDED_FLAG_XY_VEL (1<<5)
#define GUIDED_FLAG_Z_VEL (1<<6)
#define GUIDED_FLAG_YAW_RATE (1<<7)
#define NavGuided(_flags, _x, _y, _z, _yaw)
Macro for the flight plan insctructions.
Functions
bool autopilot_guided_goto_ned (float x, float y, float z, float heading)
Set position and heading setpoints in GUIDED mode.
bool autopilot_guided_goto_ned_relative (float dx, float dy, float dz, float dyaw)
Set position and heading setpoints wrt.
bool autopilot_guided_goto_body_relative (float dx, float dy, float dz, float dyaw)
Set position and heading setpoints wrt.
bool autopilot_guided_move_ned (float vx, float vy, float vz, float heading)
Set velocity and heading setpoints in GUIDED mode.
void autopilot_guided_update (uint8_t flags, float x, float y, float z, float yaw)
Set guided setpoints using flag mask in GUIDED mode.
void autopilot_guided_parse_GUIDED (uint8_t *buf)
Parse GUIDED_SETPOINT_NED messages from datalink.
void autopilot_guided_parse_GUIDED_FULL (uint8_t *buf)
Parse GUIDED_FULL_NED messages from datalink.
Detailed Description
Autopilot guided mode interface.
Definition in file autopilot_guided.h.
Macro Definition Documentation
GUIDED_FLAG_XY_BODY
#define GUIDED_FLAG_XY_BODY (1<<1)
Definition at line 103 of file autopilot_guided.h.
GUIDED_FLAG_XY_OFFSET
#define GUIDED_FLAG_XY_OFFSET (1<<0)
Bitmask for setting the flags attribute in autopilot_guided_update function See function description for more details.
Definition at line 102 of file autopilot_guided.h.
GUIDED_FLAG_XY_VEL
#define GUIDED_FLAG_XY_VEL (1<<5)
Definition at line 106 of file autopilot_guided.h.
GUIDED_FLAG_YAW_OFFSET
#define GUIDED_FLAG_YAW_OFFSET (1<<3)
Definition at line 105 of file autopilot_guided.h.
GUIDED_FLAG_YAW_RATE
#define GUIDED_FLAG_YAW_RATE (1<<7)
Definition at line 108 of file autopilot_guided.h.
GUIDED_FLAG_Z_OFFSET
#define GUIDED_FLAG_Z_OFFSET (1<<2)
Definition at line 104 of file autopilot_guided.h.
GUIDED_FLAG_Z_VEL
#define GUIDED_FLAG_Z_VEL (1<<6)
Definition at line 107 of file autopilot_guided.h.
NavGuided
#define NavGuided (_flags, _x, _y, _z, _yaw)
Value:
  {         \
  nav.horizontal_mode = NAV_HORIZONTAL_MODE_GUIDED;           \
  nav.vertical_mode = NAV_VERTICAL_MODE_GUIDED;               \
  autopilot_guided_update(_flags, _x, _y, _z, _yaw);  \
}
Macro for the flight plan insctructions.
Definition at line 112 of file autopilot_guided.h.
Function Documentation
autopilot_guided_goto_body_relative()
bool autopilot_guided_goto_body_relative (float dx, float dy, float dz, float dyaw) extern
Set position and heading setpoints wrt.
current position AND heading in GUIDED mode.
Parameters
dx relative position (body frame, forward) in meters.
dy relative position (body frame, right) in meters.
dz relative position (body frame, down) in meters.
dyaw Offset relative to current heading setpoint in radians.
Returns
TRUE if setpoint was set (currently in AP_MODE_GUIDED)
Definition at line 209 of file autopilot_guided.c.
References foo.
Referenced by mavlink_common_message_handler().
autopilot_guided_goto_ned()
bool autopilot_guided_goto_ned (float x, float y, float z, float heading) extern
Set position and heading setpoints in GUIDED mode.
Parameters
x North position (local NED frame) in meters.
y East position (local NED frame) in meters.
z Down position (local NED frame) in meters.
heading Setpoint in radians.
Returns
TRUE if setpoint was set (currently in AP_MODE_GUIDED)
Definition at line 191 of file autopilot_guided.c.
References foo, heading, FloatVect2::x, and FloatVect2::y.
Referenced by mavlink_common_message_handler(), and wedgebug_periodic().
autopilot_guided_goto_ned_relative()
bool autopilot_guided_goto_ned_relative (float dx, float dy, float dz, float dyaw) extern
Set position and heading setpoints wrt.
current position in GUIDED mode.
Parameters
dx Offset relative to current north position (local NED frame) in meters.
dy Offset relative to current east position (local NED frame) in meters.
dz Offset relative to current down position (local NED frame) in meters.
dyaw Offset relative to current heading setpoint in radians.
Returns
TRUE if setpoint was set (currently in AP_MODE_GUIDED)
Definition at line 200 of file autopilot_guided.c.
References foo.
Referenced by mavlink_common_message_handler().
autopilot_guided_move_ned()
bool autopilot_guided_move_ned (float vx, float vy, float vz, float heading) extern
Set velocity and heading setpoints in GUIDED mode.
Parameters
vx North velocity (local NED frame) in meters/sec.
vy East velocity (local NED frame) in meters/sec.
vz Down velocity (local NED frame) in meters/sec.
heading Setpoint in radians.
Returns
TRUE if setpoint was set (currently in AP_MODE_GUIDED)
Definition at line 218 of file autopilot_guided.c.
References foo, and heading.
Referenced by mavlink_common_message_handler().
autopilot_guided_parse_GUIDED()
void autopilot_guided_parse_GUIDED (uint8_t * buf) extern
Parse GUIDED_SETPOINT_NED messages from datalink.
Definition at line 238 of file autopilot_guided.c.
References foo.
autopilot_guided_parse_GUIDED_FULL()
void autopilot_guided_parse_GUIDED_FULL (uint8_t * buf) extern
Parse GUIDED_FULL_NED messages from datalink.
Definition at line 242 of file autopilot_guided.c.
References foo.
autopilot_guided_update()
void autopilot_guided_update (uint8_t flags, float x, float y, float z, float yaw) extern
Set guided setpoints using flag mask in GUIDED mode.
Parameters
flags Bits 0-3 are used to determine the axis system to be used. If bits 0 and 1 are clear then the coordinates are set in absolute NE coordinates. If bit 1 is set bit 0 is ignored. Bits 5-7 define whether the setpoints should be used as position or velocity. Bit flags are defined as follows: bit 0: x,y as offset coordinates bit 1: x,y in body coordinates bit 2: z as offset coordinates bit 3: yaw as offset coordinates bit 4: free bit 5: x,y as vel bit 6: z as vel bit 7: yaw as rate
x North position/velocity in meters or meters/sec.
y East position/velocity in meters or meters/sec.
z Down position/velocity in meters or meters/sec.
yaw Heading or heading rate setpoint in radians or radians/sec.
Definition at line 227 of file autopilot_guided.c.
References foo, FloatVect2::x, and FloatVect2::y.
Referenced by nav_fish_velocity_run().