Paparazzi UAS: sw/airborne/modules/stereocam/nav_line_avoid/avoid_navigation.c File Reference
avoid_navigation.c File Reference
#include "avoid_navigation.h"
#include "state.h"
#include "navigation.h"
#include "generated/flight_plan.h"
#include "modules/stereocam/stereocam.h"
#include "pprzlink/messages.h"
#include "modules/datalink/downlink.h"
#include "led.h"
Macros
#define DOWNLINK_DEVICE DOWNLINK_AP_DEVICE
Functions
void init_avoid_navigation ()
void run_avoid_navigation_onvision (void)
void increase_nav_heading (float *heading, float increment)
Variables
struct AvoidNavigationStruct avoid_navigation_data
global VIDEO state
bool obstacle_detected = false
int32_t counter = 0
Macro Definition Documentation
DOWNLINK_DEVICE
#define DOWNLINK_DEVICE DOWNLINK_AP_DEVICE
Definition at line 45 of file avoid_navigation.c.
Function Documentation
increase_nav_heading()
void increase_nav_heading (float * heading, float increment)
Definition at line 117 of file avoid_navigation.c.
References foo, and heading.
init_avoid_navigation()
void init_avoid_navigation (void)
Definition at line 58 of file avoid_navigation.c.
References avoid_navigation_data, and AvoidNavigationStruct::mode.
Referenced by stereo_avoid_init().
run_avoid_navigation_onvision()
void run_avoid_navigation_onvision (void)
Definition at line 65 of file avoid_navigation.c.
References avoid_navigation_data, counter, DefaultChannel, DefaultDevice, foo, RotorcraftNavigation::heading, AvoidNavigationStruct::mode, nav, NAV_LINE_AVOID_SEGMENT_LENGTH, obstacle_detected, POS_BFP_OF_REAL, stateGetPositionEnu_i(), AvoidNavigationStruct::stereo_bin, waypoint_set_xy_i(), EnuCoor_i::x, EnuCoor_i::y, and EnuCoor_i::z.
Referenced by stereo_avoid_run().
Variable Documentation
avoid_navigation_data
struct AvoidNavigationStruct avoid_navigation_data
global VIDEO state
Definition at line 53 of file avoid_navigation.c.
Referenced by init_avoid_navigation(), and run_avoid_navigation_onvision().
counter
int32_t counter = 0
Definition at line 55 of file avoid_navigation.c.
Referenced by run_avoid_navigation_onvision().
obstacle_detected
bool obstacle_detected = false
Definition at line 54 of file avoid_navigation.c.
Referenced by run_avoid_navigation_onvision(), and stereocam_droplet_periodic().