Paparazzi UAS: sw/airborne/modules/nav/ballistic_touchdown.c File Reference
ballistic_touchdown.c File Reference
#include "state.h"
Functions
void ballistic_touchdown_init (void)
void ballistic_touchdown_run (void)
Function that predicts the ballistic crash location.
Variables
float g = -9.81f
struct FloatVect2 ballistic_pos
Function Documentation
ballistic_touchdown_init()
void ballistic_touchdown_init (void)
Definition at line 29 of file ballistic_touchdown.c.
ballistic_touchdown_run()
void ballistic_touchdown_run (void)
Function that predicts the ballistic crash location.
Uses ENU coordinates (vertical up!)
Definition at line 38 of file ballistic_touchdown.c.
References ballistic_pos, foo, g, h(), stateGetPositionEnu_f(), stateGetSpeedEnu_f(), VECT2_ASSIGN, VECT2_SMUL, VECT2_SUM, FloatVect2::x, EnuCoor_f::x, FloatVect2::y, EnuCoor_f::y, and EnuCoor_f::z.
Variable Documentation
ballistic_pos
struct FloatVect2 ballistic_pos
Definition at line 27 of file ballistic_touchdown.c.
Referenced by ballistic_touchdown_run().
g
float g = -9.81f
Definition at line 25 of file ballistic_touchdown.c.
Referenced by ballistic_touchdown_run().