Paparazzi UAS: sw/airborne/modules/sensors/baro_bmp3.c File Reference
baro_bmp3.c File Reference
Bosch BMP3 I2C sensor interface.
#include "baro_bmp3.h"
#include "modules/core/abi.h"
#include "mcu_periph/uart.h"
#include "pprzlink/messages.h"
#include "modules/datalink/downlink.h"
Macros
#define BMP3_SLAVE_ADDR BMP3_I2C_ADDR
default slave address
Functions
void baro_bmp3_init (void)
void baro_bmp3_periodic (void)
void baro_bmp3_event (void)
Variables
struct Bmp3_I2c baro_bmp3
Detailed Description
Bosch BMP3 I2C sensor interface.
This reads the values for pressure and temperature from the Bosch BMP3 sensor through I2C.
Definition in file baro_bmp3.c.
Macro Definition Documentation
BMP3_SLAVE_ADDR
#define BMP3_SLAVE_ADDR BMP3_I2C_ADDR
default slave address
Definition at line 39 of file baro_bmp3.c.
Function Documentation
baro_bmp3_event()
void baro_bmp3_event (void)
Definition at line 54 of file baro_bmp3.c.
References baro_bmp3, BARO_BMP3_SENDER_ID, bmp3_i2c_event(), Bmp3_I2c::data_available, DefaultChannel, DefaultDevice, foo, get_sys_time_usec(), p, Bmp3_I2c::pressure, Bmp3_I2c::raw_pressure, Bmp3_I2c::raw_temperature, Bmp3_I2c::temperature, and up.
baro_bmp3_init()
void baro_bmp3_init (void)
Definition at line 44 of file baro_bmp3.c.
References baro_bmp3, bmp3_i2c_init(), BMP3_SLAVE_ADDR, and foo.
baro_bmp3_periodic()
void baro_bmp3_periodic (void)
Definition at line 49 of file baro_bmp3.c.
References baro_bmp3, and bmp3_i2c_periodic().
Variable Documentation
baro_bmp3
struct Bmp3_I2c baro_bmp3
Definition at line 42 of file baro_bmp3.c.
Referenced by baro_bmp3_event(), baro_bmp3_init(), and baro_bmp3_periodic().