Paparazzi UAS: sw/airborne/modules/sensors/baro_scp_i2c.h File Reference
baro_scp_i2c.h File Reference
#include "std.h"
Macros
#define SCP1000_OPERATION 0x03
#define SCP1000_HIGH_SPEED 0x09
#define SCP1000_HIGH_RES 0x0A
#define SCP1000_ULT_LOW_PW 0x0B
#define SCP1000_LOW_PW 0x0C
#define SCP1000_DATARD8 0x7F
#define SCP1000_DATARD16 0x80
#define SCP1000_TEMPOUT 0x81
#define BARO_SCP_UNINIT 0
#define BARO_SCP_IDLE 1
#define BARO_SCP_RD_TEMP 2
#define BARO_SCP_RD_PRESS_0 3
#define BARO_SCP_RD_PRESS_1 4
Functions
void baro_scp_init (void)
void baro_scp_periodic (void)
void baro_scp_event (void)
Variables
uint8_t baro_scp_status
uint32_t baro_scp_pressure
uint16_t baro_scp_temperature
Macro Definition Documentation
BARO_SCP_IDLE
#define BARO_SCP_IDLE 1
Definition at line 18 of file baro_scp_i2c.h.
BARO_SCP_RD_PRESS_0
#define BARO_SCP_RD_PRESS_0 3
Definition at line 20 of file baro_scp_i2c.h.
BARO_SCP_RD_PRESS_1
#define BARO_SCP_RD_PRESS_1 4
Definition at line 21 of file baro_scp_i2c.h.
BARO_SCP_RD_TEMP
#define BARO_SCP_RD_TEMP 2
Definition at line 19 of file baro_scp_i2c.h.
BARO_SCP_UNINIT
#define BARO_SCP_UNINIT 0
Definition at line 17 of file baro_scp_i2c.h.
SCP1000_DATARD16
#define SCP1000_DATARD16 0x80
Definition at line 14 of file baro_scp_i2c.h.
SCP1000_DATARD8
#define SCP1000_DATARD8 0x7F
Definition at line 13 of file baro_scp_i2c.h.
SCP1000_HIGH_RES
#define SCP1000_HIGH_RES 0x0A
Definition at line 9 of file baro_scp_i2c.h.
SCP1000_HIGH_SPEED
#define SCP1000_HIGH_SPEED 0x09
Definition at line 8 of file baro_scp_i2c.h.
SCP1000_LOW_PW
#define SCP1000_LOW_PW 0x0C
Definition at line 11 of file baro_scp_i2c.h.
SCP1000_OPERATION
#define SCP1000_OPERATION 0x03
Definition at line 6 of file baro_scp_i2c.h.
SCP1000_TEMPOUT
#define SCP1000_TEMPOUT 0x81
Definition at line 15 of file baro_scp_i2c.h.
SCP1000_ULT_LOW_PW
#define SCP1000_ULT_LOW_PW 0x0B
Definition at line 10 of file baro_scp_i2c.h.
Function Documentation
baro_scp_event()
void baro_scp_event (void)
Definition at line 65 of file baro_scp_i2c.c.
References BARO_SCP_IDLE, baro_scp_pressure, BARO_SCP_RD_PRESS_0, BARO_SCP_RD_PRESS_1, BARO_SCP_RD_TEMP, BARO_SCP_SENDER_ID, baro_scp_status, baro_scp_temperature, i2c_transaction::buf, DefaultChannel, DefaultDevice, foo, get_sys_time_usec(), i2c_transceive(), I2CTransSuccess, SCP1000_DATARD16, SCP1000_DATARD8, SCP1000_SLAVE_ADDR, SCP_I2C_DEV, scp_trans, and i2c_transaction::status.
baro_scp_init()
void baro_scp_init (void)
Definition at line 44 of file baro_scp_i2c.c.
References baro_scp_status, and BARO_SCP_UNINIT.
baro_scp_periodic()
void baro_scp_periodic (void)
Definition at line 49 of file baro_scp_i2c.c.
References BARO_SCP_IDLE, BARO_SCP_RD_TEMP, baro_scp_start_high_res_measurement(), baro_scp_status, BARO_SCP_UNINIT, i2c_transaction::buf, i2c_transceive(), sys_time::nb_sec, SCP1000_SLAVE_ADDR, SCP1000_TEMPOUT, SCP_I2C_DEV, and scp_trans.
Variable Documentation
baro_scp_pressure
uint32_t baro_scp_pressure extern
Definition at line 25 of file baro_scp_i2c.c.
Referenced by baro_scp_event().
baro_scp_status
uint8_t baro_scp_status extern
Definition at line 24 of file baro_scp_i2c.c.
Referenced by baro_scp_event(), baro_scp_init(), and baro_scp_periodic().
baro_scp_temperature
uint16_t baro_scp_temperature extern
Definition at line 26 of file baro_scp_i2c.c.
Referenced by baro_scp_event().