Paparazzi UAS: sw/airborne/modules/sensors/baro_ms5611_i2c.c File Reference
baro_ms5611_i2c.c File Reference
Measurement Specialties (Intersema) MS5611-01BA pressure/temperature sensor interface for I2C.
#include "modules/sensors/baro_ms5611_i2c.h"
#include "math/pprz_isa.h"
#include "mcu_periph/sys_time.h"
#include "modules/core/abi.h"
#include "mcu_periph/uart.h"
#include "pprzlink/messages.h"
#include "modules/datalink/downlink.h"
Macros
#define MS5611_I2C_DEV i2c0
#define MS5611_SLAVE_ADDR 0xEE
#define MS5611_TYPE_MS5607 FALSE
set to TRUE if baro is actually a MS5607
Functions
void baro_ms5611_init (void)
void baro_ms5611_periodic_check (void)
void baro_ms5611_read (void)
trigger new measurement or initialize if needed
void baro_ms5611_event (void)
void baro_ms5611_send_coeff (void)
Variables
struct Ms5611_I2c baro_ms5611
float fbaroms
float ftempms
float baro_ms5611_alt
bool baro_ms5611_alt_valid
bool baro_ms5611_enabled
float baro_ms5611_r
float baro_ms5611_sigma2
Detailed Description
Measurement Specialties (Intersema) MS5611-01BA pressure/temperature sensor interface for I2C.
Definition in file baro_ms5611_i2c.c.
Macro Definition Documentation
MS5611_I2C_DEV
#define MS5611_I2C_DEV i2c0
Definition at line 41 of file baro_ms5611_i2c.c.
MS5611_SLAVE_ADDR
#define MS5611_SLAVE_ADDR 0xEE
Definition at line 46 of file baro_ms5611_i2c.c.
MS5611_TYPE_MS5607
#define MS5611_TYPE_MS5607 FALSE
set to TRUE if baro is actually a MS5607
Definition at line 51 of file baro_ms5611_i2c.c.
Function Documentation
baro_ms5611_event()
void baro_ms5611_event (void)
Definition at line 96 of file baro_ms5611_i2c.c.
References baro_ms5611, baro_ms5611_alt, baro_ms5611_alt_valid, BARO_MS5611_SENDER_ID, Ms5611Data::d1, Ms5611Data::d2, Ms5611_I2c::data, Ms5611_I2c::data_available, DefaultChannel, DefaultDevice, fbaroms, foo, get_sys_time_usec(), ms5611_i2c_event(), pprz_isa_altitude_of_pressure(), Ms5611Data::pressure, and Ms5611Data::temperature.
baro_ms5611_init()
void baro_ms5611_init (void)
Definition at line 66 of file baro_ms5611_i2c.c.
References baro_ms5611, baro_ms5611_alt_valid, baro_ms5611_enabled, baro_ms5611_r, BARO_MS5611_R, baro_ms5611_sigma2, BARO_MS5611_SIGMA2, MS5611_I2C_DEV, ms5611_i2c_init(), MS5611_SLAVE_ADDR, and MS5611_TYPE_MS5607.
baro_ms5611_periodic_check()
void baro_ms5611_periodic_check (void)
Definition at line 77 of file baro_ms5611_i2c.c.
References baro_ms5611, baro_ms5611_send_coeff(), foo, and ms5611_i2c_periodic_check().
baro_ms5611_read()
void baro_ms5611_read (void)
trigger new measurement or initialize if needed
Definition at line 89 of file baro_ms5611_i2c.c.
References baro_ms5611, ms5611_i2c_read(), and sys_time::nb_sec.
baro_ms5611_send_coeff()
void baro_ms5611_send_coeff (void)
Definition at line 121 of file baro_ms5611_i2c.c.
References baro_ms5611, Ms5611Data::c, Ms5611_I2c::data, DefaultChannel, DefaultDevice, foo, and Ms5611_I2c::initialized.
Referenced by baro_ms5611_periodic_check().
Variable Documentation
baro_ms5611
struct Ms5611_I2c baro_ms5611
Definition at line 55 of file baro_ms5611_i2c.c.
Referenced by baro_ms5611_event(), baro_ms5611_init(), baro_ms5611_periodic_check(), baro_ms5611_read(), and baro_ms5611_send_coeff().
baro_ms5611_alt
float baro_ms5611_alt
Definition at line 58 of file baro_ms5611_i2c.c.
Referenced by baro_ms5611_event().
baro_ms5611_alt_valid
bool baro_ms5611_alt_valid
Definition at line 59 of file baro_ms5611_i2c.c.
Referenced by baro_ms5611_event(), and baro_ms5611_init().
baro_ms5611_enabled
bool baro_ms5611_enabled
Definition at line 60 of file baro_ms5611_i2c.c.
Referenced by alt_kalman(), and baro_ms5611_init().
baro_ms5611_r
float baro_ms5611_r
Definition at line 62 of file baro_ms5611_i2c.c.
Referenced by alt_kalman(), and baro_ms5611_init().
baro_ms5611_sigma2
float baro_ms5611_sigma2
Definition at line 63 of file baro_ms5611_i2c.c.
Referenced by alt_kalman(), and baro_ms5611_init().
fbaroms
float fbaroms
Definition at line 57 of file baro_ms5611_i2c.c.
Referenced by baro_event(), and baro_ms5611_event().
ftempms
float ftempms
Definition at line 57 of file baro_ms5611_i2c.c.