Paparazzi UAS: sw/airborne/modules/sensors/baro_mpl3115.c File Reference
baro_mpl3115.c File Reference
Module for the baro MPL3115A2 from Freescale (i2c)
#include "modules/sensors/baro_mpl3115.h"
#include "peripherals/mpl3115.h"
#include "modules/core/abi.h"
#include "mcu_periph/uart.h"
#include "pprzlink/messages.h"
#include "modules/datalink/downlink.h"
Macros
#define BARO_MPL3115_I2C_DEV i2c0
#define BARO_MPL3115_I2C_SLAVE_ADDR MPL3115_I2C_ADDR
Functions
void baro_mpl3115_init (void)
void baro_mpl3115_read_periodic (void)
void baro_mpl3115_read_event (void)
Variables
struct Mpl3115 baro_mpl
Detailed Description
Module for the baro MPL3115A2 from Freescale (i2c)
Definition in file baro_mpl3115.c.
Macro Definition Documentation
BARO_MPL3115_I2C_DEV
#define BARO_MPL3115_I2C_DEV i2c0
Definition at line 40 of file baro_mpl3115.c.
BARO_MPL3115_I2C_SLAVE_ADDR
#define BARO_MPL3115_I2C_SLAVE_ADDR MPL3115_I2C_ADDR
Definition at line 44 of file baro_mpl3115.c.
Function Documentation
baro_mpl3115_init()
void baro_mpl3115_init (void)
Definition at line 50 of file baro_mpl3115.c.
References baro_mpl, BARO_MPL3115_I2C_DEV, BARO_MPL3115_I2C_SLAVE_ADDR, and mpl3115_init().
baro_mpl3115_read_event()
void baro_mpl3115_read_event (void)
Definition at line 62 of file baro_mpl3115.c.
References baro_mpl, BARO_MPL3115_SENDER_ID, Mpl3115::data_available, DefaultChannel, DefaultDevice, foo, get_sys_time_usec(), mpl3115_event(), Mpl3115::pressure, and Mpl3115::temperature.
baro_mpl3115_read_periodic()
void baro_mpl3115_read_periodic (void)
Definition at line 56 of file baro_mpl3115.c.
References baro_mpl, and mpl3115_periodic().
Variable Documentation
baro_mpl
struct Mpl3115 baro_mpl
Definition at line 48 of file baro_mpl3115.c.
Referenced by baro_mpl3115_init(), baro_mpl3115_read_event(), and baro_mpl3115_read_periodic().