Paparazzi UAS: sw/airborne/modules/sensors/baro_ms5611_spi.h File Reference
baro_ms5611_spi.h File Reference
Measurement Specialties (Intersema) MS5611-01BA pressure/temperature sensor interface for SPI.
#include "std.h"
#include "peripherals/ms5611_spi.h"
Macros
#define BARO_MS5611_DT BARO_MS5611_READ_PERIOD
new measurement with every baro_ms5611_read() call
#define BARO_MS5611_R 20
#define BARO_MS5611_SIGMA2 1
Functions
void baro_ms5611_init (void)
void baro_ms5611_read (void)
trigger new measurement or initialize if needed
void baro_ms5611_periodic_check (void)
void baro_ms5611_event (void)
void baro_ms5611_send_coeff (void)
Variables
float baro_ms5611_r
float baro_ms5611_sigma2
float baro_ms5611_alt
bool baro_ms5611_alt_valid
bool baro_ms5611_enabled
struct Ms5611_Spi baro_ms5611
Detailed Description
Measurement Specialties (Intersema) MS5611-01BA pressure/temperature sensor interface for SPI.
Definition in file baro_ms5611_spi.h.
Macro Definition Documentation
BARO_MS5611_DT
#define BARO_MS5611_DT BARO_MS5611_READ_PERIOD
new measurement with every baro_ms5611_read() call
Definition at line 36 of file baro_ms5611_spi.h.
BARO_MS5611_R
#define BARO_MS5611_R 20
Definition at line 37 of file baro_ms5611_spi.h.
BARO_MS5611_SIGMA2
#define BARO_MS5611_SIGMA2 1
Definition at line 38 of file baro_ms5611_spi.h.
Function Documentation
baro_ms5611_event()
void baro_ms5611_event (void) extern
Definition at line 96 of file baro_ms5611_i2c.c.
References baro_ms5611, baro_ms5611_alt, baro_ms5611_alt_valid, BARO_MS5611_SENDER_ID, Ms5611Data::d1, Ms5611Data::d2, Ms5611_I2c::data, Ms5611_Spi::data, Ms5611_I2c::data_available, Ms5611_Spi::data_available, DefaultChannel, DefaultDevice, fbaroms, foo, get_sys_time_usec(), ms5611_i2c_event(), ms5611_spi_event(), pprz_isa_altitude_of_pressure(), Ms5611Data::pressure, Ms5611Data::temperature, and update_median_filter_f().
baro_ms5611_init()
void baro_ms5611_init (void) extern
Definition at line 66 of file baro_ms5611_i2c.c.
References baro_ms5611, baro_ms5611_alt_valid, baro_ms5611_enabled, baro_ms5611_r, BARO_MS5611_R, baro_ms5611_sigma2, BARO_MS5611_SIGMA2, FALSE, foo, init_median_filter_f(), MEDIAN_DEFAULT_SIZE, MS5611_I2C_DEV, ms5611_i2c_init(), MS5611_SLAVE_ADDR, MS5611_SLAVE_IDX, MS5611_SPI_DEV, ms5611_spi_init(), and MS5611_TYPE_MS5607.
baro_ms5611_periodic_check()
void baro_ms5611_periodic_check (void) extern
Definition at line 77 of file baro_ms5611_i2c.c.
References baro_ms5611, baro_ms5611_send_coeff(), foo, ms5611_i2c_periodic_check(), and ms5611_spi_periodic_check().
baro_ms5611_read()
void baro_ms5611_read (void) extern
trigger new measurement or initialize if needed
Definition at line 89 of file baro_ms5611_i2c.c.
References baro_ms5611, ms5611_i2c_read(), ms5611_spi_read(), and sys_time::nb_sec.
baro_ms5611_send_coeff()
void baro_ms5611_send_coeff (void) extern
Definition at line 121 of file baro_ms5611_i2c.c.
References baro_ms5611, Ms5611Data::c, Ms5611_I2c::data, Ms5611_Spi::data, DefaultChannel, DefaultDevice, foo, Ms5611_I2c::initialized, and Ms5611_Spi::initialized.
Referenced by baro_ms5611_periodic_check().
Variable Documentation
baro_ms5611
struct Ms5611_Spi baro_ms5611 extern
Definition at line 55 of file baro_ms5611_i2c.c.
Referenced by baro_ms5611_event(), baro_ms5611_init(), baro_ms5611_periodic_check(), baro_ms5611_read(), and baro_ms5611_send_coeff().
baro_ms5611_alt
float baro_ms5611_alt extern
Definition at line 58 of file baro_ms5611_i2c.c.
Referenced by baro_ms5611_event().
baro_ms5611_alt_valid
bool baro_ms5611_alt_valid extern
Definition at line 59 of file baro_ms5611_i2c.c.
Referenced by baro_ms5611_event(), and baro_ms5611_init().
baro_ms5611_enabled
bool baro_ms5611_enabled extern
Definition at line 60 of file baro_ms5611_i2c.c.
Referenced by alt_kalman(), and baro_ms5611_init().
baro_ms5611_r
float baro_ms5611_r extern
Definition at line 62 of file baro_ms5611_i2c.c.
Referenced by alt_kalman(), and baro_ms5611_init().
baro_ms5611_sigma2
float baro_ms5611_sigma2 extern
Definition at line 63 of file baro_ms5611_i2c.c.
Referenced by alt_kalman(), and baro_ms5611_init().