Paparazzi UAS: sw/airborne/modules/sensors/baro_bmp.h File Reference
baro_bmp.h File Reference
Bosch BMP085 I2C sensor interface.
#include "peripherals/bmp085.h"
Macros
#define BARO_BMP_DT (BARO_BMP_PERIODIC_PERIOD / 3)
new measurement every 3rd baro_bmp_periodic
Functions
void baro_bmp_init (void)
void baro_bmp_periodic (void)
void baro_bmp_event (void)
Variables
struct Bmp085 baro_bmp
bool baro_bmp_enabled
float baro_bmp_r
float baro_bmp_sigma2
int32_t baro_bmp_alt
Detailed Description
Bosch BMP085 I2C sensor interface.
This reads the values for pressure and temperature from the Bosch BMP085 sensor through I2C.
Definition in file baro_bmp.h.
Macro Definition Documentation
BARO_BMP_DT
#define BARO_BMP_DT (BARO_BMP_PERIODIC_PERIOD / 3)
new measurement every 3rd baro_bmp_periodic
Definition at line 39 of file baro_bmp.h.
Function Documentation
baro_bmp_event()
void baro_bmp_event (void)
Definition at line 81 of file baro_bmp.c.
References baro_bmp, baro_bmp_alt, BARO_BMP_SENDER_ID, BARO_BOARD_SENDER_ID, bmp085_event(), Bmp085::data_available, DefaultChannel, DefaultDevice, foo, get_sys_time_usec(), Bmp085::pressure, Bmp085::temperature, Bmp085::up, and Bmp085::ut.
baro_bmp_init()
void baro_bmp_init (void)
Definition at line 59 of file baro_bmp.c.
References baro_bmp, baro_bmp_enabled, BARO_BMP_R, baro_bmp_r, BARO_BMP_SIGMA2, baro_bmp_sigma2, bmp085_init(), BMP085_SLAVE_ADDR, and BMP_I2C_DEV.
baro_bmp_periodic()
void baro_bmp_periodic (void)
Definition at line 70 of file baro_bmp.c.
References baro_bmp, bmp085_periodic(), bmp085_read_eeprom_calib(), and Bmp085::initialized.
Variable Documentation
baro_bmp
struct Bmp085 baro_bmp extern
Definition at line 52 of file baro_bmp.c.
Referenced by baro_bmp_event(), baro_bmp_init(), and baro_bmp_periodic().
baro_bmp_alt
int32_t baro_bmp_alt extern
Definition at line 57 of file baro_bmp.c.
Referenced by baro_bmp_event().
baro_bmp_enabled
bool baro_bmp_enabled extern
Definition at line 54 of file baro_bmp.c.
Referenced by alt_kalman(), and baro_bmp_init().
baro_bmp_r
float baro_bmp_r extern
Definition at line 55 of file baro_bmp.c.
Referenced by alt_kalman(), and baro_bmp_init().
baro_bmp_sigma2
float baro_bmp_sigma2 extern
Definition at line 56 of file baro_bmp.c.
Referenced by alt_kalman(), and baro_bmp_init().