Paparazzi UAS: sw/airborne/boards/baro_board_ms5611_i2c.c File Reference
baro_board_ms5611_i2c.c File Reference
Driver for onboard MS5611 baro via I2C.
#include "modules/sensors/baro.h"
#include "peripherals/ms5611_i2c.h"
#include <BOARD_CONFIG>
#include "mcu_periph/sys_time.h"
#include "led.h"
#include "std.h"
#include "modules/core/abi.h"
#include "mcu_periph/uart.h"
#include "pprzlink/messages.h"
#include "modules/datalink/downlink.h"
Macros
#define BB_MS5611_SLAVE_ADDR 0xEE
default i2c address when CSB is set to GND addr is 0xEE when CSB is set to VCC addr is 0xEC
#define BB_MS5611_TYPE_MS5607 FALSE
set to TRUE if baro is actually a MS5607
Functions
void baro_init (void)
void baro_periodic (void)
void baro_event (void)
Variables
struct Ms5611_I2c bb_ms5611
Detailed Description
Driver for onboard MS5611 baro via I2C.
Definition in file baro_board_ms5611_i2c.c.
Macro Definition Documentation
BB_MS5611_SLAVE_ADDR
#define BB_MS5611_SLAVE_ADDR 0xEE
default i2c address when CSB is set to GND addr is 0xEE when CSB is set to VCC addr is 0xEC
Note: Aspirin 2.1 has CSB bound to GND.
Definition at line 56 of file baro_board_ms5611_i2c.c.
BB_MS5611_TYPE_MS5607
#define BB_MS5611_TYPE_MS5607 FALSE
set to TRUE if baro is actually a MS5607
Definition at line 61 of file baro_board_ms5611_i2c.c.
Function Documentation
baro_event()
void baro_event (void)
Definition at line 98 of file baro_board_ms5611_i2c.c.
References BARO_BOARD_SENDER_ID, bb_ms5611, Ms5611Data::d1, Ms5611Data::d2, Ms5611_I2c::data, Ms5611_I2c::data_available, DefaultChannel, DefaultDevice, fbaroms, foo, get_sys_time_usec(), LED_TOGGLE, ms5611_i2c_event(), sys_time::nb_sec, Ms5611Data::pressure, and Ms5611Data::temperature.
baro_init()
void baro_init (void)
Definition at line 67 of file baro_board_ms5611_i2c.c.
References bb_ms5611, BB_MS5611_SLAVE_ADDR, BB_MS5611_TYPE_MS5607, foo, LED_OFF, and ms5611_i2c_init().
baro_periodic()
void baro_periodic (void)
Definition at line 76 of file baro_board_ms5611_i2c.c.
References bb_ms5611, Ms5611Data::c, Ms5611_I2c::data, DefaultChannel, DefaultDevice, foo, Ms5611_I2c::initialized, ms5611_i2c_periodic(), and sys_time::nb_sec.
Variable Documentation
bb_ms5611
struct Ms5611_I2c bb_ms5611
Definition at line 65 of file baro_board_ms5611_i2c.c.
Referenced by baro_event(), baro_init(), and baro_periodic().