Paparazzi UAS: sw/airborne/modules/sensors/baro_bmp280.c File Reference
baro_bmp280.c File Reference
Bosch BMP280 sensor interface.
#include "baro_bmp280.h"
#include "modules/core/abi.h"
#include "mcu_periph/uart.h"
#include "pprzlink/messages.h"
#include "modules/datalink/downlink.h"
#include "math/pprz_isa.h"
#include "modules/datalink/telemetry.h"
Macros
#define BMP280_USE_SPI FALSE
#define BMP280_SLAVE_ADDR BMP280_I2C_ADDR
default slave address
#define BMP280_SLAVE_IDX SPI_SLAVE0
Functions
static void send_baro_bmp_data (struct transport_tx *trans, struct link_device *dev)
void baro_bmp280_init (void)
void baro_bmp280_periodic (void)
void baro_bmp280_event (void)
Variables
float baro_alt = 0
float baro_temp = 0
float baro_press = 0
bool baro_alt_valid = 0
struct bmp280_t baro_bmp280
Detailed Description
Bosch BMP280 sensor interface.
This reads the values for pressure and temperature from the Bosch BMP280 sensor.
Definition in file baro_bmp280.c.
Macro Definition Documentation
BMP280_SLAVE_ADDR
#define BMP280_SLAVE_ADDR BMP280_I2C_ADDR
default slave address
Definition at line 51 of file baro_bmp280.c.
BMP280_SLAVE_IDX
#define BMP280_SLAVE_IDX SPI_SLAVE0
Definition at line 55 of file baro_bmp280.c.
BMP280_USE_SPI
#define BMP280_USE_SPI FALSE
Definition at line 44 of file baro_bmp280.c.
Function Documentation
baro_bmp280_event()
void baro_bmp280_event (void)
Definition at line 103 of file baro_bmp280.c.
References baro_alt, baro_alt_valid, baro_bmp280, BARO_BMP_SENDER_ID, baro_press, baro_temp, bmp280_event(), bmp280_t::data_available, DefaultChannel, DefaultDevice, foo, get_sys_time_usec(), p, pprz_isa_altitude_of_pressure(), bmp280_t::pressure, bmp280_t::raw_pressure, bmp280_t::raw_temperature, bmp280_t::temperature, and up.
baro_bmp280_init()
void baro_bmp280_init (void)
Definition at line 81 of file baro_bmp280.c.
References baro_bmp280, BMP280_I2C, bmp280_init(), BMP280_SLAVE_ADDR, BMP280_SLAVE_IDX, BMP280_SPI, bmp280_t::bus, DefaultPeriodic, foo, register_periodic_telemetry(), and send_baro_bmp_data().
baro_bmp280_periodic()
void baro_bmp280_periodic (void)
Definition at line 98 of file baro_bmp280.c.
References baro_bmp280, and bmp280_periodic().
send_baro_bmp_data()
static void send_baro_bmp_data (struct transport_tx * trans, struct link_device * dev) static
Definition at line 68 of file baro_bmp280.c.
References baro_alt, baro_press, baro_temp, dev, and foo.
Referenced by baro_bmp280_init().
Variable Documentation
baro_alt
float baro_alt = 0
Definition at line 59 of file baro_bmp280.c.
Referenced by baro_bmp280_event(), baro_cb(), ins_mekf_wind_update_baro(), and send_baro_bmp_data().
baro_alt_valid
bool baro_alt_valid = 0
Definition at line 62 of file baro_bmp280.c.
Referenced by baro_bmp280_event().
baro_bmp280
struct bmp280_t baro_bmp280
Definition at line 65 of file baro_bmp280.c.
Referenced by baro_bmp280_event(), baro_bmp280_init(), and baro_bmp280_periodic().
baro_press
float baro_press = 0
Definition at line 61 of file baro_bmp280.c.
Referenced by baro_bmp280_event(), and send_baro_bmp_data().
baro_temp
float baro_temp = 0
Definition at line 60 of file baro_bmp280.c.
Referenced by baro_bmp280_event(), and send_baro_bmp_data().