Paparazzi UAS: sw/airborne/modules/sensors/baro_bmp280_i2c.h File Reference
baro_bmp280_i2c.h File Reference
Bosch BMP280 I2C sensor interface.
#include "peripherals/bmp280_i2c.h"
Functions
void baro_bmp280_init (void)
void baro_bmp280_periodic (void)
void baro_bmp280_event (void)
Variables
struct Bmp280_I2c baro_bmp280
float baro_alt
bool baro_alt_valid
Detailed Description
Bosch BMP280 I2C sensor interface.
This reads the values for pressure and temperature from the Bosch BMP280 sensor through I2C.
Definition in file baro_bmp280_i2c.h.
Function Documentation
void baro_bmp280_event (void)
Definition at line 82 of file baro_bmp280_i2c.c.
References baro_alt, baro_alt_valid, baro_bmp280, BARO_BMP_SENDER_ID, baro_press, baro_temp, bmp280_i2c_event(), Bmp280_I2c::data_available, DefaultChannel, DefaultDevice, get_sys_time_usec(), p, pprz_isa_altitude_of_pressure(), Bmp280_I2c::pressure, Bmp280_I2c::raw_pressure, Bmp280_I2c::raw_temperature, Bmp280_I2c::temperature, and up.
void baro_bmp280_init (void)
Definition at line 68 of file baro_bmp280_i2c.c.
References baro_bmp280, bmp280_i2c_init(), BMP280_SLAVE_ADDR, DefaultPeriodic, register_periodic_telemetry(), and send_baro_bmp_data().
void baro_bmp280_periodic (void)
Definition at line 77 of file baro_bmp280_i2c.c.
References baro_bmp280, and bmp280_i2c_periodic().
Variable Documentation
float baro_alt
Definition at line 46 of file baro_bmp280_i2c.c.
Referenced by baro_bmp280_event(), baro_cb(), ins_mekf_wind_update_baro(), and send_baro_bmp_data().
bool baro_alt_valid
Definition at line 49 of file baro_bmp280_i2c.c.
Referenced by baro_bmp280_event().
struct Bmp280_I2c baro_bmp280
Definition at line 52 of file baro_bmp280_i2c.c.
Referenced by baro_bmp280_event(), baro_bmp280_init(), and baro_bmp280_periodic().