Paparazzi UAS: sw/airborne/subsystems/sensors/baro.h File Reference
baro.h File Reference
Common barometric sensor implementation.
#include <BOARD_CONFIG>
Functions
void baro_init (void)
void baro_periodic (void)
Detailed Description
Common barometric sensor implementation.
Used with baro integrated to the autopilot board. Implementation is in boards/<board_name>/baro_board.[ch]
Definition in file baro.h.
Function Documentation
void baro_init (void)
Definition at line 76 of file baro_board.c.
References BaroBoard::absolute, adc_buf_channel(), ADC_CHANNEL_BARO, ads1114_init(), apogee_baro, baro_bmp085, baro_board, baro_eoc(), baro_read(), BARO_STARTUP_COUNTER, baro_swing_available, baro_swing_raw, bb_ms5611, bb_ms5611_filt, BB_MS5611_SLAVE_ADDR, BB_MS5611_TYPE_MS5607, BB_UNINITIALIZED, bmp085_init(), BMP085_SLAVE_ADDR, BaroBoard::buf, DACSet(), DEFAULT_AV_NB_SAMPLE, Bmp085::eoc, GPIO0, gpio_clear(), gpio_setup_input_pulldown(), GPIOB, init_median_filter_f(), init_median_filter_i(), LBS_UNINITIALIZED, LED_OFF, mcp355x_init(), MEDIAN_DEFAULT_SIZE, MPL3115_I2C_ADDR, mpl3115_init(), ms5611_i2c_init(), ms5611_spi_init(), BaroBoard::offset, BaroBoard::running, startup_cnt, BaroBoard::status, and BaroBoard::value_filtered.
Referenced by init_ap(), and main_init().
void baro_periodic (void)
Definition at line 90 of file baro_board.c.
References BaroBoard::absolute, ads1114_read(), apogee_baro, adc_buf::av_nb_sample, BARO_ABS_ADDR, BARO_ABS_ADS, baro_bmp085, baro_board, baro_board_calibrate(), baro_board_read_from_current_register(), baro_board_send_config_abs(), baro_board_send_config_diff(), baro_board_send_reset(), BARO_BOARD_SENDER_ID, baro_board_set_current_register(), BARO_DIFF_ADDR, bb_ms5611, BB_UNINITIALIZED, bmp085_periodic(), bmp085_read_eeprom_calib(), BOOZ_ANALOG_BARO_THRESHOLD, BOOZ_BARO_SENS, BaroBoard::buf, Ms5611Data::c, Mpu60x0_I2c::config, Ms5611_I2c::data, Ms5611_Spi::data, Mpl3115::data_available, DefaultChannel, DefaultDevice, get_sys_time_usec(), i2c_idle(), imu_apogee, Ms5611_I2c::initialized, Ms5611_Spi::initialized, Bmp085::initialized, Mpu60x0Config::initialized, LBS_INITIALIZING_ABS, LBS_INITIALIZING_ABS_1, LBS_INITIALIZING_DIFF, LBS_INITIALIZING_DIFF_1, LBS_READ_ABS, LBS_READ_DIFF, LBS_READING_ABS, LBS_READING_DIFF, LBS_RESETED, LBS_UNINITIALIZED, LED_ON, LED_TOGGLE, mcp355x_read(), mpl3115_periodic(), MPL_PRESCALER, ImuApogee::mpu, ms5611_i2c_periodic(), ms5611_spi_periodic(), sys_time::nb_sec, BaroBoard::running, startup_cnt, BaroBoard::status, adc_buf::sum, TRUE, and BaroBoard::value_filtered.
Referenced by handle_periodic_tasks(), and handle_periodic_tasks_ap().