Paparazzi UAS: sw/airborne/modules/sensors/baro_bmp.c File Reference
baro_bmp.c File Reference
Bosch BMP085 I2C sensor interface.
#include "baro_bmp.h"
#include "peripherals/bmp085_regs.h"
#include "mcu_periph/sys_time.h"
#include "mcu_periph/i2c.h"
#include "led.h"
#include "mcu_periph/uart.h"
#include "modules/core/abi.h"
#include "pprzlink/messages.h"
#include "modules/datalink/downlink.h"
Macros
#define BMP_I2C_DEV i2c0
#define BARO_BMP_R 0.5
#define BARO_BMP_SIGMA2 0.1
Functions
void baro_bmp_init (void)
void baro_bmp_periodic (void)
void baro_bmp_event (void)
Variables
struct Bmp085 baro_bmp
bool baro_bmp_enabled
float baro_bmp_r
float baro_bmp_sigma2
int32_t baro_bmp_alt
Detailed Description
Bosch BMP085 I2C sensor interface.
This reads the values for pressure and temperature from the Bosch BMP085 sensor through I2C.
Definition in file baro_bmp.c.
Macro Definition Documentation
BARO_BMP_R
#define BARO_BMP_R 0.5
Definition at line 48 of file baro_bmp.c.
BARO_BMP_SIGMA2
#define BARO_BMP_SIGMA2 0.1
Definition at line 49 of file baro_bmp.c.
BMP_I2C_DEV
#define BMP_I2C_DEV i2c0
Definition at line 45 of file baro_bmp.c.
Function Documentation
baro_bmp_event()
void baro_bmp_event (void)
Definition at line 81 of file baro_bmp.c.
References baro_bmp, baro_bmp_alt, BARO_BMP_SENDER_ID, BARO_BOARD_SENDER_ID, bmp085_event(), Bmp085::data_available, DefaultChannel, DefaultDevice, foo, get_sys_time_usec(), Bmp085::pressure, Bmp085::temperature, Bmp085::up, and Bmp085::ut.
baro_bmp_init()
void baro_bmp_init (void)
Definition at line 59 of file baro_bmp.c.
References baro_bmp, baro_bmp_enabled, BARO_BMP_R, baro_bmp_r, BARO_BMP_SIGMA2, baro_bmp_sigma2, bmp085_init(), BMP085_SLAVE_ADDR, and BMP_I2C_DEV.
baro_bmp_periodic()
void baro_bmp_periodic (void)
Definition at line 70 of file baro_bmp.c.
References baro_bmp, bmp085_periodic(), bmp085_read_eeprom_calib(), and Bmp085::initialized.
Variable Documentation
baro_bmp
struct Bmp085 baro_bmp
Definition at line 52 of file baro_bmp.c.
Referenced by baro_bmp_event(), baro_bmp_init(), and baro_bmp_periodic().
baro_bmp_alt
int32_t baro_bmp_alt
Definition at line 57 of file baro_bmp.c.
Referenced by baro_bmp_event().
baro_bmp_enabled
bool baro_bmp_enabled
Definition at line 54 of file baro_bmp.c.
Referenced by alt_kalman(), and baro_bmp_init().
baro_bmp_r
float baro_bmp_r
Definition at line 55 of file baro_bmp.c.
Referenced by alt_kalman(), and baro_bmp_init().
baro_bmp_sigma2
float baro_bmp_sigma2
Definition at line 56 of file baro_bmp.c.
Referenced by alt_kalman(), and baro_bmp_init().