Paparazzi UAS: sw/airborne/modules/sensors/bat_voltage_ardrone2.h File Reference
bat_voltage_ardrone2.h File Reference
Functions
void bat_voltage_ardrone2_init (void)
void bat_voltage_ardrone2_periodic (void)
Function Documentation
bat_voltage_ardrone2_init()
void bat_voltage_ardrone2_init (void)
Definition at line 48 of file bat_voltage_ardrone2.c.
References electrical_ardrone2_setup(), fd, foo, and I2C_SLAVE_FORCE.
bat_voltage_ardrone2_periodic()
void bat_voltage_ardrone2_periodic (void)
Definition at line 89 of file bat_voltage_ardrone2.c.
References electrical, electrical_ardrone2_setup(), fd, foo, i2c_smbus_read_byte_data(), and Electrical::vsupply.