Paparazzi UAS: sw/airborne/modules/sensors/bat_voltage_ardrone2.c File Reference
bat_voltage_ardrone2.c File Reference
Read battery voltage on ARDrone2 and publish to electrical subsystem.
#include "modules/sensors/bat_voltage_ardrone2.h"
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <fcntl.h>
#include <sys/time.h>
#include <unistd.h>
#include <math.h>
#include "mcu_periph/i2c_smbus.h"
#include "modules/energy/electrical.h"
Functions
void electrical_ardrone2_setup (void)
void bat_voltage_ardrone2_init (void)
void bat_voltage_ardrone2_periodic (void)
Variables
static int fd
Detailed Description
Read battery voltage on ARDrone2 and publish to electrical subsystem.
Read the battery voltage on ARDrone2.
Definition in file bat_voltage_ardrone2.c.
Function Documentation
bat_voltage_ardrone2_init()
void bat_voltage_ardrone2_init (void)
Definition at line 48 of file bat_voltage_ardrone2.c.
References electrical_ardrone2_setup(), fd, foo, and I2C_SLAVE_FORCE.
bat_voltage_ardrone2_periodic()
void bat_voltage_ardrone2_periodic (void)
Definition at line 89 of file bat_voltage_ardrone2.c.
References electrical, electrical_ardrone2_setup(), fd, foo, i2c_smbus_read_byte_data(), and Electrical::vsupply.
electrical_ardrone2_setup()
void electrical_ardrone2_setup (void)
Definition at line 65 of file bat_voltage_ardrone2.c.
References fd, foo, and i2c_smbus_write_byte_data().
Referenced by bat_voltage_ardrone2_init(), and bat_voltage_ardrone2_periodic().
Variable Documentation
fd
int fd static
Definition at line 46 of file bat_voltage_ardrone2.c.
Referenced by bat_voltage_ardrone2_init(), bat_voltage_ardrone2_periodic(), and electrical_ardrone2_setup().