Paparazzi UAS: sw/airborne/modules/datalink/missionlib/blocks.h File Reference
blocks.h File Reference
PPRZ specific mission block implementation.
#include <mavlink/mavlink_types.h>
Functions
void mavlink_block_message_handler (const mavlink_message_t *msg)
void mavlink_send_block (uint16_t seq)
Detailed Description
PPRZ specific mission block implementation.
Definition in file blocks.h.
Function Documentation
mavlink_block_message_handler()
void mavlink_block_message_handler (const mavlink_message_t * msg) extern
Definition at line 65 of file blocks.c.
References foo, MAVLINK_DEBUG, mavlink_mission_cancel_timer(), mavlink_mission_set_timer(), mavlink_send_block(), mavlink_send_block_count(), mavlink_system, mission_mgr, msg, nav_goto_block(), mavlink_mission_mgr::rem_compid, mavlink_mission_mgr::rem_sysid, mavlink_mission_mgr::seq, mavlink_mission_mgr::state, STATE_IDLE, STATE_SEND_ITEM, and STATE_SEND_LIST.
Referenced by mavlink_mission_message_handler().
mavlink_send_block()
void mavlink_send_block (uint16_t seq) extern
Definition at line 48 of file blocks.c.
References foo, MAVLINK_DEBUG, MAVLinkSendMessage, mission_mgr, mavlink_mission_mgr::rem_compid, mavlink_mission_mgr::rem_sysid, and seq.
Referenced by mavlink_block_message_handler().