Paparazzi UAS: sw/airborne/peripherals/bmi088_i2c.c File Reference
bmi088_i2c.c File Reference
Driver for the BMI088 using I2C.
#include "peripherals/bmi088_i2c.h"
Macros
#define Int16FromBuf(_buf, _idx) ((int16_t)((_buf[_idx+1]<<8) | _buf[_idx]))
Functions
void bmi088_i2c_init (struct Bmi088_I2c *bmi, struct i2c_periph *i2c_p, uint8_t gyro_addr, uint8_t accel_addr)
static void bmi088_i2c_write_to_reg (void *bmi, uint8_t _reg, uint8_t _val, uint8_t _type)
void bmi088_i2c_start_configure (struct Bmi088_I2c *bmi)
void bmi088_i2c_read (struct Bmi088_I2c *bmi)
void bmi088_i2c_event (struct Bmi088_I2c *bmi)
Detailed Description
Driver for the BMI088 using I2C.
Definition in file bmi088_i2c.c.
Macro Definition Documentation
Int16FromBuf
#define Int16FromBuf (_buf, _idx) ((int16_t)((_buf[_idx+1]<<8) | _buf[_idx]))
Definition at line 91 of file bmi088_i2c.c.
Function Documentation
bmi088_i2c_event()
void bmi088_i2c_event (struct Bmi088_I2c * bmi)
Definition at line 93 of file bmi088_i2c.c.
References Bmi088_I2c::accel_available, Bmi088_I2c::accel_trans, BMI088_CONF_ACCEL_PWR_CTRL, BMI088_CONF_UNINIT, bmi088_i2c_write_to_reg(), bmi088_send_config(), i2c_transaction::buf, Bmi088_I2c::config, Bmi088_I2c::data_accel, Bmi088_I2c::data_rates, Bmi088_I2c::gyro_available, Bmi088_I2c::gyro_trans, I2CTransDone, I2CTransFailed, I2CTransSuccess, Bmi088Config::init_status, Bmi088Config::initialized, Int16FromBuf, and i2c_transaction::status.
Referenced by imu_bmi088_event().
bmi088_i2c_init()
void bmi088_i2c_init (struct Bmi088_I2c * bmi, struct i2c_periph * i2c_p, uint8_t gyro_addr, uint8_t accel_addr)
Definition at line 30 of file bmi088_i2c.c.
References Bmi088_I2c::accel_available, Bmi088_I2c::accel_trans, BMI088_CONF_UNINIT, bmi088_set_default_config(), Bmi088_I2c::config, foo, Bmi088_I2c::gyro_available, Bmi088_I2c::gyro_trans, Bmi088_I2c::i2c_p, I2CTransDone, Bmi088Config::init_status, Bmi088Config::initialized, i2c_transaction::slave_addr, and i2c_transaction::status.
Referenced by imu_bmi088_init().
bmi088_i2c_read()
void bmi088_i2c_read (struct Bmi088_I2c * bmi)
Definition at line 77 of file bmi088_i2c.c.
References Bmi088_I2c::accel_trans, BMI088_ACCEL_X_LSB, BMI088_GYRO_RATE_X_LSB, i2c_transaction::buf, Bmi088_I2c::config, Bmi088_I2c::gyro_trans, Bmi088_I2c::i2c_p, i2c_transceive(), I2CTransDone, Bmi088Config::initialized, i2c_transaction::slave_addr, and i2c_transaction::status.
Referenced by bmi088_i2c_periodic().
bmi088_i2c_start_configure()
void bmi088_i2c_start_configure (struct Bmi088_I2c * bmi)
Definition at line 67 of file bmi088_i2c.c.
References Bmi088_I2c::accel_trans, BMI088_CONF_UNINIT, bmi088_i2c_write_to_reg(), bmi088_send_config(), Bmi088_I2c::config, I2CTransDone, I2CTransSuccess, Bmi088Config::init_status, and i2c_transaction::status.
Referenced by bmi088_i2c_periodic().
bmi088_i2c_write_to_reg()
static void bmi088_i2c_write_to_reg (void * bmi, uint8_t _reg, uint8_t _val, uint8_t _type) static
Definition at line 52 of file bmi088_i2c.c.
References Bmi088_I2c::accel_trans, BMI088_CONFIG_ACCEL, BMI088_CONFIG_GYRO, i2c_transaction::buf, foo, and i2c_transmit().
Referenced by bmi088_i2c_event(), and bmi088_i2c_start_configure().