Paparazzi UAS: sw/airborne/peripherals/bmi088.c File Reference
bmi088.c File Reference
BMI088 driver common functions (I2C and SPI).
#include "peripherals/bmi088.h"
Functions
void bmi088_set_default_config (struct Bmi088Config *c)
void bmi088_send_config (Bmi088ConfigSet bmi_set, void *bmi, struct Bmi088Config *config)
Configuration sequence called once before normal use.
Variables
const float BMI088_GYRO_SENS [5]
const struct FloatRates BMI088_GYRO_SENS_F [5]
const float BMI088_ACCEL_SENS [4]
const struct FloatVect3 BMI088_ACCEL_SENS_F [4]
Detailed Description
BMI088 driver common functions (I2C and SPI).
Still needs the either I2C or SPI specific implementation.
Definition in file bmi088.c.
Function Documentation
bmi088_send_config()
void bmi088_send_config (Bmi088ConfigSet bmi_set, void * bmi, struct Bmi088Config * config)
Configuration sequence called once before normal use.
Definition at line 70 of file bmi088.c.
References Bmi088Config::accel_bw, Bmi088Config::accel_odr, Bmi088Config::accel_range, Bmi088Config::accel_samplerate, BMI088_ACCEL_ACTIVE, BMI088_ACCEL_CONF, BMI088_ACCEL_ODR_100, BMI088_ACCEL_ODR_12, BMI088_ACCEL_ODR_1600, BMI088_ACCEL_ODR_200, BMI088_ACCEL_ODR_25, BMI088_ACCEL_ODR_400, BMI088_ACCEL_ODR_50, BMI088_ACCEL_ODR_800, BMI088_ACCEL_POWER_ON, BMI088_ACCEL_PWR_CONF, BMI088_ACCEL_PWR_CTRl, BMI088_ACCEL_RANGE, BMI088_CONF_ACCEL_ODR, BMI088_CONF_ACCEL_PWR_CONF, BMI088_CONF_ACCEL_PWR_CTRL, BMI088_CONF_ACCEL_RANGE, BMI088_CONF_DONE, BMI088_CONF_GYRO_ODR, BMI088_CONF_GYRO_PWR, BMI088_CONF_GYRO_RANGE, BMI088_CONFIG_ACCEL, BMI088_CONFIG_GYRO, BMI088_GYRO_BAND_WIDTH, BMI088_GYRO_LPM_1, BMI088_GYRO_NORMAL, BMI088_GYRO_ODR_1000_BW_116, BMI088_GYRO_ODR_100_BW_12, BMI088_GYRO_ODR_100_BW_32, BMI088_GYRO_ODR_2000_BW_230, BMI088_GYRO_ODR_2000_BW_532, BMI088_GYRO_ODR_200_BW_23, BMI088_GYRO_ODR_200_BW_64, BMI088_GYRO_ODR_400_BW_47, BMI088_GYRO_RANGE, foo, Bmi088Config::gyro_odr, Bmi088Config::gyro_range, Bmi088Config::gyro_samplerate, Bmi088Config::init_status, and Bmi088Config::initialized.
Referenced by bmi088_i2c_event(), and bmi088_i2c_start_configure().
bmi088_set_default_config()
void bmi088_set_default_config (struct Bmi088Config * c)
Definition at line 61 of file bmi088.c.
References Bmi088Config::accel_bw, Bmi088Config::accel_odr, Bmi088Config::accel_range, BMI088_DEFAULT_ACCEL_BW, BMI088_DEFAULT_ACCEL_ODR, BMI088_DEFAULT_ACCEL_RANGE, BMI088_DEFAULT_GYRO_ODR, BMI088_DEFAULT_GYRO_RANGE, Bmi088Config::gyro_odr, and Bmi088Config::gyro_range.
Referenced by bmi088_i2c_init().
Variable Documentation
BMI088_ACCEL_SENS
const float BMI088_ACCEL_SENS[4]
Initial value:
= {
  BMI088_ACCEL_SENS_3G,
  BMI088_ACCEL_SENS_6G,
  BMI088_ACCEL_SENS_12G,
  BMI088_ACCEL_SENS_24G
}
Definition at line 47 of file bmi088.c.
BMI088_ACCEL_SENS_F
const struct FloatVect3 BMI088_ACCEL_SENS_F[4]
Initial value:
= {
  {BMI088_ACCEL_SENS_3G, BMI088_ACCEL_SENS_3G, BMI088_ACCEL_SENS_3G},
  {BMI088_ACCEL_SENS_6G, BMI088_ACCEL_SENS_6G, BMI088_ACCEL_SENS_6G},
  {BMI088_ACCEL_SENS_12G, BMI088_ACCEL_SENS_12G, BMI088_ACCEL_SENS_12G},
  {BMI088_ACCEL_SENS_24G, BMI088_ACCEL_SENS_24G, BMI088_ACCEL_SENS_24G}
}
Definition at line 54 of file bmi088.c.
Referenced by imu_bmi088_init().
BMI088_GYRO_SENS
const float BMI088_GYRO_SENS[5]
Initial value:
= {
  BMI088_GYRO_SENS_2000,
  BMI088_GYRO_SENS_1000,
  BMI088_GYRO_SENS_500,
  BMI088_GYRO_SENS_250,
  BMI088_GYRO_SENS_125,
}
Definition at line 31 of file bmi088.c.
BMI088_GYRO_SENS_F
const struct FloatRates BMI088_GYRO_SENS_F[5]
Initial value:
= {
  {BMI088_GYRO_SENS_2000, BMI088_GYRO_SENS_2000, BMI088_GYRO_SENS_2000},
  {BMI088_GYRO_SENS_1000, BMI088_GYRO_SENS_1000, BMI088_GYRO_SENS_1000},
  {BMI088_GYRO_SENS_500, BMI088_GYRO_SENS_500, BMI088_GYRO_SENS_500},
  {BMI088_GYRO_SENS_250, BMI088_GYRO_SENS_250, BMI088_GYRO_SENS_250},
  {BMI088_GYRO_SENS_125, BMI088_GYRO_SENS_125, BMI088_GYRO_SENS_125}
}
Definition at line 39 of file bmi088.c.
Referenced by imu_bmi088_init().