Paparazzi UAS: sw/airborne/boards/ardrone/actuators.h File Reference
actuators.h File Reference
Actuator driver for ardrone2-raw version.
#include <stdint.h>
Macros
#define ACTUATORS_ARDRONE_NB 4
#define SERVOS_TICS_OF_USEC(_v) (_v)
#define ActuatorArdroneSet actuators_ardrone_set
#define ActuatorsArdroneCommit actuators_ardrone_commit
#define ActuatorsArdroneInit actuators_ardrone_init
#define MOT_LEDOFF 0
#define MOT_LEDRED 1
#define MOT_LEDGREEN 2
#define MOT_LEDORANGE 3
Functions
void actuators_ardrone_commit (void)
void actuators_ardrone_init (void)
void actuators_ardrone_set (uint8_t idx, int16_t value)
int actuators_ardrone_cmd (uint8_t cmd, uint8_t *reply, int replylen)
void actuators_ardrone_set_pwm (uint16_t pwm0, uint16_t pwm1, uint16_t pwm2, uint16_t pwm3)
Write motor speed command cmd = 001aaaaa aaaabbbb bbbbbccc ccccccdd ddddddd0.
void actuators_ardrone_set_leds (uint8_t led0, uint8_t led1, uint8_t led2, uint8_t led3)
Write LED command cmd = 011rrrr0 000gggg0 (this is ardrone1 format, we need ardrone2 format)
void actuators_ardrone_close (void)
Variables
uint16_t actuators_pwm_values [ACTUATORS_ARDRONE_NB]
Detailed Description
Actuator driver for ardrone2-raw version.
Definition in file actuators.h.
Macro Definition Documentation
ActuatorArdroneSet
#define ActuatorArdroneSet actuators_ardrone_set
Definition at line 42 of file actuators.h.
ACTUATORS_ARDRONE_NB
#define ACTUATORS_ARDRONE_NB 4
Definition at line 37 of file actuators.h.
ActuatorsArdroneCommit
#define ActuatorsArdroneCommit actuators_ardrone_commit
Definition at line 43 of file actuators.h.
ActuatorsArdroneInit
#define ActuatorsArdroneInit actuators_ardrone_init
Definition at line 44 of file actuators.h.
MOT_LEDGREEN
#define MOT_LEDGREEN 2
Definition at line 48 of file actuators.h.
MOT_LEDOFF
#define MOT_LEDOFF 0
Definition at line 46 of file actuators.h.
MOT_LEDORANGE
#define MOT_LEDORANGE 3
Definition at line 49 of file actuators.h.
MOT_LEDRED
#define MOT_LEDRED 1
Definition at line 47 of file actuators.h.
SERVOS_TICS_OF_USEC
#define SERVOS_TICS_OF_USEC (_v) (_v)
Definition at line 40 of file actuators.h.
Function Documentation
actuators_ardrone_close()
void actuators_ardrone_close (void)
Definition at line 279 of file actuators.c.
References actuator_ardrone2_fd, and foo.
actuators_ardrone_cmd()
int actuators_ardrone_cmd (uint8_t cmd, uint8_t * reply, int replylen)
Definition at line 159 of file actuators.c.
References actuator_ardrone2_fd, foo, full_read(), and full_write().
Referenced by actuators_ardrone_init().
actuators_ardrone_commit()
void actuators_ardrone_commit (void) extern
Definition at line 221 of file actuators.c.
References actuators_ardrone_motor_status(), actuators_ardrone_set_pwm(), actuators_pwm_values, and foo.
actuators_ardrone_init()
void actuators_ardrone_init (void) extern
Definition at line 82 of file actuators.c.
References actuator_ardrone2_fd, actuators_ardrone_cmd(), actuators_ardrone_reset_flipflop(), actuators_ardrone_set_leds(), ARDRONE_GPIO_PIN_IRQ_FLIPFLOP, ARDRONE_GPIO_PIN_IRQ_INPUT, ARDRONE_GPIO_PIN_MOTOR1, ARDRONE_GPIO_PIN_MOTOR2, ARDRONE_GPIO_PIN_MOTOR3, ARDRONE_GPIO_PIN_MOTOR4, ARDRONE_GPIO_PORT, B115200, foo, gpio_clear(), gpio_set(), gpio_setup_input(), gpio_setup_output(), led_hw_values, MOT_LEDGREEN, and MOT_LEDRED.
actuators_ardrone_set()
void actuators_ardrone_set (uint8_t idx, int16_t value) extern
Definition at line 228 of file actuators.c.
References ACTUATORS_ARDRONE_NB, actuators_pwm_values, and idx.
actuators_ardrone_set_leds()
void actuators_ardrone_set_leds (uint8_t led0, uint8_t led1, uint8_t led2, uint8_t led3)
Write LED command cmd = 011rrrr0 000gggg0 (this is ardrone1 format, we need ardrone2 format)
led0 = RearLeft led1 = RearRight led2 = FrontRight led3 = FrontLeft
Definition at line 262 of file actuators.c.
References actuator_ardrone2_fd, foo, and full_write().
Referenced by actuators_ardrone_init(), and actuators_ardrone_led_run().
actuators_ardrone_set_pwm()
void actuators_ardrone_set_pwm (uint16_t pwm0, uint16_t pwm1, uint16_t pwm2, uint16_t pwm3)
Write motor speed command cmd = 001aaaaa aaaabbbb bbbbbccc ccccccdd ddddddd0.
Definition at line 239 of file actuators.c.
References actuator_ardrone2_fd, actuators_ardrone_led_run(), foo, and full_write().
Referenced by actuators_ardrone_commit().
Variable Documentation
actuators_pwm_values
uint16_t actuators_pwm_values[ACTUATORS_ARDRONE_NB] extern
Definition at line 69 of file actuators.c.