Paparazzi UAS: sw/airborne/boards/bebop/actuators.c File Reference
actuators.c File Reference
Actuator driver for the bebop and bebop 2.
#include "modules/actuators/actuators.h"
#include "modules/energy/electrical.h"
#include "actuators.h"
#include "led_hw.h"
#include "autopilot.h"
#include "modules/core/abi.h"
#include "modules/datalink/telemetry.h"
#include "firmwares/rotorcraft/stabilization.h"
Macros
#define ACTUATORS_BEBOP_I2C_TIMEOUT 1.f
Functions
static void send_bebop_actuators (struct transport_tx *trans, struct link_device *dev)
static uint8_t actuators_bebop_checksum (uint8_t *bytes, uint8_t size)
void actuators_bebop_init (void)
void actuators_bebop_set (uint8_t idx, int16_t value)
void actuators_bebop_commit (void)
Variables
uint32_t led_hw_values
struct ActuatorsBebop actuators_bebop
Detailed Description
Actuator driver for the bebop and bebop 2.
Definition in file actuators.c.
Macro Definition Documentation
ACTUATORS_BEBOP_I2C_TIMEOUT
#define ACTUATORS_BEBOP_I2C_TIMEOUT 1.f
Definition at line 69 of file actuators.c.
Function Documentation
actuators_bebop_checksum()
static uint8_t actuators_bebop_checksum (uint8_t * bytes, uint8_t size) static
Definition at line 170 of file actuators.c.
References checksum.
Referenced by actuators_bebop_commit().
actuators_bebop_commit()
void actuators_bebop_commit (void)
Definition at line 92 of file actuators.c.
References ACT_FEEDBACK_BOARD_ID, actuators_bebop, actuators_bebop_checksum(), ACTUATORS_BEBOP_CLEAR_ERROR, ACTUATORS_BEBOP_GET_OBS_DATA, ACTUATORS_BEBOP_I2C_TIMEOUT, ACTUATORS_BEBOP_SET_REF_SPEED, ACTUATORS_BEBOP_START_PROP, ACTUATORS_BEBOP_STOP_PROP, ACTUATORS_BEBOP_TOGGLE_GPIO, autopilot_get_motors_on(), autopilot_set_motors_on(), i2c_transaction::buf, electrical, foo, i2c_blocking_transceive(), i2c_blocking_transmit(), ActuatorsBebop::i2c_trans, act_feedback_t::idx, ActuatorsBebop::led, led_hw_values, act_feedback_t::act_feedback_set_t::rpm, act_feedback_t::rpm, ActuatorsBebop::rpm_obs, ActuatorsBebop::rpm_ref, act_feedback_t::set, i2c_transaction::slave_addr, and Electrical::vsupply.
actuators_bebop_init()
void actuators_bebop_init (void)
Definition at line 75 of file actuators.c.
References actuators_bebop, ACTUATORS_BEBOP_ADDR, DefaultPeriodic, foo, ActuatorsBebop::i2c_trans, I2CTransDone, ActuatorsBebop::led, register_periodic_telemetry(), send_bebop_actuators(), i2c_transaction::slave_addr, and i2c_transaction::status.
actuators_bebop_set()
void actuators_bebop_set (uint8_t idx, int16_t value)
Definition at line 87 of file actuators.c.
References actuators_bebop, idx, and ActuatorsBebop::rpm_ref.
send_bebop_actuators()
static void send_bebop_actuators (struct transport_tx * trans, struct link_device * dev) static
Definition at line 43 of file actuators.c.
References actuators_bebop, Stabilization::cmd, commands, dev, foo, ActuatorsBebop::rpm_obs, ActuatorsBebop::rpm_ref, and stabilization.
Referenced by actuators_bebop_init().
Variable Documentation
actuators_bebop
struct ActuatorsBebop actuators_bebop
Definition at line 72 of file actuators.c.
Referenced by actuators_bebop_commit(), actuators_bebop_init(), actuators_bebop_set(), logger_file_write_row(), and send_bebop_actuators().
led_hw_values
uint32_t led_hw_values
Definition at line 71 of file actuators.c.