Paparazzi UAS: sw/airborne/modules/energy/can_fuelcell.h File Reference
can_fuelcell.h File Reference
#include "std.h"
Functions
void can_fuelcell_init (void)
void can_fuelcell_periodic (void)
Function Documentation
can_fuelcell_init()
void can_fuelcell_init (void) extern
Definition at line 106 of file can_fuelcell.c.
References can_fuelcell_send_telemetry(), DefaultPeriodic, foo, fuelcell_uavcan_cb(), fuelcell_uavcan_ev, register_periodic_telemetry(), and uavcan_bind().
can_fuelcell_periodic()
void can_fuelcell_periodic (void) extern
Definition at line 77 of file can_fuelcell.c.
References can_fuelcell_data, and uavcan_equipment_fuelcell::timeout.