Paparazzi UAS: sw/airborne/modules/energy/can_fuelcell.c File Reference
can_fuelcell.c File Reference
#include "modules/energy/can_fuelcell.h"
#include "modules/datalink/telemetry.h"
#include "uavcan/uavcan.h"
#include "pprz.equipment.fuelcell.Status.h"
Data Structures
struct uavcan_equipment_fuelcell
Functions
static void fuelcell_uavcan_cb (struct uavcan_iface_t *iface, CanardRxTransfer *transfer)
void can_fuelcell_periodic (void)
static void can_fuelcell_send_telemetry (struct transport_tx *trans, struct link_device *dev)
void can_fuelcell_init (void)
Variables
static struct uavcan_equipment_fuelcell can_fuelcell_data = { 0, 67, 0.78, 45.9, 1457.0, 1234.0, -223.0, 2, 12, 7}
static uavcan_event fuelcell_uavcan_ev
Detailed Description
Author
F. van Tienen Fuel-cell data through CAN bus
Definition in file can_fuelcell.c.
Data Structure Documentation
uavcan_equipment_fuelcell
struct uavcan_equipment_fuelcell
Definition at line 33 of file can_fuelcell.c.
Data Fields
uint8_t error
float power_batt
float power_cell
float power_out
float press_reg
uint8_t pressure
uint8_t state
uint8_t suberror
int timeout
float volt_bat
Function Documentation
can_fuelcell_init()
void can_fuelcell_init (void)
Definition at line 106 of file can_fuelcell.c.
References can_fuelcell_send_telemetry(), DefaultPeriodic, foo, fuelcell_uavcan_cb(), fuelcell_uavcan_ev, register_periodic_telemetry(), and uavcan_bind().
can_fuelcell_periodic()
void can_fuelcell_periodic (void) extern
Definition at line 77 of file can_fuelcell.c.
References can_fuelcell_data, and uavcan_equipment_fuelcell::timeout.
can_fuelcell_send_telemetry()
static void can_fuelcell_send_telemetry (struct transport_tx * trans, struct link_device * dev) static
Definition at line 93 of file can_fuelcell.c.
References can_fuelcell_data, dev, uavcan_equipment_fuelcell::error, foo, uavcan_equipment_fuelcell::power_batt, uavcan_equipment_fuelcell::power_cell, uavcan_equipment_fuelcell::power_out, uavcan_equipment_fuelcell::press_reg, uavcan_equipment_fuelcell::pressure, uavcan_equipment_fuelcell::state, uavcan_equipment_fuelcell::suberror, uavcan_equipment_fuelcell::timeout, and uavcan_equipment_fuelcell::volt_bat.
Referenced by can_fuelcell_init().
fuelcell_uavcan_cb()
static void fuelcell_uavcan_cb (struct uavcan_iface_t * iface, CanardRxTransfer * transfer) static
Definition at line 53 of file can_fuelcell.c.
References can_fuelcell_data, uavcan_equipment_fuelcell::error, foo, msg, uavcan_equipment_fuelcell::power_batt, uavcan_equipment_fuelcell::power_cell, uavcan_equipment_fuelcell::power_out, uavcan_equipment_fuelcell::press_reg, uavcan_equipment_fuelcell::pressure, uavcan_equipment_fuelcell::state, uavcan_equipment_fuelcell::suberror, uavcan_equipment_fuelcell::timeout, transfer(), and uavcan_equipment_fuelcell::volt_bat.
Referenced by can_fuelcell_init().
Variable Documentation
can_fuelcell_data
struct uavcan_equipment_fuelcell can_fuelcell_data = { 0, 67, 0.78, 45.9, 1457.0, 1234.0, -223.0, 2, 12, 7} static
Definition at line 46 of file can_fuelcell.c.
Referenced by can_fuelcell_periodic(), can_fuelcell_send_telemetry(), and fuelcell_uavcan_cb().
fuelcell_uavcan_ev
uavcan_event fuelcell_uavcan_ev static
Definition at line 51 of file can_fuelcell.c.
Referenced by can_fuelcell_init().