Paparazzi UAS: sw/airborne/arch/stm32/mcu_periph/can_arch.h File Reference
can_arch.h File Reference
STM32 architecture
Handling of CAN hardware for STM32.
Functions
void can_hw_init (void)
int can_hw_transmit (uint32_t id, const uint8_t *buf, uint8_t len)
Detailed Description
Handling of CAN hardware for STM32.
Definition in file can_arch.h.
Function Documentation
void can_hw_init (void)
Definition at line 55 of file can_arch.c.
References CAN1, can_initialized, GPIO8, GPIO9, GPIO_AF9, gpio_set(), GPIOB, NVIC_CAN1_RX_IRQ_PRIO, and NVIC_USB_LP_CAN_RX0_IRQ_PRIO.
Referenced by ppz_can_init().
int can_hw_transmit (uint32_t id, const uint8_t * buf, uint8_t len)
Definition at line 169 of file can_arch.c.
References CAN1, and can_initialized.
Referenced by ppz_can_transmit().