Paparazzi UAS: sw/airborne/modules/radio_control/cc2500_frsky/cc2500_frsky_x.h File Reference
cc2500_frsky_x.h File Reference
#include "cc2500_compat.h"
Macros
#define RC_CHANNEL_COUNT_FRSKY_X 16
Functions
void frSkyXSetRcData (uint16_t *rcData, const uint8_t *payload)
void frSkyXInit (const rx_spi_protocol_e spiProtocol)
rx_spi_received_e frSkyXHandlePacket (uint8_t *const packet, uint8_t *const protocolState)
rx_spi_received_e frSkyXProcessFrame (uint8_t *const packet)
Macro Definition Documentation
RC_CHANNEL_COUNT_FRSKY_X
#define RC_CHANNEL_COUNT_FRSKY_X 16
Definition at line 29 of file cc2500_frsky_x.h.
Function Documentation
frSkyXHandlePacket()
rx_spi_received_e frSkyXHandlePacket (uint8_t *const packet, uint8_t *const protocolState)
Definition at line 340 of file cc2500_frsky_x.c.
References telemetrySequenceMarkerData_s::ackSequenceId, buildTelemetryFrame(), CC2500_3B_RXBYTES, CC2500_READ_BURST, CC2500_SFRX, CC2500_SIDLE, CC2500_SRX, cc2500getGdo(), cc2500ReadFifo(), cc2500ReadReg(), cc2500SetPower(), cc2500setRssiDbm(), cc2500Strobe(), cc2500WriteFifo(), cmpTimeUs(), telemetrySequenceMarker_s::data, DEBUG_DATA_BAD_FRAME, DEBUG_DATA_MISSING_PACKETS, DEBUG_SET, delayMicroseconds, FALLTHROUGH, foo, frame, initialiseData(), isValidPacket(), listLength, MAX_MISSING_PKT, micros, missingPackets, telemetryBuffer_s::needsProcessing, nextChannel(), packetLength, telemetrySequenceMarkerData_s::packetSequenceId, protocolState, telemetrySequenceMarker_s::raw, remoteToProcessId, remoteToProcessIndex, responseToSend, telemetrySequenceMarkerData_s::retransmissionRequested, RSSI_SOURCE_RX_PROTOCOL, RX_SPI_RECEIVED_DATA, RX_SPI_RECEIVED_NONE, RX_SPI_ROCESSING_REQUIRED, rxSpiCheckBindRequested(), rxSpiLedOn(), rxSpiLedToggle(), setRssiDirect(), STATE_DATA, STATE_INIT, STATE_RESUME, STATE_STARTING, STATE_TELEMETRY, STATE_UPDATE, SYNC_DELAY_MAX, TELEMETRY_FRAME_SIZE, TELEMETRY_SEQUENCE_LENGTH, telemetryDelayUs, telemetryEnabled, telemetryRxBuffer, and timeoutUs.
Referenced by frSkySpiInit().
frSkyXInit()
void frSkyXInit (const rx_spi_protocol_e spiProtocol)
Definition at line 582 of file cc2500_frsky_x.c.
References FEATURE_TELEMETRY, featureIsEnabled, frSkyXTelemetryWriteFrame(), initSmartPortTelemetryExternal(), packetLength, RX_SPI_FRSKY_X, RX_SPI_FRSKY_X_LBT, spiProtocol, telemetryDelayUs, and telemetryEnabled.
Referenced by frSkySpiInit().
frSkyXProcessFrame()
rx_spi_received_e frSkyXProcessFrame (uint8_t *const packet)
Definition at line 544 of file cc2500_frsky_x.c.
References telemetryBuffer_s::data, foo, frSkyXCheckQueueEmpty(), millis, telemetryBuffer_s::needsProcessing, processSmartPortTelemetry(), remoteToProcessId, remoteToProcessIndex, RX_SPI_RECEIVED_NONE, smartPortDataReceive(), TELEMETRY_SEQUENCE_LENGTH, telemetryRxBuffer, and UNUSED.
Referenced by frSkySpiInit().
frSkyXSetRcData()
void frSkyXSetRcData (uint16_t * rcData, const uint8_t * payload)
Definition at line 304 of file cc2500_frsky_x.c.
References foo, and rcData.
Referenced by frSkySpiInit().