Paparazzi UAS: sw/airborne/modules/radio_control/cc2500_frsky/cc2500_rx_spi.h File Reference
cc2500_rx_spi.h File Reference
#include "cc2500_compat.h"
#include "cc2500_settings.h"
#include "cc2500_rx.h"
Macros
#define RC_CHANNEL_RATE RC_SPI_AUX1
#define RC_CHANNEL_FLIP RC_SPI_AUX2
#define RC_CHANNEL_PICTURE RC_SPI_AUX3
#define RC_CHANNEL_VIDEO RC_SPI_AUX4
#define RC_CHANNEL_HEADLESS RC_SPI_AUX5
#define RC_CHANNEL_RTH RC_SPI_AUX6
Enumerations
enum rx_spi_protocol_e {
RX_SPI_NRF24_V202_250K = 0 , RX_SPI_NRF24_V202_1M , RX_SPI_NRF24_SYMA_X , RX_SPI_NRF24_SYMA_X5C ,
RX_SPI_NRF24_CX10 , RX_SPI_NRF24_CX10A , RX_SPI_NRF24_H8_3D , RX_SPI_NRF24_INAV ,
RX_SPI_FRSKY_D , RX_SPI_FRSKY_X , RX_SPI_A7105_FLYSKY , RX_SPI_A7105_FLYSKY_2A ,
RX_SPI_NRF24_KN , RX_SPI_SFHSS , RX_SPI_CYRF6936_DSM , RX_SPI_FRSKY_X_LBT ,
RX_SPI_PROTOCOL_COUNT
}
enum rx_spi_received_e { RX_SPI_RECEIVED_NONE = 0 , RX_SPI_RECEIVED_BIND = (1 << 0) , RX_SPI_RECEIVED_DATA = (1 << 1) , RX_SPI_ROCESSING_REQUIRED = (1 << 2) }
enum rc_spi_aetr_e {
RC_SPI_ROLL = 0 , RC_SPI_PITCH , RC_SPI_THROTTLE , RC_SPI_YAW ,
RC_SPI_AUX1 , RC_SPI_AUX2 , RC_SPI_AUX3 , RC_SPI_AUX4 ,
RC_SPI_AUX5 , RC_SPI_AUX6 , RC_SPI_AUX7 , RC_SPI_AUX8 ,
RC_SPI_AUX9 , RC_SPI_AUX10 , RC_SPI_AUX11 , RC_SPI_AUX12 ,
RC_SPI_AUX13 , RC_SPI_AUX14
}
Functions
bool rxSpiInit (const rxSpiConfig_t *rxSpiConfig, rxRuntimeConfig_t *rxRuntimeConfig)
Macro Definition Documentation
RC_CHANNEL_FLIP
#define RC_CHANNEL_FLIP RC_SPI_AUX2
Definition at line 85 of file cc2500_rx_spi.h.
RC_CHANNEL_HEADLESS
#define RC_CHANNEL_HEADLESS RC_SPI_AUX5
Definition at line 88 of file cc2500_rx_spi.h.
RC_CHANNEL_PICTURE
#define RC_CHANNEL_PICTURE RC_SPI_AUX3
Definition at line 86 of file cc2500_rx_spi.h.
RC_CHANNEL_RATE
#define RC_CHANNEL_RATE RC_SPI_AUX1
Definition at line 84 of file cc2500_rx_spi.h.
RC_CHANNEL_RTH
#define RC_CHANNEL_RTH RC_SPI_AUX6
Definition at line 89 of file cc2500_rx_spi.h.
RC_CHANNEL_VIDEO
#define RC_CHANNEL_VIDEO RC_SPI_AUX4
Definition at line 87 of file cc2500_rx_spi.h.
Enumeration Type Documentation
rc_spi_aetr_e
enum rc_spi_aetr_e
Enumerator
RC_SPI_ROLL
RC_SPI_PITCH
RC_SPI_THROTTLE
RC_SPI_YAW
RC_SPI_AUX1
RC_SPI_AUX2
RC_SPI_AUX3
RC_SPI_AUX4
RC_SPI_AUX5
RC_SPI_AUX6
RC_SPI_AUX7
RC_SPI_AUX8
RC_SPI_AUX9
RC_SPI_AUX10
RC_SPI_AUX11
RC_SPI_AUX12
RC_SPI_AUX13
RC_SPI_AUX14
Definition at line 62 of file cc2500_rx_spi.h.
rx_spi_protocol_e
enum rx_spi_protocol_e
Enumerator
RX_SPI_NRF24_V202_250K
RX_SPI_NRF24_V202_1M
RX_SPI_NRF24_SYMA_X
RX_SPI_NRF24_SYMA_X5C
RX_SPI_NRF24_CX10
RX_SPI_NRF24_CX10A
RX_SPI_NRF24_H8_3D
RX_SPI_NRF24_INAV
RX_SPI_FRSKY_D
RX_SPI_FRSKY_X
RX_SPI_A7105_FLYSKY
RX_SPI_A7105_FLYSKY_2A
RX_SPI_NRF24_KN
RX_SPI_SFHSS
RX_SPI_CYRF6936_DSM
RX_SPI_FRSKY_X_LBT
RX_SPI_PROTOCOL_COUNT
Definition at line 34 of file cc2500_rx_spi.h.
rx_spi_received_e
enum rx_spi_received_e
Enumerator
RX_SPI_RECEIVED_NONE
RX_SPI_RECEIVED_BIND
RX_SPI_RECEIVED_DATA
RX_SPI_ROCESSING_REQUIRED
Definition at line 54 of file cc2500_rx_spi.h.
Function Documentation
rxSpiInit()
bool rxSpiInit (const rxSpiConfig_t * rxSpiConfig, rxRuntimeConfig_t * rxRuntimeConfig)
Definition at line 228 of file cc2500_rx_spi.c.
References foo, protocolInit, rxRuntimeConfig_s::rcFrameStatusFn, rxRuntimeConfig_s::rcProcessFrameFn, rxRuntimeConfig_s::rcReadRawFn, rxSpiConfig_s::rx_spi_protocol, rxRuntimeConfig_s::rxRefreshRate, rxRuntimeConfig, rxSpiConfig(), rxSpiDeviceInit, rxSpiFrameStatus(), rxSpiNewPacketAvailable, rxSpiProcessFrame(), rxSpiReadRawRC(), and rxSpiSetProtocol().
Referenced by rxInit().