Paparazzi UAS: sw/airborne/modules/radio_control/cc2500_frsky/cc2500_frsky_shared.h File Reference
cc2500_frsky_shared.h File Reference
Macros
#define MAX_MISSING_PKT 100
#define DEBUG_DATA_ERROR_COUNT 0
#define DEBUG_DATA_MISSING_PACKETS 1
#define DEBUG_DATA_BAD_FRAME 2
#define SYNC_DELAY_MAX 9000
#define MAX_MISSING_PKT 100
Enumerations
enum {
STATE_INIT = 0 , STATE_BIND , STATE_BIND_TUNING , STATE_BIND_BINDING1 ,
STATE_BIND_BINDING2 , STATE_BIND_COMPLETE , STATE_STARTING , STATE_UPDATE ,
STATE_DATA , STATE_TELEMETRY , STATE_RESUME
}
Functions
void initialiseData (bool inBindState)
void nextChannel (uint8_t skip)
Variables
uint8_t listLength
uint32_t missingPackets
timeDelta_t timeoutUs
Macro Definition Documentation
DEBUG_DATA_BAD_FRAME
#define DEBUG_DATA_BAD_FRAME 2
Definition at line 30 of file cc2500_frsky_shared.h.
DEBUG_DATA_ERROR_COUNT
#define DEBUG_DATA_ERROR_COUNT 0
Definition at line 28 of file cc2500_frsky_shared.h.
DEBUG_DATA_MISSING_PACKETS
#define DEBUG_DATA_MISSING_PACKETS 1
Definition at line 29 of file cc2500_frsky_shared.h.
MAX_MISSING_PKT [1/2]
#define MAX_MISSING_PKT 100
Definition at line 26 of file cc2500_frsky_shared.h.
MAX_MISSING_PKT [2/2]
#define MAX_MISSING_PKT 100
Definition at line 26 of file cc2500_frsky_shared.h.
SYNC_DELAY_MAX
#define SYNC_DELAY_MAX 9000
Definition at line 33 of file cc2500_frsky_shared.h.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
STATE_INIT
STATE_BIND
STATE_BIND_TUNING
STATE_BIND_BINDING1
STATE_BIND_BINDING2
STATE_BIND_COMPLETE
STATE_STARTING
STATE_UPDATE
STATE_DATA
STATE_TELEMETRY
STATE_RESUME
Definition at line 37 of file cc2500_frsky_shared.h.
Function Documentation
initialiseData()
void initialiseData (bool inBindState)
Definition at line 169 of file cc2500_frsky_shared.c.
References bindOffset, rxCc2500SpiConfig_s::bindTxId, CC2500_03_FIFOTHR, CC2500_07_PKTCTRL1, CC2500_09_ADDR, CC2500_0C_FSCTRL0, CC2500_18_MCSM0, CC2500_19_FOCCFG, cc2500WriteReg(), delay, foo, and rxCc2500SpiConfig().
Referenced by frSkySpiDataReceived(), and frSkyXHandlePacket().
nextChannel()
void nextChannel (uint8_t skip)
Definition at line 412 of file cc2500_frsky_shared.c.
References calData, CC2500_0A_CHANNR, CC2500_23_FSCAL3, CC2500_24_FSCAL2, CC2500_25_FSCAL1, CC2500_SFRX, CC2500_SIDLE, cc2500Strobe(), cc2500WriteReg(), foo, listLength, RX_SPI_FRSKY_D, rxCc2500SpiConfig(), and spiProtocol.
Referenced by frSkyXHandlePacket().
Variable Documentation
listLength
uint8_t listLength extern
Definition at line 72 of file cc2500_frsky_shared.c.
Referenced by frSkyXHandlePacket(), getBind2(), initGetBind(), and nextChannel().
missingPackets
uint32_t missingPackets extern
Definition at line 67 of file cc2500_frsky_shared.c.
Referenced by frSkySpiInit(), and frSkyXHandlePacket().
timeoutUs
timeDelta_t timeoutUs extern
Definition at line 68 of file cc2500_frsky_shared.c.
Referenced by dshotRpmCatchErps(), frSkySpiInit(), and frSkyXHandlePacket().