Paparazzi UAS: sw/airborne/modules/radio_control/cc2500_frsky/cc2500_frsky_common.h File Reference
cc2500_frsky_common.h File Reference
#include "cc2500_compat.h"
#include "cc2500_settings.h"
Functions
bool frSkySpiInit (const rxSpiConfig_t *rxSpiConfig, rxRuntimeConfig_t *rxRuntimeConfig)
rx_spi_received_e frSkySpiDataReceived (uint8_t *packet)
rx_spi_received_e frSkySpiProcessFrame (uint8_t *packet)
void frSkySpiSetRcData (uint16_t *rcData, const uint8_t *payload)
Function Documentation
frSkySpiDataReceived()
rx_spi_received_e frSkySpiDataReceived (uint8_t * packet)
Definition at line 327 of file cc2500_frsky_shared.c.
References CC2500_SIDLE, cc2500Strobe(), delay, foo, getBind1(), getBind2(), handlePacket, initGetBind(), initialise(), initialiseData(), initTuneRx(), millis, protocolState, RX_SPI_RECEIVED_BIND, RX_SPI_RECEIVED_NONE, rxCc2500SpiConfig(), rxSpiCheckBindRequested(), rxSpiLedOn(), rxSpiLedToggle(), start_time, STATE_BIND, STATE_BIND_BINDING1, STATE_BIND_BINDING2, STATE_BIND_COMPLETE, STATE_BIND_TUNING, STATE_INIT, STATE_STARTING, tuneRx(), and writeEEPROM.
Referenced by rxSpiSetProtocol().
frSkySpiInit()
bool frSkySpiInit (const rxSpiConfig_t * rxSpiConfig, rxRuntimeConfig_t * rxRuntimeConfig)
Definition at line 433 of file cc2500_frsky_shared.c.
References cc2500SpiInit(), rxRuntimeConfig_s::channelCount, frSkyDHandlePacket(), frSkyDInit(), frSkyDSetRcData(), frSkyXHandlePacket(), frSkyXInit(), frSkyXProcessFrame(), frSkyXSetRcData(), handlePacket, millis, missingPackets, processFrame, protocolState, RC_CHANNEL_COUNT_FRSKY_D, RC_CHANNEL_COUNT_FRSKY_X, RSSI_SOURCE_NONE, RSSI_SOURCE_RX_PROTOCOL, rssiSource, RX_SPI_FRSKY_D, RX_SPI_FRSKY_X, RX_SPI_FRSKY_X_LBT, rxSpiConfig_s::rx_spi_protocol, rxRuntimeConfig, rxSpiCommonIOInit(), rxSpiConfig(), setRcData, spiProtocol, start_time, STATE_INIT, and timeoutUs.
Referenced by rxSpiSetProtocol().
frSkySpiProcessFrame()
rx_spi_received_e frSkySpiProcessFrame (uint8_t * packet)
Definition at line 398 of file cc2500_frsky_shared.c.
References foo, processFrame, and RX_SPI_RECEIVED_NONE.
Referenced by rxSpiSetProtocol().
frSkySpiSetRcData()
void frSkySpiSetRcData (uint16_t * rcData, const uint8_t * payload)
Definition at line 407 of file cc2500_frsky_shared.c.
References rcData, and setRcData.
Referenced by rxSpiSetProtocol().