Paparazzi UAS: sw/airborne/subsystems/radio_control/cc2500_frsky/cc2500_common.c File Reference
cc2500_common.c File Reference
#include "cc2500_compat.h"
#include "peripherals/cc2500.h"
#include "cc2500_settings.h"
#include "cc2500_common.h"
#include "cc2500_rx.h"
#include <stdbool.h>
Functions
uint16_t cc2500getRssiDbm (void)
void cc2500setRssiDbm (uint8_t value)
bool cc2500getGdo (void)
static bool cc2500SpiDetect (void)
bool cc2500SpiInit (void)
Variables
static IO_t gdoPin
static int16_t rssiDbm
Function Documentation
bool cc2500getGdo (void)
Definition at line 80 of file cc2500_common.c.
References IORead.
Referenced by frSkyXHandlePacket(), getBind1(), getBind2(), and tuneRx().
uint16_t cc2500getRssiDbm (void)
Definition at line 64 of file cc2500_common.c.
References rssiDbm.
Referenced by buildTelemetryFrame().
void cc2500setRssiDbm (uint8_t value)
Definition at line 69 of file cc2500_common.c.
References RSSI_SOURCE_RX_PROTOCOL, rssiDbm, and setRssi().
Referenced by frSkyXHandlePacket().
static bool cc2500SpiDetect (void) static
Definition at line 116 of file cc2500_common.c.
References CC2500_30_PARTNUM, CC2500_31_VERSION, CC2500_READ_BURST, and cc2500ReadReg().
Referenced by cc2500SpiInit().
bool cc2500SpiInit (void)
Definition at line 127 of file cc2500_common.c.
References cc2500SpiDetect(), IO_NONE, IOCFG_IN_FLOATING, IOCFG_OUT_PP, IOConfigGPIO, IOGetByTag, IOHi, IOInit, OWNER_RX_SPI_EXTI, RSSI_SOURCE_NONE, RSSI_SOURCE_RX_PROTOCOL, rssiSource, rxCc2500SpiConfig(), and rxSpiConfig().
Referenced by frSkySpiInit().
Variable Documentation
IO_t gdoPin static
Definition at line 54 of file cc2500_common.c.
int16_t rssiDbm static
Definition at line 62 of file cc2500_common.c.
Referenced by cc2500getRssiDbm(), and cc2500setRssiDbm().