Paparazzi UAS: sw/airborne/modules/radio_control/cc2500_frsky/cc2500_frsky_d.h File Reference
cc2500_frsky_d.h File Reference
#include "cc2500_compat.h"
Macros
#define RC_CHANNEL_COUNT_FRSKY_D 8
Functions
static rx_spi_received_e frSkyDHandlePacket (uint8_t *const packet, uint8_t *const protocolState)
static void frSkyDSetRcData (uint16_t *rcData, const uint8_t *payload)
static void frSkyDInit (void)
Macro Definition Documentation
RC_CHANNEL_COUNT_FRSKY_D
#define RC_CHANNEL_COUNT_FRSKY_D 8
Definition at line 4 of file cc2500_frsky_d.h.
Function Documentation
frSkyDHandlePacket()
static rx_spi_received_e frSkyDHandlePacket (uint8_t *const packet, uint8_t *const protocolState) static
Definition at line 6 of file cc2500_frsky_d.h.
References foo, protocolState, and RX_SPI_RECEIVED_NONE.
Referenced by frSkySpiInit().
frSkyDInit()
static void frSkyDInit (void) static
Definition at line 18 of file cc2500_frsky_d.h.
Referenced by frSkySpiInit().
frSkyDSetRcData()
static void frSkyDSetRcData (uint16_t * rcData, const uint8_t * payload) static
Definition at line 12 of file cc2500_frsky_d.h.
References foo, and rcData.
Referenced by frSkySpiInit().