Paparazzi UAS: sw/airborne/modules/radio_control/cc2500_frsky/cc2500_common.h File Reference
cc2500_common.h File Reference
#include "cc2500_compat.h"
#include "cc2500_rx_spi.h"
Functions
uint16_t cc2500getRssiDbm (void)
void cc2500setRssiDbm (uint8_t value)
bool cc2500getGdo (void)
bool cc2500SpiInit (void)
Function Documentation
cc2500getGdo()
bool cc2500getGdo (void)
Definition at line 80 of file cc2500_common.c.
References gdoPin, and IORead.
Referenced by frSkyXHandlePacket(), getBind1(), getBind2(), and tuneRx().
cc2500getRssiDbm()
uint16_t cc2500getRssiDbm (void)
Definition at line 64 of file cc2500_common.c.
References rssiDbm.
Referenced by buildTelemetryFrame().
cc2500setRssiDbm()
void cc2500setRssiDbm (uint8_t value)
Definition at line 69 of file cc2500_common.c.
References RSSI_SOURCE_RX_PROTOCOL, rssiDbm, and setRssi().
Referenced by frSkyXHandlePacket().
cc2500SpiInit()
bool cc2500SpiInit (void)
Definition at line 127 of file cc2500_common.c.
References cc2500SpiDetect(), foo, gdoPin, IO_NONE, IOCFG_IN_FLOATING, IOCFG_OUT_PP, IOConfigGPIO, IOGetByTag, IOHi, IOInit, OWNER_RX_SPI_EXTI, RSSI_SOURCE_NONE, RSSI_SOURCE_RX_PROTOCOL, rssiSource, rxCc2500SpiConfig(), and rxSpiConfig().
Referenced by frSkySpiInit().