Paparazzi UAS: sw/airborne/modules/radio_control/cc2500_frsky/cc2500_paparazzi.h File Reference
cc2500_paparazzi.h File Reference
#include "generated/airframe.h"
#include "generated/radio.h"
Macros
#define RC_PPM_TICKS_OF_USEC(_x) (_x)
#define RC_PPM_SIGNED_TICKS_OF_USEC(_x) (_x)
#define USEC_OF_RC_PPM_TICKS(_x) (_x)
#define RADIO_CONTROL_NB_CHANNEL RADIO_CTL_NB
Functions
void radio_control_cc2500_init (void)
void radio_control_cc2500_event (void)
Macro Definition Documentation
RADIO_CONTROL_NB_CHANNEL
#define RADIO_CONTROL_NB_CHANNEL RADIO_CTL_NB
Definition at line 33 of file cc2500_paparazzi.h.
RC_PPM_SIGNED_TICKS_OF_USEC
#define RC_PPM_SIGNED_TICKS_OF_USEC (_x) (_x)
Definition at line 26 of file cc2500_paparazzi.h.
RC_PPM_TICKS_OF_USEC
#define RC_PPM_TICKS_OF_USEC (_x) (_x)
Definition at line 25 of file cc2500_paparazzi.h.
USEC_OF_RC_PPM_TICKS
#define USEC_OF_RC_PPM_TICKS (_x) (_x)
Definition at line 27 of file cc2500_paparazzi.h.
Function Documentation
radio_control_cc2500_event()
void radio_control_cc2500_event (void) extern
Definition at line 63 of file cc2500_paparazzi.c.
References foo, RadioControl::frame_cpt, frsky_raw, radio_control, RADIO_CONTROL_FRSKY_ID, RadioControl::radio_ok_cpt, RC_OK, rxRuntimeConfig_s::rcFrameStatusFn, rxRuntimeConfig_s::rcProcessFrameFn, rxRuntimeConfig_s::rcReadRawFn, RX_FRAME_COMPLETE, rxRuntimeConfig, RadioControl::status, and RadioControl::time_since_last_frame.
radio_control_cc2500_init()
void radio_control_cc2500_init (void) extern
Definition at line 51 of file cc2500_paparazzi.c.
References cc2500_init(), cc2500_settings_init(), cc2500Reset(), DefaultPeriodic, foo, RadioControl::nb_channel, radio_control, register_periodic_telemetry(), rxInit(), and send_cc2500_ppm().