Paparazzi UAS: sw/airborne/modules/radio_control/cc2500_frsky/cc2500_frsky_x.c File Reference
cc2500_frsky_x.c File Reference
#include "cc2500_compat.h"
#include "peripherals/cc2500.h"
#include "cc2500_settings.h"
#include "cc2500_rx_spi_common.h"
#include "cc2500_common.h"
#include "cc2500_frsky_common.h"
#include "cc2500_frsky_shared.h"
#include "cc2500_frsky_x.h"
#include "cc2500_smartport.h"
#include <string.h>
Data Structures
struct telemetrySequenceMarkerData_s
union telemetrySequenceMarker_s
struct telemetryData_s
struct telemetryBuffer_s
struct telemetryPayload_s
Macros
#define UNUSED(x) (void)(x)
#define TELEMETRY_OUT_BUFFER_SIZE 64
#define TELEMETRY_SEQUENCE_LENGTH 4
#define A1_CONST_X 50
#define SEQUENCE_MARKER_REMOTE_PART 0xf0
#define TELEMETRY_DATA_SIZE 5
#define TELEMETRY_FRAME_SIZE sizeof(telemetryData_t)
Typedefs
typedef struct telemetrySequenceMarkerData_s telemetrySequenceMarkerData_t
typedef union telemetrySequenceMarker_s telemetrySequenceMarker_t
typedef struct telemetryData_s telemetryData_t
typedef struct telemetryBuffer_s telemetryBuffer_t
typedef struct telemetryPayload_s telemetryPayload_t
Functions
static uint16_t calculateCrc (const uint8_t *data, uint8_t len)
static uint8_t appendSmartPortData (uint8_t *buf)
static void buildTelemetryFrame (uint8_t *packet)
static bool frSkyXCheckQueueEmpty (void)
static void frSkyXTelemetrySendByte (uint8_t c)
static void frSkyXTelemetryWriteFrame (const smartPortPayload_t *payload)
void frSkyXSetRcData (uint16_t *rcData, const uint8_t *packet)
bool isValidPacket (const uint8_t *packet)
rx_spi_received_e frSkyXHandlePacket (uint8_t *const packet, uint8_t *const protocolState)
rx_spi_received_e frSkyXProcessFrame (uint8_t *const packet)
void frSkyXInit (const rx_spi_protocol_e spiProtocol)
Variables
const uint16_t crcTable []
static telemetryData_t telemetryTxBuffer [TELEMETRY_SEQUENCE_LENGTH]
static telemetryBuffer_t telemetryRxBuffer [TELEMETRY_SEQUENCE_LENGTH]
static telemetrySequenceMarker_t responseToSend
static uint8_t frame [20]
static uint8_t telemetryOutWriter
static uint8_t telemetryOutBuffer [TELEMETRY_OUT_BUFFER_SIZE]
static bool telemetryEnabled = false
static uint8_t remoteToProcessId = 0
static uint8_t remoteToProcessIndex = 0
static uint8_t packetLength
static uint16_t telemetryDelayUs
Data Structure Documentation
telemetrySequenceMarkerData_s
struct telemetrySequenceMarkerData_s
Definition at line 116 of file cc2500_frsky_x.c.
Data Fields
unsigned int ackSequenceId: 2
unsigned int initRequest: 1
unsigned int initResponse: 1
unsigned int packetSequenceId: 2
unsigned int retransmissionRequested: 1
unsigned int unused: 1
telemetrySequenceMarker_s
union telemetrySequenceMarker_s
Definition at line 125 of file cc2500_frsky_x.c.
Data Fields
telemetrySequenceMarkerData_t data
uint8_t raw
telemetryData_s
struct telemetryData_s
Definition at line 134 of file cc2500_frsky_x.c.
Data Fields
uint8_t data[TELEMETRY_DATA_SIZE]
uint8_t dataLength
telemetryBuffer_s
struct telemetryBuffer_s
Definition at line 139 of file cc2500_frsky_x.c.
Data Fields
telemetryData_t data
uint8_t needsProcessing
telemetryPayload_s
struct telemetryPayload_s
Definition at line 146 of file cc2500_frsky_x.c.
Data Fields
uint8_t crc[2]
telemetryData_t data
uint8_t packetConst
uint8_t rssiA1
telemetrySequenceMarker_t sequence
Macro Definition Documentation
A1_CONST_X
#define A1_CONST_X 50
Definition at line 114 of file cc2500_frsky_x.c.
SEQUENCE_MARKER_REMOTE_PART
#define SEQUENCE_MARKER_REMOTE_PART 0xf0
Definition at line 130 of file cc2500_frsky_x.c.
TELEMETRY_DATA_SIZE
#define TELEMETRY_DATA_SIZE 5
Definition at line 132 of file cc2500_frsky_x.c.
TELEMETRY_FRAME_SIZE
#define TELEMETRY_FRAME_SIZE sizeof(telemetryData_t)
Definition at line 144 of file cc2500_frsky_x.c.
TELEMETRY_OUT_BUFFER_SIZE
#define TELEMETRY_OUT_BUFFER_SIZE 64
Definition at line 110 of file cc2500_frsky_x.c.
TELEMETRY_SEQUENCE_LENGTH
#define TELEMETRY_SEQUENCE_LENGTH 4
Definition at line 112 of file cc2500_frsky_x.c.
UNUSED
#define UNUSED (x) (void)(x)
Definition at line 12 of file cc2500_frsky_x.c.
Typedef Documentation
telemetryBuffer_t
typedef struct telemetryBuffer_s telemetryBuffer_t
telemetryData_t
typedef struct telemetryData_s telemetryData_t
telemetryPayload_t
typedef struct telemetryPayload_s telemetryPayload_t
telemetrySequenceMarker_t
typedef union telemetrySequenceMarker_s telemetrySequenceMarker_t
telemetrySequenceMarkerData_t
typedef struct telemetrySequenceMarkerData_s telemetrySequenceMarkerData_t
Function Documentation
appendSmartPortData()
static uint8_t appendSmartPortData (uint8_t * buf) static
Definition at line 190 of file cc2500_frsky_x.c.
References foo, TELEMETRY_DATA_SIZE, TELEMETRY_OUT_BUFFER_SIZE, telemetryOutBuffer, and telemetryOutWriter.
Referenced by buildTelemetryFrame().
buildTelemetryFrame()
static void buildTelemetryFrame (uint8_t * packet) static
Definition at line 207 of file cc2500_frsky_x.c.
References A1_CONST_X, rxCc2500SpiConfig_s::a1Source, ADC_EXTERNAL1, adcGetChannel, appendSmartPortData(), rxCc2500SpiConfig_s::bindTxId, calculateCrc(), cc2500getRssiDbm(), telemetrySequenceMarker_s::data, foo, frame, FRSKY_SPI_A1_SOURCE_CONST, FRSKY_SPI_A1_SOURCE_EXTADC, FRSKY_SPI_A1_SOURCE_VBAT, getLegacyBatteryVoltage, telemetrySequenceMarkerData_s::initRequest, telemetrySequenceMarker_s::raw, responseToSend, rxCc2500SpiConfig(), SEQUENCE_MARKER_REMOTE_PART, TELEMETRY_FRAME_SIZE, TELEMETRY_SEQUENCE_LENGTH, and telemetryTxBuffer.
Referenced by frSkyXHandlePacket().
calculateCrc()
static uint16_t calculateCrc (const uint8_t * data, uint8_t len) static
Definition at line 180 of file cc2500_frsky_x.c.
References crcTable.
Referenced by buildTelemetryFrame(), and isValidPacket().
frSkyXCheckQueueEmpty()
static bool frSkyXCheckQueueEmpty (void) static
Definition at line 271 of file cc2500_frsky_x.c.
Referenced by frSkyXProcessFrame().
frSkyXHandlePacket()
rx_spi_received_e frSkyXHandlePacket (uint8_t *const packet, uint8_t *const protocolState)
Definition at line 340 of file cc2500_frsky_x.c.
References telemetrySequenceMarkerData_s::ackSequenceId, buildTelemetryFrame(), CC2500_3B_RXBYTES, CC2500_READ_BURST, CC2500_SFRX, CC2500_SIDLE, CC2500_SRX, cc2500getGdo(), cc2500ReadFifo(), cc2500ReadReg(), cc2500SetPower(), cc2500setRssiDbm(), cc2500Strobe(), cc2500WriteFifo(), cmpTimeUs(), telemetrySequenceMarker_s::data, DEBUG_DATA_BAD_FRAME, DEBUG_DATA_MISSING_PACKETS, DEBUG_SET, delayMicroseconds, FALLTHROUGH, foo, frame, initialiseData(), isValidPacket(), listLength, MAX_MISSING_PKT, micros, missingPackets, telemetryBuffer_s::needsProcessing, nextChannel(), packetLength, telemetrySequenceMarkerData_s::packetSequenceId, protocolState, telemetrySequenceMarker_s::raw, remoteToProcessId, remoteToProcessIndex, responseToSend, telemetrySequenceMarkerData_s::retransmissionRequested, RSSI_SOURCE_RX_PROTOCOL, RX_SPI_RECEIVED_DATA, RX_SPI_RECEIVED_NONE, RX_SPI_ROCESSING_REQUIRED, rxSpiCheckBindRequested(), rxSpiLedOn(), rxSpiLedToggle(), setRssiDirect(), STATE_DATA, STATE_INIT, STATE_RESUME, STATE_STARTING, STATE_TELEMETRY, STATE_UPDATE, SYNC_DELAY_MAX, TELEMETRY_FRAME_SIZE, TELEMETRY_SEQUENCE_LENGTH, telemetryDelayUs, telemetryEnabled, telemetryRxBuffer, and timeoutUs.
Referenced by frSkySpiInit().
frSkyXInit()
void frSkyXInit (const rx_spi_protocol_e spiProtocol)
Definition at line 582 of file cc2500_frsky_x.c.
References FEATURE_TELEMETRY, featureIsEnabled, frSkyXTelemetryWriteFrame(), initSmartPortTelemetryExternal(), packetLength, RX_SPI_FRSKY_X, RX_SPI_FRSKY_X_LBT, spiProtocol, telemetryDelayUs, and telemetryEnabled.
Referenced by frSkySpiInit().
frSkyXProcessFrame()
rx_spi_received_e frSkyXProcessFrame (uint8_t *const packet)
Definition at line 544 of file cc2500_frsky_x.c.
References telemetryBuffer_s::data, foo, frSkyXCheckQueueEmpty(), millis, telemetryBuffer_s::needsProcessing, processSmartPortTelemetry(), remoteToProcessId, remoteToProcessIndex, RX_SPI_RECEIVED_NONE, smartPortDataReceive(), TELEMETRY_SEQUENCE_LENGTH, telemetryRxBuffer, and UNUSED.
Referenced by frSkySpiInit().
frSkyXSetRcData()
void frSkyXSetRcData (uint16_t * rcData, const uint8_t * packet)
Definition at line 304 of file cc2500_frsky_x.c.
References foo, and rcData.
Referenced by frSkySpiInit().
frSkyXTelemetrySendByte()
static void frSkyXTelemetrySendByte (uint8_t c) static
Definition at line 277 of file cc2500_frsky_x.c.
References FSSP_DLE, FSSP_DLE_XOR, FSSP_START_STOP, TELEMETRY_OUT_BUFFER_SIZE, telemetryOutBuffer, and telemetryOutWriter.
Referenced by frSkyXTelemetryWriteFrame().
frSkyXTelemetryWriteFrame()
static void frSkyXTelemetryWriteFrame (const smartPortPayload_t * payload) static
Definition at line 289 of file cc2500_frsky_x.c.
References frSkyXTelemetrySendByte(), FSSP_SENSOR_ID1, FSSP_START_STOP, TELEMETRY_OUT_BUFFER_SIZE, telemetryOutBuffer, and telemetryOutWriter.
Referenced by frSkyXInit().
isValidPacket()
bool isValidPacket (const uint8_t * packet)
Definition at line 327 of file cc2500_frsky_x.c.
References calculateCrc(), foo, packetLength, and rxCc2500SpiConfig().
Referenced by frSkyXHandlePacket().
Variable Documentation
crcTable
const uint16_t crcTable[]
Definition at line 75 of file cc2500_frsky_x.c.
Referenced by calculateCrc().
frame
uint8_t frame[20] static
Definition at line 163 of file cc2500_frsky_x.c.
Referenced by actuators_sbus_send(), buildTelemetryFrame(), can_transmit_frame(), DictionaryTrainingYUV(), DistributionExtraction(), DshotErpsSetFromFrame(), eperiodDecode(), frSkyXHandlePacket(), get_object(), and texton_func().
packetLength
uint8_t packetLength static
Definition at line 177 of file cc2500_frsky_x.c.
Referenced by frSkyXHandlePacket(), frSkyXInit(), and isValidPacket().
remoteToProcessId
uint8_t remoteToProcessId = 0 static
Definition at line 172 of file cc2500_frsky_x.c.
Referenced by frSkyXHandlePacket(), and frSkyXProcessFrame().
remoteToProcessIndex
uint8_t remoteToProcessIndex = 0 static
Definition at line 173 of file cc2500_frsky_x.c.
Referenced by frSkyXHandlePacket(), and frSkyXProcessFrame().
responseToSend
telemetrySequenceMarker_t responseToSend static
Definition at line 160 of file cc2500_frsky_x.c.
Referenced by buildTelemetryFrame(), and frSkyXHandlePacket().
telemetryDelayUs
uint16_t telemetryDelayUs static
Definition at line 178 of file cc2500_frsky_x.c.
Referenced by frSkyXHandlePacket(), and frSkyXInit().
telemetryEnabled
bool telemetryEnabled = false static
Definition at line 170 of file cc2500_frsky_x.c.
Referenced by frSkyXHandlePacket(), and frSkyXInit().
telemetryOutBuffer
uint8_t telemetryOutBuffer[TELEMETRY_OUT_BUFFER_SIZE] static
Definition at line 168 of file cc2500_frsky_x.c.
Referenced by appendSmartPortData(), frSkyXTelemetrySendByte(), and frSkyXTelemetryWriteFrame().
telemetryOutWriter
uint8_t telemetryOutWriter static
Definition at line 166 of file cc2500_frsky_x.c.
Referenced by appendSmartPortData(), frSkyXTelemetrySendByte(), and frSkyXTelemetryWriteFrame().
telemetryRxBuffer
telemetryBuffer_t telemetryRxBuffer[TELEMETRY_SEQUENCE_LENGTH] static
Definition at line 158 of file cc2500_frsky_x.c.
Referenced by frSkyXHandlePacket(), and frSkyXProcessFrame().
telemetryTxBuffer
telemetryData_t telemetryTxBuffer[TELEMETRY_SEQUENCE_LENGTH] static
Definition at line 155 of file cc2500_frsky_x.c.
Referenced by buildTelemetryFrame().