Paparazzi UAS: sw/airborne/modules/radio_control/cc2500_frsky/cc2500_settings.h File Reference
cc2500_settings.h File Reference
#include "cc2500_compat.h"
#include <stdint.h>
Data Structures
struct cc2500_settings_persistent_s
struct rxConfig_s
struct rxSpiConfig_s
struct rxCc2500SpiConfig_s
struct telemetryConfig_s
Macros
#define writeEEPROM() bf_writeEEPROM()
#define FRAME_ERR_RESAMPLE_US 100000
#define GET_FRAME_ERR_LPF_FREQUENCY(period) (1 / (period / 10.0f))
#define SENSOR_NONE 0
Typedefs
typedef struct rxConfig_s rxConfig_t
typedef struct rxSpiConfig_s rxSpiConfig_t
typedef struct rxCc2500SpiConfig_s rxCc2500SpiConfig_t
typedef struct telemetryConfig_s telemetryConfig_t
Enumerations
enum frSkySpiA1Source_e { FRSKY_SPI_A1_SOURCE_VBAT = 0 , FRSKY_SPI_A1_SOURCE_EXTADC , FRSKY_SPI_A1_SOURCE_CONST }
enum sensor_e {
SENSOR_VOLTAGE = 1 << 0 , SENSOR_CURRENT = 1 << 1 , SENSOR_FUEL = 1 << 2 , SENSOR_MODE = 1 << 3 ,
SENSOR_ACC_X = 1 << 4 , SENSOR_ACC_Y = 1 << 5 , SENSOR_ACC_Z = 1 << 6 , SENSOR_PITCH = 1 << 7 ,
SENSOR_ROLL = 1 << 8 , SENSOR_HEADING = 1 << 9 , SENSOR_ALTITUDE = 1 << 10 , SENSOR_VARIO = 1 << 11 ,
SENSOR_LAT_LONG = 1 << 12 , SENSOR_GROUND_SPEED = 1 << 13 , SENSOR_DISTANCE = 1 << 14 , ESC_SENSOR_CURRENT = 1 << 15 ,
ESC_SENSOR_VOLTAGE = 1 << 16 , ESC_SENSOR_RPM = 1 << 17 , ESC_SENSOR_TEMPERATURE = 1 << 18 , ESC_SENSOR_ALL ,
SENSOR_TEMPERATURE = 1 << 19 , SENSOR_ALL = (1 << 20) - 1
}
Functions
void cc2500_settings_init (void)
void bf_writeEEPROM (void)
const rxConfig_t * rxConfig (void)
const rxSpiConfig_t * rxSpiConfig (void)
const rxCc2500SpiConfig_t * rxCc2500SpiConfig (void)
rxCc2500SpiConfig_t * rxCc2500SpiConfigMutable (void)
const telemetryConfig_t * telemetryConfig (void)
bool telemetryIsSensorEnabled (sensor_e sensor)
Variables
struct cc2500_settings_persistent_s cc2500_settings_persistent
Data Structure Documentation
cc2500_settings_persistent_s
struct cc2500_settings_persistent_s
Definition at line 35 of file cc2500_settings.h.
Data Fields
uint32_t bindHopData[13]
uint32_t bindVars
rxConfig_s
struct rxConfig_s
Definition at line 53 of file cc2500_settings.h.
Data Fields
uint8_t max_aux_channel
uint16_t midrc
uint8_t rssi_channel
uint8_t rssi_src_frame_lpf_period
uint8_t serialrx_provider
rxSpiConfig_s
struct rxSpiConfig_s
Definition at line 96 of file cc2500_settings.h.
Data Fields
ioTag_t bindIoTag
ioTag_t extiIoTag
uint8_t ledInversion
ioTag_t ledIoTag
uint8_t rx_spi_protocol
rxCc2500SpiConfig_s
struct rxCc2500SpiConfig_s
Definition at line 124 of file cc2500_settings.h.
Data Fields
uint8_t a1Source
uint8_t autoBind
uint8_t bindHopData[50]
int8_t bindOffset
uint8_t bindTxId[2]
uint8_t chipDetectEnabled
uint8_t rxNum
telemetryConfig_s
struct telemetryConfig_s
Definition at line 142 of file cc2500_settings.h.
Data Fields
uint8_t pidValuesAsTelemetry
uint8_t report_cell_voltage
Macro Definition Documentation
FRAME_ERR_RESAMPLE_US
#define FRAME_ERR_RESAMPLE_US 100000
Definition at line 49 of file cc2500_settings.h.
GET_FRAME_ERR_LPF_FREQUENCY
#define GET_FRAME_ERR_LPF_FREQUENCY (period) (1 / (period / 10.0f))
Definition at line 51 of file cc2500_settings.h.
SENSOR_NONE
#define SENSOR_NONE 0
Definition at line 187 of file cc2500_settings.h.
writeEEPROM
#define writeEEPROM () bf_writeEEPROM()
Definition at line 45 of file cc2500_settings.h.
Typedef Documentation
rxCc2500SpiConfig_t
typedef struct rxCc2500SpiConfig_s rxCc2500SpiConfig_t
rxConfig_t
typedef struct rxConfig_s rxConfig_t
rxSpiConfig_t
typedef struct rxSpiConfig_s rxSpiConfig_t
telemetryConfig_t
typedef struct telemetryConfig_s telemetryConfig_t
Enumeration Type Documentation
frSkySpiA1Source_e
enum frSkySpiA1Source_e
Enumerator
FRSKY_SPI_A1_SOURCE_VBAT
FRSKY_SPI_A1_SOURCE_EXTADC
FRSKY_SPI_A1_SOURCE_CONST
Definition at line 118 of file cc2500_settings.h.
sensor_e
enum sensor_e
Enumerator
SENSOR_VOLTAGE
SENSOR_CURRENT
SENSOR_FUEL
SENSOR_MODE
SENSOR_ACC_X
SENSOR_ACC_Y
SENSOR_ACC_Z
SENSOR_PITCH
SENSOR_ROLL
SENSOR_HEADING
SENSOR_ALTITUDE
SENSOR_VARIO
SENSOR_LAT_LONG
SENSOR_GROUND_SPEED
SENSOR_DISTANCE
ESC_SENSOR_CURRENT
ESC_SENSOR_VOLTAGE
ESC_SENSOR_RPM
ESC_SENSOR_TEMPERATURE
ESC_SENSOR_ALL
SENSOR_TEMPERATURE
SENSOR_ALL
Definition at line 160 of file cc2500_settings.h.
Function Documentation
bf_writeEEPROM()
void bf_writeEEPROM (void)
Definition at line 68 of file cc2500_settings.c.
References cc2500_persistent_write(), and settings_StoreSettings.
cc2500_settings_init()
void cc2500_settings_init (void)
Definition at line 159 of file cc2500_settings.c.
References rxCc2500SpiConfig_s::a1Source, rxCc2500SpiConfig_s::autoBind, rxCc2500SpiConfig_s::bindHopData, bindIo, rxSpiConfig_s::bindIoTag, rxCc2500SpiConfig_s::bindOffset, rxCc2500SpiConfig_s::bindTxId, BUTTON_GPIO, BUTTON_PIN, CC2500_AUTOBIND, cc2500_persistent_read(), CC2500_RX_SPI_PROTOCOL, cc2500spiconfig, rxCc2500SpiConfig_s::chipDetectEnabled, extiIo, rxSpiConfig_s::extiIoTag, FALSE, foo, FRSKY_SPI_A1_SOURCE_VBAT, gpio_t::hi, LED_GPIO, LED_GPIO_OFF, LED_GPIO_ON, LED_GPIO_PIN, rxSpiConfig_s::ledInversion, ledIo, rxSpiConfig_s::ledIoTag, gpio_t::lo, rxConfig_s::max_aux_channel, rxConfig_s::midrc, telemetryConfig_s::pidValuesAsTelemetry, gpio_t::pin, gpio_t::port, telemetryConfig_s::report_cell_voltage, rxConfig_s::rssi_channel, rxConfig_s::rssi_src_frame_lpf_period, rxSpiConfig_s::rx_spi_protocol, rxconfig, rxCc2500SpiConfig_s::rxNum, settings_init(), spiconfig, telemetryconfig, and TRUE.
Referenced by radio_control_cc2500_init().
rxCc2500SpiConfig()
const rxCc2500SpiConfig_t * rxCc2500SpiConfig (void)
Definition at line 94 of file cc2500_settings.c.
References cc2500spiconfig.
Referenced by buildTelemetryFrame(), cc2500SpiInit(), frSkySpiDataReceived(), getBind2(), initialiseData(), isValidPacket(), and nextChannel().
rxCc2500SpiConfigMutable()
rxCc2500SpiConfig_t * rxCc2500SpiConfigMutable (void)
Definition at line 97 of file cc2500_settings.c.
References cc2500spiconfig.
Referenced by getBind1(), getBind2(), and tuneRx().
rxConfig()
const rxConfig_t * rxConfig (void)
Definition at line 77 of file cc2500_settings.c.
References rxconfig.
Referenced by rxInit().
rxSpiConfig()
const rxSpiConfig_t * rxSpiConfig (void)
Definition at line 87 of file cc2500_settings.c.
References spiconfig.
Referenced by cc2500SpiInit(), frSkySpiInit(), rxInit(), rxSpiCommonIOInit(), and rxSpiInit().
telemetryConfig()
const telemetryConfig_t * telemetryConfig (void)
Definition at line 105 of file cc2500_settings.c.
References telemetryconfig.
Referenced by processSmartPortTelemetry().
telemetryIsSensorEnabled()
bool telemetryIsSensorEnabled (sensor_e sensor)
Definition at line 111 of file cc2500_settings.c.
References CC2500_TELEMETRY_SENSORS, and foo.
Referenced by initSmartPortSensors().
Variable Documentation
cc2500_settings_persistent
struct cc2500_settings_persistent_s cc2500_settings_persistent extern
Definition at line 117 of file cc2500_settings.c.
Referenced by cc2500_persistent_read(), and cc2500_persistent_write().