Paparazzi UAS: sw/airborne/subsystems/radio_control/cc2500_frsky/cc2500_rx_spi_common.h File Reference
cc2500_rx_spi_common.h File Reference
#include "cc2500_compat.h"
#include "cc2500_rx_spi.h"
Macros
#define INTERVAL_RX_LOSS_MS 1000
#define INTERVAL_RX_BIND_MS 250
#define RX_LOSS_COUNT 1000
Functions
void rxSpiCommonIOInit (const rxSpiConfig_t *rxSpiConfig)
void rxSpiLedOn (void)
void rxSpiLedOff (void)
void rxSpiLedToggle (void)
void rxSpiLedBlink (timeMs_t blinkMs)
void rxSpiLedBlinkRxLoss (rx_spi_received_e result)
void rxSpiLedBlinkBind (void)
void rxSpiBind (void)
bool rxSpiCheckBindRequested (bool reset)
Macro Definition Documentation
#define INTERVAL_RX_BIND_MS 250
Definition at line 31 of file cc2500_rx_spi_common.h.
Referenced by rxSpiLedBlinkBind().
#define INTERVAL_RX_LOSS_MS 1000
Definition at line 30 of file cc2500_rx_spi_common.h.
Referenced by rxSpiLedBlinkRxLoss().
#define RX_LOSS_COUNT 1000
Definition at line 32 of file cc2500_rx_spi_common.h.
Referenced by rxSpiLedBlinkRxLoss().
Function Documentation
void rxSpiBind (void)
Definition at line 123 of file cc2500_rx_spi_common.c.
References bindRequested.
bool rxSpiCheckBindRequested (bool reset)
Definition at line 128 of file cc2500_rx_spi_common.c.
References bindRequested, IORead, and lastBindPinStatus.
Referenced by frSkySpiDataReceived(), and frSkyXHandlePacket().
void rxSpiCommonIOInit (const rxSpiConfig_t * rxSpiConfig)
Definition at line 45 of file cc2500_rx_spi_common.c.
References rxSpiConfig_s::bindIoTag, IO_NONE, IOCFG_IPU, IOCFG_OUT_PP, IOConfigGPIO, IOGetByTag, IOInit, IORead, lastBindPinStatus, ledInversion, rxSpiConfig_s::ledInversion, rxSpiConfig_s::ledIoTag, OWNER_LED, OWNER_RX_SPI_BIND, and rxSpiLedOff().
Referenced by frSkySpiInit().
void rxSpiLedBlink (timeMs_t blinkMs)
Definition at line 88 of file cc2500_rx_spi_common.c.
References millis, and rxSpiLedToggle().
Referenced by rxSpiLedBlinkBind(), and rxSpiLedBlinkRxLoss().
void rxSpiLedBlinkBind (void)
Definition at line 118 of file cc2500_rx_spi_common.c.
References INTERVAL_RX_BIND_MS, and rxSpiLedBlink().
void rxSpiLedBlinkRxLoss (rx_spi_received_e result)
Definition at line 100 of file cc2500_rx_spi_common.c.
References INTERVAL_RX_LOSS_MS, RX_LOSS_COUNT, RX_SPI_RECEIVED_DATA, rxSpiLedBlink(), and rxSpiLedOn().
void rxSpiLedOff (void)
Definition at line 74 of file cc2500_rx_spi_common.c.
References IOHi, IOLo, and ledInversion.
Referenced by rxSpiCommonIOInit().
void rxSpiLedOn (void)
Definition at line 67 of file cc2500_rx_spi_common.c.
References IOHi, IOLo, and ledInversion.
Referenced by frSkySpiDataReceived(), frSkyXHandlePacket(), and rxSpiLedBlinkRxLoss().
void rxSpiLedToggle (void)
Definition at line 81 of file cc2500_rx_spi_common.c.
References IOToggle.
Referenced by frSkySpiDataReceived(), frSkyXHandlePacket(), and rxSpiLedBlink().