Paparazzi UAS: sw/airborne/modules/range_finder/cf_deck_multi_ranger.h File Reference
cf_deck_multi_ranger.h File Reference
#include "std.h"
Functions
void multi_ranger_init (void)
Module init.
void multi_ranger_periodic (void)
Module periodic function.
void multi_ranger_report (void)
void multi_ranger_event (void)
Detailed Description
Author
Gautier Hattenberger gauti.nosp@m.er.h.nosp@m.atten.nosp@m.berg.nosp@m.er@en.nosp@m.ac.f.nosp@m.r Multi-ranger deck from Bitcraze for Crazyflie drones
Definition in file cf_deck_multi_ranger.h.
Function Documentation
multi_ranger_event()
void multi_ranger_event (void) extern
Definition at line 251 of file cf_deck_multi_ranger.c.
References multi_ranger, MULTI_RANGER_BACK, MULTI_RANGER_FRONT, MULTI_RANGER_LEFT, multi_ranger_read(), MULTI_RANGER_RIGHT, MULTI_RANGER_UP, and cf_deck_multi_ranger::ranger.
multi_ranger_init()
void multi_ranger_init (void) extern
Module init.
Definition at line 138 of file cf_deck_multi_ranger.c.
References SingleRanger::azimuth, SingleRanger::bearing, SingleRanger::dev, SingleRanger::distance, foo, VL53L1_Dev_t::i2c_p, VL53L1_Dev_t::i2c_trans, multi_ranger, multi_ranger_array_orientation, MULTI_RANGER_NB, MULTI_RANGER_PIN_ALL, MULTI_RANGER_UNINIT, cf_deck_multi_ranger::pca, pca95xx_configure(), PCA95XX_DEFAULT_ADDRESS, pca95xx_init(), pca95xx_set_output(), cf_deck_multi_ranger::ranger, VL53L1_Dev_t::read_status, i2c_transaction::slave_addr, cf_deck_multi_ranger::status, VL53L1_DEFAULT_ADDRESS, and VL53L1_READ_IDLE.
multi_ranger_periodic()
void multi_ranger_periodic (void) extern
Module periodic function.
Definition at line 181 of file cf_deck_multi_ranger.c.
References SingleRanger::dev, multi_ranger, MULTI_RANGER_BACK, multi_ranger_boot_device(), MULTI_RANGER_CONF_BACK, MULTI_RANGER_CONF_FRONT, MULTI_RANGER_CONF_IO, MULTI_RANGER_CONF_LEFT, MULTI_RANGER_CONF_RIGHT, MULTI_RANGER_CONF_UP, MULTI_RANGER_FRONT, MULTI_RANGER_LEFT, MULTI_RANGER_PIN_ALL, MULTI_RANGER_PIN_BACK, MULTI_RANGER_PIN_FRONT, MULTI_RANGER_PIN_LEFT, MULTI_RANGER_PIN_RIGHT, MULTI_RANGER_READ_BACK, MULTI_RANGER_READ_FRONT, MULTI_RANGER_READ_LEFT, MULTI_RANGER_READ_RIGHT, MULTI_RANGER_READ_UP, MULTI_RANGER_RIGHT, MULTI_RANGER_UNINIT, MULTI_RANGER_UP, cf_deck_multi_ranger::pca, pca95xx_configure(), pca95xx_set_output(), cf_deck_multi_ranger::ranger, cf_deck_multi_ranger::status, VL53L1X_NonBlocking_IsIdle(), and VL53L1X_NonBlocking_RequestData().
multi_ranger_report()
void multi_ranger_report (void) extern
Definition at line 261 of file cf_deck_multi_ranger.c.
References DefaultChannel, DefaultDevice, SingleRanger::distance, foo, multi_ranger, MULTI_RANGER_NB, and cf_deck_multi_ranger::ranger.