Paparazzi UAS: sw/airborne/modules/digital_cam/catia/chdk_pipe.h File Reference
chdk_pipe.h File Reference
Functions
void chdk_pipe_init (void)
Initialize the CHDK pipe.
void chdk_pipe_shoot (char *filename)
Shoot an image.
void chdk_pipe_deinit (void)
Deinitialize CHDK pipe.
Function Documentation
chdk_pipe_deinit()
void chdk_pipe_deinit (void)
Deinitialize CHDK pipe.
Definition at line 79 of file chdk_pipe.c.
References fi, and foo.
Referenced by main().
chdk_pipe_init()
void chdk_pipe_init (void)
Initialize the CHDK pipe.
Definition at line 50 of file chdk_pipe.c.
References fi, fo, foo, popen2(), setup, SHELL, and wait_for_cmd().
Referenced by main().
chdk_pipe_shoot()
void chdk_pipe_shoot (char * filename)
Shoot an image.
Definition at line 92 of file chdk_pipe.c.
References fi, foo, and wait_for_img().
Referenced by handle_msg_shoot().