Paparazzi UAS: sw/airborne/arch/chibios/mcu_periph/gpio_arch.h File Reference
gpio_arch.h File Reference
gpio functions implemented for ChibiOS arch
#include <hal.h>
#include "mcu_periph/gpio_def.h"
Typedefs
typedef ioportid_t gpio_port_t
Abstract gpio port type for hardware independent part.
Functions
void gpio_setup_output (ioportid_t port, uint16_t gpios)
Setup one or more pins of the given GPIO port as outputs.
void gpio_setup_input (ioportid_t port, uint16_t gpios)
Setup one or more pins of the given GPIO port as inputs.
void gpio_setup_input_pullup (ioportid_t port, uint16_t gpios)
Setup one or more pins of the given GPIO port as inputs with pull up resistor enabled.
void gpio_setup_input_pulldown (ioportid_t port, uint16_t gpios)
Setup one or more pins of the given GPIO port as inputs with pull down resistors enabled.
void gpio_setup_pin_af (ioportid_t port, uint16_t pin, uint8_t af, bool is_output)
Setup a gpio for input or output with alternate function.
void gpio_setup_pin_af_pullup (ioportid_t port, uint16_t pin, uint8_t af)
Setup a gpio for input pullup with alternate function.
void gpio_setup_pin_analog (ioportid_t port, uint16_t pin)
Setup a gpio for analog use.
static uint8_t gpio_get (ioportid_t port, uint16_t pin)
Get level of a gpio.
static void gpio_set (ioportid_t port, uint16_t pin)
Set a gpio output to high level.
static void gpio_clear (ioportid_t port, uint16_t pin)
Clear a gpio output to low level.
static void gpio_toggle (ioportid_t port, uint16_t pin)
Toggle a gpio output to low level.
Detailed Description
gpio functions implemented for ChibiOS arch
Definition in file gpio_arch.h.
Typedef Documentation
gpio_port_t
typedef ioportid_t gpio_port_t
Abstract gpio port type for hardware independent part.
Definition at line 39 of file gpio_arch.h.
Function Documentation
gpio_clear()
static void gpio_clear (ioportid_t port, uint16_t pin) inline static
Clear a gpio output to low level.
Parameters
[in] port
[in] pin
Definition at line 114 of file gpio_arch.h.
References foo.
Referenced by actuators_ardrone_init(), actuators_ardrone_motor_status(), actuators_ardrone_reset_flipflop(), baro_init(), bluegiga_broadcast_msg(), cyrf6936_init(), humid_sht_init(), imu_heater_periodic(), mag_freeze_check(), main(), main_event(), power_switch_init(), power_switch_set(), softi2c_gpio_drive_low(), spi_slave_select(), SpiSlaveSelect(), and w5100_init().
gpio_get()
static uint8_t gpio_get (ioportid_t port, uint16_t pin) inline static
Get level of a gpio.
Parameters
[in] port
[in] pin
Definition at line 94 of file gpio_arch.h.
References foo.
Referenced by actuators_ardrone_motor_status(), baro_eoc(), bf_IORead(), imu_aspirin_eoc(), mag_eoc(), main_event(), mcu_init(), opa_controller_periodic(), softi2c_gpio_read(), softi2c_read_bit(), softi2c_write_bit(), softi2c_write_restart(), softi2c_write_stop(), spektrum_try_bind(), and superbitrf_event().
gpio_set()
static void gpio_set (ioportid_t port, uint16_t pin) inline static
Set a gpio output to high level.
Parameters
[in] port
[in] pin
Definition at line 104 of file gpio_arch.h.
References foo.
Referenced by actuators_ardrone_init(), actuators_ardrone_motor_status(), actuators_ardrone_reset_flipflop(), bluegiga_init(), bluegiga_receive(), can_hw_init(), cyrf6936_init(), imu_aspirin_i2c_init(), imu_heater_periodic(), mag_freeze_check(), main_event(), mf_ptu_init(), ms2100_arch_init(), navdata_init(), power_switch_set(), softi2c_gpio_highz(), spektrum_bind(), spi_slave_unselect(), SpiSlaveUnselect(), and w5100_init().
gpio_setup_input()
void gpio_setup_input (ioportid_t port, uint16_t gpios) extern
Setup one or more pins of the given GPIO port as inputs.
Parameters
[in] port
[in] gpios
Definition at line 40 of file gpio_arch.c.
References foo.
Referenced by actuators_ardrone_init(), bf_IOConfigGPIO(), humid_sht_init(), mcu_init(), opa_controller_init(), softi2c_gpio_highz(), spektrum_bind(), and superbitrf_init().
gpio_setup_input_pulldown()
void gpio_setup_input_pulldown (ioportid_t port, uint16_t gpios) extern
Setup one or more pins of the given GPIO port as inputs with pull down resistors enabled.
Parameters
[in] port
[in] gpios
Definition at line 54 of file gpio_arch.c.
References foo.
Referenced by baro_init(), and spektrum_try_bind().
gpio_setup_input_pullup()
void gpio_setup_input_pullup (ioportid_t port, uint16_t gpios) extern
Setup one or more pins of the given GPIO port as inputs with pull up resistor enabled.
Parameters
[in] port
[in] gpios
Definition at line 47 of file gpio_arch.c.
References foo.
Referenced by bf_IOConfigGPIO(), main(), softi2c_gpio_highz(), and spektrum_try_bind().
gpio_setup_output()
void gpio_setup_output (ioportid_t port, uint16_t gpios) extern
Setup one or more pins of the given GPIO port as outputs.
Parameters
[in] port
[in] gpios
Definition at line 33 of file gpio_arch.c.
References foo.
Referenced by actuators_ardrone_init(), actuators_ardrone_motor_status(), actuators_ardrone_reset_flipflop(), bf_IOConfigGPIO(), bluegiga_init(), cyrf6936_init(), gpio_cam_ctrl_init(), gps_init(), hackhd_init(), humid_sht_init(), imu_aspirin_i2c_init(), init_bat_checker(), init_mf_daq(), main(), mcu_init(), mf_ptu_init(), navdata_init(), opa_controller_init(), opa_controller_init(), power_switch_init(), rotorcraft_cam_init(), sbus_common_init(), softi2c_gpio_drive_low(), spektrum_bind(), spektrum_init(), spi_init_slaves(), and w5100_init().
gpio_setup_pin_af()
void gpio_setup_pin_af (ioportid_t port, uint16_t pin, uint8_t af, bool is_output) extern
Setup a gpio for input or output with alternate function.
This is an STM32 specific helper funtion and should only be used in stm32 code.
Definition at line 65 of file gpio_arch.c.
References foo.
Referenced by actuators_dshot_arch_init(), actuators_dualpwm_arch_init(), actuators_pwm_arch_init(), light_ws2812_arch_init(), ppm_arch_init(), pwm_input_init(), spi1_arch_init(), and spi2_arch_init().
gpio_setup_pin_af_pullup()
void gpio_setup_pin_af_pullup (ioportid_t port, uint16_t pin, uint8_t af)
Setup a gpio for input pullup with alternate function.
This is an STM32 specific helper funtion and should only be used in stm32 code.
Definition at line 61 of file gpio_arch.c.
References foo.
Referenced by actuators_dshot_arch_init().
gpio_setup_pin_analog()
void gpio_setup_pin_analog (ioportid_t port, uint16_t pin) extern
Setup a gpio for analog use.
Parameters
[in] port
[in] pin
Definition at line 90 of file gpio_arch.c.
References foo.
Referenced by adc_init().
gpio_toggle()
static void gpio_toggle (ioportid_t port, uint16_t pin) inline static
Toggle a gpio output to low level.
Parameters
[in] port
[in] pin
Definition at line 124 of file gpio_arch.h.
References foo.
Referenced by bat_checker_periodic(), bf_IOToggle(), and spektrum_bind().