Paparazzi UAS: sw/airborne/arch/chibios/mcu_periph/rng_arch.c File Reference
rng_arch.c File Reference
arch specific Random Number Generator API
#include "mcu_periph/rng.h"
#include <hal.h>
Functions
static void TRNGStart (void)
static void TRNGStop (void)
static uint32_t TRNGGet (void)
static bool TRNGGetErrors (void)
static void TRNGClearErrors (void)
static bool TRNGGenerate (size_t size, uint32_t *out)
void rng_init (void)
void rng_deinit (void)
bool rng_get (uint32_t *rand_nr)
uint32_t rng_wait_and_get (void)
Detailed Description
arch specific Random Number Generator API
Definition in file rng_arch.c.
Function Documentation
rng_deinit()
void rng_deinit (void)
Definition at line 82 of file rng_arch.c.
References TRNGStop().
rng_get()
bool rng_get (uint32_t * rand_nr)
Definition at line 89 of file rng_arch.c.
References foo, TRNGClearErrors(), and TRNGGenerate().
Referenced by rng_wait_and_get().
rng_init()
void rng_init (void)
Definition at line 77 of file rng_arch.c.
References TRNGStart().
Referenced by mcu_init().
rng_wait_and_get()
uint32_t rng_wait_and_get (void)
Definition at line 104 of file rng_arch.c.
References foo, and TRNGGenerate().
Referenced by gec_generate_ephemeral_keys().
TRNGClearErrors()
static void TRNGClearErrors (void) static
Definition at line 59 of file rng_arch.c.
References foo.
Referenced by rng_get().
TRNGGenerate()
static bool TRNGGenerate (size_t size, uint32_t * out) static
Definition at line 64 of file rng_arch.c.
References TRNGGet(), and TRNGGetErrors().
Referenced by rng_get(), and rng_wait_and_get().
TRNGGet()
static uint32_t TRNGGet (void) static
Definition at line 47 of file rng_arch.c.
References foo.
Referenced by TRNGGenerate().
TRNGGetErrors()
static bool TRNGGetErrors (void) static
Definition at line 54 of file rng_arch.c.
References foo.
Referenced by TRNGGenerate().
TRNGStart()
static void TRNGStart (void) static
Definition at line 35 of file rng_arch.c.
References foo.
Referenced by rng_init().
TRNGStop()
static void TRNGStop (void) static
Definition at line 41 of file rng_arch.c.
References foo.
Referenced by rng_deinit().