Paparazzi UAS: sw/airborne/arch/chibios/mcu_arch.h File Reference
mcu_arch.h File Reference
Microcontroller initialization function for ChibiOS.
#include "std.h"
#include <ch.h>
Macros
#define mcu_int_enable() {}
#define mcu_int_disable() {}
Functions
void mcu_arch_init (void)
static void mcu_deep_sleep (void)
Put MCU into deep sleep mode.
static void mcu_reset (void)
Request a software reset of the MCU.
void mcu_periph_energy_save (void)
Call board specific energy saving Can be necessary for closing on power off.
Detailed Description
Microcontroller initialization function for ChibiOS.
Definition in file mcu_arch.h.
Macro Definition Documentation
#define mcu_int_disable () {}
Definition at line 37 of file mcu_arch.h.
Referenced by sys_time_update_timer().
#define mcu_int_enable () {}
Definition at line 36 of file mcu_arch.h.
Referenced by init_ap(), init_fbw(), main(), main_init(), and sys_time_update_timer().
Function Documentation
void mcu_arch_init (void)
Definition at line 109 of file mcu_arch.c.
static void mcu_deep_sleep (void) inline static
Put MCU into deep sleep mode.
This can be used when closing the SD log files right after a power down to save the remaining energy for the SD card internal MCU
Never call this during flight!
Definition at line 55 of file mcu_arch.h.
References __disable_irq(), __enable_irq(), and SCB.
Referenced by thd_bat_survey().
void mcu_periph_energy_save (void)
Call board specific energy saving Can be necessary for closing on power off.
Call board specific energy saving Can be necessary for closing on power off.
Definition at line 154 of file mcu_arch.c.
References LINE_AUX0, LINE_AUX1, LINE_AUX2, LINE_AUX3, LINE_AUX4, LINE_AUX5, LINE_AUX6, LINE_AUX7, LINE_AUX_A1, LINE_AUX_A2, LINE_AUX_A3, LINE_AUX_A4, LINE_AUX_B1, LINE_AUX_B2, LINE_AUX_B3, LINE_AUX_B4, LINE_IMU1_CS, LINE_IMU2_CS, LINE_LED1, LINE_LED2, LINE_LED3, LINE_LED4, LINE_OSD_CS, LINE_SPI1_CS, LINE_SPI2_EXTERNAL_CS, and LINE_SPI4_INTERNAL_CS.
Referenced by sdlog_chibios_finish().
static void mcu_reset (void) inline static
Request a software reset of the MCU.
Definition at line 86 of file mcu_arch.h.
Referenced by thdUsbStorage().