Paparazzi UAS: sw/airborne/arch/chibios/modules/actuators/actuators_dshot_arch.c File Reference
actuators_dshot_arch.c File Reference
#include "modules/actuators/actuators_dshot.h"
#include "modules/actuators/esc_dshot.h"
#include "modules/core/abi.h"
#include "mcu_periph/ram_arch.h"
#include "mcu_periph/gpio.h"
#include <BOARD_CONFIG>
#include "modules/datalink/telemetry.h"
#include "modules/energy/electrical.h"
Data Structures
struct dshot_private
Macros
#define DSHOT_MOTOR_POLES 14
#define _CONCAT_GPIO(num, name) UART ## num ## _GPIO_ ## name
#define CONCAT_GPIO(num, name) _CONCAT_GPIO(num, name)
Functions
static void esc_msg_send (struct transport_tx *trans, struct link_device *dev)
static void dshot_init_struct (struct dshot *ds)
static void dshot_set_struct (struct dshot *ds, struct dshot_private *dsp, DSHOTDriver *driver, uint32_t channel)
void actuators_dshot_arch_init (void)
Arch dependent init.
void actuators_dshot_arch_commit (void)
Variables
struct dshot_private actuators_dshot_private [ACTUATORS_DSHOT_NB]
Data Structure Documentation
dshot_private
struct dshot_private
Definition at line 47 of file actuators_dshot_arch.c.
Data Fields
uint32_t channel
DSHOTDriver * driver
Macro Definition Documentation
_CONCAT_GPIO
#define _CONCAT_GPIO (num, name) UART ## num ## _GPIO_ ## name
Definition at line 150 of file actuators_dshot_arch.c.
CONCAT_GPIO
#define CONCAT_GPIO (num, name) _CONCAT_GPIO(num, name)
Definition at line 151 of file actuators_dshot_arch.c.
DSHOT_MOTOR_POLES
#define DSHOT_MOTOR_POLES 14
Definition at line 44 of file actuators_dshot_arch.c.
Function Documentation
actuators_dshot_arch_commit()
void actuators_dshot_arch_commit (void)
Definition at line 291 of file actuators_dshot_arch.c.
References ACT_FEEDBACK_DSHOT_ID, ACTUATORS_DSHOT_NB, actuators_dshot_private, actuators_dshot_values, dshot::current, DSHOT_BIDIR_ERR_CRC, DSHOT_BIDIR_TLM_EDT, DSHOT_MOTOR_POLES, dshotGetTelemetry(), dshotSendFrame(), dshotSetThrottle(), dshot::energy, foo, act_feedback_t::idx, act_feedback_t::act_feedback_set_t::rpm, act_feedback_t::rpm, dshot::rpm, rpm, act_feedback_t::set, dshot::temp, and dshot::voltage.
actuators_dshot_arch_init()
void actuators_dshot_arch_init (void)
Arch dependent init.
Definition at line 153 of file actuators_dshot_arch.c.
References ACTUATORS_DSHOT_NB, actuators_dshot_private, actuators_dshot_values, CONCAT_GPIO, DefaultPeriodic, dshot_init_struct(), dshot_set_struct(), dshotStart(), esc_msg_send(), FALSE, foo, gpio_setup_pin_af(), gpio_setup_pin_af_pullup(), PRINT_CONFIG_VAR(), and register_periodic_telemetry().
dshot_init_struct()
static void dshot_init_struct (struct dshot * ds) static
Definition at line 134 of file actuators_dshot_arch.c.
References foo.
Referenced by actuators_dshot_arch_init().
dshot_set_struct()
static void dshot_set_struct (struct dshot * ds, struct dshot_private * dsp, DSHOTDriver * driver, uint32_t channel) static
Definition at line 143 of file actuators_dshot_arch.c.
References dshot_private::channel, dshot_private::driver, and foo.
Referenced by actuators_dshot_arch_init().
esc_msg_send()
static void esc_msg_send (struct transport_tx * trans, struct link_device * dev) static
Definition at line 112 of file actuators_dshot_arch.c.
References ACTUATORS_DSHOT_NB, actuators_dshot_values, dshot::current, dev, electrical, foo, rpm, and Electrical::vsupply.
Referenced by actuators_dshot_arch_init().
Variable Documentation
actuators_dshot_private
struct dshot_private actuators_dshot_private[ACTUATORS_DSHOT_NB]
Definition at line 52 of file actuators_dshot_arch.c.
Referenced by actuators_dshot_arch_commit(), and actuators_dshot_arch_init().