Paparazzi UAS: sw/airborne/arch/chibios/mcu_periph/gpio_arch.c File Reference
gpio_arch.c File Reference
gpio functions implemented for ChibiOS arch
#include "mcu_periph/gpio.h"
#include "hal.h"
Functions
void gpio_setup_output (ioportid_t port, uint16_t gpios)
Setup one or more pins of the given GPIO port as outputs.
void gpio_setup_input (ioportid_t port, uint16_t gpios)
Setup one or more pins of the given GPIO port as inputs.
void gpio_setup_input_pullup (ioportid_t port, uint16_t gpios)
Setup one or more pins of the given GPIO port as inputs with pull up resistor enabled.
void gpio_setup_input_pulldown (ioportid_t port, uint16_t gpios)
Setup one or more pins of the given GPIO port as inputs with pull down resistors enabled.
void gpio_setup_pin_af_pullup (ioportid_t port, uint16_t pin, uint8_t af)
Setup a gpio for input pullup with alternate function.
void gpio_setup_pin_af (ioportid_t port, uint16_t pin, uint8_t af, bool is_output)
Setup a gpio for input or output with alternate function.
void gpio_setup_pin_analog (ioportid_t port, uint16_t pin)
Setup a gpio for analog use.
Detailed Description
gpio functions implemented for ChibiOS arch
Definition in file gpio_arch.c.
Function Documentation
gpio_setup_input()
void gpio_setup_input (ioportid_t port, uint16_t gpios)
Setup one or more pins of the given GPIO port as inputs.
Parameters
[in] port
[in] gpios
Definition at line 40 of file gpio_arch.c.
References foo.
Referenced by actuators_ardrone_init(), bf_IOConfigGPIO(), humid_sht_init(), mcu_init(), opa_controller_init(), softi2c_gpio_highz(), spektrum_bind(), and superbitrf_init().
gpio_setup_input_pulldown()
void gpio_setup_input_pulldown (ioportid_t port, uint16_t gpios)
Setup one or more pins of the given GPIO port as inputs with pull down resistors enabled.
Parameters
[in] port
[in] gpios
Definition at line 54 of file gpio_arch.c.
References foo.
Referenced by baro_init(), and spektrum_try_bind().
gpio_setup_input_pullup()
void gpio_setup_input_pullup (ioportid_t port, uint16_t gpios)
Setup one or more pins of the given GPIO port as inputs with pull up resistor enabled.
Parameters
[in] port
[in] gpios
Definition at line 47 of file gpio_arch.c.
References foo.
Referenced by bf_IOConfigGPIO(), main(), softi2c_gpio_highz(), and spektrum_try_bind().
gpio_setup_output()
void gpio_setup_output (ioportid_t port, uint16_t gpios)
Setup one or more pins of the given GPIO port as outputs.
Parameters
[in] port
[in] gpios
Definition at line 33 of file gpio_arch.c.
References foo.
Referenced by actuators_ardrone_init(), actuators_ardrone_motor_status(), actuators_ardrone_reset_flipflop(), bf_IOConfigGPIO(), bluegiga_init(), cyrf6936_init(), gpio_cam_ctrl_init(), gps_init(), hackhd_init(), humid_sht_init(), imu_aspirin_i2c_init(), init_bat_checker(), init_mf_daq(), main(), mcu_init(), mf_ptu_init(), navdata_init(), opa_controller_init(), opa_controller_init(), power_switch_init(), rotorcraft_cam_init(), sbus_common_init(), softi2c_gpio_drive_low(), spektrum_bind(), spektrum_init(), spi_init_slaves(), and w5100_init().
gpio_setup_pin_af()
void gpio_setup_pin_af (ioportid_t port, uint16_t pin, uint8_t af, bool is_output)
Setup a gpio for input or output with alternate function.
This is an STM32 specific helper funtion and should only be used in stm32 code.
Definition at line 65 of file gpio_arch.c.
References foo.
Referenced by actuators_dshot_arch_init(), actuators_dualpwm_arch_init(), actuators_pwm_arch_init(), light_ws2812_arch_init(), ppm_arch_init(), pwm_input_init(), spi1_arch_init(), and spi2_arch_init().
gpio_setup_pin_af_pullup()
void gpio_setup_pin_af_pullup (ioportid_t port, uint16_t pin, uint8_t af)
Setup a gpio for input pullup with alternate function.
This is an STM32 specific helper funtion and should only be used in stm32 code.
Definition at line 61 of file gpio_arch.c.
References foo.
Referenced by actuators_dshot_arch_init().
gpio_setup_pin_analog()
void gpio_setup_pin_analog (ioportid_t port, uint16_t pin)
Setup a gpio for analog use.
Parameters
[in] port
[in] pin
Definition at line 90 of file gpio_arch.c.
References foo.
Referenced by adc_init().