Paparazzi UAS: sw/airborne/arch/chibios/mcu_periph/can_arch.c File Reference
can_arch.c File Reference
#include "mcu_periph/can_arch.h"
#include "mcu_periph/can.h"
#include "mcu_periph/sys_time.h"
#include "stdio.h"
#include "string.h"
#include <ch.h>
#include <hal.h>
Data Structures
struct can_arch_periph
Functions
static void can_thd_rx (void *arg)
static void can_start (struct can_periph *canp)
static bool canConfigureIface (struct can_arch_periph *cas)
Try to compute the timing registers for the can interface and set the configuration.
void can_hw_init ()
int can_transmit_frame (struct pprzcan_frame *txframe, struct pprzaddr_can *addr)
Data Structure Documentation
can_arch_periph
struct can_arch_periph
Definition at line 24 of file can_arch.c.
Data Fields
uint32_t can_baudrate
CANDriver * cand
CANConfig cfg
int if_index
uint16_t memory_offset
void * thread_rx_wa
size_t thread_rx_wa_size
Function Documentation
can_hw_init()
void can_hw_init (void)
Definition at line 71 of file can_arch.c.
References can_start(), and foo.
Referenced by can_init().
can_start()
static void can_start (struct can_periph * canp) static
Definition at line 187 of file can_arch.c.
References can_thd_rx(), canConfigureIface(), and foo.
Referenced by can_hw_init().
can_thd_rx()
static void can_thd_rx (void * arg) static
Definition at line 84 of file can_arch.c.
References can_dlc_to_len(), CAN_FRAME_EFF, CAN_FRAME_ERR, CAN_FRAME_RTR, pprzcan_frame::can_id, pprzaddr_can::can_ifindex, CAN_NB_CALLBACKS_MAX, CANFD_ESI, CANFD_FDF, foo, and status.
Referenced by can_start().
can_transmit_frame()
int can_transmit_frame (struct pprzcan_frame * txframe, struct pprzaddr_can * addr)
Definition at line 152 of file can_arch.c.
References CAN_EID_MASK, CAN_FRAME_EFF, CAN_FRAME_RTR, pprzaddr_can::can_ifindex, can_len_to_dlc(), CAN_SID_MASK, foo, and frame.
Referenced by slcan_handle_frame(), and uavcan_tx().
canConfigureIface()
static bool canConfigureIface (struct can_arch_periph * cas) static
Try to compute the timing registers for the can interface and set the configuration.
Definition at line 212 of file can_arch.c.
References foo.
Referenced by can_start().