Paparazzi UAS: AngleSelector.Ui_Form Class Reference
AngleSelector.Ui_Form Class Reference
Public Member Functions
setupUi (self, Form)
retranslateUi (self, Form)
Data Fields
verticalLayout
gridLayout
label_3
label_4
label_2
dial
label_5
horizontalLayout
label
spinBox
Detailed Description
Definition at line 9 of file AngleSelector.py.
Member Function Documentation
retranslateUi()
AngleSelector.Ui_Form.retranslateUi (self, Form)
Definition at line 57 of file AngleSelector.py.
References foo, AngleSelector.Ui_Form.label, AngleSelector.Ui_Form.label_2, AngleSelector.Ui_Form.label_3, AngleSelector.Ui_Form.label_4, and AngleSelector.Ui_Form.label_5.
setupUi()
AngleSelector.Ui_Form.setupUi (self, Form)
Definition at line 10 of file AngleSelector.py.
References foo.
Referenced by gaia.Gaia.__init__(), betterHSlider.BetterHSlider.__init__(), and betterVSlider.BetterVSlider.__init__().
Field Documentation
dial
AngleSelector.Ui_Form.dial
Definition at line 26 of file AngleSelector.py.
gridLayout
AngleSelector.Ui_Form.gridLayout
Definition at line 15 of file AngleSelector.py.
horizontalLayout
AngleSelector.Ui_Form.horizontalLayout
Definition at line 42 of file AngleSelector.py.
label
AngleSelector.Ui_Form.label
Definition at line 44 of file AngleSelector.py.
Referenced by AngleSelector.Ui_Form.retranslateUi().
label_2
AngleSelector.Ui_Form.label_2
Definition at line 23 of file AngleSelector.py.
Referenced by AngleSelector.Ui_Form.retranslateUi().
label_3
AngleSelector.Ui_Form.label_3
Definition at line 17 of file AngleSelector.py.
Referenced by AngleSelector.Ui_Form.retranslateUi().
label_4
AngleSelector.Ui_Form.label_4
Definition at line 20 of file AngleSelector.py.
Referenced by AngleSelector.Ui_Form.retranslateUi().
label_5
AngleSelector.Ui_Form.label_5
Definition at line 38 of file AngleSelector.py.
Referenced by AngleSelector.Ui_Form.retranslateUi().
spinBox
AngleSelector.Ui_Form.spinBox
Definition at line 47 of file AngleSelector.py.
verticalLayout
AngleSelector.Ui_Form.verticalLayout
Definition at line 13 of file AngleSelector.py.
The documentation for this class was generated from the following file:
sw/simulator/gaia_python/AngleSelector.py