Paparazzi UAS: sw/airborne/modules/meteo/cloud_sim.h File Reference
cloud_sim.h File Reference
#include "std.h"
#include "math/pprz_algebra_float.h"
Data Structures
struct CloudSim
Macros
#define CLOUD_SIM_WP 0
#define CLOUD_SIM_POLYGON 1
Functions
void cloud_sim_init (void)
void cloud_sim_detect (void)
periodic call for border detection
void cloud_sim_move (void)
periodic call for moving waypoints
void cloud_sim_reset (bool reset)
reset handler
Variables
struct CloudSim cloud_sim
Detailed Description
Author
Gautier Hattenberger gauti.nosp@m.er.h.nosp@m.atten.nosp@m.berg.nosp@m.er@en.nosp@m.ac.f.nosp@m.r Basic cloud simulation for testing adaptive navigation patterns
Definition in file cloud_sim.h.
Data Structure Documentation
CloudSim
struct CloudSim
Definition at line 35 of file cloud_sim.h.
Data Fields
uint8_t mode
float radius radius in WP mode
bool reset
struct FloatVect2 speed
Macro Definition Documentation
CLOUD_SIM_POLYGON
#define CLOUD_SIM_POLYGON 1
Definition at line 33 of file cloud_sim.h.
CLOUD_SIM_WP
#define CLOUD_SIM_WP 0
Definition at line 32 of file cloud_sim.h.
Function Documentation
cloud_sim_detect()
void cloud_sim_detect (void) extern
periodic call for border detection
Definition at line 102 of file cloud_sim.c.
References CLOUD_SENSOR_ID, cloud_sim, cloud_sim_circle_id, CLOUD_SIM_POLYGON, CLOUD_SIM_WP, distance_to_wp(), foo, get_sys_time_usec(), CloudSim::mode, CloudSim::radius, stateGetPositionEnu_f(), EnuCoor_f::x, and EnuCoor_f::y.
cloud_sim_init()
void cloud_sim_init (void) extern
Definition at line 92 of file cloud_sim.c.
References cloud_sim, CLOUD_SIM_MODE, CLOUD_SIM_RADIUS, CLOUD_SIM_SPEED_X, CLOUD_SIM_SPEED_Y, CloudSim::mode, CloudSim::radius, CloudSim::reset, CloudSim::speed, FloatVect2::x, and FloatVect2::y.
cloud_sim_move()
void cloud_sim_move (void) extern
periodic call for moving waypoints
Definition at line 130 of file cloud_sim.c.
References cloud_sim, cloud_sim_circle_id, cloud_sim_polygon, CLOUD_SIM_POLYGON, CLOUD_SIM_WP, CLOUD_SIM_WPS_NB, foo, CloudSim::mode, nav_move_waypoint_point(), nav_send_waypoint(), CloudSim::speed, waypoints, FloatVect2::x, point::x, FloatVect2::y, and point::y.
cloud_sim_reset()
void cloud_sim_reset (bool reset) extern
reset handler
Definition at line 154 of file cloud_sim.c.
References cloud_sim, cloud_sim_circle_id, cloud_sim_polygon, CLOUD_SIM_WPS_NB, foo, nav_move_waypoint_point(), nav_send_waypoint(), CloudSim::reset, and reset.
Variable Documentation
cloud_sim
struct CloudSim cloud_sim extern
Definition at line 72 of file cloud_sim.c.
Referenced by cloud_sim_detect(), cloud_sim_init(), cloud_sim_move(), and cloud_sim_reset().