Paparazzi UAS: sw/airborne/modules/meteo/cloud_sensor.h File Reference
cloud_sensor.h File Reference
Get data from Cloud Sensor.
#include "std.h"
Macros
#define CLOUD_SENSOR_COEF_NONE 0
#define CLOUD_SENSOR_COEF_SINGLE 1
#define CLOUD_SENSOR_COEF_ANGSTROM 2
Functions
void cloud_sensor_update_tau (float tau)
void cloud_sensor_init (void)
Init function.
void cloud_sensor_callback (uint8_t *buf)
New message/data callback.
void LWC_callback (uint8_t *buf)
void cloud_sensor_report (void)
Report function.
Variables
uint8_t cloud_sensor_compute_coef
variables for settings
uint8_t cloud_sensor_compute_background
float cloud_sensor_threshold
float cloud_sensor_hysteresis
float cloud_sensor_background
float cloud_sensor_calib_alpha
float cloud_sensor_calib_beta
float cloud_sensor_channel_scale
float cloud_sensor_tau
Detailed Description
Get data from Cloud Sensor.
compute coef value from PAYLOAD_FLOAT data
Liquid Water Content (LWC)
Angstrom coef
single sensor
get already computed LWC from PAYLOAD_COMMAND data
Definition in file cloud_sensor.h.
Macro Definition Documentation
CLOUD_SENSOR_COEF_ANGSTROM
#define CLOUD_SENSOR_COEF_ANGSTROM 2
Definition at line 40 of file cloud_sensor.h.
CLOUD_SENSOR_COEF_NONE
#define CLOUD_SENSOR_COEF_NONE 0
Definition at line 38 of file cloud_sensor.h.
CLOUD_SENSOR_COEF_SINGLE
#define CLOUD_SENSOR_COEF_SINGLE 1
Definition at line 39 of file cloud_sensor.h.
Function Documentation
cloud_sensor_callback()
void cloud_sensor_callback (uint8_t * buf) extern
New message/data callback.
New message/data callback.
Definition at line 397 of file cloud_sensor.c.
References angstrom_coef, angstrom_offset, CloudSensor::background, check_border(), cloud_sensor, cloud_sensor_background, CLOUD_SENSOR_BACKGROUND_HYSTERESIS_COEF, CLOUD_SENSOR_BACKGROUND_NB, CLOUD_SENSOR_BACKGROUND_THRESHOLD_COEF, CLOUD_SENSOR_COEF_ANGSTROM, CLOUD_SENSOR_COEF_SINGLE, cloud_sensor_compute_background, cloud_sensor_compute_coef, cloud_sensor_filtering(), cloud_sensor_hysteresis, CLOUD_SENSOR_LOG_FILE, CLOUD_SENSOR_NB, CLOUD_SENSOR_OFFSET, CLOUD_SENSOR_RAW_MAX, CLOUD_SENSOR_SINGLE_CHANNEL, cloud_sensor_threshold, CloudSensor::coef, covariance_f(), UtmCoor_f::east, GpsState::fix, foo, get_sys_time_usec(), gps, GpsFixValid, GpsState::hmsl, Background::idx, idx, LinReg::lambda, log_tagged, lowPassFilter0, Background::mean, mean_f(), medianFilter0, Min, CloudSensor::nb_raw, UtmCoor_f::north, pprzlog_tp, Background::raw, CloudSensor::raw, CloudSensor::reg, send_cloud_sensor_data(), send_data(), stateGetPositionUtm_f(), Background::std, GpsState::tow, CloudSensor::values, LinReg::var_lambda, variance_f(), and GpsState::week.
cloud_sensor_init()
void cloud_sensor_init (void) extern
Init function.
Definition at line 290 of file cloud_sensor.c.
References CloudSensor::background, cloud_sensor, cloud_sensor_background, CLOUD_SENSOR_BORDER_HYSTERESIS, CLOUD_SENSOR_BORDER_THRESHOLD, CLOUD_SENSOR_CALIB_ALPHA, cloud_sensor_calib_alpha, CLOUD_SENSOR_CALIB_BETA, cloud_sensor_calib_beta, CLOUD_SENSOR_CHANNEL_SCALE, cloud_sensor_channel_scale, CLOUD_SENSOR_COEF_SINGLE, cloud_sensor_compute_coef, cloud_sensor_hysteresis, CLOUD_SENSOR_NB, CLOUD_SENSOR_TAU, cloud_sensor_tau, cloud_sensor_threshold, CloudSensor::coef, MedianFilter::current, foo, Background::idx, init_first_order_low_pass(), CloudSensor::inside_cloud, LinReg::lambda, lambdas, MedianFilter::length, log_tagged, lowPassFilter0, Background::mean, medianFilter0, CloudSensor::nb_raw, CloudSensor::reg, Background::std, CloudSensor::values, LinReg::var_lambda, and variance_f().
cloud_sensor_report()
void cloud_sensor_report (void) extern
Report function.
Definition at line 547 of file cloud_sensor.c.
References DefaultChannel, DefaultDevice, and send_cloud_sensor_data().
cloud_sensor_update_tau()
void cloud_sensor_update_tau (float tau) extern
Definition at line 324 of file cloud_sensor.c.
References cloud_sensor_tau, lowPassFilter0, and update_first_order_low_pass_tau().
LWC_callback()
void LWC_callback (uint8_t * buf) extern
Definition at line 532 of file cloud_sensor.c.
References check_border(), cloud_sensor, CloudSensor::coef, dl_buffer, foo, get_sys_time_usec(), lwc_from_buffer(), and send_data().
Variable Documentation
cloud_sensor_background
float cloud_sensor_background extern
Definition at line 200 of file cloud_sensor.c.
Referenced by cloud_sensor_callback(), and cloud_sensor_init().
cloud_sensor_calib_alpha
float cloud_sensor_calib_alpha extern
Definition at line 201 of file cloud_sensor.c.
Referenced by cloud_sensor_filtering(), and cloud_sensor_init().
cloud_sensor_calib_beta
float cloud_sensor_calib_beta extern
Definition at line 202 of file cloud_sensor.c.
Referenced by cloud_sensor_filtering(), and cloud_sensor_init().
cloud_sensor_channel_scale
float cloud_sensor_channel_scale extern
Definition at line 203 of file cloud_sensor.c.
Referenced by cloud_sensor_filtering(), and cloud_sensor_init().
cloud_sensor_compute_background
uint8_t cloud_sensor_compute_background extern
Definition at line 197 of file cloud_sensor.c.
Referenced by cloud_sensor_callback().
cloud_sensor_compute_coef
uint8_t cloud_sensor_compute_coef extern
variables for settings
variables for settings
Definition at line 196 of file cloud_sensor.c.
Referenced by cloud_sensor_callback(), and cloud_sensor_init().
cloud_sensor_hysteresis
float cloud_sensor_hysteresis extern
Definition at line 199 of file cloud_sensor.c.
Referenced by check_border(), cloud_sensor_callback(), and cloud_sensor_init().
cloud_sensor_tau
float cloud_sensor_tau extern
Definition at line 204 of file cloud_sensor.c.
Referenced by cloud_sensor_init(), and cloud_sensor_update_tau().
cloud_sensor_threshold
float cloud_sensor_threshold extern
Definition at line 198 of file cloud_sensor.c.
Referenced by check_border(), cloud_sensor_callback(), and cloud_sensor_init().