Paparazzi UAS: sw/airborne/modules/computer_vision/colorfilter.c File Reference
colorfilter.c File Reference
#include "modules/computer_vision/colorfilter.h"
#include <stdio.h>
#include "modules/computer_vision/lib/vision/image.h"
#include "subsystems/abi.h"
Macros
#define COLORFILTER_FPS 0
Default FPS (zero means run at camera fps)
#define COLORFILTER_SEND_OBSTACLE FALSE
Default sonar/agl to use in opticflow visual_estimator.
Functions
static struct image_t * colorfilter_func (struct image_t *img, uint8_t camera_id)
void colorfilter_init (void)
Variables
struct video_listener * listener = NULL
uint8_t color_lum_min = 105
uint8_t color_lum_max = 205
uint8_t color_cb_min = 52
uint8_t color_cb_max = 140
uint8_t color_cr_min = 180
uint8_t color_cr_max = 255
volatile int color_count = 0
Macro Definition Documentation
#define COLORFILTER_FPS 0
Default FPS (zero means run at camera fps)
Definition at line 33 of file colorfilter.c.
Referenced by colorfilter_init().
#define COLORFILTER_SEND_OBSTACLE FALSE
Default sonar/agl to use in opticflow visual_estimator.
Definition at line 39 of file colorfilter.c.
Referenced by colorfilter_func().
Function Documentation
static struct image_t* colorfilter_func (struct image_t * img, uint8_t camera_id) static
Definition at line 59 of file colorfilter.c.
References COLORFILTER_SEND_OBSTACLE, f, image_yuv422_colorfilt(), and OBS_DETECTION_COLOR_ID.
Referenced by colorfilter_init().
void colorfilter_init (void)
Definition at line 82 of file colorfilter.c.
References COLORFILTER_FPS, colorfilter_func(), and cv_add_to_device().
Variable Documentation
uint8_t color_cb_max = 140
Definition at line 49 of file colorfilter.c.
uint8_t color_cb_min = 52
Definition at line 48 of file colorfilter.c.
volatile int color_count = 0
Definition at line 54 of file colorfilter.c.
Referenced by color_object_detector_periodic().
uint8_t color_cr_max = 255
Definition at line 51 of file colorfilter.c.
uint8_t color_cr_min = 180
Definition at line 50 of file colorfilter.c.
uint8_t color_lum_max = 205
Definition at line 47 of file colorfilter.c.
uint8_t color_lum_min = 105
Definition at line 46 of file colorfilter.c.
struct video_listener* listener = NULL
Definition at line 43 of file colorfilter.c.
Referenced by cv_add_to_device(), cv_add_to_device_async(), cv_async_thread(), and cv_run_device().