Paparazzi UAS: sw/airborne/modules/core/commands.h File Reference
commands.h File Reference
Hardware independent code for commands handling.
#include "paparazzi.h"
#include "generated/airframe.h"
Functions
void commands_init (void)
Detailed Description
Hardware independent code for commands handling.
Definition in file commands.h.
Function Documentation
commands_init()
void commands_init (void) extern
Definition at line 46 of file commands.c.
References command_pitch_trim, command_roll_trim, command_yaw_trim, commands_failsafe, DefaultPeriodic, foo, register_periodic_telemetry(), and send_commands().
Referenced by main_recovery_init().