Paparazzi UAS: sw/airborne/filters/complementary_filter_types.h File Reference
complementary_filter_types.h File Reference
Definitions and inline functions for 1st order complementary filter vector types.
#include "std.h"
#include "filters/complementary_filter.h"
#include "math/pprz_algebra_float.h"
Data Structures
struct FirstOrderComplementaryVect3
3D vector of 1st order complementary filters.
struct Butterworth2ComplementaryVect3
3D vector of 2nd order Butterworth complementary filters.
struct Butterworth4ComplementaryVect3
3D vector of 4th order Butterworth complementary filters.
Functions
static void init_first_order_complementary_vect3 (struct FirstOrderComplementaryVect3 *filter, const struct FloatVect3 *cut_off, float sample_time)
Initialize 3D vector of 1st order complementary filters.
static struct FloatVect3 get_first_order_complementary_vect3 (const struct FirstOrderComplementaryVect3 *filter)
Get current output 3D vector from 1st order complementary filters.
static struct FloatRates get_first_order_complementary_rates (const struct FirstOrderComplementaryVect3 *filter)
Get current output rates from 1st order complementary filters.
static struct FloatVect3 update_first_order_complementary_vect3 (struct FirstOrderComplementaryVect3 *filter, const struct FloatVect3 *value_x, const struct FloatVect3 *value_y)
Update 3D vector of 1st order complementary filters.
static struct FloatRates update_first_order_complementary_rates (struct FirstOrderComplementaryVect3 *filter, const struct FloatRates *value_x, const struct FloatRates *value_y)
Update 3D vector of 1st order complementary filters for rates.
static void reset_first_order_complementary_vect3 (struct FirstOrderComplementaryVect3 *filter, const struct FloatVect3 *value)
Reset 3D vector of 1st order complementary filters to a specific value.
static void reset_first_order_complementary_rates (struct FirstOrderComplementaryVect3 *filter, const struct FloatRates *value)
Reset 3D vector of 1st order complementary filters for rates to a specific value.
static void init_first_order_complementary_array (uint8_t n, struct FirstOrderComplementary filter_array[restrict n], const float cut_off[restrict n], float sample_time)
Initialize an array of 1st order complementary filters.
static void update_first_order_complementary_array (uint8_t n, struct FirstOrderComplementary filter_array[restrict n], const float value_x_array[restrict n], const float value_y_array[restrict n])
Update an array of 1st order complementary filters.
static void reset_first_order_complementary_array (uint8_t n, struct FirstOrderComplementary filter_array[restrict n], const float value_array[restrict n])
Reset an array of 1st order complementary filters to specific values.
static void get_first_order_complementary_array (uint8_t n, const struct FirstOrderComplementary filter_array[restrict n], float output_array[restrict n])
Get current outputs from an array of 1st order complementary filters.
static void init_butterworth_2_complementary_vect3 (struct Butterworth2ComplementaryVect3 *filter, const struct FloatVect3 *cut_off, float sample_time)
Initialize 3D vector of 2nd order Butterworth complementary filters.
static struct FloatVect3 get_butterworth_2_complementary_vect3 (const struct Butterworth2ComplementaryVect3 *filter)
Get current output 3D vector from 2nd order Butterworth complementary filters.
static struct FloatRates get_butterworth_2_complementary_rates (const struct Butterworth2ComplementaryVect3 *filter)
Get current output rates from 2nd order Butterworth complementary filters.
static struct FloatVect3 update_butterworth_2_complementary_vect3 (struct Butterworth2ComplementaryVect3 *filter, const struct FloatVect3 *value_x, const struct FloatVect3 *value_y)
Initialize 3D vector of 2nd order Butterworth complementary filters.
static struct FloatRates update_butterworth_2_complementary_rates (struct Butterworth2ComplementaryVect3 *filter, const struct FloatRates *value_x, const struct FloatRates *value_y)
Update 3D vector of 2nd order Butterworth complementary filters.
static void reset_butterworth_2_complementary_vect3 (struct Butterworth2ComplementaryVect3 *filter, const struct FloatVect3 *value)
Reset 3D vector of 2nd order Butterworth complementary filters to a specific value.
static void reset_butterworth_2_complementary_rates (struct Butterworth2ComplementaryVect3 *filter, const struct FloatRates *value)
Reset 3D vector of 2nd order Butterworth complementary filters for rates to a specific value.
static void init_butterworth_2_complementary_array (uint8_t n, Butterworth2Complementary filter_array[restrict n], const float cut_off[restrict n], float sample_time)
Initialize an array of 2nd order Butterworth complementary filters.
static void update_butterworth_2_complementary_array (uint8_t n, Butterworth2Complementary filter_array[restrict n], const float value_x_array[restrict n], const float value_y_array[restrict n])
Update an array of 2nd order Butterworth complementary filters.
static void reset_butterworth_2_complementary_array (uint8_t n, Butterworth2Complementary filter_array[restrict n], const float value_array[restrict n])
Reset an array of 2nd order Butterworth complementary filters to specific values.
static void get_butterworth_2_complementary_array (uint8_t n, const Butterworth2Complementary filter_array[restrict n], float output_array[restrict n])
Get current outputs from an array of 2nd order Butterworth complementary filters.
static void init_butterworth_4_complementary_vect3 (struct Butterworth4ComplementaryVect3 *filter, const struct FloatVect3 *cut_off, float sample_time)
Initialize 3D vector of 4th order Butterworth complementary filters.
static struct FloatVect3 get_butterworth_4_complementary_vect3 (const struct Butterworth4ComplementaryVect3 *filter)
Get current output 3D vector from 4th order Butterworth complementary filters.
static struct FloatRates get_butterworth_4_complementary_rates (const struct Butterworth4ComplementaryVect3 *filter)
Get current output rates from 4th order Butterworth complementary filters.
static struct FloatVect3 update_butterworth_4_complementary_vect3 (struct Butterworth4ComplementaryVect3 *filter, const struct FloatVect3 *value_x, const struct FloatVect3 *value_y)
Initialize 3D vector of 4th order Butterworth complementary filters.
static struct FloatRates update_butterworth_4_complementary_rates (struct Butterworth4ComplementaryVect3 *filter, const struct FloatRates *value_x, const struct FloatRates *value_y)
Update 3D vector of 4th order Butterworth complementary filters for rates.
static void reset_butterworth_4_complementary_vect3 (struct Butterworth4ComplementaryVect3 *filter, const struct FloatVect3 *value)
Reset 3D vector of 4th order Butterworth complementary filters to a specific value.
static void reset_butterworth_4_complementary_rates (struct Butterworth4ComplementaryVect3 *filter, const struct FloatRates *value)
Reset 3D vector of 4th order Butterworth complementary filters for rates to a specific value.
static void init_butterworth_4_complementary_array (uint8_t n, Butterworth4Complementary filter_array[restrict n], const float cut_off[restrict n], float sample_time)
Initialize an array of 4th order Butterworth complementary filters.
static void update_butterworth_4_complementary_array (uint8_t n, Butterworth4Complementary filter_array[restrict n], const float value_x_array[restrict n], const float value_y_array[restrict n])
Update an array of 4th order Butterworth complementary filters.
static void reset_butterworth_4_complementary_array (uint8_t n, Butterworth4Complementary filter_array[restrict n], const float value_array[restrict n])
Reset an array of 4th order Butterworth complementary filters to specific values.
static void get_butterworth_4_complementary_array (uint8_t n, const Butterworth4Complementary filter_array[restrict n], float output_array[restrict n])
Get current outputs from an array of 4th order Butterworth complementary filters.
Detailed Description
Definitions and inline functions for 1st order complementary filter vector types.
Provides structures and functions to initialize, update, reset, and get outputs from 1st order complementary filter vectors.
Author
Justin Dubois j.p.g.nosp@m..dub.nosp@m.ois@s.nosp@m.tude.nosp@m.nt.tu.nosp@m.delf.nosp@m.t.nl
Definition in file complementary_filter_types.h.
Data Structure Documentation
FirstOrderComplementaryVect3
struct FirstOrderComplementaryVect3
3D vector of 1st order complementary filters.
This structure contains three 1st order complementary filters for the x, y, and z components.
Definition at line 45 of file complementary_filter_types.h.
Data Fields
struct FirstOrderComplementary x
struct FirstOrderComplementary y
struct FirstOrderComplementary z
Butterworth2ComplementaryVect3
struct Butterworth2ComplementaryVect3
3D vector of 2nd order Butterworth complementary filters.
This structure contains three 2nd order Butterworth complementary filters for the x, y, and z components.
Definition at line 225 of file complementary_filter_types.h.
Data Fields
Butterworth2Complementary x
Butterworth2Complementary y
Butterworth2Complementary z
Butterworth4ComplementaryVect3
struct Butterworth4ComplementaryVect3
3D vector of 4th order Butterworth complementary filters.
This structure contains three 4th order Butterworth complementary filters for the x, y, and z components.
Definition at line 406 of file complementary_filter_types.h.
Data Fields
Butterworth4Complementary x
Butterworth4Complementary y
Butterworth4Complementary z
Function Documentation
get_butterworth_2_complementary_array()
static void get_butterworth_2_complementary_array (uint8_t n, const Butterworth2Complementary filter_array[restrict n], float output_array[restrict n]) inline static
Get current outputs from an array of 2nd order Butterworth complementary filters.
Parameters
[in] n Number of filters in the array.
[in] filter_array Array of Butterworth2Complementary filters.
[out] output_array Array to store the filtered output values.
Definition at line 392 of file complementary_filter_types.h.
References foo, and get_butterworth_2_complementary().
get_butterworth_2_complementary_rates()
static struct FloatRates get_butterworth_2_complementary_rates (const struct Butterworth2ComplementaryVect3 * filter) inline static
Get current output rates from 2nd order Butterworth complementary filters.
Parameters
[in] filter Pointer to Butterworth2ComplementaryVect3 struct.
Returns
FloatRates containing filtered outputs p, q, r.
Definition at line 268 of file complementary_filter_types.h.
References foo, get_butterworth_2_complementary(), FloatRates::p, FloatVect3::x, FloatVect3::y, and FloatVect3::z.
Referenced by update_butterworth_2_complementary_rates().
get_butterworth_2_complementary_vect3()
static struct FloatVect3 get_butterworth_2_complementary_vect3 (const struct Butterworth2ComplementaryVect3 * filter) inline static
Get current output 3D vector from 2nd order Butterworth complementary filters.
Parameters
[in] filter Pointer to Butterworth2ComplementaryVect3 struct.
Returns
FloatVect3 containing filtered outputs.
Definition at line 252 of file complementary_filter_types.h.
References foo, get_butterworth_2_complementary(), FloatVect3::x, FloatVect3::y, and FloatVect3::z.
Referenced by stabilization_andi_run(), and update_butterworth_2_complementary_vect3().
get_butterworth_4_complementary_array()
static void get_butterworth_4_complementary_array (uint8_t n, const Butterworth4Complementary filter_array[restrict n], float output_array[restrict n]) inline static
Get current outputs from an array of 4th order Butterworth complementary filters.
Parameters
[in] n Number of filters in the array.
[in] filter_array Array of Butterworth4Complementary filters.
[out] output_array Array to store the filtered output values.
Definition at line 574 of file complementary_filter_types.h.
References foo, and get_butterworth_4_complementary().
get_butterworth_4_complementary_rates()
static struct FloatRates get_butterworth_4_complementary_rates (const struct Butterworth4ComplementaryVect3 * filter) inline static
Get current output rates from 4th order Butterworth complementary filters.
Parameters
[in] filter Pointer to Butterworth4ComplementaryVect3 struct.
Returns
FloatRates containing filtered outputs p, q, r.
Definition at line 449 of file complementary_filter_types.h.
References foo, get_butterworth_4_complementary(), FloatRates::p, FloatVect3::x, FloatVect3::y, and FloatVect3::z.
Referenced by update_butterworth_4_complementary_rates().
get_butterworth_4_complementary_vect3()
static struct FloatVect3 get_butterworth_4_complementary_vect3 (const struct Butterworth4ComplementaryVect3 * filter) inline static
Get current output 3D vector from 4th order Butterworth complementary filters.
Parameters
[in] filter Pointer to Butterworth4ComplementaryVect3 struct.
Returns
FloatVect3 containing filtered outputs.
Definition at line 433 of file complementary_filter_types.h.
References foo, get_butterworth_4_complementary(), FloatVect3::x, FloatVect3::y, and FloatVect3::z.
Referenced by update_butterworth_4_complementary_vect3().
get_first_order_complementary_array()
static void get_first_order_complementary_array (uint8_t n, const struct FirstOrderComplementary filter_array[restrict n], float output_array[restrict n]) inline static
Get current outputs from an array of 1st order complementary filters.
Parameters
[in] n Number of filters in the array.
[in] filter_array Array of FirstOrderComplementary filters.
[out] output_array Array to store the filtered output values.
Definition at line 211 of file complementary_filter_types.h.
References foo, and get_first_order_complementary().
get_first_order_complementary_rates()
static struct FloatRates get_first_order_complementary_rates (const struct FirstOrderComplementaryVect3 * filter) inline static
Get current output rates from 1st order complementary filters.
Parameters
[in] filter Pointer to FirstOrderComplementaryVect3 struct.
Returns
FloatRates containing filtered outputs p, q, r.
Definition at line 87 of file complementary_filter_types.h.
References foo, get_first_order_complementary(), and FloatRates::p.
Referenced by stabilization_andi_run(), and update_first_order_complementary_rates().
get_first_order_complementary_vect3()
static struct FloatVect3 get_first_order_complementary_vect3 (const struct FirstOrderComplementaryVect3 * filter) inline static
Get current output 3D vector from 1st order complementary filters.
Parameters
[in] filter Pointer to FirstOrderComplementaryVect3 struct.
Returns
FloatVect3 containing filtered outputs.
Definition at line 72 of file complementary_filter_types.h.
References foo, get_first_order_complementary(), and FloatVect3::x.
Referenced by stabilization_andi_run(), and update_first_order_complementary_vect3().
init_butterworth_2_complementary_array()
static void init_butterworth_2_complementary_array (uint8_t n, Butterworth2Complementary filter_array[restrict n], const float cut_off[restrict n], float sample_time) inline static
Initialize an array of 2nd order Butterworth complementary filters.
Parameters
[in] n Number of filters in the array.
[out] filter_array Array of Butterworth2Complementary filters.
[in] cut_off Time constant in seconds.
[in] sample_time Sampling period in seconds.
Definition at line 346 of file complementary_filter_types.h.
References foo, and init_butterworth_2_complementary().
init_butterworth_2_complementary_vect3()
static void init_butterworth_2_complementary_vect3 (struct Butterworth2ComplementaryVect3 * filter, const struct FloatVect3 * cut_off, float sample_time) inline static
Initialize 3D vector of 2nd order Butterworth complementary filters.
Parameters
[out] filter Pointer to the Butterworth2ComplementaryVect3 struct.
[in] cut_off Time constant in seconds.
[in] sample_time Sampling period in seconds.
Definition at line 238 of file complementary_filter_types.h.
References foo, init_butterworth_2_complementary(), Butterworth2ComplementaryVect3::x, Butterworth2ComplementaryVect3::y, and Butterworth2ComplementaryVect3::z.
Referenced by stabilization_andi_init().
init_butterworth_4_complementary_array()
static void init_butterworth_4_complementary_array (uint8_t n, Butterworth4Complementary filter_array[restrict n], const float cut_off[restrict n], float sample_time) inline static
Initialize an array of 4th order Butterworth complementary filters.
Parameters
[in] n Number of filters to initialize.
[out] filter_array Array of Butterworth4Complementary filters.
[in] cut_off Time constant in seconds.
[in] sample_time Sampling period (seconds).
Definition at line 527 of file complementary_filter_types.h.
References foo, and init_butterworth_4_complementary().
init_butterworth_4_complementary_vect3()
static void init_butterworth_4_complementary_vect3 (struct Butterworth4ComplementaryVect3 * filter, const struct FloatVect3 * cut_off, float sample_time) inline static
Initialize 3D vector of 4th order Butterworth complementary filters.
Parameters
[out] filter Pointer to the Butterworth4ComplementaryVect3 struct.
[in] cut_off Time constant in seconds.
[in] sample_time Sampling period in seconds.
Definition at line 419 of file complementary_filter_types.h.
References foo, init_butterworth_4_complementary(), Butterworth4ComplementaryVect3::x, Butterworth4ComplementaryVect3::y, and Butterworth4ComplementaryVect3::z.
init_first_order_complementary_array()
static void init_first_order_complementary_array (uint8_t n, struct FirstOrderComplementary filter_array[restrict n], const float cut_off[restrict n], float sample_time) inline static
Initialize an array of 1st order complementary filters.
Parameters
[in] n Number of filters in the array.
[out] filter_array Array of FirstOrderComplementary filters.
[in] cut_off Time constant in seconds.
[in] sample_time Sampling period in seconds.
Definition at line 164 of file complementary_filter_types.h.
References foo, and init_first_order_complementary().
init_first_order_complementary_vect3()
static void init_first_order_complementary_vect3 (struct FirstOrderComplementaryVect3 * filter, const struct FloatVect3 * cut_off, float sample_time) inline static
Initialize 3D vector of 1st order complementary filters.
Parameters
[out] filter Pointer to the FirstOrderComplementaryVect3 struct.
[in] cut_off Time constant in seconds.
[in] sample_time Sampling period in seconds.
Definition at line 58 of file complementary_filter_types.h.
References foo, init_first_order_complementary(), FirstOrderComplementaryVect3::x, FirstOrderComplementaryVect3::y, and FirstOrderComplementaryVect3::z.
Referenced by stabilization_andi_init().
reset_butterworth_2_complementary_array()
static void reset_butterworth_2_complementary_array (uint8_t n, Butterworth2Complementary filter_array[restrict n], const float value_array[restrict n]) inline static
Reset an array of 2nd order Butterworth complementary filters to specific values.
Parameters
[in] n Number of filters in the array.
[in,out] filter_array Array of Butterworth2Complementary filters.
[in] value_array Array of values to reset the filters to.
Definition at line 378 of file complementary_filter_types.h.
References foo, and reset_butterworth_2_complementary().
reset_butterworth_2_complementary_rates()
static void reset_butterworth_2_complementary_rates (struct Butterworth2ComplementaryVect3 * filter, const struct FloatRates * value) inline static
Reset 3D vector of 2nd order Butterworth complementary filters for rates to a specific value.
Parameters
[in,out] filter Pointer to the Butterworth2ComplementaryVect3 struct.
[in] value Value to reset the filters to.
Definition at line 330 of file complementary_filter_types.h.
References FloatRates::p, FloatRates::q, FloatRates::r, reset_butterworth_2_complementary(), Butterworth2ComplementaryVect3::x, Butterworth2ComplementaryVect3::y, and Butterworth2ComplementaryVect3::z.
reset_butterworth_2_complementary_vect3()
static void reset_butterworth_2_complementary_vect3 (struct Butterworth2ComplementaryVect3 * filter, const struct FloatVect3 * value) inline static
Reset 3D vector of 2nd order Butterworth complementary filters to a specific value.
Parameters
[in,out] filter Pointer to the Butterworth2ComplementaryVect3 struct.
[in] value Value to reset the filters to.
Definition at line 316 of file complementary_filter_types.h.
References reset_butterworth_2_complementary(), Butterworth2ComplementaryVect3::x, FloatVect3::x, Butterworth2ComplementaryVect3::y, FloatVect3::y, Butterworth2ComplementaryVect3::z, and FloatVect3::z.
Referenced by stabilization_andi_enter().
reset_butterworth_4_complementary_array()
static void reset_butterworth_4_complementary_array (uint8_t n, Butterworth4Complementary filter_array[restrict n], const float value_array[restrict n]) inline static
Reset an array of 4th order Butterworth complementary filters to specific values.
Parameters
[in] n Number of filters in the array.
[in,out] filter_array Array of Butterworth4Complementary filters.
[in] value_array Array of values to reset the filters to.
Definition at line 559 of file complementary_filter_types.h.
References foo, and reset_butterworth_4_complementary().
reset_butterworth_4_complementary_rates()
static void reset_butterworth_4_complementary_rates (struct Butterworth4ComplementaryVect3 * filter, const struct FloatRates * value) inline static
Reset 3D vector of 4th order Butterworth complementary filters for rates to a specific value.
Parameters
[in,out] filter Pointer to the Butterworth4ComplementaryVect3 struct.
[in] value Value to reset the filters to.
Definition at line 511 of file complementary_filter_types.h.
References FloatRates::p, FloatRates::q, FloatRates::r, reset_butterworth_4_complementary(), Butterworth4ComplementaryVect3::x, Butterworth4ComplementaryVect3::y, and Butterworth4ComplementaryVect3::z.
reset_butterworth_4_complementary_vect3()
static void reset_butterworth_4_complementary_vect3 (struct Butterworth4ComplementaryVect3 * filter, const struct FloatVect3 * value) inline static
Reset 3D vector of 4th order Butterworth complementary filters to a specific value.
Parameters
[in,out] filter Pointer to the Butterworth4ComplementaryVect3 struct.
[in] value Value to reset the filters to.
Definition at line 497 of file complementary_filter_types.h.
References reset_butterworth_4_complementary(), Butterworth4ComplementaryVect3::x, FloatVect3::x, Butterworth4ComplementaryVect3::y, FloatVect3::y, Butterworth4ComplementaryVect3::z, and FloatVect3::z.
reset_first_order_complementary_array()
static void reset_first_order_complementary_array (uint8_t n, struct FirstOrderComplementary filter_array[restrict n], const float value_array[restrict n]) inline static
Reset an array of 1st order complementary filters to specific values.
Parameters
[in] n Number of filters in the array.
[in,out] filter_array Array of FirstOrderComplementary filters.
[in] value_array Array of values to reset the filters to.
Definition at line 196 of file complementary_filter_types.h.
References foo, and reset_first_order_complementary().
reset_first_order_complementary_rates()
static void reset_first_order_complementary_rates (struct FirstOrderComplementaryVect3 * filter, const struct FloatRates * value) inline static
Reset 3D vector of 1st order complementary filters for rates to a specific value.
Parameters
[in,out] filter Pointer to the FirstOrderComplementaryVect3 struct.
[in] value Value to reset the filters to.
Definition at line 148 of file complementary_filter_types.h.
References FloatRates::p, FloatRates::q, FloatRates::r, reset_first_order_complementary(), FirstOrderComplementaryVect3::x, FirstOrderComplementaryVect3::y, and FirstOrderComplementaryVect3::z.
Referenced by stabilization_andi_enter().
reset_first_order_complementary_vect3()
static void reset_first_order_complementary_vect3 (struct FirstOrderComplementaryVect3 * filter, const struct FloatVect3 * value) inline static
Reset 3D vector of 1st order complementary filters to a specific value.
Parameters
[in,out] filter Pointer to the FirstOrderComplementaryVect3 struct.
[in] value Value to reset the filters to.
Definition at line 134 of file complementary_filter_types.h.
References reset_first_order_complementary(), FirstOrderComplementaryVect3::x, FloatVect3::x, FirstOrderComplementaryVect3::y, FloatVect3::y, FirstOrderComplementaryVect3::z, and FloatVect3::z.
Referenced by stabilization_andi_enter().
update_butterworth_2_complementary_array()
static void update_butterworth_2_complementary_array (uint8_t n, Butterworth2Complementary filter_array[restrict n], const float value_x_array[restrict n], const float value_y_array[restrict n]) inline static
Update an array of 2nd order Butterworth complementary filters.
Parameters
[in] n Number of filters in the array.
[in,out] filter_array Array of Butterworth2Complementary filters.
[in] value_x_array Array of input x values.
[in] value_y_array Array of input y values.
Definition at line 362 of file complementary_filter_types.h.
References foo, and update_butterworth_2_complementary().
update_butterworth_2_complementary_rates()
static struct FloatRates update_butterworth_2_complementary_rates (struct Butterworth2ComplementaryVect3 * filter, const struct FloatRates * value_x, const struct FloatRates * value_y) inline static
Update 3D vector of 2nd order Butterworth complementary filters.
Parameters
[in,out] filter Pointer to the Butterworth2ComplementaryVect3 struct.
[in] value_x Pointer to FloatVect3 input vector x values.
[in] value_y Pointer to FloatVect3 input vector y values.
Definition at line 301 of file complementary_filter_types.h.
References foo, get_butterworth_2_complementary_rates(), update_butterworth_2_complementary(), FloatVect3::x, FloatVect3::y, and FloatVect3::z.
update_butterworth_2_complementary_vect3()
static struct FloatVect3 update_butterworth_2_complementary_vect3 (struct Butterworth2ComplementaryVect3 * filter, const struct FloatVect3 * value_x, const struct FloatVect3 * value_y) inline static
Initialize 3D vector of 2nd order Butterworth complementary filters.
Parameters
[out] filter Pointer to the Butterworth2ComplementaryVect3 struct.
[in] cut_off Time constant in seconds.
[in] sample_time Sampling period in seconds.
Definition at line 285 of file complementary_filter_types.h.
References foo, get_butterworth_2_complementary_vect3(), update_butterworth_2_complementary(), FloatVect3::x, FloatVect3::y, and FloatVect3::z.
Referenced by stabilization_andi_run().
update_butterworth_4_complementary_array()
static void update_butterworth_4_complementary_array (uint8_t n, Butterworth4Complementary filter_array[restrict n], const float value_x_array[restrict n], const float value_y_array[restrict n]) inline static
Update an array of 4th order Butterworth complementary filters.
Parameters
[in] n Number of filters in the array.
[in,out] filter_array Array of Butterworth4Complementary filters.
[in] value_x_array Array of input x values.
[in] value_y_array Array of input y values.
Definition at line 543 of file complementary_filter_types.h.
References foo, and update_butterworth_4_complementary().
update_butterworth_4_complementary_rates()
static struct FloatRates update_butterworth_4_complementary_rates (struct Butterworth4ComplementaryVect3 * filter, const struct FloatRates * value_x, const struct FloatRates * value_y) inline static
Update 3D vector of 4th order Butterworth complementary filters for rates.
Parameters
[in,out] filter Pointer to the Butterworth4ComplementaryVect3 struct.
[in] value_x Pointer to FloatRates input p, q, r values.
[in] value_y Pointer to FloatRates input p, q, r values.
Definition at line 482 of file complementary_filter_types.h.
References foo, get_butterworth_4_complementary_rates(), update_butterworth_4_complementary(), FloatVect3::x, FloatVect3::y, and FloatVect3::z.
update_butterworth_4_complementary_vect3()
static struct FloatVect3 update_butterworth_4_complementary_vect3 (struct Butterworth4ComplementaryVect3 * filter, const struct FloatVect3 * value_x, const struct FloatVect3 * value_y) inline static
Initialize 3D vector of 4th order Butterworth complementary filters.
Parameters
[out] filter Pointer to the Butterworth4ComplementaryVect3 struct.
[in] cut_off Time constant in seconds.
[in] sample_time Sampling period in seconds.
Definition at line 466 of file complementary_filter_types.h.
References foo, get_butterworth_4_complementary_vect3(), update_butterworth_4_complementary(), FloatVect3::x, FloatVect3::y, and FloatVect3::z.
update_first_order_complementary_array()
static void update_first_order_complementary_array (uint8_t n, struct FirstOrderComplementary filter_array[restrict n], const float value_x_array[restrict n], const float value_y_array[restrict n]) inline static
Update an array of 1st order complementary filters.
Parameters
[in] n Number of filters in the array.
[in,out] filter_array Array of FirstOrderComplementary filters.
[in] value_x_array Array of input x values.
[in] value_y_array Array of input y values.
Definition at line 180 of file complementary_filter_types.h.
References foo, and update_first_order_complementary().
update_first_order_complementary_rates()
static struct FloatRates update_first_order_complementary_rates (struct FirstOrderComplementaryVect3 * filter, const struct FloatRates * value_x, const struct FloatRates * value_y) inline static
Update 3D vector of 1st order complementary filters for rates.
Parameters
[in,out] filter Pointer to the FirstOrderComplementaryVect3 struct.
[in] value_x Pointer to FloatRates input p, q, r values.
[in] value_y Pointer to FloatRates input p, q, r values.
Definition at line 119 of file complementary_filter_types.h.
References foo, get_first_order_complementary_rates(), update_first_order_complementary(), FloatVect3::x, FloatVect3::y, and FloatVect3::z.
Referenced by stabilization_andi_run().
update_first_order_complementary_vect3()
static struct FloatVect3 update_first_order_complementary_vect3 (struct FirstOrderComplementaryVect3 * filter, const struct FloatVect3 * value_x, const struct FloatVect3 * value_y) inline static
Update 3D vector of 1st order complementary filters.
Parameters
[in,out] filter Pointer to the FirstOrderComplementaryVect3 struct.
[in] value_x Pointer to FloatVect3 input vector x values.
[in] value_y Pointer to FloatVect3 input vector y values.
Definition at line 103 of file complementary_filter_types.h.
References foo, get_first_order_complementary_vect3(), update_first_order_complementary(), FloatVect3::x, FloatVect3::y, and FloatVect3::z.
Referenced by stabilization_andi_run().