Paparazzi UAS: sw/airborne/modules/mission/copilot_rotorcraft.c File Reference
copilot_rotorcraft.c File Reference
Mission Computer module, interfacing the mission computer (also known as Copilot), based losely on ISaAC: The Intelligent Safety and Airworthiness Co-Pilot module Based on paper "A Payload Verification and Management Framework for Small UAV-based Personal Remote Sensing Systems" by Cal Coopmans and Chris Coffin.
#include "modules/mission/copilot.h"
#include "modules/datalink/telemetry.h"
#include "firmwares/rotorcraft/navigation.h"
#include "math/pprz_geodetic_int.h"
Functions
void copilot_parse_move_wp_dl (uint8_t *buf)
If MOVE_WP from GCS.
Detailed Description
Mission Computer module, interfacing the mission computer (also known as Copilot), based losely on ISaAC: The Intelligent Safety and Airworthiness Co-Pilot module Based on paper "A Payload Verification and Management Framework for Small UAV-based Personal Remote Sensing Systems" by Cal Coopmans and Chris Coffin.
Link: http://ieeexplore.ieee.org/abstract/document/6309316/
More info can be found on http://wiki.paparazziuav.org/wiki/Mission_computer
Copilot is intended mainly for mapping applications.
This module processes messages from Copilot, and either forwards them to the GCS (such as CAMERA_SNAPSHOT or CAMERA_PAYLOAD messages), or responds to them as necessary (such as MOVE_WP).
The module assumes the source of the messages is trusted (i.e. not authentication besides AC_ID check is performed).
Definition in file copilot_rotorcraft.c.
Function Documentation
copilot_parse_move_wp_dl()
void copilot_parse_move_wp_dl (uint8_t * buf)
If MOVE_WP from GCS.
processed in firmware_parse_msg(dev, trans, buf); with regular buffer
reponse over telemetry (regular buffer)
here send WP_MOVED over extra_dl
If MOVE_WP from extra_dl
processed in firmware_parse_msg(dev, trans, buf); with extra buffer
response over extra_dl
send an update to GCS
In both cases, the MOVE_WP message was already processed in firmware_parse here we are taking care only about propagating the change
Definition at line 68 of file copilot_rotorcraft.c.
References LlaCoor_f::alt, LlaCoor_i::alt, DefaultChannel, DefaultDevice, dl_buffer, extra_dl_buffer, extra_pprz_tp, foo, LlaCoor_f::lat, LlaCoor_i::lat, LlaCoor_f::lon, LlaCoor_i::lon, nav_utm_east0, nav_utm_north0, nav_utm_zone0, nb_waypoint, stateGetHmslOrigin_i(), stateGetLlaOrigin_i(), stateIsLocalCoordinateValid(), utm_of_lla_f(), waypoint_is_global(), waypoints, point::x, point::y, and UtmCoor_f::zone.