Paparazzi UAS: sw/airborne/modules/multi/ctc/ctc.h File Reference
ctc.h File Reference
Collective Tracking Control.
#include "std.h"
Data Structures
struct ctc_con
Functions
void ctc_init (void)
bool collective_tracking_vehicle (void)
bool collective_tracking_waypoint (uint8_t wp)
bool collective_tracking_point (float x, float y)
void collective_tracking_control (void)
void ctc_send_info_to_nei (void)
void parse_ctc_RegTable (uint8_t *buf)
void parse_ctc_CleanTable (uint8_t *buf)
void parse_ctc_NeiInfoTable (uint8_t *buf)
void parse_ctc_TargetInfo (uint8_t *buf)
Variables
ctc_con ctc_control
int16_t tableNei [][6]
float ctc_error_to_target
Detailed Description
Collective Tracking Control.
Definition in file ctc.h.
Data Structure Documentation
ctc_con
struct ctc_con
Definition at line 33 of file ctc.h.
Data Fields
float alpha
float k1
float k2
float omega
float p_centroid_x
float p_centroid_y
float px
float py
float ref_px
float ref_py
float target_px
float target_py
float target_vx
float target_vy
uint16_t time_broad
uint16_t timeout
float v_centroid_x
float v_centroid_y
float vx
float vy
Function Documentation
collective_tracking_control()
void collective_tracking_control (void) extern
Definition at line 145 of file ctc.c.
References ctc_con::alpha, AP_MODE_AUTO2, autopilot_get_mode(), before, ctc_control, ctc_first_time, ctc_gogo, CTC_MAX_AC, ctc_send_info_to_nei(), DefaultChannel, DefaultDevice, foo, get_sys_time_msec(), h_ctl_roll_max_setpoint, h_ctl_roll_setpoint, ctc_con::k1, ctc_con::k2, last_info, last_transmision, lateral_mode, LATERAL_MODE_ROLL, moving_target_px, moving_target_py, moving_target_vx, moving_target_vy, msg, ctc_con::omega, p, ctc_con::p_centroid_x, ctc_con::p_centroid_y, parse_ctc_CleanTable(), parse_ctc_NeiInfoTable(), parse_ctc_RegTable(), parse_ctc_TargetInfo(), ctc_con::px, ctc_con::py, ctc_con::ref_px, ctc_con::ref_py, starting_time, stateGetNedToBodyEulers_f(), stateGetPositionEnu_f(), stateGetSpeedEnu_f(), tableNei, ctc_con::target_px, ctc_con::target_py, ctc_con::target_vx, ctc_con::target_vy, FloatEulers::theta, ctc_con::time_broad, timeout, ctc_con::timeout, ctc_con::v_centroid_x, ctc_con::v_centroid_y, ctc_con::vx, ctc_con::vy, EnuCoor_f::x, and EnuCoor_f::y.
Referenced by collective_tracking_point(), collective_tracking_vehicle(), and collective_tracking_waypoint().
collective_tracking_point()
bool collective_tracking_point (float x, float y) extern
Definition at line 133 of file ctc.c.
References collective_tracking_control(), ctc_control, ctc_con::target_px, ctc_con::target_py, ctc_con::target_vx, and ctc_con::target_vy.
collective_tracking_vehicle()
bool collective_tracking_vehicle (void) extern
Definition at line 109 of file ctc.c.
References collective_tracking_control(), ctc_control, moving_target_px, moving_target_py, moving_target_vx, moving_target_vy, ctc_con::target_px, ctc_con::target_py, ctc_con::target_vx, and ctc_con::target_vy.
collective_tracking_waypoint()
bool collective_tracking_waypoint (uint8_t wp) extern
Definition at line 121 of file ctc.c.
References collective_tracking_control(), ctc_control, ctc_con::target_px, ctc_con::target_py, ctc_con::target_vx, ctc_con::target_vy, waypoints, point::x, and point::y.
ctc_init()
void ctc_init (void) extern
Definition at line 97 of file ctc.c.
References CTC_MAX_AC, DefaultPeriodic, foo, register_periodic_telemetry(), send_ctc(), send_ctc_control(), and tableNei.
ctc_send_info_to_nei()
void ctc_send_info_to_nei (void) extern
Referenced by collective_tracking_control().
parse_ctc_CleanTable()
void parse_ctc_CleanTable (uint8_t * buf) extern
Referenced by collective_tracking_control().
parse_ctc_NeiInfoTable()
void parse_ctc_NeiInfoTable (uint8_t * buf) extern
Referenced by collective_tracking_control().
parse_ctc_RegTable()
void parse_ctc_RegTable (uint8_t * buf) extern
Referenced by collective_tracking_control().
parse_ctc_TargetInfo()
void parse_ctc_TargetInfo (uint8_t * buf) extern
Referenced by collective_tracking_control().
Variable Documentation
ctc_control
ctc_con ctc_control extern
Definition at line 77 of file ctc.c.
Referenced by collective_tracking_control(), collective_tracking_point(), collective_tracking_vehicle(), collective_tracking_waypoint(), and send_ctc_control().
ctc_error_to_target
float ctc_error_to_target extern
tableNei
int16_t tableNei[][6] extern
Definition at line 81 of file ctc.c.