Paparazzi UAS: sw/airborne/modules/ctrl/follow_me.h File Reference
follow_me.h File Reference
#include "std.h"
Functions
void follow_me_init (void)
init function
void follow_me_periodic (void)
periodic function
void follow_me_parse_target_pos (uint8_t *buf)
on receiving a TARGET_POS message
void follow_me_set_wp (uint8_t wp_id, float speed)
run function
Variables
float follow_me_distance
distance from the ground gps
float follow_me_height
height from the ground gps
float follow_me_heading
heading direction in which to hover from (automatically set if ground is exceeding speed)
float follow_me_filt
Follow me course sin/cos filter value (higher is harder filter)
float follow_me_diag_speed
Diagonal speed for follow me.
float follow_me_gps_delay
Follow me GPS delay from the relative positionb packet (in ms)
float follow_me_datalink_delay
Follow me datalink delay from the ground GPS packet (in ms)
float follow_me_advance_ms
Follow me waypoint advance time in ms (multiplied by the ground speed)
float follow_me_min_dist
Follow me minimum distance in meters when trying to approach with a certain speed.
float follow_me_min_height
Follow me minimum height in meters when approaching with a speed.
Detailed Description
Author
Freek van Tienen freek.nosp@m..v.t.nosp@m.ienen.nosp@m.@gma.nosp@m.il.co.nosp@m.m Control a rotorcraft to follow at a defined distance from the target
Definition in file follow_me.h.
Function Documentation
follow_me_init()
void follow_me_init (void) extern
init function
Definition at line 87 of file follow_me.c.
References ground_set, ground_time_msec, last_targetpos_valid, moving_wps, and moving_wps_cnt.
follow_me_parse_target_pos()
void follow_me_parse_target_pos (uint8_t * buf) extern
on receiving a TARGET_POS message
Definition at line 147 of file follow_me.c.
References LlaCoor_i::alt, foo, get_sys_time_msec(), ground_climb, ground_course, ground_heading, ground_lla, ground_set, ground_speed, ground_time_msec, LlaCoor_i::lat, and LlaCoor_i::lon.
follow_me_periodic()
void follow_me_periodic (void) extern
periodic function
Definition at line 95 of file follow_me.c.
References DefaultChannel, DefaultDevice, enu_of_lla_point_i(), foo, ground_heading, ground_lla, ground_set, last_targetpos, last_targetpos_heading, last_targetpos_valid, moving_wps, moving_wps_cnt, stateGetNedOrigin_i(), VECT3_COPY, VECT3_DIFF, VECT3_FLOAT_OF_CM, waypoint_get_enu_f(), waypoint_set_enu(), waypoints, EnuCoor_f::x, point::x, and point::y.
follow_me_set_wp()
void follow_me_set_wp (uint8_t wp_id, float speed) extern
run function
should be called in a flight plan stay block using pre_call will only set the x and y position and not the height
ex: <block name="Track Object"> <stay wp="STDBY" pre_call="object_tracking_run(WP_STDBY)"> </block>
Definition at line 170 of file follow_me.c.
References DefaultChannel, DefaultDevice, ENU_OF_TO_NED, follow_me_advance_ms, follow_me_datalink_delay, FOLLOW_ME_DISTANCE, follow_me_distance, follow_me_filt, FOLLOW_ME_GROUND_TIMEOUT, follow_me_heading, FOLLOW_ME_HEIGHT, follow_me_height, follow_me_min_dist, follow_me_min_height, foo, get_sys_time_msec(), ground_course, ground_heading, ground_lla, ground_set, ground_speed, ground_time_msec, State::ned_initialized_i, ned_of_lla_point_i(), state, stateGetNedOrigin_i(), waypoint_set_enu(), waypoints, NedCoor_f::x, point::x, NedCoor_f::y, point::y, and NedCoor_f::z.
Variable Documentation
follow_me_advance_ms
float follow_me_advance_ms extern
Follow me waypoint advance time in ms (multiplied by the ground speed)
Definition at line 69 of file follow_me.c.
Referenced by follow_me_set_wp().
follow_me_datalink_delay
float follow_me_datalink_delay extern
Follow me datalink delay from the ground GPS packet (in ms)
Definition at line 68 of file follow_me.c.
Referenced by follow_me_set_wp().
follow_me_diag_speed
float follow_me_diag_speed extern
Diagonal speed for follow me.
Definition at line 66 of file follow_me.c.
follow_me_distance
float follow_me_distance extern
distance from the ground gps
Definition at line 62 of file follow_me.c.
Referenced by follow_me_set_wp().
follow_me_filt
float follow_me_filt extern
Follow me course sin/cos filter value (higher is harder filter)
Definition at line 65 of file follow_me.c.
Referenced by follow_me_set_wp().
follow_me_gps_delay
float follow_me_gps_delay extern
Follow me GPS delay from the relative positionb packet (in ms)
Definition at line 67 of file follow_me.c.
follow_me_heading
float follow_me_heading extern
heading direction in which to hover from (automatically set if ground is exceeding speed)
Definition at line 64 of file follow_me.c.
Referenced by follow_me_set_wp().
follow_me_height
float follow_me_height extern
height from the ground gps
Definition at line 63 of file follow_me.c.
Referenced by follow_me_set_wp().
follow_me_min_dist
float follow_me_min_dist extern
Follow me minimum distance in meters when trying to approach with a certain speed.
Definition at line 70 of file follow_me.c.
Referenced by follow_me_set_wp().
follow_me_min_height
float follow_me_min_height extern
Follow me minimum height in meters when approaching with a speed.
Definition at line 71 of file follow_me.c.
Referenced by follow_me_set_wp().