Paparazzi UAS: sw/airborne/modules/ctrl/ctrl_windtunnel.h File Reference
ctrl_windtunnel.h File Reference
Windtunnel controller.
#include <std.h>
Data Structures
struct min_max_ctrl_t
Functions
void ctrl_windtunnel_init (void)
void guidance_module_enter (void)
Entering the module (user switched to module)
void guidance_module_run (bool in_flight)
Main guidance loop.
Variables
float ctrl_windtunnel_steptime
struct min_max_ctrl_t ctrl_windtunnel_throttle
struct min_max_ctrl_t ctrl_windtunnel_flaps
Detailed Description
Windtunnel controller.
Implements a controller for the windtunnel which does some step controls
Definition in file ctrl_windtunnel.h.
Data Structure Documentation
min_max_ctrl_t
struct min_max_ctrl_t
Definition at line 33 of file ctrl_windtunnel.h.
Data Fields
float current
float max
float min
float step
Function Documentation
ctrl_windtunnel_init()
void ctrl_windtunnel_init (void) extern
Definition at line 77 of file ctrl_windtunnel.c.
References ctrl_windtunnel, DefaultPeriodic, foo, orientationSetEulers_f(), ctrl_windtunnel_struct::rc_pitch, ctrl_windtunnel_struct::rc_roll, ctrl_windtunnel_struct::rc_throttle, ctrl_windtunnel_struct::rc_yaw, register_periodic_telemetry(), ctrl_windtunnel_struct::rotation, send_windtunnel_meas(), WINDTUNNEL_TO_BODY_PHI, WINDTUNNEL_TO_BODY_PSI, and WINDTUNNEL_TO_BODY_THETA.
guidance_module_enter()
void guidance_module_enter (void) extern
Entering the module (user switched to module)
Entering the module (user switched to module)
Definition at line 77 of file ctrl_module_innerloop_demo.c.
guidance_module_run()
void guidance_module_run (bool in_flight) extern
Main guidance loop.
Parameters
[in] in_flight Whether we are in flight or not
Definition at line 82 of file ctrl_module_innerloop_demo.c.
Variable Documentation
ctrl_windtunnel_flaps
struct min_max_ctrl_t ctrl_windtunnel_flaps extern
Definition at line 55 of file ctrl_windtunnel.c.
Referenced by ctrl_module_run().
ctrl_windtunnel_steptime
float ctrl_windtunnel_steptime extern
Definition at line 53 of file ctrl_windtunnel.c.
Referenced by ctrl_module_run().
ctrl_windtunnel_throttle
struct min_max_ctrl_t ctrl_windtunnel_throttle extern
Definition at line 54 of file ctrl_windtunnel.c.
Referenced by ctrl_module_run().