Paparazzi UAS: sw/airborne/modules/ctrl/ctrl_module_outerloop_demo.c File Reference
ctrl_module_outerloop_demo.c File Reference
example empty controller
#include "modules/ctrl/ctrl_module_outerloop_demo.h"
#include "state.h"
#include "modules/radio_control/radio_control.h"
#include "firmwares/rotorcraft/guidance/guidance_v.h"
#include "firmwares/rotorcraft/stabilization.h"
#include "firmwares/rotorcraft/stabilization/stabilization_attitude.h"
#include "firmwares/rotorcraft/stabilization/stabilization_attitude_rc_setpoint.h"
#include "autopilot.h"
Data Structures
struct ctrl_module_demo_struct
Functions
void ctrl_module_init (void)
void guidance_module_enter (void)
void guidance_module_run (bool in_flight)
Variables
struct ctrl_module_demo_struct ctrl
float comode_time = 0
Detailed Description
example empty controller
Implements an example simple horizontal outerloop controller in a module.
Definition in file ctrl_module_outerloop_demo.c.
Data Structure Documentation
ctrl_module_demo_struct
struct ctrl_module_demo_struct
Definition at line 33 of file ctrl_module_innerloop_demo.c.
Data Fields
struct Int32Eulers cmd
struct AttitudeRCInput rc_sp
int rc_t
int rc_x
int rc_y
int rc_z
Function Documentation
ctrl_module_init()
void ctrl_module_init (void)
Definition at line 55 of file ctrl_module_outerloop_demo.c.
References ctrl, ctrl_module_demo_struct::rc_sp, and stabilization_attitude_rc_setpoint_init().
guidance_module_enter()
void guidance_module_enter (void)
Definition at line 60 of file ctrl_module_outerloop_demo.c.
References autopilot_in_flight(), ctrl_module_demo_struct::cmd, ctrl, guidance_v_mode_changed(), GUIDANCE_V_MODE_HOVER, Int32Eulers::psi, radio_control, ctrl_module_demo_struct::rc_sp, stabilization_attitude_read_rc_setpoint_eulers(), and stateGetNedToBodyEulers_i().
guidance_module_run()
void guidance_module_run (bool in_flight)
Definition at line 72 of file ctrl_module_outerloop_demo.c.
References ANGLE_BFP_OF_REAL, autopilot_in_flight(), Stabilization::cmd, ctrl_module_demo_struct::cmd, ctrl, foo, guidance_v_run(), Int32Eulers::phi, radio_control, ctrl_module_demo_struct::rc_sp, StabilizationSetpoint::sp, ThrustSetpoint::sp, stab_sp_from_eulers_i(), stabilization, stabilization_attitude_read_rc_setpoint_eulers(), stabilization_attitude_run(), and Int32Eulers::theta.
Variable Documentation
comode_time
float comode_time = 0
Definition at line 50 of file ctrl_module_outerloop_demo.c.
ctrl
struct ctrl_module_demo_struct ctrl
Referenced by ctrl_module_init(), guidance_module_enter(), and guidance_module_run().