Paparazzi UAS: sw/airborne/modules/ctrl/ctrl_effectiveness_scheduling.h File Reference
ctrl_effectiveness_scheduling.h File Reference
#include "generated/airframe.h"
#include "firmwares/rotorcraft/stabilization/stabilization_indi.h"
Functions
void ctrl_eff_scheduling_init (void)
Initialises periodic loop;.
void ctrl_eff_scheduling_periodic (void)
Periodic function that interpolates between gain sets depending on the scheduling variable.
void ctrl_eff_scheduling_periodic_a (void)
void ctrl_eff_scheduling_periodic_b (void)
Function Documentation
void ctrl_eff_scheduling_init (void)
Initialises periodic loop;.
Definition at line 52 of file ctrl_effectiveness_scheduling.c.
References g1g2_forward, g1g2_hover, g2_both, and INDI_G_SCALING.
void ctrl_eff_scheduling_periodic (void)
Periodic function that interpolates between gain sets depending on the scheduling variable.
Definition at line 70 of file ctrl_effectiveness_scheduling.c.
References actuator_state_filt_vect, Bwls, ctrl_eff_scheduling_periodic_a(), ctrl_eff_scheduling_periodic_b(), INDI_G_SCALING, radio_control, and RadioControl::values.
void ctrl_eff_scheduling_periodic_a (void)
Definition at line 94 of file ctrl_effectiveness_scheduling.c.
References FLOAT_OF_BFP, g1g2, g1g2_forward, g1g2_hover, INT32_PERCENTAGE_FRAC, and transition_percentage.
Referenced by ctrl_eff_scheduling_periodic().
void ctrl_eff_scheduling_periodic_b (void)
Definition at line 108 of file ctrl_effectiveness_scheduling.c.
References actuator_state_filt_vect, Indi_gains::att, float_eulers_of_quat_zxy(), g1g2, g1g2_hover, indi_gains, FloatRates::q, stateGetAirspeed_f(), stateGetNedToBodyQuat_f(), and FloatEulers::theta.
Referenced by ctrl_eff_scheduling_periodic().