Paparazzi UAS: sw/airborne/modules/computer_vision/cv.h File Reference
cv.h File Reference
Computer vision framework for onboard processing.
#include <pthread.h>
#include "std.h"
#include "peripherals/video_device.h"
#include <BOARD_CONFIG>
Data Structures
struct cv_async
struct video_listener
Typedefs
typedef struct image_t *(* cv_function) (struct image_t *img, uint8_t camera_id)
Functions
bool add_video_device (struct video_config_t *device)
Keep track of video devices added by modules.
struct video_listener * cv_add_to_device (struct video_config_t *device, cv_function func, uint16_t fps, uint8_t id)
struct video_listener * cv_add_to_device_async (struct video_config_t *device, cv_function func, int nice_level, uint16_t fps, uint8_t id)
void cv_run_device (struct video_config_t *device, struct image_t *img)
Detailed Description
Computer vision framework for onboard processing.
Definition in file cv.h.
Data Structure Documentation
cv_async
struct cv_async
Definition at line 41 of file cv.h.
Data Fields
pthread_cond_t img_available
struct image_t img_copy
pthread_mutex_t img_mutex
volatile bool img_processed
pthread_t thread_id
volatile int thread_priority
volatile bool thread_running
video_listener
struct video_listener
Definition at line 51 of file cv.h.
Data Fields
volatile bool active
struct cv_async * async
cv_function func
uint8_t id
uint16_t maximum_fps
struct video_listener * next
struct timeval ts
Typedef Documentation
cv_function
typedef struct image_t *(* cv_function) (struct image_t *img, uint8_t camera_id)
Definition at line 1 of file cv.h.
Function Documentation
add_video_device()
bool add_video_device (struct video_config_t * device) extern
Keep track of video devices added by modules.
Definition at line 197 of file video_thread.c.
References cameras, cameras, video_config_t::dev_name, foo, initialize_camera(), printf_debug, and VIDEO_THREAD_MAX_CAMERAS.
Referenced by cv_add_to_device().
cv_add_to_device()
struct video_listener * cv_add_to_device (struct video_config_t * device, cv_function func, uint16_t fps, uint8_t id) extern
Definition at line 46 of file cv.c.
References add_video_device(), video_config_t::cv_listener, foo, video_listener::func, video_listener::id, listener, and video_listener::next.
Referenced by color_object_detector_init(), colorfilter_init(), cv_add_to_device_async(), cv_blob_locator_init(), detect_contour_init(), detect_gate_init(), detect_window_init(), opencvdemo_init(), opticflow_module_init(), pano_unwrap_init(), qrcode_init(), textons_init(), undistort_image_init(), video_capture_init(), video_usb_logger_start(), and wedgebug_init().
cv_add_to_device_async()
struct video_listener * cv_add_to_device_async (struct video_config_t * device, cv_function func, int nice_level, uint16_t fps, uint8_t id) extern
Definition at line 83 of file cv.c.
References video_listener::async, image_t::buf, image_t::buf_size, cv_add_to_device(), cv_async_thread(), foo, video_listener::func, cv_async::img_available, cv_async::img_copy, cv_async::img_mutex, listener, cv_async::thread_id, and cv_async::thread_priority.
Referenced by bebop_ae_awb_init(), and viewvideo_init().
cv_run_device()
void cv_run_device (struct video_config_t * device, struct image_t * img) extern
Definition at line 178 of file cv.c.
References video_listener::active, video_listener::async, cv_async_function(), video_config_t::cv_listener, foo, video_listener::func, video_listener::id, listener, video_listener::maximum_fps, video_listener::next, timeval_diff(), and video_listener::ts.
Referenced by video_thread_function().