Paparazzi UAS: sw/airborne/modules/computer_vision/cv_georeference.c File Reference
cv_georeference.c File Reference
#include "modules/computer_vision/cv_georeference.h"
#include "math/pprz_trig_int.h"
#include "math/pprz_algebra.h"
#include "math/pprz_algebra_int.h"
#include "state.h"
#include "generated/flight_plan.h"
#include "modules/datalink/downlink.h"
Data Structures
struct georeference_filter_t
struct georeference_t
Functions
void georeference_project (struct camera_frame_t *tar, int wp)
void georeference_filter (bool kalman, int wp, int length)
void georeference_run (void)
void georeference_init (void)
Variables
struct georeference_t geo
int32_t focus_length
Detailed Description
Author
C. De Wagter Geo-reference computer vision detections
Definition in file cv_georeference.c.
Data Structure Documentation
georeference_filter_t
struct georeference_filter_t
Definition at line 36 of file cv_georeference.c.
Data Fields
int32_t P Covariance/Average-count.
struct Int32Vect3 v Target Velocity.
struct Int32Vect3 x Target.
georeference_t
struct georeference_t
Definition at line 42 of file cv_georeference.c.
Data Fields
struct georeference_filter_t filter Filter waypoint location.
struct Int32Vect3 target_i Target in pixels, with z being the focal length in pixels, x=up,y=right,out.
struct Int32Vect3 target_l Target in meters, relative to the drone in LTP frame.
struct Int32Vect3 x_t Target coordinates NED.
Function Documentation
georeference_filter()
void georeference_filter (bool kalman, int wp, int length)
Definition at line 119 of file cv_georeference.c.
References DefaultChannel, DefaultDevice, georeference_t::filter, foo, geo, h(), georeference_filter_t::P, georeference_filter_t::v, VECT3_ADD, VECT3_COPY, VECT3_SDIV, VECT3_SMUL, VECT3_SUB, waypoint_set_xy_i(), Int32Vect3::x, georeference_filter_t::x, georeference_t::x_t, and Int32Vect3::y.
Referenced by cv_blob_locator_event(), and georeference_run().
georeference_init()
void georeference_init (void)
Definition at line 180 of file cv_georeference.c.
References georeference_t::filter, focus_length, geo, INT32_VECT3_ZERO, georeference_filter_t::P, georeference_t::target_i, georeference_t::target_l, georeference_filter_t::v, VECT3_ASSIGN, georeference_filter_t::x, and georeference_t::x_t.
Referenced by cv_blob_locator_init(), cv_blob_locator_start(), start_vision(), start_vision_land(), and stop_vision().
georeference_project()
void georeference_project (struct camera_frame_t * tar, int wp)
Definition at line 53 of file cv_georeference.c.
References DefaultChannel, DefaultDevice, foo, geo, h(), INT32_MAT33_ZERO, int32_rmat_transp_vmult(), INT32_TRIG_FRAC, INT32_VECT3_LSHIFT, MAT33_ELMT, stateGetNedToBodyRMat_i(), stateGetPositionNed_i(), georeference_t::target_i, georeference_t::target_l, VECT3_ASSIGN, waypoint_set_alt_i(), waypoint_set_xy_i(), Int32Vect3::x, NedCoor_i::x, georeference_t::x_t, Int32Vect3::y, NedCoor_i::y, Int32Vect3::z, and NedCoor_i::z.
Referenced by cv_blob_locator_event(), and georeference_run().
georeference_run()
void georeference_run (void)
Definition at line 155 of file cv_georeference.c.
References FALSE, focus_length, foo, georeference_filter(), georeference_project(), and target.
Variable Documentation
focus_length
int32_t focus_length
Definition at line 153 of file cv_georeference.c.
Referenced by georeference_init(), and georeference_run().
geo
struct georeference_t geo
Definition at line 51 of file cv_georeference.c.
Referenced by georeference_filter(), georeference_init(), and georeference_project().