Paparazzi UAS: sw/airborne/modules/computer_vision/cv_blob_locator.h File Reference
cv_blob_locator.h File Reference
#include <stdint.h>
Macros
#define cv_blob_locator_GeoReset(_v)
#define StartVision(X) { start_vision(); false; }
#define StartVisionLand(X) { start_vision_land(); false; }
#define StopVision(X) { stop_vision(); false; }
Functions
void cv_blob_locator_init (void)
void cv_blob_locator_periodic (void)
void cv_blob_locator_event (void)
void cv_blob_locator_start (void)
void cv_blob_locator_stop (void)
void start_vision (void)
void start_vision_land (void)
void stop_vision (void)
Variables
uint8_t color_lum_min
uint8_t color_lum_max
uint8_t color_cb_min
uint8_t color_cb_max
uint8_t color_cr_min
uint8_t color_cr_max
uint8_t cv_blob_locator_reset
uint8_t cv_blob_locator_type
int marker_size
int geofilter_length
int record_video
Detailed Description
Author
C. De Wagter Find a colored item and track its geo-location and update a waypoint to it
Definition in file cv_blob_locator.h.
Macro Definition Documentation
#define cv_blob_locator_GeoReset (_v)
Value:
{       \
    cv_blob_locator_start();                 \
  }
Definition at line 53 of file cv_blob_locator.h.
#define StartVision (X) { start_vision(); false; }
Definition at line 57 of file cv_blob_locator.h.
#define StartVisionLand (X) { start_vision_land(); false; }
Definition at line 58 of file cv_blob_locator.h.
#define StopVision (X) { stop_vision(); false; }
Definition at line 59 of file cv_blob_locator.h.
Function Documentation
void cv_blob_locator_event (void)
Definition at line 264 of file cv_blob_locator.c.
References blob_enabled, blob_locator, cv_blob_locator_type, camera_frame_t::f, FALSE, geofilter_length, georeference_filter(), georeference_project(), camera_frame_t::h, marker_enabled, camera_frame_t::px, camera_frame_t::py, camera_frame_t::w, and window_enabled.
void cv_blob_locator_init (void)
Definition at line 230 of file cv_blob_locator.c.
References BLOB_LOCATOR_FPS, color_cb_max, color_cb_min, color_cr_max, color_cr_min, color_lum_max, color_lum_min, cv_add_to_device(), cv_blob_locator_func(), cv_blob_locator_reset, cv_marker_func(), cv_window_func(), and georeference_init().
void cv_blob_locator_periodic (void)
Definition at line 257 of file cv_blob_locator.c.
void cv_blob_locator_start (void)
Definition at line 316 of file cv_blob_locator.c.
References georeference_init().
void cv_blob_locator_stop (void)
Definition at line 321 of file cv_blob_locator.c.
void start_vision (void)
Definition at line 326 of file cv_blob_locator.c.
References cv_blob_locator_type, georeference_init(), and record_video.
void start_vision_land (void)
Definition at line 332 of file cv_blob_locator.c.
References cv_blob_locator_type, georeference_init(), and record_video.
void stop_vision (void)
Definition at line 338 of file cv_blob_locator.c.
References cv_blob_locator_type, georeference_init(), and record_video.
Variable Documentation
uint8_t color_cb_max
Definition at line 49 of file colorfilter.c.
Referenced by cv_blob_locator_func(), and cv_blob_locator_init().
uint8_t color_cb_min
Definition at line 48 of file colorfilter.c.
Referenced by cv_blob_locator_func(), and cv_blob_locator_init().
uint8_t color_cr_max
Definition at line 51 of file colorfilter.c.
Referenced by cv_blob_locator_func(), and cv_blob_locator_init().
uint8_t color_cr_min
Definition at line 50 of file colorfilter.c.
Referenced by cv_blob_locator_func(), and cv_blob_locator_init().
uint8_t color_lum_max
Definition at line 47 of file colorfilter.c.
Referenced by cv_blob_locator_func(), and cv_blob_locator_init().
uint8_t color_lum_min
Definition at line 46 of file colorfilter.c.
Referenced by cv_blob_locator_func(), and cv_blob_locator_init().
uint8_t cv_blob_locator_reset
Definition at line 47 of file cv_blob_locator.c.
Referenced by cv_blob_locator_init().
uint8_t cv_blob_locator_type
Definition at line 48 of file cv_blob_locator.c.
Referenced by cv_blob_locator_event(), start_vision(), start_vision_land(), and stop_vision().
int geofilter_length
Definition at line 50 of file cv_blob_locator.c.
Referenced by cv_blob_locator_event().
int marker_size
Definition at line 51 of file cv_blob_locator.c.
int record_video
Definition at line 52 of file cv_blob_locator.c.
Referenced by start_vision(), start_vision_land(), and stop_vision().