Paparazzi UAS: sw/airborne/modules/datalink/missionlib/waypoints.h File Reference
waypoints.h File Reference
#include <mavlink/mavlink_types.h>
Functions
void mavlink_wp_message_handler (const mavlink_message_t *msg)
Function Documentation
mavlink_wp_message_handler()
void mavlink_wp_message_handler (const mavlink_message_t * msg) extern
Definition at line 94 of file waypoints.c.
References LlaCoor_i::alt, foo, LlaCoor_i::lat, LlaCoor_i::lon, MAVLINK_DEBUG, mavlink_mission_cancel_timer(), mavlink_mission_set_timer(), mavlink_send_wp(), mavlink_system, MAVLinkSendMessage, mission_mgr, msg, mavlink_mission_mgr::rem_compid, mavlink_mission_mgr::rem_sysid, mavlink_mission_mgr::seq, mavlink_mission_mgr::state, STATE_IDLE, STATE_SEND_ITEM, STATE_SEND_LIST, STATE_WAYPOINT_WRITE_TRANSACTION, stateGetHmslOrigin_i(), waypoint_set_enu(), waypoint_set_lla(), and EnuCoor_f::x.
Referenced by mavlink_mission_message_handler().