Paparazzi UAS: sw/airborne/modules/datalink/missionlib/waypoints.c File Reference
waypoints.c File Reference
Improvement of the missionlib implementation of the waypoint protocol, truly global waypoints are used such that they will not be relocated after you run GeoInit.
#include "modules/datalink/missionlib/waypoints.h"
#include "modules/datalink/missionlib/mission_manager.h"
#include "modules/datalink/mavlink.h"
#include "mavlink/ardupilotmega/mavlink.h"
#include "generated/flight_plan.h"
#include "modules/nav/waypoints.h"
Functions
static void mavlink_send_wp (uint8_t sysid, uint8_t compid, uint16_t seq)
void mavlink_wp_message_handler (const mavlink_message_t *msg)
Detailed Description
Improvement of the missionlib implementation of the waypoint protocol, truly global waypoints are used such that they will not be relocated after you run GeoInit.
Definition in file waypoints.c.
Function Documentation
mavlink_send_wp()
static void mavlink_send_wp (uint8_t sysid, uint8_t compid, uint16_t seq) static
Definition at line 49 of file waypoints.c.
References LlaCoor_i::alt, foo, LlaCoor_i::lat, LlaCoor_i::lon, MAVLINK_DEBUG, MAVLinkSendMessage, seq, waypoint_get_lla(), WaypointAlt, WaypointX, and WaypointY.
Referenced by mavlink_wp_message_handler().
mavlink_wp_message_handler()
void mavlink_wp_message_handler (const mavlink_message_t * msg)
Definition at line 94 of file waypoints.c.
References LlaCoor_i::alt, foo, LlaCoor_i::lat, LlaCoor_i::lon, MAVLINK_DEBUG, mavlink_mission_cancel_timer(), mavlink_mission_set_timer(), mavlink_send_wp(), mavlink_system, MAVLinkSendMessage, mission_mgr, msg, mavlink_mission_mgr::rem_compid, mavlink_mission_mgr::rem_sysid, mavlink_mission_mgr::seq, mavlink_mission_mgr::state, STATE_IDLE, STATE_SEND_ITEM, STATE_SEND_LIST, STATE_WAYPOINT_WRITE_TRANSACTION, stateGetHmslOrigin_i(), waypoint_set_enu(), waypoint_set_lla(), and EnuCoor_f::x.
Referenced by mavlink_mission_message_handler().