Paparazzi UAS: sw/airborne/subsystems/datalink/datalink.c File Reference
datalink.c File Reference
Handling of messages coming from ground and other A/Cs.
#include "datalink.h"
#include "subsystems/datalink/downlink.h"
#include "generated/modules.h"
#include "generated/settings.h"
#include "pprzlink/messages.h"
#include "subsystems/gps.h"
Macros
#define DATALINK_C
#define MODULES_DATALINK_C
Functions
void dl_parse_msg (struct link_device *dev, struct transport_tx *trans, uint8_t *buf)
Should be called when chars are available in dl_buffer.
WEAK void firmware_parse_msg (struct link_device *dev, struct transport_tx *trans, uint8_t *buf)
Firmware specfic msg handler.
Detailed Description
Handling of messages coming from ground and other A/Cs.
Definition in file datalink.c.
Macro Definition Documentation
#define DATALINK_C
Definition at line 28 of file datalink.c.
#define MODULES_DATALINK_C
Definition at line 29 of file datalink.c.
Function Documentation
void dl_parse_msg (struct link_device * dev, struct transport_tx * trans, uint8_t * buf)
Should be called when chars are available in dl_buffer.
Definition at line 56 of file datalink.c.
References DefaultChannel, DefaultDevice, dev, firmware_parse_msg(), gps_inject_data(), IdOfMsg, LED_TOGGLE, parse_rc_3ch_datalink(), parse_rc_4ch_datalink(), and val.
Referenced by DlCheckAndParse().
WEAK void firmware_parse_msg (struct link_device * dev, struct transport_tx * trans, uint8_t * buf)
Firmware specfic msg handler.
NAV
WIND_INFO
Definition at line 193 of file datalink.c.
References LlaCoor_f::alt, UtmCoor_f::alt, dev, UtmCoor_f::east, gps_nb_ovrn, infrared, LlaCoor_f::lat, LlaCoor_f::lon, MOfMM, nav_goto_block(), nav_move_waypoint(), nav_utm_east0, nav_utm_north0, nav_utm_zone0, UtmCoor_f::north, Infrared::pitch, Infrared::roll, SEND_NAVIGATION, stateGetAirspeed_f(), stateSetAirspeed_f(), stateSetHorizontalWindspeed_f(), stateSetVerticalWindspeed_f(), Infrared::top, utm_of_lla_f(), waypoints, point::x, FloatVect2::x, point::y, FloatVect2::y, and UtmCoor_f::zone.
Referenced by dl_parse_msg().