Paparazzi UAS: sw/airborne/modules/digital_cam/dc_ctrl_parrot_mykonos.h File Reference
dc_ctrl_parrot_mykonos.h File Reference
Digital video/photo recorder control for Parrot Mykonos Platform, For others that is: control the camera of the Disco and if one manages to add pimpctl onto a Bebop or Bebop2, should work also on those.
#include "std.h"
#include "math/pprz_geodetic_float.h"
#include "dc.h"
#include <BOARD_CONFIG>
Data Structures
struct Dc_Ctrl_Parrot_Mykonos
Macros
#define dc_ctrl_parrot_mykonos_SendCmd(cmd) dc_ctrl_parrot_mykonos_command(cmd)
Enumerations
enum dc_ctrl_parrot_mykonos_status {
DC_CTRL_PARROT_MYKONOS_NONE , DC_CTRL_PARROT_MYKONOS_RECORD_START , DC_CTRL_PARROT_MYKONOS_RECORD_STOP , DC_CTRL_PARROT_MYKONOS_SHOOT ,
DC_CTRL_PARROT_MYKONOS_STREAM_START , DC_CTRL_PARROT_MYKONOS_STREAM_STOP , DC_CTRL_PARROT_MYKONOS_AUTOSHOOT_START , DC_CTRL_PARROT_MYKONOS_AUTOSHOOT_STOP
}
Functions
void dc_ctrl_parrot_mykonos_init (void)
void dc_ctrl_parrot_mykonos_periodic (void)
void dc_ctrl_parrot_mykonos_autoshoot (void)
void dc_ctrl_parrot_mykonos_autoshoot_start (void)
void dc_ctrl_parrot_mykonos_command (enum dc_ctrl_parrot_mykonos_status cmd)
Variables
struct Dc_Ctrl_Parrot_Mykonos dc_ctrl_parrot_mykonos
Send report.
Detailed Description
Digital video/photo recorder control for Parrot Mykonos Platform, For others that is: control the camera of the Disco and if one manages to add pimpctl onto a Bebop or Bebop2, should work also on those.
Provides the control of the Camera start and stop of video recording, Taking photos and switch video streaming on and off This module starts the camera in standby mode and triggers starting of recording or take a picture. Minimum time between two pictures is 1 second.
Definition in file dc_ctrl_parrot_mykonos.h.
Data Structure Documentation
Dc_Ctrl_Parrot_Mykonos
struct Dc_Ctrl_Parrot_Mykonos
Definition at line 60 of file dc_ctrl_parrot_mykonos.h.
Data Fields
uint32_t autoshoot
struct EnuCoor_f last_shot_pos
uint32_t log_delay
int16_t photo_nr
enum dc_ctrl_parrot_mykonos_status status
uint32_t timer
Macro Definition Documentation
dc_ctrl_parrot_mykonos_SendCmd
#define dc_ctrl_parrot_mykonos_SendCmd (cmd) dc_ctrl_parrot_mykonos_command(cmd)
Definition at line 78 of file dc_ctrl_parrot_mykonos.h.
Enumeration Type Documentation
dc_ctrl_parrot_mykonos_status
enum dc_ctrl_parrot_mykonos_status
Enumerator
DC_CTRL_PARROT_MYKONOS_NONE
DC_CTRL_PARROT_MYKONOS_RECORD_START
DC_CTRL_PARROT_MYKONOS_RECORD_STOP
DC_CTRL_PARROT_MYKONOS_SHOOT
DC_CTRL_PARROT_MYKONOS_STREAM_START
DC_CTRL_PARROT_MYKONOS_STREAM_STOP
DC_CTRL_PARROT_MYKONOS_AUTOSHOOT_START
DC_CTRL_PARROT_MYKONOS_AUTOSHOOT_STOP
Definition at line 49 of file dc_ctrl_parrot_mykonos.h.
Function Documentation
dc_ctrl_parrot_mykonos_autoshoot()
void dc_ctrl_parrot_mykonos_autoshoot (void) extern
Definition at line 280 of file dc_ctrl_parrot_mykonos.c.
References Dc_Ctrl_Parrot_Mykonos::autoshoot, dc_ctrl_parrot_mykonos, DC_CTRL_PARROT_MYKONOS_AUTOSHOOT_DELAY, DC_CTRL_PARROT_MYKONOS_AUTOSHOOT_START, DC_CTRL_PARROT_MYKONOS_AUTOSHOOT_TIMER_OF_DELAY, dc_ctrl_parrot_mykonos_command(), DC_CTRL_PARROT_MYKONOS_SHOOT, foo, Dc_Ctrl_Parrot_Mykonos::last_shot_pos, stateGetPositionEnu_f(), Dc_Ctrl_Parrot_Mykonos::status, VECT2_NORM2, FloatVect2::x, EnuCoor_f::x, and EnuCoor_f::y.
dc_ctrl_parrot_mykonos_autoshoot_start()
void dc_ctrl_parrot_mykonos_autoshoot_start (void) extern
Definition at line 306 of file dc_ctrl_parrot_mykonos.c.
References Dc_Ctrl_Parrot_Mykonos::autoshoot, dc_ctrl_parrot_mykonos, DC_CTRL_PARROT_MYKONOS_AUTOSHOOT_START, and Dc_Ctrl_Parrot_Mykonos::status.
dc_ctrl_parrot_mykonos_command()
void dc_ctrl_parrot_mykonos_command (enum dc_ctrl_parrot_mykonos_status cmd) extern
Definition at line 206 of file dc_ctrl_parrot_mykonos.c.
References dc_ctrl_parrot_mykonos, DC_CTRL_PARROT_MYKONOS_AUTOSHOOT_START, DC_CTRL_PARROT_MYKONOS_AUTOSHOOT_STOP, DC_CTRL_PARROT_MYKONOS_LOG_DELAY, DC_CTRL_PARROT_MYKONOS_RECORD_DELAY, DC_CTRL_PARROT_MYKONOS_RECORD_START, DC_CTRL_PARROT_MYKONOS_RECORD_STOP, DC_CTRL_PARROT_MYKONOS_SHOOT, DC_CTRL_PARROT_MYKONOS_STREAM_START, DC_CTRL_PARROT_MYKONOS_STREAM_STOP, DC_CTRL_PARROT_MYKONOS_TIMER_OF_DELAY, foo, get_sys_time_msec(), Dc_Ctrl_Parrot_Mykonos::last_shot_pos, Dc_Ctrl_Parrot_Mykonos::log_delay, stateGetPositionEnu_f(), Dc_Ctrl_Parrot_Mykonos::status, and Dc_Ctrl_Parrot_Mykonos::timer.
Referenced by dc_ctrl_parrot_mykonos_autoshoot(), dc_ctrl_parrot_mykonos_init(), and dc_ctrl_parrot_mykonos_periodic().
dc_ctrl_parrot_mykonos_init()
void dc_ctrl_parrot_mykonos_init (void) extern
Definition at line 117 of file dc_ctrl_parrot_mykonos.c.
References Dc_Ctrl_Parrot_Mykonos::autoshoot, dc_ctrl_parrot_mykonos, dc_ctrl_parrot_mykonos_command(), DC_CTRL_PARROT_MYKONOS_NONE, DC_CTRL_PARROT_MYKONOS_STREAM_START, foo, Dc_Ctrl_Parrot_Mykonos::log_delay, Dc_Ctrl_Parrot_Mykonos::photo_nr, Dc_Ctrl_Parrot_Mykonos::status, and Dc_Ctrl_Parrot_Mykonos::timer.
dc_ctrl_parrot_mykonos_periodic()
void dc_ctrl_parrot_mykonos_periodic (void) extern
Definition at line 148 of file dc_ctrl_parrot_mykonos.c.
References dc_ctrl_parrot_mykonos, dc_ctrl_parrot_mykonos_command(), DC_CTRL_PARROT_MYKONOS_SHOOT, dc_periodic(), foo, get_sys_time_msec(), Dc_Ctrl_Parrot_Mykonos::log_delay, Dc_Ctrl_Parrot_Mykonos::photo_nr, and Dc_Ctrl_Parrot_Mykonos::timer.
Variable Documentation
dc_ctrl_parrot_mykonos
struct Dc_Ctrl_Parrot_Mykonos dc_ctrl_parrot_mykonos extern
Send report.
Definition at line 115 of file dc_ctrl_parrot_mykonos.c.
Referenced by dc_ctrl_parrot_mykonos_autoshoot(), dc_ctrl_parrot_mykonos_autoshoot_start(), dc_ctrl_parrot_mykonos_command(), dc_ctrl_parrot_mykonos_init(), and dc_ctrl_parrot_mykonos_periodic().