Paparazzi UAS: sw/airborne/modules/multi/dcf/dcf.c File Reference
dcf.c File Reference
#include <math.h>
#include <std.h>
#include "modules/muti/dcf/dcf.h"
#include "modules/datalink/telemetry.h"
#include "modules/nav/common_nav.h"
#include "autopilot.h"
Macros
#define DCF_GAIN_K 10
#define DCF_RADIUS 80
#define DCF_TIMEOUT 1500
#define DCF_BROADTIME 200
Functions
static void send_dcf (struct transport_tx *trans, struct link_device *dev)
void dcf_init (void)
bool distributed_circular (uint8_t wp)
void send_theta_to_nei (void)
void parseRegTable (uint8_t *buf)
void parseThetaTable (uint8_t *buf)
Variables
struct dcf_con dcf_control = {DCF_GAIN_K, DCF_RADIUS, DCF_TIMEOUT, 0, DCF_BROADTIME}
struct dcf_tab dcf_tables
uint32_t last_transmision = 0
Macro Definition Documentation
DCF_BROADTIME
#define DCF_BROADTIME 200
Default broadcasting time
Definition at line 55 of file dcf.c.
DCF_GAIN_K
#define DCF_GAIN_K 10
Default gain k for the algorithm
Definition at line 43 of file dcf.c.
DCF_RADIUS
#define DCF_RADIUS 80
Default radius for the circumference
Definition at line 47 of file dcf.c.
DCF_TIMEOUT
#define DCF_TIMEOUT 1500
Default timeout for the neighbors' information
Definition at line 51 of file dcf.c.
Function Documentation
dcf_init()
void dcf_init (void)
Definition at line 63 of file dcf.c.
References DCF_MAX_NEIGHBORS, dcf_tables, DefaultPeriodic, dcf_tab::error_sigma, foo, register_periodic_telemetry(), send_dcf(), and dcf_tab::tableNei.
distributed_circular()
bool distributed_circular (uint8_t wp)
Definition at line 75 of file dcf.c.
References AP_MODE_AUTO2, autopilot_get_mode(), dcf_con::broadtime, c1, c2, dcf_control, DCF_MAX_NEIGHBORS, dcf_tables, dcf_tab::error_sigma, foo, get_sys_time_msec(), gvf_control, dcf_con::k, dcf_tab::last_theta, last_transmision, nav_gvf_ellipse_XY(), p, dcf_con::radius, gvf_con::s, send_theta_to_nei(), stateGetPositionEnu_f(), t1, dcf_tab::tableNei, dcf_con::theta, timeout, dcf_con::timeout, waypoints, EnuCoor_f::x, point::x, EnuCoor_f::y, and point::y.
parseRegTable()
void parseRegTable (uint8_t * buf)
Definition at line 140 of file dcf.c.
References DCF_MAX_NEIGHBORS, dcf_tables, foo, and dcf_tab::tableNei.
parseThetaTable()
void parseThetaTable (uint8_t * buf)
Definition at line 169 of file dcf.c.
References DCF_MAX_NEIGHBORS, dcf_tables, foo, get_sys_time_msec(), dcf_tab::last_theta, and dcf_tab::tableNei.
send_dcf()
static void send_dcf (struct transport_tx * trans, struct link_device * dev) static
Definition at line 33 of file dcf.c.
References DCF_MAX_NEIGHBORS, dcf_tables, dev, dcf_tab::error_sigma, foo, and dcf_tab::tableNei.
Referenced by dcf_init().
send_theta_to_nei()
void send_theta_to_nei (void)
Definition at line 125 of file dcf.c.
References dcf_control, DCF_MAX_NEIGHBORS, dcf_tables, DefaultChannel, DefaultDevice, foo, msg, dcf_tab::tableNei, and dcf_con::theta.
Referenced by distributed_circular().
Variable Documentation
dcf_control
struct dcf_con dcf_control = {DCF_GAIN_K, DCF_RADIUS, DCF_TIMEOUT, 0, DCF_BROADTIME}
Definition at line 58 of file dcf.c.
Referenced by distributed_circular(), and send_theta_to_nei().
dcf_tables
struct dcf_tab dcf_tables
Definition at line 59 of file dcf.c.
Referenced by dcf_init(), distributed_circular(), parseRegTable(), parseThetaTable(), send_dcf(), and send_theta_to_nei().
last_transmision
uint32_t last_transmision = 0
Definition at line 61 of file dcf.c.
Referenced by distributed_circular().