Paparazzi UAS: sw/airborne/modules/multi/dcf/dcf.h File Reference
dcf.h File Reference
Distributed circular formation algorithm.
#include "std.h"
Data Structures
struct dcf_con
struct dcf_tab
Macros
#define DCF_MAX_NEIGHBORS 4
Functions
void dcf_init (void)
bool distributed_circular (uint8_t wp)
void send_theta_to_nei (void)
void parseRegTable (uint8_t *buf)
void parseThetaTable (uint8_t *buf)
Variables
struct dcf_con dcf_control
struct dcf_tab dcf_tables
Detailed Description
Distributed circular formation algorithm.
Definition in file dcf.h.
Data Structure Documentation
dcf_con
struct dcf_con
Definition at line 37 of file dcf.h.
Data Fields
uint16_t broadtime
float k
float radius
float theta
uint16_t timeout
dcf_tab
struct dcf_tab
Definition at line 47 of file dcf.h.
Data Fields
int16_t error_sigma[DCF_MAX_NEIGHBORS]
uint32_t last_theta[DCF_MAX_NEIGHBORS]
int16_t tableNei[DCF_MAX_NEIGHBORS][4]
Macro Definition Documentation
DCF_MAX_NEIGHBORS
#define DCF_MAX_NEIGHBORS 4
Default number of neighbors per aircraft
Definition at line 34 of file dcf.h.
Function Documentation
dcf_init()
void dcf_init (void) extern
Definition at line 63 of file dcf.c.
References DCF_MAX_NEIGHBORS, dcf_tables, DefaultPeriodic, dcf_tab::error_sigma, foo, register_periodic_telemetry(), send_dcf(), and dcf_tab::tableNei.
distributed_circular()
bool distributed_circular (uint8_t wp) extern
Definition at line 75 of file dcf.c.
References AP_MODE_AUTO2, autopilot_get_mode(), dcf_con::broadtime, c1, c2, dcf_control, DCF_MAX_NEIGHBORS, dcf_tables, dcf_tab::error_sigma, foo, get_sys_time_msec(), gvf_control, dcf_con::k, dcf_tab::last_theta, last_transmision, nav_gvf_ellipse_XY(), p, dcf_con::radius, gvf_con::s, send_theta_to_nei(), stateGetPositionEnu_f(), t1, dcf_tab::tableNei, dcf_con::theta, timeout, dcf_con::timeout, waypoints, EnuCoor_f::x, point::x, EnuCoor_f::y, and point::y.
parseRegTable()
void parseRegTable (uint8_t * buf) extern
Definition at line 140 of file dcf.c.
References DCF_MAX_NEIGHBORS, dcf_tables, foo, and dcf_tab::tableNei.
parseThetaTable()
void parseThetaTable (uint8_t * buf) extern
Definition at line 169 of file dcf.c.
References DCF_MAX_NEIGHBORS, dcf_tables, foo, get_sys_time_msec(), dcf_tab::last_theta, and dcf_tab::tableNei.
send_theta_to_nei()
void send_theta_to_nei (void) extern
Definition at line 125 of file dcf.c.
References dcf_control, DCF_MAX_NEIGHBORS, dcf_tables, DefaultChannel, DefaultDevice, foo, msg, dcf_tab::tableNei, and dcf_con::theta.
Referenced by distributed_circular().
Variable Documentation
dcf_control
struct dcf_con dcf_control extern
Definition at line 58 of file dcf.c.
Referenced by distributed_circular(), and send_theta_to_nei().
dcf_tables
struct dcf_tab dcf_tables extern
Definition at line 59 of file dcf.c.
Referenced by dcf_init(), distributed_circular(), parseRegTable(), parseThetaTable(), send_dcf(), and send_theta_to_nei().