Paparazzi UAS: sw/airborne/modules/decawave/decawave_anchorless_communication.h File Reference
decawave_anchorless_communication.h File Reference
Functions
void decawave_anchorless_communication_init (void)
Initialization functio.
void decawave_anchorless_communication_periodic (void)
This function periodically sends state data over the serial (which is received by the arduino)
void decawave_anchorless_communication_event (void)
Event function currently checks for serial data and whether an update of states is available for a distant drone.
Function Documentation
decawave_anchorless_communication_event()
void decawave_anchorless_communication_event (void) extern
Event function currently checks for serial data and whether an update of states is available for a distant drone.
If these cases are true, then actions are taken.
Definition at line 298 of file decawave_anchorless_communication.c.
References checkStatesUpdated(), foo, and getSerialData().
decawave_anchorless_communication_init()
void decawave_anchorless_communication_init (void) extern
Initialization functio.
Definition at line 272 of file decawave_anchorless_communication.c.
References setNodeStatesFalse(), and UWB_SERIAL_COMM_DIST_NUM_NODES.
decawave_anchorless_communication_periodic()
void decawave_anchorless_communication_periodic (void) extern
This function periodically sends state data over the serial (which is received by the arduino)
Definition at line 283 of file decawave_anchorless_communication.c.
References nodeState::r, sendFloat(), stateGetAccelNed_f(), stateGetBodyRates_f(), stateGetPositionEnu_f(), stateGetSpeedEnu_f(), UWB_SERIAL_COMM_AX, UWB_SERIAL_COMM_AY, UWB_SERIAL_COMM_VX, UWB_SERIAL_COMM_VY, UWB_SERIAL_COMM_YAWR, UWB_SERIAL_COMM_Z, and nodeState::z.