Paparazzi UAS: sw/airborne/modules/dfu_command/dfu_command.c File Reference
dfu_command.c File Reference
#include "modules/dfu_command/dfu_command.h"
#include "mcu_arch.h"
Functions
void dfu_command_event (void)
Variables
static const char dfu_command_str [] = "#\nbl\n"
static int dfu_command_state = 0
Detailed Description
Author
Tom van Dijk Read USB serial for dfu command
The reset_to_dfu() function needs to be implemented for the architecture in use. (sw/airborne/arch/.../mcu_arch.c)
Definition in file dfu_command.c.
Function Documentation
dfu_command_event()
void dfu_command_event (void)
Definition at line 36 of file dfu_command.c.
References dfu_command_state, dfu_command_str, foo, VCOM_check_available(), VCOM_check_free_space(), VCOM_getchar(), and VCOM_peekchar().
Variable Documentation
dfu_command_state
int dfu_command_state = 0 static
Definition at line 34 of file dfu_command.c.
Referenced by dfu_command_event().
dfu_command_str
const char dfu_command_str[] = "#\nbl\n" static
Definition at line 33 of file dfu_command.c.
Referenced by dfu_command_event().