Paparazzi UAS: sw/airborne/modules/dfu_command/dfu_command.h File Reference
dfu_command.h File Reference
#include "mcu_periph/usb_serial.h"
Functions
void dfu_command_event (void)
Detailed Description
Author
Tom van Dijk Read USB serial for dfu command
Definition in file dfu_command.h.
Function Documentation
dfu_command_event()
void dfu_command_event (void)
Definition at line 36 of file dfu_command.c.
References dfu_command_state, dfu_command_str, foo, VCOM_check_available(), VCOM_check_free_space(), VCOM_getchar(), and VCOM_peekchar().