Paparazzi UAS: sw/airborne/modules/relative_localization_filter/discrete_ekf.h File Reference
discrete_ekf.h File Reference
#include "stdlib.h"
#include "string.h"
#include "math.h"
Data Structures
struct discrete_ekf
Macros
#define EKF_N 7
#define EKF_M 6
Functions
void linear_filter (float *X, float dt, float *dX, float **A)
void linear_measure (float *X, float *Y, float **H)
void discrete_ekf_new (struct discrete_ekf *filter)
void discrete_ekf_predict (struct discrete_ekf *filter)
void discrete_ekf_update (struct discrete_ekf *filter, float *y)
Detailed Description
Author
Mario Coppola Discrete Extended Kalman Filter for Relative Localization
Definition in file discrete_ekf.h.
Data Structure Documentation
struct discrete_ekf
Definition at line 36 of file discrete_ekf.h.
Data Fields
float dt
float H[EKF_M][EKF_N]
float Ht[EKF_N][EKF_M]
float P[EKF_N][EKF_N]
float Q[EKF_N][EKF_N]
float R[EKF_M][EKF_M]
float tmp1[EKF_N][EKF_N]
float tmp2[EKF_N][EKF_N]
float tmp3[EKF_N][EKF_N]
float X[EKF_N]
float Xp[EKF_N]
float Zp[EKF_M]
Macro Definition Documentation
#define EKF_M 6
Definition at line 34 of file discrete_ekf.h.
Referenced by c2d(), discrete_ekf_new(), discrete_ekf_no_north_Hx(), discrete_ekf_no_north_new(), discrete_ekf_no_north_update(), discrete_ekf_update(), linear_measure(), and range_msg_callback().
#define EKF_N 7
Definition at line 33 of file discrete_ekf.h.
Referenced by c2d(), discrete_ekf_new(), discrete_ekf_no_north_Fx(), discrete_ekf_no_north_G(), discrete_ekf_no_north_Hx(), discrete_ekf_no_north_new(), discrete_ekf_no_north_predict(), discrete_ekf_no_north_update(), discrete_ekf_predict(), discrete_ekf_update(), linear_filter(), and linear_measure().
Function Documentation
void discrete_ekf_new (struct discrete_ekf * filter)
Definition at line 32 of file discrete_ekf.c.
References discrete_ekf::dt, EKF_M, EKF_N, f, float_mat_diagonal_scal(), float_vect_zero(), MAKE_MATRIX_PTR, discrete_ekf::P, discrete_ekf::Q, discrete_ekf::R, and discrete_ekf::X.
Referenced by range_msg_callback().
void discrete_ekf_predict (struct discrete_ekf * filter)
Definition at line 74 of file discrete_ekf.c.
References discrete_ekf::dt, EKF_N, float_mat_mul(), float_mat_sum(), float_mat_transpose_square(), float_vect_sum(), discrete_ekf::H, linear_filter(), linear_measure(), MAKE_MATRIX_PTR, discrete_ekf::P, discrete_ekf::Q, discrete_ekf::tmp1, discrete_ekf::tmp2, discrete_ekf::tmp3, discrete_ekf::X, discrete_ekf::Xp, and discrete_ekf::Zp.
Referenced by range_msg_callback().
void discrete_ekf_update (struct discrete_ekf * filter, float * y)
Definition at line 113 of file discrete_ekf.c.
References EKF_M, EKF_N, float_mat_diff(), float_mat_invert(), float_mat_mul(), float_mat_sum(), float_mat_transpose(), float_mat_vect_mul(), float_vect_diff(), float_vect_sum(), discrete_ekf::H, discrete_ekf::Ht, MAKE_MATRIX_PTR, discrete_ekf::P, discrete_ekf::R, discrete_ekf::tmp1, discrete_ekf::tmp2, discrete_ekf::tmp3, discrete_ekf::X, discrete_ekf::Xp, and discrete_ekf::Zp.
Referenced by range_msg_callback().
void linear_filter (float * X, float dt, float * dX, float ** A)
Definition at line 148 of file discrete_ekf.c.
References EKF_N, f, float_mat_diagonal_scal(), and float_vect_zero().
Referenced by discrete_ekf_predict().
void linear_measure (float * X, float * Y, float ** H)
Definition at line 164 of file discrete_ekf.c.
References EKF_M, EKF_N, and f.
Referenced by discrete_ekf_predict().