Paparazzi UAS: sw/airborne/modules/datalink/downlink.h File Reference
downlink.h File Reference
Common code for AP and FBW telemetry.
#include <inttypes.h>
#include "generated/airframe.h"
#include "pprzlink/messages.h"
#include "modules/datalink/datalink.h"
#include "modules/datalink/pprz_dl.h"
#include "generated/modules.h"
Macros
#define DefaultChannel DOWNLINK_TRANSPORT
#define DefaultDevice DOWNLINK_DEVICE
Functions
void downlink_init (void)
Detailed Description
Common code for AP and FBW telemetry.
Definition in file downlink.h.
Macro Definition Documentation
DefaultChannel
#define DefaultChannel DOWNLINK_TRANSPORT
Definition at line 41 of file downlink.h.
DefaultDevice
#define DefaultDevice DOWNLINK_DEVICE
Definition at line 45 of file downlink.h.
Function Documentation
downlink_init()
void downlink_init (void) extern
Definition at line 67 of file downlink.c.
References DefaultDevice, DefaultPeriodic, foo, register_periodic_telemetry(), and send_downlink().
Referenced by main_init(), and main_init().