Paparazzi UAS: sw/airborne/arch/chibios/modules/actuators/dshot_rpmCapture.h File Reference
dshot_rpmCapture.h File Reference
#include <ch.h>
#include <hal.h>
#include "mcu_periph/input_capture_arch.h"
#include "mcu_periph/hal_stm32_dma.h"
#include "mcu_periph/timerDmaCache.h"
#include "modules/actuators/esc_dshot_config.h"
#include "mcu_periph/sys_time_arch.h"
Data Structures
struct DshotDmaStreamChan
structure defining dma channel
struct DshotRpmCaptureOneChannelDmaBuffer
DMA capture if (errFrame > 2000) { chSysHalt("p *dshotd.config.dma_capt_cfg.dma_capture"); } buffer.
struct DshotRpmCaptureDmaBuffer
struct DshotRpmCaptureConfig
: DSHOT Rpm Capture Driver configuration structure.
struct DshotRpmCapture
Macros
#define DSHOT_DMA_DATA_LEN 16U
#define DSHOT_DMA_EXTRADATA_LEN 2U
#define DSHOT_CONCAT_CAPTURE_NX(pre, tim, stream, channel) pre ## tim ## stream , pre ## tim ## channel
macro helper to design DMA stream
#define DSHOTS_1STREAM(tim) DSHOT_CONCAT_CAPTURE_NX(STM32_TIM, tim, _CH1_DMA_STREAM, _CH1_DMA_CHANNEL)
#define DSHOTS_2STREAMS(tim)
#define DSHOTS_3STREAMS(tim)
#define DSHOTS_4STREAMS(tim)
Functions
void dshotRpmCaptureStart (DshotRpmCapture *drcp, const DshotRpmCaptureConfig *cfg, stm32_tim_t *timer)
Configures and activates the DSHOT ERPS CAPTURE driver.
void dshotRpmCaptureStop (DshotRpmCapture *drcp)
stop the the DSHOT ERPS CAPTURE driver.
void dshotRpmCatchErps (DshotRpmCapture *drcp)
capture the DSHOT ERPS frame(s) : one frame for each DSHOT_CHANNELS
static uint32_t dshotRpmGetFrame (const DshotRpmCapture *drcp, uint8_t index)
return last collected erps frame
Data Structure Documentation
DshotDmaStreamChan
struct DshotDmaStreamChan
structure defining dma channel
Note
does not apply for DMAMUX MCU
Definition at line 72 of file dshot_rpmCapture.h.
Data Fields
uint8_t channel
uint32_t stream
DshotRpmCaptureOneChannelDmaBuffer
struct DshotRpmCaptureOneChannelDmaBuffer
DMA capture if (errFrame > 2000) { chSysHalt("p *dshotd.config.dma_capt_cfg.dma_capture"); } buffer.
Definition at line 88 of file dshot_rpmCapture.h.
Data Fields
uint16_t buf[DSHOT_DMA_DATA_LEN+DSHOT_DMA_EXTRADATA_LEN]
DshotRpmCaptureDmaBuffer
struct DshotRpmCaptureDmaBuffer
Definition at line 92 of file dshot_rpmCapture.h.
Data Fields
DshotRpmCaptureOneChannelDmaBuffer dma_buf[DSHOT_CHANNELS]
DshotRpmCaptureConfig
struct DshotRpmCaptureConfig
: DSHOT Rpm Capture Driver configuration structure.
Definition at line 99 of file dshot_rpmCapture.h.
Data Fields
DshotRpmCaptureDmaBuffer * dma_capture : pointer to the input capture DMA buffer
Note
: dma_capture must point to DMA compatible memory DCACHE disabled section for F7
DshotDmaStreamChan dma_streams[DSHOT_CHANNELS] : array of DMA stream for each capture channel
GPTDriver * gptd : GPT Driver to manage microseconds timeout
Note
: timeout is too narrow to be managed by RTOS
DshotRpmCapture
struct DshotRpmCapture
Definition at line 124 of file dshot_rpmCapture.h.
Data Fields
TimerDmaCache cache : cache for timer and dma configuration
Note
: cached configuration are restored via memcpy which is faster than field by field setting
const DshotRpmCaptureConfig * config : pointer to configuration structure
Note
: must be valid for the object life
DMAConfig dmaCfgs[DSHOT_CHANNELS] : dma input capture configuration
DMADriver dmads[DSHOT_CHANNELS] : dma input capture drivers
uint32_t erps[DSHOT_CHANNELS] : array of erps frames
TimICConfig icCfg : input capture timer configuration
TimICDriver icd : input capture timer driver
uint32_t rpms[DSHOT_CHANNELS] : array of rpms
Macro Definition Documentation
DSHOT_CONCAT_CAPTURE_NX
#define DSHOT_CONCAT_CAPTURE_NX (pre, tim, stream, channel) pre ## tim ## stream , pre ## tim ## channel
macro helper to design DMA stream
Note
does not apply for DMAMUX MCU
Definition at line 24 of file dshot_rpmCapture.h.
DSHOT_DMA_DATA_LEN
#define DSHOT_DMA_DATA_LEN 16U
Definition at line 15 of file dshot_rpmCapture.h.
DSHOT_DMA_EXTRADATA_LEN
#define DSHOT_DMA_EXTRADATA_LEN 2U
Definition at line 16 of file dshot_rpmCapture.h.
DSHOTS_1STREAM
#define DSHOTS_1STREAM (tim) DSHOT_CONCAT_CAPTURE_NX(STM32_TIM, tim, _CH1_DMA_STREAM, _CH1_DMA_CHANNEL)
Definition at line 25 of file dshot_rpmCapture.h.
DSHOTS_2STREAMS
#define DSHOTS_2STREAMS (tim)
Value:
                             DSHOT_CONCAT_CAPTURE_NX(STM32_TIM, tim, _CH1_DMA_STREAM, _CH1_DMA_CHANNEL), \
                             DSHOT_CONCAT_CAPTURE_NX(STM32_TIM, tim, _CH2_DMA_STREAM, _CH2_DMA_CHANNEL)
Definition at line 26 of file dshot_rpmCapture.h.
DSHOTS_3STREAMS
#define DSHOTS_3STREAMS (tim)
Value:
           DSHOT_CONCAT_CAPTURE_NX(STM32_TIM, tim, _CH1_DMA_STREAM, _CH1_DMA_CHANNEL), \
                 DSHOT_CONCAT_CAPTURE_NX(STM32_TIM, tim, _CH2_DMA_STREAM, _CH2_DMA_CHANNEL), \
                             DSHOT_CONCAT_CAPTURE_NX(STM32_TIM, tim, _CH3_DMA_STREAM, _CH3_DMA_CHANNEL)
Definition at line 28 of file dshot_rpmCapture.h.
DSHOTS_4STREAMS
#define DSHOTS_4STREAMS (tim)
Value:
           DSHOT_CONCAT_CAPTURE_NX(STM32_TIM, tim, _CH1_DMA_STREAM, _CH1_DMA_CHANNEL), \
                 DSHOT_CONCAT_CAPTURE_NX(STM32_TIM, tim, _CH2_DMA_STREAM, _CH2_DMA_CHANNEL), \
                 DSHOT_CONCAT_CAPTURE_NX(STM32_TIM, tim, _CH3_DMA_STREAM, _CH3_DMA_CHANNEL), \
                 DSHOT_CONCAT_CAPTURE_NX(STM32_TIM, tim, _CH4_DMA_STREAM, _CH4_DMA_CHANNEL)
Definition at line 31 of file dshot_rpmCapture.h.
Function Documentation
dshotRpmCaptureStart()
void dshotRpmCaptureStart (DshotRpmCapture * drcp, const DshotRpmCaptureConfig * cfg, stm32_tim_t * timer)
Configures and activates the DSHOT ERPS CAPTURE driver.
Parameters
[in] drcp pointer to the DshotRpmCapture object
[in] cfg pointer to the DshotRpmCaptureConfig object.
[in] timer pointer to the underlying timer (same one used to output control frame) @api
Definition at line 108 of file dshot_rpmCapture.c.
References foo, initCache(), TimICConfig::timer, and timicCfgSkel.
Referenced by dshotStart().
dshotRpmCaptureStop()
void dshotRpmCaptureStop (DshotRpmCapture * drcp)
stop the the DSHOT ERPS CAPTURE driver.
Parameters
[in] drcp pointer to the DshotRpmCapture object @api
Definition at line 124 of file dshot_rpmCapture.c.
References foo, and stopCapture().
Referenced by initCache().
dshotRpmCatchErps()
void dshotRpmCatchErps (DshotRpmCapture * drcp)
capture the DSHOT ERPS frame(s) : one frame for each DSHOT_CHANNELS
Parameters
[in] drcp pointer to the DshotRpmCapture object
Note
synchronous API, when it returns, the erpm data is available @api
Definition at line 149 of file dshot_rpmCapture.c.
References dmaGetTransactionCounter(), dmaStartTransfert(), dmaStopTransfertI(), DSHOT_CHANNELS, DSHOT_DMA_DATA_LEN, DSHOT_DMA_EXTRADATA_LEN, DSHOT_SPEED, foo, msg, processErpsDmaBuffer(), startCapture(), stopCapture(), SWTICH_TO_CAPTURE_BASE_TIMOUT, and timeoutUs.
Referenced by dshotSendFrame().
dshotRpmGetFrame()
static uint32_t dshotRpmGetFrame (const DshotRpmCapture * drcp, uint8_t index) inline static
return last collected erps frame
Parameters
[in] drcp pointer to the DshotRpmCapture object
[in] index index of the channel [1 .. 4] @api
Definition at line 190 of file dshot_rpmCapture.h.
References foo.