Paparazzi UAS: sw/airborne/modules/decawave/dw1000_range_arduino.h File Reference
dw1000_range_arduino.h File Reference
Copyright (C) 2026 Fabien-B fabie.nosp@m.n-b@.nosp@m.githu.nosp@m.b.co.nosp@m.m This file is part of paparazzi.
Functions
void dw1000_range_arduino_init (void)
void dw1000_range_arduino_event (void)
Detailed Description
Copyright (C) 2026 Fabien-B fabie.nosp@m.n-b@.nosp@m.githu.nosp@m.b.co.nosp@m.m This file is part of paparazzi.
See LICENCE file.
Author
Fabien-B fabie.nosp@m.n-b@.nosp@m.githu.nosp@m.b.co.nosp@m.m
Driver to get ranging data from Decawave DW1000 modules connected to Arduino Decawave DW1000 modules (http://www.decawave.com/products/dwm1000-module) are Ultra-Wide-Band devices that can be used for communication and ranging. Especially, using 3 modules as anchors can provide data for a localization system based on trilateration. The DW1000 is using a SPI connection, but an arduino-compatible board can be used with the library https://github.com/thotro/arduino-dw1000 to hyde the low level drivers and provide direct ranging informations.
Definition in file dw1000_range_arduino.h.
Function Documentation
dw1000_range_arduino_event()
void dw1000_range_arduino_event (void) extern
Definition at line 114 of file dw1000_range_arduino.c.
References DW1000RangeArduino::dev, dw1000_range_arduino, dw1000_range_arduino_parse(), foo, uart_char_available(), and uart_getch().
dw1000_range_arduino_init()
void dw1000_range_arduino_init (void) extern
Definition at line 109 of file dw1000_range_arduino.c.
References DW1000RangeArduino::dev, dw1000_range_arduino, and foo.