Paparazzi UAS: sw/airborne/modules/decawave/dw1000_arduino.h File Reference
dw1000_arduino.h File Reference
#include "std.h"
Macros
#define PRIMARY_GPS GPS_DW1000
Functions
void dw1000_arduino_update_ekf_q (float v)
settings handler
void dw1000_arduino_update_ekf_r_dist (float v)
void dw1000_arduino_update_ekf_r_speed (float v)
void dw1000_arduino_init (void)
void dw1000_arduino_periodic (void)
void dw1000_arduino_report (void)
void dw1000_arduino_event (void)
void dw1000_reset_heading_ref (void)
Reset reference heading to current heading AHRS/INS should be aligned before calling this function.
Variables
bool dw1000_use_ekf
enable EKF filtering
float dw1000_ekf_q
process and measurements noise
float dw1000_ekf_r_dist
float dw1000_ekf_r_speed
Detailed Description
Author
Gautier Hattenberger Driver to get ranging data from Decawave DW1000 modules connected to Arduino
Definition in file dw1000_arduino.h.
Macro Definition Documentation
PRIMARY_GPS
#define PRIMARY_GPS GPS_DW1000
Definition at line 55 of file dw1000_arduino.h.
Function Documentation
dw1000_arduino_event()
void dw1000_arduino_event (void) extern
Definition at line 617 of file dw1000_arduino.c.
References dw1000, dw1000_arduino_parse(), foo, process_data(), uart_char_available(), and uart_getch().
dw1000_arduino_init()
void dw1000_arduino_init (void) extern
Definition at line 513 of file dw1000_arduino.c.
References DW1000::anchors, GpsState::cacc, DW1000::ck, GpsState::comp_id, Anchor::distance, dw1000, dw1000_ekf_q, dw1000_ekf_r_dist, dw1000_ekf_r_speed, DW1000_INITIAL_HEADING, DW1000_NB_ANCHORS, DW1000_USE_EKF, dw1000_use_ekf, DW_WAIT_STX, DW1000::ekf_range, ekf_range_init(), DW1000::ekf_running, GpsState::fix, foo, DW1000::gps_dw1000, GPS_DW1000_ID, GPS_FIX_NONE, Anchor::id, ids, DW1000::idx, init_median_filter_f(), DW1000::initial_heading, LlaCoor_i::lat, DW1000::ltp_def, ltp_def_from_lla_i(), DW1000::mf, GpsState::pacc, GpsState::pdop, DW1000::pos, Anchor::pos, pos_x, pos_y, pos_z, DW1000::raw_dist, GpsState::sacc, DW1000::speed, DW1000::state, Anchor::time, trilateration_init(), DW1000::updated, Anchor::updated, EnuCoor_f::x, EnuCoor_f::y, and EnuCoor_f::z.
dw1000_arduino_periodic()
void dw1000_arduino_periodic (void) extern
Definition at line 568 of file dw1000_arduino.c.
References dw1000, dw1000_use_ekf, DW1000::ekf_range, ekf_range_get_pos(), ekf_range_get_speed(), ekf_range_predict(), DW1000::ekf_running, foo, DW1000::gps_dw1000, gps_periodic_check(), log_started, DW1000::pos, pprzLogFile, process_data(), and DW1000::speed.
dw1000_arduino_report()
void dw1000_arduino_report (void) extern
Definition at line 599 of file dw1000_arduino.c.
References DW1000::anchors, DefaultChannel, DefaultDevice, Anchor::distance, dw1000, foo, DW1000::pos, DW1000::raw_dist, DW1000::speed, EnuCoor_f::x, EnuCoor_f::y, and EnuCoor_f::z.
dw1000_arduino_update_ekf_q()
void dw1000_arduino_update_ekf_q (float v) extern
settings handler
Definition at line 630 of file dw1000_arduino.c.
References dw1000, dw1000_ekf_q, dw1000_ekf_r_dist, dw1000_ekf_r_speed, DW1000::ekf_range, and ekf_range_update_noise().
dw1000_arduino_update_ekf_r_dist()
void dw1000_arduino_update_ekf_r_dist (float v) extern
Definition at line 636 of file dw1000_arduino.c.
References dw1000, dw1000_ekf_q, dw1000_ekf_r_dist, dw1000_ekf_r_speed, DW1000::ekf_range, and ekf_range_update_noise().
dw1000_arduino_update_ekf_r_speed()
void dw1000_arduino_update_ekf_r_speed (float v) extern
Definition at line 642 of file dw1000_arduino.c.
References dw1000, dw1000_ekf_q, dw1000_ekf_r_dist, dw1000_ekf_r_speed, DW1000::ekf_range, and ekf_range_update_noise().
dw1000_reset_heading_ref()
void dw1000_reset_heading_ref (void) extern
Reset reference heading to current heading AHRS/INS should be aligned before calling this function.
Definition at line 463 of file dw1000_arduino.c.
References dw1000, foo, DW1000::initial_heading, FloatEulers::psi, and stateGetNedToBodyEulers_f().
Variable Documentation
dw1000_ekf_q
float dw1000_ekf_q extern
process and measurements noise
Definition at line 190 of file dw1000_arduino.c.
Referenced by dw1000_arduino_init(), dw1000_arduino_update_ekf_q(), dw1000_arduino_update_ekf_r_dist(), and dw1000_arduino_update_ekf_r_speed().
dw1000_ekf_r_dist
float dw1000_ekf_r_dist extern
Definition at line 191 of file dw1000_arduino.c.
Referenced by dw1000_arduino_init(), dw1000_arduino_update_ekf_q(), dw1000_arduino_update_ekf_r_dist(), and dw1000_arduino_update_ekf_r_speed().
dw1000_ekf_r_speed
float dw1000_ekf_r_speed extern
Definition at line 192 of file dw1000_arduino.c.
Referenced by dw1000_arduino_init(), dw1000_arduino_update_ekf_q(), dw1000_arduino_update_ekf_r_dist(), and dw1000_arduino_update_ekf_r_speed().
dw1000_use_ekf
bool dw1000_use_ekf extern
enable EKF filtering
Definition at line 189 of file dw1000_arduino.c.
Referenced by check_and_compute_data(), dw1000_arduino_init(), and dw1000_arduino_periodic().