Paparazzi UAS: sw/airborne/modules/e_identification_fr/e_identification_fr.c File Reference
e_identification_fr.c File Reference
#include "modules/e_identification_fr/e_identification_fr.h"
#include "state.h"
#include "mcu_periph/uart.h"
#include "modules/gps/gps.h"
#include "generated/airframe.h"
#include "generated/flight_plan.h"
Macros
#define MAX_BUF_LEN 50
Functions
static int put_lat (uint8_t *buf)
static int put_lon (uint8_t *buf)
static int put_alt (uint8_t *buf)
static int put_horizontal_speed (uint8_t *buf)
static int put_route (uint8_t *buf)
static int put_lat_lon_home (uint8_t *buf)
void e_identification_fr_init ()
void e_identification_fr_periodic ()
if (GpsFixValid() &&e_identification_started)
Variables
static struct uart_periph * dev = &(E_ID_DEV)
bool e_identification_started = false
Detailed Description
Author
Fabien Bonneval Format and send via UART tracking data according to French requirements.
Definition in file e_identification_fr.c.
Macro Definition Documentation
MAX_BUF_LEN
#define MAX_BUF_LEN 50
Definition at line 37 of file e_identification_fr.c.
Function Documentation
e_identification_fr_init()
void e_identification_fr_init (void)
Definition at line 142 of file e_identification_fr.c.
e_identification_fr_periodic()
void e_identification_fr_periodic (void)
Definition at line 147 of file e_identification_fr.c.
References autopilot, autopilot_in_flight(), e_identification_started, and pprz_autopilot::launch.
if()
if (GpsFixValid() && e_identification_started)
Definition at line 159 of file e_identification_fr.c.
References ck_a, ck_b, dev, MAX_BUF_LEN, offset, put_alt(), put_horizontal_speed(), put_lat(), put_lat_lon_home(), put_lon(), put_route(), and uart_put_buffer().
Referenced by airspeed_consistency_periodic().
put_alt()
static int put_alt (uint8_t * buf) static
Definition at line 64 of file e_identification_fr.c.
References E_ID_HMSL, foo, gps, and GpsState::hmsl.
Referenced by if().
put_horizontal_speed()
static int put_horizontal_speed (uint8_t * buf) static
Definition at line 74 of file e_identification_fr.c.
References E_ID_H_SPEED, foo, and stateGetHorizontalSpeedNorm_f().
Referenced by if().
put_lat()
static int put_lat (uint8_t * buf) static
warning! strong dependency over GCC!
Definition at line 43 of file e_identification_fr.c.
References E_ID_LAT, foo, LlaCoor_i::lat, and stateGetPositionLla_i().
Referenced by if().
put_lat_lon_home()
static int put_lat_lon_home (uint8_t * buf) static
Definition at line 99 of file e_identification_fr.c.
References E_ID_LAT_TO, E_ID_LON_TO, UtmCoor_f::east, foo, LLA_BFP_OF_REAL, lla_of_utm_f(), nav_utm_east0, nav_utm_north0, nav_utm_zone0, offset, waypoint_get_lla(), waypoints, point::x, and point::y.
Referenced by if().
put_lon()
static int put_lon (uint8_t * buf) static
Definition at line 54 of file e_identification_fr.c.
References E_ID_LON, foo, LlaCoor_i::lon, and stateGetPositionLla_i().
Referenced by if().
put_route()
static int put_route (uint8_t * buf) static
Definition at line 83 of file e_identification_fr.c.
References E_ID_ROUTE, foo, and stateGetHorizontalSpeedDir_f().
Referenced by if().
Variable Documentation
dev
struct uart_periph* dev = &(E_ID_DEV) static
Definition at line 40 of file e_identification_fr.c.
Referenced by actuators_sbus_send(), actuators_spektrum_send(), actuators_t4_downlink(), actuators_t4_uplink(), actuators_uavcan_send_esc(), adc_msg_send(), air_data_parse_WIND_INFO(), airspeed_ets_downlink(), airspeed_uavcan_downlink(), can_fuelcell_send_telemetry(), configure_isp(), datalink_parse_PING(), debug_vect(), debug_vect(), dl_parse_msg(), DlCheckAndParse(), DownlinkSendWp(), esc32_msg_send(), esc_msg_send(), faulhaber_send_command(), gps_mtk_event(), gps_nmea_event(), gps_sirf_event(), gps_skytraq_event(), gps_ublox_write(), gps_ubx_event(), hott_common_decode_event(), hott_common_init(), if(), ins_event_check_and_handle(), intermcu_dl_repack(), mateksys3901l0x_send_optical_flow(), mavlink_check_and_parse(), ms45xx_downlink(), multi_ranger_boot_device(), nav_parse_BLOCK(), nav_parse_MOVE_WP(), opticflow_telem_send(), pca95xx_configure(), pca95xx_get_input(), pca95xx_init(), pca95xx_set_output(), power_uavcan_send_power_device(), print_hex(), print_hex16(), print_hex32(), print_string(), range_sensor_uavcan_send_lidar(), RdByte(), RdMulti(), rpm_sensor_send_motor(), sbus_common_decode_event(), sbus_common_init(), sdp3x_downlink(), send_accel(), send_accel(), send_accel_raw(), send_accel_scaled(), send_accel_scaled(), send_actuators(), send_ahrs_bias(), send_ahrs_bias(), send_ahrs_quat(), send_ahrs_ref_quat(), send_ahrs_ref_quat(), send_ahrs_ref_quat(), send_ahrs_ref_quat(), send_air_data(), send_airspeed(), send_airspeed_wind_ekf(), send_airspeed_wind_ekf_debug(), send_aligner(), send_alive(), send_alive(), send_amsl(), send_aoa(), send_aoa(), send_approach_moving_target(), send_att(), send_att(), send_att(), send_att(), send_att(), send_att(), send_att(), send_att_full_indi(), send_att_indi(), send_att_ref(), send_att_ref(), send_att_ref(), send_att_ref(), send_attitude(), send_autopilot_version(), send_autopilot_version(), send_baro_bmp_data(), send_baro_raw(), send_batmon(), send_bebop_actuators(), send_bias(), send_bias(), send_bias(), send_bias(), send_bluegiga(), send_body_rates_accel(), send_calibration(), send_calibration(), send_cam(), send_cam(), send_cc2500_ppm(), send_chirp(), send_circle(), send_cloud_sensor_data(), send_commands(), send_commands(), send_ctc(), send_ctc_control(), send_ctl_a(), send_dcf(), send_desired(), send_detect_gate_visual_position(), send_divergence(), send_dl_value(), send_doublet(), send_downlink(), send_dragspeed(), send_eff_mat_g_indi(), send_eff_mat_g_indi_simple(), send_eff_mat_guid_indi_hybrid(), send_eff_mat_guid_oneloop_andi(), send_eff_mat_stab_oneloop_andi(), send_eff_mat_stabilization_andi(), send_energy(), send_estimator(), send_euler(), send_euler(), send_euler(), send_euler(), send_euler(), send_euler(), send_euler_int(), send_external_pose_down(), send_external_pose_down(), send_fbw_status(), send_fbw_status(), send_filter_status(), send_filter_status(), send_filter_status(), send_filter_status(), send_filter_status(), send_filter_status(), send_filter_status(), send_filter_status(), send_filter_status(), send_filter_status(), send_filter_status(), send_fp(), send_fp_min(), send_geo_mag(), send_geo_mag(), send_geo_mag(), send_geo_mag(), send_geo_mag(), send_gh(), send_gps(), send_gps_int(), send_gps_lla(), send_gps_relpos(), send_gps_sol(), send_grid_init(), send_guidance_indi_hybrid(), send_guidance_oneloop_andi(), send_gvf(), send_gvf(), send_gvf_parametric(), send_gyro(), send_gyro(), send_gyro_raw(), send_gyro_scaled(), send_gyro_scaled(), send_hff(), send_hff_debug(), send_hott(), send_hover_loop(), send_href(), send_hybrid_guidance(), send_imu_heater(), send_indi_guidance(), send_ins(), send_ins(), send_ins(), send_ins(), send_ins(), send_ins(), send_ins_ekf2(), send_ins_ekf2_ext(), send_ins_flow(), send_ins_ref(), send_ins_ref(), send_ins_ref(), send_ins_ref(), send_ins_ref(), send_ins_ref(), send_ins_ref(), send_ins_z(), send_ins_z(), send_ins_z(), send_ins_z(), send_ins_z(), send_inv_filter(), send_inv_filter(), send_jevois_mavlink_visual_position(), send_jevois_mavlink_visual_target(), send_mag(), send_mag_current(), send_mag_heading(), send_mag_raw(), send_mag_scaled(), send_minimal_com(), send_mode(), send_motor_mixing(), send_nav(), send_nav_ref(), send_nav_status(), send_nav_status(), send_navdata(), send_obstacle_grid(), send_oneloop_andi(), send_oneloop_debug(), send_optical_flow_hover(), send_parachute(), send_piksi_heartbeat(), send_ppm(), send_quat(), send_quat(), send_rate(), send_rate(), send_rc(), send_relative_localization_data(), send_rotating_wing_state(), send_rotorcraft_rc(), send_sbus(), send_sbus(), send_sdlog_status(), send_secure_link_info(), send_segment(), send_stab_attitude_stabilization_andi(), send_status(), send_status(), send_superbit(), send_survey(), send_survey(), send_svinfo(), send_svinfo_available(), send_svinfo_id(), send_target_pos_info(), send_thumbnails(), send_tune_hover(), send_tune_roll(), send_tune_vert(), send_uart_err(), send_uartx_err(), send_vert_loop(), send_vff(), send_vffe(), send_vn_info(), send_vn_info(), send_vn_info(), send_wave(), send_wind(), send_wind(), send_wind_estimator(), send_wind_info(), send_wind_info_ret(), send_windtunnel_meas(), send_wls_u(), send_wls_u_oneloop(), send_wls_u_stab(), send_wls_u_stabilization_andi(), send_wls_v(), send_wls_v_oneloop(), send_wls_v_stab(), send_wls_v_stabilization_andi(), send_wp_moved(), send_wp_moved(), send_wp_moved(), settings_parse_msg_GET_SETTING(), settings_parse_msg_SETTING(), sonar_adc_send_sonar(), sonar_i2c_send_sonar(), spektrum_uart_check(), temp_adc_downlink(), tfmini_i2c_send_lidar(), tfmini_send_lidar(), tfmini_send_lidar(), thd_lidar_vl53l5cx(), throttle_curve_send_telem(), ubx_header(), ubx_send_1byte(), ubx_send_bytes(), ubx_send_cfg_rst(), ubx_trailer(), v4l2_capture_thread(), v4l2_close(), v4l2_image_free(), v4l2_image_get(), v4l2_image_get_nonblock(), v4l2_init(), v4l2_start_capture(), v4l2_stop_capture(), VL53L1_NonBlocking_ReadMulti(), VL53L1_NonBlocking_WriteMulti(), VL53L1_RdByte(), VL53L1_RdDWord(), VL53L1_RdWord(), VL53L1_ReadMulti(), VL53L1_WrByte(), VL53L1_WrDWord(), VL53L1_WriteMulti(), VL53L1_WrWord(), VL53L1X_BootDevice(), VL53L1X_BootState(), VL53L1X_CheckForDataReady(), VL53L1X_ClearInterrupt(), VL53L1X_GetAmbientPerSpad(), VL53L1X_GetAmbientRate(), VL53L1X_GetDistance(), VL53L1X_GetDistanceMode(), VL53L1X_GetDistanceThresholdHigh(), VL53L1X_GetDistanceThresholdLow(), VL53L1X_GetDistanceThresholdWindow(), VL53L1X_GetInterMeasurementInMs(), VL53L1X_GetInterruptPolarity(), VL53L1X_GetOffset(), VL53L1X_GetRangeStatus(), VL53L1X_GetResult(), VL53L1X_GetROI_XY(), VL53L1X_GetROICenter(), VL53L1X_GetSensorId(), VL53L1X_GetSigmaThreshold(), VL53L1X_GetSignalPerSpad(), VL53L1X_GetSignalRate(), VL53L1X_GetSignalThreshold(), VL53L1X_GetSpadNb(), VL53L1X_GetTimingBudgetInMs(), VL53L1X_GetXtalk(), VL53L1X_NonBlocking_CheckForDataReady(), VL53L1X_NonBlocking_ClearInterrupt(), VL53L1X_NonBlocking_GetDistance(), VL53L1X_NonBlocking_GetRangeStatus(), VL53L1X_NonBlocking_IsIdle(), VL53L1X_NonBlocking_ReadDataEvent(), VL53L1X_NonBlocking_RequestData(), VL53L1X_SensorInit(), VL53L1X_SetDistanceMode(), VL53L1X_SetDistanceThreshold(), VL53L1X_SetI2CAddress(), VL53L1X_SetInterMeasurementInMs(), VL53L1X_SetInterruptPolarity(), VL53L1X_SetOffset(), VL53L1X_SetROI(), VL53L1X_SetROICenter(), VL53L1X_SetSigmaThreshold(), VL53L1X_SetSignalThreshold(), VL53L1X_SetTimingBudgetInMs(), VL53L1X_SetXtalk(), VL53L1X_StartRanging(), VL53L1X_StartTemperatureUpdate(), VL53L1X_StopRanging(), vn200_event(), vn200_read_buffer(), w5100_check_and_parse(), WrByte(), WrMulti(), and xsens_parser_event().
e_identification_started
bool e_identification_started = false
Definition at line 41 of file e_identification_fr.c.
Referenced by e_identification_fr_periodic().