Paparazzi UAS: sw/airborne/modules/ctrl/eff_scheduling_cyfoam.c File Reference
eff_scheduling_cyfoam.c File Reference
#include "modules/ctrl/eff_scheduling_cyfoam.h"
#include "firmwares/rotorcraft/stabilization/stabilization_indi.h"
#include "firmwares/rotorcraft/guidance/guidance_h.h"
#include "generated/airframe.h"
#include "state.h"
#include "modules/radio_control/radio_control.h"
Functions
void eff_scheduling_cyfoam_init (void)
Initialises periodic loop;.
static void eff_scheduling_periodic_a (void)
static void eff_scheduling_periodic_b (void)
void eff_scheduling_cyfoam_periodic (void)
Periodic function that interpolates between gain sets depending on the scheduling variable.
Variables
static float g1g2_forward [INDI_OUTPUTS][INDI_NUM_ACT]
static float g1g2_hover [INDI_OUTPUTS][INDI_NUM_ACT]
static float g2_both [INDI_NUM_ACT] = STABILIZATION_INDI_G2
Function Documentation
eff_scheduling_cyfoam_init()
void eff_scheduling_cyfoam_init (void)
Initialises periodic loop;.
Definition at line 64 of file eff_scheduling_cyfoam.c.
References foo, g1g2_forward, g1g2_hover, g2_both, and INDI_G_SCALING.
eff_scheduling_cyfoam_periodic()
void eff_scheduling_cyfoam_periodic (void)
Periodic function that interpolates between gain sets depending on the scheduling variable.
Definition at line 138 of file eff_scheduling_cyfoam.c.
References actuator_state_filt_vect, Bwls, eff_scheduling_periodic_a(), eff_scheduling_periodic_b(), foo, INDI_G_SCALING, radio_control, and RadioControl::values.
eff_scheduling_periodic_a()
static void eff_scheduling_periodic_a (void) static
Definition at line 82 of file eff_scheduling_cyfoam.c.
References foo, g1g2, g1g2_forward, g1g2_hover, stabilization, and Stabilization::transition_ratio.
Referenced by eff_scheduling_cyfoam_periodic().
eff_scheduling_periodic_b()
static void eff_scheduling_periodic_b (void) static
Definition at line 94 of file eff_scheduling_cyfoam.c.
References actuator_state_filt_vect, Indi_gains::att, eulers_zxy, float_eulers_of_quat_zxy(), foo, g1g2, g1g2_hover, indi_gains, FloatRates::q, stateGetAirspeed_f(), stateGetNedToBodyQuat_f(), FloatEulers::theta, and yaw_eff.
Referenced by eff_scheduling_cyfoam_periodic().
Variable Documentation
g1g2_forward
float g1g2_forward[INDI_OUTPUTS][INDI_NUM_ACT] static
Initial value:
= {
  FWD_G1_ROLL,
  FWD_G1_PITCH,
  FWD_G1_YAW,
  FWD_G1_THRUST
}
Definition at line 43 of file eff_scheduling_cyfoam.c.
Referenced by eff_scheduling_cyfoam_init(), and eff_scheduling_periodic_a().
g1g2_hover
float g1g2_hover[INDI_OUTPUTS][INDI_NUM_ACT] static
Initial value:
= {
  STABILIZATION_INDI_G1_ROLL,
  STABILIZATION_INDI_G1_PITCH,
  STABILIZATION_INDI_G1_YAW,
  STABILIZATION_INDI_G1_THRUST
}
Definition at line 54 of file eff_scheduling_cyfoam.c.
Referenced by eff_scheduling_cyfoam_init(), eff_scheduling_periodic_a(), and eff_scheduling_periodic_b().
g2_both
float g2_both[INDI_NUM_ACT] = STABILIZATION_INDI_G2 static
Definition at line 62 of file eff_scheduling_cyfoam.c.
Referenced by eff_scheduling_cyfoam_init().