Paparazzi UAS: sw/airborne/modules/ctrl/eff_scheduling_falcon.c File Reference
eff_scheduling_falcon.c File Reference
Interpolation of control effectivenss matrix of the Falcon hybrid plane.
#include "modules/ctrl/eff_scheduling_falcon.h"
#include "firmwares/rotorcraft/stabilization/stabilization_indi.h"
#include "firmwares/rotorcraft/guidance/guidance_h.h"
#include "state.h"
#include "modules/datalink/downlink.h"
Macros
#define EFF_SCHEDULING_FALCON_LOW_AIRSPEED 8.0f
Functions
void eff_scheduling_falcon_init (void)
void eff_scheduling_falcon_periodic (void)
void eff_scheduling_falcon_report (void)
Variables
static float g1g2_hover [INDI_OUTPUTS][INDI_NUM_ACT]
Detailed Description
Interpolation of control effectivenss matrix of the Falcon hybrid plane.
Definition in file eff_scheduling_falcon.c.
Macro Definition Documentation
EFF_SCHEDULING_FALCON_LOW_AIRSPEED
#define EFF_SCHEDULING_FALCON_LOW_AIRSPEED 8.0f
Definition at line 35 of file eff_scheduling_falcon.c.
Function Documentation
eff_scheduling_falcon_init()
void eff_scheduling_falcon_init (void)
Definition at line 49 of file eff_scheduling_falcon.c.
References foo, g1g2, g1g2_hover, and INDI_G_SCALING.
eff_scheduling_falcon_periodic()
void eff_scheduling_falcon_periodic (void)
Definition at line 58 of file eff_scheduling_falcon.c.
References EFF_SCHEDULING_FALCON_LOW_AIRSPEED, eulers_zxy, float_eulers_of_quat_zxy(), foo, g1g2, stateGetAirspeed_f(), stateGetNedToBodyQuat_f(), FloatEulers::theta, and yaw_eff.
eff_scheduling_falcon_report()
void eff_scheduling_falcon_report (void) extern
Definition at line 113 of file eff_scheduling_falcon.c.
References DefaultChannel, DefaultDevice, f, foo, and g1g2.
Variable Documentation
g1g2_hover
float g1g2_hover[INDI_OUTPUTS][INDI_NUM_ACT] static
Initial value:
= {
  STABILIZATION_INDI_G1_ROLL,
  STABILIZATION_INDI_G1_PITCH,
  STABILIZATION_INDI_G1_YAW,
  STABILIZATION_INDI_G1_THRUST
}
Definition at line 41 of file eff_scheduling_falcon.c.
Referenced by eff_scheduling_falcon_init().