Paparazzi UAS: sw/airborne/modules/ctrl/eff_scheduling_rotwing_V2.h File Reference
eff_scheduling_rotwing_V2.h File Reference
#include "std.h"
#include "generated/airframe.h"
Data Structures
struct rotwing_eff_sched_param_t
struct rotwing_eff_sched_var_t
struct I
struct F_M_Body
struct wing_model
struct RW_attitude
struct RW_skew
struct RW_Model
Macros
#define EFF_MAT_ROWS_NB 6
#define RW_aX 0
#define RW_aY 1
#define RW_aZ 2
#define RW_aN 0
#define RW_aE 1
#define RW_aD 2
#define RW_ap 3
#define RW_aq 4
#define RW_ar 5
#define EFF_MAT_COLS_NB (COMMANDS_NB_REAL + COMMANDS_NB_VIRTUAL)
#define RW_G_SCALE 1000.0f
#define ZERO_ELE_PPRZ 8000
#define ELE_MIN_AS 8.8
#define ELE_MAX_AS 16.0
Functions
void eff_scheduling_rotwing_init (void)
void eff_scheduling_rotwing_periodic (void)
Variables
float EFF_MAT_RW [EFF_MAT_ROWS_NB][EFF_MAT_COLS_NB]
float G2_RW [EFF_MAT_COLS_NB]
float G1_RW [EFF_MAT_ROWS_NB][EFF_MAT_COLS_NB]
bool airspeed_fake_on
float airspeed_fake
float ele_eff
float roll_eff
float yaw_eff
float ele_min
float rotation_angle_setpoint_deg
int16_t rotation_cmd
float eff_sched_pusher_time
struct RW_Model RW
Detailed Description
Author
Tomaso De Ponti T.M.L.nosp@m..DeP.nosp@m.onti@.nosp@m.tude.nosp@m.lft.n.nosp@m.l The control effectiveness scheduler for the rotating wing drone type
Definition in file eff_scheduling_rotwing_V2.h.
Data Structure Documentation
rotwing_eff_sched_param_t
struct rotwing_eff_sched_param_t
Definition at line 31 of file eff_scheduling_rotwing.h.
Data Fields
float d_rudder_d_pprz
float DMdpprz_hover_pitch[2]
float DMdpprz_hover_roll[2]
float hover_roll_pitch_coef[2]
float hover_roll_roll_coef[2]
float Ixx_body
float Ixx_wing
float Iyy_body
float Iyy_wing
float Izz
float k_aileron
float k_elevator[3]
float k_elevator_deflection[2]
float k_flaperon
float k_lift_fuselage
float k_lift_tail
float k_lift_wing[2]
float k_pusher[2]
float k_rpm_pprz_pusher[3]
float k_rudder[3]
float m
rotwing_eff_sched_var_t
struct rotwing_eff_sched_var_t
Definition at line 56 of file eff_scheduling_rotwing.h.
Data Fields
float airspeed
float airspeed2
float cmd_elevator
float cmd_pusher
float cmd_pusher_scaled
float cmd_T_mean_scaled
float cosr
float cosr2
float cosr3
float Ixx
float Iyy
float pitch_motor_dMdpprz
float roll_motor_dMdpprz
float sinr
float sinr2
float sinr3
float wing_rotation_deg
float wing_rotation_rad
I
struct I
Definition at line 118 of file eff_scheduling_rotwing_V2.h.
Data Fields
float b_xx
float b_yy
float w_xx
float w_yy
float xx
float yy
float zz
F_M_Body
struct F_M_Body
Definition at line 127 of file eff_scheduling_rotwing_V2.h.
Data Fields
float dFdu
float dMdu
float dMdud
float l
wing_model
struct wing_model
Definition at line 134 of file eff_scheduling_rotwing_V2.h.
Data Fields
float dLdtheta
float k0
float k1
float k2
float L
RW_attitude
struct RW_attitude
Definition at line 142 of file eff_scheduling_rotwing_V2.h.
Data Fields
float cphi
float cpsi
float ctheta
float phi
float psi
float sphi
float spsi
float stheta
float theta
RW_skew
struct RW_skew
Definition at line 154 of file eff_scheduling_rotwing_V2.h.
Data Fields
float cosr
float cosr2
float cosr3
float deg
float rad
float sinr
float sinr2
float sinr3
RW_Model
struct RW_Model
Definition at line 164 of file eff_scheduling_rotwing_V2.h.
Data Fields
struct F_M_Body ail
float as
float as2
struct RW_attitude att
struct F_M_Body ele
float ele_pref
struct F_M_Body flp
struct I I
float m
struct F_M_Body mB
struct F_M_Body mF
struct F_M_Body mL
struct F_M_Body mP
struct F_M_Body mR
float P
struct F_M_Body rud
struct RW_skew skew
float T
struct wing_model wing
Macro Definition Documentation
EFF_MAT_COLS_NB
#define EFF_MAT_COLS_NB (COMMANDS_NB_REAL + COMMANDS_NB_VIRTUAL)
Definition at line 47 of file eff_scheduling_rotwing_V2.h.
EFF_MAT_ROWS_NB
#define EFF_MAT_ROWS_NB 6
Definition at line 33 of file eff_scheduling_rotwing_V2.h.
ELE_MAX_AS
#define ELE_MAX_AS 16.0
Definition at line 62 of file eff_scheduling_rotwing_V2.h.
ELE_MIN_AS
#define ELE_MIN_AS 8.8
Definition at line 58 of file eff_scheduling_rotwing_V2.h.
RW_aD
#define RW_aD 2
Definition at line 41 of file eff_scheduling_rotwing_V2.h.
RW_aE
#define RW_aE 1
Definition at line 40 of file eff_scheduling_rotwing_V2.h.
RW_aN
#define RW_aN 0
Definition at line 39 of file eff_scheduling_rotwing_V2.h.
RW_ap
#define RW_ap 3
Definition at line 42 of file eff_scheduling_rotwing_V2.h.
RW_aq
#define RW_aq 4
Definition at line 43 of file eff_scheduling_rotwing_V2.h.
RW_ar
#define RW_ar 5
Definition at line 44 of file eff_scheduling_rotwing_V2.h.
RW_aX
#define RW_aX 0
Definition at line 36 of file eff_scheduling_rotwing_V2.h.
RW_aY
#define RW_aY 1
Definition at line 37 of file eff_scheduling_rotwing_V2.h.
RW_aZ
#define RW_aZ 2
Definition at line 38 of file eff_scheduling_rotwing_V2.h.
RW_G_SCALE
#define RW_G_SCALE 1000.0f
Definition at line 50 of file eff_scheduling_rotwing_V2.h.
ZERO_ELE_PPRZ
#define ZERO_ELE_PPRZ 8000
Definition at line 54 of file eff_scheduling_rotwing_V2.h.
Function Documentation
eff_scheduling_rotwing_init()
void eff_scheduling_rotwing_init (void) extern
Definition at line 218 of file eff_scheduling_rotwing.c.
References rotwing_eff_sched_var_t::airspeed, rotwing_eff_sched_var_t::airspeed2, rotwing_eff_sched_var_t::cmd_elevator, rotwing_eff_sched_var_t::cmd_pusher, rotwing_eff_sched_var_t::cmd_pusher_scaled, rotwing_eff_sched_var_t::cmd_T_mean_scaled, rotwing_eff_sched_var_t::cosr, rotwing_eff_sched_var_t::cosr2, rotwing_eff_sched_param_t::DMdpprz_hover_pitch, rotwing_eff_sched_param_t::DMdpprz_hover_roll, eff_sched_p, eff_sched_var, foo, init_butterworth_2_low_pass(), init_RW_Model(), rotwing_eff_sched_var_t::Ixx, rotwing_eff_sched_param_t::Ixx_body, rotwing_eff_sched_param_t::Ixx_wing, rotwing_eff_sched_var_t::Iyy, rotwing_eff_sched_param_t::Iyy_body, rotwing_eff_sched_param_t::Iyy_wing, rotwing_eff_sched_var_t::pitch_motor_dMdpprz, rotwing_eff_sched_var_t::roll_motor_dMdpprz, rotwing_eff_sched_var_t::sinr, rotwing_eff_sched_var_t::sinr2, rotwing_eff_sched_var_t::sinr3, skew_filt, update_attitude(), wing_position_cb(), wing_position_cb(), wing_position_ev, wing_position_ev, WING_ROTATION_CAN_ROTWING_ID, rotwing_eff_sched_var_t::wing_rotation_deg, and rotwing_eff_sched_var_t::wing_rotation_rad.
eff_scheduling_rotwing_periodic()
void eff_scheduling_rotwing_periodic (void) extern
Definition at line 248 of file eff_scheduling_rotwing.c.
References calc_G1_G2_RW(), eff_scheduling_rotwing_schedule_liftd(), eff_scheduling_rotwing_update_aileron_effectiveness(), eff_scheduling_rotwing_update_airspeed(), eff_scheduling_rotwing_update_cmd(), eff_scheduling_rotwing_update_elevator_effectiveness(), eff_scheduling_rotwing_update_flaperon_effectiveness(), eff_scheduling_rotwing_update_hover_motor_effectiveness(), eff_scheduling_rotwing_update_MMOI(), eff_scheduling_rotwing_update_pusher_effectiveness(), eff_scheduling_rotwing_update_rudder_effectiveness(), eff_scheduling_rotwing_update_wing_angle(), ele_pref_sched(), sum_EFF_MAT_RW(), and update_attitude().
Variable Documentation
airspeed_fake
float airspeed_fake extern
Definition at line 77 of file eff_scheduling_rotwing_V2.c.
Referenced by eff_scheduling_rotwing_update_airspeed().
airspeed_fake_on
bool airspeed_fake_on extern
Definition at line 76 of file eff_scheduling_rotwing_V2.c.
Referenced by eff_scheduling_rotwing_update_airspeed().
EFF_MAT_RW
float EFF_MAT_RW[EFF_MAT_ROWS_NB][EFF_MAT_COLS_NB] extern
Definition at line 69 of file eff_scheduling_rotwing_V2.c.
Referenced by calc_model(), G1G2_oneloop(), send_eff_mat_guid_oneloop_andi(), send_eff_mat_stab_oneloop_andi(), and sum_EFF_MAT_RW().
eff_sched_pusher_time
float eff_sched_pusher_time extern
Definition at line 172 of file eff_scheduling_rotwing.c.
Referenced by stabilization_indi_set_wls_settings().
ele_eff
float ele_eff extern
Definition at line 78 of file eff_scheduling_rotwing_V2.c.
Referenced by calc_G1_G2_RW(), and init_RW_Model().
ele_min
float ele_min extern
Definition at line 81 of file eff_scheduling_rotwing_V2.c.
Referenced by ele_pref_sched(), and oneloop_andi_enter().
G1_RW
float G1_RW[EFF_MAT_ROWS_NB][EFF_MAT_COLS_NB] extern
Definition at line 68 of file eff_scheduling_rotwing_V2.c.
Referenced by calc_G1_G2_RW(), and sum_EFF_MAT_RW().
G2_RW
float G2_RW[EFF_MAT_COLS_NB] extern
Definition at line 67 of file eff_scheduling_rotwing_V2.c.
Referenced by calc_G1_G2_RW(), oneloop_andi_run(), and sum_EFF_MAT_RW().
roll_eff
float roll_eff extern
Definition at line 79 of file eff_scheduling_rotwing_V2.c.
Referenced by init_RW_Model().
rotation_angle_setpoint_deg
float rotation_angle_setpoint_deg extern
rotation_cmd
int16_t rotation_cmd extern
RW
struct RW_Model RW extern
Definition at line 83 of file eff_scheduling_rotwing_V2.c.
Referenced by calc_G1_G2_RW(), calc_model(), eff_scheduling_rotwing_update_airspeed(), eff_scheduling_rotwing_update_wing_angle(), ele_pref_sched(), init_RW_Model(), oneloop_andi_run(), sum_EFF_MAT_RW(), and update_attitude().
yaw_eff
float yaw_eff extern
Definition at line 80 of file eff_scheduling_rotwing_V2.c.
Referenced by eff_scheduling_falcon_periodic(), eff_scheduling_periodic_b(), and init_RW_Model().