Paparazzi UAS: sw/airborne/modules/ctrl/eff_scheduling_falcon.h File Reference
eff_scheduling_falcon.h File Reference
Interpolation of control effectivenss matrix of the Falcon hybrid plane.
Functions
void eff_scheduling_falcon_init (void)
void eff_scheduling_falcon_periodic (void)
void eff_scheduling_falcon_report (void)
Detailed Description
Interpolation of control effectivenss matrix of the Falcon hybrid plane.
Definition in file eff_scheduling_falcon.h.
Function Documentation
eff_scheduling_falcon_init()
void eff_scheduling_falcon_init (void) extern
Definition at line 49 of file eff_scheduling_falcon.c.
References foo, g1g2, g1g2_hover, and INDI_G_SCALING.
eff_scheduling_falcon_periodic()
void eff_scheduling_falcon_periodic (void) extern
Definition at line 58 of file eff_scheduling_falcon.c.
References EFF_SCHEDULING_FALCON_LOW_AIRSPEED, eulers_zxy, float_eulers_of_quat_zxy(), foo, g1g2, stateGetAirspeed_f(), stateGetNedToBodyQuat_f(), FloatEulers::theta, and yaw_eff.
eff_scheduling_falcon_report()
void eff_scheduling_falcon_report (void) extern
Definition at line 113 of file eff_scheduling_falcon.c.
References DefaultChannel, DefaultDevice, f, foo, and g1g2.