Paparazzi UAS: sw/airborne/modules/sensors/encoder_amt22.h File Reference
encoder_amt22.h File Reference
Functions
void encoder_amt22_init (void)
void encoder_amt22_periodic (void)
Detailed Description
Author
Flo&Fab name..nosp@m.surn.nosp@m.ame@e.nosp@m.nac..nosp@m.fr Driver for AMT22 encoder from CUI devices.
Definition in file encoder_amt22.h.
Function Documentation
encoder_amt22_init()
void encoder_amt22_init (void) extern
Definition at line 37 of file encoder_amt22.c.
References amt22, amt22_conf, and amt22_init().
encoder_amt22_periodic()
void encoder_amt22_periodic (void) extern
Definition at line 42 of file encoder_amt22.c.
References amt22, amt22_get_position(), amt22_get_turns(), amt22_periodic(), DefaultChannel, DefaultDevice, f, and foo.