Paparazzi UAS: sw/airborne/modules/sensors/encoder_amt22.c File Reference
encoder_amt22.c File Reference
#include "modules/sensors/encoder_amt22.h"
#include "peripherals/amt22.h"
#include "modules/datalink/downlink.h"
Functions
void encoder_amt22_init (void)
void encoder_amt22_periodic (void)
Variables
static amt22_t amt22
static amt22_config_t amt22_conf
Detailed Description
Author
Flo&Fab name..nosp@m.surn.nosp@m.ame@e.nosp@m.nac..nosp@m.fr Driver for AMT22 encoder from CUI devices.
Definition in file encoder_amt22.c.
Function Documentation
encoder_amt22_init()
void encoder_amt22_init (void)
Definition at line 37 of file encoder_amt22.c.
References amt22, amt22_conf, and amt22_init().
encoder_amt22_periodic()
void encoder_amt22_periodic (void)
Definition at line 42 of file encoder_amt22.c.
References amt22, amt22_get_position(), amt22_get_turns(), amt22_periodic(), DefaultChannel, DefaultDevice, f, and foo.
Variable Documentation
amt22
amt22_t amt22 static
Definition at line 30 of file encoder_amt22.c.
Referenced by encoder_amt22_init(), and encoder_amt22_periodic().
amt22_conf
amt22_config_t amt22_conf static
Initial value:
= {
  .p = &AMT22_SPI_DEV,
  .slave_idx = AMT22_SPI_SLAVE_IDX,
  .type = AMT22_12_SINGLE,
}
Definition at line 31 of file encoder_amt22.c.
Referenced by encoder_amt22_init().