Paparazzi UAS: sw/airborne/arch/chibios/modules/actuators/esc_dshot.c File Reference
esc_dshot.c File Reference
DSHOT driver based on ChibiOS.
#include "modules/actuators/esc_dshot.h"
#include <stdnoreturn.h>
#include <math.h>
#include <string.h>
#include "mcu_periph/sys_time.h"
#include "mcu_periph/sys_time_arch.h"
Macros
#define DSHOT_TELEMETRY_BAUD 115200U
Baudrate of the serial link used for telemetry data Can depend on the ESC, but only 115k have been used so far.
#define DSHOT_BIDIR_EXTENTED_TELEMETRY FALSE
#define DSHOT_TELEMETRY_TIMEOUT_MS 3
Telemetry timeout in ms.
#define PWM_FREQ (STM32_SYSCLK / 2000U)
#define TICKS_PER_PERIOD 1000
Ticks per period that let use any timer: does not care if linked to PCLK1 or PCLK2 tick_per_period will be dynamically calculated after pwm init.
#define DSHOT_BIT0_DUTY_RATIO 373U
#define DSHOT_FREQ (driver->config->speed_khz * 1000U)
#define DSHOT_BIT0_DUTY (driver->bit0Duty)
#define DSHOT_BIT1_DUTY (driver->bit1Duty)
#define TICK_FREQ (PWM_FREQ * TICKS_PER_PERIOD)
#define DSHOT_PWM_PERIOD (TICK_FREQ/DSHOT_FREQ)
#define DCR_DBL ((DSHOT_CHANNELS-1) << 8)
#define DCR_DBA(pwmd) (((uint32_t *) (&pwmd->tim->CCR) - ((uint32_t *) pwmd->tim)))
#define DSHOT_MAX_VALUE ((1U<<11U)-1U)
#define ARRAY_LEN(a) (sizeof(a)/sizeof(a[0]))
#define Min(x, y) (x < y ? x : y)
Functions
static DshotPacket makeDshotPacket (const uint16_t throttle, const bool tlmRequest)
static void setCrc4 (DshotPacket *dp)
static void setDshotPacketThrottle (DshotPacket *const dp, const uint16_t throttle)
static void setDshotPacketTlm (DshotPacket *const dp, const bool tlmRequest)
static void buildDshotDmaBuffer (DSHOTDriver *driver)
static uint8_t updateCrc8 (uint8_t crc, uint8_t crc_seed)
static uint8_t calculateCrc8 (const uint8_t *Buf, const uint8_t BufLen)
static noreturn void dshotTlmRec (void *arg)
static size_t getTimerWidth (const PWMDriver *pwmp)
void dshotStart (DSHOTDriver *driver, const DSHOTConfig *config)
Configures and activates the DSHOT peripheral.
void dshotStop (DSHOTDriver *driver)
stop the DSHOT driver and free the related resources : pwm driver and dma driver.
void dshotSetThrottle (DSHOTDriver *driver, const uint8_t index, const uint16_t throttle)
prepare throttle order for specified ESC
void dshotSendSpecialCommand (DSHOTDriver *driver, const uint8_t index, const dshot_special_commands_t specmd)
send special order to one of the ESC (BHELIX, KISS, ...)
void dshotSendThrottles (DSHOTDriver *driver, const uint16_t throttles[DSHOT_CHANNELS])
send throttle packed order to all of the ESCs
void dshotSendFrame (DSHOTDriver *driver)
send throttle order
uint32_t dshotGetCrcErrorCount (const DSHOTDriver *driver)
return number of telemetry crc error since dshotStart
uint32_t dshotGetTelemetryFrameCount (const DSHOTDriver *driver)
return number of telemetry succesfull frame since dshotStart
DshotTelemetry dshotGetTelemetry (DSHOTDriver *driver, uint32_t index)
return last received telemetry data
Detailed Description
DSHOT driver based on ChibiOS.
Author
Alexandre Bustico @maintainer Gautier Hattenberger gauti.nosp@m.er.h.nosp@m.atten.nosp@m.berg.nosp@m.er@en.nosp@m.ac.f.nosp@m.r
Definition in file esc_dshot.c.
Macro Definition Documentation
ARRAY_LEN
#define ARRAY_LEN (a) (sizeof(a)/sizeof(a[0]))
Definition at line 109 of file esc_dshot.c.
DCR_DBA
#define DCR_DBA (pwmd) (((uint32_t *) (&pwmd->tim->CCR) - ((uint32_t *) pwmd->tim)))
Definition at line 105 of file esc_dshot.c.
DCR_DBL
#define DCR_DBL ((DSHOT_CHANNELS-1) << 8)
Definition at line 103 of file esc_dshot.c.
DSHOT_BIDIR_EXTENTED_TELEMETRY
#define DSHOT_BIDIR_EXTENTED_TELEMETRY FALSE
Definition at line 55 of file esc_dshot.c.
DSHOT_BIT0_DUTY
#define DSHOT_BIT0_DUTY (driver->bit0Duty)
Definition at line 96 of file esc_dshot.c.
DSHOT_BIT0_DUTY_RATIO
#define DSHOT_BIT0_DUTY_RATIO 373U
Definition at line 87 of file esc_dshot.c.
DSHOT_BIT1_DUTY
#define DSHOT_BIT1_DUTY (driver->bit1Duty)
Definition at line 97 of file esc_dshot.c.
DSHOT_FREQ
#define DSHOT_FREQ (driver->config->speed_khz * 1000U)
Definition at line 95 of file esc_dshot.c.
DSHOT_MAX_VALUE
#define DSHOT_MAX_VALUE ((1U<<11U)-1U)
Definition at line 107 of file esc_dshot.c.
DSHOT_PWM_PERIOD
#define DSHOT_PWM_PERIOD (TICK_FREQ/DSHOT_FREQ)
Definition at line 100 of file esc_dshot.c.
DSHOT_TELEMETRY_BAUD
#define DSHOT_TELEMETRY_BAUD 115200U
Baudrate of the serial link used for telemetry data Can depend on the ESC, but only 115k have been used so far.
Definition at line 51 of file esc_dshot.c.
DSHOT_TELEMETRY_TIMEOUT_MS
#define DSHOT_TELEMETRY_TIMEOUT_MS 3
Telemetry timeout in ms.
Definition at line 61 of file esc_dshot.c.
Min
#define Min (x, y) (x < y ? x : y)
Definition at line 110 of file esc_dshot.c.
PWM_FREQ
#define PWM_FREQ (STM32_SYSCLK / 2000U)
Definition at line 72 of file esc_dshot.c.
TICK_FREQ
#define TICK_FREQ (PWM_FREQ * TICKS_PER_PERIOD)
Definition at line 99 of file esc_dshot.c.
TICKS_PER_PERIOD
#define TICKS_PER_PERIOD 1000
Ticks per period that let use any timer: does not care if linked to PCLK1 or PCLK2 tick_per_period will be dynamically calculated after pwm init.
Definition at line 82 of file esc_dshot.c.
Function Documentation
buildDshotDmaBuffer()
static void buildDshotDmaBuffer (DSHOTDriver * driver) static
Definition at line 624 of file esc_dshot.c.
References DSHOTDriver::config, DSHOTConfig::dma_buf, DSHOT_BIT0_DUTY, DSHOT_BIT1_DUTY, DSHOT_BIT_WIDTHS, DSHOT_CHANNELS, DSHOT_PRE_FRAME_SILENT_SYNC_BITS, DSHOTDriver::dshotMotors, foo, getTimerWidth(), DSHOTConfig::pwmp, DshotPacket::rawFrame, and setCrc4().
Referenced by dshotSendFrame().
calculateCrc8()
static uint8_t calculateCrc8 (const uint8_t * Buf, const uint8_t BufLen) static
Definition at line 666 of file esc_dshot.c.
References foo, and updateCrc8().
Referenced by dshotTlmRec().
dshotGetCrcErrorCount()
uint32_t dshotGetCrcErrorCount (const DSHOTDriver * driver)
return number of telemetry crc error since dshotStart
Parameters
[in] driver pointer to the DSHOTDriver object
Returns
number of CRC errors @api
Definition at line 443 of file esc_dshot.c.
References DSHOTDriver::crc_errors.
dshotGetTelemetry()
DshotTelemetry dshotGetTelemetry (DSHOTDriver * driver, uint32_t index)
return last received telemetry data
Parameters
[in] driver pointer to the DSHOTDriver object
[in] index channel : [0..3] or [0..1] depending on driver used
Returns
telemetry structure by copy @api
Definition at line 469 of file esc_dshot.c.
References DSHOT_CHANNEL_FIRST_INDEX, DSHOT_CHANNELS, DSHOTDriver::dshotMotors, DshotPackets::dt, foo, and DshotPackets::tlmMtx.
Referenced by actuators_dshot_arch_commit().
dshotGetTelemetryFrameCount()
uint32_t dshotGetTelemetryFrameCount (const DSHOTDriver * driver)
return number of telemetry succesfull frame since dshotStart
Parameters
[in] driver pointer to the DSHOTDriver object
Returns
number of frames @api
Definition at line 455 of file esc_dshot.c.
References DSHOTDriver::tlm_frame_nb.
dshotSendFrame()
void dshotSendFrame (DSHOTDriver * driver)
send throttle order
Parameters
[in] driver pointer to the DSHOTDriver object
Note
dshotSetXXX api should be called prior to this function @api
Definition at line 405 of file esc_dshot.c.
References buildDshotDmaBuffer(), DSHOTDriver::config, DshotPackets::currentTlmQry, DSHOTConfig::dma_buf, DMA_READY, DSHOTDriver::dmap, dmaTransfert(), DshotPackets::dp, DSHOT_CHANNELS, DSHOT_DMA_BUFFER_SIZE, DSHOTDriver::dshotMotors, dshotRpmCatchErps(), dshotStop(), foo, DSHOTDriver::mb, DshotPackets::onGoingQry, DSHOTConfig::pwmp, setDshotPacketTlm(), DMADriver::state, and DSHOTConfig::tlm_sd.
Referenced by actuators_dshot_arch_commit(), dshotSendSpecialCommand(), and dshotSendThrottles().
dshotSendSpecialCommand()
void dshotSendSpecialCommand (DSHOTDriver * driver, const uint8_t index, const dshot_special_commands_t specmd)
send special order to one of the ESC (BHELIX, KISS, ...)
Parameters
[in] driver pointer to the DSHOTDriver object
[in] index channel : [0..3] or [0..1] depending on driver used
[in] specmd special commands, see enum @api
Definition at line 331 of file esc_dshot.c.
References DSHOTDriver::config, DshotPackets::dp, DSHOT_ALL_MOTORS, DSHOT_CHANNELS, DSHOT_CMD_3D_MODE_OFF, DSHOT_CMD_3D_MODE_ON, DSHOT_CMD_AUDIO_STREAM_MODE_ON_OFF, DSHOT_CMD_BIDIR_EDT_MODE_OFF, DSHOT_CMD_BIDIR_EDT_MODE_ON, DSHOT_CMD_MAX, DSHOT_CMD_SAVE_SETTINGS, DSHOT_CMD_SETTINGS_REQUEST, DSHOT_CMD_SILENT_MODE_ON_OFF, DSHOT_CMD_SPIN_DIRECTION_1, DSHOT_CMD_SPIN_DIRECTION_2, DSHOTDriver::dshotMotors, dshotSendFrame(), foo, setDshotPacketThrottle(), setDshotPacketTlm(), and DSHOTConfig::tlm_sd.
dshotSendThrottles()
void dshotSendThrottles (DSHOTDriver * driver, const uint16_t throttles[DSHOT_CHANNELS])
send throttle packed order to all of the ESCs
Parameters
[in] driver pointer to the DSHOTDriver object
[in] throttle[DSHOT_CHANNELS] [48 .. 2047]
Note
dshotSendFrame is called by this function
telemetry bit is set in turn for each ESC of the ESCs @api
Definition at line 386 of file esc_dshot.c.
References DshotPackets::dp, DSHOT_CHANNELS, DSHOTDriver::dshotMotors, dshotSendFrame(), foo, and setDshotPacketThrottle().
dshotSetThrottle()
void dshotSetThrottle (DSHOTDriver * driver, const uint8_t index, const uint16_t throttle)
prepare throttle order for specified ESC
Parameters
[in] driver pointer to the DSHOTDriver object
[in] index channel : [0..3] or [0..1] depending on driver used
[in] throttle [48 .. 2047]
Note
dshotSendFrame has to be called after using this function
see also dshotSendThrottles @api
Definition at line 302 of file esc_dshot.c.
References DshotPackets::dp, DSHOT_ALL_MOTORS, DSHOT_CHANNEL_FIRST_INDEX, DSHOT_CHANNELS, DSHOT_CMD_MAX, DSHOT_MAX_VALUE, DSHOTDriver::dshotMotors, foo, Min, and setDshotPacketThrottle().
Referenced by actuators_dshot_arch_commit().
dshotStart()
void dshotStart (DSHOTDriver * driver, const DSHOTConfig * config)
Configures and activates the DSHOT peripheral.
Parameters
[in] driver pointer to the DSHOTDriver object
[in] config pointer to the DSHOTConfig object. @api
Definition at line 155 of file esc_dshot.c.
References DSHOTDriver::_mbBuf, ARRAY_LEN, DSHOTDriver::bit0Duty, DSHOTDriver::bit1Duty, DSHOTDriver::config, DSHOTDriver::crc_errors, DshotPackets::currentTlmQry, DCR_DBA, DCR_DBL, DSHOTConfig::dma_buf, DSHOTConfig::dma_channel, DSHOTDriver::dma_conf, DMA_DIR_M2P, DMA_ONESHOT, DSHOTConfig::dma_stream, dmaObjectInit(), DSHOTDriver::dmap, dmaStart(), DshotPackets::dp, DSHOT_BIDIR, DSHOT_BIT0_DUTY_RATIO, DSHOT_CHANNELS, DSHOT_PWM_PERIOD, DSHOT_TELEMETRY_BAUD, DSHOTDriver::dshotMotors, dshotRpmCaptureStart(), dshotTlmRec(), foo, getTimerWidth(), makeDshotPacket(), DSHOTDriver::mb, DshotPackets::onGoingQry, DSHOTDriver::pwm_conf, DSHOTConfig::pwmp, DMAConfig::stream, TICK_FREQ, TICKS_PER_PERIOD, DSHOTDriver::tlm_frame_nb, DSHOTConfig::tlm_sd, and DshotPackets::tlmMtx.
Referenced by actuators_dshot_arch_init().
dshotStop()
void dshotStop (DSHOTDriver * driver)
stop the DSHOT driver and free the related resources : pwm driver and dma driver.
Parameters
[in] driver pointer to the DSHOTDriver object @api
Definition at line 261 of file esc_dshot.c.
References DSHOTDriver::config, DSHOTDriver::dmap, dmaStop(), dmaStopTransfert(), foo, and DSHOTConfig::pwmp.
Referenced by dshotSendFrame().
dshotTlmRec()
static noreturn void dshotTlmRec (void * arg) static
Definition at line 713 of file esc_dshot.c.
References calculateCrc8(), DSHOTDriver::config, DSHOTDriver::crc_errors, DSHOT_TELEMETRY_TIMEOUT_MS, DSHOTDriver::dshotMotors, DshotPackets::dt, foo, idx, DSHOTDriver::mb, DshotPackets::onGoingQry, DSHOTDriver::tlm_frame_nb, DSHOTConfig::tlm_sd, and DshotPackets::tlmMtx.
Referenced by dshotStart().
getTimerWidth()
static size_t getTimerWidth (const PWMDriver * pwmp) static
Definition at line 688 of file esc_dshot.c.
References foo, and STM32_PWM_USE_TIM2.
Referenced by buildDshotDmaBuffer(), and dshotStart().
makeDshotPacket()
static DshotPacket makeDshotPacket (const uint16_t throttle, const bool tlmRequest) static
Definition at line 602 of file esc_dshot.c.
References foo, and setCrc4().
Referenced by dshotStart().
setCrc4()
static void setCrc4 (DshotPacket * dp) static
Definition at line 588 of file esc_dshot.c.
References foo.
Referenced by buildDshotDmaBuffer(), and makeDshotPacket().
setDshotPacketThrottle()
static void setDshotPacketThrottle (DshotPacket *const dp, const uint16_t throttle) inline static
Definition at line 613 of file esc_dshot.c.
Referenced by dshotSendSpecialCommand(), dshotSendThrottles(), and dshotSetThrottle().
setDshotPacketTlm()
static void setDshotPacketTlm (DshotPacket *const dp, const bool tlmRequest) inline static
Definition at line 619 of file esc_dshot.c.
References foo.
Referenced by dshotSendFrame(), and dshotSendSpecialCommand().
updateCrc8()
static uint8_t updateCrc8 (uint8_t crc, uint8_t crc_seed) inline static
Definition at line 654 of file esc_dshot.c.
References foo.
Referenced by calculateCrc8().