Paparazzi UAS: sw/airborne/arch/chibios/modules/actuators/esc_dshot.h File Reference
esc_dshot.h File Reference
DSHOT driver based on ChibiOS.
#include <ch.h>
#include <hal.h>
#include "mcu_periph/hal_stm32_dma.h"
#include "modules/actuators/esc_dshot_config.h"
Data Structures
struct DshotTelemetryFrame
telemetry packed as sent by some KISS ESC
struct DshotTelemetry
telemetry with timestamp
union DshotDmaBuffer
struct DSHOTConfig
DSHOT Driver configuration structure.
union DshotPacket
struct DshotPackets
struct DSHOTDriver
DSHOT driver structure.
union DshotTelemetryFrame.__unnamed7__
struct DshotTelemetryFrame.__unnamed7__.__unnamed9__
struct DshotPacket.__unnamed11__
Macros
#define DSHOT_CHANNEL_FIRST_INDEX 0U
#define DSHOT_BIT_WIDTHS 16U
DMA buffer size and number of channels.
#define DSHOT_PRE_FRAME_SILENT_SYNC_BITS 2U
#define DSHOT_POST_FRAME_SILENT_SYNC_BITS 4U
#define DSHOT_DMA_BUFFER_SIZE
#define DSHOT_BIDIR_ERR_CRC UINT32_MAX
special values returned by dshotGetRpm function
#define DSHOT_BIDIR_TLM_EDT (UINT32_MAX-1U)
#define DSHOT_ALL_MOTORS 255U
special value for index : send order to all channels
Typedefs
typedef struct DSHOTDriver DSHOTDriver
Type of a structure representing an DSHOT driver.
Enumerations
enum dshot_special_commands_t {
DSHOT_CMD_MOTOR_STOP = 0U , DSHOT_CMD_BEACON1 , DSHOT_CMD_BEACON2 , DSHOT_CMD_BEACON3 ,
DSHOT_CMD_BEACON4 , DSHOT_CMD_BEACON5 , DSHOT_CMD_ESC_INFO , DSHOT_CMD_SPIN_DIRECTION_1 ,
DSHOT_CMD_SPIN_DIRECTION_2 , DSHOT_CMD_3D_MODE_OFF , DSHOT_CMD_3D_MODE_ON , DSHOT_CMD_SETTINGS_REQUEST ,
DSHOT_CMD_SAVE_SETTINGS , DSHOT_CMD_BIDIR_EDT_MODE_ON , DSHOT_CMD_BIDIR_EDT_MODE_OFF , DSHOT_CMD_SPIN_DIRECTION_NORMAL = 20U ,
DSHOT_CMD_SPIN_DIRECTION_REVERSED = 21U , DSHOT_CMD_LED0_ON , DSHOT_CMD_LED1_ON , DSHOT_CMD_LED2_ON ,
DSHOT_CMD_LED3_ON , DSHOT_CMD_LED0_OFF , DSHOT_CMD_LED1_OFF , DSHOT_CMD_LED2_OFF ,
DSHOT_CMD_LED3_OFF , DSHOT_CMD_AUDIO_STREAM_MODE_ON_OFF = 30U , DSHOT_CMD_SILENT_MODE_ON_OFF = 31U , DSHOT_CMD_MAX = 47U ,
DSHOT_MIN_THROTTLE
}
DSHOT special commands (0-47) for KISS and BLHELI ESC.
Functions
void dshotStart (DSHOTDriver *driver, const DSHOTConfig *config)
Configures and activates the DSHOT peripheral.
void dshotStop (DSHOTDriver *driver)
stop the DSHOT driver and free the related resources : pwm driver and dma driver.
void dshotSetThrottle (DSHOTDriver *driver, const uint8_t index, const uint16_t throttle)
prepare throttle order for specified ESC
void dshotSendFrame (DSHOTDriver *driver)
send throttle order
void dshotSendThrottles (DSHOTDriver *driver, const uint16_t throttles[DSHOT_CHANNELS])
send throttle packed order to all of the ESCs
void dshotSendSpecialCommand (DSHOTDriver *driver, const uint8_t index, const dshot_special_commands_t specmd)
send special order to one of the ESC (BHELIX, KISS, ...)
uint32_t dshotGetCrcErrorCount (const DSHOTDriver *driver)
return number of telemetry crc error since dshotStart
uint32_t dshotGetTelemetryFrameCount (const DSHOTDriver *driver)
return number of telemetry succesfull frame since dshotStart
DshotTelemetry dshotGetTelemetry (DSHOTDriver *driver, const uint32_t index)
return last received telemetry data
Detailed Description
DSHOT driver based on ChibiOS.
Author
Alexandre Bustico @maintainer Gautier Hattenberger gauti.nosp@m.er.h.nosp@m.atten.nosp@m.berg.nosp@m.er@en.nosp@m.ac.f.nosp@m.r
Definition in file esc_dshot.h.
Data Structure Documentation
DshotTelemetryFrame
struct DshotTelemetryFrame
telemetry packed as sent by some KISS ESC
Note
if other ESC use different binary representation in the future we'll have to add a little bit abstraction here
Definition at line 139 of file esc_dshot.h.
Data Fields
union DshotTelemetryFrame.__unnamed7__ __unnamed__
uint8_t crc8
DshotTelemetry
struct DshotTelemetry
telemetry with timestamp
Definition at line 158 of file esc_dshot.h.
Data Fields
DshotTelemetryFrame frame
uint8_t status
uint8_t stress
systime_t ts
DshotDmaBuffer
union DshotDmaBuffer
Definition at line 166 of file esc_dshot.h.
Data Fields
uint16_t widths16[DSHOT_DMA_BUFFER_SIZE][DSHOT_CHANNELS]
DSHOTConfig
struct DSHOTConfig
DSHOT Driver configuration structure.
Definition at line 182 of file esc_dshot.h.
Data Fields
DshotDmaBuffer * dma_buf dshot dma buffer, should be defined in a non Dcached region
uint8_t dma_channel : dma channel associated with pwm timer used to generate dshot output
uint32_t dma_stream : dma stream associated with pwm timer used to generate dshot output
PWMDriver * pwmp PWM driver that feed up to 4 dshot lines.
uint16_t speed_khz dynamic dshot speed, when speed id not known at compilation
Note
incompatible with BIDIR
SerialDriver * tlm_sd if non null : dshot telemetry serial driver
DshotPacket
union DshotPacket
Definition at line 265 of file esc_dshot.h.
Data Fields
struct DshotPacket.__unnamed11__ __unnamed__
uint16_t rawFrame
DshotPackets
struct DshotPackets
Definition at line 275 of file esc_dshot.h.
Data Fields
uint8_t currentTlmQry
DshotPacket dp[DSHOT_CHANNELS]
DshotTelemetry dt[DSHOT_CHANNELS]
volatile bool onGoingQry
mutex_t tlmMtx[DSHOT_CHANNELS]
DshotTelemetryFrame.__unnamed7__
union DshotTelemetryFrame.__unnamed7__
Definition at line 140 of file esc_dshot.h.
Data Fields
struct DshotTelemetryFrame.__unnamed7__.__unnamed9__ __unnamed__
uint8_t rawData[9]
DshotTelemetryFrame.__unnamed7__.__unnamed9__
struct DshotTelemetryFrame.__unnamed7__.__unnamed9__
Definition at line 141 of file esc_dshot.h.
Data Fields
uint16_t consumption
uint16_t current
uint16_t rpm
uint8_t temp
uint16_t voltage
DshotPacket.__unnamed11__
struct DshotPacket.__unnamed11__
Definition at line 266 of file esc_dshot.h.
Data Fields
uint16_t crc:4
uint16_t telemetryRequest:1
uint16_t throttle:11
Macro Definition Documentation
DSHOT_ALL_MOTORS
#define DSHOT_ALL_MOTORS 255U
special value for index : send order to all channels
Note
could be used as index in dshotSetThrottle and dshotSendSpecialCommand functions
Definition at line 74 of file esc_dshot.h.
DSHOT_BIDIR_ERR_CRC
#define DSHOT_BIDIR_ERR_CRC UINT32_MAX
special values returned by dshotGetRpm function
Note
must be checked after each call to dshotGetRpm
Definition at line 65 of file esc_dshot.h.
DSHOT_BIDIR_TLM_EDT
#define DSHOT_BIDIR_TLM_EDT (UINT32_MAX-1U)
Definition at line 66 of file esc_dshot.h.
DSHOT_BIT_WIDTHS
#define DSHOT_BIT_WIDTHS 16U
DMA buffer size and number of channels.
Definition at line 48 of file esc_dshot.h.
DSHOT_CHANNEL_FIRST_INDEX
#define DSHOT_CHANNEL_FIRST_INDEX 0U
Definition at line 43 of file esc_dshot.h.
DSHOT_DMA_BUFFER_SIZE
#define DSHOT_DMA_BUFFER_SIZE
Value:
               (DSHOT_BIT_WIDTHS + \
               DSHOT_PRE_FRAME_SILENT_SYNC_BITS + \
               DSHOT_POST_FRAME_SILENT_SYNC_BITS )
Definition at line 51 of file esc_dshot.h.
DSHOT_POST_FRAME_SILENT_SYNC_BITS
#define DSHOT_POST_FRAME_SILENT_SYNC_BITS 4U
Definition at line 50 of file esc_dshot.h.
DSHOT_PRE_FRAME_SILENT_SYNC_BITS
#define DSHOT_PRE_FRAME_SILENT_SYNC_BITS 2U
Definition at line 49 of file esc_dshot.h.
Typedef Documentation
DSHOTDriver
typedef struct DSHOTDriver DSHOTDriver
Type of a structure representing an DSHOT driver.
Definition at line 176 of file esc_dshot.h.
Enumeration Type Documentation
dshot_special_commands_t
enum dshot_special_commands_t
DSHOT special commands (0-47) for KISS and BLHELI ESC.
Note
commands 48-2047 are used to send motor power
Enumerator
DSHOT_CMD_MOTOR_STOP
DSHOT_CMD_BEACON1
DSHOT_CMD_BEACON2
DSHOT_CMD_BEACON3
DSHOT_CMD_BEACON4
DSHOT_CMD_BEACON5
DSHOT_CMD_ESC_INFO
DSHOT_CMD_SPIN_DIRECTION_1
DSHOT_CMD_SPIN_DIRECTION_2
DSHOT_CMD_3D_MODE_OFF
DSHOT_CMD_3D_MODE_ON
DSHOT_CMD_SETTINGS_REQUEST
DSHOT_CMD_SAVE_SETTINGS
DSHOT_CMD_BIDIR_EDT_MODE_ON
DSHOT_CMD_BIDIR_EDT_MODE_OFF
DSHOT_CMD_SPIN_DIRECTION_NORMAL
DSHOT_CMD_SPIN_DIRECTION_REVERSED
DSHOT_CMD_LED0_ON
DSHOT_CMD_LED1_ON
DSHOT_CMD_LED2_ON
DSHOT_CMD_LED3_ON
DSHOT_CMD_LED0_OFF
DSHOT_CMD_LED1_OFF
DSHOT_CMD_LED2_OFF
DSHOT_CMD_LED3_OFF
DSHOT_CMD_AUDIO_STREAM_MODE_ON_OFF
DSHOT_CMD_SILENT_MODE_ON_OFF
DSHOT_CMD_MAX
DSHOT_MIN_THROTTLE
Definition at line 102 of file esc_dshot.h.
Function Documentation
dshotGetCrcErrorCount()
uint32_t dshotGetCrcErrorCount (const DSHOTDriver * driver)
return number of telemetry crc error since dshotStart
Parameters
[in] driver pointer to the DSHOTDriver object
Returns
number of CRC errors @api
Definition at line 443 of file esc_dshot.c.
References DSHOTDriver::crc_errors.
dshotGetTelemetry()
DshotTelemetry dshotGetTelemetry (DSHOTDriver * driver, uint32_t index)
return last received telemetry data
Parameters
[in] driver pointer to the DSHOTDriver object
[in] index channel : [0..3] or [0..1] depending on driver used
Returns
telemetry structure by copy @api
Definition at line 469 of file esc_dshot.c.
References DSHOT_CHANNEL_FIRST_INDEX, DSHOT_CHANNELS, DSHOTDriver::dshotMotors, DshotPackets::dt, foo, and DshotPackets::tlmMtx.
Referenced by actuators_dshot_arch_commit().
dshotGetTelemetryFrameCount()
uint32_t dshotGetTelemetryFrameCount (const DSHOTDriver * driver)
return number of telemetry succesfull frame since dshotStart
Parameters
[in] driver pointer to the DSHOTDriver object
Returns
number of frames @api
Definition at line 455 of file esc_dshot.c.
References DSHOTDriver::tlm_frame_nb.
dshotSendFrame()
void dshotSendFrame (DSHOTDriver * driver)
send throttle order
Parameters
[in] driver pointer to the DSHOTDriver object
Note
dshotSetXXX api should be called prior to this function @api
Definition at line 405 of file esc_dshot.c.
References buildDshotDmaBuffer(), DSHOTDriver::config, DshotPackets::currentTlmQry, DSHOTConfig::dma_buf, DMA_READY, DSHOTDriver::dmap, dmaTransfert(), DshotPackets::dp, DSHOT_CHANNELS, DSHOT_DMA_BUFFER_SIZE, DSHOTDriver::dshotMotors, dshotRpmCatchErps(), dshotStop(), foo, DSHOTDriver::mb, DshotPackets::onGoingQry, DSHOTConfig::pwmp, setDshotPacketTlm(), DMADriver::state, and DSHOTConfig::tlm_sd.
Referenced by actuators_dshot_arch_commit(), dshotSendSpecialCommand(), and dshotSendThrottles().
dshotSendSpecialCommand()
void dshotSendSpecialCommand (DSHOTDriver * driver, const uint8_t index, const dshot_special_commands_t specmd)
send special order to one of the ESC (BHELIX, KISS, ...)
Parameters
[in] driver pointer to the DSHOTDriver object
[in] index channel : [0..3] or [0..1] depending on driver used
[in] specmd special commands, see enum @api
Definition at line 331 of file esc_dshot.c.
References DSHOTDriver::config, DshotPackets::dp, DSHOT_ALL_MOTORS, DSHOT_CHANNELS, DSHOT_CMD_3D_MODE_OFF, DSHOT_CMD_3D_MODE_ON, DSHOT_CMD_AUDIO_STREAM_MODE_ON_OFF, DSHOT_CMD_BIDIR_EDT_MODE_OFF, DSHOT_CMD_BIDIR_EDT_MODE_ON, DSHOT_CMD_MAX, DSHOT_CMD_SAVE_SETTINGS, DSHOT_CMD_SETTINGS_REQUEST, DSHOT_CMD_SILENT_MODE_ON_OFF, DSHOT_CMD_SPIN_DIRECTION_1, DSHOT_CMD_SPIN_DIRECTION_2, DSHOTDriver::dshotMotors, dshotSendFrame(), foo, setDshotPacketThrottle(), setDshotPacketTlm(), and DSHOTConfig::tlm_sd.
dshotSendThrottles()
void dshotSendThrottles (DSHOTDriver * driver, const uint16_t throttles[DSHOT_CHANNELS])
send throttle packed order to all of the ESCs
Parameters
[in] driver pointer to the DSHOTDriver object
[in] throttle[DSHOT_CHANNELS] [48 .. 2047]
Note
dshotSendFrame is called by this function
telemetry bit is set in turn for each ESC of the ESCs @api
Definition at line 386 of file esc_dshot.c.
References DshotPackets::dp, DSHOT_CHANNELS, DSHOTDriver::dshotMotors, dshotSendFrame(), foo, and setDshotPacketThrottle().
dshotSetThrottle()
void dshotSetThrottle (DSHOTDriver * driver, const uint8_t index, const uint16_t throttle)
prepare throttle order for specified ESC
Parameters
[in] driver pointer to the DSHOTDriver object
[in] index channel : [0..3] or [0..1] depending on driver used
[in] throttle [48 .. 2047]
Note
dshotSendFrame has to be called after using this function
see also dshotSendThrottles @api
Definition at line 302 of file esc_dshot.c.
References DshotPackets::dp, DSHOT_ALL_MOTORS, DSHOT_CHANNEL_FIRST_INDEX, DSHOT_CHANNELS, DSHOT_CMD_MAX, DSHOT_MAX_VALUE, DSHOTDriver::dshotMotors, foo, Min, and setDshotPacketThrottle().
Referenced by actuators_dshot_arch_commit().
dshotStart()
void dshotStart (DSHOTDriver * driver, const DSHOTConfig * config)
Configures and activates the DSHOT peripheral.
Parameters
[in] driver pointer to the DSHOTDriver object
[in] config pointer to the DSHOTConfig object. @api
Definition at line 155 of file esc_dshot.c.
References DSHOTDriver::_mbBuf, ARRAY_LEN, DSHOTDriver::bit0Duty, DSHOTDriver::bit1Duty, DSHOTDriver::config, DSHOTDriver::crc_errors, DshotPackets::currentTlmQry, DCR_DBA, DCR_DBL, DSHOTConfig::dma_buf, DSHOTConfig::dma_channel, DSHOTDriver::dma_conf, DMA_DIR_M2P, DMA_ONESHOT, DSHOTConfig::dma_stream, dmaObjectInit(), DSHOTDriver::dmap, dmaStart(), DshotPackets::dp, DSHOT_BIDIR, DSHOT_BIT0_DUTY_RATIO, DSHOT_CHANNELS, DSHOT_PWM_PERIOD, DSHOT_TELEMETRY_BAUD, DSHOTDriver::dshotMotors, dshotRpmCaptureStart(), dshotTlmRec(), foo, getTimerWidth(), makeDshotPacket(), DSHOTDriver::mb, DshotPackets::onGoingQry, DSHOTDriver::pwm_conf, DSHOTConfig::pwmp, DMAConfig::stream, TICK_FREQ, TICKS_PER_PERIOD, DSHOTDriver::tlm_frame_nb, DSHOTConfig::tlm_sd, and DshotPackets::tlmMtx.
Referenced by actuators_dshot_arch_init().
dshotStop()
void dshotStop (DSHOTDriver * driver)
stop the DSHOT driver and free the related resources : pwm driver and dma driver.
Parameters
[in] driver pointer to the DSHOTDriver object @api
Definition at line 261 of file esc_dshot.c.
References DSHOTDriver::config, DSHOTDriver::dmap, dmaStop(), dmaStopTransfert(), foo, and DSHOTConfig::pwmp.
Referenced by dshotSendFrame().