Paparazzi UAS: sw/airborne/modules/computer_vision/lib/exif/exif_module.h File Reference
exif_module.h File Reference
Write JPEG images containing EXIF headers with GPS coordinates.
Functions
int write_exif_jpeg (char *filename, const unsigned char *image_jpg, const unsigned int image_jpg_len, const unsigned int image_jpg_x, const unsigned int image_jpg_y)
void push_gps_to_vision (void)
Detailed Description
Write JPEG images containing EXIF headers with GPS coordinates.
Definition in file exif_module.h.
Function Documentation
push_gps_to_vision()
void push_gps_to_vision (void)
Definition at line 38 of file exif_module.c.
References alt_mm, gps, GpsState::hmsl, LlaCoor_i::lat, lat_em7deg, LlaCoor_i::lon, lon_em7deg, and stateGetPositionLla_i().
write_exif_jpeg()
int write_exif_jpeg (char * filename, const unsigned char * image_jpg, const unsigned int image_jpg_len, const unsigned int image_jpg_x, const unsigned int image_jpg_y)
Definition at line 146 of file exif_module.c.
References LlaCoor_i::alt, alt_mm, ASCII_COMMENT, create_tag(), exif_header, exif_header_len, f, FILE_BYTE_ORDER, FILE_COMMENT, foo, image_data_len, image_data_offset, init_tag(), LlaCoor_i::lat, lat_em7deg, LlaCoor_i::lon, and lon_em7deg.
Referenced by save_shot_on_disk(), and video_capture_save().