Paparazzi UAS: sw/airborne/firmwares/fixedwing/fbw_datalink.c File Reference
fbw_datalink.c File Reference
Datalink through FBW (FlyByWire) process/mcu.
#include "firmwares/fixedwing/fbw_datalink.h"
#include "mcu_periph/uart.h"
#include "led.h"
Macros
#define ModemLinkDevice (&(MODEM_LINK).device)
#define AutopilotLinkDevice (&(AUTOPILOT_LINK).device)
Functions
static void autopilot_parse (char c)
static void modem_parse (char c)
void fbw_datalink_periodic (void)
void fbw_datalink_event (void)
Detailed Description
Datalink through FBW (FlyByWire) process/mcu.
So it can decode flight termination modes even when AP is down.
Definition in file fbw_datalink.c.
Macro Definition Documentation
AutopilotLinkDevice
#define AutopilotLinkDevice (&(AUTOPILOT_LINK).device)
Definition at line 35 of file fbw_datalink.c.
ModemLinkDevice
#define ModemLinkDevice (&(MODEM_LINK).device)
Definition at line 34 of file fbw_datalink.c.
Function Documentation
autopilot_parse()
static void autopilot_parse (char c) inline static
Definition at line 37 of file fbw_datalink.c.
References ModemLinkDevice.
Referenced by fbw_datalink_event().
fbw_datalink_event()
void fbw_datalink_event (void)
Definition at line 57 of file fbw_datalink.c.
References autopilot_parse(), AutopilotLinkDevice, foo, LED_ON, modem_parse(), and ModemLinkDevice.
fbw_datalink_periodic()
void fbw_datalink_periodic (void)
Definition at line 47 of file fbw_datalink.c.
References foo, and LED_OFF.
modem_parse()
static void modem_parse (char c) inline static
Definition at line 42 of file fbw_datalink.c.
References AutopilotLinkDevice.
Referenced by fbw_datalink_event().