Paparazzi UAS: sw/airborne/modules/imu/filter_1euro_imu.h File Reference
filter_1euro_imu.h File Reference
#include "std.h"
Data Structures
struct Filter1eImu
Functions
void filter_1euro_imu_init (void)
Init and bindings.
void filter_1euro_imu_reset (float enabled)
settings handlers
void filter_1euro_imu_update_gyro_mincutoff (float mincutoff)
void filter_1euro_imu_update_gyro_beta (float beta)
void filter_1euro_imu_update_gyro_dcutoff (float dcutoff)
void filter_1euro_imu_update_accel_mincutoff (float mincutoff)
void filter_1euro_imu_update_accel_beta (float beta)
void filter_1euro_imu_update_accel_dcutoff (float dcutoff)
Variables
struct Filter1eImu filter_1e_imu
configuration structure
Detailed Description
Author
Gautier Hattenberger gauti.nosp@m.er.h.nosp@m.atten.nosp@m.berg.nosp@m.er@en.nosp@m.ac.f.nosp@m.r Prefiltering for IMU data using 1euro filter
Definition in file filter_1euro_imu.h.
Data Structure Documentation
Filter1eImu
struct Filter1eImu
Definition at line 31 of file filter_1euro_imu.h.
Data Fields
float accel_beta
float accel_dcutoff
float accel_mincutoff
bool enabled
float gyro_beta
float gyro_dcutoff
float gyro_mincutoff
Function Documentation
filter_1euro_imu_init()
void filter_1euro_imu_init (void) extern
Init and bindings.
Definition at line 185 of file filter_1euro_imu.c.
References accel_1e, Filter1eImu::accel_beta, accel_cb(), Filter1eImu::accel_dcutoff, accel_ev, Filter1eImu::accel_mincutoff, Filter1eImu::enabled, filter_1e_imu, FILTER_1EURO_ACCEL_BETA, FILTER_1EURO_ACCEL_DCUTOFF, FILTER_1EURO_ACCEL_MINCUTOFF, FILTER_1EURO_ENABLED, FILTER_1EURO_FREQ, FILTER_1EURO_GYRO_BETA, FILTER_1EURO_GYRO_DCUTOFF, FILTER_1EURO_GYRO_MINCUTOFF, foo, gyro_1e, Filter1eImu::gyro_beta, gyro_cb(), Filter1eImu::gyro_dcutoff, gyro_ev, Filter1eImu::gyro_mincutoff, IMU_F1E_BIND_ID, init_1e_filter(), mag_cb(), and mag_ev.
filter_1euro_imu_reset()
void filter_1euro_imu_reset (float enabled) extern
settings handlers
Definition at line 217 of file filter_1euro_imu.c.
References accel_1e, Filter1eImu::enabled, filter_1e_imu, gyro_1e, and reset_1e_filter().
filter_1euro_imu_update_accel_beta()
void filter_1euro_imu_update_accel_beta (float beta) extern
Definition at line 258 of file filter_1euro_imu.c.
References accel_1e, Filter1eImu::accel_beta, OneEuroFilter::beta, and filter_1e_imu.
filter_1euro_imu_update_accel_dcutoff()
void filter_1euro_imu_update_accel_dcutoff (float dcutoff) extern
Definition at line 266 of file filter_1euro_imu.c.
References accel_1e, Filter1eImu::accel_dcutoff, OneEuroFilter::dcutoff, and filter_1e_imu.
filter_1euro_imu_update_accel_mincutoff()
void filter_1euro_imu_update_accel_mincutoff (float mincutoff) extern
Definition at line 250 of file filter_1euro_imu.c.
References accel_1e, Filter1eImu::accel_mincutoff, filter_1e_imu, and OneEuroFilter::mincutoff.
filter_1euro_imu_update_gyro_beta()
void filter_1euro_imu_update_gyro_beta (float beta) extern
Definition at line 234 of file filter_1euro_imu.c.
References OneEuroFilter::beta, filter_1e_imu, gyro_1e, and Filter1eImu::gyro_beta.
filter_1euro_imu_update_gyro_dcutoff()
void filter_1euro_imu_update_gyro_dcutoff (float dcutoff) extern
Definition at line 242 of file filter_1euro_imu.c.
References OneEuroFilter::dcutoff, filter_1e_imu, gyro_1e, and Filter1eImu::gyro_dcutoff.
filter_1euro_imu_update_gyro_mincutoff()
void filter_1euro_imu_update_gyro_mincutoff (float mincutoff) extern
Definition at line 226 of file filter_1euro_imu.c.
References filter_1e_imu, gyro_1e, Filter1eImu::gyro_mincutoff, and OneEuroFilter::mincutoff.
Variable Documentation
filter_1e_imu
struct Filter1eImu filter_1e_imu extern
configuration structure
Definition at line 86 of file filter_1euro_imu.c.
Referenced by accel_cb(), filter_1euro_imu_init(), filter_1euro_imu_reset(), filter_1euro_imu_update_accel_beta(), filter_1euro_imu_update_accel_dcutoff(), filter_1euro_imu_update_accel_mincutoff(), filter_1euro_imu_update_gyro_beta(), filter_1euro_imu_update_gyro_dcutoff(), filter_1euro_imu_update_gyro_mincutoff(), and gyro_cb().