Paparazzi UAS: sw/airborne/firmwares/fixedwing/autopilot_generated.c File Reference
autopilot_generated.c File Reference
Generated autopilot implementation.
#include "firmwares/fixedwing/autopilot_generated.h"
#include "autopilot.h"
#include "modules/radio_control/radio_control.h"
#include "modules/core/commands.h"
#include "modules/actuators/actuators.h"
#include "modules/core/settings.h"
#include "modules/datalink/telemetry.h"
#include "generated/settings.h"
Macros
#define AUTOPILOT_CORE_AP_C
Functions
void autopilot_generated_init (void)
void autopilot_generated_periodic (void)
void autopilot_generated_SetModeHandler (float mode)
AP mode setting handler.
void autopilot_generated_set_mode (uint8_t new_autopilot_mode)
void autopilot_generated_set_motors_on (bool motors_on)
void autopilot_generated_on_rc_frame (void)
Detailed Description
Generated autopilot implementation.
Definition in file autopilot_generated.c.
Macro Definition Documentation
AUTOPILOT_CORE_AP_C
#define AUTOPILOT_CORE_AP_C
Definition at line 27 of file autopilot_generated.c.
Function Documentation
autopilot_generated_init()
void autopilot_generated_init (void)
Definition at line 41 of file autopilot_generated.c.
References autopilot, foo, and pprz_autopilot::mode.
Referenced by autopilot_init().
autopilot_generated_on_rc_frame()
void autopilot_generated_on_rc_frame (void)
Definition at line 92 of file autopilot_generated.c.
References commands, foo, radio_control, radio_control_get(), RADIO_YAW, and RadioControl::values.
Referenced by autopilot_on_rc_frame().
autopilot_generated_periodic()
void autopilot_generated_periodic (void)
Definition at line 50 of file autopilot_generated.c.
References autopilot, foo, and pprz_autopilot::mode.
Referenced by autopilot_periodic().
autopilot_generated_set_mode()
void autopilot_generated_set_mode (uint8_t new_autopilot_mode)
Definition at line 77 of file autopilot_generated.c.
References autopilot, FALSE, foo, and pprz_autopilot::mode.
Referenced by autopilot_generated_SetModeHandler(), and autopilot_set_mode().
autopilot_generated_set_motors_on()
void autopilot_generated_set_motors_on (bool motors_on)
Definition at line 85 of file autopilot_generated.c.
References autopilot, and pprz_autopilot::motors_on.
Referenced by autopilot_force_motors_on().
autopilot_generated_SetModeHandler()
void autopilot_generated_SetModeHandler (float mode)
AP mode setting handler.
FIXME generated something else for this?
Definition at line 71 of file autopilot_generated.c.
References autopilot_generated_set_mode(), and mode.
Referenced by autopilot_SetModeHandler().