Paparazzi UAS: sw/airborne/firmwares/fixedwing/main_ap.h File Reference
main_ap.h File Reference
AP (AutoPilot) process API.
Functions
void init_ap (void)
void handle_periodic_tasks_ap (void)
void event_task_ap (void)
void sensors_task (void)
Run at PERIODIC_FREQUENCY (60Hz if not defined)
void monitor_task (void)
monitor stuff run at 1Hz
void reporting_task (void)
Send a series of initialisation messages followed by a stream of periodic ones.
Detailed Description
AP (AutoPilot) process API.
Definition in file main_ap.h.
Function Documentation
void event_task_ap (void)
Definition at line 369 of file main_ap.c.
References autopilot_event(), autopilot_on_rc_frame(), BaroEvent, inter_mcu_received_fbw, link_mcu_event_task(), and mcu_event().
Referenced by sim_periodic_task().
void handle_periodic_tasks_ap (void)
Definition at line 229 of file main_ap.c.
References attitude_loop(), autopilot_periodic(), baro_periodic(), LED_PERIODIC, monitor_task(), navigation_task(), reporting_task(), sensors_task(), and sys_time_check_and_ack_timer().
void init_ap (void)
init done in main_fbw in single MCU
start interrupt task
Definition at line 149 of file main_ap.c.
References ahrs_init(), ap_state, autopilot_generated_init(), autopilot_init(), autopilot_static_init(), baro_init(), BARO_PERIODIC_FREQUENCY, Imu::body_to_imu, COMMAND_PITCH_TRIM, COMMAND_ROLL_TRIM, COMMAND_YAW_TRIM, CONTROL_FREQUENCY, downlink_init(), imu, link_mcu_init(), mcu_int_enable, NAVIGATION_FREQUENCY, orientationGetQuat_f(), PPRZ_MUTEX_LOCK, PPRZ_MUTEX_UNLOCK, settings_init(), stateInit(), sys_time_register_timer(), and TELEMETRY_FREQUENCY.
Referenced by sim_init().
void monitor_task (void)
monitor stuff run at 1Hz
Definition at line 334 of file main_ap.c.
References ap_electrical, autopilot, CATASTROPHIC_BAT_KILL_DELAY, datalink_time, DefaultChannel, DefaultDevice, dist2_to_home, pprz_autopilot::flight_time, KILL_MODE_DISTANCE, pprz_autopilot::kill_throttle, pprz_autopilot::launch, MIN_SPEED_FOR_TAKEOFF, sys_time::nb_sec, Square, stateGetHorizontalSpeedNorm_f(), and Electrical::vsupply.
Referenced by handle_periodic_tasks_ap(), and sim_monitor_task().
void reporting_task (void)
Send a series of initialisation messages followed by a stream of periodic ones.
Called at 60Hz.
Definition at line 283 of file main_ap.c.
References autopilot_send_version(), DefaultChannel, DefaultDevice, and DefaultPeriodic.
Referenced by handle_periodic_tasks_ap(), and sim_periodic_task().
void sensors_task (void)
Run at PERIODIC_FREQUENCY (60Hz if not defined)
Definition at line 306 of file main_ap.c.
References update_ahrs_from_sim().
Referenced by handle_periodic_tasks_ap(), and sim_periodic_task().