Paparazzi UAS: sw/airborne/modules/benchmark/flight_benchmark.h File Reference
flight_benchmark.h File Reference
#include <inttypes.h>
Functions
void flight_benchmark_init (void)
void flight_benchmark_periodic (void)
void flight_benchmark_reset (void)
Variables
float ToleranceAispeed
float ToleranceAltitude
float TolerancePosition
bool benchm_reset
bool benchm_go
Function Documentation
flight_benchmark_init()
void flight_benchmark_init (void)
Definition at line 32 of file flight_benchmark.c.
References benchm_go, benchm_reset, foo, SquareSumErr_airspeed, SquareSumErr_altitude, SquareSumErr_position, ToleranceAispeed, ToleranceAltitude, and TolerancePosition.
flight_benchmark_periodic()
void flight_benchmark_periodic (void)
Definition at line 44 of file flight_benchmark.c.
References benchm_go, benchm_reset, DefaultChannel, DefaultDevice, flight_benchmark_reset(), foo, nav_circle_radius, nav_circle_x, nav_circle_y, nav_segment_x_1, nav_segment_x_2, nav_segment_y_1, nav_segment_y_2, SquareSumErr_airspeed, SquareSumErr_altitude, SquareSumErr_position, stateGetAirspeed_f(), stateGetPositionEnu_f(), stateGetPositionUtm_f(), ToleranceAispeed, ToleranceAltitude, TolerancePosition, v_ctl_altitude_setpoint, v_ctl_auto_airspeed_setpoint, EnuCoor_f::x, and EnuCoor_f::y.
flight_benchmark_reset()
void flight_benchmark_reset (void)
Definition at line 115 of file flight_benchmark.c.
References SquareSumErr_airspeed, SquareSumErr_altitude, and SquareSumErr_position.
Referenced by flight_benchmark_periodic().
Variable Documentation
benchm_go
bool benchm_go extern
Definition at line 28 of file flight_benchmark.c.
Referenced by flight_benchmark_init(), and flight_benchmark_periodic().
benchm_reset
bool benchm_reset extern
Definition at line 27 of file flight_benchmark.c.
Referenced by flight_benchmark_init(), and flight_benchmark_periodic().
ToleranceAispeed
float ToleranceAispeed extern
Definition at line 24 of file flight_benchmark.c.
Referenced by flight_benchmark_init(), and flight_benchmark_periodic().
ToleranceAltitude
float ToleranceAltitude extern
Definition at line 25 of file flight_benchmark.c.
Referenced by flight_benchmark_init(), and flight_benchmark_periodic().
TolerancePosition
float TolerancePosition extern
Definition at line 26 of file flight_benchmark.c.
Referenced by flight_benchmark_init(), and flight_benchmark_periodic().