Paparazzi UAS: sw/airborne/modules/multi/formation.h File Reference
formation.h File Reference
Formation flight library.
#include "modules/datalink/datalink.h"
#include "generated/airframe.h"
#include "modules/multi/traffic_info.h"
Data Structures
struct slot_
Macros
#define FORM_MODE_GLOBAL 0
#define FORM_MODE_COURSE 1
Enumerations
enum slot_status { UNSET , ACTIVE , IDLE , LOST }
Functions
int formation_init (void)
int add_slot (uint8_t _id, float slot_e, float slot_n, float slot_a)
static void updateSlot (uint8_t id, float se, float sn, float sa)
static void updateFormationStatus (uint8_t id, uint8_t status)
static void parseFormationStatus (uint8_t *buf)
static void parseFormationSlot (uint8_t *buf)
int start_formation (void)
int stop_formation (void)
int formation_flight (void)
void formation_pre_call (void)
Variables
float coef_form_alt
float coef_form_pos
float coef_form_speed
float coef_form_course
float form_prox
uint8_t form_mode
uint8_t leader_id
struct slot_ formation []
Detailed Description
Formation flight library.
Definition in file formation.h.
Data Structure Documentation
slot_
struct slot_
Definition at line 24 of file formation.h.
Data Fields
float alt
float east
float north
enum slot_status status
Macro Definition Documentation
FORM_MODE_COURSE
#define FORM_MODE_COURSE 1
Definition at line 15 of file formation.h.
FORM_MODE_GLOBAL
#define FORM_MODE_GLOBAL 0
Definition at line 14 of file formation.h.
Enumeration Type Documentation
slot_status
enum slot_status
Enumerator
UNSET
ACTIVE
IDLE
LOST
Definition at line 22 of file formation.h.
Function Documentation
add_slot()
int add_slot (uint8_t _id, float slot_e, float slot_n, float slot_a) extern
Definition at line 80 of file formation.c.
References slot_::alt, DefaultChannel, DefaultDevice, slot_::east, foo, form_mode, formation, IDLE, slot_::north, slot_::status, and ti_acs_id.
formation_flight()
int formation_flight (void) extern
Definition at line 124 of file formation.c.
References acInfoGetCourse(), acInfoGetGspeed(), acInfoGetItow(), acInfoGetPositionEnu_f(), acInfoGetVelocityEnu_f(), ACTIVE, slot_::alt, coef_form_alt, coef_form_pos, coef_form_speed, DefaultChannel, DefaultDevice, desired_x, desired_y, slot_::east, flight_altitude, fly_to_xy(), foo, form_a, form_carrot, FORM_CARROT, form_e, form_mode, FORM_MODE_COURSE, form_n, form_prox, form_speed, form_speed_e, form_speed_n, formation, gps, ground_alt, IDLE, leader_id, LOST, nav_altitude, NavVerticalAutoThrottleMode, NB_ACS, slot_::north, stateGetHorizontalSpeedDir_f(), stateGetHorizontalSpeedNorm_f(), stateGetPositionEnu_f(), slot_::status, status, ti_acs, ti_acs_id, GpsState::tow, UNSET, v_ctl_auto_throttle_cruise_throttle, EnuCoor_f::x, and EnuCoor_f::y.
formation_init()
int formation_init (void) extern
Definition at line 62 of file formation.c.
References coef_form_alt, coef_form_course, coef_form_pos, coef_form_speed, foo, FORM_ALTITUDE_PGAIN, form_carrot, FORM_CARROT, FORM_COURSE_PGAIN, form_mode, FORM_MODE, FORM_POS_PGAIN, form_prox, FORM_PROX, FORM_SPEED_PGAIN, formation, ground_alt, leader_id, NB_ACS, old_alt, old_cruise, slot_::status, and UNSET.
formation_pre_call()
void formation_pre_call (void) extern
Definition at line 254 of file formation.c.
References slot_::east, foo, formation, leader_id, slot_::north, stateGetPositionEnu_f(), ti_acs_id, EnuCoor_f::x, and EnuCoor_f::y.
parseFormationSlot()
static void parseFormationSlot (uint8_t * buf) inline static
Definition at line 56 of file formation.h.
References foo, form_mode, leader_id, mode, and updateSlot().
parseFormationStatus()
static void parseFormationStatus (uint8_t * buf) inline static
Definition at line 46 of file formation.h.
References foo, leader_id, status, UNSET, and updateFormationStatus().
start_formation()
int start_formation (void) extern
Definition at line 91 of file formation.c.
References ACTIVE, DefaultChannel, DefaultDevice, foo, formation, IDLE, leader_id, nav_altitude, NB_ACS, old_alt, old_cruise, slot_::status, status, and v_ctl_auto_throttle_cruise_throttle.
stop_formation()
int stop_formation (void) extern
Definition at line 106 of file formation.c.
References ACTIVE, DefaultChannel, DefaultDevice, foo, formation, ground_alt, IDLE, leader_id, nav_altitude, NB_ACS, old_alt, old_cruise, slot_::status, status, and v_ctl_auto_throttle_cruise_throttle.
updateFormationStatus()
static void updateFormationStatus (uint8_t id, uint8_t status) inline static
Definition at line 44 of file formation.h.
References formation, slot_::status, status, and ti_acs_id.
Referenced by parseFormationStatus().
updateSlot()
static void updateSlot (uint8_t id, float se, float sn, float sa) inline static
Definition at line 37 of file formation.h.
References slot_::alt, slot_::east, foo, formation, slot_::north, and ti_acs_id.
Referenced by parseFormationSlot().
Variable Documentation
coef_form_alt
float coef_form_alt extern
Definition at line 27 of file formation.c.
Referenced by formation_flight(), and formation_init().
coef_form_course
float coef_form_course
Definition at line 17 of file formation.h.
coef_form_pos
float coef_form_pos
Definition at line 17 of file formation.h.
coef_form_speed
float coef_form_speed
Definition at line 17 of file formation.h.
form_mode
uint8_t form_mode extern
Definition at line 28 of file formation.c.
Referenced by add_slot(), formation_flight(), formation_init(), and parseFormationSlot().
form_prox
float form_prox extern
Definition at line 23 of file formation.c.
Referenced by formation_flight(), and formation_init().
formation
struct slot_ formation[] extern
Definition at line 32 of file formation.c.
Referenced by add_slot(), formation_flight(), formation_init(), formation_pre_call(), start_formation(), stop_formation(), updateFormationStatus(), and updateSlot().
leader_id
uint8_t leader_id extern
Definition at line 29 of file formation.c.
Referenced by formation_flight(), formation_init(), formation_pre_call(), parseFormationSlot(), parseFormationStatus(), start_formation(), and stop_formation().