Paparazzi UAS: sw/airborne/modules/datalink/frsky_x.h File Reference
frsky_x.h File Reference
#include "pprzlink/pprzlink_device.h"
Data Structures
struct fifo_t
struct frsky_x_serial_periph
Macros
#define DOWNLINK_BUFFER_SIZE 512
#define UPLINK_BUFFER_SIZE 512
Functions
void datalink_frsky_x_init (void)
Variables
struct frsky_x_serial_periph frsky_x_serial
Data Structure Documentation
fifo_t
struct fifo_t
Definition at line 30 of file frsky_x.h.
Data Fields
uint8_t * buf
int head
size_t size
int tail
frsky_x_serial_periph
struct frsky_x_serial_periph
Definition at line 37 of file frsky_x.h.
Data Fields
struct link_device device Generic device interface.
uint8_t downlink_buf[DOWNLINK_BUFFER_SIZE]
fifo_t downlink_fifo
uint8_t uplink_buf[UPLINK_BUFFER_SIZE]
fifo_t uplink_fifo
Macro Definition Documentation
DOWNLINK_BUFFER_SIZE
#define DOWNLINK_BUFFER_SIZE 512
Definition at line 27 of file frsky_x.h.
UPLINK_BUFFER_SIZE
#define UPLINK_BUFFER_SIZE 512
Definition at line 28 of file frsky_x.h.
Function Documentation
datalink_frsky_x_init()
void datalink_frsky_x_init (void)
Definition at line 156 of file frsky_x.c.
References frsky_x_serial_periph::device, frsky_x_serial_periph::downlink_buf, DOWNLINK_BUFFER_SIZE, frsky_x_serial_periph::downlink_fifo, fifo_init(), frsky_x_serial, frsky_x_serial_char_available(), frsky_x_serial_check_free_space(), frsky_x_serial_get_byte(), frsky_x_serial_put_buffer(), frsky_x_serial_put_byte(), frsky_x_serial_send_message(), smartPortDownlink, smartPortDownlink_cb(), smartPortUplink, smartPortUplink_cb(), frsky_x_serial_periph::uplink_buf, UPLINK_BUFFER_SIZE, and frsky_x_serial_periph::uplink_fifo.
Variable Documentation
frsky_x_serial
struct frsky_x_serial_periph frsky_x_serial extern
Definition at line 27 of file frsky_x.c.
Referenced by datalink_frsky_x_init(), smartPortDownlink_cb(), and smartPortUplink_cb().