Paparazzi UAS: sw/airborne/modules/com/generic_com.c File Reference
generic_com.c File Reference
#include "std.h"
#include "modules/com/generic_com.h"
#include "mcu_periph/i2c.h"
#include "state.h"
#include "modules/gps/gps.h"
#include "modules/energy/electrical.h"
#include "generated/airframe.h"
#include "modules/core/commands.h"
#include "autopilot.h"
#include "modules/nav/common_nav.h"
Macros
#define NB_DATA 24
#define GENERIC_COM_I2C_DEV i2c0
#define GENERIC_COM_SLAVE_ADDR 0x26
#define FillBufWith32bit(_buf, _index, _value)
#define FillBufWith16bit(_buf, _index, _value)
Functions
void generic_com_init (void)
void generic_com_periodic (void)
void generic_com_event (void)
void start_com (void)
void stop_com (void)
Variables
struct i2c_transaction com_trans
bool active_com
Macro Definition Documentation
FillBufWith16bit
#define FillBufWith16bit (_buf, _index, _value)
Value:
    {  \
    _buf[_index] = (uint8_t) (_value);              \
    _buf[_index+1] = (uint8_t) ((_value) >> 8);     \
  }
Definition at line 65 of file generic_com.c.
FillBufWith32bit
#define FillBufWith32bit (_buf, _index, _value)
Value:
    {  \
    _buf[_index] = (uint8_t) (_value);              \
    _buf[_index+1] = (uint8_t) ((_value) >> 8);     \
    _buf[_index+2] = (uint8_t) ((_value) >> 16);    \
    _buf[_index+3] = (uint8_t) ((_value) >> 24);    \
  }
Definition at line 58 of file generic_com.c.
GENERIC_COM_I2C_DEV
#define GENERIC_COM_I2C_DEV i2c0
Definition at line 41 of file generic_com.c.
GENERIC_COM_SLAVE_ADDR
#define GENERIC_COM_SLAVE_ADDR 0x26
Definition at line 45 of file generic_com.c.
NB_DATA
#define NB_DATA 24
Definition at line 38 of file generic_com.c.
Function Documentation
generic_com_event()
void generic_com_event (void)
Definition at line 93 of file generic_com.c.
References com_trans, I2CTransDone, I2CTransFailed, I2CTransSuccess, and i2c_transaction::status.
generic_com_init()
void generic_com_init (void)
Definition at line 52 of file generic_com.c.
References active_com, com_trans, I2CTransDone, and i2c_transaction::status.
generic_com_periodic()
void generic_com_periodic (void)
Definition at line 70 of file generic_com.c.
References active_com, LlaCoor_i::alt, autopilot, autopilot_get_mode(), i2c_transaction::buf, charge, com_trans, GpsState::course, electrical, FillBufWith16bit, FillBufWith32bit, pprz_autopilot::flight_time, foo, GENERIC_COM_I2C_DEV, GENERIC_COM_SLAVE_ADDR, get_nav_block(), gps, GpsState::gspeed, i2c_transmit(), I2CTransDone, LlaCoor_i::lat, GpsState::lla_pos, LlaCoor_i::lon, MAX_PPRZ, Min, NB_DATA, stateGetAirspeed_f(), i2c_transaction::status, and Electrical::vsupply.
start_com()
void start_com (void)
Definition at line 101 of file generic_com.c.
References active_com, com_trans, I2CTransDone, and i2c_transaction::status.
stop_com()
void stop_com (void)
Definition at line 107 of file generic_com.c.
References active_com, i2c_transaction::buf, com_trans, GENERIC_COM_I2C_DEV, GENERIC_COM_SLAVE_ADDR, and i2c_transmit().
Variable Documentation
active_com
bool active_com
Definition at line 50 of file generic_com.c.
Referenced by generic_com_init(), generic_com_periodic(), start_com(), and stop_com().
com_trans
struct i2c_transaction com_trans
Definition at line 48 of file generic_com.c.
Referenced by generic_com_event(), generic_com_init(), generic_com_periodic(), start_com(), and stop_com().