Paparazzi UAS: sw/airborne/modules/com/generic_com.h File Reference
generic_com.h File Reference
Functions
void generic_com_init (void)
void generic_com_periodic (void)
void generic_com_event (void)
void start_com (void)
void stop_com (void)
Function Documentation
generic_com_event()
void generic_com_event (void)
Definition at line 93 of file generic_com.c.
References com_trans, I2CTransDone, I2CTransFailed, I2CTransSuccess, and i2c_transaction::status.
generic_com_init()
void generic_com_init (void)
Definition at line 52 of file generic_com.c.
References active_com, com_trans, I2CTransDone, and i2c_transaction::status.
generic_com_periodic()
void generic_com_periodic (void)
Definition at line 70 of file generic_com.c.
References active_com, LlaCoor_i::alt, autopilot, autopilot_get_mode(), i2c_transaction::buf, charge, com_trans, GpsState::course, electrical, FillBufWith16bit, FillBufWith32bit, pprz_autopilot::flight_time, foo, GENERIC_COM_I2C_DEV, GENERIC_COM_SLAVE_ADDR, get_nav_block(), gps, GpsState::gspeed, i2c_transmit(), I2CTransDone, LlaCoor_i::lat, GpsState::lla_pos, LlaCoor_i::lon, MAX_PPRZ, Min, NB_DATA, stateGetAirspeed_f(), i2c_transaction::status, and Electrical::vsupply.
start_com()
void start_com (void)
Definition at line 101 of file generic_com.c.
References active_com, com_trans, I2CTransDone, and i2c_transaction::status.
stop_com()
void stop_com (void)
Definition at line 107 of file generic_com.c.
References active_com, i2c_transaction::buf, com_trans, GENERIC_COM_I2C_DEV, GENERIC_COM_SLAVE_ADDR, and i2c_transmit().