Paparazzi UAS: sw/airborne/modules/cam_control/gimbal_caddx_gm3.h File Reference
gimbal_caddx_gm3.h File Reference
#include "std.h"
Functions
void gimbal_caddx_gm3_init (void)
void gimbal_caddx_gm3_periodic (void)
Variables
float gimbal_caddx_gm3_roll
Detailed Description
Author
Julia Cabarbaye julia.nosp@m..cab.nosp@m.arbay.nosp@m.e1@g.nosp@m.mail..nosp@m.com caddx gm3 gimbal control sbus
Definition in file gimbal_caddx_gm3.h.
Function Documentation
gimbal_caddx_gm3_init()
void gimbal_caddx_gm3_init (void) extern
Definition at line 61 of file gimbal_caddx_gm3.c.
References cam_gimbal, cam_gimbal_set_angles_callback(), cam_gimbal_setup_angles(), foo, gimbal_caddx_compute_angles(), gimbal_caddx_gm3_roll, GIMBAL_CADDX_PAN_MAX, GIMBAL_CADDX_TILT_MAX, and MIN_PPRZ.
gimbal_caddx_gm3_periodic()
void gimbal_caddx_gm3_periodic (void) extern
Definition at line 84 of file gimbal_caddx_gm3.c.
References foo, gimbal_caddx_gm3_roll, GIMBAL_CADDX_ROLL_MAX, and MAX_PPRZ.
Variable Documentation
gimbal_caddx_gm3_roll
float gimbal_caddx_gm3_roll extern
Definition at line 41 of file gimbal_caddx_gm3.c.
Referenced by gimbal_caddx_compute_angles(), gimbal_caddx_gm3_init(), and gimbal_caddx_gm3_periodic().