Paparazzi UAS: sw/airborne/modules/glide_wing_lock/glide_wing_lock.h File Reference
glide_wing_lock.h File Reference
#include "std.h"
#include "generated/airframe.h"
#include "paparazzi.h"
Macros
#define ROTORCRAFT_COMMANDS_THROUGH_MODULE
Functions
void init (void)
void glide_wing_lock_init (void)
void glide_wing_lock_event (void)
void glide_wing_lock_periodic (void)
Detailed Description
Author
Kevin van Hecke Locks the wing of an ornicopter so it can glide.
Definition in file glide_wing_lock.h.
Macro Definition Documentation
ROTORCRAFT_COMMANDS_THROUGH_MODULE
#define ROTORCRAFT_COMMANDS_THROUGH_MODULE
Definition at line 33 of file glide_wing_lock.h.
Function Documentation
glide_wing_lock_event()
void glide_wing_lock_event (void) extern
Definition at line 63 of file glide_wing_lock.c.
References adcbuf, adc_buf::av_nb_sample, foo, lock_wings, MIN_PPRZ, radio_control, adc_buf::sum, RadioControl::values, WING_POS_DOWN_THRESH, WING_POS_LOCK_MAX_THRESH, WING_POS_LOCK_MIN_THRESH, and WING_POS_LOCK_SWITCH.
glide_wing_lock_init()
void glide_wing_lock_init (void) extern
Definition at line 58 of file glide_wing_lock.c.
References adc_buf_channel(), adcbuf, and foo.
glide_wing_lock_periodic()
void glide_wing_lock_periodic (void) extern
Definition at line 101 of file glide_wing_lock.c.
References adcbuf, adc_buf::av_nb_sample, DefaultChannel, DefaultDevice, foo, and adc_buf::sum.
init()
void init (void) extern
Definition at line 57 of file nav_gls.c.
Referenced by calculate_wind_no_airspeed(), gls_run(), gls_start(), main(), mission_nav_custom(), mission_nav_custom(), and mission_nav_custom().