Paparazzi UAS: sw/airborne/modules/digital_cam/gpio_cam_ctrl.h File Reference
gpio_cam_ctrl.h File Reference
Digital Camera Control.
Functions
void gpio_cam_ctrl_init (void)
void gpio_cam_ctrl_periodic (void)
Periodic.
Detailed Description
Digital Camera Control.
Provides the control of the shutter and the zoom of a digital camera through standard binary IOs of the board.
The required initialization (dc_init()) and periodic process.
Definition in file gpio_cam_ctrl.h.
Function Documentation
gpio_cam_ctrl_init()
void gpio_cam_ctrl_init (void) extern
Definition at line 74 of file gpio_cam_ctrl.c.
References DC_RELEASE, dc_timer, foo, and gpio_setup_output().
gpio_cam_ctrl_periodic()
void gpio_cam_ctrl_periodic (void) extern
Periodic.
Definition at line 99 of file gpio_cam_ctrl.c.
References dc_periodic(), DC_RELEASE, dc_send_shot_position(), dc_timer, and foo.