Paparazzi UAS: sw/airborne/modules/gpio_ext/gpio_ext_pca95xx.c File Reference
gpio_ext_pca95xx.c File Reference
#include "modules/gpio_ext/gpio_ext_pca95xx.h"
#include "modules/gpio_ext/gpio_ext_common.h"
#include "generated/airframe.h"
#include "peripherals/pca95xx.h"
#include "mcu_periph/i2c.h"
#include <stdbool.h>
Data Structures
struct gpio_ext_pca95xx_impl_t
Macros
#define GPIO_EXT_PCA95XX_I2C_PERIPH1_PTR NULL
#define GPIO_EXT_PCA95XX_I2C_PERIPH2_PTR NULL
#define GPIO_EXT_PCA95XX_I2C_PERIPH3_PTR NULL
#define GPIO_EXT_PCA95XX_I2C_PERIPH4_PTR NULL
#define GPIO_EXT_PCA95XX_I2C_ADDRESS1 0x00
#define GPIO_EXT_PCA95XX_I2C_ADDRESS2 0x00
#define GPIO_EXT_PCA95XX_I2C_ADDRESS3 0x00
#define GPIO_EXT_PCA95XX_I2C_ADDRESS4 0x00
#define GPIO_EXT_PCA95XX_BLOCKING1 TRUE
#define GPIO_EXT_PCA95XX_BLOCKING2 TRUE
#define GPIO_EXT_PCA95XX_BLOCKING3 TRUE
#define GPIO_EXT_PCA95XX_BLOCKING4 TRUE
Functions
static void gpio_ext_pca95xx_setup_output (uint32_t port, uint32_t gpios)
static void gpio_ext_pca95xx_setup_input (uint32_t port, uint32_t gpios)
static uint32_t gpio_ext_pca95xx_get (uint32_t port, uint32_t gpios)
static void gpio_ext_pca95xx_set (uint32_t port, uint32_t gpios)
static void gpio_ext_pca95xx_clear (uint32_t port, uint32_t gpios)
static void gpio_ext_pca95xx_toggle (uint32_t port, uint32_t gpios)
static void gpio_ext_pca95xx_lazy_init (uint32_t port)
Variables
static struct i2c_periph *const i2c_periph []
static const uint8_t i2c_addr []
static const bool blocking []
struct gpio_ext_functions pca95xx_functions
static struct gpio_ext_pca95xx_impl_t impl [GPIOEXT_NB]
Detailed Description
Author
Tom van Dijk tomva.nosp@m.nd@u.nosp@m.sers..nosp@m.nore.nosp@m.ply.g.nosp@m.ithu.nosp@m.b.com PCA95XX external GPIO peripheral
Definition in file gpio_ext_pca95xx.c.
Data Structure Documentation
gpio_ext_pca95xx_impl_t
struct gpio_ext_pca95xx_impl_t
Definition at line 120 of file gpio_ext_pca95xx.c.
Data Fields
uint8_t config_reg
bool initialized
uint8_t output_reg
struct pca95xx periph
Macro Definition Documentation
GPIO_EXT_PCA95XX_BLOCKING1
#define GPIO_EXT_PCA95XX_BLOCKING1 TRUE
Definition at line 83 of file gpio_ext_pca95xx.c.
GPIO_EXT_PCA95XX_BLOCKING2
#define GPIO_EXT_PCA95XX_BLOCKING2 TRUE
Definition at line 86 of file gpio_ext_pca95xx.c.
GPIO_EXT_PCA95XX_BLOCKING3
#define GPIO_EXT_PCA95XX_BLOCKING3 TRUE
Definition at line 89 of file gpio_ext_pca95xx.c.
GPIO_EXT_PCA95XX_BLOCKING4
#define GPIO_EXT_PCA95XX_BLOCKING4 TRUE
Definition at line 92 of file gpio_ext_pca95xx.c.
GPIO_EXT_PCA95XX_I2C_ADDRESS1
#define GPIO_EXT_PCA95XX_I2C_ADDRESS1 0x00
Definition at line 64 of file gpio_ext_pca95xx.c.
GPIO_EXT_PCA95XX_I2C_ADDRESS2
#define GPIO_EXT_PCA95XX_I2C_ADDRESS2 0x00
Definition at line 67 of file gpio_ext_pca95xx.c.
GPIO_EXT_PCA95XX_I2C_ADDRESS3
#define GPIO_EXT_PCA95XX_I2C_ADDRESS3 0x00
Definition at line 70 of file gpio_ext_pca95xx.c.
GPIO_EXT_PCA95XX_I2C_ADDRESS4
#define GPIO_EXT_PCA95XX_I2C_ADDRESS4 0x00
Definition at line 73 of file gpio_ext_pca95xx.c.
GPIO_EXT_PCA95XX_I2C_PERIPH1_PTR
#define GPIO_EXT_PCA95XX_I2C_PERIPH1_PTR NULL
Definition at line 39 of file gpio_ext_pca95xx.c.
GPIO_EXT_PCA95XX_I2C_PERIPH2_PTR
#define GPIO_EXT_PCA95XX_I2C_PERIPH2_PTR NULL
Definition at line 44 of file gpio_ext_pca95xx.c.
GPIO_EXT_PCA95XX_I2C_PERIPH3_PTR
#define GPIO_EXT_PCA95XX_I2C_PERIPH3_PTR NULL
Definition at line 49 of file gpio_ext_pca95xx.c.
GPIO_EXT_PCA95XX_I2C_PERIPH4_PTR
#define GPIO_EXT_PCA95XX_I2C_PERIPH4_PTR NULL
Definition at line 54 of file gpio_ext_pca95xx.c.
Function Documentation
gpio_ext_pca95xx_clear()
static void gpio_ext_pca95xx_clear (uint32_t port, uint32_t gpios) static
Definition at line 173 of file gpio_ext_pca95xx.c.
References blocking, foo, impl, gpio_ext_pca95xx_impl_t::output_reg, pca95xx_set_output(), and gpio_ext_pca95xx_impl_t::periph.
gpio_ext_pca95xx_get()
static uint32_t gpio_ext_pca95xx_get (uint32_t port, uint32_t gpios) static
Definition at line 160 of file gpio_ext_pca95xx.c.
References foo, impl, pca95xx_get_input(), and gpio_ext_pca95xx_impl_t::periph.
gpio_ext_pca95xx_lazy_init()
static void gpio_ext_pca95xx_lazy_init (uint32_t port) static
Definition at line 129 of file gpio_ext_pca95xx.c.
References gpio_ext_pca95xx_impl_t::config_reg, foo, i2c_addr, pca95xx::i2c_trans, I2CTransSuccess, impl, gpio_ext_pca95xx_impl_t::initialized, gpio_ext_pca95xx_impl_t::output_reg, pca95xx_configure(), pca95xx_init(), gpio_ext_pca95xx_impl_t::periph, and i2c_transaction::status.
Referenced by gpio_ext_pca95xx_setup_input(), and gpio_ext_pca95xx_setup_output().
gpio_ext_pca95xx_set()
static void gpio_ext_pca95xx_set (uint32_t port, uint32_t gpios) static
Definition at line 167 of file gpio_ext_pca95xx.c.
References blocking, foo, impl, gpio_ext_pca95xx_impl_t::output_reg, pca95xx_set_output(), and gpio_ext_pca95xx_impl_t::periph.
gpio_ext_pca95xx_setup_input()
static void gpio_ext_pca95xx_setup_input (uint32_t port, uint32_t gpios) static
Definition at line 153 of file gpio_ext_pca95xx.c.
References blocking, gpio_ext_pca95xx_impl_t::config_reg, foo, gpio_ext_pca95xx_lazy_init(), impl, pca95xx_configure(), and gpio_ext_pca95xx_impl_t::periph.
gpio_ext_pca95xx_setup_output()
static void gpio_ext_pca95xx_setup_output (uint32_t port, uint32_t gpios) static
Definition at line 146 of file gpio_ext_pca95xx.c.
References blocking, gpio_ext_pca95xx_impl_t::config_reg, foo, gpio_ext_pca95xx_lazy_init(), impl, pca95xx_configure(), and gpio_ext_pca95xx_impl_t::periph.
gpio_ext_pca95xx_toggle()
static void gpio_ext_pca95xx_toggle (uint32_t port, uint32_t gpios) static
Definition at line 179 of file gpio_ext_pca95xx.c.
References blocking, foo, impl, gpio_ext_pca95xx_impl_t::output_reg, pca95xx_set_output(), and gpio_ext_pca95xx_impl_t::periph.
Variable Documentation
blocking
const bool blocking[] static
Initial value:
= {
    GPIO_EXT_PCA95XX_BLOCKING1,
    GPIO_EXT_PCA95XX_BLOCKING1,
    GPIO_EXT_PCA95XX_BLOCKING1,
    GPIO_EXT_PCA95XX_BLOCKING1,
}
Definition at line 94 of file gpio_ext_pca95xx.c.
Referenced by gpio_ext_pca95xx_clear(), gpio_ext_pca95xx_set(), gpio_ext_pca95xx_setup_input(), gpio_ext_pca95xx_setup_output(), gpio_ext_pca95xx_toggle(), open_udp(), pca95xx_configure(), and pca95xx_set_output().
i2c_addr
const uint8_t i2c_addr[] static
Initial value:
= {
    GPIO_EXT_PCA95XX_I2C_ADDRESS1,
    GPIO_EXT_PCA95XX_I2C_ADDRESS2,
    GPIO_EXT_PCA95XX_I2C_ADDRESS3,
    GPIO_EXT_PCA95XX_I2C_ADDRESS4,
}
Definition at line 75 of file gpio_ext_pca95xx.c.
Referenced by gpio_ext_pca95xx_lazy_init().
i2c_periph
struct i2c_periph* const i2c_periph[] static
Initial value:
= {
    GPIO_EXT_PCA95XX_I2C_PERIPH1_PTR,
    GPIO_EXT_PCA95XX_I2C_PERIPH2_PTR,
    GPIO_EXT_PCA95XX_I2C_PERIPH3_PTR,
    GPIO_EXT_PCA95XX_I2C_PERIPH4_PTR,
}
Definition at line 56 of file gpio_ext_pca95xx.c.
impl
struct gpio_ext_pca95xx_impl_t impl[GPIOEXT_NB] static
Definition at line 126 of file gpio_ext_pca95xx.c.
Referenced by gpio_ext_pca95xx_clear(), gpio_ext_pca95xx_get(), gpio_ext_pca95xx_lazy_init(), gpio_ext_pca95xx_set(), gpio_ext_pca95xx_setup_input(), gpio_ext_pca95xx_setup_output(), and gpio_ext_pca95xx_toggle().
pca95xx_functions
struct gpio_ext_functions pca95xx_functions
Initial value:
= {
    gpio_ext_pca95xx_setup_output,
    gpio_ext_pca95xx_setup_input,
    gpio_ext_pca95xx_get,
    gpio_ext_pca95xx_set,
    gpio_ext_pca95xx_clear,
    gpio_ext_pca95xx_toggle,
}
Definition at line 110 of file gpio_ext_pca95xx.c.