Paparazzi UAS: sw/airborne/modules/gps/gps_uavcan.c File Reference
gps_uavcan.c File Reference
#include "modules/gps/gps_uavcan.h"
#include "uavcan/uavcan.h"
#include "core/abi.h"
#include "uavcan.equipment.gnss.Fix2.h"
#include "gps.h"
#include "math/pprz_geodetic_int.h"
#include "math/pprz_geodetic_float.h"
#include "math/pprz_geodetic_double.h"
#include "std.h"
Macros
#define SECS_IN_WEEK (7*24*3600000)
Functions
static void gps_uavcan_cb (struct uavcan_iface_t *iface, CanardRxTransfer *transfer)
void gps_uavcan_init (void)
Variables
static uavcan_event gps_uavcan_ev
Detailed Description
Author
Fabien-B fabie.nosp@m.n-b@.nosp@m.githu.nosp@m.b.co.nosp@m.m UAVCAN gps module. Handle uavcan.equipment.gnss.Fix2 message (1063). See: https://dronecan.github.io/Specification/7._List_of_standard_data_types/#fix2
Definition in file gps_uavcan.c.
Macro Definition Documentation
SECS_IN_WEEK
#define SECS_IN_WEEK (7*24*3600000)
Definition at line 39 of file gps_uavcan.c.
Function Documentation
gps_uavcan_cb()
static void gps_uavcan_cb (struct uavcan_iface_t * iface, CanardRxTransfer * transfer) static
Definition at line 43 of file gps_uavcan.c.
References course, foo, get_sys_time_usec(), GPS_FIX_2D, GPS_FIX_3D, GPS_FIX_DGPS, GPS_FIX_NONE, GPS_FIX_RTK, GPS_UAVCAN_ID, GPS_VALID_COURSE_BIT, GPS_VALID_HMSL_BIT, GPS_VALID_POS_ECEF_BIT, GPS_VALID_POS_LLA_BIT, GPS_VALID_VEL_ECEF_BIT, GPS_VALID_VEL_NED_BIT, msg, sys_time::nb_sec, sys_time::nb_sec_rem, NormCourseRad, SECS_IN_WEEK, SQUARE, state, transfer(), VECT2_NORM2, and VECT3_NORM2.
Referenced by gps_uavcan_init().
gps_uavcan_init()
void gps_uavcan_init (void)
Definition at line 205 of file gps_uavcan.c.
References foo, gps_uavcan_cb(), gps_uavcan_ev, and uavcan_bind().
Variable Documentation
gps_uavcan_ev
uavcan_event gps_uavcan_ev static
Definition at line 41 of file gps_uavcan.c.
Referenced by gps_uavcan_init().