Paparazzi UAS: sw/airborne/modules/gps/gps_piksi.h File Reference
gps_piksi.h File Reference
Driver for Piksi modules from Swift-Nav.
Macros
#define PRIMARY_GPS GPS_PIKSI
#define gps_piksi_periodic_check() gps_periodic_check(&gps_piksi)
Functions
void gps_piksi_event (void)
void gps_piksi_init (void)
void gps_piksi_set_base_pos (void)
Variables
struct GpsState gps_piksi
Detailed Description
Driver for Piksi modules from Swift-Nav.
http://docs.swiftnav.com/wiki/Piksi_Integration_Tutorial https://github.com/swift-nav/sbp_tutorial
Definition in file gps_piksi.h.
Macro Definition Documentation
gps_piksi_periodic_check
#define gps_piksi_periodic_check () gps_periodic_check(&gps_piksi)
Definition at line 44 of file gps_piksi.h.
PRIMARY_GPS
#define PRIMARY_GPS GPS_PIKSI
Definition at line 36 of file gps_piksi.h.
Function Documentation
gps_piksi_event()
void gps_piksi_event (void) extern
Definition at line 349 of file gps_piksi.c.
References GpsState::fix, foo, get_sys_time_msec(), GPS_FIX_NONE, gps_piksi, gps_piksi_read(), POS_ECEF_TIMEOUT, sbp_state, time_since_last_pos_update, and uart_char_available().
gps_piksi_init()
void gps_piksi_init (void) extern
Definition at line 308 of file gps_piksi.c.
References GpsState::comp_id, DefaultPeriodic, dops_node, foo, gps_piksi, GPS_PIKSI_ID, gps_piksi_write(), gps_time_node, heartbeat_node, GpsState::nb_channels, pos_ecef_node, pos_llh_node, register_periodic_telemetry(), SBP_ANT_SET, sbp_dops_callback(), sbp_gps_time_callback(), sbp_pos_ecef_callback(), sbp_pos_llh_callback(), sbp_state, sbp_tracking_state_callback(), sbp_tracking_state_dep_a_callback(), SBP_UART_SET1, SBP_UART_SET2, SBP_UART_SET3, sbp_vel_ecef_callback(), sbp_vel_ned_callback(), send_piksi_heartbeat(), spb_heartbeat_callback(), tracking_state_dep_a_node, tracking_state_node, vel_ecef_node, and vel_ned_node.
gps_piksi_set_base_pos()
void gps_piksi_set_base_pos (void) extern
Variable Documentation
gps_piksi
struct GpsState gps_piksi extern
Definition at line 59 of file gps_piksi.c.
Referenced by gps_piksi_event(), gps_piksi_init(), gps_piksi_publish(), sbp_dops_callback(), sbp_gps_time_callback(), sbp_pos_ecef_callback(), sbp_pos_llh_callback(), sbp_tracking_state_callback(), sbp_tracking_state_dep_a_callback(), sbp_vel_ecef_callback(), and sbp_vel_ned_callback().