Paparazzi UAS: sw/airborne/modules/gps/gps_nmea_send.c File Reference
gps_nmea_send.c File Reference
module used to send GPS data over a Tawaki UART for extern instrument using NMEA protocol Exemple of use : MAPIR camera stores GPS data in metadata on each frame
#include "modules/gps/gps_nmea_send.h"
#include "mcu_periph/uart.h"
#include "generated/airframe.h"
#include "state.h"
#include "modules/gps/gps.h"
#include <string.h>
#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>
#include <math.h>
#include <inttypes.h>
Functions
static void recover_gps_data (void)
Function to recover data available onboard from GPS.
static void build_nmea_sentence (void)
Function to build sentence for NMEA Protocol.
static uint8_t nmea_checksum (const char *sentence, int length)
Function to calculate checksum.
static void nmea_convert_deg_to_DDMM (double deg, char *buf, int is_lat)
Function to convert lat long in DDLL.MMMM Format Lat and long don't have the same length.
static void gps_nmea_get_system_date_str (char *buf_date, size_t buf_date_size, char *buf_time, size_t buf_time_size)
Get Date from system.
static void nmea_send (const char *payload, int payload_length)
Function to send payload to UART.
void gps_nmea_send_init (void)
Initialization function.
void gps_nmea_send_periodic (void)
Periodic function to send data.
Variables
struct Gps_Nmea_Send gps_nmea_send
Detailed Description
module used to send GPS data over a Tawaki UART for extern instrument using NMEA protocol Exemple of use : MAPIR camera stores GPS data in metadata on each frame
Author
Jean-Baptiste FORESTIER
Definition in file gps_nmea_send.c.
Function Documentation
build_nmea_sentence()
void build_nmea_sentence (void) static
Function to build sentence for NMEA Protocol.
Definition at line 105 of file gps_nmea_send.c.
References gps_nmea_send_msg_t::course, GpsState::fix, foo, gps, GPS_FIX_3D, gps_nmea_get_system_date_str(), gps_nmea_send, gps_nmea_send_msg_t::hmsl, gps_nmea_send_msg_t::lat, gps_nmea_send_msg_t::lon, Gps_Nmea_Send::msg, nmea_checksum(), nmea_convert_deg_to_DDMM(), nmea_send(), gps_nmea_send_msg_t::num_sv, gps_nmea_send_msg_t::pdop, and gps_nmea_send_msg_t::vground.
Referenced by gps_nmea_send_periodic().
gps_nmea_get_system_date_str()
void gps_nmea_get_system_date_str (char * buf_date, size_t buf_date_size, char * buf_time, size_t buf_time_size) static
Get Date from system.
Definition at line 221 of file gps_nmea_send.c.
References foo, gps, GpsState::tow, and GpsState::week.
Referenced by build_nmea_sentence().
gps_nmea_send_init()
void gps_nmea_send_init (void)
Initialization function.
Definition at line 56 of file gps_nmea_send.c.
References gps_nmea_send_msg_t::course, Gps_Nmea_Send::error_init, gps_nmea_send, gps_nmea_send_msg_t::hmsl, gps_nmea_send_msg_t::lat, gps_nmea_send_msg_t::lon, Gps_Nmea_Send::msg, gps_nmea_send_msg_t::num_sv, gps_nmea_send_msg_t::pdop, and gps_nmea_send_msg_t::vground.
gps_nmea_send_periodic()
void gps_nmea_send_periodic (void)
Periodic function to send data.
Definition at line 72 of file gps_nmea_send.c.
References build_nmea_sentence(), and recover_gps_data().
nmea_checksum()
uint8_t nmea_checksum (const char * sentence, int length) static
Function to calculate checksum.
Definition at line 190 of file gps_nmea_send.c.
References foo.
Referenced by build_nmea_sentence().
nmea_convert_deg_to_DDMM()
void nmea_convert_deg_to_DDMM (double deg, char * buf, int is_lat) static
Function to convert lat long in DDLL.MMMM Format Lat and long don't have the same length.
Definition at line 203 of file gps_nmea_send.c.
References foo.
Referenced by build_nmea_sentence().
nmea_send()
void nmea_send (const char * payload, int payload_length) static
Function to send payload to UART.
Definition at line 273 of file gps_nmea_send.c.
References foo, and uart_put_buffer().
Referenced by build_nmea_sentence().
recover_gps_data()
void recover_gps_data (void) static
Function to recover data available onboard from GPS.
Definition at line 82 of file gps_nmea_send.c.
References GpsState::course, gps_nmea_send_msg_t::course, foo, gps, gps_nmea_send, GpsState::gspeed, GpsState::hmsl, gps_nmea_send_msg_t::hmsl, LlaCoor_i::lat, gps_nmea_send_msg_t::lat, GpsState::lla_pos, LlaCoor_i::lon, gps_nmea_send_msg_t::lon, Gps_Nmea_Send::msg, NormCourseRad, GpsState::num_sv, gps_nmea_send_msg_t::num_sv, GpsState::pdop, gps_nmea_send_msg_t::pdop, stateGetHmslOrigin_f(), stateGetHorizontalSpeedDir_f(), stateGetHorizontalSpeedNorm_f(), stateGetPositionEnu_f(), stateGetPositionLla_f(), gps_nmea_send_msg_t::vground, and EnuCoor_f::z.
Referenced by gps_nmea_send_periodic().
Variable Documentation
gps_nmea_send
struct Gps_Nmea_Send gps_nmea_send
Definition at line 43 of file gps_nmea_send.c.
Referenced by build_nmea_sentence(), gps_nmea_send_init(), and recover_gps_data().