Paparazzi UAS: sw/airborne/modules/gps/gps.c File Reference
gps.c File Reference
Device independent GPS code.
#include "modules/core/abi.h"
#include "modules/gps/gps.h"
#include "led.h"
#include "modules/core/settings.h"
#include "generated/settings.h"
#include "math/pprz_geodetic_wgs84.h"
#include "math/pprz_geodetic.h"
#include "modules/datalink/telemetry.h"
#include "state.h"
Macros
#define GPS_RELPOS_MAX 3
#define MSEC_PER_WEEK (1000*60*60*24*7)
#define TIME_TO_SWITCH 5000
Functions
void gps_periodic_fix_counter (void)
Increment periodic counter.
static void send_svinfo_id (struct transport_tx *trans, struct link_device *dev, uint8_t svid)
static void send_svinfo (struct transport_tx *trans, struct link_device *dev)
send SVINFO message (regardless of state)
static void send_svinfo_available (struct transport_tx *trans, struct link_device *dev)
send SVINFO message if updated.
static void send_gps (struct transport_tx *trans, struct link_device *dev)
static void send_gps_relpos (struct transport_tx *trans, struct link_device *dev)
static void send_gps_int (struct transport_tx *trans, struct link_device *dev)
static void send_gps_lla (struct transport_tx *trans, struct link_device *dev)
static void send_gps_sol (struct transport_tx *trans, struct link_device *dev)
void gps_periodic_check (struct GpsState *gps_s)
Periodic GPS check.
bool gps_fix_valid (void)
Check if GPS fix is valid.
static void gps_cb (uint8_t sender_id, uint32_t stamp, struct GpsState *gps_s)
static void gps_relpos_cb (uint8_t sender_id, uint32_t stamp, struct RelPosNED *relpos)
void gps_init (void)
initialize the global GPS state
uint32_t gps_tow_from_sys_ticks (uint32_t sys_ticks)
Convert time in sys_time ticks to GPS time of week.
void WEAK gps_inject_data (uint8_t packet_id, uint8_t length, uint8_t *data)
Default parser for GPS injected data.
void gps_parse_GPS_INJECT (uint8_t *buf)
void gps_parse_RTCM_INJECT (uint8_t *buf)
struct LlaCoor_f lla_float_from_gps (struct GpsState *gps_s)
Get GPS lla (float) Converted on the fly if not available.
struct LlaCoor_i lla_int_from_gps (struct GpsState *gps_s)
Get GPS lla (integer) Converted on the fly if not available.
struct EcefCoor_f ecef_float_from_gps (struct GpsState *gps_s)
Get GPS ecef pos (float) Converted on the fly if not available.
struct EcefCoor_i ecef_int_from_gps (struct GpsState *gps_s)
Get GPS ecef pos (integer) Converted on the fly if not available.
struct EcefCoor_f ecef_vel_float_from_gps (struct GpsState *gps_s)
Get GPS ecef velocity (float) Converted on the fly if not available.
struct EcefCoor_i ecef_vel_int_from_gps (struct GpsState *gps_s)
Get GPS ecef velocity (integer) Converted on the fly if not available.
struct NedCoor_f ned_vel_float_from_gps (struct GpsState *gps_s)
Get GPS ned velocity (float) Converted on the fly if not available.
struct NedCoor_i ned_vel_int_from_gps (struct GpsState *gps_s)
Get GPS ned velocity (integer) Converted on the fly if not available.
struct UtmCoor_f utm_float_from_gps (struct GpsState *gps_s, uint8_t zone)
Convenience functions to get utm position from GPS state.
struct UtmCoor_i utm_int_from_gps (struct GpsState *gps_s, uint8_t zone)
Convenience function to get utm position in int from GPS structure.
uint16_t gps_day_number (uint16_t year, uint8_t month, uint8_t day)
Number of days since navigation epoch (6 January 1980)
uint16_t gps_week_number (uint16_t year, uint8_t month, uint8_t day)
Number of weeks since navigation epoch (6 January 1980)
Variables
struct GpsState gps
global GPS state
struct GpsTimeSync gps_time_sync
static struct RelPosNED gps_relposned [GPS_RELPOS_MAX] = {0}
uint8_t multi_gps_mode
int gps_disable_fix = 0
Disable fix.
static abi_event gps_ev
static abi_event gps_relpos_ev
static const uint16_t month_days [2][13]
GPS week number roll-over workaround application note.
Detailed Description
Device independent GPS code.
This provides some general GPS functions and handles the selection of the currently active GPS (if multiple ones are used).
Each GPS implementation sends a GPS message via ABI for each new measurement, which can be received by any other part (either from all or only one specific GPS).
To make it easy to switch to the currently best (or simply the preferred) GPS at runtime, the multi_gps_mode can be set to GPS_MODE_PRIMARY, GPS_MODE_SECONDARY or GPS_MODE_AUTO. This re-sends the GPS message of the "selected" GPS with GPS_MULTI_ID as sender id. In the (default) GPS_MODE_AUTO mode, the GPS with the best fix is selected.
The global gps struct is also updated from the "selected" GPS and used to send the normal GPS telemetry messages.
Definition in file gps.c.
Macro Definition Documentation
GPS_RELPOS_MAX
#define GPS_RELPOS_MAX 3
Definition at line 68 of file gps.c.
MSEC_PER_WEEK
#define MSEC_PER_WEEK (1000*60*60*24*7)
Definition at line 71 of file gps.c.
TIME_TO_SWITCH
#define TIME_TO_SWITCH 5000
Definition at line 72 of file gps.c.
Function Documentation
ecef_float_from_gps()
struct EcefCoor_f ecef_float_from_gps (struct GpsState * gps_s)
Get GPS ecef pos (float) Converted on the fly if not available.
Parameters
[in] gps_s pointer to the gps structure
Returns
ecef position in float (m)
Definition at line 506 of file gps.c.
References ECEF_FLOAT_OF_BFP, ecef_int_from_gps(), and foo.
ecef_int_from_gps()
struct EcefCoor_i ecef_int_from_gps (struct GpsState * gps_s)
Get GPS ecef pos (integer) Converted on the fly if not available.
Parameters
[in] gps_s pointer to the gps structure
Returns
ecef position in cm
Definition at line 519 of file gps.c.
References ecef_of_lla_i(), foo, GPS_VALID_POS_ECEF_BIT, and GPS_VALID_POS_LLA_BIT.
Referenced by ecef_float_from_gps(), gps_cb(), gps_cb(), ins_float_invariant_reset_ref(), ins_float_invariant_update_gps(), ins_int_update_gps(), reset_ref(), reset_ref(), and reset_ref().
ecef_vel_float_from_gps()
struct EcefCoor_f ecef_vel_float_from_gps (struct GpsState * gps_s)
Get GPS ecef velocity (float) Converted on the fly if not available.
Parameters
[in] gps_s pointer to the gps structure
Returns
ecef velocity in float (m/s)
Definition at line 535 of file gps.c.
References ECEF_FLOAT_OF_BFP, ecef_vel_int_from_gps(), and foo.
Referenced by gps_cb(), and ins_float_invariant_update_gps().
ecef_vel_int_from_gps()
struct EcefCoor_i ecef_vel_int_from_gps (struct GpsState * gps_s)
Get GPS ecef velocity (integer) Converted on the fly if not available.
Parameters
[in] gps_s pointer to the gps structure
Returns
ecef velocity in cm/s
Definition at line 548 of file gps.c.
References ecef_of_ned_vect_i(), foo, GPS_VALID_POS_LLA_BIT, GPS_VALID_VEL_ECEF_BIT, GPS_VALID_VEL_NED_BIT, ltp_def_from_ecef_i(), and ltp_def_from_lla_i().
Referenced by ecef_vel_float_from_gps(), gps_cb(), and ins_int_update_gps().
gps_cb()
static void gps_cb (uint8_t sender_id, uint32_t stamp , struct GpsState * gps_s) static
Definition at line 319 of file gps.c.
References GpsState::fix, foo, get_sys_time_usec(), gps, gps_disable_fix, GPS_FIX_NONE, GPS_MULTI_ID, gps_time_sync, sys_time::nb_tick, GpsTimeSync::t0_ticks, GpsTimeSync::t0_tow, and GpsState::tow.
Referenced by gps_init().
gps_day_number()
uint16_t gps_day_number (uint16_t year, uint8_t month, uint8_t day)
Number of days since navigation epoch (6 January 1980)
Parameters
[in] year current year
[in] month current month
[in] day current day
Returns
number of days since navigation epoch
Definition at line 665 of file gps.c.
References foo, and month_days.
Referenced by gps_week_number().
gps_fix_valid()
bool gps_fix_valid (void)
Check if GPS fix is valid.
If GPS_FIX_TIMEOUT is configured, check for 3D fix with timeout, otherwise, returns the last value from GPS module
Definition at line 306 of file gps.c.
References GpsState::fix, foo, get_sys_time_float(), gps, GPS_FIX_3D, and gps_time_since_last_3dfix().
gps_init()
void gps_init (void)
initialize the global GPS state
Definition at line 375 of file gps.c.
References ABI_BROADCAST, GpsState::cacc, DefaultPeriodic, GpsState::fix, foo, gpio_setup_output(), gps, gps_cb(), gps_disable_fix, gps_ev, GPS_FIX_NONE, GPS_POWER_GPIO, gps_relpos_cb(), gps_relpos_ev, GpsState::hacc, GpsState::last_3dfix_ticks, GpsState::last_3dfix_time, GpsState::last_msg_ticks, GpsState::last_msg_time, LED_OFF, multi_gps_mode, MULTI_GPS_MODE, preflight_check_register(), register_periodic_telemetry(), send_gps(), send_gps_int(), send_gps_lla(), send_gps_relpos(), send_gps_sol(), send_svinfo(), GpsState::tow, GpsState::vacc, GpsState::valid_fields, and GpsState::week.
gps_inject_data()
void WEAK gps_inject_data (uint8_t packet_id, uint8_t length, uint8_t * data)
Default parser for GPS injected data.
GPS packet injection (default empty)
Definition at line 444 of file gps.c.
Referenced by gps_parse_GPS_INJECT(), and gps_parse_RTCM_INJECT().
gps_parse_GPS_INJECT()
void gps_parse_GPS_INJECT (uint8_t * buf)
Definition at line 450 of file gps.c.
References foo, and gps_inject_data().
gps_parse_RTCM_INJECT()
void gps_parse_RTCM_INJECT (uint8_t * buf)
Definition at line 463 of file gps.c.
References foo, and gps_inject_data().
gps_periodic_check()
void gps_periodic_check (struct GpsState * gps_s)
Periodic GPS check.
Marks GPS as lost when no GPS message was received for GPS_TIMEOUT seconds
Definition at line 290 of file gps.c.
References foo, gps, GPS_FIX_NONE, GPS_TIMEOUT, and sys_time::nb_sec.
Referenced by dw1000_arduino_periodic(), and gps_ubx_periodic_check().
gps_periodic_fix_counter()
void gps_periodic_fix_counter (void)
Increment periodic counter.
Definition at line 85 of file gps.c.
References gps_disable_fix.
gps_relpos_cb()
static void gps_relpos_cb (uint8_t sender_id, uint32_t stamp, struct RelPosNED * relpos) static
Definition at line 359 of file gps.c.
References foo, GPS_RELPOS_MAX, gps_relposned, and RelPosNED::reference_id.
Referenced by gps_init().
gps_tow_from_sys_ticks()
uint32_t gps_tow_from_sys_ticks (uint32_t sys_ticks)
Convert time in sys_time ticks to GPS time of week.
The resolution is sys_time.resolution
Returns
GPS tow in ms
Definition at line 419 of file gps.c.
References foo, gps_time_sync, msec_of_sys_time_ticks(), MSEC_PER_WEEK, GpsTimeSync::t0_ticks, and GpsTimeSync::t0_tow.
Referenced by acInfoSetPositionEnu_f(), acInfoSetPositionEnu_i(), acInfoSetPositionLla_f(), acInfoSetPositionLla_i(), acInfoSetPositionUtm_f(), acInfoSetPositionUtm_i(), acInfoSetVelocityEnu_f(), acInfoSetVelocityEnu_i(), parse_acinfo_dl(), target_parse_target_pos(), and windturbine_periodic().
gps_week_number()
uint16_t gps_week_number (uint16_t year, uint8_t month, uint8_t day)
Number of weeks since navigation epoch (6 January 1980)
Parameters
[in] year current year
[in] month current month
[in] day current day
Returns
number of weeks since navigation epoch
Definition at line 675 of file gps.c.
References gps_day_number().
Referenced by gps_ubx_parse_nav_pvt().
lla_float_from_gps()
struct LlaCoor_f lla_float_from_gps (struct GpsState * gps_s)
Get GPS lla (float) Converted on the fly if not available.
Parameters
[in] gps_s pointer to the gps structure
Returns
lla position in float (rad), altitude ellipsoid (m)
Definition at line 477 of file gps.c.
References foo, LLA_FLOAT_OF_BFP, and lla_int_from_gps().
lla_int_from_gps()
struct LlaCoor_i lla_int_from_gps (struct GpsState * gps_s)
Get GPS lla (integer) Converted on the fly if not available.
Parameters
[in] gps_s pointer to the gps structure
Returns
lla position (lat,lon: deg*1e7; alt: mm over ellipsoid)
Definition at line 490 of file gps.c.
References foo, GPS_VALID_POS_ECEF_BIT, GPS_VALID_POS_LLA_BIT, and lla_of_ecef_i().
Referenced by gps_cb(), ins_float_invariant_reset_ref(), lla_float_from_gps(), reset_ref(), reset_ref(), reset_ref(), reset_ref(), reset_vertical_ref(), and reset_vertical_ref().
ned_vel_float_from_gps()
struct NedCoor_f ned_vel_float_from_gps (struct GpsState * gps_s)
Get GPS ned velocity (float) Converted on the fly if not available.
Parameters
[in] gps_s pointer to the gps structure
Returns
ned velocity in float (m/s)
Definition at line 570 of file gps.c.
References foo, ned_vel_int_from_gps(), and VECT3_FLOAT_OF_CM.
Referenced by gps_cb(), gps_cb(), gps_cb(), gps_cb(), gps_cb(), ins_alt_float_update_gps(), and ins_float_invariant_update_gps().
ned_vel_int_from_gps()
struct NedCoor_i ned_vel_int_from_gps (struct GpsState * gps_s)
Get GPS ned velocity (integer) Converted on the fly if not available.
Parameters
[in] gps_s pointer to the gps structure
Returns
ned velocity in cm/s
Definition at line 583 of file gps.c.
References foo, GPS_VALID_POS_LLA_BIT, GPS_VALID_VEL_ECEF_BIT, GPS_VALID_VEL_NED_BIT, ltp_def_from_ecef_i(), ltp_def_from_lla_i(), and ned_of_ecef_vect_i().
Referenced by ned_vel_float_from_gps().
send_gps()
static void send_gps (struct transport_tx * trans, struct link_device * dev) static
Definition at line 153 of file gps.c.
References GpsState::course, course, dev, GpsState::fix, foo, gps, gps_disable_fix, GpsState::gspeed, GpsState::hmsl, msg, GpsState::ned_vel, send_svinfo_available(), GpsState::tow, utm_int_from_gps(), GpsState::week, and NedCoor_i::z.
Referenced by gps_init().
send_gps_int()
static void send_gps_int (struct transport_tx * trans, struct link_device * dev) static
Definition at line 201 of file gps.c.
References LlaCoor_i::alt, GpsState::comp_id, dev, GpsState::ecef_pos, GpsState::ecef_vel, GpsState::fix, foo, gps, GpsState::hmsl, LlaCoor_i::lat, GpsState::lla_pos, LlaCoor_i::lon, msg, GpsState::num_sv, GpsState::pacc, GpsState::pdop, GpsState::sacc, send_svinfo_available(), GpsState::tow, EcefCoor_i::x, EcefCoor_i::y, and EcefCoor_i::z.
Referenced by gps_init().
send_gps_lla()
static void send_gps_lla (struct transport_tx * trans, struct link_device * dev) static
Definition at line 229 of file gps.c.
References LlaCoor_i::alt, GpsState::course, course, dev, GpsState::fix, foo, gps, GpsState::gspeed, GpsState::hmsl, LlaCoor_i::lat, GpsState::lla_pos, LlaCoor_i::lon, msg, GpsState::ned_vel, GpsState::tow, GpsState::week, and NedCoor_i::z.
Referenced by gps_init().
send_gps_relpos()
static void send_gps_relpos (struct transport_tx * trans, struct link_device * dev) static
Definition at line 179 of file gps.c.
References dev, RelPosNED::distance, RelPosNED::distance_acc, foo, GPS_RELPOS_MAX, gps_relposned, RelPosNED::heading, RelPosNED::heading_acc, idx, RelPosNED::pos, RelPosNED::pos_acc, NedCoor_f::x, NedCoor_d::y, NedCoor_f::y, NedCoor_d::z, and NedCoor_f::z.
Referenced by gps_init().
send_gps_sol()
static void send_gps_sol (struct transport_tx * trans, struct link_device * dev) static
Definition at line 252 of file gps.c.
References dev, foo, gps, GpsState::num_sv, GpsState::pacc, GpsState::pdop, and GpsState::sacc.
Referenced by gps_init().
send_svinfo()
static void send_svinfo (struct transport_tx * trans, struct link_device * dev) static
send SVINFO message (regardless of state)
Definition at line 125 of file gps.c.
References dev, gps, GpsState::nb_channels, and send_svinfo_id().
Referenced by gps_init().
send_svinfo_available()
static void send_svinfo_available (struct transport_tx * trans, struct link_device * dev) inline static
send SVINFO message if updated.
send SVINFO for all satellites while no GPS fix, after 3D fix, send avialable sats only when there is new information
Definition at line 137 of file gps.c.
References SVinfo::cno, dev, GpsState::fix, foo, gps, GPS_FIX_3D, GPS_NB_CHANNELS, GpsState::nb_channels, send_svinfo_id(), and GpsState::svinfos.
Referenced by send_gps(), and send_gps_int().
send_svinfo_id()
static void send_svinfo_id (struct transport_tx * trans, struct link_device * dev, uint8_t svid) static
Definition at line 113 of file gps.c.
References SVinfo::azim, SVinfo::cno, dev, SVinfo::elev, SVinfo::flags, foo, gps, GPS_NB_CHANNELS, SVinfo::qi, SVinfo::svid, and GpsState::svinfos.
Referenced by send_svinfo(), and send_svinfo_available().
utm_float_from_gps()
struct UtmCoor_f utm_float_from_gps (struct GpsState * gps_s, uint8_t zone)
Convenience functions to get utm position from GPS state.
Convenience function to get utm position in float from GPS structure.
Definition at line 603 of file gps.c.
References UtmCoor_f::east, foo, GPS_VALID_HMSL_BIT, GPS_VALID_POS_LLA_BIT, GPS_VALID_POS_UTM_BIT, UTM_FLOAT_OF_BFP, utm_of_lla_i(), wgs84_ellipsoid_to_geoid_i(), UtmCoor_f::zone, and UtmCoor_i::zone.
Referenced by gps_cb(), gps_cb(), gps_cb(), gps_cb(), ins_alt_float_update_gps(), ins_float_invariant_reset_ref(), ins_float_invariant_update_gps(), reset_ref(), reset_ref(), and reset_ref().
utm_int_from_gps()
struct UtmCoor_i utm_int_from_gps (struct GpsState * gps_s, uint8_t zone)
Convenience function to get utm position in int from GPS structure.
Beware that altitude is initialized to zero but not set to the correct value
Parameters
[in] gps_s pointer to the gps structure
[in] zone set the utm zone in which the position should be computed, 0 to try to get it automatically from lla position
Returns
utm position in fixed point (cm), altitude hmsl (mm).
Definition at line 628 of file gps.c.
References UtmCoor_i::east, foo, GPS_VALID_HMSL_BIT, GPS_VALID_POS_LLA_BIT, GPS_VALID_POS_UTM_BIT, UTM_COPY, utm_of_lla_i(), wgs84_ellipsoid_to_geoid_i(), and UtmCoor_i::zone.
Referenced by send_gps().
Variable Documentation
gps
struct GpsState gps
global GPS state
Definition at line 74 of file gps.c.
Referenced by airspeed_ets_read_event(), alt_filter_periodic(), apogee_baro_event(), ArduIMU_periodicGPS(), autopilot_failsafe_checks(), baro_sim_periodic(), calculate_new_heading(), cloud_sensor_callback(), draw_osd(), error_output(), formation_flight(), generic_com_periodic(), geo_mag_event(), get_fix_mode(), gps_cb(), gps_fix_valid(), gps_init(), gps_periodic_check(), gps_sim_init(), gps_sim_publish(), gps_time_since_last_3dfix(), gps_vectornav_init(), gsm_send_report_continue(), hff_update_gps(), home_direction(), humid_sht_periodic(), ins_float_invariant_reset_ref(), ins_float_invariant_reset_vertical_ref(), ins_vectornav_monitor(), ins_vectornav_propagate(), ins_vectornav_set_pacc(), ins_vectornav_set_sacc(), mavlink_send_gps_raw_int(), mavlink_send_gps_status(), meteo_stick_send_data(), mf_daq_send_report(), mf_ptu_periodic(), nav_reset_utm_zone(), nps_sensor_gps_init(), nps_sensor_gps_run_step(), parse_xsens_msg(), potential_task(), push_gps_to_vision(), put_alt(), reset_cb(), reset_ref(), reset_ref(), reset_ref(), reset_ref(), reset_ref(), reset_ref(), reset_vertical_ref(), reset_vertical_ref(), reset_vertical_ref(), reset_vertical_ref(), reset_vertical_ref(), reset_vertical_ref(), send_cloud_sensor_data(), send_fp_min(), send_gps(), send_gps_int(), send_gps_lla(), send_gps_sol(), send_minimal_com(), send_status(), send_svinfo(), send_svinfo_available(), send_svinfo_id(), sim_overwrite_lidar(), snav_on_time(), tcas_periodic_task_1Hz(), temod_event(), thd_startlog(), and update_geoid_height().
gps_disable_fix
int gps_disable_fix = 0
Disable fix.
Definition at line 83 of file gps.c.
Referenced by gps_cb(), gps_init(), gps_periodic_fix_counter(), and send_gps().
gps_ev
abi_event gps_ev static
Definition at line 318 of file gps.c.
Referenced by gps_init().
gps_relpos_ev
abi_event gps_relpos_ev static
Definition at line 358 of file gps.c.
Referenced by gps_init().
gps_relposned
struct RelPosNED gps_relposned[GPS_RELPOS_MAX] = {0} static
Definition at line 76 of file gps.c.
Referenced by gps_relpos_cb(), and send_gps_relpos().
gps_time_sync
struct GpsTimeSync gps_time_sync
Definition at line 75 of file gps.c.
Referenced by gps_cb(), and gps_tow_from_sys_ticks().
month_days
const uint16_t month_days[2][13] static
Initial value:
= {
  { 0, 31, 59, 90, 120, 151, 181, 212, 243, 273, 304, 334, 365 },
  { 0, 31, 60, 91, 121, 152, 182, 213, 244, 274, 305, 335, 366 }
}
GPS week number roll-over workaround application note.
Definition at line 657 of file gps.c.
Referenced by gps_day_number().
multi_gps_mode
uint8_t multi_gps_mode
Definition at line 82 of file gps.c.
Referenced by gps_init().