Paparazzi UAS: sw/airborne/subsystems/gps/gps_sim_hitl.c File Reference
gps_sim_hitl.c File Reference
GPS subsystem simulation from rotorcrafts horizontal/vertical reference system.
#include "subsystems/gps/gps_sim_hitl.h"
#include "subsystems/gps.h"
#include "subsystems/abi.h"
#include "state.h"
#include "guidance/guidance_h.h"
#include "guidance/guidance_v.h"
#include "autopilot.h"
Functions
void gps_sim_hitl_init (void)
void gps_sim_hitl_event (void)
Variables
bool gps_available
uint32_t gps_sim_hitl_timer
Detailed Description
GPS subsystem simulation from rotorcrafts horizontal/vertical reference system.
Definition in file gps_sim_hitl.c.
Function Documentation
void gps_sim_hitl_event (void)
Definition at line 44 of file gps_sim_hitl.c.
References HorizontalGuidanceReference::accel, LlaCoor_i::alt, autopilot_in_flight(), ecef_of_ned_point_i(), ecef_of_ned_vect_i(), GpsState::ecef_pos, GpsState::ecef_vel, GpsState::fix, get_sys_time_usec(), gh_set_ref(), gps, gps_available, GPS_FIX_3D, gps_sim_hitl_timer, GPS_SIM_ID, guidance_h, guidance_v_z_ref, guidance_v_zd_ref, guidance_v_zdd_ref, gv_set_ref(), GpsState::hmsl, LtpDef_i::hmsl, INT32_POS_OF_CM_DEN, INT32_POS_OF_CM_NUM, INT32_SPEED_OF_CM_S_DEN, INT32_SPEED_OF_CM_S_NUM, INT_VECT2_ZERO, GpsState::last_3dfix_ticks, GpsState::last_3dfix_time, GpsState::last_msg_ticks, GpsState::last_msg_time, LtpDef_i::lla, GpsState::lla_pos, sys_time::nb_sec, sys_time::nb_sec_rem, State::ned_initialized_i, State::ned_origin_i, HorizontalGuidanceReference::pos, HorizontalGuidance::ref, HorizontalGuidanceReference::speed, state, SysTimeTimer, SysTimeTimerStart, NedCoor_i::x, Int32Vect2::x, NedCoor_i::y, Int32Vect2::y, and NedCoor_i::z.
void gps_sim_hitl_init (void)
Definition at line 39 of file gps_sim_hitl.c.
References GpsState::fix, gps, and GPS_FIX_NONE.
Variable Documentation
bool gps_available
Definition at line 36 of file gps_sim_hitl.c.
Referenced by gps_sim_hitl_event().
uint32_t gps_sim_hitl_timer
Definition at line 37 of file gps_sim_hitl.c.
Referenced by gps_sim_hitl_event().