Paparazzi UAS: sw/airborne/modules/gps/gps_datalink.h File Reference
gps_datalink.h File Reference
GPS system based on datalink.
#include "std.h"
#include "generated/airframe.h"
#include "modules/gps/gps.h"
Macros
#define PRIMARY_GPS GPS_DATALINK
#define gps_datalink_periodic_check() gps_periodic_check(&gps_datalink)
Functions
void gps_datalink_init (void)
GPS initialization.
void gps_datalink_parse_EXTERNAL_POSE (uint8_t *buf)
Parse the full EXTERNAL_POSE message and publish as GPS through ABI.
void gps_datalink_parse_EXTERNAL_POSE_SMALL (uint8_t *buf)
Parse the EXTERNAL_POSE_SMALL message and publish as GPS through ABI.
void gps_datalink_parse_REMOTE_GPS_LOCAL (uint8_t *buf)
Variables
struct GpsState gps_datalink
Detailed Description
GPS system based on datalink.
This GPS parses the datalink REMOTE_GPS packet and sets the GPS structure to the values received.
Definition in file gps_datalink.h.
Macro Definition Documentation
gps_datalink_periodic_check
#define gps_datalink_periodic_check () gps_periodic_check(&gps_datalink)
Definition at line 45 of file gps_datalink.h.
PRIMARY_GPS
#define PRIMARY_GPS GPS_DATALINK
Definition at line 38 of file gps_datalink.h.
Function Documentation
gps_datalink_init()
void gps_datalink_init (void) extern
GPS initialization.
Definition at line 51 of file gps_datalink.c.
References GpsState::cacc, GpsState::comp_id, GpsState::fix, foo, gps_datalink, GPS_DATALINK_ID, GPS_FIX_NONE, LlaCoor_i::lat, ltp_def, ltp_def_from_lla_i(), GpsState::pacc, GpsState::pdop, and GpsState::sacc.
gps_datalink_parse_EXTERNAL_POSE()
void gps_datalink_parse_EXTERNAL_POSE (uint8_t * buf) extern
Parse the full EXTERNAL_POSE message and publish as GPS through ABI.
Definition at line 123 of file gps_datalink.c.
References float_eulers_of_quat(), foo, gps_datalink_publish(), heading, FloatQuat::qi, and EnuCoor_f::x.
gps_datalink_parse_EXTERNAL_POSE_SMALL()
void gps_datalink_parse_EXTERNAL_POSE_SMALL (uint8_t * buf) extern
Parse the EXTERNAL_POSE_SMALL message and publish as GPS through ABI.
Definition at line 151 of file gps_datalink.c.
References EXTERNAL_POSE_SMALL_POS_RES, EXTERNAL_POSE_SMALL_SPEED_RES, foo, gps_datalink_publish(), and heading.
gps_datalink_parse_REMOTE_GPS_LOCAL()
void gps_datalink_parse_REMOTE_GPS_LOCAL (uint8_t * buf) extern
Definition at line 203 of file gps_datalink.c.
References course, foo, gps_datalink_publish(), and EnuCoor_f::x.
Variable Documentation
gps_datalink
struct GpsState gps_datalink extern
Definition at line 47 of file gps_datalink.c.
Referenced by gps_datalink_init(), and gps_datalink_publish().