Paparazzi UAS: Acceleration representations
Acceleration representations
State interface
Macros
#define ACCEL_ECEF_I 0
#define ACCEL_NED_I 1
#define ACCEL_ECEF_F 2
#define ACCEL_NED_F 3
Functions
void stateCalcAccelNed_i (void)
void stateCalcAccelEcef_i (void)
void stateCalcAccelNed_f (void)
void stateCalcAccelEcef_f (void)
static bool stateIsAccelValid (void)
Test if accelerations are valid.
static void stateSetAccelNed_i (uint16_t id, struct NedCoor_i *ned_accel)
Set acceleration in NED coordinates (int).
static void stateSetAccelEcef_i (uint16_t id, struct EcefCoor_i *ecef_accel)
Set acceleration in ECEF coordinates (int).
static void stateSetAccelNed_f (uint16_t id, struct NedCoor_f *ned_accel)
Set acceleration in NED coordinates (float).
static void stateSetAccelEcef_f (uint16_t id, struct EcefCoor_f *ecef_accel)
Set acceleration in ECEF coordinates (float).
static void stateSetAccelBody_i (uint16_t id, struct Int32Vect3 *body_accel)
Set acceleration in Body coordinates (int).
static struct NedCoor_i * stateGetAccelNed_i (void)
Get acceleration in NED coordinates (int).
static struct EcefCoor_i * stateGetAccelEcef_i (void)
Get acceleration in ECEF coordinates (int).
static struct NedCoor_f * stateGetAccelNed_f (void)
Get acceleration in NED coordinates (float).
static struct EcefCoor_f * stateGetAccelEcef_f (void)
Get acceleration in ECEF coordinates (float).
Variables
uint8_t State::accel_status
Holds the status bits for all acceleration representations.
uint16_t State::accel_input_filter
Holds the input filter id for acceleration.
struct Int32Vect3 State::body_accel_i
Acceleration in Body coordinates.
struct NedCoor_i State::ned_accel_i
Acceleration in North East Down coordinates.
struct EcefCoor_i State::ecef_accel_i
Acceleration in EarthCenteredEarthFixed coordinates.
struct NedCoor_f State::ned_accel_f
Acceleration in North East Down coordinates.
struct EcefCoor_f State::ecef_accel_f
Acceleration in EarthCenteredEarthFixed coordinates.
Detailed Description
Macro Definition Documentation
ACCEL_ECEF_F
#define ACCEL_ECEF_F 2
Definition at line 108 of file state.h.
ACCEL_ECEF_I
#define ACCEL_ECEF_I 0
Definition at line 106 of file state.h.
ACCEL_NED_F
#define ACCEL_NED_F 3
Definition at line 109 of file state.h.
ACCEL_NED_I
#define ACCEL_NED_I 1
Definition at line 107 of file state.h.
Function Documentation
stateCalcAccelEcef_f()
void stateCalcAccelEcef_f (void)
Definition at line 1315 of file state.c.
References ACCEL_ECEF_F, ACCEL_ECEF_I, ACCEL_NED_F, ACCEL_NED_I, State::accel_status, ACCELS_FLOAT_OF_BFP, State::ecef_accel_f, ecef_of_ned_vect_f(), foo, State::ned_accel_f, State::ned_accel_i, State::ned_initialized_f, State::ned_origin_f, and state.
Referenced by stateGetAccelEcef_f().
stateCalcAccelEcef_i()
void stateCalcAccelEcef_i (void)
Definition at line 1250 of file state.c.
References ACCEL_ECEF_F, ACCEL_ECEF_I, ACCEL_NED_F, ACCEL_NED_I, State::accel_status, ACCELS_BFP_OF_REAL, State::ecef_accel_f, State::ecef_accel_i, ecef_of_ned_vect_i(), foo, State::ned_accel_f, State::ned_accel_i, State::ned_initialized_i, State::ned_origin_i, and state.
Referenced by stateGetAccelEcef_i().
stateCalcAccelNed_f()
void stateCalcAccelNed_f (void)
Definition at line 1282 of file state.c.
References ACCEL_ECEF_F, ACCEL_ECEF_I, ACCEL_NED_F, ACCEL_NED_I, State::accel_status, ACCELS_FLOAT_OF_BFP, State::ecef_accel_f, State::ecef_accel_i, foo, State::ned_accel_f, State::ned_accel_i, State::ned_initialized_f, ned_of_ecef_vect_f(), State::ned_origin_f, and state.
Referenced by stateGetAccelNed_f().
stateCalcAccelNed_i()
void stateCalcAccelNed_i (void)
Definition at line 1217 of file state.c.
References ACCEL_ECEF_F, ACCEL_ECEF_I, ACCEL_NED_F, ACCEL_NED_I, State::accel_status, ACCELS_BFP_OF_REAL, State::ecef_accel_f, State::ecef_accel_i, foo, State::ned_accel_f, State::ned_accel_i, State::ned_initialized_i, ned_of_ecef_vect_i(), State::ned_origin_i, and state.
Referenced by stateGetAccelNed_i().
stateGetAccelEcef_f()
static struct EcefCoor_f * stateGetAccelEcef_f (void) inline static
Get acceleration in ECEF coordinates (float).
Definition at line 1212 of file state.h.
References ACCEL_ECEF_F, State::accel_status, State::ecef_accel_f, foo, state, and stateCalcAccelEcef_f().
stateGetAccelEcef_i()
static struct EcefCoor_i * stateGetAccelEcef_i (void) inline static
Get acceleration in ECEF coordinates (int).
Definition at line 1194 of file state.h.
References ACCEL_ECEF_I, State::accel_status, State::ecef_accel_i, foo, state, and stateCalcAccelEcef_i().
stateGetAccelNed_f()
static struct NedCoor_f * stateGetAccelNed_f (void) inline static
Get acceleration in NED coordinates (float).
Definition at line 1203 of file state.h.
References ACCEL_NED_F, State::accel_status, foo, State::ned_accel_f, state, and stateCalcAccelNed_f().
Referenced by autopilot_ground_detection(), autopilot_in_flight_end_detection(), decawave_anchorless_communication_periodic(), ground_detect_filter_accel(), ground_detect_periodic(), guidance_indi_propagate_filters(), guidance_indi_propagate_filters(), mf_daq_send_state(), nav_catapult_highrate_module(), oneloop_andi_propagate_filters(), parse_mf_daq_msg(), range_msg_callback(), and wind_estimator_periodic().
stateGetAccelNed_i()
static struct NedCoor_i * stateGetAccelNed_i (void) inline static
Get acceleration in NED coordinates (int).
Definition at line 1185 of file state.h.
References ACCEL_NED_I, State::accel_status, foo, State::ned_accel_i, state, and stateCalcAccelNed_i().
Referenced by ekf_aw_wrapper_fetch(), guidance_v_thrust_adapt(), ins_vectornav_propagate(), save_shot_on_disk(), send_hover_loop(), send_vert_loop(), and stabilization_attitude_run().
stateIsAccelValid()
static bool stateIsAccelValid (void) inline static
Test if accelerations are valid.
Definition at line 1127 of file state.h.
References State::accel_status, and state.
stateSetAccelBody_i()
static void stateSetAccelBody_i (uint16_t id, struct Int32Vect3 * body_accel) inline static
Set acceleration in Body coordinates (int).
Definition at line 1175 of file state.h.
References State::accel_input_filter, State::body_accel_i, state, STATE_CHECK_INPUT_AND_RETURN, and VECT3_COPY.
Referenced by accel_cb(), accel_cb(), ekf_run(), ins_ekf2_publish_attitude(), ins_float_invariant_propagate(), ins_int_propagate(), and ins_module_propagate().
stateSetAccelEcef_f()
static void stateSetAccelEcef_f (uint16_t id, struct EcefCoor_f * ecef_accel) inline static
Set acceleration in ECEF coordinates (float).
Definition at line 1165 of file state.h.
References ACCEL_ECEF_F, State::accel_input_filter, State::accel_status, State::ecef_accel_f, foo, state, STATE_CHECK_INPUT_AND_RETURN, and VECT3_COPY.
stateSetAccelEcef_i()
static void stateSetAccelEcef_i (uint16_t id, struct EcefCoor_i * ecef_accel) inline static
Set acceleration in ECEF coordinates (int).
Definition at line 1145 of file state.h.
References ACCEL_ECEF_I, State::accel_input_filter, State::accel_status, State::ecef_accel_i, foo, state, STATE_CHECK_INPUT_AND_RETURN, and VECT3_COPY.
stateSetAccelNed_f()
static void stateSetAccelNed_f (uint16_t id, struct NedCoor_f * ned_accel) inline static
Set acceleration in NED coordinates (float).
Definition at line 1155 of file state.h.
References State::accel_input_filter, ACCEL_NED_F, State::accel_status, foo, State::ned_accel_f, state, STATE_CHECK_INPUT_AND_RETURN, and VECT3_COPY.
Referenced by ArduIMU_event(), ekf_run(), ins_ekf2_update(), ins_float_invariant_propagate(), ins_vectornav_propagate(), set_state_from_ins(), and sim_overwrite_ins().
stateSetAccelNed_i()
static void stateSetAccelNed_i (uint16_t id, struct NedCoor_i * ned_accel) inline static
Set acceleration in NED coordinates (int).
Definition at line 1135 of file state.h.
References State::accel_input_filter, ACCEL_NED_I, State::accel_status, foo, State::ned_accel_i, state, STATE_CHECK_INPUT_AND_RETURN, and VECT3_COPY.
Referenced by accel_cb(), accel_cb(), ins_ned_to_state(), and ins_ned_to_state().
Variable Documentation
accel_input_filter
uint16_t State::accel_input_filter
Holds the input filter id for acceleration.
Definition at line 370 of file state.h.
Referenced by stateInit(), stateSetAccelBody_i(), stateSetAccelEcef_f(), stateSetAccelEcef_i(), stateSetAccelNed_f(), stateSetAccelNed_i(), and stateSetInputFilter().
accel_status
uint8_t State::accel_status
Holds the status bits for all acceleration representations.
When the corresponding bit is one the representation is already computed.
Definition at line 365 of file state.h.
Referenced by stateCalcAccelEcef_f(), stateCalcAccelEcef_i(), stateCalcAccelNed_f(), stateCalcAccelNed_i(), stateGetAccelEcef_f(), stateGetAccelEcef_i(), stateGetAccelNed_f(), stateGetAccelNed_i(), stateInit(), stateIsAccelValid(), stateSetAccelEcef_f(), stateSetAccelEcef_i(), stateSetAccelNed_f(), stateSetAccelNed_i(), stateSetLocalOrigin_i(), and stateSetLocalUtmOrigin_f().
body_accel_i
struct Int32Vect3 State::body_accel_i
Acceleration in Body coordinates.
Units: m/s^2 in BFP with INT32_ACCEL_FRAC
Definition at line 376 of file state.h.
Referenced by stateGetAccelBody_f(), stateGetAccelBody_i(), and stateSetAccelBody_i().
ecef_accel_f
struct EcefCoor_f State::ecef_accel_f
Acceleration in EarthCenteredEarthFixed coordinates.
Units: m/s^2
Definition at line 400 of file state.h.
Referenced by stateCalcAccelEcef_f(), stateCalcAccelEcef_i(), stateCalcAccelNed_f(), stateCalcAccelNed_i(), stateGetAccelEcef_f(), and stateSetAccelEcef_f().
ecef_accel_i
struct EcefCoor_i State::ecef_accel_i
Acceleration in EarthCenteredEarthFixed coordinates.
Units: m/s^2 in BFP with INT32_ACCEL_FRAC
Definition at line 388 of file state.h.
Referenced by stateCalcAccelEcef_i(), stateCalcAccelNed_f(), stateCalcAccelNed_i(), stateGetAccelEcef_i(), and stateSetAccelEcef_i().
ned_accel_f
struct NedCoor_f State::ned_accel_f
Acceleration in North East Down coordinates.
Units: m/s^2
Definition at line 394 of file state.h.
Referenced by stateCalcAccelEcef_f(), stateCalcAccelEcef_i(), stateCalcAccelNed_f(), stateCalcAccelNed_i(), stateGetAccelNed_f(), and stateSetAccelNed_f().
ned_accel_i
struct NedCoor_i State::ned_accel_i
Acceleration in North East Down coordinates.
Units: m/s^2 in BFP with INT32_ACCEL_FRAC
Definition at line 382 of file state.h.
Referenced by stateCalcAccelEcef_f(), stateCalcAccelEcef_i(), stateCalcAccelNed_f(), stateCalcAccelNed_i(), stateGetAccelNed_i(), and stateSetAccelNed_i().