Paparazzi UAS: Angular rate representations
Angular rate representations
State interface
Macros
#define RATE_I 0
#define RATE_F 1
Functions
void stateCalcBodyRates_i (void)
void stateCalcBodyRates_f (void)
static bool stateIsRateValid (void)
Test if rates are valid.
static void stateSetBodyRates_i (uint16_t id, struct Int32Rates *body_rate)
Set vehicle body angular rate (int).
static void stateSetBodyRates_f (uint16_t id, struct FloatRates *body_rate)
Set vehicle body angular rate (float).
static struct Int32Rates * stateGetBodyRates_i (void)
Get vehicle body angular rate (int).
static struct FloatRates * stateGetBodyRates_f (void)
Get vehicle body angular rate (float).
Variables
uint8_t State::rate_status
Holds the status bits for all angular rate representations.
uint16_t State::rates_input_filter
Holds the input filter id for rates.
struct Int32Rates State::body_rates_i
Angular rates in body frame.
struct FloatRates State::body_rates_f
Angular rates in body frame.
Detailed Description
Macro Definition Documentation
RATE_F
#define RATE_F 1
Definition at line 117 of file state.h.
RATE_I
#define RATE_I 0
Definition at line 116 of file state.h.
Function Documentation
stateCalcBodyRates_f()
void stateCalcBodyRates_f (void)
Definition at line 1371 of file state.c.
References State::body_rates_f, State::body_rates_i, foo, RATE_F, RATE_I, State::rate_status, RATES_FLOAT_OF_BFP, and state.
Referenced by stateGetBodyRates_f().
stateCalcBodyRates_i()
void stateCalcBodyRates_i (void)
Definition at line 1356 of file state.c.
References State::body_rates_f, State::body_rates_i, foo, RATE_F, RATE_I, State::rate_status, RATES_BFP_OF_REAL, and state.
Referenced by stateGetBodyRates_i().
stateGetBodyRates_f()
static struct FloatRates * stateGetBodyRates_f (void) inline static
Get vehicle body angular rate (float).
Definition at line 1375 of file state.h.
References State::body_rates_f, foo, RATE_F, State::rate_status, state, and stateCalcBodyRates_f().
Referenced by CN_potential_heading(), CN_potential_velocity(), decawave_anchorless_communication_periodic(), ekf_aw_wrapper_fetch(), h_ctl_pitch_loop(), h_ctl_roll_loop(), indi_init_filters(), init_filters(), lms_estimation(), logger_file_write_row(), mavlink_send_attitude(), mavlink_send_attitude(), mavlink_send_attitude_quaternion(), mavlink_send_highres_imu(), mf_daq_send_state(), oneloop_andi_propagate_filters(), opticflow_pmw3901_publish(), parse_mf_daq_msg(), pose_periodic(), print_true_state(), process_data(), range_msg_callback(), rover_guidance_run(), rover_holo_guidance_run(), send_att(), send_att(), send_att(), send_att_full_indi(), send_body_rates_accel(), send_ins_flow(), send_tune_roll(), stabilization_andi_enter(), stabilization_andi_run(), stabilization_attitude_plane_pid_run(), stabilization_attitude_run(), stabilization_attitude_run(), stabilization_indi_rate_run(), stabilization_indi_simple_reset_r_filter_cutoff(), stabilization_indi_update_filt_freq(), stabilization_rate_run(), and wind_estimator_periodic().
stateGetBodyRates_i()
static struct Int32Rates * stateGetBodyRates_i (void) inline static
Get vehicle body angular rate (int).
Definition at line 1366 of file state.h.
References State::body_rates_i, foo, RATE_I, State::rate_status, state, and stateCalcBodyRates_i().
Referenced by ctrl_module_run(), logger_control_effectiveness_periodic(), send_att(), send_att(), stabilization_attitude_run(), and stabilization_attitude_run().
stateIsRateValid()
static bool stateIsRateValid (void) inline static
Test if rates are valid.
Definition at line 1336 of file state.h.
References State::rate_status, and state.
stateSetBodyRates_f()
static void stateSetBodyRates_f (uint16_t id, struct FloatRates * body_rate) inline static
Set vehicle body angular rate (float).
Definition at line 1354 of file state.h.
References State::body_rates_f, RATE_F, State::rate_status, RATES_COPY, State::rates_input_filter, state, and STATE_CHECK_INPUT_AND_RETURN.
Referenced by ahrs_vectornav_propagate(), ArduIMU_event(), ArduIMU_periodic(), compute_body_orientation_and_rates(), compute_body_orientation_and_rates(), compute_body_orientation_and_rates(), ekf_run(), ins_ekf2_publish_attitude(), ins_float_invariant_propagate(), ins_vectornav_propagate(), set_body_orientation_and_rates(), set_body_state_from_quat(), set_state_from_ins(), sim_overwrite_ahrs(), update_ahrs_from_sim(), update_state_interface(), update_state_interface(), and vn100_event_task().
stateSetBodyRates_i()
static void stateSetBodyRates_i (uint16_t id, struct Int32Rates * body_rate) inline static
Set vehicle body angular rate (int).
Definition at line 1344 of file state.h.
References State::body_rates_i, RATE_I, State::rate_status, RATES_COPY, State::rates_input_filter, state, and STATE_CHECK_INPUT_AND_RETURN.
Referenced by set_body_state_from_quat(), and set_body_state_from_quat().
Variable Documentation
body_rates_f
struct FloatRates State::body_rates_f
Angular rates in body frame.
Units: rad/s
Definition at line 438 of file state.h.
Referenced by stateCalcBodyRates_f(), stateCalcBodyRates_i(), stateGetBodyRates_f(), and stateSetBodyRates_f().
body_rates_i
struct Int32Rates State::body_rates_i
Angular rates in body frame.
Units: rad/s in BFP with INT32_RATE_FRAC
Definition at line 432 of file state.h.
Referenced by stateCalcBodyRates_f(), stateCalcBodyRates_i(), stateGetBodyRates_i(), and stateSetBodyRates_i().
rate_status
uint8_t State::rate_status
Holds the status bits for all angular rate representations.
When the corresponding bit is one the representation is already computed.
Definition at line 421 of file state.h.
Referenced by stateCalcBodyRates_f(), stateCalcBodyRates_i(), stateGetBodyRates_f(), stateGetBodyRates_i(), stateInit(), stateIsRateValid(), stateSetBodyRates_f(), and stateSetBodyRates_i().
rates_input_filter
uint16_t State::rates_input_filter
Holds the input filter id for rates.
Definition at line 426 of file state.h.
Referenced by stateInit(), stateSetBodyRates_f(), stateSetBodyRates_i(), and stateSetInputFilter().