Paparazzi UAS: Attitude representations
Attitude representations
State interface
Functions
static bool stateIsAttitudeValid (void)
Test if attitudes are valid.
static void stateSetNedToBodyQuat_i (uint16_t id, struct Int32Quat *ned_to_body_quat)
Set vehicle body attitude from quaternion (int).
static void stateSetNedToBodyRMat_i (uint16_t id, struct Int32RMat *ned_to_body_rmat)
Set vehicle body attitude from rotation matrix (int).
static void stateSetNedToBodyEulers_i (uint16_t id, struct Int32Eulers *ned_to_body_eulers)
Set vehicle body attitude from euler angles (int).
static void stateSetNedToBodyQuat_f (uint16_t id, struct FloatQuat *ned_to_body_quat)
Set vehicle body attitude from quaternion (float).
static void stateSetNedToBodyRMat_f (uint16_t id, struct FloatRMat *ned_to_body_rmat)
Set vehicle body attitude from rotation matrix (float).
static void stateSetNedToBodyEulers_f (uint16_t id, struct FloatEulers *ned_to_body_eulers)
Set vehicle body attitude from euler angles (float).
static struct Int32Quat * stateGetNedToBodyQuat_i (void)
Get vehicle body attitude quaternion (int).
static struct Int32RMat * stateGetNedToBodyRMat_i (void)
Get vehicle body attitude rotation matrix (int).
static struct Int32Eulers * stateGetNedToBodyEulers_i (void)
Get vehicle body attitude euler angles (int).
static struct FloatQuat * stateGetNedToBodyQuat_f (void)
Get vehicle body attitude quaternion (float).
static struct FloatRMat * stateGetNedToBodyRMat_f (void)
Get vehicle body attitude rotation matrix (float).
static struct FloatEulers * stateGetNedToBodyEulers_f (void)
Get vehicle body attitude euler angles (float).
Detailed Description
Function Documentation
stateGetNedToBodyEulers_f()
static struct FloatEulers * stateGetNedToBodyEulers_f (void) inline static
Get vehicle body attitude euler angles (float).
Definition at line 1314 of file state.h.
References State::ned_to_body_orientation, orientationGetEulers_f(), and state.
Referenced by calculate_new_heading(), calculateForwards(), calculateForwards(), calibrate_coeff(), check_parachute_trigger(), CN_calculate_target(), CN_escape_velocity(), CN_potential_heading(), CN_potential_velocity(), CN_vector_escape_velocity(), CN_vector_velocity(), collective_tracking_control(), control_mixing_heewing_nav_run(), ctrl_eff_scheduling_periodic(), dc_circle(), dc_info(), dc_periodic(), decode_optical_flow_msg(), draw_osd(), dw1000_reset_heading_ref(), ekf_aw_wrapper_fetch(), ekf_aw_wrapper_periodic(), fill_free_cells(), get_world_position_from_image_points(), guidance_h_hover_enter(), guidance_h_set_body_acc(), guidance_h_set_body_vel(), guidance_indi_enter(), guidance_indi_run(), guidance_pid_h_enter(), guidance_plane_attitude_from_nav(), gvf_low_level_control_2D(), gvf_low_level_control_3D(), gvf_low_level_getState(), h_ctl_course_loop(), h_ctl_pitch_loop(), h_ctl_pitch_loop(), h_ctl_roll_loop(), h_ctl_roll_loop(), imu_SetBodyToImuCurrent(), increase_nav_heading(), increase_nav_heading(), ins_update_lidar(), lidar_lite_periodic(), lidar_sf11_periodic(), logger_file_write_row(), logger_uart_periodic(), main_periodic_task(), mateksys3901l0x_parse(), mavlink_send_attitude(), mavlink_send_attitude(), mavlink_send_global_position_int(), mavlink_send_highres_imu(), mavlink_send_vfr_hud(), mf_daq_send_state(), nav_launcher_setup(), nav_set_heading_current(), OA_update(), object_tracking_run(), orange_avoider_guided_periodic(), parse_mf_daq_msg(), pose_periodic(), print_true_state(), px4flow_i2c_frame_cb(), read_rc_setpoint_heading(), rover_guidance_enter(), rover_guidance_run(), rover_guidance_steering_setpoints(), rover_holo_guidance_enter(), rover_holo_guidance_run(), save_speeds(), send_att(), send_att(), send_att(), send_att_full_indi(), send_attitude(), send_ctl_a(), send_dragspeed(), send_ins_flow(), send_tune_roll(), sim_overwrite_lidar(), sonar_adc_periodic(), sonar_bebop_event(), sonar_i2c_periodic(), sonar_pwm_read(), stab_sp_rotate_f(), stabilization_attitude_get_heading_f(), stabilization_attitude_plane_pid_run(), stabilization_attitude_read_rc_setpoint(), stabilization_attitude_read_rc_setpoint_earth_bound(), stabilization_attitude_read_rc_setpoint_eulers_f(), stabilization_attitude_reset_care_free_heading(), stabilization_attitude_reset_rc_setpoint(), stabilization_attitude_run(), stabilization_get_failsafe_sp(), state2stereocam(), stereo_avoid_run(), takeoff_detect_periodic(), tfmini_i2c_periodic(), tfmini_parse(), v_ctl_climb_loop(), vertical_ctrl_module_run(), wedgebug_periodic(), and wind_estimator_periodic().
stateGetNedToBodyEulers_i()
static struct Int32Eulers * stateGetNedToBodyEulers_i (void) inline static
Get vehicle body attitude euler angles (int).
Definition at line 1296 of file state.h.
References State::ned_to_body_orientation, orientationGetEulers_i(), and state.
Referenced by computeOptiTrack(), dc_send_command(), guidance_flip_run(), guidance_module_enter(), OA_update(), read_rc_setpoint_speed_i(), reset_psi_ref_from_body(), rotorcraft_cam_periodic(), send_att(), send_att(), send_euler(), send_euler(), send_fp(), send_tune_hover(), stab_sp_rotate_i(), stabilization_attitude_get_heading_i(), stabilization_attitude_read_rc_setpoint_eulers(), and stabilization_attitude_run().
stateGetNedToBodyQuat_f()
static struct FloatQuat * stateGetNedToBodyQuat_f (void) inline static
Get vehicle body attitude quaternion (float).
Definition at line 1302 of file state.h.
References State::ned_to_body_orientation, orientationGetQuat_f(), and state.
Referenced by aoa_t4_update(), compute_accel_from_speed_sp(), eff_scheduling_falcon_periodic(), eff_scheduling_periodic_b(), guidance_indi_enter(), guidance_indi_hybrid_set_wls_settings(), guidance_indi_run(), jevois_send_state(), mag_calib_ukf_run(), mavlink_send_attitude_quaternion(), oneloop_andi_run(), schdule_control_effectiveness(), send_att_full_indi(), send_fp(), send_windtunnel_meas(), stabilization_andi_enter(), stabilization_andi_run(), stabilization_attitude_enter(), stabilization_attitude_reset_rc(), stabilization_attitude_reset_rc_setpoint(), stabilization_attitude_run(), stabilization_indi_attitude_run(), update_attitude(), update_tag_position(), vel_est_cb(), and wind_estimator_periodic().
stateGetNedToBodyQuat_i()
static struct Int32Quat * stateGetNedToBodyQuat_i (void) inline static
Get vehicle body attitude quaternion (int).
Definition at line 1284 of file state.h.
References State::ned_to_body_orientation, orientationGetQuat_i(), and state.
Referenced by ins_int_update_gps(), send_ahrs_quat(), send_ahrs_ref_quat(), send_ahrs_ref_quat(), send_ahrs_ref_quat(), send_ahrs_ref_quat(), send_quat(), send_quat(), stabilization_attitude_enter(), stabilization_attitude_run(), and stabilization_attitude_run().
stateGetNedToBodyRMat_f()
static struct FloatRMat * stateGetNedToBodyRMat_f (void) inline static
Get vehicle body attitude rotation matrix (float).
Definition at line 1308 of file state.h.
References State::ned_to_body_orientation, orientationGetRMat_f(), and state.
Referenced by cam_gimbal_target(), detection_cb(), gps_cb(), ground_detect_periodic(), nav_catapult_highrate_module(), process_data(), rotwing_state_choose_circle_direction(), send_ins_flow(), unwrap_LUT(), update_tag_position(), wedgebug_periodic(), wind_estimation_quadrotor_periodic(), and wind_estimator_periodic().
stateGetNedToBodyRMat_i()
static struct Int32RMat * stateGetNedToBodyRMat_i (void) inline static
Get vehicle body attitude rotation matrix (int).
Definition at line 1290 of file state.h.
References State::ned_to_body_orientation, orientationGetRMat_i(), and state.
Referenced by accel_cb(), accel_cb(), ekf_aw_wrapper_fetch(), georeference_project(), get_vertical_thrust_coeff(), hff_propagate(), ins_int_propagate(), ins_module_propagate(), and stabilization_attitude_run().
stateIsAttitudeValid()
static bool stateIsAttitudeValid (void) inline static
Test if attitudes are valid.
Definition at line 1232 of file state.h.
References State::ned_to_body_orientation, orienationCheckValid(), and state.
Referenced by imu_SetBodyToImuCurrent(), and mavlink_send_heartbeat().
stateSetNedToBodyEulers_f()
static void stateSetNedToBodyEulers_f (uint16_t id, struct FloatEulers * ned_to_body_eulers) inline static
Set vehicle body attitude from euler angles (float).
Definition at line 1275 of file state.h.
References State::attitude_input_filter, foo, State::ned_to_body_orientation, orientationSetEulers_f(), state, and STATE_CHECK_INPUT_AND_RETURN.
Referenced by ArduIMU_event(), ArduIMU_periodic(), ekf_run(), IMU_Daten_verarbeiten(), update_ahrs_from_sim(), update_state_interface(), update_state_interface(), and vn100_event_task().
stateSetNedToBodyEulers_i()
static void stateSetNedToBodyEulers_i (uint16_t id, struct Int32Eulers * ned_to_body_eulers) inline static
Set vehicle body attitude from euler angles (int).
Definition at line 1254 of file state.h.
References State::attitude_input_filter, foo, State::ned_to_body_orientation, orientationSetEulers_i(), state, and STATE_CHECK_INPUT_AND_RETURN.
stateSetNedToBodyQuat_f()
static void stateSetNedToBodyQuat_f (uint16_t id, struct FloatQuat * ned_to_body_quat) inline static
Set vehicle body attitude from quaternion (float).
Definition at line 1261 of file state.h.
References State::attitude_input_filter, foo, State::ned_to_body_orientation, orientationSetQuat_f(), state, and STATE_CHECK_INPUT_AND_RETURN.
Referenced by ahrs_vectornav_propagate(), compute_body_orientation_and_rates(), compute_body_orientation_and_rates(), compute_body_orientation_and_rates(), ins_ekf2_publish_attitude(), ins_float_invariant_align(), ins_float_invariant_propagate(), set_body_state_from_quat(), set_state_from_ins(), and sim_overwrite_ahrs().
stateSetNedToBodyQuat_i()
static void stateSetNedToBodyQuat_i (uint16_t id, struct Int32Quat * ned_to_body_quat) inline static
Set vehicle body attitude from quaternion (int).
Definition at line 1240 of file state.h.
References State::attitude_input_filter, foo, State::ned_to_body_orientation, orientationSetQuat_i(), state, and STATE_CHECK_INPUT_AND_RETURN.
Referenced by set_body_state_from_quat(), and set_body_state_from_quat().
stateSetNedToBodyRMat_f()
static void stateSetNedToBodyRMat_f (uint16_t id, struct FloatRMat * ned_to_body_rmat) inline static
Set vehicle body attitude from rotation matrix (float).
Definition at line 1268 of file state.h.
References State::attitude_input_filter, foo, State::ned_to_body_orientation, orientationSetRMat_f(), state, and STATE_CHECK_INPUT_AND_RETURN.
Referenced by ins_vectornav_propagate(), and set_body_orientation_and_rates().
stateSetNedToBodyRMat_i()
static void stateSetNedToBodyRMat_i (uint16_t id, struct Int32RMat * ned_to_body_rmat) inline static
Set vehicle body attitude from rotation matrix (int).
Definition at line 1247 of file state.h.
References State::attitude_input_filter, foo, State::ned_to_body_orientation, orientationSetRMat_i(), state, and STATE_CHECK_INPUT_AND_RETURN.