Paparazzi UAS: sw/airborne/modules/nav/ground_detect.h File Reference
ground_detect.h File Reference
#include "std.h"
#include "filters/low_pass_filter.h"
Data Structures
union ground_detect_bitmask_t
struct ground_detect_values_t
struct ground_detect_bitmask_t.__unnamed304__
Functions
void ground_detect_init (void)
void ground_detect_periodic (void)
bool ground_detect (void)
void ground_detect_filter_accel (void)
Filter the vertical acceleration with a low cutoff frequency.
bool ground_detect_reverse_thrust (void)
void ground_detect_stop_reverse_thrust (void)
void ground_detect_start_reverse_thrust (void)
void ground_detect_set_offset_sensors (bool set_offset)
Variables
bool disarm_on_not_in_flight
float force_sensor_ground_threshold
uint16_t reverse_th_level
Detailed Description
Author
Dennis van Wijngaarden D.C.v.nosp@m.anWi.nosp@m.jngaa.nosp@m.rden.nosp@m.@tude.nosp@m.lft..nosp@m.nl Ground detection module
Definition in file ground_detect.h.
Data Structure Documentation
ground_detect_bitmask_t
union ground_detect_bitmask_t
Definition at line 32 of file ground_detect.h.
Data Fields
struct ground_detect_bitmask_t.__unnamed304__ __unnamed__
uint16_t value
ground_detect_values_t
struct ground_detect_values_t
Definition at line 43 of file ground_detect.h.
Data Fields
Butterworth2LowPass accel_down_filt
float agl_dist_value_filtered
float spec_thrust_down
float speed_down
ground_detect_bitmask_t.__unnamed304__
struct ground_detect_bitmask_t.__unnamed304__
Definition at line 34 of file ground_detect.h.
Data Fields
bool accel_filt_trigger: 1
bool agl_trigger: 1
bool force_sensor_trigger: 1
bool spec_thrust_trigger: 1
bool vspeed_trigger: 1
Function Documentation
ground_detect()
bool ground_detect (void) extern
Definition at line 230 of file ground_detect.c.
References ground_detected.
ground_detect_filter_accel()
void ground_detect_filter_accel (void) extern
Filter the vertical acceleration with a low cutoff frequency.
Definition at line 313 of file ground_detect.c.
References ground_detect_values_t::accel_down_filt, ground_detect_values, stateGetAccelNed_f(), update_butterworth_2_low_pass(), and NedCoor_f::z.
ground_detect_init()
void ground_detect_init (void) extern
Definition at line 199 of file ground_detect.c.
References ground_detect_values_t::accel_down_filt, ground_detect_values_t::agl_dist_value_filtered, force_sensor_data_t::count, DefaultPeriodic, foo, force_sensor, FORCE_SENSOR_MAX_NB, GROUND_DETECT_FILT_FREQ, GROUND_DETECT_FORCE_SENSOR_MEDIAN_FILT_SIZE, ground_detect_status, ground_detect_values, init_butterworth_2_low_pass(), init_median_filter_i(), force_sensor_data_t::offsets, register_periodic_telemetry(), send_ground_detect(), ground_detect_values_t::spec_thrust_down, ground_detect_values_t::speed_down, ground_detect_bitmask_t::value, and force_sensor_data_t::values_filt.
ground_detect_periodic()
void ground_detect_periodic (void) extern
Definition at line 241 of file ground_detect.c.
References ground_detect_values_t::accel_down_filt, act_is_servo, actuator_state_filt_vect, agl_dist_valid, ground_detect_values_t::agl_dist_value_filtered, agl_dist_value_filtered, autopilot_set_motors_on(), counter, disarm_on_not_in_flight, foo, g1g2, GROUND_DETECT_COUNTER_TRIGGER, GROUND_DETECT_NUM_TRIGGERS, GROUND_DETECT_SPECIFIC_THRUST_THRESHOLD, ground_detect_status, ground_detect_values, GROUND_DETECT_VERTICAL_ACCEL_THRESHOLD, GROUND_DETECT_VERTICAL_SPEED_THRESHOLD, ground_detected, SecondOrderLowPass::o, ground_detect_values_t::spec_thrust_down, ground_detect_values_t::speed_down, stateGetNedToBodyRMat_f(), stateGetSpeedNed_f(), ground_detect_bitmask_t::value, and NedCoor_f::z.
ground_detect_reverse_thrust()
bool ground_detect_reverse_thrust (void) extern
Definition at line 319 of file ground_detect.c.
References GROUND_DETECT_REVERSE_THRUST_ON_GROUND_DETECTED, and reverse_thrust.
ground_detect_set_offset_sensors()
void ground_detect_set_offset_sensors (bool set_offset) extern
Definition at line 339 of file ground_detect.c.
References foo.
ground_detect_start_reverse_thrust()
void ground_detect_start_reverse_thrust (void) extern
Definition at line 334 of file ground_detect.c.
References reverse_thrust.
ground_detect_stop_reverse_thrust()
void ground_detect_stop_reverse_thrust (void) extern
Definition at line 329 of file ground_detect.c.
References reverse_thrust.
Variable Documentation
disarm_on_not_in_flight
bool disarm_on_not_in_flight extern
Definition at line 115 of file ground_detect.c.
Referenced by ground_detect_periodic().
force_sensor_ground_threshold
float force_sensor_ground_threshold extern
Definition at line 125 of file ground_detect.c.
reverse_th_level
uint16_t reverse_th_level extern
Definition at line 88 of file ground_detect.c.