Paparazzi UAS: Aircraft data availability representations
Aircraft data availability representations
Data Structures
struct acInfo
Macros
#define AC_INFO_POS_UTM_I 0
#define AC_INFO_POS_LLA_I 1
#define AC_INFO_POS_ENU_I 2
#define AC_INFO_POS_UTM_F 3
#define AC_INFO_POS_LLA_F 4
#define AC_INFO_POS_ENU_F 5
#define AC_INFO_VEL_ENU_I 6
#define AC_INFO_VEL_ENU_F 7
#define AC_INFO_VEL_LOCAL_F 8
#define traffic_info_log() {}
Functions
void traffic_info_init (void)
bool parse_acinfo_dl (uint8_t *buf)
Parse all datalink or telemetry messages that contain global position of other acs Messages currently handled: Telemetry (vehicle -> ground or vehicle -> vehicle): GPS_SMALL, GPS, GPS_LLA Datalink (ground -> vehicle): ACINFO, ACINFO_LLA.
void set_ac_info_utm (uint8_t id, uint32_t utm_east, uint32_t utm_north, uint32_t alt, uint8_t utm_zone, uint16_t course, uint16_t gspeed, uint16_t climb, uint32_t itow)
Set Aircraft info.
void set_ac_info_lla (uint8_t id, int32_t lat, int32_t lon, int32_t alt, int16_t course, uint16_t gspeed, int16_t climb, uint32_t itow)
Set Aircraft info.
static void acInfoSetPositionUtm_i (uint8_t ac_id, struct UtmCoor_i *utm_pos)
Set position from UTM coordinates (int).
static void acInfoSetPositionLla_i (uint8_t ac_id, struct LlaCoor_i *lla_pos)
Set position from LLA coordinates (int).
static void acInfoSetPositionEnu_i (uint8_t ac_id, struct EnuCoor_i *enu_pos)
Set position from ENU coordinates (int).
static void acInfoSetPositionUtm_f (uint8_t ac_id, struct UtmCoor_f *utm_pos)
Set position from UTM coordinates (float).
static void acInfoSetPositionLla_f (uint8_t ac_id, struct LlaCoor_f *lla_pos)
Set position from LLA coordinates (float).
static void acInfoSetPositionEnu_f (uint8_t ac_id, struct EnuCoor_f *enu_pos)
Set position from ENU coordinates (float).
static void acInfoSetVelocityEnu_i (uint8_t ac_id, struct EnuCoor_i *enu_vel)
Set velocity from ENU coordinates (int).
static void acInfoSetVelocityEnu_f (uint8_t ac_id, struct EnuCoor_f *enu_vel)
Set velocity from ENU coordinates (float).
void acInfoCalcPositionUtm_i (uint8_t ac_id)
void acInfoCalcPositionUtm_f (uint8_t ac_id)
void acInfoCalcPositionLla_i (uint8_t ac_id)
void acInfoCalcPositionLla_f (uint8_t ac_id)
void acInfoCalcPositionEnu_i (uint8_t ac_id)
void acInfoCalcPositionEnu_f (uint8_t ac_id)
void acInfoCalcVelocityEnu_i (uint8_t ac_id)
void acInfoCalcVelocityEnu_f (uint8_t ac_id)
static struct UtmCoor_i * acInfoGetPositionUtm_i (uint8_t ac_id)
Get position from UTM coordinates (int).
static struct LlaCoor_i * acInfoGetPositionLla_i (uint8_t ac_id)
Get position from LLA coordinates (int).
static struct EnuCoor_i * acInfoGetPositionEnu_i (uint8_t ac_id)
Get position in local ENU coordinates (int).
static struct UtmCoor_f * acInfoGetPositionUtm_f (uint8_t ac_id)
Get position from UTM coordinates (float).
static struct LlaCoor_f * acInfoGetPositionLla_f (uint8_t ac_id)
Get position from LLA coordinates (float).
static struct EnuCoor_f * acInfoGetPositionEnu_f (uint8_t ac_id)
Get position in local ENU coordinates (float).
static struct EnuCoor_i * acInfoGetVelocityEnu_i (uint8_t ac_id)
Get position from ENU coordinates (int).
static struct EnuCoor_f * acInfoGetVelocityEnu_f (uint8_t ac_id)
Get position from ENU coordinates (float).
static float acInfoGetCourse (uint8_t ac_id)
Get vehicle course (float).
static float acInfoGetGspeed (uint8_t ac_id)
Get vehicle ground speed (float).
static float acInfoGetClimb (uint8_t ac_id)
Get vehicle climb speed (float).
static uint32_t acInfoGetItow (uint8_t ac_id)
Get time of week from latest message (ms).
void traffic_info_log_start (void)
void traffic_info_log_stop (void)
Variables
uint8_t ti_acs_idx
uint8_t ti_acs_id []
struct acInfo ti_acs []
Detailed Description
Data Structure Documentation
acInfo
struct acInfo
Definition at line 57 of file traffic_info.h.
Data Fields
uint8_t ac_id
float climb m/s
float course rad
struct EnuCoor_f enu_pos_f Position in North East Down coordinates Units: m.
struct EnuCoor_i enu_pos_i Position in North East Down coordinates.
Units: m in BFP with INT32_POS_FRAC
struct EnuCoor_f enu_vel_f speed in North East Down coordinates
Units: m/s
struct EnuCoor_i enu_vel_i Velocity in North East Down coordinates.
Units: m/s in BFP with INT32_SPEED_FRAC
float gspeed m/s
uint32_t itow ms
struct LlaCoor_f lla_pos_f Position in Latitude, Longitude and Altitude.
Units lat,lon: radians Units alt: meters above reference ellipsoid
struct LlaCoor_i lla_pos_i Position in Latitude, Longitude and Altitude.
Units lat,lon: degrees*1e7 Units alt: milimeters above reference ellipsoid
uint16_t status Holds the status bits for all acinfo position and velocity representations.
When the corresponding bit is set the representation is already computed.
struct UtmCoor_f utm_pos_f Position in UTM coordinates.
Units x,y: meters. Units z: meters above MSL
struct UtmCoor_i utm_pos_i Position in UTM coordinates.
Units x,y: centimetres. Units z: millimetres above MSL
Macro Definition Documentation
AC_INFO_POS_ENU_F
#define AC_INFO_POS_ENU_F 5
Definition at line 52 of file traffic_info.h.
AC_INFO_POS_ENU_I
#define AC_INFO_POS_ENU_I 2
Definition at line 49 of file traffic_info.h.
AC_INFO_POS_LLA_F
#define AC_INFO_POS_LLA_F 4
Definition at line 51 of file traffic_info.h.
AC_INFO_POS_LLA_I
#define AC_INFO_POS_LLA_I 1
Definition at line 48 of file traffic_info.h.
AC_INFO_POS_UTM_F
#define AC_INFO_POS_UTM_F 3
Definition at line 50 of file traffic_info.h.
AC_INFO_POS_UTM_I
#define AC_INFO_POS_UTM_I 0
Definition at line 47 of file traffic_info.h.
AC_INFO_VEL_ENU_F
#define AC_INFO_VEL_ENU_F 7
Definition at line 54 of file traffic_info.h.
AC_INFO_VEL_ENU_I
#define AC_INFO_VEL_ENU_I 6
Definition at line 53 of file traffic_info.h.
AC_INFO_VEL_LOCAL_F
#define AC_INFO_VEL_LOCAL_F 8
Definition at line 55 of file traffic_info.h.
traffic_info_log
#define traffic_info_log () {}
Definition at line 446 of file traffic_info.h.
Function Documentation
acInfoCalcPositionEnu_f()
void acInfoCalcPositionEnu_f (uint8_t ac_id) extern
Definition at line 523 of file traffic_info.c.
References AC_INFO_POS_ENU_F, AC_INFO_POS_ENU_I, AC_INFO_POS_LLA_F, AC_INFO_POS_LLA_I, AC_INFO_POS_UTM_F, AC_INFO_POS_UTM_I, acInfoGetPositionLla_f(), acInfoGetPositionLla_i(), acInfoGetPositionUtm_f(), ENU_FLOAT_OF_BFP, enu_of_lla_point_f(), enu_of_lla_point_i(), ENU_OF_UTM_DIFF, acInfo::enu_pos_i, foo, State::ned_initialized_i, POS_BFP_OF_REAL, state, stateGetNedOrigin_f(), stateGetNedOrigin_i(), stateGetUtmOrigin_f(), status, ti_acs, ti_acs_id, and State::utm_initialized_f.
Referenced by acInfoGetPositionEnu_f().
acInfoCalcPositionEnu_i()
void acInfoCalcPositionEnu_i (uint8_t ac_id) extern
Definition at line 423 of file traffic_info.c.
References AC_INFO_POS_ENU_F, AC_INFO_POS_ENU_I, AC_INFO_POS_LLA_F, AC_INFO_POS_LLA_I, AC_INFO_POS_UTM_F, AC_INFO_POS_UTM_I, acInfoGetPositionLla_f(), acInfoGetPositionLla_i(), acInfoGetPositionUtm_f(), ENU_BFP_OF_REAL, enu_of_lla_point_f(), enu_of_lla_point_i(), ENU_OF_UTM_DIFF, acInfo::enu_pos_i, foo, State::ned_initialized_i, POS_BFP_OF_REAL, state, stateGetNedOrigin_f(), stateGetNedOrigin_i(), stateGetUtmOrigin_f(), status, ti_acs, ti_acs_id, and State::utm_initialized_f.
Referenced by acInfoGetPositionEnu_i().
acInfoCalcPositionLla_f()
void acInfoCalcPositionLla_f (uint8_t ac_id) extern
Definition at line 495 of file traffic_info.c.
References AC_INFO_POS_LLA_F, AC_INFO_POS_LLA_I, AC_INFO_POS_UTM_F, AC_INFO_POS_UTM_I, LlaCoor_f::alt, LlaCoor_i::alt, foo, geoid_height, LLA_FLOAT_OF_BFP, lla_of_utm_f(), lla_of_utm_i(), acInfo::lla_pos_f, acInfo::lla_pos_i, status, ti_acs, ti_acs_id, and update_geoid_height().
Referenced by acInfoGetPositionLla_f().
acInfoCalcPositionLla_i()
void acInfoCalcPositionLla_i (uint8_t ac_id) extern
Definition at line 395 of file traffic_info.c.
References AC_INFO_POS_LLA_F, AC_INFO_POS_LLA_I, AC_INFO_POS_UTM_F, AC_INFO_POS_UTM_I, LlaCoor_f::alt, LlaCoor_i::alt, foo, geoid_height, LLA_BFP_OF_REAL, lla_of_utm_f(), lla_of_utm_i(), acInfo::lla_pos_f, acInfo::lla_pos_i, status, ti_acs, ti_acs_id, and update_geoid_height().
Referenced by acInfoGetPositionLla_i().
acInfoCalcPositionUtm_f()
void acInfoCalcPositionUtm_f (uint8_t ac_id) extern
Definition at line 463 of file traffic_info.c.
References AC_INFO_POS_LLA_F, AC_INFO_POS_LLA_I, AC_INFO_POS_UTM_F, AC_INFO_POS_UTM_I, UtmCoor_f::alt, UtmCoor_i::alt, foo, geoid_height, stateGetUtmOrigin_f(), status, ti_acs, ti_acs_id, update_geoid_height(), UTM_FLOAT_OF_BFP, utm_of_lla_f(), utm_of_lla_i(), acInfo::utm_pos_f, acInfo::utm_pos_i, UtmCoor_f::zone, and UtmCoor_i::zone.
Referenced by acInfoGetPositionUtm_f().
acInfoCalcPositionUtm_i()
void acInfoCalcPositionUtm_i (uint8_t ac_id) extern
Definition at line 362 of file traffic_info.c.
References AC_INFO_POS_LLA_F, AC_INFO_POS_LLA_I, AC_INFO_POS_UTM_F, AC_INFO_POS_UTM_I, UtmCoor_f::alt, UtmCoor_i::alt, foo, geoid_height, stateGetUtmOrigin_f(), status, ti_acs, ti_acs_id, update_geoid_height(), UTM_BFP_OF_REAL, utm_of_lla_f(), utm_of_lla_i(), acInfo::utm_pos_f, acInfo::utm_pos_i, UtmCoor_f::zone, and UtmCoor_i::zone.
Referenced by acInfoGetPositionUtm_i().
acInfoCalcVelocityEnu_f()
void acInfoCalcVelocityEnu_f (uint8_t ac_id) extern
Definition at line 583 of file traffic_info.c.
References AC_INFO_VEL_ENU_F, AC_INFO_VEL_ENU_I, AC_INFO_VEL_LOCAL_F, acInfo::climb, course, acInfo::enu_vel_f, foo, acInfo::gspeed, SPEEDS_FLOAT_OF_BFP, status, ti_acs, ti_acs_id, EnuCoor_f::x, EnuCoor_f::y, and EnuCoor_f::z.
Referenced by acInfoGetVelocityEnu_f().
acInfoCalcVelocityEnu_i()
void acInfoCalcVelocityEnu_i (uint8_t ac_id) extern
Definition at line 561 of file traffic_info.c.
References AC_INFO_VEL_ENU_F, AC_INFO_VEL_ENU_I, acInfo::climb, course, acInfo::enu_vel_f, foo, acInfo::gspeed, SPEEDS_BFP_OF_REAL, status, ti_acs, ti_acs_id, EnuCoor_f::x, EnuCoor_f::y, and EnuCoor_f::z.
Referenced by acInfoGetVelocityEnu_i().
acInfoGetClimb()
static float acInfoGetClimb (uint8_t ac_id) inline static
Get vehicle climb speed (float).
Parameters
[in] ac_id aircraft id of aircraft info to get
Definition at line 432 of file traffic_info.h.
References acInfo::climb, ti_acs, and ti_acs_id.
acInfoGetCourse()
static float acInfoGetCourse (uint8_t ac_id) inline static
Get vehicle course (float).
Parameters
[in] ac_id aircraft id of aircraft info to get
Definition at line 416 of file traffic_info.h.
References acInfo::course, ti_acs, and ti_acs_id.
Referenced by calculate_new_heading(), and formation_flight().
acInfoGetGspeed()
static float acInfoGetGspeed (uint8_t ac_id) inline static
Get vehicle ground speed (float).
Parameters
[in] ac_id aircraft id of aircraft info to get
Definition at line 424 of file traffic_info.h.
References acInfo::gspeed, ti_acs, and ti_acs_id.
Referenced by formation_flight().
acInfoGetItow()
static uint32_t acInfoGetItow (uint8_t ac_id) inline static
Get time of week from latest message (ms).
Parameters
[in] ac_id aircraft id of aircraft info to get
Definition at line 440 of file traffic_info.h.
References acInfo::itow, ti_acs, and ti_acs_id.
Referenced by calculate_new_heading(), formation_flight(), and potential_task().
acInfoGetPositionEnu_f()
static struct EnuCoor_f * acInfoGetPositionEnu_f (uint8_t ac_id) inline static
Get position in local ENU coordinates (float).
Parameters
[in] ac_id aircraft id of aircraft info to get
Definition at line 383 of file traffic_info.h.
References AC_INFO_POS_ENU_F, acInfoCalcPositionEnu_f(), acInfo::enu_pos_f, foo, status, ti_acs, and ti_acs_id.
Referenced by calculate_new_heading(), cam_gimbal_ac_target(), formation_flight(), parse_acinfo_dl(), potential_task(), tcas_periodic_task_1Hz(), tcas_periodic_task_4Hz(), and tcas_test_direction().
acInfoGetPositionEnu_i()
static struct EnuCoor_i * acInfoGetPositionEnu_i (uint8_t ac_id) inline static
Get position in local ENU coordinates (int).
Parameters
[in] ac_id aircraft id of aircraft info to get
Definition at line 350 of file traffic_info.h.
References AC_INFO_POS_ENU_I, acInfoCalcPositionEnu_i(), acInfo::enu_pos_i, foo, status, ti_acs, and ti_acs_id.
Referenced by follow_wp().
acInfoGetPositionLla_f()
static struct LlaCoor_f * acInfoGetPositionLla_f (uint8_t ac_id) inline static
Get position from LLA coordinates (float).
Parameters
[in] ac_id aircraft id of aircraft info to get
Definition at line 372 of file traffic_info.h.
References AC_INFO_POS_LLA_F, acInfoCalcPositionLla_f(), foo, acInfo::lla_pos_f, status, ti_acs, and ti_acs_id.
Referenced by acInfoCalcPositionEnu_f(), acInfoCalcPositionEnu_i(), and parse_acinfo_dl().
acInfoGetPositionLla_i()
static struct LlaCoor_i * acInfoGetPositionLla_i (uint8_t ac_id) inline static
Get position from LLA coordinates (int).
Parameters
[in] ac_id aircraft id of aircraft info to get
Definition at line 339 of file traffic_info.h.
References AC_INFO_POS_LLA_I, acInfoCalcPositionLla_i(), foo, acInfo::lla_pos_i, status, ti_acs, and ti_acs_id.
Referenced by acInfoCalcPositionEnu_f(), and acInfoCalcPositionEnu_i().
acInfoGetPositionUtm_f()
static struct UtmCoor_f * acInfoGetPositionUtm_f (uint8_t ac_id) inline static
Get position from UTM coordinates (float).
Parameters
[in] ac_id aircraft id of aircraft info to get
Definition at line 361 of file traffic_info.h.
References AC_INFO_POS_UTM_F, acInfoCalcPositionUtm_f(), foo, status, ti_acs, ti_acs_id, and acInfo::utm_pos_f.
Referenced by acInfoCalcPositionEnu_f(), and acInfoCalcPositionEnu_i().
acInfoGetPositionUtm_i()
static struct UtmCoor_i * acInfoGetPositionUtm_i (uint8_t ac_id) inline static
Get position from UTM coordinates (int).
Parameters
[in] ac_id aircraft id of aircraft info to get
Definition at line 328 of file traffic_info.h.
References AC_INFO_POS_UTM_I, acInfoCalcPositionUtm_i(), foo, status, ti_acs, ti_acs_id, and acInfo::utm_pos_i.
acInfoGetVelocityEnu_f()
static struct EnuCoor_f * acInfoGetVelocityEnu_f (uint8_t ac_id) inline static
Get position from ENU coordinates (float).
Parameters
[in] ac_id aircraft id of aircraft info to get
Definition at line 405 of file traffic_info.h.
References AC_INFO_VEL_ENU_F, acInfoCalcVelocityEnu_f(), acInfo::enu_vel_f, foo, status, ti_acs, and ti_acs_id.
Referenced by formation_flight(), potential_task(), and tcas_periodic_task_1Hz().
acInfoGetVelocityEnu_i()
static struct EnuCoor_i * acInfoGetVelocityEnu_i (uint8_t ac_id) inline static
Get position from ENU coordinates (int).
Parameters
[in] ac_id aircraft id of aircraft info to get
Definition at line 394 of file traffic_info.h.
References AC_INFO_VEL_ENU_I, acInfoCalcVelocityEnu_i(), acInfo::enu_vel_i, foo, status, ti_acs, and ti_acs_id.
acInfoSetPositionEnu_f()
static void acInfoSetPositionEnu_f (uint8_t ac_id, struct EnuCoor_f * enu_pos) inline static
Set position from ENU coordinates (float).
Parameters
[in] ac_id aircraft id of aircraft info to set
[in] enu_pos position in ENU (float)
Definition at line 261 of file traffic_info.h.
References acInfo::ac_id, AC_INFO_POS_ENU_F, acInfo::enu_pos_f, foo, gps_tow_from_sys_ticks(), acInfo::itow, NB_ACS, sys_time::nb_tick, acInfo::status, ti_acs, ti_acs_id, ti_acs_idx, and VECT3_COPY.
acInfoSetPositionEnu_i()
static void acInfoSetPositionEnu_i (uint8_t ac_id, struct EnuCoor_i * enu_pos) inline static
Set position from ENU coordinates (int).
Parameters
[in] ac_id aircraft id of aircraft info to set
[in] enu_pos position in ENU (int)
Definition at line 207 of file traffic_info.h.
References acInfo::ac_id, AC_INFO_POS_ENU_I, acInfo::enu_pos_i, foo, gps_tow_from_sys_ticks(), acInfo::itow, NB_ACS, sys_time::nb_tick, acInfo::status, ti_acs, ti_acs_id, ti_acs_idx, and VECT3_COPY.
acInfoSetPositionLla_f()
static void acInfoSetPositionLla_f (uint8_t ac_id, struct LlaCoor_f * lla_pos) inline static
Set position from LLA coordinates (float).
Parameters
[in] ac_id aircraft id of aircraft info to set
[in] lla_pos LLA position (float)
Definition at line 243 of file traffic_info.h.
References acInfo::ac_id, AC_INFO_POS_LLA_F, gps_tow_from_sys_ticks(), acInfo::itow, LLA_COPY, acInfo::lla_pos_i, NB_ACS, sys_time::nb_tick, acInfo::status, ti_acs, ti_acs_id, and ti_acs_idx.
acInfoSetPositionLla_i()
static void acInfoSetPositionLla_i (uint8_t ac_id, struct LlaCoor_i * lla_pos) inline static
Set position from LLA coordinates (int).
Parameters
[in] ac_id aircraft id of aircraft info to set
[in] lla_pos LLA position (int)
Definition at line 189 of file traffic_info.h.
References acInfo::ac_id, AC_INFO_POS_LLA_I, gps_tow_from_sys_ticks(), acInfo::itow, LLA_COPY, acInfo::lla_pos_i, NB_ACS, sys_time::nb_tick, acInfo::status, ti_acs, ti_acs_id, and ti_acs_idx.
acInfoSetPositionUtm_f()
static void acInfoSetPositionUtm_f (uint8_t ac_id, struct UtmCoor_f * utm_pos) inline static
Set position from UTM coordinates (float).
Parameters
[in] ac_id aircraft id of aircraft info to set
[in] utm_pos UTM position (float)
Definition at line 225 of file traffic_info.h.
References acInfo::ac_id, AC_INFO_POS_UTM_F, gps_tow_from_sys_ticks(), acInfo::itow, NB_ACS, sys_time::nb_tick, acInfo::status, ti_acs, ti_acs_id, ti_acs_idx, UTM_COPY, and acInfo::utm_pos_f.
acInfoSetPositionUtm_i()
static void acInfoSetPositionUtm_i (uint8_t ac_id, struct UtmCoor_i * utm_pos) inline static
Set position from UTM coordinates (int).
Parameters
[in] ac_id aircraft id of aircraft info to set
[in] utm_pos UTM position (int)
Definition at line 171 of file traffic_info.h.
References acInfo::ac_id, AC_INFO_POS_UTM_I, gps_tow_from_sys_ticks(), acInfo::itow, NB_ACS, sys_time::nb_tick, acInfo::status, ti_acs, ti_acs_id, ti_acs_idx, UTM_COPY, and acInfo::utm_pos_i.
acInfoSetVelocityEnu_f()
static void acInfoSetVelocityEnu_f (uint8_t ac_id, struct EnuCoor_f * enu_vel) inline static
Set velocity from ENU coordinates (float).
Parameters
[in] ac_id aircraft id of aircraft info to set
[in] enu_vel velocity in ENU (float)
Definition at line 297 of file traffic_info.h.
References acInfo::ac_id, AC_INFO_VEL_ENU_F, acInfo::enu_vel_i, foo, gps_tow_from_sys_ticks(), acInfo::itow, NB_ACS, sys_time::nb_tick, acInfo::status, ti_acs, ti_acs_id, ti_acs_idx, and VECT3_COPY.
acInfoSetVelocityEnu_i()
static void acInfoSetVelocityEnu_i (uint8_t ac_id, struct EnuCoor_i * enu_vel) inline static
Set velocity from ENU coordinates (int).
Parameters
[in] ac_id aircraft id of aircraft info to set
[in] enu_vel velocity in ENU (int)
Definition at line 279 of file traffic_info.h.
References acInfo::ac_id, AC_INFO_VEL_ENU_I, acInfo::enu_vel_i, foo, gps_tow_from_sys_ticks(), acInfo::itow, NB_ACS, sys_time::nb_tick, acInfo::status, ti_acs, ti_acs_id, ti_acs_idx, and VECT3_COPY.
parse_acinfo_dl()
bool parse_acinfo_dl (uint8_t * buf) extern
Parse all datalink or telemetry messages that contain global position of other acs Messages currently handled: Telemetry (vehicle -> ground or vehicle -> vehicle): GPS_SMALL, GPS, GPS_LLA Datalink (ground -> vehicle): ACINFO, ACINFO_LLA.
Definition at line 130 of file traffic_info.c.
References acInfoGetPositionEnu_f(), acInfoGetPositionLla_f(), LlaCoor_f::alt, CM_OF_M, course, FALSE, FLOAT_VECT2_NORM, foo, gps, gps_tow_from_sys_ticks(), LlaCoor_f::lat, LogFileIsOpen, LogWrite, LlaCoor_f::lon, ltp_def_from_ecef_i(), sys_time::nb_tick, ned_of_ecef_vect_i(), pprzLogFile, set_ac_info_lla(), set_ac_info_utm(), GpsState::tow, TRUE, VECT3_FLOAT_OF_CM, EnuCoor_f::x, EcefCoor_i::x, EnuCoor_f::y, and EnuCoor_f::z.
set_ac_info_lla()
void set_ac_info_lla (uint8_t id, int32_t lat, int32_t lon, int32_t alt, int16_t course, uint16_t gspeed, int16_t climb, uint32_t itow) extern
Set Aircraft info.
Parameters
[in] id aircraft id, 0 is reserved for GCS, 1 for this aircraft (id=AC_ID)
[in] lat Latitude in 1e7deg
[in] lon Longitude in 1e7deg
[in] alt Altitude in mm above ellipsoid
[in] course Course in decideg (CW)
[in] gspeed Ground speed in cm/s
[in] climb Climb rate in cm/s
[in] itow GPS time of week in ms
Definition at line 329 of file traffic_info.c.
References acInfo::ac_id, AC_INFO_POS_LLA_I, AC_INFO_VEL_LOCAL_F, LlaCoor_i::alt, acInfo::climb, acInfo::course, course, foo, acInfo::gspeed, acInfo::itow, LlaCoor_i::lat, LLA_COPY, LlaCoor_i::lon, NB_ACS, acInfo::status, status, ti_acs, ti_acs_id, and ti_acs_idx.
Referenced by parse_acinfo_dl().
set_ac_info_utm()
void set_ac_info_utm (uint8_t id, uint32_t utm_east, uint32_t utm_north, uint32_t alt, uint8_t utm_zone, uint16_t course, uint16_t gspeed, uint16_t climb, uint32_t itow) extern
Set Aircraft info.
Parameters
[in] id aircraft id, 0 is reserved for GCS, 1 for this aircraft (id=AC_ID)
[in] utm_east UTM east in cm
[in] utm_north UTM north in cm
[in] alt Altitude in mm above MSL
[in] utm_zone UTM zone
[in] course Course in decideg (CW)
[in] gspeed Ground speed in m/s
[in] climb Climb rate in m/s
[in] itow GPS time of week in ms
Definition at line 283 of file traffic_info.c.
References acInfo::ac_id, AC_INFO_POS_LLA_I, AC_INFO_POS_UTM_I, AC_INFO_VEL_LOCAL_F, UtmCoor_i::alt, acInfo::climb, acInfo::course, course, UtmCoor_i::east, foo, acInfo::gspeed, acInfo::itow, LLA_COPY, lla_of_utm_i(), NB_ACS, UtmCoor_i::north, stateGetUtmOrigin_f(), acInfo::status, status, ti_acs, ti_acs_id, ti_acs_idx, UTM_COPY, utm_of_lla_i(), acInfo::utm_pos_i, UtmCoor_f::zone, and UtmCoor_i::zone.
Referenced by parse_acinfo_dl().
traffic_info_init()
void traffic_info_init (void) extern
Definition at line 100 of file traffic_info.c.
References acInfo::ac_id, DefaultPeriodic, foo, geoid_height, NB_ACS_ID, register_periodic_telemetry(), send_acinfo_lla(), ti_acs, ti_acs_id, and ti_acs_idx.
traffic_info_log_start()
void traffic_info_log_start (void) extern
Definition at line 602 of file traffic_info.c.
References foo, LogOpen, and pprzLogFile.
traffic_info_log_stop()
void traffic_info_log_stop (void) extern
Definition at line 609 of file traffic_info.c.
References LogClose, LogFileIsOpen, and pprzLogFile.
Variable Documentation
ti_acs
struct acInfo ti_acs[] extern
Definition at line 59 of file traffic_info.c.
Referenced by acInfoCalcPositionEnu_f(), acInfoCalcPositionEnu_i(), acInfoCalcPositionLla_f(), acInfoCalcPositionLla_i(), acInfoCalcPositionUtm_f(), acInfoCalcPositionUtm_i(), acInfoCalcVelocityEnu_f(), acInfoCalcVelocityEnu_i(), acInfoGetClimb(), acInfoGetCourse(), acInfoGetGspeed(), acInfoGetItow(), acInfoGetPositionEnu_f(), acInfoGetPositionEnu_i(), acInfoGetPositionLla_f(), acInfoGetPositionLla_i(), acInfoGetPositionUtm_f(), acInfoGetPositionUtm_i(), acInfoGetVelocityEnu_f(), acInfoGetVelocityEnu_i(), acInfoSetPositionEnu_f(), acInfoSetPositionEnu_i(), acInfoSetPositionLla_f(), acInfoSetPositionLla_i(), acInfoSetPositionUtm_f(), acInfoSetPositionUtm_i(), acInfoSetVelocityEnu_f(), acInfoSetVelocityEnu_i(), calculate_new_heading(), formation_flight(), potential_task(), set_ac_info_lla(), set_ac_info_utm(), tcas_periodic_task_1Hz(), and traffic_info_init().
ti_acs_id
uint8_t ti_acs_id[] extern
Definition at line 57 of file traffic_info.c.
Referenced by acInfoCalcPositionEnu_f(), acInfoCalcPositionEnu_i(), acInfoCalcPositionLla_f(), acInfoCalcPositionLla_i(), acInfoCalcPositionUtm_f(), acInfoCalcPositionUtm_i(), acInfoCalcVelocityEnu_f(), acInfoCalcVelocityEnu_i(), acInfoGetClimb(), acInfoGetCourse(), acInfoGetGspeed(), acInfoGetItow(), acInfoGetPositionEnu_f(), acInfoGetPositionEnu_i(), acInfoGetPositionLla_f(), acInfoGetPositionLla_i(), acInfoGetPositionUtm_f(), acInfoGetPositionUtm_i(), acInfoGetVelocityEnu_f(), acInfoGetVelocityEnu_i(), acInfoSetPositionEnu_f(), acInfoSetPositionEnu_i(), acInfoSetPositionLla_f(), acInfoSetPositionLla_i(), acInfoSetPositionUtm_f(), acInfoSetPositionUtm_i(), acInfoSetVelocityEnu_f(), acInfoSetVelocityEnu_i(), add_slot(), formation_flight(), formation_pre_call(), parseTcasRA(), parseTcasResolve(), set_ac_info_lla(), set_ac_info_utm(), tcas_periodic_task_1Hz(), traffic_info_init(), updateFormationStatus(), and updateSlot().
ti_acs_idx
uint8_t ti_acs_idx extern
Definition at line 55 of file traffic_info.c.
Referenced by acInfoSetPositionEnu_f(), acInfoSetPositionEnu_i(), acInfoSetPositionLla_f(), acInfoSetPositionLla_i(), acInfoSetPositionUtm_f(), acInfoSetPositionUtm_i(), acInfoSetVelocityEnu_f(), acInfoSetVelocityEnu_i(), set_ac_info_lla(), set_ac_info_utm(), and traffic_info_init().