Paparazzi UAS: Wind- and airspeed representations
Wind- and airspeed representations
State interface
Macros
#define WINDSPEED_I 0
#define DOWNWIND_I 1
#define AIRSPEED_I 2
#define WINDSPEED_F 3
#define DOWNWIND_F 4
#define AIRSPEED_F 5
#define AOA_F 6
#define SIDESLIP_F 7
Functions
void stateCalcHorizontalWindspeed_i (void)
void stateCalcVerticalWindspeed_i (void)
void stateCalcAirspeed_i (void)
void stateCalcHorizontalWindspeed_f (void)
void stateCalcVerticalWindspeed_f (void)
void stateCalcAirspeed_f (void)
static bool stateIsWindspeedValid (void)
test if wind speed is available.
static bool stateIsVerticalWindspeedValid (void)
test if vertical wind speed is available.
static bool stateIsAirspeedValid (void)
test if air speed is available.
static bool stateIsAngleOfAttackValid (void)
test if angle of attack is available.
static bool stateIsSideslipValid (void)
test if sideslip is available.
static void stateSetHorizontalWindspeed_i (uint16_t id, struct Int32Vect2 *h_windspeed)
Set horizontal windspeed (int).
static void stateSetVerticalWindspeed_i (uint16_t id, int32_t v_windspeed)
Set vertical windspeed (int).
static void stateSetAirspeed_i (uint16_t id, int32_t airspeed)
Set airspeed (int).
static void stateSetHorizontalWindspeed_f (uint16_t id, struct FloatVect2 *h_windspeed)
Set horizontal windspeed (float).
static void stateSetVerticalWindspeed_f (uint16_t id, float v_windspeed)
Set vertical windspeed (float).
static void stateSetAirspeed_f (uint16_t id, float airspeed)
Set airspeed (float).
static void stateSetAngleOfAttack_f (uint16_t id, float aoa)
Set angle of attack in radians (float).
static void stateSetSideslip_f (uint16_t id, float sideslip)
Set sideslip angle in radians (float).
static struct Int32Vect2 * stateGetHorizontalWindspeed_i (void)
Get horizontal windspeed (int).
static float stateGetVerticalWindspeed_i (void)
Get vertical windspeed (int).
static struct Int32Vect3 * stateGetWindspeed_i (void)
Get windspeed (int).
static int32_t stateGetAirspeed_i (void)
Get airspeed (int).
static struct FloatVect2 * stateGetHorizontalWindspeed_f (void)
Get horizontal windspeed (float).
static float stateGetVerticalWindspeed_f (void)
Get vertical windspeed (float).
static struct FloatVect3 * stateGetWindspeed_f (void)
Get windspeed (float).
static float stateGetAirspeed_f (void)
Get airspeed (float).
static float stateGetAngleOfAttack_f (void)
Get angle of attack (float).
static float stateGetSideslip_f (void)
Get sideslip (float).
Variables
uint8_t State::wind_air_status
Holds the status bits for all wind- and airspeed representations.
uint16_t State::wind_air_input_filter
Holds the input filter id for air data.
union {
struct Int32Vect3 vect3
struct Int32Vect2 vect2
} State::windspeed_i
Horizontal windspeed in north/east/down.
int32_t State::airspeed_i
Norm of relative wind speed.
union {
struct FloatVect3 vect3
struct FloatVect2 vect2
} State::windspeed_f
Horizontal windspeed.
float State::airspeed_f
Norm of relative air speed.
float State::angle_of_attack_f
Angle of attack Unit: rad.
float State::sideslip_f
Sideslip angle Unit: rad.
Detailed Description
Macro Definition Documentation
AIRSPEED_F
#define AIRSPEED_F 5
Definition at line 129 of file state.h.
AIRSPEED_I
#define AIRSPEED_I 2
Definition at line 126 of file state.h.
AOA_F
#define AOA_F 6
Definition at line 130 of file state.h.
DOWNWIND_F
#define DOWNWIND_F 4
Definition at line 128 of file state.h.
DOWNWIND_I
#define DOWNWIND_I 1
Definition at line 125 of file state.h.
SIDESLIP_F
#define SIDESLIP_F 7
Definition at line 131 of file state.h.
WINDSPEED_F
#define WINDSPEED_F 3
Definition at line 127 of file state.h.
WINDSPEED_I
#define WINDSPEED_I 0
Definition at line 124 of file state.h.
Function Documentation
stateCalcAirspeed_f()
void stateCalcAirspeed_f (void)
Definition at line 1474 of file state.c.
References AIRSPEED_F, State::airspeed_f, AIRSPEED_I, State::airspeed_i, foo, SPEED_FLOAT_OF_BFP, state, and State::wind_air_status.
Referenced by stateGetAirspeed_f().
stateCalcAirspeed_i()
void stateCalcAirspeed_i (void)
Definition at line 1428 of file state.c.
References AIRSPEED_F, State::airspeed_f, AIRSPEED_I, State::airspeed_i, foo, SPEED_BFP_OF_REAL, state, and State::wind_air_status.
Referenced by stateGetAirspeed_i().
stateCalcHorizontalWindspeed_f()
void stateCalcHorizontalWindspeed_f (void)
Definition at line 1443 of file state.c.
References foo, SPEED_FLOAT_OF_BFP, state, State::wind_air_status, WINDSPEED_F, State::windspeed_f, WINDSPEED_I, and State::windspeed_i.
Referenced by stateGetHorizontalWindspeed_f(), and stateGetWindspeed_f().
stateCalcHorizontalWindspeed_i()
void stateCalcHorizontalWindspeed_i (void)
Definition at line 1397 of file state.c.
References foo, SPEED_BFP_OF_REAL, state, State::wind_air_status, WINDSPEED_F, State::windspeed_f, WINDSPEED_I, and State::windspeed_i.
Referenced by stateGetHorizontalWindspeed_i(), and stateGetWindspeed_i().
stateCalcVerticalWindspeed_f()
void stateCalcVerticalWindspeed_f (void)
Definition at line 1459 of file state.c.
References DOWNWIND_F, DOWNWIND_I, foo, SPEED_FLOAT_OF_BFP, state, State::wind_air_status, State::windspeed_f, and State::windspeed_i.
Referenced by stateGetVerticalWindspeed_f(), and stateGetWindspeed_f().
stateCalcVerticalWindspeed_i()
void stateCalcVerticalWindspeed_i (void)
Definition at line 1413 of file state.c.
References DOWNWIND_F, DOWNWIND_I, foo, SPEED_BFP_OF_REAL, state, State::wind_air_status, State::windspeed_f, and State::windspeed_i.
Referenced by stateGetVerticalWindspeed_i(), and stateGetWindspeed_i().
stateGetAirspeed_f()
static float stateGetAirspeed_f (void) inline static
Get airspeed (float).
Definition at line 1598 of file state.h.
References AIRSPEED_F, State::airspeed_f, foo, state, stateCalcAirspeed_f(), and State::wind_air_status.
Referenced by air_data_parse_WIND_INFO(), bound_vz_sp(), compute_accel_from_speed_sp(), ctrl_eff_scheduling_periodic(), eff_scheduling_falcon_periodic(), eff_scheduling_periodic_b(), eff_scheduling_rotwing_update_airspeed(), ekf_aw_wrapper_fetch(), flight_benchmark_periodic(), follow_diagonal_approach(), generic_com_periodic(), get_time_to_home(), guidance_indi_calcg_wing(), guidance_indi_hybrid_set_wls_settings(), guidance_indi_propagate_filters(), guidance_indi_run(), logger_control_effectiveness_periodic(), mavlink_send_vfr_hud(), nav_bungee_takeoff_run(), oneloop_andi_propagate_filters(), rotwing_state_periodic(), schdule_control_effectiveness(), send_airspeed(), snav_on_time(), stabilization_indi_set_wls_settings(), transition_run(), v_ctl_climb_loop(), and wind_estimator_periodic().
stateGetAirspeed_i()
static int32_t stateGetAirspeed_i (void) inline static
Get airspeed (int).
Definition at line 1559 of file state.h.
References AIRSPEED_I, State::airspeed_i, foo, state, stateCalcAirspeed_i(), and State::wind_air_status.
stateGetAngleOfAttack_f()
static float stateGetAngleOfAttack_f (void) inline static
Get angle of attack (float).
Todo:
only float for now
Definition at line 1607 of file state.h.
References State::angle_of_attack_f, and state.
Referenced by h_ctl_pitch_loop(), and wind_estimator_periodic().
stateGetHorizontalWindspeed_f()
static struct FloatVect2 * stateGetHorizontalWindspeed_f (void) inline static
Get horizontal windspeed (float).
Definition at line 1568 of file state.h.
References foo, state, stateCalcHorizontalWindspeed_f(), State::wind_air_status, WINDSPEED_F, and State::windspeed_f.
Referenced by compute_TOD(), get_time_to_home(), gls_compute_TOD(), mf_daq_send_state(), nav_survey_disc_run(), parse_mf_daq_msg(), and snav_on_time().
stateGetHorizontalWindspeed_i()
static struct Int32Vect2 * stateGetHorizontalWindspeed_i (void) inline static
Get horizontal windspeed (int).
Definition at line 1529 of file state.h.
References foo, state, stateCalcHorizontalWindspeed_i(), State::wind_air_status, WINDSPEED_I, and State::windspeed_i.
stateGetSideslip_f()
static float stateGetSideslip_f (void) inline static
Get sideslip (float).
Todo:
only float for now
Definition at line 1616 of file state.h.
References State::sideslip_f, and state.
Referenced by wind_estimator_periodic().
stateGetVerticalWindspeed_f()
static float stateGetVerticalWindspeed_f (void) inline static
Get vertical windspeed (float).
Definition at line 1577 of file state.h.
References DOWNWIND_F, foo, state, stateCalcVerticalWindspeed_f(), State::wind_air_status, and State::windspeed_f.
stateGetVerticalWindspeed_i()
static float stateGetVerticalWindspeed_i (void) inline static
Get vertical windspeed (int).
Definition at line 1538 of file state.h.
References DOWNWIND_I, foo, state, stateCalcVerticalWindspeed_i(), State::wind_air_status, and State::windspeed_i.
stateGetWindspeed_f()
static struct FloatVect3 * stateGetWindspeed_f (void) inline static
Get windspeed (float).
Definition at line 1586 of file state.h.
References DOWNWIND_F, foo, state, stateCalcHorizontalWindspeed_f(), stateCalcVerticalWindspeed_f(), State::wind_air_status, WINDSPEED_F, and State::windspeed_f.
stateGetWindspeed_i()
static struct Int32Vect3 * stateGetWindspeed_i (void) inline static
Get windspeed (int).
Definition at line 1547 of file state.h.
References DOWNWIND_I, foo, state, stateCalcHorizontalWindspeed_i(), stateCalcVerticalWindspeed_i(), State::wind_air_status, WINDSPEED_I, and State::windspeed_i.
stateIsAirspeedValid()
static bool stateIsAirspeedValid (void) inline static
test if air speed is available.
Definition at line 1419 of file state.h.
References AIRSPEED_F, AIRSPEED_I, state, and State::wind_air_status.
Referenced by get_time_to_home(), and transition_run().
stateIsAngleOfAttackValid()
static bool stateIsAngleOfAttackValid (void) inline static
test if angle of attack is available.
Definition at line 1425 of file state.h.
References AOA_F, state, and State::wind_air_status.
stateIsSideslipValid()
static bool stateIsSideslipValid (void) inline static
test if sideslip is available.
Definition at line 1431 of file state.h.
References SIDESLIP_F, state, and State::wind_air_status.
stateIsVerticalWindspeedValid()
static bool stateIsVerticalWindspeedValid (void) inline static
test if vertical wind speed is available.
Definition at line 1413 of file state.h.
References DOWNWIND_F, DOWNWIND_I, state, and State::wind_air_status.
stateIsWindspeedValid()
static bool stateIsWindspeedValid (void) inline static
test if wind speed is available.
Definition at line 1407 of file state.h.
References state, State::wind_air_status, WINDSPEED_F, and WINDSPEED_I.
Referenced by get_time_to_home().
stateSetAirspeed_f()
static void stateSetAirspeed_f (uint16_t id, float airspeed) inline static
Set airspeed (float).
Definition at line 1494 of file state.h.
References AIRSPEED_F, State::airspeed_f, AIRSPEED_I, foo, state, STATE_CHECK_INPUT_AND_RETURN, State::wind_air_input_filter, and State::wind_air_status.
Referenced by air_data_parse_WIND_INFO(), airspeed_adc_update(), airspeed_amsys_read_event(), airspeed_amsys_read_periodic(), airspeed_cb(), airspeed_ets_read_event(), airspeed_ets_read_periodic(), nps_autopilot_run_step(), and pressure_diff_cb().
stateSetAirspeed_i()
static void stateSetAirspeed_i (uint16_t id, int32_t airspeed) inline static
Set airspeed (int).
Definition at line 1461 of file state.h.
References AIRSPEED_F, AIRSPEED_I, State::airspeed_i, foo, state, STATE_CHECK_INPUT_AND_RETURN, State::wind_air_input_filter, and State::wind_air_status.
stateSetAngleOfAttack_f()
static void stateSetAngleOfAttack_f (uint16_t id, float aoa) inline static
Set angle of attack in radians (float).
Todo:
no integer yet
Definition at line 1505 of file state.h.
References State::angle_of_attack_f, AOA_F, foo, state, STATE_CHECK_INPUT_AND_RETURN, State::wind_air_input_filter, and State::wind_air_status.
Referenced by aoa_adc_update(), and incidence_cb().
stateSetHorizontalWindspeed_f()
static void stateSetHorizontalWindspeed_f (uint16_t id, struct FloatVect2 * h_windspeed) inline static
Set horizontal windspeed (float).
Definition at line 1472 of file state.h.
References foo, state, STATE_CHECK_INPUT_AND_RETURN, VECT2_COPY, State::wind_air_input_filter, State::wind_air_status, WINDSPEED_F, State::windspeed_f, and WINDSPEED_I.
Referenced by air_data_parse_WIND_INFO(), wind_estimation_quadrotor_periodic(), wind_estimation_quadrotor_stop(), and wind_estimator_event().
stateSetHorizontalWindspeed_i()
static void stateSetHorizontalWindspeed_i (uint16_t id, struct Int32Vect2 * h_windspeed) inline static
Set horizontal windspeed (int).
Definition at line 1439 of file state.h.
References foo, state, STATE_CHECK_INPUT_AND_RETURN, VECT2_COPY, State::wind_air_input_filter, State::wind_air_status, WINDSPEED_F, WINDSPEED_I, and State::windspeed_i.
stateSetSideslip_f()
static void stateSetSideslip_f (uint16_t id, float sideslip) inline static
Set sideslip angle in radians (float).
Todo:
no integer yet
Definition at line 1516 of file state.h.
References foo, SIDESLIP_F, State::sideslip_f, state, STATE_CHECK_INPUT_AND_RETURN, State::wind_air_input_filter, and State::wind_air_status.
Referenced by incidence_cb().
stateSetVerticalWindspeed_f()
static void stateSetVerticalWindspeed_f (uint16_t id, float v_windspeed) inline static
Set vertical windspeed (float).
Definition at line 1483 of file state.h.
References DOWNWIND_F, DOWNWIND_I, foo, state, STATE_CHECK_INPUT_AND_RETURN, State::wind_air_input_filter, State::wind_air_status, and State::windspeed_f.
Referenced by air_data_parse_WIND_INFO(), and wind_estimator_event().
stateSetVerticalWindspeed_i()
static void stateSetVerticalWindspeed_i (uint16_t id, int32_t v_windspeed) inline static
Set vertical windspeed (int).
Definition at line 1450 of file state.h.
References DOWNWIND_F, DOWNWIND_I, foo, state, STATE_CHECK_INPUT_AND_RETURN, State::wind_air_input_filter, State::wind_air_status, and State::windspeed_i.
Variable Documentation
airspeed_f
float State::airspeed_f
Norm of relative air speed.
Unit: m/s
Definition at line 484 of file state.h.
Referenced by stateCalcAirspeed_f(), stateCalcAirspeed_i(), stateGetAirspeed_f(), and stateSetAirspeed_f().
airspeed_i
int32_t State::airspeed_i
Norm of relative wind speed.
Unit: m/s in BFP with INT32_SPEED_FRAC
Definition at line 469 of file state.h.
Referenced by stateCalcAirspeed_f(), stateCalcAirspeed_i(), stateGetAirspeed_i(), and stateSetAirspeed_i().
angle_of_attack_f
float State::angle_of_attack_f
Angle of attack Unit: rad.
Definition at line 490 of file state.h.
Referenced by stateGetAngleOfAttack_f(), and stateSetAngleOfAttack_f().
sideslip_f
float State::sideslip_f
Sideslip angle Unit: rad.
Definition at line 496 of file state.h.
Referenced by stateGetSideslip_f(), and stateSetSideslip_f().
[] [1/2]
struct Int32Vect2 { ... } ::vect2
Definition at line 462 of file state.h.
[] [2/2]
struct FloatVect2 { ... } ::vect2
Definition at line 477 of file state.h.
[] [1/2]
struct Int32Vect3 { ... } ::vect3
Definition at line 461 of file state.h.
[] [2/2]
struct FloatVect3 { ... } ::vect3
Definition at line 476 of file state.h.
wind_air_input_filter
uint16_t State::wind_air_input_filter
Holds the input filter id for air data.
Definition at line 454 of file state.h.
Referenced by stateInit(), stateSetAirspeed_f(), stateSetAirspeed_i(), stateSetAngleOfAttack_f(), stateSetHorizontalWindspeed_f(), stateSetHorizontalWindspeed_i(), stateSetInputFilter(), stateSetSideslip_f(), stateSetVerticalWindspeed_f(), and stateSetVerticalWindspeed_i().
wind_air_status
uint8_t State::wind_air_status
Holds the status bits for all wind- and airspeed representations.
When the corresponding bit is one the representation is already computed.
Definition at line 449 of file state.h.
Referenced by stateCalcAirspeed_f(), stateCalcAirspeed_i(), stateCalcHorizontalWindspeed_f(), stateCalcHorizontalWindspeed_i(), stateCalcVerticalWindspeed_f(), stateCalcVerticalWindspeed_i(), stateGetAirspeed_f(), stateGetAirspeed_i(), stateGetHorizontalWindspeed_f(), stateGetHorizontalWindspeed_i(), stateGetVerticalWindspeed_f(), stateGetVerticalWindspeed_i(), stateGetWindspeed_f(), stateGetWindspeed_i(), stateInit(), stateIsAirspeedValid(), stateIsAngleOfAttackValid(), stateIsSideslipValid(), stateIsVerticalWindspeedValid(), stateIsWindspeedValid(), stateSetAirspeed_f(), stateSetAirspeed_i(), stateSetAngleOfAttack_f(), stateSetHorizontalWindspeed_f(), stateSetHorizontalWindspeed_i(), stateSetSideslip_f(), stateSetVerticalWindspeed_f(), and stateSetVerticalWindspeed_i().
[union]
union { ... } State::windspeed_f
Horizontal windspeed.
Units: m/s with x=north, y=east, z=down
Referenced by stateCalcHorizontalWindspeed_f(), stateCalcHorizontalWindspeed_i(), stateCalcVerticalWindspeed_f(), stateCalcVerticalWindspeed_i(), stateGetHorizontalWindspeed_f(), stateGetVerticalWindspeed_f(), stateGetWindspeed_f(), stateSetHorizontalWindspeed_f(), and stateSetVerticalWindspeed_f().
[union]
union { ... } State::windspeed_i
Horizontal windspeed in north/east/down.
Units: m/s in BFP with INT32_SPEED_FRAC
Referenced by stateCalcHorizontalWindspeed_f(), stateCalcHorizontalWindspeed_i(), stateCalcVerticalWindspeed_f(), stateCalcVerticalWindspeed_i(), stateGetHorizontalWindspeed_i(), stateGetVerticalWindspeed_i(), stateGetWindspeed_i(), stateSetHorizontalWindspeed_i(), and stateSetVerticalWindspeed_i().