Paparazzi UAS: Speed representations
Speed representations
State interface
Macros
#define SPEED_ECEF_I 0
#define SPEED_NED_I 1
#define SPEED_ENU_I 2
#define SPEED_HNORM_I 3
#define SPEED_HDIR_I 4
#define SPEED_ECEF_F 5
#define SPEED_NED_F 6
#define SPEED_ENU_F 7
#define SPEED_HNORM_F 8
#define SPEED_HDIR_F 9
#define SPEED_LOCAL_COORD ((1<<SPEED_NED_I)|(1<<SPEED_ENU_I)|(1<<SPEED_NED_F)|(1<<SPEED_ENU_F))
Functions
void stateCalcSpeedNed_i (void)
void stateCalcSpeedEnu_i (void)
void stateCalcSpeedEcef_i (void)
void stateCalcHorizontalSpeedNorm_i (void)
void stateCalcHorizontalSpeedDir_i (void)
void stateCalcSpeedNed_f (void)
void stateCalcSpeedEnu_f (void)
void stateCalcSpeedEcef_f (void)
void stateCalcHorizontalSpeedNorm_f (void)
void stateCalcHorizontalSpeedDir_f (void)
static void stateSetSpeedNed_i (uint16_t id, struct NedCoor_i *ned_speed)
Set ground speed in local NED coordinates (int).
static void stateSetSpeedEnu_i (uint16_t id, struct EnuCoor_i *enu_speed)
Set ground speed in local ENU coordinates (int).
static void stateSetSpeedEcef_i (uint16_t id, struct EcefCoor_i *ecef_speed)
Set ground speed in ECEF coordinates (int).
static void stateSetSpeed_i (uint16_t id, struct EcefCoor_i *ecef_speed, struct NedCoor_i *ned_speed, struct EnuCoor_i *enu_speed)
Set multiple speed coordinates (int).
static void stateSetSpeedNed_f (uint16_t id, struct NedCoor_f *ned_speed)
Set ground speed in local NED coordinates (float).
static void stateSetSpeedEnu_f (uint16_t id, struct EnuCoor_f *enu_speed)
Set ground speed in local ENU coordinates (float).
static void stateSetSpeedEcef_f (uint16_t id, struct EcefCoor_f *ecef_speed)
Set ground speed in ECEF coordinates (float).
static void stateSetSpeed_f (uint16_t id, struct EcefCoor_f *ecef_speed, struct NedCoor_f *ned_speed, struct EnuCoor_f *enu_speed)
Set multiple speed coordinates (float).
static struct NedCoor_i * stateGetSpeedNed_i (void)
Get ground speed in local NED coordinates (int).
static struct EnuCoor_i * stateGetSpeedEnu_i (void)
Get ground speed in local ENU coordinates (int).
static struct EcefCoor_i * stateGetSpeedEcef_i (void)
Get ground speed in ECEF coordinates (int).
static uint32_t stateGetHorizontalSpeedNorm_i (void)
Get norm of horizontal ground speed (int).
static int32_t stateGetHorizontalSpeedDir_i (void)
Get dir of horizontal ground speed (int).
static struct NedCoor_f * stateGetSpeedNed_f (void)
Get ground speed in local NED coordinates (float).
static struct EnuCoor_f * stateGetSpeedEnu_f (void)
Get ground speed in local ENU coordinates (float).
static struct EcefCoor_f * stateGetSpeedEcef_f (void)
Get ground speed in ECEF coordinates (float).
static float stateGetHorizontalSpeedNorm_f (void)
Get norm of horizontal ground speed (float).
static float stateGetHorizontalSpeedDir_f (void)
Get dir of horizontal ground speed (float).
static struct Int32Vect3 * stateGetAccelBody_i (void)
Get acceleration in Body coordinates (int).
Variables
uint16_t State::speed_status
Holds the status bits for all ground speed representations.
uint16_t State::speed_input_filter
Holds the input filter id for speed.
struct EcefCoor_i State::ecef_speed_i
Velocity in EarthCenteredEarthFixed coordinates.
struct NedCoor_i State::ned_speed_i
Velocity in North East Down coordinates.
struct EnuCoor_i State::enu_speed_i
Velocity in East North Up coordinates.
uint32_t State::h_speed_norm_i
Norm of horizontal ground speed.
int32_t State::h_speed_dir_i
Direction of horizontal ground speed.
struct EcefCoor_f State::ecef_speed_f
Velocity in EarthCenteredEarthFixed coordinates.
struct NedCoor_f State::ned_speed_f
speed in North East Down coordinates
struct EnuCoor_f State::enu_speed_f
Velocity in East North Up coordinates.
float State::h_speed_norm_f
Norm of horizontal ground speed.
float State::h_speed_dir_f
Direction of horizontal ground speed.
Detailed Description
Macro Definition Documentation
SPEED_ECEF_F
#define SPEED_ECEF_F 5
Definition at line 94 of file state.h.
SPEED_ECEF_I
#define SPEED_ECEF_I 0
Definition at line 89 of file state.h.
SPEED_ENU_F
#define SPEED_ENU_F 7
Definition at line 96 of file state.h.
SPEED_ENU_I
#define SPEED_ENU_I 2
Definition at line 91 of file state.h.
SPEED_HDIR_F
#define SPEED_HDIR_F 9
Definition at line 98 of file state.h.
SPEED_HDIR_I
#define SPEED_HDIR_I 4
Definition at line 93 of file state.h.
SPEED_HNORM_F
#define SPEED_HNORM_F 8
Definition at line 97 of file state.h.
SPEED_HNORM_I
#define SPEED_HNORM_I 3
Definition at line 92 of file state.h.
SPEED_LOCAL_COORD
#define SPEED_LOCAL_COORD ((1<<SPEED_NED_I)|(1<<SPEED_ENU_I)|(1<<SPEED_NED_F)|(1<<SPEED_ENU_F))
Definition at line 99 of file state.h.
SPEED_NED_F
#define SPEED_NED_F 6
Definition at line 95 of file state.h.
SPEED_NED_I
#define SPEED_NED_I 1
Definition at line 90 of file state.h.
Function Documentation
stateCalcHorizontalSpeedDir_f()
void stateCalcHorizontalSpeedDir_f (void)
Definition at line 1179 of file state.c.
References State::enu_speed_f, State::enu_speed_i, foo, State::h_speed_dir_f, State::h_speed_dir_i, State::ned_speed_f, State::ned_speed_i, SPEED_ENU_F, SPEED_ENU_I, SPEED_FLOAT_OF_BFP, SPEED_HDIR_F, SPEED_HDIR_I, SPEED_NED_F, SPEED_NED_I, State::speed_status, SPEEDS_FLOAT_OF_BFP, state, NedCoor_f::x, EnuCoor_f::x, NedCoor_f::y, and EnuCoor_f::y.
Referenced by stateGetHorizontalSpeedDir_f().
stateCalcHorizontalSpeedDir_i()
void stateCalcHorizontalSpeedDir_i (void)
Definition at line 996 of file state.c.
References State::enu_speed_f, State::enu_speed_i, foo, State::h_speed_dir_f, State::h_speed_dir_i, int32_atan2(), INT32_COURSE_NORMALIZE, State::ned_speed_f, State::ned_speed_i, SPEED_BFP_OF_REAL, SPEED_ENU_F, SPEED_ENU_I, SPEED_HDIR_F, SPEED_HDIR_I, SPEED_NED_F, SPEED_NED_I, State::speed_status, SPEEDS_BFP_OF_REAL, state, NedCoor_i::x, EnuCoor_i::x, NedCoor_i::y, and EnuCoor_i::y.
Referenced by stateGetHorizontalSpeedDir_i().
stateCalcHorizontalSpeedNorm_f()
void stateCalcHorizontalSpeedNorm_f (void)
Definition at line 1152 of file state.c.
References State::enu_speed_f, State::enu_speed_i, FLOAT_VECT2_NORM, foo, State::h_speed_norm_f, State::h_speed_norm_i, State::ned_speed_f, State::ned_speed_i, SPEED_ENU_F, SPEED_ENU_I, SPEED_FLOAT_OF_BFP, SPEED_HNORM_F, SPEED_HNORM_I, SPEED_NED_F, SPEED_NED_I, State::speed_status, SPEEDS_FLOAT_OF_BFP, and state.
Referenced by stateGetHorizontalSpeedNorm_f().
stateCalcHorizontalSpeedNorm_i()
void stateCalcHorizontalSpeedNorm_i (void)
Definition at line 950 of file state.c.
References State::ecef_speed_f, State::ecef_speed_i, State::enu_speed_f, State::enu_speed_i, FLOAT_VECT2_NORM, foo, State::h_speed_norm_f, State::h_speed_norm_i, INT32_SPEED_FRAC, int32_sqrt(), ned_of_ecef_vect_f(), ned_of_ecef_vect_i(), State::ned_origin_f, State::ned_origin_i, State::ned_speed_f, State::ned_speed_i, SPEED_BFP_OF_REAL, SPEED_ECEF_F, SPEED_ECEF_I, SPEED_ENU_F, SPEED_ENU_I, SPEED_HNORM_F, SPEED_HNORM_I, SPEED_NED_F, SPEED_NED_I, State::speed_status, state, NedCoor_i::x, EnuCoor_i::x, NedCoor_i::y, and EnuCoor_i::y.
Referenced by stateGetHorizontalSpeedNorm_i().
stateCalcSpeedEcef_f()
void stateCalcSpeedEcef_f (void)
Definition at line 1127 of file state.c.
References ecef_of_ned_vect_f(), State::ecef_speed_f, foo, State::ned_origin_f, State::ned_speed_f, State::ned_speed_i, SPEED_ECEF_F, SPEED_ECEF_I, SPEED_NED_F, SPEED_NED_I, State::speed_status, SPEEDS_FLOAT_OF_BFP, and state.
Referenced by stateGetSpeedEcef_f().
stateCalcSpeedEcef_i()
void stateCalcSpeedEcef_i (void)
Definition at line 925 of file state.c.
References ecef_of_ned_vect_i(), State::ecef_speed_f, State::ecef_speed_i, foo, State::ned_origin_i, State::ned_speed_f, State::ned_speed_i, SPEED_ECEF_F, SPEED_ECEF_I, SPEED_NED_F, SPEED_NED_I, State::speed_status, SPEEDS_BFP_OF_REAL, and state.
Referenced by stateGetSpeedEcef_i().
stateCalcSpeedEnu_f()
void stateCalcSpeedEnu_f (void)
Definition at line 1077 of file state.c.
References State::ecef_speed_f, State::ecef_speed_i, enu_of_ecef_vect_f(), State::enu_speed_f, State::enu_speed_i, foo, State::ned_initialized_f, State::ned_origin_f, State::ned_speed_f, State::ned_speed_i, SPEED_ECEF_F, SPEED_ECEF_I, SPEED_ENU_F, SPEED_ENU_I, SPEED_NED_F, SPEED_NED_I, State::speed_status, SPEEDS_FLOAT_OF_BFP, state, State::utm_initialized_f, and VECT3_ENU_OF_NED.
Referenced by stateGetSpeedEnu_f().
stateCalcSpeedEnu_i()
void stateCalcSpeedEnu_i (void)
Definition at line 873 of file state.c.
References State::ecef_speed_f, State::ecef_speed_i, enu_of_ecef_vect_i(), State::enu_speed_f, State::enu_speed_i, foo, INT32_VECT3_ENU_OF_NED, State::ned_initialized_i, State::ned_origin_i, State::ned_speed_f, State::ned_speed_i, SPEED_ECEF_F, SPEED_ECEF_I, SPEED_ENU_F, SPEED_ENU_I, SPEED_NED_F, SPEED_NED_I, State::speed_status, SPEEDS_BFP_OF_REAL, state, and State::utm_initialized_f.
Referenced by stateGetSpeedEnu_i().
stateCalcSpeedNed_f()
void stateCalcSpeedNed_f (void)
Definition at line 1027 of file state.c.
References State::ecef_speed_f, State::ecef_speed_i, State::enu_speed_f, State::enu_speed_i, foo, State::ned_initialized_f, ned_of_ecef_vect_f(), State::ned_origin_f, State::ned_speed_f, State::ned_speed_i, SPEED_ECEF_F, SPEED_ECEF_I, SPEED_ENU_F, SPEED_ENU_I, SPEED_NED_F, SPEED_NED_I, State::speed_status, SPEEDS_FLOAT_OF_BFP, state, State::utm_initialized_f, and VECT3_NED_OF_ENU.
Referenced by stateGetSpeedNed_f().
stateCalcSpeedNed_i()
void stateCalcSpeedNed_i (void)
Definition at line 823 of file state.c.
References State::ecef_speed_f, State::ecef_speed_i, State::enu_speed_f, State::enu_speed_i, foo, INT32_VECT3_NED_OF_ENU, State::ned_initialized_i, ned_of_ecef_vect_i(), State::ned_origin_i, State::ned_speed_f, State::ned_speed_i, SPEED_ECEF_F, SPEED_ECEF_I, SPEED_ENU_F, SPEED_ENU_I, SPEED_NED_F, SPEED_NED_I, State::speed_status, SPEEDS_BFP_OF_REAL, state, and State::utm_initialized_f.
Referenced by stateGetSpeedNed_i().
stateGetAccelBody_i()
static struct Int32Vect3 * stateGetAccelBody_i (void) inline static
Get acceleration in Body coordinates (int).
Definition at line 1094 of file state.h.
References State::body_accel_i, and state.
Referenced by ekf_aw_wrapper_fetch(), guidance_indi_propagate_filters(), guidance_indi_quadplane_propagate_filters(), hff_propagate(), lms_estimation(), logger_control_effectiveness_periodic(), oneloop_andi_propagate_filters(), send_body_rates_accel(), stabilization_indi_rate_run(), and wind_estimator_periodic().
stateGetHorizontalSpeedDir_f()
static float stateGetHorizontalSpeedDir_f (void) inline static
Get dir of horizontal ground speed (float).
Definition at line 1085 of file state.h.
References foo, State::h_speed_dir_f, SPEED_HDIR_F, State::speed_status, state, and stateCalcHorizontalSpeedDir_f().
Referenced by calculate_wind_no_airspeed(), fly_to_xy(), formation_flight(), guidance_plane_attitude_from_nav(), gvf_low_level_getState(), gvf_parametric_control_2D(), h_ctl_course_loop(), home_direction(), nav_lace_run(), nav_rosette_run(), nav_survey_rectangle_init(), nav_trinity_run(), potential_task(), put_route(), recover_gps_data(), send_acinfo_lla(), send_minimal_com(), snav_init(), and tcas_periodic_task_1Hz().
stateGetHorizontalSpeedDir_i()
static int32_t stateGetHorizontalSpeedDir_i (void) inline static
Get dir of horizontal ground speed (int).
Definition at line 1040 of file state.h.
References foo, State::h_speed_dir_i, SPEED_HDIR_I, State::speed_status, state, and stateCalcHorizontalSpeedDir_i().
Referenced by dc_send_command().
stateGetHorizontalSpeedNorm_f()
static float stateGetHorizontalSpeedNorm_f (void) inline static
Get norm of horizontal ground speed (float).
Definition at line 1076 of file state.h.
References foo, State::h_speed_norm_f, SPEED_HNORM_F, State::speed_status, state, and stateCalcHorizontalSpeedNorm_f().
Referenced by ArduIMU_periodicGPS(), calc_flight_time_left(), calculate_wind_no_airspeed(), draw_osd(), fly_to_xy(), formation_flight(), gls_run(), gvf_low_level_control_2D(), gvf_low_level_control_3D(), gvf_low_level_getState(), gvf_parametric_control_2D(), h_ctl_course_loop(), home_direction(), mavlink_send_vfr_hud(), monitor_task(), nav_approaching_xy(), nav_bungee_takeoff_run(), nav_circle_XY(), nav_glide_alt(), nav_launcher_run(), potential_task(), put_horizontal_speed(), recover_gps_data(), rover_guidance_run(), rover_guidance_steering_heading_ctrl(), rover_guidance_steering_speed_ctrl(), rover_holo_guidance_run(), send_acinfo_lla(), send_fp_min(), send_minimal_com(), tcas_periodic_task_1Hz(), v_ctl_climb_loop(), and v_ctl_landing_loop().
stateGetHorizontalSpeedNorm_i()
static uint32_t stateGetHorizontalSpeedNorm_i (void) inline static
Get norm of horizontal ground speed (int).
Definition at line 1031 of file state.h.
References foo, State::h_speed_norm_i, SPEED_HNORM_I, State::speed_status, state, and stateCalcHorizontalSpeedNorm_i().
Referenced by dc_send_command(), and hott_update_eam_msg().
stateGetSpeedEcef_f()
static struct EcefCoor_f * stateGetSpeedEcef_f (void) inline static
Get ground speed in ECEF coordinates (float).
Definition at line 1067 of file state.h.
References State::ecef_speed_f, foo, SPEED_ECEF_F, State::speed_status, state, and stateCalcSpeedEcef_f().
stateGetSpeedEcef_i()
static struct EcefCoor_i * stateGetSpeedEcef_i (void) inline static
Get ground speed in ECEF coordinates (int).
Definition at line 1022 of file state.h.
References State::ecef_speed_i, foo, SPEED_ECEF_I, State::speed_status, state, and stateCalcSpeedEcef_i().
stateGetSpeedEnu_f()
static struct EnuCoor_f * stateGetSpeedEnu_f (void) inline static
Get ground speed in local ENU coordinates (float).
Definition at line 1058 of file state.h.
References State::enu_speed_f, foo, SPEED_ENU_F, State::speed_status, state, and stateCalcSpeedEnu_f().
Referenced by ac_char_update(), ballistic_touchdown_run(), bf_getEstimatedVario(), calibrate_coeff(), calibrate_zero(), collective_tracking_control(), ctc_target_send_info_to_nei(), decawave_anchorless_communication_periodic(), draw_osd(), guidance_plane_set_pitch(), guidance_plane_set_throttle(), gvf_low_level_getState(), gvf_parametric_control_2D(), mf_daq_send_state(), nav_approaching(), nav_approaching(), nav_hybrid_approaching(), parse_mf_daq_msg(), potential_task(), process_data(), send_acinfo_lla(), send_dragspeed(), send_estimator(), send_minimal_com(), tcas_periodic_task_1Hz(), v_ctl_climb_auto_throttle_loop(), v_ctl_climb_loop(), v_ctl_set_pitch(), v_ctl_set_throttle(), and vertical_ctrl_module_run().
stateGetSpeedEnu_i()
static struct EnuCoor_i * stateGetSpeedEnu_i (void) inline static
Get ground speed in local ENU coordinates (int).
Definition at line 1013 of file state.h.
References State::enu_speed_i, foo, SPEED_ENU_I, State::speed_status, state, and stateCalcSpeedEnu_i().
Referenced by hott_update_eam_msg(), logger_control_effectiveness_periodic(), and send_fp().
stateGetSpeedNed_f()
static struct NedCoor_f * stateGetSpeedNed_f (void) inline static
Get ground speed in local NED coordinates (float).
Definition at line 1049 of file state.h.
References foo, State::ned_speed_f, SPEED_NED_F, State::speed_status, state, and stateCalcSpeedNed_f().
Referenced by autopilot_in_flight_end_detection(), compute_accel_from_speed_sp(), ekf_aw_wrapper_fetch(), ground_detect_periodic(), guidance_indi_controller(), guidance_indi_controller(), guidance_indi_run_mode(), guidance_indi_run_mode(), ins_alt_float_update_baro(), logger_file_write_row(), mavlink_send_global_position_int(), mavlink_send_local_position_ned(), mavlink_send_vfr_hud(), OA_update(), oneloop_andi_propagate_filters(), print_true_state(), range_msg_callback(), save_speeds(), send_ins_flow(), stabilization_andi_enter(), stabilization_andi_run(), wind_estimation_quadrotor_periodic(), and wind_estimator_periodic().
stateGetSpeedNed_i()
static struct NedCoor_i * stateGetSpeedNed_i (void) inline static
Get ground speed in local NED coordinates (int).
Definition at line 1004 of file state.h.
References foo, State::ned_speed_i, SPEED_NED_I, State::speed_status, state, and stateCalcSpeedNed_i().
Referenced by computeOptiTrack(), guidance_h_update_reference(), guidance_hybrid_determine_wind_estimate(), guidance_pid_h_run_pos(), guidance_pid_h_run_speed(), guidance_pid_v_run(), guidance_v_from_nav(), guidance_v_guided_enter(), guidance_v_mode_changed(), guidance_v_set_th(), ins_vectornav_propagate(), reset_guidance_reference_from_current_position(), send_hover_loop(), send_hybrid_guidance(), and send_vert_loop().
stateSetSpeed_f()
static void stateSetSpeed_f (uint16_t id, struct EcefCoor_f * ecef_speed, struct NedCoor_f * ned_speed, struct EnuCoor_f * enu_speed) inline static
Set multiple speed coordinates (float).
Definition at line 977 of file state.h.
References State::ecef_speed_f, State::enu_speed_f, foo, State::ned_speed_f, SPEED_ECEF_F, SPEED_ENU_F, State::speed_input_filter, SPEED_NED_F, State::speed_status, state, STATE_CHECK_INPUT_AND_RETURN, and VECT3_COPY.
stateSetSpeed_i()
static void stateSetSpeed_i (uint16_t id, struct EcefCoor_i * ecef_speed, struct NedCoor_i * ned_speed, struct EnuCoor_i * enu_speed) inline static
Set multiple speed coordinates (int).
Definition at line 922 of file state.h.
References State::ecef_speed_i, State::enu_speed_i, foo, State::ned_speed_i, SPEED_ECEF_I, SPEED_ENU_I, State::speed_input_filter, SPEED_NED_I, State::speed_status, state, STATE_CHECK_INPUT_AND_RETURN, and VECT3_COPY.
stateSetSpeedEcef_f()
static void stateSetSpeedEcef_f (uint16_t id, struct EcefCoor_f * ecef_speed) inline static
Set ground speed in ECEF coordinates (float).
Definition at line 967 of file state.h.
References State::ecef_speed_f, foo, SPEED_ECEF_F, State::speed_input_filter, State::speed_status, state, STATE_CHECK_INPUT_AND_RETURN, and VECT3_COPY.
stateSetSpeedEcef_i()
static void stateSetSpeedEcef_i (uint16_t id, struct EcefCoor_i * ecef_speed) inline static
Set ground speed in ECEF coordinates (int).
Definition at line 912 of file state.h.
References State::ecef_speed_i, foo, SPEED_ECEF_I, State::speed_input_filter, State::speed_status, state, STATE_CHECK_INPUT_AND_RETURN, and VECT3_COPY.
stateSetSpeedEnu_f()
static void stateSetSpeedEnu_f (uint16_t id, struct EnuCoor_f * enu_speed) inline static
Set ground speed in local ENU coordinates (float).
Definition at line 957 of file state.h.
References State::enu_speed_f, foo, SPEED_ENU_F, State::speed_input_filter, State::speed_status, state, STATE_CHECK_INPUT_AND_RETURN, and VECT3_COPY.
stateSetSpeedEnu_i()
static void stateSetSpeedEnu_i (uint16_t id, struct EnuCoor_i * enu_speed) inline static
Set ground speed in local ENU coordinates (int).
Definition at line 902 of file state.h.
References State::enu_speed_i, foo, SPEED_ENU_I, State::speed_input_filter, State::speed_status, state, STATE_CHECK_INPUT_AND_RETURN, and VECT3_COPY.
stateSetSpeedNed_f()
static void stateSetSpeedNed_f (uint16_t id, struct NedCoor_f * ned_speed) inline static
Set ground speed in local NED coordinates (float).
Definition at line 947 of file state.h.
References foo, State::ned_speed_f, State::speed_input_filter, SPEED_NED_F, State::speed_status, state, STATE_CHECK_INPUT_AND_RETURN, and VECT3_COPY.
Referenced by ekf_run(), gps_cb(), gps_cb(), gps_cb(), ins_alt_float_update_baro(), ins_alt_float_update_gps(), ins_ekf2_update(), ins_float_invariant_propagate(), ins_vectornav_propagate(), set_state_from_ins(), and sim_overwrite_ins().
stateSetSpeedNed_i()
static void stateSetSpeedNed_i (uint16_t id, struct NedCoor_i * ned_speed) inline static
Set ground speed in local NED coordinates (int).
Definition at line 892 of file state.h.
References foo, State::ned_speed_i, State::speed_input_filter, SPEED_NED_I, State::speed_status, state, STATE_CHECK_INPUT_AND_RETURN, and VECT3_COPY.
Referenced by gps_cb(), gps_cb(), ins_ned_to_state(), and ins_ned_to_state().
Variable Documentation
ecef_speed_f
struct EcefCoor_f State::ecef_speed_f
Velocity in EarthCenteredEarthFixed coordinates.
Units: m/s
Definition at line 331 of file state.h.
Referenced by stateCalcHorizontalSpeedNorm_i(), stateCalcSpeedEcef_f(), stateCalcSpeedEcef_i(), stateCalcSpeedEnu_f(), stateCalcSpeedEnu_i(), stateCalcSpeedNed_f(), stateCalcSpeedNed_i(), stateGetSpeedEcef_f(), stateSetSpeed_f(), and stateSetSpeedEcef_f().
ecef_speed_i
struct EcefCoor_i State::ecef_speed_i
Velocity in EarthCenteredEarthFixed coordinates.
Units: m/s in BFP with INT32_SPEED_FRAC
Definition at line 300 of file state.h.
Referenced by stateCalcHorizontalSpeedNorm_i(), stateCalcSpeedEcef_i(), stateCalcSpeedEnu_f(), stateCalcSpeedEnu_i(), stateCalcSpeedNed_f(), stateCalcSpeedNed_i(), stateGetSpeedEcef_i(), stateSetSpeed_i(), and stateSetSpeedEcef_i().
enu_speed_f
struct EnuCoor_f State::enu_speed_f
Velocity in East North Up coordinates.
Units: m/s
Definition at line 342 of file state.h.
Referenced by stateCalcHorizontalSpeedDir_f(), stateCalcHorizontalSpeedDir_i(), stateCalcHorizontalSpeedNorm_f(), stateCalcHorizontalSpeedNorm_i(), stateCalcSpeedEnu_f(), stateCalcSpeedEnu_i(), stateCalcSpeedNed_f(), stateCalcSpeedNed_i(), stateGetSpeedEnu_f(), stateSetSpeed_f(), and stateSetSpeedEnu_f().
enu_speed_i
struct EnuCoor_i State::enu_speed_i
Velocity in East North Up coordinates.
Units: m/s in BFP with INT32_SPEED_FRAC
Definition at line 312 of file state.h.
Referenced by stateCalcHorizontalSpeedDir_f(), stateCalcHorizontalSpeedDir_i(), stateCalcHorizontalSpeedNorm_f(), stateCalcHorizontalSpeedNorm_i(), stateCalcSpeedEnu_f(), stateCalcSpeedEnu_i(), stateCalcSpeedNed_f(), stateCalcSpeedNed_i(), stateGetSpeedEnu_i(), stateSetSpeed_i(), and stateSetSpeedEnu_i().
h_speed_dir_f
float State::h_speed_dir_f
Direction of horizontal ground speed.
Unit: rad (clockwise, zero=north)
Definition at line 354 of file state.h.
Referenced by stateCalcHorizontalSpeedDir_f(), stateCalcHorizontalSpeedDir_i(), and stateGetHorizontalSpeedDir_f().
h_speed_dir_i
int32_t State::h_speed_dir_i
Direction of horizontal ground speed.
Unit: rad in BFP with INT32_ANGLE_FRAC (clockwise, zero=north)
Definition at line 325 of file state.h.
Referenced by stateCalcHorizontalSpeedDir_f(), stateCalcHorizontalSpeedDir_i(), and stateGetHorizontalSpeedDir_i().
h_speed_norm_f
float State::h_speed_norm_f
Norm of horizontal ground speed.
Unit: m/s
Definition at line 348 of file state.h.
Referenced by stateCalcHorizontalSpeedNorm_f(), stateCalcHorizontalSpeedNorm_i(), and stateGetHorizontalSpeedNorm_f().
h_speed_norm_i
uint32_t State::h_speed_norm_i
Norm of horizontal ground speed.
Unit: m/s in BFP with INT32_SPEED_FRAC
Definition at line 318 of file state.h.
Referenced by stateCalcHorizontalSpeedNorm_f(), stateCalcHorizontalSpeedNorm_i(), and stateGetHorizontalSpeedNorm_i().
ned_speed_f
struct NedCoor_f State::ned_speed_f
speed in North East Down coordinates
Units: m/s
Definition at line 336 of file state.h.
Referenced by stateCalcHorizontalSpeedDir_f(), stateCalcHorizontalSpeedDir_i(), stateCalcHorizontalSpeedNorm_f(), stateCalcHorizontalSpeedNorm_i(), stateCalcSpeedEcef_f(), stateCalcSpeedEcef_i(), stateCalcSpeedEnu_f(), stateCalcSpeedEnu_i(), stateCalcSpeedNed_f(), stateCalcSpeedNed_i(), stateGetSpeedNed_f(), stateSetSpeed_f(), and stateSetSpeedNed_f().
ned_speed_i
struct NedCoor_i State::ned_speed_i
Velocity in North East Down coordinates.
Units: m/s in BFP with INT32_SPEED_FRAC
Definition at line 306 of file state.h.
Referenced by stateCalcHorizontalSpeedDir_f(), stateCalcHorizontalSpeedDir_i(), stateCalcHorizontalSpeedNorm_f(), stateCalcHorizontalSpeedNorm_i(), stateCalcSpeedEcef_f(), stateCalcSpeedEcef_i(), stateCalcSpeedEnu_f(), stateCalcSpeedEnu_i(), stateCalcSpeedNed_f(), stateCalcSpeedNed_i(), stateGetSpeedNed_i(), stateSetSpeed_i(), and stateSetSpeedNed_i().
speed_input_filter
uint16_t State::speed_input_filter
Holds the input filter id for speed.
Definition at line 294 of file state.h.
Referenced by stateInit(), stateSetInputFilter(), stateSetSpeed_f(), stateSetSpeed_i(), stateSetSpeedEcef_f(), stateSetSpeedEcef_i(), stateSetSpeedEnu_f(), stateSetSpeedEnu_i(), stateSetSpeedNed_f(), and stateSetSpeedNed_i().
speed_status
uint16_t State::speed_status
Holds the status bits for all ground speed representations.
When the corresponding bit is one the representation is already computed.
Definition at line 289 of file state.h.
Referenced by stateCalcHorizontalSpeedDir_f(), stateCalcHorizontalSpeedDir_i(), stateCalcHorizontalSpeedNorm_f(), stateCalcHorizontalSpeedNorm_i(), stateCalcSpeedEcef_f(), stateCalcSpeedEcef_i(), stateCalcSpeedEnu_f(), stateCalcSpeedEnu_i(), stateCalcSpeedNed_f(), stateCalcSpeedNed_i(), stateGetHorizontalSpeedDir_f(), stateGetHorizontalSpeedDir_i(), stateGetHorizontalSpeedNorm_f(), stateGetHorizontalSpeedNorm_i(), stateGetSpeedEcef_f(), stateGetSpeedEcef_i(), stateGetSpeedEnu_f(), stateGetSpeedEnu_i(), stateGetSpeedNed_f(), stateGetSpeedNed_i(), stateInit(), stateSetLocalOrigin_i(), stateSetLocalUtmOrigin_f(), stateSetSpeed_f(), stateSetSpeed_i(), stateSetSpeedEcef_f(), stateSetSpeedEcef_i(), stateSetSpeedEnu_f(), stateSetSpeedEnu_i(), stateSetSpeedNed_f(), and stateSetSpeedNed_i().