Paparazzi UAS: sw/airborne/modules/gsm/gsm.h File Reference
gsm.h File Reference
Communications through GSM.
Functions
void gsm_init (void)
void gsm_periodic_1Hz (void)
void gsm_init_report (void)
void gsm_send_report (void)
void gsm_start (void)
void gsm_stop (void)
void gsm_event (void)
Detailed Description
Communications through GSM.
Definition in file gsm.h.
Function Documentation
gsm_event()
void gsm_event (void)
Definition at line 179 of file gsm.c.
References DefaultChannel, DefaultDevice, foo, gsm_buf, gsm_buf_len, gsm_got_line(), gsm_got_prompt(), gsm_line_received, GSMLinkChAvailable, prompt_received, and ReadGSMBuffer.
gsm_init()
void gsm_init (void)
Definition at line 144 of file gsm.c.
References foo, gcs_index, gcs_index_max, gsm_status, LED_ON, STATUS_NONE, and STATUS_POWERON.
gsm_init_report()
void gsm_init_report (void)
Definition at line 167 of file gsm.c.
References foo, gsm_buf_idx, gsm_line_received, gsm_status, Send_AT(), STATUS_NONE, and STATUS_SEND_AT.
gsm_periodic_1Hz()
void gsm_periodic_1Hz (void)
gsm_send_report()
void gsm_send_report (void)
Definition at line 385 of file gsm.c.
References gsm_status, Send_CSQ(), STATUS_CSQ, and STATUS_IDLE.
gsm_start()
void gsm_start (void)
gsm_stop()
void gsm_stop (void)