Paparazzi UAS: sw/airborne/firmwares/rotorcraft/guidance/guidance_flip.c File Reference
guidance_flip.c File Reference
Open Loop guidance for making a flip.
#include "guidance_flip.h"
#include "autopilot.h"
#include "guidance_h.h"
#include "stabilization/stabilization_attitude_rc_setpoint.h"
#include "stabilization/stabilization_attitude.h"
Macros
#define STOP_ROLL_CMD_ANGLE 25.0
#define FIRST_THRUST_DURATION 0.3
#define FINAL_THRUST_LEVEL 6000
Functions
void guidance_flip_enter (void)
void guidance_flip_run (void)
Variables
uint32_t flip_counter
uint8_t flip_state
bool flip_rollout
int32_t heading_save
uint8_t autopilot_mode_old
struct Int32Vect2 flip_cmd_earth
Detailed Description
Open Loop guidance for making a flip.
You need to tune this before using. When entering this mode it saves the previous guidance mode and changes AUTO2 back to the previous mode after finishing the flip. Use it with caution!
Definition in file guidance_flip.c.
Macro Definition Documentation
#define FINAL_THRUST_LEVEL 6000
Definition at line 46 of file guidance_flip.c.
Referenced by guidance_flip_run().
#define FIRST_THRUST_DURATION 0.3
Definition at line 43 of file guidance_flip.c.
Referenced by guidance_flip_run().
#define STOP_ROLL_CMD_ANGLE 25.0
Definition at line 40 of file guidance_flip.c.
Referenced by guidance_flip_run().
Function Documentation
void guidance_flip_enter (void)
Definition at line 56 of file guidance_flip.c.
References autopilot_get_mode(), autopilot_mode_old, flip_counter, flip_rollout, flip_state, heading_save, and stabilization_attitude_get_heading_i().
Referenced by guidance_h_mode_changed().
void guidance_flip_run (void)
Definition at line 65 of file guidance_flip.c.
References ANGLE_BFP_OF_REAL, autopilot_in_flight(), autopilot_mode_auto2, autopilot_mode_old, autopilot_set_mode(), BFP_OF_REAL, FINAL_THRUST_LEVEL, FIRST_THRUST_DURATION, flip_cmd_earth, flip_counter, flip_rollout, flip_state, heading_save, Int32Eulers::phi, FloatEulers::psi, stab_att_sp_euler, stabilization_attitude_run(), stabilization_attitude_set_earth_cmd_i(), stabilization_cmd, stateGetNedToBodyEulers_i(), STOP_ROLL_CMD_ANGLE, Int32Vect2::x, and Int32Vect2::y.
Referenced by guidance_h_run().
Variable Documentation
uint8_t autopilot_mode_old
Definition at line 53 of file guidance_flip.c.
Referenced by guidance_flip_enter(), and guidance_flip_run().
struct Int32Vect2 flip_cmd_earth
Definition at line 54 of file guidance_flip.c.
Referenced by guidance_flip_run().
uint32_t flip_counter
Definition at line 49 of file guidance_flip.c.
Referenced by guidance_flip_enter(), and guidance_flip_run().
bool flip_rollout
Definition at line 51 of file guidance_flip.c.
Referenced by guidance_flip_enter(), and guidance_flip_run().
uint8_t flip_state
Definition at line 50 of file guidance_flip.c.
Referenced by guidance_flip_enter(), and guidance_flip_run().
int32_t heading_save
Definition at line 52 of file guidance_flip.c.
Referenced by guidance_flip_enter(), and guidance_flip_run().