Paparazzi UAS: sw/airborne/modules/guidance/gvf/nav/nav_line.h File Reference
nav_line.h File Reference
#include "modules/guidance/trajectories/gvf_traj.h"
#include "math/pprz_algebra_float.h"
Data Structures
struct gvf_li_par
struct gvf_seg_par
Functions
bool nav_gvf_line_XY_heading (float x, float y, float heading)
bool nav_gvf_line_wp_heading (uint8_t wp, float heading)
bool nav_gvf_line_XY1_XY2 (float x1, float y1, float x2, float y2)
bool nav_gvf_line_wp1_wp2 (uint8_t wp1, uint8_t wp2)
bool nav_gvf_segment_loop_XY1_XY2 (float x1, float y1, float x2, float y2, float d1, float d2)
bool nav_gvf_segment_loop_wp1_wp2 (uint8_t wp1, uint8_t wp2, float d1, float d2)
bool nav_gvf_segment_XY1_XY2 (float x1, float y1, float x2, float y2)
bool nav_gvf_segment_wp1_wp2 (uint8_t wp1, uint8_t wp2)
bool nav_gvf_segment_points (struct FloatVect2 start, struct FloatVect2 end)
Variables
gvf_li_par gvf_line_par
gvf_seg_par gvf_segment_par
Data Structure Documentation
gvf_li_par
struct gvf_li_par
Definition at line 41 of file nav_line.h.
Data Fields
float heading
float ke
float kn
gvf_seg_par
struct gvf_seg_par
Definition at line 52 of file nav_line.h.
Data Fields
float d1
float d2
Function Documentation
nav_gvf_line_wp1_wp2()
bool nav_gvf_line_wp1_wp2 (uint8_t wp1, uint8_t wp2) extern
Definition at line 161 of file nav_line.c.
References foo, gvf_p_len_wps, gvf_trajectory, nav_gvf_line_XY1_XY2(), gvf_tra::p, WaypointX, and WaypointY.
nav_gvf_line_wp_heading()
bool nav_gvf_line_wp_heading (uint8_t wp, float heading) extern
Definition at line 127 of file nav_line.c.
References b, foo, heading, nav_gvf_line_XY_heading(), WaypointX, and WaypointY.
nav_gvf_line_XY1_XY2()
bool nav_gvf_line_XY1_XY2 (float x1, float y1, float x2, float y2) extern
Definition at line 137 of file nav_line.c.
References foo, gvf_p_len_wps, gvf_segment, gvf_trajectory, nav_gvf_line_XY_heading(), gvf_tra::p, gvf_seg::seg, gvf_seg::x1, gvf_seg::x2, gvf_seg::y1, and gvf_seg::y2.
Referenced by nav_gvf_line_wp1_wp2(), and nav_gvf_segment_XY1_XY2().
nav_gvf_line_XY_heading()
bool nav_gvf_line_XY_heading (float a, float b, float heading) extern
Definition at line 120 of file nav_line.c.
References b, gvf_line(), gvf_set_direction(), and heading.
Referenced by nav_gvf_line_wp_heading(), and nav_gvf_line_XY1_XY2().
nav_gvf_segment_loop_wp1_wp2()
bool nav_gvf_segment_loop_wp1_wp2 (uint8_t wp1, uint8_t wp2, float d1, float d2) extern
Definition at line 201 of file nav_line.c.
References d1, d2, foo, gvf_p_len_wps, gvf_trajectory, nav_gvf_segment_loop_XY1_XY2(), gvf_tra::p, WaypointX, and WaypointY.
nav_gvf_segment_loop_XY1_XY2()
bool nav_gvf_segment_loop_XY1_XY2 (float x1, float y1, float x2, float y2, float d1, float d2) extern
Definition at line 177 of file nav_line.c.
References alpha, d1, d2, foo, gvf_line(), gvf_segment, gvf_set_direction(), out_of_segment_area(), s, gvf_seg::seg, gvf_seg::x1, gvf_seg::x2, gvf_seg::y1, and gvf_seg::y2.
Referenced by nav_gvf_segment_loop_wp1_wp2().
nav_gvf_segment_points()
bool nav_gvf_segment_points (struct FloatVect2 start, struct FloatVect2 end) extern
Definition at line 253 of file nav_line.c.
References nav_gvf_segment_XY1_XY2(), FloatVect2::x, and FloatVect2::y.
Referenced by nav_gvf_survey_polygon_run().
nav_gvf_segment_wp1_wp2()
bool nav_gvf_segment_wp1_wp2 (uint8_t wp1, uint8_t wp2) extern
Definition at line 239 of file nav_line.c.
References foo, gvf_p_len_wps, gvf_trajectory, nav_gvf_segment_XY1_XY2(), gvf_tra::p, WaypointX, and WaypointY.
nav_gvf_segment_XY1_XY2()
bool nav_gvf_segment_XY1_XY2 (float x1, float y1, float x2, float y2) extern
Definition at line 217 of file nav_line.c.
References foo, nav_gvf_line_XY1_XY2(), p, and stateGetPositionEnu_f().
Referenced by nav_gvf_segment_points(), and nav_gvf_segment_wp1_wp2().
Variable Documentation
gvf_line_par
gvf_li_par gvf_line_par extern
Definition at line 53 of file nav_line.c.
Referenced by gvf_line().
gvf_segment_par
gvf_seg_par gvf_segment_par extern
Definition at line 54 of file nav_line.c.