Paparazzi UAS: sw/airborne/firmwares/rotorcraft/guidance/guidance_oneloop.c File Reference
guidance_oneloop.c File Reference
A dummy guidance module to run the oneloop_andi controller.
#include "firmwares/rotorcraft/guidance/guidance_h.h"
#include "firmwares/rotorcraft/guidance/guidance_v.h"
#include "firmwares/rotorcraft/guidance/guidance_oneloop.h"
#include "firmwares/rotorcraft/oneloop/oneloop_andi.h"
Functions
void guidance_h_run_enter (void)
void guidance_v_run_enter (void)
struct StabilizationSetpoint guidance_h_run_pos (bool in_flight, struct HorizontalGuidance *gh)
struct StabilizationSetpoint guidance_h_run_speed (bool in_flight, struct HorizontalGuidance *gh)
struct StabilizationSetpoint guidance_h_run_accel (bool in_flight, struct HorizontalGuidance *gh)
struct ThrustSetpoint guidance_v_run_pos (bool in_flight UNUSED, struct VerticalGuidance *gv)
struct ThrustSetpoint guidance_v_run_speed (bool in_flight UNUSED, struct VerticalGuidance *gv)
struct ThrustSetpoint guidance_v_run_accel (bool in_flight UNUSED, struct VerticalGuidance *gv)
struct StabilizationSetpoint guidance_oneloop_run_mode (bool in_flight, struct HorizontalGuidance *gh, struct VerticalGuidance *gv, enum GuidanceOneloop_HMode h_mode, enum GuidanceOneloop_VMode v_mode)
Variables
struct ThrustSetpoint thrust_sp
static struct VerticalGuidance * _gv = &guidance_v
static enum GuidanceOneloop_VMode _v_mode = GUIDANCE_ONELOOP_V_POS
Detailed Description
A dummy guidance module to run the oneloop_andi controller.
Definition in file guidance_oneloop.c.
Function Documentation
guidance_h_run_accel()
struct StabilizationSetpoint guidance_h_run_accel (bool in_flight, struct HorizontalGuidance * gh)
Definition at line 58 of file guidance_oneloop.c.
References _gv, _v_mode, foo, GUIDANCE_ONELOOP_H_ACCEL, and guidance_oneloop_run_mode().
Referenced by guidance_h_from_nav().
guidance_h_run_enter()
void guidance_h_run_enter (void)
Definition at line 35 of file guidance_oneloop.c.
References CTRL_ANDI, and oneloop_andi_enter().
Referenced by guidance_h_hover_enter(), and guidance_h_nav_enter().
guidance_h_run_pos()
struct StabilizationSetpoint guidance_h_run_pos (bool in_flight, struct HorizontalGuidance * gh)
Definition at line 48 of file guidance_oneloop.c.
References _gv, _v_mode, foo, GUIDANCE_ONELOOP_H_POS, and guidance_oneloop_run_mode().
Referenced by guidance_h_from_nav(), and guidance_h_guided_run().
guidance_h_run_speed()
struct StabilizationSetpoint guidance_h_run_speed (bool in_flight, struct HorizontalGuidance * gh)
Definition at line 53 of file guidance_oneloop.c.
References _gv, _v_mode, foo, GUIDANCE_ONELOOP_H_SPEED, and guidance_oneloop_run_mode().
Referenced by guidance_h_from_nav(), and guidance_h_guided_run().
guidance_oneloop_run_mode()
struct StabilizationSetpoint guidance_oneloop_run_mode (bool in_flight, struct HorizontalGuidance * gh, struct VerticalGuidance * gv, enum GuidanceOneloop_HMode h_mode, enum GuidanceOneloop_VMode v_mode)
Definition at line 84 of file guidance_oneloop.c.
References ACCEL_FLOAT_OF_BFP, foo, GUIDANCE_ONELOOP_H_POS, GUIDANCE_ONELOOP_H_SPEED, GUIDANCE_ONELOOP_V_POS, GUIDANCE_ONELOOP_V_SPEED, OneloopGeneral::half_loop, oneloop_andi, oneloop_andi_run(), POS_FLOAT_OF_BFP, StabilizationSetpoint::sp, SPEED_FLOAT_OF_BFP, and FloatVect3::x.
Referenced by guidance_h_run_accel(), guidance_h_run_pos(), and guidance_h_run_speed().
guidance_v_run_accel()
struct ThrustSetpoint guidance_v_run_accel (bool in_flight UNUSED, struct VerticalGuidance * gv)
Definition at line 77 of file guidance_oneloop.c.
References _gv, _v_mode, foo, GUIDANCE_ONELOOP_V_ACCEL, and thrust_sp.
guidance_v_run_enter()
void guidance_v_run_enter (void)
Definition at line 40 of file guidance_oneloop.c.
Referenced by guidance_v_from_nav(), guidance_v_guided_enter(), guidance_v_mode_changed(), and guidance_v_z_enter().
guidance_v_run_pos()
struct ThrustSetpoint guidance_v_run_pos (bool in_flight UNUSED, struct VerticalGuidance * gv)
Definition at line 63 of file guidance_oneloop.c.
References _gv, _v_mode, foo, GUIDANCE_ONELOOP_V_POS, and thrust_sp.
Referenced by guidance_v_from_nav(), and guidance_v_guided_run().
guidance_v_run_speed()
struct ThrustSetpoint guidance_v_run_speed (bool in_flight UNUSED, struct VerticalGuidance * gv)
Definition at line 70 of file guidance_oneloop.c.
References _gv, _v_mode, foo, GUIDANCE_ONELOOP_V_SPEED, and thrust_sp.
Referenced by guidance_v_from_nav(), guidance_v_guided_run(), and guidance_v_run().
Variable Documentation
_gv
struct VerticalGuidance* _gv = &guidance_v static
Definition at line 45 of file guidance_oneloop.c.
Referenced by guidance_h_run_accel(), guidance_h_run_pos(), guidance_h_run_speed(), guidance_v_run_accel(), guidance_v_run_pos(), and guidance_v_run_speed().
_v_mode
enum GuidanceOneloop_VMode _v_mode = GUIDANCE_ONELOOP_V_POS static
Definition at line 46 of file guidance_oneloop.c.
Referenced by guidance_h_run_accel(), guidance_h_run_pos(), guidance_h_run_speed(), guidance_v_run_accel(), guidance_v_run_pos(), and guidance_v_run_speed().
thrust_sp
struct ThrustSetpoint thrust_sp
Definition at line 33 of file guidance_oneloop.c.
Referenced by guidance_v_run_accel(), guidance_v_run_pos(), and guidance_v_run_speed().