Paparazzi UAS: sw/airborne/firmwares/rotorcraft/guidance/guidance_indi_hybrid_quadplane.h File Reference
guidance_indi_hybrid_quadplane.h File Reference
Macros
#define GUIDANCE_INDI_MIN_PITCH -20
#define GUIDANCE_INDI_MAX_PITCH 20
Functions
void guidance_indi_quadplane_init (void)
Call upon entering indi guidance.
void guidance_indi_quadplane_propagate_filters (void)
Low pass the accelerometer measurements to remove noise from vibrations.
Macro Definition Documentation
GUIDANCE_INDI_MAX_PITCH
#define GUIDANCE_INDI_MAX_PITCH 20
Definition at line 32 of file guidance_indi_hybrid_quadplane.h.
GUIDANCE_INDI_MIN_PITCH
#define GUIDANCE_INDI_MIN_PITCH -20
Definition at line 31 of file guidance_indi_hybrid_quadplane.h.
Function Documentation
guidance_indi_quadplane_init()
void guidance_indi_quadplane_init (void) extern
Call upon entering indi guidance.
Definition at line 61 of file guidance_indi_hybrid_quadplane.c.
References accel_bodyz_filt, foo, GUIDANCE_INDI_BODYZ_FILTER_CUTOFF, and init_butterworth_2_low_pass().
guidance_indi_quadplane_propagate_filters()
void guidance_indi_quadplane_propagate_filters (void) extern
Low pass the accelerometer measurements to remove noise from vibrations.
The roll and pitch also need to be filtered to synchronize them with the acceleration Called as a periodic function with PERIODIC_FREQ
Definition at line 73 of file guidance_indi_hybrid_quadplane.c.
References accel_bodyz_filt, ACCEL_FLOAT_OF_BFP, foo, stateGetAccelBody_i(), and update_butterworth_2_low_pass().