Paparazzi UAS: sw/airborne/firmwares/rotorcraft/guidance/guidance_flip.h File Reference
guidance_flip.h File Reference
Open Loop guidance for making a flip.
Functions
void guidance_flip_enter (void)
void guidance_flip_run (void)
Detailed Description
Open Loop guidance for making a flip.
You need to tune this before using. When entering this mode it saves the previous guidance mode and changes AUTO2 back to the previous mode after finishing the flip. Use it with caution!
Definition in file guidance_flip.h.
Function Documentation
guidance_flip_enter()
void guidance_flip_enter (void)
Definition at line 56 of file guidance_flip.c.
References autopilot_get_mode(), autopilot_mode_old, flip_counter, flip_rollout, flip_state, heading_save, and stabilization_attitude_get_heading_i().
guidance_flip_run()
void guidance_flip_run (void)
Definition at line 65 of file guidance_flip.c.
References ANGLE_BFP_OF_REAL, autopilot_in_flight(), autopilot_mode_auto2, autopilot_mode_old, autopilot_set_mode(), BFP_OF_REAL, Stabilization::cmd, FINAL_THRUST_LEVEL, FIRST_THRUST_DURATION, flip_cmd_earth, flip_counter, flip_rollout, flip_state, foo, heading_save, Int32Eulers::phi, FloatEulers::psi, stab_att_sp_euler, stabilization, stabilization_attitude_run(), stateGetNedToBodyEulers_i(), STOP_ROLL_CMD_ANGLE, Int32Vect2::x, and Int32Vect2::y.