Paparazzi UAS: sw/airborne/modules/guidance/gvf_ik/nav/nav_line.c File Reference
nav_line.c File Reference
#include "nav_line.h"
#include "generated/airframe.h"
#include "modules/guidance/gvf_ik/gvf_ik.h"
Macros
#define GVF_IK_LINE_KE 1
#define GVF_IK_LINE_KN 1
#define GVF_IK_LINE_HEADING 0
#define GVF_IK_SEGMENT_D1 0
#define GVF_IK_SEGMENT_D2 0
Functions
static void gvf_ik_line (float a, float b, float heading)
static int out_of_segment_area (float x1, float y1, float x2, float y2, float d1, float d2)
bool nav_gvf_ik_line_XY_heading (float a, float b, float heading)
bool nav_gvf_ik_line_wp_heading (uint8_t wp, float heading)
bool nav_gvf_ik_line_XY1_XY2 (float x1, float y1, float x2, float y2)
bool nav_gvf_ik_line_wp1_wp2 (uint8_t wp1, uint8_t wp2)
bool nav_gvf_ik_segment_loop_XY1_XY2 (float x1, float y1, float x2, float y2, float d1, float d2)
bool nav_gvf_ik_segment_loop_wp1_wp2 (uint8_t wp1, uint8_t wp2, float d1, float d2)
bool nav_gvf_ik_segment_XY1_XY2 (float x1, float y1, float x2, float y2)
bool nav_gvf_ik_segment_wp1_wp2 (uint8_t wp1, uint8_t wp2)
Variables
gvf_ik_li_par gvf_ik_line_par = {GVF_IK_LINE_KE, GVF_IK_LINE_KN, GVF_IK_LINE_HEADING}
gvf_ik_seg_par gvf_ik_segment_par = {GVF_IK_SEGMENT_D1, GVF_IK_SEGMENT_D2}
static int gvf_p_len_wps = 0
Macro Definition Documentation
GVF_IK_LINE_HEADING
#define GVF_IK_LINE_HEADING 0
Default heading in degrees for a trajectory called from gvf_line_**_HEADING
Definition at line 40 of file nav_line.c.
GVF_IK_LINE_KE
#define GVF_IK_LINE_KE 1
Gain ke for the line trajectory
Definition at line 30 of file nav_line.c.
GVF_IK_LINE_KN
#define GVF_IK_LINE_KN 1
Gain kn for the line trajectory
Definition at line 35 of file nav_line.c.
GVF_IK_SEGMENT_D1
#define GVF_IK_SEGMENT_D1 0
In case of tracking a segment, how much distance in meters will go the vehicle beyond the point x1,y1 before turning back
Definition at line 45 of file nav_line.c.
GVF_IK_SEGMENT_D2
#define GVF_IK_SEGMENT_D2 0
In case of tracking a segment, how much distance in meters will go the vehicle beyond the point x2,y2 before turning back
Definition at line 50 of file nav_line.c.
Function Documentation
gvf_ik_line()
static void gvf_ik_line (float a, float b, float heading) static
Definition at line 61 of file nav_line.c.
References b, gvf_ik_con::error, foo, gvf_ik_control, gvf_ik_control_2D(), gvf_ik_line_par, gvf_line_info(), gvf_p_len_wps, gvf_segment, gvf_trajectory, heading, gvf_ik_con::ke, gvf_ik_li_par::ke, gvf_ik_li_par::kn, gvf_tra::p, gvf_tra::p_len, gvf_seg::seg, and gvf_tra::type.
Referenced by nav_gvf_ik_line_XY_heading(), and nav_gvf_ik_segment_loop_XY1_XY2().
nav_gvf_ik_line_wp1_wp2()
bool nav_gvf_ik_line_wp1_wp2 (uint8_t wp1, uint8_t wp2)
Definition at line 161 of file nav_line.c.
References foo, gvf_p_len_wps, gvf_trajectory, nav_gvf_ik_line_XY1_XY2(), gvf_tra::p, WaypointX, and WaypointY.
nav_gvf_ik_line_wp_heading()
bool nav_gvf_ik_line_wp_heading (uint8_t wp, float heading)
Definition at line 127 of file nav_line.c.
References b, foo, heading, nav_gvf_ik_line_XY_heading(), WaypointX, and WaypointY.
nav_gvf_ik_line_XY1_XY2()
bool nav_gvf_ik_line_XY1_XY2 (float x1, float y1, float x2, float y2)
Definition at line 137 of file nav_line.c.
References foo, gvf_p_len_wps, gvf_segment, gvf_trajectory, nav_gvf_ik_line_XY_heading(), gvf_tra::p, gvf_seg::seg, gvf_seg::x1, gvf_seg::x2, gvf_seg::y1, and gvf_seg::y2.
Referenced by nav_gvf_ik_line_wp1_wp2(), and nav_gvf_ik_segment_XY1_XY2().
nav_gvf_ik_line_XY_heading()
bool nav_gvf_ik_line_XY_heading (float a, float b, float heading)
Definition at line 120 of file nav_line.c.
References b, gvf_ik_line(), gvf_ik_set_direction(), and heading.
Referenced by nav_gvf_ik_line_wp_heading(), and nav_gvf_ik_line_XY1_XY2().
nav_gvf_ik_segment_loop_wp1_wp2()
bool nav_gvf_ik_segment_loop_wp1_wp2 (uint8_t wp1, uint8_t wp2, float d1, float d2)
Definition at line 199 of file nav_line.c.
References d1, d2, foo, gvf_p_len_wps, gvf_trajectory, nav_gvf_ik_segment_loop_XY1_XY2(), gvf_tra::p, WaypointX, and WaypointY.
nav_gvf_ik_segment_loop_XY1_XY2()
bool nav_gvf_ik_segment_loop_XY1_XY2 (float x1, float y1, float x2, float y2, float d1, float d2)
Definition at line 175 of file nav_line.c.
References alpha, d1, d2, foo, gvf_ik_line(), gvf_ik_set_direction(), gvf_segment, out_of_segment_area(), s, gvf_seg::seg, gvf_seg::x1, gvf_seg::x2, gvf_seg::y1, and gvf_seg::y2.
Referenced by nav_gvf_ik_segment_loop_wp1_wp2().
nav_gvf_ik_segment_wp1_wp2()
bool nav_gvf_ik_segment_wp1_wp2 (uint8_t wp1, uint8_t wp2)
Definition at line 237 of file nav_line.c.
References foo, gvf_p_len_wps, gvf_trajectory, nav_gvf_ik_segment_XY1_XY2(), gvf_tra::p, WaypointX, and WaypointY.
nav_gvf_ik_segment_XY1_XY2()
bool nav_gvf_ik_segment_XY1_XY2 (float x1, float y1, float x2, float y2)
Definition at line 215 of file nav_line.c.
References foo, nav_gvf_ik_line_XY1_XY2(), p, and stateGetPositionEnu_f().
Referenced by nav_gvf_ik_segment_wp1_wp2().
out_of_segment_area()
static int out_of_segment_area (float x1, float y1, float x2, float y2, float d1, float d2) static
Definition at line 85 of file nav_line.c.
References alpha, d1, d2, foo, p, s, and stateGetPositionEnu_f().
Variable Documentation
gvf_ik_line_par
gvf_ik_li_par gvf_ik_line_par = {GVF_IK_LINE_KE, GVF_IK_LINE_KN, GVF_IK_LINE_HEADING}
Definition at line 53 of file nav_line.c.
Referenced by gvf_ik_line().
gvf_ik_segment_par
gvf_ik_seg_par gvf_ik_segment_par = {GVF_IK_SEGMENT_D1, GVF_IK_SEGMENT_D2}
Definition at line 54 of file nav_line.c.
gvf_p_len_wps
int gvf_p_len_wps = 0 static
Definition at line 57 of file nav_line.c.