Paparazzi UAS: sw/airborne/firmwares/rotorcraft/guidance/guidance_plane.h File Reference
guidance_plane.h File Reference
Guidance controller for planes in rotorcraft firmware using basic PID controller no airspeed control.
#include "std.h"
#include "math/pprz_algebra_int.h"
#include "math/pprz_algebra_float.h"
Data Structures
struct GuidancePlane
Functions
void guidance_plane_init (void)
void guidance_plane_enter (void)
struct StabilizationSetpoint guidance_plane_attitude_from_nav (bool in_flight)
run horizontal control loop for position and speed control
struct ThrustSetpoint guidance_plane_thrust_from_nav (bool in_flight)
run vertical control loop for position and speed control
Variables
struct GuidancePlane guidance_plane
Guidance PID structyre.
Detailed Description
Guidance controller for planes in rotorcraft firmware using basic PID controller no airspeed control.
Definition in file guidance_plane.h.
Data Structure Documentation
GuidancePlane
struct GuidancePlane
Definition at line 39 of file guidance_plane.h.
Data Fields
float altitude_setpoint
float climb_kp
float climb_max_setpoint
float climb_setpoint
float climb_throttle_increment
float course_kd
float course_kp
float course_pre_bank_correction
float course_setpoint
float cruise_throttle
float p_kd
float p_ki
float p_kp
float pitch_cmd
float pitch_max_setpoint
float pitch_min_setpoint
float pitch_of_vz
float pitch_trim
float roll_cmd
float roll_max_setpoint
float t_kd
float t_ki
float t_kp
int32_t throttle_cmd
Function Documentation
guidance_plane_attitude_from_nav()
struct StabilizationSetpoint guidance_plane_attitude_from_nav (bool in_flight) extern
run horizontal control loop for position and speed control
Definition at line 128 of file guidance_plane.c.
References RotorcraftNavigation::carrot, GuidancePlane::course_kd, GuidancePlane::course_kp, GuidancePlane::course_setpoint, float_eulers_of_quat(), foo, guidance_h, guidance_plane, RotorcraftNavigation::horizontal_mode, nav, NAV_HORIZONTAL_MODE_ATTITUDE, NAV_HORIZONTAL_MODE_GUIDED, NAV_HORIZONTAL_MODE_NONE, NAV_SETPOINT_MODE_ACCEL, NAV_SETPOINT_MODE_POS, NAV_SETPOINT_MODE_QUAT, NAV_SETPOINT_MODE_SPEED, FloatEulers::phi, RotorcraftNavigation::pitch, GuidancePlane::pitch_cmd, HorizontalGuidanceSetpoint::pos, POS_BFP_OF_REAL, FloatEulers::psi, RotorcraftNavigation::quat, RotorcraftNavigation::roll, GuidancePlane::roll_cmd, GuidancePlane::roll_max_setpoint, RotorcraftNavigation::setpoint_mode, HorizontalGuidance::sp, RotorcraftNavigation::speed, stab_sp_from_eulers_f(), stateGetHorizontalSpeedDir_f(), stateGetNedToBodyEulers_f(), stateGetPositionEnu_f(), stateGetPositionNed_f(), FloatEulers::theta, waypoint_get_x(), waypoint_get_y(), Int32Vect2::x, EnuCoor_f::x, Int32Vect2::y, and EnuCoor_f::y.
Referenced by control_mixing_heewing_nav_run().
guidance_plane_enter()
void guidance_plane_enter (void) extern
Definition at line 276 of file guidance_plane.c.
References pitch_sum_err, and throttle_sum_err.
guidance_plane_init()
void guidance_plane_init (void) extern
Definition at line 90 of file guidance_plane.c.
References GuidancePlane::altitude_setpoint, GuidancePlane::climb_kp, GuidancePlane::climb_max_setpoint, GuidancePlane::climb_setpoint, GuidancePlane::climb_throttle_increment, GuidancePlane::course_kd, GuidancePlane::course_kp, GuidancePlane::course_pre_bank_correction, GuidancePlane::course_setpoint, GuidancePlane::cruise_throttle, foo, GUIDANCE_PLANCE_COURSE_PRE_BANK, guidance_plane, GUIDANCE_PLANE_CLIMB_THROTTLE_INCREMENT, GUIDANCE_PLANE_MAX_BANK, GUIDANCE_PLANE_MAX_CLIMB, GUIDANCE_PLANE_MAX_PITCH, GUIDANCE_PLANE_MIN_PITCH, GUIDANCE_PLANE_PITCH_OF_VZ, GUIDANCE_PLANE_PITCH_TRIM, GuidancePlane::p_kd, GuidancePlane::p_ki, GuidancePlane::p_kp, GuidancePlane::pitch_cmd, GuidancePlane::pitch_max_setpoint, GuidancePlane::pitch_min_setpoint, GuidancePlane::pitch_of_vz, pitch_sum_err, GuidancePlane::pitch_trim, GuidancePlane::roll_cmd, GuidancePlane::roll_max_setpoint, GuidancePlane::t_kd, GuidancePlane::t_ki, GuidancePlane::t_kp, GuidancePlane::throttle_cmd, and throttle_sum_err.
guidance_plane_thrust_from_nav()
struct ThrustSetpoint guidance_plane_thrust_from_nav (bool in_flight) extern
run vertical control loop for position and speed control
Definition at line 253 of file guidance_plane.c.
References GuidancePlane::altitude_setpoint, RotorcraftNavigation::climb, GuidancePlane::climb_kp, GuidancePlane::climb_max_setpoint, GuidancePlane::climb_setpoint, foo, guidance_plane, guidance_plane_set_pitch(), guidance_plane_set_throttle(), nav, RotorcraftNavigation::nav_altitude, NAV_VERTICAL_MODE_ALT, NAV_VERTICAL_MODE_CLIMB, NAV_VERTICAL_MODE_MANUAL, stateGetPositionEnu_f(), th_sp_from_thrust_i(), RotorcraftNavigation::throttle, GuidancePlane::throttle_cmd, THRUST_AXIS_X, RotorcraftNavigation::vertical_mode, and EnuCoor_f::z.
Referenced by control_mixing_heewing_nav_run().
Variable Documentation
guidance_plane
struct GuidancePlane guidance_plane extern
Guidance PID structyre.
Definition at line 73 of file guidance_plane.c.
Referenced by control_mixing_heewing_nav_run(), guidance_plane_attitude_from_nav(), guidance_plane_init(), guidance_plane_set_pitch(), guidance_plane_set_throttle(), and guidance_plane_thrust_from_nav().