Paparazzi UAS: sw/airborne/firmwares/rotorcraft/guidance/guidance_indi_hybrid_quadplane.c File Reference
guidance_indi_hybrid_quadplane.c File Reference
#include "firmwares/rotorcraft/guidance/guidance_indi_hybrid.h"
#include "filters/low_pass_filter.h"
#include "state.h"
#include "autopilot.h"
#include "generated/modules.h"
Macros
#define GUIDANCE_INDI_BODYZ_FILTER_CUTOFF 3.0
#define GUIDANCE_INDI_PITCH_EFF_SCALING 1.0
Functions
void guidance_indi_quadplane_init (void)
Call upon entering indi guidance.
void guidance_indi_quadplane_propagate_filters (void)
Low pass the accelerometer measurements to remove noise from vibrations.
void guidance_indi_calcg_wing (float Gmat[GUIDANCE_INDI_HYBRID_V][GUIDANCE_INDI_HYBRID_U], struct FloatVect3 a_diff, float body_v[GUIDANCE_INDI_HYBRID_V])
Perform WLS.
void WEAK guidance_indi_hybrid_set_wls_settings (float body_v[3], float roll_angle, float pitch_angle)
bool autopilot_in_flight_end_detection (bool motors_on UNUSED)
Quadplanes can still be in-flight with COMMAND_THRUST==0 and can even soar not descending in updrafts with all thrust off.
Variables
Butterworth2LowPass accel_bodyz_filt
Macro Definition Documentation
GUIDANCE_INDI_BODYZ_FILTER_CUTOFF
#define GUIDANCE_INDI_BODYZ_FILTER_CUTOFF 3.0
Definition at line 51 of file guidance_indi_hybrid_quadplane.c.
GUIDANCE_INDI_PITCH_EFF_SCALING
#define GUIDANCE_INDI_PITCH_EFF_SCALING 1.0
Function Documentation
autopilot_in_flight_end_detection()
bool autopilot_in_flight_end_detection (bool motors_on UNUSED)
Quadplanes can still be in-flight with COMMAND_THRUST==0 and can even soar not descending in updrafts with all thrust off.
Definition at line 158 of file guidance_indi_hybrid_quadplane.c.
guidance_indi_calcg_wing()
void guidance_indi_calcg_wing (float Gmat[GUIDANCE_INDI_HYBRID_V][GUIDANCE_INDI_HYBRID_U], struct FloatVect3 a_diff, float body_v[GUIDANCE_INDI_HYBRID_V])
Perform WLS.
Parameters
Gmat Dynamics matrix
a_diff acceleration errors in earth frame
body_v 3D vector to write the control objective v
Definition at line 86 of file guidance_indi_hybrid_quadplane.c.
guidance_indi_hybrid_set_wls_settings()
void guidance_indi_hybrid_set_wls_settings (float body_v[3], float roll_angle, float pitch_angle)
Definition at line 130 of file guidance_indi_hybrid_quadplane.c.
References Stabilization::cmd, foo, g1g2, guidance_indi_max_bank, GUIDANCE_INDI_MAX_PITCH, GUIDANCE_INDI_MIN_PITCH, guidance_indi_pitch_pref_deg, guidance_indi_thrust_z_eff, MAX_PPRZ, and stabilization.
Referenced by guidance_indi_run().
guidance_indi_quadplane_init()
void guidance_indi_quadplane_init (void)
Call upon entering indi guidance.
Definition at line 61 of file guidance_indi_hybrid_quadplane.c.
References accel_bodyz_filt, foo, GUIDANCE_INDI_BODYZ_FILTER_CUTOFF, and init_butterworth_2_low_pass().
guidance_indi_quadplane_propagate_filters()
void guidance_indi_quadplane_propagate_filters (void)
Low pass the accelerometer measurements to remove noise from vibrations.
The roll and pitch also need to be filtered to synchronize them with the acceleration Called as a periodic function with PERIODIC_FREQ
Definition at line 73 of file guidance_indi_hybrid_quadplane.c.
References accel_bodyz_filt, ACCEL_FLOAT_OF_BFP, foo, stateGetAccelBody_i(), and update_butterworth_2_low_pass().
Variable Documentation
accel_bodyz_filt
Butterworth2LowPass accel_bodyz_filt
Definition at line 55 of file guidance_indi_hybrid_quadplane.c.
Referenced by guidance_indi_calcg_wing(), guidance_indi_quadplane_init(), and guidance_indi_quadplane_propagate_filters().