Paparazzi UAS: sw/airborne/firmwares/rotorcraft/guidance/guidance_pid.h File Reference
guidance_pid.h File Reference
Guidance controller with PID for rotorcrafts.
#include "std.h"
#include "math/pprz_algebra_int.h"
#include "firmwares/rotorcraft/guidance/guidance_h.h"
#include "firmwares/rotorcraft/guidance/guidance_v.h"
Data Structures
struct GuidancePID
Functions
void guidance_pid_init (void)
void guidance_pid_h_enter (void)
void guidance_pid_v_enter (void)
struct StabilizationSetpoint guidance_pid_h_run_pos (bool in_flight, struct HorizontalGuidance *gh)
struct StabilizationSetpoint guidance_pid_h_run_speed (bool in_flight, struct HorizontalGuidance *gh)
struct StabilizationSetpoint guidance_pid_h_run_accel (bool in_flight, struct HorizontalGuidance *gh)
struct ThrustSetpoint guidance_pid_v_run_pos (bool in_flight, struct VerticalGuidance *gv)
struct ThrustSetpoint guidance_pid_v_run_speed (bool in_flight, struct VerticalGuidance *gv)
struct ThrustSetpoint guidance_pid_v_run_accel (bool in_flight, struct VerticalGuidance *gv)
void guidance_pid_set_h_igain (uint32_t igain)
settings handler
void guidance_pid_set_v_igain (uint32_t igain)
const struct Int32Vect2 * guidance_pid_get_h_pos_err (void)
Gets the position error.
Variables
struct GuidancePID guidance_pid
Guidance PID structyre.
Detailed Description
Guidance controller with PID for rotorcrafts.
Definition in file guidance_pid.h.
Data Structure Documentation
GuidancePID
struct GuidancePID
Definition at line 38 of file guidance_pid.h.
Data Fields
bool adapt_throttle_enabled
bool approx_force_by_thrust
struct Int32Vect2 cmd_earth
int32_t cmd_thrust
int32_t ka
int32_t kd
int32_t ki
int32_t kp
int32_t kv
int32_t v_kd
int32_t v_ki
int32_t v_kp
Function Documentation
guidance_pid_get_h_pos_err()
const struct Int32Vect2 * guidance_pid_get_h_pos_err (void) extern
Gets the position error.
Parameters
none.
Returns
Pointer to a structure containing x and y position errors
Definition at line 417 of file guidance_pid.c.
References guidance_pid_pos_err.
guidance_pid_h_enter()
void guidance_pid_h_enter (void) extern
Definition at line 389 of file guidance_pid.c.
References RotorcraftNavigation::heading, nav, FloatEulers::psi, and stateGetNedToBodyEulers_f().
guidance_pid_h_run_accel()
struct StabilizationSetpoint guidance_pid_h_run_accel (bool in_flight, struct HorizontalGuidance * gh) extern
guidance_pid_h_run_pos()
struct StabilizationSetpoint guidance_pid_h_run_pos (bool in_flight, struct HorizontalGuidance * gh) extern
Definition at line 278 of file guidance_pid.c.
References foo, guidance_pid_h_run(), guidance_pid_pos_err, guidance_pid_speed_err, MAX_POS_ERR, MAX_SPEED_ERR, stateGetPositionNed_i(), stateGetSpeedNed_i(), VECT2_DIFF, and VECT2_STRIM.
guidance_pid_h_run_speed()
struct StabilizationSetpoint guidance_pid_h_run_speed (bool in_flight, struct HorizontalGuidance * gh) extern
Definition at line 294 of file guidance_pid.c.
References foo, guidance_pid_h_run(), guidance_pid_pos_err, guidance_pid_speed_err, INT_VECT2_ZERO, MAX_SPEED_ERR, stateGetSpeedNed_i(), VECT2_DIFF, and VECT2_STRIM.
guidance_pid_init()
void guidance_pid_init (void) extern
Definition at line 184 of file guidance_pid.c.
References GuidancePID::adapt_throttle_enabled, GuidancePID::approx_force_by_thrust, GuidancePID::cmd_earth, GuidancePID::cmd_thrust, DefaultPeriodic, foo, GUIDANCE_H_AGAIN, GUIDANCE_H_APPROX_FORCE_BY_THRUST, GUIDANCE_H_VGAIN, guidance_pid, guidance_pid_pos_err, guidance_pid_speed_err, guidance_pid_trim_att_integrator, guidance_pid_v_fb_cmd, guidance_pid_v_ff_cmd, guidance_pid_z_sum_err, GUIDANCE_V_ADAPT_THROTTLE_ENABLED, INT_VECT2_ZERO, GuidancePID::ka, GuidancePID::kd, GuidancePID::ki, GuidancePID::kp, GuidancePID::kv, register_periodic_telemetry(), send_hover_loop(), send_vert_loop(), GuidancePID::v_kd, GuidancePID::v_ki, and GuidancePID::v_kp.
guidance_pid_set_h_igain()
void guidance_pid_set_h_igain (uint32_t igain) extern
settings handler
Definition at line 404 of file guidance_pid.c.
References guidance_pid, guidance_pid_trim_att_integrator, INT_VECT2_ZERO, and GuidancePID::ki.
guidance_pid_set_v_igain()
void guidance_pid_set_v_igain (uint32_t igain) extern
Definition at line 410 of file guidance_pid.c.
References guidance_pid, guidance_pid_z_sum_err, and GuidancePID::v_ki.
guidance_pid_v_enter()
void guidance_pid_v_enter (void) extern
Definition at line 395 of file guidance_pid.c.
References guidance_pid_z_sum_err.
guidance_pid_v_run_accel()
struct ThrustSetpoint guidance_pid_v_run_accel (bool in_flight, struct VerticalGuidance * gv) extern
guidance_pid_v_run_pos()
struct ThrustSetpoint guidance_pid_v_run_pos (bool in_flight, struct VerticalGuidance * gv) extern
Definition at line 371 of file guidance_pid.c.
References foo, and guidance_pid_v_run().
Referenced by guidance_hybrid_v_run_pos().
guidance_pid_v_run_speed()
struct ThrustSetpoint guidance_pid_v_run_speed (bool in_flight, struct VerticalGuidance * gv) extern
Definition at line 376 of file guidance_pid.c.
References foo, and guidance_pid_v_run().
Referenced by guidance_hybrid_v_run_speed().
Variable Documentation
guidance_pid
struct GuidancePID guidance_pid extern
Guidance PID structyre.
Definition at line 124 of file guidance_pid.c.
Referenced by guidance_hybrid_vertical(), guidance_pid_h_run(), guidance_pid_init(), guidance_pid_set_h_igain(), guidance_pid_set_v_igain(), guidance_pid_v_run(), send_hover_loop(), and send_vert_loop().