Paparazzi UAS: sw/airborne/firmwares/rotorcraft/guidance/guidance_oneloop.h File Reference
guidance_oneloop.h File Reference
A dummy guidance mode to run the oneloop_andi controller.
#include "firmwares/rotorcraft/oneloop/oneloop_andi.h"
Enumerations
enum GuidanceOneloop_HMode { GUIDANCE_ONELOOP_H_POS , GUIDANCE_ONELOOP_H_SPEED , GUIDANCE_ONELOOP_H_ACCEL }
enum GuidanceOneloop_VMode { GUIDANCE_ONELOOP_V_POS , GUIDANCE_ONELOOP_V_SPEED , GUIDANCE_ONELOOP_V_ACCEL }
Functions
struct StabilizationSetpoint guidance_oneloop_run_mode (bool in_flight, struct HorizontalGuidance *gh, struct VerticalGuidance *gv, enum GuidanceOneloop_HMode h_mode, enum GuidanceOneloop_VMode v_mode)
Detailed Description
A dummy guidance mode to run the oneloop_andi controller.
Definition in file guidance_oneloop.h.
Enumeration Type Documentation
GuidanceOneloop_HMode
enum GuidanceOneloop_HMode
Enumerator
GUIDANCE_ONELOOP_H_POS
GUIDANCE_ONELOOP_H_SPEED
GUIDANCE_ONELOOP_H_ACCEL
Definition at line 33 of file guidance_oneloop.h.
GuidanceOneloop_VMode
enum GuidanceOneloop_VMode
Enumerator
GUIDANCE_ONELOOP_V_POS
GUIDANCE_ONELOOP_V_SPEED
GUIDANCE_ONELOOP_V_ACCEL
Definition at line 39 of file guidance_oneloop.h.
Function Documentation
guidance_oneloop_run_mode()
struct StabilizationSetpoint guidance_oneloop_run_mode (bool in_flight, struct HorizontalGuidance * gh, struct VerticalGuidance * gv, enum GuidanceOneloop_HMode h_mode, enum GuidanceOneloop_VMode v_mode) extern
Definition at line 84 of file guidance_oneloop.c.
References ACCEL_FLOAT_OF_BFP, foo, GUIDANCE_ONELOOP_H_POS, GUIDANCE_ONELOOP_H_SPEED, GUIDANCE_ONELOOP_V_POS, GUIDANCE_ONELOOP_V_SPEED, OneloopGeneral::half_loop, oneloop_andi, oneloop_andi_run(), POS_FLOAT_OF_BFP, StabilizationSetpoint::sp, SPEED_FLOAT_OF_BFP, and FloatVect3::x.
Referenced by guidance_h_run_accel(), guidance_h_run_pos(), and guidance_h_run_speed().