Paparazzi UAS: sw/airborne/firmwares/rotorcraft/guidance/guidance_indi.h File Reference
guidance_indi.h File Reference
A guidance mode based on Incremental Nonlinear Dynamic Inversion.
#include "std.h"
#include "math/pprz_algebra_int.h"
#include "math/pprz_algebra_float.h"
#include "firmwares/rotorcraft/guidance.h"
#include "firmwares/rotorcraft/stabilization.h"
Macros
#define GUIDANCE_INDI_NV 3
#define GUIDANCE_INDI_NU 3
Enumerations
enum GuidanceIndi_HMode { GUIDANCE_INDI_H_POS , GUIDANCE_INDI_H_SPEED , GUIDANCE_INDI_H_ACCEL }
enum GuidanceIndi_VMode { GUIDANCE_INDI_V_POS , GUIDANCE_INDI_V_SPEED , GUIDANCE_INDI_V_ACCEL }
Functions
void guidance_indi_init (void)
Init function.
void guidance_indi_enter (void)
Call upon entering indi guidance.
struct StabilizationSetpoint guidance_indi_run (struct FloatVect3 *accep_sp, float heading_sp)
struct StabilizationSetpoint guidance_indi_run_mode (bool in_flight, struct HorizontalGuidance *gh, struct VerticalGuidance *gv, enum GuidanceIndi_HMode h_mode, enum GuidanceIndi_VMode v_mode)
struct FloatVect3 guidance_indi_controller (bool in_flight, struct HorizontalGuidance *gh, struct VerticalGuidance *gv, enum GuidanceIndi_HMode h_mode, enum GuidanceIndi_VMode v_mode)
void guidance_indi_calcG (float Gmat[GUIDANCE_INDI_NV][GUIDANCE_INDI_NU], const struct FloatQuat *att)
Variables
float guidance_indi_specific_force_gain
float guidance_indi_pos_gain
float guidance_indi_speed_gain
float guidance_indi_max_bank
Detailed Description
A guidance mode based on Incremental Nonlinear Dynamic Inversion.
Definition in file guidance_indi.h.
Macro Definition Documentation
GUIDANCE_INDI_NU
#define GUIDANCE_INDI_NU 3
Definition at line 63 of file guidance_indi.h.
GUIDANCE_INDI_NV
#define GUIDANCE_INDI_NV 3
Definition at line 58 of file guidance_indi.h.
Enumeration Type Documentation
GuidanceIndi_HMode
enum GuidanceIndi_HMode
Enumerator
GUIDANCE_INDI_H_POS
GUIDANCE_INDI_H_SPEED
GUIDANCE_INDI_H_ACCEL
Definition at line 39 of file guidance_indi.h.
GuidanceIndi_VMode
enum GuidanceIndi_VMode
Enumerator
GUIDANCE_INDI_V_POS
GUIDANCE_INDI_V_SPEED
GUIDANCE_INDI_V_ACCEL
Definition at line 45 of file guidance_indi.h.
Function Documentation
guidance_indi_calcG()
void guidance_indi_calcG (float Gmat[GUIDANCE_INDI_NV][GUIDANCE_INDI_NU], const struct FloatQuat * att) extern
Referenced by guidance_indi_run().
guidance_indi_controller()
struct FloatVect3 guidance_indi_controller (bool in_flight, struct HorizontalGuidance * gh, struct VerticalGuidance * gv, enum GuidanceIndi_HMode h_mode, enum GuidanceIndi_VMode v_mode) extern
Definition at line 352 of file guidance_indi.c.
References ACCEL_FLOAT_OF_BFP, foo, GUIDANCE_INDI_H_ACCEL, GUIDANCE_INDI_H_SPEED, guidance_indi_pos_gain, guidance_indi_speed_gain, GUIDANCE_INDI_V_ACCEL, GUIDANCE_INDI_V_SPEED, POS_FLOAT_OF_BFP, SPEED_FLOAT_OF_BFP, speed_sp, stateGetPositionNed_f(), stateGetSpeedNed_f(), FloatVect3::x, NedCoor_f::x, FloatVect3::y, NedCoor_f::y, FloatVect3::z, and NedCoor_f::z.
Referenced by guidance_indi_run_mode().
guidance_indi_enter()
void guidance_indi_enter (void) extern
Call upon entering indi guidance.
Definition at line 214 of file guidance_indi.c.
guidance_indi_init()
void guidance_indi_init (void) extern
Init function.
Definition at line 199 of file guidance_indi.c.
guidance_indi_run()
struct StabilizationSetpoint guidance_indi_run (struct FloatVect3 * accel_sp, float heading_sp) extern
Parameters
accel_sp accel setpoint in NED frame [m/s^2]
heading_sp the desired heading [rad]
Returns
stabilization setpoint structure
main indi guidance function
Definition at line 246 of file guidance_indi.c.
guidance_indi_run_mode()
struct StabilizationSetpoint guidance_indi_run_mode (bool in_flight, struct HorizontalGuidance * gh, struct VerticalGuidance * gv, enum GuidanceIndi_HMode h_mode, enum GuidanceIndi_VMode v_mode) extern
Definition at line 403 of file guidance_indi.c.
References foo, get_sys_time_float(), guidance_indi_controller(), guidance_indi_run(), guidance_indi_speed_gain, indi_accel_sp, indi_accel_sp_set_2d, indi_accel_sp_set_3d, speed_sp, stateGetSpeedNed_f(), time_of_accel_sp_2d, time_of_accel_sp_3d, FloatVect3::x, FloatVect3::y, FloatVect3::z, and NedCoor_f::z.
Variable Documentation
guidance_indi_max_bank
float guidance_indi_max_bank extern
Definition at line 156 of file guidance_indi.c.
guidance_indi_pos_gain
float guidance_indi_pos_gain extern
Definition at line 54 of file guidance_indi.c.
Referenced by guidance_indi_controller().
guidance_indi_specific_force_gain
float guidance_indi_specific_force_gain extern
Referenced by ctrl_eff_scheduling_periodic(), and guidance_indi_run().
guidance_indi_speed_gain
float guidance_indi_speed_gain extern
Definition at line 60 of file guidance_indi.c.
Referenced by guidance_indi_controller(), and guidance_indi_run_mode().