Paparazzi UAS: sw/airborne/firmwares/rotorcraft/guidance/guidance_indi_hybrid_tailsitter.c File Reference
guidance_indi_hybrid_tailsitter.c File Reference
#include "firmwares/rotorcraft/guidance/guidance_indi_hybrid.h"
#include "firmwares/rotorcraft/guidance/guidance_indi_hybrid_tailsitter.h"
#include "state.h"
#include "generated/modules.h"
Macros
#define GUIDANCE_INDI_PITCH_EFF_SCALING 1.0
Functions
void guidance_indi_calcg_wing (float Gmat[GUIDANCE_INDI_HYBRID_V][GUIDANCE_INDI_HYBRID_U], struct FloatVect3 a_diff, float v_gih[GUIDANCE_INDI_HYBRID_V])
Calculate the matrix of partial derivatives of the roll, pitch and thrust w.r.t.
Macro Definition Documentation
GUIDANCE_INDI_PITCH_EFF_SCALING
#define GUIDANCE_INDI_PITCH_EFF_SCALING 1.0
Function Documentation
guidance_indi_calcg_wing()
void guidance_indi_calcg_wing (float Gmat[GUIDANCE_INDI_HYBRID_V][GUIDANCE_INDI_HYBRID_U], struct FloatVect3 a_diff, float v_gih[GUIDANCE_INDI_HYBRID_V])
Calculate the matrix of partial derivatives of the roll, pitch and thrust w.r.t.
Perform WLS.
the NED accelerations, taking into account the lift of a wing that is horizontal at -90 degrees pitch
Parameters
Gmat Dynamics matrix
a_diff acceleration errors in earth frame
body_v 3D vector to write the control objective v
Definition at line 41 of file guidance_indi_hybrid_tailsitter.c.
References accel_bodyz_filt, float_eulers_of_quat_zxy(), foo, Gmat, guidance_indi_get_liftd(), GUIDANCE_INDI_PITCH_EFF_SCALING, SecondOrderLowPass::o, QuatSecondOrderLowPass::quat, quat_filt, stateGetAirspeed_f(), and v_gih.
Referenced by guidance_indi_run().