Paparazzi UAS: sw/airborne/firmwares/rotorcraft/guidance/guidance_indi_fully_actuated.c File Reference
guidance_indi_fully_actuated.c File Reference
Fully actuated plateform can be achieve with hexa-copter with tilted propellers for example TODO cite Mohamad Hachem.
#include "firmwares/rotorcraft/guidance/guidance_indi.h"
#include "firmwares/rotorcraft/stabilization/stabilization_indi.h"
#include "state.h"
#include "generated/modules.h"
Macros
#define GUIDANCE_INDI_MAX_H_THRUST 2.f
#define GUIDANCE_INDI_MAX_V_THRUST 15.f
Functions
static void guidance_indi_calcG_yxz (float Gmat[3][6], struct FloatEulers euler_yxz)
void guidance_indi_calcG (float Gmat[3][6], struct FloatEulers euler)
Compute effectiveness matrix for guidance.
void guidance_indi_set_wls_settings (struct WLS_t *wls, struct FloatEulers *euler_yxz, float heading_sp)
Variables
float guidance_indi_max_h_thrust = GUIDANCE_INDI_MAX_H_THRUST
float guidance_indi_max_v_thrust = GUIDANCE_INDI_MAX_V_THRUST
Detailed Description
Fully actuated plateform can be achieve with hexa-copter with tilted propellers for example TODO cite Mohamad Hachem.
Definition in file guidance_indi_fully_actuated.c.
Macro Definition Documentation
GUIDANCE_INDI_MAX_H_THRUST
#define GUIDANCE_INDI_MAX_H_THRUST 2.f
Definition at line 38 of file guidance_indi_fully_actuated.c.
GUIDANCE_INDI_MAX_V_THRUST
#define GUIDANCE_INDI_MAX_V_THRUST 15.f
Definition at line 42 of file guidance_indi_fully_actuated.c.
Function Documentation
guidance_indi_calcG()
void guidance_indi_calcG (float Gmat[3][6], struct FloatEulers euler)
Compute effectiveness matrix for guidance.
Parameters
Gmat Dynamics matrix
Definition at line 105 of file guidance_indi_fully_actuated.c.
References Gmat, and guidance_indi_calcG_yxz().
guidance_indi_calcG_yxz()
static void guidance_indi_calcG_yxz (float Gmat[3][6], struct FloatEulers euler_yxz) static
Parameters
Gmat array to write the matrix to [3x6]
Calculate the matrix of partial derivatives of the pitch, roll and thrust. w.r.t. the NED accelerations for YXZ eulers ddx = G*[dphi,dtheta,dpsi,dTx,dTy,dTz]
Definition at line 55 of file guidance_indi_fully_actuated.c.
References foo, Gmat, stab_thrust_filt, FloatVect3::x, FloatVect3::y, and FloatVect3::z.
Referenced by guidance_indi_calcG().
guidance_indi_set_wls_settings()
void guidance_indi_set_wls_settings (struct WLS_t * wls, struct FloatEulers * euler_yxz, float heading_sp)
Definition at line 109 of file guidance_indi_fully_actuated.c.
References foo, guidance_indi_max_bank, guidance_indi_max_h_thrust, guidance_indi_max_v_thrust, MAX_PPRZ, FloatEulers::phi, radio_control_get(), RADIO_PITCH, RADIO_ROLL, stab_thrust_filt, FloatVect3::x, FloatVect3::y, and FloatVect3::z.
Referenced by guidance_indi_run().
Variable Documentation
guidance_indi_max_h_thrust
float guidance_indi_max_h_thrust = GUIDANCE_INDI_MAX_H_THRUST
Definition at line 45 of file guidance_indi_fully_actuated.c.
Referenced by guidance_indi_set_wls_settings().
guidance_indi_max_v_thrust
float guidance_indi_max_v_thrust = GUIDANCE_INDI_MAX_V_THRUST
Definition at line 46 of file guidance_indi_fully_actuated.c.
Referenced by guidance_indi_set_wls_settings().