Paparazzi UAS: sw/airborne/firmwares/rotorcraft/guidance/guidance_indi_quadrotor.c File Reference
guidance_indi_quadrotor.c File Reference
#include "firmwares/rotorcraft/guidance/guidance_indi.h"
#include "filters/low_pass_filter.h"
#include "state.h"
#include "autopilot.h"
#include "generated/modules.h"
Functions
static UNUSED void guidance_indi_calcG_zyx (float Gmat[3][3], struct FloatEulers euler_zyx)
static void guidance_indi_calcG_yxz (float Gmat[3][3], struct FloatEulers euler_yxz)
void guidance_indi_calcG (float Gmat[3][3], struct FloatEulers att)
Compute effectiveness matrix for guidance.
Function Documentation
guidance_indi_calcG()
void guidance_indi_calcG (float Gmat[3][3], struct FloatEulers att)
Compute effectiveness matrix for guidance.
Parameters
Gmat Dynamics matrix
Definition at line 92 of file guidance_indi_quadrotor.c.
References Gmat, guidance_indi_calcG_yxz(), and guidance_indi_calcG_zyx().
guidance_indi_calcG_yxz()
static void guidance_indi_calcG_yxz (float Gmat[3][3], struct FloatEulers euler_yxz) static
Parameters
Gmat array to write the matrix to [3x3]
Calculate the matrix of partial derivatives of the pitch, roll and thrust. w.r.t. the NED accelerations for YXZ eulers ddx = G*[dtheta,dphi,dT]
Definition at line 68 of file guidance_indi_quadrotor.c.
References foo, and Gmat.
Referenced by guidance_indi_calcG().
guidance_indi_calcG_zyx()
static UNUSED void guidance_indi_calcG_zyx (float Gmat[3][3], struct FloatEulers euler_zyx) static
Parameters
Gmat array to write the matrix to [3x3]
Calculate the matrix of partial derivatives of the roll, pitch and thrust. w.r.t. the NED accelerations for ZYX eulers ddx = G*[dtheta,dphi,dT]
Definition at line 39 of file guidance_indi_quadrotor.c.
References foo, and Gmat.
Referenced by guidance_indi_calcG().