Paparazzi UAS: sw/airborne/modules/guidance/gvf_ik/gvf_ik.c File Reference
gvf_ik.c File Reference
#include <math.h>
#include "std.h"
#include "gvf_ik.h"
#include "autopilot.h"
#include "modules/datalink/telemetry.h"
Functions
static void send_gvf (struct transport_tx *trans, struct link_device *dev)
TELEMETRY -----------------------------------------------------------—.
static void reset_gamma_t0 (void)
STATIC FUNCTIONS ----------------------------------------------------—.
static bool check_alpha (float ke, float J1, float J2, float phi, float speed)
void gvf_ik_init (void)
EXTERN FUNCTIONS ----------------------------------------------------—.
void gvf_ik_control_2D (float ke, float kn, float phi, struct gvf_grad *grad, struct gvf_Hess *hess)
void gvf_ik_set_direction (int8_t s)
Variables
gvf_ik_con gvf_ik_control = {0}
gvf_ik_tel gvf_ik_telemetry = {0}
static uint32_t gamma_t0 = 0
static uint32_t last_gvf_t0 = 0
Function Documentation
check_alpha()
static bool check_alpha (float ke, float J1, float J2, float phi, float speed) static
Definition at line 104 of file gvf_ik.c.
References foo, gvf_ik_con::gamma, gvf_ik_con::gamma_dot, and gvf_ik_control.
Referenced by gvf_ik_control_2D().
gvf_ik_control_2D()
void gvf_ik_control_2D (float ke, float kn, float phi, struct gvf_grad * grad, struct gvf_Hess * hess)
Definition at line 141 of file gvf_ik.c.
References alpha, check_alpha(), gvf_common_state::course, course, gvf_ik_con::error, gvf_ik_con::error_n, foo, gvf_ik_con::gamma, gvf_ik_con::gamma_amplitude, gvf_ik_con::gamma_dot, gvf_ik_con::gamma_omega, gamma_t0, get_sys_time_msec(), gvf_c_info, gvf_c_state, gvf_ik_control, gvf_ik_telemetry, gvf_low_level_control_2D(), gvf_low_level_getState(), gvf_common_info::kappa, last_gvf_t0, gvf_ik_tel::n_norm, gvf_ik_tel::omega, gvf_ik_tel::omega_d, gvf_common_info::ori_err, gvf_ik_con::phi, gvf_common_state::px_dot, gvf_common_state::py_dot, reset_gamma_t0(), gvf_ik_con::s, s, and gvf_ik_tel::t_norm.
Referenced by gvf_ik_line(), nav_gvf_ik_ellipse_XY(), and nav_gvf_ik_sin_XY_alpha().
gvf_ik_init()
void gvf_ik_init (void)
EXTERN FUNCTIONS ----------------------------------------------------—.
Definition at line 123 of file gvf_ik.c.
References DefaultPeriodic, foo, gvf_ik_con::gamma_amplitude, gvf_ik_con::gamma_omega, gvf_ik_control, GVF_IK_GAMMA_AMPLITUDE, GVF_IK_GAMMA_OMEGA, gvf_trajectory, gvf_ik_con::ke, gvf_ik_con::kn, NONE, register_periodic_telemetry(), reset_gamma_t0(), gvf_ik_con::s, send_gvf(), and gvf_tra::type.
gvf_ik_set_direction()
void gvf_ik_set_direction (int8_t s)
Definition at line 294 of file gvf_ik.c.
References gvf_ik_control, gvf_ik_con::s, and s.
Referenced by nav_gvf_ik_line_XY_heading(), and nav_gvf_ik_segment_loop_XY1_XY2().
reset_gamma_t0()
static void reset_gamma_t0 (void) static
STATIC FUNCTIONS ----------------------------------------------------—.
Definition at line 99 of file gvf_ik.c.
References gamma_t0, and get_sys_time_msec().
Referenced by gvf_ik_control_2D(), and gvf_ik_init().
send_gvf()
static void send_gvf (struct transport_tx * trans, struct link_device * dev) static
TELEMETRY -----------------------------------------------------------—.
Definition at line 46 of file gvf_ik.c.
References dev, ELLIPSE, gvf_ik_con::error, gvf_ik_con::error_n, foo, gvf_ik_con::gamma, gvf_ik_con::gamma_amplitude, gvf_ik_con::gamma_dot, gvf_ik_con::gamma_omega, get_sys_time_msec(), gvf_ik_control, gvf_ik_telemetry, gvf_segment, gvf_trajectory, gvf_ik_con::ke, last_gvf_t0, LINE, gvf_ik_tel::n_norm, gvf_ik_tel::omega, gvf_ik_tel::omega_d, gvf_tra::p, gvf_tra::p_len, gvf_ik_con::phi, gvf_ik_con::s, gvf_seg::seg, gvf_ik_tel::t_norm, gvf_tra::type, gvf_seg::x1, gvf_seg::x2, gvf_seg::y1, and gvf_seg::y2.
Referenced by gvf_ik_init().
Variable Documentation
gamma_t0
uint32_t gamma_t0 = 0 static
Definition at line 39 of file gvf_ik.c.
Referenced by gvf_ik_control_2D(), and reset_gamma_t0().
gvf_ik_control
gvf_ik_con gvf_ik_control = {0}
Definition at line 35 of file gvf_ik.c.
Referenced by check_alpha(), gvf_ik_control_2D(), gvf_ik_init(), gvf_ik_line(), gvf_ik_set_direction(), nav_gvf_ik_ellipse_XY(), nav_gvf_ik_sin_XY_alpha(), and send_gvf().
gvf_ik_telemetry
gvf_ik_tel gvf_ik_telemetry = {0}
Definition at line 36 of file gvf_ik.c.
Referenced by gvf_ik_control_2D(), and send_gvf().
last_gvf_t0
uint32_t last_gvf_t0 = 0 static
Definition at line 40 of file gvf_ik.c.
Referenced by gvf_ik_control_2D(), and send_gvf().