Paparazzi UAS: sw/airborne/modules/guidance/gvf_ik/gvf_ik.h File Reference
gvf_ik.h File Reference
#include "std.h"
#include "modules/guidance/gvf_common.h"
#include "modules/guidance/trajectories/gvf_traj.h"
Data Structures
struct gvf_ik_con
struct gvf_ik_tel
Macros
#define GVF_GRAVITY 9.806
#define GVF_IK_GAMMA_AMPLITUDE 0
#define GVF_IK_GAMMA_OMEGA 0
#define GVF_OCAML_GCS true
Functions
void gvf_ik_init (void)
EXTERN FUNCTIONS ----------------------------------------------------—.
void gvf_ik_control_2D (float ke, float kn, float e, struct gvf_grad *, struct gvf_Hess *)
void gvf_ik_set_direction (int8_t s)
Variables
gvf_ik_con gvf_ik_control
Data Structure Documentation
gvf_ik_con
struct gvf_ik_con
Definition at line 60 of file gvf_ik.h.
Data Fields
float error
float error_n
float gamma
float gamma_amplitude
float gamma_dot
float gamma_omega
float ke
float kn
float phi
int8_t s
gvf_ik_tel
struct gvf_ik_tel
Definition at line 74 of file gvf_ik.h.
Data Fields
float n_norm
float omega
float omega_d
float t_norm
Macro Definition Documentation
GVF_GRAVITY
#define GVF_GRAVITY 9.806
Definition at line 31 of file gvf_ik.h.
GVF_IK_GAMMA_AMPLITUDE
#define GVF_IK_GAMMA_AMPLITUDE 0
GVF-IK settings
Definition at line 35 of file gvf_ik.h.
GVF_IK_GAMMA_OMEGA
#define GVF_IK_GAMMA_OMEGA 0
Definition at line 39 of file gvf_ik.h.
GVF_OCAML_GCS
#define GVF_OCAML_GCS true
Default GCS trajectory painter
Definition at line 44 of file gvf_ik.h.
Function Documentation
gvf_ik_control_2D()
void gvf_ik_control_2D (float ke, float kn, float e, struct gvf_grad * grad, struct gvf_Hess * hess) extern
Definition at line 141 of file gvf_ik.c.
References alpha, check_alpha(), gvf_common_state::course, course, gvf_ik_con::error, gvf_ik_con::error_n, foo, gvf_ik_con::gamma, gvf_ik_con::gamma_amplitude, gvf_ik_con::gamma_dot, gvf_ik_con::gamma_omega, gamma_t0, get_sys_time_msec(), gvf_c_info, gvf_c_state, gvf_ik_control, gvf_ik_telemetry, gvf_low_level_control_2D(), gvf_low_level_getState(), gvf_common_info::kappa, last_gvf_t0, gvf_ik_tel::n_norm, gvf_ik_tel::omega, gvf_ik_tel::omega_d, gvf_common_info::ori_err, gvf_ik_con::phi, gvf_common_state::px_dot, gvf_common_state::py_dot, reset_gamma_t0(), gvf_ik_con::s, s, and gvf_ik_tel::t_norm.
Referenced by gvf_ik_line(), nav_gvf_ik_ellipse_XY(), and nav_gvf_ik_sin_XY_alpha().
gvf_ik_init()
void gvf_ik_init (void) extern
EXTERN FUNCTIONS ----------------------------------------------------—.
Definition at line 123 of file gvf_ik.c.
References DefaultPeriodic, foo, gvf_ik_con::gamma_amplitude, gvf_ik_con::gamma_omega, gvf_ik_control, GVF_IK_GAMMA_AMPLITUDE, GVF_IK_GAMMA_OMEGA, gvf_trajectory, gvf_ik_con::ke, gvf_ik_con::kn, NONE, register_periodic_telemetry(), reset_gamma_t0(), gvf_ik_con::s, send_gvf(), and gvf_tra::type.
gvf_ik_set_direction()
void gvf_ik_set_direction (int8_t s) extern
Definition at line 294 of file gvf_ik.c.
References gvf_ik_control, gvf_ik_con::s, and s.
Referenced by nav_gvf_ik_line_XY_heading(), and nav_gvf_ik_segment_loop_XY1_XY2().
Variable Documentation
gvf_ik_control
gvf_ik_con gvf_ik_control extern
Definition at line 35 of file gvf_ik.c.
Referenced by check_alpha(), gvf_ik_control_2D(), gvf_ik_init(), gvf_ik_line(), gvf_ik_set_direction(), nav_gvf_ik_ellipse_XY(), nav_gvf_ik_sin_XY_alpha(), and send_gvf().