Paparazzi UAS: sw/airborne/modules/guidance/gvf_common.c File Reference
gvf_common.c File Reference
#include "gvf_common.h"
#include "generated/modules.h"
Functions
void gvf_low_level_getState (void)
void gvf_low_level_control_2D (float omega)
void gvf_low_level_control_3D (float heading_rate, float climbing_rate)
bool gvf_nav_approaching (float wp_x, float wp_y, float from_x, float from_y, float t)
Variables
gvf_common_ctrl gvf_c_ctrl
gvf_common_info gvf_c_info
gvf_common_params gvf_c_params = {1,1}
gvf_common_state gvf_c_state
Function Documentation
gvf_low_level_control_2D()
void gvf_low_level_control_2D (float omega)
Definition at line 58 of file gvf_common.c.
References AP_MODE_AUTO2, autopilot_get_mode(), foo, ground_speed, gvf_c_ctrl, gvf_c_params, GVF_GRAVITY, h_ctl_roll_max_setpoint, h_ctl_roll_setpoint, gvf_common_params::k_roll, lateral_mode, LATERAL_MODE_ROLL, gvf_common_ctrl::omega, stateGetHorizontalSpeedNorm_f(), stateGetNedToBodyEulers_f(), and FloatEulers::theta.
Referenced by gvf_control_2D(), gvf_ik_control_2D(), gvf_low_level_control_3D(), and gvf_parametric_control_2D().
gvf_low_level_control_3D()
void gvf_low_level_control_3D (float heading_rate, float climbing_rate)
Definition at line 79 of file gvf_common.c.
References AP_MODE_AUTO2, autopilot_get_mode(), foo, ground_speed, gvf_c_params, GVF_GRAVITY, gvf_low_level_control_2D(), h_ctl_roll_max_setpoint, h_ctl_roll_setpoint, gvf_common_params::k_climb, gvf_common_params::k_roll, lateral_mode, LATERAL_MODE_ROLL, stateGetHorizontalSpeedNorm_f(), stateGetNedToBodyEulers_f(), FloatEulers::theta, v_ctl_climb_setpoint, v_ctl_mode, V_CTL_MODE_AUTO_CLIMB, v_ctl_speed_mode, and V_CTL_SPEED_THROTTLE.
gvf_low_level_getState()
void gvf_low_level_getState (void)
Definition at line 37 of file gvf_common.c.
References gvf_common_state::course, foo, ground_speed, gvf_c_state, FloatEulers::psi, gvf_common_state::px, gvf_common_state::px_dot, gvf_common_state::py, gvf_common_state::py_dot, stateGetHorizontalSpeedDir_f(), stateGetHorizontalSpeedNorm_f(), stateGetNedToBodyEulers_f(), stateGetPositionEnu_f(), stateGetSpeedEnu_f(), EnuCoor_f::x, and EnuCoor_f::y.
Referenced by gvf_control_2D(), and gvf_ik_control_2D().
gvf_nav_approaching()
bool gvf_nav_approaching (float wp_x, float wp_y, float from_x, float from_y, float t)
Definition at line 106 of file gvf_common.c.
References foo, nav, RotorcraftNavigation::nav_approaching, nav_approaching_xy(), EnuCoor_f::x, and EnuCoor_f::y.
Variable Documentation
gvf_c_ctrl
gvf_common_ctrl gvf_c_ctrl
Definition at line 28 of file gvf_common.c.
Referenced by gvf_low_level_control_2D(), and gvf_parametric_control_2D().
gvf_c_info
gvf_common_info gvf_c_info
Definition at line 29 of file gvf_common.c.
Referenced by gvf_control_2D(), gvf_ik_control_2D(), and gvf_parametric_control_2D().
gvf_c_params
gvf_common_params gvf_c_params = {1,1}
Definition at line 30 of file gvf_common.c.
Referenced by gvf_low_level_control_2D(), gvf_low_level_control_3D(), and gvf_parametric_init().
gvf_c_state
gvf_common_state gvf_c_state
Definition at line 33 of file gvf_common.c.
Referenced by gvf_control_2D(), gvf_ik_control_2D(), and gvf_low_level_getState().