Paparazzi UAS: sw/airborne/modules/digital_cam/hackhd.h File Reference
hackhd.h File Reference
Digital video/photo recorder HackHD control.
#include "std.h"
#include "math/pprz_geodetic_float.h"
Data Structures
struct HackHD
Macros
#define hackhd_SendCmd(cmd) hackhd_command(cmd)
Enumerations
enum hackhd_status {
HACKHD_NONE , HACKHD_POWER_ON , HACKHD_POWER_OFF , HACKHD_START_RECORD ,
HACKHD_STOP_RECORD , HACKHD_SHOOT , HACKHD_AUTOSHOOT_START
}
Functions
void hackhd_init (void)
void hackhd_periodic (void)
void hackhd_autoshoot (void)
void hackhd_autoshoot_start (void)
void hackhd_command (enum hackhd_status cmd)
Variables
struct HackHD hackhd
send report
Detailed Description
Digital video/photo recorder HackHD control.
Provides the control of the HackHD power, start and stop of recording. If you are using firmware >= 1.1.5, it is also possible to take pictures according to the parameter in the config.txt file (on HackHD SD card). It is not possible to have both video and photo at the same time. This driver starts the HackHD in standby mode and trigger the start/stop of recording or take a picture. Minimum time between two pictures is 2 seconds.
It is mandatory to configure the control GPIO:
*   <configure name="HACKHD_GPIO" value="GPIOC,GPIO5"/>
*
Definition in file hackhd.h.
Data Structure Documentation
HackHD
struct HackHD
Definition at line 58 of file hackhd.h.
Data Fields
uint32_t autoshoot
struct EnuCoor_f last_shot_pos
uint32_t log_delay
int16_t photo_nr
enum hackhd_status status
uint32_t timer
Macro Definition Documentation
hackhd_SendCmd
#define hackhd_SendCmd (cmd) hackhd_command(cmd)
Definition at line 76 of file hackhd.h.
Enumeration Type Documentation
hackhd_status
enum hackhd_status
Enumerator
HACKHD_NONE
HACKHD_POWER_ON
HACKHD_POWER_OFF
HACKHD_START_RECORD
HACKHD_STOP_RECORD
HACKHD_SHOOT
HACKHD_AUTOSHOOT_START
Definition at line 48 of file hackhd.h.
Function Documentation
hackhd_autoshoot()
void hackhd_autoshoot (void) extern
Definition at line 220 of file hackhd.c.
References HackHD::autoshoot, foo, hackhd, HACKHD_AUTOSHOOT_DELAY, HACKHD_AUTOSHOOT_START, HACKHD_AUTOSHOOT_TIMER_OF_DELAY, hackhd_command(), HACKHD_SHOOT, HackHD::last_shot_pos, stateGetPositionEnu_f(), HackHD::status, VECT2_NORM2, FloatVect2::x, EnuCoor_f::x, and EnuCoor_f::y.
hackhd_autoshoot_start()
void hackhd_autoshoot_start (void) extern
Definition at line 246 of file hackhd.c.
References HackHD::autoshoot, hackhd, HACKHD_AUTOSHOOT_START, and HackHD::status.
hackhd_command()
void hackhd_command (enum hackhd_status cmd) extern
Definition at line 194 of file hackhd.c.
References foo, get_sys_time_msec(), hackhd, HACKHD_AUTOSHOOT_START, HACKHD_LOG_DELAY, HACKHD_POWER_DELAY, HACKHD_POWER_OFF, HACKHD_POWER_ON, HACKHD_PUSH, HACKHD_RECORD_DELAY, HACKHD_SHOOT, HACKHD_START_RECORD, HACKHD_STOP_RECORD, HACKHD_TIMER_OF_DELAY, HackHD::last_shot_pos, HackHD::log_delay, stateGetPositionEnu_f(), HackHD::status, and HackHD::timer.
Referenced by hackhd_autoshoot().
hackhd_init()
void hackhd_init (void) extern
Definition at line 145 of file hackhd.c.
References HackHD::autoshoot, foo, gpio_setup_output(), hackhd, HACKHD_NONE, HACKHD_RELEASE, HackHD::log_delay, HackHD::photo_nr, pin_of_gpio(), port_of_gpio(), HackHD::status, and HackHD::timer.
hackhd_periodic()
void hackhd_periodic (void) extern
Definition at line 165 of file hackhd.c.
References foo, get_sys_time_msec(), hackhd, HACKHD_RELEASE, HackHD::log_delay, HackHD::photo_nr, and HackHD::timer.
Variable Documentation
hackhd
struct HackHD hackhd extern
send report
Definition at line 143 of file hackhd.c.
Referenced by hackhd_autoshoot(), hackhd_autoshoot_start(), hackhd_command(), hackhd_init(), and hackhd_periodic().