Paparazzi UAS: sw/airborne/modules/loggers/high_speed_logger_spi_link.h File Reference
high_speed_logger_spi_link.h File Reference
#include "std.h"
Data Structures
struct high_speed_logger_spi_link_data
Macros
#define PACKED __attribute__((__packed__))
Functions
void high_speed_logger_spi_link_init (void)
void high_speed_logger_spi_link_periodic (void)
Data Structure Documentation
high_speed_logger_spi_link_data
struct high_speed_logger_spi_link_data
Definition at line 33 of file high_speed_logger_spi_link.h.
Data Fields
int32_t acc_x
int32_t acc_y
int32_t acc_z
int32_t extra1
int32_t extra2
int32_t extra3
int32_t gyro_p
int32_t gyro_q
int32_t gyro_r
int32_t id
int32_t mag_x
int32_t mag_y
int32_t mag_z
int32_t phi
int32_t psi
int32_t theta
Macro Definition Documentation
PACKED
#define PACKED __attribute__((__packed__))
Definition at line 31 of file high_speed_logger_spi_link.h.
Function Documentation
high_speed_logger_spi_link_init()
void high_speed_logger_spi_link_init (void) extern
Definition at line 40 of file high_speed_logger_spi_link.c.
References spi_transaction::after_cb, spi_transaction::bitorder, spi_transaction::cdiv, spi_transaction::cpha, spi_transaction::cpol, spi_transaction::dss, foo, high_speed_logger_spi_link_data, high_speed_logger_spi_link_trans_cb(), high_speed_logger_spi_link_transaction, high_speed_logger_spi_link_data::id, spi_transaction::input_buf, spi_transaction::input_length, spi_transaction::output_buf, spi_transaction::output_length, spi_transaction::select, spi_transaction::slave_idx, SPICphaEdge2, SPICpolIdleHigh, SPIDiv64, SPIDss8bit, SPIMSBFirst, and SPISelectUnselect.
high_speed_logger_spi_link_periodic()
void high_speed_logger_spi_link_periodic (void) extern
Definition at line 59 of file high_speed_logger_spi_link.c.
References ABI_BROADCAST, high_speed_logger_spi_link_data::acc_x, high_speed_logger_spi_link_data::acc_y, high_speed_logger_spi_link_data::acc_z, counter, foo, high_speed_logger_spi_link_data::gyro_p, high_speed_logger_spi_link_data::gyro_q, high_speed_logger_spi_link_data::gyro_r, high_speed_logger_spi_link_ready, high_speed_logger_spi_link_transaction, hsl_accel, hsl_gyro, hsl_mag, high_speed_logger_spi_link_data::id, imu_get_accel(), imu_get_gyro(), imu_get_mag(), high_speed_logger_spi_link_data::mag_x, high_speed_logger_spi_link_data::mag_y, high_speed_logger_spi_link_data::mag_z, Int32Rates::p, Int32Rates::q, Int32Rates::r, spi_submit(), imu_gyro_t::unscaled, imu_accel_t::unscaled, imu_mag_t::unscaled, Int32Vect3::x, Int32Vect3::y, and Int32Vect3::z.