Paparazzi UAS: sw/airborne/modules/loggers/high_speed_logger_spi_link.c File Reference
high_speed_logger_spi_link.c File Reference
#include "high_speed_logger_spi_link.h"
#include "modules/core/abi.h"
#include "modules/imu/imu.h"
#include "mcu_periph/spi.h"
Functions
static void high_speed_logger_spi_link_trans_cb (struct spi_transaction *trans)
void high_speed_logger_spi_link_init (void)
void high_speed_logger_spi_link_periodic (void)
Variables
struct high_speed_logger_spi_link_data high_speed_logger_spi_link_data
struct spi_transaction high_speed_logger_spi_link_transaction
static volatile bool high_speed_logger_spi_link_ready = true
static struct imu_gyro_t * hsl_gyro
static struct imu_accel_t * hsl_accel
static struct imu_mag_t * hsl_mag
Function Documentation
high_speed_logger_spi_link_init()
void high_speed_logger_spi_link_init (void)
Definition at line 40 of file high_speed_logger_spi_link.c.
References spi_transaction::after_cb, spi_transaction::bitorder, spi_transaction::cdiv, spi_transaction::cpha, spi_transaction::cpol, spi_transaction::dss, foo, high_speed_logger_spi_link_data, high_speed_logger_spi_link_trans_cb(), high_speed_logger_spi_link_transaction, high_speed_logger_spi_link_data::id, spi_transaction::input_buf, spi_transaction::input_length, spi_transaction::output_buf, spi_transaction::output_length, spi_transaction::select, spi_transaction::slave_idx, SPICphaEdge2, SPICpolIdleHigh, SPIDiv64, SPIDss8bit, SPIMSBFirst, and SPISelectUnselect.
high_speed_logger_spi_link_periodic()
void high_speed_logger_spi_link_periodic (void)
Definition at line 59 of file high_speed_logger_spi_link.c.
References ABI_BROADCAST, high_speed_logger_spi_link_data::acc_x, high_speed_logger_spi_link_data::acc_y, high_speed_logger_spi_link_data::acc_z, counter, foo, high_speed_logger_spi_link_data::gyro_p, high_speed_logger_spi_link_data::gyro_q, high_speed_logger_spi_link_data::gyro_r, high_speed_logger_spi_link_ready, high_speed_logger_spi_link_transaction, hsl_accel, hsl_gyro, hsl_mag, high_speed_logger_spi_link_data::id, imu_get_accel(), imu_get_gyro(), imu_get_mag(), high_speed_logger_spi_link_data::mag_x, high_speed_logger_spi_link_data::mag_y, high_speed_logger_spi_link_data::mag_z, Int32Rates::p, Int32Rates::q, Int32Rates::r, spi_submit(), imu_gyro_t::unscaled, imu_accel_t::unscaled, imu_mag_t::unscaled, Int32Vect3::x, Int32Vect3::y, and Int32Vect3::z.
high_speed_logger_spi_link_trans_cb()
static void high_speed_logger_spi_link_trans_cb (struct spi_transaction * trans) static
Definition at line 97 of file high_speed_logger_spi_link.c.
References high_speed_logger_spi_link_ready.
Referenced by high_speed_logger_spi_link_init().
Variable Documentation
high_speed_logger_spi_link_data
struct high_speed_logger_spi_link_data high_speed_logger_spi_link_data
Definition at line 30 of file high_speed_logger_spi_link.c.
Referenced by high_speed_logger_spi_link_init().
high_speed_logger_spi_link_ready
volatile bool high_speed_logger_spi_link_ready = true static
Definition at line 33 of file high_speed_logger_spi_link.c.
Referenced by high_speed_logger_spi_link_periodic(), and high_speed_logger_spi_link_trans_cb().
high_speed_logger_spi_link_transaction
struct spi_transaction high_speed_logger_spi_link_transaction
Definition at line 31 of file high_speed_logger_spi_link.c.
Referenced by high_speed_logger_spi_link_init(), and high_speed_logger_spi_link_periodic().
hsl_accel
struct imu_accel_t* hsl_accel static
Definition at line 35 of file high_speed_logger_spi_link.c.
Referenced by high_speed_logger_spi_link_periodic().
hsl_gyro
struct imu_gyro_t* hsl_gyro static
Definition at line 34 of file high_speed_logger_spi_link.c.
Referenced by high_speed_logger_spi_link_periodic().
hsl_mag
struct imu_mag_t* hsl_mag static
Definition at line 36 of file high_speed_logger_spi_link.c.
Referenced by high_speed_logger_spi_link_periodic().