Paparazzi UAS: sw/airborne/modules/hott/hott_gam.h File Reference
hott_gam.h File Reference
#include "autopilot.h"
Data Structures
struct HOTT_GAM_MSG
Macros
#define HOTT_TELEMETRY_GAM_SENSOR_ID 0x8D
Functions
static void hott_init_gam_msg (struct HOTT_GAM_MSG *hott_gam_msg)
static void hott_update_gam_msg (struct HOTT_GAM_MSG *hott_gam_msg)
Data Structure Documentation
struct HOTT_GAM_MSG
Definition at line 35 of file hott_gam.h.
Data Fields
int8_t alarm_invers1
int8_t alarm_invers2
int8_t altitude_H
int8_t altitude_L
int8_t batt1_H
int8_t batt1_L
int8_t batt2_H
int8_t batt2_L
int8_t batt_cap_H
int8_t batt_cap_L
int8_t cell1
int8_t cell2
int8_t cell3
int8_t cell4
int8_t cell5
int8_t cell6
int8_t climbrate3s
int8_t climbrate_H
int8_t climbrate_L
int8_t current_H
int8_t current_L
int8_t fuel_ml_H
int8_t fuel_ml_L
int8_t fuel_procent
int8_t gam_sensor_id
int8_t general_error_number
int8_t main_voltage_H
int8_t main_voltage_L
int8_t min_cell_volt
int8_t min_cell_volt_num
int8_t pressure
int8_t rpm2_H
int8_t rpm2_L
int8_t rpm_H
int8_t rpm_L
int8_t sensor_id
int8_t speed_H
int8_t speed_L
int8_t start_byte
int8_t stop_byte
int8_t temperature1
int8_t temperature2
int8_t version
int8_t warning_beeps
Macro Definition Documentation
#define HOTT_TELEMETRY_GAM_SENSOR_ID 0x8D
Definition at line 33 of file hott_gam.h.
Referenced by hott_check_serial_data(), hott_init_gam_msg(), and hott_periodic().
Function Documentation
static void hott_init_gam_msg (struct HOTT_GAM_MSG * hott_gam_msg) static
Definition at line 125 of file hott_gam.h.
References HOTT_GAM_MSG::gam_sensor_id, HOTT_TELEMETRY_GAM_SENSOR_ID, HOTT_GAM_MSG::sensor_id, HOTT_GAM_MSG::start_byte, and HOTT_GAM_MSG::stop_byte.
Referenced by hott_msgs_init().
static void hott_update_gam_msg (struct HOTT_GAM_MSG * hott_gam_msg) static
Definition at line 134 of file hott_gam.h.
References HOTT_GAM_MSG::alarm_invers2, HOTT_GAM_MSG::altitude_L, autopilot_get_motors_on(), HOTT_GAM_MSG::batt_cap_L, HOTT_GAM_MSG::climbrate3s, HOTT_GAM_MSG::climbrate_L, HOTT_GAM_MSG::current_L, HOTT_GAM_MSG::fuel_procent, HOTT_GAM_MSG::main_voltage_L, HOTT_GAM_MSG::speed_L, HOTT_GAM_MSG::temperature1, and HOTT_GAM_MSG::temperature2.
Referenced by hott_periodic().