Paparazzi UAS: sw/airborne/modules/hott/hott.c File Reference
hott.c File Reference
Graupner HOTT telemetry control module.
#include "hott/hott.h"
#include "mcu_periph/sys_time.h"
#include "mcu_periph/uart.h"
Macros
#define HOTT_TEXT_MODE_REQUEST_ID 0x7f
#define HOTT_BINARY_MODE_REQUEST_ID 0x80
#define HOTT_TELEMETRY_GPS_SENSOR_ID 0x8A
#define HOTT_TELEMETRY_VARIO_SENSOR_ID 0x89
Functions
static void hott_msgs_init (void)
Initializes a HoTT GPS message (Receiver answer type !Not Smartbox)
static void hott_enable_transmitter (void)
static void hott_enable_receiver (void)
void hott_init (void)
RC init function.
void hott_periodic (void)
static void hott_send_msg (int8_t *buffer, int16_t len)
static void hott_send_telemetry_data (void)
static void hott_check_serial_data (uint32_t tnow)
static void hott_periodic_event (uint32_t tnow)
void hott_event (void)
RC event function.
Variables
static uint32_t hott_event_timer
static bool hott_telemetry_is_sending = false
static uint16_t hott_telemetry_sendig_msgs_id = 0
static int8_t * hott_msg_ptr = 0
static int16_t hott_msg_len = 0
Detailed Description
Graupner HOTT telemetry control module.
Definition in file hott.c.
Macro Definition Documentation
HOTT_BINARY_MODE_REQUEST_ID
#define HOTT_BINARY_MODE_REQUEST_ID 0x80
Definition at line 45 of file hott.c.
HOTT_TELEMETRY_GPS_SENSOR_ID
#define HOTT_TELEMETRY_GPS_SENSOR_ID 0x8A
Definition at line 49 of file hott.c.
HOTT_TELEMETRY_VARIO_SENSOR_ID
#define HOTT_TELEMETRY_VARIO_SENSOR_ID 0x89
Definition at line 51 of file hott.c.
HOTT_TEXT_MODE_REQUEST_ID
#define HOTT_TEXT_MODE_REQUEST_ID 0x7f
Definition at line 44 of file hott.c.
Function Documentation
hott_check_serial_data()
static void hott_check_serial_data (uint32_t tnow) static
Definition at line 197 of file hott.c.
References autopilot_get_motors_on(), foo, HOTT_BINARY_MODE_REQUEST_ID, hott_send_msg(), HOTT_TELEMETRY_EAM_SENSOR_ID, HOTT_TELEMETRY_GAM_SENSOR_ID, HOTT_TELEMETRY_GPS_SENSOR_ID, hott_telemetry_is_sending, HOTT_TELEMETRY_VARIO_SENSOR_ID, HOTT_TEXT_MODE_REQUEST_ID, TRUE, uart_char_available(), and uart_getch().
Referenced by hott_periodic_event().
hott_enable_receiver()
static void hott_enable_receiver (void) static
Definition at line 117 of file hott.c.
References FALSE, foo, TRUE, and uart_periph_set_mode().
Referenced by hott_send_telemetry_data().
hott_enable_transmitter()
static void hott_enable_transmitter (void) static
Definition at line 111 of file hott.c.
References FALSE, foo, TRUE, and uart_periph_set_mode().
Referenced by hott_send_telemetry_data().
hott_event()
void hott_event (void)
RC event function.
Definition at line 291 of file hott.c.
References hott_event_timer, hott_periodic_event(), SysTimeTimer, and SysTimeTimerStart.
hott_init()
void hott_init (void)
RC init function.
Definition at line 123 of file hott.c.
References hott_msgs_init().
hott_msgs_init()
static void hott_msgs_init (void) static
Initializes a HoTT GPS message (Receiver answer type !Not Smartbox)
Definition at line 91 of file hott.c.
References foo, hott_init_eam_msg(), and hott_init_gam_msg().
Referenced by hott_init().
hott_periodic()
void hott_periodic (void)
Definition at line 129 of file hott.c.
References foo, HOTT_TELEMETRY_EAM_SENSOR_ID, HOTT_TELEMETRY_GAM_SENSOR_ID, HOTT_TELEMETRY_GPS_SENSOR_ID, hott_telemetry_sendig_msgs_id, HOTT_TELEMETRY_VARIO_SENSOR_ID, hott_update_eam_msg(), hott_update_gam_msg(), and TRUE.
hott_periodic_event()
static void hott_periodic_event (uint32_t tnow) static
Definition at line 274 of file hott.c.
References foo, get_sys_time_usec(), hott_check_serial_data(), hott_msg_ptr, hott_send_telemetry_data(), and hott_telemetry_is_sending.
Referenced by hott_event().
hott_send_msg()
static void hott_send_msg (int8_t * buffer, int16_t len) static
Definition at line 161 of file hott.c.
References hott_msg_len, hott_msg_ptr, hott_telemetry_is_sending, hott_telemetry_sendig_msgs_id, and TRUE.
Referenced by hott_check_serial_data().
hott_send_telemetry_data()
static void hott_send_telemetry_data (void) static
Definition at line 169 of file hott.c.
References foo, hott_enable_receiver(), hott_enable_transmitter(), hott_msg_len, hott_msg_ptr, hott_telemetry_is_sending, hott_telemetry_sendig_msgs_id, uart_char_available(), uart_getch(), and uart_put_byte().
Referenced by hott_periodic_event().
Variable Documentation
hott_event_timer
uint32_t hott_event_timer static
Definition at line 53 of file hott.c.
Referenced by hott_event().
hott_msg_len
int16_t hott_msg_len = 0 static
Definition at line 73 of file hott.c.
Referenced by hott_send_msg(), and hott_send_telemetry_data().
hott_msg_ptr
int8_t* hott_msg_ptr = 0 static
Definition at line 71 of file hott.c.
Referenced by hott_periodic_event(), hott_send_msg(), and hott_send_telemetry_data().
hott_telemetry_is_sending
bool hott_telemetry_is_sending = false static
Definition at line 54 of file hott.c.
Referenced by hott_check_serial_data(), hott_periodic_event(), hott_send_msg(), and hott_send_telemetry_data().
hott_telemetry_sendig_msgs_id
uint16_t hott_telemetry_sendig_msgs_id = 0 static
Definition at line 55 of file hott.c.
Referenced by hott_periodic(), hott_send_msg(), and hott_send_telemetry_data().