Paparazzi UAS: sw/airborne/modules/meteo/humid_sht.h File Reference
humid_sht.h File Reference
SHTxx sensor interface.
#include "std.h"
Functions
void humid_sht_init (void)
void humid_sht_periodic (void)
Variables
uint16_t humidsht
uint16_t tempsht
float fhumidsht
float ftempsht
bool humid_sht_available
uint8_t humid_sht_status
Detailed Description
SHTxx sensor interface.
This reads the values for humidity and temperature from the SHTxx sensor through bit banging.
Definition in file humid_sht.h.
Function Documentation
humid_sht_init()
void humid_sht_init (void)
Definition at line 299 of file humid_sht.c.
References foo, gpio_clear(), gpio_setup_input(), gpio_setup_output(), humid_sht_available, humid_sht_status, and SHT_IDLE.
humid_sht_periodic()
void humid_sht_periodic (void)
Definition at line 316 of file humid_sht.c.
References calc_sht(), checksum, GpsState::course, DefaultChannel, DefaultDevice, fhumidsht, GpsState::fix, foo, ftempsht, gps, GpsState::gspeed, GpsState::hmsl, HUMI, humid_sht_available, humid_sht_status, humidsht, LlaCoor_i::lat, GpsState::lla_pos, LlaCoor_i::lon, GpsState::ned_vel, pprzLogFile, s_connectionreset(), s_read_measure(), s_start_measure(), SHT_IDLE, SHT_MEASURING_HUMID, SHT_MEASURING_TEMP, TEMP, tempsht, GpsState::tow, GpsState::week, and NedCoor_i::z.
Variable Documentation
fhumidsht
float fhumidsht extern
Definition at line 87 of file humid_sht.c.
ftempsht
float ftempsht
Definition at line 36 of file humid_sht.h.
humid_sht_available
bool humid_sht_available extern
Definition at line 88 of file humid_sht.c.
humid_sht_status
uint8_t humid_sht_status extern
Definition at line 89 of file humid_sht.c.
humidsht
uint16_t humidsht extern
Definition at line 86 of file humid_sht.c.
tempsht
uint16_t tempsht
Definition at line 35 of file humid_sht.h.