Paparazzi UAS: sw/airborne/modules/meteo/humid_sht_uart.c File Reference
humid_sht_uart.c File Reference
SHTxx sensor interface.
#include "std.h"
#include "mcu_periph/gpio.h"
#include "mcu_periph/uart.h"
#include "pprzlink/messages.h"
#include "modules/datalink/downlink.h"
#include "humid_sht_uart.h"
Functions
void calc_sht (uint16_t hum, uint16_t tem, float *fhum, float *ftem)
void humid_sht_uart_parse (uint8_t c)
void humid_sht_uart_periodic (void)
void humid_sht_uart_init (void)
void humid_sht_uart_event (void)
Variables
uint16_t humidsht
!SITL
uint16_t tempsht
float fhumidsht
float ftempsht
bool humid_sht_available
Detailed Description
SHTxx sensor interface.
This reads the values for humidity and temperature from the SHTxx sensor through an uart.
Definition in file humid_sht_uart.c.
Function Documentation
calc_sht()
void calc_sht (uint16_t hum, uint16_t tem, float * fhum, float * ftem)
Definition at line 45 of file humid_sht_uart.c.
References C1, C2, and foo.
Referenced by humid_sht_uart_parse().
humid_sht_uart_event()
void humid_sht_uart_event (void)
Definition at line 109 of file humid_sht_uart.c.
References foo, humid_sht_uart_parse(), MetBuffer, and MetGetch.
humid_sht_uart_init()
void humid_sht_uart_init (void)
Definition at line 105 of file humid_sht_uart.c.
humid_sht_uart_parse()
void humid_sht_uart_parse (uint8_t c)
Definition at line 81 of file humid_sht_uart.c.
References calc_sht(), DefaultChannel, DefaultDevice, fhumidsht, foo, ftempsht, humidsht, and tempsht.
Referenced by humid_sht_uart_event().
humid_sht_uart_periodic()
void humid_sht_uart_periodic (void)
Definition at line 76 of file humid_sht_uart.c.
Variable Documentation
fhumidsht
float fhumidsht
Definition at line 39 of file humid_sht_uart.c.
Referenced by humid_sht_uart_parse().
ftempsht
float ftempsht
Definition at line 39 of file humid_sht_uart.c.
Referenced by humid_sht_uart_parse().
humid_sht_available
bool humid_sht_available
Definition at line 40 of file humid_sht_uart.c.
humidsht
uint16_t humidsht
!SITL
Definition at line 38 of file humid_sht_uart.c.
Referenced by humid_sht_uart_parse().
tempsht
uint16_t tempsht
Definition at line 38 of file humid_sht_uart.c.
Referenced by humid_sht_uart_parse().