Paparazzi UAS: sw/airborne/arch/chibios/modules/sensors/hx711.h File Reference
hx711.h File Reference
Interface for the HX711 sensor.
#include "std.h"
Functions
void hx711_init (void)
void hx711_event (void)
Start a measurement and publish the results when possible.
Detailed Description
Interface for the HX711 sensor.
Definition in file hx711.h.
Function Documentation
hx711_event()
void hx711_event (void)
Start a measurement and publish the results when possible.
Definition at line 135 of file hx711.c.
References hx711_t::busy, hx711_dev_t::data_pin, hx711_dev_t::data_port, DefaultChannel, DefaultDevice, hx711_t::devices, foo, get_sys_time_float(), get_sys_time_usec(), gpio_get(), hx711, HX711_DEVICES_NB, HX711_FORCE_SENSOR_ID, hx711_meas_time, HX711_PERIOD, hx711_dev_t::measurement, hx711_t::measurement_ready, pprzlog_tp, and hx711_t::read_bit_idx.
hx711_init()
void hx711_init (void)
Definition at line 110 of file hx711.c.
References hx711_t::busy, hx711_dev_t::data_pin, hx711_dev_t::data_port, hx711_t::devices, foo, gpio_setup_input(), gpio_setup_pin_af(), hx711, HX711_DEVICES_NB, hx711_t::measurement_ready, pwmcfg, pwmpcb(), and hx711_t::read_bit_idx.