Paparazzi UAS: sw/airborne/modules/benchmark/i2c_abuse_test.h File Reference
i2c_abuse_test.h File Reference
Total I2C Abuse:
Macros
#define I2C_ABUSE_SHORT_SCL_LED 2
#define I2C_ABUSE_SHORT_SDA_LED 3
Functions
void init_i2c_abuse_test (void)
void event_i2c_abuse_test (void)
void periodic_50Hz_i2c_abuse_test (void)
Detailed Description
Total I2C Abuse:
-all transaction types: T1 T2 T3 T4 R1 R2 R3 R4 T1R1 T2R1 T1R2 T1R3 T1R4 T1R5 T2R5 -all bitrates: 1k (way too slow) to 1M (way to fast) -occasional Short circuit (simulate bus capacitance or EMI errors) -variable bus load: from empty to full stack
-Connect LED to MosFet that pulls-down the SCL and SDA lines
Definition in file i2c_abuse_test.h.
Macro Definition Documentation
I2C_ABUSE_SHORT_SCL_LED
#define I2C_ABUSE_SHORT_SCL_LED 2
Definition at line 39 of file i2c_abuse_test.h.
I2C_ABUSE_SHORT_SDA_LED
#define I2C_ABUSE_SHORT_SDA_LED 3
Definition at line 43 of file i2c_abuse_test.h.
Function Documentation
event_i2c_abuse_test()
void event_i2c_abuse_test (void)
Definition at line 180 of file i2c_abuse_test.c.
References foo, i2c_abuse_send_transaction(), i2c_abuse_test_bitrate, i2c_abuse_test_counter, i2c_idle(), i2c_setbitrate(), i2c_submit(), i2c_test1, i2c_test2, I2CTransFailed, I2CTransRx, I2CTransSuccess, LED_OFF, LED_ON, LED_TOGGLE, i2c_transaction::len_r, i2c_transaction::slave_addr, i2c_transaction::status, and i2c_transaction::type.
init_i2c_abuse_test()
void init_i2c_abuse_test (void)
Definition at line 45 of file i2c_abuse_test.c.
References i2c_abuse_test_bitrate, i2c_abuse_test_counter, i2c_test1, i2c_test2, I2CTransSuccess, i2c_transaction::slave_addr, and i2c_transaction::status.
periodic_50Hz_i2c_abuse_test()
void periodic_50Hz_i2c_abuse_test (void)
Definition at line 226 of file i2c_abuse_test.c.