Paparazzi UAS: sw/airborne/modules/computer_vision/lib/vision/image.h File Reference
image.h File Reference
Image helper functions like resizing, color filter, converters...
#include "std.h"
#include <sys/time.h>
#include <state.h>
Data Structures
struct image_t
struct point_t
struct point3d_t
struct flow_t
struct img_size_t
struct crop_t
Enumerations
enum image_type {
IMAGE_YUV422 , IMAGE_GRAYSCALE , IMAGE_JPEG , IMAGE_GRADIENT ,
IMAGE_INT16
}
Functions
void image_add_border (struct image_t *input, struct image_t *output, uint8_t border_size)
This function adds padding to input image by mirroring the edge image elements.
void image_create (struct image_t *img, uint16_t width, uint16_t height, enum image_type type)
Create a new image.
void image_free (struct image_t *img)
Free the image.
void image_copy (struct image_t *input, struct image_t *output)
Copy an image from inut to output This will only work if the formats are the same.
void image_switch (struct image_t *a, struct image_t *b)
This will switch image *a and *b This is faster as image_copy because it doesn't copy the whole image buffer.
void image_to_grayscale (struct image_t *input, struct image_t *output)
Convert an image to grayscale.
uint16_t image_yuv422_colorfilt (struct image_t *input, struct image_t *output, uint8_t y_m, uint8_t y_M, uint8_t u_m, uint8_t u_M, uint8_t v_m, uint8_t v_M)
Filter colors in an YUV422 image.
int check_color_yuv422 (struct image_t *im, int x, int y, uint8_t y_m, uint8_t y_M, uint8_t u_m, uint8_t u_M, uint8_t v_m, uint8_t v_M)
Checks the color of a single pixel in a YUV422 image.
void set_color_yuv422 (struct image_t *im, int x, int y, uint8_t Y, uint8_t U, uint8_t V)
Sets Y,U,V for a single pixel.
void image_yuv422_downsample (struct image_t *input, struct image_t *output, uint8_t downsample)
Simplified high-speed low CPU downsample function without averaging downsample factor must be 1, 2, 4, 8 ... 2^X image of type UYVY expected.
void image_subpixel_window (struct image_t *input, struct image_t *output, struct point_t *center, uint32_t subpixel_factor, uint8_t border_size)
This outputs a subpixel window image in grayscale Currently only works with Grayscale images as input but could be upgraded to also support YUV422 images.
void image_gradients (struct image_t *input, struct image_t *dx, struct image_t *dy)
Calculate the gradients using the following matrix: [0 -1 0; -1 0 1; 0 1 0].
void image_calculate_g (struct image_t *dx, struct image_t *dy, int32_t *g)
Calculate the G vector of an image gradient This is used for optical flow calculation.
uint32_t image_difference (struct image_t *img_a, struct image_t *img_b, struct image_t *diff)
Calculate the difference between two images and return the error This will only work with grayscale images.
int32_t image_multiply (struct image_t *img_a, struct image_t *img_b, struct image_t *mult)
Calculate the multiplication between two images and return the error This will only work with image gradients.
void image_show_points (struct image_t *img, struct point_t *points, uint16_t points_cnt)
Show points in an image by coloring them through giving the pixels the maximum value.
void image_show_points_color (struct image_t *img, struct point_t *points, uint16_t points_cnt, uint8_t *color)
Show points in an image by coloring them through giving the pixels the maximum value.
void image_show_flow_color (struct image_t *img, struct flow_t *vectors, uint16_t points_cnt, uint8_t subpixel_factor, const uint8_t *color, const uint8_t *bad_color)
Shows the flow from a specific point to a new point This works on YUV422 and Grayscale images.
void image_show_flow (struct image_t *img, struct flow_t *vectors, uint16_t points_cnt, uint8_t subpixel_factor)
void image_draw_crosshair (struct image_t *img, struct point_t *loc, const uint8_t *color, uint32_t size_crosshair)
Draw a cross-hair on the image.
void image_draw_rectangle (struct image_t *img, int x_min, int x_max, int y_min, int y_max, uint8_t *color)
Draw a rectangle on the image.
void image_draw_line (struct image_t *img, struct point_t *from, struct point_t *to)
Draw a pink line on the image.
void image_draw_line_color (struct image_t *img, struct point_t *from, struct point_t *to, const uint8_t *color)
Draw a line on the image.
void pyramid_next_level (struct image_t *input, struct image_t *output, uint8_t border_size)
This function takes previous padded pyramid level and outputs next level of pyramid without padding.
void pyramid_build (struct image_t *input, struct image_t *output_array, uint8_t pyr_level, uint16_t border_size)
This function populates given array of image_t structs with wanted number of padded pyramids based on given input.
void image_gradient_pixel (struct image_t *img, struct point_t *loc, int method, int *dx, int *dy)
Get the gradient at a pixel location.
uint8_t ker_mul_3x3 (uint8_t const *source, int_fast8_t const *kernel, uint8_t total, uint8_t setting, int width, int YUV)
Kernel multiplication for a 3 x 3 kernel.
void image_convolution_3x3 (struct image_t *input, struct image_t *output, int_fast8_t const *kernel, uint8_t kernel_total)
Image convolution for a 3x3 kernel.
Detailed Description
Image helper functions like resizing, color filter, converters...
Definition in file image.h.
Data Structure Documentation
image_t
struct image_t
Definition at line 44 of file image.h.
Data Fields
void * buf Image buffer (depending on the image_type)
uint8_t buf_idx Buffer index for V4L2 freeing.
uint32_t buf_size The buffer size.
struct FloatEulers eulers Euler Angles at time of image.
uint16_t h Image height.
uint32_t pprz_ts The timestamp in us since system startup.
struct timeval ts The timestamp of creation.
enum image_type type The image type.
uint16_t w Image width.
point_t
struct point_t
Definition at line 58 of file image.h.
Data Fields
uint16_t count Number of times the point has been tracked successfully.
uint32_t x The x coordinate of the point.
uint16_t x_sub The x subpixel coordinate of the point.
uint32_t y The y coordinate of the point.
uint16_t y_sub The y subpixel coordinate of the point.
point3d_t
struct point3d_t
Definition at line 68 of file image.h.
Data Fields
float X The x coordinate of the point.
float Y The y coordinate of the point.
float Z The y coordinate of the point.
flow_t
struct flow_t
Definition at line 78 of file image.h.
Data Fields
uint32_t error The matching error in the tracking process in subpixels.
int32_t flow_x The x direction flow in subpixels.
int32_t flow_y The y direction flow in subpixels.
struct point_t pos The original position the flow comes from in subpixels.
img_size_t
struct img_size_t
Definition at line 86 of file image.h.
Data Fields
uint16_t h The height.
uint16_t w The width.
crop_t
struct crop_t
Definition at line 92 of file image.h.
Data Fields
uint16_t h height of the cropped area
uint16_t w Width of the cropped area.
uint16_t x Start position x (horizontal)
uint16_t y Start position y (vertical)
Enumeration Type Documentation
image_type
enum image_type
Enumerator
IMAGE_YUV422
UYVY format (uint16 per pixel)
IMAGE_GRAYSCALE
Grayscale image with only the Y part (uint8 per pixel)
IMAGE_JPEG
An JPEG encoded image (not per pixel encoded)
IMAGE_GRADIENT
An image gradient (int16 per pixel)
IMAGE_INT16
An image to hold disparity image data from openCV (int16 per pixel)
Definition at line 35 of file image.h.
Function Documentation
check_color_yuv422()
int check_color_yuv422 (struct image_t * im, int x, int y, uint8_t y_m, uint8_t y_M, uint8_t u_m, uint8_t u_M, uint8_t v_m, uint8_t v_M)
Checks the color of a single pixel in a YUV422 image.
1 means that it passes the filter, 0 that it does not.
Parameters
[in] im The input image to filter
[in] x The x-coordinate of the pixel
[in] y The y-coordinate of the pixel
[in] y_m The Y minimum value
[in] y_M The Y maximum value
[in] u_m The U minimum value
[in] u_M The U maximum value
[in] v_m The V minimum value
[in] v_M The V maximum value
Returns
The success of the filter.
Definition at line 237 of file image.c.
References image_t::buf, foo, image_t::h, and image_t::w.
Referenced by check_color_snake_gate_detection().
image_add_border()
void image_add_border (struct image_t * input, struct image_t * output, uint8_t border_size)
This function adds padding to input image by mirroring the edge image elements.
Parameters
[in] *input - input image (grayscale only)
[out] *output - the output image
[in] border_size - amount of padding around image. Padding is made by reflecting image elements at the edge Example: f e d c b a | a b c d e f | f e d c b a
Definition at line 368 of file image.c.
References image_t::buf, foo, image_t::h, image_create(), image_t::type, and image_t::w.
Referenced by pyramid_build().
image_calculate_g()
void image_calculate_g (struct image_t * dx, struct image_t * dy, int32_t * g)
Calculate the G vector of an image gradient This is used for optical flow calculation.
Parameters
[in] *dx The gradient in the X direction
[in] *dy The gradient in the Y direction
[out] *g The G[4] vector devided by 255 to keep in range
Definition at line 573 of file image.c.
References image_t::buf, foo, g, image_t::h, and image_t::w.
Referenced by opticFlowLK(), and opticFlowLK_flat().
image_convolution_3x3()
void image_convolution_3x3 (struct image_t * input, struct image_t * output, int_fast8_t const * kernel, uint8_t kernel_total)
Image convolution for a 3x3 kernel.
Parameters
[in] input Input image
[in,out] output Output image
[in] kernel The kernel values
Definition at line 1068 of file image.c.
References image_t::buf, dest, image_t::eulers, foo, IMAGE_GRAYSCALE, IMAGE_YUV422, ker_mul_3x3(), image_t::pprz_ts, image_t::ts, point_t::x, and point_t::y.
image_copy()
void image_copy (struct image_t * input, struct image_t * output)
Copy an image from inut to output This will only work if the formats are the same.
Parameters
[in] *input The input image to copy from
[out] *output The out image to copy to
Definition at line 89 of file image.c.
References image_t::buf, image_t::buf_size, image_t::eulers, foo, image_t::h, image_t::pprz_ts, image_t::ts, image_t::type, and image_t::w.
Referenced by calc_fast9_lukas_kanade(), copy_left_img_func(), copy_right_img_func(), cv_async_function(), and undistort_image_func().
image_create()
void image_create (struct image_t * img, uint16_t width, uint16_t height, enum image_type type)
Create a new image.
Parameters
[out] *img The output image
[in] width The width of the image
[in] height The height of the image
[in] type The type of image (YUV422 or grayscale)
Definition at line 43 of file image.c.
References CACHE_LINE_LENGTH, foo, IMAGE_GRADIENT, IMAGE_INT16, IMAGE_JPEG, and IMAGE_YUV422.
Referenced by calc_fast9_lukas_kanade(), cv_async_function(), cv_blob_locator_func(), cv_window_func(), detect_window(), image_add_border(), log_image(), opticFlowLK(), opticFlowLK_flat(), pano_unwrap_init(), pyramid_next_level(), qrscan(), set_output_image_size(), undistort_image_func(), video_capture_save(), video_thread_function(), viewvideo_function(), and wedgebug_init().
image_difference()
uint32_t image_difference (struct image_t * img_a, struct image_t * img_b, struct image_t * diff)
Calculate the difference between two images and return the error This will only work with grayscale images.
Parameters
[in] *img_a The image to substract from
[in] *img_b The image to substract from img_a
[out] *diff The image difference (if not needed can be NULL)
Returns
The squared difference summed
Definition at line 605 of file image.c.
References foo.
Referenced by opticFlowLK(), and opticFlowLK_flat().
image_draw_crosshair()
void image_draw_crosshair (struct image_t * img, struct point_t * loc, const uint8_t * color, uint32_t size_crosshair)
Draw a cross-hair on the image.
Parameters
[in,out] *img The image to show the line on
[in] loc The location of the cross-hair
[in] color The line color as a [U, Y1, V, Y2] uint8_t array, or a uint8_t value pointer for grayscale images. Example colors: white = {127, 255, 127, 255}, green = {0, 127, 0, 127};
[in] size_crosshair Actually the half size of the cross hair
Definition at line 891 of file image.c.
References foo, image_draw_line_color(), point_t::x, and point_t::y.
Referenced by draw_gate_color_polygon(), draw_gate_color_square(), image_show_flow_color(), image_show_points_color(), and snake_gate_detection().
image_draw_line()
void image_draw_line (struct image_t * img, struct point_t * from, struct point_t * to)
Draw a pink line on the image.
Parameters
[in,out] *img The image to show the line on
[in] *from The point to draw from
[in] *to The point to draw to
Definition at line 917 of file image.c.
References foo, and image_draw_line_color().
Referenced by draw_edgeflow_img(), and qrscan().
image_draw_line_color()
void image_draw_line_color (struct image_t * img, struct point_t * from, struct point_t * to, const uint8_t * color)
Draw a line on the image.
Parameters
[in,out] *img The image to show the line on
[in] *from The point to draw from
[in] *to The point to draw to
[in] *color The line color as a [U, Y1, V, Y2] uint8_t array, or a uint8_t value pointer for grayscale images. Example colors: white = {127, 255, 127, 255}, green = {0, 127, 0, 127};
Definition at line 932 of file image.c.
References foo, IMAGE_YUV422, point_t::x, and point_t::y.
Referenced by draw_gate_color_polygon(), draw_gate_color_square(), image_draw_crosshair(), image_draw_line(), image_draw_rectangle(), and image_show_flow_color().
image_draw_rectangle()
void image_draw_rectangle (struct image_t * img, int x_min, int x_max, int y_min, int y_max, uint8_t * color)
Draw a rectangle on the image.
Parameters
[in,out] *img The image to show the line on
[in] x_min start in x
[in] x_max end of x
[in] y_min start in y
[in] y_max end of y
[in] color in [U, Y, V, Y] format
Definition at line 849 of file image.c.
References foo, image_draw_line_color(), point_t::x, and point_t::y.
image_free()
void image_free (struct image_t * img)
Free the image.
Parameters
[in] *img The image to free
Definition at line 75 of file image.c.
References foo.
Referenced by cv_async_function(), cv_blob_locator_func(), cv_window_func(), detect_window(), opticFlowLK(), opticFlowLK_flat(), pyramid_build(), set_output_image_size(), undistort_image_func(), video_capture_save(), video_thread_function(), and viewvideo_function().
image_gradient_pixel()
void image_gradient_pixel (struct image_t * img, struct point_t * loc, int method, int * dx, int * dy)
Get the gradient at a pixel location.
Parameters
[in,out] *img The image
[in] loc The location at which to get the gradient
[in] method 0 = {-1, 0, 1}, 1 = Sobel {-1, 0, 1; -2, 0, 2; -1, 0, 1}
[in] dx The gradient in x-direction
[in] dy The gradient in y-direction
Definition at line 777 of file image.c.
References foo, IMAGE_YUV422, point_t::x, and point_t::y.
Referenced by act_fast().
image_gradients()
void image_gradients (struct image_t * input, struct image_t * dx, struct image_t * dy)
Calculate the gradients using the following matrix: [0 -1 0; -1 0 1; 0 1 0].
Parameters
[in] *input Input grayscale image
[out] *dx Output gradient in the X direction (dx->w = input->w-2, dx->h = input->h-2)
[out] *dy Output gradient in the Y direction (dx->w = input->w-2, dx->h = input->h-2)
Definition at line 549 of file image.c.
References image_t::buf, foo, image_t::h, and image_t::w.
Referenced by opticFlowLK(), and opticFlowLK_flat().
image_multiply()
int32_t image_multiply (struct image_t * img_a, struct image_t * img_b, struct image_t * mult)
Calculate the multiplication between two images and return the error This will only work with image gradients.
Parameters
[in] *img_a The image to multiply
[in] *img_b The image to multiply with
[out] *mult The image multiplication (if not needed can be NULL)
Returns
The sum of the multiplcation
Definition at line 643 of file image.c.
References foo.
Referenced by opticFlowLK(), and opticFlowLK_flat().
image_show_flow()
void image_show_flow (struct image_t * img, struct flow_t * vectors, uint16_t points_cnt, uint8_t subpixel_factor)
Definition at line 726 of file image.c.
References foo, and image_show_flow_color().
image_show_flow_color()
void image_show_flow_color (struct image_t * img, struct flow_t * vectors, uint16_t points_cnt, uint8_t subpixel_factor, const uint8_t * color, const uint8_t * bad_color)
Shows the flow from a specific point to a new point This works on YUV422 and Grayscale images.
Parameters
[in,out] *img The image to show the flow on
[in] *vectors The flow vectors to show
[in] *points_cnt The amount of points and vectors to show
[in] subpixel_factor
[in] color color for good vectors
[in] bad_color color for bad vectors
Definition at line 743 of file image.c.
References foo, image_draw_crosshair(), image_draw_line_color(), LARGE_FLOW_ERROR, point_t::x, and point_t::y.
Referenced by calc_fast9_lukas_kanade(), and image_show_flow().
image_show_points()
void image_show_points (struct image_t * img, struct point_t * points, uint16_t points_cnt)
Show points in an image by coloring them through giving the pixels the maximum value.
This works with YUV422 and grayscale images
Parameters
[in,out] *img The image to place the points on
[in] *points The points to sohw
[in] *points_cnt The amount of points to show
Definition at line 679 of file image.c.
References foo, and image_show_points_color().
Referenced by calc_fast9_lukas_kanade().
image_show_points_color()
void image_show_points_color (struct image_t * img, struct point_t * points, uint16_t points_cnt, uint8_t * color)
Show points in an image by coloring them through giving the pixels the maximum value.
This works with YUV422 and grayscale images
Parameters
[in,out] *img The image to place the points on
[in] *points The points to show
[in] *points_cnt The amount of points to show
[in] *color The color of the points as a [U, Y1, V, Y2] uint8_t array, or a uint8_t value pointer for grayscale images. Example colors: white = {127, 255, 127, 255}, green = {0, 127, 0, 127};
Definition at line 701 of file image.c.
References foo, idx, image_draw_crosshair(), IMAGE_YUV422, point_t::x, and point_t::y.
Referenced by image_show_points().
image_subpixel_window()
void image_subpixel_window (struct image_t * input, struct image_t * output, struct point_t * center, uint32_t subpixel_factor, uint8_t border_size)
This outputs a subpixel window image in grayscale Currently only works with Grayscale images as input but could be upgraded to also support YUV422 images.
You can and should only ask a subpixel window of a center point that is w/2 pixels away from the edges
Parameters
[in] *input Input image (grayscale only)
[out] *output Window output (width and height is used to calculate the window size)
[in] *center Center point in subpixel coordinates
[in] subpixel_factor The subpixel factor per pixel
[in] border_size - amount of padding around image. Padding is made by reflecting image elements at the edge Example: f e d c b a | a b c d e f | f e d c b a
Definition at line 491 of file image.c.
References image_t::buf, foo, image_t::h, image_t::w, point_t::x, and point_t::y.
Referenced by opticFlowLK(), and opticFlowLK_flat().
image_switch()
void image_switch (struct image_t * a, struct image_t * b)
This will switch image *a and *b This is faster as image_copy because it doesn't copy the whole image buffer.
Parameters
[in,out] *a The image to switch
[in,out] *b The image to switch with
Definition at line 112 of file image.c.
References b, and foo.
Referenced by calc_fast9_lukas_kanade().
image_to_grayscale()
void image_to_grayscale (struct image_t * input, struct image_t * output)
Convert an image to grayscale.
Depending on the output type the U/V bytes are removed
Parameters
[in] *input The input image (Needs to be YUV422)
[out] *output The output image
Definition at line 131 of file image.c.
References image_t::buf, dest, image_t::eulers, foo, IMAGE_YUV422, image_t::pprz_ts, and image_t::ts.
Referenced by background_processes(), background_processes_16bit(), calc_fast9_lukas_kanade(), cv_window_func(), and detect_window().
image_yuv422_colorfilt()
uint16_t image_yuv422_colorfilt (struct image_t * input, struct image_t * output, uint8_t y_m, uint8_t y_M, uint8_t u_m, uint8_t u_M, uint8_t v_m, uint8_t v_M)
Filter colors in an YUV422 image.
Parameters
[in] *input The input image to filter
[out] *output The filtered output image
[in] y_m The Y minimum value
[in] y_M The Y maximum value
[in] u_m The U minimum value
[in] u_M The U maximum value
[in] v_m The V minimum value
[in] v_M The V maximum value
Returns
The amount of filtered pixels
Definition at line 173 of file image.c.
References image_t::buf, dest, foo, and image_t::ts.
Referenced by colorfilter_func(), detect_gate_func(), and snake_gate_detection().
image_yuv422_downsample()
void image_yuv422_downsample (struct image_t * input, struct image_t * output, uint8_t downsample)
Simplified high-speed low CPU downsample function without averaging downsample factor must be 1, 2, 4, 8 ... 2^X image of type UYVY expected.
Only one color UV per 2 pixels
we keep the UV color of the first pixel pair and sample the intensity evenly 1-3-5-7-... or 1-5-9-...
input: u1y1 v1y2 u3y3 v3y4 u5y5 v5y6 u7y7 v7y8 ... downsample=1 u1y1 v1y2 u3y3 v3y4 u5y5 v5y6 u7y7 v7y8 ... downsample=2 u1y1v1 (skip2) y3 (skip2) u5y5v5 (skip2) y7 (skip2) ... downsample=4 u1y1v1 (skip6) y5 (skip6) ...
Parameters
[in] *input The input YUV422 image
[out] *output The downscaled YUV422 image
[in] downsample The downsample factor (must be downsample=2^X)
Definition at line 318 of file image.c.
References image_t::buf, dest, foo, image_t::h, image_t::ts, image_t::type, and image_t::w.
Referenced by viewvideo_function().
ker_mul_3x3()
uint8_t ker_mul_3x3 (uint8_t const * source, int_fast8_t const * kernel, uint8_t total, uint8_t setting, int width, int YUV)
Kernel multiplication for a 3 x 3 kernel.
Pixels outside the edges are taken to be 0.
Parameters
[in] source The source values
[in] kernel The kernel values
total The kernel total, set to 1 if the result should not be normalised
setting Variable is used to indicate which pixels the multiplication uses at a specific edges.
YUV A bool that adds an extra pixel offset if the YUV format is used.
Definition at line 1013 of file image.c.
References foo, and offset.
Referenced by image_convolution_3x3().
pyramid_build()
void pyramid_build (struct image_t * input, struct image_t * output_array, uint8_t pyr_level, uint16_t border_size)
This function populates given array of image_t structs with wanted number of padded pyramids based on given input.
Parameters
[in] *input - input image (grayscale only)
[out] *output - array of image_t structs containing image pyiramid levels. Level zero contains original image, followed by pyr_level of pyramid.
[in] pyr_level - number of pyramids to be built. If 0, original image is padded and outputed.
[in] border_size - amount of padding around image. Padding is made by reflecting image elements at the edge Example: f e d c b a | a b c d e f | f e d c b a
Definition at line 464 of file image.c.
References foo, image_add_border(), image_free(), and pyramid_next_level().
Referenced by opticFlowLK().
pyramid_next_level()
void pyramid_next_level (struct image_t * input, struct image_t * output, uint8_t border_size)
This function takes previous padded pyramid level and outputs next level of pyramid without padding.
For calculating new pixel value 3x3 Gaussian filter matrix is used: [1/4 1/2 1/4]' x [1/4 1/2 1/4] Blur and downsample is performed with two 1D convolutions (horizontal then vertical) instead of a single 2D convolution, to increase performance
Parameters
[in] *input - input image (grayscale only)
[out] *output - the output image
[in] border_size - amount of padding around image. Padding is made by reflecting image elements at the edge Example: f e d c b a | a b c d e f | f e d c b a
Definition at line 414 of file image.c.
References image_t::buf, foo, image_t::h, image_create(), image_t::type, and image_t::w.
Referenced by pyramid_build().
set_color_yuv422()
void set_color_yuv422 (struct image_t * im, int x, int y, uint8_t Y, uint8_t U, uint8_t V)
Sets Y,U,V for a single pixel.
Parameters
[in] im The input image to filter
[in] x The x-coordinate of the pixel
[in] y The y-coordinate of the pixel
[in] Y The Y-value.
[in] U The U-value.
[in] V The V value
Definition at line 279 of file image.c.
References image_t::buf, foo, image_t::h, and image_t::w.