Paparazzi UAS: sw/airborne/modules/computer_vision/blob/imavmarker.c File Reference
imavmarker.c File Reference
Find a IMAV pattern.
#include "imavmarker.h"
Macros
#define Img(X, Y) (source[(Y)*input->w*2+(X)*2+1])
Find the marker location.
#define Out(X, Y) (source[(Y)*input->w*2+(X)*2])
Functions
int AbsDiff (int A, int B)
struct marker_deviation_t marker (struct image_t *input, uint8_t M)
Detailed Description
Find a IMAV pattern.
Definition in file imavmarker.c.
Macro Definition Documentation
#define Img (X, Y) (source[(Y)*input->w*2+(X)*2+1])
Find the marker location.
Parameters
[in] *input The input image to filter
[in] M The distance between the pixel of interest and farthest neighbor pixel [pixel]
Returns
The deviation of the marker location wrt the center.
Definition at line 39 of file imavmarker.c.
Referenced by marker().
#define Out (X, Y) (source[(Y)*input->w*2+(X)*2])
Definition at line 40 of file imavmarker.c.
Referenced by marker().
Function Documentation
int AbsDiff (int A, int B) inline
Definition at line 43 of file imavmarker.c.
References A, and B.
Referenced by marker().
struct marker_deviation_t marker (struct image_t * input, uint8_t M)
Definition at line 51 of file imavmarker.c.
References AbsDiff(), if(), Img, marker_deviation_t::inlier, Out, marker_deviation_t::x, and marker_deviation_t::y.
Referenced by cv_marker_func().