Paparazzi UAS: sw/airborne/modules/ins/imu_xsens.h File Reference
imu_xsens.h File Reference
XSENS to just provide IMU measurements.
#include "std.h"
#include "modules/imu/imu.h"
#include "xsens.h"
Functions
void imu_xsens_init (void)
void imu_xsens_event (void)
Detailed Description
XSENS to just provide IMU measurements.
For use with an external AHRS algorithm.
Definition in file imu_xsens.h.
Function Documentation
imu_xsens_event()
void imu_xsens_event (void) extern
Definition at line 43 of file imu_xsens.c.
References FALSE, handle_ins_msg(), XsensParser::msg_received, parse_xsens_msg(), Xsens::parser, xsens, and xsens_parser_event().
imu_xsens_init()
void imu_xsens_init (void) extern
Definition at line 38 of file imu_xsens.c.
References xsens_init().