Paparazzi UAS: sw/airborne/modules/imu/imu_bmi088_i2c.c File Reference
imu_bmi088_i2c.c File Reference
IMU driver for the BMI088 using I2C.
#include "modules/imu/imu_bmi088_i2c.h"
#include "modules/imu/imu.h"
#include "mcu_periph/i2c.h"
#include "mcu_periph/sys_time.h"
#include "modules/core/abi.h"
Macros
#define IMU_BMI088_GYRO_ODR BMI088_GYRO_ODR_1000_BW_116
#define IMU_BMI088_ACCEL_ODR BMI088_ACCEL_ODR_1600
#define IMU_BMI088_ACCEL_BW BMI088_ACCEL_BW_OSR4
#define IMU_BMI088_GYRO_I2C_ADDR BMI088_GYRO_ADDR
#define IMU_BMI088_ACCEL_I2C_ADDR BMI088_ACCEL_ADDR
#define IMU_BMI088_CHAN_X 0
#define IMU_BMI088_CHAN_Y 1
#define IMU_BMI088_CHAN_Z 2
#define IMU_BMI088_X_SIGN 1
#define IMU_BMI088_Y_SIGN 1
#define IMU_BMI088_Z_SIGN 1
Functions
void imu_bmi088_init (void)
void imu_bmi088_periodic (void)
void imu_bmi088_event (void)
Variables
struct ImuBmi088 imu_bmi088
Detailed Description
IMU driver for the BMI088 using I2C.
Definition in file imu_bmi088_i2c.c.
Macro Definition Documentation
IMU_BMI088_ACCEL_BW
#define IMU_BMI088_ACCEL_BW BMI088_ACCEL_BW_OSR4
Definition at line 48 of file imu_bmi088_i2c.c.
IMU_BMI088_ACCEL_I2C_ADDR
#define IMU_BMI088_ACCEL_I2C_ADDR BMI088_ACCEL_ADDR
Definition at line 58 of file imu_bmi088_i2c.c.
IMU_BMI088_ACCEL_ODR
#define IMU_BMI088_ACCEL_ODR BMI088_ACCEL_ODR_1600
Definition at line 43 of file imu_bmi088_i2c.c.
IMU_BMI088_CHAN_X
#define IMU_BMI088_CHAN_X 0
Definition at line 64 of file imu_bmi088_i2c.c.
IMU_BMI088_CHAN_Y
#define IMU_BMI088_CHAN_Y 1
Definition at line 68 of file imu_bmi088_i2c.c.
IMU_BMI088_CHAN_Z
#define IMU_BMI088_CHAN_Z 2
Definition at line 72 of file imu_bmi088_i2c.c.
IMU_BMI088_GYRO_I2C_ADDR
#define IMU_BMI088_GYRO_I2C_ADDR BMI088_GYRO_ADDR
Definition at line 53 of file imu_bmi088_i2c.c.
IMU_BMI088_GYRO_ODR
#define IMU_BMI088_GYRO_ODR BMI088_GYRO_ODR_1000_BW_116
Definition at line 38 of file imu_bmi088_i2c.c.
IMU_BMI088_X_SIGN
#define IMU_BMI088_X_SIGN 1
Definition at line 77 of file imu_bmi088_i2c.c.
IMU_BMI088_Y_SIGN
#define IMU_BMI088_Y_SIGN 1
Definition at line 81 of file imu_bmi088_i2c.c.
IMU_BMI088_Z_SIGN
#define IMU_BMI088_Z_SIGN 1
Definition at line 85 of file imu_bmi088_i2c.c.
Function Documentation
imu_bmi088_event()
void imu_bmi088_event (void)
Definition at line 113 of file imu_bmi088_i2c.c.
References Bmi088_I2c::accel_available, Bmi088Config::accel_samplerate, ImuBmi088::bmi, bmi088_i2c_event(), Bmi088_I2c::config, Bmi088_I2c::data_accel, Bmi088_I2c::data_rates, foo, get_sys_time_usec(), Bmi088_I2c::gyro_available, Bmi088Config::gyro_samplerate, imu_bmi088, IMU_BMI088_CHAN_X, IMU_BMI088_CHAN_Y, IMU_BMI088_CHAN_Z, IMU_BMI088_ID, IMU_BMI088_X_SIGN, IMU_BMI088_Y_SIGN, and IMU_BMI088_Z_SIGN.
imu_bmi088_init()
void imu_bmi088_init (void)
Definition at line 92 of file imu_bmi088_i2c.c.
References Bmi088Config::accel_bw, Bmi088Config::accel_odr, Bmi088Config::accel_range, ImuBmi088::bmi, BMI088_ACCEL_SENS_F, BMI088_GYRO_SENS_F, bmi088_i2c_init(), Bmi088_I2c::config, foo, Bmi088Config::gyro_odr, Bmi088Config::gyro_range, imu_bmi088, IMU_BMI088_ACCEL_BW, IMU_BMI088_ACCEL_I2C_ADDR, IMU_BMI088_ACCEL_ODR, IMU_BMI088_ACCEL_RANGE, IMU_BMI088_GYRO_I2C_ADDR, IMU_BMI088_GYRO_ODR, IMU_BMI088_GYRO_RANGE, IMU_BMI088_ID, imu_set_defaults_accel(), and imu_set_defaults_gyro().
imu_bmi088_periodic()
void imu_bmi088_periodic (void)
Definition at line 108 of file imu_bmi088_i2c.c.
References ImuBmi088::bmi, bmi088_i2c_periodic(), and imu_bmi088.
Variable Documentation
imu_bmi088
struct ImuBmi088 imu_bmi088
Definition at line 90 of file imu_bmi088_i2c.c.
Referenced by imu_bmi088_event(), imu_bmi088_init(), and imu_bmi088_periodic().