Paparazzi UAS: sw/airborne/modules/imu/imu_mpu9250.c File Reference
imu_mpu9250.c File Reference
#include "modules/imu/imu_mpu9250.h"
#include "math/pprz_algebra_int.h"
#include "modules/datalink/downlink.h"
#include "modules/core/abi.h"
Macros
#define IMU_MPU9250_ADDR MPU9250_ADDR
Functions
void imu_mpu9250_init (void)
void imu_mpu9250_periodic (void)
void imu_mpu9250_event (void)
void imu_mpu9250_report (void)
Variables
struct Mpu9250_I2c mpu9250
Detailed Description
Author
Gautier Hattenberger
Test module for the mpu9250
Definition in file imu_mpu9250.c.
Macro Definition Documentation
IMU_MPU9250_ADDR
#define IMU_MPU9250_ADDR MPU9250_ADDR
Definition at line 32 of file imu_mpu9250.c.
Function Documentation
imu_mpu9250_event()
void imu_mpu9250_event (void)
Definition at line 47 of file imu_mpu9250.c.
References mpu9250, and mpu9250_i2c_event().
imu_mpu9250_init()
void imu_mpu9250_init (void)
Definition at line 37 of file imu_mpu9250.c.
References foo, IMU_MPU9250_ADDR, mpu9250, and mpu9250_i2c_init().
imu_mpu9250_periodic()
void imu_mpu9250_periodic (void)
Definition at line 42 of file imu_mpu9250.c.
References mpu9250, and mpu9250_i2c_periodic().
imu_mpu9250_report()
void imu_mpu9250_report (void)
Definition at line 56 of file imu_mpu9250.c.
References Mpu9250_I2c::akm, Ak8963::data, Mpu9250_I2c::data_accel, Mpu9250_I2c::data_rates, DefaultChannel, DefaultDevice, foo, IMU_MPU9250_ID, mpu9250, Int32Rates::p, Int32Rates::q, Int32Rates::r, Int32Vect3::x, Int32Vect3::y, and Int32Vect3::z.
Variable Documentation
mpu9250
struct Mpu9250_I2c mpu9250
Definition at line 35 of file imu_mpu9250.c.
Referenced by imu_mpu9250_event(), imu_mpu9250_init(), imu_mpu9250_periodic(), and imu_mpu9250_report().