Paparazzi UAS: sw/airborne/modules/imu/imu_cube.h File Reference
imu_cube.h File Reference
Driver for the IMU's in the Cube autopilots.
#include "std.h"
Functions
void imu_cube_init (void)
void imu_cube_periodic (void)
void imu_cube_event (void)
Detailed Description
Driver for the IMU's in the Cube autopilots.
Definition in file imu_cube.h.
Function Documentation
imu_cube_event()
void imu_cube_event (void) extern
Definition at line 202 of file imu_cube.c.
References Mpu60x0_Spi::data_accel, Mpu60x0_Spi::data_available, Mpu60x0_Spi::data_rates, foo, get_sys_time_usec(), imu1, imu2, imu3, IMU_CUBE2_ID, invensense2_event(), invensense3_456_event(), invensense3_event(), mpu60x0_spi_event(), and Mpu60x0_Spi::temp.
imu_cube_init()
void imu_cube_init (void) extern
Definition at line 53 of file imu_cube.c.
References invensense2_t::abi_id, invensense2_t::accel_dlpf, invensense2_t::accel_range, Mpu60x0Config::accel_range, ANGLE_BFP_OF_REAL, invensense2_t::bus, Mpu60x0_Spi::config, Mpu60x0Config::dlpf_cfg, Mpu60x0Config::dlpf_cfg_acc, foo, invensense2_t::gyro_dlpf, invensense2_t::gyro_range, Mpu60x0Config::gyro_range, imu1, imu2, imu3, IMU_CUBE1_ID, IMU_CUBE2_ID, IMU_CUBE3_ID, imu_set_defaults_accel(), imu_set_defaults_gyro(), int32_rmat_of_eulers, INVENSENSE2_ACCEL_DLPF_265HZ, INVENSENSE2_ACCEL_RANGE_30G, INVENSENSE2_GYRO_DLPF_229HZ, INVENSENSE2_GYRO_RANGE_4000DPS, invensense2_init(), INVENSENSE2_SPI, invensense3_456_init(), INVENSENSE3_456_ODR_6_4KHZ, INVENSENSE3_ACCEL_ODR_4KHZ, INVENSENSE3_ACCEL_RANGE_32G, INVENSENSE3_GYRO_ODR_4KHZ, INVENSENSE3_GYRO_RANGE_2000DPS, invensense3_init(), INVENSENSE3_PARSER_FIFO, INVENSENSE3_SPI, MPU60X0_ACCEL_RANGE_16G, MPU60X0_ACCEL_SENS_F, MPU60X0_DLPF_256HZ, MPU60X0_DLPF_ACC_218HZ, MPU60X0_GYRO_RANGE_2000, MPU60X0_GYRO_SENS_F, mpu60x0_spi_init(), Int32Eulers::phi, Int32Eulers::psi, Mpu60x0Config::smplrt_div, and Int32Eulers::theta.
imu_cube_periodic()
void imu_cube_periodic (void) extern
Definition at line 185 of file imu_cube.c.
References imu1, imu2, imu3, invensense2_periodic(), invensense3_456_periodic(), invensense3_periodic(), and mpu60x0_spi_periodic().