Paparazzi UAS: sw/airborne/modules/imu/imu_icm42688.c File Reference
imu_icm42688.c File Reference
Driver module for the Invensense v3 IMU ICM42688.
#include "modules/imu/imu_icm42688.h"
#include "modules/imu/imu.h"
#include "modules/core/abi.h"
#include "mcu_periph/spi.h"
#include "peripherals/invensense3.h"
Macros
#define INVENSENSE3_GYRO_AAF 977
#define INVENSENSE3_ACCEL_AAF 213
Functions
void imu_icm42688_init (void)
void imu_icm42688_periodic (void)
void imu_icm42688_event (void)
Variables
static struct invensense3_t imu_icm42688
Detailed Description
Driver module for the Invensense v3 IMU ICM42688.
Definition in file imu_icm42688.c.
Macro Definition Documentation
INVENSENSE3_ACCEL_AAF
#define INVENSENSE3_ACCEL_AAF 213
Definition at line 39 of file imu_icm42688.c.
INVENSENSE3_GYRO_AAF
#define INVENSENSE3_GYRO_AAF 977
Definition at line 35 of file imu_icm42688.c.
Function Documentation
imu_icm42688_event()
void imu_icm42688_event (void)
Definition at line 71 of file imu_icm42688.c.
References imu_icm42688, and invensense3_event().
imu_icm42688_init()
void imu_icm42688_init (void)
Definition at line 44 of file imu_icm42688.c.
References invensense3_t::abi_id, invensense3_t::accel_aaf, invensense3_t::accel_odr, invensense3_t::accel_range, invensense3_t::bus, foo, invensense3_t::gyro_aaf, invensense3_t::gyro_odr, invensense3_t::gyro_range, imu_icm42688, IMU_ICM42688_ID, INVENSENSE3_ACCEL_AAF, INVENSENSE3_GYRO_AAF, invensense3_init(), INVENSENSE3_PARSER_FIFO, INVENSENSE3_SPI, and invensense3_t::parser.
imu_icm42688_periodic()
void imu_icm42688_periodic (void)
Definition at line 66 of file imu_icm42688.c.
References imu_icm42688, and invensense3_periodic().
Variable Documentation
imu_icm42688
struct invensense3_t imu_icm42688 static
Definition at line 42 of file imu_icm42688.c.
Referenced by imu_icm42688_event(), imu_icm42688_init(), and imu_icm42688_periodic().