Paparazzi UAS: sw/airborne/subsystems/imu/imu_mpu6000.h File Reference
imu_mpu6000.h File Reference
Driver for IMU with only MPU6000 via SPI.
#include "std.h"
#include "generated/airframe.h"
#include "subsystems/imu.h"
#include "peripherals/mpu60x0_spi.h"
Data Structures
struct ImuMpu6000
Macros
#define IMU_MPU_GYRO_RANGE MPU60X0_GYRO_RANGE_2000
#define IMU_MPU_ACCEL_RANGE MPU60X0_ACCEL_RANGE_16G
#define IMU_GYRO_P_SENS MPU60X0_GYRO_SENS[IMU_MPU_GYRO_RANGE]
#define IMU_GYRO_P_SENS_NUM MPU60X0_GYRO_SENS_FRAC[IMU_MPU_GYRO_RANGE][0]
#define IMU_GYRO_P_SENS_DEN MPU60X0_GYRO_SENS_FRAC[IMU_MPU_GYRO_RANGE][1]
#define IMU_GYRO_Q_SENS MPU60X0_GYRO_SENS[IMU_MPU_GYRO_RANGE]
#define IMU_GYRO_Q_SENS_NUM MPU60X0_GYRO_SENS_FRAC[IMU_MPU_GYRO_RANGE][0]
#define IMU_GYRO_Q_SENS_DEN MPU60X0_GYRO_SENS_FRAC[IMU_MPU_GYRO_RANGE][1]
#define IMU_GYRO_R_SENS MPU60X0_GYRO_SENS[IMU_MPU_GYRO_RANGE]
#define IMU_GYRO_R_SENS_NUM MPU60X0_GYRO_SENS_FRAC[IMU_MPU_GYRO_RANGE][0]
#define IMU_GYRO_R_SENS_DEN MPU60X0_GYRO_SENS_FRAC[IMU_MPU_GYRO_RANGE][1]
#define IMU_ACCEL_X_SENS MPU60X0_ACCEL_SENS[IMU_MPU_ACCEL_RANGE]
#define IMU_ACCEL_X_SENS_NUM MPU60X0_ACCEL_SENS_FRAC[IMU_MPU_ACCEL_RANGE][0]
#define IMU_ACCEL_X_SENS_DEN MPU60X0_ACCEL_SENS_FRAC[IMU_MPU_ACCEL_RANGE][1]
#define IMU_ACCEL_Y_SENS MPU60X0_ACCEL_SENS[IMU_MPU_ACCEL_RANGE]
#define IMU_ACCEL_Y_SENS_NUM MPU60X0_ACCEL_SENS_FRAC[IMU_MPU_ACCEL_RANGE][0]
#define IMU_ACCEL_Y_SENS_DEN MPU60X0_ACCEL_SENS_FRAC[IMU_MPU_ACCEL_RANGE][1]
#define IMU_ACCEL_Z_SENS MPU60X0_ACCEL_SENS[IMU_MPU_ACCEL_RANGE]
#define IMU_ACCEL_Z_SENS_NUM MPU60X0_ACCEL_SENS_FRAC[IMU_MPU_ACCEL_RANGE][0]
#define IMU_ACCEL_Z_SENS_DEN MPU60X0_ACCEL_SENS_FRAC[IMU_MPU_ACCEL_RANGE][1]
Functions
void imu_mpu_spi_init (void)
void imu_mpu_spi_periodic (void)
void imu_mpu_spi_event (void)
Variables
struct ImuMpu6000 imu_mpu_spi
Detailed Description
Driver for IMU with only MPU6000 via SPI.
Definition in file imu_mpu6000.h.
Data Structure Documentation
struct ImuMpu6000
Definition at line 71 of file imu_mpu6000.h.
Data Fields
struct Mpu60x0_Spi mpu
Macro Definition Documentation
#define IMU_ACCEL_X_SENS MPU60X0_ACCEL_SENS[IMU_MPU_ACCEL_RANGE]
Definition at line 59 of file imu_mpu6000.h.
#define IMU_ACCEL_X_SENS_DEN MPU60X0_ACCEL_SENS_FRAC[IMU_MPU_ACCEL_RANGE][1]
Definition at line 61 of file imu_mpu6000.h.
#define IMU_ACCEL_X_SENS_NUM MPU60X0_ACCEL_SENS_FRAC[IMU_MPU_ACCEL_RANGE][0]
Definition at line 60 of file imu_mpu6000.h.
#define IMU_ACCEL_Y_SENS MPU60X0_ACCEL_SENS[IMU_MPU_ACCEL_RANGE]
Definition at line 62 of file imu_mpu6000.h.
#define IMU_ACCEL_Y_SENS_DEN MPU60X0_ACCEL_SENS_FRAC[IMU_MPU_ACCEL_RANGE][1]
Definition at line 64 of file imu_mpu6000.h.
#define IMU_ACCEL_Y_SENS_NUM MPU60X0_ACCEL_SENS_FRAC[IMU_MPU_ACCEL_RANGE][0]
Definition at line 63 of file imu_mpu6000.h.
#define IMU_ACCEL_Z_SENS MPU60X0_ACCEL_SENS[IMU_MPU_ACCEL_RANGE]
Definition at line 65 of file imu_mpu6000.h.
#define IMU_ACCEL_Z_SENS_DEN MPU60X0_ACCEL_SENS_FRAC[IMU_MPU_ACCEL_RANGE][1]
Definition at line 67 of file imu_mpu6000.h.
#define IMU_ACCEL_Z_SENS_NUM MPU60X0_ACCEL_SENS_FRAC[IMU_MPU_ACCEL_RANGE][0]
Definition at line 66 of file imu_mpu6000.h.
#define IMU_GYRO_P_SENS MPU60X0_GYRO_SENS[IMU_MPU_GYRO_RANGE]
Definition at line 46 of file imu_mpu6000.h.
#define IMU_GYRO_P_SENS_DEN MPU60X0_GYRO_SENS_FRAC[IMU_MPU_GYRO_RANGE][1]
Definition at line 48 of file imu_mpu6000.h.
#define IMU_GYRO_P_SENS_NUM MPU60X0_GYRO_SENS_FRAC[IMU_MPU_GYRO_RANGE][0]
Definition at line 47 of file imu_mpu6000.h.
#define IMU_GYRO_Q_SENS MPU60X0_GYRO_SENS[IMU_MPU_GYRO_RANGE]
Definition at line 49 of file imu_mpu6000.h.
#define IMU_GYRO_Q_SENS_DEN MPU60X0_GYRO_SENS_FRAC[IMU_MPU_GYRO_RANGE][1]
Definition at line 51 of file imu_mpu6000.h.
#define IMU_GYRO_Q_SENS_NUM MPU60X0_GYRO_SENS_FRAC[IMU_MPU_GYRO_RANGE][0]
Definition at line 50 of file imu_mpu6000.h.
#define IMU_GYRO_R_SENS MPU60X0_GYRO_SENS[IMU_MPU_GYRO_RANGE]
Definition at line 52 of file imu_mpu6000.h.
#define IMU_GYRO_R_SENS_DEN MPU60X0_GYRO_SENS_FRAC[IMU_MPU_GYRO_RANGE][1]
Definition at line 54 of file imu_mpu6000.h.
#define IMU_GYRO_R_SENS_NUM MPU60X0_GYRO_SENS_FRAC[IMU_MPU_GYRO_RANGE][0]
Definition at line 53 of file imu_mpu6000.h.
#define IMU_MPU_ACCEL_RANGE MPU60X0_ACCEL_RANGE_16G
Definition at line 41 of file imu_mpu6000.h.
Referenced by imu_mpu_hmc_init(), and imu_mpu_spi_init().
#define IMU_MPU_GYRO_RANGE MPU60X0_GYRO_RANGE_2000
Definition at line 37 of file imu_mpu6000.h.
Referenced by imu_mpu_hmc_init(), and imu_mpu_spi_init().
Function Documentation
void imu_mpu_spi_event (void)
Definition at line 125 of file imu_mpu6000.c.
References Imu::accel, Imu::accel_unscaled, Mpu60x0_Spi::data_accel, Mpu60x0_Spi::data_available, Mpu60x0_Spi::data_rates, get_sys_time_usec(), Imu::gyro, Imu::gyro_unscaled, imu, IMU_MPU6000_ID, IMU_MPU_CHAN_X, IMU_MPU_CHAN_Y, IMU_MPU_CHAN_Z, imu_mpu_spi, IMU_MPU_X_SIGN, IMU_MPU_Y_SIGN, IMU_MPU_Z_SIGN, imu_scale_accel(), imu_scale_gyro(), ImuMpu6000::mpu, mpu60x0_spi_event(), RATES_COPY, and VECT3_COPY.
void imu_mpu_spi_init (void)
Definition at line 108 of file imu_mpu6000.c.
References Mpu60x0Config::accel_range, Mpu60x0_Spi::config, Mpu60x0Config::dlpf_cfg, Mpu60x0Config::dlpf_cfg_acc, Mpu60x0Config::gyro_range, IMU_MPU_ACCEL_LOWPASS_FILTER, IMU_MPU_ACCEL_RANGE, IMU_MPU_GYRO_RANGE, IMU_MPU_LOWPASS_FILTER, IMU_MPU_SMPLRT_DIV, ImuMpu6000::mpu, mpu60x0_spi_init(), and Mpu60x0Config::smplrt_div.
void imu_mpu_spi_periodic (void)
Definition at line 120 of file imu_mpu6000.c.
References imu_mpu_spi, ImuMpu6000::mpu, and mpu60x0_spi_periodic().
Variable Documentation
struct ImuMpu6000 imu_mpu_spi
Definition at line 106 of file imu_mpu6000.c.
Referenced by imu_mpu_spi_event(), and imu_mpu_spi_periodic().