Paparazzi UAS: sw/airborne/modules/imu/imu_aspirin_i2c.h File Reference
imu_aspirin_i2c.h File Reference
Interface for the Aspirin v1.x IMU using I2C for the accelerometer.
#include "generated/airframe.h"
#include "modules/imu/imu.h"
#include "peripherals/itg3200.h"
#include "peripherals/hmc58xx.h"
#include "peripherals/adxl345_i2c.h"
Data Structures
struct ImuAspirinI2c
Functions
void imu_aspirin_i2c_init (void)
void imu_aspirin_i2c_periodic (void)
void imu_aspirin_i2c_event (void)
Variables
struct ImuAspirinI2c imu_aspirin
Detailed Description
Interface for the Aspirin v1.x IMU using I2C for the accelerometer.
Definition in file imu_aspirin_i2c.h.
Data Structure Documentation
ImuAspirinI2c
struct ImuAspirinI2c
Definition at line 40 of file imu_aspirin_i2c.h.
Data Fields
struct Adxl345_I2c acc_adxl
struct Itg3200 gyro_itg
struct Hmc58xx mag_hmc
Function Documentation
imu_aspirin_i2c_event()
void imu_aspirin_i2c_event (void) extern
Definition at line 143 of file imu_aspirin_i2c.c.
References ImuAspirinI2c::acc_adxl, adxl345_i2c_event(), Adxl345_I2c::data, Hmc58xx::data, Itg3200::data, Adxl345_I2c::data_available, Hmc58xx::data_available, Itg3200::data_available, foo, get_sys_time_usec(), ImuAspirinI2c::gyro_itg, hmc58xx_event(), imu_aspirin, IMU_ASPIRIN_ID, itg3200_event(), ImuAspirinI2c::mag_hmc, VECT3_COPY, Int32Vect3::x, Int32Vect3::y, and Int32Vect3::z.
imu_aspirin_i2c_init()
void imu_aspirin_i2c_init (void) extern
Todo:
drdy int handling for adxl345
Todo:
eoc interrupt for itg3200, polling for now (including status reg)
Definition at line 85 of file imu_aspirin_i2c.c.
References ImuAspirinI2c::acc_adxl, accel_scale_f, ADXL345_ADDR, adxl345_i2c_init(), ASPIRIN_ACCEL_RATE, ASPIRIN_GYRO_LOWPASS, ASPIRIN_GYRO_SMPLRT_DIV, ASPIRIN_I2C_DEV, Adxl345_I2c::config, Itg3200::config, Itg3200Config::dlpf_cfg, foo, gpio_set(), gpio_setup_output(), ImuAspirinI2c::gyro_itg, gyro_scale_f, HMC58XX_ADDR, hmc58xx_init(), HMC_TYPE_5843, imu_aspirin, IMU_ASPIRIN_ID, imu_set_defaults_accel(), imu_set_defaults_gyro(), ITG3200_ADDR, itg3200_init(), ImuAspirinI2c::mag_hmc, Adxl345Config::rate, Itg3200Config::smplrt_div, and Hmc58xx::type.
imu_aspirin_i2c_periodic()
void imu_aspirin_i2c_periodic (void) extern
Definition at line 132 of file imu_aspirin_i2c.c.
References ImuAspirinI2c::acc_adxl, adxl345_i2c_periodic(), foo, ImuAspirinI2c::gyro_itg, hmc58xx_periodic(), imu_aspirin, itg3200_periodic(), and ImuAspirinI2c::mag_hmc.
Variable Documentation
imu_aspirin
struct ImuAspirinI2c imu_aspirin extern
Definition at line 68 of file imu_aspirin.c.
Referenced by imu_aspirin_event(), imu_aspirin_i2c_event(), imu_aspirin_i2c_init(), imu_aspirin_i2c_periodic(), imu_aspirin_init(), and imu_aspirin_periodic().