Paparazzi UAS: sw/airborne/subsystems/imu/imu_mpu6000_hmc5883.c File Reference
imu_mpu6000_hmc5883.c File Reference
Driver for IMU with MPU6000 via SPI and HMC5883 via I2c.
#include "subsystems/imu.h"
#include "subsystems/abi.h"
#include "mcu_periph/spi.h"
#include "peripherals/hmc58xx_regs.h"
Macros
#define IMU_MPU_CHAN_X 0
#define IMU_MPU_CHAN_Y 1
#define IMU_MPU_CHAN_Z 2
#define IMU_MPU_X_SIGN 1
#define IMU_MPU_Y_SIGN 1
#define IMU_MPU_Z_SIGN 1
#define IMU_HMC_CHAN_X 1
#define IMU_HMC_CHAN_Y 0
#define IMU_HMC_CHAN_Z 2
#define IMU_HMC_X_SIGN 1
#define IMU_HMC_Y_SIGN -1
#define IMU_HMC_Z_SIGN 1
Functions
void imu_mpu_hmc_init (void)
void imu_mpu_hmc_periodic (void)
void imu_mpu_hmc_event (void)
Variables
struct ImuMpu6000Hmc5883 imu_mpu_hmc
Detailed Description
Driver for IMU with MPU6000 via SPI and HMC5883 via I2c.
Definition in file imu_mpu6000_hmc5883.c.
Macro Definition Documentation
#define IMU_HMC_CHAN_X 1
Definition at line 94 of file imu_mpu6000_hmc5883.c.
Referenced by imu_mpu_hmc_event().
#define IMU_HMC_CHAN_Y 0
Definition at line 98 of file imu_mpu6000_hmc5883.c.
Referenced by imu_mpu_hmc_event().
#define IMU_HMC_CHAN_Z 2
Definition at line 102 of file imu_mpu6000_hmc5883.c.
Referenced by imu_mpu_hmc_event().
#define IMU_HMC_X_SIGN 1
Definition at line 107 of file imu_mpu6000_hmc5883.c.
Referenced by imu_mpu_hmc_event().
#define IMU_HMC_Y_SIGN -1
Definition at line 111 of file imu_mpu6000_hmc5883.c.
Referenced by imu_mpu_hmc_event().
#define IMU_HMC_Z_SIGN 1
Definition at line 115 of file imu_mpu6000_hmc5883.c.
Referenced by imu_mpu_hmc_event().
#define IMU_MPU_CHAN_X 0
Definition at line 67 of file imu_mpu6000_hmc5883.c.
Referenced by imu_mpu_hmc_event().
#define IMU_MPU_CHAN_Y 1
Definition at line 71 of file imu_mpu6000_hmc5883.c.
Referenced by imu_mpu_hmc_event().
#define IMU_MPU_CHAN_Z 2
Definition at line 75 of file imu_mpu6000_hmc5883.c.
Referenced by imu_mpu_hmc_event().
#define IMU_MPU_X_SIGN 1
Definition at line 80 of file imu_mpu6000_hmc5883.c.
Referenced by imu_mpu_hmc_event().
#define IMU_MPU_Y_SIGN 1
Definition at line 84 of file imu_mpu6000_hmc5883.c.
Referenced by imu_mpu_hmc_event().
#define IMU_MPU_Z_SIGN 1
Definition at line 88 of file imu_mpu6000_hmc5883.c.
Referenced by imu_mpu_hmc_event().
Function Documentation
void imu_mpu_hmc_event (void)
Definition at line 146 of file imu_mpu6000_hmc5883.c.
References Imu::accel, Imu::accel_unscaled, Hmc58xx::data, Mpu60x0_Spi::data_accel, Mpu60x0_Spi::data_available, Hmc58xx::data_available, Mpu60x0_Spi::data_rates, get_sys_time_usec(), Imu::gyro, Imu::gyro_unscaled, ImuMpu6000Hmc5883::hmc, hmc58xx_event(), imu, IMU_HMC_CHAN_X, IMU_HMC_CHAN_Y, IMU_HMC_CHAN_Z, IMU_HMC_X_SIGN, IMU_HMC_Y_SIGN, IMU_HMC_Z_SIGN, IMU_MPU6000_HMC_ID, IMU_MPU_CHAN_X, IMU_MPU_CHAN_Y, IMU_MPU_CHAN_Z, imu_mpu_hmc, IMU_MPU_X_SIGN, IMU_MPU_Y_SIGN, IMU_MPU_Z_SIGN, imu_scale_accel(), imu_scale_gyro(), imu_scale_mag(), Imu::mag, Imu::mag_unscaled, ImuMpu6000Hmc5883::mpu, mpu60x0_spi_event(), RATES_COPY, VECT3_COPY, Int32Vect3::x, Int32Vect3::y, and Int32Vect3::z.
void imu_mpu_hmc_init (void)
Definition at line 122 of file imu_mpu6000_hmc5883.c.
References Mpu60x0Config::accel_range, Mpu60x0_Spi::config, Mpu60x0Config::dlpf_cfg, Mpu60x0Config::gyro_range, ImuMpu6000Hmc5883::hmc, HMC58XX_ADDR, hmc58xx_init(), IMU_MPU_ACCEL_RANGE, IMU_MPU_GYRO_RANGE, IMU_MPU_LOWPASS_FILTER, IMU_MPU_SMPLRT_DIV, ImuMpu6000Hmc5883::mpu, mpu60x0_spi_init(), and Mpu60x0Config::smplrt_div.
void imu_mpu_hmc_periodic (void)
Definition at line 136 of file imu_mpu6000_hmc5883.c.
References ImuMpu6000Hmc5883::hmc, hmc58xx_periodic(), imu_mpu_hmc, ImuMpu6000Hmc5883::mpu, and mpu60x0_spi_periodic().
Variable Documentation
struct ImuMpu6000Hmc5883 imu_mpu_hmc
Definition at line 120 of file imu_mpu6000_hmc5883.c.
Referenced by imu_mpu_hmc_event(), and imu_mpu_hmc_periodic().