Paparazzi UAS: sw/airborne/modules/imu/imu_aspirin_i2c.c File Reference
imu_aspirin_i2c.c File Reference
Driver for the Aspirin v1.x IMU using I2C for the accelerometer.
#include "modules/imu/imu_aspirin_i2c.h"
#include "modules/imu/imu.h"
#include "modules/core/abi.h"
#include "mcu_periph/i2c.h"
#include "generated/modules.h"
#include "mcu_periph/gpio.h"
Macros
#define ASPIRIN_I2C_DEV i2c2
#define ASPIRIN_ACCEL_RATE ADXL345_RATE_50HZ
adxl345 accelerometer output rate, lowpass is set to half of rate
#define ASPIRIN_GYRO_LOWPASS ITG3200_DLPF_20HZ
gyro internal lowpass frequency
#define ASPIRIN_GYRO_SMPLRT_DIV 19
gyro sample rate divider
Functions
void imu_aspirin_i2c_init (void)
void imu_aspirin_i2c_periodic (void)
void imu_aspirin_i2c_event (void)
Variables
struct ImuAspirinI2c imu_aspirin
Detailed Description
Driver for the Aspirin v1.x IMU using I2C for the accelerometer.
Definition in file imu_aspirin_i2c.c.
Macro Definition Documentation
ASPIRIN_ACCEL_RATE
#define ASPIRIN_ACCEL_RATE ADXL345_RATE_50HZ
adxl345 accelerometer output rate, lowpass is set to half of rate
Definition at line 47 of file imu_aspirin_i2c.c.
ASPIRIN_GYRO_LOWPASS
#define ASPIRIN_GYRO_LOWPASS ITG3200_DLPF_20HZ
gyro internal lowpass frequency
Definition at line 60 of file imu_aspirin_i2c.c.
ASPIRIN_GYRO_SMPLRT_DIV
#define ASPIRIN_GYRO_SMPLRT_DIV 19
gyro sample rate divider
Definition at line 73 of file imu_aspirin_i2c.c.
ASPIRIN_I2C_DEV
#define ASPIRIN_I2C_DEV i2c2
Definition at line 40 of file imu_aspirin_i2c.c.
Function Documentation
imu_aspirin_i2c_event()
void imu_aspirin_i2c_event (void)
Definition at line 143 of file imu_aspirin_i2c.c.
References ImuAspirinI2c::acc_adxl, adxl345_i2c_event(), Adxl345_I2c::data, Hmc58xx::data, Itg3200::data, Adxl345_I2c::data_available, Hmc58xx::data_available, Itg3200::data_available, foo, get_sys_time_usec(), ImuAspirinI2c::gyro_itg, hmc58xx_event(), imu_aspirin, IMU_ASPIRIN_ID, itg3200_event(), ImuAspirinI2c::mag_hmc, VECT3_COPY, Int32Vect3::x, Int32Vect3::y, and Int32Vect3::z.
imu_aspirin_i2c_init()
void imu_aspirin_i2c_init (void)
Todo:
drdy int handling for adxl345
Todo:
eoc interrupt for itg3200, polling for now (including status reg)
Definition at line 85 of file imu_aspirin_i2c.c.
References ImuAspirinI2c::acc_adxl, accel_scale_f, ADXL345_ADDR, adxl345_i2c_init(), ASPIRIN_ACCEL_RATE, ASPIRIN_GYRO_LOWPASS, ASPIRIN_GYRO_SMPLRT_DIV, ASPIRIN_I2C_DEV, Adxl345_I2c::config, Itg3200::config, Itg3200Config::dlpf_cfg, foo, gpio_set(), gpio_setup_output(), ImuAspirinI2c::gyro_itg, gyro_scale_f, HMC58XX_ADDR, hmc58xx_init(), HMC_TYPE_5843, imu_aspirin, IMU_ASPIRIN_ID, imu_set_defaults_accel(), imu_set_defaults_gyro(), ITG3200_ADDR, itg3200_init(), ImuAspirinI2c::mag_hmc, Adxl345Config::rate, Itg3200Config::smplrt_div, and Hmc58xx::type.
imu_aspirin_i2c_periodic()
void imu_aspirin_i2c_periodic (void)
Definition at line 132 of file imu_aspirin_i2c.c.
References ImuAspirinI2c::acc_adxl, adxl345_i2c_periodic(), foo, ImuAspirinI2c::gyro_itg, hmc58xx_periodic(), imu_aspirin, itg3200_periodic(), and ImuAspirinI2c::mag_hmc.
Variable Documentation
imu_aspirin
struct ImuAspirinI2c imu_aspirin
Definition at line 83 of file imu_aspirin_i2c.c.
Referenced by imu_aspirin_i2c_event(), imu_aspirin_i2c_init(), and imu_aspirin_i2c_periodic().