Paparazzi UAS: sw/airborne/modules/imu/imu_mpu6000.c File Reference
imu_mpu6000.c File Reference
Driver for IMU with only MPU6000 via SPI.
#include "modules/imu/imu_mpu6000.h"
#include "modules/imu/imu.h"
#include "modules/core/abi.h"
#include "mcu_periph/spi.h"
#include "generated/modules.h"
Macros
#define IMU_MPU_LOWPASS_FILTER MPU60X0_DLPF_42HZ
#define IMU_MPU_SMPLRT_DIV 9
#define IMU_MPU_ACCEL_LOWPASS_FILTER MPU60X0_DLPF_ACC_44HZ
#define IMU_MPU_CHAN_X 0
#define IMU_MPU_CHAN_Y 1
#define IMU_MPU_CHAN_Z 2
#define IMU_MPU_X_SIGN 1
#define IMU_MPU_Y_SIGN 1
#define IMU_MPU_Z_SIGN 1
Functions
void imu_mpu_spi_init (void)
void imu_mpu_spi_periodic (void)
void imu_mpu_spi_event (void)
Variables
struct ImuMpu6000 imu_mpu_spi
Detailed Description
Driver for IMU with only MPU6000 via SPI.
Definition in file imu_mpu6000.c.
Macro Definition Documentation
IMU_MPU_ACCEL_LOWPASS_FILTER
#define IMU_MPU_ACCEL_LOWPASS_FILTER MPU60X0_DLPF_ACC_44HZ
Definition at line 69 of file imu_mpu6000.c.
IMU_MPU_CHAN_X
#define IMU_MPU_CHAN_X 0
Definition at line 83 of file imu_mpu6000.c.
IMU_MPU_CHAN_Y
#define IMU_MPU_CHAN_Y 1
Definition at line 87 of file imu_mpu6000.c.
IMU_MPU_CHAN_Z
#define IMU_MPU_CHAN_Z 2
Definition at line 91 of file imu_mpu6000.c.
IMU_MPU_LOWPASS_FILTER
#define IMU_MPU_LOWPASS_FILTER MPU60X0_DLPF_42HZ
Definition at line 65 of file imu_mpu6000.c.
IMU_MPU_SMPLRT_DIV
#define IMU_MPU_SMPLRT_DIV 9
Definition at line 66 of file imu_mpu6000.c.
IMU_MPU_X_SIGN
#define IMU_MPU_X_SIGN 1
Definition at line 97 of file imu_mpu6000.c.
IMU_MPU_Y_SIGN
#define IMU_MPU_Y_SIGN 1
Definition at line 101 of file imu_mpu6000.c.
IMU_MPU_Z_SIGN
#define IMU_MPU_Z_SIGN 1
Definition at line 105 of file imu_mpu6000.c.
Function Documentation
imu_mpu_spi_event()
void imu_mpu_spi_event (void)
Definition at line 142 of file imu_mpu6000.c.
References Mpu60x0_Spi::data_accel, Mpu60x0_Spi::data_available, Mpu60x0_Spi::data_rates, foo, get_sys_time_usec(), IMU_MPU6000_ID, IMU_MPU_CHAN_X, IMU_MPU_CHAN_Y, IMU_MPU_CHAN_Z, imu_mpu_spi, IMU_MPU_X_SIGN, IMU_MPU_Y_SIGN, IMU_MPU_Z_SIGN, ImuMpu6000::mpu, mpu60x0_spi_event(), Mpu60x0_Spi::temp, UpdateMedianFilterRatesInt, and UpdateMedianFilterVect3Int.
imu_mpu_spi_init()
void imu_mpu_spi_init (void)
Definition at line 116 of file imu_mpu6000.c.
References Mpu60x0Config::accel_range, Mpu60x0_Spi::config, Mpu60x0Config::dlpf_cfg, Mpu60x0Config::dlpf_cfg_acc, foo, Mpu60x0Config::gyro_range, IMU_MPU6000_ID, IMU_MPU_ACCEL_LOWPASS_FILTER, IMU_MPU_ACCEL_RANGE, IMU_MPU_GYRO_RANGE, IMU_MPU_LOWPASS_FILTER, IMU_MPU_SMPLRT_DIV, imu_mpu_spi, imu_set_defaults_accel(), imu_set_defaults_gyro(), InitMedianFilterRatesInt, InitMedianFilterVect3Int, ImuMpu6000::mpu, MPU60X0_ACCEL_SENS_F, MPU60X0_GYRO_SENS_F, mpu60x0_spi_init(), and Mpu60x0Config::smplrt_div.
imu_mpu_spi_periodic()
void imu_mpu_spi_periodic (void)
Definition at line 137 of file imu_mpu6000.c.
References imu_mpu_spi, ImuMpu6000::mpu, and mpu60x0_spi_periodic().
Variable Documentation
imu_mpu_spi
struct ImuMpu6000 imu_mpu_spi
Definition at line 109 of file imu_mpu6000.c.
Referenced by imu_mpu_spi_event(), imu_mpu_spi_init(), and imu_mpu_spi_periodic().