Paparazzi UAS: sw/airborne/modules/imu/imu_icm42688.h File Reference
imu_icm42688.h File Reference
Driver for the IMU ICM42688.
#include "std.h"
Functions
void imu_icm42688_init (void)
void imu_icm42688_periodic (void)
void imu_icm42688_event (void)
Detailed Description
Driver for the IMU ICM42688.
Definition in file imu_icm42688.h.
Function Documentation
imu_icm42688_event()
void imu_icm42688_event (void) extern
Definition at line 71 of file imu_icm42688.c.
References imu_icm42688, and invensense3_event().
imu_icm42688_init()
void imu_icm42688_init (void) extern
Definition at line 44 of file imu_icm42688.c.
References invensense3_t::abi_id, invensense3_t::accel_aaf, invensense3_t::accel_odr, invensense3_t::accel_range, invensense3_t::bus, foo, invensense3_t::gyro_aaf, invensense3_t::gyro_odr, invensense3_t::gyro_range, imu_icm42688, IMU_ICM42688_ID, INVENSENSE3_ACCEL_AAF, INVENSENSE3_GYRO_AAF, invensense3_init(), INVENSENSE3_PARSER_FIFO, INVENSENSE3_SPI, and invensense3_t::parser.
imu_icm42688_periodic()
void imu_icm42688_periodic (void) extern
Definition at line 66 of file imu_icm42688.c.
References imu_icm42688, and invensense3_periodic().