Paparazzi UAS: sw/airborne/modules/imu/imu_mpu60x0_i2c.c File Reference
imu_mpu60x0_i2c.c File Reference
Driver for IMU with only MPU60X0 via I2C.
#include <math.h>
#include "modules/imu/imu_mpu60x0_i2c.h"
#include "modules/imu/imu.h"
#include "modules/core/abi.h"
#include "mcu_periph/i2c.h"
#include "led.h"
#include "generated/modules.h"
Macros
#define IMU_MPU60X0_I2C_ADDR MPU60X0_ADDR
Functions
void imu_mpu_i2c_init (void)
void imu_mpu_i2c_periodic (void)
void imu_mpu_i2c_event (void)
Variables
struct ImuMpu60x0 imu_mpu_i2c
Detailed Description
Driver for IMU with only MPU60X0 via I2C.
Definition in file imu_mpu60x0_i2c.c.
Macro Definition Documentation
IMU_MPU60X0_I2C_ADDR
#define IMU_MPU60X0_I2C_ADDR MPU60X0_ADDR
Definition at line 62 of file imu_mpu60x0_i2c.c.
Function Documentation
imu_mpu_i2c_event()
void imu_mpu_i2c_event (void)
Definition at line 86 of file imu_mpu60x0_i2c.c.
References Mpu60x0_I2c::data_accel, Mpu60x0_I2c::data_available, Mpu60x0_I2c::data_rates, foo, get_sys_time_usec(), IMU_MPU60X0_ID, imu_mpu_i2c, ImuMpu60x0::mpu, mpu60x0_i2c_event(), and Mpu60x0_I2c::temp.
imu_mpu_i2c_init()
void imu_mpu_i2c_init (void)
Definition at line 67 of file imu_mpu60x0_i2c.c.
References Mpu60x0Config::accel_range, Mpu60x0_I2c::config, Mpu60x0Config::dlpf_cfg, foo, Mpu60x0Config::gyro_range, IMU_MPU60X0_ACCEL_RANGE, IMU_MPU60X0_GYRO_RANGE, IMU_MPU60X0_I2C_ADDR, IMU_MPU60X0_ID, imu_mpu_i2c, imu_set_defaults_accel(), imu_set_defaults_gyro(), ImuMpu60x0::mpu, MPU60X0_ACCEL_SENS_F, MPU60X0_GYRO_SENS_F, mpu60x0_i2c_init(), and Mpu60x0Config::smplrt_div.
imu_mpu_i2c_periodic()
void imu_mpu_i2c_periodic (void)
Definition at line 81 of file imu_mpu60x0_i2c.c.
References imu_mpu_i2c, ImuMpu60x0::mpu, and mpu60x0_i2c_periodic().
Variable Documentation
imu_mpu_i2c
struct ImuMpu60x0 imu_mpu_i2c
Definition at line 65 of file imu_mpu60x0_i2c.c.
Referenced by imu_mpu_i2c_event(), imu_mpu_i2c_init(), and imu_mpu_i2c_periodic().