Paparazzi UAS: sw/airborne/modules/imu/imu.c File Reference
imu.c File Reference
Inertial Measurement Unit interface.
#include "modules/imu/imu.h"
#include "state.h"
#include "modules/core/abi.h"
#include "modules/energy/electrical.h"
#include "modules/datalink/telemetry.h"
Macros
#define IMU_INTEGRATION false
By default disable IMU integration calculations.
#define IMU_GYRO_P_SIGN 1
By default gyro signs are positive for single IMU with old format or defaults.
#define IMU_GYRO_Q_SIGN 1
#define IMU_GYRO_R_SIGN 1
#define IMU_GYRO_CALIB {}
Default gyro calibration is for single IMU with old format.
#define IMU_ACCEL_X_SIGN 1
By default accel signs are positive for single IMU with old format and defaults.
#define IMU_ACCEL_Y_SIGN 1
#define IMU_ACCEL_Z_SIGN 1
#define IMU_ACCEL_CALIB {}
Default accel calibration is for single IMU with old format.
#define IMU_MAG_X_SIGN 1
By default mag signs are positive for single IMU with old format and defaults.
#define IMU_MAG_Y_SIGN 1
#define IMU_MAG_Z_SIGN 1
#define IMU_MAG_CALIB {}
Default mag calibration is for single IMU with old format.
#define IMU_BODY_TO_IMU_PHI 0
Default body to imu is 0 (radians)
#define IMU_BODY_TO_IMU_THETA 0
#define IMU_BODY_TO_IMU_PSI 0
#define IMU_GYRO_ABI_SEND_ID ABI_BROADCAST
Which gyro measurements to send over telemetry/logging.
#define IMU_ACCEL_ABI_SEND_ID ABI_BROADCAST
Which accel measurements to send over telemetry/logging.
#define IMU_MAG_ABI_SEND_ID ABI_BROADCAST
Which mag measurements to send over telemetry/logging.
#define IMU_LOG_HIGHSPEED_DEVICE flightrecorder_sdlog
By default log highspeed on the flightrecorder.
Functions
static void send_accel_raw (struct transport_tx *trans, struct link_device *dev)
static void send_accel_scaled (struct transport_tx *trans, struct link_device *dev)
static void send_accel (struct transport_tx *trans, struct link_device *dev)
static void send_gyro_raw (struct transport_tx *trans, struct link_device *dev)
static void send_gyro_scaled (struct transport_tx *trans, struct link_device *dev)
static void send_gyro (struct transport_tx *trans, struct link_device *dev)
static void send_mag_raw (struct transport_tx *trans, struct link_device *dev)
static void send_mag_scaled (struct transport_tx *trans, struct link_device *dev)
static void send_mag (struct transport_tx *trans, struct link_device *dev)
static void send_mag_current (struct transport_tx *trans, struct link_device *dev)
static void imu_gyro_raw_cb (uint8_t sender_id, uint32_t stamp, struct Int32Rates *data, uint8_t samples, float rate, float temp)
static void imu_accel_raw_cb (uint8_t sender_id, uint32_t stamp, struct Int32Vect3 *data, uint8_t samples, float rate, float temp)
static void imu_mag_raw_cb (uint8_t sender_id, uint32_t stamp, struct Int32Vect3 *data)
static void imu_set_body_to_imu_eulers (struct FloatEulers *body_to_imu_eulers)
Set the body to IMU rotation in eulers This will update all the sensor values.
void imu_init (void)
External functions.
void imu_set_defaults_gyro (uint8_t abi_id, const struct Int32RMat *imu_to_sensor, const struct Int32Rates *neutral, const struct FloatRates *scale_f)
Set the defaults for a gyro sensor WARNING: Should be called before sensor is publishing messages to ensure correct values.
void imu_set_defaults_accel (uint8_t abi_id, const struct Int32RMat *imu_to_sensor, const struct Int32Vect3 *neutral, const struct FloatVect3 *scale_f)
Set the defaults for a accel sensor WARNING: Should be called before sensor is publishing messages to ensure correct values.
void imu_set_defaults_mag (uint8_t abi_id, const struct Int32RMat *imu_to_sensor, const struct Int32Vect3 *neutral, const struct FloatVect3 *scale_f)
Set the defaults for a mag sensor WARNING: Should be called before sensor is publishing messages to ensure correct values.
struct imu_gyro_t * imu_get_gyro (uint8_t sender_id, bool create)
Find or create the gyro in the imu structure.
struct imu_accel_t * imu_get_accel (uint8_t sender_id, bool create)
Find or create the accel in the imu structure.
struct imu_mag_t * imu_get_mag (uint8_t sender_id, bool create)
Find or create the mag in the imu structure.
void imu_SetBodyToImuPhi (float phi)
void imu_SetBodyToImuTheta (float theta)
void imu_SetBodyToImuPsi (float psi)
void imu_SetBodyToImuCurrent (float set)
Variables
struct Imu imu = {0}
global IMU state
static abi_event imu_gyro_raw_ev
static abi_event imu_accel_raw_ev
static abi_event imu_mag_raw_ev
Detailed Description
Inertial Measurement Unit interface.
Definition in file imu.c.
Macro Definition Documentation
IMU_ACCEL_ABI_SEND_ID
#define IMU_ACCEL_ABI_SEND_ID ABI_BROADCAST
Which accel measurements to send over telemetry/logging.
Definition at line 170 of file imu.c.
IMU_ACCEL_CALIB
#define IMU_ACCEL_CALIB {}
Default accel calibration is for single IMU with old format.
Definition at line 113 of file imu.c.
IMU_ACCEL_X_SIGN
#define IMU_ACCEL_X_SIGN 1
By default accel signs are positive for single IMU with old format and defaults.
Definition at line 86 of file imu.c.
IMU_ACCEL_Y_SIGN
#define IMU_ACCEL_Y_SIGN 1
Definition at line 89 of file imu.c.
IMU_ACCEL_Z_SIGN
#define IMU_ACCEL_Z_SIGN 1
Definition at line 92 of file imu.c.
IMU_BODY_TO_IMU_PHI
#define IMU_BODY_TO_IMU_PHI 0
Default body to imu is 0 (radians)
Definition at line 154 of file imu.c.
IMU_BODY_TO_IMU_PSI
#define IMU_BODY_TO_IMU_PSI 0
Definition at line 156 of file imu.c.
IMU_BODY_TO_IMU_THETA
#define IMU_BODY_TO_IMU_THETA 0
Definition at line 155 of file imu.c.
IMU_GYRO_ABI_SEND_ID
#define IMU_GYRO_ABI_SEND_ID ABI_BROADCAST
Which gyro measurements to send over telemetry/logging.
Definition at line 164 of file imu.c.
IMU_GYRO_CALIB
#define IMU_GYRO_CALIB {}
Default gyro calibration is for single IMU with old format.
Definition at line 74 of file imu.c.
IMU_GYRO_P_SIGN
#define IMU_GYRO_P_SIGN 1
By default gyro signs are positive for single IMU with old format or defaults.
Definition at line 47 of file imu.c.
IMU_GYRO_Q_SIGN
#define IMU_GYRO_Q_SIGN 1
Definition at line 50 of file imu.c.
IMU_GYRO_R_SIGN
#define IMU_GYRO_R_SIGN 1
Definition at line 53 of file imu.c.
IMU_INTEGRATION
#define IMU_INTEGRATION false
By default disable IMU integration calculations.
Definition at line 39 of file imu.c.
IMU_LOG_HIGHSPEED_DEVICE
#define IMU_LOG_HIGHSPEED_DEVICE flightrecorder_sdlog
By default log highspeed on the flightrecorder.
Definition at line 182 of file imu.c.
IMU_MAG_ABI_SEND_ID
#define IMU_MAG_ABI_SEND_ID ABI_BROADCAST
Which mag measurements to send over telemetry/logging.
Definition at line 176 of file imu.c.
IMU_MAG_CALIB
#define IMU_MAG_CALIB {}
Default mag calibration is for single IMU with old format.
Definition at line 148 of file imu.c.
IMU_MAG_X_SIGN
#define IMU_MAG_X_SIGN 1
By default mag signs are positive for single IMU with old format and defaults.
Definition at line 121 of file imu.c.
IMU_MAG_Y_SIGN
#define IMU_MAG_Y_SIGN 1
Definition at line 124 of file imu.c.
IMU_MAG_Z_SIGN
#define IMU_MAG_Z_SIGN 1
Definition at line 127 of file imu.c.
Function Documentation
imu_accel_raw_cb()
static void imu_accel_raw_cb (uint8_t sender_id, uint32_t stamp, struct Int32Vect3 * data, uint8_t samples, float rate, float temp) static
Definition at line 790 of file imu.c.
References ACCEL_FLOAT_OF_BFP, ACCELS_FLOAT_OF_BFP, imu_accel_t::body_to_sensor, imu_accel_t::calibrated, imu_calib_t::filter, imu_accel_t::filter, float_rmat_transp_vmult(), float_rmat_vmult(), foo, imu_get_accel(), IMU_LOG_HIGHSPEED_DEVICE, int32_rmat_transp_vmult(), imu_accel_t::last_stamp, imu_accel_t::neutral, pprzlog_tp, RMAT_FLOAT_OF_BFP, imu_accel_t::scale_f, imu_accel_t::scaled, imu_accel_t::temperature, imu_accel_t::unscaled, update_butterworth_2_low_pass(), VECT3_COPY, FloatVect3::x, Int32Vect3::x, FloatVect3::y, Int32Vect3::y, FloatVect3::z, and Int32Vect3::z.
Referenced by imu_init().
imu_get_accel()
struct imu_accel_t * imu_get_accel (uint8_t sender_id, bool create)
Find or create the accel in the imu structure.
Parameters
sender_id The ABI sender id to search for
create Create a new index if not found
Returns
struct imu_accel_t* The accel structure if found/created else NULL
Definition at line 944 of file imu.c.
References ABI_BROADCAST, ABI_DISABLE, imu_accel_t::abi_id, Imu::accels, foo, imu, and IMU_MAX_SENSORS.
Referenced by ahrs_aligner_run(), high_speed_logger_spi_link_periodic(), imu_accel_raw_cb(), imu_quality_assessment_periodic(), and imu_set_defaults_accel().
imu_get_gyro()
struct imu_gyro_t * imu_get_gyro (uint8_t sender_id, bool create)
Find or create the gyro in the imu structure.
Parameters
sender_id The ABI sender id to search for
create Create a new index if not found
Returns
struct imu_gyro_t* The gyro structure if found/created else NULL
Definition at line 921 of file imu.c.
References ABI_BROADCAST, ABI_DISABLE, imu_gyro_t::abi_id, foo, Imu::gyros, imu, and IMU_MAX_SENSORS.
Referenced by ahrs_aligner_run(), high_speed_logger_spi_link_periodic(), imu_gyro_raw_cb(), imu_set_defaults_gyro(), and send_aligner().
imu_get_mag()
struct imu_mag_t * imu_get_mag (uint8_t sender_id, bool create)
Find or create the mag in the imu structure.
Parameters
sender_id The ABI sender id to search for
create Create a new index if not found
Returns
struct imu_mag_t* The mag structure if found/created else NULL
Definition at line 968 of file imu.c.
References ABI_BROADCAST, ABI_DISABLE, imu_mag_t::abi_id, foo, imu, IMU_MAX_SENSORS, and Imu::mags.
Referenced by ahrs_aligner_run(), high_speed_logger_spi_link_periodic(), imu_mag_raw_cb(), and imu_set_defaults_mag().
imu_gyro_raw_cb()
static void imu_gyro_raw_cb (uint8_t sender_id, uint32_t stamp, struct Int32Rates * data, uint8_t samples, float rate, float temp) static
Definition at line 695 of file imu.c.
References imu_gyro_t::body_to_sensor, imu_gyro_t::calibrated, imu_calib_t::filter, imu_gyro_t::filter, float_rmat_ratemult(), float_rmat_transp_ratemult(), foo, imu_get_gyro(), IMU_LOG_HIGHSPEED_DEVICE, int32_rmat_transp_ratemult(), imu_gyro_t::last_stamp, imu_gyro_t::neutral, FloatRates::p, Int32Rates::p, p, pprzlog_tp, FloatRates::q, Int32Rates::q, FloatRates::r, Int32Rates::r, RATE_FLOAT_OF_BFP, RATES_COPY, RATES_FLOAT_OF_BFP, RMAT_FLOAT_OF_BFP, imu_gyro_t::scale_f, imu_gyro_t::scaled, imu_gyro_t::temperature, imu_gyro_t::unscaled, and update_butterworth_2_low_pass().
Referenced by imu_init().
imu_init()
void imu_init (void)
External functions.
Definition at line 439 of file imu.c.
References ABI_BROADCAST, ABI_DISABLE, imu_gyro_t::abi_id, imu_accel_t::abi_id, imu_mag_t::abi_id, Imu::accel_abi_send_id, Imu::accels, Imu::body_to_imu, imu_gyro_t::body_to_sensor, imu_accel_t::body_to_sensor, imu_mag_t::body_to_sensor, imu_gyro_t::calibrated, imu_accel_t::calibrated, imu_mag_t::calibrated, imu_calib_t::current, imu_mag_t::current_scale, DefaultPeriodic, imu_calib_t::filter, imu_gyro_t::filter, imu_accel_t::filter, imu_gyro_t::filter_freq, imu_accel_t::filter_freq, imu_gyro_t::filter_sample_freq, imu_accel_t::filter_sample_freq, foo, Imu::gyro_abi_send_id, Imu::gyros, imu, IMU_ACCEL_ABI_SEND_ID, IMU_ACCEL_CALIB, imu_accel_raw_cb(), imu_accel_raw_ev, IMU_ACCEL_X_SIGN, IMU_ACCEL_Y_SIGN, IMU_ACCEL_Z_SIGN, IMU_BODY_TO_IMU_PHI, IMU_BODY_TO_IMU_PSI, IMU_BODY_TO_IMU_THETA, IMU_GYRO_ABI_SEND_ID, IMU_GYRO_CALIB, IMU_GYRO_P_SIGN, IMU_GYRO_Q_SIGN, IMU_GYRO_R_SIGN, imu_gyro_raw_cb(), imu_gyro_raw_ev, IMU_MAG_ABI_SEND_ID, IMU_MAG_CALIB, imu_mag_raw_cb(), imu_mag_raw_ev, IMU_MAG_X_SIGN, IMU_MAG_Y_SIGN, IMU_MAG_Z_SIGN, IMU_MAX_SENSORS, init_butterworth_2_low_pass(), Imu::initialized, int32_rmat_comp(), int32_rmat_identity(), INT_RATES_ZERO, INT_VECT3_ZERO, imu_gyro_t::last_stamp, imu_accel_t::last_stamp, Imu::mag_abi_send_id, mag_calib, Imu::mags, imu_calib_t::neutral, imu_gyro_t::neutral, imu_accel_t::neutral, imu_mag_t::neutral, orientationGetRMat_i(), orientationSetEulers_f(), FloatRates::p, Int32Rates::p, FloatRates::q, Int32Rates::q, FloatRates::r, Int32Rates::r, RATES_ASSIGN, register_periodic_telemetry(), RMAT_COPY, imu_calib_t::rotation, imu_calib_t::scale, imu_gyro_t::scale, imu_accel_t::scale, imu_mag_t::scale, imu_calib_t::scale_f, imu_gyro_t::scale_f, imu_accel_t::scale_f, imu_mag_t::scale_f, send_accel(), send_accel_raw(), send_accel_scaled(), send_gyro(), send_gyro_raw(), send_gyro_scaled(), send_mag(), send_mag_current(), send_mag_raw(), send_mag_scaled(), shell_add_entry(), VECT3_ASSIGN, FloatVect3::x, Int32Vect3::x, FloatVect3::y, Int32Vect3::y, FloatVect3::z, and Int32Vect3::z.
imu_mag_raw_cb()
static void imu_mag_raw_cb (uint8_t sender_id, uint32_t stamp, struct Int32Vect3 * data) static
Definition at line 886 of file imu.c.
References imu_mag_t::body_to_sensor, Electrical::current, imu_mag_t::current_scale, electrical, foo, imu_get_mag(), int32_rmat_transp_vmult(), imu_mag_t::neutral, imu_mag_t::scale_f, imu_mag_t::scaled, imu_mag_t::unscaled, VECT3_COPY, FloatVect3::x, Int32Vect3::x, FloatVect3::y, Int32Vect3::y, FloatVect3::z, and Int32Vect3::z.
Referenced by imu_init().
imu_set_body_to_imu_eulers()
static void imu_set_body_to_imu_eulers (struct FloatEulers * body_to_imu_eulers) static
Set the body to IMU rotation in eulers This will update all the sensor values.
Parameters
body_to_imu_eulers 321 Euler angles in radians
Definition at line 990 of file imu.c.
References Imu::accels, Imu::body_to_imu, imu_gyro_t::body_to_sensor, imu_accel_t::body_to_sensor, imu_mag_t::body_to_sensor, EULERS_BFP_OF_REAL, foo, Imu::gyros, imu, IMU_MAX_SENSORS, int32_rmat_comp(), int32_rmat_comp_inv(), int32_rmat_of_eulers, Imu::mags, orientationGetRMat_i(), and orientationSetEulers_f().
Referenced by imu_SetBodyToImuCurrent(), imu_SetBodyToImuPhi(), imu_SetBodyToImuPsi(), and imu_SetBodyToImuTheta().
imu_set_defaults_accel()
void imu_set_defaults_accel (uint8_t abi_id, const struct Int32RMat * imu_to_sensor, const struct Int32Vect3 * neutral, const struct FloatVect3 * scale_f)
Set the defaults for a accel sensor WARNING: Should be called before sensor is publishing messages to ensure correct values.
Parameters
abi_id The ABI sender id to set the defaults for
imu_to_sensor Imu to sensor rotation matrix
neutral Neutral values
scale_f Scale values
Definition at line 645 of file imu.c.
References imu_accel_t::abi_id, Imu::body_to_imu, imu_accel_t::body_to_sensor, imu_accel_t::calibrated, foo, imu, IMU_ACCEL_X_SIGN, IMU_ACCEL_Y_SIGN, IMU_ACCEL_Z_SIGN, imu_get_accel(), int32_rmat_comp(), imu_calib_t::neutral, imu_accel_t::neutral, orientationGetRMat_i(), RMAT_COPY, imu_calib_t::rotation, imu_calib_t::scale_f, imu_accel_t::scale_f, VECT3_ASSIGN, VECT3_COPY, FloatVect3::x, FloatVect3::y, and FloatVect3::z.
Referenced by imu_apogee_init(), imu_aspirin2_init(), imu_aspirin_i2c_init(), imu_aspirin_init(), imu_bebop_init(), imu_bmi088_init(), imu_cube_init(), imu_disco_init(), imu_mpu9250_init(), imu_mpu_hmc_init(), imu_mpu_i2c_init(), imu_mpu_spi_init(), imu_nps_init(), imu_pixhawk6x_init(), imu_px4_init(), imu_px4fmu_init(), invensense2_fix_config(), invensense3_456_set_scalings(), invensense3_fix_config(), navdata_init(), and sensors_hitl_init().
imu_set_defaults_gyro()
void imu_set_defaults_gyro (uint8_t abi_id, const struct Int32RMat * imu_to_sensor, const struct Int32Rates * neutral, const struct FloatRates * scale_f)
Set the defaults for a gyro sensor WARNING: Should be called before sensor is publishing messages to ensure correct values.
Parameters
abi_id The ABI sender id to set the defaults for
imu_to_sensor Imu to sensor rotation matrix
neutral Neutral values
scale_f Scale values
Definition at line 616 of file imu.c.
References imu_gyro_t::abi_id, Imu::body_to_imu, imu_gyro_t::body_to_sensor, imu_gyro_t::calibrated, foo, imu, imu_get_gyro(), IMU_GYRO_P_SIGN, IMU_GYRO_Q_SIGN, IMU_GYRO_R_SIGN, int32_rmat_comp(), imu_calib_t::neutral, imu_gyro_t::neutral, orientationGetRMat_i(), FloatRates::p, FloatRates::q, FloatRates::r, RATES_ASSIGN, RATES_COPY, RMAT_COPY, imu_calib_t::rotation, imu_calib_t::scale_f, and imu_gyro_t::scale_f.
Referenced by imu_apogee_init(), imu_aspirin2_init(), imu_aspirin_i2c_init(), imu_aspirin_init(), imu_bebop_init(), imu_bmi088_init(), imu_cube_init(), imu_disco_init(), imu_mpu9250_init(), imu_mpu_hmc_init(), imu_mpu_i2c_init(), imu_mpu_spi_init(), imu_nps_init(), imu_pixhawk6x_init(), imu_px4_init(), imu_px4fmu_init(), invensense2_fix_config(), invensense3_456_set_scalings(), invensense3_fix_config(), navdata_init(), and sensors_hitl_init().
imu_set_defaults_mag()
void imu_set_defaults_mag (uint8_t abi_id, const struct Int32RMat * imu_to_sensor, const struct Int32Vect3 * neutral, const struct FloatVect3 * scale_f)
Set the defaults for a mag sensor WARNING: Should be called before sensor is publishing messages to ensure correct values.
Parameters
abi_id The ABI sender id to set the defaults for
imu_to_sensor Imu to sensor rotation matrix
neutral Neutral values
scale_f Scale values
Definition at line 674 of file imu.c.
References imu_mag_t::abi_id, Imu::body_to_imu, imu_mag_t::body_to_sensor, imu_mag_t::calibrated, foo, imu, imu_get_mag(), IMU_MAG_X_SIGN, IMU_MAG_Y_SIGN, IMU_MAG_Z_SIGN, int32_rmat_comp(), imu_calib_t::neutral, imu_mag_t::neutral, orientationGetRMat_i(), RMAT_COPY, imu_calib_t::rotation, imu_calib_t::scale_f, imu_mag_t::scale_f, VECT3_ASSIGN, VECT3_COPY, FloatVect3::x, FloatVect3::y, and FloatVect3::z.
Referenced by imu_nps_init(), mag_ist8310_module_init(), mag_lis3mdl_module_init(), mag_uavcan_init(), navdata_init(), and sensors_hitl_init().
imu_SetBodyToImuCurrent()
void imu_SetBodyToImuCurrent (float set)
Definition at line 1043 of file imu.c.
References Imu::b2i_set_current, Imu::body_to_imu, foo, imu, IMU_BODY_TO_IMU_PHI, IMU_BODY_TO_IMU_PSI, IMU_BODY_TO_IMU_THETA, imu_set_body_to_imu_eulers(), orientationGetEulers_f(), FloatEulers::phi, stateGetNedToBodyEulers_f(), stateIsAttitudeValid(), and FloatEulers::theta.
imu_SetBodyToImuPhi()
void imu_SetBodyToImuPhi (float phi)
Definition at line 1019 of file imu.c.
References Imu::body_to_imu, foo, imu, imu_set_body_to_imu_eulers(), orientationGetEulers_f(), and FloatEulers::phi.
imu_SetBodyToImuPsi()
void imu_SetBodyToImuPsi (float psi)
Definition at line 1035 of file imu.c.
References Imu::body_to_imu, foo, imu, imu_set_body_to_imu_eulers(), orientationGetEulers_f(), and FloatEulers::psi.
imu_SetBodyToImuTheta()
void imu_SetBodyToImuTheta (float theta)
Definition at line 1027 of file imu.c.
References Imu::body_to_imu, foo, imu, imu_set_body_to_imu_eulers(), orientationGetEulers_f(), and FloatEulers::theta.
send_accel()
static void send_accel (struct transport_tx * trans, struct link_device * dev) static
Definition at line 217 of file imu.c.
References ABI_BROADCAST, ABI_DISABLE, imu_accel_t::abi_id, Imu::accel_abi_send_id, accel_float, Imu::accels, ACCELS_FLOAT_OF_BFP, dev, foo, imu, IMU_MAX_SENSORS, imu_accel_t::scaled, FloatVect3::x, FloatVect3::y, and FloatVect3::z.
Referenced by imu_init().
send_accel_raw()
static void send_accel_raw (struct transport_tx * trans, struct link_device * dev) static
Definition at line 189 of file imu.c.
References ABI_BROADCAST, ABI_DISABLE, imu_accel_t::abi_id, Imu::accel_abi_send_id, Imu::accels, dev, foo, imu, IMU_MAX_SENSORS, imu_accel_t::temperature, imu_accel_t::unscaled, Int32Vect3::x, Int32Vect3::y, and Int32Vect3::z.
Referenced by imu_init().
send_accel_scaled()
static void send_accel_scaled (struct transport_tx * trans, struct link_device * dev) static
Definition at line 203 of file imu.c.
References ABI_BROADCAST, ABI_DISABLE, imu_accel_t::abi_id, Imu::accel_abi_send_id, Imu::accels, dev, foo, imu, IMU_MAX_SENSORS, imu_accel_t::scaled, Int32Vect3::x, Int32Vect3::y, and Int32Vect3::z.
Referenced by imu_init().
send_gyro()
static void send_gyro (struct transport_tx * trans, struct link_device * dev) static
Definition at line 261 of file imu.c.
References ABI_BROADCAST, ABI_DISABLE, imu_gyro_t::abi_id, dev, foo, Imu::gyro_abi_send_id, Imu::gyros, imu, IMU_MAX_SENSORS, RATES_FLOAT_OF_BFP, and imu_gyro_t::scaled.
Referenced by imu_init().
send_gyro_raw()
static void send_gyro_raw (struct transport_tx * trans, struct link_device * dev) static
Definition at line 233 of file imu.c.
References ABI_BROADCAST, ABI_DISABLE, imu_gyro_t::abi_id, dev, foo, Imu::gyro_abi_send_id, Imu::gyros, imu, IMU_MAX_SENSORS, Int32Rates::p, Int32Rates::q, Int32Rates::r, imu_gyro_t::temperature, and imu_gyro_t::unscaled.
Referenced by imu_init().
send_gyro_scaled()
static void send_gyro_scaled (struct transport_tx * trans, struct link_device * dev) static
Definition at line 247 of file imu.c.
References ABI_BROADCAST, ABI_DISABLE, imu_gyro_t::abi_id, dev, foo, Imu::gyro_abi_send_id, Imu::gyros, imu, IMU_MAX_SENSORS, Int32Rates::p, Int32Rates::q, Int32Rates::r, and imu_gyro_t::scaled.
Referenced by imu_init().
send_mag()
static void send_mag (struct transport_tx * trans, struct link_device * dev) static
Definition at line 305 of file imu.c.
References ABI_BROADCAST, ABI_DISABLE, imu_mag_t::abi_id, dev, foo, imu, IMU_MAX_SENSORS, Imu::mag_abi_send_id, mag_float, Imu::mags, MAGS_FLOAT_OF_BFP, imu_mag_t::scaled, FloatVect3::x, FloatVect3::y, and FloatVect3::z.
Referenced by imu_init().
send_mag_current()
static void send_mag_current (struct transport_tx * trans, struct link_device * dev) static
Definition at line 321 of file imu.c.
References ABI_BROADCAST, ABI_DISABLE, imu_mag_t::abi_id, Electrical::current, dev, electrical, foo, imu, IMU_MAX_SENSORS, Imu::mag_abi_send_id, Imu::mags, imu_mag_t::unscaled, Int32Vect3::x, Int32Vect3::y, and Int32Vect3::z.
Referenced by imu_init().
send_mag_raw()
static void send_mag_raw (struct transport_tx * trans, struct link_device * dev) static
Definition at line 277 of file imu.c.
References ABI_BROADCAST, ABI_DISABLE, imu_mag_t::abi_id, dev, foo, imu, IMU_MAX_SENSORS, Imu::mag_abi_send_id, Imu::mags, imu_mag_t::unscaled, Int32Vect3::x, Int32Vect3::y, and Int32Vect3::z.
Referenced by imu_init().
send_mag_scaled()
static void send_mag_scaled (struct transport_tx * trans, struct link_device * dev) static
Definition at line 291 of file imu.c.
References ABI_BROADCAST, ABI_DISABLE, imu_mag_t::abi_id, dev, foo, imu, IMU_MAX_SENSORS, Imu::mag_abi_send_id, Imu::mags, imu_mag_t::scaled, Int32Vect3::x, Int32Vect3::y, and Int32Vect3::z.
Referenced by imu_init().
Variable Documentation
imu
struct Imu imu = {0}
global IMU state
Definition at line 432 of file imu.c.
Referenced by direct_memory_logger_periodic(), imu_get_accel(), imu_get_gyro(), imu_get_mag(), imu_init(), imu_set_body_to_imu_eulers(), imu_set_defaults_accel(), imu_set_defaults_gyro(), imu_set_defaults_mag(), imu_SetBodyToImuCurrent(), imu_SetBodyToImuPhi(), imu_SetBodyToImuPsi(), imu_SetBodyToImuTheta(), jevois_mavlink_filter_init(), jevois_mavlink_filter_periodic(), logger_uart_periodic(), mag_calib_ukf_run(), send_accel(), send_accel_raw(), send_accel_scaled(), send_gyro(), send_gyro_raw(), send_gyro_scaled(), send_mag(), send_mag_current(), send_mag_raw(), and send_mag_scaled().
imu_accel_raw_ev
abi_event imu_accel_raw_ev static
Definition at line 433 of file imu.c.
Referenced by imu_init().
imu_gyro_raw_ev
abi_event imu_gyro_raw_ev static
Definition at line 433 of file imu.c.
Referenced by imu_init().
imu_mag_raw_ev
abi_event imu_mag_raw_ev static
Definition at line 433 of file imu.c.
Referenced by imu_init().