Paparazzi UAS: sw/airborne/modules/imu/imu_bebop.c File Reference
imu_bebop.c File Reference
Driver for the Bebop (2) magnetometer, accelerometer and gyroscope.
#include "modules/imu/imu_bebop.h"
#include "modules/imu/imu.h"
#include "modules/core/abi.h"
#include "mcu_periph/i2c.h"
#include "generated/modules.h"
Macros
#define BEBOP_MAG_I2C_DEV i2c1
#define BEBOP_MPU_I2C_DEV i2c2
Functions
void imu_bebop_init (void)
Navstik IMU initializtion of the MPU-60x0 and HMC58xx.
void imu_bebop_periodic (void)
Handle all the periodic tasks of the Navstik IMU components.
void imu_bebop_event (void)
Handle all the events of the Navstik IMU components.
Variables
struct OrientationReps imu_to_mag_bebop
IMU to magneto rotation.
struct ImuBebop imu_bebop
Basic Navstik IMU data.
Detailed Description
Driver for the Bebop (2) magnetometer, accelerometer and gyroscope.
Definition in file imu_bebop.c.
Macro Definition Documentation
BEBOP_MAG_I2C_DEV
#define BEBOP_MAG_I2C_DEV i2c1
Definition at line 36 of file imu_bebop.c.
BEBOP_MPU_I2C_DEV
#define BEBOP_MPU_I2C_DEV i2c2
Definition at line 41 of file imu_bebop.c.
Function Documentation
imu_bebop_event()
void imu_bebop_event (void)
Handle all the events of the Navstik IMU components.
When there is data available convert it to the correct axis and save it in the imu structure.
Definition at line 118 of file imu_bebop.c.
References ImuBebop::ak, ak8963_event(), Ak8963::data, Mpu60x0_I2c::data_accel, Ak8963::data_available, Mpu60x0_I2c::data_available, Mpu60x0_I2c::data_rates, foo, get_sys_time_usec(), imu_bebop, IMU_BOARD_ID, imu_to_mag_bebop, int32_rmat_vmult(), ImuBebop::mpu, mpu60x0_i2c_event(), orientationGetRMat_i(), RATES_ASSIGN, Mpu60x0_I2c::temp, and VECT3_ASSIGN.
imu_bebop_init()
void imu_bebop_init (void)
Navstik IMU initializtion of the MPU-60x0 and HMC58xx.
Definition at line 76 of file imu_bebop.c.
References Mpu60x0Config::accel_range, ImuBebop::ak, AK8963_ADDR, ak8963_init(), BEBOP_ACCEL_RANGE, BEBOP_GYRO_RANGE, BEBOP_MAG_I2C_DEV, BEBOP_MPU_I2C_DEV, Mpu60x0_I2c::config, Mpu60x0Config::dlpf_cfg, foo, Mpu60x0Config::gyro_range, imu_bebop, IMU_BOARD_ID, imu_set_defaults_accel(), imu_set_defaults_gyro(), imu_to_mag_bebop, ImuBebop::mpu, MPU60X0_ACCEL_SENS_F, MPU60X0_ADDR, MPU60X0_GYRO_SENS_F, mpu60x0_i2c_init(), orientationSetEulers_f(), and Mpu60x0Config::smplrt_div.
imu_bebop_periodic()
void imu_bebop_periodic (void)
Handle all the periodic tasks of the Navstik IMU components.
Read the MPU60x0 every periodic call and the HMC58XX every 10th call.
Definition at line 105 of file imu_bebop.c.
References ImuBebop::ak, ak8963_periodic(), imu_bebop, ImuBebop::mpu, and mpu60x0_i2c_periodic().
Variable Documentation
imu_bebop
struct ImuBebop imu_bebop
Basic Navstik IMU data.
Definition at line 71 of file imu_bebop.c.
Referenced by imu_bebop_event(), imu_bebop_init(), imu_bebop_periodic(), and imu_temp_ctrl_periodic().
imu_to_mag_bebop
struct OrientationReps imu_to_mag_bebop
IMU to magneto rotation.
Definition at line 68 of file imu_bebop.c.
Referenced by imu_bebop_event(), and imu_bebop_init().