Paparazzi UAS: sw/airborne/boards/apogee/imu_apogee.h File Reference
imu_apogee.h File Reference
Driver for the IMU on the Apogee board.
#include "std.h"
#include "generated/airframe.h"
#include "modules/imu/imu.h"
#include "peripherals/mpu60x0_i2c.h"
Data Structures
struct ImuApogee
Macros
#define APOGEE_GYRO_RANGE MPU60X0_GYRO_RANGE_1000
#define APOGEE_ACCEL_RANGE MPU60X0_ACCEL_RANGE_8G
Functions
void imu_apogee_init (void)
void imu_apogee_periodic (void)
void imu_apogee_event (void)
Variables
struct ImuApogee imu_apogee
Detailed Description
Driver for the IMU on the Apogee board.
Invensense MPU-6050
Definition in file imu_apogee.h.
Data Structure Documentation
ImuApogee
struct ImuApogee
Definition at line 50 of file imu_apogee.h.
Data Fields
struct Mpu60x0_I2c mpu
Macro Definition Documentation
APOGEE_ACCEL_RANGE
#define APOGEE_ACCEL_RANGE MPU60X0_ACCEL_RANGE_8G
Definition at line 47 of file imu_apogee.h.
APOGEE_GYRO_RANGE
#define APOGEE_GYRO_RANGE MPU60X0_GYRO_RANGE_1000
Definition at line 44 of file imu_apogee.h.
Function Documentation
imu_apogee_event()
void imu_apogee_event (void) extern
Definition at line 132 of file imu_apogee.c.
References ak8975_event(), Mpu60x0_I2c::data_accel, Mpu60x0_I2c::data_available, Mpu60x0_I2c::data_rates, foo, get_sys_time_usec(), imu_apogee, IMU_APOGEE_CHAN_X, IMU_APOGEE_CHAN_Y, IMU_APOGEE_CHAN_Z, IMU_BOARD_ID, ImuApogee::mpu, mpu60x0_i2c_event(), and Mpu60x0_I2c::temp.
imu_apogee_init()
void imu_apogee_init (void) extern
Definition at line 95 of file imu_apogee.c.
References Mpu60x0Config::accel_range, AK8975_I2C_SLV_ADDR, ak8975_init(), APOGEE_ACCEL_RANGE, APOGEE_GYRO_RANGE, APOGEE_LOWPASS_FILTER, APOGEE_SMPLRT_DIV, Mpu60x0_I2c::config, Mpu60x0I2cSlave::configure, configure_baro_slave(), Mpu60x0Config::dlpf_cfg, foo, Mpu60x0Config::gyro_range, Mpu60x0Config::i2c_bypass, imu_apogee, IMU_BOARD_ID, imu_set_defaults_accel(), imu_set_defaults_gyro(), ImuApogee::mpu, MPU60X0_ACCEL_SENS_F, MPU60X0_ADDR_ALT, MPU60X0_GYRO_SENS_F, mpu60x0_i2c_init(), Mpu60x0Config::nb_slaves, Mpu60x0Config::slaves, and Mpu60x0Config::smplrt_div.
imu_apogee_periodic()
void imu_apogee_periodic (void) extern
Definition at line 121 of file imu_apogee.c.
References ak8975_periodic(), foo, imu_apogee, ImuApogee::mpu, and mpu60x0_i2c_periodic().
Variable Documentation
imu_apogee
struct ImuApogee imu_apogee extern
Definition at line 86 of file imu_apogee.c.
Referenced by baro_periodic(), imu_apogee_event(), imu_apogee_init(), and imu_apogee_periodic().