Paparazzi UAS: sw/airborne/modules/imu/imu_px4fmu_v2.4.c File Reference
imu_px4fmu_v2.4.c File Reference
#include "modules/imu/imu_px4fmu_v2.4.h"
#include "modules/imu/imu.h"
#include "modules/core/abi.h"
#include "mcu_periph/spi.h"
#include "generated/modules.h"
Functions
void imu_px4_init (void)
void imu_px4_periodic (void)
void imu_px4_event (void)
Variables
struct ImuPX4 imu_px4
Function Documentation
imu_px4_event()
void imu_px4_event (void)
Definition at line 74 of file imu_px4fmu_v2.4.c.
References Lsm303d_Spi::data_accel, L3gd20_Spi::data_available, Lsm303d_Spi::data_available_acc, Lsm303d_Spi::data_available_mag, Lsm303d_Spi::data_mag, L3gd20_Spi::data_rates, FALSE, foo, get_sys_time_usec(), imu_px4, IMU_PX4_ID, ImuPX4::l3g, l3gd20_spi_event(), lsm303d_spi_event(), ImuPX4::lsm_acc, ImuPX4::lsm_mag, VECT3_ASSIGN, and VECT3_COPY.
imu_px4_init()
void imu_px4_init (void)
Definition at line 41 of file imu_px4fmu_v2.4.c.
References accel_scale_f, foo, gyro_scale_f, imu_px4, IMU_PX4_ID, imu_set_defaults_accel(), imu_set_defaults_gyro(), ImuPX4::l3g, L3GD20_SENS_2000, l3gd20_spi_init(), LSM303D_ACCEL_SENS_16G, lsm303d_spi_init(), LSM303D_TARGET_ACC, LSM303D_TARGET_MAG, ImuPX4::lsm_acc, and ImuPX4::lsm_mag.
imu_px4_periodic()
void imu_px4_periodic (void)
Definition at line 62 of file imu_px4fmu_v2.4.c.
References foo, imu_px4, ImuPX4::l3g, l3gd20_spi_periodic(), lsm303d_spi_periodic(), ImuPX4::lsm_acc, and ImuPX4::lsm_mag.
Variable Documentation
imu_px4
struct ImuPX4 imu_px4
Definition at line 39 of file imu_px4fmu_v2.4.c.
Referenced by imu_px4_event(), imu_px4_init(), and imu_px4_periodic().