Paparazzi UAS: sw/airborne/modules/imu/imu_nps.c File Reference
imu_nps.c File Reference
#include "modules/imu/imu_nps.h"
#include "modules/imu/imu.h"
#include "modules/core/abi.h"
#include "generated/airframe.h"
#include "nps_sensors.h"
Functions
void imu_nps_init (void)
void imu_feed_gyro_accel (void)
void imu_feed_mag (void)
void imu_nps_event (void)
Variables
struct ImuNps imu_nps
Function Documentation
imu_feed_gyro_accel()
void imu_feed_gyro_accel (void)
Definition at line 50 of file imu_nps.c.
References ImuNps::accel, ImuNps::accel_available, ImuNps::gyro, ImuNps::gyro_available, imu_nps, RATES_ASSIGN, sensors, and VECT3_COPY.
Referenced by nps_autopilot_run_step().
imu_feed_mag()
void imu_feed_mag (void)
Definition at line 61 of file imu_nps.c.
References imu_nps, ImuNps::mag, ImuNps::mag_available, sensors, and VECT3_COPY.
Referenced by nps_autopilot_run_step().
imu_nps_event()
void imu_nps_event (void)
Definition at line 68 of file imu_nps.c.
References ImuNps::accel, ImuNps::accel_available, foo, get_sys_time_usec(), ImuNps::gyro, ImuNps::gyro_available, imu_nps, IMU_NPS_ID, ImuNps::mag, and ImuNps::mag_available.
imu_nps_init()
void imu_nps_init (void)
Definition at line 30 of file imu_nps.c.
References ImuNps::accel_available, ACCEL_FLOAT_OF_BFP, accel_neutral, accel_scale_f, foo, ImuNps::gyro_available, gyro_scale_f, imu_nps, IMU_NPS_ID, imu_set_defaults_accel(), imu_set_defaults_gyro(), imu_set_defaults_mag(), ImuNps::mag_available, MAG_FLOAT_OF_BFP, mag_scale_f, and RATE_FLOAT_OF_BFP.
Variable Documentation
imu_nps
struct ImuNps imu_nps
Definition at line 28 of file imu_nps.c.
Referenced by imu_feed_gyro_accel(), imu_feed_mag(), imu_nps_event(), and imu_nps_init().