Paparazzi UAS: sw/airborne/modules/imu/imu.h File Reference
imu.h File Reference
Inertial Measurement Unit interface.
#include "math/pprz_algebra_int.h"
#include "math/pprz_algebra_float.h"
#include "math/pprz_orientation_conversion.h"
#include "filters/low_pass_filter.h"
#include "generated/airframe.h"
Data Structures
struct imu_calib_t
struct imu_gyro_t
struct imu_accel_t
struct imu_mag_t
struct Imu
abstract IMU interface providing fixed point interface
Macros
#define IMU_MAX_SENSORS 4
Functions
void imu_init (void)
External functions.
void imu_set_defaults_gyro (uint8_t abi_id, const struct Int32RMat *imu_to_sensor, const struct Int32Rates *neutral, const struct FloatRates *scale_f)
Set the defaults for a gyro sensor WARNING: Should be called before sensor is publishing messages to ensure correct values.
void imu_set_defaults_accel (uint8_t abi_id, const struct Int32RMat *imu_to_sensor, const struct Int32Vect3 *neutral, const struct FloatVect3 *scale_f)
Set the defaults for a accel sensor WARNING: Should be called before sensor is publishing messages to ensure correct values.
void imu_set_defaults_mag (uint8_t abi_id, const struct Int32RMat *imu_to_sensor, const struct Int32Vect3 *neutral, const struct FloatVect3 *scale_f)
Set the defaults for a mag sensor WARNING: Should be called before sensor is publishing messages to ensure correct values.
struct imu_gyro_t * imu_get_gyro (uint8_t sender_id, bool create)
Find or create the gyro in the imu structure.
struct imu_accel_t * imu_get_accel (uint8_t sender_id, bool create)
Find or create the accel in the imu structure.
struct imu_mag_t * imu_get_mag (uint8_t sender_id, bool create)
Find or create the mag in the imu structure.
void imu_SetBodyToImuPhi (float phi)
void imu_SetBodyToImuTheta (float theta)
void imu_SetBodyToImuPsi (float psi)
void imu_SetBodyToImuCurrent (float set)
void imu_ResetBodyToImu (float reset)
Variables
struct Imu imu
global IMU state
Detailed Description
Inertial Measurement Unit interface.
Definition in file imu.h.
Data Structure Documentation
imu_calib_t
struct imu_calib_t
Definition at line 41 of file imu.h.
Data Fields
bool current: 1 Current calibrated.
bool filter: 1 Enable the lowpass filter.
bool neutral: 1 Neutral values calibrated.
bool rotation: 1 Rotation calibrated.
bool scale: 1 Scale calibrated.
bool scale_f: 1 Scale calibrated with floating point.
imu_gyro_t
struct imu_gyro_t
Definition at line 50 of file imu.h.
Data Fields
uint8_t abi_id ABI sensor ID.
struct Int32RMat body_to_sensor Rotation from body to sensor frame (body to imu combined with imu to sensor)
struct imu_calib_t calibrated Calibration bitmask.
Butterworth2LowPass filter[3] Lowpass filter optional.
float filter_freq Filter frequency.
float filter_sample_freq Lowpass filter sample frequency (Hz)
uint32_t last_stamp Last measurement timestamp for integration.
struct Int32Rates neutral Neutral values, compensation on unscaled->scaled.
struct Int32Rates scale[2] Scaling, first is numerator and second denominator.
struct FloatRates scale_f Scaling.
struct Int32Rates scaled Last scaled values in body frame.
float temperature Temperature in degrees celcius.
struct Int32Rates unscaled Last unscaled values in sensor frame.
imu_accel_t
struct imu_accel_t
Definition at line 66 of file imu.h.
Data Fields
uint8_t abi_id ABI sensor ID.
struct Int32RMat body_to_sensor Rotation from body to sensor frame (body to imu combined with imu to sensor)
struct imu_calib_t calibrated Calibration bitmask.
Butterworth2LowPass filter[3] Lowpass filter optional.
float filter_freq Lowpass filter frequency (Hz)
float filter_sample_freq Lowpass filter sample frequency (Hz)
uint32_t last_stamp Last measurement timestamp for integration.
struct Int32Vect3 neutral Neutral values, compensation on unscaled->scaled.
struct Int32Vect3 scale[2] Scaling, first is numerator and second denominator.
struct FloatVect3 scale_f Scaling.
struct Int32Vect3 scaled Last scaled values in body frame.
float temperature Temperature in degrees celcius.
struct Int32Vect3 unscaled Last unscaled values in sensor frame.
imu_mag_t
struct imu_mag_t
Definition at line 82 of file imu.h.
Data Fields
uint8_t abi_id ABI sensor ID.
struct Int32RMat body_to_sensor Rotation from body to sensor frame (body to imu combined with imu to sensor)
struct imu_calib_t calibrated Calibration bitmask.
struct FloatVect3 current_scale Current scaling multiplying.
struct Int32Vect3 neutral Neutral values, compensation on unscaled->scaled.
struct Int32Vect3 scale[2] Scaling, first is numerator and second denominator.
struct FloatVect3 scale_f Scaling.
struct Int32Vect3 scaled Last scaled values in body frame.
struct Int32Vect3 unscaled Last unscaled values in sensor frame.
Imu
struct Imu
abstract IMU interface providing fixed point interface
Definition at line 96 of file imu.h.
Data Fields
uint8_t accel_abi_send_id Filter out and send only a specific ABI id in telemetry for the accelerometer.
struct imu_accel_t accels[IMU_MAX_SENSORS] The accelerometer sensors.
bool b2i_set_current flag for adjusting body_to_imu via settings.
if FALSE, reset to airframe values, if TRUE set current roll/pitch
struct OrientationReps body_to_imu Rotation from body to imu (all sensors) frame.
uint8_t gyro_abi_send_id Filter out and send only a specific ABI id in telemetry for the gyro.
struct imu_gyro_t gyros[IMU_MAX_SENSORS] The gyro sensors.
bool initialized Check if the IMU is initialized.
uint8_t mag_abi_send_id Filter out and send only a specific ABI id in telemetry for the magnetometer.
struct imu_mag_t mags[IMU_MAX_SENSORS] The magnetometer sensors.
Macro Definition Documentation
IMU_MAX_SENSORS
#define IMU_MAX_SENSORS 4
Definition at line 38 of file imu.h.
Function Documentation
imu_get_accel()
struct imu_accel_t * imu_get_accel (uint8_t sender_id, bool create) extern
Find or create the accel in the imu structure.
Parameters
sender_id The ABI sender id to search for
create Create a new index if not found
Returns
struct imu_accel_t* The accel structure if found/created else NULL
Definition at line 944 of file imu.c.
References ABI_BROADCAST, ABI_DISABLE, imu_accel_t::abi_id, Imu::accels, foo, imu, and IMU_MAX_SENSORS.
Referenced by ahrs_aligner_run(), high_speed_logger_spi_link_periodic(), imu_accel_raw_cb(), imu_quality_assessment_periodic(), and imu_set_defaults_accel().
imu_get_gyro()
struct imu_gyro_t * imu_get_gyro (uint8_t sender_id, bool create) extern
Find or create the gyro in the imu structure.
Parameters
sender_id The ABI sender id to search for
create Create a new index if not found
Returns
struct imu_gyro_t* The gyro structure if found/created else NULL
Definition at line 921 of file imu.c.
References ABI_BROADCAST, ABI_DISABLE, imu_gyro_t::abi_id, foo, Imu::gyros, imu, and IMU_MAX_SENSORS.
Referenced by ahrs_aligner_run(), high_speed_logger_spi_link_periodic(), imu_gyro_raw_cb(), imu_set_defaults_gyro(), and send_aligner().
imu_get_mag()
struct imu_mag_t * imu_get_mag (uint8_t sender_id, bool create) extern
Find or create the mag in the imu structure.
Parameters
sender_id The ABI sender id to search for
create Create a new index if not found
Returns
struct imu_mag_t* The mag structure if found/created else NULL
Definition at line 968 of file imu.c.
References ABI_BROADCAST, ABI_DISABLE, imu_mag_t::abi_id, foo, imu, IMU_MAX_SENSORS, and Imu::mags.
Referenced by ahrs_aligner_run(), high_speed_logger_spi_link_periodic(), imu_mag_raw_cb(), and imu_set_defaults_mag().
imu_init()
void imu_init (void) extern
External functions.
Definition at line 439 of file imu.c.
References ABI_BROADCAST, ABI_DISABLE, imu_gyro_t::abi_id, imu_accel_t::abi_id, imu_mag_t::abi_id, Imu::accel_abi_send_id, Imu::accels, Imu::body_to_imu, imu_gyro_t::body_to_sensor, imu_accel_t::body_to_sensor, imu_mag_t::body_to_sensor, imu_gyro_t::calibrated, imu_accel_t::calibrated, imu_mag_t::calibrated, imu_calib_t::current, imu_mag_t::current_scale, DefaultPeriodic, imu_calib_t::filter, imu_gyro_t::filter, imu_accel_t::filter, imu_gyro_t::filter_freq, imu_accel_t::filter_freq, imu_gyro_t::filter_sample_freq, imu_accel_t::filter_sample_freq, foo, Imu::gyro_abi_send_id, Imu::gyros, imu, IMU_ACCEL_ABI_SEND_ID, IMU_ACCEL_CALIB, imu_accel_raw_cb(), imu_accel_raw_ev, IMU_ACCEL_X_SIGN, IMU_ACCEL_Y_SIGN, IMU_ACCEL_Z_SIGN, IMU_BODY_TO_IMU_PHI, IMU_BODY_TO_IMU_PSI, IMU_BODY_TO_IMU_THETA, IMU_GYRO_ABI_SEND_ID, IMU_GYRO_CALIB, IMU_GYRO_P_SIGN, IMU_GYRO_Q_SIGN, IMU_GYRO_R_SIGN, imu_gyro_raw_cb(), imu_gyro_raw_ev, IMU_MAG_ABI_SEND_ID, IMU_MAG_CALIB, imu_mag_raw_cb(), imu_mag_raw_ev, IMU_MAG_X_SIGN, IMU_MAG_Y_SIGN, IMU_MAG_Z_SIGN, IMU_MAX_SENSORS, init_butterworth_2_low_pass(), Imu::initialized, int32_rmat_comp(), int32_rmat_identity(), INT_RATES_ZERO, INT_VECT3_ZERO, imu_gyro_t::last_stamp, imu_accel_t::last_stamp, Imu::mag_abi_send_id, mag_calib, Imu::mags, imu_calib_t::neutral, imu_gyro_t::neutral, imu_accel_t::neutral, imu_mag_t::neutral, orientationGetRMat_i(), orientationSetEulers_f(), FloatRates::p, Int32Rates::p, FloatRates::q, Int32Rates::q, FloatRates::r, Int32Rates::r, RATES_ASSIGN, register_periodic_telemetry(), RMAT_COPY, imu_calib_t::rotation, imu_calib_t::scale, imu_gyro_t::scale, imu_accel_t::scale, imu_mag_t::scale, imu_calib_t::scale_f, imu_gyro_t::scale_f, imu_accel_t::scale_f, imu_mag_t::scale_f, send_accel(), send_accel_raw(), send_accel_scaled(), send_gyro(), send_gyro_raw(), send_gyro_scaled(), send_mag(), send_mag_current(), send_mag_raw(), send_mag_scaled(), shell_add_entry(), VECT3_ASSIGN, FloatVect3::x, Int32Vect3::x, FloatVect3::y, Int32Vect3::y, FloatVect3::z, and Int32Vect3::z.
imu_ResetBodyToImu()
void imu_ResetBodyToImu (float reset) extern
imu_set_defaults_accel()
void imu_set_defaults_accel (uint8_t abi_id, const struct Int32RMat * imu_to_sensor, const struct Int32Vect3 * neutral, const struct FloatVect3 * scale_f) extern
Set the defaults for a accel sensor WARNING: Should be called before sensor is publishing messages to ensure correct values.
Parameters
abi_id The ABI sender id to set the defaults for
imu_to_sensor Imu to sensor rotation matrix
neutral Neutral values
scale_f Scale values
Definition at line 645 of file imu.c.
References imu_accel_t::abi_id, Imu::body_to_imu, imu_accel_t::body_to_sensor, imu_accel_t::calibrated, foo, imu, IMU_ACCEL_X_SIGN, IMU_ACCEL_Y_SIGN, IMU_ACCEL_Z_SIGN, imu_get_accel(), int32_rmat_comp(), imu_calib_t::neutral, imu_accel_t::neutral, orientationGetRMat_i(), RMAT_COPY, imu_calib_t::rotation, imu_calib_t::scale_f, imu_accel_t::scale_f, VECT3_ASSIGN, VECT3_COPY, FloatVect3::x, FloatVect3::y, and FloatVect3::z.
Referenced by imu_apogee_init(), imu_aspirin2_init(), imu_aspirin_i2c_init(), imu_aspirin_init(), imu_bebop_init(), imu_bmi088_init(), imu_cube_init(), imu_disco_init(), imu_mpu9250_init(), imu_mpu_hmc_init(), imu_mpu_i2c_init(), imu_mpu_spi_init(), imu_nps_init(), imu_pixhawk6x_init(), imu_px4_init(), imu_px4fmu_init(), invensense2_fix_config(), invensense3_456_set_scalings(), invensense3_fix_config(), navdata_init(), and sensors_hitl_init().
imu_set_defaults_gyro()
void imu_set_defaults_gyro (uint8_t abi_id, const struct Int32RMat * imu_to_sensor, const struct Int32Rates * neutral, const struct FloatRates * scale_f) extern
Set the defaults for a gyro sensor WARNING: Should be called before sensor is publishing messages to ensure correct values.
Parameters
abi_id The ABI sender id to set the defaults for
imu_to_sensor Imu to sensor rotation matrix
neutral Neutral values
scale_f Scale values
Definition at line 616 of file imu.c.
References imu_gyro_t::abi_id, Imu::body_to_imu, imu_gyro_t::body_to_sensor, imu_gyro_t::calibrated, foo, imu, imu_get_gyro(), IMU_GYRO_P_SIGN, IMU_GYRO_Q_SIGN, IMU_GYRO_R_SIGN, int32_rmat_comp(), imu_calib_t::neutral, imu_gyro_t::neutral, orientationGetRMat_i(), FloatRates::p, FloatRates::q, FloatRates::r, RATES_ASSIGN, RATES_COPY, RMAT_COPY, imu_calib_t::rotation, imu_calib_t::scale_f, and imu_gyro_t::scale_f.
Referenced by imu_apogee_init(), imu_aspirin2_init(), imu_aspirin_i2c_init(), imu_aspirin_init(), imu_bebop_init(), imu_bmi088_init(), imu_cube_init(), imu_disco_init(), imu_mpu9250_init(), imu_mpu_hmc_init(), imu_mpu_i2c_init(), imu_mpu_spi_init(), imu_nps_init(), imu_pixhawk6x_init(), imu_px4_init(), imu_px4fmu_init(), invensense2_fix_config(), invensense3_456_set_scalings(), invensense3_fix_config(), navdata_init(), and sensors_hitl_init().
imu_set_defaults_mag()
void imu_set_defaults_mag (uint8_t abi_id, const struct Int32RMat * imu_to_sensor, const struct Int32Vect3 * neutral, const struct FloatVect3 * scale_f) extern
Set the defaults for a mag sensor WARNING: Should be called before sensor is publishing messages to ensure correct values.
Parameters
abi_id The ABI sender id to set the defaults for
imu_to_sensor Imu to sensor rotation matrix
neutral Neutral values
scale_f Scale values
Definition at line 674 of file imu.c.
References imu_mag_t::abi_id, Imu::body_to_imu, imu_mag_t::body_to_sensor, imu_mag_t::calibrated, foo, imu, imu_get_mag(), IMU_MAG_X_SIGN, IMU_MAG_Y_SIGN, IMU_MAG_Z_SIGN, int32_rmat_comp(), imu_calib_t::neutral, imu_mag_t::neutral, orientationGetRMat_i(), RMAT_COPY, imu_calib_t::rotation, imu_calib_t::scale_f, imu_mag_t::scale_f, VECT3_ASSIGN, VECT3_COPY, FloatVect3::x, FloatVect3::y, and FloatVect3::z.
Referenced by imu_nps_init(), mag_ist8310_module_init(), mag_lis3mdl_module_init(), mag_uavcan_init(), navdata_init(), and sensors_hitl_init().
imu_SetBodyToImuCurrent()
void imu_SetBodyToImuCurrent (float set) extern
Definition at line 1043 of file imu.c.
References Imu::b2i_set_current, Imu::body_to_imu, foo, imu, IMU_BODY_TO_IMU_PHI, IMU_BODY_TO_IMU_PSI, IMU_BODY_TO_IMU_THETA, imu_set_body_to_imu_eulers(), orientationGetEulers_f(), FloatEulers::phi, stateGetNedToBodyEulers_f(), stateIsAttitudeValid(), and FloatEulers::theta.
imu_SetBodyToImuPhi()
void imu_SetBodyToImuPhi (float phi) extern
Definition at line 1019 of file imu.c.
References Imu::body_to_imu, foo, imu, imu_set_body_to_imu_eulers(), orientationGetEulers_f(), and FloatEulers::phi.
imu_SetBodyToImuPsi()
void imu_SetBodyToImuPsi (float psi) extern
Definition at line 1035 of file imu.c.
References Imu::body_to_imu, foo, imu, imu_set_body_to_imu_eulers(), orientationGetEulers_f(), and FloatEulers::psi.
imu_SetBodyToImuTheta()
void imu_SetBodyToImuTheta (float theta) extern
Definition at line 1027 of file imu.c.
References Imu::body_to_imu, foo, imu, imu_set_body_to_imu_eulers(), orientationGetEulers_f(), and FloatEulers::theta.
Variable Documentation
imu
struct Imu imu extern
global IMU state
Definition at line 432 of file imu.c.
Referenced by direct_memory_logger_periodic(), imu_get_accel(), imu_get_gyro(), imu_get_mag(), imu_init(), imu_set_body_to_imu_eulers(), imu_set_defaults_accel(), imu_set_defaults_gyro(), imu_set_defaults_mag(), imu_SetBodyToImuCurrent(), imu_SetBodyToImuPhi(), imu_SetBodyToImuPsi(), imu_SetBodyToImuTheta(), jevois_mavlink_filter_init(), jevois_mavlink_filter_periodic(), logger_uart_periodic(), mag_calib_ukf_run(), send_accel(), send_accel_raw(), send_accel_scaled(), send_gyro(), send_gyro_raw(), send_gyro_scaled(), send_mag(), send_mag_current(), send_mag_raw(), and send_mag_scaled().