Paparazzi UAS: sw/airborne/modules/imu/imu_pixhawk6x.c File Reference
imu_pixhawk6x.c File Reference
#include "generated/modules.h"
#include "modules/imu/imu.h"
#include "modules/core/abi.h"
#include "mcu_periph/spi.h"
#include "peripherals/invensense2.h"
#include "peripherals/invensense3.h"
Functions
void imu_pixhawk6x_init (void)
void imu_pixhawk6x_periodic (void)
void imu_pixhawk6x_event (void)
Variables
static struct invensense3_t imu1
static struct invensense3_t imu2
static struct invensense2_t imu3
Function Documentation
imu_pixhawk6x_event()
void imu_pixhawk6x_event (void)
Definition at line 119 of file imu_pixhawk6x.c.
References imu1, imu2, imu3, invensense2_event(), and invensense3_event().
imu_pixhawk6x_init()
void imu_pixhawk6x_init (void)
Definition at line 39 of file imu_pixhawk6x.c.
References invensense2_t::abi_id, invensense3_t::abi_id, invensense3_t::accel_aaf, invensense2_t::accel_dlpf, invensense3_t::accel_odr, invensense2_t::accel_range, invensense3_t::accel_range, ANGLE_BFP_OF_REAL, invensense2_t::bus, invensense3_t::bus, foo, invensense3_t::gyro_aaf, invensense2_t::gyro_dlpf, invensense3_t::gyro_odr, invensense2_t::gyro_range, invensense3_t::gyro_range, imu1, imu2, imu3, IMU_PIXHAWK1_ID, IMU_PIXHAWK2_ID, IMU_PIXHAWK3_ID, imu_set_defaults_accel(), imu_set_defaults_gyro(), int32_rmat_of_eulers, INVENSENSE2_ACCEL_DLPF_265HZ, INVENSENSE2_ACCEL_RANGE_30G, INVENSENSE2_GYRO_DLPF_229HZ, INVENSENSE2_GYRO_RANGE_4000DPS, invensense2_init(), INVENSENSE2_SPI, INVENSENSE3_ACCEL_ODR_4KHZ, INVENSENSE3_ACCEL_RANGE_32G, INVENSENSE3_GYRO_ODR_4KHZ, INVENSENSE3_GYRO_RANGE_2000DPS, invensense3_init(), INVENSENSE3_PARSER_FIFO, INVENSENSE3_SPI, invensense3_t::parser, Int32Eulers::phi, Int32Eulers::psi, and Int32Eulers::theta.
imu_pixhawk6x_periodic()
void imu_pixhawk6x_periodic (void)
Definition at line 112 of file imu_pixhawk6x.c.
References imu1, imu2, imu3, invensense2_periodic(), and invensense3_periodic().
Variable Documentation
imu1
struct invensense3_t imu1 static
Definition at line 35 of file imu_pixhawk6x.c.
Referenced by imu_pixhawk6x_event(), imu_pixhawk6x_init(), and imu_pixhawk6x_periodic().
imu2
struct invensense3_t imu2 static
Definition at line 36 of file imu_pixhawk6x.c.
Referenced by imu_pixhawk6x_event(), imu_pixhawk6x_init(), and imu_pixhawk6x_periodic().
imu3
struct invensense2_t imu3 static
Definition at line 37 of file imu_pixhawk6x.c.
Referenced by imu_pixhawk6x_event(), imu_pixhawk6x_init(), and imu_pixhawk6x_periodic().