Paparazzi UAS: sw/airborne/modules/ins/ins_xsens.h File Reference
ins_xsens.h File Reference
Xsens as a full INS solution.
#include "std.h"
#include "xsens.h"
Functions
void ins_xsens_init (void)
void ins_xsens_event (void)
Variables
float ins_pitch_neutral
float ins_roll_neutral
Detailed Description
Xsens as a full INS solution.
Definition in file ins_xsens.h.
Function Documentation
ins_xsens_event()
void ins_xsens_event (void) extern
Definition at line 78 of file ins_xsens.c.
References FALSE, handle_ins_msg(), XsensParser::msg_received, parse_xsens_msg(), Xsens::parser, xsens, and xsens_parser_event().
ins_xsens_init()
void ins_xsens_init (void) extern
Definition at line 64 of file ins_xsens.c.
References foo, gps_cb(), gps_ev, ins_pitch_neutral, INS_PITCH_NEUTRAL_DEFAULT, ins_roll_neutral, INS_ROLL_NEUTRAL_DEFAULT, INS_XSENS_GPS_ID, nav_utm_east0, nav_utm_north0, nav_utm_zone0, stateSetLocalUtmOrigin_f(), stateSetPositionUtm_f(), and xsens_init().
Variable Documentation
ins_pitch_neutral
float ins_pitch_neutral extern
Definition at line 15 of file ins_arduimu.c.
ins_roll_neutral
float ins_roll_neutral extern
Definition at line 14 of file ins_arduimu.c.