Paparazzi UAS: sw/airborne/modules/ins/ins_gps_passthrough.h File Reference
ins_gps_passthrough.h File Reference
Simply passes GPS through to the state interface.
Functions
void ins_gps_passthrough_init (void)
Detailed Description
Simply passes GPS through to the state interface.
Definition in file ins_gps_passthrough.h.
Function Documentation
ins_gps_passthrough_init()
void ins_gps_passthrough_init (void) extern
Definition at line 141 of file ins_gps_passthrough.c.
References ABI_BROADCAST, accel_cb(), accel_ev, DefaultPeriodic, ecef_of_lla_i(), foo, gps_cb(), gps_cb(), gps_ev, gps_ev, LtpDef_i::hmsl, ins_gp, INS_PT_GPS_ID, INS_PT_IMU_ID, INT32_VECT3_ZERO, LlaCoor_i::lat, InsGpsPassthrough::ltp_accel, InsGpsPassthrough::ltp_def, ltp_def_from_ecef_i(), InsGpsPassthrough::ltp_initialized, InsGpsPassthrough::ltp_pos, InsGpsPassthrough::ltp_speed, nav_utm_east0, nav_utm_north0, nav_utm_zone0, register_periodic_telemetry(), reset_cb(), reset_cb(), reset_ev, reset_ev, send_ins(), send_ins_ref(), send_ins_z(), stateSetLocalOrigin_i(), stateSetLocalUtmOrigin_f(), and stateSetPositionUtm_f().