Paparazzi UAS: sw/airborne/modules/ins/ins_arduimu_basic.h File Reference
ins_arduimu_basic.h File Reference
#include "std.h"
#include "math/pprz_algebra_float.h"
Functions
void ArduIMU_init (void)
void ArduIMU_periodic (void)
void ArduIMU_periodicGPS (void)
void ArduIMU_event (void)
Variables
struct FloatEulers arduimu_eulers
ArduIMU simulation.
struct FloatRates arduimu_rates
struct FloatVect3 arduimu_accel
float ins_roll_neutral
float ins_pitch_neutral
bool arduimu_calibrate_neutrals
Function Documentation
ArduIMU_event()
void ArduIMU_event (void)
Definition at line 41 of file ins_arduimu_basic.c.
References ACCEL_FLOAT_OF_BFP, ANGLE_FLOAT_OF_BFP, ardu_gps_trans, ardu_ins_trans, arduimu_accel, arduimu_eulers, arduimu_rates, i2c_transaction::buf, DefaultChannel, DefaultDevice, foo, I2CTransDone, I2CTransFailed, I2CTransSuccess, ins_pitch_neutral, ins_roll_neutral, FloatRates::p, FloatEulers::phi, FloatEulers::psi, FloatRates::q, FloatRates::r, RATE_FLOAT_OF_BFP, recievedData, stateSetAccelNed_f(), stateSetBodyRates_f(), stateSetNedToBodyEulers_f(), i2c_transaction::status, FloatEulers::theta, FloatVect3::x, FloatVect3::y, and FloatVect3::z.
ArduIMU_init()
void ArduIMU_init (void)
Definition at line 25 of file ins_arduimu.c.
References ardu_gps_trans, ardu_ins_trans, arduimu_accel, arduimu_calibrate_neutrals, arduimu_eulers, arduimu_rates, i2c_transaction::buf, FLOAT_EULERS_ZERO, FLOAT_RATES_ZERO, FLOAT_VECT3_ZERO, gps_daten_abgespeichert, gps_daten_versendet_msg1, gps_daten_versendet_msg2, high_accel_done, high_accel_flag, I2CTransDone, imu_daten_angefordert, ins_pitch_neutral, INS_PITCH_NEUTRAL_DEFAULT, ins_roll_neutral, INS_ROLL_NEUTRAL_DEFAULT, messageNr, i2c_transaction::status, throttle_slew, and V_CTL_THROTTLE_SLEW.
ArduIMU_periodic()
void ArduIMU_periodic (void)
Definition at line 26 of file ins_arduimu.c.
References ardu_ins_trans, ARDUIMU_I2C_DEV, ArduIMU_SLAVE_ADDR, foo, i2c_receive(), I2CTransDone, imu_daten_angefordert, IMU_Daten_verarbeiten(), ins_pitch_neutral, ins_roll_neutral, NB_DATA, sim_p, sim_phi, sim_q, sim_r, sim_theta, stateSetBodyRates_f(), stateSetNedToBodyEulers_f(), i2c_transaction::status, and TRUE.
ArduIMU_periodicGPS()
void ArduIMU_periodicGPS (void)
Definition at line 36 of file ins_arduimu.c.
References LlaCoor_i::alt, ardu_gps_trans, arduimu_calibrate_neutrals, ARDUIMU_I2C_DEV, ArduIMU_SLAVE_ADDR, i2c_transaction::buf, GpsState::course, FALSE, FillBufWith32bit, GpsState::fix, foo, gps, GPS_Data, gps_daten_abgespeichert, gps_daten_versendet_msg1, gps_daten_versendet_msg2, gps_ubx, GpsState::gspeed, high_accel_done, high_accel_flag, HIGH_ACCEL_HIGH_THRUST, HIGH_ACCEL_HIGH_THRUST_RESUME, HIGH_ACCEL_LOW_SPEED, GpsState::hmsl, i2c_transmit(), I2CTransDone, imu_daten_angefordert, IMU_Daten_verarbeiten(), LlaCoor_i::lat, GpsState::lla_pos, LlaCoor_i::lon, messageNr, GpsState::ned_vel, GpsState::num_sv, GpsState::speed_3d, stateGetHorizontalSpeedNorm_f(), i2c_transaction::status, GpsUbx::status_flags, GpsState::tow, TRUE, and NedCoor_i::z.
Variable Documentation
arduimu_accel
struct FloatVect3 arduimu_accel extern
Definition at line 14 of file ins_arduimu_basic.c.
Referenced by ArduIMU_event(), and ArduIMU_init().
arduimu_calibrate_neutrals
bool arduimu_calibrate_neutrals extern
Definition at line 18 of file ins_arduimu_basic.c.
Referenced by ArduIMU_init(), and ArduIMU_periodicGPS().
arduimu_eulers
struct FloatEulers arduimu_eulers extern
ArduIMU simulation.
Sim provides attitude and rates.
Definition at line 12 of file ins_arduimu_basic.c.
Referenced by ArduIMU_event(), and ArduIMU_init().
arduimu_rates
struct FloatRates arduimu_rates extern
Definition at line 13 of file ins_arduimu_basic.c.
Referenced by ArduIMU_event(), and ArduIMU_init().
ins_pitch_neutral
float ins_pitch_neutral extern
Definition at line 15 of file ins_arduimu.c.
ins_roll_neutral
float ins_roll_neutral extern
Definition at line 14 of file ins_arduimu.c.