Paparazzi UAS: sw/airborne/modules/ins/ins_xsens700.c File Reference
ins_xsens700.c File Reference
Xsens700 as a full INS solution.
#include "ins_xsens700.h"
#include "modules/ins/ins.h"
#include "generated/airframe.h"
#include "mcu_periph/sys_time.h"
#include "modules/datalink/downlink.h"
#include "pprzlink/messages.h"
Macros
#define INS_XSENS700_GPS_ID GPS_MULTI_ID
ABI binding for gps data.
Functions
static void handle_ins_msg (void)
static void update_state_interface (void)
static void gps_cb (uint8_t sender_id, uint32_t stamp, struct GpsState *gps_s)
void ins_xsens700_init (void)
void ins_xsens700_event (void)
Variables
static abi_event gps_ev
float ins_pitch_neutral
float ins_roll_neutral
Detailed Description
Xsens700 as a full INS solution.
Definition in file ins_xsens700.c.
Macro Definition Documentation
INS_XSENS700_GPS_ID
#define INS_XSENS700_GPS_ID GPS_MULTI_ID
ABI binding for gps data.
Used for GPS ABI messages.
Definition at line 52 of file ins_xsens700.c.
Function Documentation
gps_cb()
static void gps_cb (uint8_t sender_id, uint32_t stamp , struct GpsState * gps_s) static
Definition at line 90 of file ins_xsens700.c.
References foo, nav_utm_zone0, ned_vel_float_from_gps(), stateSetPositionUtm_f(), stateSetSpeedNed_f(), and utm_float_from_gps().
Referenced by ins_xsens700_init().
handle_ins_msg()
static void handle_ins_msg (void) static
Definition at line 157 of file ins_xsens700.c.
References FLOAT_VECT2_NORM, float_vect3_norm(), foo, GPS_FIX_3D, GPS_VALID_COURSE_BIT, Xsens::new_attitude, new_ins_attitude, update_state_interface(), Xsens::vel, FloatVect3::x, xsens700, and FloatVect3::y.
Referenced by ins_xsens700_event().
ins_xsens700_event()
void ins_xsens700_event (void)
Definition at line 80 of file ins_xsens700.c.
References handle_ins_msg(), XsensParser::msg_received, parse_xsens700_msg(), Xsens::parser, xsens700, and xsens_parser_event().
ins_xsens700_init()
void ins_xsens700_init (void)
Definition at line 66 of file ins_xsens700.c.
References foo, gps_cb(), gps_ev, ins_pitch_neutral, INS_PITCH_NEUTRAL_DEFAULT, ins_roll_neutral, INS_ROLL_NEUTRAL_DEFAULT, INS_XSENS700_GPS_ID, nav_utm_east0, nav_utm_north0, nav_utm_zone0, stateSetLocalUtmOrigin_f(), stateSetPositionUtm_f(), and xsens700_init().
update_state_interface()
static void update_state_interface (void) static
Definition at line 126 of file ins_xsens700.c.
References Xsens::euler, foo, Xsens::gyro, ins_pitch_neutral, ins_roll_neutral, FloatRates::p, FloatEulers::phi, FloatEulers::psi, FloatRates::q, FloatRates::r, stateSetBodyRates_f(), stateSetNedToBodyEulers_f(), FloatEulers::theta, and xsens700.
Referenced by handle_ins_msg().
Variable Documentation
gps_ev
abi_event gps_ev static
Definition at line 55 of file ins_xsens700.c.
Referenced by ins_xsens700_init().
ins_pitch_neutral
float ins_pitch_neutral
Definition at line 57 of file ins_xsens700.c.
Referenced by ins_xsens700_init(), and update_state_interface().
ins_roll_neutral
float ins_roll_neutral
Definition at line 58 of file ins_xsens700.c.
Referenced by ins_xsens700_init(), and update_state_interface().