Paparazzi UAS: sw/airborne/modules/ins/ins_float_invariant_wrapper.h File Reference
ins_float_invariant_wrapper.h File Reference
Paparazzi specific wrapper to run INVARIANT filter.
#include "modules/ins/ins_float_invariant.h"
Functions
void ins_float_invariant_wrapper_init (void)
Detailed Description
Paparazzi specific wrapper to run INVARIANT filter.
Definition in file ins_float_invariant_wrapper.h.
Function Documentation
ins_float_invariant_wrapper_init()
void ins_float_invariant_wrapper_init (void) extern
Definition at line 228 of file ins_float_invariant_wrapper.c.
References ABI_BROADCAST, accel_cb(), accel_ev, ahrs_aligner_init(), aligner_cb(), aligner_ev, baro_cb(), baro_ev, DefaultPeriodic, foo, geo_mag_cb(), geo_mag_ev, gps_cb(), gps_ev, gyro_cb(), gyro_ev, INS_FINV_BARO_ID, INS_FINV_GPS_ID, INS_FINV_IMU_ID, INS_FINV_MAG_ID, ins_float_invariant_init(), mag_cb(), mag_ev, register_periodic_telemetry(), reset_cb(), reset_ev, send_filter_status(), and send_ins_ref().