Paparazzi UAS: sw/airborne/modules/ins/ins_module.h File Reference
ins_module.h File Reference
Device independent INS code.
#include "std.h"
#include "modules/ins/ins.h"
#include "pprzlink/pprzlink_device.h"
#include "mcu_periph/uart.h"
#include "mcu_periph/spi.h"
Macros
#define INS_FORMAT float
#define InsLinkDevice (&((INS_LINK).device))
#define InsSend1(c) InsLinkDevice->put_byte(InsLinkDevice->periph, 0, c)
#define InsUartSend1(c) InsSend1(c)
#define InsSend(_dat, _len) { for (uint8_t i = 0; i< (_len); i++) InsSend1(_dat[i]); };
#define InsUartSetBaudrate(_b) uart_periph_set_baudrate(INS_LINK, _b)
Functions
void handle_ins_msg (void)
void parse_ins_msg (void)
void parse_ins_buffer (uint8_t)
static void ins_event_check_and_handle (void(*handler)(void))
!SITL
Variables
INS_FORMAT ins_x
INS_FORMAT ins_y
INS_FORMAT ins_z
INS_FORMAT ins_vx
INS_FORMAT ins_vy
INS_FORMAT ins_vz
INS_FORMAT ins_phi
INS_FORMAT ins_theta
INS_FORMAT ins_psi
INS_FORMAT ins_p
INS_FORMAT ins_q
INS_FORMAT ins_r
INS_FORMAT ins_ax
INS_FORMAT ins_ay
INS_FORMAT ins_az
INS_FORMAT ins_mx
INS_FORMAT ins_my
INS_FORMAT ins_mz
volatile uint8_t ins_msg_received
volatile uint8_t new_ins_attitude
Detailed Description
Device independent INS code.
Definition in file ins_module.h.
Macro Definition Documentation
INS_FORMAT
#define INS_FORMAT float
Definition at line 35 of file ins_module.h.
InsLinkDevice
#define InsLinkDevice (&((INS_LINK).device))
Definition at line 76 of file ins_module.h.
InsSend
#define InsSend (_dat, _len) { for (uint8_t i = 0; i< (_len); i++) InsSend1(_dat[i]); };
Definition at line 84 of file ins_module.h.
InsSend1
#define InsSend1 (c) InsLinkDevice->put_byte(InsLinkDevice->periph, 0, c)
Definition at line 82 of file ins_module.h.
InsUartSend1
#define InsUartSend1 (c) InsSend1(c)
Definition at line 83 of file ins_module.h.
InsUartSetBaudrate
#define InsUartSetBaudrate (_b) uart_periph_set_baudrate(INS_LINK, _b)
Definition at line 85 of file ins_module.h.
Function Documentation
handle_ins_msg()
void handle_ins_msg (void)
Definition at line 151 of file ins_xsens.c.
References FLOAT_VECT2_NORM, float_vect3_norm(), foo, GPS_FIX_3D, GPS_VALID_COURSE_BIT, Xsens::new_attitude, new_ins_attitude, update_state_interface(), Xsens::vel, FloatVect3::x, xsens, and FloatVect3::y.
ins_event_check_and_handle()
static void ins_event_check_and_handle (void(*)(void) handler) inline static
!SITL
Definition at line 89 of file ins_module.h.
References dev, foo, ins_msg_received, InsLinkDevice, parse_ins_buffer(), and parse_ins_msg().
parse_ins_buffer()
void parse_ins_buffer (uint8_t)
Referenced by ins_event_check_and_handle().
parse_ins_msg()
static void parse_ins_msg (void) inline
Definition at line 185 of file ins_vn100.c.
References VN100_Res_Packet::Data, VN100_Res_Packet::ErrID, VN100_Param::Float, float_eulers_of_quat(), foo, ins_accel, ins_adof, ins_ador, ins_baud, ins_eulers, ins_mag, ins_quat, ins_rates, last_received_packet, FloatRates::p, FloatEulers::phi, FloatEulers::psi, FloatRates::q, FloatQuat::qi, FloatQuat::qx, FloatQuat::qy, FloatQuat::qz, FloatRates::r, VN100_Res_Packet::RegID, FloatEulers::theta, VN100_Param::UInt, VN100_Error_None, VN100_REG_ADOF, VN100_REG_ADOR, VN100_REG_QAR, VN100_REG_QMA, VN100_REG_QMR, VN100_REG_QTA, VN100_REG_QTM, VN100_REG_QTN, VN100_REG_QTR, VN100_REG_SBAUD, VN100_REG_YMR, VN100_REG_YPR, FloatVect3::x, FloatVect3::y, and FloatVect3::z.
Referenced by ins_event_check_and_handle().
Variable Documentation
ins_ax
INS_FORMAT ins_ax extern
ins_ay
INS_FORMAT ins_ay extern
ins_az
INS_FORMAT ins_az extern
ins_msg_received
volatile uint8_t ins_msg_received extern
Definition at line 64 of file ins_vn100.c.
Referenced by ins_event_check_and_handle().
ins_mx
INS_FORMAT ins_mx extern
ins_my
INS_FORMAT ins_my extern
ins_mz
INS_FORMAT ins_mz extern
ins_p
INS_FORMAT ins_p extern
ins_phi
INS_FORMAT ins_phi extern
ins_psi
INS_FORMAT ins_psi extern
ins_q
INS_FORMAT ins_q extern
ins_r
INS_FORMAT ins_r extern
ins_theta
INS_FORMAT ins_theta extern
ins_vx
INS_FORMAT ins_vx extern
ins_vy
INS_FORMAT ins_vy extern
ins_vz
INS_FORMAT ins_vz extern
ins_x
INS_FORMAT ins_x extern
ins_y
INS_FORMAT ins_y extern
ins_z
INS_FORMAT ins_z extern
new_ins_attitude
volatile uint8_t new_ins_attitude extern
Referenced by handle_ins_msg(), and handle_ins_msg().