Paparazzi UAS: sw/airborne/modules/ins/ins_alt_float.h File Reference
ins_alt_float.h File Reference
Filters altitude and climb rate for fixedwings.
#include "modules/ins/ins.h"
#include <inttypes.h>
#include "std.h"
Data Structures
struct InsAltFloat
Ins implementation state (altitude, float)
Functions
void ins_alt_float_init (void)
void ins_alt_float_update_baro (float pressure)
Variables
struct InsAltFloat ins_altf
Detailed Description
Filters altitude and climb rate for fixedwings.
Definition in file ins_alt_float.h.
Data Structure Documentation
InsAltFloat
struct InsAltFloat
Ins implementation state (altitude, float)
Definition at line 37 of file ins_alt_float.h.
Data Fields
float alt estimated altitude above MSL in meters
float alt_dot estimated vertical speed in m/s (positive-up)
float baro_alt
bool baro_initialized
bool origin_initialized TRUE if UTM origin was initialized.
float qfe
bool reset_alt_ref flag to request reset of altitude reference to current alt
Function Documentation
ins_alt_float_init()
void ins_alt_float_init (void) extern
Definition at line 101 of file ins_alt_float.c.
References ABI_BROADCAST, accel_cb(), accel_ev, alt_kalman(), alt_kalman_init(), InsAltFloat::baro_alt, baro_cb(), baro_ev, InsAltFloat::baro_initialized, foo, gps_cb(), gps_ev, INS_ALT_BARO_ID, INS_ALT_GPS_ID, INS_ALT_IMU_ID, ins_altf, nav_utm_east0, nav_utm_north0, nav_utm_zone0, InsAltFloat::origin_initialized, InsAltFloat::qfe, InsAltFloat::reset_alt_ref, reset_cb(), reset_ev, stateSetLocalUtmOrigin_f(), and stateSetPositionUtm_f().
ins_alt_float_update_baro()
void ins_alt_float_update_baro (float pressure) extern
Definition at line 172 of file ins_alt_float.c.
References InsAltFloat::alt, InsAltFloat::alt_dot, alt_kalman(), alt_kalman_reset(), InsAltFloat::baro_alt, InsAltFloat::baro_initialized, foo, get_sys_time_usec(), ground_alt, ins_altf, last_ts, pprz_isa_height_of_pressure(), InsAltFloat::qfe, InsAltFloat::reset_alt_ref, stateGetPositionUtm_f(), stateGetSpeedNed_f(), stateSetPositionUtm_f(), stateSetSpeedNed_f(), UTM_COPY, and NedCoor_f::z.
Referenced by baro_cb().
Variable Documentation
ins_altf
struct InsAltFloat ins_altf extern
Definition at line 54 of file ins_alt_float.c.
Referenced by alt_kalman(), ins_alt_float_init(), ins_alt_float_update_baro(), ins_alt_float_update_gps(), reset_ref(), and reset_vertical_ref().