Paparazzi UAS: sw/airborne/modules/ins/ins_ext_pose.h File Reference
ins_ext_pose.h File Reference
Integrated Navigation System interface.
#include "std.h"
#include "generated/airframe.h"
#include <stdio.h>
Enumerations
enum ins_ext_pose_state {
EKF_X_POS_X , EKF_X_POS_Y , EKF_X_POS_Z , EKF_X_VEL_X ,
EKF_X_VEL_Y , EKF_X_VEL_Z , EKF_X_PHI , EKF_X_THETA ,
EKF_X_PSI , EKF_X_A_BIAS_X , EKF_X_A_BIAS_Y , EKF_X_A_BIAS_Z ,
EKF_X_G_BIAS_P , EKF_X_G_BIAS_Q , EKF_X_G_BIAS_R , EKF_NUM_STATES
}
enum ins_ext_pose_inputs {
EKF_U_ACC_X , EKF_U_ACC_Y , EKF_U_ACC_Z , EKF_U_GYRO_P ,
EKF_U_GYRO_Q , EKF_U_GYRO_R , EKF_NUM_INPUTS
}
enum ins_ext_pose_outputs {
EKF_Z_POS_X , EKF_Z_POS_Y , EKF_Z_POS_Z , EKF_Z_PHI ,
EKF_Z_THETA , EKF_Z_PSI , EKF_NUM_OUTPUTS
}
Functions
void ins_ext_pose_init (void)
Module.
void ins_ext_pose_run (void)
void ins_ext_pose_msg_update (uint8_t *buf)
Import External Pose Message.
void ins_ext_pose_log_header (FILE *file)
Logging.
void ins_ext_pose_log_data (FILE *file)
Variables
float ekf_X [EKF_NUM_STATES]
Detailed Description
Integrated Navigation System interface.
Definition in file ins_ext_pose.h.
Enumeration Type Documentation
ins_ext_pose_inputs
enum ins_ext_pose_inputs
Enumerator
EKF_U_ACC_X
EKF_U_ACC_Y
EKF_U_ACC_Z
EKF_U_GYRO_P
EKF_U_GYRO_Q
EKF_U_GYRO_R
EKF_NUM_INPUTS
Definition at line 58 of file ins_ext_pose.h.
ins_ext_pose_outputs
enum ins_ext_pose_outputs
Enumerator
EKF_Z_POS_X
EKF_Z_POS_Y
EKF_Z_POS_Z
EKF_Z_PHI
EKF_Z_THETA
EKF_Z_PSI
EKF_NUM_OUTPUTS
Definition at line 68 of file ins_ext_pose.h.
ins_ext_pose_state
enum ins_ext_pose_state
Enumerator
EKF_X_POS_X
EKF_X_POS_Y
EKF_X_POS_Z
EKF_X_VEL_X
EKF_X_VEL_Y
EKF_X_VEL_Z
EKF_X_PHI
EKF_X_THETA
EKF_X_PSI
EKF_X_A_BIAS_X
EKF_X_A_BIAS_Y
EKF_X_A_BIAS_Z
EKF_X_G_BIAS_P
EKF_X_G_BIAS_Q
EKF_X_G_BIAS_R
EKF_NUM_STATES
Definition at line 39 of file ins_ext_pose.h.
Function Documentation
ins_ext_pose_init()
void ins_ext_pose_init (void) extern
Module.
Definition at line 283 of file ins_ext_pose.c.
References accel_cb(), accel_ev, DefaultPeriodic, ekf_init(), foo, gyro_cb(), gyro_ev, InsExtPose::has_new_acc, InsExtPose::has_new_ext_pose, InsExtPose::has_new_gyro, ins_ext_pose, INS_EXT_POSE_IMU_ID, ins_ext_pose_init_from_flightplan(), register_periodic_telemetry(), send_ahrs_bias(), send_external_pose_down(), send_filter_status(), send_ins(), send_ins_ref(), send_ins_z(), and InsExtPose::started.
ins_ext_pose_log_data()
void ins_ext_pose_log_data (FILE * file) extern
Definition at line 956 of file ins_ext_pose.c.
References ekf_U, ekf_X, ekf_Z, and foo.
Referenced by logger_file_write_row().
ins_ext_pose_log_header()
void ins_ext_pose_log_header (FILE * file) extern
Logging.
Definition at line 948 of file ins_ext_pose.c.
References foo.
Referenced by logger_file_write_header().
ins_ext_pose_msg_update()
void ins_ext_pose_msg_update (uint8_t * buf) extern
Import External Pose Message.
Definition at line 226 of file ins_ext_pose.c.
References DEBUG_PRINT, ENU_OF_TO_NED, EULERS_COPY, InsExtPose::ev_att, InsExtPose::ev_pos, InsExtPose::ev_quat, InsExtPose::ev_time, InsExtPose::ev_vel, float_eulers_of_quat(), float_quat_comp(), foo, get_sys_time_usec(), InsExtPose::has_new_ext_pose, ins_ext_pose, FloatEulers::phi, FloatEulers::psi, FloatQuat::qi, QUAT_COPY, FloatQuat::qx, FloatQuat::qy, FloatQuat::qz, FloatEulers::theta, and EnuCoor_f::x.
ins_ext_pose_run()
void ins_ext_pose_run (void) extern
Definition at line 314 of file ins_ext_pose.c.
References ekf_run().
Variable Documentation
ekf_X
float ekf_X[EKF_NUM_STATES] extern
Definition at line 340 of file ins_ext_pose.c.
Referenced by ekf_init(), ekf_measurement_step(), ekf_prediction_step(), ekf_run(), ins_ext_pose_log_data(), and send_ahrs_bias().