Paparazzi UAS: sw/airborne/modules/ins/ins_arduimu.h File Reference
ins_arduimu.h File Reference
#include <inttypes.h>
Macros
#define NB_DATA 6
Functions
void ArduIMU_init (void)
void ArduIMU_periodic (void)
void ArduIMU_periodicGPS (void)
void IMU_Daten_verarbeiten (void)
Variables
float ArduIMU_data [NB_DATA]
ArduIMU simulation.
float ins_roll_neutral
float ins_pitch_neutral
float pitch_of_throttle_gain
float throttle_slew
Macro Definition Documentation
NB_DATA
#define NB_DATA 6
Definition at line 6 of file ins_arduimu.h.
Function Documentation
ArduIMU_init()
void ArduIMU_init (void)
Definition at line 25 of file ins_arduimu.c.
ArduIMU_periodic()
void ArduIMU_periodic (void)
Definition at line 26 of file ins_arduimu.c.
ArduIMU_periodicGPS()
void ArduIMU_periodicGPS (void)
Definition at line 36 of file ins_arduimu.c.
IMU_Daten_verarbeiten()
void IMU_Daten_verarbeiten (void)
Definition at line 37 of file ins_arduimu.c.
References ardu_ins_trans, ArduIMU_data, i2c_transaction::buf, DefaultChannel, DefaultDevice, foo, imu_daten_angefordert, ins_pitch_neutral, ins_roll_neutral, FloatEulers::phi, FloatEulers::psi, recievedData, stateSetNedToBodyEulers_f(), and FloatEulers::theta.
Referenced by ArduIMU_periodic(), and ArduIMU_periodicGPS().
Variable Documentation
ArduIMU_data
float ArduIMU_data[NB_DATA] extern
ArduIMU simulation.
Sim provides attitude.
Definition at line 12 of file ins_arduimu.c.
Referenced by IMU_Daten_verarbeiten().
ins_pitch_neutral
float ins_pitch_neutral extern
Definition at line 15 of file ins_arduimu.c.
ins_roll_neutral
float ins_roll_neutral extern
Definition at line 14 of file ins_arduimu.c.
pitch_of_throttle_gain
float pitch_of_throttle_gain extern
Definition at line 18 of file ins_arduimu.c.
throttle_slew
float throttle_slew extern
Definition at line 19 of file ins_arduimu.c.
Referenced by ArduIMU_init().