Paparazzi UAS: sw/airborne/modules/intermcu/intermcu.h File Reference
intermcu.h File Reference
Inter-MCU interface.
#include "std.h"
#include "modules/core/commands.h"
#include "pprzlink/pprz_transport.h"
#include <BOARD_CONFIG>
Data Structures
struct intermcu_t
Macros
#define INTERMCU_LOST_CNT 25 /* 50ms with a 512Hz timer TODO fixed value */
#define INTERMCU_SET_CMD_STATUS(_bit) { intermcu.cmd_status |= (1 << _bit); }
#define INTERMCU_CLR_CMD_STATUS(_bit) { intermcu.cmd_status &= ~(1 << _bit); }
#define INTERMCU_GET_CMD_STATUS(_bit) (intermcu.cmd_status & (1 << _bit))
Enumerations
enum intermcu_status { INTERMCU_OK , INTERMCU_LOST }
enum intermcu_cmd_status { INTERMCU_CMD_MOTORS_ON , INTERMCU_CMD_DISARM , INTERMCU_CMD_TIPPROPS , INTERMCU_CMD_FAILSAFE }
Functions
void intermcu_init (void)
void intermcu_periodic (void)
void intermcu_event (void)
Variables
struct intermcu_t intermcu
Detailed Description
Inter-MCU interface.
Definition in file intermcu.h.
Data Structure Documentation
intermcu_t
struct intermcu_t
Definition at line 69 of file intermcu.h.
Data Fields
uint8_t cmd_status Command status information that is transfered (intermcu_cmd_status)
struct link_device * device Device used for communication.
bool enabled If the InterMCU communication is enabled.
bool msg_available If we have an InterMCU message.
enum intermcu_status status Status of the INTERMCU.
uint8_t time_since_last_frame Time since last frame.
struct pprz_transport transport Transport over communication line (PPRZ)
Macro Definition Documentation
INTERMCU_CLR_CMD_STATUS
#define INTERMCU_CLR_CMD_STATUS (_bit) { intermcu.cmd_status &= ~(1 << _bit); }
Definition at line 65 of file intermcu.h.
INTERMCU_GET_CMD_STATUS
#define INTERMCU_GET_CMD_STATUS (_bit) (intermcu.cmd_status & (1 << _bit))
Definition at line 66 of file intermcu.h.
INTERMCU_LOST_CNT
#define INTERMCU_LOST_CNT 25 /* 50ms with a 512Hz timer TODO fixed value */
Definition at line 35 of file intermcu.h.
INTERMCU_SET_CMD_STATUS
#define INTERMCU_SET_CMD_STATUS (_bit) { intermcu.cmd_status |= (1 << _bit); }
Definition at line 64 of file intermcu.h.
Enumeration Type Documentation
intermcu_cmd_status
enum intermcu_cmd_status
Enumerator
INTERMCU_CMD_MOTORS_ON
The status of intermcu_ap_motors_on.
INTERMCU_CMD_DISARM
Whether or not to dis-arm the FBW.
INTERMCU_CMD_TIPPROPS
Enable tip props.
INTERMCU_CMD_FAILSAFE
Set FBW in failsafe mode.
Definition at line 56 of file intermcu.h.
intermcu_status
enum intermcu_status
Enumerator
INTERMCU_OK
InterMCU communication is OK.
INTERMCU_LOST
No interMCU communication anymore.
Definition at line 41 of file intermcu.h.
Function Documentation
intermcu_event()
void intermcu_event (void) extern
Definition at line 95 of file intermcu_ap.c.
References datalink_nb_msgs, datalink_time, intermcu_t::device, dl_parse_msg(), intermcu_t::enabled, foo, imcu_msg_buf, intermcu, intermcu_dl_on_msg(), intermcu_t::msg_available, intermcu_t::time_since_last_frame, and intermcu_t::transport.
Referenced by main_fbw_event().
intermcu_init()
void intermcu_init (void) extern
Definition at line 69 of file intermcu_ap.c.
References DefaultPeriodic, foo, gps_cb(), gps_ev, IMCU_GPS_ID, IMCU_RADIO_CONTROL_ID, intermcu, rc_cb(), rc_ev, register_periodic_telemetry(), send_status(), sys_time_register_timer(), and intermcu_t::transport.
intermcu_periodic()
void intermcu_periodic (void) extern
Definition at line 79 of file intermcu_ap.c.
References DefaultPeriodic, intermcu_t::device, foo, intermcu, INTERMCU_LOST, INTERMCU_LOST_CNT, intermcu_t::status, intermcu_t::time_since_last_frame, and intermcu_t::transport.
Variable Documentation
intermcu
struct intermcu_t intermcu extern
Definition at line 45 of file intermcu_ap.c.
Referenced by fbw_safety_check(), gps_cb(), intermcu_event(), intermcu_forward_uplink(), intermcu_init(), intermcu_parse_IMCU_COMMANDS(), intermcu_periodic(), intermcu_send_commands(), intermcu_send_spektrum_bind(), intermcu_send_status(), intermcu_set_enabled(), main_task_periodic(), opa_controller_periodic(), rc_cb(), and rc_cb().