Paparazzi UAS: sw/airborne/modules/datalink/intermcu_dl.h File Reference
intermcu_dl.h File Reference
datalink forwarder for InterMCU
#include "std.h"
#include "pprzlink/pprzlink_device.h"
#include "pprzlink/pprzlink_transport.h"
Data Structures
struct intermcu_dl_t
Functions
void intermcu_dl_init (void)
Init function.
void intermcu_dl_repack (struct transport_tx *trans, struct link_device *dev, uint8_t *msg, uint8_t size)
repack a message and send on device
void intermcu_dl_on_msg (uint8_t *msg, uint8_t size)
function to forward telemetry on new message
Variables
struct intermcu_dl_t intermcu_dl
Detailed Description
datalink forwarder for InterMCU
Definition in file intermcu_dl.h.
Data Structure Documentation
intermcu_dl_t
struct intermcu_dl_t
Definition at line 34 of file intermcu_dl.h.
Data Fields
struct link_device * dev Device structure for communication.
struct transport_tx * trans Forwarding transport.
Function Documentation
intermcu_dl_init()
void intermcu_dl_init (void) extern
Init function.
Definition at line 40 of file intermcu_dl.c.
References intermcu_dl_t::dev, foo, intermcu_dl, and intermcu_dl_t::trans.
intermcu_dl_on_msg()
void intermcu_dl_on_msg (uint8_t * msg, uint8_t size) extern
function to forward telemetry on new message
Parameters
msg pointer to the message buffer
size size of the message to send
function to forward telemetry on new message
Definition at line 79 of file intermcu_dl.c.
References intermcu_dl_t::dev, foo, intermcu_dl, intermcu_dl_repack(), msg, and intermcu_dl_t::trans.
Referenced by intermcu_event().
intermcu_dl_repack()
void intermcu_dl_repack (struct transport_tx * trans, struct link_device * dev, uint8_t * msg, uint8_t size) extern
repack a message and send on device
Parameters
trans pointer to the TX transport
dev pointer to the sending device
msg pointer to the message buffer
size size of the message to send
repack a message and send on device
Definition at line 57 of file intermcu_dl.c.
References dev, foo, and msg.
Referenced by intermcu_dl_on_msg(), and intermcu_forward_uplink().
Variable Documentation
intermcu_dl
struct intermcu_dl_t intermcu_dl extern
Definition at line 37 of file intermcu_dl.c.
Referenced by intermcu_dl_init(), and intermcu_dl_on_msg().