Paparazzi UAS: sw/airborne/modules/datalink/intermcu_dl.c File Reference
intermcu_dl.c File Reference
datalink forwarder for InterMCU
#include "modules/datalink/intermcu_dl.h"
#include "modules/datalink/datalink.h"
#include "modules/intermcu/intermcu.h"
#include "pprzlink/intermcu_msg.h"
#include "modules/datalink/telemetry.h"
Macros
#define INTERMCU_DL_UPDATE_DL TRUE
Functions
void intermcu_dl_init (void)
Init function.
void intermcu_dl_repack (struct transport_tx *trans, struct link_device *dev, uint8_t *msg, uint8_t size)
Repack message with same header and send on selected link if possible.
void intermcu_dl_on_msg (uint8_t *msg, uint8_t size)
function to forward telemetry from AP to the ground
Variables
struct intermcu_dl_t intermcu_dl
Detailed Description
datalink forwarder for InterMCU
Definition in file intermcu_dl.c.
Macro Definition Documentation
INTERMCU_DL_UPDATE_DL
#define INTERMCU_DL_UPDATE_DL TRUE
Definition at line 34 of file intermcu_dl.c.
Function Documentation
intermcu_dl_init()
void intermcu_dl_init (void)
Init function.
Definition at line 40 of file intermcu_dl.c.
References intermcu_dl_t::dev, foo, intermcu_dl, and intermcu_dl_t::trans.
intermcu_dl_on_msg()
void intermcu_dl_on_msg (uint8_t * msg, uint8_t size)
function to forward telemetry from AP to the ground
function to forward telemetry on new message
Definition at line 79 of file intermcu_dl.c.
References intermcu_dl_t::dev, foo, intermcu_dl, intermcu_dl_repack(), msg, and intermcu_dl_t::trans.
Referenced by intermcu_event().
intermcu_dl_repack()
void intermcu_dl_repack (struct transport_tx * trans, struct link_device * dev, uint8_t * msg, uint8_t size)
Repack message with same header and send on selected link if possible.
repack a message and send on device
Definition at line 57 of file intermcu_dl.c.
References dev, foo, and msg.
Referenced by intermcu_dl_on_msg(), and intermcu_forward_uplink().
Variable Documentation
intermcu_dl
struct intermcu_dl_t intermcu_dl
Definition at line 37 of file intermcu_dl.c.
Referenced by intermcu_dl_init(), and intermcu_dl_on_msg().