Paparazzi UAS: sw/airborne/peripherals/invensense3.c File Reference
invensense3.c File Reference
Driver for the Invensense v3 IMUs ICM40605, ICM40609, ICM42605, IIM42652 and ICM42688.
#include "peripherals/invensense3.h"
#include "peripherals/invensense3_regs.h"
#include "math/pprz_isa.h"
#include "math/pprz_algebra_int.h"
#include "math/pprz_algebra_float.h"
#include "modules/imu/imu.h"
#include "modules/core/abi.h"
#include "mcu_periph/gpio_arch.h"
#include "std.h"
Functions
static void invensense3_parse_fifo_data (struct invensense3_t *inv, uint8_t *data, uint16_t samples)
Parse the FIFO buffer data.
static void invensense3_parse_reg_data (struct invensense3_t *inv, uint8_t *data)
Parse data from registers.
static void invensense3_fix_config (struct invensense3_t *inv)
This fixes the configuration errors and sets the correct scalings.
static bool invensense3_register_write (struct invensense3_t *inv, uint16_t bank_reg, uint8_t value)
Write a register based on a combined bank/regsiter value.
static bool invensense3_register_read (struct invensense3_t *inv, uint16_t bank_reg, uint16_t size)
Read a register based on a combined bank/regsiter value.
static bool invensense3_select_bank (struct invensense3_t *inv, uint8_t bank)
Select the correct register bank.
static bool invensense3_config (struct invensense3_t *inv)
Configure the Invensense 3 device register by register.
static bool invensense3_reset_fifo (struct invensense3_t *inv)
Reset FIFO (can be useful in some situations)
static int samples_from_odr (int odr)
void invensense3_init (struct invensense3_t *inv)
Initialize the invensense v3 sensor instance.
void invensense3_periodic (struct invensense3_t *inv)
Should be called periodically to request sensor readings.
void invensense3_event (struct invensense3_t *inv)
Should be called in the event thread.
Variables
static const struct FloatRates invensense3_gyro_scale_f [8]
static const struct FloatVect3 invensense3_accel_scale_f [5]
static const uint16_t invensense3_aaf [][4]
static const uint16_t invensense3_aaf4x605 [][4]
static const uint8_t invensense3_fifo_sample_size [4] = {8,8,16,20}
Detailed Description
Driver for the Invensense v3 IMUs ICM40605, ICM40609, ICM42605, IIM42652 and ICM42688.
Definition in file invensense3.c.
Function Documentation
invensense3_config()
static bool invensense3_config (struct invensense3_t * inv) static
Configure the Invensense 3 device register by register.
Parameters
inv The invensense v3 instance
Returns
true When the configuration is completed
false Still busy configuring
Definition at line 825 of file invensense3.c.
References ACCEL_AAF_BITSHIFT_SHIFT, ACCEL_AAF_DELT_SHIFT, ACCEL_FS_SEL_SHIFT, ACCEL_MODE_LN, ACCEL_MODE_SHIFT, ACCEL_ODR_SHIFT, BIT_DEVICE_CONFIG_SOFT_RESET_CONFIG, BIT_FIFO_CONFIG1_ACCEL_EN, BIT_FIFO_CONFIG1_GYRO_EN, BIT_FIFO_CONFIG1_TEMP_EN, BIT_FIFO_FULL_INT_EN, BIT_FIFO_THS_INT_EN, BIT_INT_ASYNC_RESET, BIT_UI_DRDY_INT_EN, FIFO_CONFIG_MODE_SHIFT, FIFO_CONFIG_MODE_STOP_ON_FULL, FIFO_COUNT_REC, foo, get_sys_time_usec(), GYRO_AAF_BITSHIFT_SHIFT, GYRO_FS_SEL_SHIFT, GYRO_MODE_LN, GYRO_MODE_SHIFT, GYRO_ODR_SHIFT, INV3REG_ACCEL_CONFIG0, INV3REG_ACCEL_CONFIG_STATIC2, INV3REG_ACCEL_CONFIG_STATIC3, INV3REG_ACCEL_CONFIG_STATIC4, INV3REG_DEVICE_CONFIG, INV3REG_FIFO_CONFIG, INV3REG_FIFO_CONFIG1, INV3REG_FIFO_CONFIG2, INV3REG_FIFO_CONFIG3, INV3REG_GYRO_CONFIG0, INV3REG_GYRO_CONFIG_STATIC2, INV3REG_GYRO_CONFIG_STATIC3, INV3REG_GYRO_CONFIG_STATIC4, INV3REG_GYRO_CONFIG_STATIC5, INV3REG_INT_CONFIG1, INV3REG_INT_SOURCE0, INV3REG_INTF_CONFIG0, INV3REG_INTF_CONFIG1, INV3REG_PWR_MGMT0, INVENSENSE3_ICM40609, INVENSENSE3_PARSER_FIFO, INVENSENSE3_PARSER_REGISTERS, invensense3_register_write(), and invensense3_reset_fifo().
Referenced by invensense3_event(), and invensense3_periodic().
invensense3_event()
void invensense3_event (struct invensense3_t * inv)
Should be called in the event thread.
Checks the response of the WHO_AM_I reading
Configures the sensor and reads the responses
Parse and request the sensor data from the FIFO buffers
Parameters
inv The invensense v3 instance
Definition at line 315 of file invensense3.c.
References foo, I2CTransDone, I2CTransFailed, I2CTransSuccess, INV3_WHOAMI_ICM40605, INV3_WHOAMI_ICM40609, INV3_WHOAMI_ICM42605, INV3_WHOAMI_ICM42688, INV3_WHOAMI_IIM42652, INV3REG_BANK_SEL, INV3REG_FIFO_COUNTH, invensense3_config(), INVENSENSE3_CONFIG, invensense3_fifo_sample_size, invensense3_fix_config(), INVENSENSE3_I2C, INVENSENSE3_ICM40605, INVENSENSE3_ICM40609, INVENSENSE3_ICM42605, INVENSENSE3_ICM42688, INVENSENSE3_IDLE, INVENSENSE3_IIM42652, invensense3_parse_fifo_data(), invensense3_parse_reg_data(), INVENSENSE3_PARSER_FIFO, INVENSENSE3_PARSER_REGISTERS, invensense3_register_read(), INVENSENSE3_RUNNING, INVENSENSE3_SPI, Min, n_samples, SPITransDone, SPITransFailed, and SPITransSuccess.
Referenced by imu_cube_event(), imu_icm42688_event(), and imu_pixhawk6x_event().
invensense3_fix_config()
static void invensense3_fix_config (struct invensense3_t * inv) static
This fixes the configuration errors and sets the correct scalings.
Parameters
inv The invensense v3 instance
Definition at line 546 of file invensense3.c.
References foo, imu_set_defaults_accel(), imu_set_defaults_gyro(), invensense3_aaf, invensense3_aaf4x605, INVENSENSE3_ACCEL_ODR_100HZ, INVENSENSE3_ACCEL_ODR_12_5HZ, INVENSENSE3_ACCEL_ODR_16KHZ, INVENSENSE3_ACCEL_ODR_1_5625HZ, INVENSENSE3_ACCEL_ODR_1KHZ, INVENSENSE3_ACCEL_ODR_200HZ, INVENSENSE3_ACCEL_ODR_25HZ, INVENSENSE3_ACCEL_ODR_2KHZ, INVENSENSE3_ACCEL_ODR_32KHZ, INVENSENSE3_ACCEL_ODR_3_125HZ, INVENSENSE3_ACCEL_ODR_4KHZ, INVENSENSE3_ACCEL_ODR_500HZ, INVENSENSE3_ACCEL_ODR_50HZ, INVENSENSE3_ACCEL_ODR_6_25HZ, INVENSENSE3_ACCEL_ODR_8KHZ, INVENSENSE3_ACCEL_RANGE_16G, INVENSENSE3_ACCEL_RANGE_4G, invensense3_accel_scale_f, INVENSENSE3_GYRO_ODR_100HZ, INVENSENSE3_GYRO_ODR_12_5HZ, INVENSENSE3_GYRO_ODR_16KHZ, INVENSENSE3_GYRO_ODR_1_5625HZ, INVENSENSE3_GYRO_ODR_1KHZ, INVENSENSE3_GYRO_ODR_200HZ, INVENSENSE3_GYRO_ODR_25HZ, INVENSENSE3_GYRO_ODR_2KHZ, INVENSENSE3_GYRO_ODR_32KHZ, INVENSENSE3_GYRO_ODR_3_125HZ, INVENSENSE3_GYRO_ODR_4KHZ, INVENSENSE3_GYRO_ODR_500HZ, INVENSENSE3_GYRO_ODR_50HZ, INVENSENSE3_GYRO_ODR_6_25HZ, INVENSENSE3_GYRO_ODR_8KHZ, invensense3_gyro_scale_f, INVENSENSE3_ICM40605, INVENSENSE3_ICM40609, INVENSENSE3_ICM42605, and RMAT_COPY.
Referenced by invensense3_event().
invensense3_init()
void invensense3_init (struct invensense3_t * inv)
Initialize the invensense v3 sensor instance.
Parameters
inv The structure containing the configuration of the invensense v3 instance
Definition at line 211 of file invensense3.c.
References foo, I2CTransDone, INVENSENSE3_IDLE, INVENSENSE3_SAMPLE_SIZE_PK3, INVENSENSE3_SPI, INVENSENSE3_UNKOWN, Min, samples_from_odr(), SPICphaEdge2, SPICpolIdleHigh, SPIDiv16, SPIDss8bit, SPIMSBFirst, SPISelectUnselect, and SPITransDone.
Referenced by imu_cube_init(), imu_icm42688_init(), and imu_pixhawk6x_init().
invensense3_parse_fifo_data()
static void invensense3_parse_fifo_data (struct invensense3_t * inv, uint8_t * data, uint16_t samples) static
Parse the FIFO buffer data.
Parameters
inv The invensense v3 instance
data The FIFO buffer data to parse
len The length of the FIFO buffer
Definition at line 446 of file invensense3.c.
References foo, get_sys_time_usec(), INVENSENSE3_FIFO_BUFFER_LEN, invensense3_fifo_sample_size, Min, Int32Rates::p, Int32Rates::q, Int32Rates::r, Int32Vect3::x, Int32Vect3::y, and Int32Vect3::z.
Referenced by invensense3_event().
invensense3_parse_reg_data()
static void invensense3_parse_reg_data (struct invensense3_t * inv, uint8_t * data) static
Parse data from registers.
Parameters
inv The invensense v3 instance
data The data from all registers (DATA_TEMP, DATA_ACCEL and DATA_GYRO)
Definition at line 518 of file invensense3.c.
References foo, get_sys_time_usec(), Int32Rates::p, Int32Rates::q, Int32Rates::r, Int32Vect3::x, Int32Vect3::y, and Int32Vect3::z.
Referenced by invensense3_event().
invensense3_periodic()
void invensense3_periodic (struct invensense3_t * inv)
Should be called periodically to request sensor readings.
First detects the sensor using WHO_AM_I reading
Configures the sensor according the users requested configuration
Requests a sensor reading by reading the FIFO_COUNT register
Parameters
inv The invensense v3 instance
Definition at line 263 of file invensense3.c.
References foo, I2CTransDone, INV3REG_FIFO_COUNTH, INV3REG_TEMP_DATA1, INV3REG_WHO_AM_I, invensense3_config(), INVENSENSE3_CONFIG, invensense3_fifo_sample_size, INVENSENSE3_I2C, INVENSENSE3_IDLE, INVENSENSE3_PARSER_FIFO, INVENSENSE3_PARSER_REGISTERS, invensense3_register_read(), INVENSENSE3_RUNNING, INVENSENSE3_SPI, Min, and SPITransDone.
Referenced by imu_cube_periodic(), imu_icm42688_periodic(), and imu_pixhawk6x_periodic().
invensense3_register_read()
static bool invensense3_register_read (struct invensense3_t * inv, uint16_t bank_reg, uint16_t size) static
Read a register based on a combined bank/regsiter value.
Parameters
inv The invensense v3 instance
bank_reg The bank is shifted 8 bits left, adn register is &0xFF
size The size to read (already 1 is added for the transmission of the register to read)
Returns
true If we initiated the register read succesfully
false First we are busy switching the register bank
Definition at line 751 of file invensense3.c.
References foo, i2c_transceive(), INV3_READ_FLAG, invensense3_select_bank(), INVENSENSE3_SPI, and spi_submit().
Referenced by invensense3_event(), and invensense3_periodic().
invensense3_register_write()
static bool invensense3_register_write (struct invensense3_t * inv, uint16_t bank_reg, uint8_t value) static
Write a register based on a combined bank/regsiter value.
Parameters
inv The invensense v3 instance
bank_reg The bank is shifted 8 bits left, adn register is &0xFF
value The value to write to the register
Returns
true Whenever the register write was started
false First we are busy switching the register bank
Definition at line 715 of file invensense3.c.
References foo, i2c_transmit(), invensense3_select_bank(), INVENSENSE3_SPI, and spi_submit().
Referenced by invensense3_config(), and invensense3_reset_fifo().
invensense3_reset_fifo()
static bool invensense3_reset_fifo (struct invensense3_t * inv) static
Reset FIFO (can be useful in some situations)
Parameters
inv The invensense v3 instance
Returns
true When reset is done
Definition at line 812 of file invensense3.c.
References BIT_SIGNAL_PATH_RESET_FIFO_FLUSH, foo, INV3REG_SIGNAL_PATH_RESET, and invensense3_register_write().
Referenced by invensense3_config().
invensense3_select_bank()
static bool invensense3_select_bank (struct invensense3_t * inv, uint8_t bank) static
Select the correct register bank.
Parameters
inv The invensense v3 instance
bank The bank ID to select
Returns
true The bank change has been requested
false The register bank is already correct
Definition at line 785 of file invensense3.c.
References foo, i2c_transmit(), INV3REG_BANK_SEL, INVENSENSE3_SPI, and spi_submit().
Referenced by invensense3_register_read(), and invensense3_register_write().
samples_from_odr()
static int samples_from_odr (int odr) static
Definition at line 969 of file invensense3.c.
References foo, INVENSENSE3_GYRO_ODR_200HZ, INVENSENSE3_GYRO_ODR_32KHZ, and INVENSENSE3_GYRO_ODR_500HZ.
Referenced by invensense3_init().
Variable Documentation
invensense3_aaf
const uint16_t invensense3_aaf[][4] static
Definition at line 72 of file invensense3.c.
Referenced by invensense3_fix_config().
invensense3_aaf4x605
const uint16_t invensense3_aaf4x605[][4] static
Definition at line 138 of file invensense3.c.
Referenced by invensense3_fix_config().
invensense3_accel_scale_f
const struct FloatVect3 invensense3_accel_scale_f[5] static
Initial value:
= {
  {9.81, 9.81, 9.81},
  {4.905, 4.905, 4.905},
  {2.4525,  2.4525,  2.4525},
  {1.22583, 1.22583, 1.22583},
  {0.61312, 0.61312, 0.61312},
}
Definition at line 63 of file invensense3.c.
Referenced by invensense3_fix_config().
invensense3_fifo_sample_size
const uint8_t invensense3_fifo_sample_size[4] = {8,8,16,20} static
Definition at line 204 of file invensense3.c.
Referenced by invensense3_event(), invensense3_parse_fifo_data(), and invensense3_periodic().
invensense3_gyro_scale_f
const struct FloatRates invensense3_gyro_scale_f[8] static
Initial value:
= {
  {4.36332, 4.36332, 4.36332},
  {2.18166, 2.18166, 2.18166},
  {1.09083, 1.09083, 1.09083},
  {0.545415, 0.545415, 0.545415},
  {0.272707, 0.272707, 0.272707},
  {0.136353, 0.136353, 0.136353},
  {0.0681769, 0.0681769, 0.0681769},
  {0.0340884, 0.0340884, 0.0340884},
}
Definition at line 51 of file invensense3.c.
Referenced by invensense3_fix_config().