Paparazzi UAS: sw/airborne/peripherals/invensense2.c File Reference
invensense2.c File Reference
Driver for the Invensense V2 IMUs ICM20948, ICM20648 and ICM20649.
#include "peripherals/invensense2.h"
#include "peripherals/invensense2_regs.h"
#include "math/pprz_isa.h"
#include "math/pprz_algebra_int.h"
#include "modules/imu/imu.h"
#include "modules/core/abi.h"
#include "mcu_periph/gpio_arch.h"
Functions
static void invensense2_parse_data (struct invensense2_t *inv, volatile uint8_t *data, uint16_t len)
Parse the FIFO buffer data.
static void invensense2_fix_config (struct invensense2_t *inv)
This fixes the configuration errors and sets the correct scalings.
static bool invensense2_register_write (struct invensense2_t *inv, uint16_t bank_reg, uint8_t value)
Write a register based on a combined bank/regsiter value.
static bool invensense2_register_read (struct invensense2_t *inv, uint16_t bank_reg, uint16_t size)
Read a register based on a combined bank/regsiter value.
static bool invensense2_select_bank (struct invensense2_t *inv, uint8_t bank)
Select the correct register bank.
static bool invensense2_config (struct invensense2_t *inv)
Configure the Invensense 2 device register by register.
void invensense2_init (struct invensense2_t *inv)
Initialize the invensense v2 sensor instance.
void invensense2_periodic (struct invensense2_t *inv)
Should be called periodically to request sensor readings.
void invensense2_event (struct invensense2_t *inv)
Should be called in the event thread.
Variables
static const struct FloatRates invensense2_gyro_scale_f [5]
static const struct FloatVect3 invensense2_accel_scale_f [5]
Detailed Description
Driver for the Invensense V2 IMUs ICM20948, ICM20648 and ICM20649.
Definition in file invensense2.c.
Function Documentation
invensense2_config()
static bool invensense2_config (struct invensense2_t * inv) static
Configure the Invensense 2 device register by register.
Parameters
inv The invensense v2 instance
Returns
true When the configuration is completed
false Still busy configuring
Definition at line 447 of file invensense2.c.
References ACCEL_DLPF_CFG_SHIFT, ACCEL_FS_SEL_SHIFT, BIT_ACCEL_DLPF_ENABLE, BIT_ACCEL_FIFO_EN, BIT_GYRO_DLPF_ENABLE, BIT_PWR_MGMT_1_CLK_AUTO, BIT_PWR_MGMT_1_DEVICE_RESET, BIT_TEMP_FIFO_EN, BIT_USER_CTRL_FIFO_EN, BIT_USER_CTRL_I2C_IF_DIS, BIT_USER_CTRL_I2C_MST_RESET, BIT_USER_CTRL_SRAM_RESET, BIT_XG_FIFO_EN, BIT_YG_FIFO_EN, BIT_ZG_FIFO_EN, foo, get_sys_time_usec(), GYRO_DLPF_CFG_SHIFT, GYRO_FS_SEL_SHIFT, INV2REG_ACCEL_CONFIG, INV2REG_FIFO_EN_2, INV2REG_FIFO_MODE, INV2REG_FIFO_RST, INV2REG_GYRO_CONFIG_1, INV2REG_GYRO_SMPLRT_DIV, INV2REG_INT_ENABLE_1, INV2REG_PWR_MGMT_1, INV2REG_TIMEBASE_CORRECTIO, INV2REG_USER_CTRL, INVENSENSE2_ACCEL_DLPF_OFF, INVENSENSE2_GYRO_DLPF_OFF, INVENSENSE2_ICM20649, invensense2_register_read(), invensense2_register_write(), and INVENSENSE2_SPI.
Referenced by invensense2_event(), and invensense2_periodic().
invensense2_event()
void invensense2_event (struct invensense2_t * inv)
Should be called in the event thread.
Checks the response of the WHO_AM_I reading
Configures the sensor and reads the responses
Parse and request the sensor data from the FIFO buffers
Parameters
inv The invensense v2 instance
Definition at line 142 of file invensense2.c.
References foo, I2CTransDone, I2CTransFailed, I2CTransSuccess, INV2_WHOAMI_ICM20648, INV2_WHOAMI_ICM20649, INV2_WHOAMI_ICM20948, INV2REG_BANK_SEL, INV2REG_FIFO_COUNTH, invensense2_config(), INVENSENSE2_CONFIG, invensense2_fix_config(), INVENSENSE2_I2C, INVENSENSE2_ICM20648, INVENSENSE2_ICM20649, INVENSENSE2_ICM20948, INVENSENSE2_IDLE, invensense2_parse_data(), invensense2_register_read(), INVENSENSE2_RUNNING, INVENSENSE2_SAMPLE_SIZE, INVENSENSE2_SPI, SPITransDone, SPITransFailed, and SPITransSuccess.
Referenced by imu_cube_event(), and imu_pixhawk6x_event().
invensense2_fix_config()
static void invensense2_fix_config (struct invensense2_t * inv) static
This fixes the configuration errors and sets the correct scalings.
Parameters
inv The invensense v2 instance
Definition at line 316 of file invensense2.c.
References foo, imu_set_defaults_accel(), imu_set_defaults_gyro(), INVENSENSE2_ACCEL_RANGE_16G, INVENSENSE2_ACCEL_RANGE_2G, INVENSENSE2_ACCEL_RANGE_30G, INVENSENSE2_ACCEL_RANGE_4G, invensense2_accel_scale_f, INVENSENSE2_GYRO_RANGE_2000DPS, INVENSENSE2_GYRO_RANGE_250DPS, INVENSENSE2_GYRO_RANGE_4000DPS, INVENSENSE2_GYRO_RANGE_500DPS, invensense2_gyro_scale_f, and INVENSENSE2_ICM20649.
Referenced by invensense2_event().
invensense2_init()
void invensense2_init (struct invensense2_t * inv)
Initialize the invensense v2 sensor instance.
Parameters
inv The structure containing the configuration of the invensense v2 instance
Definition at line 69 of file invensense2.c.
References foo, I2CTransDone, INVENSENSE2_IDLE, INVENSENSE2_SPI, INVENSENSE2_UNKOWN, SPICphaEdge2, SPICpolIdleHigh, SPIDiv16, SPIDss8bit, SPIMSBFirst, SPISelectUnselect, and SPITransDone.
Referenced by imu_cube_init(), and imu_pixhawk6x_init().
invensense2_parse_data()
static void invensense2_parse_data (struct invensense2_t * inv, volatile uint8_t * data, uint16_t len) static
Parse the FIFO buffer data.
Parameters
inv The invensense v2 instance
data The FIFO buffer data to parse
len The length of the FIFO buffer
Definition at line 267 of file invensense2.c.
References foo, get_sys_time_usec(), INVENSENSE2_ACCEL_DLPF_OFF, INVENSENSE2_GYRO_DLPF_OFF, INVENSENSE2_SAMPLE_CNT, INVENSENSE2_SAMPLE_SIZE, Int32Rates::p, Int32Rates::q, Int32Rates::r, Int32Vect3::x, Int32Vect3::y, and Int32Vect3::z.
Referenced by invensense2_event().
invensense2_periodic()
void invensense2_periodic (struct invensense2_t * inv)
Should be called periodically to request sensor readings.
First detects the sensor using WHO_AM_I reading
Configures the sensor according the users requested configuration
Requests a sensor reading by reading the FIFO_COUNT register
Parameters
inv The invensense v2 instance
Definition at line 109 of file invensense2.c.
References foo, I2CTransDone, INV2REG_FIFO_COUNTH, INV2REG_WHO_AM_I, invensense2_config(), INVENSENSE2_CONFIG, INVENSENSE2_I2C, INVENSENSE2_IDLE, invensense2_register_read(), INVENSENSE2_RUNNING, INVENSENSE2_SPI, and SPITransDone.
Referenced by imu_cube_periodic(), and imu_pixhawk6x_periodic().
invensense2_register_read()
static bool invensense2_register_read (struct invensense2_t * inv, uint16_t bank_reg, uint16_t size) static
Read a register based on a combined bank/regsiter value.
Parameters
inv The invensense v2 instance
bank_reg The bank is shifted 8 bits left, adn register is &0xFF
size The size to read (already 1 is added for the transmission of the register to read)
Returns
true If we initiated the register read succesfully
false First we are busy switching the register bank
Definition at line 382 of file invensense2.c.
References foo, i2c_transceive(), INV2_READ_FLAG, invensense2_select_bank(), INVENSENSE2_SPI, and spi_submit().
Referenced by invensense2_config(), invensense2_event(), and invensense2_periodic().
invensense2_register_write()
static bool invensense2_register_write (struct invensense2_t * inv, uint16_t bank_reg, uint8_t value) static
Write a register based on a combined bank/regsiter value.
Parameters
inv The invensense v2 instance
bank_reg The bank is shifted 8 bits left, adn register is &0xFF
value The value to write to the register
Returns
true Whenever the register write was started
false First we are busy switching the register bank
Definition at line 345 of file invensense2.c.
References foo, i2c_transmit(), invensense2_select_bank(), INVENSENSE2_SPI, and spi_submit().
Referenced by invensense2_config().
invensense2_select_bank()
static bool invensense2_select_bank (struct invensense2_t * inv, uint8_t bank) static
Select the correct register bank.
Parameters
inv The invensense v2 instance
bank The bank ID to select
Returns
true The bank change has been requested
false The register bank is already correct
Definition at line 417 of file invensense2.c.
References foo, i2c_transmit(), INV2REG_BANK_SEL, INVENSENSE2_SPI, and spi_submit().
Referenced by invensense2_register_read(), and invensense2_register_write().
Variable Documentation
invensense2_accel_scale_f
const struct FloatVect3 invensense2_accel_scale_f[5] static
Initial value:
= {
  {0.61312, 0.61312, 0.61312},
  {1.22583, 1.22583, 1.22583},
  {2.4525,  2.4525,  2.4525},
  {4.905, 4.905, 4.905},
  {9.196875, 9.196875, 9.196875},
}
Definition at line 56 of file invensense2.c.
Referenced by invensense2_fix_config().
invensense2_gyro_scale_f
const struct FloatRates invensense2_gyro_scale_f[5] static
Initial value:
= {
  {0.545415, 0.545415, 0.545415},
  {1.09083, 1.09083, 1.09083},
  {2.18166, 2.18166, 2.18166},
  {4.36332, 4.36332, 4.36332},
  {8.72664, 8.72664, 8.72664},
}
Definition at line 47 of file invensense2.c.
Referenced by invensense2_fix_config().