Paparazzi UAS: sw/airborne/peripherals/invensense3_456.c File Reference
invensense3_456.c File Reference
Driver for the Invensense 456XY IMUs:
#include "peripherals/invensense3_456.h"
#include "peripherals/invensense3_456_regs.h"
#include "math/pprz_isa.h"
#include "math/pprz_algebra_int.h"
#include "math/pprz_algebra_float.h"
#include "modules/imu/imu.h"
#include "modules/core/abi.h"
#include "mcu_periph/gpio_arch.h"
#include "std.h"
#include <string.h>
#include "modules/datalink/telemetry.h"
Functions
static void invensense3_456_parse_fifo_data (struct invensense3_456_t *inv, uint8_t *data, uint16_t samples)
Parse the FIFO buffer data.
static void invensense3_456_set_scalings (struct invensense3_456_t *inv)
This sets the correct scalings.
static bool invensense3_456_register_write (struct invensense3_456_t *inv, uint8_t reg, uint8_t value)
Write a register.
static bool invensense3_456_register_read (struct invensense3_456_t *inv, uint8_t reg, uint16_t size)
Read a register based on a combined bank/regsiter value.
static bool invensense3_456_config (struct invensense3_456_t *inv)
Configure the Invensense 3 device register by register.
static int samples_from_odr (int odr)
void invensense3_456_init (struct invensense3_456_t *inv)
Initialize the invensense v3 sensor instance.
void invensense3_456_periodic (struct invensense3_456_t *inv)
Should be called periodically to request sensor readings.
void invensense3_456_event (struct invensense3_456_t *inv)
Should be called in the event thread.
static int32_t reassemble_uint20 (uint8_t msb, uint8_t bits, uint8_t lsb)
static bool invensense3_register_write_bank (struct invensense3_456_t *inv, uint16_t bank_addr, uint16_t reg, uint8_t val)
Write to a register in a specific bank.
Detailed Description
Driver for the Invensense 456XY IMUs:
ICM45686
Definition in file invensense3_456.c.
Function Documentation
invensense3_456_config()
static bool invensense3_456_config (struct invensense3_456_t * inv) static
Configure the Invensense 3 device register by register.
REF: https://github.com/ArduPilot/ardupilot/blob/85a8a55611a95d4c59052f79f56744a93a9c5a63/libraries/AP_InertialSensor/AP_InertialSensor_Invensensev3.cpp#L933
Parameters
inv The invensense v3 instance
Returns
true When the configuration is completed
false Still busy configuring
Definition at line 415 of file invensense3_456.c.
References ACCEL_FS_SEL_SHIFT, ACCEL_ODR_SHIFT, foo, get_sys_time_usec(), GYRO_FS_SEL_SHIFT, GYRO_ODR_SHIFT, INV3BANK_456_IPREG_SYS1_ADDR, INV3BANK_456_IPREG_SYS2_ADDR, INV3BANK_456_IPREG_TOP1_ADDR, INV3REG_456_ACCEL_CONFIG0, INV3REG_456_FIFO_CONFIG0, INV3REG_456_FIFO_CONFIG3, INV3REG_456_GYRO_CONFIG0, INV3REG_456_PWR_MGMT0, INV3REG_456_REG_MISC2, INV_456_BASE_FIFO3_CONFIG_VALUE, INV_456_FIFO_IF_EN, invensense3_456_register_write(), and invensense3_register_write_bank().
Referenced by invensense3_456_event(), and invensense3_456_periodic().
invensense3_456_event()
void invensense3_456_event (struct invensense3_456_t * inv)
Should be called in the event thread.
Checks the response of the WHO_AM_I reading
Configures the sensor and reads the responses
Parse and request the sensor data from the FIFO buffers
Parameters
inv The invensense v3 instance
Definition at line 137 of file invensense3_456.c.
References foo, INV3_456_WHOAMI_ICM45686, INV3REG_456_FIFO_COUNTH, invensense3_456_config(), INVENSENSE3_456_CONFIG, INVENSENSE3_456_ICM45686, INVENSENSE3_456_IDLE, invensense3_456_parse_fifo_data(), invensense3_456_register_read(), INVENSENSE3_456_RUNNING, invensense3_456_set_scalings(), Min, n_samples, SPITransDone, SPITransFailed, and SPITransSuccess.
Referenced by imu_cube_event().
invensense3_456_init()
void invensense3_456_init (struct invensense3_456_t * inv)
Initialize the invensense v3 sensor instance.
Parameters
inv The structure containing the configuration of the invensense v3 instance
Definition at line 57 of file invensense3_456.c.
References foo, INVENSENSE3_456_IDLE, INVENSENSE3_456_UNKOWN, samples_from_odr(), SPICphaEdge2, SPICpolIdleHigh, SPIDiv16, SPIDss8bit, SPIMSBFirst, SPISelectUnselect, and SPITransDone.
Referenced by imu_cube_init().
invensense3_456_parse_fifo_data()
static void invensense3_456_parse_fifo_data (struct invensense3_456_t * inv, uint8_t * data, uint16_t samples) static
Parse the FIFO buffer data.
Parameters
inv The invensense v3 instance
data The FIFO buffer data to parse
len The length of the FIFO buffer
Definition at line 247 of file invensense3_456.c.
References FIFODataHighRes::accel, FIFODataHighRes::ax, FIFODataHighRes::ay, FIFODataHighRes::az, foo, get_sys_time_usec(), FIFODataHighRes::gx, FIFODataHighRes::gy, FIFODataHighRes::gyro, FIFODataHighRes::gz, FIFODataHighRes::header, INVENSENSE3_456_FIFO_BUFFER_LEN, Min, reassemble_uint20(), and FIFODataHighRes::temperature.
Referenced by invensense3_456_event().
invensense3_456_periodic()
void invensense3_456_periodic (struct invensense3_456_t * inv)
Should be called periodically to request sensor readings.
First detects the sensor using WHO_AM_I reading
Configures the sensor according the users requested configuration
Requests a sensor reading by reading the FIFO_COUNT register
Parameters
inv The invensense v3 instance
Definition at line 95 of file invensense3_456.c.
References foo, INV3REG_456_FIFO_COUNTH, INV3REG_456_WHOAMI, invensense3_456_config(), INVENSENSE3_456_CONFIG, INVENSENSE3_456_IDLE, invensense3_456_register_read(), INVENSENSE3_456_RUNNING, Min, and SPITransDone.
Referenced by imu_cube_periodic().
invensense3_456_register_read()
static bool invensense3_456_register_read (struct invensense3_456_t * inv, uint8_t reg, uint16_t size) static
Read a register based on a combined bank/regsiter value.
Parameters
inv The invensense v3 instance
reg The address of the register to read
size The size to read (already 1 is added for the transmission of the register to read)
Returns
true If we initiated the register read succesfully
false First we are busy switching the register bank
Definition at line 396 of file invensense3_456.c.
References foo, INV3_456_READ_FLAG, and spi_submit().
Referenced by invensense3_456_event(), and invensense3_456_periodic().
invensense3_456_register_write()
static bool invensense3_456_register_write (struct invensense3_456_t * inv, uint8_t reg, uint8_t value) static
Write a register.
Parameters
inv The invensense v3 instance
reg The address of the register to write to
value The value to write to the register
Returns
true Whenever the register write was started
Definition at line 349 of file invensense3_456.c.
References foo, and spi_submit().
Referenced by invensense3_456_config().
invensense3_456_set_scalings()
static void invensense3_456_set_scalings (struct invensense3_456_t * inv) static
This sets the correct scalings.
Parameters
inv The invensense v3 instance
Definition at line 297 of file invensense3_456.c.
References ACCEL_BFP_OF_REAL, foo, imu_set_defaults_accel(), imu_set_defaults_gyro(), INVENSENSE3_456_ODR_100HZ, INVENSENSE3_456_ODR_1_6KHZ, INVENSENSE3_456_ODR_200HZ, INVENSENSE3_456_ODR_25HZ, INVENSENSE3_456_ODR_3_2KHZ, INVENSENSE3_456_ODR_400HZ, INVENSENSE3_456_ODR_50HZ, INVENSENSE3_456_ODR_6_4KHZ, INVENSENSE3_456_ODR_800HZ, and RATE_BFP_OF_REAL.
Referenced by invensense3_456_event().
invensense3_register_write_bank()
static bool invensense3_register_write_bank (struct invensense3_456_t * inv, uint16_t bank_addr, uint16_t reg, uint8_t val) static
Write to a register in a specific bank.
Parameters
inv The invensense v3 instance
bank_addr The address of the bank to write to
reg The address of the register to write to
value The value to write to the register
Returns
true Whenever the register write was started
Definition at line 371 of file invensense3_456.c.
References foo, INV3REG_456_IREG_ADDRH, spi_submit(), and val.
Referenced by invensense3_456_config().
reassemble_uint20()
static int32_t reassemble_uint20 (uint8_t msb, uint8_t bits, uint8_t lsb) inline static
Definition at line 225 of file invensense3_456.c.
References foo.
Referenced by invensense3_456_parse_fifo_data().
samples_from_odr()
static int samples_from_odr (int odr) static
Definition at line 495 of file invensense3_456.c.
References foo, INVENSENSE3_456_ODR_100HZ, INVENSENSE3_456_ODR_1_6KHZ, INVENSENSE3_456_ODR_200HZ, INVENSENSE3_456_ODR_25HZ, INVENSENSE3_456_ODR_3_2KHZ, INVENSENSE3_456_ODR_400HZ, INVENSENSE3_456_ODR_50HZ, INVENSENSE3_456_ODR_6_4KHZ, and INVENSENSE3_456_ODR_800HZ.
Referenced by invensense3_456_init().