Paparazzi UAS: sw/airborne/modules/meteo/ir_mlx.h File Reference
ir_mlx.h File Reference
#include "std.h"
Macros
#define MLX90614_TA 0x06
#define MLX90614_TOBJ 0x07
#define MLX90614_SADR 0x2E
#define MLX90614_ID_0 0x3C
#define MLX90614_ID_1 0x3D
#define MLX90614_ID_2 0x3E
#define MLX90614_ID_3 0x3F
Enumerations
enum mlx_type {
IR_MLX_ADDR_CHANGE, IR_MLX_ADDR_ERASE, IR_MLX_ADDR_SET, IR_MLX_UNINIT,
IR_MLX_RD_ID_0, IR_MLX_RD_ID_1, IR_MLX_RD_ID_2, IR_MLX_RD_ID_3,
IR_MLX_IDLE, IR_MLX_RD_CASE_TEMP, IR_MLX_RD_OBJ_TEMP
}
Functions
void ir_mlx_crc (unsigned char addr, volatile unsigned char *data)
void ir_mlx_init (void)
void ir_mlx_periodic (void)
void ir_mlx_event (void)
Macro Definition Documentation
#define MLX90614_ID_0 0x3C
Definition at line 9 of file ir_mlx.h.
Referenced by ir_mlx_periodic().
#define MLX90614_ID_1 0x3D
Definition at line 10 of file ir_mlx.h.
Referenced by ir_mlx_event().
#define MLX90614_ID_2 0x3E
Definition at line 11 of file ir_mlx.h.
Referenced by ir_mlx_event().
#define MLX90614_ID_3 0x3F
Definition at line 12 of file ir_mlx.h.
Referenced by ir_mlx_event().
#define MLX90614_SADR 0x2E
Definition at line 8 of file ir_mlx.h.
Referenced by ir_mlx_periodic().
#define MLX90614_TA 0x06
Definition at line 6 of file ir_mlx.h.
Referenced by ir_mlx_periodic().
#define MLX90614_TOBJ 0x07
Definition at line 7 of file ir_mlx.h.
Referenced by ir_mlx_event().
Enumeration Type Documentation
enum mlx_type
Enumerator
IR_MLX_ADDR_CHANGE
IR_MLX_ADDR_ERASE
IR_MLX_ADDR_SET
IR_MLX_UNINIT
IR_MLX_RD_ID_0
IR_MLX_RD_ID_1
IR_MLX_RD_ID_2
IR_MLX_RD_ID_3
IR_MLX_IDLE
IR_MLX_RD_CASE_TEMP
IR_MLX_RD_OBJ_TEMP
Definition at line 14 of file ir_mlx.h.
Function Documentation
void ir_mlx_crc (unsigned char addr, volatile unsigned char * data)
Definition at line 63 of file ir_mlx.c.
References crc.
Referenced by ir_mlx_periodic().
void ir_mlx_event (void)
Definition at line 138 of file ir_mlx.c.
References i2c_transaction::buf, DefaultChannel, DefaultDevice, i2c_transceive(), I2CTransDone, I2CTransSuccess, ir_mlx_id_01, ir_mlx_id_23, IR_MLX_IDLE, ir_mlx_itemp_case, ir_mlx_itemp_obj, IR_MLX_RD_CASE_TEMP, IR_MLX_RD_ID_0, IR_MLX_RD_ID_1, IR_MLX_RD_ID_2, IR_MLX_RD_ID_3, IR_MLX_RD_OBJ_TEMP, ir_mlx_status, ir_mlx_temp_case, ir_mlx_temp_obj, MLX90614_ADDR, MLX90614_ID_1, MLX90614_ID_2, MLX90614_ID_3, MLX90614_TOBJ, MLX_I2C_DEV, mlx_trans, and i2c_transaction::status.
void ir_mlx_init (void)
Definition at line 83 of file ir_mlx.c.
References IR_MLX_ADDR_CHANGE, ir_mlx_status, and IR_MLX_UNINIT.
void ir_mlx_periodic (void)
Definition at line 94 of file ir_mlx.c.
References i2c_transaction::buf, DefaultChannel, DefaultDevice, i2c_transceive(), i2c_transmit(), IR_MLX_ADDR_CHANGE, IR_MLX_ADDR_ERASE, IR_MLX_ADDR_SET, ir_mlx_crc(), ir_mlx_id_01, ir_mlx_id_23, IR_MLX_IDLE, IR_MLX_RD_CASE_TEMP, IR_MLX_RD_ID_0, ir_mlx_status, IR_MLX_UNINIT, MLX90614_ADDR, MLX90614_GENERAL_ADDR, MLX90614_ID_0, MLX90614_SADR, MLX90614_TA, MLX_I2C_DEV, mlx_trans, and sys_time::nb_sec.