Paparazzi UAS: sw/airborne/modules/sensors/cameras/jevois.h File Reference
jevois.h File Reference
#include "std.h"
Macros
#define JEVOIS_MSG_T1 10
JEVOIS messages types.
#define JEVOIS_MSG_N1 11
#define JEVOIS_MSG_D1 12
#define JEVOIS_MSG_T2 20
#define JEVOIS_MSG_N2 21
#define JEVOIS_MSG_D2 22
#define JEVOIS_MSG_F2 23
#define JEVOIS_MSG_T3 30
#define JEVOIS_MSG_N3 31
#define JEVOIS_MSG_D3 32
#define JEVOIS_MSG_F3 33
#define JEVOIS_NORM 1000
Normalized data from JEVOIS are between -1000 and 1000.
#define JEVOIS_HFOV RadOfDeg(45)
Camera horizontal FOV From datasheet it should be 65deg, but it seems that better results are acheived with 45.
#define JEVOIS_VFOV (3*JEVOIS_HFOV/4)
Camera vertical FOV Camera has a 4/3 ratio.
Functions
void jevois_init (void)
void jevois_event (void)
void jevois_report (void)
void jevois_send_string (char *s)
Generic function to send a string command to Jevois.
void jevois_stream (bool activate)
Start and stop streaming.
void jevois_setmapping (int number)
Set video mapping.
void jevois_send_state (void)
Send state to camera.
int jevois_extract_nb (char *in)
Extract a number from jevoid ID field.
Variables
bool jevois_stream_setting
int jevois_mapping_setting
Detailed Description
Author
Gautier Hattenberger Decoder for standardized messages from the JEVOIS smart camera (http://jevois.org)
Definition in file jevois.h.
Macro Definition Documentation
JEVOIS_HFOV
#define JEVOIS_HFOV RadOfDeg(45)
Camera horizontal FOV From datasheet it should be 65deg, but it seems that better results are acheived with 45.
Definition at line 52 of file jevois.h.
JEVOIS_MSG_D1
#define JEVOIS_MSG_D1 12
Definition at line 34 of file jevois.h.
JEVOIS_MSG_D2
#define JEVOIS_MSG_D2 22
Definition at line 37 of file jevois.h.
JEVOIS_MSG_D3
#define JEVOIS_MSG_D3 32
Definition at line 41 of file jevois.h.
JEVOIS_MSG_F2
#define JEVOIS_MSG_F2 23
Definition at line 38 of file jevois.h.
JEVOIS_MSG_F3
#define JEVOIS_MSG_F3 33
Definition at line 42 of file jevois.h.
JEVOIS_MSG_N1
#define JEVOIS_MSG_N1 11
Definition at line 33 of file jevois.h.
JEVOIS_MSG_N2
#define JEVOIS_MSG_N2 21
Definition at line 36 of file jevois.h.
JEVOIS_MSG_N3
#define JEVOIS_MSG_N3 31
Definition at line 40 of file jevois.h.
JEVOIS_MSG_T1
#define JEVOIS_MSG_T1 10
JEVOIS messages types.
Definition at line 32 of file jevois.h.
JEVOIS_MSG_T2
#define JEVOIS_MSG_T2 20
Definition at line 35 of file jevois.h.
JEVOIS_MSG_T3
#define JEVOIS_MSG_T3 30
Definition at line 39 of file jevois.h.
JEVOIS_NORM
#define JEVOIS_NORM 1000
Normalized data from JEVOIS are between -1000 and 1000.
Definition at line 45 of file jevois.h.
JEVOIS_VFOV
#define JEVOIS_VFOV (3*JEVOIS_HFOV/4)
Camera vertical FOV Camera has a 4/3 ratio.
Definition at line 59 of file jevois.h.
Function Documentation
jevois_event()
void jevois_event (void) extern
Definition at line 402 of file jevois.c.
References foo, jevois, JEVOIS_DEV, jevois_parse(), uart_char_available(), and uart_getch().
jevois_extract_nb()
int jevois_extract_nb (char * in) extern
Extract a number from jevoid ID field.
Definition at line 130 of file jevois.c.
References foo, and JEVOIS_MAX_LEN.
Referenced by jevois_send_message(), and tag_track_cb().
jevois_init()
void jevois_init (void) extern
Definition at line 113 of file jevois.c.
References jevois_t::buf, jevois_t::data_available, foo, jevois_t::idx, jevois, jevois_mapping_setting, JEVOIS_MAX_LEN, jevois_stream_setting, JV_SYNC, jevois_t::n, and jevois_t::state.
jevois_report()
void jevois_report (void) extern
Definition at line 82 of file jevois.c.
References jevois_msg_t::coord, jevois_t::data_available, DefaultChannel, DefaultDevice, jevois_msg_t::dim, foo, jevois_msg_t::id, jevois, jevois_t::msg, jevois_msg_t::nb, FloatQuat::qi, jevois_msg_t::quat, FloatQuat::qx, FloatQuat::qy, FloatQuat::qz, and jevois_msg_t::type.
Referenced by jevois_send_message().
jevois_send_state()
void jevois_send_state (void) extern
Send state to camera.
Definition at line 445 of file jevois.c.
References alt_mm, foo, jevois_send_string(), FloatQuat::qi, FloatQuat::qx, FloatQuat::qy, FloatQuat::qz, stateGetNedToBodyQuat_f(), stateGetPositionEnu_f(), EnuCoor_f::x, EnuCoor_f::y, and EnuCoor_f::z.
jevois_send_string()
void jevois_send_string (char * s) extern
Generic function to send a string command to Jevois.
Parameters
[in] s string command to send
Definition at line 412 of file jevois.c.
References JEVOIS_DEV, s, and uart_put_byte().
Referenced by jevois_send_state(), jevois_setmapping(), and jevois_stream().
jevois_setmapping()
void jevois_setmapping (int number) extern
Set video mapping.
Parameters
[in] number video mapping number
Definition at line 431 of file jevois.c.
References foo, jevois_mapping_setting, jevois_send_string(), jevois_stream(), and s.
jevois_stream()
void jevois_stream (bool activate) extern
Start and stop streaming.
Parameters
[in] activate enable or disable streaming
Definition at line 421 of file jevois.c.
References foo, jevois_send_string(), and jevois_stream_setting.
Referenced by jevois_setmapping().
Variable Documentation
jevois_mapping_setting
int jevois_mapping_setting extern
Definition at line 36 of file jevois.c.
Referenced by jevois_init(), and jevois_setmapping().
jevois_stream_setting
bool jevois_stream_setting extern
Definition at line 37 of file jevois.c.
Referenced by jevois_init(), and jevois_stream().