Paparazzi UAS: sw/airborne/modules/sensors/cameras/jevois_mavlink.h File Reference
jevois_mavlink.h File Reference
#include "mcu_periph/uart.h"
#include <mavlink/mavlink_types.h>
Macros
#define JEVOIS_DEV uart2
#define MAVLinkDev (&(JEVOIS_DEV).device)
#define MAVLinkTransmit(c) MAVLinkDev->put_byte(MAVLinkDev->periph, 0, c)
#define MAVLinkChAvailable() MAVLinkDev->char_available(MAVLinkDev->periph)
#define MAVLinkGetch() MAVLinkDev->get_byte(MAVLinkDev->periph)
#define MAVLinkSendMessage() MAVLinkDev->send_message(MAVLinkDev->periph, 0)
#define MAVLINK_USE_CONVENIENCE_FUNCTIONS
#define MAVLINK_ALIGNED_FIELDS 0
Functions
static void comm_send_ch (mavlink_channel_t chan, uint8_t ch)
void jevois_mavlink_init (void)
void jevois_mavlink_periodic (void)
void jevois_mavlink_filter_periodic (void)
void jevois_mavlink_event (void)
Variables
mavlink_system_t mavlink_system
Detailed Description
Author
MAVLab Send sensor data to jevois and read commands from jevois
Definition in file jevois_mavlink.h.
Macro Definition Documentation
JEVOIS_DEV
#define JEVOIS_DEV uart2
Definition at line 39 of file jevois_mavlink.h.
MAVLINK_ALIGNED_FIELDS
#define MAVLINK_ALIGNED_FIELDS 0
Definition at line 59 of file jevois_mavlink.h.
MAVLINK_USE_CONVENIENCE_FUNCTIONS
#define MAVLINK_USE_CONVENIENCE_FUNCTIONS
Definition at line 58 of file jevois_mavlink.h.
MAVLinkChAvailable
#define MAVLinkChAvailable () MAVLinkDev->char_available(MAVLinkDev->periph)
Definition at line 44 of file jevois_mavlink.h.
MAVLinkDev
#define MAVLinkDev (&(JEVOIS_DEV).device)
Definition at line 42 of file jevois_mavlink.h.
MAVLinkGetch
#define MAVLinkGetch () MAVLinkDev->get_byte(MAVLinkDev->periph)
Definition at line 45 of file jevois_mavlink.h.
MAVLinkSendMessage
#define MAVLinkSendMessage () MAVLinkDev->send_message(MAVLinkDev->periph, 0)
Definition at line 46 of file jevois_mavlink.h.
MAVLinkTransmit
#define MAVLinkTransmit (c) MAVLinkDev->put_byte(MAVLinkDev->periph, 0, c)
Definition at line 43 of file jevois_mavlink.h.
Function Documentation
comm_send_ch()
static void comm_send_ch (mavlink_channel_t chan, uint8_t ch) inline static
Definition at line 63 of file jevois_mavlink.h.
References foo, and MAVLinkTransmit.
jevois_mavlink_event()
void jevois_mavlink_event (void) extern
Definition at line 182 of file jevois_mavlink.c.
References vision_relative_position_struct::cnt, visual_target_struct::count, DEBUG_PRINT, foo, visual_target_struct::h, heartbeat, JEVOIS_MAVLINK_ABI_ID, jevois_vision_position, jevois_visual_target, MAVLinkChAvailable, MAVLinkGetch, msg, visual_target_struct::quality, vision_relative_position_struct::received, visual_target_struct::received, visual_target_struct::source, status, visual_target_struct::w, vision_relative_position_struct::x, visual_target_struct::x, vision_relative_position_struct::y, visual_target_struct::y, and vision_relative_position_struct::z.
jevois_mavlink_filter_periodic()
void jevois_mavlink_filter_periodic (void) extern
Definition at line 99 of file jevois_mavlink.c.
References ax_filtered, ay_filtered, az_filtered, imu, and update_butterworth_2_low_pass_int().
jevois_mavlink_init()
void jevois_mavlink_init (void) extern
Definition at line 154 of file jevois_mavlink.c.
References DefaultPeriodic, foo, jevois_mavlink_filter_init(), MAVLINK_SYSID, mavlink_system, register_periodic_telemetry(), send_jevois_mavlink_visual_position(), and send_jevois_mavlink_visual_target().
jevois_mavlink_periodic()
void jevois_mavlink_periodic (void) extern
Definition at line 168 of file jevois_mavlink.c.
References foo, mavlink_send_attitude(), mavlink_send_heartbeat(), mavlink_send_highres_imu(), and mavlink_send_set_mode().
Variable Documentation
mavlink_system
mavlink_system_t mavlink_system extern
Definition at line 72 of file mavlink.c.
Referenced by jevois_mavlink_init(), mavlink_block_message_handler(), mavlink_init(), and mavlink_wp_message_handler().