Paparazzi UAS: sw/airborne/modules/computer_vision/lib/encoding/jpeg.h File Reference
jpeg.h File Reference
Encode images with the use of the JPEG encoding.
#include "std.h"
#include "lib/vision/image.h"
Macros
#define FOUR_ZERO_ZERO 0
#define FOUR_TWO_ZERO 1
#define FOUR_TWO_TWO 2
#define FOUR_FOUR_FOUR 3
#define RGB 4
Functions
void jpeg_encode_image (struct image_t *in, struct image_t *out, uint32_t quality_factor, bool add_dri_header)
Encode an YUV422 image.
int jpeg_create_svs_header (unsigned char *buf, int32_t size, int w)
Detailed Description
Encode images with the use of the JPEG encoding.
Definition in file jpeg.h.
Macro Definition Documentation
#define FOUR_FOUR_FOUR 3
Definition at line 31 of file jpeg.h.
#define FOUR_TWO_TWO 2
Definition at line 30 of file jpeg.h.
Referenced by jpeg_encode_image(), jpeg_encodeMCU(), and jpeg_write_markers().
#define FOUR_TWO_ZERO 1
Definition at line 29 of file jpeg.h.
#define FOUR_ZERO_ZERO 0
Definition at line 28 of file jpeg.h.
Referenced by jpeg_encode_image(), jpeg_initialization(), and jpeg_write_markers().
#define RGB 4
Definition at line 32 of file jpeg.h.
Function Documentation
int jpeg_create_svs_header (unsigned char * buf, int32_t size, int w)
Definition at line 44 of file jpeg.c.
References p, s, and svs_size_code().
void jpeg_encode_image (struct image_t * in, struct image_t * out, uint32_t quality_factor, bool add_dri_header)
Encode an YUV422 image.
Parameters
[in] *in The input image
[out] *out The output JPEG image
[in] quality_factor Quality factor of the encoding (0-99)
[in] add_dri_header Add the DRI header (needed for full JPEG)
Definition at line 408 of file jpeg.c.
References image_t::buf, image_t::buf_size, JPEG_ENCODER_STRUCTURE::cols, JPEG_ENCODER_STRUCTURE::cols_in_right_mcus, FOUR_TWO_TWO, FOUR_ZERO_ZERO, image_t::h, JPEG_ENCODER_STRUCTURE::horizontal_mcus, IMAGE_GRAYSCALE, IMAGE_YUV422, JPEG_ENCODER_STRUCTURE::incr, jpeg_close_bitstream(), jpeg_encodeMCU(), jpeg_initialization(), jpeg_write_markers(), JPEG_ENCODER_STRUCTURE::length_minus_mcu_width, JPEG_ENCODER_STRUCTURE::length_minus_width, MakeTables(), JPEG_ENCODER_STRUCTURE::mcu_height, JPEG_ENCODER_STRUCTURE::mcu_width, JPEG_ENCODER_STRUCTURE::mcu_width_size, JPEG_ENCODER_STRUCTURE::offset, read_format, JPEG_ENCODER_STRUCTURE::rows, JPEG_ENCODER_STRUCTURE::rows_in_bottom_mcus, image_t::type, JPEG_ENCODER_STRUCTURE::vertical_mcus, and image_t::w.
Referenced by save_shot_on_disk(), video_capture_save(), and viewvideo_function().