Paparazzi UAS: sw/airborne/utils/kv_store.c File Reference
kv_store.c File Reference
#include "kv_store.h"
#include "string.h"
Functions
void kv_init (kv_store_t *kv, size_t capacity, size_t esize, uint32_t *keys, void *values, uint8_t *used)
Initializes a key-value store.
static int kv_find (const kv_store_t *kv, uint32_t key, size_t *index)
Finds the index of a given key in the store.
int kv_exists (const kv_store_t *kv, uint32_t key)
Checks if a key exists in the store.
int kv_set (kv_store_t *kv, uint32_t key, const void *value)
Sets a value for a given key.
void * kv_get (const kv_store_t *kv, uint32_t key)
Retrieves the value associated with a given key.
int kv_remove (kv_store_t *kv, uint32_t key)
Removes a key-value pair from the store.
Function Documentation
kv_exists()
int kv_exists (const kv_store_t * kv, uint32_t key)
Checks if a key exists in the store.
Parameters
kv Pointer to the kv_store_t structure.
key The key to check for existence.
Returns
1 if the key exists, 0 otherwise.
Definition at line 64 of file kv_store.c.
References foo, kv, and kv_find().
kv_find()
static int kv_find (const kv_store_t * kv, uint32_t key, size_t * index) static
Finds the index of a given key in the store.
Parameters
kv Pointer to the kv_store_t structure.
key The key to search for.
index Pointer to a size_t where the index will be stored if found (can be NULL).
Returns
1 if the key is found, 0 otherwise.
Definition at line 42 of file kv_store.c.
References kv.
Referenced by kv_exists(), kv_get(), kv_remove(), and kv_set().
kv_get()
void * kv_get (const kv_store_t * kv, uint32_t key)
Retrieves the value associated with a given key.
Parameters
kv Pointer to the kv_store_t structure.
key The key to retrieve the value for.
Returns
Pointer to the value if the key exists, NULL otherwise.
Definition at line 111 of file kv_store.c.
References foo, kv, and kv_find().
Referenced by get_transfer_id().
kv_init()
void kv_init (kv_store_t * kv, size_t capacity, size_t esize, uint32_t * keys, void * values, uint8_t * used)
Initializes a key-value store.
Parameters
kv Pointer to the kv_store_t structure to initialize.
capacity The maximum number of key-value pairs the store can hold.
esize The size in bytes of each value element.
keys Pointer to an array of uint32_t for storing keys. At least "capacity" long.
values Pointer to the memory area for storing values. At least "capacity * esize" long.
used Pointer to an array of uint8_t flags indicating if a slot is used. At least "capacity" long.
Definition at line 20 of file kv_store.c.
References kv.
Referenced by uavcanInitIface().
kv_remove()
int kv_remove (kv_store_t * kv, uint32_t key)
Removes a key-value pair from the store.
Parameters
kv Pointer to the kv_store_t structure.
key The key to remove.
Returns
0 on success, -1 if the key was not found.
Definition at line 127 of file kv_store.c.
References kv, and kv_find().
kv_set()
int kv_set (kv_store_t * kv, uint32_t key, const void * value)
Sets a value for a given key.
If the key already exists, its value is updated. If not, a new key-value pair is inserted into the first available slot. If the store is full, the operation fails.
Parameters
kv Pointer to the kv_store_t structure.
key The key to set.
value Pointer to the value to store. Value will be memcpy in the store, so the pointer does not need to be valid afterward.
Returns
0 on success, -1 if the store is full.
Definition at line 79 of file kv_store.c.
References foo, kv, and kv_find().
Referenced by get_transfer_id().