Paparazzi UAS: sw/airborne/arch/lpc21/modules/display/lcd_dogm_hw.c File Reference
lcd_dogm_hw.c File Reference
#include "LPC21xx.h"
#include "armVIC.h"
#include "lcd_dogm_hw.h"
Macros
#define PINSEL1_SCK (2 << 2)
#define PINSEL1_MOSI (2 << 6)
#define PINSEL1_SSEL (2 << 8)
#define SSP_DSS 0x07 << 0 /* data size : 8 bits */
#define SSP_FRF 0x00 << 4 /* frame format : SPI */
#define SSP_CPOL 0x01 << 6 /* clock polarity : idle high */
#define SSP_CPHA 0x01 << 7 /* clock phase : low->high */
#define SSP_SCR 0x1F << 8 /* serial clock rate : 29.3kHz, SSP input clock / 16 */
#define SSP_LBM 0x00 << 0 /* loopback mode : disabled */
#define SSP_SSE 0x00 << 1 /* SSP enable : disabled */
#define SSP_MS 0x00 << 2 /* master slave mode : master */
#define SSP_SOD 0x00 << 3 /* slave output disable : don't care when master */
#define SSPCPSR_VAL 0x04
#define SPI1_VIC_SLOT 7
Functions
static void SPI1_ISR (void)
void lcd_spi_tx (uint8_t data)
void lcd_dogm_init_hw (void)
Macro Definition Documentation
#define PINSEL1_MOSI (2 << 6)
Definition at line 31 of file lcd_dogm_hw.c.
Referenced by lcd_dogm_init_hw().
#define PINSEL1_SCK (2 << 2)
Definition at line 30 of file lcd_dogm_hw.c.
Referenced by lcd_dogm_init_hw().
#define PINSEL1_SSEL (2 << 8)
Definition at line 32 of file lcd_dogm_hw.c.
#define SPI1_VIC_SLOT 7
Definition at line 54 of file lcd_dogm_hw.c.
Referenced by lcd_dogm_init_hw().
#define SSP_CPHA 0x01 << 7 /* clock phase : low->high */
Definition at line 38 of file lcd_dogm_hw.c.
Referenced by lcd_dogm_init_hw().
#define SSP_CPOL 0x01 << 6 /* clock polarity : idle high */
Definition at line 37 of file lcd_dogm_hw.c.
Referenced by lcd_dogm_init_hw().
#define SSP_DSS 0x07 << 0 /* data size : 8 bits */
Definition at line 35 of file lcd_dogm_hw.c.
Referenced by lcd_dogm_init_hw().
#define SSP_FRF 0x00 << 4 /* frame format : SPI */
Definition at line 36 of file lcd_dogm_hw.c.
Referenced by lcd_dogm_init_hw().
#define SSP_LBM 0x00 << 0 /* loopback mode : disabled */
Definition at line 42 of file lcd_dogm_hw.c.
Referenced by lcd_dogm_init_hw().
#define SSP_MS 0x00 << 2 /* master slave mode : master */
Definition at line 44 of file lcd_dogm_hw.c.
Referenced by lcd_dogm_init_hw().
#define SSP_SCR 0x1F << 8 /* serial clock rate : 29.3kHz, SSP input clock / 16 */
Definition at line 39 of file lcd_dogm_hw.c.
Referenced by lcd_dogm_init_hw().
#define SSP_SOD 0x00 << 3 /* slave output disable : don't care when master */
Definition at line 45 of file lcd_dogm_hw.c.
Referenced by lcd_dogm_init_hw().
#define SSP_SSE 0x00 << 1 /* SSP enable : disabled */
Definition at line 43 of file lcd_dogm_hw.c.
#define SSPCPSR_VAL 0x04
Definition at line 48 of file lcd_dogm_hw.c.
Referenced by lcd_dogm_init_hw().
Function Documentation
void lcd_dogm_init_hw (void)
Definition at line 65 of file lcd_dogm_hw.c.
References _VIC_CNTL, LCDDOGM_RS_IODIR, LCDDOGM_RS_PIN, LCDDOGM_SS_IODIR, LCDDOGM_SS_PIN, lcddogmUnselect, PINSEL1, PINSEL1_MOSI, PINSEL1_SCK, SPI1_ISR(), SPI1_VIC_SLOT, SSP_CPHA, SSP_CPOL, SSP_DSS, SSP_FRF, SSP_LBM, SSP_MS, SSP_SCR, SSP_SOD, SSPCPSR, SSPCPSR_VAL, SSPCR0, SSPCR1, VIC_BIT, VIC_ENABLE, VIC_SPI1, VICIntEnable, and VICIntSelect.
Referenced by lcd_dogm_init().
void lcd_spi_tx (uint8_t data)
Definition at line 57 of file lcd_dogm_hw.c.
References SpiClearRti(), SpiEnable, SpiEnableRti(), and SSPDR.
Referenced by lcd_cmd(), and lcd_data().
void SPI1_ISR (void) static
Definition at line 88 of file lcd_dogm_hw.c.
References foo, ISR_ENTRY, ISR_EXIT, lcddogmUnselect, RNE, SpiClearRti(), SpiDisable, SpiDisableRti(), SSPDR, SSPSR, and VICVectAddr.
Referenced by lcd_dogm_init_hw().