Paparazzi UAS: sw/airborne/modules/lidar/lidar_sf11.c File Reference
lidar_sf11.c File Reference
#include "modules/lidar/lidar_sf11.h"
#include "modules/core/abi.h"
#include "filters/median_filter.h"
#include "state.h"
#include "pprzlink/messages.h"
#include "modules/datalink/downlink.h"
Functions
void lidar_sf11_init (void)
Initialization function.
void lidar_sf11_event (void)
Lidar event function Check if the transaction succeded before reading the result.
void lidar_sf11_periodic (void)
Poll lidar for data.
void lidar_sf11_downlink (void)
Downlink message for debug.
Variables
struct LidarSF11 lidar_sf11
struct MedianFilterInt lidar_sf11_filter
Function Documentation
lidar_sf11_downlink()
void lidar_sf11_downlink (void)
Downlink message for debug.
Definition at line 134 of file lidar_sf11.c.
References DefaultChannel, DefaultDevice, LidarSF11::distance, foo, lidar_sf11, i2c_transaction::status, LidarSF11::status, status, and LidarSF11::trans.
lidar_sf11_event()
void lidar_sf11_event (void)
Lidar event function Check if the transaction succeded before reading the result.
Definition at line 62 of file lidar_sf11.c.
References I2CTransDone, I2CTransFailed, I2CTransPending, I2CTransRunning, I2CTransSuccess, lidar_sf11, LIDAR_SF11_READ_OK, i2c_transaction::status, LidarSF11::status, and LidarSF11::trans.
lidar_sf11_init()
void lidar_sf11_init (void)
Initialization function.
Definition at line 44 of file lidar_sf11.c.
References LidarSF11::addr, LidarSF11::compensate_rotation, LidarSF11::distance, LidarSF11::distance_raw, foo, I2CTransDone, init_median_filter_i(), lidar_sf11, lidar_sf11_filter, LIDAR_SF11_REQ_READ, MEDIAN_DEFAULT_SIZE, i2c_transaction::status, LidarSF11::status, LidarSF11::trans, and LidarSF11::update_agl.
lidar_sf11_periodic()
void lidar_sf11_periodic (void)
Poll lidar for data.
Definition at line 92 of file lidar_sf11.c.
References LidarSF11::addr, AGL_LIDAR_SF11_ID, i2c_transaction::buf, LidarSF11::compensate_rotation, LidarSF11::distance, LidarSF11::distance_raw, foo, get_sys_time_usec(), i2c_transceive(), lidar_sf11, lidar_sf11_filter, LIDAR_SF11_READ_OK, LIDAR_SF11_REQ_READ, FloatEulers::phi, stateGetNedToBodyEulers_f(), LidarSF11::status, FloatEulers::theta, LidarSF11::trans, LidarSF11::update_agl, and update_median_filter_i().
Variable Documentation
lidar_sf11
struct LidarSF11 lidar_sf11
Definition at line 37 of file lidar_sf11.c.
Referenced by lidar_sf11_downlink(), lidar_sf11_event(), lidar_sf11_init(), and lidar_sf11_periodic().
lidar_sf11_filter
struct MedianFilterInt lidar_sf11_filter
Definition at line 38 of file lidar_sf11.c.
Referenced by lidar_sf11_init(), and lidar_sf11_periodic().