Paparazzi UAS: sw/airborne/modules/lidar/lidar_sf11.h File Reference
lidar_sf11.h File Reference
driver for the Parallax SF11-A/B/C Laser Rangefinder connected over i2c bus.
#include "std.h"
#include "mcu_periph/i2c.h"
Data Structures
struct LidarSF11
Enumerations
enum LidarSF11Status { LIDAR_SF11_REQ_READ , LIDAR_SF11_READ_OK }
Functions
void lidar_sf11_init (void)
Initialization function.
void lidar_sf11_event (void)
Lidar event function Check if the transaction succeded before reading the result.
void lidar_sf11_periodic (void)
Poll lidar for data.
void lidar_sf11_downlink (void)
Downlink message for debug.
Variables
struct LidarSF11 lidar_sf11
Detailed Description
driver for the Parallax SF11-A/B/C Laser Rangefinder connected over i2c bus.
Definition in file lidar_sf11.h.
Data Structure Documentation
LidarSF11
struct LidarSF11
Definition at line 37 of file lidar_sf11.h.
Data Fields
uint8_t addr
bool compensate_rotation
float distance
uint32_t distance_raw
enum LidarSF11Status status
struct i2c_transaction trans
bool update_agl
Enumeration Type Documentation
LidarSF11Status
enum LidarSF11Status
Enumerator
LIDAR_SF11_REQ_READ
LIDAR_SF11_READ_OK
Definition at line 32 of file lidar_sf11.h.
Function Documentation
lidar_sf11_downlink()
void lidar_sf11_downlink (void) extern
Downlink message for debug.
Definition at line 134 of file lidar_sf11.c.
References DefaultChannel, DefaultDevice, LidarSF11::distance, foo, lidar_sf11, i2c_transaction::status, LidarSF11::status, status, and LidarSF11::trans.
lidar_sf11_event()
void lidar_sf11_event (void) extern
Lidar event function Check if the transaction succeded before reading the result.
Definition at line 62 of file lidar_sf11.c.
References I2CTransDone, I2CTransFailed, I2CTransPending, I2CTransRunning, I2CTransSuccess, lidar_sf11, LIDAR_SF11_READ_OK, i2c_transaction::status, LidarSF11::status, and LidarSF11::trans.
lidar_sf11_init()
void lidar_sf11_init (void) extern
Initialization function.
Definition at line 44 of file lidar_sf11.c.
References LidarSF11::addr, LidarSF11::compensate_rotation, LidarSF11::distance, LidarSF11::distance_raw, foo, I2CTransDone, init_median_filter_i(), lidar_sf11, lidar_sf11_filter, LIDAR_SF11_REQ_READ, MEDIAN_DEFAULT_SIZE, i2c_transaction::status, LidarSF11::status, LidarSF11::trans, and LidarSF11::update_agl.
lidar_sf11_periodic()
void lidar_sf11_periodic (void) extern
Poll lidar for data.
Definition at line 92 of file lidar_sf11.c.
References LidarSF11::addr, AGL_LIDAR_SF11_ID, i2c_transaction::buf, LidarSF11::compensate_rotation, LidarSF11::distance, LidarSF11::distance_raw, foo, get_sys_time_usec(), i2c_transceive(), lidar_sf11, lidar_sf11_filter, LIDAR_SF11_READ_OK, LIDAR_SF11_REQ_READ, FloatEulers::phi, stateGetNedToBodyEulers_f(), LidarSF11::status, FloatEulers::theta, LidarSF11::trans, LidarSF11::update_agl, and update_median_filter_i().
Variable Documentation
lidar_sf11
struct LidarSF11 lidar_sf11 extern
Definition at line 37 of file lidar_sf11.c.
Referenced by lidar_sf11_downlink(), lidar_sf11_event(), lidar_sf11_init(), and lidar_sf11_periodic().