Paparazzi UAS: sw/airborne/modules/lidar/slam/lidar_correction.c File Reference
lidar_correction.c File Reference
#include "lidar_correction.h"
#include "modules/lidar/tfmini.h"
#include "modules/ins/ins_int.h"
#include "math/pprz_algebra.h"
#include <math.h>
#include <float.h>
#include <state.h>
Functions
float distance_to_wall (float theta, const struct FloatVect2 *P, const struct FloatVect2 *A, const struct FloatVect2 *B)
static float distance_to_segment (const struct FloatVect2 *P, const struct FloatVect2 *A, const struct FloatVect2 *B, struct FloatVect2 *C)
float find_nearest_wall (const struct FloatVect2 *obstacle_pos, struct FloatVect2 *nearest_point)
void init_walls (void)
void convert_walls_to_ltp (void)
Variables
struct WallSystem wall_system
const struct WallConfig obstacle_walls [] = OBSTACLE_WALLS
Function Documentation
convert_walls_to_ltp()
void convert_walls_to_ltp (void)
Definition at line 168 of file lidar_correction.c.
References Wall::converted, WallSystem::converted_to_ltp, Wall::count, foo, ned_of_lla_point_f(), p, Wall::points_ltp, Wall::points_wgs84, stateGetNedOrigin_f(), stateIsLocalCoordinateValid(), WallSystem::wall_count, wall_system, WallSystem::walls, FloatVect2::x, and FloatVect2::y.
Referenced by ins_update_lidar().
distance_to_segment()
static float distance_to_segment (const struct FloatVect2 * P, const struct FloatVect2 * A, const struct FloatVect2 * B, struct FloatVect2 * C) static
Definition at line 75 of file lidar_correction.c.
References A, B, foo, P, FloatVect2::x, and FloatVect2::y.
Referenced by find_nearest_wall().
distance_to_wall()
float distance_to_wall (float theta, const struct FloatVect2 * P, const struct FloatVect2 * A, const struct FloatVect2 * B)
Definition at line 48 of file lidar_correction.c.
References A, B, foo, P, and s.
Referenced by sim_overwrite_lidar().
find_nearest_wall()
float find_nearest_wall (const struct FloatVect2 * obstacle_pos, struct FloatVect2 * nearest_point)
Definition at line 97 of file lidar_correction.c.
References WallSystem::converted_to_ltp, distance_to_segment(), foo, p, WallSystem::wall_count, wall_system, WallSystem::walls, FloatVect2::x, and FloatVect2::y.
init_walls()
void init_walls (void)
Definition at line 144 of file lidar_correction.c.
References ObstaclePoint::alt, WallSystem::converted_to_ltp, WallConfig::count, Wall::count, foo, ObstaclePoint::lat_deg, ObstaclePoint::lon_deg, obstacle_walls, p, WallConfig::points, WallSystem::wall_count, wall_system, and WallSystem::walls.
Variable Documentation
obstacle_walls
const struct WallConfig obstacle_walls[] = OBSTACLE_WALLS
Definition at line 141 of file lidar_correction.c.
Referenced by init_walls().
wall_system
struct WallSystem wall_system
Definition at line 35 of file lidar_correction.c.
Referenced by convert_walls_to_ltp(), find_nearest_wall(), init_walls(), ins_update_lidar(), and sim_overwrite_lidar().