Paparazzi UAS: sw/airborne/modules/lidar/slam/lidar_correction.h File Reference
lidar_correction.h File Reference
#include "math/pprz_algebra.h"
#include "math/pprz_algebra_float.h"
#include "math/pprz_geodetic_float.h"
Data Structures
struct ObstaclePoint
struct WallConfig
struct Wall
struct WallSystem
Macros
#define MAX_WALLS 10
#define MAX_POINTS 5
Functions
void init_walls (void)
void convert_walls_to_ltp (void)
float find_nearest_wall (const struct FloatVect2 *obstacle_pos, struct FloatVect2 *nearest_point)
float distance_to_wall (float theta, const struct FloatVect2 *P, const struct FloatVect2 *A, const struct FloatVect2 *B)
Variables
struct WallSystem wall_system
Data Structure Documentation
ObstaclePoint
struct ObstaclePoint
Definition at line 38 of file lidar_correction.h.
Data Fields
float alt
float lat_deg
float lon_deg
WallConfig
struct WallConfig
Definition at line 44 of file lidar_correction.h.
Data Fields
uint8_t count
struct ObstaclePoint points[MAX_POINTS]
Wall
struct Wall
Definition at line 51 of file lidar_correction.h.
Data Fields
bool converted
uint8_t count
struct FloatVect2 points_ltp[MAX_POINTS]
struct LlaCoor_f points_wgs84[MAX_POINTS]
WallSystem
struct WallSystem
Definition at line 58 of file lidar_correction.h.
Data Fields
bool converted_to_ltp
uint8_t wall_count
struct Wall walls[MAX_WALLS]
Macro Definition Documentation
MAX_POINTS
#define MAX_POINTS 5
Definition at line 34 of file lidar_correction.h.
MAX_WALLS
#define MAX_WALLS 10
Definition at line 33 of file lidar_correction.h.
Function Documentation
convert_walls_to_ltp()
void convert_walls_to_ltp (void) extern
Definition at line 168 of file lidar_correction.c.
References Wall::converted, WallSystem::converted_to_ltp, Wall::count, foo, ned_of_lla_point_f(), p, Wall::points_ltp, Wall::points_wgs84, stateGetNedOrigin_f(), stateIsLocalCoordinateValid(), WallSystem::wall_count, wall_system, WallSystem::walls, FloatVect2::x, and FloatVect2::y.
Referenced by ins_update_lidar().
distance_to_wall()
float distance_to_wall (float theta, const struct FloatVect2 * P, const struct FloatVect2 * A, const struct FloatVect2 * B) extern
Definition at line 48 of file lidar_correction.c.
References A, B, foo, P, and s.
Referenced by sim_overwrite_lidar().
find_nearest_wall()
float find_nearest_wall (const struct FloatVect2 * obstacle_pos, struct FloatVect2 * nearest_point) extern
Definition at line 97 of file lidar_correction.c.
References WallSystem::converted_to_ltp, distance_to_segment(), foo, p, WallSystem::wall_count, wall_system, WallSystem::walls, FloatVect2::x, and FloatVect2::y.
init_walls()
void init_walls (void) extern
Definition at line 144 of file lidar_correction.c.
References ObstaclePoint::alt, WallSystem::converted_to_ltp, WallConfig::count, Wall::count, foo, ObstaclePoint::lat_deg, ObstaclePoint::lon_deg, obstacle_walls, p, WallConfig::points, WallSystem::wall_count, wall_system, and WallSystem::walls.
Variable Documentation
wall_system
struct WallSystem wall_system extern
Definition at line 35 of file lidar_correction.c.
Referenced by convert_walls_to_ltp(), find_nearest_wall(), init_walls(), ins_update_lidar(), and sim_overwrite_lidar().