Paparazzi UAS: sw/airborne/arch/chibios/modules/lidar/lidar_vl53l5cx.c File Reference
lidar_vl53l5cx.c File Reference
#include "modules/lidar/lidar_vl53l5cx.h"
#include "mcu_periph/i2c.h"
#include "ch.h"
#include "lidar/vl53l5cx_platform.h"
#include "peripherals/vl53l5cx_api.h"
#include "modules/core/abi.h"
#include "modules/datalink/downlink.h"
#include "hal.h"
#include "mcu_periph/ram_arch.h"
Macros
#define LIDAR_VL53L5CX_I2C_ADDR 0x29
#define SUBTYPE_DISTANCE 0
Functions
static IN_DMA_SECTION (VL53L5CX_Configuration vl53l5cx_dev)
static IN_DMA_SECTION (VL53L5CX_ResultsData vl53l5cx_results)
static THD_WORKING_AREA (wa_thd_lidar_vl53l5cx, 1024)
static void thd_lidar_vl53l5cx (void *arg)
void lidar_vl53l5cx_init (void)
void lidar_vl53l5cx_periodic (void)
Variables
char * VL53L5CX_ERROR_MSGS []
Detailed Description
Author
Fabien-B name..nosp@m.surn.nosp@m.ame@g.nosp@m.mail.nosp@m..com VL53L5CX multizone range sensor.
Definition in file lidar_vl53l5cx.c.
Macro Definition Documentation
LIDAR_VL53L5CX_I2C_ADDR
#define LIDAR_VL53L5CX_I2C_ADDR 0x29
Definition at line 38 of file lidar_vl53l5cx.c.
SUBTYPE_DISTANCE
#define SUBTYPE_DISTANCE 0
Definition at line 41 of file lidar_vl53l5cx.c.
Function Documentation
IN_DMA_SECTION() [1/2]
static IN_DMA_SECTION (VL53L5CX_Configuration vl53l5cx_dev) static
IN_DMA_SECTION() [2/2]
static IN_DMA_SECTION (VL53L5CX_ResultsData vl53l5cx_results) static
lidar_vl53l5cx_init()
void lidar_vl53l5cx_init (void)
Definition at line 59 of file lidar_vl53l5cx.c.
References foo, LIDAR_VL53L5CX_I2C_ADDR, thd_lidar_vl53l5cx(), and VL53L5CX_NO_ERROR.
lidar_vl53l5cx_periodic()
void lidar_vl53l5cx_periodic (void)
Definition at line 71 of file lidar_vl53l5cx.c.
References DefaultChannel, DefaultDevice, foo, get_sys_time_usec(), LIDAR_DATA_VL53L5CX_ID, SUBTYPE_DISTANCE, and VL53L5CX_ERROR_MSGS.
thd_lidar_vl53l5cx()
static void thd_lidar_vl53l5cx (void * arg) static
Definition at line 106 of file lidar_vl53l5cx.c.
References dev, foo, status, vl53l5cx_check_data_ready(), vl53l5cx_get_ranging_data(), vl53l5cx_init(), vl53l5cx_is_alive(), VL53L5CX_NOT_DETECTED, VL53L5CX_RESOLUTION_4X4, vl53l5cx_set_resolution(), VL53L5CX_SET_RESOLUTION_FAILED, vl53l5cx_start_ranging(), and VL53L5CX_ULD_LOADING_FAILED.
Referenced by lidar_vl53l5cx_init().
THD_WORKING_AREA()
static THD_WORKING_AREA (wa_thd_lidar_vl53l5cx , 1024) static
Variable Documentation
VL53L5CX_ERROR_MSGS
char* VL53L5CX_ERROR_MSGS[]
Initial value:
= {
  "VL53L5CX_NO_ERROR",
  "VL53L5CX_NOT_DETECTED",
  "VL53L5CX_ULD_LOADING_FAILED",
  "VL53L5CX_SET_RESOLUTION_FAILED",
  "VL53L5CX_RUNTIME_ERROR",
}
Definition at line 50 of file lidar_vl53l5cx.c.
Referenced by lidar_vl53l5cx_periodic().