Paparazzi UAS: sw/airborne/arch/chibios/modules/light/light_ws2812_arch.h File Reference
light_ws2812_arch.h File Reference
ws2812 driver based on ChibiOS
#include "std.h"
Macros
#define WS2812_NB_LEDS 8
Number of LEDs.
Functions
void light_ws2812_arch_init (void)
void light_ws2812_arch_set (uint32_t led_number, uint8_t r, uint8_t g, uint8_t b)
set color RGB color of one led
Detailed Description
ws2812 driver based on ChibiOS
Author
Xavier Paris @maintainer Gautier Hattenberger gauti.nosp@m.er.h.nosp@m.atten.nosp@m.berg.nosp@m.er@en.nosp@m.ac.f.nosp@m.r
Definition in file light_ws2812_arch.h.
Macro Definition Documentation
WS2812_NB_LEDS
#define WS2812_NB_LEDS 8
Number of LEDs.
Definition at line 36 of file light_ws2812_arch.h.
Function Documentation
light_ws2812_arch_init()
void light_ws2812_arch_init (void) extern
Definition at line 89 of file light_ws2812_arch.c.
References WS2812Driver::buf, WS2812Driver::config, WS2812Config::dma_channel, WS2812Driver::dma_conf, DMA_CONTINUOUS_HALF_BUFFER, DMA_DIR_M2P, WS2812Config::dma_priority, WS2812Config::dma_stream, dmaObjectInit(), WS2812Driver::dmap, dmaStart(), dmaStartTransfert(), foo, gpio_setup_pin_af(), WS2812Config::pwm_channel, WS2812Driver::pwm_conf, WS2812Config::pwmp, DMAConfig::stream, WS2812_AF, WS2812_BIT_N, WS2812_COLOR_BIT_N, WS2812_DMA_IRQ_PRIORITY, WS2812_DUTYCYCLE_0, WS2812_GPIO, WS2812_PIN, WS2812_PWM_FREQUENCY, WS2812_RESET_BIT_N, WS2812_SERVO_HZ, WS2812CFG, and WS2812D.
Referenced by light_scheduler_init().
light_ws2812_arch_set()
void light_ws2812_arch_set (uint32_t led_number, uint8_t r, uint8_t g, uint8_t b) extern
set color RGB color of one led
Definition at line 162 of file light_ws2812_arch.c.
References b, WS2812Driver::buf, foo, g, WS2812_BLUE_BIT, WS2812_DUTYCYCLE_0, WS2812_DUTYCYCLE_1, WS2812_GREEN_BIT, WS2812_NB_LEDS, WS2812_RED_BIT, and WS2812D.
Referenced by light_scheduler_periodic().