Paparazzi UAS: sw/airborne/link_mcu_usart.h File Reference
link_mcu_usart.h File Reference
Transport for the communication between FBW and AP via UART.
#include <inttypes.h>
#include "inter_mcu.h"
Data Structures
struct link_mcu_msg
union link_mcu_msg.payload
Functions
void link_mcu_send (void)
void link_mcu_init (void)
void link_mcu_event_task (void)
void link_mcu_periodic_task (void)
Variables
struct link_mcu_msg link_mcu_from_ap_msg
struct link_mcu_msg link_mcu_from_fbw_msg
bool link_mcu_received
Detailed Description
Transport for the communication between FBW and AP via UART.
Definition in file link_mcu_usart.h.
Data Structure Documentation
struct link_mcu_msg
Definition at line 33 of file link_mcu_can.h.
Data Fields
uint16_t checksum
union link_mcu_msg payload
union link_mcu_msg payload
union link_mcu_msg payload
union link_mcu_msg.payload
Definition at line 34 of file link_mcu_usart.h.
Data Fields
struct ap_state from_ap
struct fbw_state from_fbw
Function Documentation
void link_mcu_event_task (void)
Definition at line 229 of file link_mcu_can.c.
References intermcu_data, intermcu_parse(), InterMcuBuffer, InterMcuUartGetch, InterMcuData::msg_available, and parse_mavpilot_msg().
Referenced by event_task_ap().
void link_mcu_init (void)
Definition at line 216 of file link_mcu_can.c.
References DefaultPeriodic, InterMcuData::error_cnt, intermcu_data, link_mcu_on_can_msg(), LINK_MCU_UNINIT, InterMcuData::msg_available, ppz_can_init(), register_periodic_telemetry(), send_commands(), send_fbw_status(), and InterMcuData::status.
Referenced by init_ap(), and init_fbw().
void link_mcu_periodic_task (void)
void link_mcu_send (void)
Variable Documentation
struct link_mcu_msg link_mcu_from_ap_msg
Definition at line 176 of file link_mcu_can.c.
struct link_mcu_msg link_mcu_from_fbw_msg
Definition at line 177 of file link_mcu_can.c.
bool link_mcu_received
Definition at line 34 of file link_mcu_spi.c.