Paparazzi UAS: sw/airborne/arch/linux/mcu_periph/adc_arch.c File Reference
adc_arch.c File Reference
Driver for the analog to digital converters in Linux based systems.
#include "mcu_periph/adc.h"
#include <BOARD_CONFIG>
#include <stdlib.h>
#include <unistd.h>
#include <stdio.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <poll.h>
Functions
static void adc_dev_init (struct adc_t *adc)
Initialize an ADC device.
static void write_sysfs_int (uint8_t dev_id, char *filename, int val)
Write an int to a sysfs file.
void adc_init (void)
Initialize the ADC.
void adc_buf_channel (uint8_t adc_channel, struct adc_buf *s, uint8_t av_nb_sample)
Registers a buffer to be used to store the specified converted channel Usage:
void adc_enable (struct adc_t *adc, uint8_t value)
Start or stop the ADC readings.
int adc_read (struct adc_t *adc, uint16_t *buf, uint16_t size)
Read the ADC buffer from the driver.
Detailed Description
Driver for the analog to digital converters in Linux based systems.
Definition in file adc_arch.c.
Function Documentation
void adc_buf_channel (uint8_t adc_channel, struct adc_buf * s, uint8_t av_nb_sample)
Registers a buffer to be used to store the specified converted channel Usage:
Todo:
: fx a more general ADC
Definition at line 91 of file adc_arch.c.
static void adc_dev_init (struct adc_t * adc) inline static
Initialize an ADC device.
Parameters
[in] *adc The ADC device to initialize
Definition at line 148 of file adc_arch.c.
References adc_t::buf_length, adc_t::channels, adc_t::channels_cnt, adc_t::dev_id, and write_sysfs_int().
Referenced by adc_init().
void adc_enable (struct adc_t * adc, uint8_t value)
Start or stop the ADC readings.
Parameters
[in] *adc The ADC to start the readings for
[in] value 1 to enable and 0 to disable
Definition at line 101 of file adc_arch.c.
References adc_t::dev_id, and write_sysfs_int().
Referenced by sonar_bebop_read().
void adc_init (void)
Initialize the ADC.
Starts conversions.
Definition at line 78 of file adc_arch.c.
References adc_dev_init().
int adc_read (struct adc_t * adc, uint16_t * buf, uint16_t size)
Read the ADC buffer from the driver.
Parameters
[in] *adc The adc you want to read from
[out] *buf Output values
[in] size The amount of bytes you want to read
Definition at line 113 of file adc_arch.c.
References adc_t::dev_id, and fd.
Referenced by sonar_bebop_read().
static void write_sysfs_int (uint8_t dev_id, char * filename, int val) static
Write an int to a sysfs file.
Parameters
[in] dev_id The device id
[in] *filename The file to write to
[in] val The value to write
Definition at line 169 of file adc_arch.c.
References fd.
Referenced by adc_dev_init(), and adc_enable().