Paparazzi UAS: sw/airborne/boards/lisa_mx/baro_board.c File Reference
baro_board.c File Reference
#include "std.h"
#include "modules/sensors/baro.h"
#include "peripherals/bmp085.h"
#include "peripherals/bmp085_regs.h"
#include <libopencm3/stm32/gpio.h>
#include "modules/core/abi.h"
#include "led.h"
Functions
static bool baro_eoc (void)
void baro_init (void)
void baro_periodic (void)
void baro_event (void)
Variables
struct Bmp085 baro_bmp085
Function Documentation
baro_eoc()
static bool baro_eoc (void) static
Definition at line 39 of file baro_board.c.
References GPIO0, gpio_get(), and GPIOB.
baro_event()
void baro_event (void)
Definition at line 71 of file baro_board.c.
References baro_bmp085, BARO_BOARD_SENDER_ID, bmp085_event(), Bmp085::data_available, foo, get_sys_time_usec(), LED_TOGGLE, Bmp085::pressure, and Bmp085::temperature.
baro_init()
void baro_init (void)
Definition at line 44 of file baro_board.c.
References baro_bmp085, baro_eoc(), bmp085_init(), BMP085_SLAVE_ADDR, Bmp085::eoc, foo, GPIO0, gpio_clear(), gpio_setup_input_pulldown(), GPIOB, and LED_OFF.
baro_periodic()
void baro_periodic (void)
Definition at line 60 of file baro_board.c.
References baro_bmp085, bmp085_periodic(), bmp085_read_eeprom_calib(), and Bmp085::initialized.
Variable Documentation
baro_bmp085
struct Bmp085 baro_bmp085
Definition at line 37 of file baro_board.c.