Paparazzi UAS: sw/airborne/boards/lisa_l/baro_board.c File Reference
baro_board.c File Reference
#include "std.h"
#include "modules/sensors/baro.h"
#include "mcu_periph/i2c.h"
#include "modules/core/abi.h"
#include "led.h"
Data Structures
struct BaroBoard
Macros
#define BARO_ABS_ADDR 0x90
#define BARO_DIFF_ADDR 0x92
#define LISA_L_BARO_SENS 1.0
#define LISA_L_DIFF_SENS 1.0
Enumerations
enum LisaBaroStatus {
LBS_UNINITIALIZED , LBS_RESETED , LBS_INITIALIZING_ABS , LBS_INITIALIZING_ABS_1 ,
LBS_INITIALIZING_DIFF , LBS_INITIALIZING_DIFF_1 , LBS_IDLE , LBS_READING_ABS ,
LBS_READ_ABS , LBS_READING_DIFF , LBS_READ_DIFF
}
Functions
static void baro_board_send_reset (void)
static void baro_board_send_config_abs (void)
static void baro_board_send_config_diff (void)
static void baro_board_write_to_register (uint8_t baro_addr, uint8_t reg_addr, uint8_t val_msb, uint8_t val_lsb)
static void baro_board_read_from_register (uint8_t baro_addr, uint8_t reg_addr)
static void baro_board_set_current_register (uint8_t baro_addr, uint8_t reg_addr)
static void baro_board_read_from_current_register (uint8_t baro_addr)
void baro_init (void)
void baro_periodic (void)
void lisa_l_baro_event (void)
Variables
struct BaroBoard baro_board
struct i2c_transaction baro_trans
Data Structure Documentation
BaroBoard
struct BaroBoard
Definition at line 43 of file baro_board.c.
Data Fields
bool running
enum LisaBaroStatus status
Macro Definition Documentation
BARO_ABS_ADDR
#define BARO_ABS_ADDR 0x90
Definition at line 61 of file baro_board.c.
BARO_DIFF_ADDR
#define BARO_DIFF_ADDR 0x92
Definition at line 63 of file baro_board.c.
LISA_L_BARO_SENS
#define LISA_L_BARO_SENS 1.0
Definition at line 67 of file baro_board.c.
LISA_L_DIFF_SENS
#define LISA_L_DIFF_SENS 1.0
Definition at line 71 of file baro_board.c.
Enumeration Type Documentation
LisaBaroStatus
enum LisaBaroStatus
Enumerator
LBS_UNINITIALIZED
LBS_RESETED
LBS_INITIALIZING_ABS
LBS_INITIALIZING_ABS_1
LBS_INITIALIZING_DIFF
LBS_INITIALIZING_DIFF_1
LBS_IDLE
LBS_READING_ABS
LBS_READ_ABS
LBS_READING_DIFF
LBS_READ_DIFF
Definition at line 29 of file baro_board.c.
Function Documentation
baro_board_read_from_current_register()
static void baro_board_read_from_current_register (uint8_t baro_addr) inline static
Definition at line 217 of file baro_board.c.
References baro_trans, foo, i2c_submit(), I2CTransRx, i2c_transaction::len_r, i2c_transaction::slave_addr, and i2c_transaction::type.
Referenced by baro_periodic().
baro_board_read_from_register()
static void baro_board_read_from_register (uint8_t baro_addr, uint8_t reg_addr) inline static
Definition at line 194 of file baro_board.c.
References baro_trans, i2c_transaction::buf, foo, i2c_submit(), I2CTransTxRx, i2c_transaction::len_r, i2c_transaction::len_w, i2c_transaction::slave_addr, and i2c_transaction::type.
baro_board_send_config_abs()
static void baro_board_send_config_abs (void) inline static
Definition at line 157 of file baro_board.c.
References BARO_ABS_ADDR, baro_board_write_to_register(), and foo.
Referenced by baro_periodic().
baro_board_send_config_diff()
static void baro_board_send_config_diff (void) inline static
Definition at line 169 of file baro_board.c.
References baro_board_write_to_register(), and BARO_DIFF_ADDR.
Referenced by baro_periodic().
baro_board_send_reset()
static void baro_board_send_reset (void) inline static
Definition at line 174 of file baro_board.c.
References baro_trans, i2c_transaction::buf, foo, i2c_submit(), I2CTransTx, i2c_transaction::len_w, i2c_transaction::slave_addr, and i2c_transaction::type.
Referenced by baro_periodic().
baro_board_set_current_register()
static void baro_board_set_current_register (uint8_t baro_addr, uint8_t reg_addr) inline static
Definition at line 206 of file baro_board.c.
References baro_trans, i2c_transaction::buf, foo, i2c_submit(), I2CTransTx, i2c_transaction::len_w, i2c_transaction::slave_addr, and i2c_transaction::type.
Referenced by baro_periodic().
baro_board_write_to_register()
static void baro_board_write_to_register (uint8_t baro_addr, uint8_t reg_addr, uint8_t val_msb, uint8_t val_lsb) inline static
Definition at line 183 of file baro_board.c.
References baro_trans, i2c_transaction::buf, foo, i2c_submit(), I2CTransTx, i2c_transaction::len_w, i2c_transaction::slave_addr, and i2c_transaction::type.
Referenced by baro_board_send_config_abs(), and baro_board_send_config_diff().
baro_init()
void baro_init (void)
Definition at line 74 of file baro_board.c.
References baro_board, foo, LBS_UNINITIALIZED, LED_OFF, BaroBoard::running, and BaroBoard::status.
baro_periodic()
void baro_periodic (void)
Definition at line 84 of file baro_board.c.
References BARO_ABS_ADDR, baro_board, baro_board_read_from_current_register(), baro_board_send_config_abs(), baro_board_send_config_diff(), baro_board_send_reset(), baro_board_set_current_register(), BARO_DIFF_ADDR, foo, i2c_idle(), LBS_INITIALIZING_ABS, LBS_INITIALIZING_ABS_1, LBS_INITIALIZING_DIFF, LBS_INITIALIZING_DIFF_1, LBS_READ_ABS, LBS_READ_DIFF, LBS_READING_ABS, LBS_READING_DIFF, LBS_RESETED, LBS_UNINITIALIZED, LED_ON, LED_TOGGLE, BaroBoard::running, BaroBoard::status, and TRUE.
lisa_l_baro_event()
void lisa_l_baro_event (void)
Definition at line 135 of file baro_board.c.
References baro_board, BARO_BOARD_SENDER_ID, baro_trans, i2c_transaction::buf, foo, get_sys_time_usec(), I2CTransPending, I2CTransSuccess, LBS_READ_ABS, LBS_READ_DIFF, LBS_READING_ABS, LBS_READING_DIFF, LISA_L_BARO_SENS, LISA_L_DIFF_SENS, BaroBoard::status, and i2c_transaction::status.
Variable Documentation
baro_board
struct BaroBoard baro_board
Definition at line 49 of file baro_board.c.
Referenced by baro_init(), baro_periodic(), and lisa_l_baro_event().
baro_trans
struct i2c_transaction baro_trans
Definition at line 50 of file baro_board.c.
Referenced by baro_board_read_from_current_register(), baro_board_read_from_register(), baro_board_send_reset(), baro_board_set_current_register(), baro_board_write_to_register(), and lisa_l_baro_event().