Paparazzi UAS: sw/airborne/modules/loggers/logger_control_effectiveness.c File Reference
logger_control_effectiveness.c File Reference
Log data required to compute control effectiveness.
#include "modules/loggers/logger_control_effectiveness.h"
#include "modules/loggers/sdlog_chibios.h"
#include "mcu_periph/sys_time.h"
#include "state.h"
Macros
#define LOGGER_CONTROL_EFFECTIVENESS_COMMANDS TRUE
#define LOGGER_CONTROL_EFFECTIVENESS_ACTUATORS FALSE
#define LOGGER_CONTROL_EFFECTIVENESS_POS FALSE
#define LOGGER_CONTROL_EFFECTIVENESS_SPEED FALSE
#define LOGGER_CONTROL_EFFECTIVENESS_AIRSPEED FALSE
Functions
void logger_control_effectiveness_start (void)
Write the log header line according to the enabled parts.
void logger_control_effectiveness_periodic (void)
Log the values to file.
Detailed Description
Log data required to compute control effectiveness.
Definition in file logger_control_effectiveness.c.
Macro Definition Documentation
LOGGER_CONTROL_EFFECTIVENESS_ACTUATORS
#define LOGGER_CONTROL_EFFECTIVENESS_ACTUATORS FALSE
Definition at line 38 of file logger_control_effectiveness.c.
LOGGER_CONTROL_EFFECTIVENESS_AIRSPEED
#define LOGGER_CONTROL_EFFECTIVENESS_AIRSPEED FALSE
Definition at line 50 of file logger_control_effectiveness.c.
LOGGER_CONTROL_EFFECTIVENESS_COMMANDS
#define LOGGER_CONTROL_EFFECTIVENESS_COMMANDS TRUE
Definition at line 34 of file logger_control_effectiveness.c.
LOGGER_CONTROL_EFFECTIVENESS_POS
#define LOGGER_CONTROL_EFFECTIVENESS_POS FALSE
Definition at line 42 of file logger_control_effectiveness.c.
LOGGER_CONTROL_EFFECTIVENESS_SPEED
#define LOGGER_CONTROL_EFFECTIVENESS_SPEED FALSE
Definition at line 46 of file logger_control_effectiveness.c.
Function Documentation
logger_control_effectiveness_periodic()
void logger_control_effectiveness_periodic (void)
Log the values to file.
Definition at line 93 of file logger_control_effectiveness.c.
References commands, foo, get_sys_time_float(), Int32Rates::p, pprzLogFile, Int32Rates::q, Int32Rates::r, stateGetAccelBody_i(), stateGetAirspeed_f(), stateGetBodyRates_i(), stateGetPositionEnu_i(), stateGetSpeedEnu_i(), EnuCoor_i::x, EnuCoor_i::y, and EnuCoor_i::z.
logger_control_effectiveness_start()
void logger_control_effectiveness_start (void)
Write the log header line according to the enabled parts.
Definition at line 64 of file logger_control_effectiveness.c.
References foo, and pprzLogFile.