Paparazzi UAS: sw/airborne/modules/loggers/logger_file.c File Reference
logger_file.c File Reference
File logger for Linux based autopilots.
#include "logger_file.h"
#include <stdio.h>
#include <sys/stat.h>
#include <time.h>
#include <unistd.h>
#include "std.h"
#include "mcu_periph/sys_time.h"
#include "state.h"
#include "generated/airframe.h"
#include "firmwares/fixedwing/stabilization/stabilization_attitude.h"
#include "firmwares/fixedwing/stabilization/stabilization_adaptive.h"
#include "generated/modules.h"
Macros
#define LOGGER_FILE_PATH /data/video/usb
Set the default File logger path to the USB drive.
Functions
static void logger_file_write_header (FILE *file)
Logging functions.
static void logger_file_write_row (FILE *file)
Write CSV row Write values at this timestamp to log file.
void logger_file_start (void)
Start the file logger and open a new file.
void logger_file_stop (void)
Stop the logger an nicely close the file.
void logger_file_periodic (void)
Log the values to a csv file
Variables
static FILE * logger_file = NULL
The file pointer.
Detailed Description
File logger for Linux based autopilots.
Definition in file logger_file.c.
Macro Definition Documentation
LOGGER_FILE_PATH
#define LOGGER_FILE_PATH /data/video/usb
Set the default File logger path to the USB drive.
Definition at line 50 of file logger_file.c.
Function Documentation
logger_file_periodic()
void logger_file_periodic (void)
Log the values to a csv file
Definition at line 175 of file logger_file.c.
References foo, logger_file, and logger_file_write_row().
logger_file_start()
void logger_file_start (void)
Start the file logger and open a new file.
Definition at line 120 of file logger_file.c.
References counter, foo, logger_file, LOGGER_FILE_PATH, logger_file_write_header(), and time.
logger_file_stop()
void logger_file_stop (void)
Stop the logger an nicely close the file.
Definition at line 166 of file logger_file.c.
References foo, and logger_file.
logger_file_write_header()
static void logger_file_write_header (FILE * file) static
Logging functions.
Write CSV header Write column names at the top of the CSV file. Make sure that the columns match those in logger_file_write_row! Don't forget the
at the end of the line.
Parameters
file Log file pointer
Definition at line 65 of file logger_file.c.
References foo, and ins_ext_pose_log_header().
Referenced by logger_file_start().
logger_file_write_row()
static void logger_file_write_row (FILE * file) static
Write CSV row Write values at this timestamp to log file.
Make sure that the printf's match the column headers of logger_file_write_header! Don't forget the
at the end of the line.
Parameters
file Log file pointer
Definition at line 91 of file logger_file.c.
References actuators_bebop, Stabilization::cmd, foo, get_sys_time_float(), h_ctl_aileron_setpoint, h_ctl_elevator_setpoint, ins_ext_pose_log_data(), FloatRates::p, FloatEulers::phi, FloatEulers::psi, FloatRates::q, FloatRates::r, ActuatorsBebop::rpm_obs, ActuatorsBebop::rpm_ref, stabilization, stateGetBodyRates_f(), stateGetNedToBodyEulers_f(), stateGetPositionNed_f(), stateGetSpeedNed_f(), FloatEulers::theta, NedCoor_f::x, NedCoor_f::y, and NedCoor_f::z.
Referenced by logger_file_periodic().
Variable Documentation
logger_file
FILE* logger_file = NULL static
The file pointer.
Definition at line 54 of file logger_file.c.
Referenced by logger_file_periodic(), logger_file_start(), and logger_file_stop().