Paparazzi UAS: sw/airborne/modules/loggers/logger_control_effectiveness.h File Reference
logger_control_effectiveness.h File Reference
Log data required to compute control effectiveness.
Functions
void logger_control_effectiveness_start (void)
Write the log header line according to the enabled parts.
void logger_control_effectiveness_stop (void)
void logger_control_effectiveness_periodic (void)
Log the values to file.
Detailed Description
Log data required to compute control effectiveness.
Definition in file logger_control_effectiveness.h.
Function Documentation
logger_control_effectiveness_periodic()
void logger_control_effectiveness_periodic (void) extern
Log the values to file.
Definition at line 117 of file logger_control_effectiveness.c.
References commands, foo, get_sys_time_float(), LogFileIsOpen, LogFormatHeader, LogFormatVect3, LogWrite, Int32Rates::p, pprzLogFile, Int32Rates::q, Int32Rates::r, stateGetAccelBody_i(), stateGetAirspeed_f(), stateGetBodyRates_i(), stateGetPositionEnu_i(), stateGetSpeedEnu_i(), EnuCoor_i::x, EnuCoor_i::y, and EnuCoor_i::z.
logger_control_effectiveness_start()
void logger_control_effectiveness_start (void) extern
Write the log header line according to the enabled parts.
Definition at line 80 of file logger_control_effectiveness.c.
References foo, LogFileIsOpen, LOGGER_CONTROL_EFFECTIVENESS_FILE_PATH, LogOpen, LogWrite, and pprzLogFile.
logger_control_effectiveness_stop()
void logger_control_effectiveness_stop (void) extern
Definition at line 109 of file logger_control_effectiveness.c.
References LogClose, LogFileIsOpen, and pprzLogFile.