Paparazzi UAS: sw/airborne/filters/low_pass_filter_types.h File Reference
low_pass_filter_types.h File Reference
Definitions and inline functions for 1st order low-pass filter vector types.
#include "std.h"
#include "filters/low_pass_filter.h"
#include "math/pprz_algebra_float.h"
Data Structures
struct FirstOrderLowPassVect3
struct Butterworth2LowPassVect3
struct Butterworth4LowPassVect3
Functions
static void init_first_order_low_pass_vect3 (struct FirstOrderLowPassVect3 *filter, const struct FloatVect3 *cut_off, const float dt)
Initialize a set of first order low-pass filters to zero for 3D vector data.
static struct FloatVect3 get_first_order_low_pass_vect3 (const struct FirstOrderLowPassVect3 *filter)
Retrieve the filtered output from 3D vector first order low-pass filters.
static struct FloatRates get_first_order_low_pass_rates (const struct FirstOrderLowPassVect3 *filter)
Retrieve the filtered output from 3D vector first order low-pass filters.
static struct FloatVect3 update_first_order_low_pass_vect3 (struct FirstOrderLowPassVect3 *filter, const struct FloatVect3 *input)
Update 3D vector first order low-pass filters with new input data.
static struct FloatRates update_first_order_low_pass_rates (struct FirstOrderLowPassVect3 *filter, const struct FloatRates *input)
Update 3D vector first order low-pass filters with new rate input data.
static void reset_first_order_low_pass_vect3 (struct FirstOrderLowPassVect3 *filter, const struct FloatVect3 *value)
Reset 3D vector first order low-pass filters to a specific value.
static void reset_first_order_low_pass_rates (struct FirstOrderLowPassVect3 *filter, const struct FloatRates *value)
Reset 3D vector first order low-pass filters to specific rate values.
static void init_first_order_low_pass_array (const uint8_t n, struct FirstOrderLowPass filter_array[restrict n], const float cut_off[restrict n], const float dt)
Initialize an array of first order low-pass filters.
static void update_first_order_low_pass_array (const uint8_t n, struct FirstOrderLowPass filter_array[restrict n], const float input_array[restrict n])
Update an array of first order low-pass filters.
static void reset_first_order_low_pass_array (const uint8_t n, struct FirstOrderLowPass filter_array[restrict n], const float value_array[restrict n])
Reset an array of first order low-pass filters to specific values.
static void get_first_order_low_pass_array (const uint8_t n, const struct FirstOrderLowPass filter_array[restrict n], float output_array[restrict n])
Retrieve the filtered outputs from an array of first order low-pass filters.
static void init_butterworth_2_low_pass_vect3 (struct Butterworth2LowPassVect3 *filter, const struct FloatVect3 *cut_off, const float dt)
Initialize a set of Butterworth low-pass filters to zero for 3D vector data.
static struct FloatVect3 get_butterworth_2_low_pass_vect3 (const struct Butterworth2LowPassVect3 *filter)
Retrieve the filtered output from 3D vector Butterworth filters.
static struct FloatRates get_butterworth_2_low_pass_rates (const struct Butterworth2LowPassVect3 *filter)
Retrieve the filtered output from a Butterworth low-pass filter.
static struct FloatVect3 update_butterworth_2_low_pass_vect3 (struct Butterworth2LowPassVect3 *filter, const struct FloatVect3 *input)
Update 3D vector Butterworth filters with new input data.
static struct FloatRates update_butterworth_2_low_pass_rates (struct Butterworth2LowPassVect3 *filter, const struct FloatRates *input)
Update 3D vector Butterworth filters with new rate input data.
static void reset_butterworth_2_low_pass_vect3 (struct Butterworth2LowPassVect3 *filter, const struct FloatVect3 *value)
Reset 3D vector Butterworth filters to a specific value.
static void reset_butterworth_2_low_pass_rates (struct Butterworth2LowPassVect3 *filter, const struct FloatRates *value)
Reset 3D vector Butterworth filters to specific rate values.
static void init_butterworth_2_low_pass_array (const uint8_t n, Butterworth2LowPass filter_array[restrict n], const float cut_off[restrict n], const float dt)
Initialize an array of Butterworth low-pass filters to zero.
static void update_butterworth_2_low_pass_array (const uint8_t n, Butterworth2LowPass filter_array[restrict n], const float input_array[restrict n])
Update an array of Butterworth low-pass filters with new input data.
static void reset_butterworth_2_low_pass_array (const uint8_t n, Butterworth2LowPass filter_array[restrict n], const float value_array[restrict n])
Reset an array of Butterworth low-pass filters to specific values.
static void get_butterworth_2_low_pass_array (const uint8_t n, const Butterworth2LowPass filter_array[restrict n], float output_array[restrict n])
Retrieve the filtered outputs from an array of Butterworth low-pass filters.
static void init_butterworth_4_low_pass_vect3 (struct Butterworth4LowPassVect3 *filter, const struct FloatVect3 *cut_off, const float dt)
Initialize a set of Butterworth low-pass filters to zero for 3D vector data.
static struct FloatVect3 get_butterworth_4_low_pass_vect3 (const struct Butterworth4LowPassVect3 *filter)
Retrieve the filtered output from 3D vector Butterworth filters.
static struct FloatRates get_butterworth_4_low_pass_rates (const struct Butterworth4LowPassVect3 *filter)
Retrieve the filtered output from a Butterworth low-pass filter.
static struct FloatVect3 update_butterworth_4_low_pass_vect3 (struct Butterworth4LowPassVect3 *filter, const struct FloatVect3 *input)
Update 3D vector Butterworth filters with new input data.
static struct FloatRates update_butterworth_4_low_pass_rates (struct Butterworth4LowPassVect3 *filter, const struct FloatRates *input)
Update 3D vector Butterworth filters with new rate input data.
static void reset_butterworth_4_low_pass_vect3 (struct Butterworth4LowPassVect3 *filter, const struct FloatVect3 *value)
Reset 3D vector Butterworth filters to a specific value.
static void reset_butterworth_4_low_pass_rates (struct Butterworth4LowPassVect3 *filter, const struct FloatRates *value)
Reset 3D vector Butterworth filters to specific rate values.
static void init_butterworth_4_low_pass_array (const uint8_t n, Butterworth4LowPass filter_array[restrict n], const float cut_off[restrict n], const float dt)
Initialize an array of Butterworth low-pass filters to zero.
static void update_butterworth_4_low_pass_array (const uint8_t n, Butterworth4LowPass filter_array[restrict n], const float input_array[restrict n])
Update an array of Butterworth low-pass filters with new input data.
static void reset_butterworth_4_low_pass_array (const uint8_t n, Butterworth4LowPass filter_array[restrict n], const float value_array[restrict n])
Reset an array of Butterworth low-pass filters to specific values.
static void get_butterworth_4_low_pass_array (const uint8_t n, const Butterworth4LowPass filter_array[restrict n], float output_array[restrict n])
Retrieve the filtered outputs from an array of Butterworth low-pass filters.
Detailed Description
Definitions and inline functions for 1st order low-pass filter vector types.
Provides structures and functions to initialize, update, reset, and get outputs from 1st order low-pass filter vectors.
Author
Justin Dubois j.p.g.nosp@m..dub.nosp@m.ois@s.nosp@m.tude.nosp@m.nt.tu.nosp@m.delf.nosp@m.t.nl
Definition in file low_pass_filter_types.h.
Data Structure Documentation
FirstOrderLowPassVect3
struct FirstOrderLowPassVect3
Definition at line 39 of file low_pass_filter_types.h.
Data Fields
struct FirstOrderLowPass x
struct FirstOrderLowPass y
struct FirstOrderLowPass z
Butterworth2LowPassVect3
struct Butterworth2LowPassVect3
Definition at line 210 of file low_pass_filter_types.h.
Data Fields
Butterworth2LowPass x
Butterworth2LowPass y
Butterworth2LowPass z
Butterworth4LowPassVect3
struct Butterworth4LowPassVect3
Definition at line 380 of file low_pass_filter_types.h.
Data Fields
Butterworth4LowPass x
Butterworth4LowPass y
Butterworth4LowPass z
Function Documentation
get_butterworth_2_low_pass_array()
static void get_butterworth_2_low_pass_array (const uint8_t n, const Butterworth2LowPass filter_array[restrict n], float output_array[restrict n]) inline static
Retrieve the filtered outputs from an array of Butterworth low-pass filters.
Parameters
[in] n Number of filters in the array.
[in] filter_array Array of Butterworth2LowPass filters.
[out] output_array Array to store the filtered output values.
Definition at line 372 of file low_pass_filter_types.h.
References foo, and get_butterworth_2_low_pass().
get_butterworth_2_low_pass_rates()
static struct FloatRates get_butterworth_2_low_pass_rates (const struct Butterworth2LowPassVect3 * filter) inline static
Retrieve the filtered output from a Butterworth low-pass filter.
Parameters
[in] filter Butterworth2LowPass filter instance.
Returns
Filtered output value.
Definition at line 252 of file low_pass_filter_types.h.
References foo, get_butterworth_2_low_pass(), FloatRates::p, FloatVect3::x, FloatVect3::y, and FloatVect3::z.
Referenced by update_butterworth_2_low_pass_rates().
get_butterworth_2_low_pass_vect3()
static struct FloatVect3 get_butterworth_2_low_pass_vect3 (const struct Butterworth2LowPassVect3 * filter) inline static
Retrieve the filtered output from 3D vector Butterworth filters.
Parameters
[in] filter Struct containing Butterworth filters for x, y, z components.
Returns
FloatVect3 struct containing the filtered output values.
Definition at line 237 of file low_pass_filter_types.h.
References foo, get_butterworth_2_low_pass(), FloatVect3::x, FloatVect3::y, and FloatVect3::z.
Referenced by update_butterworth_2_low_pass_vect3().
get_butterworth_4_low_pass_array()
static void get_butterworth_4_low_pass_array (const uint8_t n, const Butterworth4LowPass filter_array[restrict n], float output_array[restrict n]) inline static
Retrieve the filtered outputs from an array of Butterworth low-pass filters.
Parameters
[in] n Number of filters in the array.
[in] filter_array Array of Butterworth4LowPass filters.
[out] output_array Array to store the filtered output values.
Definition at line 542 of file low_pass_filter_types.h.
References foo, and get_butterworth_4_low_pass().
get_butterworth_4_low_pass_rates()
static struct FloatRates get_butterworth_4_low_pass_rates (const struct Butterworth4LowPassVect3 * filter) inline static
Retrieve the filtered output from a Butterworth low-pass filter.
Parameters
[in] filter Butterworth4LowPass filter instance.
Returns
Filtered output value.
Definition at line 422 of file low_pass_filter_types.h.
References foo, get_butterworth_4_low_pass(), FloatRates::p, FloatVect3::x, FloatVect3::y, and FloatVect3::z.
Referenced by update_butterworth_4_low_pass_rates().
get_butterworth_4_low_pass_vect3()
static struct FloatVect3 get_butterworth_4_low_pass_vect3 (const struct Butterworth4LowPassVect3 * filter) inline static
Retrieve the filtered output from 3D vector Butterworth filters.
Parameters
[in] filter Struct containing Butterworth filters for x, y, z components.
Returns
FloatVect3 struct containing the filtered output values.
Definition at line 407 of file low_pass_filter_types.h.
References foo, get_butterworth_4_low_pass(), FloatVect3::x, FloatVect3::y, and FloatVect3::z.
Referenced by update_butterworth_4_low_pass_vect3().
get_first_order_low_pass_array()
static void get_first_order_low_pass_array (const uint8_t n, const struct FirstOrderLowPass filter_array[restrict n], float output_array[restrict n]) inline static
Retrieve the filtered outputs from an array of first order low-pass filters.
Parameters
n Number of filters in the array.
filter_array Array of FirstOrderLowPass filters.
output_array Array to store the filtered output values.
Definition at line 201 of file low_pass_filter_types.h.
References foo, and get_first_order_low_pass().
get_first_order_low_pass_rates()
static struct FloatRates get_first_order_low_pass_rates (const struct FirstOrderLowPassVect3 * filter) inline static
Retrieve the filtered output from 3D vector first order low-pass filters.
Parameters
[in] filter Struct containing first order low-pass filters for x, y, z components.
Returns
FloatRates struct containing the filtered output rate values.
Definition at line 81 of file low_pass_filter_types.h.
References foo, get_first_order_low_pass(), and FloatRates::p.
Referenced by update_first_order_low_pass_rates().
get_first_order_low_pass_vect3()
static struct FloatVect3 get_first_order_low_pass_vect3 (const struct FirstOrderLowPassVect3 * filter) inline static
Retrieve the filtered output from 3D vector first order low-pass filters.
Parameters
[in] filter Struct containing first order low-pass filters for x, y, z components.
Returns
FloatVect3 struct containing the filtered output values.
Definition at line 66 of file low_pass_filter_types.h.
References foo, get_first_order_low_pass(), and FloatVect3::x.
Referenced by update_first_order_low_pass_vect3().
init_butterworth_2_low_pass_array()
static void init_butterworth_2_low_pass_array (const uint8_t n, Butterworth2LowPass filter_array[restrict n], const float cut_off[restrict n], const float dt) inline static
Initialize an array of Butterworth low-pass filters to zero.
Parameters
[in] n Number of filters to initialize.
[out] filter_array Array of Butterworth2LowPass filters to initialize.
[in] cut_off Time constant for the filters (s).
[in] dt Sampling time interval (seconds).
Definition at line 327 of file low_pass_filter_types.h.
References foo, and init_butterworth_2_low_pass().
init_butterworth_2_low_pass_vect3()
static void init_butterworth_2_low_pass_vect3 (struct Butterworth2LowPassVect3 * filter, const struct FloatVect3 * cut_off, const float dt) inline static
Initialize a set of Butterworth low-pass filters to zero for 3D vector data.
Parameters
[out] filter Struct containing Butterworth filters for x, y, z components.
[in] cut_off Time constant for the filters (s).
[in] dt Sampling time interval (seconds).
Definition at line 223 of file low_pass_filter_types.h.
References foo, init_butterworth_2_low_pass(), Butterworth2LowPassVect3::x, Butterworth2LowPassVect3::y, and Butterworth2LowPassVect3::z.
init_butterworth_4_low_pass_array()
static void init_butterworth_4_low_pass_array (const uint8_t n, Butterworth4LowPass filter_array[restrict n], const float cut_off[restrict n], const float dt) inline static
Initialize an array of Butterworth low-pass filters to zero.
Parameters
[in] n Number of filters to initialize.
[out] filter_array Array of Butterworth4LowPass filters to initialize.
[in] cut_off Time constant for the filters (s).
[in] dt Sampling time interval (seconds).
Definition at line 497 of file low_pass_filter_types.h.
References foo, and init_butterworth_4_low_pass().
init_butterworth_4_low_pass_vect3()
static void init_butterworth_4_low_pass_vect3 (struct Butterworth4LowPassVect3 * filter, const struct FloatVect3 * cut_off, const float dt) inline static
Initialize a set of Butterworth low-pass filters to zero for 3D vector data.
Parameters
[out] filter Struct containing Butterworth filters for x, y, z components.
[in] cut_off Time constant for the filters (s).
[in] dt Sampling time interval (seconds).
Definition at line 393 of file low_pass_filter_types.h.
References foo, init_butterworth_4_low_pass(), Butterworth4LowPassVect3::x, Butterworth4LowPassVect3::y, and Butterworth4LowPassVect3::z.
init_first_order_low_pass_array()
static void init_first_order_low_pass_array (const uint8_t n, struct FirstOrderLowPass filter_array[restrict n], const float cut_off[restrict n], const float dt) inline static
Initialize an array of first order low-pass filters.
Parameters
n Number of filters in the array.
filter_array Array of FirstOrderLowPass filters to initialize.
cut_off Time constant for the filters (s).
dt Sampling time interval (seconds).
Definition at line 156 of file low_pass_filter_types.h.
References foo, and init_first_order_low_pass().
init_first_order_low_pass_vect3()
static void init_first_order_low_pass_vect3 (struct FirstOrderLowPassVect3 * filter, const struct FloatVect3 * cut_off, const float dt) inline static
Initialize a set of first order low-pass filters to zero for 3D vector data.
Parameters
[out] filter Struct containing first order low-pass filters for x, y, z components.
[in] cut_off Time constant for the filters (s).
[in] dt Sampling time interval (seconds).
Definition at line 52 of file low_pass_filter_types.h.
References foo, init_first_order_low_pass(), FirstOrderLowPassVect3::x, FirstOrderLowPassVect3::y, and FirstOrderLowPassVect3::z.
reset_butterworth_2_low_pass_array()
static void reset_butterworth_2_low_pass_array (const uint8_t n, Butterworth2LowPass filter_array[restrict n], const float value_array[restrict n]) inline static
Reset an array of Butterworth low-pass filters to specific values.
Parameters
[in] n Number of filters in the array.
[out] filter_array Array of Butterworth2LowPass filters to reset.
[in] value_array Array containing reset values for each filter.
Definition at line 357 of file low_pass_filter_types.h.
References foo, and reset_butterworth_2_low_pass().
reset_butterworth_2_low_pass_rates()
static void reset_butterworth_2_low_pass_rates (struct Butterworth2LowPassVect3 * filter, const struct FloatRates * value) inline static
Reset 3D vector Butterworth filters to specific rate values.
Parameters
[out] filter Struct containing Butterworth filters for x, y, z components.
[in] value Pointer to FloatRates struct containing the reset values.
Definition at line 311 of file low_pass_filter_types.h.
References FloatRates::p, FloatRates::q, FloatRates::r, reset_butterworth_2_low_pass(), Butterworth2LowPassVect3::x, Butterworth2LowPassVect3::y, and Butterworth2LowPassVect3::z.
reset_butterworth_2_low_pass_vect3()
static void reset_butterworth_2_low_pass_vect3 (struct Butterworth2LowPassVect3 * filter, const struct FloatVect3 * value) inline static
Reset 3D vector Butterworth filters to a specific value.
Parameters
[out] filter Struct containing Butterworth filters for x, y, z components.
[in] value Pointer to FloatVect3 struct containing the reset value.
Definition at line 297 of file low_pass_filter_types.h.
References reset_butterworth_2_low_pass(), Butterworth2LowPassVect3::x, FloatVect3::x, Butterworth2LowPassVect3::y, FloatVect3::y, Butterworth2LowPassVect3::z, and FloatVect3::z.
reset_butterworth_4_low_pass_array()
static void reset_butterworth_4_low_pass_array (const uint8_t n, Butterworth4LowPass filter_array[restrict n], const float value_array[restrict n]) inline static
Reset an array of Butterworth low-pass filters to specific values.
Parameters
[in] n Number of filters in the array.
[out] filter_array Array of Butterworth4LowPass filters to reset.
[in] value_array Array containing reset values for each filter.
Definition at line 527 of file low_pass_filter_types.h.
References foo, and reset_butterworth_4_low_pass().
reset_butterworth_4_low_pass_rates()
static void reset_butterworth_4_low_pass_rates (struct Butterworth4LowPassVect3 * filter, const struct FloatRates * value) inline static
Reset 3D vector Butterworth filters to specific rate values.
Parameters
[out] filter Struct containing Butterworth filters for x, y, z components.
[in] value Pointer to FloatRates struct containing the reset values.
Definition at line 481 of file low_pass_filter_types.h.
References FloatRates::p, FloatRates::q, FloatRates::r, reset_butterworth_4_low_pass(), Butterworth4LowPassVect3::x, Butterworth4LowPassVect3::y, and Butterworth4LowPassVect3::z.
reset_butterworth_4_low_pass_vect3()
static void reset_butterworth_4_low_pass_vect3 (struct Butterworth4LowPassVect3 * filter, const struct FloatVect3 * value) inline static
Reset 3D vector Butterworth filters to a specific value.
Parameters
[out] filter Struct containing Butterworth filters for x, y, z components.
[in] value Pointer to FloatVect3 struct containing the reset value.
Definition at line 467 of file low_pass_filter_types.h.
References reset_butterworth_4_low_pass(), Butterworth4LowPassVect3::x, FloatVect3::x, Butterworth4LowPassVect3::y, FloatVect3::y, Butterworth4LowPassVect3::z, and FloatVect3::z.
reset_first_order_low_pass_array()
static void reset_first_order_low_pass_array (const uint8_t n, struct FirstOrderLowPass filter_array[restrict n], const float value_array[restrict n]) inline static
Reset an array of first order low-pass filters to specific values.
Parameters
n Number of filters in the array.
filter_array Array of FirstOrderLowPass filters to reset.
value_array Array of values to reset the filters to.
Definition at line 186 of file low_pass_filter_types.h.
References foo, and reset_first_order_low_pass().
reset_first_order_low_pass_rates()
static void reset_first_order_low_pass_rates (struct FirstOrderLowPassVect3 * filter, const struct FloatRates * value) inline static
Reset 3D vector first order low-pass filters to specific rate values.
Parameters
[out] filter Struct containing first order low-pass filters for x, y, z components.
[in] value Pointer to FloatRates struct containing the reset values.
Definition at line 140 of file low_pass_filter_types.h.
References FloatRates::p, FloatRates::q, FloatRates::r, reset_first_order_low_pass(), FirstOrderLowPassVect3::x, FirstOrderLowPassVect3::y, and FirstOrderLowPassVect3::z.
reset_first_order_low_pass_vect3()
static void reset_first_order_low_pass_vect3 (struct FirstOrderLowPassVect3 * filter, const struct FloatVect3 * value) inline static
Reset 3D vector first order low-pass filters to a specific value.
Parameters
[out] filter Struct containing first order low-pass filters for x, y, z components.
[in] value Pointer to FloatVect3 struct containing the reset value.
Definition at line 126 of file low_pass_filter_types.h.
References reset_first_order_low_pass(), FirstOrderLowPassVect3::x, FloatVect3::x, FirstOrderLowPassVect3::y, FloatVect3::y, FirstOrderLowPassVect3::z, and FloatVect3::z.
update_butterworth_2_low_pass_array()
static void update_butterworth_2_low_pass_array (const uint8_t n, Butterworth2LowPass filter_array[restrict n], const float input_array[restrict n]) inline static
Update an array of Butterworth low-pass filters with new input data.
Parameters
[in] n Number of filters in the array.
[in,out] filter_array Array of Butterworth2LowPass filters to update.
[in] input_array Array containing new input data for each filter.
Definition at line 342 of file low_pass_filter_types.h.
References foo, and update_butterworth_2_low_pass().
update_butterworth_2_low_pass_rates()
static struct FloatRates update_butterworth_2_low_pass_rates (struct Butterworth2LowPassVect3 * filter, const struct FloatRates * input) inline static
Update 3D vector Butterworth filters with new rate input data.
Parameters
[in,out] filter Struct containing Butterworth filters for x, y, z components.
[in] input Pointer to FloatRates struct containing new input rate data.
Definition at line 282 of file low_pass_filter_types.h.
References get_butterworth_2_low_pass_rates(), update_butterworth_2_low_pass(), FloatVect3::x, FloatVect3::y, and FloatVect3::z.
update_butterworth_2_low_pass_vect3()
static struct FloatVect3 update_butterworth_2_low_pass_vect3 (struct Butterworth2LowPassVect3 * filter, const struct FloatVect3 * input) inline static
Update 3D vector Butterworth filters with new input data.
Parameters
[in,out] filter Struct containing Butterworth filters for x, y, z components.
[in] input Pointer to FloatVect3 struct containing new input data.
Definition at line 267 of file low_pass_filter_types.h.
References get_butterworth_2_low_pass_vect3(), update_butterworth_2_low_pass(), FloatVect3::x, FloatVect3::y, and FloatVect3::z.
update_butterworth_4_low_pass_array()
static void update_butterworth_4_low_pass_array (const uint8_t n, Butterworth4LowPass filter_array[restrict n], const float input_array[restrict n]) inline static
Update an array of Butterworth low-pass filters with new input data.
Parameters
[in] n Number of filters in the array.
[in,out] filter_array Array of Butterworth4LowPass filters to update.
[in] input_array Array containing new input data for each filter.
Definition at line 512 of file low_pass_filter_types.h.
References foo, and update_butterworth_4_low_pass().
update_butterworth_4_low_pass_rates()
static struct FloatRates update_butterworth_4_low_pass_rates (struct Butterworth4LowPassVect3 * filter, const struct FloatRates * input) inline static
Update 3D vector Butterworth filters with new rate input data.
Parameters
[in,out] filter Struct containing Butterworth filters for x, y, z components.
[in] input Pointer to FloatRates struct containing new input rate data.
Definition at line 452 of file low_pass_filter_types.h.
References get_butterworth_4_low_pass_rates(), update_butterworth_4_low_pass(), FloatVect3::x, FloatVect3::y, and FloatVect3::z.
update_butterworth_4_low_pass_vect3()
static struct FloatVect3 update_butterworth_4_low_pass_vect3 (struct Butterworth4LowPassVect3 * filter, const struct FloatVect3 * input) inline static
Update 3D vector Butterworth filters with new input data.
Parameters
[in,out] filter Struct containing Butterworth filters for x, y, z components.
[in] input Pointer to FloatVect3 struct containing new input data.
Definition at line 437 of file low_pass_filter_types.h.
References get_butterworth_4_low_pass_vect3(), update_butterworth_4_low_pass(), FloatVect3::x, FloatVect3::y, and FloatVect3::z.
update_first_order_low_pass_array()
static void update_first_order_low_pass_array (const uint8_t n, struct FirstOrderLowPass filter_array[restrict n], const float input_array[restrict n]) inline static
Update an array of first order low-pass filters.
Parameters
n Number of filters in the array.
filter_array Array of FirstOrderLowPass filters to update.
input_array Array of input values for the filters.
Definition at line 171 of file low_pass_filter_types.h.
References foo, and update_first_order_low_pass().
update_first_order_low_pass_rates()
static struct FloatRates update_first_order_low_pass_rates (struct FirstOrderLowPassVect3 * filter, const struct FloatRates * input) inline static
Update 3D vector first order low-pass filters with new rate input data.
Parameters
[in,out] filter Struct containing first order low-pass filters for x, y, z components.
[in] input Pointer to FloatRates struct containing new input rate data.
Definition at line 111 of file low_pass_filter_types.h.
References get_first_order_low_pass_rates(), update_first_order_low_pass(), FloatVect3::x, FloatVect3::y, and FloatVect3::z.
update_first_order_low_pass_vect3()
static struct FloatVect3 update_first_order_low_pass_vect3 (struct FirstOrderLowPassVect3 * filter, const struct FloatVect3 * input) inline static
Update 3D vector first order low-pass filters with new input data.
Parameters
[in,out] filter Struct containing first order low-pass filters for x, y, z components.
[in] input Pointer to FloatVect3 struct containing new input data.
Definition at line 96 of file low_pass_filter_types.h.
References get_first_order_low_pass_vect3(), update_first_order_low_pass(), FloatVect3::x, FloatVect3::y, and FloatVect3::z.