Paparazzi UAS: sw/airborne/filters/low_pass_zoh_filter_types.h File Reference
low_pass_zoh_filter_types.h File Reference
#include "std.h"
#include "filters/low_pass_zoh_filter.h"
#include "math/pprz_algebra_float.h"
Functions
static void init_first_order_zoh_low_pass_array (const uint8_t n, struct FirstOrderZOHLowPass filter_array[restrict n], const float omega[restrict n], const float sample_time)
Initialize a set of first order ZOH low-pass filters to zero for 3D vector data.
static void update_first_order_zoh_low_pass_array (const uint8_t n, struct FirstOrderZOHLowPass filter_array[restrict n], const float input_array[restrict n])
Update an array of first order ZOH low-pass filters.
static void reset_first_order_zoh_low_pass_array (const uint8_t n, struct FirstOrderZOHLowPass filter_array[restrict n], const float value_array[restrict n])
Reset an array of first order ZOH low-pass filters to specific values.
static void get_first_order_zoh_low_pass_array (const uint8_t n, const struct FirstOrderZOHLowPass filter_array[restrict n], float output_array[restrict n])
Retrieve the filtered outputs from an array of first order ZOH low-pass filters.
Function Documentation
get_first_order_zoh_low_pass_array()
static void get_first_order_zoh_low_pass_array (const uint8_t n, const struct FirstOrderZOHLowPass filter_array[restrict n], float output_array[restrict n]) inline static
Retrieve the filtered outputs from an array of first order ZOH low-pass filters.
Parameters
[in] n Number of filters in the array.
[in] filter_array Array of FirstOrderZOHLowPass filters.
[out] output_array Array to store the filtered output values.
Definition at line 89 of file low_pass_zoh_filter_types.h.
References foo.
Referenced by stabilization_andi_run().
init_first_order_zoh_low_pass_array()
static void init_first_order_zoh_low_pass_array (const uint8_t n, struct FirstOrderZOHLowPass filter_array[restrict n], const float omega[restrict n], const float sample_time) inline static
Initialize a set of first order ZOH low-pass filters to zero for 3D vector data.
Parameters
[out] filter_array Array of FirstOrderZOHLowPass filters to initialize.
[in] omega Cut-off frequencies for the filters (rad/s).
[in] sample_time Sampling time interval (seconds).
Definition at line 45 of file low_pass_zoh_filter_types.h.
References foo, and init_first_order_zoh_low_pass().
Referenced by stabilization_andi_init().
reset_first_order_zoh_low_pass_array()
static void reset_first_order_zoh_low_pass_array (const uint8_t n, struct FirstOrderZOHLowPass filter_array[restrict n], const float value_array[restrict n]) inline static
Reset an array of first order ZOH low-pass filters to specific values.
Parameters
[in] n Number of filters in the array.
[out] filter_array Array of FirstOrderZOHLowPass filters to reset.
[in] value_array Array of values to reset the filters to.
Definition at line 74 of file low_pass_zoh_filter_types.h.
References foo.
Referenced by stabilization_andi_enter().
update_first_order_zoh_low_pass_array()
static void update_first_order_zoh_low_pass_array (const uint8_t n, struct FirstOrderZOHLowPass filter_array[restrict n], const float input_array[restrict n]) inline static
Update an array of first order ZOH low-pass filters.
Parameters
[in] n Number of filters in the array.
[in,out] filter_array Array of FirstOrderZOHLowPass filters to update.
[in] input_array Array of input values for the filters.
Definition at line 60 of file low_pass_zoh_filter_types.h.
References foo, and update_first_order_zoh_low_pass().
Referenced by stabilization_andi_run().