Paparazzi UAS: sw/airborne/arch/lpc21/mcu_periph/sys_time_arch.c File Reference
sys_time_arch.c File Reference
LPC21 architecture
LPC21xx timing functions.
#include "mcu_periph/sys_time.h"
#include "armVIC.h"
Macros
#define SYS_TICK_IT TIR_MR0I
#define ACTUATORS_IT 0x00
#define PPM_IT 0x00
#define MB_SCALE_IT 0x00
#define MB_TACHO_IT 0x00
#define PWM_INPUT_IT1 0x00
#define PWM_INPUT_IT2 0x00
#define AMI601_IT 0x00
#define TRIGGER_IT 0x00
#define TIMER0_IT_MASK
Functions
void sys_time_arch_init (void)
static void sys_tick_irq_handler (void)
void TIMER0_ISR (void)
Detailed Description
LPC21xx timing functions.
Definition in file sys_time_arch.c.
Macro Definition Documentation
#define ACTUATORS_IT 0x00
Definition at line 51 of file sys_time_arch.c.
Referenced by TIMER0_ISR().
#define AMI601_IT 0x00
Definition at line 85 of file sys_time_arch.c.
Referenced by TIMER0_ISR().
#define MB_SCALE_IT 0x00
Definition at line 63 of file sys_time_arch.c.
Referenced by TIMER0_ISR().
#define MB_TACHO_IT 0x00
Definition at line 69 of file sys_time_arch.c.
Referenced by TIMER0_ISR().
#define PPM_IT 0x00
Definition at line 57 of file sys_time_arch.c.
Referenced by TIMER0_ISR().
#define PWM_INPUT_IT1 0x00
Definition at line 76 of file sys_time_arch.c.
Referenced by TIMER0_ISR().
#define PWM_INPUT_IT2 0x00
Definition at line 79 of file sys_time_arch.c.
Referenced by TIMER0_ISR().
#define SYS_TICK_IT TIR_MR0I
Definition at line 38 of file sys_time_arch.c.
Referenced by TIMER0_ISR().
#define TIMER0_IT_MASK
Value:
(SYS_TICK_IT          |  \
                        ACTUATORS_IT         |  \
                        PPM_IT               |  \
                        TRIGGER_IT           |  \
                        MB_SCALE_IT          |  \
                        MB_TACHO_IT          |  \
                        PWM_INPUT_IT1        |  \
                        PWM_INPUT_IT2        |  \
                        AMI601_IT)
Definition at line 94 of file sys_time_arch.c.
Referenced by TIMER0_ISR().
#define TRIGGER_IT 0x00
Definition at line 91 of file sys_time_arch.c.
Referenced by TIMER0_ISR().
Function Documentation
static void sys_tick_irq_handler (void) inline static
Definition at line 152 of file sys_time_arch.c.
References sys_time_timer::cb, sys_time::cpu_ticks_per_sec, sys_time_timer::duration, sys_time_timer::elapsed, sys_time_timer::end_time, sys_time_timer::in_use, LED_TOGGLE, sys_time::nb_sec, sys_time::nb_sec_rem, sys_time::nb_tick, sys_time::resolution_cpu_ticks, SYS_TIME_NB_TIMER, T0MR0, and sys_time::timer.
Referenced by TIMER0_ISR().
void sys_time_arch_init (void)
Definition at line 105 of file sys_time_arch.c.
References _VIC_ADDR, _VIC_CNTL, sys_time::cpu_ticks_per_sec, PCLK, sys_time::resolution, sys_time::resolution_cpu_ticks, T0CCR, T0EMR, T0MCR, T0MR0, T0PR, T0TCR, TCR_ENABLE, TCR_RESET, TIMER0_ISR(), TIMER0_VIC_SLOT, TMCR_MR0_I, VIC_BIT, VIC_ENABLE, VIC_TIMER0, VICIntEnable, and VICIntSelect.
void TIMER0_ISR (void)
Definition at line 179 of file sys_time_arch.c.
References ACTUATORS_IT, AMI601_ISR, AMI601_IT, ISR_ENTRY, ISR_EXIT, LED_TOGGLE, MB_SCALE_IT, MB_TACHO_IT, PPM_ISR, PPM_IT, PWM_INPUT_IT1, PWM_INPUT_IT2, Servos4015Mat_ISR, SERVOS_4017_ISR, ServosPPMMat_ISR, sys_tick_irq_handler(), SYS_TICK_IT, T0IR, TIMER0_IT_MASK, TRIG_ISR(), TRIGGER_IT, and VICVectAddr.
Referenced by sys_time_arch_init().