Paparazzi UAS: sw/airborne/modules/sensors/mag_lis3mdl.h File Reference
mag_lis3mdl.h File Reference
Module wrapper for ST LIS3MDL magnetometers.
#include "peripherals/lis3mdl.h"
Functions
void mag_lis3mdl_module_init (void)
void mag_lis3mdl_module_periodic (void)
void mag_lis3mdl_module_event (void)
void mag_lis3mdl_report (void)
Variables
struct Lis3mdl mag_lis3mdl
Detailed Description
Module wrapper for ST LIS3MDL magnetometers.
Definition in file mag_lis3mdl.h.
Function Documentation
mag_lis3mdl_module_event()
void mag_lis3mdl_module_event (void) extern
Definition at line 81 of file mag_lis3mdl.c.
References Lis3mdl::data, Lis3mdl::data_available, foo, get_sys_time_usec(), LIS3MDL_CHAN_X, LIS3MDL_CHAN_X_SIGN, LIS3MDL_CHAN_Y, LIS3MDL_CHAN_Y_SIGN, LIS3MDL_CHAN_Z, LIS3MDL_CHAN_Z_SIGN, lis3mdl_event(), mag_lis3mdl, mag_lis3mdl_report(), and MAG_LIS3MDL_SENDER_ID.
mag_lis3mdl_module_init()
void mag_lis3mdl_module_init (void) extern
Definition at line 55 of file mag_lis3mdl.c.
References ANGLE_BFP_OF_REAL, foo, imu_set_defaults_mag(), int32_rmat_of_eulers, LIS3MDL_ADDR1, LIS3MDL_DATA_RATE_80_HZ, lis3mdl_init(), LIS3MDL_MODE_CONTINUOUS, LIS3MDL_PERFORMANCE_ULTRA_HIGH, LIS3MDL_SCALE_4_GAUSS, mag_lis3mdl, and MAG_LIS3MDL_SENDER_ID.
mag_lis3mdl_module_periodic()
void mag_lis3mdl_module_periodic (void) extern
Definition at line 76 of file mag_lis3mdl.c.
References lis3mdl_periodic(), and mag_lis3mdl.
mag_lis3mdl_report()
void mag_lis3mdl_report (void) extern
Definition at line 108 of file mag_lis3mdl.c.
References Lis3mdl::data, DefaultChannel, DefaultDevice, foo, LIS3MDL_CHAN_X, LIS3MDL_CHAN_X_SIGN, LIS3MDL_CHAN_Y, LIS3MDL_CHAN_Y_SIGN, LIS3MDL_CHAN_Z, LIS3MDL_CHAN_Z_SIGN, mag_lis3mdl, MAG_LIS3MDL_SENDER_ID, Int32Vect3::x, Int32Vect3::y, and Int32Vect3::z.
Referenced by mag_lis3mdl_module_event().
Variable Documentation
mag_lis3mdl
struct Lis3mdl mag_lis3mdl extern
Definition at line 53 of file mag_lis3mdl.c.
Referenced by mag_lis3mdl_module_event(), mag_lis3mdl_module_init(), mag_lis3mdl_module_periodic(), and mag_lis3mdl_report().