Paparazzi UAS: sw/airborne/modules/sensors/mag_uavcan.c File Reference
mag_uavcan.c File Reference
#include "modules/sensors/mag_uavcan.h"
#include "uavcan/uavcan.h"
#include "core/abi.h"
#include "uavcan.equipment.ahrs.MagneticFieldStrength.h"
#include "uavcan.equipment.ahrs.MagneticFieldStrength2.h"
#include "imu/imu.h"
#include "modules/datalink/downlink.h"
Functions
static void mag_uavcan_cb (struct uavcan_iface_t *iface, CanardRxTransfer *transfer)
static void mag_uavcan_cb2 (struct uavcan_iface_t *iface, CanardRxTransfer *transfer)
void mag_uavcan_init (void)
Variables
static uavcan_event mag_uavcan_ev
static uavcan_event mag_uavcan_ev2
static struct FloatVect3 default_uavcan_mag_scale = {1,1,1}
Detailed Description
Author
FabienB fabie.nosp@m.n-b@.nosp@m.githu.nosp@m.b.co.nosp@m.m Mag driver for UAVCAN message MagneticFieldStrength
Definition in file mag_uavcan.c.
Function Documentation
mag_uavcan_cb()
static void mag_uavcan_cb (struct uavcan_iface_t * iface, CanardRxTransfer * transfer) static
Definition at line 40 of file mag_uavcan.c.
References DefaultChannel, DefaultDevice, foo, get_sys_time_usec(), MAG_UAVCAN_SENDER_ID, msg, transfer(), Int32Vect3::x, Int32Vect3::y, and Int32Vect3::z.
Referenced by mag_uavcan_init().
mag_uavcan_cb2()
static void mag_uavcan_cb2 (struct uavcan_iface_t * iface, CanardRxTransfer * transfer) static
Definition at line 66 of file mag_uavcan.c.
References DefaultChannel, DefaultDevice, foo, get_sys_time_usec(), msg, transfer(), Int32Vect3::x, Int32Vect3::y, and Int32Vect3::z.
Referenced by mag_uavcan_init().
mag_uavcan_init()
void mag_uavcan_init (void)
Definition at line 94 of file mag_uavcan.c.
References default_uavcan_mag_scale, foo, imu_set_defaults_mag(), int32_rmat_of_eulers, mag_uavcan_cb(), mag_uavcan_cb2(), mag_uavcan_ev, mag_uavcan_ev2, MAG_UAVCAN_SENDER_ID, and uavcan_bind().
Variable Documentation
default_uavcan_mag_scale
struct FloatVect3 default_uavcan_mag_scale = {1,1,1} static
Definition at line 37 of file mag_uavcan.c.
Referenced by mag_uavcan_init().
mag_uavcan_ev
uavcan_event mag_uavcan_ev static
Definition at line 34 of file mag_uavcan.c.
Referenced by mag_uavcan_init().
mag_uavcan_ev2
uavcan_event mag_uavcan_ev2 static
Definition at line 35 of file mag_uavcan.c.
Referenced by mag_uavcan_init().