Paparazzi UAS: sw/airborne/modules/sensors/mag_rm3100.h File Reference
mag_rm3100.h File Reference
Module wrapper for PNI RM3100 magnetometers.
#include "peripherals/rm3100.h"
Functions
void mag_rm3100_module_init (void)
void mag_rm3100_module_periodic (void)
void mag_rm3100_module_event (void)
void mag_rm3100_report (void)
Variables
struct Rm3100 mag_rm3100
Detailed Description
Module wrapper for PNI RM3100 magnetometers.
Definition in file mag_rm3100.h.
Function Documentation
mag_rm3100_module_event()
void mag_rm3100_module_event (void) extern
Definition at line 92 of file mag_rm3100.c.
References Rm3100::data, Rm3100::data_available, foo, get_sys_time_usec(), int32_rmat_vmult(), mag_rm3100, mag_rm3100_report(), MAG_RM3100_SENDER_ID, RM3100_CHAN_X, RM3100_CHAN_X_SIGN, RM3100_CHAN_Y, RM3100_CHAN_Y_SIGN, RM3100_CHAN_Z, RM3100_CHAN_Z_SIGN, rm3100_event(), and VECT3_COPY.
mag_rm3100_module_init()
void mag_rm3100_module_init (void) extern
Definition at line 73 of file mag_rm3100.c.
References ANGLE_BFP_OF_REAL, foo, int32_rmat_of_eulers, mag_rm3100, RM3100_ADDR, RM3100_DATA_RATE, and rm3100_init().
mag_rm3100_module_periodic()
void mag_rm3100_module_periodic (void) extern
Definition at line 87 of file mag_rm3100.c.
References mag_rm3100, and rm3100_periodic().
mag_rm3100_report()
void mag_rm3100_report (void) extern
Definition at line 127 of file mag_rm3100.c.
References Rm3100::data, DefaultChannel, DefaultDevice, foo, mag_rm3100, MAG_RM3100_SENDER_ID, RM3100_CHAN_X, RM3100_CHAN_X_SIGN, RM3100_CHAN_Y, RM3100_CHAN_Y_SIGN, RM3100_CHAN_Z, RM3100_CHAN_Z_SIGN, Int32Vect3::x, Int32Vect3::y, and Int32Vect3::z.
Referenced by mag_rm3100_module_event().
Variable Documentation
mag_rm3100
struct Rm3100 mag_rm3100 extern
Definition at line 71 of file mag_rm3100.c.
Referenced by mag_rm3100_module_event(), mag_rm3100_module_init(), mag_rm3100_module_periodic(), and mag_rm3100_report().