Paparazzi UAS: sw/airborne/modules/calibration/mag_calib_ukf.h File Reference
mag_calib_ukf.h File Reference
#include "std.h"
Functions
void mag_calib_ukf_init (void)
void mag_calib_hotstart_write (void)
void mag_calib_hotstart_read (void)
void mag_calib_send_state (void)
Variables
bool mag_calib_ukf_reset_state
bool mag_calib_ukf_send_state
Detailed Description
Author
w.vlenterie Calibrate the magnetometer using an unscented kalman filter For more information please visit the following links:
https://github.com/sfwa/trical
http://au.tono.my/log/20131213-trical-magnetometer-calibration.html
http://www.acsu.buffalo.edu/~johnc/mag_cal05.pdf
Definition in file mag_calib_ukf.h.
Function Documentation
mag_calib_hotstart_read()
void mag_calib_hotstart_read (void)
Definition at line 215 of file mag_calib_ukf.c.
References foo, mag_calib, MAG_CALIB_UKF_HOTSTART_SAVE_FILE, and VERBOSE_PRINT.
Referenced by mag_calib_ukf_init().
mag_calib_hotstart_write()
void mag_calib_hotstart_write (void)
Definition at line 237 of file mag_calib_ukf.c.
References foo, mag_calib, and VERBOSE_PRINT.
mag_calib_send_state()
void mag_calib_send_state (void)
Definition at line 210 of file mag_calib_ukf.c.
References DefaultChannel, DefaultDevice, foo, and mag_calib.
Referenced by mag_calib_ukf_run().
mag_calib_ukf_init()
void mag_calib_ukf_init (void)
< GEO_MAG_SENDER_ID is defined in geo_mag.c so unknown
Definition at line 134 of file mag_calib_ukf.c.
References ABI_BROADCAST, foo, h_ev, mag_calib, mag_calib_hotstart_read(), MAG_CALIB_UKF_ABI_BIND_ID, MAG_CALIB_UKF_NOISE_RMS, MAG_CALIB_UKF_NORM, mag_calib_ukf_run(), mag_calib_update_field(), and mag_ev.
Variable Documentation
mag_calib_ukf_reset_state
bool mag_calib_ukf_reset_state extern
Definition at line 119 of file mag_calib_ukf.c.
Referenced by mag_calib_ukf_run().
mag_calib_ukf_send_state
bool mag_calib_ukf_send_state extern
Definition at line 120 of file mag_calib_ukf.c.
Referenced by mag_calib_ukf_run().