Paparazzi UAS: sw/airborne/modules/sensors/mag_ist8310.h File Reference
mag_ist8310.h File Reference
Module wrapper for Isentek IST8310 magnetometers.
#include "peripherals/ist8310.h"
Functions
void mag_ist8310_module_init (void)
void mag_ist8310_module_periodic (void)
void mag_ist8310_module_event (void)
void mag_ist8310_report (void)
Variables
struct IST8310 mag_ist8310
Detailed Description
Module wrapper for Isentek IST8310 magnetometers.
Definition in file mag_ist8310.h.
Function Documentation
mag_ist8310_module_event()
void mag_ist8310_module_event (void) extern
Definition at line 77 of file mag_ist8310.c.
References IST8310::data, IST8310::data_available, foo, get_sys_time_usec(), IST8310_CHAN_X, IST8310_CHAN_X_SIGN, IST8310_CHAN_Y, IST8310_CHAN_Y_SIGN, IST8310_CHAN_Z, IST8310_CHAN_Z_SIGN, ist8310_event(), mag_ist8310, mag_ist8310_report(), and MAG_IST8310_SENDER_ID.
mag_ist8310_module_init()
void mag_ist8310_module_init (void) extern
Definition at line 55 of file mag_ist8310.c.
References ANGLE_BFP_OF_REAL, foo, imu_set_defaults_mag(), int32_rmat_of_eulers, IST8310_ADDR, ist8310_init(), mag_ist8310, and MAG_IST8310_SENDER_ID.
mag_ist8310_module_periodic()
void mag_ist8310_module_periodic (void) extern
Definition at line 72 of file mag_ist8310.c.
References ist8310_periodic(), and mag_ist8310.
mag_ist8310_report()
void mag_ist8310_report (void) extern
Definition at line 104 of file mag_ist8310.c.
References IST8310::data, DefaultChannel, DefaultDevice, foo, IST8310_CHAN_X, IST8310_CHAN_X_SIGN, IST8310_CHAN_Y, IST8310_CHAN_Y_SIGN, IST8310_CHAN_Z, IST8310_CHAN_Z_SIGN, mag_ist8310, MAG_IST8310_SENDER_ID, Int32Vect3::x, Int32Vect3::y, and Int32Vect3::z.
Referenced by mag_ist8310_module_event().
Variable Documentation
mag_ist8310
struct IST8310 mag_ist8310 extern
Definition at line 53 of file mag_ist8310.c.
Referenced by mag_ist8310_module_event(), mag_ist8310_module_init(), mag_ist8310_module_periodic(), and mag_ist8310_report().