Paparazzi UAS: sw/airborne/modules/sensors/mag_hmc58xx.h File Reference
mag_hmc58xx.h File Reference
Module wrapper for Honeywell HMC5843 and HMC5883 magnetometers.
#include "peripherals/hmc58xx.h"
Functions
void mag_hmc58xx_module_init (void)
void mag_hmc58xx_module_periodic (void)
void mag_hmc58xx_module_event (void)
void mag_hmc58xx_report (void)
Variables
struct Hmc58xx mag_hmc58xx
Detailed Description
Module wrapper for Honeywell HMC5843 and HMC5883 magnetometers.
Definition in file mag_hmc58xx.h.
Function Documentation
mag_hmc58xx_module_event()
void mag_hmc58xx_module_event (void) extern
Definition at line 85 of file mag_hmc58xx.c.
References Hmc58xx::data, Hmc58xx::data_available, foo, get_sys_time_usec(), HMC58XX_CHAN_X, HMC58XX_CHAN_X_SIGN, HMC58XX_CHAN_Y, HMC58XX_CHAN_Y_SIGN, HMC58XX_CHAN_Z, HMC58XX_CHAN_Z_SIGN, hmc58xx_event(), int32_rmat_vmult(), mag_hmc58xx, mag_hmc58xx_report(), MAG_HMC58XX_SENDER_ID, and VECT3_COPY.
mag_hmc58xx_module_init()
void mag_hmc58xx_module_init (void) extern
Definition at line 66 of file mag_hmc58xx.c.
References ANGLE_BFP_OF_REAL, foo, HMC58XX_ADDR, hmc58xx_init(), int32_rmat_of_eulers, and mag_hmc58xx.
mag_hmc58xx_module_periodic()
void mag_hmc58xx_module_periodic (void) extern
Definition at line 80 of file mag_hmc58xx.c.
References hmc58xx_periodic(), and mag_hmc58xx.
mag_hmc58xx_report()
void mag_hmc58xx_report (void) extern
Definition at line 120 of file mag_hmc58xx.c.
References Hmc58xx::data, DefaultChannel, DefaultDevice, foo, HMC58XX_CHAN_X, HMC58XX_CHAN_X_SIGN, HMC58XX_CHAN_Y, HMC58XX_CHAN_Y_SIGN, HMC58XX_CHAN_Z, HMC58XX_CHAN_Z_SIGN, mag_hmc58xx, MAG_HMC58XX_SENDER_ID, Int32Vect3::x, Int32Vect3::y, and Int32Vect3::z.
Referenced by mag_hmc58xx_module_event().
Variable Documentation
mag_hmc58xx
struct Hmc58xx mag_hmc58xx extern
Definition at line 64 of file mag_hmc58xx.c.
Referenced by mag_hmc58xx_module_event(), mag_hmc58xx_module_init(), mag_hmc58xx_module_periodic(), and mag_hmc58xx_report().