Paparazzi UAS: sw/airborne/modules/sensors/mag_uavcan.h File Reference
mag_uavcan.h File Reference
Functions
void mag_uavcan_init (void)
Detailed Description
Author
FabienB fabie.nosp@m.n-b@.nosp@m.githu.nosp@m.b.co.nosp@m.m Mag driver for UAVCAN message MagneticFieldStrength
Definition in file mag_uavcan.h.
Function Documentation
mag_uavcan_init()
void mag_uavcan_init (void) extern
Definition at line 94 of file mag_uavcan.c.
References default_uavcan_mag_scale, foo, imu_set_defaults_mag(), int32_rmat_of_eulers, mag_uavcan_cb(), mag_uavcan_cb2(), mag_uavcan_ev, mag_uavcan_ev2, MAG_UAVCAN_SENDER_ID, and uavcan_bind().