Paparazzi UAS: sw/airborne/modules/sensors/mag_qmc5883l.c File Reference
mag_qmc5883l.c File Reference
Module for QST QMC5883L magnetometer, the DB version.
#include "modules/sensors/mag_qmc5883l.h"
#include "mcu_periph/uart.h"
#include "pprzlink/messages.h"
#include "modules/datalink/downlink.h"
#include "generated/airframe.h"
#include "modules/core/abi.h"
Macros
#define QMC5883L_CHAN_X 0
#define QMC5883L_CHAN_Y 1
#define QMC5883L_CHAN_Z 2
#define QMC5883L_CHAN_X_SIGN +
#define QMC5883L_CHAN_Y_SIGN +
#define QMC5883L_CHAN_Z_SIGN +
#define QMC5883L_DATA_RATE QMC5883L_ODR_DEFAULT
#define QMC5883L_ADDR QMC5883L_ADDR0
Functions
void mag_qmc5883l_module_init (void)
void mag_qmc5883l_module_periodic (void)
void mag_qmc5883l_module_event (void)
void mag_qmc5883l_report (void)
Variables
struct Qmc5883l mag_qmc5883l
Detailed Description
Module for QST QMC5883L magnetometer, the DB version.
Definition in file mag_qmc5883l.c.
Macro Definition Documentation
QMC5883L_ADDR
#define QMC5883L_ADDR QMC5883L_ADDR0
Definition at line 58 of file mag_qmc5883l.c.
QMC5883L_CHAN_X
#define QMC5883L_CHAN_X 0
Definition at line 35 of file mag_qmc5883l.c.
QMC5883L_CHAN_X_SIGN
#define QMC5883L_CHAN_X_SIGN +
Definition at line 44 of file mag_qmc5883l.c.
QMC5883L_CHAN_Y
#define QMC5883L_CHAN_Y 1
Definition at line 38 of file mag_qmc5883l.c.
QMC5883L_CHAN_Y_SIGN
#define QMC5883L_CHAN_Y_SIGN +
Definition at line 47 of file mag_qmc5883l.c.
QMC5883L_CHAN_Z
#define QMC5883L_CHAN_Z 2
Definition at line 41 of file mag_qmc5883l.c.
QMC5883L_CHAN_Z_SIGN
#define QMC5883L_CHAN_Z_SIGN +
Definition at line 50 of file mag_qmc5883l.c.
QMC5883L_DATA_RATE
#define QMC5883L_DATA_RATE QMC5883L_ODR_DEFAULT
Definition at line 54 of file mag_qmc5883l.c.
Function Documentation
mag_qmc5883l_module_event()
void mag_qmc5883l_module_event (void)
Definition at line 92 of file mag_qmc5883l.c.
References Qmc5883l::data, Qmc5883l::data_available, foo, get_sys_time_usec(), int32_rmat_vmult(), mag_qmc5883l, mag_qmc5883l_report(), MAG_QMC5883L_SENDER_ID, QMC5883L_CHAN_X, QMC5883L_CHAN_X_SIGN, QMC5883L_CHAN_Y, QMC5883L_CHAN_Y_SIGN, QMC5883L_CHAN_Z, QMC5883L_CHAN_Z_SIGN, qmc5883l_event(), and VECT3_COPY.
mag_qmc5883l_module_init()
void mag_qmc5883l_module_init (void)
Definition at line 73 of file mag_qmc5883l.c.
References ANGLE_BFP_OF_REAL, foo, int32_rmat_of_eulers, mag_qmc5883l, QMC5883L_ADDR, QMC5883L_DATA_RATE, and qmc5883l_init().
mag_qmc5883l_module_periodic()
void mag_qmc5883l_module_periodic (void)
Definition at line 87 of file mag_qmc5883l.c.
References mag_qmc5883l, and qmc5883l_periodic().
mag_qmc5883l_report()
void mag_qmc5883l_report (void)
Definition at line 127 of file mag_qmc5883l.c.
References Qmc5883l::data, DefaultChannel, DefaultDevice, foo, mag_qmc5883l, MAG_QMC5883L_SENDER_ID, QMC5883L_CHAN_X, QMC5883L_CHAN_X_SIGN, QMC5883L_CHAN_Y, QMC5883L_CHAN_Y_SIGN, QMC5883L_CHAN_Z, QMC5883L_CHAN_Z_SIGN, Int32Vect3::x, Int32Vect3::y, and Int32Vect3::z.
Referenced by mag_qmc5883l_module_event().
Variable Documentation
mag_qmc5883l
struct Qmc5883l mag_qmc5883l
Definition at line 71 of file mag_qmc5883l.c.
Referenced by mag_qmc5883l_module_event(), mag_qmc5883l_module_init(), mag_qmc5883l_module_periodic(), and mag_qmc5883l_report().