Paparazzi UAS: sw/airborne/modules/sensors/mag_hmc5843.c File Reference
mag_hmc5843.c File Reference
#include "mcu_periph/i2c.h"
#include "mcu_periph/uart.h"
#include "pprzlink/messages.h"
#include "modules/datalink/downlink.h"
#include <math.h>
#include "modules/core/abi.h"
#include "../../peripherals/hmc5843.h"
Functions
void hmc5843_module_init (void)
void hmc5843_module_periodic (void)
void hmc5843_module_event (void)
Variables
int32_t mag_x
int32_t mag_y
int32_t mag_z
bool mag_valid
Function Documentation
hmc5843_module_event()
void hmc5843_module_event (void)
Definition at line 50 of file mag_hmc5843.c.
References hmc5843_idle_task().
hmc5843_module_init()
void hmc5843_module_init (void)
Definition at line 35 of file mag_hmc5843.c.
References hmc5843_init().
hmc5843_module_periodic()
void hmc5843_module_periodic (void)
Definition at line 40 of file mag_hmc5843.c.
References Hmc5843::data, DefaultChannel, DefaultDevice, foo, hmc5843, hmc5843_periodic(), MAG_HMC58XX_SENDER_ID, mag_x, mag_y, and mag_z.
Variable Documentation
mag_valid
bool mag_valid
Definition at line 30 of file mag_hmc5843.c.
mag_x
int32_t mag_x
Definition at line 29 of file mag_hmc5843.c.
Referenced by hmc5843_module_periodic().
mag_y
int32_t mag_y
Definition at line 29 of file mag_hmc5843.c.
Referenced by hmc5843_module_periodic().
mag_z
int32_t mag_z
Definition at line 29 of file mag_hmc5843.c.
Referenced by hmc5843_module_periodic().