Paparazzi UAS: sw/airborne/modules/sensors/mag_ist8310.c File Reference
mag_ist8310.c File Reference
Module wrapper for Isentek IST8310 magnetometers.
#include "modules/sensors/mag_ist8310.h"
#include "mcu_periph/uart.h"
#include "pprzlink/messages.h"
#include "subsystems/datalink/downlink.h"
#include "generated/airframe.h"
Macros
#define IST8310_CHAN_X 1
#define IST8310_CHAN_Y 0
#define IST8310_CHAN_Z 2
#define IST8310_CHAN_X_SIGN +
#define IST8310_CHAN_Y_SIGN +
#define IST8310_CHAN_Z_SIGN +
Functions
void mag_ist8310_module_init (void)
void mag_ist8310_module_periodic (void)
void mag_ist8310_module_event (void)
void mag_ist8310_report (void)
Variables
struct IST8310 mag_ist8310
Detailed Description
Module wrapper for Isentek IST8310 magnetometers.
Definition in file mag_ist8310.c.
Macro Definition Documentation
#define IST8310_CHAN_X 1
Definition at line 34 of file mag_ist8310.c.
Referenced by mag_ist8310_module_event(), and mag_ist8310_report().
#define IST8310_CHAN_X_SIGN +
Definition at line 43 of file mag_ist8310.c.
Referenced by mag_ist8310_module_event(), and mag_ist8310_report().
#define IST8310_CHAN_Y 0
Definition at line 37 of file mag_ist8310.c.
Referenced by mag_ist8310_module_event(), and mag_ist8310_report().
#define IST8310_CHAN_Y_SIGN +
Definition at line 46 of file mag_ist8310.c.
Referenced by mag_ist8310_module_event(), and mag_ist8310_report().
#define IST8310_CHAN_Z 2
Definition at line 40 of file mag_ist8310.c.
Referenced by mag_ist8310_module_event(), and mag_ist8310_report().
#define IST8310_CHAN_Z_SIGN +
Definition at line 49 of file mag_ist8310.c.
Referenced by mag_ist8310_module_event(), and mag_ist8310_report().
Function Documentation
void mag_ist8310_module_event (void)
Definition at line 85 of file mag_ist8310.c.
References IST8310::data, IST8310::data_available, get_sys_time_usec(), imu, imu_scale_mag(), int32_rmat_vmult(), IST8310_CHAN_X, IST8310_CHAN_X_SIGN, IST8310_CHAN_Y, IST8310_CHAN_Y_SIGN, IST8310_CHAN_Z, IST8310_CHAN_Z_SIGN, ist8310_event(), Imu::mag, mag_ist8310, mag_ist8310_report(), MAG_IST8310_SENDER_ID, Imu::mag_unscaled, and VECT3_COPY.
void mag_ist8310_module_init (void)
Definition at line 66 of file mag_ist8310.c.
References ANGLE_BFP_OF_REAL, int32_rmat_of_eulers, IST8310_ADDR, ist8310_init(), and mag_ist8310.
void mag_ist8310_module_periodic (void)
Definition at line 80 of file mag_ist8310.c.
References ist8310_periodic(), and mag_ist8310.
void mag_ist8310_report (void)
Definition at line 125 of file mag_ist8310.c.
References IST8310::data, DefaultChannel, DefaultDevice, IST8310_CHAN_X, IST8310_CHAN_X_SIGN, IST8310_CHAN_Y, IST8310_CHAN_Y_SIGN, IST8310_CHAN_Z, IST8310_CHAN_Z_SIGN, mag_ist8310, Int32Vect3::x, Int32Vect3::y, and Int32Vect3::z.
Referenced by mag_ist8310_module_event().
Variable Documentation
struct IST8310 mag_ist8310
Definition at line 64 of file mag_ist8310.c.
Referenced by mag_ist8310_module_event(), mag_ist8310_module_init(), mag_ist8310_module_periodic(), and mag_ist8310_report().