Paparazzi UAS: sw/airborne/main_chibios.c File Reference
main_chibios.c File Reference
Program main function for ChibiOS inplementation.
#include "mcu_periph/sys_time.h"
#include "mcu.h"
#include <ch.h>
#include "generated/modules.h"
Macros
#define THD_WORKING_AREA_MAIN 8192
Functions
static void thd_ap (void *arg)
THD_WORKING_AREA (wa_thd_ap, THD_WORKING_AREA_MAIN)
int main (void)
Main function.
void pprz_terminate_autopilot_threads (void)
Terminate all autopilot threads Wait until proper stop.
Variables
static thread_t * apThdPtr = NULL
Detailed Description
Program main function for ChibiOS inplementation.
Calls AP thread on single/dual MCU
Definition in file main_chibios.c.
Macro Definition Documentation
THD_WORKING_AREA_MAIN
#define THD_WORKING_AREA_MAIN 8192
Definition at line 60 of file main_chibios.c.
Function Documentation
main()
int main (void)
Main function.
Definition at line 85 of file main_chibios.c.
References apThdPtr, foo, init, main_recovery_init(), and thd_ap().
pprz_terminate_autopilot_threads()
void pprz_terminate_autopilot_threads (void)
Terminate all autopilot threads Wait until proper stop.
Definition at line 171 of file main_chibios.c.
References apThdPtr, and foo.
Referenced by thdUsbStorage().
thd_ap()
static void thd_ap (void * arg) static
Definition at line 122 of file main_chibios.c.
References CH_CFG_ST_FREQUENCY, and foo.
Referenced by main().
THD_WORKING_AREA()
THD_WORKING_AREA (wa_thd_ap , THD_WORKING_AREA_MAIN)
Variable Documentation
apThdPtr
thread_t* apThdPtr = NULL static
Definition at line 68 of file main_chibios.c.
Referenced by main(), and pprz_terminate_autopilot_threads().