Paparazzi UAS: sw/airborne/main_ap.h File Reference
main_ap.h File Reference
Autopilot main loop.
Functions
void main_ap_init (void)
void main_ap_periodic (void)
void main_ap_event (void)
Detailed Description
Autopilot main loop.
This process is reponsible for the collecting the different sensors data, calling the appropriate estimation algorithms and running the different control loops.
Definition in file main_ap.h.
Function Documentation
main_ap_event()
void main_ap_event (void) extern
Definition at line 146 of file main_ap.c.
References foo.
Referenced by nps_autopilot_run_step().
main_ap_init()
void main_ap_init (void) extern
Definition at line 79 of file main_ap.c.
References autopilot_failsafe_checks(), DATALINK_PERIOD, foo, modules_datalink_tid, modules_gnc_tid, modules_mcu_core_tid, modules_radio_control_tid, modules_sensors_tid, SENSORS_PERIOD, SYS_PERIOD, sys_time_register_timer(), and sys_time_register_timer_offset().
Referenced by nps_autopilot_init(), and nps_autopilot_init().
main_ap_periodic()
void main_ap_periodic (void) extern
Definition at line 119 of file main_ap.c.
References foo, modules_datalink_tid, modules_gnc_tid, modules_mcu_core_tid, modules_radio_control_tid, modules_sensors_tid, and sys_time_check_and_ack_timer().
Referenced by nps_autopilot_run_step().