Paparazzi UAS: sw/airborne/firmwares/tutorial/main_demo2.c File Reference
main_demo2.c File Reference
#include "std.h"
#include "mcu.h"
#include "mcu_periph/sys_time.h"
#include "led.h"
Functions
static void main_init (void)
static void main_periodic_task (void)
int main (void)
Function Documentation
main()
int main (void)
Definition at line 10 of file main_demo2.c.
References main_init(), main_periodic_task(), and sys_time_check_and_ack_timer().
main_init()
static void main_init (void) inline static
Definition at line 21 of file main_demo2.c.
References foo, mcu_init(), and sys_time_register_timer().
Referenced by main().
main_periodic_task()
static void main_periodic_task (void) inline static
Definition at line 27 of file main_demo2.c.
References LED_TOGGLE.
Referenced by main().