Paparazzi UAS: sw/airborne/firmwares/fixedwing/main_recovery.h File Reference
main_recovery.h File Reference
Recovery mode: run manual mode in case of hardfault Based on legacy FBW.
#include "std.h"
Macros
#define RECOVERY_MODE_MANUAL 0
recovery modes
#define RECOVERY_MODE_FAILSAFE 2
Functions
void main_recovery_init (void)
void main_recovery_periodic (void)
void main_recovery_event (void)
Variables
uint8_t recovery_mode
Detailed Description
Recovery mode: run manual mode in case of hardfault Based on legacy FBW.
Definition in file main_recovery.h.
Macro Definition Documentation
RECOVERY_MODE_FAILSAFE
#define RECOVERY_MODE_FAILSAFE 2
Definition at line 36 of file main_recovery.h.
RECOVERY_MODE_MANUAL
#define RECOVERY_MODE_MANUAL 0
recovery modes
Definition at line 35 of file main_recovery.h.
Function Documentation
main_recovery_event()
void main_recovery_event (void)
Definition at line 126 of file main_recovery.c.
References foo.
main_recovery_init()
void main_recovery_init (void)
Definition at line 89 of file main_recovery.c.
References AP_MODE_MANUAL, autopilot, commands_init(), DefaultPeriodic, electrical_init(), electrical_tid, foo, pprz_autopilot::mode, periodic_tid, rc_cb(), rc_ev, recovery_mode, RECOVERY_MODE_FAILSAFE, RECOVERY_RC_ID, register_periodic_telemetry(), send_fbw_status(), sys_time_register_timer(), and telemetry_tid.
Referenced by main().
main_recovery_periodic()
void main_recovery_periodic (void)
Definition at line 136 of file main_recovery.c.
References commands_failsafe, DefaultChannel, DefaultDevice, DefaultPeriodic, electrical_periodic(), electrical_tid, foo, periodic_tid, radio_control, RC_REALLY_LOST, recovery_mode, RECOVERY_MODE_FAILSAFE, RadioControl::status, sys_time_check_and_ack_timer(), and telemetry_tid.
Variable Documentation
recovery_mode
uint8_t recovery_mode extern
Definition at line 42 of file main_recovery.c.
Referenced by main_recovery_init(), main_recovery_periodic(), rc_cb(), and send_fbw_status().