Paparazzi UAS: sw/airborne/modules/optical_flow/mateksys_3901_l0x.h File Reference
mateksys_3901_l0x.h File Reference
Driver for the mateksys_3901_l0x sensor via MSP protocol output.
#include "std.h"
#include "stdbool.h"
Data Structures
struct Mateksys3901l0X
Macros
#define MSP2_IS_SENSOR_MESSAGE(x) ((x) >= 0x1F00 && (x) <= 0x1FFF)
#define MSP2_SENSOR_RANGEFINDER 0x1F01
#define MSP2_SENSOR_OPTIC_FLOW 0x1F02
Enumerations
enum Mateksys3901l0XParseStatus {
MATEKSYS_3901_L0X_INITIALIZE , MATEKSYS_3901_L0X_PARSE_HEAD , MATEKSYS_3901_L0X_PARSE_HEAD2 , MATEKSYS_3901_L0X_PARSE_DIRECTION ,
MATEKSYS_3901_L0X_PARSE_LENGTH , MATEKSYS_3901_L0X_PARSE_FUNCTION_ID_B1 , MATEKSYS_3901_L0X_PARSE_FUNCTION_ID_B2 , MATEKSYS_3901_L0X_PARSE_SIZE ,
MATEKSYS_3901_L0X_PARSE_POINTER , MATEKSYS_3901_L0X_PARSE_DISTANCEQUALITY , MATEKSYS_3901_L0X_PARSE_DISTANCE_B1 , MATEKSYS_3901_L0X_PARSE_DISTANCE_B2 ,
MATEKSYS_3901_L0X_PARSE_DISTANCE_B3 , MATEKSYS_3901_L0X_PARSE_DISTANCE_B4 , MATEKSYS_3901_L0X_PARSE_MOTIONQUALITY , MATEKSYS_3901_L0X_PARSE_MOTIONY_B1 ,
MATEKSYS_3901_L0X_PARSE_MOTIONY_B2 , MATEKSYS_3901_L0X_PARSE_MOTIONY_B3 , MATEKSYS_3901_L0X_PARSE_MOTIONY_B4 , MATEKSYS_3901_L0X_PARSE_MOTIONX_B1 ,
MATEKSYS_3901_L0X_PARSE_MOTIONX_B2 , MATEKSYS_3901_L0X_PARSE_MOTIONX_B3 , MATEKSYS_3901_L0X_PARSE_MOTIONX_B4 , MATEKSYS_3901_L0X_PARSE_CHECKSUM
}
Functions
void mateksys3901l0x_init (void)
Initialization function.
void mateksys3901l0x_event (void)
Receive bytes from the UART port and parse them.
void mateksys3901l0x_downlink (void)
void mateksys_3901_l0x_scale_X (float scalex)
Scale the Flow X.
void mateksys_3901_l0x_scale_Y (float scaley)
Scale the Flow Y.
Variables
struct Mateksys3901l0X mateksys3901l0x
Detailed Description
Driver for the mateksys_3901_l0x sensor via MSP protocol output.
Driver for the mateksys_3901_l0x sensor via MSPx protocol output.
Definition in file mateksys_3901_l0x.h.
Data Structure Documentation
Mateksys3901l0X
struct Mateksys3901l0X
Definition at line 72 of file mateksys_3901_l0x.h.
Data Fields
struct link_device * device
float distance_compensated
float distancemm
uint8_t distancemm_quality
int32_t distancemm_temp
uint8_t motion_quality
int32_t motionX
int32_t motionX_temp
int32_t motionY
int32_t motionY_temp
uint8_t parse_crc
enum Mateksys3901l0XParseStatus parse_status
float scaler_x
float scaler_y
uint8_t sensor_id
float time_usec
float velocityX
float velocityY
Macro Definition Documentation
MSP2_IS_SENSOR_MESSAGE
#define MSP2_IS_SENSOR_MESSAGE (x) ((x) >= 0x1F00 && (x) <= 0x1FFF)
Definition at line 40 of file mateksys_3901_l0x.h.
MSP2_SENSOR_OPTIC_FLOW
#define MSP2_SENSOR_OPTIC_FLOW 0x1F02
Definition at line 43 of file mateksys_3901_l0x.h.
MSP2_SENSOR_RANGEFINDER
#define MSP2_SENSOR_RANGEFINDER 0x1F01
Definition at line 42 of file mateksys_3901_l0x.h.
Enumeration Type Documentation
Mateksys3901l0XParseStatus
enum Mateksys3901l0XParseStatus
Enumerator
MATEKSYS_3901_L0X_INITIALIZE
MATEKSYS_3901_L0X_PARSE_HEAD
MATEKSYS_3901_L0X_PARSE_HEAD2
MATEKSYS_3901_L0X_PARSE_DIRECTION
MATEKSYS_3901_L0X_PARSE_LENGTH
MATEKSYS_3901_L0X_PARSE_FUNCTION_ID_B1
MATEKSYS_3901_L0X_PARSE_FUNCTION_ID_B2
MATEKSYS_3901_L0X_PARSE_SIZE
MATEKSYS_3901_L0X_PARSE_POINTER
MATEKSYS_3901_L0X_PARSE_DISTANCEQUALITY
MATEKSYS_3901_L0X_PARSE_DISTANCE_B1
MATEKSYS_3901_L0X_PARSE_DISTANCE_B2
MATEKSYS_3901_L0X_PARSE_DISTANCE_B3
MATEKSYS_3901_L0X_PARSE_DISTANCE_B4
MATEKSYS_3901_L0X_PARSE_MOTIONQUALITY
MATEKSYS_3901_L0X_PARSE_MOTIONY_B1
MATEKSYS_3901_L0X_PARSE_MOTIONY_B2
MATEKSYS_3901_L0X_PARSE_MOTIONY_B3
MATEKSYS_3901_L0X_PARSE_MOTIONY_B4
MATEKSYS_3901_L0X_PARSE_MOTIONX_B1
MATEKSYS_3901_L0X_PARSE_MOTIONX_B2
MATEKSYS_3901_L0X_PARSE_MOTIONX_B3
MATEKSYS_3901_L0X_PARSE_MOTIONX_B4
MATEKSYS_3901_L0X_PARSE_CHECKSUM
Definition at line 45 of file mateksys_3901_l0x.h.
Function Documentation
mateksys3901l0x_downlink()
void mateksys3901l0x_downlink (void) extern
mateksys3901l0x_event()
void mateksys3901l0x_event (void) extern
Receive bytes from the UART port and parse them.
Definition at line 151 of file mateksys_3901_l0x.c.
References Mateksys3901l0X::device, mateksys3901l0x, mateksys3901l0x_parse(), MATEKSYS_3901_L0X_INITIALIZE, and Mateksys3901l0X::parse_status.
mateksys3901l0x_init()
void mateksys3901l0x_init (void) extern
Initialization function.
Definition at line 110 of file mateksys_3901_l0x.c.
References DefaultPeriodic, Mateksys3901l0X::device, Mateksys3901l0X::distance_compensated, Mateksys3901l0X::distancemm, Mateksys3901l0X::distancemm_quality, Mateksys3901l0X::distancemm_temp, foo, mateksys3901l0x, mateksys3901l0x_send_optical_flow(), MATEKSYS_3901_L0X_FLOW_X_SCALER, MATEKSYS_3901_L0X_FLOW_Y_SCALER, MATEKSYS_3901_L0X_PARSE_HEAD, Mateksys3901l0X::motion_quality, Mateksys3901l0X::motionX, Mateksys3901l0X::motionX_temp, Mateksys3901l0X::motionY, Mateksys3901l0X::motionY_temp, Mateksys3901l0X::parse_crc, Mateksys3901l0X::parse_status, register_periodic_telemetry(), Mateksys3901l0X::scaler_x, and Mateksys3901l0X::scaler_y.
mateksys_3901_l0x_scale_X()
void mateksys_3901_l0x_scale_X (float scalex) extern
Scale the Flow X.
Definition at line 135 of file mateksys_3901_l0x.c.
References foo, mateksys3901l0x, and Mateksys3901l0X::scaler_x.
mateksys_3901_l0x_scale_Y()
void mateksys_3901_l0x_scale_Y (float scaley) extern
Scale the Flow Y.
Definition at line 143 of file mateksys_3901_l0x.c.
References foo, mateksys3901l0x, and Mateksys3901l0X::scaler_y.
Variable Documentation
mateksys3901l0x
struct Mateksys3901l0X mateksys3901l0x extern
Definition at line 78 of file mateksys_3901_l0x.c.
Referenced by mateksys3901l0x_event(), mateksys3901l0x_init(), mateksys3901l0x_parse(), mateksys3901l0x_send_optical_flow(), mateksys_3901_l0x_scale_X(), and mateksys_3901_l0x_scale_Y().