Paparazzi UAS: sw/airborne/modules/mav_course_exercise/mav_exercise.h File Reference
mav_exercise.h File Reference
Functions
void mav_exercise_init (void)
void mav_exercise_periodic (void)
Function Documentation
mav_exercise_init()
void mav_exercise_init (void) extern
Definition at line 67 of file mav_exercise.c.
References color_detection_cb(), color_detection_ev, foo, and ORANGE_AVOIDER_VISUAL_DETECTION_ID.
mav_exercise_periodic()
void mav_exercise_periodic (void) extern
Definition at line 72 of file mav_exercise.c.
References autopilot_in_flight(), color_count, foo, front_camera, HOLD, increase_nav_heading(), max_trajectory_confidence, moveDistance, moveWaypointForward(), oa_color_count_frac, OBSTACLE_FOUND, obstacle_free_confidence, oob_haeding_increment, OUT_OF_BOUNDS, PRINT, SAFE, waypoint_move_here_2d(), WaypointX, and WaypointY.