Paparazzi UAS: sw/airborne/modules/datalink/mavlink.c File Reference
mavlink.c File Reference
Basic MAVLink datalink implementation.
#include "modules/datalink/mavlink.h"
#include "mavlink/ardupilotmega/mavlink.h"
#include "modules/datalink/telemetry_common.h"
#include "generated/periodic_telemetry.h"
#include "generated/airframe.h"
#include "generated/modules.h"
#include "generated/settings.h"
#include "generated/flight_plan.h"
#include "mcu_periph/sys_time.h"
#include "modules/energy/electrical.h"
#include "state.h"
#include "pprz_version.h"
#include "autopilot.h"
#include "autopilot_guided.h"
#include "modules/radio_control/radio_control.h"
#include "modules/datalink/missionlib/mission_manager.h"
#include <stdint.h>
#include "modules/gps/gps.h"
#include "modules/core/commands.h"
Macros
#define PERIODIC_C_MAVLINK
#define MAV_AUTOPILOT_ID MAV_AUTOPILOT_PPZ
#define MAVLINK_SYSID AC_ID
MAVLink initialization.
#define UAV_SENSORS (MAV_SYS_STATUS_SENSOR_3D_GYRO|MAV_SYS_STATUS_SENSOR_3D_ACCEL|MAV_SYS_STATUS_SENSOR_3D_MAG|MAV_SYS_STATUS_SENSOR_ABSOLUTE_PRESSURE)
#define RC_CHANNELS RADIO_CONTROL_NB_CHANNEL
#define PPM_OF_PPRZ(_v) ((_v) / 19.2 + 1500)
#define PPM_PULSES(_i) ((_i) < RADIO_CONTROL_NB_CHANNEL ? PPM_OF_PPRZ(radio_control.values[(_i)]) + MAX_PPRZ : UINT16_MAX)
Functions
void mavlink_common_message_handler (const mavlink_message_t *msg)
static void mavlink_send_extended_sys_state (struct transport_tx *trans, struct link_device *dev)
static void mavlink_send_heartbeat (struct transport_tx *trans, struct link_device *dev)
Send a heartbeat.
static void mavlink_send_sys_status (struct transport_tx *trans, struct link_device *dev)
Send the system status.
static void mavlink_send_system_time (struct transport_tx *trans, struct link_device *dev)
Send SYSTEM_TIME.
static void mavlink_send_attitude (struct transport_tx *trans, struct link_device *dev)
Send the attitude.
static void mavlink_send_local_position_ned (struct transport_tx *trans, struct link_device *dev)
static void mavlink_send_global_position_int (struct transport_tx *trans, struct link_device *dev)
static void mavlink_send_params (struct transport_tx *trans, struct link_device *dev)
Send the parameters.
static void mavlink_send_autopilot_version (struct transport_tx *trans, struct link_device *dev)
static void mavlink_send_attitude_quaternion (struct transport_tx *trans, struct link_device *dev)
static void mavlink_send_gps_raw_int (struct transport_tx *trans, struct link_device *dev)
static void mavlink_send_rc_channels (struct transport_tx *trans, struct link_device *dev)
static void mavlink_send_battery_status (struct transport_tx *trans, struct link_device *dev)
static void mavlink_send_gps_global_origin (struct transport_tx *trans, struct link_device *dev)
static void mavlink_send_gps_status (struct transport_tx *trans, struct link_device *dev)
Send gps status.
static void mavlink_send_vfr_hud (struct transport_tx *trans, struct link_device *dev)
Send Metrics typically displayed on a HUD for fixed wing aircraft.
void mavlink_init (void)
Module functions.
void mavlink_periodic_telemetry (void)
Send periodic mavlink messages as defined in Mavlink process of telemetry xml file.
void mavlink_periodic (void)
Periodic MAVLink calls.
static int16_t settings_idx_from_param_id (char *param_id)
void mavlink_event (void)
Event MAVLink calls.
Variables
mavlink_system_t mavlink_system
static uint8_t mavlink_params_idx = NB_SETTING
Transmitting parameters index.
static char mavlink_param_names [NB_SETTING][16+1] = SETTINGS_NAMES_SHORT
mavlink parameter names.
static uint8_t custom_version [8]
first 8 bytes (16 chars) of GIT SHA1
mavlink_mission_mgr mission_mgr
Detailed Description
Basic MAVLink datalink implementation.
Definition in file mavlink.c.
Macro Definition Documentation
MAV_AUTOPILOT_ID
#define MAV_AUTOPILOT_ID MAV_AUTOPILOT_PPZ
Definition at line 64 of file mavlink.c.
MAVLINK_SYSID
#define MAVLINK_SYSID AC_ID
MAVLink initialization.
Definition at line 108 of file mavlink.c.
PERIODIC_C_MAVLINK
#define PERIODIC_C_MAVLINK
Definition at line 38 of file mavlink.c.
PPM_OF_PPRZ
#define PPM_OF_PPRZ (_v) ((_v) / 19.2 + 1500)
Definition at line 837 of file mavlink.c.
PPM_PULSES
#define PPM_PULSES (_i) ((_i) < RADIO_CONTROL_NB_CHANNEL ? PPM_OF_PPRZ(radio_control.values[(_i)]) + MAX_PPRZ : UINT16_MAX)
Definition at line 838 of file mavlink.c.
RC_CHANNELS
#define RC_CHANNELS RADIO_CONTROL_NB_CHANNEL
Definition at line 836 of file mavlink.c.
UAV_SENSORS
#define UAV_SENSORS (MAV_SYS_STATUS_SENSOR_3D_GYRO|MAV_SYS_STATUS_SENSOR_3D_ACCEL|MAV_SYS_STATUS_SENSOR_3D_MAG|MAV_SYS_STATUS_SENSOR_ABSOLUTE_PRESSURE)
Function Documentation
mavlink_common_message_handler()
void mavlink_common_message_handler (const mavlink_message_t * msg)
Definition at line 232 of file mavlink.c.
References LlaCoor_i::alt, AP_MODE_GUIDED, AP_MODE_NAV, autopilot_get_mode(), autopilot_get_motors_on(), autopilot_guided_goto_body_relative(), autopilot_guided_goto_ned(), autopilot_guided_goto_ned_relative(), autopilot_guided_move_ned(), autopilot_set_mode(), autopilot_set_motors_on(), DefaultChannel, DefaultDevice, FALSE, foo, LtpDef_i::hmsl, idx, LlaCoor_i::lat, LtpDef_i::lla, LlaCoor_i::lon, MAVLINK_DEBUG, mavlink_param_names, mavlink_params_idx, MAVLinkSendMessage, MM_OF_M, mode, msg, ned_of_lla_point_i(), origin, parse_rc_up_datalink(), settings_idx_from_param_id(), stateGetHmslOrigin_i(), stateGetNedOrigin_i(), target, TRUE, waypoint_set_alt(), and waypoint_set_latlon().
Referenced by mavlink_event().
mavlink_event()
void mavlink_event (void)
Event MAVLink calls.
Definition at line 215 of file mavlink.c.
References foo, mavlink_common_message_handler(), mavlink_mission_message_handler(), MAVLinkChAvailable, MAVLinkGetch, msg, and status.
mavlink_init()
void mavlink_init (void)
Module functions.
Definition at line 116 of file mavlink.c.
References custom_version, foo, mavlink_mission_init(), mavlink_send_attitude(), mavlink_send_attitude_quaternion(), mavlink_send_autopilot_version(), mavlink_send_battery_status(), mavlink_send_extended_sys_state(), mavlink_send_global_position_int(), mavlink_send_gps_global_origin(), mavlink_send_gps_raw_int(), mavlink_send_gps_status(), mavlink_send_heartbeat(), mavlink_send_local_position_ned(), mavlink_send_rc_channels(), mavlink_send_sys_status(), mavlink_send_system_time(), mavlink_send_vfr_hud(), MAVLINK_SYSID, mavlink_system, mission_mgr, and register_periodic_telemetry().
mavlink_periodic()
void mavlink_periodic (void)
Periodic MAVLink calls.
Called at MAVLINK_PERIODIC_FREQ (set in module xml to 10Hz)
Definition at line 161 of file mavlink.c.
References foo, mavlink_mission_periodic(), mavlink_send_attitude(), mavlink_send_attitude_quaternion(), mavlink_send_autopilot_version(), mavlink_send_battery_status(), mavlink_send_global_position_int(), mavlink_send_gps_global_origin(), mavlink_send_gps_raw_int(), mavlink_send_gps_status(), mavlink_send_heartbeat(), mavlink_send_local_position_ned(), mavlink_send_params(), mavlink_send_rc_channels(), mavlink_send_sys_status(), mavlink_send_system_time(), and mavlink_send_vfr_hud().
mavlink_periodic_telemetry()
void mavlink_periodic_telemetry (void)
Send periodic mavlink messages as defined in Mavlink process of telemetry xml file.
Called at TELEMETRY_FREQUENCY
Definition at line 148 of file mavlink.c.
References foo.
mavlink_send_attitude()
static void mavlink_send_attitude (struct transport_tx * trans, struct link_device * dev) static
Send the attitude.
Definition at line 630 of file mavlink.c.
References foo, get_sys_time_msec(), MAVLinkSendMessage, p, stateGetBodyRates_f(), and stateGetNedToBodyEulers_f().
mavlink_send_attitude_quaternion()
static void mavlink_send_attitude_quaternion (struct transport_tx * trans, struct link_device * dev) static
Definition at line 738 of file mavlink.c.
References foo, get_sys_time_msec(), MAVLinkSendMessage, p, stateGetBodyRates_f(), and stateGetNedToBodyQuat_f().
Referenced by mavlink_init(), and mavlink_periodic().
mavlink_send_autopilot_version()
static void mavlink_send_autopilot_version (struct transport_tx * trans, struct link_device * dev) static
TODO: fill in versions correctly, how should they be encoded?
Definition at line 716 of file mavlink.c.
References foo, and MAVLinkSendMessage.
Referenced by mavlink_init(), and mavlink_periodic().
mavlink_send_battery_status()
static void mavlink_send_battery_status (struct transport_tx * trans, struct link_device * dev) static
TODO: check what all these fields are supposed to represent
Definition at line 869 of file mavlink.c.
References Electrical::charge, Electrical::current, electrical, Electrical::energy, foo, MAVLinkSendMessage, and Electrical::vsupply.
Referenced by mavlink_init(), and mavlink_periodic().
mavlink_send_extended_sys_state()
static void mavlink_send_extended_sys_state (struct transport_tx * trans, struct link_device * dev) static
Definition at line 582 of file mavlink.c.
References autopilot_in_flight(), foo, and MAVLinkSendMessage.
Referenced by mavlink_init().
mavlink_send_global_position_int()
static void mavlink_send_global_position_int (struct transport_tx * trans, struct link_device * dev) static
TODO: check/ask what coordinate system vel is supposed to be in, not clear from docs
Definition at line 656 of file mavlink.c.
References LlaCoor_i::alt, foo, get_sys_time_msec(), heading, MAVLinkSendMessage, stateGetHmslOrigin_i(), stateGetLlaOrigin_i(), stateGetNedOrigin_i(), stateGetNedToBodyEulers_f(), stateGetPositionLla_i(), and stateGetSpeedNed_f().
Referenced by mavlink_init(), and mavlink_periodic().
mavlink_send_gps_global_origin()
static void mavlink_send_gps_global_origin (struct transport_tx * trans, struct link_device * dev) static
Definition at line 684 of file mavlink.c.
References foo, get_sys_time_usec(), MAVLinkSendMessage, State::ned_initialized_i, state, stateGetHmslOrigin_i(), and stateGetLlaOrigin_i().
Referenced by mavlink_init(), and mavlink_periodic().
mavlink_send_gps_raw_int()
static void mavlink_send_gps_raw_int (struct transport_tx * trans, struct link_device * dev) static
Definition at line 758 of file mavlink.c.
References LlaCoor_i::alt, GpsState::course, course, GpsState::fix, foo, get_sys_time_usec(), gps, GpsState::gspeed, GpsState::hacc, GpsState::hmsl, LlaCoor_i::lat, GpsState::lla_pos, LlaCoor_i::lon, MAVLinkSendMessage, GpsState::num_sv, GpsState::pdop, GpsState::sacc, and GpsState::vacc.
Referenced by mavlink_init(), and mavlink_periodic().
mavlink_send_gps_status()
static void mavlink_send_gps_status (struct transport_tx * trans, struct link_device * dev) static
Send gps status.
The GPS status message consists of:
satellites visible
satellite pnr[] (ignored)
satellite used[] (ignored)
satellite elevation[] (ignored)
satellite azimuth[] (ignored)
satellite snr[] (ignored)
Definition at line 796 of file mavlink.c.
References SVinfo::azim, SVinfo::cno, SVinfo::elev, foo, gps, GPS_NB_CHANNELS, MAVLinkSendMessage, Min, GpsState::num_sv, SVinfo::svid, and GpsState::svinfos.
Referenced by mavlink_init(), and mavlink_periodic().
mavlink_send_heartbeat()
static void mavlink_send_heartbeat (struct transport_tx * trans, struct link_device * dev) static
Send a heartbeat.
Definition at line 504 of file mavlink.c.
References AP_MODE_ATTITUDE_CLIMB, AP_MODE_ATTITUDE_DIRECT, AP_MODE_ATTITUDE_RC_CLIMB, AP_MODE_ATTITUDE_Z_HOLD, AP_MODE_AUTO1, AP_MODE_AUTO2, AP_MODE_CARE_FREE_DIRECT, AP_MODE_GUIDED, AP_MODE_HOME, AP_MODE_HOVER_CLIMB, AP_MODE_HOVER_DIRECT, AP_MODE_HOVER_Z_HOLD, AP_MODE_MANUAL, AP_MODE_NAV, AP_MODE_RATE_DIRECT, AP_MODE_RATE_RC_CLIMB, AP_MODE_RATE_Z_HOLD, AP_MODE_RC_DIRECT, autopilot_get_mode(), autopilot_throttle_killed(), foo, MAV_AUTOPILOT_ID, MAVLinkSendMessage, and stateIsAttitudeValid().
mavlink_send_local_position_ned()
static void mavlink_send_local_position_ned (struct transport_tx * trans, struct link_device * dev) static
Definition at line 643 of file mavlink.c.
References foo, get_sys_time_msec(), MAVLinkSendMessage, stateGetPositionNed_f(), and stateGetSpeedNed_f().
Referenced by mavlink_init(), and mavlink_periodic().
mavlink_send_params()
static void mavlink_send_params (struct transport_tx * trans, struct link_device * dev) static
Send the parameters.
Definition at line 699 of file mavlink.c.
References foo, mavlink_param_names, mavlink_params_idx, and MAVLinkSendMessage.
Referenced by mavlink_periodic().
mavlink_send_rc_channels()
static void mavlink_send_rc_channels (struct transport_tx * trans, struct link_device * dev) static
Definition at line 842 of file mavlink.c.
References foo, get_sys_time_msec(), MAVLinkSendMessage, PPM_PULSES, and RC_CHANNELS.
Referenced by mavlink_init(), and mavlink_periodic().
mavlink_send_sys_status()
static void mavlink_send_sys_status (struct transport_tx * trans, struct link_device * dev) static
Send the system status.
TODO: FIXME
Definition at line 591 of file mavlink.c.
References Electrical::current, electrical, foo, MAVLinkSendMessage, UAV_SENSORS, and Electrical::vsupply.
Referenced by mavlink_init(), and mavlink_periodic().
mavlink_send_system_time()
static void mavlink_send_system_time (struct transport_tx * trans, struct link_device * dev) static
Send SYSTEM_TIME.
time_unix_usec
time_boot_ms
Definition at line 621 of file mavlink.c.
References foo, get_sys_time_msec(), and MAVLinkSendMessage.
Referenced by mavlink_init(), and mavlink_periodic().
mavlink_send_vfr_hud()
static void mavlink_send_vfr_hud (struct transport_tx * trans, struct link_device * dev) static
Send Metrics typically displayed on a HUD for fixed wing aircraft.
Definition at line 897 of file mavlink.c.
References LlaCoor_f::alt, commands, foo, heading, MAVLinkSendMessage, MAX_PPRZ, stateGetAirspeed_f(), stateGetHmslOrigin_f(), stateGetHorizontalSpeedNorm_f(), stateGetLlaOrigin_f(), stateGetNedToBodyEulers_f(), stateGetPositionLla_f(), and stateGetSpeedNed_f().
Referenced by mavlink_init(), and mavlink_periodic().
settings_idx_from_param_id()
static int16_t settings_idx_from_param_id (char * param_id) static
Definition at line 187 of file mavlink.c.
References foo, and mavlink_param_names.
Referenced by mavlink_common_message_handler().
Variable Documentation
custom_version
uint8_t custom_version[8] static
first 8 bytes (16 chars) of GIT SHA1
Definition at line 79 of file mavlink.c.
Referenced by mavlink_init().
mavlink_param_names
char mavlink_param_names[NB_SETTING][16+1] = SETTINGS_NAMES_SHORT static
mavlink parameter names.
16 chars + 1 NULL termination.
Definition at line 78 of file mavlink.c.
Referenced by mavlink_common_message_handler(), mavlink_send_params(), and settings_idx_from_param_id().
mavlink_params_idx
uint8_t mavlink_params_idx = NB_SETTING static
Transmitting parameters index.
Definition at line 74 of file mavlink.c.
Referenced by mavlink_common_message_handler(), and mavlink_send_params().
mavlink_system
mavlink_system_t mavlink_system
Definition at line 72 of file mavlink.c.
Referenced by mavlink_block_message_handler(), mavlink_init(), and mavlink_wp_message_handler().
mission_mgr
mavlink_mission_mgr mission_mgr
Definition at line 81 of file mavlink.c.
Referenced by mavlink_block_message_handler(), mavlink_init(), mavlink_mission_cancel_timer(), mavlink_mission_message_handler(), mavlink_mission_periodic(), mavlink_mission_set_timer(), mavlink_send_block(), mavlink_send_block_count(), mavlink_send_mission_ack(), and mavlink_wp_message_handler().