Paparazzi UAS: sw/airborne/modules/datalink/mavlink.h File Reference
mavlink.h File Reference
Basic MAVLink datalink implementation.
#include <mavlink/mavlink_types.h>
#include "mcu_periph/uart.h"
#include <stdio.h>
Macros
#define MAVLINK_USE_CONVENIENCE_FUNCTIONS
#define MAVLINK_ALIGNED_FIELDS 0
#define MAVLINK_DEBUG(...) {}
#define MAVLINK_DEV uart1
#define MAVLinkDev (&(MAVLINK_DEV).device)
#define MAVLinkTransmit(c) MAVLinkDev->put_byte(MAVLinkDev->periph, 0, c)
#define MAVLinkChAvailable() MAVLinkDev->char_available(MAVLinkDev->periph)
#define MAVLinkGetch() MAVLinkDev->get_byte(MAVLinkDev->periph)
#define MAVLinkSendMessage() MAVLinkDev->send_message(MAVLinkDev->periph, 0)
Functions
void mavlink_init (void)
Module functions.
void mavlink_periodic (void)
Periodic MAVLink calls.
void mavlink_periodic_telemetry (void)
Send periodic mavlink messages as defined in Mavlink process of telemetry xml file.
void mavlink_event (void)
Event MAVLink calls.
static void comm_send_ch (mavlink_channel_t chan, uint8_t ch)
Send one char (uint8_t) over a comm channel.
Variables
mavlink_system_t mavlink_system
Detailed Description
Basic MAVLink datalink implementation.
Definition in file mavlink.h.
Macro Definition Documentation
#define MAVLINK_ALIGNED_FIELDS 0
Definition at line 31 of file mavlink.h.
#define MAVLINK_DEBUG (...) {}
Definition at line 44 of file mavlink.h.
Referenced by mavlink_block_message_handler(), mavlink_common_message_handler(), mavlink_mission_message_handler(), mavlink_mission_periodic(), mavlink_send_block(), mavlink_send_block_count(), mavlink_send_mission_ack(), mavlink_send_wp(), and mavlink_wp_message_handler().
#define MAVLINK_DEV uart1
Definition at line 57 of file mavlink.h.
#define MAVLINK_USE_CONVENIENCE_FUNCTIONS
Definition at line 30 of file mavlink.h.
#define MAVLinkChAvailable () MAVLinkDev->char_available(MAVLinkDev->periph)
Definition at line 65 of file mavlink.h.
Referenced by jevois_mavlink_event(), and mavlink_event().
#define MAVLinkDev (&(MAVLINK_DEV).device)
Definition at line 63 of file mavlink.h.
#define MAVLinkGetch () MAVLinkDev->get_byte(MAVLinkDev->periph)
Definition at line 66 of file mavlink.h.
Referenced by jevois_mavlink_event(), and mavlink_event().
#define MAVLinkSendMessage () MAVLinkDev->send_message(MAVLinkDev->periph, 0)
Definition at line 67 of file mavlink.h.
Referenced by mavlink_common_message_handler(), mavlink_mission_periodic(), mavlink_send_attitude(), mavlink_send_attitude_quaternion(), mavlink_send_autopilot_version(), mavlink_send_battery_status(), mavlink_send_block(), mavlink_send_block_count(), mavlink_send_global_position_int(), mavlink_send_gps_global_origin(), mavlink_send_gps_raw_int(), mavlink_send_gps_status(), mavlink_send_heartbeat(), mavlink_send_highres_imu(), mavlink_send_local_position_ned(), mavlink_send_mission_ack(), mavlink_send_params(), mavlink_send_rc_channels(), mavlink_send_set_mode(), mavlink_send_sys_status(), mavlink_send_system_time(), mavlink_send_vfr_hud(), mavlink_send_wp(), and mavlink_wp_message_handler().
#define MAVLinkTransmit (c) MAVLinkDev->put_byte(MAVLinkDev->periph, 0, c)
Definition at line 64 of file mavlink.h.
Referenced by comm_send_ch().
Function Documentation
static void comm_send_ch (mavlink_channel_t chan, uint8_t ch) inline static
Send one char (uint8_t) over a comm channel.
Parameters
chan MAVLink channel to use, usually MAVLINK_COMM_0 = UART0
ch Character to send
Definition at line 83 of file mavlink.h.
References MAVLinkTransmit.
void mavlink_event (void)
Event MAVLink calls.
Definition at line 205 of file mavlink.c.
References mavlink_common_message_handler(), mavlink_mission_message_handler(), MAVLinkChAvailable, MAVLinkGetch, msg, and status.
void mavlink_init (void)
Module functions.
Definition at line 107 of file mavlink.c.
References custom_version, mavlink_mission_init(), mavlink_send_attitude(), mavlink_send_attitude_quaternion(), mavlink_send_autopilot_version(), mavlink_send_battery_status(), mavlink_send_global_position_int(), mavlink_send_gps_global_origin(), mavlink_send_gps_raw_int(), mavlink_send_gps_status(), mavlink_send_heartbeat(), mavlink_send_local_position_ned(), mavlink_send_rc_channels(), mavlink_send_sys_status(), mavlink_send_system_time(), mavlink_send_vfr_hud(), MAVLINK_SYSID, mavlink_system, and register_periodic_telemetry().
void mavlink_periodic (void)
Periodic MAVLink calls.
Called at MAVLINK_PERIODIC_FREQ (set in module xml to 10Hz)
Definition at line 151 of file mavlink.c.
References mavlink_mission_periodic(), mavlink_send_attitude(), mavlink_send_attitude_quaternion(), mavlink_send_autopilot_version(), mavlink_send_battery_status(), mavlink_send_global_position_int(), mavlink_send_gps_global_origin(), mavlink_send_gps_raw_int(), mavlink_send_gps_status(), mavlink_send_heartbeat(), mavlink_send_local_position_ned(), mavlink_send_params(), mavlink_send_rc_channels(), mavlink_send_sys_status(), mavlink_send_system_time(), and mavlink_send_vfr_hud().
void mavlink_periodic_telemetry (void)
Send periodic mavlink messages as defined in Mavlink process of telemetry xml file.
Called at TELEMETRY_FREQUENCY
Definition at line 138 of file mavlink.c.
Variable Documentation
mavlink_system_t mavlink_system
Definition at line 64 of file mavlink.c.