Paparazzi UAS: sw/airborne/modules/display/max7456.h File Reference
max7456.h File Reference
Maxim MAX7456 single-channel monochrome on-screen display driver.
#include "std.h"
Functions
void max7456_init (void)
void max7456_periodic (void)
void max7456_event (void)
Variables
uint8_t osd_enable
float mag_course_deg
float mag_heading_rad
float home_dir_deg
Detailed Description
Maxim MAX7456 single-channel monochrome on-screen display driver.
Definition in file max7456.h.
Function Documentation
max7456_event()
void max7456_event (void) extern
Definition at line 996 of file max7456.c.
References foo, spi_transaction::input_buf, spi_transaction::input_length, max7456_osd_status, max7456_trans, osd_attr, OSD_AUTO_INCREMENT_MODE, osd_char_address, OSD_DMAL_REG, OSD_DMM_REG, osd_enable_val, OSD_FINISHED, OSD_IDLE, OSD_INIT1, OSD_INIT2, OSD_INIT3, OSD_INIT4, OSD_NVRAM_BUSY_FLAG, OSD_OSDBL_REG, OSD_READ_STATUS, OSD_RESET_BUSY_FLAG, OSD_S_STEP1, OSD_S_STEP2, OSD_S_STEP3, osd_stat_reg, OSD_STAT_REG, osd_string, OSD_VIDEO_MODE_PAL, OSD_VM0_REG, spi_transaction::output_buf, spi_transaction::output_length, spi_submit(), SPITransDone, SPITransSuccess, spi_transaction::status, and EnuCoor_f::x.
max7456_init()
void max7456_init (void) extern
Definition at line 926 of file max7456.c.
References spi_transaction::after_cb, spi_transaction::before_cb, spi_transaction::bitorder, spi_transaction::cdiv, spi_transaction::cpha, spi_transaction::cpol, DefaultPeriodic, spi_transaction::dss, foo, home_direction(), spi_transaction::input_buf, spi_transaction::input_length, max7456_osd_status, max7456_trans, osd_enable, osd_enable_val, OSD_IMAGE_ENABLE, osd_spi_rx_buffer, osd_spi_tx_buffer, OSD_UNINIT, spi_transaction::output_buf, spi_transaction::output_length, register_periodic_telemetry(), spi_transaction::select, send_mag_heading(), spi_transaction::slave_idx, SPICphaEdge1, SPICpolIdleLow, SPIDiv64, SPIDss8bit, SPIMSBFirst, and SPISelectUnselect.
max7456_periodic()
void max7456_periodic (void) extern
Definition at line 955 of file max7456.c.
References draw_osd(), foo, spi_transaction::input_length, max7456_osd_status, max7456_trans, osd_enable, osd_enable_val, OSD_IDLE, OSD_INIT1, OSD_INIT2, OSD_INIT3, OSD_OSDBL_REG_R, OSD_RESET, OSD_UNINIT, OSD_VM0_REG, spi_transaction::output_buf, spi_transaction::output_length, spi_submit(), SPITransDone, spi_transaction::status, and step.
Variable Documentation
home_dir_deg
float home_dir_deg extern
Definition at line 177 of file max7456.c.
Referenced by home_direction(), and send_mag_heading().
mag_course_deg
float mag_course_deg extern
Definition at line 174 of file max7456.c.
Referenced by draw_osd(), and send_mag_heading().
mag_heading_rad
float mag_heading_rad extern
Definition at line 175 of file max7456.c.
osd_enable
uint8_t osd_enable extern
Definition at line 169 of file max7456.c.
Referenced by max7456_init(), and max7456_periodic().