Paparazzi UAS: sw/airborne/modules/meteo/meteo_stick.h File Reference
meteo_stick.h File Reference
Data acquisition module for ENAC PTU board.
#include "std.h"
#include "peripherals/ads1220.h"
Data Structures
struct MeteoStick
Raw sensors structure.
Macros
#define USE_MS_EEPROM TRUE
Functions
void meteo_stick_init (void)
Functions.
void meteo_stick_periodic (void)
Periodic function.
void meteo_stick_event (void)
Event function.
void meteo_stick_report (void)
Variables
struct MeteoStick meteo_stick
General structure.
Detailed Description
Data acquisition module for ENAC PTU board.
provides meteo data:
temperature
humidity
absolute pressure
differential pressure
based on the ADS1220 spi ADC for pressures and temperature, and PWM input for humidity
data can be send other telemetry and/or logged on SD card (on capable autopilots)
designed and debugged by Michel Gorraz and Alexandre Bustico @ Enac (2014)
Definition in file meteo_stick.h.
Data Structure Documentation
MeteoStick
struct MeteoStick
Raw sensors structure.
Definition at line 59 of file meteo_stick.h.
Data Fields
float current_airspeed calibrated airspeed
float current_humidity calibrated humidity
float current_pressure calibrated pressure
float current_temperature calibrated temperature
struct Ads1220 diff_pressure differential pressure
uint32_t humidity_period humidity (in ticks)
struct Ads1220 pressure absolute pressure
bool reset_dp_offset reset differential pressure offset
struct Ads1220 temperature temperature
Macro Definition Documentation
USE_MS_EEPROM
#define USE_MS_EEPROM TRUE
Definition at line 50 of file meteo_stick.h.
Function Documentation
meteo_stick_event()
void meteo_stick_event (void) extern
Event function.
Definition at line 434 of file meteo_stick.c.
References ads1220_event(), MeteoStick::current_airspeed, MeteoStick::current_pressure, MeteoStick::current_temperature, Ads1220::data, Ads1220::data_available, MeteoStick::diff_pressure, eeprom25AA256_event(), foo, get_diff(), get_pitot(), get_pressure(), get_sys_time_usec(), get_temp(), meteo_stick, METEO_STICK_SENDER_ID, MS_PITOT_COUNTER, MS_PITOT_FILTER, pitot_counter, pitot_offset, MeteoStick::pressure, and MeteoStick::temperature.
meteo_stick_init()
void meteo_stick_init (void) extern
Functions.
Functions.
Definition at line 300 of file meteo_stick.c.
References ADS1220_CONTINIOUS_CONVERSION, ADS1220_GAIN_1, ADS1220_GAIN_2, ADS1220_GAIN_4, ADS1220_IDAC_250_uA, ADS1220_IDAC_OFF, ADS1220_IMUX_A0_RP1, ADS1220_IMUX_OFF, ads1220_init(), ADS1220_MUX_AIN0_AIN1, ADS1220_MUX_AIN0_AVSS, ADS1220_RATE_45_HZ, ADS1220_VREF_EXTERNAL_REF, ADS1220_VREF_VDD, Ads1220::config, Ads1220Config::conv, MeteoStick::current_airspeed, MeteoStick::current_humidity, MeteoStick::current_pressure, MeteoStick::current_temperature, MeteoStick::diff_pressure, eeprom25AA256_init(), foo, Ads1220Config::gain, MeteoStick::humidity_period, Ads1220Config::i1mux, Ads1220Config::i2mux, Ads1220Config::idac, log_tagged, meteo_stick, MS_PITOT_COUNTER, MTOSTK_NUM_SENSORS, Ads1220Config::mux, Ads1220Config::pga_bypass, pitot_counter, MeteoStick::pressure, Ads1220Config::rate, MeteoStick::reset_dp_offset, MeteoStick::temperature, and Ads1220Config::vref.
meteo_stick_periodic()
void meteo_stick_periodic (void) extern
Periodic function.
Definition at line 377 of file meteo_stick.c.
References ads1220_periodic(), MeteoStick::current_humidity, DefaultChannel, DefaultDevice, MeteoStick::diff_pressure, eeprom25AA256_read(), foo, get_humidity(), MeteoStick::humidity_period, meteo_stick, meteo_stick_send_data(), MS_PITOT_COUNTER, MTOSTK_NUM_SENSORS, mtostk_populate_cal_from_buffer(), pitot_counter, MeteoStick::pressure, pwm_input_period_tics, MeteoStick::reset_dp_offset, SPITransDone, and MeteoStick::temperature.
meteo_stick_report()
void meteo_stick_report (void) extern
Definition at line 497 of file meteo_stick.c.
References DefaultChannel, DefaultDevice, and meteo_stick_send_data().
Variable Documentation
meteo_stick
struct MeteoStick meteo_stick extern
General structure.
Definition at line 87 of file meteo_stick.c.
Referenced by get_diff(), get_humidity(), get_pressure(), get_temp(), meteo_stick_event(), meteo_stick_init(), meteo_stick_periodic(), and meteo_stick_send_data().