Paparazzi UAS: sw/airborne/modules/meteo/meteo_france_DAQ.h File Reference
meteo_france_DAQ.h File Reference
Communication module with the Data Acquisition board from Meteo France.
#include "std.h"
#include "mcu_periph/gpio.h"
#include "generated/airframe.h"
Data Structures
struct MF_DAQ
Macros
#define MF_DAQ_SIZE 32
#define meteo_france_DAQ_SetPower(_x) {}
Functions
void init_mf_daq (void)
void mf_daq_send_state (void)
void mf_daq_send_report (void)
void parse_mf_daq_msg (uint8_t *buf)
Variables
struct MF_DAQ mf_daq
Detailed Description
Communication module with the Data Acquisition board from Meteo France.
DAQ board sends measurments to the AP AP sends periodic report to the ground, store data on SD card and sends A/C state to DAQ board
Definition in file meteo_france_DAQ.h.
Data Structure Documentation
MF_DAQ
struct MF_DAQ
Definition at line 43 of file meteo_france_DAQ.h.
Data Fields
uint8_t nb
uint8_t power
float values[MF_DAQ_SIZE]
Macro Definition Documentation
meteo_france_DAQ_SetPower
#define meteo_france_DAQ_SetPower (_x) {}
Definition at line 63 of file meteo_france_DAQ.h.
MF_DAQ_SIZE
#define MF_DAQ_SIZE 32
Definition at line 41 of file meteo_france_DAQ.h.
Function Documentation
init_mf_daq()
void init_mf_daq (void) extern
Definition at line 57 of file meteo_france_DAQ.c.
References foo, gpio_setup_output(), log_started, meteo_france_DAQ_SetPower, mf_daq, MF_DAQ_POWER_INIT, MF_DAQ::nb, and MF_DAQ::power.
mf_daq_send_report()
void mf_daq_send_report (void) extern
Definition at line 92 of file meteo_france_DAQ.c.
References GpsState::course, course, DefaultChannel, DefaultDevice, UtmCoor_f::east, FALSE, GpsState::fix, foo, gps, GpsState::gspeed, GpsState::hmsl, log_started, mf_daq, MF_DAQ::nb, GpsState::ned_vel, UtmCoor_f::north, pprzlog_tp, pprzLogFile, stateGetPositionUtm_f(), GpsState::tow, MF_DAQ::values, GpsState::week, and NedCoor_i::z.
mf_daq_send_state()
void mf_daq_send_state (void) extern
Definition at line 68 of file meteo_france_DAQ.c.
References autopilot, extra_pprz_tp, pprz_autopilot::flight_time, foo, p, stateGetAccelNed_f(), stateGetBodyRates_f(), stateGetHorizontalWindspeed_f(), stateGetNedToBodyEulers_f(), stateGetPositionLla_f(), and stateGetSpeedEnu_f().
parse_mf_daq_msg()
void parse_mf_daq_msg (uint8_t * buf) extern
Definition at line 118 of file meteo_france_DAQ.c.
References UtmCoor_f::alt, autopilot, b, pprz_autopilot::flight_time, foo, log_started, mf_daq, MF_DAQ_SIZE, MF_DAQ::nb, p, pprzlog_tp, stateGetAccelNed_f(), stateGetBodyRates_f(), stateGetHorizontalWindspeed_f(), stateGetNedToBodyEulers_f(), stateGetPositionLla_f(), stateGetSpeedEnu_f(), and MF_DAQ::values.
Variable Documentation
mf_daq
struct MF_DAQ mf_daq extern
Definition at line 46 of file meteo_france_DAQ.c.
Referenced by init_mf_daq(), mf_daq_send_report(), and parse_mf_daq_msg().