Paparazzi UAS: sw/airborne/modules/meteo/meteo_france_DAQ.c File Reference
meteo_france_DAQ.c File Reference
Communication module with the Data Acquisition board from Meteo France.
#include "modules/meteo/meteo_france_DAQ.h"
#include "state.h"
#include "autopilot.h"
#include "modules/datalink/datalink.h"
#include "modules/datalink/downlink.h"
#include "modules/loggers/sdlog_chibios.h"
#include "modules/loggers/pprzlog_tp.h"
#include "modules/gps/gps.h"
#include "modules/datalink/extra_pprz_dl.h"
Macros
#define MF_DAQ_POWER_INIT TRUE
Functions
void init_mf_daq (void)
void mf_daq_send_state (void)
void mf_daq_send_report (void)
void parse_mf_daq_msg (uint8_t *buf)
Variables
struct MF_DAQ mf_daq
bool log_started
Detailed Description
Communication module with the Data Acquisition board from Meteo France.
DAQ board sends measurments to the AP AP sends periodic report to the ground, store data on SD card and sends A/C state to DAQ board
Definition in file meteo_france_DAQ.c.
Macro Definition Documentation
MF_DAQ_POWER_INIT
#define MF_DAQ_POWER_INIT TRUE
Definition at line 50 of file meteo_france_DAQ.c.
Function Documentation
init_mf_daq()
void init_mf_daq (void)
Definition at line 57 of file meteo_france_DAQ.c.
References foo, gpio_setup_output(), log_started, meteo_france_DAQ_SetPower, mf_daq, MF_DAQ_POWER_INIT, MF_DAQ::nb, and MF_DAQ::power.
mf_daq_send_report()
void mf_daq_send_report (void)
Definition at line 92 of file meteo_france_DAQ.c.
References GpsState::course, course, DefaultChannel, DefaultDevice, UtmCoor_f::east, FALSE, GpsState::fix, foo, gps, GpsState::gspeed, GpsState::hmsl, log_started, mf_daq, MF_DAQ::nb, GpsState::ned_vel, UtmCoor_f::north, pprzlog_tp, pprzLogFile, stateGetPositionUtm_f(), GpsState::tow, MF_DAQ::values, GpsState::week, and NedCoor_i::z.
mf_daq_send_state()
void mf_daq_send_state (void)
Definition at line 68 of file meteo_france_DAQ.c.
References autopilot, extra_pprz_tp, pprz_autopilot::flight_time, foo, p, stateGetAccelNed_f(), stateGetBodyRates_f(), stateGetHorizontalWindspeed_f(), stateGetNedToBodyEulers_f(), stateGetPositionLla_f(), and stateGetSpeedEnu_f().
parse_mf_daq_msg()
void parse_mf_daq_msg (uint8_t * buf)
Definition at line 118 of file meteo_france_DAQ.c.
References UtmCoor_f::alt, autopilot, b, pprz_autopilot::flight_time, foo, log_started, mf_daq, MF_DAQ_SIZE, MF_DAQ::nb, p, pprzlog_tp, stateGetAccelNed_f(), stateGetBodyRates_f(), stateGetHorizontalWindspeed_f(), stateGetNedToBodyEulers_f(), stateGetPositionLla_f(), stateGetSpeedEnu_f(), and MF_DAQ::values.
Variable Documentation
log_started
bool log_started
Definition at line 47 of file meteo_france_DAQ.c.
Referenced by aoa_pwm_init(), aoa_pwm_update(), dw1000_arduino_periodic(), init_mf_daq(), ins_float_invariant_propagate(), mf_daq_send_report(), parse_mf_daq_msg(), and process_data().
mf_daq
struct MF_DAQ mf_daq
Definition at line 46 of file meteo_france_DAQ.c.
Referenced by init_mf_daq(), mf_daq_send_report(), and parse_mf_daq_msg().