Paparazzi UAS: sw/airborne/modules/meteo/mf_ptu.h File Reference
mf_ptu.h File Reference
Functions
void mf_ptu_init (void)
Data acquisition module for Meteo France PTU board.
void mf_ptu_periodic (void)
Function Documentation
mf_ptu_init()
void mf_ptu_init (void) extern
Data acquisition module for Meteo France PTU board.
Definition at line 76 of file mf_ptu.c.
References adc_buf_channel(), ADC_CHANNEL_PTU_NB_SAMPLES, foo, gpio_set(), gpio_setup_output(), humid_period, pressure_adc, pressure_buf, temp_adc, and temp_buf.
mf_ptu_periodic()
void mf_ptu_periodic (void) extern
Definition at line 95 of file mf_ptu.c.
References adc_buf::av_nb_sample, GpsState::course, DefaultChannel, DefaultDevice, GpsState::fix, foo, get_pwm_input_period_in_usec(), gps, GpsState::gspeed, GpsState::hmsl, humid_period, LlaCoor_i::lat, GpsState::lla_pos, LlaCoor_i::lon, GpsState::ned_vel, pprzLogFile, pressure_adc, pressure_buf, PTU_HUMIDTY_OFFSET, PTU_HUMIDTY_SCALE, PTU_PRESSURE_OFFSET, PTU_PRESSURE_SCALE, PTU_TEMPERATURE_OFFSET, PTU_TEMPERATURE_SCALE, adc_buf::sum, temp_adc, temp_buf, GpsState::tow, GpsState::week, and NedCoor_i::z.