Paparazzi UAS: sw/airborne/modules/actuators/actuators.c File Reference
actuators.c File Reference
Hardware independent actuators code.
#include "modules/actuators/actuators.h"
#include "modules/core/commands.h"
#include "mcu_periph/sys_time.h"
Functions
void actuators_init (void)
void actuators_periodic (void)
Detailed Description
Hardware independent actuators code.
Definition in file actuators.c.
Function Documentation
actuators_init()
void actuators_init (void)
Definition at line 321 of file actuators.c.
Referenced by main_init(), main_init(), and px4_gimbal_init().
actuators_periodic()
void actuators_periodic (void)
Definition at line 322 of file actuators.c.