Paparazzi UAS: sw/airborne/modules/actuators/actuators.h File Reference
actuators.h File Reference
Hardware independent API for actuators (servos, motor controllers).
#include "paparazzi.h"
#include "std.h"
#include "generated/airframe.h"
Data Structures
struct act_feedback_t
struct act_feedback_t::act_feedback_set_t
struct act_config_t
Typedefs
typedef void(* act_set_t) (uint8_t driver_idx, int16_t driver_value)
Actuator set callback.
Functions
void actuators_init (void)
void actuators_periodic (void)
Detailed Description
Hardware independent API for actuators (servos, motor controllers).
Definition in file actuators.h.
Data Structure Documentation
act_feedback_t
struct act_feedback_t
Definition at line 44 of file actuators.h.
Data Fields
uint8_t idx General index of the actuators (generated in airframe.h)
float position In radians.
int32_t rpm RPM.
struct act_feedback_set_t set Bitset registering what is set as feedback.
act_feedback_t::act_feedback_set_t
struct act_feedback_t::act_feedback_set_t
Definition at line 46 of file actuators.h.
Data Fields
bool position: 1 Position is set.
bool rpm: 1 RPM is set.
act_config_t
struct act_config_t
Definition at line 56 of file actuators.h.
Data Fields
uint8_t driver_no Driver number.
int32_t max Driver max value (or motor max position)
int32_t min Driver min value (or motor stop position)
int32_t neutral Driver neutral value (or motor idle position)
uint8_t servo_idx Driver servo index.
float travel_down Precomputed travel down coef.
float travel_up Precomputed travel up coef.
Typedef Documentation
act_set_t
typedef void(* act_set_t) (uint8_t driver_idx, int16_t driver_value)
Actuator set callback.
Parameters
driver_idx actuator index in driver frame
driver_value actuator value in driver unit
Definition at line 71 of file actuators.h.
Function Documentation
actuators_init()
void actuators_init (void) extern
Definition at line 321 of file actuators.c.
Referenced by main_init(), main_init(), and px4_gimbal_init().
actuators_periodic()
void actuators_periodic (void) extern
Definition at line 322 of file actuators.c.