Paparazzi UAS: sw/airborne/modules/actuators/motor_mixing.h File Reference
motor_mixing.h File Reference
Motor Mixing.
#include "std.h"
#include "paparazzi.h"
#include "generated/airframe.h"
#include "motor_mixing_types.h"
Data Structures
struct MotorMixing
Functions
void motor_mixing_init (void)
void motor_mixing_run (bool motors_on, bool override_on, pprz_t in_cmd[])
void motor_mixing_run_spinup (uint32_t counter, uint32_t max_counter)
Variables
struct MotorMixing motor_mixing
Detailed Description
Motor Mixing.
Handles the mapping of roll/pitch/yaw commands to actual motor commands.
Definition in file motor_mixing.h.
Data Structure Documentation
MotorMixing
struct MotorMixing
Definition at line 36 of file motor_mixing.h.
Data Fields
int32_t commands[MOTOR_MIXING_NB_MOTOR]
uint32_t nb_failure
uint32_t nb_saturation
bool override_enabled[MOTOR_MIXING_NB_MOTOR]
int32_t override_value[MOTOR_MIXING_NB_MOTOR]
int32_t trim[MOTOR_MIXING_NB_MOTOR]
Function Documentation
motor_mixing_init()
void motor_mixing_init (void) extern
Definition at line 109 of file motor_mixing.c.
References MotorMixing::commands, DefaultPeriodic, foo, motor_mixing, MOTOR_MIXING_NB_MOTOR, MOTOR_MIXING_STOP_MOTOR, MOTOR_MIXING_TRIM_PITCH, MOTOR_MIXING_TRIM_ROLL, MOTOR_MIXING_TRIM_YAW, MotorMixing::nb_failure, MotorMixing::nb_saturation, MotorMixing::override_enabled, MotorMixing::override_value, pitch_coef, register_periodic_telemetry(), roll_coef, send_motor_mixing(), MotorMixing::trim, and yaw_coef.
motor_mixing_run()
void motor_mixing_run (bool motors_on, bool override_on, pprz_t in_cmd[]) extern
Definition at line 193 of file motor_mixing.c.
References bound_commands(), bound_commands_step(), MotorMixing::commands, FALSE, foo, INT32_MAX, INT32_MIN, MAX_PPRZ, motor_mixing, MOTOR_MIXING_MAX_MOTOR, MOTOR_MIXING_MAX_SATURATION_OFFSET, MOTOR_MIXING_MIN_MOTOR, MOTOR_MIXING_NB_MOTOR, MOTOR_MIXING_SCALE, MOTOR_MIXING_STOP_MOTOR, MotorMixing::nb_failure, MotorMixing::nb_saturation, offset_commands(), MotorMixing::override_enabled, MotorMixing::override_value, pitch_coef, roll_coef, thrust_coef, MotorMixing::trim, and yaw_coef.
motor_mixing_run_spinup()
void motor_mixing_run_spinup (uint32_t counter, uint32_t max_counter) extern
Definition at line 168 of file motor_mixing.c.
References MotorMixing::commands, counter, foo, motor_mixing, MOTOR_MIXING_MIN_MOTOR, MOTOR_MIXING_MIN_MOTOR_STARTUP, and MOTOR_MIXING_NB_MOTOR.
Variable Documentation
motor_mixing
struct MotorMixing motor_mixing extern
Definition at line 94 of file motor_mixing.c.
Referenced by actuators_hitl_periodic(), bound_commands(), bound_commands_step(), motor_mixing_init(), motor_mixing_run(), motor_mixing_run_spinup(), nps_autopilot_run_step(), offset_commands(), send_motor_mixing(), and send_status().