Paparazzi UAS: sw/airborne/modules/actuators/motor_mixing.c File Reference
motor_mixing.c File Reference
Motor Mixing.
#include "modules/actuators/motor_mixing.h"
#include "paparazzi.h"
#include "modules/datalink/telemetry.h"
Macros
#define INT32_MIN (-2147483647-1)
#define INT32_MAX (2147483647)
#define MOTOR_MIXING_MIN_MOTOR 0
#define MOTOR_MIXING_MAX_MOTOR MAX_PPRZ
#define MOTOR_MIXING_STOP_MOTOR -MAX_PPRZ
#define MOTOR_MIXING_TRIM_ROLL 0
#define MOTOR_MIXING_TRIM_PITCH 0
#define MOTOR_MIXING_TRIM_YAW 0
#define MOTOR_MIXING_MAX_SATURATION_OFFSET MAX_PPRZ/10
Maximum offset in case of saturation.
#define MOTOR_MIXING_MIN_MOTOR_STARTUP MOTOR_MIXING_MIN_MOTOR
Functions
static void send_motor_mixing (struct transport_tx *trans, struct link_device *dev)
void motor_mixing_init (void)
static void offset_commands (int32_t offset)
static void bound_commands (void)
static void bound_commands_step (void)
void motor_mixing_run_spinup (uint32_t counter, uint32_t max_counter)
void motor_mixing_run (bool motors_on, bool override_on, pprz_t in_cmd[])
Variables
static const int32_t roll_coef [MOTOR_MIXING_NB_MOTOR] = MOTOR_MIXING_ROLL_COEF
static const int32_t pitch_coef [MOTOR_MIXING_NB_MOTOR] = MOTOR_MIXING_PITCH_COEF
static const int32_t yaw_coef [MOTOR_MIXING_NB_MOTOR] = MOTOR_MIXING_YAW_COEF
static const int32_t thrust_coef [MOTOR_MIXING_NB_MOTOR] = MOTOR_MIXING_THRUST_COEF
struct MotorMixing motor_mixing
Detailed Description
Motor Mixing.
Handles the mapping of roll/pitch/yaw commands to actual motor commands.
Definition in file motor_mixing.c.
Macro Definition Documentation
INT32_MAX
#define INT32_MAX (2147483647)
Definition at line 37 of file motor_mixing.c.
INT32_MIN
#define INT32_MIN (-2147483647-1)
Definition at line 33 of file motor_mixing.c.
MOTOR_MIXING_MAX_MOTOR
#define MOTOR_MIXING_MAX_MOTOR MAX_PPRZ
Definition at line 44 of file motor_mixing.c.
MOTOR_MIXING_MAX_SATURATION_OFFSET
#define MOTOR_MIXING_MAX_SATURATION_OFFSET MAX_PPRZ/10
Maximum offset in case of saturation.
If a saturation is reached (desired motor command outside of possible MIN_MOTOR/MAX_MOTOR range), this saturation_offset is applied to all motors in order to give attitude commands a higher priority than thrust. This setting limits the saturation_offset. Default is 10% of maximum command.
Definition at line 69 of file motor_mixing.c.
MOTOR_MIXING_MIN_MOTOR
#define MOTOR_MIXING_MIN_MOTOR 0
Definition at line 43 of file motor_mixing.c.
MOTOR_MIXING_MIN_MOTOR_STARTUP
#define MOTOR_MIXING_MIN_MOTOR_STARTUP MOTOR_MIXING_MIN_MOTOR
Definition at line 73 of file motor_mixing.c.
MOTOR_MIXING_STOP_MOTOR
#define MOTOR_MIXING_STOP_MOTOR -MAX_PPRZ
Definition at line 47 of file motor_mixing.c.
MOTOR_MIXING_TRIM_PITCH
#define MOTOR_MIXING_TRIM_PITCH 0
Definition at line 55 of file motor_mixing.c.
MOTOR_MIXING_TRIM_ROLL
#define MOTOR_MIXING_TRIM_ROLL 0
Definition at line 51 of file motor_mixing.c.
MOTOR_MIXING_TRIM_YAW
#define MOTOR_MIXING_TRIM_YAW 0
Definition at line 59 of file motor_mixing.c.
Function Documentation
bound_commands()
static void bound_commands (void) static
Definition at line 136 of file motor_mixing.c.
References MotorMixing::commands, foo, motor_mixing, MOTOR_MIXING_MAX_MOTOR, MOTOR_MIXING_MIN_MOTOR, and MOTOR_MIXING_NB_MOTOR.
Referenced by motor_mixing_run().
bound_commands_step()
static void bound_commands_step (void) static
Definition at line 144 of file motor_mixing.c.
References MotorMixing::commands, foo, motor_mixing, and MOTOR_MIXING_NB_MOTOR.
Referenced by motor_mixing_run().
motor_mixing_init()
void motor_mixing_init (void)
Definition at line 109 of file motor_mixing.c.
References MotorMixing::commands, DefaultPeriodic, foo, motor_mixing, MOTOR_MIXING_NB_MOTOR, MOTOR_MIXING_STOP_MOTOR, MOTOR_MIXING_TRIM_PITCH, MOTOR_MIXING_TRIM_ROLL, MOTOR_MIXING_TRIM_YAW, MotorMixing::nb_failure, MotorMixing::nb_saturation, MotorMixing::override_enabled, MotorMixing::override_value, pitch_coef, register_periodic_telemetry(), roll_coef, send_motor_mixing(), MotorMixing::trim, and yaw_coef.
motor_mixing_run()
void motor_mixing_run (bool motors_on, bool override_on, pprz_t in_cmd[])
Definition at line 193 of file motor_mixing.c.
References bound_commands(), bound_commands_step(), MotorMixing::commands, FALSE, foo, INT32_MAX, INT32_MIN, MAX_PPRZ, motor_mixing, MOTOR_MIXING_MAX_MOTOR, MOTOR_MIXING_MAX_SATURATION_OFFSET, MOTOR_MIXING_MIN_MOTOR, MOTOR_MIXING_NB_MOTOR, MOTOR_MIXING_SCALE, MOTOR_MIXING_STOP_MOTOR, MotorMixing::nb_failure, MotorMixing::nb_saturation, offset_commands(), MotorMixing::override_enabled, MotorMixing::override_value, pitch_coef, roll_coef, thrust_coef, MotorMixing::trim, and yaw_coef.
motor_mixing_run_spinup()
void motor_mixing_run_spinup (uint32_t counter, uint32_t max_counter)
Definition at line 168 of file motor_mixing.c.
References MotorMixing::commands, counter, foo, motor_mixing, MOTOR_MIXING_MIN_MOTOR, MOTOR_MIXING_MIN_MOTOR_STARTUP, and MOTOR_MIXING_NB_MOTOR.
offset_commands()
static void offset_commands (int32_t offset) static
Definition at line 128 of file motor_mixing.c.
References MotorMixing::commands, foo, motor_mixing, MOTOR_MIXING_NB_MOTOR, and offset.
Referenced by motor_mixing_run().
send_motor_mixing()
static void send_motor_mixing (struct transport_tx * trans, struct link_device * dev) static
Definition at line 98 of file motor_mixing.c.
References MotorMixing::commands, dev, foo, motor_mixing, and MOTOR_MIXING_NB_MOTOR.
Referenced by motor_mixing_init().
Variable Documentation
motor_mixing
struct MotorMixing motor_mixing
Definition at line 94 of file motor_mixing.c.
Referenced by actuators_hitl_periodic(), bound_commands(), bound_commands_step(), motor_mixing_init(), motor_mixing_run(), motor_mixing_run_spinup(), nps_autopilot_run_step(), offset_commands(), send_motor_mixing(), and send_status().
pitch_coef
const int32_t pitch_coef[MOTOR_MIXING_NB_MOTOR] = MOTOR_MIXING_PITCH_COEF static
Definition at line 90 of file motor_mixing.c.
Referenced by motor_mixing_init(), and motor_mixing_run().
roll_coef
const int32_t roll_coef[MOTOR_MIXING_NB_MOTOR] = MOTOR_MIXING_ROLL_COEF static
Definition at line 89 of file motor_mixing.c.
Referenced by motor_mixing_init(), and motor_mixing_run().
thrust_coef
const int32_t thrust_coef[MOTOR_MIXING_NB_MOTOR] = MOTOR_MIXING_THRUST_COEF static
Definition at line 92 of file motor_mixing.c.
Referenced by motor_mixing_run().
yaw_coef
const int32_t yaw_coef[MOTOR_MIXING_NB_MOTOR] = MOTOR_MIXING_YAW_COEF static
Definition at line 91 of file motor_mixing.c.
Referenced by init_gazebo(), motor_mixing_init(), and motor_mixing_run().