Paparazzi UAS: sw/airborne/modules/energy/MPPT.h File Reference
MPPT.h File Reference
Solar cells MPTT monitoring.
#include <inttypes.h>
Macros
#define MPPT_MODE_OFF 1
#define MPPT_MODE_PASSIVE 2
#define MPPT_MODE_ACTIVE 3
#define NB_DATA 9
#define MPPT_IBAT_INDEX 1
#define MPPT_ICONV_INDEX 6
#define MPPT_ITOTAL_INDEX 8
Functions
void MPPT_init (void)
void MPPT_automata (void)
void MPPT_periodic (void)
Variables
uint8_t MPPT_mode
0: VBat (mV) 1: IBat (mA) 2: PBat (mW) 3: VSol (mV) 4: ISol (mA) 5: PSol (mW) 6: IConv (mA) 7: PConv (mW)
Detailed Description
Solar cells MPTT monitoring.
Definition in file MPPT.h.
Macro Definition Documentation
MPPT_IBAT_INDEX
#define MPPT_IBAT_INDEX 1
Definition at line 39 of file MPPT.h.
MPPT_ICONV_INDEX
#define MPPT_ICONV_INDEX 6
Definition at line 40 of file MPPT.h.
MPPT_ITOTAL_INDEX
#define MPPT_ITOTAL_INDEX 8
Definition at line 41 of file MPPT.h.
MPPT_MODE_ACTIVE
#define MPPT_MODE_ACTIVE 3
Definition at line 36 of file MPPT.h.
MPPT_MODE_OFF
#define MPPT_MODE_OFF 1
Definition at line 34 of file MPPT.h.
MPPT_MODE_PASSIVE
#define MPPT_MODE_PASSIVE 2
Definition at line 35 of file MPPT.h.
NB_DATA
#define NB_DATA 9
Definition at line 38 of file MPPT.h.
Function Documentation
MPPT_automata()
void MPPT_automata (void)
MPPT_init()
void MPPT_init (void)
Definition at line 73 of file MPPT.c.
References MPPT_data, MPPT_mode, MPPT_status, MPPT_STATUS_IDLE, and NB_DATA.
MPPT_periodic()
void MPPT_periodic (void)
Definition at line 97 of file MPPT.c.
References i2c_transaction::buf, data_index, DefaultChannel, DefaultDevice, foo, i2c_receive(), i2c_transmit(), I2CTransSuccess, MPPT_ask(), MPPT_data, MPPT_data, MPPT_IBAT_INDEX, MPPT_ICONV_INDEX, MPPT_ITOTAL_INDEX, MPPT_mode, MPPT_MODE_ADDR, MPPT_SLAVE_ADDR, MPPT_status, MPPT_STATUS_ASKING, MPPT_STATUS_IDLE, MPPT_STATUS_READING, MPPT_STATUS_WRITING, mppt_trans, NB_DATA, NB_I2C_DATA, and i2c_transaction::status.
Variable Documentation
MPPT_mode
uint8_t MPPT_mode extern
0: VBat (mV) 1: IBat (mA) 2: PBat (mW) 3: VSol (mV) 4: ISol (mA) 5: PSol (mW) 6: IConv (mA) 7: PConv (mW)
9: IBat + IConv
Definition at line 60 of file MPPT.c.
Referenced by MPPT_init(), and MPPT_periodic().