Paparazzi UAS: sw/airborne/peripherals/mpu60x0.c File Reference
mpu60x0.c File Reference
MPU-60X0 driver common functions (I2C and SPI).
#include "peripherals/mpu60x0.h"
Functions
void mpu60x0_set_default_config (struct Mpu60x0Config *c)
void mpu60x0_send_config (Mpu60x0ConfigSet mpu_set, void *mpu, struct Mpu60x0Config *config)
Configuration sequence called once before normal use.
Variables
const float MPU60X0_GYRO_SENS [4]
const int32_t MPU60X0_GYRO_SENS_FRAC [4][2]
const float MPU60X0_ACCEL_SENS [4]
const int32_t MPU60X0_ACCEL_SENS_FRAC [4][2]
Detailed Description
MPU-60X0 driver common functions (I2C and SPI).
Still needs the either I2C or SPI specific implementation.
Definition in file mpu60x0.c.
Function Documentation
void mpu60x0_send_config (Mpu60x0ConfigSet mpu_set, void * mpu, struct Mpu60x0Config * config)
Configuration sequence called once before normal use.
Definition at line 82 of file mpu60x0.c.
References Mpu60x0Config::accel_range, Mpu60x0Config::clk_sel, Mpu60x0Config::dlpf_cfg, Mpu60x0Config::dlpf_cfg_acc, Mpu60x0Config::drdy_int_enable, Mpu60x0Config::gyro_range, Mpu60x0Config::init_status, Mpu60x0Config::initialized, MPU60X0, MPU60X0_CONF_ACCEL, MPU60X0_CONF_ACCEL2, MPU60X0_CONF_DLPF, MPU60X0_CONF_DONE, MPU60X0_CONF_GYRO, MPU60X0_CONF_I2C_SLAVES, MPU60X0_CONF_INT_ENABLE, MPU60X0_CONF_PWR, MPU60X0_CONF_RESET, MPU60X0_CONF_SD, MPU60X0_CONF_UNDOC1, MPU60X0_CONF_USER_RESET, mpu60x0_configure_i2c_slaves(), MPU60X0_FIFO_RESET, MPU60X0_I2C_MST_RESET, MPU60X0_REG_ACCEL_CONFIG, MPU60X0_REG_ACCEL_CONFIG2, MPU60X0_REG_CONFIG, MPU60X0_REG_GYRO_CONFIG, MPU60X0_REG_INT_ENABLE, MPU60X0_REG_PWR_MGMT_1, MPU60X0_REG_SMPLRT_DIV, MPU60X0_REG_UNDOC1, MPU60X0_REG_USER_CTRL, MPU60X0_SIG_COND_RESET, Mpu60x0Config::nb_slaves, Mpu60x0Config::smplrt_div, and Mpu60x0Config::type.
Referenced by mpu60x0_i2c_event(), mpu60x0_i2c_start_configure(), mpu60x0_spi_event(), and mpu60x0_spi_start_configure().
void mpu60x0_set_default_config (struct Mpu60x0Config * c)
Definition at line 60 of file mpu60x0.c.
References Mpu60x0Config::accel_range, Mpu60x0Config::clk_sel, Mpu60x0Config::dlpf_cfg, Mpu60x0Config::dlpf_cfg_acc, Mpu60x0Config::drdy_int_enable, Mpu60x0Config::gyro_range, Mpu60x0Config::i2c_bypass, MPU60X0, MPU60X0_DEFAULT_AFS_SEL, MPU60X0_DEFAULT_CLK_SEL, MPU60X0_DEFAULT_DLPF_CFG, MPU60X0_DEFAULT_DLPF_CFG_ACC, MPU60X0_DEFAULT_FS_SEL, MPU60X0_DEFAULT_SMPLRT_DIV, Mpu60x0Config::nb_bytes, Mpu60x0Config::nb_slave_init, Mpu60x0Config::nb_slaves, Mpu60x0Config::smplrt_div, and Mpu60x0Config::type.
Referenced by mpu60x0_i2c_init(), and mpu60x0_spi_init().
Variable Documentation
const float MPU60X0_ACCEL_SENS[4]
Initial value:
= {
  MPU60X0_ACCEL_SENS_2G,
  MPU60X0_ACCEL_SENS_4G,
  MPU60X0_ACCEL_SENS_8G,
  MPU60X0_ACCEL_SENS_16G
}
Definition at line 46 of file mpu60x0.c.
const int32_t MPU60X0_ACCEL_SENS_FRAC[4][2]
Initial value:
= {
  { MPU60X0_ACCEL_SENS_2G_NUM, MPU60X0_ACCEL_SENS_2G_DEN },
  { MPU60X0_ACCEL_SENS_4G_NUM, MPU60X0_ACCEL_SENS_4G_DEN },
  { MPU60X0_ACCEL_SENS_8G_NUM, MPU60X0_ACCEL_SENS_8G_DEN },
  { MPU60X0_ACCEL_SENS_16G_NUM, MPU60X0_ACCEL_SENS_16G_DEN }
}
Definition at line 53 of file mpu60x0.c.
const float MPU60X0_GYRO_SENS[4]
Initial value:
= {
  MPU60X0_GYRO_SENS_250,
  MPU60X0_GYRO_SENS_500,
  MPU60X0_GYRO_SENS_1000,
  MPU60X0_GYRO_SENS_2000
}
Definition at line 32 of file mpu60x0.c.
const int32_t MPU60X0_GYRO_SENS_FRAC[4][2]
Initial value:
= {
  { MPU60X0_GYRO_SENS_250_NUM, MPU60X0_GYRO_SENS_250_DEN },
  { MPU60X0_GYRO_SENS_500_NUM, MPU60X0_GYRO_SENS_500_DEN },
  { MPU60X0_GYRO_SENS_1000_NUM, MPU60X0_GYRO_SENS_1000_DEN },
  { MPU60X0_GYRO_SENS_2000_NUM, MPU60X0_GYRO_SENS_2000_DEN }
}
Definition at line 39 of file mpu60x0.c.