Paparazzi UAS: sw/airborne/peripherals/mpu9250.c File Reference
mpu9250.c File Reference
MPU-9250 driver common functions (I2C and SPI).
#include "peripherals/mpu9250.h"
Functions
void mpu9250_set_default_config (struct Mpu9250Config *c)
void mpu9250_send_config (Mpu9250ConfigSet mpu_set, void *mpu, struct Mpu9250Config *config)
Configuration sequence called once before normal use.
Variables
const float MPU9250_GYRO_SENS [4]
const struct FloatRates MPU9250_GYRO_SENS_F [4]
const float MPU9250_ACCEL_SENS [4]
const struct FloatVect3 MPU9250_ACCEL_SENS_F [4]
Detailed Description
MPU-9250 driver common functions (I2C and SPI).
Still needs the either I2C or SPI specific implementation.
Definition in file mpu9250.c.
Function Documentation
mpu9250_send_config()
void mpu9250_send_config (Mpu9250ConfigSet mpu_set, void * mpu, struct Mpu9250Config * config)
Configuration sequence called once before normal use.
Definition at line 81 of file mpu9250.c.
References Mpu9250Config::accel_range, Mpu9250Config::clk_sel, Mpu9250Config::dlpf_accel_cfg, Mpu9250Config::dlpf_gyro_cfg, Mpu9250Config::drdy_int_enable, foo, Mpu9250Config::gyro_range, Mpu9250Config::init_status, Mpu9250Config::initialized, MPU9250_CONF_ACCEL, MPU9250_CONF_DLPF_ACCEL, MPU9250_CONF_DLPF_GYRO, MPU9250_CONF_DONE, MPU9250_CONF_GYRO, MPU9250_CONF_I2C_SLAVES, MPU9250_CONF_INT_ENABLE, MPU9250_CONF_PWR, MPU9250_CONF_RESET, MPU9250_CONF_SD, MPU9250_CONF_USER_RESET, mpu9250_configure_i2c_slaves(), MPU9250_FIFO_RESET, MPU9250_I2C_MST_RESET, MPU9250_REG_ACCEL_CONFIG, MPU9250_REG_ACCEL_CONFIG_2, MPU9250_REG_CONFIG, MPU9250_REG_GYRO_CONFIG, MPU9250_REG_INT_ENABLE, MPU9250_REG_PWR_MGMT_1, MPU9250_REG_SMPLRT_DIV, MPU9250_REG_USER_CTRL, MPU9250_SIG_COND_RESET, Mpu9250Config::nb_slaves, and Mpu9250Config::smplrt_div.
Referenced by mpu9250_i2c_event(), mpu9250_i2c_start_configure(), mpu9250_spi_event(), and mpu9250_spi_start_configure().
mpu9250_set_default_config()
void mpu9250_set_default_config (struct Mpu9250Config * c)
Definition at line 60 of file mpu9250.c.
References Mpu9250Config::accel_range, Mpu9250Config::clk_sel, Mpu9250Config::dlpf_accel_cfg, Mpu9250Config::dlpf_gyro_cfg, Mpu9250Config::drdy_int_enable, Mpu9250Config::gyro_range, Mpu9250Config::i2c_bypass, MPU9250_DEFAULT_AFS_SEL, MPU9250_DEFAULT_CLK_SEL, MPU9250_DEFAULT_DLPF_ACCEL_CFG, MPU9250_DEFAULT_DLPF_GYRO_CFG, MPU9250_DEFAULT_FS_SEL, MPU9250_DEFAULT_SMPLRT_DIV, Mpu9250Config::nb_bytes, Mpu9250Config::nb_slave_init, Mpu9250Config::nb_slaves, and Mpu9250Config::smplrt_div.
Referenced by mpu9250_i2c_init(), and mpu9250_spi_init().
Variable Documentation
MPU9250_ACCEL_SENS
const float MPU9250_ACCEL_SENS[4]
Initial value:
= {
  MPU9250_ACCEL_SENS_2G,
  MPU9250_ACCEL_SENS_4G,
  MPU9250_ACCEL_SENS_8G,
  MPU9250_ACCEL_SENS_16G
}
Definition at line 46 of file mpu9250.c.
MPU9250_ACCEL_SENS_F
const struct FloatVect3 MPU9250_ACCEL_SENS_F[4]
Initial value:
= {
  {MPU9250_ACCEL_SENS_2G, MPU9250_ACCEL_SENS_2G, MPU9250_ACCEL_SENS_2G},
  {MPU9250_ACCEL_SENS_4G, MPU9250_ACCEL_SENS_4G, MPU9250_ACCEL_SENS_4G},
  {MPU9250_ACCEL_SENS_8G, MPU9250_ACCEL_SENS_8G, MPU9250_ACCEL_SENS_8G},
  {MPU9250_ACCEL_SENS_16G, MPU9250_ACCEL_SENS_16G, MPU9250_ACCEL_SENS_16G}
}
Definition at line 53 of file mpu9250.c.
Referenced by imu_mpu9250_init().
MPU9250_GYRO_SENS
const float MPU9250_GYRO_SENS[4]
Initial value:
= {
  MPU9250_GYRO_SENS_250,
  MPU9250_GYRO_SENS_500,
  MPU9250_GYRO_SENS_1000,
  MPU9250_GYRO_SENS_2000
}
Definition at line 32 of file mpu9250.c.
MPU9250_GYRO_SENS_F
const struct FloatRates MPU9250_GYRO_SENS_F[4]
Initial value:
= {
  {MPU9250_GYRO_SENS_250, MPU9250_GYRO_SENS_250, MPU9250_GYRO_SENS_250},
  {MPU9250_GYRO_SENS_500, MPU9250_GYRO_SENS_500, MPU9250_GYRO_SENS_500},
  {MPU9250_GYRO_SENS_1000, MPU9250_GYRO_SENS_1000, MPU9250_GYRO_SENS_1000},
  {MPU9250_GYRO_SENS_2000, MPU9250_GYRO_SENS_2000, MPU9250_GYRO_SENS_2000}
}
Definition at line 39 of file mpu9250.c.
Referenced by imu_mpu9250_init().