Paparazzi UAS: sw/airborne/peripherals/mpu9250_i2c.h File Reference
mpu9250_i2c.h File Reference
Driver for the MPU-9250 using I2C.
#include "std.h"
#include "math/pprz_algebra_int.h"
#include "mcu_periph/i2c.h"
#include "peripherals/mpu9250.h"
#include "peripherals/ak8963.h"
Data Structures
struct Mpu9250_I2c
union Mpu9250_I2c.data_accel
union Mpu9250_I2c.data_rates
Macros
#define IMU_MPU9250_READ_MAG TRUE
#define MPU9250_BUFFER_EXT_LEN 16
Enumerations
enum Mpu9250I2cSlaveInitStatus {
MPU9250_I2C_CONF_UNINIT , MPU9250_I2C_CONF_I2C_MST_DIS , MPU9250_I2C_CONF_I2C_BYPASS_EN , MPU9250_I2C_CONF_SLAVES_CONFIGURE ,
MPU9250_I2C_CONF_I2C_BYPASS_DIS , MPU9250_I2C_CONF_I2C_MST_CLK , MPU9250_I2C_CONF_I2C_MST_DELAY , MPU9250_I2C_CONF_I2C_SMPLRT ,
MPU9250_I2C_CONF_I2C_MST_EN , MPU9250_I2C_CONF_DONE
}
Functions
void mpu9250_i2c_init (struct Mpu9250_I2c *mpu, struct i2c_periph *i2c_p, uint8_t addr)
void mpu9250_i2c_start_configure (struct Mpu9250_I2c *mpu)
void mpu9250_i2c_read (struct Mpu9250_I2c *mpu)
void mpu9250_i2c_event (struct Mpu9250_I2c *mpu)
static void mpu9250_i2c_periodic (struct Mpu9250_I2c *mpu)
convenience function: read or start configuration if not already initialized
Detailed Description
Driver for the MPU-9250 using I2C.
Definition in file mpu9250_i2c.h.
Data Structure Documentation
Mpu9250_I2c
struct Mpu9250_I2c
Definition at line 59 of file mpu9250_i2c.h.
Data Fields
struct Ak8963 akm "internal" magnetometer
struct Mpu9250Config config
union Mpu9250_I2c.data_accel data_accel
volatile bool data_available data ready flag
uint8_t data_ext[MPU9250_BUFFER_EXT_LEN]
union Mpu9250_I2c.data_rates data_rates
struct i2c_periph * i2c_p
struct i2c_transaction i2c_trans
enum Mpu9250I2cSlaveInitStatus slave_init_status
Mpu9250_I2c.data_accel
union Mpu9250_I2c.data_accel
Definition at line 63 of file mpu9250_i2c.h.
Data Fields
int16_t value[3] accel data values accessible by channel index
struct Int16Vect3 vect accel data vector in accel coordinate system
Mpu9250_I2c.data_rates
union Mpu9250_I2c.data_rates
Definition at line 67 of file mpu9250_i2c.h.
Data Fields
struct Int16Rates rates rates data as angular rates in gyro coordinate system
int16_t value[3] rates data values accessible by channel index
Macro Definition Documentation
IMU_MPU9250_READ_MAG
#define IMU_MPU9250_READ_MAG TRUE
Definition at line 40 of file mpu9250_i2c.h.
MPU9250_BUFFER_EXT_LEN
#define MPU9250_BUFFER_EXT_LEN 16
Definition at line 44 of file mpu9250_i2c.h.
Enumeration Type Documentation
Mpu9250I2cSlaveInitStatus
enum Mpu9250I2cSlaveInitStatus
Enumerator
MPU9250_I2C_CONF_UNINIT
MPU9250_I2C_CONF_I2C_MST_DIS
MPU9250_I2C_CONF_I2C_BYPASS_EN
MPU9250_I2C_CONF_SLAVES_CONFIGURE
MPU9250_I2C_CONF_I2C_BYPASS_DIS
MPU9250_I2C_CONF_I2C_MST_CLK
MPU9250_I2C_CONF_I2C_MST_DELAY
MPU9250_I2C_CONF_I2C_SMPLRT
MPU9250_I2C_CONF_I2C_MST_EN
MPU9250_I2C_CONF_DONE
Definition at line 46 of file mpu9250_i2c.h.
Function Documentation
mpu9250_i2c_event()
void mpu9250_i2c_event (struct Mpu9250_I2c * mpu) extern
Definition at line 106 of file mpu9250_i2c.c.
References ak8963_event(), Mpu9250_I2c::akm, i2c_transaction::buf, Mpu9250_I2c::config, Mpu9250_I2c::data_accel, Mpu9250_I2c::data_available, Mpu9250_I2c::data_ext, Mpu9250_I2c::data_rates, FALSE, foo, Mpu9250Config::i2c_bypass, Mpu9250_I2c::i2c_trans, I2CTransDone, I2CTransFailed, I2CTransSuccess, Mpu9250Config::init_status, Mpu9250Config::initialized, Int16FromBuf, MPU9250_CONF_UNINIT, mpu9250_i2c_write_to_reg(), mpu9250_send_config(), Mpu9250Config::nb_bytes, Mpu9250Config::nb_slaves, and i2c_transaction::status.
Referenced by imu_mpu9250_event().
mpu9250_i2c_init()
void mpu9250_i2c_init (struct Mpu9250_I2c * mpu, struct i2c_periph * i2c_p, uint8_t addr) extern
Definition at line 33 of file mpu9250_i2c.c.
References ak8963_init(), Mpu9250_I2c::akm, Mpu9250_I2c::config, Mpu9250I2cSlave::configure, Mpu9250_I2c::data_available, Mpu9250Config::i2c_bypass, Mpu9250_I2c::i2c_p, Mpu9250_I2c::i2c_trans, I2CTransDone, imu_mpu9250_configure_mag_slave(), Mpu9250Config::init_status, Mpu9250Config::initialized, MPU9250_CONF_UNINIT, MPU9250_I2C_CONF_UNINIT, MPU9250_MAG_ADDR, mpu9250_set_default_config(), Mpu9250Config::nb_slaves, i2c_transaction::slave_addr, Mpu9250_I2c::slave_init_status, Mpu9250Config::slaves, and i2c_transaction::status.
Referenced by imu_mpu9250_init().
mpu9250_i2c_periodic()
static void mpu9250_i2c_periodic (struct Mpu9250_I2c * mpu) inline static
convenience function: read or start configuration if not already initialized
Definition at line 86 of file mpu9250_i2c.h.
References Mpu9250_I2c::config, Mpu9250Config::initialized, mpu9250_i2c_read(), and mpu9250_i2c_start_configure().
Referenced by imu_mpu9250_periodic().
mpu9250_i2c_read()
void mpu9250_i2c_read (struct Mpu9250_I2c * mpu) extern
Definition at line 87 of file mpu9250_i2c.c.
References ak8963_read(), Mpu9250_I2c::akm, i2c_transaction::buf, Mpu9250_I2c::config, foo, Mpu9250_I2c::i2c_p, Mpu9250_I2c::i2c_trans, i2c_transceive(), I2CTransDone, Mpu9250Config::initialized, MPU9250_REG_INT_STATUS, Mpu9250Config::nb_bytes, i2c_transaction::slave_addr, and i2c_transaction::status.
Referenced by mpu9250_i2c_periodic().
mpu9250_i2c_start_configure()
void mpu9250_i2c_start_configure (struct Mpu9250_I2c * mpu) extern
Definition at line 77 of file mpu9250_i2c.c.
References Mpu9250_I2c::config, Mpu9250_I2c::i2c_trans, I2CTransDone, I2CTransSuccess, Mpu9250Config::init_status, MPU9250_CONF_UNINIT, mpu9250_i2c_write_to_reg(), mpu9250_send_config(), and i2c_transaction::status.
Referenced by mpu9250_i2c_periodic().