Paparazzi UAS: sw/airborne/arch/stm32/peripherals/ms2100_arch.h File Reference
ms2100_arch.h File Reference
STM32 specific functions for the ms2100 magnetic sensor from PNI.
#include <libopencm3/stm32/gpio.h>
#include "mcu_periph/spi.h"
Macros
#define Ms2100HasEOC() (gpio_get(GPIOB, GPIO5) != 0)
Functions
static void Ms2100Reset (void)
Here Reset indicates the Ms2100 is in normal state, i.e.
static void Ms2100Set (void)
Here Set indicates the Ms2100 is in reset state, i.e.
void ms2100_reset_cb (struct spi_transaction *t)
Reset callback.
Detailed Description
STM32 specific functions for the ms2100 magnetic sensor from PNI.
Definition in file ms2100_arch.h.
Macro Definition Documentation
Ms2100HasEOC
#define Ms2100HasEOC () (gpio_get(GPIOB, GPIO5) != 0)
Definition at line 52 of file ms2100_arch.h.
Function Documentation
ms2100_reset_cb()
void ms2100_reset_cb (struct spi_transaction * t) extern
Reset callback.
called before spi transaction and after slave select
Definition at line 63 of file ms2100_arch.c.
References cpu_ticks_of_nsec(), foo, Ms2100Reset(), and Ms2100Set().
Referenced by ms2100_init().
Ms2100Reset()
static void Ms2100Reset (void) inline static
Here Reset indicates the Ms2100 is in normal state, i.e.
the reset line is driven low (i.e. the GPIO is "reset")
Definition at line 38 of file ms2100_arch.h.
References foo, and GPIO13.
Referenced by ms2100_arch_init(), and ms2100_reset_cb().
Ms2100Set()
static void Ms2100Set (void) inline static
Here Set indicates the Ms2100 is in reset state, i.e.
the reset line is driven high (i.e. the GPIO is "set")
Definition at line 47 of file ms2100_arch.h.
References foo, and GPIO13.
Referenced by ms2100_reset_cb().