Paparazzi UAS: sw/airborne/arch/stm32/peripherals/ms2100_arch.c File Reference
ms2100_arch.c File Reference
STM32 specific functions for the ms2100 magnetic sensor from PNI.
#include "peripherals/ms2100.h"
#include "mcu_periph/sys_time.h"
#include <libopencm3/stm32/rcc.h>
#include <libopencm3/stm32/gpio.h>
#include <libopencm3/stm32/exti.h>
#include <libopencm3/cm3/nvic.h>
Functions
void ms2100_arch_init (void)
void ms2100_reset_cb (struct spi_transaction *t)
Reset callback.
void exti9_5_isr (void)
Detailed Description
STM32 specific functions for the ms2100 magnetic sensor from PNI.
Definition in file ms2100_arch.c.
Function Documentation
exti9_5_isr()
void exti9_5_isr (void)
Definition at line 81 of file ms2100_arch.c.
References foo, ms2100, MS2100_GOT_EOC, and Ms2100::status.
ms2100_arch_init()
void ms2100_arch_init (void)
Definition at line 40 of file ms2100_arch.c.
References foo, GPIO13, GPIO5, gpio_set(), GPIOB, GPIOC, and Ms2100Reset().
Referenced by ms2100_init().
ms2100_reset_cb()
void ms2100_reset_cb (struct spi_transaction * t)
Reset callback.
called before spi transaction and after slave select
Definition at line 63 of file ms2100_arch.c.
References cpu_ticks_of_nsec(), foo, Ms2100Reset(), and Ms2100Set().
Referenced by ms2100_init().