Paparazzi UAS: sw/airborne/boards/bebop/mt9v117.h File Reference
mt9v117.h File Reference
Initialization and configuration of the MT9V117 CMOS Chip.
#include "std.h"
#include "mcu_periph/i2c.h"
#include "generated/airframe.h"
Data Structures
struct mt9v117_t
Macros
#define MT9V117_TARGET_FPS 0
#define MT9V117_FOCAL_X 307.f
#define MT9V117_FOCAL_Y 307.f
#define MT9V117_CENTER_X 120.f
#define MT9V117_CENTER_Y 120.f
#define MT9V117_DHANE_K 1.f
#define MT9V117_TARGET_LUMA 18000
Functions
void mt9v117_init (struct mt9v117_t *mt)
Initialisation of the Aptina MT9V117 CMOS sensor (1/6 inch VGA, bottom camera)
Variables
struct mt9v117_t mt9v117
Detailed Description
Initialization and configuration of the MT9V117 CMOS Chip.
Definition in file mt9v117.h.
Data Structure Documentation
mt9v117_t
struct mt9v117_t
Definition at line 59 of file mt9v117.h.
Data Fields
struct i2c_periph * i2c_periph I2C peripheral used to communicate over.
struct i2c_transaction i2c_trans I2C transaction for comminication with CMOS chip.
Macro Definition Documentation
MT9V117_CENTER_X
#define MT9V117_CENTER_X 120.f
Definition at line 47 of file mt9v117.h.
MT9V117_CENTER_Y
#define MT9V117_CENTER_Y 120.f
Definition at line 50 of file mt9v117.h.
MT9V117_DHANE_K
#define MT9V117_DHANE_K 1.f
Definition at line 53 of file mt9v117.h.
MT9V117_FOCAL_X
#define MT9V117_FOCAL_X 307.f
Definition at line 41 of file mt9v117.h.
MT9V117_FOCAL_Y
#define MT9V117_FOCAL_Y 307.f
Definition at line 44 of file mt9v117.h.
MT9V117_TARGET_FPS
#define MT9V117_TARGET_FPS 0
Definition at line 36 of file mt9v117.h.
MT9V117_TARGET_LUMA
#define MT9V117_TARGET_LUMA 18000
Definition at line 56 of file mt9v117.h.
Function Documentation
mt9v117_init()
void mt9v117_init (struct mt9v117_t * mt)
Initialisation of the Aptina MT9V117 CMOS sensor (1/6 inch VGA, bottom camera)
Definition at line 393 of file mt9v117.c.
References foo, I2CTransDone, MT9V117_AE_LUMA, MT9V117_AE_RULE_ALGO_AVERAGE, MT9V117_AE_RULE_ALGO_OFFSET, MT9V117_AE_RULE_VAR, MT9V117_AWB_PIXEL_THRESHOLD_COUNT_OFFSET, MT9V117_AWB_VAR, MT9V117_CAM_CTRL_VAR, MT9V117_CAM_OUTPUT_FORMAT_BT656_ENABLE, MT9V117_CAM_OUTPUT_FORMAT_OFFSET, MT9V117_CHIP_ID, MT9V117_CHIP_ID_RESP, MT9V117_COMMAND, MT9V117_COMMAND_OK, MT9V117_COMMAND_SET_STATE, mt9v117_config(), MT9V117_PAD_SLEW, MT9V117_RESET_MISC_CTRL, MT9V117_RESET_SOC_I2C, MT9V117_SYS_STATE_ENTER_CONFIG_CHANGE, MT9V117_SYSMGR_NEXT_STATE_OFFSET, MT9V117_SYSMGR_VAR, MT9V117_TARGET_LUMA, mt9v117_write_patch(), read_reg(), read_var(), write_reg(), and write_var().
Variable Documentation
mt9v117
struct mt9v117_t mt9v117 extern
Definition at line 93 of file mt9v117.c.