Paparazzi UAS: mesonh.mesonh Namespace Reference
mesonh.mesonh Namespace Reference
Functions
get_wind (east, north, up)
ivy_request_callback (sender, msg, resp, *args, **kwargs)
worldenv_cb (ac_id, msg)
signal_handler (signal, frame)
main ()
Variables
PPRZ_HOME = getenv("PAPARAZZI_HOME", os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), '../../../')))
int M_IN_KM = 1000.
atm = None
origin = np.array([0, 0, 0, 0])
scale = np.array([1., 1/M_IN_KM, 1/M_IN_KM, 1/M_IN_KM])
start_time = time.time()
Function Documentation
get_wind()
mesonh.mesonh.get_wind (east, north, up)
Definition at line 31 of file mesonh.py.
References foo.
Referenced by mesonh.mesonh.worldenv_cb().
ivy_request_callback()
mesonh.mesonh.ivy_request_callback (sender, msg, resp, * args, ** kwargs)
    Ivy Callback for Paparazzi Requests
Definition at line 43 of file mesonh.py.
References foo, and mesonh.mesonh.worldenv_cb().
main()
mesonh.mesonh.main (void)
Definition at line 86 of file mesonh.py.
References foo, and mesonh.mesonh.main().
Referenced by mesonh.mesonh.main().
signal_handler()
mesonh.mesonh.signal_handler (signal, frame)
Definition at line 80 of file mesonh.py.
References foo.
worldenv_cb()
mesonh.mesonh.worldenv_cb (ac_id, msg)
    Callback for paparazzi WORLD_ENV requests
Definition at line 55 of file mesonh.py.
References foo, and mesonh.mesonh.get_wind().
Referenced by mesonh.mesonh.ivy_request_callback().
Variable Documentation
atm
mesonh.mesonh.atm = None
Definition at line 24 of file mesonh.py.
M_IN_KM
int mesonh.mesonh.M_IN_KM = 1000.
Definition at line 22 of file mesonh.py.
origin
mesonh.mesonh.origin = np.array([0, 0, 0, 0])
Definition at line 25 of file mesonh.py.
PPRZ_HOME
mesonh.mesonh.PPRZ_HOME = getenv("PAPARAZZI_HOME", os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), '../../../')))
Definition at line 16 of file mesonh.py.
scale
mesonh.mesonh.scale = np.array([1., 1/M_IN_KM, 1/M_IN_KM, 1/M_IN_KM])
Definition at line 26 of file mesonh.py.
start_time
mesonh.mesonh.start_time = time.time()
Definition at line 28 of file mesonh.py.