Paparazzi UAS: sw/airborne/modules/nav/waypoints.c File Reference
waypoints.c File Reference
#include "modules/nav/waypoints.h"
#include "state.h"
#include "modules/datalink/downlink.h"
#include "generated/flight_plan.h"
#include "modules/datalink/telemetry.h"
#include "math/pprz_random.h"
Functions
static void send_wp_moved (struct transport_tx *trans, struct link_device *dev)
void waypoints_init (void)
initialize global and local waypoints
bool waypoint_is_global (uint8_t wp_id)
void waypoint_set_global_flag (uint8_t wp_id)
void waypoint_clear_global_flag (uint8_t wp_id)
float waypoint_get_x (uint8_t wp_id)
Get X/East coordinate of waypoint in meters.
float waypoint_get_y (uint8_t wp_id)
Get Y/North coordinate of waypoint in meters.
float waypoint_get_alt (uint8_t wp_id)
Get altitude of waypoint in meters (above reference)
float waypoint_get_lla_alt (uint8_t wp_id)
float waypoint_get_lat_deg (uint8_t wp_id)
Get latitude of waypoint in deg.
float waypoint_get_lat_rad (uint8_t wp_id)
Get latitude of waypoint in rad.
float waypoint_get_lon_deg (uint8_t wp_id)
Get longitude of waypoint in deg.
float waypoint_get_lon_rad (uint8_t wp_id)
Get longitude of waypoint in rad.
void waypoint_set_enu_i (uint8_t wp_id, struct EnuCoor_i *enu)
void waypoint_set_enu (uint8_t wp_id, struct EnuCoor_f *enu)
Set local ENU waypoint coordinates.
void waypoint_move_enu_i (uint8_t wp_id, struct EnuCoor_i *new_pos)
void waypoint_set_xy_i (uint8_t wp_id, int32_t x, int32_t y)
Set only local XY coordinates of waypoint without update altitude.
void waypoint_move_xy_i (uint8_t wp_id, int32_t x, int32_t y)
void waypoint_set_alt_i (uint8_t wp_id, int32_t alt)
void waypoint_set_alt (uint8_t wp_id, float alt)
Set altitude of waypoint in meters (above reference)
void waypoint_set_lla (uint8_t wp_id, struct LlaCoor_i *lla)
void waypoint_move_lla (uint8_t wp_id, struct LlaCoor_i *lla)
void waypoint_set_latlon (uint8_t wp_id, struct LlaCoor_i *lla)
set waypoint latitude/longitude without updating altitude
void waypoint_set_here (uint8_t wp_id)
set waypoint to current location and altitude
void waypoint_set_here_2d (uint8_t wp_id)
set waypoint to current horizontal location without modifying altitude
void waypoint_move_here_2d (uint8_t wp_id)
void waypoint_globalize (uint8_t wp_id)
update global LLA coordinates from its ENU coordinates
void waypoint_localize (uint8_t wp_id)
update local ENU coordinates from its LLA coordinates
void waypoints_localize_all (void)
update local ENU coordinates of global waypoints
struct LlaCoor_i * waypoint_get_lla (uint8_t wp_id)
Get LLA coordinates of waypoint.
struct EnuCoor_f * waypoint_get_enu_f (uint8_t wp_id)
Get ENU coordinates (float)
struct EnuCoor_i * waypoint_get_enu_i (uint8_t wp_id)
Get ENU coordinates (integer)
void waypoint_copy (uint8_t wp_dest, uint8_t wp_src)
copy one waypoint to another, this includes all flags from the source waypoint
void waypoint_position_copy (uint8_t wp_dest, uint8_t wp_src)
Variables
const uint8_t nb_waypoint = NB_WAYPOINT
struct Waypoint waypoints [NB_WAYPOINT]
size == nb_waypoint, waypoint 0 is a dummy waypoint
Function Documentation
send_wp_moved()
static void send_wp_moved (struct transport_tx * trans, struct link_device * dev) static
Definition at line 38 of file waypoints.c.
References dev, Waypoint::enu_i, foo, nb_waypoint, rand_uniform(), waypoints, EnuCoor_i::x, EnuCoor_i::y, and EnuCoor_i::z.
Referenced by waypoints_init().
waypoint_clear_global_flag()
void waypoint_clear_global_flag (uint8_t wp_id)
Definition at line 95 of file waypoints.c.
References foo, nb_waypoint, waypoints, and WP_FLAG_GLOBAL.
waypoint_copy()
void waypoint_copy (uint8_t wp_dest, uint8_t wp_src)
copy one waypoint to another, this includes all flags from the source waypoint
Definition at line 418 of file waypoints.c.
References foo, nb_waypoint, and waypoints.
Referenced by drop_zone_set().
waypoint_get_alt()
float waypoint_get_alt (uint8_t wp_id)
Get altitude of waypoint in meters (above reference)
Definition at line 118 of file waypoints.c.
References Waypoint::enu_f, nb_waypoint, waypoints, and EnuCoor_f::z.
Referenced by nav_home(), and stereocam_droplet_periodic().
waypoint_get_enu_f()
struct EnuCoor_f * waypoint_get_enu_f (uint8_t wp_id)
Get ENU coordinates (float)
Parameters
wp_id waypoint id
Returns
pointer to waypoint ENU (float) coordinates, NULL if invalid
Definition at line 392 of file waypoints.c.
References Waypoint::enu_f, foo, nb_waypoint, waypoint_is_global(), waypoint_localize(), waypoints, and WP_FLAG_ENU_F.
Referenced by follow_me_periodic(), nav_land_at_wp(), nav_poles_setup_wp(), nav_survey_hybrid_setup_orientation(), nav_survey_hybrid_setup_towards(), nav_takeoff_from_wp(), NavApproaching(), NavApproachingFrom(), NavCircleWaypoint(), NavGlide(), NavGotoWaypoint(), NavSegment(), and Oval().
waypoint_get_enu_i()
struct EnuCoor_i * waypoint_get_enu_i (uint8_t wp_id)
Get ENU coordinates (integer)
Parameters
wp_id waypoint id
Returns
pointer to waypoint ENU (integer) coordinates, NULL if invalid
Definition at line 405 of file waypoints.c.
References Waypoint::enu_i, foo, nb_waypoint, waypoint_is_global(), waypoint_localize(), waypoints, and WP_FLAG_ENU_I.
waypoint_get_lat_deg()
float waypoint_get_lat_deg (uint8_t wp_id)
Get latitude of waypoint in deg.
Definition at line 134 of file waypoints.c.
References DEG_OF_EM7DEG, foo, nb_waypoint, waypoint_globalize(), waypoint_is_global(), waypoints, and WP_FLAG_LLA_I.
Referenced by waypoint_get_lat_rad().
waypoint_get_lat_rad()
float waypoint_get_lat_rad (uint8_t wp_id)
Get latitude of waypoint in rad.
Definition at line 147 of file waypoints.c.
References foo, and waypoint_get_lat_deg().
waypoint_get_lla()
struct LlaCoor_i * waypoint_get_lla (uint8_t wp_id)
Get LLA coordinates of waypoint.
If the waypoint does not have its global coordinates set, the LLA representation is computed if the local origin is set.
Parameters
wp_id waypoint id
Returns
pointer to waypoint LLA coordinates, NULL if invalid
Definition at line 379 of file waypoints.c.
References foo, Waypoint::lla, nb_waypoint, waypoint_globalize(), waypoint_is_global(), waypoints, and WP_FLAG_LLA_I.
Referenced by mavlink_send_wp(), and put_lat_lon_home().
waypoint_get_lla_alt()
float waypoint_get_lla_alt (uint8_t wp_id)
Definition at line 126 of file waypoints.c.
References LlaCoor_i::alt, Waypoint::lla, nb_waypoint, stateGetLlaOrigin_i(), and waypoints.
waypoint_get_lon_deg()
float waypoint_get_lon_deg (uint8_t wp_id)
Get longitude of waypoint in deg.
Definition at line 152 of file waypoints.c.
References DEG_OF_EM7DEG, foo, nb_waypoint, waypoint_globalize(), waypoint_is_global(), waypoints, and WP_FLAG_LLA_I.
Referenced by waypoint_get_lon_rad().
waypoint_get_lon_rad()
float waypoint_get_lon_rad (uint8_t wp_id)
Get longitude of waypoint in rad.
Definition at line 165 of file waypoints.c.
References foo, and waypoint_get_lon_deg().
waypoint_get_x()
float waypoint_get_x (uint8_t wp_id)
Get X/East coordinate of waypoint in meters.
Definition at line 102 of file waypoints.c.
References Waypoint::enu_f, nb_waypoint, waypoints, and EnuCoor_f::x.
Referenced by distance_to_wall(), draw_osd(), guidance_plane_attitude_from_nav(), home_direction(), mission_point_of_lla(), and stereocam_droplet_periodic().
waypoint_get_y()
float waypoint_get_y (uint8_t wp_id)
Get Y/North coordinate of waypoint in meters.
Definition at line 110 of file waypoints.c.
References Waypoint::enu_f, nb_waypoint, waypoints, and EnuCoor_f::y.
Referenced by distance_to_wall(), draw_osd(), guidance_plane_attitude_from_nav(), home_direction(), mission_point_of_lla(), and stereocam_droplet_periodic().
waypoint_globalize()
void waypoint_globalize (uint8_t wp_id)
update global LLA coordinates from its ENU coordinates
Definition at line 334 of file waypoints.c.
References ecef_of_enu_pos_i(), foo, lla_of_ecef_i(), State::ned_initialized_i, state, stateGetNedOrigin_i(), waypoints, and WP_FLAG_LLA_I.
Referenced by waypoint_get_lat_deg(), waypoint_get_lla(), waypoint_get_lon_deg(), waypoint_set_alt(), waypoint_set_alt_i(), waypoint_set_enu(), waypoint_set_enu_i(), and waypoint_set_xy_i().
waypoint_is_global()
bool waypoint_is_global (uint8_t wp_id)
Definition at line 80 of file waypoints.c.
References foo, nb_waypoint, waypoints, and WP_FLAG_GLOBAL.
Referenced by copilot_parse_move_wp_dl(), waypoint_get_enu_f(), waypoint_get_enu_i(), waypoint_get_lat_deg(), waypoint_get_lla(), waypoint_get_lon_deg(), waypoint_move_here_2d(), waypoint_move_lla(), waypoint_set_here(), waypoint_set_here_2d(), and waypoints_localize_all().
waypoint_localize()
void waypoint_localize (uint8_t wp_id)
update local ENU coordinates from its LLA coordinates
Definition at line 345 of file waypoints.c.
References ENU_FLOAT_OF_BFP, Waypoint::enu_i, enu_of_lla_point_i(), foo, State::ned_initialized_i, POS_BFP_OF_REAL, state, stateGetNedOrigin_i(), waypoints, WP_FLAG_ENU_F, and WP_FLAG_ENU_I.
Referenced by waypoint_get_enu_f(), waypoint_get_enu_i(), waypoint_set_latlon(), waypoint_set_lla(), and waypoints_localize_all().
waypoint_move_enu_i()
void waypoint_move_enu_i (uint8_t wp_id, struct EnuCoor_i * new_pos)
Definition at line 194 of file waypoints.c.
References DefaultChannel, DefaultDevice, foo, nb_waypoint, and waypoint_set_enu_i().
Referenced by follow_wp(), and update_wp().
waypoint_move_here_2d()
void waypoint_move_here_2d (uint8_t wp_id)
Definition at line 315 of file waypoints.c.
References LlaCoor_i::alt, DefaultChannel, DefaultDevice, Waypoint::enu_i, foo, LlaCoor_i::lat, Waypoint::lla, LlaCoor_i::lon, nb_waypoint, stateGetHmslOrigin_i(), stateGetLlaOrigin_i(), waypoint_is_global(), waypoints, EnuCoor_i::y, and EnuCoor_i::z.
Referenced by mav_exercise_periodic(), and orange_avoider_periodic().
waypoint_move_lla()
void waypoint_move_lla (uint8_t wp_id, struct LlaCoor_i * lla)
Definition at line 258 of file waypoints.c.
References LlaCoor_i::alt, DefaultChannel, DefaultDevice, Waypoint::enu_i, foo, LlaCoor_i::lat, LlaCoor_i::lon, nb_waypoint, stateGetHmslOrigin_i(), stateGetLlaOrigin_i(), waypoint_is_global(), waypoint_set_lla(), waypoints, EnuCoor_i::y, and EnuCoor_i::z.
Referenced by nav_parse_MOVE_WP().
waypoint_move_xy_i()
void waypoint_move_xy_i (uint8_t wp_id, int32_t x, int32_t y)
Definition at line 219 of file waypoints.c.
References DefaultChannel, DefaultDevice, foo, nb_waypoint, waypoint_set_xy_i(), and waypoints.
Referenced by detection_cb(), moveWaypoint(), and moveWaypoint().
waypoint_position_copy()
void waypoint_position_copy (uint8_t wp_dest, uint8_t wp_src)
Definition at line 425 of file waypoints.c.
References Waypoint::enu_f, Waypoint::enu_i, foo, LlaCoor_i::lat, Waypoint::lla, LlaCoor_i::lon, nb_waypoint, waypoints, EnuCoor_f::x, EnuCoor_i::x, EnuCoor_f::y, and EnuCoor_i::y.
waypoint_set_alt()
void waypoint_set_alt (uint8_t wp_id, float alt)
Set altitude of waypoint in meters (above reference)
Definition at line 238 of file waypoints.c.
References LlaCoor_i::alt, Waypoint::enu_f, Waypoint::enu_i, nb_waypoint, POS_BFP_OF_REAL, waypoint_globalize(), waypoints, EnuCoor_f::z, and EnuCoor_i::z.
Referenced by follow_me(), and mavlink_common_message_handler().
waypoint_set_alt_i()
void waypoint_set_alt_i (uint8_t wp_id, int32_t alt)
Definition at line 228 of file waypoints.c.
References LlaCoor_i::alt, Waypoint::enu_f, Waypoint::enu_i, nb_waypoint, POS_FLOAT_OF_BFP, waypoint_globalize(), waypoints, EnuCoor_f::z, and EnuCoor_i::z.
Referenced by georeference_project().
waypoint_set_enu()
void waypoint_set_enu (uint8_t wp_id, struct EnuCoor_f * enu)
Set local ENU waypoint coordinates.
Definition at line 182 of file waypoints.c.
References ENU_BFP_OF_REAL, Waypoint::enu_f, foo, nb_waypoint, waypoint_globalize(), waypoints, WP_FLAG_ENU_F, WP_FLAG_ENU_I, and WP_FLAG_LLA_I.
Referenced by follow_me_periodic(), follow_me_set_wp(), mavlink_wp_message_handler(), nav_takeoff_from_here(), stereocam_droplet_periodic(), update_waypoint(), and waypoints_init().
waypoint_set_enu_i()
void waypoint_set_enu_i (uint8_t wp_id, struct EnuCoor_i * enu)
Definition at line 170 of file waypoints.c.
References ENU_FLOAT_OF_BFP, Waypoint::enu_i, foo, nb_waypoint, waypoint_globalize(), waypoints, WP_FLAG_ENU_F, WP_FLAG_ENU_I, and WP_FLAG_LLA_I.
Referenced by update_wp(), waypoint_move_enu_i(), and waypoint_set_here().
waypoint_set_global_flag()
void waypoint_set_global_flag (uint8_t wp_id)
Definition at line 88 of file waypoints.c.
References foo, nb_waypoint, waypoints, and WP_FLAG_GLOBAL.
Referenced by waypoints_init().
waypoint_set_here()
void waypoint_set_here (uint8_t wp_id)
set waypoint to current location and altitude
Definition at line 290 of file waypoints.c.
References nb_waypoint, stateGetPositionEnu_i(), stateGetPositionLla_i(), waypoint_is_global(), waypoint_set_enu_i(), and waypoint_set_lla().
waypoint_set_here_2d()
void waypoint_set_here_2d (uint8_t wp_id)
set waypoint to current horizontal location without modifying altitude
Definition at line 303 of file waypoints.c.
References nb_waypoint, stateGetPositionEnu_i(), stateGetPositionLla_i(), waypoint_is_global(), waypoint_set_latlon(), and waypoint_set_xy_i().
Referenced by nav_takeoff_from_wp().
waypoint_set_latlon()
void waypoint_set_latlon (uint8_t wp_id, struct LlaCoor_i * lla)
set waypoint latitude/longitude without updating altitude
Definition at line 278 of file waypoints.c.
References foo, LlaCoor_i::lat, Waypoint::lla, LlaCoor_i::lon, nb_waypoint, waypoint_localize(), waypoints, and WP_FLAG_LLA_I.
Referenced by mavlink_common_message_handler(), and waypoint_set_here_2d().
waypoint_set_lla()
void waypoint_set_lla (uint8_t wp_id, struct LlaCoor_i * lla)
Definition at line 248 of file waypoints.c.
References foo, Waypoint::lla, nb_waypoint, waypoint_localize(), waypoints, and WP_FLAG_LLA_I.
Referenced by mavlink_wp_message_handler(), waypoint_move_lla(), waypoint_set_here(), and waypoints_init().
waypoint_set_xy_i()
void waypoint_set_xy_i (uint8_t wp_id, int32_t x, int32_t y)
Set only local XY coordinates of waypoint without update altitude.
Todo:
: how to handle global waypoints?
Definition at line 207 of file waypoints.c.
References Waypoint::enu_f, Waypoint::enu_i, nb_waypoint, POS_FLOAT_OF_BFP, waypoint_globalize(), waypoints, EnuCoor_f::x, EnuCoor_i::x, EnuCoor_f::y, and EnuCoor_i::y.
Referenced by georeference_filter(), georeference_project(), run_avoid_navigation_onvision(), waypoint_move_xy_i(), and waypoint_set_here_2d().
waypoints_init()
void waypoints_init (void)
initialize global and local waypoints
Definition at line 56 of file waypoints.c.
References DefaultPeriodic, Waypoint::flags, foo, nb_waypoint, register_periodic_telemetry(), send_wp_moved(), waypoint_set_enu(), waypoint_set_global_flag(), waypoint_set_lla(), and waypoints.
Referenced by nav_init().
waypoints_localize_all()
void waypoints_localize_all (void)
update local ENU coordinates of global waypoints
update local ENU coordinates of all global waypoints
Definition at line 362 of file waypoints.c.
References nb_waypoint, waypoint_is_global(), and waypoint_localize().
Referenced by ins_ekf2_init(), ins_ekf2_update(), ins_ext_pose_init_from_flightplan(), nav_reset_alt(), and nav_reset_reference().
Variable Documentation
nb_waypoint
const uint8_t nb_waypoint = NB_WAYPOINT
Definition at line 31 of file waypoints.c.
Referenced by send_wp_moved(), waypoint_clear_global_flag(), waypoint_copy(), waypoint_get_alt(), waypoint_get_enu_f(), waypoint_get_enu_i(), waypoint_get_lat_deg(), waypoint_get_lla(), waypoint_get_lla_alt(), waypoint_get_lon_deg(), waypoint_get_x(), waypoint_get_y(), waypoint_is_global(), waypoint_move_enu_i(), waypoint_move_here_2d(), waypoint_move_lla(), waypoint_move_xy_i(), waypoint_position_copy(), waypoint_set_alt(), waypoint_set_alt_i(), waypoint_set_enu(), waypoint_set_enu_i(), waypoint_set_global_flag(), waypoint_set_here(), waypoint_set_here_2d(), waypoint_set_latlon(), waypoint_set_lla(), waypoint_set_xy_i(), waypoints_init(), and waypoints_localize_all().
waypoints
struct Waypoint waypoints[NB_WAYPOINT]
size == nb_waypoint, waypoint 0 is a dummy waypoint
Definition at line 32 of file waypoints.c.
Referenced by send_wp_moved(), waypoint_clear_global_flag(), waypoint_copy(), waypoint_get_alt(), waypoint_get_enu_f(), waypoint_get_enu_i(), waypoint_get_lat_deg(), waypoint_get_lla(), waypoint_get_lla_alt(), waypoint_get_lon_deg(), waypoint_get_x(), waypoint_get_y(), waypoint_globalize(), waypoint_is_global(), waypoint_localize(), waypoint_move_here_2d(), waypoint_move_lla(), waypoint_move_xy_i(), waypoint_position_copy(), waypoint_set_alt(), waypoint_set_alt_i(), waypoint_set_enu(), waypoint_set_enu_i(), waypoint_set_global_flag(), waypoint_set_latlon(), waypoint_set_lla(), waypoint_set_xy_i(), and waypoints_init().