Paparazzi UAS: sw/airborne/modules/nav/nav_geofence.h File Reference
nav_geofence.h File Reference
Optional exceptions triggeringg HOME_MODE 1) GEOFENCE_DATALINK_LOST_TIME: go to HOME mode if datalink lost for GEOFENCE_DATALINK_LOST_TIME 2) GEOFENCE_MAX_ALTITUDE: go HOME if airplane higher than the max altitude 3) GEOFENCE_MAX_HEIGHT: go HOME if airplane higher than the max height.
Functions
static bool datalink_lost (void)
static bool higher_than_max_altitude (void)
Detailed Description
Optional exceptions triggeringg HOME_MODE 1) GEOFENCE_DATALINK_LOST_TIME: go to HOME mode if datalink lost for GEOFENCE_DATALINK_LOST_TIME 2) GEOFENCE_MAX_ALTITUDE: go HOME if airplane higher than the max altitude 3) GEOFENCE_MAX_HEIGHT: go HOME if airplane higher than the max height.
home_mode_max_alt is (optionally) defined in the flight plan GEOFENCE_DATALINK_LOST_TIME is defined in the airframe config file
Definition in file nav_geofence.h.
Function Documentation
datalink_lost()
static bool datalink_lost (void) inline static
Definition at line 45 of file nav_geofence.h.
Referenced by autopilot_failsafe_checks(), and autopilot_static_periodic().
higher_than_max_altitude()
static bool higher_than_max_altitude (void) inline static
Definition at line 66 of file nav_geofence.h.
Referenced by autopilot_failsafe_checks(), and autopilot_static_periodic().