Paparazzi UAS: sw/airborne/modules/guidance/gvf_parametric/nav/nav_parametric_2d_trefoil.h File Reference
nav_parametric_2d_trefoil.h File Reference
#include "modules/guidance/trajectories/gvf_param_traj.h"
Data Structures
struct gvf_par_2d_tre_par
Functions
bool nav_gvf_parametric_2D_trefoil_XY (float xo, float yo, float w1, float w2, float ratio, float r, float alpha)
bool nav_gvf_parametric_2D_trefoil_wp (uint8_t wp, float w1, float w2, float ratio, float r, float alpha)
Variables
gvf_par_2d_tre_par gvf_parametric_2d_trefoil_par
Data Structure Documentation
gvf_par_2d_tre_par
struct gvf_par_2d_tre_par
Definition at line 46 of file nav_parametric_2d_trefoil.h.
Data Fields
float alpha
float kx
float ky
float r
float ratio
float w1
float w2
Function Documentation
nav_gvf_parametric_2D_trefoil_wp()
bool nav_gvf_parametric_2D_trefoil_wp (uint8_t wp, float w1, float w2, float ratio, float r, float alpha) extern
Definition at line 101 of file nav_parametric_2d_trefoil.c.
References alpha, gvf_parametric_p_len_wps, gvf_parametric_trajectory, nav_gvf_parametric_2D_trefoil_XY(), gvf_parametric_tra::p_parametric, WaypointX, and WaypointY.
nav_gvf_parametric_2D_trefoil_XY()
bool nav_gvf_parametric_2D_trefoil_XY (float xo, float yo, float w1, float w2, float ratio, float r, float alpha) extern
Definition at line 78 of file nav_parametric_2d_trefoil.c.
References alpha, gvf_parametric_con::beta, foo, gvf_parametric_2d_trefoil_info(), gvf_parametric_2d_trefoil_par, gvf_parametric_control, gvf_parametric_control_2D(), gvf_parametric_p_len_wps, gvf_parametric_trajectory, gvf_par_2d_tre_par::kx, gvf_par_2d_tre_par::ky, gvf_parametric_tra::p_len, gvf_parametric_tra::p_parametric, gvf_parametric_con::s, TREFOIL_2D, gvf_parametric_tra::type, and gvf_parametric_con::w.
Referenced by nav_gvf_parametric_2D_trefoil_wp().
Variable Documentation
gvf_parametric_2d_trefoil_par
gvf_par_2d_tre_par gvf_parametric_2d_trefoil_par extern
Definition at line 65 of file nav_parametric_2d_trefoil.c.
Referenced by nav_gvf_parametric_2D_trefoil_XY().