Paparazzi UAS: sw/airborne/modules/nav/nav_takeoff_and_landing_rotorcraft.c File Reference
nav_takeoff_and_landing_rotorcraft.c File Reference
#include "modules/nav/nav_takeoff_and_landing.h"
#include "math/pprz_geodetic_float.h"
#include "generated/flight_plan.h"
#include "firmwares/rotorcraft/navigation.h"
#include "modules/nav/waypoints.h"
#include "autopilot.h"
Macros
#define NAV_TAKEOFF_CLIMB_SPEED NAV_CLIMB_VSPEED
#define NAV_TAKEOFF_HEIGHT 2.f
#define NAV_LANDING_DESCEND_SPEED NAV_DESCEND_VSPEED
#define NAV_LANDING_AF_HEIGHT 5.f
#define NAV_LANDING_FLARE_HEIGHT 2.f
Functions
static bool nav_takeoff_run (void)
static bool nav_land_run (void)
void nav_takeoff_and_landing_init (void)
Init function.
void nav_takeoff_and_landing_periodic (void)
Periodic timeout check function.
bool nav_takeoff_from_wp (uint8_t wp_id, float height)
Takeoff from a waypoint.
bool nav_takeoff_from_loc (float lat UNUSED, float lon UNUSED, float height)
bool nav_takeoff_from_here (float height)
Takeoff from current location.
bool nav_land_at_wp (uint8_t td_id, uint8_t af_id, float radius UNUSED)
bool nav_land_at_loc (float td_alt, float lat, float lon, float dir, float dist, float radius UNUSED)
bool nav_land_here (float td_alt, float radius UNUSED)
Variables
static struct nav_takeoff takeoff
static struct nav_landing landing
float nav_takeoff_direction
Takeoff direction in range [0-360] (deg) set to flight plan QFU by default.
Detailed Description
Author
Gautier Hattenberger gauti.nosp@m.er.h.nosp@m.atten.nosp@m.berg.nosp@m.er@en.nosp@m.ac.f.nosp@m.r Navigation routines for takeoff and landing Basic procedures for rotorcraft
Definition in file nav_takeoff_and_landing_rotorcraft.c.
Macro Definition Documentation
NAV_LANDING_AF_HEIGHT
#define NAV_LANDING_AF_HEIGHT 5.f
Definition at line 47 of file nav_takeoff_and_landing_rotorcraft.c.
NAV_LANDING_DESCEND_SPEED
#define NAV_LANDING_DESCEND_SPEED NAV_DESCEND_VSPEED
Definition at line 43 of file nav_takeoff_and_landing_rotorcraft.c.
NAV_LANDING_FLARE_HEIGHT
#define NAV_LANDING_FLARE_HEIGHT 2.f
Definition at line 51 of file nav_takeoff_and_landing_rotorcraft.c.
NAV_TAKEOFF_CLIMB_SPEED
#define NAV_TAKEOFF_CLIMB_SPEED NAV_CLIMB_VSPEED
Definition at line 35 of file nav_takeoff_and_landing_rotorcraft.c.
NAV_TAKEOFF_HEIGHT
#define NAV_TAKEOFF_HEIGHT 2.f
Definition at line 39 of file nav_takeoff_and_landing_rotorcraft.c.
Function Documentation
nav_land_at_loc()
bool nav_land_at_loc (float td_alt, float lat, float lon, float dir, float dist, float radius UNUSED)
Definition at line 277 of file nav_takeoff_and_landing_rotorcraft.c.
References nav_landing::af_id, nav_landing::af_pos, LlaCoor_f::alt, dir, enu_of_lla_point_f(), foo, landing, LlaCoor_f::lat, LlaCoor_f::lon, nav_land_run(), NAV_LANDING_AF_HEIGHT, NAV_LANDING_FLARE_HEIGHT, NAV_LANDING_INIT, stateGetLlaOrigin_f(), stateGetNedOrigin_f(), nav_landing::status, nav_landing::td_id, nav_landing::td_pos, EnuCoor_f::x, EnuCoor_f::y, and EnuCoor_f::z.
nav_land_at_wp()
bool nav_land_at_wp (uint8_t td_id, uint8_t af_id, float radius UNUSED)
Definition at line 263 of file nav_takeoff_and_landing_rotorcraft.c.
References nav_landing::af_id, nav_landing::af_pos, landing, nav_land_run(), NAV_LANDING_AF_HEIGHT, NAV_LANDING_FLARE_HEIGHT, NAV_LANDING_INIT, nav_landing::status, nav_landing::td_id, nav_landing::td_pos, waypoint_get_enu_f(), and EnuCoor_f::z.
nav_land_here()
bool nav_land_here (float td_alt, float radius UNUSED)
Definition at line 293 of file nav_takeoff_and_landing_rotorcraft.c.
References nav_landing::af_id, nav_landing::af_pos, foo, landing, nav_land_run(), NAV_LANDING_AF_HEIGHT, NAV_LANDING_FLARE_HEIGHT, NAV_LANDING_INIT, stateGetPositionEnu_f(), nav_landing::status, nav_landing::td_id, nav_landing::td_pos, and EnuCoor_f::z.
nav_land_run()
static bool nav_land_run (void) static
Definition at line 215 of file nav_takeoff_and_landing_rotorcraft.c.
References nav_landing::af_pos, foo, landing, nav, RotorcraftNavigation::nav_approaching, nav_glide_points(), RotorcraftNavigation::nav_goto, nav_is_in_flight(), NAV_LANDING_DESCEND_SPEED, NAV_LANDING_DESCENT, NAV_LANDING_DONE, NAV_LANDING_FLARE, NAV_LANDING_INIT, NAV_LANDING_REACH_AF, RotorcraftNavigation::nav_route, NavKillThrottle, NavVerticalAltitudeMode, NavVerticalClimbMode, stateGetPositionEnu_f(), nav_landing::status, nav_landing::td_pos, nav_landing::timeout, EnuCoor_f::x, EnuCoor_f::y, and EnuCoor_f::z.
Referenced by nav_land_at_loc(), nav_land_at_wp(), and nav_land_here().
nav_takeoff_and_landing_init()
void nav_takeoff_and_landing_init (void)
Init function.
Definition at line 103 of file nav_takeoff_and_landing_rotorcraft.c.
References nav_landing::af_id, nav_takeoff::climb_id, foo, landing, landing, mission_register(), NAV_LANDING_INIT, nav_takeoff_direction, NAV_TAKEOFF_INIT, nav_landing::radius, nav_takeoff::status, nav_landing::status, takeoff, takeoff, nav_landing::td_id, nav_takeoff::timeout, and nav_landing::timeout.
nav_takeoff_and_landing_periodic()
void nav_takeoff_and_landing_periodic (void)
Periodic timeout check function.
Definition at line 122 of file nav_takeoff_and_landing_rotorcraft.c.
References landing, landing, NAV_LANDING_INIT, NAV_TAKEOFF_INIT, nav_takeoff::status, nav_landing::status, takeoff, takeoff, nav_takeoff::timeout, and nav_landing::timeout.
nav_takeoff_from_here()
bool nav_takeoff_from_here (float height)
Takeoff from current location.
fixedwing: climb direction is specified with setting
rotorcraft: start from current location and climb verticaly
Parameters
[in] height height in meters for ending takeoff procedure (<0 to use default value)
Returns
true until procedure is completed
Definition at line 197 of file nav_takeoff_and_landing_rotorcraft.c.
References nav_takeoff::climb_id, nav_takeoff::climb_pos, foo, nav_takeoff_direction, NAV_TAKEOFF_DIST, NAV_TAKEOFF_HEIGHT, NAV_TAKEOFF_INIT, nav_takeoff_run(), nav_takeoff_run(), nav_takeoff::start_pos, stateGetPositionEnu_f(), nav_takeoff::status, takeoff, takeoff, waypoint_set_enu(), EnuCoor_f::x, EnuCoor_f::y, and EnuCoor_f::z.
Referenced by nav_takeoff_from_loc().
nav_takeoff_from_loc()
bool nav_takeoff_from_loc (float lat UNUSED, float lon UNUSED, float height)
Definition at line 192 of file nav_takeoff_and_landing_rotorcraft.c.
References nav_takeoff_from_here().
nav_takeoff_from_wp()
bool nav_takeoff_from_wp (uint8_t wp_id, float height)
Takeoff from a waypoint.
fixedwing: set the climb direction
rotorcraft: set the wp at current location and climb verticaly
Parameters
[in] wp_id waypoint ID
[in] height height in meters for ending takeoff procedure (<0 to use default value)
Returns
true until procedure is completed
Definition at line 175 of file nav_takeoff_and_landing_rotorcraft.c.
References nav_takeoff::climb_id, nav_takeoff::climb_pos, NAV_TAKEOFF_HEIGHT, NAV_TAKEOFF_INIT, nav_takeoff_run(), nav_takeoff_run(), nav_takeoff::start_pos, stateGetPositionEnu_f(), nav_takeoff::status, takeoff, takeoff, waypoint_get_enu_f(), waypoint_set_here_2d(), WaypointX, WaypointY, EnuCoor_f::x, EnuCoor_f::y, and EnuCoor_f::z.
nav_takeoff_run()
static bool nav_takeoff_run (void) static
Definition at line 136 of file nav_takeoff_and_landing_rotorcraft.c.
References autopilot_get_motors_on(), autopilot_set_in_flight(), nav_takeoff::climb_id, nav_takeoff::climb_pos, foo, NAV_TAKEOFF_CLIMB, NAV_TAKEOFF_CLIMB_SPEED, NAV_TAKEOFF_DONE, NAV_TAKEOFF_INIT, NAV_TAKEOFF_START_MOTOR, NavGotoWaypoint, NAVIGATION_FREQUENCY, NavResurrect(), NavVerticalClimbMode, nav_takeoff::start_pos, stateGetPositionEnu_f(), nav_takeoff::status, takeoff, nav_takeoff::timeout, and EnuCoor_f::z.
Referenced by nav_takeoff_from_here(), and nav_takeoff_from_wp().
Variable Documentation
landing
struct nav_landing landing static
Definition at line 55 of file nav_takeoff_and_landing_rotorcraft.c.
Referenced by nav_land_at_loc(), nav_land_at_wp(), nav_land_here(), nav_land_run(), nav_takeoff_and_landing_init(), and nav_takeoff_and_landing_periodic().
nav_takeoff_direction
float nav_takeoff_direction
Takeoff direction in range [0-360] (deg) set to flight plan QFU by default.
Definition at line 60 of file nav_takeoff_and_landing_rotorcraft.c.
Referenced by nav_takeoff_and_landing_init().
takeoff
struct nav_takeoff takeoff static
Definition at line 54 of file nav_takeoff_and_landing_rotorcraft.c.
Referenced by nav_takeoff_and_landing_init(), nav_takeoff_and_landing_periodic(), nav_takeoff_from_here(), nav_takeoff_from_wp(), and nav_takeoff_run().