Paparazzi UAS: sw/airborne/modules/nav/nav_survey_poly_rotorcraft.h File Reference
nav_survey_poly_rotorcraft.h File Reference
#include "std.h"
Functions
void nav_survey_poly_setup (uint8_t FirstWP, uint8_t Size, float Sweep, float Orientation)
Setup polygon survey.
void nav_survey_poly_setup_towards (uint8_t FirstWP, uint8_t Size, float Sweep, int SecondWP)
Setup "dynamic" polygon survey with sweep orientation towards a waypoint.
bool nav_survey_poly_run (void)
Run polygon survey.
Variables
uint8_t Poly_Size
float Poly_Distance
uint16_t PolySurveySweepNum
uint16_t PolySurveySweepBackNum
bool Half_Sweep_Enabled
Function Documentation
nav_survey_poly_run()
bool nav_survey_poly_run (void) extern
Run polygon survey.
Definition at line 307 of file nav_survey_poly_rotorcraft.c.
References CSurveyStatus, dc_distance_interval, dc_send_command(), DC_SHOOT, dSweep, EdgeMaxY, EdgeMinY, Edges, Entry, EvaluateLineForX(), foo, Half_Sweep_Enabled, Init, LINE_START_FUNCTION, LINE_STOP_FUNCTION, MaxY, nav, RotorcraftNavigation::nav_approaching, RotorcraftNavigation::nav_goto, nav_init_stage(), RotorcraftNavigation::nav_route, nav_survey_shift, Poly_Distance, PolySurveySweepBackNum, PolySurveySweepNum, RotateAndTranslateToWorld(), SmallestCorner, stateGetPositionEnu_f(), survey_from, survey_to, SurveyEntry, SurveyEntryWP, SurveyFromWP, SurveySize, SurveyTheta, SurveyToWP, Sweep, Turn, VECT3_COPY, waypoints, EnuCoor_f::x, Point2D::x, EnuCoor_f::y, Point2D::y, and EnuCoor_f::z.
nav_survey_poly_setup()
void nav_survey_poly_setup (uint8_t FirstWP, uint8_t Size, float Sweep, float Orientation) extern
Setup polygon survey.
Parameters
FirstWP first waypoint/corner of the polygon
Size number of waypoints/corners used to define the polygon
Sweep distance between scan lines
Orientation angle of scan lines in degrees (CCW, east)
Definition at line 123 of file nav_survey_poly_rotorcraft.c.
References Line::b, CSurveyStatus, dSweep, EdgeMaxY, EdgeMinY, Edges, Entry, EvaluateLineForX(), FindInterceptOfTwoLines(), foo, Init, LINE_STOP_FUNCTION, Line::m, MaxFloat, MaxPolygonSize, MaxY, nav_set_heading_deg(), NavVerticalAltitudeMode, Poly_Distance, POLYSURVEY_ENTRY_DISTANCE, PolySurveySweepBackNum, PolySurveySweepNum, SmallestCorner, SurveyEntry, SurveyEntryWP, SurveyFromWP, SurveySize, SurveyTheta, SurveyToWP, TranslateAndRotateFromWorld(), waypoints, EnuCoor_f::x, point::x, Point2D::x, EnuCoor_f::y, point::y, and Point2D::y.
Referenced by nav_survey_poly_setup_towards().
nav_survey_poly_setup_towards()
void nav_survey_poly_setup_towards (uint8_t FirstWP, uint8_t Size, float Sweep, int SecondWP) extern
Setup "dynamic" polygon survey with sweep orientation towards a waypoint.
Computes the sweep orientation angle from the line FirstWP-SecondWP. If you pass zero for Size and/or Sweep it will use the global Poly_Size and Poly_Distance variables respectively (which can be changed via telemetry/settings).
Parameters
FirstWP first waypoint/corner of the polygon
Size number of waypoints/corners used to define the polygon, if zero uses Poly_Size
Sweep distance between scan lines, if zero uses Poly_Distance
SecondWP second waypoint towards which the sweep orientation is computed
Definition at line 63 of file nav_survey_poly_rotorcraft.c.
References foo, nav_survey_poly_setup(), Poly_Distance, Poly_Size, Sweep, waypoints, point::x, and point::y.
Variable Documentation
Half_Sweep_Enabled
bool Half_Sweep_Enabled extern
Definition at line 78 of file nav_survey_poly_osam.c.
Referenced by nav_survey_poly_osam_run(), and nav_survey_poly_run().
Poly_Distance
float Poly_Distance extern
Definition at line 61 of file nav_survey_poly_rotorcraft.c.
Referenced by nav_survey_poly_run(), nav_survey_poly_setup(), and nav_survey_poly_setup_towards().
Poly_Size
uint8_t Poly_Size extern
Definition at line 75 of file nav_survey_poly_osam.c.
Referenced by nav_survey_poly_osam_setup_towards(), and nav_survey_poly_setup_towards().
PolySurveySweepBackNum
uint16_t PolySurveySweepBackNum extern
Definition at line 142 of file nav_survey_poly_osam.c.
Referenced by nav_survey_poly_osam_ResetSweepNumber(), nav_survey_poly_osam_run(), nav_survey_poly_osam_setup(), nav_survey_poly_run(), and nav_survey_poly_setup().
PolySurveySweepNum
uint16_t PolySurveySweepNum extern
Definition at line 141 of file nav_survey_poly_osam.c.
Referenced by nav_survey_poly_osam_run(), nav_survey_poly_osam_setup(), nav_survey_poly_run(), and nav_survey_poly_setup().