Paparazzi UAS: sw/airborne/modules/nav/nav_line.c File Reference
nav_line.c File Reference
Fixedwing navigation along a line with nice U-turns.
#include "generated/airframe.h"
#include "modules/nav/nav_line.h"
#include "firmwares/fixedwing/nav.h"
Enumerations
enum line_status {
LR12 , LQC21 , LTC2 , LQC22 ,
LR21 , LQC12 , LTC1 , LQC11
}
Status along the pattern.
Functions
void nav_line_init (void)
void nav_line_setup (void)
bool nav_line_run (uint8_t l1, uint8_t l2, float radius)
Variables
static enum line_status line_status
Detailed Description
Fixedwing navigation along a line with nice U-turns.
Definition in file nav_line.c.
Enumeration Type Documentation
line_status
enum line_status
Status along the pattern.
Enumerator
LR12
LQC21
LTC2
LQC22
LR21
LQC12
LTC1
LQC11
Definition at line 53 of file nav_line.c.
Function Documentation
nav_line_init()
void nav_line_init (void)
Definition at line 56 of file nav_line.c.
References foo, and mission_register().
nav_line_run()
bool nav_line_run (uint8_t l1, uint8_t l2, float radius)
Definition at line 68 of file nav_line.c.
References point::a, CARROT, foo, LQC11, LQC12, LQC21, LQC22, LR12, LR21, LTC1, LTC2, nav_circle_XY(), nav_init_stage(), NavApproachingFrom, NavQdrCloseTo, NavSegment, NavVerticalAltitudeMode, NavVerticalAutoThrottleMode, WaypointAlt, waypoints, WaypointX, and WaypointY.
nav_line_setup()
void nav_line_setup (void)
Definition at line 63 of file nav_line.c.
References LR12.
Variable Documentation
line_status
enum line_status line_status static
Definition at line 54 of file nav_line.c.