Paparazzi UAS: sw/airborne/firmwares/fixedwing/nav.h File Reference
nav.h File Reference
Fixedwing Navigation library.
#include "std.h"
#include "paparazzi.h"
#include "state.h"
#include "modules/nav/nav_survey_rectangle.h"
#include "modules/nav/common_flight_plan.h"
#include "modules/nav/common_nav.h"
#include "autopilot.h"
#include "pprzlink/pprzlink_device.h"
#include "pprzlink/pprzlink_transport.h"
Macros
#define NAVIGATION_FREQUENCY 20
Default fixedwing navigation frequency.
#define NAV_GRAVITY 9.806
#define Square(_x) ((_x)*(_x))
#define DistanceSquare(p1_x, p1_y, p2_x, p2_y) (Square(p1_x-p2_x)+Square(p1_y-p2_y))
#define PowerVoltage() (electrical.vsupply)
#define RcRoll(travel) (radio_control_get(RADIO_ROLL) * (float)travel /(float)MAX_PPRZ)
#define NAV_MODE_ROLL 1
#define NAV_MODE_COURSE 2
#define HORIZONTAL_MODE_WAYPOINT 0
#define HORIZONTAL_MODE_ROUTE 1
#define HORIZONTAL_MODE_CIRCLE 2
#define NavGotoWaypoint(_wp)
#define NavGotoPoint(_point)
#define Eight(a, b, c) nav_eight((a), (b), (c))
#define Oval(a, b, c) nav_oval((b), (a), (c))
#define RCLost() RadioControlIsLost()
#define NavFollow(_ac_id, _distance, _height) nav_follow(_ac_id, _distance, _height)
#define NavGlide(_start_wp, _wp) nav_glide(_start_wp, _wp)
#define NavCircleWaypoint(wp, radius) nav_circle_XY(waypoints[wp].x, waypoints[wp].y, radius)
#define NavCircleCountNoRewind() (nav_circle_radians_no_rewind / (2*M_PI))
#define NavCircleCount() (fabs(nav_circle_radians) / (2*M_PI))
#define NavCircleQdr() ({ float qdr = DegOfRad(M_PI_2 - nav_circle_trigo_qdr); NormCourse(qdr); qdr; })
#define CloseDegAngles(_c1, _c2) ({ float _diff = _c1 - _c2; NormCourse(_diff); 350 < _diff || _diff < 10; })
#define NavQdrCloseTo(x) CloseDegAngles(x, NavCircleQdr())
True if x (in degrees) is close to the current QDR (less than 10 degrees)
#define NavCourseCloseTo(x) CloseDegAngles(x, DegOfRad(stateGetHorizontalSpeedDir_f()))
#define NavSegment(_start, _end) nav_route_xy(waypoints[_start].x, waypoints[_start].y, waypoints[_end].x, waypoints[_end].y)
#define NavApproaching(wp, time) nav_approaching_xy(waypoints[wp].x, waypoints[wp].y, last_x, last_y, time)
#define NavApproachingFrom(wp, from, time) nav_approaching_xy(waypoints[wp].x, waypoints[wp].y, waypoints[from].x, waypoints[from].y, time)
#define NavVerticalAutoThrottleMode(_pitch)
Set the climb control to auto-throttle with the specified pitch pre-command.
#define NavVerticalAutoPitchMode(_throttle)
Set the climb control to auto-pitch with the specified throttle pre-command.
#define NavVerticalAltitudeMode(_alt, _pre_climb)
Set the vertical mode to altitude control with the specified altitude setpoint and climb pre-command.
#define NavVerticalClimbMode(_climb)
Set the vertical mode to climb control with the specified climb setpoint.
#define NavVerticalThrottleMode(_throttle)
Set the vertical mode to fixed throttle with the specified setpoint.
#define NavHeading(_course)
#define NavAttitude(_roll)
#define NavSetMaxSpeed(_speed) {}
#define nav_IncreaseShift(x) { if (x==0) nav_shift = 0; else nav_shift += x; }
#define nav_SetNavRadius(x) { if (x==1) nav_radius = DEFAULT_CIRCLE_RADIUS; else if (x==-1) nav_radius = -DEFAULT_CIRCLE_RADIUS; else nav_radius = x; }
#define NavKillThrottle() { autopilot_set_kill_throttle(true); }
#define GetPosX() (stateGetPositionEnu_f()->x)
Get current x (east) position in local coordinates.
#define GetPosY() (stateGetPositionEnu_f()->y)
Get current y (north) position in local coordinates.
#define GetPosAlt() (stateGetPositionUtm_f()->alt)
Get current altitude above MSL.
#define GetPosHeight() (stateGetPositionEnu_f()->z)
Get current height above reference.
#define GetAltRef() (ground_alt)
Get current altitude reference for local coordinates.
#define SEND_NAVIGATION(_trans, _dev)
Enumerations
enum oval_status { OR12 , OC2 , OR21 , OC1 }
Functions
void fly_to_xy (float x, float y)
Computes desired_x, desired_y and desired_course.
void nav_eight_init (void)
void nav_eight (uint8_t, uint8_t, float)
Navigation along a figure 8.
void nav_oval_init (void)
void nav_oval (uint8_t, uint8_t, float)
void nav_periodic_task (void)
Navigation main: call to the code generated from the XML flight plan.
void nav_home (void)
Home mode navigation (circle around HOME)
void nav_init (void)
Navigation Initialisation.
void nav_without_gps (void)
Failsafe navigation without position estimation.
void nav_parse_BLOCK (struct link_device *dev, struct transport_tx *trans, uint8_t *buf)
void nav_parse_MOVE_WP (struct link_device *dev, struct transport_tx *trans, uint8_t *buf)
void nav_circle_XY (float x, float y, float radius)
Angle from center to mobile.
void nav_compute_baseleg (uint8_t wp_af, uint8_t wp_td, uint8_t wp_baseleg, float radius)
void nav_compute_final_from_glide (uint8_t wp_af, uint8_t wp_td, float glide)
void nav_follow (uint8_t _ac_id, float _distance, float _height)
void nav_glide (uint8_t start_wp, uint8_t wp)
void nav_glide_alt (float start_alt, float final_alt)
void nav_route_xy (float last_wp_x, float last_wp_y, float wp_x, float wp_y)
Computes the carrot position along the desired segment.
bool nav_approaching_xy (float x, float y, float from_x, float from_y, float approaching_time)
Decide if the UAV is approaching the current waypoint.
void DownlinkSendWpNr (uint8_t _wp)
Variables
enum oval_status oval_status
float cur_pos_x
float cur_pos_y
float last_x
float last_y
float desired_x
float desired_y
float nav_altitude
float flight_altitude
Dynamically adjustable, reset to nav_altitude when it is changing.
float nav_glide_pitch_trim
pprz_t nav_throttle_setpoint
float nav_pitch
float rc_pitch
float fp_pitch
float fp_throttle
float fp_climb
float carrot_x
float carrot_y
float nav_circle_radians
Status on the current circle.
float nav_circle_radians_no_rewind
bool nav_in_circle
bool nav_in_segment
float nav_circle_x
float nav_circle_y
float nav_circle_radius
float nav_segment_x_1
float nav_segment_y_1
float nav_segment_x_2
float nav_segment_y_2
int nav_mode
uint8_t horizontal_mode
uint8_t nav_oval_count
Navigation along a figure O.
float nav_radius
float nav_course
float nav_climb
float nav_shift
float nav_ground_speed_pgain
float nav_ground_speed_setpoint
float nav_survey_shift
float nav_survey_west
float nav_survey_east
float nav_survey_north
float nav_survey_south
bool nav_survey_active
float nav_circle_trigo_qdr
float baseleg_out_qdr
Detailed Description
Fixedwing Navigation library.
This collection of macros and functions is used by the C code generated from the XML flight plan.
Definition in file nav.h.
Macro Definition Documentation
CloseDegAngles
#define CloseDegAngles (_c1, _c2) ({ float _diff = _c1 - _c2; NormCourse(_diff); 350 < _diff || _diff < 10; })
Definition at line 158 of file nav.h.
DistanceSquare
#define DistanceSquare (p1_x, p1_y, p2_x, p2_y) (Square(p1_x-p2_x)+Square(p1_y-p2_y))
Definition at line 54 of file nav.h.
Eight
#define Eight (a, b, c) nav_eight((a), (b), (c))
Definition at line 109 of file nav.h.
GetAltRef
#define GetAltRef () (ground_alt)
Get current altitude reference for local coordinates.
This is the ground_alt from the flight plan at first, but might be updated later through a call to NavSetGroundReferenceHere() or NavSetAltitudeReferenceHere(), e.g. in the GeoInit flight plan block.
Definition at line 242 of file nav.h.
GetPosAlt
#define GetPosAlt () (stateGetPositionUtm_f()->alt)
Get current altitude above MSL.
Definition at line 233 of file nav.h.
GetPosHeight
#define GetPosHeight () (stateGetPositionEnu_f()->z)
Get current height above reference.
Definition at line 235 of file nav.h.
GetPosX
#define GetPosX () (stateGetPositionEnu_f()->x)
Get current x (east) position in local coordinates.
Definition at line 229 of file nav.h.
GetPosY
#define GetPosY () (stateGetPositionEnu_f()->y)
Get current y (north) position in local coordinates.
Definition at line 231 of file nav.h.
HORIZONTAL_MODE_CIRCLE
#define HORIZONTAL_MODE_CIRCLE 2
Definition at line 92 of file nav.h.
HORIZONTAL_MODE_ROUTE
#define HORIZONTAL_MODE_ROUTE 1
Definition at line 91 of file nav.h.
HORIZONTAL_MODE_WAYPOINT
#define HORIZONTAL_MODE_WAYPOINT 0
Definition at line 90 of file nav.h.
NAV_GRAVITY
#define NAV_GRAVITY 9.806
Definition at line 52 of file nav.h.
nav_IncreaseShift
#define nav_IncreaseShift (x) { if (x==0) nav_shift = 0; else nav_shift += x; }
Definition at line 222 of file nav.h.
NAV_MODE_COURSE
#define NAV_MODE_COURSE 2
Definition at line 86 of file nav.h.
NAV_MODE_ROLL
#define NAV_MODE_ROLL 1
Definition at line 85 of file nav.h.
nav_SetNavRadius
#define nav_SetNavRadius (x) { if (x==1) nav_radius = DEFAULT_CIRCLE_RADIUS; else if (x==-1) nav_radius = -DEFAULT_CIRCLE_RADIUS; else nav_radius = x; }
Definition at line 224 of file nav.h.
NavApproaching
#define NavApproaching (wp, time) nav_approaching_xy(waypoints[wp].x, waypoints[wp].y, last_x, last_y, time)
Definition at line 171 of file nav.h.
NavApproachingFrom
#define NavApproachingFrom (wp, from, time) nav_approaching_xy(waypoints[wp].x, waypoints[wp].y, waypoints[from].x, waypoints[from].y, time)
Definition at line 172 of file nav.h.
NavAttitude
#define NavAttitude (_roll)
Value:
    { \
    lateral_mode = LATERAL_MODE_ROLL; \
    if(autopilot_get_mode() != AP_MODE_AUTO1)  \
    {h_ctl_roll_setpoint = _roll;} \
  }
Definition at line 214 of file nav.h.
NavCircleCount
#define NavCircleCount () (fabs(nav_circle_radians) / (2*M_PI))
Definition at line 155 of file nav.h.
NavCircleCountNoRewind
#define NavCircleCountNoRewind () (nav_circle_radians_no_rewind / (2*M_PI))
Definition at line 154 of file nav.h.
NavCircleQdr
#define NavCircleQdr () ({ float qdr = DegOfRad(M_PI_2 - nav_circle_trigo_qdr); NormCourse(qdr); qdr; })
Definition at line 156 of file nav.h.
NavCircleWaypoint
#define NavCircleWaypoint (wp, radius) nav_circle_XY(waypoints[wp].x, waypoints[wp].y, radius)
Definition at line 151 of file nav.h.
NavCourseCloseTo
#define NavCourseCloseTo (x) CloseDegAngles(x, DegOfRad(stateGetHorizontalSpeedDir_f()))
Definition at line 163 of file nav.h.
NavFollow
#define NavFollow (_ac_id, _distance, _height) nav_follow(_ac_id, _distance, _height)
Definition at line 145 of file nav.h.
NavGlide
#define NavGlide (_start_wp, _wp) nav_glide(_start_wp, _wp)
Definition at line 149 of file nav.h.
NavGotoPoint
#define NavGotoPoint (_point)
Value:
    { \
    horizontal_mode = HORIZONTAL_MODE_WAYPOINT; \
    fly_to_xy(_point.x, _point.y); \
  }
Definition at line 101 of file nav.h.
NavGotoWaypoint
#define NavGotoWaypoint (_wp)
Value:
    { \
    horizontal_mode = HORIZONTAL_MODE_WAYPOINT; \
    fly_to_xy(waypoints[_wp].x, waypoints[_wp].y); \
  }
Definition at line 96 of file nav.h.
NavHeading
#define NavHeading (_course)
Value:
    { \
    lateral_mode = LATERAL_MODE_COURSE; \
    h_ctl_course_setpoint = _course; \
  }
Definition at line 209 of file nav.h.
NAVIGATION_FREQUENCY
#define NAVIGATION_FREQUENCY 20
Default fixedwing navigation frequency.
Definition at line 49 of file nav.h.
NavKillThrottle
#define NavKillThrottle (void) { autopilot_set_kill_throttle(true); }
Definition at line 226 of file nav.h.
NavQdrCloseTo
#define NavQdrCloseTo (x) CloseDegAngles(x, NavCircleQdr())
True if x (in degrees) is close to the current QDR (less than 10 degrees)
Definition at line 161 of file nav.h.
NavSegment
#define NavSegment (_start, _end) nav_route_xy(waypoints[_start].x, waypoints[_start].y, waypoints[_end].x, waypoints[_end].y)
Definition at line 167 of file nav.h.
NavSetMaxSpeed
#define NavSetMaxSpeed (_speed) {}
Definition at line 220 of file nav.h.
NavVerticalAltitudeMode
#define NavVerticalAltitudeMode (_alt, _pre_climb)
Value:
    { \
    v_ctl_mode = V_CTL_MODE_AUTO_ALT; \
    nav_altitude = _alt; \
    v_ctl_altitude_pre_climb = _pre_climb; \
  }
Set the vertical mode to altitude control with the specified altitude setpoint and climb pre-command.
Definition at line 191 of file nav.h.
NavVerticalAutoPitchMode
#define NavVerticalAutoPitchMode (_throttle)
Value:
    { \
    v_ctl_climb_mode = V_CTL_CLIMB_MODE_AUTO_PITCH; \
    nav_throttle_setpoint = _throttle; \
  }
Set the climb control to auto-pitch with the specified throttle pre-command.
Definition at line 184 of file nav.h.
NavVerticalAutoThrottleMode
#define NavVerticalAutoThrottleMode (_pitch)
Value:
    { \
    v_ctl_climb_mode = V_CTL_CLIMB_MODE_AUTO_THROTTLE; \
    nav_pitch = _pitch; \
  }
Set the climb control to auto-throttle with the specified pitch pre-command.
Definition at line 177 of file nav.h.
NavVerticalClimbMode
#define NavVerticalClimbMode (_climb)
Value:
    { \
    v_ctl_mode = V_CTL_MODE_AUTO_CLIMB; \
    v_ctl_climb_setpoint = _climb; \
  }
Set the vertical mode to climb control with the specified climb setpoint.
Definition at line 198 of file nav.h.
NavVerticalThrottleMode
#define NavVerticalThrottleMode (_throttle)
Value:
    { \
    v_ctl_mode = V_CTL_MODE_AUTO_THROTTLE; \
    nav_throttle_setpoint = _throttle; \
  }
Set the vertical mode to fixed throttle with the specified setpoint.
Definition at line 204 of file nav.h.
Oval
#define Oval (a, b, c) nav_oval((b), (a), (c))
Definition at line 114 of file nav.h.
PowerVoltage
#define PowerVoltage () (electrical.vsupply)
Definition at line 56 of file nav.h.
RCLost
#define RCLost () RadioControlIsLost()
Definition at line 142 of file nav.h.
RcRoll
#define RcRoll (travel) (radio_control_get(RADIO_ROLL) * (float)travel /(float)MAX_PPRZ)
Definition at line 57 of file nav.h.
SEND_NAVIGATION
#define SEND_NAVIGATION (_trans, _dev)
Value:
    { \
    uint8_t _circle_count = NavCircleCount(); \
    struct EnuCoor_f* pos = stateGetPositionEnu_f(); \
    float dist_wp = sqrtf(dist2_to_wp); \
    float dist_home = sqrtf(dist2_to_home); \
    uint8_t kill = (uint8_t)autopilot.kill_throttle; \
    pprz_msg_send_NAVIGATION(_trans, _dev, AC_ID, &nav_block, &nav_stage, &(pos->x), &(pos->y), &dist_wp, &dist_home, &autopilot.flight_time, &block_time, &stage_time, &kill, &_circle_count, &nav_oval_count); \
  }
Definition at line 245 of file nav.h.
Square
#define Square (_x) ((_x)*(_x))
Definition at line 53 of file nav.h.
Enumeration Type Documentation
oval_status
enum oval_status
Enumerator
OR12
OC2
OR21
OC1
Definition at line 60 of file nav.h.
Function Documentation
DownlinkSendWpNr()
void DownlinkSendWpNr (uint8_t _wp) extern
Definition at line 497 of file nav.c.
References DefaultChannel, DefaultDevice, DownlinkSendWp(), foo, and nb_waypoint.
Referenced by nav_catapult_run().
fly_to_xy()
void fly_to_xy (float x, float y) extern
Computes desired_x, desired_y and desired_course.
Definition at line 356 of file nav.c.
References CARROT, desired_x, desired_y, foo, h_ctl_course_pgain, h_ctl_course_setpoint, h_ctl_roll_max_setpoint, h_ctl_roll_setpoint, lateral_mode, LATERAL_MODE_COURSE, LATERAL_MODE_ROLL, nav_mode, NAV_MODE_COURSE, s, stateGetHorizontalSpeedDir_f(), stateGetHorizontalSpeedNorm_f(), stateGetPositionEnu_f(), EnuCoor_f::x, and EnuCoor_f::y.
Referenced by formation_flight(), mission_nav_wp(), nav_circle_XY(), nav_route_xy(), and potential_task().
nav_approaching_xy()
bool nav_approaching_xy (float x, float y, float from_x, float from_y, float approaching_time)
Decide if the UAV is approaching the current waypoint.
Computes dist2_to_wp and compare it to square carrot. Return true if it is smaller. Else computes by scalar products if uav has not gone past waypoint. approaching_time can be negative and in this case, the UAV will fly after the waypoint for the given number of seconds.
Returns
true if the position (x, y) is reached
distance to waypoint in x
distance to waypoint in y
Definition at line 325 of file nav.c.
References dist2_to_wp, foo, stateGetHorizontalSpeedNorm_f(), stateGetPositionEnu_f(), EnuCoor_f::x, and EnuCoor_f::y.
Referenced by gvf_nav_approaching(), mission_nav_path(), mission_nav_segment(), mission_nav_wp(), nav_catapult_run(), nav_eight(), nav_gvf_survey_polygon_run(), nav_land_run(), nav_line_osam_run(), nav_oval(), nav_spiral_run(), nav_survey_disc_run(), nav_survey_poly_osam_run(), nav_survey_polygon_run(), nav_survey_zamboni_run(), nav_takeoff_run(), and snav_route().
nav_circle_XY()
void nav_circle_XY (float x, float y, float radius) extern
Angle from center to mobile.
Angle from center to mobile.
Clockwise iff radius > 0
Computes a prebank. Go straight if inside or outside the circle
Definition at line 108 of file nav.c.
References CARROT, circle_bank, DistanceSquare, fly_to_xy(), foo, horizontal_mode, HORIZONTAL_MODE_CIRCLE, Min, nav_circle_radians, nav_circle_radians_no_rewind, nav_circle_radius, nav_circle_trigo_qdr, nav_circle_x, nav_circle_y, NAV_GRAVITY, nav_in_circle, nav_in_segment, nav_mode, NAV_MODE_COURSE, nav_shift, Square, stateGetHorizontalSpeedNorm_f(), stateGetPositionEnu_f(), EnuCoor_f::x, and EnuCoor_f::y.
Referenced by mission_nav_circle(), nav_eight(), nav_flower_run(), nav_lace_run(), nav_launcher_run(), nav_line_border_run(), nav_line_osam_run(), nav_line_run(), nav_oval(), nav_rosette_run(), nav_skid_landing_run(), nav_spiral_3D_run(), nav_spiral_run(), nav_survey_disc_run(), nav_survey_poly_osam_run(), nav_survey_polygon_run(), nav_survey_zamboni_run(), nav_trinity_run(), nav_vertical_raster_run(), snav_circle1(), snav_circle2(), and snav_on_time().
nav_compute_baseleg()
void nav_compute_baseleg (uint8_t wp_af, uint8_t wp_td, uint8_t wp_baseleg, float radius) extern
Definition at line 220 of file nav.c.
References point::a, baseleg_out_qdr, foo, nav_radius, waypoints, point::x, and point::y.
nav_compute_final_from_glide()
void nav_compute_final_from_glide (uint8_t wp_af, uint8_t wp_td, float glide) extern
Definition at line 241 of file nav.c.
References point::a, foo, waypoints, point::x, and point::y.
nav_eight()
void nav_eight (uint8_t target, uint8_t c1, float radius) extern
Navigation along a figure 8.
The cross center is defined by the waypoint [target], the center of one of the circles is defined by [c1]. Altitude is given by [target]. The navigation goes through 6 states: C1 (circle around [c1]), R1T, RT2 (route from circle 1 to circle 2 over [target]), C2 and R2T, RT1. If necessary, the [c1] waypoint is moved in the direction of [target] to be not far than [2*radius].
Definition at line 633 of file nav.c.
References point::a, UtmCoor_f::alt, C1, c1, C2, c2, CARROT, foo, InitStage, nav_approaching_xy(), nav_circle_XY(), nav_route_xy(), NavCircleWaypoint, NavQdrCloseTo, R1T, R2T, RT1, RT2, target, waypoints, point::x, and point::y.
nav_eight_init()
void nav_eight_init (void) extern
Definition at line 620 of file nav.c.
References C1.
nav_follow()
void nav_follow (uint8_t _ac_id, float _distance, float _height) extern
Definition at line 302 of file nav.c.
nav_glide()
void nav_glide (uint8_t start_wp, uint8_t wp) extern
Definition at line 158 of file nav.c.
References foo, nav_glide_alt(), and waypoints.
nav_glide_alt()
void nav_glide_alt (float start_alt, float final_alt) extern
Definition at line 163 of file nav.c.
References foo, nav_leg_length, nav_leg_progress, NavVerticalAltitudeMode, and stateGetHorizontalSpeedNorm_f().
Referenced by nav_glide(), and nav_land_run().
nav_home()
void nav_home (void) extern
Home mode navigation (circle around HOME)
Home mode navigation (circle around HOME)
Nominal speed
Definition at line 424 of file nav.c.
nav_init()
void nav_init (void) extern
Navigation Initialisation.
Definition at line 532 of file nav.c.
nav_oval()
void nav_oval (uint8_t p1, uint8_t p2, float radius) extern
Definition at line 762 of file nav.c.
References point::a, CARROT, foo, InitStage, LINE_START_FUNCTION, LINE_STOP_FUNCTION, nav_approaching_xy(), nav_circle_XY(), nav_oval_count, nav_route_xy(), NavQdrCloseTo, OC1, OC2, OR12, OR21, waypoints, point::x, and point::y.
Referenced by nav_register_oval(), and nav_register_oval().
nav_oval_init()
void nav_oval_init (void) extern
Definition at line 756 of file nav.c.
References nav_oval_count, and OC2.
Referenced by nav_register_oval().
nav_parse_BLOCK()
void nav_parse_BLOCK (struct link_device * dev, struct transport_tx * trans, uint8_t * buf) extern
Definition at line 585 of file nav.c.
References dev, foo, nav_goto_block(), and SEND_NAVIGATION.
nav_parse_MOVE_WP()
void nav_parse_MOVE_WP (struct link_device * dev, struct transport_tx * trans, uint8_t * buf) extern
Definition at line 592 of file nav.c.
References LlaCoor_f::alt, dev, foo, LlaCoor_f::lat, LlaCoor_f::lon, nav_move_waypoint(), nav_utm_east0, nav_utm_north0, nav_utm_zone0, utm_of_lla_f(), waypoints, point::x, point::y, and UtmCoor_f::zone.
nav_periodic_task()
void nav_periodic_task (void) extern
Navigation main: call to the code generated from the XML flight plan.
Definition at line 445 of file nav.c.
nav_route_xy()
void nav_route_xy (float last_wp_x, float last_wp_y, float wp_x, float wp_y) extern
Computes the carrot position along the desired segment.
distance of carrot (in meter)
Definition at line 382 of file nav.c.
References CARROT, fly_to_xy(), foo, horizontal_mode, HORIZONTAL_MODE_ROUTE, nav_carrot_leg_progress, nav_in_circle, nav_in_segment, nav_leg_length, nav_leg_progress, nav_segment_x_1, nav_segment_x_2, nav_segment_y_1, nav_segment_y_2, nav_shift, stateGetPositionEnu_f(), EnuCoor_f::x, and EnuCoor_f::y.
Referenced by mission_nav_path(), mission_nav_segment(), nav_bungee_takeoff_run(), nav_eight(), nav_flower_run(), nav_lace_run(), nav_land_run(), nav_launcher_run(), nav_line_osam_run(), nav_oval(), nav_points(), nav_rosette_run(), nav_skid_landing_run(), nav_spiral_run(), nav_survey_disc_run(), nav_survey_poly_osam_run(), nav_survey_rectangle(), nav_survey_zamboni_run(), nav_trinity_run(), and snav_route().
nav_without_gps()
void nav_without_gps (void) extern
Failsafe navigation without position estimation.
Just set attitude and throttle to FAILSAFE values to prevent the plane from crashing.
Definition at line 569 of file nav.c.
References foo, h_ctl_roll_setpoint, lateral_mode, LATERAL_MODE_ROLL, MAX_PPRZ, nav_pitch, nav_throttle_setpoint, TRIM_UPPRZ, v_ctl_mode, and V_CTL_MODE_AUTO_THROTTLE.
Referenced by navigation_task().
Variable Documentation
baseleg_out_qdr
float baseleg_out_qdr extern
Definition at line 219 of file nav.c.
Referenced by nav_compute_baseleg(), and nav_land_run().
carrot_x
float carrot_x extern
Definition at line 50 of file nav.c.
carrot_y
float carrot_y
Definition at line 75 of file nav.h.
cur_pos_x
float cur_pos_x extern
cur_pos_y
float cur_pos_y extern
desired_x
float desired_x extern
Definition at line 308 of file nav.c.
Referenced by fly_to_xy(), formation_flight(), gvf_parametric_control_2D(), potential_task(), and send_desired().
desired_y
float desired_y
Definition at line 66 of file nav.h.
flight_altitude
float flight_altitude
Dynamically adjustable, reset to nav_altitude when it is changing.
Definition at line 66 of file nav.h.
fp_climb
float fp_climb extern
Definition at line 313 of file nav.c.
Referenced by nav_init().
fp_pitch
float fp_pitch extern
Definition at line 311 of file nav.c.
Referenced by nav_init().
fp_throttle
float fp_throttle extern
Definition at line 312 of file nav.c.
Referenced by nav_init().
horizontal_mode
uint8_t horizontal_mode extern
Definition at line 70 of file nav.c.
Referenced by nav_circle_XY(), nav_route_xy(), and send_mode().
last_x
float last_x extern
Definition at line 47 of file nav.c.
Referenced by nav_gvf_survey_polygon_run(), nav_init_stage(), and nav_survey_polygon_run().
last_y
float last_y
Definition at line 64 of file nav.h.
nav_altitude
float nav_altitude
Definition at line 66 of file nav.h.
nav_circle_radians
float nav_circle_radians extern
Status on the current circle.
Definition at line 53 of file nav.c.
Referenced by nav_circle_XY(), and nav_init_stage().
nav_circle_radians_no_rewind
float nav_circle_radians_no_rewind extern
Definition at line 54 of file nav.c.
Referenced by nav_circle_XY(), and nav_init_stage().
nav_circle_radius
float nav_circle_radius
Definition at line 81 of file nav.h.
nav_circle_trigo_qdr
float nav_circle_trigo_qdr extern
Definition at line 55 of file nav.c.
Referenced by nav_circle_XY(), and nav_land_run().
nav_circle_x
float nav_circle_x extern
Definition at line 68 of file nav.c.
Referenced by flight_benchmark_periodic(), nav_circle_XY(), and send_circle().
nav_circle_y
float nav_circle_y
Definition at line 81 of file nav.h.
nav_climb
float nav_climb extern
Definition at line 56 of file nav.c.
nav_course
float nav_course extern
Definition at line 56 of file nav.c.
nav_glide_pitch_trim
float nav_glide_pitch_trim
Definition at line 66 of file nav.h.
nav_ground_speed_pgain
float nav_ground_speed_pgain extern
Definition at line 83 of file nav.c.
Referenced by nav_init().
nav_ground_speed_setpoint
float nav_ground_speed_setpoint
Definition at line 121 of file nav.h.
nav_in_circle
bool nav_in_circle extern
Definition at line 66 of file nav.c.
Referenced by calculate_wind_no_airspeed(), nav_circle_XY(), nav_init_stage(), nav_periodic_task(), nav_route_xy(), nav_survey_rectangle(), nav_survey_rectangle_rotorcraft_run(), and send_circle().
nav_in_segment
bool nav_in_segment extern
Definition at line 67 of file nav.c.
Referenced by nav_circle_XY(), nav_init_stage(), nav_route_xy(), nav_survey_rectangle(), nav_survey_rectangle_rotorcraft_run(), and send_segment().
nav_mode
int nav_mode extern
Definition at line 90 of file nav.c.
Referenced by fly_to_xy(), nav_circle_XY(), and nav_init().
nav_oval_count
uint8_t nav_oval_count extern
Navigation along a figure O.
One side leg is defined by waypoints [p1] and [p2]. The navigation goes through 4 states: OC1 (half circle next to [p1]), OR21 (route [p2] to [p1], OC2 (half circle next to [p2]) and OR12 (opposite leg).
Initial state is the route along the desired segment (OC2).
Definition at line 754 of file nav.c.
Referenced by nav_oval(), and nav_oval_init().
nav_pitch
float nav_pitch extern
Definition at line 310 of file nav.c.
Referenced by attitude_loop(), nav_home(), nav_without_gps(), v_ctl_climb_auto_throttle_loop(), v_ctl_climb_loop(), v_ctl_guidance_loop(), v_ctl_landing_loop(), and v_ctl_set_pitch().
nav_radius
float nav_radius extern
Definition at line 56 of file nav.c.
Referenced by nav_compute_baseleg(), nav_flower_run(), nav_init(), and parachute_compute_approach().
nav_segment_x_1
float nav_segment_x_1 extern
Definition at line 69 of file nav.c.
Referenced by flight_benchmark_periodic(), nav_route_xy(), and send_segment().
nav_segment_x_2
float nav_segment_x_2
Definition at line 82 of file nav.h.
nav_segment_y_1
float nav_segment_y_1
Definition at line 82 of file nav.h.
nav_segment_y_2
float nav_segment_y_2
Definition at line 82 of file nav.h.
nav_shift
float nav_shift extern
Definition at line 56 of file nav.c.
Referenced by nav_circle_XY(), nav_init_stage(), and nav_route_xy().
nav_survey_active
bool nav_survey_active extern
Definition at line 88 of file nav.c.
Referenced by nav_periodic_task(), nav_survey_rectangle(), and send_survey().
nav_survey_east
float nav_survey_east
Definition at line 125 of file nav.h.
nav_survey_north
float nav_survey_north
Definition at line 125 of file nav.h.
nav_survey_shift
float nav_survey_shift extern
Definition at line 86 of file nav.c.
Referenced by nav_init(), nav_survey_disc_run(), nav_survey_disc_setup(), nav_survey_poly_osam_run(), nav_survey_poly_run(), nav_survey_rectangle(), nav_survey_rectangle_init(), nav_survey_rectangle_rotorcraft_run(), and nav_survey_rectangle_rotorcraft_setup().
nav_survey_south
float nav_survey_south
Definition at line 125 of file nav.h.
nav_survey_west
float nav_survey_west extern
Definition at line 87 of file nav.c.
Referenced by nav_survey_rectangle(), nav_survey_rectangle_init(), nav_survey_rectangle_rotorcraft_run(), nav_survey_rectangle_rotorcraft_setup(), send_survey(), and send_survey().
nav_throttle_setpoint
pprz_t nav_throttle_setpoint extern
Definition at line 309 of file nav.c.
Referenced by attitude_loop(), nav_without_gps(), and v_ctl_guidance_loop().
oval_status
enum oval_status oval_status extern
Definition at line 45 of file nav.c.
rc_pitch
float rc_pitch extern
Definition at line 49 of file nav.c.