Paparazzi UAS: sw/airborne/modules/nav/nav_rover_base.h File Reference
nav_rover_base.h File Reference
#include "firmwares/rover/navigation.h"
Data Structures
struct RoverNavGoto
Waypoint and route pattern.
struct RoverNavCircle
Circle pattern.
struct RoverNavOval
struct RoverNavBase
Basic Nav struct.
Macros
#define ROVER_BASE_SEND_TRAJECTORY TRUE
#define NavCircleCount() (fabsf(nav_rover_base.circle.radians) / (2*M_PI))
Macros for circle nav.
#define NavCircleQdr() ({ float qdr = DegOfRad(M_PI_2 - nav_rover_base.circle.qdr); NormCourse(qdr); qdr; })
#define CloseDegAngles(_c1, _c2) ({ float _diff = _c1 - _c2; NormCourse(_diff); 350 < _diff || _diff < 10; })
#define CloseRadAngles(_c1, _c2) ({ float _diff = _c1 - _c2; NormRadAngle(_diff); fabsf(_diff) < 0.0177; })
#define NavQdrCloseTo(x) CloseDegAngles(x, NavCircleQdr())
True if x (in degrees) is close to the current QDR (less than 10 degrees)
#define NavCourseCloseTo(x) CloseDegAngles(x, DegOfRad(stateGetHorizontalSpeedDir_f()))
Enumerations
enum oval_status { OR12 , OC2 , OR21 , OC1 }
Oval pattern.
Functions
void nav_rover_init (void)
Init and register nav functions.
Variables
struct RoverNavBase nav_rover_base
Detailed Description
Author
2018 Gautier Hattenberger gauti.nosp@m.er.h.nosp@m.atten.nosp@m.berg.nosp@m.er@en.nosp@m.ac.f.nosp@m.r Basic navigation functions for Rovers
Definition in file nav_rover_base.h.
Data Structure Documentation
RoverNavGoto
struct RoverNavGoto
Waypoint and route pattern.
Definition at line 38 of file nav_rover_base.h.
Data Fields
float dist2_to_wp squared distance to next waypoint
struct EnuCoor_f from start WP position
float leg_length leg length
float leg_progress progress over leg
struct EnuCoor_f to end WP position
RoverNavCircle
struct RoverNavCircle
Circle pattern.
Definition at line 48 of file nav_rover_base.h.
Data Fields
struct EnuCoor_f center center WP position
float qdr qdr in radians
float radians incremental angular distance
float radius radius in meters
RoverNavOval
struct RoverNavOval
Definition at line 58 of file nav_rover_base.h.
Data Fields
uint8_t count number of laps
enum oval_status status oval status
RoverNavBase
struct RoverNavBase
Basic Nav struct.
Definition at line 65 of file nav_rover_base.h.
Data Fields
struct RoverNavCircle circle
struct RoverNavGoto goto_wp
struct RoverNavOval oval
Macro Definition Documentation
CloseDegAngles
#define CloseDegAngles (_c1, _c2) ({ float _diff = _c1 - _c2; NormCourse(_diff); 350 < _diff || _diff < 10; })
Definition at line 81 of file nav_rover_base.h.
CloseRadAngles
#define CloseRadAngles (_c1, _c2) ({ float _diff = _c1 - _c2; NormRadAngle(_diff); fabsf(_diff) < 0.0177; })
Definition at line 82 of file nav_rover_base.h.
NavCircleCount
#define NavCircleCount () (fabsf(nav_rover_base.circle.radians) / (2*M_PI))
Macros for circle nav.
Definition at line 78 of file nav_rover_base.h.
NavCircleQdr
#define NavCircleQdr () ({ float qdr = DegOfRad(M_PI_2 - nav_rover_base.circle.qdr); NormCourse(qdr); qdr; })
Definition at line 79 of file nav_rover_base.h.
NavCourseCloseTo
#define NavCourseCloseTo (x) CloseDegAngles(x, DegOfRad(stateGetHorizontalSpeedDir_f()))
Definition at line 87 of file nav_rover_base.h.
NavQdrCloseTo
#define NavQdrCloseTo (x) CloseDegAngles(x, NavCircleQdr())
True if x (in degrees) is close to the current QDR (less than 10 degrees)
Definition at line 86 of file nav_rover_base.h.
ROVER_BASE_SEND_TRAJECTORY
#define ROVER_BASE_SEND_TRAJECTORY TRUE
Definition at line 33 of file nav_rover_base.h.
Enumeration Type Documentation
oval_status
enum oval_status
Oval pattern.
Enumerator
OR12
OC2
OR21
OC1
Definition at line 57 of file nav_rover_base.h.
Function Documentation
nav_rover_init()
void nav_rover_init (void) extern
Init and register nav functions.
Definition at line 291 of file nav_rover_base.c.
References _nav_oval_init(), RoverNavBase::circle, DEFAULT_CIRCLE_RADIUS, DefaultPeriodic, foo, RoverNavBase::goto_wp, RoverNavGoto::leg_length, RoverNavGoto::leg_progress, nav_approaching(), nav_circle(), nav_goto(), nav_oval(), nav_register_circle(), nav_register_goto_wp(), nav_register_oval(), nav_register_stage_init(), nav_route(), nav_rover_base, nav_stage_init(), RoverNavCircle::radius, register_periodic_telemetry(), and send_nav_status().
Variable Documentation
nav_rover_base
struct RoverNavBase nav_rover_base extern
Definition at line 29 of file nav_rover_base.c.
Referenced by _nav_oval_init(), nav_circle(), nav_goto(), nav_oval(), nav_route(), nav_rover_init(), nav_stage_init(), and send_nav_status().