Paparazzi UAS: sw/airborne/modules/nav/nav_trinity.h File Reference
nav_trinity.h File Reference
#include "std.h"
#include "math/pprz_geodetic_float.h"
Functions
void nav_trinity_init (void)
Init function called by modules init.
void nav_trinity_setup (float init_x, float init_y, float init_z, int turn, float desired_radius, float vx, float vy, float vz)
Initialized the exploration with a first target point inside the cloud Called from flight plan or with mission parameters.
bool nav_trinity_run (void)
Navigation function Called by flight plan or mission run function.
Detailed Description
Author
Titouan Verdu Adaptative trinity pattern for cloud exploration.
Definition in file nav_trinity.h.
Function Documentation
nav_trinity_init()
void nav_trinity_init (void) extern
Init function called by modules init.
Definition at line 189 of file nav_trinity.c.
References DEFAULT_CIRCLE_RADIUS, foo, NavTrinity::inside_cloud, NavTrinity::last_border_time, lwc_cb(), lwc_ev, NavTrinity::max_recover_radius, mission_register(), nav_trinity, NAV_TRINITY_LWC_ID, NavTrinity::radius, NavTrinity::recover_radius, NavTrinity::status, and TRINITY_ENTER.
nav_trinity_run()
bool nav_trinity_run (void) extern
Navigation function Called by flight plan or mission run function.
Returns
true until pattern ends or fail
Definition at line 230 of file nav_trinity.c.
References NavTrinity::actual, change_rep(), NavTrinity::circle, NavTrinity::direction, NavTrinity::estim_border, foo, get_sys_time_float(), ground_alt, NavTrinity::inside_cloud, NavTrinity::last_border_time, NavTrinity::max_recover_radius, nav_circle_XY(), nav_dt, nav_init_stage(), nav_move_waypoint_enu(), nav_route_xy(), nav_send_waypoint(), nav_trinity, NAV_TRINITY_BORDER_FILTER, NAV_TRINITY_RECOVER_MAX_TURN, NavCircleCountNoRewind, NavVerticalAltitudeMode, NavVerticalAutoThrottleMode, NavTrinity::pos_incr, process_first_point_trinity(), process_new_point_trinity(), NavTrinity::radius, NavTrinity::radius_sign, NavTrinity::recover_circle, NavTrinity::recover_radius, stateGetHorizontalSpeedDir_f(), stateGetPositionEnu_f(), NavTrinity::status, NavTrinity::target, time, TRINITY_ENTER, TRINITY_INSIDE, TRINITY_INSIDE_FIRST, TRINITY_OUTSIDE, TRINITY_OUTSIDE_START, TRINITY_RECOVER_INSIDE, TRINITY_RECOVER_OUTSIDE, TRINITY_RECOVER_START, update_target_point(), VECT3_ADD, EnuCoor_f::x, EnuCoor_f::y, FloatVect3::z, and EnuCoor_f::z.
nav_trinity_setup()
void nav_trinity_setup (float init_x, float init_y, float init_z, int turn, float desired_radius, float vx, float vy, float vz) extern
Initialized the exploration with a first target point inside the cloud Called from flight plan or with mission parameters.
Definition at line 205 of file nav_trinity.c.
References NavTrinity::actual, foo, NavTrinity::inside_cloud, nav_dt, nav_trinity, NavTrinity::pos_incr, NavTrinity::radius, NavTrinity::radius_sign, NavTrinity::rotation, stateGetPositionEnu_f(), NavTrinity::status, NavTrinity::target, TRINITY_ENTER, TRINITY_LEFT, TRINITY_RIGHT, and VECT3_ASSIGN.