Paparazzi UAS: sw/airborne/modules/nav/nav_smooth.h File Reference
nav_smooth.h File Reference
Smooth navigation to wp_a along an arc (around wp_cd), a segment (from wp_rd to wp_ta) and a second arc (around wp_ca).
#include "std.h"
Functions
bool snav_init (uint8_t wp_a, float desired_course_rad, float radius)
bool snav_circle1 (void)
bool snav_route (void)
bool snav_circle2 (void)
bool snav_on_time (float radius)
Variables
float snav_desired_tow
Detailed Description
Smooth navigation to wp_a along an arc (around wp_cd), a segment (from wp_rd to wp_ta) and a second arc (around wp_ca).
Definition in file nav_smooth.h.
Function Documentation
snav_circle1()
bool snav_circle1 (void)
Definition at line 121 of file nav_smooth.c.
References d_radius, foo, nav_circle_XY(), NavQdrCloseTo, NavVerticalAltitudeMode, NavVerticalAutoThrottleMode, and qdr_td.
snav_circle2()
bool snav_circle2 (void)
Definition at line 140 of file nav_smooth.c.
References a_radius, foo, nav_circle_XY(), NavQdrCloseTo, NavVerticalAltitudeMode, NavVerticalAutoThrottleMode, and qdr_a.
snav_init()
bool snav_init (uint8_t wp_a, float desired_course_rad, float radius)
Definition at line 49 of file nav_smooth.c.
References point::a, a_radius, alpha, d_radius, foo, ground_speed_timer, qdr_a, qdr_td, Sign, stateGetHorizontalSpeedDir_f(), stateGetPositionEnu_f(), u_a_ca_x, u_a_ca_y, WaypointAlt, WaypointX, WaypointY, wp_a, wp_ta, EnuCoor_f::x, point::x, EnuCoor_f::y, and point::y.
snav_on_time()
bool snav_on_time (float radius)
Definition at line 183 of file nav_smooth.c.
References point::a, a_radius, ANGLE_STEP, compute_ground_speed(), foo, gps, ground_speed, ground_speed_of_course(), ground_speed_timer, nav_circle_XY(), NavVerticalAltitudeMode, NavVerticalAutoThrottleMode, Norm2Pi, qdr_a, Sign, snav_desired_tow, stateGetAirspeed_f(), stateGetHorizontalWindspeed_f(), stateGetPositionEnu_f(), GpsState::tow, u_a_ca_x, u_a_ca_y, WaypointX, WaypointY, wp_a, EnuCoor_f::x, point::x, EnuCoor_f::y, and point::y.
snav_route()
bool snav_route (void)
Definition at line 130 of file nav_smooth.c.
References CARROT, foo, nav_approaching_xy(), nav_route_xy(), NavVerticalAltitudeMode, NavVerticalAutoThrottleMode, wp_ta, point::x, and point::y.
Variable Documentation
snav_desired_tow
float snav_desired_tow extern
Definition at line 44 of file nav_smooth.c.
Referenced by snav_on_time().