Paparazzi UAS: sw/airborne/modules/nav/nav_flower.h File Reference
nav_flower.h File Reference
#include "std.h"
Functions
void nav_flower_init (void)
bool nav_flower_run (void)
void nav_flower_setup (uint8_t CenterWP, uint8_t EdgeWP)
Function Documentation
nav_flower_init()
void nav_flower_init (void) extern
Definition at line 53 of file nav_flower.c.
References foo, and mission_register().
nav_flower_run()
bool nav_flower_run (void) extern
Definition at line 115 of file nav_flower.c.
References Center, CFlowerStatus, Circle, CircleX, CircleY, DistanceFromCenter, Edge, EdgeCurrentX, EdgeCurrentY, FlowerLine, Flowerradius, FlowerTheta, Fly2X, Fly2Y, FlyFromX, FlyFromY, foo, nav_circle_XY(), nav_init_stage(), nav_radius, nav_route_xy(), NavVerticalAltitudeMode, NavVerticalAutoThrottleMode, Outside, stateGetPositionEnu_f(), TransCurrentX, TransCurrentY, waypoints, WaypointX, WaypointY, EnuCoor_f::x, and EnuCoor_f::y.
nav_flower_setup()
void nav_flower_setup (uint8_t CenterWP, uint8_t EdgeWP) extern
Definition at line 85 of file nav_flower.c.
References Center, CFlowerStatus, CircleX, CircleY, DistanceFromCenter, Edge, EdgeCurrentX, EdgeCurrentY, FlowerLine, Flowerradius, FlowerTheta, Fly2X, Fly2Y, FlyFromX, FlyFromY, foo, Outside, stateGetPositionEnu_f(), TransCurrentX, TransCurrentY, WaypointX, WaypointY, EnuCoor_f::x, and EnuCoor_f::y.