Paparazzi UAS: sw/airborne/modules/nav/nav_survey_rectangle_rotorcraft.h File Reference
nav_survey_rectangle_rotorcraft.h File Reference
Automatic survey of a rectangle for rotorcraft.
#include "firmwares/rotorcraft/navigation.h"
Macros
#define NavSurveyRectangleInit(_wp1, _wp2, _grid, _orientation) nav_survey_rectangle_rotorcraft_setup(_wp1, _wp2, _grid, _orientation)
#define NavSurveyRectangle(_wp1, _wp2) nav_survey_rectangle_rotorcraft_run(_wp1, _wp2)
Enumerations
enum survey_orientation_t { NS , WE }
Functions
void nav_survey_rectangle_rotorcraft_init (void)
void nav_survey_rectangle_rotorcraft_setup (uint8_t wp1, uint8_t wp2, float grid, survey_orientation_t so)
bool nav_survey_rectangle_rotorcraft_run (uint8_t wp1, uint8_t wp2)
Variables
float sweep
uint16_t rectangle_survey_sweep_num
bool interleave
Detailed Description
Automatic survey of a rectangle for rotorcraft.
Rectangle is defined by two points, sweep can be south-north or west-east.
Definition in file nav_survey_rectangle_rotorcraft.h.
Macro Definition Documentation
NavSurveyRectangle
#define NavSurveyRectangle (_wp1, _wp2) nav_survey_rectangle_rotorcraft_run(_wp1, _wp2)
Definition at line 48 of file nav_survey_rectangle_rotorcraft.h.
NavSurveyRectangleInit
#define NavSurveyRectangleInit (_wp1, _wp2, _grid, _orientation) nav_survey_rectangle_rotorcraft_setup(_wp1, _wp2, _grid, _orientation)
Definition at line 47 of file nav_survey_rectangle_rotorcraft.h.
Enumeration Type Documentation
survey_orientation_t
enum survey_orientation_t
Enumerator
NS
WE
Definition at line 36 of file nav_survey_rectangle_rotorcraft.h.
Function Documentation
nav_survey_rectangle_rotorcraft_init()
void nav_survey_rectangle_rotorcraft_init (void) extern
Definition at line 101 of file nav_survey_rectangle_rotorcraft.c.
References DefaultPeriodic, foo, register_periodic_telemetry(), and send_survey().
nav_survey_rectangle_rotorcraft_run()
bool nav_survey_rectangle_rotorcraft_run (uint8_t wp1, uint8_t wp2) extern
Do half a circle around WP 0
Do half a circle around WP 0
Definition at line 165 of file nav_survey_rectangle_rotorcraft.c.
References dc_distance_interval, dc_send_command(), DC_SHOOT, foo, interleave, LINE_START_FUNCTION, LINE_STOP_FUNCTION, Min, nav, RotorcraftNavigation::nav_approaching, nav_in_circle, nav_in_segment, RotorcraftNavigation::nav_route, nav_survey_east, nav_survey_north, nav_survey_rectangle_active, nav_survey_send, nav_survey_shift, nav_survey_south, nav_survey_west, NS, rectangle_survey_sweep_num, stateGetPositionEnu_f(), survey_from, survey_orientation, survey_to, survey_uturn, SurveyGoingEast, SurveyGoingNorth, SurveyGoingSouth, SurveyGoingWest, sweep, waypoints, WaypointX, WaypointY, WE, EnuCoor_f::x, point::x, EnuCoor_f::y, point::y, and EnuCoor_f::z.
nav_survey_rectangle_rotorcraft_setup()
void nav_survey_rectangle_rotorcraft_setup (uint8_t wp1, uint8_t wp2, float grid, survey_orientation_t so) extern
Definition at line 108 of file nav_survey_rectangle_rotorcraft.c.
References foo, RotorcraftNavigation::horizontal_mode, LINE_STOP_FUNCTION, Min, nav, NAV_HORIZONTAL_MODE_ROUTE, nav_set_heading_deg(), nav_survey_east, nav_survey_north, nav_survey_rectangle_active, nav_survey_shift, nav_survey_south, nav_survey_west, NavVerticalAltitudeMode, NS, RECTANGLE_SURVEY_HEADING_NS, RECTANGLE_SURVEY_HEADING_WE, rectangle_survey_sweep_num, stateGetPositionEnu_f(), survey_from, survey_orientation, survey_to, survey_uturn, sweep, RotorcraftNavigation::target, VECT3_COPY, waypoints, WaypointX, WaypointY, EnuCoor_f::x, point::x, EnuCoor_f::y, and point::y.
Variable Documentation
interleave
bool interleave extern
Definition at line 67 of file nav_survey_rectangle_rotorcraft.c.
Referenced by nav_survey_rectangle_rotorcraft_run().
rectangle_survey_sweep_num
uint16_t rectangle_survey_sweep_num extern
Definition at line 64 of file nav_survey_rectangle_rotorcraft.c.
Referenced by nav_survey_rectangle_rotorcraft_run(), and nav_survey_rectangle_rotorcraft_setup().
sweep
float sweep extern
Definition at line 62 of file nav_survey_rectangle_rotorcraft.c.
Referenced by nav_gvf_survey_polygon_setup(), nav_survey_hybrid_setup(), nav_survey_hybrid_setup_orientation(), nav_survey_hybrid_setup_towards(), nav_survey_polygon_setup(), nav_survey_rectangle_rotorcraft_run(), and nav_survey_rectangle_rotorcraft_setup().