Paparazzi UAS: sw/airborne/modules/nav/nav_lace.h File Reference
nav_lace.h File Reference
Adaptive border pattern for cloud exploration Can be used in mission mode with custom pattern and ID "LACE".
#include "std.h"
#include "math/pprz_geodetic_float.h"
Functions
void nav_lace_init (void)
Init function called by modules init.
void nav_lace_setup (float init_x, float init_y, float init_z, int turn, float desired_radius, float vx, float vy, float vz)
Initialized the exploration with a first target point inside the cloud Called from flight plan or with mission parameters.
bool nav_lace_run (void)
Navigation function Called by flight plan or mission run function.
Detailed Description
Adaptive border pattern for cloud exploration Can be used in mission mode with custom pattern and ID "LACE".
See: Titouan Verdu, Gautier Hattenberger, Simon Lacroix. Flight patterns for clouds exploration with a fleet of UAVs. 2019 International Conference on Unmanned Aircraft Systems (ICUAS 2019), Jul 2019, Atlanta, United States. https://hal-enac.archives-ouvertes.fr/hal-02137839
Definition in file nav_lace.h.
Function Documentation
nav_lace_init()
void nav_lace_init (void) extern
Init function called by modules init.
Definition at line 181 of file nav_lace.c.
References DEFAULT_CIRCLE_RADIUS, foo, NavLace::inside_cloud, LACE_ENTER, NavLace::last_border_time, lwc_cb(), lwc_ev, NavLace::max_recover_radius, mission_register(), nav_lace, NAV_LACE_LWC_ID, NavLace::radius, NavLace::recover_radius, and NavLace::status.
nav_lace_run()
bool nav_lace_run (void) extern
Navigation function Called by flight plan or mission run function.
Returns
true until pattern ends or fail
Definition at line 222 of file nav_lace.c.
References NavLace::actual, change_rep(), NavLace::circle, NavLace::direction, NavLace::estim_border, foo, get_sys_time_float(), ground_alt, NavLace::inside_cloud, LACE_ENTER, LACE_INSIDE, LACE_INSIDE_START, LACE_OUTSIDE, LACE_OUTSIDE_START, LACE_RECOVER_INSIDE, LACE_RECOVER_OUTSIDE, LACE_RECOVER_START, NavLace::last_border_time, NavLace::max_recover_radius, nav_circle_XY(), nav_dt, nav_init_stage(), nav_lace, NAV_LACE_BORDER_FILTER, NAV_LACE_RECOVER_MAX_TURN, nav_move_waypoint_enu(), nav_route_xy(), nav_send_waypoint(), NavCircleCountNoRewind, NavVerticalAltitudeMode, NavVerticalAutoThrottleMode, NavLace::pos_incr, process_new_point_lace(), NavLace::radius, NavLace::radius_sign, NavLace::recover_circle, NavLace::recover_radius, stateGetHorizontalSpeedDir_f(), stateGetPositionEnu_f(), NavLace::status, NavLace::target, time, update_target_point(), VECT3_ADD, EnuCoor_f::x, EnuCoor_f::y, FloatVect3::z, and EnuCoor_f::z.
nav_lace_setup()
void nav_lace_setup (float init_x, float init_y, float init_z, int turn, float desired_radius, float vx, float vy, float vz) extern
Initialized the exploration with a first target point inside the cloud Called from flight plan or with mission parameters.
Definition at line 197 of file nav_lace.c.
References NavLace::actual, foo, NavLace::inside_cloud, LACE_ENTER, LACE_LEFT, LACE_RIGHT, nav_dt, nav_lace, NavLace::pos_incr, NavLace::radius, NavLace::radius_sign, NavLace::rotation, stateGetPositionEnu_f(), NavLace::status, NavLace::target, and VECT3_ASSIGN.