Paparazzi UAS: sw/airborne/modules/nav/nav_spiral_3D.h File Reference
nav_spiral_3D.h File Reference
Fixedwing navigation in a 3D spiral.
#include "std.h"
#include "math/pprz_algebra_float.h"
Functions
void nav_spiral_3D_init (void)
bool nav_spiral_3D_run (void)
Run spiral 3D navigation.
void nav_spiral_3D_setup (float center_x, float center_y, float alt_start, float alt_stop, float radius_start, float radius_stop, float vx, float vy, float vz)
Initialize spiral 3D based on:
Detailed Description
Fixedwing navigation in a 3D spiral.
Definition in file nav_spiral_3D.h.
Function Documentation
nav_spiral_3D_init()
void nav_spiral_3D_init (void) extern
Definition at line 117 of file nav_spiral_3D.c.
References FLOAT_VECT3_ZERO, foo, mission_register(), nav_spiral_3D, and NavSpiral3D::pos_incr.
nav_spiral_3D_run()
bool nav_spiral_3D_run (void) extern
Run spiral 3D navigation.
Definition at line 185 of file nav_spiral_3D.c.
References NavSpiral3D::alt_start, NavSpiral3D::alt_stop, NavSpiral3D::center, float_vect2_norm(), foo, nav_circle_XY(), nav_dt, nav_spiral_3D, NAV_SPIRAL_3D_ALT_DIFF, NAV_SPIRAL_3D_DIST_DIFF, NavVerticalAltitudeMode, NavVerticalAutoThrottleMode, pos_diff, NavSpiral3D::pos_incr, NavSpiral3D::radius, NavSpiral3D::radius_increment, NavSpiral3D::radius_start, NavSpiral3D::radius_stop, Spiral3DCircle, Spiral3DFail, Spiral3DStart, stateGetPositionEnu_f(), stateGetPositionUtm_f(), NavSpiral3D::status, VECT2_DIFF, VECT3_ADD, FloatVect3::x, FloatVect3::y, and FloatVect3::z.
nav_spiral_3D_setup()
void nav_spiral_3D_setup (float center_x, float center_y, float alt_start, float alt_stop, float radius_start, float radius_stop, float vx, float vy, float vz) extern
Initialize spiral 3D based on:
position X, Y
start and stop altitude
start and stop radius
speeds (horizontal and vertical)
Definition at line 127 of file nav_spiral_3D.c.
References NavSpiral3D::alt_start, NavSpiral3D::alt_stop, NavSpiral3D::center, foo, nav_dt, nav_spiral_3D, NAV_SPIRAL_3D_MIN_CIRCLE_RADIUS, NavSpiral3D::pos_incr, NavSpiral3D::radius, NavSpiral3D::radius_increment, NavSpiral3D::radius_min, NavSpiral3D::radius_start, NavSpiral3D::radius_stop, sign(), Spiral3DFail, Spiral3DStart, NavSpiral3D::status, VECT3_ASSIGN, and FloatVect3::z.