Paparazzi UAS: sw/airborne/modules/nav/nav_survey_zamboni.c File Reference
nav_survey_zamboni.c File Reference
Zamboni pattern survey for fixedwings.
#include "modules/nav/nav_survey_zamboni.h"
#include "firmwares/fixedwing/nav.h"
#include "autopilot.h"
#include "generated/flight_plan.h"
Macros
#define LINE_START_FUNCTION {}
#define LINE_STOP_FUNCTION {}
Functions
void nav_survey_zamboni_setup (uint8_t center_wp, uint8_t dir_wp, float sweep_length, float sweep_spacing, int sweep_lines, float altitude)
initializes the variables needed for the survey to start.
bool nav_survey_zamboni_run (void)
main navigation routine.
Variables
struct ZamboniSurvey zs
Detailed Description
Zamboni pattern survey for fixedwings.
Definition in file nav_survey_zamboni.c.
Macro Definition Documentation
LINE_START_FUNCTION
#define LINE_START_FUNCTION {}
Definition at line 39 of file nav_survey_zamboni.c.
LINE_STOP_FUNCTION
#define LINE_STOP_FUNCTION {}
Definition at line 42 of file nav_survey_zamboni.c.
Function Documentation
nav_survey_zamboni_run()
bool nav_survey_zamboni_run (void)
main navigation routine.
This is called periodically evaluates the current Position and stage and navigates accordingly.
Returns
TRUE until the survey is finished
Definition at line 129 of file nav_survey_zamboni.c.
References ZamboniSurvey::altitude, CARROT, ZamboniSurvey::current_laps, ZamboniSurvey::flight_angle, LINE_START_FUNCTION, LINE_STOP_FUNCTION, nav_approaching_xy(), nav_circle_XY(), nav_init_stage(), nav_route_xy(), NavCourseCloseTo, NavVerticalAltitudeMode, NavVerticalAutoThrottleMode, ZamboniSurvey::pre_leave_angle, ZamboniSurvey::ret_end, ZamboniSurvey::ret_start, ZamboniSurvey::return_angle, ZamboniSurvey::seg_end, ZamboniSurvey::seg_start, ZamboniSurvey::stage, ZamboniSurvey::sweep_width, ZamboniSurvey::total_laps, ZamboniSurvey::turn_center1, ZamboniSurvey::turn_center2, ZamboniSurvey::turnradius1, ZamboniSurvey::turnradius2, VECT2_ADD, ZamboniSurvey::wp_center, FloatVect2::x, FloatVect2::y, Z_ENTRY, Z_RET, Z_SEG, Z_TURN1, Z_TURN2, and zs.
nav_survey_zamboni_setup()
void nav_survey_zamboni_setup (uint8_t center_wp, uint8_t dir_wp, float sweep_length, float sweep_spacing, int sweep_lines, float altitude)
initializes the variables needed for the survey to start.
Parameters
center_wp the waypoint defining the center of the survey-rectangle
dir_wp the waypoint defining the orientation of the survey-rectangle
sweep_length the length of the survey-rectangle
sweep_spacing distance between the sweeps
sweep_lines number of sweep_lines to fly
altitude the altitude that must be reached before the flyover starts
Definition at line 57 of file nav_survey_zamboni.c.
References ZamboniSurvey::altitude, altitude, ZamboniSurvey::current_laps, ZamboniSurvey::flight_angle, FLOAT_VECT2_NORMALIZE, foo, NavVerticalAltitudeMode, NavVerticalAutoThrottleMode, ZamboniSurvey::pre_leave_angle, ZamboniSurvey::ret_end, ZamboniSurvey::ret_start, ZamboniSurvey::return_angle, ZamboniSurvey::seg_end, ZamboniSurvey::seg_start, ZamboniSurvey::stage, ZamboniSurvey::sweep_width, ZamboniSurvey::total_laps, ZamboniSurvey::turn_center1, ZamboniSurvey::turn_center2, ZamboniSurvey::turnradius1, ZamboniSurvey::turnradius2, VECT2_COPY, VECT2_DIFF, VECT2_SMUL, VECT2_SUM, waypoints, ZamboniSurvey::wp_center, ZamboniSurvey::wp_dir, FloatVect2::x, FloatVect2::y, Z_ENTRY, and zs.
Variable Documentation
zs
struct ZamboniSurvey zs
Definition at line 45 of file nav_survey_zamboni.c.
Referenced by nav_survey_zamboni_run(), and nav_survey_zamboni_setup().