Paparazzi UAS: sw/airborne/modules/nav/nav_rotorcraft_base.h File Reference
nav_rotorcraft_base.h File Reference
#include "modules/nav/nav_base.h"
Macros
#define ROTORCRAFT_BASE_SEND_TRAJECTORY TRUE
#define NavCircleCount() nav_circle_get_count(&nav_rotorcraft_base.circle)
Macros for circle and oval nav.
#define NavCircleQdr() nav_circle_qdr(&nav_rotorcraft_base.circle)
#define NavOvalCount nav_rotorcraft_base.oval.count
#define NavQdrCloseTo(x) CloseDegAngles(x, NavCircleQdr())
True if x (in degrees) is close to the current QDR (less than 10 degrees)
#define NavCourseCloseTo(x) CloseDegAngles(x, DegOfRad(stateGetHorizontalSpeedDir_f()))
Functions
void nav_rotorcraft_init (void)
Init and register nav functions.
Variables
struct NavBase_t nav_rotorcraft_base
Basic Nav struct.
Detailed Description
Author
2018 Gautier Hattenberger gauti.nosp@m.er.h.nosp@m.atten.nosp@m.berg.nosp@m.er@en.nosp@m.ac.f.nosp@m.r Basic navigation functions for Rotorcraft
Definition in file nav_rotorcraft_base.h.
Macro Definition Documentation
NavCircleCount
#define NavCircleCount () nav_circle_get_count(&nav_rotorcraft_base.circle)
Macros for circle and oval nav.
Definition at line 45 of file nav_rotorcraft_base.h.
NavCircleQdr
#define NavCircleQdr () nav_circle_qdr(&nav_rotorcraft_base.circle)
Definition at line 46 of file nav_rotorcraft_base.h.
NavCourseCloseTo
#define NavCourseCloseTo (x) CloseDegAngles(x, DegOfRad(stateGetHorizontalSpeedDir_f()))
Definition at line 52 of file nav_rotorcraft_base.h.
NavOvalCount
#define NavOvalCount nav_rotorcraft_base.oval.count
Definition at line 47 of file nav_rotorcraft_base.h.
NavQdrCloseTo
#define NavQdrCloseTo (x) CloseDegAngles(x, NavCircleQdr())
True if x (in degrees) is close to the current QDR (less than 10 degrees)
Definition at line 51 of file nav_rotorcraft_base.h.
ROTORCRAFT_BASE_SEND_TRAJECTORY
#define ROTORCRAFT_BASE_SEND_TRAJECTORY TRUE
Definition at line 33 of file nav_rotorcraft_base.h.
Function Documentation
nav_rotorcraft_init()
void nav_rotorcraft_init (void) extern
Init and register nav functions.
Definition at line 302 of file nav_rotorcraft_base.c.
References _nav_oval_init(), NavBase_t::circle, DEFAULT_CIRCLE_RADIUS, DefaultPeriodic, foo, NavBase_t::goto_wp, NavGoto_t::leg_length, NavGoto_t::leg_progress, nav_approaching(), nav_circle(), nav_goto(), nav_oval(), nav_register_circle(), nav_register_goto_wp(), nav_register_oval(), nav_register_stage_init(), nav_rotorcraft_base, nav_route(), nav_stage_init(), NavCircle_t::radius, register_periodic_telemetry(), and send_nav_status().
Variable Documentation
nav_rotorcraft_base
struct NavBase_t nav_rotorcraft_base extern
Basic Nav struct.
Definition at line 31 of file nav_rotorcraft_base.c.
Referenced by _nav_oval_init(), airspeed_consistency_periodic(), nav_circle(), nav_goto(), nav_hybrid_circle(), nav_hybrid_goto(), nav_hybrid_route(), nav_oval(), nav_rotorcraft_hybrid_init(), nav_rotorcraft_init(), nav_route(), nav_stage_init(), and send_nav_status().