Paparazzi UAS: sw/airborne/modules/nav/nav_line_osam.h File Reference
nav_line_osam.h File Reference
#include "std.h"
Functions
bool nav_line_osam_run (uint8_t From_WP, uint8_t To_WP, float radius, float Space_Before, float Space_After)
bool nav_line_osam_block_run (uint8_t First_WP, uint8_t Last_WP, float radius, float Space_Before, float Space_After)
Function Documentation
nav_line_osam_block_run()
bool nav_line_osam_block_run (uint8_t First_WP, uint8_t Last_WP, float radius, float Space_Before, float Space_After) extern
Definition at line 176 of file nav_line_osam.c.
References CFLStatus, FLBlockCount, FLInitialize, foo, and nav_line_osam_run().
nav_line_osam_run()
bool nav_line_osam_run (uint8_t From_WP, uint8_t To_WP, float radius, float Space_Before, float Space_After) extern
Definition at line 71 of file nav_line_osam.c.
References CFLStatus, FLCircle, FLCircleS, FLFinished, FLFROMWP, FLInitialize, FLLine, FLQDR, FLRadius, FLTOWP, foo, LINE_START_FUNCTION, LINE_STOP_FUNCTION, nav_approaching_xy(), nav_circle_XY(), nav_init_stage(), nav_route_xy(), NavCircleCount, NavQdrCloseTo, NavVerticalAltitudeMode, NavVerticalAutoThrottleMode, P, stateGetPositionEnu_f(), TranslateAndRotateFromWorld(), waypoints, WaypointX, WaypointY, EnuCoor_f::x, Point2D::x, EnuCoor_f::y, and Point2D::y.
Referenced by nav_line_osam_block_run().