Paparazzi UAS: sw/airborne/modules/nav/nav_spiral.h File Reference
nav_spiral.h File Reference
Fixedwing navigation in a spiral/helix.
#include "std.h"
#include "math/pprz_algebra_float.h"
Data Structures
struct NavSpiral
Enumerations
enum SpiralStatus { SpiralOutside , SpiralStartCircle , SpiralCircle , SpiralInc }
Functions
bool nav_spiral_run (void)
void nav_spiral_setup (uint8_t center_wp, uint8_t edge_wp, float radius_start, float radius_inc, float segments)
Variables
struct NavSpiral nav_spiral
Detailed Description
Fixedwing navigation in a spiral/helix.
Definition in file nav_spiral.h.
Data Structure Documentation
NavSpiral
struct NavSpiral
Definition at line 37 of file nav_spiral.h.
Data Fields
float alpha_limit
struct FloatVect3 center
float dist_from_center
struct FloatVect2 fly_from
struct FloatVect2 last_circle
float radius
float radius_increment
float radius_min
float radius_start
float segments
enum SpiralStatus status
struct FloatVect3 trans_current
Enumeration Type Documentation
SpiralStatus
enum SpiralStatus
Enumerator
SpiralOutside
SpiralStartCircle
SpiralCircle
SpiralInc
Definition at line 35 of file nav_spiral.h.
Function Documentation
nav_spiral_run()
bool nav_spiral_run (void) extern
Definition at line 86 of file nav_spiral.c.
References NavSpiral::alpha_limit, UtmCoor_f::alt, NavSpiral::center, dc_cam_angle, dc_cam_tracing, dc_Circle, dc_send_command(), DC_SHOOT, dc_stop(), NavSpiral::dist_from_center, float_vect2_norm(), FLOAT_VECT3_NORM, NavSpiral::fly_from, foo, NavSpiral::last_circle, nav_approaching_xy(), nav_circle_XY(), nav_route_xy(), nav_spiral, NavVerticalAltitudeMode, NavVerticalAutoThrottleMode, pos_diff, NavSpiral::radius, NavSpiral::radius_increment, NavSpiral::radius_start, NavSpiral::segments, SpiralCircle, SpiralInc, SpiralOutside, SpiralStartCircle, stateGetPositionEnu_f(), stateGetPositionUtm_f(), NavSpiral::status, NavSpiral::trans_current, VECT2_COPY, VECT2_DIFF, FloatVect2::x, FloatVect3::x, FloatVect2::y, FloatVect3::y, and FloatVect3::z.
nav_spiral_setup()
void nav_spiral_setup (uint8_t center_wp, uint8_t edge_wp, float radius_start, float radius_inc, float segments) extern
Definition at line 50 of file nav_spiral.c.
References point::a, NavSpiral::alpha_limit, UtmCoor_f::alt, NavSpiral::center, NavSpiral::dist_from_center, float_vect2_norm(), FLOAT_VECT3_NORM, NavSpiral::fly_from, foo, nav_spiral, NAV_SPIRAL_MIN_CIRCLE_RADIUS, NavSpiral::radius, NavSpiral::radius_increment, NavSpiral::radius_min, NavSpiral::radius_start, NavSpiral::segments, SpiralOutside, stateGetPositionEnu_f(), stateGetPositionUtm_f(), NavSpiral::status, NavSpiral::trans_current, VECT2_COPY, VECT2_DIFF, waypoints, FloatVect2::x, EnuCoor_f::x, FloatVect2::y, EnuCoor_f::y, and FloatVect3::z.
Variable Documentation
nav_spiral
struct NavSpiral nav_spiral extern
Definition at line 48 of file nav_spiral.c.
Referenced by nav_spiral_run(), and nav_spiral_setup().