Paparazzi UAS: sw/airborne/modules/nav/nav_fish.h File Reference
nav_fish.h File Reference
#include "std.h"
Data Structures
struct NavFishParams
nav fish param structure
Functions
void nav_fish_init (void)
nav fish init
bool nav_fish_velocity_run (void)
nav fish velocity run
Variables
struct NavFishParams nav_fish_params
Detailed Description
Author
Adjiri Adam adam..nosp@m.adji.nosp@m.ri@et.nosp@m.u.is.nosp@m.ae-en.nosp@m.sma..nosp@m.fr Bio-inspired swarm navigation
Definition in file nav_fish.h.
Data Structure Documentation
NavFishParams
struct NavFishParams
nav fish param structure
Definition at line 35 of file nav_fish.h.
Data Fields
float alpha random fluctuation reduction to wall
float alpha_rep intensity of repulsion
float alt flight altitude
float d0_ali alignement balance distance
float d0_att attraction balance distance
float e_w1 wall interaction's first coefficient
float e_w2 wall interaction's first coefficient
float fluct random fluctuation intensity
float l_ali alignement distance
float l_att attraction distance
float l_w wall interaction distance
float max_velocity max velocity allowed
float min_d2d minimum distance between two drones
float min_velocity minimum velocity when facing obstacles
uint8_t strategy strategy for choosing focal uav : 0 for closest uav , 1 for most influential uav
float tr_l_ali alignement distance to trajectory intensity
float tr_l_att attraction distance to trajectory intensity
float tr_y_ali alignement to trajectory intensity
float tr_y_att attraction to trajectory intensity
float y_ali alignement intensity
float y_att attraction intensity
float y_w wall interaction intensity
Function Documentation
nav_fish_init()
void nav_fish_init (void) extern
nav fish init
nav fish init
Definition at line 175 of file nav_fish.c.
References NavFishParams::alpha, NavFishParams::alpha_rep, NavFishParams::alt, NavFishParams::d0_ali, NavFishParams::d0_att, NavFishParams::e_w1, NavFishParams::e_w2, NavFish::f_ali, NavFish::f_att, NavFish::f_fluct, NavFish::f_w, NavFish::f_wall, NavFishParams::fluct, NavFish::heading, NavFishParams::l_ali, NavFishParams::l_att, NavFishParams::l_w, NavFishParams::max_velocity, NavFishParams::min_d2d, NavFishParams::min_velocity, nav_fish, NAV_FISH_ALPHA, NAV_FISH_ALPHA_REP, NAV_FISH_ALT, NAV_FISH_BODY_LENGTH, NAV_FISH_D0ALI, NAV_FISH_D0ATT, NAV_FISH_EW1, NAV_FISH_EW2, NAV_FISH_FLUCT, NAV_FISH_LALI, NAV_FISH_LATT, NAV_FISH_LW, NAV_FISH_MAXVELOCITY, NAV_FISH_MIND2D, NAV_FISH_MINVELOCITY, nav_fish_params, NAV_FISH_STRATEGY, NAV_FISH_TRLALI, NAV_FISH_TRLATT, NAV_FISH_TRYALI, NAV_FISH_TRYATT, NAV_FISH_YALI, NAV_FISH_YATT, NAV_FISH_YW, NavFish::r_w, NavFish::step_size, NavFishParams::strategy, NavFish::theta_w, NavFishParams::tr_l_ali, NavFishParams::tr_l_att, NavFishParams::tr_y_ali, NavFishParams::tr_y_att, NavFish::velocity, NavFishParams::y_ali, NavFishParams::y_att, and NavFishParams::y_w.
nav_fish_velocity_run()
bool nav_fish_velocity_run (void) extern
nav fish velocity run
nav fish velocity run
Returns
true
Definition at line 487 of file nav_fish.c.
References autopilot_guided_update(), calculate_new_heading(), counter, NavFish::f_w, FLOAT_ANGLE_NORMALIZE, foo, GUIDED_FLAG_XY_BODY, GUIDED_FLAG_XY_VEL, NavFish::heading, nav_fish, new_heading, nfp, PRESCALE, send_swarm_message(), and NavFish::velocity.
Variable Documentation
nav_fish_params
struct NavFishParams nav_fish_params extern
Definition at line 153 of file nav_fish.c.
Referenced by nav_fish_init().