Paparazzi UAS: sw/airborne/modules/guidance/gvf/nav/nav_sin.c File Reference
nav_sin.c File Reference
#include "nav_sin.h"
#include "generated/airframe.h"
#include "modules/guidance/gvf/gvf.h"
Macros
#define GVF_SIN_KE 1
#define GVF_SIN_KN 1
#define GVF_SIN_ALPHA 0
#define GVF_SIN_W 0
#define GVF_SIN_OFF 0
#define GVF_SIN_A 0
Functions
bool nav_gvf_sin_XY_alpha (float a, float b, float alpha, float w, float off, float A)
bool nav_gvf_sin_wp1_wp2 (uint8_t wp1, uint8_t wp2, float w, float off, float A)
bool nav_gvf_sin_wp_alpha (uint8_t wp, float alpha, float w, float off, float A)
Variables
gvf_s_par gvf_sin_par
static int gvf_p_len_wps = 0
Macro Definition Documentation
GVF_SIN_A
#define GVF_SIN_A 0
Default amplitude for the sin trajectory in meters
Definition at line 55 of file nav_sin.c.
GVF_SIN_ALPHA
#define GVF_SIN_ALPHA 0
Default orientation in rads for the sin trajectory function gvf_sin_**_alpha
Definition at line 40 of file nav_sin.c.
GVF_SIN_KE
#define GVF_SIN_KE 1
Default gain ke for the sin trajectory
Definition at line 30 of file nav_sin.c.
GVF_SIN_KN
#define GVF_SIN_KN 1
Default gain kn for the sin trajectory
Definition at line 35 of file nav_sin.c.
GVF_SIN_OFF
#define GVF_SIN_OFF 0
Default off-set in rads for the sin trajectory in rads
Definition at line 50 of file nav_sin.c.
GVF_SIN_W
#define GVF_SIN_W 0
Default frequency for the sin trajectory in rads
Definition at line 45 of file nav_sin.c.
Function Documentation
nav_gvf_sin_wp1_wp2()
bool nav_gvf_sin_wp1_wp2 (uint8_t wp1, uint8_t wp2, float w, float off, float A)
Definition at line 94 of file nav_sin.c.
References A, alpha, foo, gvf_p_len_wps, gvf_trajectory, nav_gvf_sin_XY_alpha(), gvf_tra::p, WaypointX, and WaypointY.
nav_gvf_sin_wp_alpha()
bool nav_gvf_sin_wp_alpha (uint8_t wp, float alpha, float w, float off, float A)
Definition at line 117 of file nav_sin.c.
References A, alpha, foo, gvf_p_len_wps, gvf_trajectory, nav_gvf_sin_XY_alpha(), gvf_tra::p, WaypointX, and WaypointY.
nav_gvf_sin_XY_alpha()
bool nav_gvf_sin_XY_alpha (float a, float b, float alpha, float w, float off, float A)
Definition at line 69 of file nav_sin.c.
References A, alpha, b, gvf_con::error, foo, gvf_control, gvf_control_2D(), gvf_p_len_wps, gvf_sin_info(), gvf_sin_par, gvf_trajectory, gvf_con::ke, gvf_s_par::ke, gvf_s_par::kn, gvf_tra::p, gvf_tra::p_len, and gvf_tra::type.
Referenced by nav_gvf_sin_wp1_wp2(), and nav_gvf_sin_wp_alpha().
Variable Documentation
gvf_p_len_wps
int gvf_p_len_wps = 0 static
Definition at line 63 of file nav_sin.c.
Referenced by nav_gvf_ik_sin_wp1_wp2(), nav_gvf_ik_sin_wp_alpha(), nav_gvf_ik_sin_XY_alpha(), nav_gvf_sin_wp1_wp2(), nav_gvf_sin_wp_alpha(), and nav_gvf_sin_XY_alpha().
gvf_sin_par
gvf_s_par gvf_sin_par
Initial value:
= {GVF_SIN_KE, GVF_SIN_KN,
                         GVF_SIN_ALPHA, GVF_SIN_W, GVF_SIN_OFF, GVF_SIN_A
                        }
Definition at line 58 of file nav_sin.c.
Referenced by nav_gvf_sin_XY_alpha().