Paparazzi UAS: sw/airborne/modules/nav/nav_vertical_raster.h File Reference
nav_vertical_raster.h File Reference
#include "std.h"
Functions
void nav_vertical_raster_setup (void)
bool nav_vertical_raster_run (uint8_t wp1, uint8_t wp2, float radius, float AltSweep)
Function Documentation
nav_vertical_raster_run()
bool nav_vertical_raster_run (uint8_t wp1, uint8_t wp2, float radius, float AltSweep) extern
Definition at line 48 of file nav_vertical_raster.c.
References point::a, CARROT, foo, LQC11, LQC12, LQC21, LQC22, LR12, LR21, LTC1, LTC2, nav_circle_XY(), nav_init_stage(), NavApproachingFrom, NavQdrCloseTo, NavSegment, NavVerticalAltitudeMode, NavVerticalAutoThrottleMode, stateGetPositionUtm_f(), WaypointAlt, waypoints, WaypointX, and WaypointY.
nav_vertical_raster_setup()
void nav_vertical_raster_setup (void) extern
Definition at line 43 of file nav_vertical_raster.c.
References LR12.