Paparazzi UAS: sw/airborne/modules/nav/nav_rosette.h File Reference
nav_rosette.h File Reference
Adaptive flower pattern for cloud exploration Can be used in mission mode with custom pattern and ID "RSTT".
#include "std.h"
#include "math/pprz_geodetic_float.h"
Functions
void nav_rosette_init (void)
Init function called by modules init.
void nav_rosette_setup (float init_x, float init_y, float init_z, int turn, float desired_radius, float vx, float vy, float vz)
Initialized the exploration with a first target point inside the cloud Called from flight plan or with mission parameters.
bool nav_rosette_run (void)
Navigation function Called by flight plan or mission run function.
Detailed Description
Adaptive flower pattern for cloud exploration Can be used in mission mode with custom pattern and ID "RSTT".
See: Titouan Verdu, Gautier Hattenberger, Simon Lacroix. Flight patterns for clouds exploration with a fleet of UAVs. 2019 International Conference on Unmanned Aircraft Systems (ICUAS 2019), Jul 2019, Atlanta, United States. https://hal-enac.archives-ouvertes.fr/hal-02137839
Definition in file nav_rosette.h.
Function Documentation
nav_rosette_init()
void nav_rosette_init (void) extern
Init function called by modules init.
Definition at line 191 of file nav_rosette.c.
References DEFAULT_CIRCLE_RADIUS, foo, NavRosette::inside_cloud, NavRosette::last_border_time, lwc_cb(), lwc_ev, NavRosette::max_recover_radius, mission_register(), nav_rosette, NAV_ROSETTE_LWC_ID, NavRosette::radius, NavRosette::recover_radius, RSTT_ENTER, and NavRosette::status.
nav_rosette_run()
bool nav_rosette_run (void) extern
Navigation function Called by flight plan or mission run function.
Returns
true until pattern ends or fail
Definition at line 233 of file nav_rosette.c.
References NavRosette::actual, change_rep(), NavRosette::circle, NavRosette::direction, NavRosette::estim_border, NavRosette::first, foo, get_sys_time_float(), ground_alt, NavRosette::inside_cloud, NavRosette::last_border_time, NavRosette::max_recover_radius, nav_circle_XY(), nav_dt, nav_init_stage(), nav_move_waypoint_enu(), nav_rosette, NAV_ROSETTE_BORDER_FILTER, NAV_ROSETTE_RECOVER_MAX_TURN, nav_route_xy(), nav_send_waypoint(), NavCircleCountNoRewind, NavVerticalAltitudeMode, NavVerticalAutoThrottleMode, NavRosette::pos_incr, process_new_point_rosette(), NavRosette::radius, NavRosette::radius_sign, NavRosette::recover_circle, NavRosette::recover_radius, RSTT_CROSSING, RSTT_CROSSING_FIRST, RSTT_CROSSING_START, RSTT_ENTER, RSTT_RECOVER_OUTSIDE, RSTT_RECOVER_START, RSTT_TURNING, RSTT_TURNING_START, stateGetHorizontalSpeedDir_f(), stateGetPositionEnu_f(), NavRosette::status, NavRosette::target, time, update_barycenter(), VECT3_ADD, EnuCoor_f::x, EnuCoor_f::y, FloatVect3::z, and EnuCoor_f::z.
nav_rosette_setup()
void nav_rosette_setup (float init_x, float init_y, float init_z, int turn, float desired_radius, float vx, float vy, float vz) extern
Initialized the exploration with a first target point inside the cloud Called from flight plan or with mission parameters.
Definition at line 207 of file nav_rosette.c.
References NavRosette::actual, NavRosette::first, foo, get_sys_time_float(), NavRosette::inside_cloud, NavRosette::last_border_time, nav_dt, nav_rosette, NavRosette::pos_incr, NavRosette::radius, NavRosette::radius_sign, NavRosette::rotation, RSTT_ENTER, RSTT_LEFT, RSTT_RIGHT, stateGetPositionEnu_f(), NavRosette::status, NavRosette::target, and VECT3_ASSIGN.