Paparazzi UAS: sw/airborne/modules/guidance/gvf_parametric/nav/nav_parametric_2d_bezier_splines.c File Reference
nav_parametric_2d_bezier_splines.c File Reference
#include "nav_parametric_2d_bezier_splines.h"
#include "modules/guidance/gvf_parametric/gvf_parametric.h"
Macros
#define GVF_PARAMETRIC_2D_BEZIER_SPLINES_KX 2.0
#define GVF_PARAMETRIC_2D_BEZIER_SPLINES_KY 2.0
Functions
static void create_bezier_spline (bezier_t *bezier, float *px, float *py)
bool nav_gvf_parametric_2D_bezier_run (void)
bool nav_gvf_parametric_2D_bezier_wp (uint8_t first_wp)
Variables
gvf_par_2d_bezier_par gvf_parametric_2d_bezier_par
bezier_t gvf_bezier_2D [GVF_PARAMETRIC_2D_BEZIER_N_SEG]
Macro Definition Documentation
GVF_PARAMETRIC_2D_BEZIER_SPLINES_KX
#define GVF_PARAMETRIC_2D_BEZIER_SPLINES_KX 2.0
Definition at line 25 of file nav_parametric_2d_bezier_splines.c.
GVF_PARAMETRIC_2D_BEZIER_SPLINES_KY
#define GVF_PARAMETRIC_2D_BEZIER_SPLINES_KY 2.0
Definition at line 29 of file nav_parametric_2d_bezier_splines.c.
Function Documentation
create_bezier_spline()
static void create_bezier_spline (bezier_t * bezier, float * px, float * py) static
Definition at line 41 of file nav_parametric_2d_bezier_splines.c.
References foo, GVF_PARAMETRIC_2D_BEZIER_N_SEG, and bezier_t::p0.
Referenced by nav_gvf_parametric_2D_bezier_wp().
nav_gvf_parametric_2D_bezier_run()
bool nav_gvf_parametric_2D_bezier_run (void)
Definition at line 64 of file nav_parametric_2d_bezier_splines.c.
References BEZIER_2D, foo, gvf_bezier_2D, gvf_parametric_2d_bezier_par, gvf_parametric_2d_bezier_splines_info(), gvf_parametric_control, gvf_parametric_control_2D(), gvf_parametric_trajectory, gvf_par_2d_bezier_par::kx, gvf_par_2d_bezier_par::ky, gvf_parametric_tra::type, and gvf_parametric_con::w.
Referenced by nav_gvf_parametric_2D_bezier_wp().
nav_gvf_parametric_2D_bezier_wp()
bool nav_gvf_parametric_2D_bezier_wp (uint8_t first_wp)
Definition at line 77 of file nav_parametric_2d_bezier_splines.c.
References gvf_parametric_con::beta, create_bezier_spline(), foo, gvf_bezier_2D, GVF_PARAMETRIC_2D_BEZIER_N_SEG, gvf_parametric_2d_bezier_par, gvf_parametric_control, gvf_parametric_telemetry, gvf_parametric_trajectory, gvf_par_2d_bezier_par::kx, gvf_par_2d_bezier_par::ky, nav_gvf_parametric_2D_bezier_run(), gvf_parametric_tra::p_len, gvf_parametric_tra::p_parametric, gvf_parametric_tel::splines_ctr, gvf_parametric_con::w, WaypointX, and WaypointY.
Variable Documentation
gvf_bezier_2D
bezier_t gvf_bezier_2D[GVF_PARAMETRIC_2D_BEZIER_N_SEG]
Definition at line 36 of file nav_parametric_2d_bezier_splines.c.
Referenced by nav_gvf_parametric_2D_bezier_run(), and nav_gvf_parametric_2D_bezier_wp().
gvf_parametric_2d_bezier_par
gvf_par_2d_bezier_par gvf_parametric_2d_bezier_par
Initial value:
= {
  GVF_PARAMETRIC_2D_BEZIER_SPLINES_KX, GVF_PARAMETRIC_2D_BEZIER_SPLINES_KY
}
Definition at line 32 of file nav_parametric_2d_bezier_splines.c.
Referenced by nav_gvf_parametric_2D_bezier_run(), and nav_gvf_parametric_2D_bezier_wp().