Paparazzi UAS: sw/airborne/modules/guidance/gvf/nav/nav_ellipse.c File Reference
nav_ellipse.c File Reference
#include "nav_ellipse.h"
#include "generated/airframe.h"
#include "modules/guidance/gvf/gvf.h"
Macros
#define GVF_ELLIPSE_KE 1
#define GVF_ELLIPSE_KN 1
#define GVF_ELLIPSE_A 80
#define GVF_ELLIPSE_B 80
#define GVF_ELLIPSE_ALPHA 0
Functions
bool nav_gvf_ellipse_XY (float x, float y, float a, float b, float alpha)
bool nav_gvf_ellipse_wp (uint8_t wp, float a, float b, float alpha)
Variables
gvf_ell_par gvf_ellipse_par
static int gvf_p_len_wps = 0
Macro Definition Documentation
GVF_ELLIPSE_A
#define GVF_ELLIPSE_A 80
Default first axis for the ellipse trajectory
Definition at line 40 of file nav_ellipse.c.
GVF_ELLIPSE_ALPHA
#define GVF_ELLIPSE_ALPHA 0
Default orientation in degrees for the ellipse trajectory
Definition at line 50 of file nav_ellipse.c.
GVF_ELLIPSE_B
#define GVF_ELLIPSE_B 80
Default second axis for the ellipse trajectory
Definition at line 45 of file nav_ellipse.c.
GVF_ELLIPSE_KE
#define GVF_ELLIPSE_KE 1
Default gain ke for the ellipse trajectory
Definition at line 30 of file nav_ellipse.c.
GVF_ELLIPSE_KN
#define GVF_ELLIPSE_KN 1
Default gain kn for the ellipse trajectory
Definition at line 35 of file nav_ellipse.c.
Function Documentation
nav_gvf_ellipse_wp()
bool nav_gvf_ellipse_wp (uint8_t wp, float a, float b, float alpha)
Definition at line 103 of file nav_ellipse.c.
References alpha, b, gvf_p_len_wps, gvf_trajectory, nav_gvf_ellipse_XY(), gvf_tra::p, WaypointX, and WaypointY.
nav_gvf_ellipse_XY()
bool nav_gvf_ellipse_XY (float x, float y, float a, float b, float alpha)
Definition at line 64 of file nav_ellipse.c.
References alpha, b, gvf_con::error, foo, gvf_control, gvf_control_2D(), gvf_ellipse_info(), gvf_ellipse_par, gvf_p_len_wps, gvf_trajectory, gvf_con::ke, gvf_ell_par::ke, gvf_ell_par::kn, gvf_tra::p, gvf_tra::p_len, and gvf_tra::type.
Referenced by distributed_circular(), nav_gvf_ellipse_wp(), and nav_gvf_survey_polygon_run().
Variable Documentation
gvf_ellipse_par
gvf_ell_par gvf_ellipse_par
Initial value:
= {GVF_ELLIPSE_KE, GVF_ELLIPSE_KN,
                               GVF_ELLIPSE_A, GVF_ELLIPSE_B, GVF_ELLIPSE_ALPHA
                              }
Definition at line 53 of file nav_ellipse.c.
Referenced by nav_gvf_ellipse_XY().
gvf_p_len_wps
int gvf_p_len_wps = 0 static
Definition at line 58 of file nav_ellipse.c.
Referenced by nav_gvf_ellipse_wp(), nav_gvf_ellipse_XY(), nav_gvf_ik_ellipse_wp(), and nav_gvf_ik_ellipse_XY().