Paparazzi UAS: sw/airborne/modules/nav/nav_survey_disc.h File Reference
nav_survey_disc.h File Reference
#include "std.h"
Functions
void nav_survey_disc_setup (float grid)
bool nav_survey_disc_run (uint8_t c, float radius)
Function Documentation
nav_survey_disc_run()
bool nav_survey_disc_run (uint8_t c, float radius) extern
Not null even if wind_east=wind_north=0
Definition at line 58 of file nav_survey_disc.c.
References DiscSurvey::c, DiscSurvey::c1, DiscSurvey::c2, CARROT, disc_survey, DOWNWIND, foo, nav_approaching_xy(), nav_circle_XY(), nav_init_stage(), nav_route_xy(), nav_survey_shift, NavQdrCloseTo, NavVerticalAltitudeMode, NavVerticalAutoThrottleMode, SEGMENT, DiscSurvey::sign, stateGetHorizontalWindspeed_f(), stateGetPositionEnu_f(), DiscSurvey::status, UTURN, VECT2_DIFF, VECT2_DOT_PRODUCT, WaypointAlt, waypoints, FloatVect2::x, EnuCoor_f::x, point::x, FloatVect2::y, EnuCoor_f::y, and point::y.
nav_survey_disc_setup()
void nav_survey_disc_setup (float grid) extern
Definition at line 49 of file nav_survey_disc.c.
References DiscSurvey::c1, disc_survey, DOWNWIND, foo, nav_survey_shift, DiscSurvey::sign, stateGetPositionEnu_f(), DiscSurvey::status, FloatVect2::x, EnuCoor_f::x, FloatVect2::y, and EnuCoor_f::y.