Paparazzi UAS: sw/airborne/modules/nav/nav_survey_disc.c File Reference
nav_survey_disc.c File Reference
#include "modules/nav/nav_survey_disc.h"
#include "generated/airframe.h"
#include "state.h"
#include "std.h"
#include "firmwares/fixedwing/nav.h"
#include "generated/flight_plan.h"
#include "math/pprz_algebra_float.h"
Data Structures
struct DiscSurvey
Enumerations
enum DiscSurveyStatus { UTURN , SEGMENT , DOWNWIND }
Functions
void nav_survey_disc_setup (float grid)
bool nav_survey_disc_run (uint8_t center_wp, float radius)
Variables
static struct DiscSurvey disc_survey
Data Structure Documentation
DiscSurvey
struct DiscSurvey
Definition at line 38 of file nav_survey_disc.c.
Data Fields
struct FloatVect2 c
struct FloatVect2 c1
struct FloatVect2 c2
int8_t sign
enum DiscSurveyStatus status
Enumeration Type Documentation
DiscSurveyStatus
enum DiscSurveyStatus
Enumerator
UTURN
SEGMENT
DOWNWIND
Definition at line 36 of file nav_survey_disc.c.
Function Documentation
nav_survey_disc_run()
bool nav_survey_disc_run (uint8_t center_wp, float radius)
Not null even if wind_east=wind_north=0
Definition at line 58 of file nav_survey_disc.c.
References DiscSurvey::c, DiscSurvey::c1, DiscSurvey::c2, CARROT, disc_survey, DOWNWIND, foo, nav_approaching_xy(), nav_circle_XY(), nav_init_stage(), nav_route_xy(), nav_survey_shift, NavQdrCloseTo, NavVerticalAltitudeMode, NavVerticalAutoThrottleMode, SEGMENT, DiscSurvey::sign, stateGetHorizontalWindspeed_f(), stateGetPositionEnu_f(), DiscSurvey::status, UTURN, VECT2_DIFF, VECT2_DOT_PRODUCT, WaypointAlt, waypoints, FloatVect2::x, EnuCoor_f::x, point::x, FloatVect2::y, EnuCoor_f::y, and point::y.
nav_survey_disc_setup()
void nav_survey_disc_setup (float grid)
Definition at line 49 of file nav_survey_disc.c.
References DiscSurvey::c1, disc_survey, DOWNWIND, foo, nav_survey_shift, DiscSurvey::sign, stateGetPositionEnu_f(), DiscSurvey::status, FloatVect2::x, EnuCoor_f::x, FloatVect2::y, and EnuCoor_f::y.
Variable Documentation
disc_survey
struct DiscSurvey disc_survey static
Definition at line 46 of file nav_survey_disc.c.
Referenced by nav_survey_disc_run(), and nav_survey_disc_setup().