Paparazzi UAS: sw/airborne/modules/nav/nav_line_osam.c File Reference
nav_line_osam.c File Reference
Flight line from OSAM advanced navigation routines.
#include "modules/nav/nav_line_osam.h"
#include "firmwares/fixedwing/nav.h"
#include "state.h"
#include "autopilot.h"
#include "generated/flight_plan.h"
Data Structures
struct Point2D
Macros
#define LINE_START_FUNCTION {}
#define LINE_STOP_FUNCTION {}
Enumerations
enum FLStatus { FLInitialize , FLCircleS , FLLine , FLFinished }
Functions
static void TranslateAndRotateFromWorld (struct Point2D *p, float Zrot, float transX, float transY)
bool nav_line_osam_run (uint8_t From_WP, uint8_t To_WP, float radius, float Space_Before, float Space_After)
bool nav_line_osam_block_run (uint8_t First_WP, uint8_t Last_WP, float radius, float Space_Before, float Space_After)
Variables
static enum FLStatus CFLStatus = FLInitialize
static struct Point2D FLCircle
static struct Point2D FLFROMWP
static struct Point2D FLTOWP
static float FLQDR
static float FLRadius
static uint8_t FLBlockCount = 0
Detailed Description
Flight line from OSAM advanced navigation routines.
Todo:
compare with normal flight line
Definition in file nav_line_osam.c.
Data Structure Documentation
Point2D
struct Point2D
Definition at line 90 of file nav_launcher.c.
Data Fields
float x
float y
Macro Definition Documentation
LINE_START_FUNCTION
#define LINE_START_FUNCTION {}
Definition at line 38 of file nav_line_osam.c.
LINE_STOP_FUNCTION
#define LINE_STOP_FUNCTION {}
Definition at line 41 of file nav_line_osam.c.
Enumeration Type Documentation
FLStatus
enum FLStatus
Enumerator
FLInitialize
FLCircleS
FLLine
FLFinished
Definition at line 46 of file nav_line_osam.c.
Function Documentation
nav_line_osam_block_run()
bool nav_line_osam_block_run (uint8_t First_WP, uint8_t Last_WP, float radius, float Space_Before, float Space_After)
Definition at line 176 of file nav_line_osam.c.
References CFLStatus, FLBlockCount, FLInitialize, foo, and nav_line_osam_run().
nav_line_osam_run()
bool nav_line_osam_run (uint8_t From_WP, uint8_t To_WP, float radius, float Space_Before, float Space_After)
Definition at line 71 of file nav_line_osam.c.
References CFLStatus, FLCircle, FLCircleS, FLFinished, FLFROMWP, FLInitialize, FLLine, FLQDR, FLRadius, FLTOWP, foo, LINE_START_FUNCTION, LINE_STOP_FUNCTION, nav_approaching_xy(), nav_circle_XY(), nav_init_stage(), nav_route_xy(), NavCircleCount, NavQdrCloseTo, NavVerticalAltitudeMode, NavVerticalAutoThrottleMode, P, stateGetPositionEnu_f(), TranslateAndRotateFromWorld(), waypoints, WaypointX, WaypointY, EnuCoor_f::x, Point2D::x, EnuCoor_f::y, and Point2D::y.
Referenced by nav_line_osam_block_run().
TranslateAndRotateFromWorld()
static void TranslateAndRotateFromWorld (struct Point2D * p, float Zrot, float transX, float transY) static
Definition at line 58 of file nav_line_osam.c.
References foo, p, and Point2D::x.
Referenced by nav_line_osam_run().
Variable Documentation
CFLStatus
enum FLStatus CFLStatus = FLInitialize static
Definition at line 48 of file nav_line_osam.c.
Referenced by nav_line_osam_block_run(), and nav_line_osam_run().
FLBlockCount
uint8_t FLBlockCount = 0 static
Definition at line 174 of file nav_line_osam.c.
Referenced by nav_line_osam_block_run().
FLCircle
struct Point2D FLCircle static
Definition at line 49 of file nav_line_osam.c.
Referenced by nav_line_osam_run().
FLFROMWP
struct Point2D FLFROMWP static
Definition at line 50 of file nav_line_osam.c.
Referenced by nav_line_osam_run().
FLQDR
float FLQDR static
Definition at line 52 of file nav_line_osam.c.
Referenced by nav_line_osam_run().
FLRadius
float FLRadius static
Definition at line 53 of file nav_line_osam.c.
Referenced by nav_line_osam_run().
FLTOWP
struct Point2D FLTOWP static
Definition at line 51 of file nav_line_osam.c.
Referenced by nav_line_osam_run().