Paparazzi UAS: sw/airborne/modules/nav/nav_catapult.h File Reference
nav_catapult.h File Reference
catapult launch timing system
#include "std.h"
#include "math/pprz_algebra_float.h"
Data Structures
struct nav_catapult_struct
Enumerations
enum nav_catapult_state {
NAV_CATAPULT_UNINIT , NAV_CATAPULT_ARMED , NAV_CATAPULT_WAIT_ACCEL , NAV_CATAPULT_MOTOR_ON ,
NAV_CATAPULT_MOTOR_CLIMB , NAV_CATAPULT_DISARM
}
Functions
void nav_catapult_init (void)
void nav_catapult_highrate_module (void)
bool nav_catapult_run (uint8_t _climb)
Variables
struct nav_catapult_struct nav_catapult
Detailed Description
catapult launch timing system
Phase 1: Zero Roll, Climb Pitch, Zero Throttle
Phase 2: After detecting the Start Acceleration
Zero Roll, Climb Pitch, Full Throttle
Phase 3: After getting the GPS heading (time based)
Place climb in front of us
GoTo(climb)
Definition in file nav_catapult.h.
Data Structure Documentation
nav_catapult_struct
struct nav_catapult_struct
Definition at line 53 of file nav_catapult.h.
Data Fields
float accel_threshold acceleration threshold for launch detection (in g)
float heading_delay delay to estimate initial heading after launch (in seconds)
float initial_pitch pitch angle during first take-off phase (in radian)
float initial_throttle throttle during first take-off phase (in radian)
float motor_delay delay to start motor after launch detection (in seconds)
struct FloatVect3 pos catapult position
enum nav_catapult_state status current procedure state
uint32_t timer internal timer
Enumeration Type Documentation
nav_catapult_state
enum nav_catapult_state
Enumerator
NAV_CATAPULT_UNINIT
NAV_CATAPULT_ARMED
NAV_CATAPULT_WAIT_ACCEL
NAV_CATAPULT_MOTOR_ON
NAV_CATAPULT_MOTOR_CLIMB
NAV_CATAPULT_DISARM
Definition at line 43 of file nav_catapult.h.
Function Documentation
nav_catapult_highrate_module()
void nav_catapult_highrate_module (void) extern
Definition at line 102 of file nav_catapult.c.
References nav_catapult_struct::accel_threshold, autopilot, float_rmat_transp_vmult(), foo, nav_catapult_struct::initial_throttle, pprz_autopilot::launch, MAX_PPRZ, nav_catapult_struct::motor_delay, nav_catapult, NAV_CATAPULT_ACCELERATION_DETECTION, NAV_CATAPULT_ARMED, NAV_CATAPULT_MOTOR_ON, NAV_CATAPULT_TIMEOUT, NAV_CATAPULT_UNINIT, NAV_CATAPULT_WAIT_ACCEL, NavVerticalThrottleMode, stateGetAccelNed_f(), stateGetNedToBodyRMat_f(), nav_catapult_struct::status, and nav_catapult_struct::timer.
nav_catapult_init()
void nav_catapult_init (void) extern
Definition at line 86 of file nav_catapult.c.
References nav_catapult_struct::accel_threshold, nav_catapult_struct::heading_delay, nav_catapult_struct::initial_pitch, nav_catapult_struct::initial_throttle, nav_catapult_struct::motor_delay, nav_catapult, NAV_CATAPULT_ACCELERATION_THRESHOLD, NAV_CATAPULT_HEADING_DELAY, NAV_CATAPULT_INITIAL_PITCH, NAV_CATAPULT_INITIAL_THROTTLE, NAV_CATAPULT_MOTOR_DELAY, NAV_CATAPULT_UNINIT, nav_catapult_struct::status, and nav_catapult_struct::timer.
nav_catapult_run()
bool nav_catapult_run (uint8_t _climb) extern
Definition at line 159 of file nav_catapult.c.
References UtmCoor_f::alt, DownlinkSendWpNr(), foo, nav_catapult_struct::heading_delay, nav_catapult_struct::initial_pitch, nav_catapult_struct::initial_throttle, MAX_PPRZ, nav_approaching_xy(), nav_catapult, NAV_CATAPULT_ARMED, NAV_CATAPULT_CLIMB_DISTANCE, NAV_CATAPULT_DISARM, NAV_CATAPULT_MOTOR_CLIMB, NAV_CATAPULT_MOTOR_ON, NAV_CATAPULT_UNINIT, NAV_CATAPULT_WAIT_ACCEL, NavAttitude, NavGotoWaypoint, NavVerticalAltitudeMode, NavVerticalAutoThrottleMode, NavVerticalThrottleMode, nav_catapult_struct::pos, stateGetPositionEnu_f(), stateGetPositionUtm_f(), nav_catapult_struct::status, nav_catapult_struct::timer, WaypointAlt, WaypointX, WaypointY, FloatVect3::x, EnuCoor_f::x, FloatVect3::y, EnuCoor_f::y, and FloatVect3::z.
Variable Documentation
nav_catapult
struct nav_catapult_struct nav_catapult extern
Definition at line 83 of file nav_catapult.c.
Referenced by nav_catapult_highrate_module(), nav_catapult_init(), and nav_catapult_run().