Paparazzi UAS: sw/airborne/filters/notch_filter.h File Reference
notch_filter.h File Reference
Second order notch filter.
#include "std.h"
Data Structures
struct SecondOrderNotchFilter
Functions
static void notch_filter_set_sampling_frequency (struct SecondOrderNotchFilter *filter, uint16_t frequency)
Set sampling frequency of the notch filter.
static void notch_filter_set_bandwidth (struct SecondOrderNotchFilter *filter, float bandwidth)
Set bandwidth of the notch filter.
static void notch_filter_set_filter_frequency (struct SecondOrderNotchFilter *filter, float frequency)
Set notch filter frequency in Hz.
static void notch_filter_update (struct SecondOrderNotchFilter *filter, int32_t *input_signal, int32_t *output_signal)
Notch filter propagate.
static int32_t notch_filter_get_output (struct SecondOrderNotchFilter *filter)
Get latest notch filter output.
static void notch_filter_init (struct SecondOrderNotchFilter *filter, float cutoff_frequency, float bandwidth, uint16_t sample_frequency)
Initialize second order notch filter.
Detailed Description
Second order notch filter.
Definition in file notch_filter.h.
Data Structure Documentation
SecondOrderNotchFilter
struct SecondOrderNotchFilter
Definition at line 32 of file notch_filter.h.
Data Fields
float costheta
float d2
float Ts
int32_t xn1
float xn1
int32_t xn2
float xn2
int32_t yn1
float yn1
int32_t yn2
float yn2
Function Documentation
notch_filter_get_output()
static int32_t notch_filter_get_output (struct SecondOrderNotchFilter * filter) inline static
Get latest notch filter output.
Parameters
filter filter data structure
Returns
Latest filtered value
Definition at line 105 of file notch_filter.h.
References SecondOrderNotchFilter::yn1.
notch_filter_init()
static void notch_filter_init (struct SecondOrderNotchFilter * filter, float cutoff_frequency, float bandwidth, uint16_t sample_frequency) inline static
Initialize second order notch filter.
Discrete implementation: y[n] = b * y[n-1] - d^2 * y[n-2] + a * x[n] - b * x[n-1] + a * x[n-2]
Parameters
cutoff_frequency frequency to attenuate [Hz]
bandwidth bandwidth of the filter [Hz]
sample_frequency frequency at which the filter is updated
Definition at line 119 of file notch_filter.h.
References foo, notch_filter_set_bandwidth(), notch_filter_set_filter_frequency(), notch_filter_set_sampling_frequency(), SecondOrderNotchFilter::xn1, SecondOrderNotchFilter::xn2, SecondOrderNotchFilter::yn1, and SecondOrderNotchFilter::yn2.
Referenced by adaptive_notch_filter_init(), init_filter(), and stabilization_attitude_heli_indi_init().
notch_filter_set_bandwidth()
static void notch_filter_set_bandwidth (struct SecondOrderNotchFilter * filter, float bandwidth) inline static
Set bandwidth of the notch filter.
Parameters
filter filter data structure
bandwidth bandwidth of the filter [Hz]
Definition at line 57 of file notch_filter.h.
References SecondOrderNotchFilter::d2, foo, and SecondOrderNotchFilter::Ts.
Referenced by notch_filter_init().
notch_filter_set_filter_frequency()
static void notch_filter_set_filter_frequency (struct SecondOrderNotchFilter * filter, float frequency) inline static
Set notch filter frequency in Hz.
Parameters
filter filter data structure
frequency to attenuate [Hz]
Definition at line 68 of file notch_filter.h.
References SecondOrderNotchFilter::costheta, foo, and SecondOrderNotchFilter::Ts.
Referenced by adaptive_notch_filter_update(), indi_apply_notch_filters(), and notch_filter_init().
notch_filter_set_sampling_frequency()
static void notch_filter_set_sampling_frequency (struct SecondOrderNotchFilter * filter, uint16_t frequency) inline static
Set sampling frequency of the notch filter.
Parameters
filter filter data structure
frequency frequency at which the filter is updated
Definition at line 47 of file notch_filter.h.
References foo, and SecondOrderNotchFilter::Ts.
Referenced by notch_filter_init().
notch_filter_update()
static void notch_filter_update (struct SecondOrderNotchFilter * filter, int32_t * input_signal, int32_t * output_signal) inline static
Notch filter propagate.
Discrete implementation: y[n] = b * y[n-1] - d^2 * y[n-2] + a * x[n] - b * x[n-1] + a * x[n-2]
Parameters
filter filter data structure
input_signal input x[n]
output_signal output y[n]
Definition at line 83 of file notch_filter.h.
References b, SecondOrderNotchFilter::costheta, SecondOrderNotchFilter::d2, foo, SecondOrderNotchFilter::xn1, SecondOrderNotchFilter::xn2, SecondOrderNotchFilter::yn1, and SecondOrderNotchFilter::yn2.
Referenced by adaptive_notch_filter_update(), indi_apply_notch_filters(), and oneloop_andi_propagate_filters().