Paparazzi UAS: sw/simulator/nps/nps_autopilot_rover.c File Reference
nps_autopilot_rover.c File Reference
#include "nps_autopilot.h"
#include "main_ap.h"
#include "nps_sensors.h"
#include "nps_radio_control.h"
#include "nps_electrical.h"
#include "nps_fdm.h"
#include "modules/radio_control/radio_control.h"
#include "modules/imu/imu.h"
#include "mcu_periph/sys_time.h"
#include "state.h"
#include "modules/ahrs/ahrs.h"
#include "modules/ins/ins.h"
#include "math/pprz_algebra.h"
#include "modules/core/abi.h"
#include "pprzlink/messages.h"
#include "modules/datalink/downlink.h"
#include "modules/datalink/datalink.h"
#include "modules/actuators/actuators.h"
#include <stdio.h>
#include "modules/gps/gps.h"
Macros
#define NPS_BYPASS_AHRS FALSE
#define NPS_BYPASS_INS FALSE
Functions
void sys_tick_handler (void)
void nps_autopilot_init (enum NpsRadioControlType type_rc, int num_rc_script, char *rc_dev)
void nps_autopilot_run_systime_step (void)
void nps_autopilot_run_step (double time)
void sim_overwrite_ahrs (void)
void sim_overwrite_ins (void)
Variables
struct NpsAutopilot nps_autopilot
ifndef NPS_NO_MOTOR_MIXING include "modules/actuators/motor_mixing.h"
bool nps_bypass_ahrs
bool nps_bypass_ins
Macro Definition Documentation
NPS_BYPASS_AHRS
#define NPS_BYPASS_AHRS FALSE
Definition at line 61 of file nps_autopilot_rover.c.
NPS_BYPASS_INS
#define NPS_BYPASS_INS FALSE
Definition at line 65 of file nps_autopilot_rover.c.
Function Documentation
nps_autopilot_init()
void nps_autopilot_init (enum NpsRadioControlType type_rc, int num_rc_script, char * rc_dev)
Definition at line 74 of file nps_autopilot_rover.c.
References FALSE, foo, NpsAutopilot::launch, main_ap_init(), nps_autopilot, nps_bypass_ahrs, NPS_BYPASS_AHRS, nps_bypass_ins, NPS_BYPASS_INS, nps_electrical_init(), nps_radio_control_init(), and TRUE.
Referenced by nps_radio_and_autopilot_init().
nps_autopilot_run_step()
void nps_autopilot_run_step (double time)
Definition at line 97 of file nps_autopilot_rover.c.
References AGL_SONAR_NPS_ID, AIRSPEED_NPS_ID, autopilot, autopilot_get_motors_on(), BARO_SIM_SENDER_ID, commands, NpsAutopilot::commands, DefaultChannel, DefaultDevice, foo, get_sys_time_usec(), gps_feed_value(), imu_feed_gyro_accel(), imu_feed_mag(), INCIDENCE_NPS_ID, pprz_autopilot::kill_throttle, pprz_autopilot::launch, NpsAutopilot::launch, main_ap_event(), main_ap_periodic(), MAX_PPRZ, nps_autopilot, nps_bypass_ahrs, nps_bypass_ins, NPS_COMMANDS_NB, nps_electrical_run_step(), nps_radio_control_available(), nps_sensors_airspeed_available(), nps_sensors_aoa_available(), nps_sensors_baro_available(), nps_sensors_gps_available(), nps_sensors_gyro_available(), nps_sensors_mag_available(), nps_sensors_sideslip_available(), nps_sensors_sonar_available(), nps_sensors_temperature_available(), PRINT_CONFIG_MSG(), PRINT_CONFIG_VAR(), radio_control_feed(), sensors, sim_overwrite_ahrs(), sim_overwrite_ins(), stateSetAirspeed_f(), and time.
Referenced by nps_main_run_sim_step().
nps_autopilot_run_systime_step()
void nps_autopilot_run_systime_step (void)
Definition at line 89 of file nps_autopilot_rover.c.
References sys_tick_handler().
Referenced by nps_main_run_sim_step().
sim_overwrite_ahrs()
void sim_overwrite_ahrs (void)
Definition at line 183 of file nps_autopilot_rover.c.
References NpsFdm::body_ecef_rotvel, fdm, foo, NpsFdm::ltp_to_body_quat, QUAT_COPY, RATES_COPY, STATE_INPUT_ATTITUDE, stateSetBodyRates_f(), stateSetInputFilter(), and stateSetNedToBodyQuat_f().
Referenced by nps_autopilot_run_step().
sim_overwrite_ins()
void sim_overwrite_ins (void)
Definition at line 197 of file nps_autopilot_rover.c.
References fdm, foo, LLA_COPY, NpsFdm::lla_pos, LlaCoor_f::lon, NpsFdm::ltpprz_ecef_accel, NpsFdm::ltpprz_ecef_vel, NpsFdm::ltpprz_pos, State::ned_initialized_f, State::ned_initialized_i, state, stateCalcPositionEnu_i(), stateSetAccelNed_f(), stateSetPositionNed_f(), stateSetPositionUtm_f(), stateSetSpeedNed_f(), State::utm_initialized_f, utm_of_lla_f(), VECT3_COPY, and UtmCoor_f::zone.
Referenced by ins_ekf2_update(), ins_ned_to_state(), ins_ned_to_state(), and nps_autopilot_run_step().
sys_tick_handler()
void sys_tick_handler (void)
Definition at line 150 of file sys_time_arch.c.
References sys_time_timer::cb, CH_CFG_ST_FREQUENCY, cpu_counter, cpu_ticks, cpu_ticks_of_nsec(), cpu_ticks_of_sec(), sys_time::cpu_ticks_per_sec, sys_time_timer::duration, sys_time_timer::elapsed, sys_time_timer::end_time, foo, sys_time_timer::in_use, LED_TOGGLE, sys_time::nb_sec, sys_time::nb_sec_rem, sys_time::nb_tick, sys_time::resolution_cpu_ticks, startup_time, SYS_TIME_NB_TIMER, sys_time_ticks_of_sec(), sys_time_ticks_of_usec(), sys_time::timer, and TRUE.
Referenced by nps_autopilot_run_systime_step(), sys_time_thread_main(), and thd_sys_tick().
Variable Documentation
nps_autopilot
struct NpsAutopilot nps_autopilot
ifndef NPS_NO_MOTOR_MIXING include "modules/actuators/motor_mixing.h"
if NPS_COMMANDS_NB != MOTOR_MIXING_NB_MOTOR warning "NPS_COMMANDS_NB does not match MOTOR_MIXING_NB_MOTOR!" endif endif
Definition at line 56 of file nps_autopilot_rover.c.
Referenced by nps_autopilot_init(), and nps_autopilot_run_step().
nps_bypass_ahrs
bool nps_bypass_ahrs
Definition at line 57 of file nps_autopilot_rover.c.
Referenced by nps_autopilot_init(), and nps_autopilot_run_step().
nps_bypass_ins
bool nps_bypass_ins
Definition at line 58 of file nps_autopilot_rover.c.
Referenced by ins_ekf2_update(), ins_ned_to_state(), ins_ned_to_state(), nps_autopilot_init(), and nps_autopilot_run_step().