Paparazzi UAS: sw/simulator/nps/nps_autopilot.h File Reference
nps_autopilot.h File Reference
#include "generated/airframe.h"
#include "nps_radio_control.h"
Data Structures
struct NpsAutopilot
Macros
#define NPS_COMMANDS_NB ACTUATORS_NB
Number of commands sent to the FDM of NPS.
Functions
void sim_overwrite_ahrs (void)
void sim_overwrite_ins (void)
void nps_autopilot_init (enum NpsRadioControlType type, int num_script, char *js_dev)
void nps_autopilot_run_step (double time)
void nps_autopilot_run_systime_step (void)
Variables
struct NpsAutopilot nps_autopilot
ifndef NPS_NO_MOTOR_MIXING include "modules/actuators/motor_mixing.h"
bool nps_bypass_ahrs
bool nps_bypass_ins
Data Structure Documentation
NpsAutopilot
struct NpsAutopilot
Definition at line 48 of file nps_autopilot.h.
Data Fields
double commands[NPS_COMMANDS_NB]
bool launch
Macro Definition Documentation
NPS_COMMANDS_NB
#define NPS_COMMANDS_NB ACTUATORS_NB
Number of commands sent to the FDM of NPS.
If MOTOR_MIXING_NB_MOTOR is defined (usually rotorcraft firmware) we have that many commands (one per motor), otherwise we default to the number of high level commands (COMMANDS_NB).
Definition at line 44 of file nps_autopilot.h.
Function Documentation
nps_autopilot_init()
void nps_autopilot_init (enum NpsRadioControlType type, int num_script, char * js_dev) extern
Definition at line 69 of file nps_autopilot_fixedwing.c.
References FALSE, foo, NpsAutopilot::launch, main_ap_init(), nps_autopilot, nps_bypass_ahrs, NPS_BYPASS_AHRS, nps_bypass_ins, NPS_BYPASS_INS, nps_electrical_init(), nps_radio_control_init(), and TRUE.
Referenced by nps_radio_and_autopilot_init().
nps_autopilot_run_step()
void nps_autopilot_run_step (double time) extern
Definition at line 95 of file nps_autopilot_fixedwing.c.
References actuators_pprz, AGL_SONAR_NPS_ID, AIRSPEED_NPS_ID, autopilot, autopilot_get_motors_on(), BARO_SIM_SENDER_ID, commands, MotorMixing::commands, NpsAutopilot::commands, DefaultChannel, DefaultDevice, foo, get_sys_time_usec(), gps_feed_value(), imu_feed_gyro_accel(), imu_feed_mag(), INCIDENCE_NPS_ID, pprz_autopilot::kill_throttle, pprz_autopilot::launch, NpsAutopilot::launch, main_ap_event(), main_ap_periodic(), MAX_PPRZ, motor_mixing, nps_autopilot, nps_bypass_ahrs, nps_bypass_ins, NPS_COMMANDS_NB, nps_electrical_run_step(), nps_radio_control_available(), nps_sensors_airspeed_available(), nps_sensors_aoa_available(), nps_sensors_baro_available(), nps_sensors_gps_available(), nps_sensors_gyro_available(), nps_sensors_mag_available(), nps_sensors_sideslip_available(), nps_sensors_sonar_available(), nps_sensors_temperature_available(), PRINT_CONFIG_MSG(), PRINT_CONFIG_VAR(), radio_control_feed(), sensors, sim_overwrite_ahrs(), sim_overwrite_ins(), stateSetAirspeed_f(), and time.
Referenced by nps_main_run_sim_step().
nps_autopilot_run_systime_step()
void nps_autopilot_run_systime_step (void) extern
Definition at line 87 of file nps_autopilot_fixedwing.c.
References sys_tick_handler().
Referenced by nps_main_run_sim_step().
sim_overwrite_ahrs()
void sim_overwrite_ahrs (void) extern
Definition at line 234 of file nps_autopilot_fixedwing.c.
References NpsFdm::body_ecef_rotvel, fdm, foo, NpsFdm::ltp_to_body_quat, QUAT_COPY, RATES_COPY, STATE_INPUT_ATTITUDE, stateSetBodyRates_f(), stateSetInputFilter(), and stateSetNedToBodyQuat_f().
Referenced by nps_autopilot_run_step().
sim_overwrite_ins()
void sim_overwrite_ins (void) extern
Definition at line 247 of file nps_autopilot_fixedwing.c.
References fdm, foo, LLA_COPY, NpsFdm::lla_pos, LlaCoor_f::lon, NpsFdm::ltpprz_ecef_accel, NpsFdm::ltpprz_ecef_vel, NpsFdm::ltpprz_pos, State::ned_initialized_f, State::ned_initialized_i, state, stateCalcPositionEnu_i(), stateSetAccelNed_f(), stateSetPositionNed_f(), stateSetPositionUtm_f(), stateSetSpeedNed_f(), State::utm_initialized_f, utm_of_lla_f(), VECT3_COPY, and UtmCoor_f::zone.
Referenced by ins_ekf2_update(), ins_ned_to_state(), ins_ned_to_state(), and nps_autopilot_run_step().
Variable Documentation
nps_autopilot
struct NpsAutopilot nps_autopilot extern
ifndef NPS_NO_MOTOR_MIXING include "modules/actuators/motor_mixing.h"
if NPS_COMMANDS_NB != MOTOR_MIXING_NB_MOTOR warning "NPS_COMMANDS_NB does not match MOTOR_MIXING_NB_MOTOR!" endif endif
Definition at line 52 of file nps_autopilot_fixedwing.c.
Referenced by nps_ap_data_loop(), nps_autopilot_init(), nps_autopilot_init(), nps_autopilot_run_step(), nps_main_run_sim_step(), and nps_update_launch_from_dl().
nps_bypass_ahrs
bool nps_bypass_ahrs extern
Definition at line 53 of file nps_autopilot_fixedwing.c.
Referenced by nps_autopilot_init(), nps_autopilot_init(), and nps_autopilot_run_step().
nps_bypass_ins
bool nps_bypass_ins extern
Definition at line 54 of file nps_autopilot_fixedwing.c.
Referenced by ins_ekf2_update(), ins_ned_to_state(), ins_ned_to_state(), nps_autopilot_init(), nps_autopilot_init(), and nps_autopilot_run_step().