Paparazzi UAS: sw/simulator/nps/nps_electrical.h File Reference
nps_electrical.h File Reference
Electrical status (bat voltage) for NPS.
Data Structures
struct NpsElectrical
Functions
void nps_electrical_init (void)
void nps_electrical_run_step (double time)
Variables
struct NpsElectrical nps_electrical
Detailed Description
Electrical status (bat voltage) for NPS.
Definition in file nps_electrical.h.
Data Structure Documentation
NpsElectrical
struct NpsElectrical
Definition at line 30 of file nps_electrical.h.
Data Fields
float supply_voltage
Function Documentation
nps_electrical_init()
void nps_electrical_init (void) extern
Definition at line 33 of file nps_electrical.c.
References foo, nps_electrical, and NpsElectrical::supply_voltage.
Referenced by nps_autopilot_init(), and nps_autopilot_init().
nps_electrical_run_step()
void nps_electrical_run_step (double time) extern
Definition at line 44 of file nps_electrical.c.
References electrical, nps_electrical, NpsElectrical::supply_voltage, and Electrical::vsupply.
Referenced by nps_autopilot_run_step().
Variable Documentation
nps_electrical
struct NpsElectrical nps_electrical extern
Definition at line 31 of file nps_electrical.c.
Referenced by nps_electrical_init(), and nps_electrical_run_step().