Paparazzi UAS: sw/simulator/nps/nps_main.h File Reference
nps_main.h File Reference
#include <pthread.h>
#include <sys/time.h>
#include "nps_fdm.h"
#include "mcu_periph/sys_time.h"
#include "nps_atmosphere.h"
#include "nps_sensors.h"
#include "nps_autopilot.h"
Data Structures
struct NpsMain
Macros
#define clock_get_current_time(_x) clock_gettime(CLOCK_REALTIME, _x)
#define SIM_DT (1./SYS_TIME_FREQUENCY)
#define DISPLAY_DT (1./30.)
#define HOST_TIMEOUT_MS 40
Functions
bool nps_main_parse_options (int argc, char **argv)
int nps_main_init (int argc, char **argv)
void nps_radio_and_autopilot_init (void)
void nps_main_run_sim_step (void)
void nps_set_time_factor (float time_factor)
void * nps_main_loop (void *data)
void * nps_flight_gear_loop (void *data)
void * nps_main_display (void *data)
void tstp_hdl (int n)
void cont_hdl (int n)
double time_to_double (struct timeval *t)
double ntime_to_double (struct timespec *t)
void nps_update_launch_from_dl (uint8_t value)
void nps_hitl_impl_init (void)
END pprzlink_dev.
Variables
pthread_t th_flight_gear
pthread_t th_display_ivy
pthread_t th_main_loop
pthread_mutex_t fdm_mutex
int pauseSignal
struct NpsMain nps_main
Data Structure Documentation
NpsMain
struct NpsMain
Definition at line 53 of file nps_main.h.
Data Fields
double display_time
int fg_fdm
char * fg_host
unsigned int fg_port
unsigned int fg_port_in
unsigned int fg_time_offset
double host_time_factor
char * ivy_bus
char * js_dev
bool nodisplay
bool norc
int rc_script
double real_initial_time
double scaled_initial_time
double sim_time
char * spektrum_dev
Macro Definition Documentation
clock_get_current_time
#define clock_get_current_time (_x) clock_gettime(CLOCK_REALTIME, _x)
Definition at line 17 of file nps_main.h.
DISPLAY_DT
#define DISPLAY_DT (1./30.)
Definition at line 21 of file nps_main.h.
HOST_TIMEOUT_MS
#define HOST_TIMEOUT_MS 40
Definition at line 22 of file nps_main.h.
SIM_DT
#define SIM_DT (1./SYS_TIME_FREQUENCY)
Definition at line 20 of file nps_main.h.
Function Documentation
cont_hdl()
void cont_hdl (int n) extern
Definition at line 68 of file nps_main_common.c.
References cont_hdl(), foo, and tstp_hdl().
Referenced by cont_hdl(), and nps_main_init().
nps_flight_gear_loop()
void * nps_flight_gear_loop (void * data) extern
Definition at line 265 of file nps_main_common.c.
References clock_get_current_time, DISPLAY_DT, fdm_mutex, NpsMain::fg_fdm, NpsMain::fg_host, NpsMain::fg_port, NpsMain::fg_port_in, NpsMain::fg_time_offset, foo, nps_flightgear_init(), nps_flightgear_send(), nps_flightgear_send_fdm(), nps_main, and TRUE.
Referenced by main().
nps_hitl_impl_init()
void nps_hitl_impl_init (void) extern
END pprzlink_dev.
Definition at line 154 of file nps_hitl_sensors.c.
References AP_BAUD, AP_DEV, char_available(), check_free_space(), dev, linkdev::device, SerialPort::fd, linkdev::fds, foo, getch(), nps_ap_data_loop(), nps_sensors_loop(), linkdev::port, linkdev::pprz_tp, put_buffer(), put_byte(), send_message(), serial_port_free(), serial_port_new(), serial_port_open_raw(), th_ap_data, and th_sensors.
Referenced by main().
nps_main_display()
void * nps_main_display (void * data) extern
Definition at line 313 of file nps_main_common.c.
References clock_get_current_time, DISPLAY_DT, fdm, foo, NpsMain::ivy_bus, NpsMain::nodisplay, nps_ivy_display(), nps_ivy_init(), nps_main, sensors, and TRUE.
Referenced by main().
nps_main_init()
int nps_main_init (int argc, char ** argv) extern
Definition at line 86 of file nps_main_common.c.
References cont_hdl(), NpsMain::display_time, foo, NpsMain::host_time_factor, nps_atmosphere_init(), nps_fdm_init(), nps_main, nps_main_parse_options(), nps_radio_and_autopilot_init(), nps_sensors_init(), pauseSignal, NpsMain::real_initial_time, NpsMain::scaled_initial_time, SIM_DT, NpsMain::sim_time, time_to_double(), and tstp_hdl().
Referenced by main().
nps_main_loop()
void * nps_main_loop (void * data) extern
Definition at line 78 of file nps_main_hitl.c.
References clock_get_current_time, NpsMain::display_time, fdm, fdm_mutex, foo, NpsMain::host_time_factor, HOST_TIMEOUT_MS, nps_main, nps_main_run_sim_step(), ntime_to_double(), pauseSignal, NpsMain::real_initial_time, NpsMain::scaled_initial_time, SIM_DT, NpsMain::sim_time, t1, NpsFdm::time, time_to_double(), and TRUE.
Referenced by main().
nps_main_parse_options()
bool nps_main_parse_options (int argc, char ** argv) extern
Definition at line 154 of file nps_main_common.c.
References NpsMain::fg_fdm, NpsMain::fg_host, NpsMain::fg_port, NpsMain::fg_port_in, NpsMain::fg_time_offset, foo, NpsMain::host_time_factor, NpsMain::ivy_bus, NpsMain::js_dev, NpsMain::nodisplay, NpsMain::norc, nps_main, NpsMain::rc_script, NpsMain::spektrum_dev, TRUE, and usage().
Referenced by nps_main_init().
nps_main_run_sim_step()
void nps_main_run_sim_step (void) extern
Definition at line 68 of file nps_main_hitl.c.
References NpsAutopilot::commands, NpsAutopilot::launch, nps_atmosphere_update(), nps_autopilot, nps_autopilot_run_step(), nps_autopilot_run_systime_step(), NPS_COMMANDS_NB, nps_fdm_run_step(), nps_main, nps_sensors_run_step(), SIM_DT, and NpsMain::sim_time.
Referenced by nps_main_loop().
nps_radio_and_autopilot_init()
void nps_radio_and_autopilot_init (void) extern
Definition at line 58 of file nps_main_hitl.c.
References foo, JOYSTICK, NpsMain::js_dev, NpsMain::norc, NORC, nps_autopilot_init(), nps_main, NpsMain::rc_script, SCRIPT, SPEKTRUM, and NpsMain::spektrum_dev.
Referenced by nps_main_init().
nps_set_time_factor()
void nps_set_time_factor (float time_factor) extern
Definition at line 126 of file nps_main_common.c.
References foo, NpsMain::host_time_factor, nps_main, NpsMain::scaled_initial_time, and time_to_double().
Referenced by on_WORLD_ENV().
nps_update_launch_from_dl()
void nps_update_launch_from_dl (uint8_t value)
Definition at line 62 of file nps_main_hitl.c.
References foo, NpsAutopilot::launch, and nps_autopilot.
Referenced by on_DL_SETTING().
ntime_to_double()
double ntime_to_double (struct timespec * t) extern
Definition at line 81 of file nps_main_common.c.
References foo.
Referenced by nps_main_loop().
time_to_double()
double time_to_double (struct timeval * t) extern
Definition at line 76 of file nps_main_common.c.
References foo.
Referenced by nps_main_init(), nps_main_loop(), and nps_set_time_factor().
tstp_hdl()
void tstp_hdl (int n) extern
Definition at line 56 of file nps_main_common.c.
References foo, and pauseSignal.
Referenced by cont_hdl(), and nps_main_init().
Variable Documentation
fdm_mutex
pthread_mutex_t fdm_mutex extern
Definition at line 36 of file nps_main_common.c.
Referenced by nps_ap_data_loop(), nps_flight_gear_loop(), nps_flightgear_receive(), nps_ivy_display(), nps_main_loop(), and nps_sensors_loop().
nps_main
struct NpsMain nps_main extern
Definition at line 38 of file nps_main_common.c.
Referenced by main(), nps_flight_gear_loop(), nps_main_display(), nps_main_init(), nps_main_loop(), nps_main_parse_options(), nps_main_run_sim_step(), nps_radio_and_autopilot_init(), nps_sensors_loop(), and nps_set_time_factor().
pauseSignal
int pauseSignal extern
Definition at line 37 of file nps_main_common.c.
Referenced by nps_main_init(), nps_main_loop(), and tstp_hdl().
th_display_ivy
pthread_t th_display_ivy extern
Definition at line 34 of file nps_main_common.c.
Referenced by main().
th_flight_gear
pthread_t th_flight_gear extern
Definition at line 33 of file nps_main_common.c.
Referenced by main().
th_main_loop
pthread_t th_main_loop extern
Definition at line 35 of file nps_main_common.c.
Referenced by main().