Paparazzi UAS: sw/simulator/nps/nps_sensors.h File Reference
nps_sensors.h File Reference
#include "math/pprz_algebra.h"
#include "nps_sensors_params_default.h"
#include "nps_sensor_gyro.h"
#include "nps_sensor_accel.h"
#include "nps_sensor_mag.h"
#include "nps_sensor_baro.h"
#include "nps_sensor_gps.h"
#include "nps_sensor_sonar.h"
#include "nps_sensor_airspeed.h"
#include "nps_sensor_temperature.h"
#include "nps_sensor_aoa.h"
#include "nps_sensor_sideslip.h"
Data Structures
struct NpsSensors
Functions
void nps_sensors_init (double time)
void nps_sensors_run_step (double time)
bool nps_sensors_gyro_available ()
bool nps_sensors_mag_available ()
bool nps_sensors_baro_available ()
bool nps_sensors_gps_available ()
bool nps_sensors_sonar_available ()
bool nps_sensors_airspeed_available ()
bool nps_sensors_temperature_available ()
bool nps_sensors_aoa_available ()
bool nps_sensors_sideslip_available ()
Variables
struct NpsSensors sensors
Data Structure Documentation
NpsSensors
struct NpsSensors
Definition at line 22 of file nps_sensors.h.
Data Fields
struct NpsSensorAccel accel
struct NpsSensorAirspeed airspeed
struct NpsSensorAngleOfAttack aoa
struct NpsSensorBaro baro
struct DoubleRMat body_to_imu_rmat
struct NpsSensorGps gps
struct NpsSensorGyro gyro
struct NpsSensorMag mag
struct NpsSensorSideSlip sideslip
struct NpsSensorSonar sonar
struct NpsSensorTemperature temp
Function Documentation
nps_sensors_airspeed_available()
bool nps_sensors_airspeed_available () extern
Definition at line 85 of file nps_sensors.c.
References NpsSensors::airspeed, NpsSensorAirspeed::data_available, FALSE, sensors, and TRUE.
Referenced by nps_autopilot_run_step(), and nps_sensors_loop().
nps_sensors_aoa_available()
bool nps_sensors_aoa_available () extern
Definition at line 103 of file nps_sensors.c.
References NpsSensors::aoa, NpsSensorAngleOfAttack::data_available, FALSE, sensors, and TRUE.
Referenced by nps_autopilot_run_step(), and nps_sensors_loop().
nps_sensors_baro_available()
bool nps_sensors_baro_available () extern
Definition at line 58 of file nps_sensors.c.
References NpsSensors::baro, NpsSensorBaro::data_available, FALSE, sensors, and TRUE.
Referenced by nps_autopilot_run_step(), and nps_sensors_loop().
nps_sensors_gps_available()
bool nps_sensors_gps_available () extern
Definition at line 67 of file nps_sensors.c.
References NpsSensorGps::data_available, FALSE, NpsSensors::gps, sensors, and TRUE.
Referenced by nps_autopilot_run_step(), and nps_sensors_loop().
nps_sensors_gyro_available()
bool nps_sensors_gyro_available () extern
Definition at line 40 of file nps_sensors.c.
References NpsSensorGyro::data_available, FALSE, NpsSensors::gyro, sensors, and TRUE.
Referenced by nps_autopilot_run_step(), and nps_sensors_loop().
nps_sensors_init()
void nps_sensors_init (double time) extern
Definition at line 5 of file nps_sensors.c.
References NpsSensors::accel, NpsSensors::airspeed, NpsSensors::aoa, NpsSensors::baro, NpsSensors::body_to_imu_rmat, double_rmat_of_eulers(), foo, NpsSensors::gps, NpsSensors::gyro, NpsSensors::mag, nps_sensor_accel_init(), nps_sensor_airspeed_init(), nps_sensor_aoa_init(), nps_sensor_baro_init(), nps_sensor_gps_init(), nps_sensor_gyro_init(), nps_sensor_mag_init(), nps_sensor_sideslip_init(), nps_sensor_sonar_init(), nps_sensor_temperature_init(), sensors, NpsSensors::sideslip, NpsSensors::sonar, NpsSensors::temp, and time.
Referenced by nps_main_init().
nps_sensors_mag_available()
bool nps_sensors_mag_available () extern
Definition at line 49 of file nps_sensors.c.
References NpsSensorMag::data_available, FALSE, NpsSensors::mag, sensors, and TRUE.
Referenced by nps_autopilot_run_step().
nps_sensors_run_step()
void nps_sensors_run_step (double time) extern
Definition at line 25 of file nps_sensors.c.
References NpsSensors::accel, NpsSensors::airspeed, NpsSensors::aoa, NpsSensors::baro, NpsSensors::body_to_imu_rmat, NpsSensors::gps, NpsSensors::gyro, NpsSensors::mag, nps_sensor_accel_run_step(), nps_sensor_airspeed_run_step(), nps_sensor_aoa_run_step(), nps_sensor_baro_run_step(), nps_sensor_gps_run_step(), nps_sensor_gyro_run_step(), nps_sensor_mag_run_step(), nps_sensor_sideslip_run_step(), nps_sensor_sonar_run_step(), nps_sensor_temperature_run_step(), sensors, NpsSensors::sideslip, NpsSensors::sonar, NpsSensors::temp, and time.
Referenced by nps_main_run_sim_step().
nps_sensors_sideslip_available()
bool nps_sensors_sideslip_available () extern
Definition at line 112 of file nps_sensors.c.
References NpsSensorSideSlip::data_available, FALSE, sensors, NpsSensors::sideslip, and TRUE.
Referenced by nps_autopilot_run_step(), and nps_sensors_loop().
nps_sensors_sonar_available()
bool nps_sensors_sonar_available () extern
Definition at line 76 of file nps_sensors.c.
References NpsSensorSonar::data_available, FALSE, sensors, NpsSensors::sonar, and TRUE.
Referenced by nps_autopilot_run_step().
nps_sensors_temperature_available()
bool nps_sensors_temperature_available () extern
Definition at line 94 of file nps_sensors.c.
References NpsSensorTemperature::data_available, FALSE, sensors, NpsSensors::temp, and TRUE.
Referenced by nps_autopilot_run_step().
Variable Documentation
sensors
struct NpsSensors sensors extern
Definition at line 3 of file nps_sensors.c.
Referenced by nps_sensors_airspeed_available(), nps_sensors_aoa_available(), nps_sensors_baro_available(), nps_sensors_gps_available(), nps_sensors_gyro_available(), nps_sensors_init(), nps_sensors_mag_available(), nps_sensors_run_step(), nps_sensors_sideslip_available(), nps_sensors_sonar_available(), and nps_sensors_temperature_available().