Paparazzi UAS: sw/simulator/nps/nps_sensor_sonar.c File Reference
nps_sensor_sonar.c File Reference
Simulated sonar for NPS simulator.
#include "nps_sensor_sonar.h"
#include "generated/airframe.h"
#include "std.h"
#include "nps_fdm.h"
#include "nps_random.h"
#include "nps_sensors.h"
Macros
#define NPS_SONAR_DT 0.01
10Hz default
#define NPS_SONAR_NOISE_STD_DEV 0.01
standard devition in meters (default 1cm)
#define NPS_SONAR_OFFSET 0
#define NPS_SONAR_MIN_DIST 0.1f
#define NPS_SONAR_MAX_DIST 7.0f
Functions
void nps_sensor_sonar_init (struct NpsSensorSonar *sonar, double time)
void nps_sensor_sonar_run_step (struct NpsSensorSonar *sonar, double time)
Detailed Description
Simulated sonar for NPS simulator.
Definition in file nps_sensor_sonar.c.
Macro Definition Documentation
NPS_SONAR_DT
#define NPS_SONAR_DT 0.01
10Hz default
Definition at line 40 of file nps_sensor_sonar.c.
NPS_SONAR_MAX_DIST
#define NPS_SONAR_MAX_DIST 7.0f
Definition at line 57 of file nps_sensor_sonar.c.
NPS_SONAR_MIN_DIST
#define NPS_SONAR_MIN_DIST 0.1f
Definition at line 53 of file nps_sensor_sonar.c.
NPS_SONAR_NOISE_STD_DEV
#define NPS_SONAR_NOISE_STD_DEV 0.01
standard devition in meters (default 1cm)
Definition at line 45 of file nps_sensor_sonar.c.
NPS_SONAR_OFFSET
#define NPS_SONAR_OFFSET 0
Definition at line 49 of file nps_sensor_sonar.c.
Function Documentation
nps_sensor_sonar_init()
void nps_sensor_sonar_init (struct NpsSensorSonar * sonar, double time)
Definition at line 60 of file nps_sensor_sonar.c.
References FALSE, NPS_SONAR_NOISE_STD_DEV, NPS_SONAR_OFFSET, sonar, and time.
Referenced by nps_sensors_init().
nps_sensor_sonar_run_step()
void nps_sensor_sonar_run_step (struct NpsSensorSonar * sonar, double time)
Definition at line 70 of file nps_sensor_sonar.c.
References NpsFdm::agl, fdm, foo, get_gaussian_noise(), NPS_SONAR_DT, NPS_SONAR_MAX_DIST, NPS_SONAR_MIN_DIST, sonar, and TRUE.
Referenced by nps_sensors_run_step().