Paparazzi UAS: sw/simulator/nps/nps_radio_control.h File Reference
nps_radio_control.h File Reference
#include "std.h"
Data Structures
struct NpsRadioControl
Macros
#define MODE_SWITCH_MANUAL -1.0
#define MODE_SWITCH_AUTO1 0.0
#define MODE_SWITCH_AUTO2 1.0
Enumerations
enum NpsRadioControlType { SCRIPT , JOYSTICK , SPEKTRUM , NORC }
Functions
void nps_radio_control_init (enum NpsRadioControlType type, int num_script, char *js_dev)
bool nps_radio_control_available (double time)
Variables
struct NpsRadioControl nps_radio_control
Data Structure Documentation
NpsRadioControl
struct NpsRadioControl
Definition at line 42 of file nps_radio_control.h.
Data Fields
char * js_dev
double mode
double next_update
int num_script
double pitch
double roll
double throttle
enum NpsRadioControlType type
bool valid
double yaw
Macro Definition Documentation
MODE_SWITCH_AUTO1
#define MODE_SWITCH_AUTO1 0.0
Definition at line 28 of file nps_radio_control.h.
MODE_SWITCH_AUTO2
#define MODE_SWITCH_AUTO2 1.0
Definition at line 29 of file nps_radio_control.h.
MODE_SWITCH_MANUAL
#define MODE_SWITCH_MANUAL -1.0
Definition at line 27 of file nps_radio_control.h.
Enumeration Type Documentation
NpsRadioControlType
enum NpsRadioControlType
Enumerator
SCRIPT
JOYSTICK
SPEKTRUM
NORC
Definition at line 31 of file nps_radio_control.h.
Function Documentation
nps_radio_control_available()
bool nps_radio_control_available (double time) extern
Definition at line 81 of file nps_radio_control.c.
References FALSE, JOYSTICK, NpsRadioControl::mode, NpsJoystick::mode, NpsRadioControl::next_update, NORC, nps_joystick, nps_radio_control, nps_radio_control_joystick_update(), NpsRadioControl::num_script, NpsRadioControl::pitch, NpsJoystick::pitch, RADIO_CONTROL_DT, radio_control_script_takeoff(), RADIO_CONTROL_TAKEOFF_TIME, NpsRadioControl::roll, NpsJoystick::roll, SCRIPT, scripts, NpsRadioControl::throttle, NpsJoystick::throttle, time, TRUE, NpsRadioControl::type, NpsRadioControl::yaw, and NpsJoystick::yaw.
Referenced by nps_autopilot_run_step().
nps_radio_control_init()
void nps_radio_control_init (enum NpsRadioControlType type, int num_script, char * js_dev) extern
Definition at line 35 of file nps_radio_control.c.
References JOYSTICK, NpsRadioControl::js_dev, NpsRadioControl::next_update, NORC, nps_radio_control, nps_radio_control_joystick_init(), nps_radio_control_spektrum_init(), NpsRadioControl::num_script, SCRIPT, SPEKTRUM, and NpsRadioControl::type.
Referenced by nps_autopilot_init(), and nps_autopilot_init().
Variable Documentation
nps_radio_control
struct NpsRadioControl nps_radio_control extern
Definition at line 31 of file nps_radio_control.c.
Referenced by handle_frame(), nps_radio_control_available(), nps_radio_control_init(), radio_control_feed(), radio_control_script_ff(), radio_control_script_hover(), radio_control_script_step_pitch(), radio_control_script_step_roll(), radio_control_script_step_yaw(), and radio_control_script_takeoff().