Paparazzi UAS: sw/simulator/nps/nps_atmosphere.c File Reference
nps_atmosphere.c File Reference
Atmosphere model (pressure, wind) for NPS.
#include "nps_atmosphere.h"
#include "nps_fdm.h"
#include "nps_ivy.h"
Macros
#define NPS_QNH 101325.0
#define NPS_WIND_SPEED 0.0
#define NPS_WIND_DIR 0
#define NPS_TURBULENCE_SEVERITY 0
#define NPS_WORLD_ENV_UPDATE 1.0
Functions
void nps_atmosphere_init (void)
void nps_atmosphere_set_wind_speed (double speed)
void nps_atmosphere_set_wind_dir (double dir)
void nps_atmosphere_set_wind_ned (double wind_north, double wind_east, double wind_down)
void nps_atmosphere_update (double dt)
Variables
struct NpsAtmosphere nps_atmosphere
Detailed Description
Atmosphere model (pressure, wind) for NPS.
Definition in file nps_atmosphere.c.
Macro Definition Documentation
NPS_QNH
#define NPS_QNH 101325.0
Definition at line 32 of file nps_atmosphere.c.
NPS_TURBULENCE_SEVERITY
#define NPS_TURBULENCE_SEVERITY 0
Definition at line 44 of file nps_atmosphere.c.
NPS_WIND_DIR
#define NPS_WIND_DIR 0
Definition at line 40 of file nps_atmosphere.c.
NPS_WIND_SPEED
#define NPS_WIND_SPEED 0.0
Definition at line 36 of file nps_atmosphere.c.
NPS_WORLD_ENV_UPDATE
#define NPS_WORLD_ENV_UPDATE 1.0
Definition at line 48 of file nps_atmosphere.c.
Function Documentation
nps_atmosphere_init()
void nps_atmosphere_init (void)
Definition at line 53 of file nps_atmosphere.c.
References FLOAT_VECT3_ZERO, NpsAtmosphere::last_world_env_req, nps_atmosphere, nps_atmosphere_set_wind_dir(), nps_atmosphere_set_wind_speed(), NPS_QNH, NPS_TURBULENCE_SEVERITY, NPS_WIND_DIR, NPS_WIND_SPEED, NpsAtmosphere::qnh, NpsAtmosphere::turbulence_severity, and NpsAtmosphere::wind.
Referenced by nps_main_init().
nps_atmosphere_set_wind_dir()
void nps_atmosphere_set_wind_dir (double dir)
Definition at line 71 of file nps_atmosphere.c.
References dir, foo, nps_atmosphere, NpsAtmosphere::wind, NpsAtmosphere::wind_dir, NpsAtmosphere::wind_speed, DoubleVect3::x, and DoubleVect3::y.
Referenced by nps_atmosphere_init().
nps_atmosphere_set_wind_ned()
void nps_atmosphere_set_wind_ned (double wind_north, double wind_east, double wind_down)
Definition at line 83 of file nps_atmosphere.c.
References dir, FLOAT_VECT2_NORM, foo, nps_atmosphere, NpsAtmosphere::wind, NpsAtmosphere::wind_dir, NpsAtmosphere::wind_speed, DoubleVect3::x, DoubleVect3::y, and DoubleVect3::z.
Referenced by nps_flightgear_receive(), and on_WORLD_ENV().
nps_atmosphere_set_wind_speed()
void nps_atmosphere_set_wind_speed (double speed)
Definition at line 63 of file nps_atmosphere.c.
References foo, nps_atmosphere, NpsAtmosphere::wind, NpsAtmosphere::wind_dir, NpsAtmosphere::wind_speed, DoubleVect3::x, and DoubleVect3::y.
Referenced by nps_atmosphere_init().
nps_atmosphere_update()
void nps_atmosphere_update (double dt)
Definition at line 98 of file nps_atmosphere.c.
References foo, NpsAtmosphere::last_world_env_req, nps_atmosphere, nps_fdm_set_turbulence(), nps_fdm_set_wind_ned(), nps_ivy_send_world_env, NPS_WORLD_ENV_UPDATE, NpsAtmosphere::turbulence_severity, NpsAtmosphere::wind, NpsAtmosphere::wind_speed, DoubleVect3::x, DoubleVect3::y, and DoubleVect3::z.
Referenced by nps_main_run_sim_step().
Variable Documentation
nps_atmosphere
struct NpsAtmosphere nps_atmosphere
Definition at line 51 of file nps_atmosphere.c.
Referenced by nps_atmosphere_init(), nps_atmosphere_set_wind_dir(), nps_atmosphere_set_wind_ned(), nps_atmosphere_set_wind_speed(), and nps_atmosphere_update().