Paparazzi UAS: sw/simulator/nps/nps_sensor_temperature.c File Reference
nps_sensor_temperature.c File Reference
#include "nps_sensor_temperature.h"
#include "generated/airframe.h"
#include "std.h"
#include "nps_fdm.h"
#include "nps_random.h"
#include "nps_sensors.h"
Macros
#define NPS_TEMPERATURE_DT 0.01
10Hz default
#define NPS_TEMPERATURE_NOISE_STD_DEV 0.1
Functions
void nps_sensor_temperature_init (struct NpsSensorTemperature *temperature, double time)
void nps_sensor_temperature_run_step (struct NpsSensorTemperature *temperature, double time)
Macro Definition Documentation
NPS_TEMPERATURE_DT
#define NPS_TEMPERATURE_DT 0.01
10Hz default
Definition at line 12 of file nps_sensor_temperature.c.
NPS_TEMPERATURE_NOISE_STD_DEV
#define NPS_TEMPERATURE_NOISE_STD_DEV 0.1
Definition at line 16 of file nps_sensor_temperature.c.
Function Documentation
nps_sensor_temperature_init()
void nps_sensor_temperature_init (struct NpsSensorTemperature * temperature, double time)
Definition at line 19 of file nps_sensor_temperature.c.
References NpsSensorTemperature::data_available, FALSE, NpsSensorTemperature::next_update, NpsSensorTemperature::noise_std_dev, NPS_TEMPERATURE_NOISE_STD_DEV, time, and NpsSensorTemperature::value.
Referenced by nps_sensors_init().
nps_sensor_temperature_run_step()
void nps_sensor_temperature_run_step (struct NpsSensorTemperature * temperature, double time)
Definition at line 28 of file nps_sensor_temperature.c.
References NpsSensorTemperature::data_available, fdm, foo, get_gaussian_noise(), NpsSensorTemperature::next_update, NpsSensorTemperature::noise_std_dev, NPS_TEMPERATURE_DT, NpsFdm::temperature, TRUE, and NpsSensorTemperature::value.
Referenced by nps_sensors_run_step().