Paparazzi UAS: sw/simulator/nps/nps_sensor_gyro.h File Reference
nps_sensor_gyro.h File Reference
#include "math/pprz_algebra.h"
#include "math/pprz_algebra_double.h"
#include "math/pprz_algebra_float.h"
#include "std.h"
Data Structures
struct NpsSensorGyro
Functions
void nps_sensor_gyro_init (struct NpsSensorGyro *gyro, double time)
void nps_sensor_gyro_run_step (struct NpsSensorGyro *gyro, double time, struct DoubleRMat *body_to_imu)
Data Structure Documentation
NpsSensorGyro
struct NpsSensorGyro
Definition at line 9 of file nps_sensor_gyro.h.
Data Fields
struct DoubleVect3 bias_initial
struct DoubleVect3 bias_random_walk_std_dev
struct DoubleVect3 bias_random_walk_value
bool data_available
int max
int min
struct DoubleVect3 neutral
double next_update
struct DoubleVect3 noise_std_dev
struct DoubleMat33 sensitivity
struct DoubleVect3 value
Function Documentation
nps_sensor_gyro_init()
void nps_sensor_gyro_init (struct NpsSensorGyro * gyro, double time) extern
Definition at line 9 of file nps_sensor_gyro.c.
References NpsSensorGyro::bias_initial, NpsSensorGyro::bias_random_walk_std_dev, NpsSensorGyro::bias_random_walk_value, NpsSensorGyro::data_available, FALSE, FLOAT_MAT33_DIAG, FLOAT_VECT3_ZERO, foo, NpsSensorGyro::max, NpsSensorGyro::min, NpsSensorGyro::neutral, NpsSensorGyro::next_update, NpsSensorGyro::noise_std_dev, NpsSensorGyro::sensitivity, time, NpsSensorGyro::value, and VECT3_ASSIGN.
Referenced by nps_sensors_init().
nps_sensor_gyro_run_step()
void nps_sensor_gyro_run_step (struct NpsSensorGyro * gyro, double time, struct DoubleRMat * body_to_imu) extern
Definition at line 33 of file nps_sensor_gyro.c.
References NpsSensorGyro::bias_initial, NpsSensorGyro::bias_random_walk_std_dev, NpsSensorGyro::bias_random_walk_value, NpsFdm::body_inertial_rotvel, NpsSensorGyro::data_available, double_vect3_add_gaussian_noise(), DOUBLE_VECT3_ROUND, double_vect3_update_random_walk(), fdm, foo, DoubleMat33::m, MAT33_VECT3_MUL, NpsSensorGyro::max, NpsSensorGyro::min, NpsSensorGyro::neutral, NpsSensorGyro::next_update, NpsSensorGyro::noise_std_dev, NpsSensorGyro::sensitivity, TRUE, NpsSensorGyro::value, VECT3_ADD, VECT3_BOUND_CUBE, VECT3_COPY, and VECT3_EW_MUL.
Referenced by nps_sensors_run_step().