Paparazzi UAS: sw/simulator/nps/nps_sensor_gps.c File Reference
nps_sensor_gps.c File Reference
#include "nps_sensor_gps.h"
#include <stdio.h>
#include "generated/airframe.h"
#include "nps_fdm.h"
#include "nps_random.h"
#include "nps_sensors_utils.h"
#include "nps_sensors.h"
Functions
void nps_sensor_gps_init (struct NpsSensorGps *gps, double time)
void nps_sensor_gps_run_step (struct NpsSensorGps *gps, double time)
Function Documentation
nps_sensor_gps_init()
void nps_sensor_gps_init (struct NpsSensorGps * gps, double time)
Definition at line 10 of file nps_sensor_gps.c.
References GpsState::ecef_pos, GpsState::ecef_vel, FALSE, FLOAT_VECT3_ZERO, foo, gps, GpsState::hmsl, time, and VECT3_ASSIGN.
Referenced by nps_sensors_init().
nps_sensor_gps_run_step()
void nps_sensor_gps_run_step (struct NpsSensorGps * gps, double time)
Definition at line 39 of file nps_sensor_gps.c.
References double_vect3_add_gaussian_noise(), double_vect3_update_random_walk(), NpsFdm::ecef_ecef_vel, GpsState::ecef_pos, NpsFdm::ecef_pos, GpsState::ecef_vel, fdm, foo, gps, GpsState::hmsl, NpsFdm::hmsl, lla_of_ecef_d(), GpsState::lla_pos, time, TRUE, UpdateSensorLatency(), UpdateSensorLatency_Single(), VECT3_ADD, and VECT3_COPY.
Referenced by nps_sensors_run_step().