Paparazzi UAS: sw/simulator/nps/nps_main_common.c File Reference
nps_main_common.c File Reference
#include "nps_main.h"
#include <signal.h>
#include <stdio.h>
#include <getopt.h>
#include "nps_flightgear.h"
#include "nps_ivy.h"
Functions
void tstp_hdl (int n)
void cont_hdl (int n)
double time_to_double (struct timeval *t)
double ntime_to_double (struct timespec *t)
int nps_main_init (int argc, char **argv)
void nps_set_time_factor (float time_factor)
bool nps_main_parse_options (int argc, char **argv)
void * nps_flight_gear_loop (void *data)
void * nps_main_display (void *data)
Variables
pthread_t th_flight_gear
pthread_t th_display_ivy
pthread_t th_main_loop
pthread_mutex_t fdm_mutex
int pauseSignal
struct NpsMain nps_main
Function Documentation
cont_hdl()
void cont_hdl (int n)
Definition at line 68 of file nps_main_common.c.
References cont_hdl(), foo, and tstp_hdl().
Referenced by cont_hdl(), and nps_main_init().
nps_flight_gear_loop()
void * nps_flight_gear_loop (void * data)
Definition at line 265 of file nps_main_common.c.
References clock_get_current_time, DISPLAY_DT, fdm_mutex, NpsMain::fg_fdm, NpsMain::fg_host, NpsMain::fg_port, NpsMain::fg_port_in, NpsMain::fg_time_offset, foo, nps_flightgear_init(), nps_flightgear_send(), nps_flightgear_send_fdm(), nps_main, and TRUE.
Referenced by main().
nps_main_display()
void * nps_main_display (void * data)
Definition at line 313 of file nps_main_common.c.
References clock_get_current_time, DISPLAY_DT, fdm, foo, NpsMain::ivy_bus, NpsMain::nodisplay, nps_ivy_display(), nps_ivy_init(), nps_main, sensors, and TRUE.
Referenced by main().
nps_main_init()
int nps_main_init (int argc, char ** argv)
Definition at line 86 of file nps_main_common.c.
References cont_hdl(), NpsMain::display_time, foo, NpsMain::host_time_factor, nps_atmosphere_init(), nps_fdm_init(), nps_main, nps_main_parse_options(), nps_radio_and_autopilot_init(), nps_sensors_init(), pauseSignal, NpsMain::real_initial_time, NpsMain::scaled_initial_time, SIM_DT, NpsMain::sim_time, time_to_double(), and tstp_hdl().
Referenced by main().
nps_main_parse_options()
bool nps_main_parse_options (int argc, char ** argv)
Definition at line 154 of file nps_main_common.c.
References NpsMain::fg_fdm, NpsMain::fg_host, NpsMain::fg_port, NpsMain::fg_port_in, NpsMain::fg_time_offset, foo, NpsMain::host_time_factor, NpsMain::ivy_bus, NpsMain::js_dev, NpsMain::nodisplay, NpsMain::norc, nps_main, NpsMain::rc_script, NpsMain::spektrum_dev, TRUE, and usage().
Referenced by nps_main_init().
nps_set_time_factor()
void nps_set_time_factor (float time_factor)
Definition at line 126 of file nps_main_common.c.
References foo, NpsMain::host_time_factor, nps_main, NpsMain::scaled_initial_time, and time_to_double().
Referenced by on_WORLD_ENV().
ntime_to_double()
double ntime_to_double (struct timespec * t)
Definition at line 81 of file nps_main_common.c.
References foo.
Referenced by nps_main_loop().
time_to_double()
double time_to_double (struct timeval * t)
Definition at line 76 of file nps_main_common.c.
References foo.
Referenced by nps_main_init(), nps_main_loop(), and nps_set_time_factor().
tstp_hdl()
void tstp_hdl (int n)
Definition at line 56 of file nps_main_common.c.
References foo, and pauseSignal.
Referenced by cont_hdl(), and nps_main_init().
Variable Documentation
fdm_mutex
pthread_mutex_t fdm_mutex
Definition at line 36 of file nps_main_common.c.
Referenced by nps_ap_data_loop(), nps_flight_gear_loop(), nps_flightgear_receive(), nps_ivy_display(), nps_main_loop(), and nps_sensors_loop().
nps_main
struct NpsMain nps_main
Definition at line 38 of file nps_main_common.c.
Referenced by main(), nps_flight_gear_loop(), nps_main_display(), nps_main_init(), nps_main_loop(), nps_main_parse_options(), nps_main_run_sim_step(), nps_radio_and_autopilot_init(), nps_sensors_loop(), and nps_set_time_factor().
pauseSignal
int pauseSignal
Definition at line 37 of file nps_main_common.c.
Referenced by nps_main_init(), nps_main_loop(), and tstp_hdl().
th_display_ivy
pthread_t th_display_ivy
Definition at line 34 of file nps_main_common.c.
Referenced by main().
th_flight_gear
pthread_t th_flight_gear
Definition at line 33 of file nps_main_common.c.
Referenced by main().
th_main_loop
pthread_t th_main_loop
Definition at line 35 of file nps_main_common.c.
Referenced by main().