Paparazzi UAS: sw/simulator/nps/nps_ivy.c File Reference
nps_ivy.c File Reference
#include "nps_ivy.h"
#include <stdlib.h>
#include <stdio.h>
#include <sys/types.h>
#include <unistd.h>
#include <Ivy/ivy.h>
#include <Ivy/ivyloop.h>
#include <Ivy/timer.h>
#include "generated/airframe.h"
#include "math/pprz_algebra_float.h"
#include "math/pprz_algebra_double.h"
#include "nps_main.h"
#include "nps_autopilot.h"
#include "nps_fdm.h"
#include "nps_sensors.h"
#include "nps_atmosphere.h"
#include "generated/settings.h"
#include "pprzlink/dl_protocol.h"
#include "modules/datalink/downlink.h"
#include "modules/gps/gps.h"
Macros
#define NPS_IVY_DISPLAY_PERIOD_MS ((long)(3 * DISPLAY_DT * 1000))
Functions
static void on_WORLD_ENV (IvyClientPtr app, void *user_data, int argc, char *argv[])
static void on_DL_SETTING (IvyClientPtr app, void *user_data, int argc, char *argv[])
int find_launch_index (void)
static void nps_ivy_display_cb (TimerId id, void *user_data, unsigned long delta)
void nps_ivy_init (char *ivy_bus, bool nodisplay)
void nps_ivy_send_WORLD_ENV_REQ (void)
void nps_ivy_display (struct NpsFdm *fdm_data, struct NpsSensors *sensors_data)
void nps_ivy_run (void)
Variables
bool nps_ivy_send_world_env = false
static MsgRcvPtr ivyPtr = NULL
static int seq = 1
static int ap_launch_index
static TimerId nps_ivy_display_timer = NULL
Macro Definition Documentation
NPS_IVY_DISPLAY_PERIOD_MS
#define NPS_IVY_DISPLAY_PERIOD_MS ((long)(3 * DISPLAY_DT * 1000))
Definition at line 45 of file nps_ivy.c.
Function Documentation
find_launch_index()
int find_launch_index (void)
Definition at line 177 of file nps_ivy.c.
References foo, and idx.
Referenced by nps_ivy_init().
nps_ivy_display()
void nps_ivy_display (struct NpsFdm * fdm_data, struct NpsSensors * sensors_data)
Definition at line 237 of file nps_ivy.c.
References double_quat_vmult(), fdm, fdm_mutex, foo, nps_ivy_send_world_env, nps_ivy_send_WORLD_ENV_REQ(), RATE_FLOAT_OF_BFP, and sensors.
Referenced by nps_ivy_display_cb().
nps_ivy_display_cb()
static void nps_ivy_display_cb (TimerId id, void * user_data, unsigned long delta) static
Definition at line 60 of file nps_ivy.c.
References fdm, foo, nps_ivy_display(), NPS_IVY_DISPLAY_PERIOD_MS, and sensors.
Referenced by nps_ivy_init().
nps_ivy_init()
void nps_ivy_init (char * ivy_bus, bool nodisplay)
Definition at line 73 of file nps_ivy.c.
References ap_launch_index, find_launch_index(), foo, nps_ivy_display_cb(), NPS_IVY_DISPLAY_PERIOD_MS, nps_ivy_display_timer, nps_ivy_send_world_env, on_DL_SETTING(), and on_WORLD_ENV().
Referenced by nps_main_display().
nps_ivy_run()
void nps_ivy_run (void)
Definition at line 311 of file nps_ivy.c.
References foo.
Referenced by nps_main_display().
nps_ivy_send_WORLD_ENV_REQ()
void nps_ivy_send_WORLD_ENV_REQ (void)
Definition at line 147 of file nps_ivy.c.
References fdm, fdm_mutex, foo, ivyPtr, on_WORLD_ENV(), and seq.
Referenced by nps_ivy_display().
on_DL_SETTING()
static void on_DL_SETTING (IvyClientPtr app, void * user_data, int argc, char * argv[]) static
Definition at line 198 of file nps_ivy.c.
References ap_launch_index, DefaultChannel, DefaultDevice, foo, and nps_update_launch_from_dl().
Referenced by nps_ivy_init().
on_WORLD_ENV()
static void on_WORLD_ENV (IvyClientPtr app, void * user_data, int argc, char * argv[]) static
Definition at line 114 of file nps_ivy.c.
References foo, gps_has_fix, nps_atmosphere_set_wind_ned(), nps_set_time_factor(), FloatVect3::x, FloatVect3::y, and FloatVect3::z.
Referenced by nps_ivy_init(), and nps_ivy_send_WORLD_ENV_REQ().
Variable Documentation
ap_launch_index
int ap_launch_index static
Definition at line 32 of file nps_ivy.c.
Referenced by nps_ivy_init(), and on_DL_SETTING().
ivyPtr
MsgRcvPtr ivyPtr = NULL static
Definition at line 30 of file nps_ivy.c.
Referenced by nps_ivy_send_WORLD_ENV_REQ().
nps_ivy_display_timer
TimerId nps_ivy_display_timer = NULL static
Definition at line 48 of file nps_ivy.c.
Referenced by nps_ivy_init().
nps_ivy_send_world_env
bool nps_ivy_send_world_env = false
Definition at line 29 of file nps_ivy.c.
Referenced by nps_atmosphere_update(), nps_ivy_display(), and nps_ivy_init().
seq
int seq = 1 static
Definition at line 31 of file nps_ivy.c.
Referenced by escape_process(), mavlink_send_block(), mavlink_send_wp(), and nps_ivy_send_WORLD_ENV_REQ().