Paparazzi UAS: sw/simulator/nps/nps_random.c File Reference
nps_random.c File Reference
#include "nps_random.h"
#include <math.h>
#include <limits.h>
#include <gsl/gsl_rng.h>
#include <gsl/gsl_randist.h>
#include <stdlib.h>
Functions
void double_vect3_add_gaussian_noise (struct DoubleVect3 *vect, struct DoubleVect3 *std_dev)
void float_vect3_add_gaussian_noise (struct FloatVect3 *vect, struct FloatVect3 *std_dev)
void float_rates_add_gaussian_noise (struct FloatRates *vect, struct FloatRates *std_dev)
void double_vect3_get_gaussian_noise (struct DoubleVect3 *vect, struct DoubleVect3 *std_dev)
void double_vect3_update_random_walk (struct DoubleVect3 *rw, struct DoubleVect3 *std_dev, double dt, double thau)
double get_gaussian_noise (void)
Function Documentation
double_vect3_add_gaussian_noise()
void double_vect3_add_gaussian_noise (struct DoubleVect3 * vect, struct DoubleVect3 * std_dev)
Definition at line 34 of file nps_random.c.
References foo, get_gaussian_noise(), DoubleVect3::x, DoubleVect3::y, and DoubleVect3::z.
Referenced by nps_sensor_accel_run_step(), nps_sensor_gps_run_step(), and nps_sensor_gyro_run_step().
double_vect3_get_gaussian_noise()
void double_vect3_get_gaussian_noise (struct DoubleVect3 * vect, struct DoubleVect3 * std_dev)
Definition at line 57 of file nps_random.c.
References foo, get_gaussian_noise(), DoubleVect3::x, DoubleVect3::y, and DoubleVect3::z.
Referenced by double_vect3_update_random_walk().
double_vect3_update_random_walk()
void double_vect3_update_random_walk (struct DoubleVect3 * rw, struct DoubleVect3 * std_dev, double dt, double thau)
Definition at line 65 of file nps_random.c.
References double_vect3_get_gaussian_noise(), foo, VECT3_ADD, and VECT3_SMUL.
Referenced by nps_sensor_gps_run_step(), and nps_sensor_gyro_run_step().
float_rates_add_gaussian_noise()
void float_rates_add_gaussian_noise (struct FloatRates * vect, struct FloatRates * std_dev)
Definition at line 48 of file nps_random.c.
References foo, get_gaussian_noise(), FloatRates::p, FloatRates::q, and FloatRates::r.
float_vect3_add_gaussian_noise()
void float_vect3_add_gaussian_noise (struct FloatVect3 * vect, struct FloatVect3 * std_dev)
Definition at line 41 of file nps_random.c.
References foo, get_gaussian_noise(), FloatVect3::x, FloatVect3::y, and FloatVect3::z.
get_gaussian_noise()
double get_gaussian_noise (void)
Definition at line 109 of file nps_random.c.
References foo.
Referenced by double_vect3_add_gaussian_noise(), double_vect3_get_gaussian_noise(), float_rates_add_gaussian_noise(), float_vect3_add_gaussian_noise(), nps_sensor_airspeed_run_step(), nps_sensor_aoa_run_step(), nps_sensor_baro_run_step(), nps_sensor_sideslip_run_step(), nps_sensor_sonar_run_step(), and nps_sensor_temperature_run_step().