Paparazzi UAS: sw/simulator/nps/nps_radio_control.c File Reference
nps_radio_control.c File Reference
#include "nps_radio_control.h"
#include "nps_radio_control_spektrum.h"
#include "nps_radio_control_joystick.h"
#include <stdio.h>
Macros
#define RADIO_CONTROL_DT (1./40.)
#define RADIO_CONTROL_TAKEOFF_TIME 8
Typedefs
typedef void(* rc_script) (double)
Functions
void nps_radio_control_init (enum NpsRadioControlType type, int num_script, char *js_dev)
static void radio_control_script_takeoff (double time)
static void radio_control_script_hover (double time)
static void radio_control_script_step_roll (double time)
static void radio_control_script_step_pitch (double time)
static void radio_control_script_step_yaw (double time)
static void radio_control_script_ff (double time)
bool nps_radio_control_available (double time)
Variables
struct NpsRadioControl nps_radio_control
static rc_script scripts []
Macro Definition Documentation
RADIO_CONTROL_DT
#define RADIO_CONTROL_DT (1./40.)
Definition at line 29 of file nps_radio_control.c.
RADIO_CONTROL_TAKEOFF_TIME
#define RADIO_CONTROL_TAKEOFF_TIME 8
Definition at line 78 of file nps_radio_control.c.
Typedef Documentation
rc_script
typedef void(* rc_script) (double)
Definition at line 60 of file nps_radio_control.c.
Function Documentation
nps_radio_control_available()
bool nps_radio_control_available (double time)
Definition at line 81 of file nps_radio_control.c.
References FALSE, JOYSTICK, NpsRadioControl::mode, NpsJoystick::mode, NpsRadioControl::next_update, NORC, nps_joystick, nps_radio_control, nps_radio_control_joystick_update(), NpsRadioControl::num_script, NpsRadioControl::pitch, NpsJoystick::pitch, RADIO_CONTROL_DT, radio_control_script_takeoff(), RADIO_CONTROL_TAKEOFF_TIME, NpsRadioControl::roll, NpsJoystick::roll, SCRIPT, scripts, NpsRadioControl::throttle, NpsJoystick::throttle, time, TRUE, NpsRadioControl::type, NpsRadioControl::yaw, and NpsJoystick::yaw.
Referenced by nps_autopilot_run_step().
nps_radio_control_init()
void nps_radio_control_init (enum NpsRadioControlType type, int num_script, char * js_dev)
Definition at line 35 of file nps_radio_control.c.
References JOYSTICK, NpsRadioControl::js_dev, NpsRadioControl::next_update, NORC, nps_radio_control, nps_radio_control_joystick_init(), nps_radio_control_spektrum_init(), NpsRadioControl::num_script, SCRIPT, SPEKTRUM, and NpsRadioControl::type.
Referenced by nps_autopilot_init(), and nps_autopilot_init().
radio_control_script_ff()
void radio_control_script_ff (double time) static
Definition at line 181 of file nps_radio_control.c.
References NpsRadioControl::mode, MODE_SWITCH_AUTO2, nps_radio_control, NpsRadioControl::pitch, RADIO_CONTROL_TAKEOFF_TIME, NpsRadioControl::roll, NpsRadioControl::throttle, and time.
radio_control_script_hover()
void radio_control_script_hover (double time) static
Definition at line 131 of file nps_radio_control.c.
References NpsRadioControl::mode, MODE_SWITCH_AUTO2, nps_radio_control, NpsRadioControl::roll, NpsRadioControl::throttle, and NpsRadioControl::yaw.
radio_control_script_step_pitch()
void radio_control_script_step_pitch (double time) static
Definition at line 154 of file nps_radio_control.c.
References foo, NpsRadioControl::mode, MODE_SWITCH_AUTO2, nps_radio_control, NpsRadioControl::pitch, NpsRadioControl::roll, NpsRadioControl::throttle, time, and NpsRadioControl::yaw.
radio_control_script_step_roll()
void radio_control_script_step_roll (double time) static
Definition at line 140 of file nps_radio_control.c.
References foo, NpsRadioControl::mode, MODE_SWITCH_AUTO2, nps_radio_control, NpsRadioControl::roll, NpsRadioControl::throttle, time, and NpsRadioControl::yaw.
radio_control_script_step_yaw()
void radio_control_script_step_yaw (double time) static
Definition at line 167 of file nps_radio_control.c.
References foo, NpsRadioControl::mode, MODE_SWITCH_AUTO2, nps_radio_control, NpsRadioControl::pitch, NpsRadioControl::roll, NpsRadioControl::throttle, time, and NpsRadioControl::yaw.
radio_control_script_takeoff()
void radio_control_script_takeoff (double time) static
Definition at line 115 of file nps_radio_control.c.
References NpsRadioControl::mode, MODE_SWITCH_MANUAL, nps_radio_control, NpsRadioControl::pitch, NpsRadioControl::roll, NpsRadioControl::throttle, time, and NpsRadioControl::yaw.
Referenced by nps_radio_control_available().
Variable Documentation
nps_radio_control
struct NpsRadioControl nps_radio_control
Definition at line 31 of file nps_radio_control.c.
Referenced by handle_frame(), nps_radio_control_available(), nps_radio_control_init(), radio_control_feed(), radio_control_script_ff(), radio_control_script_hover(), radio_control_script_step_pitch(), radio_control_script_step_roll(), radio_control_script_step_yaw(), and radio_control_script_takeoff().
scripts
rc_script scripts[] static
Initial value:
= {
  radio_control_script_hover,
  radio_control_script_step_roll,
  radio_control_script_step_pitch,
  radio_control_script_step_yaw,
  radio_control_script_ff
}
Definition at line 69 of file nps_radio_control.c.
Referenced by nps_radio_control_available().