Paparazzi UAS: sw/simulator/nps/nps_main_sitl.c File Reference
nps_main_sitl.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/time.h>
#include "nps_main.h"
#include "nps_fdm.h"
Functions
int main (int argc, char **argv)
void nps_update_launch_from_dl (uint8_t value)
void nps_radio_and_autopilot_init (void)
void nps_main_run_sim_step (void)
void * nps_main_loop (void *data)
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 35 of file nps_main_sitl.c.
References NpsMain::fg_host, foo, nps_flight_gear_loop(), nps_main, nps_main_display(), nps_main_init(), nps_main_loop(), th_display_ivy, th_flight_gear, and th_main_loop.
nps_main_loop()
void * nps_main_loop (void * data)
Definition at line 89 of file nps_main_sitl.c.
References clock_get_current_time, NpsMain::display_time, fdm, fdm_mutex, foo, NpsMain::host_time_factor, HOST_TIMEOUT_MS, nps_main, nps_main_run_sim_step(), ntime_to_double(), pauseSignal, NpsMain::real_initial_time, NpsMain::scaled_initial_time, SIM_DT, NpsMain::sim_time, t1, NpsFdm::time, time_to_double(), and TRUE.
Referenced by main().
nps_main_run_sim_step()
void nps_main_run_sim_step (void)
Definition at line 74 of file nps_main_sitl.c.
References NpsAutopilot::commands, NpsAutopilot::launch, nps_atmosphere_update(), nps_autopilot, nps_autopilot_run_step(), nps_autopilot_run_systime_step(), NPS_COMMANDS_NB, nps_fdm_run_step(), nps_main, nps_sensors_run_step(), SIM_DT, and NpsMain::sim_time.
Referenced by nps_main_loop().
nps_radio_and_autopilot_init()
void nps_radio_and_autopilot_init (void)
Definition at line 55 of file nps_main_sitl.c.
References foo, JOYSTICK, NpsMain::js_dev, NpsMain::norc, NORC, nps_autopilot_init(), nps_main, NpsMain::rc_script, SCRIPT, SPEKTRUM, and NpsMain::spektrum_dev.
Referenced by nps_main_init().
nps_update_launch_from_dl()
void nps_update_launch_from_dl (uint8_t value)
Definition at line 52 of file nps_main_sitl.c.
References foo, NpsAutopilot::launch, and nps_autopilot.
Referenced by on_DL_SETTING().