Paparazzi UAS: sw/simulator/nps/nps_sensor_airspeed.c File Reference
nps_sensor_airspeed.c File Reference
Simulated airspeed for NPS simulator.
#include "nps_sensor_airspeed.h"
#include "generated/airframe.h"
#include "std.h"
#include "nps_fdm.h"
#include "nps_random.h"
#include "nps_sensors.h"
Macros
#define NPS_AIRSPEED_DT 0.01
10Hz default
#define NPS_AIRSPEED_NOISE_STD_DEV 0.1
standard deviation in meters/second (default 0.1 m/s)
#define NPS_AIRSPEED_OFFSET 0
Functions
void nps_sensor_airspeed_init (struct NpsSensorAirspeed *airspeed, double time)
void nps_sensor_airspeed_run_step (struct NpsSensorAirspeed *airspeed, double time)
Detailed Description
Simulated airspeed for NPS simulator.
Definition in file nps_sensor_airspeed.c.
Macro Definition Documentation
NPS_AIRSPEED_DT
#define NPS_AIRSPEED_DT 0.01
10Hz default
Definition at line 40 of file nps_sensor_airspeed.c.
NPS_AIRSPEED_NOISE_STD_DEV
#define NPS_AIRSPEED_NOISE_STD_DEV 0.1
standard deviation in meters/second (default 0.1 m/s)
Definition at line 45 of file nps_sensor_airspeed.c.
NPS_AIRSPEED_OFFSET
#define NPS_AIRSPEED_OFFSET 0
Definition at line 49 of file nps_sensor_airspeed.c.
Function Documentation
nps_sensor_airspeed_init()
void nps_sensor_airspeed_init (struct NpsSensorAirspeed * airspeed, double time)
Definition at line 53 of file nps_sensor_airspeed.c.
References NpsSensorAirspeed::data_available, FALSE, NpsSensorAirspeed::next_update, NpsSensorAirspeed::noise_std_dev, NPS_AIRSPEED_NOISE_STD_DEV, NPS_AIRSPEED_OFFSET, NpsSensorAirspeed::offset, time, and NpsSensorAirspeed::value.
Referenced by nps_sensors_init().
nps_sensor_airspeed_run_step()
void nps_sensor_airspeed_run_step (struct NpsSensorAirspeed * airspeed, double time)
Definition at line 63 of file nps_sensor_airspeed.c.
References NpsFdm::airspeed, NpsSensorAirspeed::data_available, fdm, foo, get_gaussian_noise(), NpsSensorAirspeed::next_update, NpsSensorAirspeed::noise_std_dev, NPS_AIRSPEED_DT, NpsSensorAirspeed::offset, TRUE, and NpsSensorAirspeed::value.
Referenced by nps_sensors_run_step().