Paparazzi UAS: sw/simulator/nps/nps_sensor_temperature.h File Reference
nps_sensor_temperature.h File Reference
#include "math/pprz_algebra.h"
#include "math/pprz_algebra_double.h"
#include "math/pprz_algebra_float.h"
#include "std.h"
Data Structures
struct NpsSensorTemperature
Functions
void nps_sensor_temperature_init (struct NpsSensorTemperature *temperature, double time)
void nps_sensor_temperature_run_step (struct NpsSensorTemperature *temperature, double time)
Data Structure Documentation
NpsSensorTemperature
struct NpsSensorTemperature
Definition at line 9 of file nps_sensor_temperature.h.
Data Fields
bool data_available
double next_update
double noise_std_dev noise standard deviation
double value temperature in degrees Celcius
Function Documentation
nps_sensor_temperature_init()
void nps_sensor_temperature_init (struct NpsSensorTemperature * temperature, double time) extern
Definition at line 19 of file nps_sensor_temperature.c.
References NpsSensorTemperature::data_available, FALSE, NpsSensorTemperature::next_update, NpsSensorTemperature::noise_std_dev, NPS_TEMPERATURE_NOISE_STD_DEV, time, and NpsSensorTemperature::value.
Referenced by nps_sensors_init().
nps_sensor_temperature_run_step()
void nps_sensor_temperature_run_step (struct NpsSensorTemperature * temperature, double time) extern
Definition at line 28 of file nps_sensor_temperature.c.
References NpsSensorTemperature::data_available, fdm, foo, get_gaussian_noise(), NpsSensorTemperature::next_update, NpsSensorTemperature::noise_std_dev, NPS_TEMPERATURE_DT, NpsFdm::temperature, TRUE, and NpsSensorTemperature::value.
Referenced by nps_sensors_run_step().