Paparazzi UAS: sw/simulator/nps/nps_sensor_baro.h File Reference
nps_sensor_baro.h File Reference
#include "math/pprz_algebra.h"
#include "math/pprz_algebra_double.h"
#include "math/pprz_algebra_float.h"
#include "std.h"
Data Structures
struct NpsSensorBaro
Functions
void nps_sensor_baro_init (struct NpsSensorBaro *baro, double time)
void nps_sensor_baro_run_step (struct NpsSensorBaro *baro, double time)
Data Structure Documentation
struct NpsSensorBaro
Definition at line 9 of file nps_sensor_baro.h.
Data Fields
bool data_available
double next_update
double noise_std_dev noise standard deviation
double value pressure in Pascal
Function Documentation
void nps_sensor_baro_init (struct NpsSensorBaro * baro, double time)
Definition at line 14 of file nps_sensor_baro.c.
References NpsSensorBaro::data_available, FALSE, NpsSensorBaro::next_update, NpsSensorBaro::noise_std_dev, NPS_BARO_NOISE_STD_DEV, and NpsSensorBaro::value.
Referenced by nps_sensors_init().
void nps_sensor_baro_run_step (struct NpsSensorBaro * baro, double time)
Definition at line 23 of file nps_sensor_baro.c.
References NpsSensorBaro::data_available, fdm, get_gaussian_noise(), NpsSensorBaro::next_update, NpsSensorBaro::noise_std_dev, NpsFdm::pressure, TRUE, and NpsSensorBaro::value.
Referenced by nps_sensors_run_step().