Paparazzi UAS: sw/simulator/nps/nps_sensor_baro.c File Reference
nps_sensor_baro.c File Reference
#include "nps_sensor_baro.h"
#include "generated/airframe.h"
#include "std.h"
#include "nps_fdm.h"
#include "nps_random.h"
#include "nps_sensors.h"
Macros
#define NPS_BARO_NOISE_STD_DEV 0.
Functions
void nps_sensor_baro_init (struct NpsSensorBaro *baro, double time)
void nps_sensor_baro_run_step (struct NpsSensorBaro *baro, double time)
Macro Definition Documentation
NPS_BARO_NOISE_STD_DEV
#define NPS_BARO_NOISE_STD_DEV 0.
Definition at line 11 of file nps_sensor_baro.c.
Function Documentation
nps_sensor_baro_init()
void nps_sensor_baro_init (struct NpsSensorBaro * baro, double time)
Definition at line 14 of file nps_sensor_baro.c.
References NpsSensorBaro::data_available, FALSE, NpsSensorBaro::next_update, NpsSensorBaro::noise_std_dev, NPS_BARO_NOISE_STD_DEV, time, and NpsSensorBaro::value.
Referenced by nps_sensors_init().
nps_sensor_baro_run_step()
void nps_sensor_baro_run_step (struct NpsSensorBaro * baro, double time)
Definition at line 23 of file nps_sensor_baro.c.
References NpsSensorBaro::data_available, fdm, foo, get_gaussian_noise(), NpsSensorBaro::next_update, NpsSensorBaro::noise_std_dev, NpsFdm::pressure, TRUE, and NpsSensorBaro::value.
Referenced by nps_sensors_run_step().