Paparazzi UAS: sw/airborne/modules/obstacle_avoidance/obstacle_avoidance.h File Reference
obstacle_avoidance.h File Reference
Obstacle avoidance methods.
Functions
void serial_init (void)
void serial_update (void)
void serial_start (void)
void setAnglesMeasurements (float *anglesMeasurements, float *centersensorRad, float *fieldOfViewRad, uint16_t *size_matrix_local)
void pingpong_euler (float *distances_hor, float *horizontalAnglesMeasurements, int horizontalAmountOfMeasurements, float attitude_reference_pitch, float attitude_reference_roll, float dist_treshold)
void matrix_2_pingpong (float *distancesMeters, uint16_t *size_matrix, float *distances_hor)
void CN_matrix_Kalman_filter (void)
void CN_matrix_butterworth (void)
void CN_calculate_target (void)
void CN_potential_heading (void)
void CN_potential_velocity (void)
void CN_vector_velocity (void)
void CN_vector_escape_velocity (void)
void CN_escape_velocity (void)
Variables
float F1
float F2
float Cfreq
float Ko
float Kg
float Dist_offset
int8_t dis_treshold
float dx_ref
float dy_ref
float K_goal
float K_obst
float b_damp
float c1_oa
float c2_oa
float c3_oa
float c4_oa
float c5_oa
float kv
float epsilon
Detailed Description
Obstacle avoidance methods.
Definition in file obstacle_avoidance.h.
Function Documentation
CN_calculate_target()
void CN_calculate_target (void) extern
Definition at line 321 of file obstacle_avoidance.c.
References current_pos, dx_ref, dy_ref, foo, heading_goal_f, init_target, OA_method_flag, pos_diff, FloatEulers::psi, stateGetNedToBodyEulers_f(), stateGetPositionNed_f(), target, waypoint_rot, FloatVect2::x, NedCoor_f::x, FloatVect2::y, and NedCoor_f::y.
Referenced by serial_update().
CN_escape_velocity()
void CN_escape_velocity (void) extern
Definition at line 1032 of file obstacle_avoidance.c.
References angle_hor_board, baseline, direction, FLOAT_ANGLE_NORMALIZE, focal, foo, heading_goal_f, heading_goal_ref, min_disparity, new_heading, new_heading_old, obstacle_flag, pos_diff, FloatEulers::psi, ref_pitch, ref_roll, set_bias, size_matrix, speed_pot, stateGetNedToBodyEulers_f(), stereo_fow, VECT2_NORM2, vref_max, and waypoint_rot.
Referenced by serial_update().
CN_matrix_butterworth()
void CN_matrix_butterworth (void) extern
Definition at line 295 of file obstacle_avoidance.c.
References butter_old, foo, READimageBuffer_old, and size_matrix.
CN_matrix_Kalman_filter()
void CN_matrix_Kalman_filter (void) extern
Definition at line 263 of file obstacle_avoidance.c.
References A_kal, foo, H_kal, Pest_new, Q_kal, R_kal, size_matrix, and Xest_new.
CN_potential_heading()
void CN_potential_heading (void) extern
Definition at line 404 of file obstacle_avoidance.c.
References angle_hor_board, b_damp, baseline, c1_oa, c2_oa, c3_oa, c4_oa, epsilon, FLOAT_ANGLE_NORMALIZE, focal, foo, heading_goal_f, heading_goal_ref, K_goal, K_obst, kv, min_disparity, pos_diff, FloatEulers::psi, FloatRates::r, r_dot_new, size_matrix, speed_pot, stateGetBodyRates_f(), stateGetNedToBodyEulers_f(), stereo_fow, VECT2_NORM2, and vref_max.
Referenced by serial_update().
CN_potential_velocity()
void CN_potential_velocity (void) extern
Definition at line 506 of file obstacle_avoidance.c.
References alpha_fil, angle_hor_board, b_damp, baseline, c1_oa, c2_oa, c3_oa, c4_oa, epsilon, FLOAT_ANGLE_NORMALIZE, focal, foo, heading_goal_f, heading_goal_ref, K_goal, K_obst, kv, min_disparity, new_heading, pos_diff, FloatEulers::psi, FloatRates::r, r_dot_new, ref_pitch, size_matrix, speed_pot, stateGetBodyRates_f(), stateGetNedToBodyEulers_f(), stereo_fow, VECT2_NORM2, vmin, and vref_max.
Referenced by serial_update().
CN_vector_escape_velocity()
void CN_vector_escape_velocity (void) extern
Definition at line 777 of file obstacle_avoidance.c.
References angle_hor_board, Attractforce_goal, baseline, Cfreq, direction, Dist_offset, escape_flag, F1, F2, filter_repforce_old, FLOAT_ANGLE_NORMALIZE, focal, foo, heading_goal_f, heading_goal_ref, Kg, Ko, min_disparity, new_heading, new_heading_old, obstacle_flag, pos_diff, FloatEulers::psi, ref_pitch, ref_roll, repulsionforce_filter_flag, Repulsionforce_Kan, Repulsionforce_Kan_old, Repulsionforce_Used, set_bias, size_matrix, speed_pot, stateGetNedToBodyEulers_f(), stereo_fow, v_max, v_min, VECT2_NORM2, VECT3_ADD, VECT3_COPY, VECT3_SMUL, vref_max, waypoint_rot, FloatVect3::x, FloatVect3::y, and FloatVect3::z.
Referenced by serial_update().
CN_vector_velocity()
void CN_vector_velocity (void) extern
Definition at line 590 of file obstacle_avoidance.c.
References angle_hor_board, Attractforce_goal, baseline, Cfreq, Dist_offset, F1, F2, filter_repforce_old, focal, foo, heading_goal_f, heading_goal_ref, hysteris_flag, Kg, Ko, min_disparity, pos_diff, FloatEulers::psi, ref_pitch, ref_roll, repulsionforce_filter_flag, Repulsionforce_Kan, Repulsionforce_Kan_old, Repulsionforce_Used, size_matrix, stateGetNedToBodyEulers_f(), stereo_fow, V_hys_high, V_hys_low, VECT2_NORM2, VECT3_ADD, VECT3_COPY, VECT3_SMUL, FloatVect3::x, FloatVect3::y, and FloatVect3::z.
Referenced by serial_update().
matrix_2_pingpong()
void matrix_2_pingpong (float * distancesMeters, uint16_t * size_matrix, float * distances_hor) extern
Definition at line 237 of file obstacle_avoidance.c.
References AVOIDANCES_DISTANCES_HOR_COUNT, and foo.
Referenced by serial_update().
pingpong_euler()
void pingpong_euler (float * distances_hor, float * horizontalAnglesMeasurements, int horizontalAmountOfMeasurements, float attitude_reference_pitch, float attitude_reference_roll, float dist_treshold) extern
Definition at line 357 of file obstacle_avoidance.c.
References foo, ref_pitch, and ref_roll.
Referenced by serial_update().
serial_init()
void serial_init (void) extern
Definition at line 146 of file obstacle_avoidance.c.
References AVOIDANCE_AMOUNT_OF_BOARDS, AVOIDANCE_HEIGHT_IN_MEASUREMENT_VALUES, AVOIDANCE_WIDTH_IN_MEASUREMENT_VALUES, butter_old, foo, Pest_new, and Xest_new.
Referenced by digital_cam_uart_init(), and main().
serial_start()
void serial_start (void) extern
Definition at line 159 of file obstacle_avoidance.c.
serial_update()
void serial_update (void) extern
Definition at line 176 of file obstacle_avoidance.c.
References angle_hor_board, AVOIDANCE_AMOUNT_OF_BOARDS, CN_calculate_target(), CN_escape_velocity(), CN_potential_heading(), CN_potential_velocity(), CN_vector_escape_velocity(), CN_vector_velocity(), DefaultChannel, DefaultDevice, dist_treshold, distances_hor, foo, LOGICBASED, matrix_2_pingpong(), OA_method_flag, PINGPONG, pingpong_euler(), POT_HEADING, POT_VEL, reference_pitch, reference_roll, SAFETYZONE, setAnglesMeasurements(), size_matrix, and stereo_fow.
setAnglesMeasurements()
void setAnglesMeasurements (float * anglesMeasurements, float * centersensorRad, float * fieldOfViewRad, uint16_t * size_matrix_local)
Definition at line 164 of file obstacle_avoidance.c.
References foo.
Referenced by serial_update().
Variable Documentation
b_damp
float b_damp extern
Definition at line 110 of file obstacle_avoidance.c.
Referenced by CN_potential_heading(), and CN_potential_velocity().
c1_oa
float c1_oa extern
Definition at line 113 of file obstacle_avoidance.c.
Referenced by CN_potential_heading(), and CN_potential_velocity().
c2_oa
float c2_oa extern
Definition at line 114 of file obstacle_avoidance.c.
Referenced by CN_potential_heading(), and CN_potential_velocity().
c3_oa
float c3_oa extern
Definition at line 115 of file obstacle_avoidance.c.
Referenced by CN_potential_heading(), and CN_potential_velocity().
c4_oa
float c4_oa extern
Definition at line 116 of file obstacle_avoidance.c.
Referenced by CN_potential_heading(), and CN_potential_velocity().
c5_oa
float c5_oa extern
Definition at line 117 of file obstacle_avoidance.c.
Cfreq
float Cfreq extern
Definition at line 101 of file obstacle_avoidance.c.
Referenced by CN_vector_escape_velocity(), and CN_vector_velocity().
dis_treshold
int8_t dis_treshold extern
Definition at line 105 of file obstacle_avoidance.c.
Dist_offset
float Dist_offset extern
Definition at line 104 of file obstacle_avoidance.c.
Referenced by CN_vector_escape_velocity(), and CN_vector_velocity().
dx_ref
float dx_ref extern
Definition at line 80 of file obstacle_avoidance.c.
Referenced by CN_calculate_target().
dy_ref
float dy_ref extern
Definition at line 81 of file obstacle_avoidance.c.
Referenced by CN_calculate_target().
epsilon
float epsilon extern
Definition at line 119 of file obstacle_avoidance.c.
Referenced by CN_potential_heading(), CN_potential_velocity(), inverse_isometric_latitude_d(), and inverse_isometric_latitude_f().
F1
float F1 extern
Definition at line 99 of file obstacle_avoidance.c.
Referenced by CN_vector_escape_velocity(), and CN_vector_velocity().
F2
float F2 extern
Definition at line 100 of file obstacle_avoidance.c.
Referenced by CN_vector_escape_velocity(), and CN_vector_velocity().
K_goal
float K_goal extern
Definition at line 111 of file obstacle_avoidance.c.
Referenced by CN_potential_heading(), and CN_potential_velocity().
K_obst
float K_obst extern
Definition at line 112 of file obstacle_avoidance.c.
Referenced by CN_potential_heading(), and CN_potential_velocity().
Kg
float Kg extern
Definition at line 103 of file obstacle_avoidance.c.
Referenced by CN_vector_escape_velocity(), and CN_vector_velocity().
Ko
float Ko extern
Definition at line 102 of file obstacle_avoidance.c.
Referenced by CN_vector_escape_velocity(), and CN_vector_velocity().
kv
float kv extern
Definition at line 118 of file obstacle_avoidance.c.
Referenced by CN_potential_heading(), CN_potential_velocity(), kv_exists(), kv_find(), kv_get(), kv_init(), kv_remove(), and kv_set().