Paparazzi UAS: sw/airborne/modules/boards/opa_controller_fbw.c File Reference
opa_controller_fbw.c File Reference
#include "modules/boards/opa_controller_fbw.h"
#include "modules/intermcu/intermcu.h"
#include "generated/airframe.h"
#include "mcu_periph/gpio.h"
#include "led.h"
Macros
#define OFF_TIMER 5*1
#define MIN_ARMING_TRIG 1*1
Functions
void opa_controller_init (void)
void opa_controller_periodic (void)
Variables
static bool arming_led = false
bool autopilot_motors_on
bool opa_controller_disarm = false
Detailed Description
Author
Freek van Tienen freek.nosp@m..v.t.nosp@m.ienen.nosp@m.@gma.nosp@m.il.co.nosp@m.m Controller for OPA board functionalities
Definition in file opa_controller_fbw.c.
Macro Definition Documentation
MIN_ARMING_TRIG
#define MIN_ARMING_TRIG 1*1
Definition at line 33 of file opa_controller_fbw.c.
OFF_TIMER
#define OFF_TIMER 5*1
Definition at line 32 of file opa_controller_fbw.c.
Function Documentation
opa_controller_init()
void opa_controller_init (void)
Definition at line 41 of file opa_controller_fbw.c.
References foo, gpio_setup_input(), gpio_setup_output(), and LED_OFF.
opa_controller_periodic()
void opa_controller_periodic (void)
Definition at line 65 of file opa_controller_fbw.c.
References arming_led, foo, gpio_get(), INTERMCU_CLR_CMD_STATUS, INTERMCU_CMD_DISARM, INTERMCU_GET_CMD_STATUS, LED_OFF, LED_ON, MIN_ARMING_TRIG, OFF_TIMER, RADIO_CONTROL_POWER_OFF, RADIO_CONTROL_POWER_PIN, and RADIO_CONTROL_POWER_PORT.
Variable Documentation
arming_led
bool arming_led = false static
Definition at line 36 of file opa_controller_fbw.c.
Referenced by opa_controller_periodic().
autopilot_motors_on
bool autopilot_motors_on extern
opa_controller_disarm
bool opa_controller_disarm = false
Definition at line 38 of file opa_controller_fbw.c.