Paparazzi UAS: sw/airborne/modules/boards/opa_controller_fbw.h File Reference
opa_controller_fbw.h File Reference
#include "std.h"
Functions
void opa_controller_init (void)
void opa_controller_periodic (void)
Variables
bool opa_controller_disarm
Detailed Description
Author
Freek van Tienen freek.nosp@m..v.t.nosp@m.ienen.nosp@m.@gma.nosp@m.il.co.nosp@m.m Controller for OPA board functionalities
Definition in file opa_controller_fbw.h.
Function Documentation
opa_controller_init()
void opa_controller_init (void) extern
Definition at line 39 of file opa_controller_ap.c.
References foo, gpio_setup_input(), gpio_setup_output(), LED_OFF, opa_controller_ftd_disarm, and opa_controller_vision_power.
opa_controller_periodic()
void opa_controller_periodic (void) extern
Definition at line 48 of file opa_controller_ap.c.
References arming_led, intermcu_t::cmd_status, foo, gpio_get(), intermcu, INTERMCU_CLR_CMD_STATUS, INTERMCU_CMD_DISARM, INTERMCU_GET_CMD_STATUS, LED_OFF, LED_ON, MIN_ARMING_TRIG, OFF_TIMER, opa_controller_ftd_disarm, opa_controller_vision_power, RADIO_CONTROL_POWER_OFF, RADIO_CONTROL_POWER_PIN, and RADIO_CONTROL_POWER_PORT.
Variable Documentation
opa_controller_disarm
bool opa_controller_disarm extern
Definition at line 38 of file opa_controller_fbw.c.