Paparazzi UAS: sw/airborne/modules/computer_vision/opencv_contour.cpp File Reference
opencv_contour.cpp File Reference
#include "opencv_contour.h"
#include <opencv2/core/core.hpp>
#include <opencv2/imgproc/imgproc.hpp>
#include "opencv_image_functions.h"
Functions
RNG rng (12345)
void yuv_opencv_to_yuv422 (Mat image, char *img, int width, int height)
void uyvy_opencv_to_yuv_opencv (Mat image, Mat image_in, int width, int height)
void find_contour (char *img, int width, int height)
Variables
struct contour_estimation cont_est
struct contour_threshold cont_thres
Detailed Description
Author
Roland Meertens and Peng Lu
Definition in file opencv_contour.cpp.
Function Documentation
find_contour()
void find_contour (char * img, int width, int height)
Find contours
Draw contours
Definition at line 79 of file opencv_contour.cpp.
References cont_est, cont_thres, contour_estimation::contour_d_x, contour_estimation::contour_d_y, contour_estimation::contour_d_z, foo, grayscale_opencv_to_yuv422(), contour_threshold::lower_u, contour_threshold::lower_v, contour_threshold::lower_y, moments, rng(), contour_threshold::upper_u, contour_threshold::upper_v, and contour_threshold::upper_y.
Referenced by contour_func().
rng()
RNG rng (12345)
Referenced by find_contour().
uyvy_opencv_to_yuv_opencv()
void uyvy_opencv_to_yuv_opencv (Mat image, Mat image_in, int width, int height)
Definition at line 56 of file opencv_contour.cpp.
References foo.
yuv_opencv_to_yuv422()
void yuv_opencv_to_yuv422 (Mat image, char * img, int width, int height)
Definition at line 40 of file opencv_contour.cpp.
References foo.
Variable Documentation
cont_est
struct contour_estimation cont_est
Definition at line 34 of file opencv_contour.cpp.
Referenced by find_contour().
cont_thres
struct contour_threshold cont_thres
Definition at line 35 of file opencv_contour.cpp.
Referenced by detect_contour_init(), and find_contour().