Paparazzi UAS: sw/airborne/modules/computer_vision/opencv_example.cpp File Reference
opencv_example.cpp File Reference
#include "opencv_example.h"
#include <opencv2/core/core.hpp>
#include <opencv2/imgproc/imgproc.hpp>
#include "opencv_image_functions.h"
Functions
int opencv_example (char *img, int width, int height)
Detailed Description
Author
C. De Wagter A simple module showing what you can do with opencv on the bebop.
Definition in file opencv_example.cpp.
Function Documentation
opencv_example()
int opencv_example (char * img, int width, int height)
Definition at line 38 of file opencv_example.cpp.
References colorbgr_opencv_to_yuv422(), foo, and grayscale_opencv_to_yuv422().
Referenced by opencv_func().