Paparazzi UAS: sw/airborne/modules/computer_vision/opencv_image_functions.cpp File Reference
opencv_image_functions.cpp File Reference
A small library with functions to convert between the Paparazzi used YUV422 arrays and the opencv image functions.
#include "opencv_image_functions.h"
#include <opencv2/core/core.hpp>
#include <opencv2/imgproc/imgproc.hpp>
Functions
void coloryuv_opencv_to_yuv422 (Mat image, char *img, int width, int height)
void colorbgr_opencv_to_yuv422 (Mat image, char *img, int width, int height)
void grayscale_opencv_to_yuv422 (Mat image, char *img, int width, int height)
Detailed Description
A small library with functions to convert between the Paparazzi used YUV422 arrays and the opencv image functions.
Definition in file opencv_image_functions.cpp.
Function Documentation
colorbgr_opencv_to_yuv422()
void colorbgr_opencv_to_yuv422 (Mat image, char * img, int width, int height)
Definition at line 59 of file opencv_image_functions.cpp.
References coloryuv_opencv_to_yuv422(), and foo.
Referenced by opencv_example().
coloryuv_opencv_to_yuv422()
void coloryuv_opencv_to_yuv422 (Mat image, char * img, int width, int height)
Definition at line 37 of file opencv_image_functions.cpp.
References foo.
Referenced by colorbgr_opencv_to_yuv422().
grayscale_opencv_to_yuv422()
void grayscale_opencv_to_yuv422 (Mat image, char * img, int width, int height)
Definition at line 68 of file opencv_image_functions.cpp.
References foo, and p.
Referenced by find_contour(), and opencv_example().