Paparazzi UAS: sw/airborne/modules/computer_vision/opencv_contour.h File Reference
opencv_contour.h File Reference
Detects contours of an obstacle used in the autonomous drone racing.
Data Structures
struct contour_estimation
struct contour_threshold
Functions
void find_contour (char *img, int width, int height)
Variables
struct contour_estimation cont_est
struct contour_threshold cont_thres
Detailed Description
Detects contours of an obstacle used in the autonomous drone racing.
Definition in file opencv_contour.h.
Data Structure Documentation
contour_estimation
struct contour_estimation
Definition at line 34 of file opencv_contour.h.
Data Fields
float contour_d_x
float contour_d_y
float contour_d_z
contour_threshold
struct contour_threshold
Definition at line 40 of file opencv_contour.h.
Data Fields
int lower_u
int lower_v
int lower_y
int upper_u
int upper_v
int upper_y
Function Documentation
find_contour()
void find_contour (char * img, int width, int height)
Find contours
Draw contours
Definition at line 79 of file opencv_contour.cpp.
References cont_est, cont_thres, contour_estimation::contour_d_x, contour_estimation::contour_d_y, contour_estimation::contour_d_z, foo, grayscale_opencv_to_yuv422(), contour_threshold::lower_u, contour_threshold::lower_v, contour_threshold::lower_y, moments, rng(), contour_threshold::upper_u, contour_threshold::upper_v, and contour_threshold::upper_y.
Referenced by contour_func().
Variable Documentation
cont_est
struct contour_estimation cont_est extern
Definition at line 34 of file opencv_contour.cpp.
Referenced by find_contour().
cont_thres
struct contour_threshold cont_thres extern
Definition at line 35 of file opencv_contour.cpp.
Referenced by detect_contour_init(), and find_contour().