Paparazzi UAS: sw/airborne/modules/computer_vision/opencv_example.h File Reference
opencv_example.h File Reference
Functions
int opencv_example (char *img, int width, int height)
Function Documentation
opencv_example()
int opencv_example (char * img, int width, int height)
Definition at line 38 of file opencv_example.cpp.
References colorbgr_opencv_to_yuv422(), foo, and grayscale_opencv_to_yuv422().
Referenced by opencv_func().