Paparazzi UAS: sw/airborne/modules/computer_vision/opticflow_module.h File Reference
opticflow_module.h File Reference
optical-flow calculation for Parrot Drones
#include "opticflow/opticflow_calculator.h"
Functions
void opticflow_module_init (void)
Initialize the optical flow module for the bottom camera.
void opticflow_module_run (void)
Update the optical flow state for the calculation thread and update the stabilization loops with the newest result.
void opticflow_module_start (void)
void opticflow_module_stop (void)
Variables
struct opticflow_t opticflow []
Opticflow calculations.
Detailed Description
optical-flow calculation for Parrot Drones
Definition in file opticflow_module.h.
Function Documentation
opticflow_module_init()
void opticflow_module_init (void) extern
Initialize the optical flow module for the bottom camera.
Definition at line 110 of file opticflow_module.c.
References ACTIVE_CAMERAS, cv_add_to_device(), DefaultPeriodic, foo, opticflow, opticflow_calc_init(), OPTICFLOW_FPS, OPTICFLOW_FPS_CAMERA2, opticflow_got_result, opticflow_module_calc(), opticflow_telem_send(), and register_periodic_telemetry().
opticflow_module_run()
void opticflow_module_run (void) extern
Update the optical flow state for the calculation thread and update the stabilization loops with the newest result.
Definition at line 133 of file opticflow_module.c.
References ACTIVE_CAMERAS, FLOW_OPTICFLOW_ID, foo, get_sys_time_usec(), opticflow_result_t::noise_measurement, opticflow_got_result, opticflow_mutex, opticflow_result, opticflow_result_t::vel_body, VEL_OPTICFLOW_ID, and FloatVect3::y.
opticflow_module_start()
void opticflow_module_start (void) extern
opticflow_module_stop()
void opticflow_module_stop (void) extern
Variable Documentation
opticflow
struct opticflow_t opticflow[] extern
Opticflow calculations.
Definition at line 69 of file opticflow_module.c.
Referenced by calc_edgeflow_tot(), calc_fast9_lukas_kanade(), calc_previous_frame_nr(), manage_flow_features(), opticflow_calc_frame(), opticflow_calc_init(), opticflow_module_calc(), opticflow_module_init(), and predict_flow_vectors().