Paparazzi UAS: sw/airborne/modules/sensors/opticflow_pmw3901.h File Reference
opticflow_pmw3901.h File Reference
#include "peripherals/pmw3901.h"
Data Structures
struct opticflow_pmw3901_t
Functions
void opticflow_pmw3901_init (void)
void opticflow_pmw3901_periodic (void)
void opticflow_pmw3901_event (void)
Variables
struct opticflow_pmw3901_t of_pmw
Detailed Description
Author
Tom van Dijk Driver for PMW3901 optical flow sensor
Definition in file opticflow_pmw3901.h.
Data Structure Documentation
opticflow_pmw3901_t
struct opticflow_pmw3901_t
Definition at line 31 of file opticflow_pmw3901.h.
Data Fields
uint32_t agl_timeout
struct pmw3901_t pmw
float sensor_angle
float std_px
int16_t subpixel_factor
Function Documentation
opticflow_pmw3901_event()
void opticflow_pmw3901_event (void) extern
Definition at line 186 of file opticflow_pmw3901.c.
References get_sys_time_usec(), of_pmw, opticflow_pmw3901_publish(), opticflow_pmw3901_t::pmw, pmw3901_data_available(), pmw3901_event(), and pmw3901_get_data().
opticflow_pmw3901_init()
void opticflow_pmw3901_init (void) extern
Definition at line 168 of file opticflow_pmw3901.c.
References agl_cb(), agl_ev, opticflow_pmw3901_t::agl_timeout, foo, of_pmw, OPTICFLOW_PMW3901_AGL_ID, OPTICFLOW_PMW3901_AGL_TIMEOUT_US, OPTICFLOW_PMW3901_SENSOR_ANGLE, OPTICFLOW_PMW3901_STD_PX, OPTICFLOW_PMW3901_SUBPIXEL_FACTOR, opticflow_pmw3901_t::pmw, pmw3901_init(), pmw3901_t::rad_per_px, opticflow_pmw3901_t::sensor_angle, opticflow_pmw3901_t::std_px, and opticflow_pmw3901_t::subpixel_factor.
opticflow_pmw3901_periodic()
void opticflow_pmw3901_periodic (void) extern
Definition at line 180 of file opticflow_pmw3901.c.
References of_pmw, opticflow_pmw3901_t::pmw, pmw3901_is_idle(), and pmw3901_start_read().
Variable Documentation
of_pmw
struct opticflow_pmw3901_t of_pmw extern
Definition at line 61 of file opticflow_pmw3901.c.
Referenced by agl_valid(), opticflow_pmw3901_event(), opticflow_pmw3901_init(), opticflow_pmw3901_periodic(), and opticflow_pmw3901_publish().