Paparazzi UAS: sw/airborne/modules/orange_avoider/orange_avoider_guided.h File Reference
orange_avoider_guided.h File Reference
Functions
void orange_avoider_guided_init (void)
void orange_avoider_guided_periodic (void)
Variables
float oag_color_count_frac
float oag_floor_count_frac
float oag_max_speed
float oag_heading_rate
Function Documentation
orange_avoider_guided_init()
void orange_avoider_guided_init (void) extern
Definition at line 102 of file orange_avoider_guided.c.
References chooseRandomIncrementAvoidance(), color_detection_cb(), color_detection_ev, floor_detection_cb(), floor_detection_ev, foo, ORANGE_AVOIDER_VISUAL_DETECTION_ID, and time.
orange_avoider_guided_periodic()
void orange_avoider_guided_periodic (void) extern
Definition at line 116 of file orange_avoider_guided.c.
References avoidance_heading_direction, chooseRandomIncrementAvoidance(), color_count, floor_centroid, floor_count, foo, front_camera, guidance_h, GUIDANCE_H_MODE_GUIDED, guidance_h_set_body_vel(), guidance_h_set_heading(), guidance_h_set_heading_rate(), max_trajectory_confidence, HorizontalGuidance::mode, oag_color_count_frac, oag_floor_count_frac, oag_heading_rate, oag_max_speed, OBSTACLE_FOUND, obstacle_free_confidence, OUT_OF_BOUNDS, REENTER_ARENA, SAFE, SEARCH_FOR_SAFE_HEADING, speed_sp, stateGetNedToBodyEulers_f(), and VERBOSE_PRINT.
Variable Documentation
oag_color_count_frac
float oag_color_count_frac extern
Definition at line 56 of file orange_avoider_guided.c.
Referenced by orange_avoider_guided_periodic().
oag_floor_count_frac
float oag_floor_count_frac extern
Definition at line 57 of file orange_avoider_guided.c.
Referenced by orange_avoider_guided_periodic().
oag_heading_rate
float oag_heading_rate extern
Definition at line 59 of file orange_avoider_guided.c.
Referenced by chooseRandomIncrementAvoidance(), and orange_avoider_guided_periodic().
oag_max_speed
float oag_max_speed extern
Definition at line 58 of file orange_avoider_guided.c.
Referenced by orange_avoider_guided_periodic().