Paparazzi UAS: sw/airborne/modules/orange_avoider/orange_avoider.h File Reference
orange_avoider.h File Reference
Functions
void orange_avoider_init (void)
void orange_avoider_periodic (void)
Variables
float oa_color_count_frac
Detailed Description
Author
Roland Meertens Example on how to use the colours detected to avoid orange pole in the cyberzoo
Definition in file orange_avoider.h.
Function Documentation
orange_avoider_init()
void orange_avoider_init (void) extern
Definition at line 86 of file orange_avoider.c.
References chooseRandomIncrementAvoidance(), color_detection_cb(), color_detection_ev, foo, ORANGE_AVOIDER_VISUAL_DETECTION_ID, and time.
orange_avoider_periodic()
void orange_avoider_periodic (void) extern
Definition at line 99 of file orange_avoider.c.
References autopilot_in_flight(), chooseRandomIncrementAvoidance(), color_count, foo, front_camera, heading_increment, increase_nav_heading(), max_trajectory_confidence, maxDistance, moveDistance, moveWaypointForward(), oa_color_count_frac, OBSTACLE_FOUND, obstacle_free_confidence, OUT_OF_BOUNDS, SAFE, SEARCH_FOR_SAFE_HEADING, VERBOSE_PRINT, waypoint_move_here_2d(), WaypointX, and WaypointY.
Variable Documentation
oa_color_count_frac
float oa_color_count_frac extern
Definition at line 45 of file mav_exercise.c.
Referenced by mav_exercise_periodic(), and orange_avoider_periodic().