Paparazzi UAS: sw/airborne/modules/pano_unwrap/pano_unwrap.h File Reference
pano_unwrap.h File Reference
#include "modules/computer_vision/lib/vision/image.h"
Data Structures
struct pano_unwrap_t
Functions
void pano_unwrap_init (void)
Variables
struct pano_unwrap_t pano_unwrap
struct image_t pano_unwrapped_image
Unwrapped panoramic image.
Detailed Description
Author
Tom van Dijk Unwrap images taken through a panoramic lens.
Definition in file pano_unwrap.h.
Data Structure Documentation
pano_unwrap_t
struct pano_unwrap_t
Definition at line 31 of file pano_unwrap.h.
Data Fields
struct FloatVect2 center Center point of panoramic lens [fraction of image width, height].
bool derotate_attitude Set to true if roll/pitch movement should be corrected.
bool flip_horizontal Set to true to horizontally flip the unwrapped image.
float forward_direction Angle [deg] in raw image that corresponds to the forward direction, where 0 points right and the value increases counterclockwise.
uint16_t height Height of unwrapped image. Set to 0 (default) to determine automatically from unwrapped_width, radius_bottom, _top and vertical_resolution.
bool overwrite_video_thread Set to true if the unwrapped image should be returned to the video thread.
float radius_bottom Distance from center point to bottom of region of interest [fraction of image height].
float radius_top Distance from center point to top of region of interest [fraction of image height].
bool show_calibration Draw calibration pattern on raw image.
float vertical_resolution Vertical resolution of raw image in the region of interest, used for attitude derotation [fraction of image height/rad] (Note: negative values are allowed)
uint16_t width Width of unwrapped image.
Function Documentation
pano_unwrap_init()
void pano_unwrap_init (void) extern
Definition at line 313 of file pano_unwrap.c.
References camera_cb(), cv_add_to_device(), image_create(), IMAGE_YUV422, PANO_UNWRAP_CAMERA, PANO_UNWRAP_FPS, pano_unwrapped_image, and set_output_image_size().
Variable Documentation
pano_unwrap
struct pano_unwrap_t pano_unwrap extern
Definition at line 78 of file pano_unwrap.c.
Referenced by camera_cb(), set_output_image_size(), unwrap_LUT(), and update_LUT().
pano_unwrapped_image
struct image_t pano_unwrapped_image extern
Unwrapped panoramic image.
Definition at line 99 of file pano_unwrap.c.
Referenced by camera_cb(), pano_unwrap_init(), set_output_image_size(), and update_LUT().