Paparazzi UAS: sw/airborne/modules/safety/parachute.h File Reference
parachute.h File Reference
#include "std.h"
Data Structures
struct Parachute
Enumerations
enum arming_method_t { OFF , AUTO , ON }
Functions
void init_parachute (void)
void periodic_parachute (void)
Variables
struct Parachute parachute
Detailed Description
Author
Ewoud Smeur e.j.j.nosp@m..sme.nosp@m.ur@tu.nosp@m.delf.nosp@m.t.nl This module triggers automatic deployment of the parachute.
Definition in file parachute.h.
Data Structure Documentation
Parachute
struct Parachute
Definition at line 37 of file parachute.h.
Data Fields
bool armed
enum arming_method_t arming_method
bool deploy
Enumeration Type Documentation
arming_method_t
enum arming_method_t
Enumerator
OFF
ARMING OVERRIDE OFF.
AUTO
AUTOMATIC ARMING.
ON
ALWAYS ARMED.
Definition at line 31 of file parachute.h.
Function Documentation
init_parachute()
void init_parachute (void) extern
Definition at line 59 of file parachute.c.
References Parachute::armed, Parachute::arming_method, AUTO, DefaultPeriodic, Parachute::deploy, foo, parachute, register_periodic_telemetry(), and send_parachute().
periodic_parachute()
void periodic_parachute (void) extern
Definition at line 71 of file parachute.c.
References Parachute::armed, Parachute::arming_method, AUTO, check_parachute_arming(), check_parachute_trigger(), OFF, and parachute.
Variable Documentation
parachute
struct Parachute parachute extern
Definition at line 43 of file parachute.c.
Referenced by check_parachute_arming(), check_parachute_trigger(), init_parachute(), periodic_parachute(), and send_parachute().