Paparazzi UAS: sw/airborne/modules/safety/parachute.c File Reference
parachute.c File Reference
#include "modules/safety/parachute.h"
#include "firmwares/rotorcraft/autopilot_firmware.h"
#include "modules/sonar/agl_dist.h"
#include "modules/datalink/telemetry.h"
Macros
#define PARACHUTE_AGL_THRESHOLD 6.0
#define PARACHUTE_AGL_COUNTER_TRIGGER 10
#define PARACHUTE_ATT_ANGLE_THRESHOLD RadOfDeg(55.f)
Functions
void check_parachute_arming (void)
void check_parachute_trigger (void)
static void send_parachute (struct transport_tx *trans, struct link_device *dev)
void init_parachute (void)
void periodic_parachute (void)
Variables
struct Parachute parachute
bool close_to_ground = true
Detailed Description
Author
Ewoud Smeur e.j.j.nosp@m..sme.nosp@m.ur@tu.nosp@m.delf.nosp@m.t.nl This module triggers automatic deployment of the parachute.
Definition in file parachute.c.
Macro Definition Documentation
PARACHUTE_AGL_COUNTER_TRIGGER
#define PARACHUTE_AGL_COUNTER_TRIGGER 10
Definition at line 35 of file parachute.c.
PARACHUTE_AGL_THRESHOLD
#define PARACHUTE_AGL_THRESHOLD 6.0
Definition at line 31 of file parachute.c.
PARACHUTE_ATT_ANGLE_THRESHOLD
#define PARACHUTE_ATT_ANGLE_THRESHOLD RadOfDeg(55.f)
Definition at line 40 of file parachute.c.
Function Documentation
check_parachute_arming()
void check_parachute_arming (void) inline
Definition at line 88 of file parachute.c.
References agl_dist_valid, agl_dist_value_filtered, AP_MODE_RATE_DIRECT, Parachute::armed, autopilot, close_to_ground, foo, pprz_autopilot::mode, parachute, PARACHUTE_AGL_COUNTER_TRIGGER, PARACHUTE_AGL_THRESHOLD, and stateGetPositionEnu_f().
Referenced by periodic_parachute().
check_parachute_trigger()
void check_parachute_trigger (void)
Definition at line 121 of file parachute.c.
References AP_MODE_KILL, autopilot, Parachute::deploy, foo, pprz_autopilot::mode, parachute, PARACHUTE_ATT_ANGLE_THRESHOLD, FloatEulers::phi, stateGetNedToBodyEulers_f(), and FloatEulers::theta.
Referenced by periodic_parachute().
init_parachute()
void init_parachute (void)
Definition at line 59 of file parachute.c.
References Parachute::armed, Parachute::arming_method, AUTO, DefaultPeriodic, Parachute::deploy, foo, parachute, register_periodic_telemetry(), and send_parachute().
periodic_parachute()
void periodic_parachute (void)
Definition at line 71 of file parachute.c.
References Parachute::armed, Parachute::arming_method, AUTO, check_parachute_arming(), check_parachute_trigger(), OFF, and parachute.
send_parachute()
static void send_parachute (struct transport_tx * trans, struct link_device * dev) static
Definition at line 52 of file parachute.c.
References Parachute::armed, Parachute::arming_method, Parachute::deploy, dev, foo, msg, and parachute.
Referenced by init_parachute().
Variable Documentation
close_to_ground
bool close_to_ground = true
Definition at line 45 of file parachute.c.
Referenced by check_parachute_arming().
parachute
struct Parachute parachute
Definition at line 43 of file parachute.c.
Referenced by check_parachute_arming(), check_parachute_trigger(), init_parachute(), periodic_parachute(), and send_parachute().