Paparazzi UAS: sw/airborne/modules/pca9685/pca9685_i2c.h File Reference
pca9685_i2c.h File Reference
#include "std.h"
Macros
#define PCA9865_SRV0 PCA9685_LED0_OFF_L_REG_ADDR
#define PCA9865_SRV1 PCA9685_LED1_OFF_L_REG_ADDR
#define PCA9865_SRV2 PCA9685_LED2_OFF_L_REG_ADDR
#define PCA9865_SRV3 PCA9685_LED3_OFF_L_REG_ADDR
#define PCA9865_SRV4 PCA9685_LED4_OFF_L_REG_ADDR
#define PCA9865_SRV5 PCA9685_LED5_OFF_L_REG_ADDR
#define PCA9865_SRV6 PCA9685_LED6_OFF_L_REG_ADDR
#define PCA9865_SRV7 PCA9685_LED7_OFF_L_REG_ADDR
#define PCA9865_SRV8 PCA9685_LED8_OFF_L_REG_ADDR
#define PCA9865_SRV9 PCA9685_LED9_OFF_L_REG_ADDR
#define PCA9865_SRV10 PCA9685_LED10_OFF_L_REG_ADDR
#define PCA9865_SRV11 PCA9685_LED11_OFF_L_REG_ADDR
#define PCA9865_SRV12 PCA9685_LED12_OFF_L_REG_ADDR
#define PCA9865_SRV13 PCA9685_LED13_OFF_L_REG_ADDR
#define PCA9865_SRV14 PCA9685_LED14_OFF_L_REG_ADDR
#define PCA9865_SRV15 PCA9685_LED15_OFF_L_REG_ADDR
Functions
void pca9685_i2c_init (void)
void pca9685_i2c_periodic (void)
void pca9685_i2c_event (void)
bool pca9865_set_servo (uint8_t srv_nb, uint16_t srv_val)
Macro Definition Documentation
PCA9865_SRV0
#define PCA9865_SRV0 PCA9685_LED0_OFF_L_REG_ADDR
Definition at line 34 of file pca9685_i2c.h.
PCA9865_SRV1
#define PCA9865_SRV1 PCA9685_LED1_OFF_L_REG_ADDR
Definition at line 35 of file pca9685_i2c.h.
PCA9865_SRV10
#define PCA9865_SRV10 PCA9685_LED10_OFF_L_REG_ADDR
Definition at line 44 of file pca9685_i2c.h.
PCA9865_SRV11
#define PCA9865_SRV11 PCA9685_LED11_OFF_L_REG_ADDR
Definition at line 45 of file pca9685_i2c.h.
PCA9865_SRV12
#define PCA9865_SRV12 PCA9685_LED12_OFF_L_REG_ADDR
Definition at line 46 of file pca9685_i2c.h.
PCA9865_SRV13
#define PCA9865_SRV13 PCA9685_LED13_OFF_L_REG_ADDR
Definition at line 47 of file pca9685_i2c.h.
PCA9865_SRV14
#define PCA9865_SRV14 PCA9685_LED14_OFF_L_REG_ADDR
Definition at line 48 of file pca9685_i2c.h.
PCA9865_SRV15
#define PCA9865_SRV15 PCA9685_LED15_OFF_L_REG_ADDR
Definition at line 49 of file pca9685_i2c.h.
PCA9865_SRV2
#define PCA9865_SRV2 PCA9685_LED2_OFF_L_REG_ADDR
Definition at line 36 of file pca9685_i2c.h.
PCA9865_SRV3
#define PCA9865_SRV3 PCA9685_LED3_OFF_L_REG_ADDR
Definition at line 37 of file pca9685_i2c.h.
PCA9865_SRV4
#define PCA9865_SRV4 PCA9685_LED4_OFF_L_REG_ADDR
Definition at line 38 of file pca9685_i2c.h.
PCA9865_SRV5
#define PCA9865_SRV5 PCA9685_LED5_OFF_L_REG_ADDR
Definition at line 39 of file pca9685_i2c.h.
PCA9865_SRV6
#define PCA9865_SRV6 PCA9685_LED6_OFF_L_REG_ADDR
Definition at line 40 of file pca9685_i2c.h.
PCA9865_SRV7
#define PCA9865_SRV7 PCA9685_LED7_OFF_L_REG_ADDR
Definition at line 41 of file pca9685_i2c.h.
PCA9865_SRV8
#define PCA9865_SRV8 PCA9685_LED8_OFF_L_REG_ADDR
Definition at line 42 of file pca9685_i2c.h.
PCA9865_SRV9
#define PCA9865_SRV9 PCA9685_LED9_OFF_L_REG_ADDR
Definition at line 43 of file pca9685_i2c.h.
Function Documentation
pca9685_i2c_event()
void pca9685_i2c_event (void) extern
Definition at line 421 of file pca9685_i2c.c.
References i2c_transaction::buf, BUF2INT, foo, i2c_transceive(), I2CTransSuccess, PCA9685_I2C_DEV, PCA9685_I2C_SLAVE_ADDR, pca9685_i2c_status, pca9685_i2c_trans, PCA9865_I2C_STATUS_CHANGE_LED_REG_FINISHED, PCA9865_I2C_STATUS_READ_LED_REG_BUSY, PCA9865_I2C_STATUS_WRITE_LED_REG_BUSY, pca9865_reg_nb, pca9865_write_servo_vals, srv_cnt, and i2c_transaction::status.
pca9685_i2c_init()
void pca9685_i2c_init (void) extern
Definition at line 279 of file pca9685_i2c.c.
References i2c_transaction::buf, DefaultPeriodic, foo, i2c_transceive(), i2c_transmit(), I2CTransDone, I2CTransPending, sys_time::nb_tick, PCA9685_ALL_LED_ON_L_REG_ADDR, PCA9685_I2C_ALLCALL_ADDR, PCA9685_I2C_DEV, PCA9685_I2C_GEN_CALL_ADDR, PCA9685_I2C_RESET_ADDR, PCA9685_I2C_SLAVE_ADDR, pca9685_i2c_status, PCA9685_I2C_STATUS_INITIALIZED, PCA9685_I2C_STATUS_UNINIT, pca9685_i2c_trans, PCA9685_MODE1_REG_ADDR, PCA9685_PRESCALER_REG_ADDR, PCA9865_ALLCALL_BIT, PCA9865_AUTO_INCREMENT_BIT, pca9865_reg_nb, PCA9865_RESTART_BIT, pca9865_set_servo(), PCA9865_SLEEP_BIT, PCA9865_SRV_DEFAULT_VAL_US, PCA9865_SRV_NUMBER, PCA9865_SRV_RESOLUTION, pca9865_write_servo_vals, register_periodic_telemetry(), srv_cnt, i2c_transaction::status, and SYS_TIME_FREQUENCY.
pca9685_i2c_periodic()
void pca9685_i2c_periodic (void) extern
Definition at line 380 of file pca9685_i2c.c.
References i2c_transaction::buf, i2c_transmit(), PCA9685_I2C_DEV, PCA9685_I2C_SLAVE_ADDR, pca9685_i2c_status, PCA9685_I2C_STATUS_INITIALIZED, pca9685_i2c_trans, PCA9865_I2C_STATUS_CHANGE_LED_REG_FINISHED, PCA9865_I2C_STATUS_WRITE_LED_REG_BUSY, pca9865_reg_nb, pca9865_write_servo_vals, and srv_cnt.
pca9865_set_servo()
bool pca9865_set_servo (uint8_t srv_nb, uint16_t srv_val)
Definition at line 262 of file pca9685_i2c.c.
References FALSE, foo, pca9865_reg_nb, PCA9865_SRV_RESOLUTION, and pca9865_write_servo_vals.
Referenced by pca9685_i2c_init().