Paparazzi UAS: sw/airborne/modules/checks/pfc_actuators.h File Reference
pfc_actuators.h File Reference
#include "std.h"
Functions
void pfc_actuators_init (void)
Register the preflight checks for the actuators.
void pfc_actuators_run (void)
Move the actuators, should be put in the command laws.
void pfc_actuators_start (bool start)
Start the actuator testing.
int16_t pfc_actuators_value (uint8_t idx, int16_t value)
Get the actuator value in the command laws to move the actuator during the preflight checks.
Detailed Description
Author
Freek van Tienen freek.nosp@m..v.t.nosp@m.ienen.nosp@m.@gma.nosp@m.il.co.nosp@m.m Checks the actuators with feedback before takeoff
Definition in file pfc_actuators.h.
Function Documentation
pfc_actuators_init()
void pfc_actuators_init (void) extern
Register the preflight checks for the actuators.
Definition at line 141 of file pfc_actuators.c.
References ABI_BROADCAST, act_feedback_ev, pfc_actuators_t::act_idx, pfc_actuators_t::act_nb, pfc_actuators_t::act_state, actuators_pfc, foo, pfc_actuators_t::last_feedback, pfc_actuators_t::last_feedback2, pfc_act_feedback_cb(), pfc_acts, PFC_ACTUATOR_STATE_WAIT, pfc_actuators, pfc_actuators_cb(), PFC_ACTUATORS_STATE_INIT, preflight_check_register(), and pfc_actuators_t::state.
pfc_actuators_run()
void pfc_actuators_run (void) extern
Move the actuators, should be put in the command laws.
Definition at line 156 of file pfc_actuators.c.
References pfc_actuators_t::act_idx, pfc_actuators_t::act_nb, pfc_actuators_t::act_start_time, pfc_actuators_t::act_state, foo, get_sys_time_float(), pfc_actuators_t::last_feedback, pfc_actuators_t::last_feedback2, pfc_actuators_t::last_feedback_err, pfc_actuators_t::last_feedback_err2, pfc_acts, PFC_ACTUATOR_STATE_HIGH, PFC_ACTUATOR_STATE_LOW, PFC_ACTUATOR_STATE_WAIT, pfc_actuators, PFC_ACTUATORS_DEBUG, pfc_actuators_debug, pfc_actuators_error(), PFC_ACTUATORS_STATE_ERROR, PFC_ACTUATORS_STATE_RUNNING, PFC_ACTUATORS_STATE_SUCCESS, and pfc_actuators_t::state.
pfc_actuators_start()
void pfc_actuators_start (bool start) extern
Start the actuator testing.
Definition at line 227 of file pfc_actuators.c.
References pfc_actuators_t::act_idx, pfc_actuators_t::act_start_time, pfc_actuators_t::act_state, foo, pfc_actuators_t::last_feedback, pfc_actuators_t::last_feedback2, PFC_ACTUATOR_STATE_WAIT, pfc_actuators, PFC_ACTUATORS_STATE_INIT, PFC_ACTUATORS_STATE_RUNNING, and pfc_actuators_t::state.
pfc_actuators_value()
int16_t pfc_actuators_value (uint8_t idx, int16_t value) extern
Get the actuator value in the command laws to move the actuator during the preflight checks.
Parameters
idx The index of the actuator in the preflight checks struct
value The value if no checks are performed on this actuator
Definition at line 249 of file pfc_actuators.c.
References pfc_actuators_t::act_idx, pfc_actuators_t::act_state, pfc_actuator_t::high, idx, pfc_actuator_t::low, pfc_acts, PFC_ACTUATOR_STATE_HIGH, PFC_ACTUATOR_STATE_LOW, pfc_actuators, PFC_ACTUATORS_STATE_RUNNING, and pfc_actuators_t::state.