Paparazzi UAS: sw/airborne/mcu_periph/pipe.h File Reference
pipe.h File Reference
arch independent PIPE API
#include "std.h"
#include "mcu_periph/pipe_arch.h"
#include "pprzlink/pprzlink_device.h"
Data Structures
struct pipe_periph
Functions
void pipe_arch_init (void)
void pipe_arch_periph_init (struct pipe_periph *p, char *read_name, char *write_name)
Initialize the PIPE peripheral.
void pipe_periph_init (struct pipe_periph *p, char *name, char *write_name)
Initialize the PIPE peripheral.
int pipe_char_available (struct pipe_periph *p)
Get number of bytes available in receive buffer.
uint8_t pipe_getch (struct pipe_periph *p)
Get the last character from the receive buffer.
void pipe_receive (struct pipe_periph *p)
Read bytes from PIPE.
void pipe_send_message (struct pipe_periph *p, long fd)
Send a message.
void pipe_send_raw (struct pipe_periph *p, long fd, uint8_t *buffer, uint16_t size)
Send a packet from another buffer.
int pipe_check_free_space (struct pipe_periph *p, long *fd, uint16_t len)
Check if there is enough free space in the transmit buffer.
void pipe_put_byte (struct pipe_periph *p, long fd, uint8_t data)
Add one data byte to the tx buffer.
void pipe_put_buffer (struct pipe_periph *p, long fd, const uint8_t *data, uint16_t len)
Detailed Description
arch independent PIPE API
Definition in file pipe.h.
Data Structure Documentation
struct pipe_periph
Definition at line 35 of file pipe.h.
Data Fields
struct link_device device Generic device interface.
int fd_read PIPE file descriptor.
int fd_write
uint8_t rx_buf[PIPE_RX_BUFFER_SIZE] Receive buffer.
uint16_t rx_extract_idx
uint16_t rx_insert_idx
uint8_t tx_buf[PIPE_TX_BUFFER_SIZE] Transmit buffer.
uint16_t tx_insert_idx
Function Documentation
void pipe_arch_init (void)
Definition at line 48 of file pipe_arch.c.
References pipe_thread().
void pipe_arch_periph_init (struct pipe_periph * p, char * read_name, char * write_name)
Initialize the PIPE peripheral.
Allocate UdpSocket struct and create and bind the PIPE socket.
Definition at line 76 of file pipe_arch.c.
References pipe_periph::fd_read, and pipe_periph::fd_write.
Referenced by pipe_periph_init().
int pipe_char_available (struct pipe_periph * p)
Get number of bytes available in receive buffer.
Parameters
p pointer to PIPE peripheral
Returns
number of bytes available in receive buffer
Definition at line 104 of file pipe_arch.c.
References PIPE_RX_BUFFER_SIZE, pipe_periph::rx_extract_idx, and pipe_periph::rx_insert_idx.
Referenced by pipe_periph_init(), and pipe_receive().
int pipe_check_free_space (struct pipe_periph * p, long * fd, uint16_t len)
Check if there is enough free space in the transmit buffer.
Parameters
p pointer to PIPE peripheral
len how many bytes of free space to check for
Returns
number of bytes available or 0 if not enough
Definition at line 94 of file pipe.c.
References PIPE_TX_BUFFER_SIZE, and pipe_periph::tx_insert_idx.
Referenced by pipe_periph_init().
uint8_t pipe_getch (struct pipe_periph * p)
Get the last character from the receive buffer.
Parameters
p pointer to PIPE peripheral
Returns
last byte
Definition at line 120 of file pipe_arch.c.
References PIPE_RX_BUFFER_SIZE, pipe_periph::rx_buf, and pipe_periph::rx_extract_idx.
Referenced by pipe_periph_init().
void pipe_periph_init (struct pipe_periph * p, char * name, char * write_name)
Initialize the PIPE peripheral.
Definition at line 72 of file pipe.c.
References pipe_periph::device, pipe_arch_periph_init(), pipe_char_available(), pipe_check_free_space(), pipe_getch(), pipe_put_buffer(), pipe_put_byte(), pipe_send_message(), pipe_periph::rx_extract_idx, pipe_periph::rx_insert_idx, and pipe_periph::tx_insert_idx.
void pipe_put_buffer (struct pipe_periph * p, long fd, const uint8_t * data, uint16_t len)
Definition at line 115 of file pipe.c.
References PIPE_TX_BUFFER_SIZE, pipe_periph::tx_buf, and pipe_periph::tx_insert_idx.
Referenced by pipe_periph_init().
void pipe_put_byte (struct pipe_periph * p, long fd, uint8_t data)
Add one data byte to the tx buffer.
Parameters
p pointer to PIPE peripheral
data byte to add to tx buffer
Definition at line 105 of file pipe.c.
References PIPE_TX_BUFFER_SIZE, pipe_periph::tx_buf, and pipe_periph::tx_insert_idx.
Referenced by pipe_periph_init().
void pipe_receive (struct pipe_periph * p)
Read bytes from PIPE.
Definition at line 132 of file pipe_arch.c.
References pipe_periph::fd_read, pipe_char_available(), PIPE_RX_BUFFER_SIZE, pipe_periph::rx_buf, and pipe_periph::rx_insert_idx.
Referenced by pipe_thread().
void pipe_send_message (struct pipe_periph * p, long fd)
Send a message.
Definition at line 160 of file pipe_arch.c.
References pipe_periph::fd_write, pipe_periph::tx_buf, and pipe_periph::tx_insert_idx.
Referenced by pipe_periph_init().
void pipe_send_raw (struct pipe_periph * p, long fd, uint8_t * buffer, uint16_t size)
Send a packet from another buffer.
Definition at line 182 of file pipe_arch.c.
References pipe_periph::fd_write.