Paparazzi UAS: sw/airborne/modules/cam_control/point.h File Reference
point.h File Reference
Functions
void vPoint (float fPlaneEast, float fPlaneNorth, float fPlaneAltitude, float fRollAngle, float fPitchAngle, float fYawAngle, float fObjectEast, float fObjectNorth, float fAltitude, float *fPan, float *fTilt)
Function Documentation
void vPoint (float fPlaneEast, float fPlaneNorth, float fPlaneAltitude, float fRollAngle, float fPitchAngle, float fYawAngle, float fObjectEast, float fObjectNorth, float fAltitude, float * fPan, float * fTilt)
Definition at line 164 of file point.c.
References point::a, AP_MODE_AUTO2, autopilot_get_mode(), cam_lock, cam_mode, CAM_MODE_RC, CAM_MODE_STABILIZED, CAM_MODE_WP_TARGET, CAM_MODE_XY_TARGET, CAM_PAN_MAX, CAM_PAN_MIN, cam_phi, cam_theta, CAM_TILT_MAX, CAM_TILT_MIN, UtmCoor_f::east, FALSE, fbw_state, VECTOR::fx, MATRIX::fx1, MATRIX::fx2, MATRIX::fx3, VECTOR::fy, MATRIX::fy1, MATRIX::fy2, MATRIX::fy3, VECTOR::fz, MATRIX::fz1, MATRIX::fz2, MATRIX::fz3, ground_alt, LlaCoor_f::lat, lla_of_utm_f(), LlaCoor_f::lon, MAX_PPRZ, memory_x, memory_y, memory_z, MIN_PPRZ, nav_utm_east0, nav_utm_north0, nav_utm_zone0, UtmCoor_f::north, PPRZ_MUTEX_LOCK, PPRZ_MUTEX_UNLOCK, RADIO_PITCH, RADIO_ROLL, stateGetPositionUtm_f(), vMultiplyMatrixByVector(), vSubtractVectors(), waypoints, point::x, point::y, and UtmCoor_f::zone.
Referenced by cam_target().