Paparazzi UAS: sw/airborne/modules/pose_history/pose_history.h File Reference
pose_history.h File Reference
#include "math/pprz_algebra_float.h"
Data Structures
struct pose_t
Functions
void pose_init (void)
Initialises the pose history.
void pose_periodic (void)
Records the pose history 512 times per second.
struct pose_t get_rotation_at_timestamp (uint32_t timestamp)
Given a pprz timestamp in used (obtained with get_sys_time_usec) we return the pose in FloatEulers closest to that time.
Detailed Description
Author
Roland Meertens Ask this module for the pose the drone had closest to a given timestamp
Definition in file pose_history.h.
Data Structure Documentation
pose_t
struct pose_t
Definition at line 31 of file pose_history.h.
Data Fields
struct FloatEulers eulers
struct FloatRates rates
uint32_t timestamp
Function Documentation
get_rotation_at_timestamp()
struct pose_t get_rotation_at_timestamp (uint32_t timestamp) extern
Given a pprz timestamp in used (obtained with get_sys_time_usec) we return the pose in FloatEulers closest to that time.
Definition at line 53 of file pose_history.c.
References pose_t::eulers, foo, location_history, pose_t::rates, rotation_history_ring_buffer_t::ring_data, rotation_history_ring_buffer_t::ring_size, and pose_t::timestamp.
Referenced by opticflow_module_calc(), and save_shot_on_disk().
pose_init()
void pose_init (void) extern
Initialises the pose history.
Definition at line 85 of file pose_history.c.
References location_history, POSE_HISTORY_SIZE, rotation_history_ring_buffer_t::ring_index, and rotation_history_ring_buffer_t::ring_size.
pose_periodic()
void pose_periodic (void) extern
Records the pose history 512 times per second.
Time gets saved in pprz usec, obtained with get_sys_time_usec();
Definition at line 95 of file pose_history.c.
References pose_t::eulers, foo, get_sys_time_usec(), location_history, rotation_history_ring_buffer_t::ring_data, rotation_history_ring_buffer_t::ring_index, rotation_history_ring_buffer_t::ring_size, stateGetBodyRates_f(), and stateGetNedToBodyEulers_f().