Paparazzi UAS: sw/airborne/modules/multi/potential.h File Reference
potential.h File Reference
flying with potential field to avoid collision
#include "firmwares/fixedwing/nav.h"
#include "modules/multi/traffic_info.h"
Data Structures
struct force_
Functions
void potential_init (void)
int potential_task (void)
Variables
struct force_ potential_force
float force_pos_gain
float force_speed_gain
float force_climb_gain
Detailed Description
flying with potential field to avoid collision
Definition in file potential.h.
Data Structure Documentation
force_
struct force_
Definition at line 13 of file potential.h.
Data Fields
float alt
float climb
float east
float north
float speed
Function Documentation
potential_init()
void potential_init (void) extern
Definition at line 43 of file potential.c.
References force_::alt, force_::climb, force_::east, force_climb_gain, FORCE_CLIMB_GAIN, force_pos_gain, FORCE_POS_GAIN, force_speed_gain, FORCE_SPEED_GAIN, force_::north, potential_force, and force_::speed.
potential_task()
int potential_task (void) extern
Definition at line 58 of file potential.c.
References acInfoGetItow(), acInfoGetPositionEnu_f(), acInfoGetVelocityEnu_f(), force_::alt, CARROT, force_::climb, DefaultChannel, DefaultDevice, desired_x, desired_y, dn, force_::east, fly_to_xy(), foo, force_climb_gain, FORCE_MAX_DIST, force_pos_gain, force_speed_gain, gps, NavVerticalAutoThrottleMode, NavVerticalClimbMode, NB_ACS, force_::north, potential_force, force_::speed, stateGetHorizontalSpeedDir_f(), stateGetHorizontalSpeedNorm_f(), stateGetPositionEnu_f(), stateGetSpeedEnu_f(), ti_acs, GpsState::tow, V_CTL_ALTITUDE_MAX_CLIMB, v_ctl_auto_throttle_cruise_throttle, EnuCoor_f::x, EnuCoor_f::y, and EnuCoor_f::z.
Variable Documentation
force_climb_gain
float force_climb_gain extern
Definition at line 25 of file potential.c.
Referenced by potential_init(), and potential_task().
force_pos_gain
float force_pos_gain extern
Definition at line 23 of file potential.c.
Referenced by potential_init(), and potential_task().
force_speed_gain
float force_speed_gain extern
Definition at line 24 of file potential.c.
Referenced by potential_init(), and potential_task().
potential_force
struct force_ potential_force extern
Definition at line 21 of file potential.c.
Referenced by potential_init(), and potential_task().