Paparazzi UAS: sw/airborne/modules/sensors/power_uavcan.h File Reference
power_uavcan.h File Reference
Power sensors on the uavcan bus.
#include "std.h"
Functions
void power_uavcan_init (void)
Detailed Description
Power sensors on the uavcan bus.
Definition in file power_uavcan.h.
Function Documentation
power_uavcan_init()
void power_uavcan_init (void) extern
Definition at line 190 of file power_uavcan.c.
References battery_circuits, uavcan_circuit_battery_t::circuit_id, circuit_uavcan_ev, circuits, DefaultPeriodic, foo, init_random(), circuit_status::is_battery, circuit_status::node_id, uavcan_circuit_battery_t::node_id, power_uavcan_battery_cb(), power_uavcan_circuit_cb(), power_uavcan_ev, power_uavcan_send_power_device(), register_periodic_telemetry(), circuit_status::set, circuit_status::status, and uavcan_bind().