Paparazzi UAS: sw/airborne/modules/boards/power_switch.h File Reference
power_switch.h File Reference
#include "std.h"
Functions
void power_switch_init (void)
Intialize the power switch pins This sets the power switch pins to te initial state.
void power_switch_set (bool val)
Set the power switch to enable/disable.
Variables
bool power_switch_status
Detailed Description
Author
F. van Tienen Simple GPIO power switch module
Definition in file power_switch.h.
Function Documentation
power_switch_init()
void power_switch_init (void) extern
Intialize the power switch pins This sets the power switch pins to te initial state.
Definition at line 39 of file power_switch.c.
References foo, gpio_clear(), gpio_setup_output(), POWER_SWITCH_GPIO, and power_switch_set().
power_switch_set()
void power_switch_set (bool val) extern
Set the power switch to enable/disable.
Parameters
val True enables the pin, False disables the pin
Definition at line 53 of file power_switch.c.
References gpio_clear(), gpio_set(), POWER_SWITCH_GPIO, power_switch_status, and val.
Referenced by power_switch_init().
Variable Documentation
power_switch_status
bool power_switch_status extern
Definition at line 29 of file power_switch.c.
Referenced by power_switch_set().