Paparazzi UAS: sw/airborne/modules/datalink/pprz_dl.h File Reference
pprz_dl.h File Reference
Datalink using PPRZ protocol.
#include "pprzlink/pprz_transport.h"
#include "mcu_periph/uart.h"
Functions
void pprz_dl_init (void)
Init function.
void pprz_dl_event (void)
Datalink Event.
Variables
struct pprz_transport pprz_tp
PPRZ transport structure.
Detailed Description
Datalink using PPRZ protocol.
Definition in file pprz_dl.h.
Function Documentation
pprz_dl_event()
void pprz_dl_event (void) extern
Datalink Event.
Definition at line 40 of file pprz_dl.c.
References dl_buffer, dl_msg_available, DlCheckAndParse(), DOWNLINK_DEVICE, foo, pprz_tp, and PPRZ_UPDATE_DL.
Referenced by main_event().
pprz_dl_init()
void pprz_dl_init (void) extern
Init function.
Definition at line 35 of file pprz_dl.c.
References foo, and pprz_tp.
Referenced by main_init().
Variable Documentation
pprz_tp
struct pprz_transport pprz_tp extern
PPRZ transport structure.
Definition at line 33 of file pprz_dl.c.
Referenced by pprz_dl_event(), and pprz_dl_init().