Paparazzi UAS: sw/airborne/modules/digital_cam/pprzlink_cam_ctrl.c File Reference
pprzlink_cam_ctrl.c File Reference
#include "modules/digital_cam/pprzlink_cam_ctrl.h"
#include "generated/airframe.h"
#include "generated/modules.h"
#include "dc.h"
#include "modules/datalink/downlink.h"
#include "modules/datalink/extra_pprz_dl.h"
Functions
void pprzlink_cam_ctrl_init (void)
void pprzlink_cam_ctrl_periodic (void)
Periodic.
void dc_send_command (uint8_t cmd)
Send Command To Camera.
void dc_set_expo (float expo)
void dc_expo_cb (uint8_t *buf)
Function Documentation
dc_expo_cb()
void dc_expo_cb (uint8_t * buf)
Definition at line 68 of file pprzlink_cam_ctrl.c.
References dc_exposure, and foo.
dc_send_command()
void dc_send_command (uint8_t cmd)
Send Command To Camera.
Definition at line 44 of file pprzlink_cam_ctrl.c.
References dc_send_command_common(), dc_send_shot_position(), and DC_SHOOT.
dc_set_expo()
void dc_set_expo (float expo)
Definition at line 58 of file pprzlink_cam_ctrl.c.
References dc_exposure, extra_pprz_tp, and foo.
pprzlink_cam_ctrl_init()
void pprzlink_cam_ctrl_init (void)
Definition at line 32 of file pprzlink_cam_ctrl.c.
References dc_exposure, and PPRZLINK_CAM_AUTO_EXPO.
pprzlink_cam_ctrl_periodic()
void pprzlink_cam_ctrl_periodic (void)
Periodic.
Definition at line 37 of file pprzlink_cam_ctrl.c.
References dc_periodic().