Paparazzi UAS: sw/airborne/modules/system_identification/pprz_doublet.h File Reference
pprz_doublet.h File Reference
#include "std.h"
Data Structures
struct doublet_t
Initialize with doublet_init.
Functions
void doublet_init (struct doublet_t *doublet, float length_s, float extra_waiting_time_s, float current_time_s, uint8_t mod3211)
void doublet_reset (struct doublet_t *doublet, float current_time_s)
bool doublet_is_running (struct doublet_t *doublet, float current_time_s)
float doublet_update (struct doublet_t *doublet, float current_time_s)
Data Structure Documentation
doublet_t
struct doublet_t
Initialize with doublet_init.
Definition at line 56 of file pprz_doublet.h.
Data Fields
float current_time_s
float current_value
uint8_t mod
float t0
float t1
float t2
float t3
float t4
float t5
float tf
float total_length_s
Function Documentation
doublet_init()
void doublet_init (struct doublet_t * doublet, float length_s, float extra_waiting_time_s, float current_time_s, uint8_t mod3211) extern
Definition at line 31 of file pprz_doublet.c.
References doublet_t::current_time_s, doublet_t::current_value, doublet, foo, doublet_t::mod, doublet_t::t0, doublet_t::t1, doublet_t::t2, doublet_t::t3, doublet_t::t4, doublet_t::t5, doublet_t::tf, and doublet_t::total_length_s.
Referenced by sys_id_doublet_activate_handler(), and sys_id_doublet_init().
doublet_is_running()
bool doublet_is_running (struct doublet_t * doublet, float current_time_s) extern
Definition at line 67 of file pprz_doublet.c.
References doublet, foo, doublet_t::t0, and doublet_t::total_length_s.
Referenced by doublet_update(), and sys_id_doublet_run().
doublet_reset()
void doublet_reset (struct doublet_t * doublet, float current_time_s) extern
Definition at line 61 of file pprz_doublet.c.
References doublet_t::current_time_s, doublet_t::current_value, doublet, and doublet_t::t0.
Referenced by start_doublet(), and stop_doublet().
doublet_update()
float doublet_update (struct doublet_t * doublet, float current_time_s) extern
Definition at line 72 of file pprz_doublet.c.
References doublet_t::current_value, doublet, doublet_is_running(), foo, doublet_t::mod, doublet_t::t0, doublet_t::t1, doublet_t::t2, doublet_t::t3, and doublet_t::t4.
Referenced by sys_id_doublet_run().