Paparazzi UAS: sw/airborne/math/pprz_algebra_float.c File Reference
pprz_algebra_float.c File Reference
Paparazzi floating point algebra.
#include "pprz_algebra_float.h"
Functions
void float_vect3_integrate_fi (struct FloatVect3 *vec, const struct FloatVect3 *dv, const float dt)
in place first order integration of a 3D-vector
void float_rates_integrate_fi (struct FloatRates *r, const struct FloatRates *dr, const float dt)
in place first order integration of angular rates
void float_rates_vect3_integrate_fi (struct FloatRates *r, const struct FloatVect3 *dr, const float dt)
in place first order integration of angular rates
void float_rates_of_euler_dot (struct FloatRates *r, const struct FloatEulers *e, const struct FloatEulers *edot)
void float_rmat_inv (struct FloatRMat *m_b2a, const struct FloatRMat *m_a2b)
Inverse/transpose of a rotation matrix.
float float_rmat_norm (const struct FloatRMat *rm)
Norm of a rotation matrix.
void float_rmat_comp (struct FloatRMat *m_a2c, const struct FloatRMat *m_a2b, const struct FloatRMat *m_b2c)
Composition (multiplication) of two rotation matrices.
void float_rmat_comp_inv (struct FloatRMat *m_a2b, const struct FloatRMat *m_a2c, const struct FloatRMat *m_b2c)
Composition (multiplication) of two rotation matrices.
void float_rmat_vmult (struct FloatVect3 *vb, const struct FloatRMat *m_a2b, const struct FloatVect3 *va)
rotate 3D vector by rotation matrix.
void float_rmat_transp_vmult (struct FloatVect3 *vb, const struct FloatRMat *m_b2a, const struct FloatVect3 *va)
rotate 3D vector by transposed rotation matrix.
void float_rmat_mult (struct FloatEulers *rb, const struct FloatRMat *m_a2b, const struct FloatEulers *ra)
rotate angle by rotation matrix.
void float_rmat_transp_mult (struct FloatEulers *rb, const struct FloatRMat *m_b2a, const struct FloatEulers *ra)
rotate angle by transposed rotation matrix.
void float_rmat_ratemult (struct FloatRates *rb, const struct FloatRMat *m_a2b, const struct FloatRates *ra)
rotate anglular rates by rotation matrix.
void float_rmat_transp_ratemult (struct FloatRates *rb, const struct FloatRMat *m_b2a, const struct FloatRates *ra)
rotate anglular rates by transposed rotation matrix.
void float_rmat_of_axis_angle (struct FloatRMat *rm, const struct FloatVect3 *uv, const float angle)
initialises a rotation matrix from unit vector axis and angle
void float_rmat_of_eulers_321 (struct FloatRMat *rm, const struct FloatEulers *e)
Rotation matrix from 321 Euler angles (float).
void float_rmat_of_eulers_312 (struct FloatRMat *rm, const struct FloatEulers *e)
void float_rmat_of_quat (struct FloatRMat *rm, const struct FloatQuat *q)
void float_rmat_integrate_fi (struct FloatRMat *rm, const struct FloatRates *omega, float dt)
in place first order integration of a rotation matrix
static float renorm_factor (float n)
float float_rmat_reorthogonalize (struct FloatRMat *rm)
void float_quat_comp (struct FloatQuat *a2c, const struct FloatQuat *a2b, const struct FloatQuat *b2c)
Composition (multiplication) of two quaternions.
void float_quat_comp_inv (struct FloatQuat *a2b, const struct FloatQuat *a2c, const struct FloatQuat *b2c)
Composition (multiplication) of two quaternions.
void float_quat_inv_comp (struct FloatQuat *b2c, const struct FloatQuat *a2b, const struct FloatQuat *a2c)
Composition (multiplication) of two quaternions.
void float_quat_comp_norm_shortest (struct FloatQuat *a2c, const struct FloatQuat *a2b, const struct FloatQuat *b2c)
Composition (multiplication) of two quaternions with normalization.
void float_quat_comp_inv_norm_shortest (struct FloatQuat *a2b, const struct FloatQuat *a2c, const struct FloatQuat *b2c)
Composition (multiplication) of two quaternions with normalization.
void float_quat_inv_comp_norm_shortest (struct FloatQuat *b2c, const struct FloatQuat *a2b, const struct FloatQuat *a2c)
Composition (multiplication) of two quaternions with normalization.
void float_quat_differential (struct FloatQuat *q_out, const struct FloatRates *w, const float dt)
Delta rotation quaternion with constant angular rates.
void float_quat_integrate_fi (struct FloatQuat *q, const struct FloatRates *omega, const float dt)
in place first order quaternion integration with constant rotational velocity
void float_quat_integrate (struct FloatQuat *q, const struct FloatRates *omega, const float dt)
in place quaternion integration with constant rotational velocity
void float_quat_vmult (struct FloatVect3 *v_out, const struct FloatQuat *q, const struct FloatVect3 *v_in)
rotate 3D vector by quaternion.
void float_quat_derivative (struct FloatQuat *qd, const struct FloatRates *r, const struct FloatQuat *q)
Quaternion derivative from rotational velocity.
void float_quat_derivative_lagrange (struct FloatQuat *qd, const struct FloatRates *r, const struct FloatQuat *q)
Quaternion derivative from rotational velocity.
void float_quat_of_eulers (struct FloatQuat *q, const struct FloatEulers *e)
quat of euler roation 'ZYX'
void float_quat_of_eulers_zxy (struct FloatQuat *q, const struct FloatEulers *e)
quat from euler rotation 'ZXY' This rotation order is useful if you need 90 deg pitch
void float_quat_of_eulers_yxz (struct FloatQuat *q, const struct FloatEulers *e)
quat from euler rotation 'YXZ' This function calculates a quaternion from Euler angles with the order YXZ, so pitch, roll, yaw, instead of the conventional ZYX order.
void float_quat_of_axis_angle (struct FloatQuat *q, const struct FloatVect3 *uv, const float angle)
Quaternion from unit vector and angle.
void float_quat_of_orientation_vect (struct FloatQuat *q, const struct FloatVect3 *ov)
Quaternion from orientation vector.
void float_quat_of_rmat (struct FloatQuat *q, const struct FloatRMat *rm)
Quaternion from rotation matrix.
void float_quat_tilt_twist (struct FloatQuat *tilt, struct FloatQuat *twist, const struct FloatQuat *quat)
Tilt twist decomposition of a quaternion (z axis)
void float_eulers_of_rmat (struct FloatEulers *e, const struct FloatRMat *rm)
void float_eulers_of_quat (struct FloatEulers *e, const struct FloatQuat *q)
euler rotation 'ZYX'
void float_eulers_of_quat_yxz (struct FloatEulers *e, const struct FloatQuat *q)
euler rotation 'YXZ' This function calculates from a quaternion the Euler angles with the order YXZ, so pitch, roll, yaw, instead of the conventional ZYX order.
void float_eulers_of_quat_zxy (struct FloatEulers *e, const struct FloatQuat *q)
euler rotation 'ZXY' This rotation order is useful if you need 90 deg pitch
bool float_mat_inv_2d (float inv_out[4], const float mat_in[4])
2x2 matrix inverse
void float_mat2_mult (struct FloatVect2 *vect_out, const float mat[4], const struct FloatVect2 vect_in)
Multiply 2D matrix with vector.
bool float_mat_inv_3d (float inv_out[3][3], const float mat_in[3][3])
3x3 matrix inverse
void float_mat3_mult (struct FloatVect3 *vect_out, const float mat[3][3], const struct FloatVect3 vect_in)
Multiply 3D matrix with vector.
static float float_mat_minor_4d (const float m[4][4], int r0, int r1, int r2, int c0, int c1, int c2)
static void float_mat_adjoint_4d (float adjOut[4][4], const float m[4][4])
static float float_mat_det_4d (const float m[4][4])
bool float_mat_inv_4d (float invOut[4][4], const float mat_in[4][4])
4x4 Matrix inverse
void float_mat_invert (float **o, float **mat, const int n)
Calculate inverse of any n x n matrix (passed as C array) o = mat^-1 Algorithm verified with Matlab.
void float_mat_exp (float **a, float **o, const int n)
float float_mat_norm_li (float **a, const int m, const int n)
void float_vect3_bound_in_2d (struct FloatVect3 *vect3, const float bound)
void float_vect3_bound_in_3d (struct FloatVect3 *vect3, const float bound)
void float_vect3_scale_in_2d (struct FloatVect3 *vect3, const float norm_des)
void float_vect2_bound_in_2d (struct FloatVect2 *vect2, const float bound)
void float_vect2_scale_in_2d (struct FloatVect2 *vect2, const float norm_des)
Detailed Description
Paparazzi floating point algebra.
Definition in file pprz_algebra_float.c.
Function Documentation
float_mat_adjoint_4d()
static void float_mat_adjoint_4d (float adjOut[4][4], const float m[4][4]) static
Definition at line 886 of file pprz_algebra_float.c.
References float_mat_minor_4d(), and foo.
Referenced by float_mat_inv_4d().
float_mat_det_4d()
static float float_mat_det_4d (const float m[4][4]) static
Definition at line 906 of file pprz_algebra_float.c.
References float_mat_minor_4d().
Referenced by float_mat_inv_4d().
float_mat_minor_4d()
static float float_mat_minor_4d (const float m[4][4], int r0, int r1, int r2, int c0, int c1, int c2) static
Definition at line 878 of file pprz_algebra_float.c.
References c1, c2, and foo.
Referenced by float_mat_adjoint_4d(), and float_mat_det_4d().
renorm_factor()
static float renorm_factor (float n) inline static
Definition at line 283 of file pprz_algebra_float.c.
References foo.
Referenced by float_rmat_reorthogonalize().