Paparazzi UAS: sw/airborne/modules/datalink/pprz_dl.c File Reference
pprz_dl.c File Reference
#include "modules/datalink/pprz_dl.h"
#include "modules/datalink/datalink.h"
Macros
#define PPRZ_UPDATE_DL TRUE
Functions
void pprz_dl_init (void)
Init function.
void pprz_dl_event (void)
Datalink Event.
Variables
struct pprz_transport pprz_tp
PPRZ transport structure.
Macro Definition Documentation
PPRZ_UPDATE_DL
#define PPRZ_UPDATE_DL TRUE
Definition at line 30 of file pprz_dl.c.
Function Documentation
pprz_dl_event()
void pprz_dl_event (void)
Datalink Event.
Definition at line 40 of file pprz_dl.c.
References dl_buffer, dl_msg_available, DlCheckAndParse(), DOWNLINK_DEVICE, foo, pprz_tp, and PPRZ_UPDATE_DL.
Referenced by main_event().
pprz_dl_init()
void pprz_dl_init (void)
Init function.
Definition at line 35 of file pprz_dl.c.
References foo, and pprz_tp.
Referenced by main_init().
Variable Documentation
pprz_tp
struct pprz_transport pprz_tp
PPRZ transport structure.
Definition at line 33 of file pprz_dl.c.
Referenced by pprz_dl_event(), and pprz_dl_init().