Paparazzi UAS: sw/airborne/math/pprz_random.h File Reference
pprz_random.h File Reference
#include <std.h>
#include <stdlib.h>
#include <math.h>
#include <stdbool.h>
Functions
void init_random (void)
double rand_uniform (void)
double rand_gaussian (void)
Function Documentation
init_random()
void init_random (void)
Definition at line 35 of file pprz_random.c.
References foo, get_sys_time_msec(), and time.
Referenced by actuators_uavcan_init(), power_uavcan_init(), and sys_id_chirp_init().
rand_gaussian()
double rand_gaussian (void)
Definition at line 53 of file pprz_random.c.
References foo, and rand_uniform().
Referenced by set_current_chirp_values().
rand_uniform()
double rand_uniform (void)
Definition at line 45 of file pprz_random.c.
References foo.
Referenced by actuators_uavcan_next_telem(), imu_heater_periodic(), power_uavcan_send_power_device(), rand_gaussian(), and send_wp_moved().