Paparazzi UAS: sw/airborne/modules/px4_flash/px4_flash.c File Reference
px4_flash.c File Reference
#include "modules/px4_flash/px4_flash.h"
#include "modules/px4_flash/protocol.h"
#include "mcu_periph/sys_time_arch.h"
#include "modules/intermcu/intermcu_ap.h"
#include "mcu_periph/uart.h"
#include "mcu_periph/usb_serial.h"
#include "mcu.h"
#include "led.h"
#include "mcu_arch.h"
#include "mcu_periph/sys_time.h"
Macros
#define FLASH_PORT (&((FLASH_UART).device))
#define PX4_IO_FORCE_PROG FALSE
#define PROTO_INSYNC 0x12
'in sync' byte sent before status
#define PROTO_EOC 0x20
end of command
#define PROTO_OK 0x10
INSYNC/OK - 'ok' response.
#define PROTO_FAILED 0x11
INSYNC/FAILED - 'fail' response.
#define PROTO_INVALID 0x13
INSYNC/INVALID - 'invalid' response for bad commands.
#define PROTO_GET_SYNC 0x21
NOP for re-establishing sync.
#define PROTO_GET_DEVICE 0x22
get device ID bytes
#define PROTO_CHIP_ERASE 0x23
erase program area and reset program address
#define PROTO_CHIP_VERIFY 0x24
set next programming address
#define PROTO_PROG_MULTI 0x27
write bytes at program address and increment
#define PROTO_GET_CRC 0x29
compute & return a CRC
#define PROTO_BOOT 0x30
boot the application
Functions
void px4flash_init (void)
void px4flash_event (void)
Variables
bool setToBootloaderMode
bool px4ioRebootTimeout
Detailed Description
Author
Kevin van Hecke Enables to flashes the px4 FBW and AP through the original px4 bootloader. Assumes the flash port on the Pixhawk is configured as the usb.
Definition in file px4_flash.c.
Macro Definition Documentation
FLASH_PORT
#define FLASH_PORT (&((FLASH_UART).device))
Definition at line 51 of file px4_flash.c.
PROTO_BOOT
#define PROTO_BOOT 0x30
boot the application
Definition at line 74 of file px4_flash.c.
PROTO_CHIP_ERASE
#define PROTO_CHIP_ERASE 0x23
erase program area and reset program address
Definition at line 70 of file px4_flash.c.
PROTO_CHIP_VERIFY
#define PROTO_CHIP_VERIFY 0x24
set next programming address
Definition at line 71 of file px4_flash.c.
PROTO_EOC
#define PROTO_EOC 0x20
end of command
Definition at line 62 of file px4_flash.c.
PROTO_FAILED
#define PROTO_FAILED 0x11
INSYNC/FAILED - 'fail' response.
Definition at line 65 of file px4_flash.c.
PROTO_GET_CRC
#define PROTO_GET_CRC 0x29
compute & return a CRC
Definition at line 73 of file px4_flash.c.
PROTO_GET_DEVICE
#define PROTO_GET_DEVICE 0x22
get device ID bytes
Definition at line 69 of file px4_flash.c.
PROTO_GET_SYNC
#define PROTO_GET_SYNC 0x21
NOP for re-establishing sync.
Definition at line 68 of file px4_flash.c.
PROTO_INSYNC
#define PROTO_INSYNC 0x12
'in sync' byte sent before status
Definition at line 61 of file px4_flash.c.
PROTO_INVALID
#define PROTO_INVALID 0x13
INSYNC/INVALID - 'invalid' response for bad commands.
Definition at line 66 of file px4_flash.c.
PROTO_OK
#define PROTO_OK 0x10
INSYNC/OK - 'ok' response.
Definition at line 64 of file px4_flash.c.
PROTO_PROG_MULTI
#define PROTO_PROG_MULTI 0x27
write bytes at program address and increment
Definition at line 72 of file px4_flash.c.
PX4_IO_FORCE_PROG
#define PX4_IO_FORCE_PROG FALSE
Definition at line 54 of file px4_flash.c.
Function Documentation
px4flash_event()
void px4flash_event (void)
Definition at line 88 of file px4_flash.c.
References b, B115200, B230400, char_available(), IOPacket::count_code, crc_packet(), FALSE, FLASH_PORT, foo, intermcu_set_enabled(), mcu_reboot(), MCU_REBOOT_BOOTLOADER, p, PKT_CODE_SUCCESS, PROTO_EOC, PROTO_GET_SYNC, PROTO_INSYNC, PROTO_OK, PX4IO_P_SETUP_REBOOT_BL, PX4IO_PAGE_SETUP, PX4IO_REBOOT_BL_MAGIC, px4ioRebootTimeout, setToBootloaderMode, state, sys_time_cancel_timer(), sys_time_check_and_ack_timer(), sys_time_usleep(), target, TRUE, and uart_periph_set_baudrate().
px4flash_init()
void px4flash_init (void)
Definition at line 79 of file px4_flash.c.
References foo, px4ioRebootTimeout, setToBootloaderMode, and sys_time_register_timer().
Variable Documentation
px4ioRebootTimeout
bool px4ioRebootTimeout
Definition at line 77 of file px4_flash.c.
Referenced by px4flash_event(), and px4flash_init().
setToBootloaderMode
bool setToBootloaderMode
Definition at line 76 of file px4_flash.c.
Referenced by px4flash_event(), and px4flash_init().