Paparazzi UAS: sw/airborne/modules/computer_vision/qrcode/qr_code.h File Reference
qr_code.h File Reference
Parse video stream to detect and decode QR-codes using the ZBAR library.
#include <stdint.h>
#include "../lib/vision/image.h"
Functions
void qrcode_init (void)
struct image_t * qrscan (struct image_t *img, uint8_t camera_id)
Variables
bool drawRectangleAroundQRCode
Detailed Description
Parse video stream to detect and decode QR-codes using the ZBAR library.
Definition in file qr_code.h.
Function Documentation
qrcode_init()
void qrcode_init (void) extern
Definition at line 42 of file qr_code.c.
References cv_add_to_device(), foo, QRCODE_FPS, and qrscan().
qrscan()
struct image_t * qrscan (struct image_t * img, uint8_t camera_id) extern
Definition at line 54 of file qr_code.c.
References DefaultChannel, DefaultDevice, drawRectangleAroundQRCode, foo, image_create(), image_draw_line(), IMAGE_GRAYSCALE, scanner, point_t::x, and point_t::y.
Referenced by qrcode_init().
Variable Documentation
drawRectangleAroundQRCode
bool drawRectangleAroundQRCode extern
Definition at line 35 of file qr_code.c.
Referenced by qrscan().