Paparazzi UAS: sw/airborne/modules/gumstix_interface/qr_code_spi_link.c File Reference
qr_code_spi_link.c File Reference
#include "qr_code_spi_link.h"
#include "modules/imu/imu.h"
#include "mcu_periph/spi.h"
#include "mcu_periph/uart.h"
#include "pprzlink/messages.h"
#include "modules/datalink/downlink.h"
Functions
static void qr_code_spi_link_trans_cb (struct spi_transaction *trans)
void qr_code_spi_link_init (void)
void qr_code_spi_link_periodic (void)
Variables
struct spi_transaction qr_code_spi_link_transaction
static volatile bool qr_code_spi_data_available = false
uint8_t testDataOut [3] = {1, 2, 3}
uint8_t testDataIn [3] = {9, 9, 9}
Function Documentation
qr_code_spi_link_init()
void qr_code_spi_link_init (void)
Definition at line 42 of file qr_code_spi_link.c.
References spi_transaction::after_cb, spi_transaction::bitorder, spi_transaction::cpha, spi_transaction::cpol, spi_transaction::dss, spi_transaction::input_buf, spi_transaction::input_length, spi_transaction::output_buf, spi_transaction::output_length, qr_code_spi_link_trans_cb(), qr_code_spi_link_transaction, spi1, spi_slave_register(), SPICphaEdge2, SPICpolIdleHigh, SPIDss8bit, SPIMSBFirst, testDataIn, and testDataOut.
qr_code_spi_link_periodic()
void qr_code_spi_link_periodic (void)
Definition at line 58 of file qr_code_spi_link.c.
References DefaultChannel, DefaultDevice, foo, h(), spi_transaction::input_buf, qr_code_spi_data_available, qr_code_spi_link_transaction, spi1, and spi_slave_register().
qr_code_spi_link_trans_cb()
static void qr_code_spi_link_trans_cb (struct spi_transaction * trans) static
Definition at line 74 of file qr_code_spi_link.c.
References qr_code_spi_data_available.
Referenced by qr_code_spi_link_init().
Variable Documentation
qr_code_spi_data_available
volatile bool qr_code_spi_data_available = false static
Definition at line 35 of file qr_code_spi_link.c.
Referenced by qr_code_spi_link_periodic(), and qr_code_spi_link_trans_cb().
qr_code_spi_link_transaction
struct spi_transaction qr_code_spi_link_transaction
Definition at line 33 of file qr_code_spi_link.c.
Referenced by qr_code_spi_link_init(), and qr_code_spi_link_periodic().
testDataIn
uint8_t testDataIn[3] = {9, 9, 9}
Definition at line 38 of file qr_code_spi_link.c.
Referenced by qr_code_spi_link_init().
testDataOut
uint8_t testDataOut[3] = {1, 2, 3}
Definition at line 37 of file qr_code_spi_link.c.
Referenced by qr_code_spi_link_init().