Paparazzi UAS: sw/airborne/math/qr_solve/qr_solve.h File Reference
qr_solve.h File Reference
Functions
void daxpy (int n, float da, float dx[], int incx, float dy[], int incy)
float ddot (int n, float dx[], int incx, float dy[], int incy)
float dnrm2 (int n, float x[], int incx)
void dqrank (float a[], int lda, int m, int n, float tol, int *kr, int jpvt[], float qraux[])
void dqrdc (float a[], int lda, int n, int p, float qraux[], int jpvt[], float work[], int job)
int dqrls (float a[], int lda, int m, int n, float tol, int *kr, float b[], float x[], float rsd[], int jpvt[], float qraux[], int itask)
void dqrlss (float a[], int lda, int m, int n, int kr, float b[], float x[], float rsd[], int jpvt[], float qraux[])
int dqrsl (float a[], int lda, int n, int k, float qraux[], float y[], float qy[], float qty[], float b[], float rsd[], float ab[], int job)
void drotg (float *sa, float *sb, float *c, float *s)
void dscal (int n, float sa, float x[], int incx)
void dswap (int n, float x[], int incx, float y[], int incy)
void qr_solve (int m, int n, float a[], float b[], float x[])
Function Documentation
daxpy()
void daxpy (int n, float da, float dx[], int incx, float dy[], int incy)
Definition at line 23 of file qr_solve.c.
References foo.
Referenced by dqrdc(), and dqrsl().
ddot()
float ddot (int n, float dx[], int incx, float dy[], int incy)
Definition at line 144 of file qr_solve.c.
References foo.
Referenced by dqrdc(), and dqrsl().
dnrm2()
float dnrm2 (int n, float x[], int incx)
Definition at line 264 of file qr_solve.c.
References foo, and scale.
Referenced by dqrdc().
dqrank()
void dqrank (float a[], int lda, int m, int n, float tol, int * kr, int jpvt[], float qraux[])
Definition at line 357 of file qr_solve.c.
References dqrdc(), foo, and i4_min().
Referenced by dqrls().
dqrdc()
void dqrdc (float a[], int lda, int n, int p, float qraux[], int jpvt[], float work[], int job)
Definition at line 465 of file qr_solve.c.
References daxpy(), ddot(), dnrm2(), dscal(), dswap(), foo, i4_min(), p, r8_max(), and r8_sign().
Referenced by dqrank().
dqrls()
int dqrls (float a[], int lda, int m, int n, float tol, int * kr, float b[], float x[], float rsd[], int jpvt[], float qraux[], int itask)
Definition at line 714 of file qr_solve.c.
References b, DEBUG_FPRINTF, dqrank(), dqrlss(), and foo.
Referenced by qr_solve().
dqrlss()
void dqrlss (float a[], int lda, int m, int n, int kr, float b[], float x[], float rsd[], int jpvt[], float qraux[])
Definition at line 867 of file qr_solve.c.
References b, dqrsl(), foo, and UNUSED.
Referenced by dqrls().
dqrsl()
int dqrsl (float a[], int lda, int n, int k, float qraux[], float y[], float qy[], float qty[], float b[], float rsd[], float ab[], int job)
Definition at line 985 of file qr_solve.c.
References b, daxpy(), ddot(), foo, and i4_min().
Referenced by dqrlss().
drotg()
void drotg (float * sa, float * sb, float * c, float * s)
dscal()
void dscal (int n, float sa, float x[], int incx)
Definition at line 1344 of file qr_solve.c.
References foo.
Referenced by dqrdc().
dswap()
void dswap (int n, float x[], int incx, float y[], int incy)
Definition at line 1433 of file qr_solve.c.
References foo.
Referenced by dqrdc().
qr_solve()
void qr_solve (int m, int n, float a[], float b[], float x[])
Definition at line 1548 of file qr_solve.c.
References b, dqrls(), foo, r8_epsilon(), r8mat_amax(), r8mat_copy_new(), and UNUSED.
Referenced by qr_solve_wrapper().