Paparazzi UAS: sw/airborne/modules/gumstix_interface/qr_code_spi_link.h File Reference
qr_code_spi_link.h File Reference
#include "std.h"
Functions
void qr_code_spi_link_init (void)
void qr_code_spi_link_periodic (void)
Function Documentation
qr_code_spi_link_init()
void qr_code_spi_link_init (void) extern
Definition at line 42 of file qr_code_spi_link.c.
References spi_transaction::after_cb, spi_transaction::bitorder, spi_transaction::cpha, spi_transaction::cpol, spi_transaction::dss, spi_transaction::input_buf, spi_transaction::input_length, spi_transaction::output_buf, spi_transaction::output_length, qr_code_spi_link_trans_cb(), qr_code_spi_link_transaction, spi1, spi_slave_register(), SPICphaEdge2, SPICpolIdleHigh, SPIDss8bit, SPIMSBFirst, testDataIn, and testDataOut.
qr_code_spi_link_periodic()
void qr_code_spi_link_periodic (void) extern
Definition at line 58 of file qr_code_spi_link.c.
References DefaultChannel, DefaultDevice, foo, h(), spi_transaction::input_buf, qr_code_spi_data_available, qr_code_spi_link_transaction, spi1, and spi_slave_register().