Paparazzi UAS: sw/airborne/modules/computer_vision/qrcode/qr_code.c File Reference
qr_code.c File Reference
#include "qr_code.h"
#include "cv.h"
#include "zbar.h"
#include <stdio.h>
#include "modules/datalink/telemetry.h"
Macros
#define QRCODE_DRAW_RECTANGLE FALSE
#define QRCODE_FPS 0
Default FPS (zero means run at camera fps)
Functions
void qrcode_init (void)
struct image_t * qrscan (struct image_t *img, uint8_t camera_id)
Variables
bool drawRectangleAroundQRCode = QRCODE_DRAW_RECTANGLE
zbar_image_scanner_t * scanner = 0
Macro Definition Documentation
QRCODE_DRAW_RECTANGLE
#define QRCODE_DRAW_RECTANGLE FALSE
Definition at line 33 of file qr_code.c.
QRCODE_FPS
#define QRCODE_FPS 0
Default FPS (zero means run at camera fps)
Definition at line 38 of file qr_code.c.
Function Documentation
qrcode_init()
void qrcode_init (void)
Definition at line 42 of file qr_code.c.
References cv_add_to_device(), foo, QRCODE_FPS, and qrscan().
qrscan()
struct image_t * qrscan (struct image_t * img, uint8_t camera_id)
Definition at line 54 of file qr_code.c.
References DefaultChannel, DefaultDevice, drawRectangleAroundQRCode, foo, image_create(), image_draw_line(), IMAGE_GRAYSCALE, scanner, point_t::x, and point_t::y.
Referenced by qrcode_init().
Variable Documentation
drawRectangleAroundQRCode
bool drawRectangleAroundQRCode = QRCODE_DRAW_RECTANGLE
Definition at line 35 of file qr_code.c.
Referenced by qrscan().
scanner
zbar_image_scanner_t* scanner = 0
Definition at line 52 of file qr_code.c.
Referenced by qrscan().