Paparazzi UAS: sw/airborne/math/qr_solve/r8lib_min.h File Reference
r8lib_min.h File Reference
Functions
void r8mat_copy_new (int m, int n, float a1[], float a2[])
float r8_epsilon (void)
float r8mat_amax (int m, int n, float a[])
float r8_sign (float x)
float r8_max (float x, float y)
float * r8mat_transpose_new (int m, int n, float a[])
float * r8mat_mm_new (int n1, int n2, int n3, float a[], float b[])
float * r8mat_cholesky_factor (int n, float a[], int *flag)
float * r8mat_mv_new (int m, int n, float a[], float x[])
float * r8mat_cholesky_solve (int n, float l[], float b[])
float * r8mat_l_solve (int n, float a[], float b[])
float * r8mat_lt_solve (int n, float a[], float b[])
float * r8mat_mtv_new (int m, int n, float a[], float x[])
float r8vec_max (int n, float r8vec[])
int i4_min (int i1, int i2)
int i4_max (int i1, int i2)
Function Documentation
i4_max()
int i4_max (int i1, int i2)
Definition at line 515 of file r8lib_min.c.
References foo.
i4_min()
int i4_min (int i1, int i2)
Definition at line 474 of file r8lib_min.c.
References foo.
Referenced by dqrank(), dqrdc(), and dqrsl().
r8_epsilon()
float r8_epsilon (void)
Definition at line 68 of file r8lib_min.c.
Referenced by qr_solve().
r8_max()
float r8_max (float x, float y)
Definition at line 204 of file r8lib_min.c.
Referenced by dqrdc().
r8_sign()
float r8_sign (float x)
Definition at line 163 of file r8lib_min.c.
Referenced by dqrdc().
r8mat_amax()
float r8mat_amax (int m, int n, float a[])
Definition at line 107 of file r8lib_min.c.
References foo.
Referenced by qr_solve().
r8mat_cholesky_factor()
float * r8mat_cholesky_factor (int n, float a[], int * flag)
r8mat_cholesky_solve()
float * r8mat_cholesky_solve (int n, float l[], float b[])
r8mat_copy_new()
void r8mat_copy_new (int m, int n, float a1[], float a2[])
Definition at line 19 of file r8lib_min.c.
References foo.
Referenced by qr_solve().
r8mat_l_solve()
float * r8mat_l_solve (int n, float a[], float b[])
Definition at line 245 of file r8lib_min.c.
References b, and foo.
r8mat_lt_solve()
float * r8mat_lt_solve (int n, float a[], float b[])
Definition at line 305 of file r8lib_min.c.
References b, and foo.
r8mat_mm_new()
float * r8mat_mm_new (int n1, int n2, int n3, float a[], float b[])
r8mat_mtv_new()
float * r8mat_mtv_new (int m, int n, float a[], float x[])
Definition at line 365 of file r8lib_min.c.
References foo.
r8mat_mv_new()
float * r8mat_mv_new (int m, int n, float a[], float x[])
r8mat_transpose_new()
float * r8mat_transpose_new (int m, int n, float a[])
r8vec_max()
float r8vec_max (int n, float r8vec[])
Definition at line 422 of file r8lib_min.c.
References foo.