Paparazzi UAS: sw/airborne/modules/radio_control/radio_control_uavcan.h File Reference
radio_control_uavcan.h File Reference
#include "generated/radio.h"
Macros
#define RC_PPM_TICKS_OF_USEC(_x) (_x)
#define RC_PPM_SIGNED_TICKS_OF_USEC(_x) (_x)
#define USEC_OF_RC_PPM_TICKS(_x) (_x)
Functions
void rc_uavcan_init (void)
void rc_uavcan_event (void)
Detailed Description
Author
Fabien-B Fabie.nosp@m.n-B@.nosp@m.githu.nosp@m.b.co.nosp@m.m Radio control from DroneCAN message dronecan.sensors.rc.RCInput.
Definition in file radio_control_uavcan.h.
Macro Definition Documentation
RC_PPM_SIGNED_TICKS_OF_USEC
#define RC_PPM_SIGNED_TICKS_OF_USEC (_x) (_x)
Definition at line 18 of file radio_control_uavcan.h.
RC_PPM_TICKS_OF_USEC
#define RC_PPM_TICKS_OF_USEC (_x) (_x)
Definition at line 17 of file radio_control_uavcan.h.
USEC_OF_RC_PPM_TICKS
#define USEC_OF_RC_PPM_TICKS (_x) (_x)
Definition at line 19 of file radio_control_uavcan.h.
Function Documentation
rc_uavcan_event()
void rc_uavcan_event (void) extern
Definition at line 46 of file radio_control_uavcan.c.
References foo, RadioControl::frame_cpt, RadioControl::nb_channel, pprz_mtx_trylock(), pprz_mtx_unlock(), radio_control, RADIO_CONTROL_UAVCAN_ID, RadioControl::radio_ok_cpt, rc_dronecan_msg, rc_frame_available, rc_mtx, RC_OK, RadioControl::status, and RadioControl::time_since_last_frame.
rc_uavcan_init()
void rc_uavcan_init (void) extern
Definition at line 37 of file radio_control_uavcan.c.
References foo, RadioControl::nb_channel, pprz_mtx_init(), radio_control, rc_frame_available, rc_mtx, rc_uavcan_cb(), rc_uavcan_ev, and uavcan_bind().