Paparazzi UAS: sw/airborne/modules/radio_control/hott.h File Reference
hott.h File Reference
Radio control via single HOTT receiver in SUMD mode.
#include "modules/radio_control/hott_common.h"
Functions
void hott_init (void)
RC init function.
void hott_event (void)
RC event function.
Variables
struct SHott hott
HOTT struct.
Detailed Description
Radio control via single HOTT receiver in SUMD mode.
Definition in file hott.h.
Function Documentation
hott_event()
void hott_event (void) extern
RC event function.
Definition at line 291 of file hott.c.
References foo, SHott::frame_available, RadioControl::frame_cpt, hott, hott_common_decode_event(), hott_event_timer, hott_periodic_event(), SHott::pulses, radio_control, RADIO_CONTROL_HOTT_ID, RadioControl::radio_ok_cpt, RC_OK, RadioControl::status, SysTimeTimer, SysTimeTimerStart, and RadioControl::time_since_last_frame.
hott_init()
void hott_init (void) extern
RC init function.
Definition at line 123 of file hott.c.
References DefaultPeriodic, foo, hott, hott_common_init(), hott_msgs_init(), HOTT_NB_CHANNEL, RadioControl::nb_channel, radio_control, register_periodic_telemetry(), and send_hott().
Variable Documentation
hott
struct SHott hott extern
HOTT struct.
Definition at line 33 of file hott.c.
Referenced by hott_event(), hott_init(), and send_hott().