Paparazzi UAS: sw/airborne/modules/radio_control/radio_control_uavcan.c File Reference
radio_control_uavcan.c File Reference
#include "modules/radio_control/radio_control_uavcan.h"
#include "modules/radio_control/radio_control.h"
#include "uavcan/uavcan.h"
#include "modules/core/abi.h"
#include "modules/core/threads.h"
#include "dronecan.sensors.rc.RCInput.h"
#include "generated/radio.h"
Functions
static void rc_uavcan_cb (struct uavcan_iface_t *iface, CanardRxTransfer *transfer)
void rc_uavcan_init (void)
void rc_uavcan_event (void)
Variables
static uavcan_event rc_uavcan_ev
struct dronecan_sensors_rc_RCInput rc_dronecan_msg
static bool rc_frame_available
static pprz_mutex_t rc_mtx
Detailed Description
Author
Fabien-B Fabie.nosp@m.n-B@.nosp@m.githu.nosp@m.b.co.nosp@m.m Radio control from DroneCAN message dronecan.sensors.rc.RCInput.
Definition in file radio_control_uavcan.c.
Function Documentation
rc_uavcan_cb()
static void rc_uavcan_cb (struct uavcan_iface_t * iface, CanardRxTransfer * transfer) static
Definition at line 27 of file radio_control_uavcan.c.
References foo, pprz_mtx_trylock(), pprz_mtx_unlock(), rc_dronecan_msg, rc_frame_available, rc_mtx, and transfer().
Referenced by rc_uavcan_init().
rc_uavcan_event()
void rc_uavcan_event (void)
Definition at line 46 of file radio_control_uavcan.c.
References foo, RadioControl::frame_cpt, RadioControl::nb_channel, pprz_mtx_trylock(), pprz_mtx_unlock(), radio_control, RADIO_CONTROL_UAVCAN_ID, RadioControl::radio_ok_cpt, rc_dronecan_msg, rc_frame_available, rc_mtx, RC_OK, RadioControl::status, and RadioControl::time_since_last_frame.
rc_uavcan_init()
void rc_uavcan_init (void)
Definition at line 37 of file radio_control_uavcan.c.
References foo, RadioControl::nb_channel, pprz_mtx_init(), radio_control, rc_frame_available, rc_mtx, rc_uavcan_cb(), rc_uavcan_ev, and uavcan_bind().
Variable Documentation
rc_dronecan_msg
struct dronecan_sensors_rc_RCInput rc_dronecan_msg
Definition at line 22 of file radio_control_uavcan.c.
Referenced by rc_uavcan_cb(), and rc_uavcan_event().
rc_frame_available
bool rc_frame_available static
Definition at line 23 of file radio_control_uavcan.c.
Referenced by rc_uavcan_cb(), rc_uavcan_event(), and rc_uavcan_init().
rc_mtx
pprz_mutex_t rc_mtx static
Definition at line 24 of file radio_control_uavcan.c.
Referenced by rc_uavcan_cb(), rc_uavcan_event(), and rc_uavcan_init().
rc_uavcan_ev
uavcan_event rc_uavcan_ev static
Definition at line 20 of file radio_control_uavcan.c.
Referenced by rc_uavcan_init().