Paparazzi UAS: sw/airborne/modules/sensors/range_sensor_uavcan.c File Reference
range_sensor_uavcan.c File Reference
Range sensor on the uavcan bus.
#include "range_sensor_uavcan.h"
#include "uavcan/uavcan.h"
#include "core/abi.h"
#include "uavcan.equipment.range_sensor.Measurement.h"
#include "modules/datalink/telemetry.h"
Functions
static void range_sensor_uavcan_send_lidar (struct transport_tx *trans, struct link_device *dev)
static void range_sensor_uavcan_cb (struct uavcan_iface_t *iface, CanardRxTransfer *transfer)
void range_sensor_uavcan_init (void)
Variables
static struct uavcan_equipment_range_sensor_Measurement range_sensor_uavcan = {0}
static uavcan_event range_sensor_uavcan_ev
Detailed Description
Range sensor on the uavcan bus.
Definition in file range_sensor_uavcan.c.
Function Documentation
range_sensor_uavcan_cb()
static void range_sensor_uavcan_cb (struct uavcan_iface_t * iface, CanardRxTransfer * transfer) static
Definition at line 50 of file range_sensor_uavcan.c.
References AGL_UAVCAN_ID, foo, get_sys_time_usec(), range_sensor_uavcan, and transfer().
Referenced by range_sensor_uavcan_init().
range_sensor_uavcan_init()
void range_sensor_uavcan_init (void)
Definition at line 62 of file range_sensor_uavcan.c.
References DefaultPeriodic, foo, range_sensor_uavcan_cb(), range_sensor_uavcan_ev, range_sensor_uavcan_send_lidar(), register_periodic_telemetry(), and uavcan_bind().
range_sensor_uavcan_send_lidar()
static void range_sensor_uavcan_send_lidar (struct transport_tx * trans, struct link_device * dev) static
Definition at line 39 of file range_sensor_uavcan.c.
References dev, foo, and range_sensor_uavcan.
Referenced by range_sensor_uavcan_init().
Variable Documentation
range_sensor_uavcan
struct uavcan_equipment_range_sensor_Measurement range_sensor_uavcan = {0} static
Definition at line 33 of file range_sensor_uavcan.c.
Referenced by range_sensor_uavcan_cb(), and range_sensor_uavcan_send_lidar().
range_sensor_uavcan_ev
uavcan_event range_sensor_uavcan_ev static
Definition at line 34 of file range_sensor_uavcan.c.
Referenced by range_sensor_uavcan_init().