Paparazzi UAS: sw/airborne/modules/sensors/range_sensor_uavcan.h File Reference
range_sensor_uavcan.h File Reference
Range sensor sensor on the uavcan bus.
Functions
void range_sensor_uavcan_init (void)
Detailed Description
Range sensor sensor on the uavcan bus.
Definition in file range_sensor_uavcan.h.
Function Documentation
range_sensor_uavcan_init()
void range_sensor_uavcan_init (void) extern
Definition at line 62 of file range_sensor_uavcan.c.
References DefaultPeriodic, foo, range_sensor_uavcan_cb(), range_sensor_uavcan_ev, range_sensor_uavcan_send_lidar(), register_periodic_telemetry(), and uavcan_bind().