Paparazzi UAS: sw/airborne/modules/range_forcefield/range_forcefield.h File Reference
range_forcefield.h File Reference
#include <std.h>
#include "math/pprz_algebra_float.h"
Data Structures
struct range_forcefield_param_t
Functions
void range_forcefield_init (void)
void range_forcefield_periodic (void)
void range_forcefield_update (float range, struct FloatEulers *body_to_sensor_eulers)
Variables
struct range_forcefield_param_t range_forcefield_param
Data Structure Documentation
range_forcefield_param_t
struct range_forcefield_param_t
Definition at line 32 of file range_forcefield.h.
Data Fields
float inner_limit
float max_vel
float min_vel
float outer_limit
Function Documentation
range_forcefield_init()
void range_forcefield_init (void) extern
Definition at line 76 of file range_forcefield.c.
References ff_nearest_obs_neg, ff_nearest_obs_pos, foo, range_forcefield_param_t::inner_limit, range_forcefield_param_t::max_vel, range_forcefield_param_t::min_vel, obstacle_cb(), obstacle_ev, range_forcefield_param_t::outer_limit, RANGE_FORCEFIELD_INNER_LIMIT, RANGE_FORCEFIELD_MAX_VEL, RANGE_FORCEFIELD_MIN_VEL, RANGE_FORCEFIELD_OUTER_LIMIT, range_forcefield_param, RANGE_FORCEFIELD_RECIEVE_ID, FloatVect3::x, FloatVect3::y, and FloatVect3::z.
range_forcefield_periodic()
void range_forcefield_periodic (void) extern
Definition at line 97 of file range_forcefield.c.
References compute_ff_vel(), ff_nearest_obs_neg, ff_nearest_obs_pos, foo, RANGE_FORCEFIELD_ID, RANGE_FORCEFIELD_OUTER_LIMIT, FloatVect3::x, FloatVect3::y, and FloatVect3::z.
range_forcefield_update()
void range_forcefield_update (float range, struct FloatEulers * body_to_sensor_eulers) extern
Definition at line 121 of file range_forcefield.c.
References ff_nearest_obs_neg, ff_nearest_obs_pos, float_rmat_of_eulers, float_rmat_transp_vmult(), foo, store_min_dist(), FloatVect3::x, FloatVect3::y, and FloatVect3::z.
Referenced by obstacle_cb().
Variable Documentation
range_forcefield_param
struct range_forcefield_param_t range_forcefield_param extern
Definition at line 56 of file range_forcefield.c.
Referenced by compute_ff_vel(), and range_forcefield_init().