Paparazzi UAS: sw/airborne/modules/radio_control/rc_datalink.h File Reference
rc_datalink.h File Reference
Radio control input via datalink.
#include "std.h"
Macros
#define RC_DL_NB_CHANNEL 11
#define RADIO_ROLL 0
Redefining RADIO_* Do not use with radio.h (ppm rc)
#define RADIO_PITCH 1
#define RADIO_YAW 2
#define RADIO_THROTTLE 3
#define RADIO_MODE 4
#define RADIO_AUX1 5
#define RADIO_AUX2 7
#define RADIO_AUX4 8
#define RADIO_AUX5 9
#define RADIO_AUX6 10
#define RADIO_AUX7 6
#define RADIO_KILL_SWITCH RADIO_AUX1
#define AP_MODE_SWITCH RADIO_AUX7
Functions
void parse_rc_up_datalink (int8_t n, int8_t *channels)
Decode datalink message to get rc values with RC_UP message.
void rc_datalink_parse_RC_UP (uint8_t *buf)
void rc_datalink_init (void)
RC init function.
void rc_datalink_event (void)
RC event function.
Variables
int8_t rc_dl_values [RC_DL_NB_CHANNEL]
volatile bool rc_dl_frame_available
Detailed Description
Radio control input via datalink.
Definition in file rc_datalink.h.
Macro Definition Documentation
AP_MODE_SWITCH
#define AP_MODE_SWITCH RADIO_AUX7
Definition at line 55 of file rc_datalink.h.
RADIO_AUX1
#define RADIO_AUX1 5
Definition at line 43 of file rc_datalink.h.
RADIO_AUX2
#define RADIO_AUX2 7
Definition at line 44 of file rc_datalink.h.
RADIO_AUX4
#define RADIO_AUX4 8
Definition at line 45 of file rc_datalink.h.
RADIO_AUX5
#define RADIO_AUX5 9
Definition at line 46 of file rc_datalink.h.
RADIO_AUX6
#define RADIO_AUX6 10
Definition at line 47 of file rc_datalink.h.
RADIO_AUX7
#define RADIO_AUX7 6
Definition at line 48 of file rc_datalink.h.
RADIO_KILL_SWITCH
#define RADIO_KILL_SWITCH RADIO_AUX1
Definition at line 51 of file rc_datalink.h.
RADIO_MODE
#define RADIO_MODE 4
Definition at line 42 of file rc_datalink.h.
RADIO_PITCH
#define RADIO_PITCH 1
Definition at line 39 of file rc_datalink.h.
RADIO_ROLL
#define RADIO_ROLL 0
Redefining RADIO_* Do not use with radio.h (ppm rc)
Definition at line 38 of file rc_datalink.h.
RADIO_THROTTLE
#define RADIO_THROTTLE 3
Definition at line 41 of file rc_datalink.h.
RADIO_YAW
#define RADIO_YAW 2
Definition at line 40 of file rc_datalink.h.
RC_DL_NB_CHANNEL
#define RC_DL_NB_CHANNEL 11
Definition at line 32 of file rc_datalink.h.
Function Documentation
parse_rc_up_datalink()
void parse_rc_up_datalink (int8_t n, int8_t * channels) extern
Decode datalink message to get rc values with RC_UP message.
Definition at line 51 of file rc_datalink.c.
References rc_dl_frame_available, and rc_dl_values.
Referenced by mavlink_common_message_handler(), and rc_datalink_parse_RC_UP().
rc_datalink_event()
void rc_datalink_event (void) extern
RC event function.
Definition at line 76 of file rc_datalink.c.
References foo, RadioControl::frame_cpt, radio_control, RADIO_CONTROL_DATALINK_ID, RadioControl::radio_ok_cpt, rc_datalink_normalize(), rc_dl_frame_available, rc_dl_values, RC_OK, RadioControl::status, RadioControl::time_since_last_frame, and RadioControl::values.
rc_datalink_init()
void rc_datalink_init (void) extern
RC init function.
Definition at line 36 of file rc_datalink.c.
References RadioControl::nb_channel, radio_control, rc_dl_frame_available, and RC_DL_NB_CHANNEL.
rc_datalink_parse_RC_UP()
void rc_datalink_parse_RC_UP (uint8_t * buf) extern
Definition at line 42 of file rc_datalink.c.
References foo, LED_TOGGLE, and parse_rc_up_datalink().
Variable Documentation
rc_dl_frame_available
volatile bool rc_dl_frame_available extern
Definition at line 33 of file rc_datalink.c.
Referenced by parse_rc_up_datalink(), rc_datalink_event(), and rc_datalink_init().
rc_dl_values
int8_t rc_dl_values[RC_DL_NB_CHANNEL] extern
Definition at line 32 of file rc_datalink.c.
Referenced by parse_rc_up_datalink(), and rc_datalink_event().