Paparazzi UAS: sw/airborne/utils/ring_buffer.c File Reference
ring_buffer.c File Reference
#include "utils/ring_buffer.h"
#include <string.h>
Functions
void ring_buffer_init (ring_buffer_t *rb, uint8_t *buf, size_t size)
Init.
size_t ring_buffer_available (ring_buffer_t *rb)
size_t ring_buffer_free_space (ring_buffer_t *ring_buffer)
size_t ring_buffer_write (ring_buffer_t *rb, const uint8_t *data, size_t len)
Write.
size_t ring_buffer_read (ring_buffer_t *rb, uint8_t *read_buffer, size_t len)
Read.
Function Documentation
ring_buffer_available()
size_t ring_buffer_available (ring_buffer_t * ring_buffer)
Returns
the number of bytes available in the
Parameters
ring_buffer.
Definition at line 20 of file ring_buffer.c.
References foo.
Referenced by ring_buffer_free_space(), ring_buffer_read(), tunnel_uavcan_char_available(), and tunnel_uavcan_send_message().
ring_buffer_free_space()
size_t ring_buffer_free_space (ring_buffer_t * ring_buffer)
Returns
the number of bytes that can be written in
Parameters
ring_buffer
Definition at line 29 of file ring_buffer.c.
References foo, and ring_buffer_available().
Referenced by ring_buffer_write(), and tunnel_uavcan_check_free_space().
ring_buffer_init()
void ring_buffer_init (ring_buffer_t * ring_buffer, uint8_t * buf, size_t size)
Init.
Parameters
ring_buffer with the
buf subjacent buffer of size
size.
Definition at line 13 of file ring_buffer.c.
References foo.
Referenced by tunnel_uavcan_init_periph().
ring_buffer_read()
size_t ring_buffer_read (ring_buffer_t * ring_buffer, uint8_t * read_buffer, size_t len)
Read.
Parameters
len bytes from
ring_buffer into
read_buffer.
Returns
the number of byte effectively read from the ring_buffer.
Definition at line 58 of file ring_buffer.c.
References foo, and ring_buffer_available().
Referenced by tunnel_uavcan_get_byte(), and tunnel_uavcan_send_message().
ring_buffer_write()
size_t ring_buffer_write (ring_buffer_t * ring_buffer, const uint8_t * data, size_t len)
Write.
Parameters
data of size
len in
ring_buffer.
Returns
the number of byte effectively written in the ring_buffer.
Definition at line 33 of file ring_buffer.c.
References foo, and ring_buffer_free_space().
Referenced by tunnel_uavcan_cb(), and tunnel_uavcan_put_buffer().