Paparazzi UAS: sw/airborne/firmwares/rotorcraft/guidance/guidance_h.h File Reference
guidance_h.h File Reference
Horizontal guidance for rotorcrafts.
#include "math/pprz_algebra_int.h"
#include "math/pprz_algebra_float.h"
#include "firmwares/rotorcraft/guidance/guidance_h_ref.h"
#include "generated/airframe.h"
#include "std.h"
Data Structures
struct HorizontalGuidanceSetpoint
struct HorizontalGuidanceReference
struct HorizontalGuidanceGains
struct HorizontalGuidance
Macros
#define GUIDANCE_H_USE_REF TRUE
Use horizontal guidance reference trajectory.
#define GUIDANCE_H_USE_SPEED_REF TRUE
Use horizontal guidance speed reference.
#define GUIDANCE_H_MODE_KILL 0
#define GUIDANCE_H_MODE_RATE 1
#define GUIDANCE_H_MODE_ATTITUDE 2
#define GUIDANCE_H_MODE_HOVER 3
#define GUIDANCE_H_MODE_NAV 4
#define GUIDANCE_H_MODE_RC_DIRECT 5
#define GUIDANCE_H_MODE_CARE_FREE 6
#define GUIDANCE_H_MODE_FORWARD 7
#define GUIDANCE_H_MODE_MODULE 8
#define GUIDANCE_H_MODE_FLIP 9
#define GUIDANCE_H_MODE_GUIDED 10
#define guidance_h_SetUseRef(_val)
Functions
void guidance_h_init (void)
void guidance_h_mode_changed (uint8_t new_mode)
void guidance_h_read_rc (bool in_flight)
void guidance_h_run (bool in_flight)
void guidance_h_hover_enter (void)
void guidance_h_nav_enter (void)
void guidance_h_from_nav (bool in_flight)
Set horizontal guidance from NAV and run control loop.
void guidance_h_set_igain (uint32_t igain)
void guidance_h_guided_run (bool in_flight)
Run GUIDED mode control.
bool guidance_h_set_guided_pos (float x, float y)
Set horizontal position setpoint in GUIDED mode.
bool guidance_h_set_guided_heading (float heading)
Set heading setpoint in GUIDED mode.
bool guidance_h_set_guided_body_vel (float vx, float vy)
Set body relative horizontal velocity setpoint in GUIDED mode.
bool guidance_h_set_guided_vel (float vx, float vy)
Set horizontal velocity setpoint in GUIDED mode.
bool guidance_h_set_guided_heading_rate (float rate)
Set heading rate setpoint in GUIDED mode.
const struct Int32Vect2 * guidance_h_get_pos_err (void)
Gets the position error.
static void guidance_h_SetMaxSpeed (float speed)
static void guidance_h_SetOmega (float omega)
static void guidance_h_SetZeta (float zeta)
static void guidance_h_SetTau (float tau)
Variables
struct HorizontalGuidance guidance_h
int32_t transition_percentage
Detailed Description
Horizontal guidance for rotorcrafts.
Definition in file guidance_h.h.
Data Structure Documentation
struct HorizontalGuidanceSetpoint
Definition at line 69 of file guidance_h.h.
Data Fields
float heading
float heading_rate
uint8_t mask bit 5: vx & vy, bit 6: vz, bit 7: vyaw
struct Int32Vect2 pos horizontal position setpoint in NED.
fixed point representation: Q23.8 accuracy 0.0039, range 8388km
struct Int32Vect2 speed only used in HOVER mode if GUIDANCE_H_USE_SPEED_REF or in GUIDED mode
struct HorizontalGuidanceReference
Definition at line 81 of file guidance_h.h.
Data Fields
struct Int32Vect2 accel with INT32_ACCEL_FRAC
struct Int32Vect2 pos with INT32_POS_FRAC
struct Int32Vect2 speed with INT32_SPEED_FRAC
struct HorizontalGuidanceGains
Definition at line 87 of file guidance_h.h.
Data Fields
int32_t a
int32_t d
int32_t i
int32_t p
int32_t v
struct HorizontalGuidance
Definition at line 95 of file guidance_h.h.
Data Fields
bool approx_force_by_thrust
struct HorizontalGuidanceGains gains
uint8_t mode
struct FloatEulers rc_sp
struct HorizontalGuidanceReference ref reference calculated from setpoints
struct HorizontalGuidanceSetpoint sp setpoints
bool use_ref
Macro Definition Documentation
#define GUIDANCE_H_MODE_ATTITUDE 2
Definition at line 58 of file guidance_h.h.
Referenced by autopilot_static_set_mode(), booz_fms_impl_init(), guidance_h_mode_changed(), guidance_h_read_rc(), guidance_h_run(), vi_init(), and vi_periodic().
#define GUIDANCE_H_MODE_CARE_FREE 6
Definition at line 62 of file guidance_h.h.
Referenced by autopilot_static_set_mode(), guidance_h_mode_changed(), guidance_h_read_rc(), and guidance_h_run().
#define GUIDANCE_H_MODE_FLIP 9
Definition at line 65 of file guidance_h.h.
Referenced by autopilot_static_set_mode(), guidance_h_mode_changed(), guidance_h_read_rc(), and guidance_h_run().
#define GUIDANCE_H_MODE_FORWARD 7
Definition at line 63 of file guidance_h.h.
Referenced by autopilot_static_set_mode(), guidance_h_mode_changed(), guidance_h_read_rc(), and guidance_h_run().
#define GUIDANCE_H_MODE_GUIDED 10
Definition at line 66 of file guidance_h.h.
Referenced by autopilot_static_set_mode(), guidance_h_mode_changed(), guidance_h_run(), guidance_h_set_guided_heading(), guidance_h_set_guided_heading_rate(), guidance_h_set_guided_pos(), guidance_h_set_guided_vel(), and orange_avoider_guided_periodic().
#define GUIDANCE_H_MODE_HOVER 3
Definition at line 59 of file guidance_h.h.
Referenced by autopilot_static_set_mode(), guidance_h_mode_changed(), guidance_h_read_rc(), guidance_h_run(), guidance_h_update_reference(), and stabilization_indi_rate_run().
#define GUIDANCE_H_MODE_KILL 0
Definition at line 56 of file guidance_h.h.
Referenced by autopilot_static_set_mode(), guidance_h_init(), and guidance_h_mode_changed().
#define GUIDANCE_H_MODE_MODULE 8
Definition at line 64 of file guidance_h.h.
Referenced by guidance_h_mode_changed(), guidance_h_read_rc(), and guidance_h_run().
#define GUIDANCE_H_MODE_NAV 4
Definition at line 60 of file guidance_h.h.
Referenced by autopilot_static_set_mode(), guidance_h_mode_changed(), guidance_h_read_rc(), guidance_h_run(), and stabilization_indi_rate_run().
#define GUIDANCE_H_MODE_RATE 1
Definition at line 57 of file guidance_h.h.
Referenced by autopilot_static_set_mode(), guidance_h_mode_changed(), guidance_h_read_rc(), and guidance_h_run().
#define GUIDANCE_H_MODE_RC_DIRECT 5
Definition at line 61 of file guidance_h.h.
Referenced by autopilot_static_set_mode(), guidance_h_mode_changed(), guidance_h_read_rc(), and guidance_h_run().
#define guidance_h_SetUseRef (_val)
Value:
{                    \
    guidance_h.use_ref = _val && GUIDANCE_H_USE_REF;    \
  }
Definition at line 173 of file guidance_h.h.
#define GUIDANCE_H_USE_REF TRUE
Use horizontal guidance reference trajectory.
Default is TRUE, define to FALSE to always disable it.
Definition at line 45 of file guidance_h.h.
Referenced by guidance_h_init().
#define GUIDANCE_H_USE_SPEED_REF TRUE
Use horizontal guidance speed reference.
This also allows to give velocity commands via RC in GUIDANCE_H_MODE_HOVER. Default is TRUE, define to FALSE to always disable it.
Definition at line 53 of file guidance_h.h.
Function Documentation
void guidance_h_from_nav (bool in_flight)
Set horizontal guidance from NAV and run control loop.
Definition at line 579 of file guidance_h.c.
References ANGLE_BFP_OF_REAL, ANGLE_FLOAT_OF_BFP, FLOAT_ANGLE_NORMALIZE, guidance_h, guidance_h_cmd_earth, guidance_h_nav_enter(), guidance_h_traj_run(), guidance_h_update_reference(), guidance_hybrid_reset_heading(), guidance_hybrid_run(), guidance_indi_run(), HorizontalGuidanceSetpoint::heading, horizontal_mode, HORIZONTAL_MODE_ATTITUDE, HORIZONTAL_MODE_MANUAL, INT32_VECT2_NED_OF_ENU, nav_cmd_pitch, nav_cmd_roll, nav_cmd_yaw, nav_heading, nav_pitch, nav_roll, navigation_carrot, navigation_target, Int32Eulers::phi, HorizontalGuidanceSetpoint::pos, Int32Eulers::psi, HorizontalGuidance::sp, stabilization_attitude_run(), stabilization_attitude_set_earth_cmd_i(), stabilization_attitude_set_rpy_setpoint_i(), stabilization_cmd, and Int32Eulers::theta.
Referenced by guidance_h_run().
const struct Int32Vect2* guidance_h_get_pos_err (void)
Gets the position error.
Parameters
none.
Returns
Pointer to a structure containing x and y position errors
Definition at line 760 of file guidance_h.c.
References guidance_h_pos_err.
void guidance_h_guided_run (bool in_flight)
Run GUIDED mode control.
Definition at line 688 of file guidance_h.c.
References ANGLE_BFP_OF_REAL, guidance_h, guidance_h_cmd_earth, guidance_h_hover_enter(), guidance_h_traj_run(), guidance_h_update_reference(), guidance_indi_run(), HorizontalGuidanceSetpoint::heading, HorizontalGuidance::sp, stabilization_attitude_run(), and stabilization_attitude_set_earth_cmd_i().
Referenced by guidance_h_run().
void guidance_h_hover_enter (void)
Definition at line 542 of file guidance_h.c.
References guidance_h, HorizontalGuidanceSetpoint::heading, HorizontalGuidanceSetpoint::mask, HorizontalGuidanceSetpoint::pos, FloatEulers::psi, HorizontalGuidance::rc_sp, reset_guidance_reference_from_current_position(), HorizontalGuidance::sp, HorizontalGuidanceSetpoint::speed, stateGetNedToBodyEulers_f(), stateGetPositionNed_i(), VECT2_COPY, Int32Vect2::x, and Int32Vect2::y.
Referenced by guidance_h_guided_run(), guidance_h_mode_changed(), and wedgebug_periodic().
void guidance_h_init (void)
Definition at line 176 of file guidance_h.c.
References HorizontalGuidanceGains::a, HorizontalGuidance::approx_force_by_thrust, HorizontalGuidanceGains::d, DefaultPeriodic, FLOAT_EULERS_ZERO, HorizontalGuidance::gains, gh_ref_init(), guidance_h, GUIDANCE_H_AGAIN, GUIDANCE_H_APPROX_FORCE_BY_THRUST, GUIDANCE_H_MODE_KILL, guidance_h_module_init(), guidance_h_trim_att_integrator, GUIDANCE_H_USE_REF, GUIDANCE_H_VGAIN, HorizontalGuidanceSetpoint::heading, HorizontalGuidanceSetpoint::heading_rate, HorizontalGuidanceGains::i, INT_VECT2_ZERO, HorizontalGuidance::mode, HorizontalGuidanceGains::p, HorizontalGuidanceSetpoint::pos, HorizontalGuidance::rc_sp, register_periodic_telemetry(), send_gh(), send_hover_loop(), send_href(), send_tune_hover(), HorizontalGuidance::sp, transition_theta_offset, HorizontalGuidance::use_ref, and HorizontalGuidanceGains::v.
void guidance_h_mode_changed (uint8_t new_mode)
Definition at line 222 of file guidance_h.c.
References guidance_flip_enter(), guidance_h, guidance_h_hover_enter(), GUIDANCE_H_MODE_ATTITUDE, GUIDANCE_H_MODE_CARE_FREE, GUIDANCE_H_MODE_FLIP, GUIDANCE_H_MODE_FORWARD, GUIDANCE_H_MODE_GUIDED, GUIDANCE_H_MODE_HOVER, GUIDANCE_H_MODE_KILL, GUIDANCE_H_MODE_MODULE, GUIDANCE_H_MODE_NAV, GUIDANCE_H_MODE_RATE, GUIDANCE_H_MODE_RC_DIRECT, guidance_h_module_enter(), guidance_h_nav_enter(), guidance_hybrid_norm_ref_airspeed, guidance_indi_enter(), HorizontalGuidance::mode, stabilization_attitude_enter(), stabilization_attitude_reset_care_free_heading(), stabilization_none_enter(), and stabilization_rate_enter().
Referenced by autopilot_static_set_mode().
void guidance_h_nav_enter (void)
Definition at line 565 of file guidance_h.c.
References guidance_h, HorizontalGuidanceSetpoint::heading, INT32_VECT2_NED_OF_ENU, HorizontalGuidanceSetpoint::mask, nav_heading, navigation_carrot, HorizontalGuidanceSetpoint::pos, FloatEulers::psi, Int32Eulers::psi, reset_guidance_reference_from_current_position(), HorizontalGuidance::sp, stateGetNedToBodyEulers_f(), and stateGetNedToBodyEulers_i().
Referenced by guidance_h_from_nav(), and guidance_h_mode_changed().
void guidance_h_read_rc (bool in_flight)
Definition at line 302 of file guidance_h.c.
References FALSE, FLOAT_EULERS_ZERO, guidance_h, GUIDANCE_H_MODE_ATTITUDE, GUIDANCE_H_MODE_CARE_FREE, GUIDANCE_H_MODE_FLIP, GUIDANCE_H_MODE_FORWARD, GUIDANCE_H_MODE_HOVER, GUIDANCE_H_MODE_MODULE, GUIDANCE_H_MODE_NAV, GUIDANCE_H_MODE_RATE, GUIDANCE_H_MODE_RC_DIRECT, guidance_h_module_read_rc(), HorizontalGuidanceSetpoint::mask, HorizontalGuidance::mode, radio_control, RC_OK, HorizontalGuidance::rc_sp, read_rc_setpoint_speed_i(), HorizontalGuidance::sp, HorizontalGuidanceSetpoint::speed, stabilization_attitude_read_rc(), stabilization_attitude_read_rc_setpoint_eulers_f(), stabilization_none_read_rc(), stabilization_rate_read_rc(), stabilization_rate_read_rc_switched_sticks(), RadioControl::status, and TRUE.
Referenced by autopilot_static_on_rc_frame(), and ins_ekf2_publish_attitude().
void guidance_h_run (bool in_flight)
Definition at line 361 of file guidance_h.c.
References guidance_flip_run(), guidance_h, guidance_h_from_nav(), guidance_h_guided_run(), GUIDANCE_H_MODE_ATTITUDE, GUIDANCE_H_MODE_CARE_FREE, GUIDANCE_H_MODE_FLIP, GUIDANCE_H_MODE_FORWARD, GUIDANCE_H_MODE_GUIDED, GUIDANCE_H_MODE_HOVER, GUIDANCE_H_MODE_MODULE, GUIDANCE_H_MODE_NAV, GUIDANCE_H_MODE_RATE, GUIDANCE_H_MODE_RC_DIRECT, guidance_h_module_run(), HorizontalGuidanceSetpoint::heading, INT32_PERCENTAGE_FRAC, HorizontalGuidance::mode, FloatEulers::psi, HorizontalGuidance::rc_sp, HorizontalGuidance::sp, stabilization_attitude_run(), stabilization_filter_commands(), stabilization_none_run(), stabilization_rate_run(), and transition_run().
Referenced by autopilot_static_periodic().
bool guidance_h_set_guided_body_vel (float vx, float vy)
Set body relative horizontal velocity setpoint in GUIDED mode.
Parameters
vx forward velocity (body frame) in meters/sec.
vy right velocity (body frame) in meters/sec.
Returns
TRUE if setpoints were set (currently in GUIDANCE_H_MODE_GUIDED)
Definition at line 731 of file guidance_h.c.
References guidance_h_set_guided_vel(), FloatEulers::psi, Int32Eulers::psi, and stateGetNedToBodyEulers_f().
Referenced by autopilot_guided_update(), and orange_avoider_guided_periodic().
bool guidance_h_set_guided_heading (float heading)
Set heading setpoint in GUIDED mode.
Parameters
heading Setpoint in radians.
Returns
TRUE if setpoint was set (currently in GUIDANCE_H_MODE_GUIDED)
Definition at line 720 of file guidance_h.c.
References FLOAT_ANGLE_NORMALIZE, guidance_h, GUIDANCE_H_MODE_GUIDED, HorizontalGuidanceSetpoint::heading, heading, HorizontalGuidanceSetpoint::mask, HorizontalGuidance::mode, and HorizontalGuidance::sp.
Referenced by autopilot_guided_goto_ned(), autopilot_guided_move_ned(), autopilot_guided_update(), orange_avoider_guided_periodic(), and wedgebug_periodic().
bool guidance_h_set_guided_heading_rate (float rate)
Set heading rate setpoint in GUIDED mode.
Parameters
rate Heading rate in radians.
Returns
TRUE if setpoints were set (currently in GUIDANCE_H_MODE_GUIDED)
Definition at line 750 of file guidance_h.c.
References guidance_h, GUIDANCE_H_MODE_GUIDED, HorizontalGuidanceSetpoint::heading_rate, HorizontalGuidanceSetpoint::mask, HorizontalGuidance::mode, and HorizontalGuidance::sp.
Referenced by autopilot_guided_update(), and orange_avoider_guided_periodic().
bool guidance_h_set_guided_pos (float x, float y)
Set horizontal position setpoint in GUIDED mode.
Parameters
x North position (local NED frame) in meters.
y East position (local NED frame) in meters.
Returns
TRUE if setpoints were set (currently in GUIDANCE_H_MODE_GUIDED)
Definition at line 709 of file guidance_h.c.
References guidance_h, GUIDANCE_H_MODE_GUIDED, HorizontalGuidanceSetpoint::mask, HorizontalGuidance::mode, HorizontalGuidanceSetpoint::pos, POS_BFP_OF_REAL, HorizontalGuidance::sp, Int32Vect2::x, and Int32Vect2::y.
Referenced by autopilot_guided_goto_ned(), autopilot_guided_update(), and wedgebug_periodic().
bool guidance_h_set_guided_vel (float vx, float vy)
Set horizontal velocity setpoint in GUIDED mode.
Parameters
vx North velocity (local NED frame) in meters/sec.
vy East velocity (local NED frame) in meters/sec.
Returns
TRUE if setpoints were set (currently in GUIDANCE_H_MODE_GUIDED)
Definition at line 739 of file guidance_h.c.
References guidance_h, GUIDANCE_H_MODE_GUIDED, HorizontalGuidanceSetpoint::mask, HorizontalGuidance::mode, HorizontalGuidance::sp, HorizontalGuidanceSetpoint::speed, SPEED_BFP_OF_REAL, Int32Vect2::x, and Int32Vect2::y.
Referenced by autopilot_guided_move_ned(), autopilot_guided_update(), and guidance_h_set_guided_body_vel().
void guidance_h_set_igain (uint32_t igain)
Definition at line 681 of file guidance_h.c.
References HorizontalGuidance::gains, guidance_h, guidance_h_trim_att_integrator, HorizontalGuidanceGains::i, and INT_VECT2_ZERO.
static void guidance_h_SetMaxSpeed (float speed) inline static
Definition at line 177 of file guidance_h.h.
References gh_set_max_speed().
static void guidance_h_SetOmega (float omega) inline static
Definition at line 182 of file guidance_h.h.
References gh_set_omega().
static void guidance_h_SetTau (float tau) inline static
Definition at line 192 of file guidance_h.h.
References gh_set_tau().
static void guidance_h_SetZeta (float zeta) inline static
Definition at line 187 of file guidance_h.h.
References gh_set_zeta().
Variable Documentation
struct HorizontalGuidance guidance_h
Definition at line 90 of file guidance_h.c.
Referenced by gps_sim_hitl_event(), guidance_h_from_nav(), guidance_h_guided_run(), guidance_h_hover_enter(), guidance_h_init(), guidance_h_mode_changed(), guidance_h_nav_enter(), guidance_h_read_rc(), guidance_h_run(), guidance_h_set_guided_heading(), guidance_h_set_guided_heading_rate(), guidance_h_set_guided_pos(), guidance_h_set_guided_vel(), guidance_h_set_igain(), guidance_h_traj_run(), guidance_h_update_reference(), guidance_hybrid_position_to_airspeed(), guidance_indi_run(), ins_ekf2_publish_attitude(), orange_avoider_guided_periodic(), reset_guidance_reference_from_current_position(), send_fp(), send_gh(), send_hover_loop(), send_href(), send_status(), and stabilization_indi_rate_run().
int32_t transition_percentage
Definition at line 92 of file guidance_h.c.
Referenced by ctrl_eff_scheduling_periodic_a(), and guidance_indi_run().