Paparazzi UAS: sw/airborne/firmwares/rotorcraft/autopilot_rc_helpers.h File Reference
autopilot_rc_helpers.h File Reference
Some helper functions to check RC sticks.
#include "generated/airframe.h"
#include "modules/radio_control/radio_control.h"
#include "generated/modules.h"
Macros
#define AUTOPILOT_THROTTLE_THRESHOLD (MAX_PPRZ / 20)
#define AUTOPILOT_YAW_THRESHOLD (MAX_PPRZ * 19 / 20)
#define AUTOPILOT_STICK_CENTER_THRESHOLD (MAX_PPRZ * 1 / 20)
#define THROTTLE_STICK_DOWN() (radio_control.values[RADIO_THROTTLE] < AUTOPILOT_THROTTLE_THRESHOLD)
#define YAW_STICK_PUSHED()
#define YAW_STICK_CENTERED()
#define PITCH_STICK_CENTERED()
#define ROLL_STICK_CENTERED()
#define THROTTLE_STICK_DOWN_FROM_RC(_rc) (_rc->values[RADIO_THROTTLE] < AUTOPILOT_THROTTLE_THRESHOLD)
Functions
static bool rc_mode_switch (uint8_t chan, uint8_t pos, uint8_t max)
RC mode switch position helper switch positions threshold are evenly spaced.
static bool rc_attitude_sticks_centered (void)
Convenience macro for 3way switch.
static bool kill_switch_is_on (void)
static uint8_t percent_from_rc (int channel)
Detailed Description
Some helper functions to check RC sticks.
Definition in file autopilot_rc_helpers.h.
Macro Definition Documentation
AUTOPILOT_STICK_CENTER_THRESHOLD
#define AUTOPILOT_STICK_CENTER_THRESHOLD (MAX_PPRZ * 1 / 20)
Definition at line 38 of file autopilot_rc_helpers.h.
AUTOPILOT_THROTTLE_THRESHOLD
#define AUTOPILOT_THROTTLE_THRESHOLD (MAX_PPRZ / 20)
Definition at line 35 of file autopilot_rc_helpers.h.
AUTOPILOT_YAW_THRESHOLD
#define AUTOPILOT_YAW_THRESHOLD (MAX_PPRZ * 19 / 20)
Definition at line 36 of file autopilot_rc_helpers.h.
PITCH_STICK_CENTERED
#define PITCH_STICK_CENTERED ()
Value:
  (radio_control.values[RADIO_PITCH] < AUTOPILOT_STICK_CENTER_THRESHOLD && \
   radio_control.values[RADIO_PITCH] > -AUTOPILOT_STICK_CENTER_THRESHOLD)
Definition at line 49 of file autopilot_rc_helpers.h.
ROLL_STICK_CENTERED
#define ROLL_STICK_CENTERED ()
Value:
  (radio_control.values[RADIO_ROLL] < AUTOPILOT_STICK_CENTER_THRESHOLD && \
   radio_control.values[RADIO_ROLL] > -AUTOPILOT_STICK_CENTER_THRESHOLD)
Definition at line 52 of file autopilot_rc_helpers.h.
THROTTLE_STICK_DOWN
#define THROTTLE_STICK_DOWN () (radio_control.values[RADIO_THROTTLE] < AUTOPILOT_THROTTLE_THRESHOLD)
Definition at line 41 of file autopilot_rc_helpers.h.
THROTTLE_STICK_DOWN_FROM_RC
#define THROTTLE_STICK_DOWN_FROM_RC (_rc) (_rc->values[RADIO_THROTTLE] < AUTOPILOT_THROTTLE_THRESHOLD)
Definition at line 57 of file autopilot_rc_helpers.h.
YAW_STICK_CENTERED
#define YAW_STICK_CENTERED ()
Value:
  (radio_control.values[RADIO_YAW] < AUTOPILOT_STICK_CENTER_THRESHOLD && \
   radio_control.values[RADIO_YAW] > -AUTOPILOT_STICK_CENTER_THRESHOLD)
Definition at line 46 of file autopilot_rc_helpers.h.
YAW_STICK_PUSHED
#define YAW_STICK_PUSHED ()
Value:
  (radio_control.values[RADIO_YAW] > AUTOPILOT_YAW_THRESHOLD ||  \
   radio_control.values[RADIO_YAW] < -AUTOPILOT_YAW_THRESHOLD)
Definition at line 43 of file autopilot_rc_helpers.h.
Function Documentation
kill_switch_is_on()
static bool kill_switch_is_on (void) inline static
Definition at line 108 of file autopilot_rc_helpers.h.
Referenced by autopilot_arming_check_motors_on(), autopilot_arming_check_motors_on(), autopilot_arming_set(), and autopilot_static_on_rc_frame().
percent_from_rc()
static uint8_t percent_from_rc (int channel) inline static
Definition at line 114 of file autopilot_rc_helpers.h.
References foo, MAX_PPRZ, radio_control, and RadioControl::values.
rc_attitude_sticks_centered()
static bool rc_attitude_sticks_centered (void) inline static
Convenience macro for 3way switch.
Definition at line 93 of file autopilot_rc_helpers.h.
References PITCH_STICK_CENTERED, ROLL_STICK_CENTERED, and YAW_STICK_CENTERED.
Referenced by autopilot_arming_check_motors_on().
rc_mode_switch()
static bool rc_mode_switch (uint8_t chan, uint8_t pos, uint8_t max) inline static
RC mode switch position helper switch positions threshold are evenly spaced.
Parameters
[in] chan RC mode channel number
[in] pos switch position to be tested
[in] max maximum number of position of the switch
Returns
true if current position is the same as requested (and RC status is OK)
Definition at line 68 of file autopilot_rc_helpers.h.
References foo, MAX_PPRZ, MIN_PPRZ, p, radio_control, RC_OK, RadioControl::status, and RadioControl::values.