Paparazzi UAS: sw/airborne/firmwares/rotorcraft/autopilot_firmware.c File Reference
autopilot_firmware.c File Reference
#include "firmwares/rotorcraft/autopilot_firmware.h"
#include "generated/modules.h"
#include <stdint.h>
#include "modules/energy/electrical.h"
#include "modules/datalink/telemetry.h"
#include "modules/radio_control/radio_control.h"
#include "modules/gps/gps.h"
#include "modules/nav/nav_geofence.h"
Macros
#define AUTOPILOT_IN_FLIGHT_TIME 20
time steps for in_flight detection (at 20Hz, so 20=1second)
#define AUTOPILOT_IN_FLIGHT_MIN_SPEED 0.2
minimum vertical speed for in_flight condition in m/s
#define AUTOPILOT_IN_FLIGHT_MIN_ACCEL 2.0
minimum vertical acceleration for in_flight condition in m/s^2
#define AUTOPILOT_IN_FLIGHT_MIN_THRUST 500
minimum thrust for in_flight condition in pprz_t units (max = 9600)
#define THRESHOLD_GROUND_DETECT 25.0
Z-acceleration threshold to detect ground in m/s^2.
Functions
bool WEAK autopilot_ground_detection (void)
Default ground-detection estimation based on accelerometer shock.
bool WEAK autopilot_in_flight_end_detection (bool motors_on UNUSED)
Default end-of-in-flight detection estimation based on thrust and speed.
static void send_status (struct transport_tx *trans, struct link_device *dev)
static void send_energy (struct transport_tx *trans, struct link_device *dev)
static void send_fp (struct transport_tx *trans, struct link_device *dev)
static void send_body_rates_accel (struct transport_tx *trans, struct link_device *dev)
static void send_fp_min (struct transport_tx *trans, struct link_device *dev)
static void send_rotorcraft_rc (struct transport_tx *trans, struct link_device *dev)
static void send_rotorcraft_cmd (struct transport_tx *trans UNUSED, struct link_device *dev UNUSED)
void autopilot_firmware_init (void)
Init function.
void autopilot_send_mode (void)
Report autopilot mode on default downlink channel.
void autopilot_event (void)
autopilot event function
void autopilot_reset_in_flight_counter (void)
reset in_flight counter
void autopilot_check_in_flight (bool motors_on)
in flight check utility function
Variables
uint8_t autopilot_mode_auto2
static uint32_t autopilot_in_flight_counter
Macro Definition Documentation
AUTOPILOT_IN_FLIGHT_MIN_ACCEL
#define AUTOPILOT_IN_FLIGHT_MIN_ACCEL 2.0
minimum vertical acceleration for in_flight condition in m/s^2
Definition at line 67 of file autopilot_firmware.c.
AUTOPILOT_IN_FLIGHT_MIN_SPEED
#define AUTOPILOT_IN_FLIGHT_MIN_SPEED 0.2
minimum vertical speed for in_flight condition in m/s
Definition at line 62 of file autopilot_firmware.c.
AUTOPILOT_IN_FLIGHT_MIN_THRUST
#define AUTOPILOT_IN_FLIGHT_MIN_THRUST 500
minimum thrust for in_flight condition in pprz_t units (max = 9600)
Definition at line 72 of file autopilot_firmware.c.
AUTOPILOT_IN_FLIGHT_TIME
#define AUTOPILOT_IN_FLIGHT_TIME 20
time steps for in_flight detection (at 20Hz, so 20=1second)
Definition at line 57 of file autopilot_firmware.c.
THRESHOLD_GROUND_DETECT
#define THRESHOLD_GROUND_DETECT 25.0
Z-acceleration threshold to detect ground in m/s^2.
Definition at line 77 of file autopilot_firmware.c.
Function Documentation
autopilot_check_in_flight()
void autopilot_check_in_flight (bool motors_on)
in flight check utility function
Check if airframe is in flight.
Definition at line 295 of file autopilot_firmware.c.
References autopilot, autopilot_in_flight_counter, autopilot_in_flight_end_detection(), AUTOPILOT_IN_FLIGHT_MIN_THRUST, AUTOPILOT_IN_FLIGHT_TIME, Stabilization::cmd, foo, pprz_autopilot::in_flight, and stabilization.
autopilot_event()
void autopilot_event (void)
autopilot event function
Autopilot event check function.
used for automatic ground detection
Definition at line 272 of file autopilot_firmware.c.
References AP_MODE_FAILSAFE, autopilot, autopilot_ground_detection(), pprz_autopilot::detect_ground_once, foo, pprz_autopilot::ground_detected, and pprz_autopilot::mode.
autopilot_firmware_init()
void autopilot_firmware_init (void)
Init function.
Definition at line 242 of file autopilot_firmware.c.
References autopilot_in_flight_counter, autopilot_mode_auto2, DefaultPeriodic, foo, MODE_AUTO2, register_periodic_telemetry(), send_body_rates_accel(), send_energy(), send_fp(), send_fp_min(), send_rotorcraft_cmd(), send_rotorcraft_rc(), and send_status().
autopilot_ground_detection()
bool WEAK autopilot_ground_detection (void)
Default ground-detection estimation based on accelerometer shock.
Definition at line 81 of file autopilot_firmware.c.
References stateGetAccelNed_f(), THRESHOLD_GROUND_DETECT, and NedCoor_f::z.
Referenced by autopilot_event().
autopilot_in_flight_end_detection()
bool WEAK autopilot_in_flight_end_detection (bool motors_on UNUSED)
Default end-of-in-flight detection estimation based on thrust and speed.
Definition at line 92 of file autopilot_firmware.c.
References autopilot_in_flight_counter, AUTOPILOT_IN_FLIGHT_MIN_ACCEL, AUTOPILOT_IN_FLIGHT_MIN_SPEED, AUTOPILOT_IN_FLIGHT_MIN_THRUST, AUTOPILOT_IN_FLIGHT_TIME, Stabilization::cmd, foo, stabilization, stateGetAccelNed_f(), stateGetSpeedNed_f(), and NedCoor_f::z.
Referenced by autopilot_check_in_flight().
autopilot_reset_in_flight_counter()
void autopilot_reset_in_flight_counter (void)
reset in_flight counter
reset in_flight counter actual implementation is firmware dependent
Definition at line 288 of file autopilot_firmware.c.
References autopilot_in_flight_counter.
autopilot_send_mode()
void autopilot_send_mode (void)
Report autopilot mode on default downlink channel.
Report autopilot mode on default downlink channel.
Definition at line 261 of file autopilot_firmware.c.
References DefaultChannel, DefaultDevice, and send_status().
send_body_rates_accel()
static void send_body_rates_accel (struct transport_tx * trans, struct link_device * dev) static
Definition at line 183 of file autopilot_firmware.c.
References dev, foo, p, stateGetAccelBody_i(), and stateGetBodyRates_f().
Referenced by autopilot_firmware_init().
send_energy()
static void send_energy (struct transport_tx * trans, struct link_device * dev) static
Definition at line 138 of file autopilot_firmware.c.
References autopilot, Electrical::avg_cnt, Electrical::avg_power, Electrical::charge, Electrical::current, dev, electrical, Electrical::energy, foo, MAX_PPRZ, pprz_autopilot::throttle, and Electrical::vsupply.
send_fp()
static void send_fp (struct transport_tx * trans, struct link_device * dev) static
Definition at line 151 of file autopilot_firmware.c.
References ANGLE_BFP_OF_REAL, autopilot, dev, EULERS_BFP_OF_REAL, eulers_zxy, pprz_autopilot::flight_time, float_eulers_of_quat_zxy(), foo, guidance_h, guidance_v, HorizontalGuidanceSetpoint::heading, Int32Eulers::phi, HorizontalGuidanceSetpoint::pos, Int32Eulers::psi, HorizontalGuidance::sp, stateGetNedToBodyEulers_i(), stateGetNedToBodyQuat_f(), stateGetPositionEnu_i(), stateGetSpeedEnu_i(), Int32Eulers::theta, pprz_autopilot::throttle, Int32Vect2::x, EnuCoor_i::x, Int32Vect2::y, EnuCoor_i::y, EnuCoor_i::z, and VerticalGuidance::z_sp.
Referenced by autopilot_firmware_init().
send_fp_min()
static void send_fp_min (struct transport_tx * trans, struct link_device * dev) static
Definition at line 194 of file autopilot_firmware.c.
References dev, foo, gps, GpsState::gspeed, stateGetHorizontalSpeedNorm_f(), and stateGetPositionEnu_i().
Referenced by autopilot_firmware_init().
send_rotorcraft_cmd()
static void send_rotorcraft_cmd (struct transport_tx *trans UNUSED, struct link_device *dev UNUSED) static
Definition at line 238 of file autopilot_firmware.c.
Referenced by autopilot_firmware_init().
send_rotorcraft_rc()
static void send_rotorcraft_rc (struct transport_tx * trans, struct link_device * dev) static
Definition at line 210 of file autopilot_firmware.c.
References dev, foo, radio_control, RADIO_KILL_SWITCH, RADIO_MODE, RADIO_PITCH, RADIO_ROLL, RADIO_THROTTLE, RADIO_YAW, RadioControl::status, and RadioControl::values.
Referenced by autopilot_firmware_init().
send_status()
static void send_status (struct transport_tx * trans, struct link_device * dev) static
Definition at line 114 of file autopilot_firmware.c.
References pprz_autopilot::arming_status, autopilot, dev, electrical, GpsState::fix, foo, RadioControl::frame_rate, gps, guidance_h, guidance_v, pprz_autopilot::in_flight, pprz_autopilot::mode, HorizontalGuidance::mode, VerticalGuidance::mode, motor_mixing, pprz_autopilot::motors_on, MotorMixing::nb_failure, MotorMixing::nb_saturation, sys_time::nb_sec, radio_control, RadioControl::status, Electrical::vboard, and Electrical::vsupply.
Referenced by autopilot_firmware_init(), and autopilot_send_mode().
Variable Documentation
autopilot_in_flight_counter
uint32_t autopilot_in_flight_counter static
Definition at line 50 of file autopilot_firmware.c.
Referenced by autopilot_check_in_flight(), autopilot_firmware_init(), autopilot_in_flight_end_detection(), and autopilot_reset_in_flight_counter().
autopilot_mode_auto2
uint8_t autopilot_mode_auto2
Definition at line 49 of file autopilot_firmware.c.
Referenced by autopilot_firmware_init(), and guidance_flip_run().