Paparazzi UAS: sw/airborne/firmwares/rotorcraft/autopilot_firmware.h File Reference
autopilot_firmware.h File Reference
Rotorcraft specific autopilot interface and initialization.
#include "std.h"
#include "autopilot.h"
Functions
bool autopilot_ground_detection (void)
Default ground-detection estimation based on accelerometer shock.
bool autopilot_in_flight_end_detection (bool motors_on)
Default end-of-in-flight detection estimation based on thrust and speed.
void autopilot_firmware_init (void)
Init function.
Variables
uint8_t autopilot_mode_auto2
Detailed Description
Rotorcraft specific autopilot interface and initialization.
Definition in file autopilot_firmware.h.
Function Documentation
autopilot_firmware_init()
void autopilot_firmware_init (void) extern
Init function.
Definition at line 157 of file autopilot_firmware.c.
autopilot_ground_detection()
bool autopilot_ground_detection (void) extern
Default ground-detection estimation based on accelerometer shock.
Definition at line 81 of file autopilot_firmware.c.
References stateGetAccelNed_f(), THRESHOLD_GROUND_DETECT, and NedCoor_f::z.
Referenced by autopilot_event().
autopilot_in_flight_end_detection()
bool autopilot_in_flight_end_detection (bool motors_on) extern
Default end-of-in-flight detection estimation based on thrust and speed.
Definition at line 92 of file autopilot_firmware.c.
References autopilot_in_flight_counter, AUTOPILOT_IN_FLIGHT_MIN_ACCEL, AUTOPILOT_IN_FLIGHT_MIN_SPEED, AUTOPILOT_IN_FLIGHT_MIN_THRUST, AUTOPILOT_IN_FLIGHT_TIME, Stabilization::cmd, foo, stabilization, stateGetAccelNed_f(), stateGetSpeedNed_f(), and NedCoor_f::z.
Referenced by autopilot_check_in_flight().
Variable Documentation
autopilot_mode_auto2
uint8_t autopilot_mode_auto2 extern
Definition at line 49 of file autopilot_firmware.c.
Referenced by autopilot_firmware_init(), and guidance_flip_run().