Paparazzi UAS: sw/airborne/firmwares/rover/autopilot_generated.h File Reference
autopilot_generated.h File Reference
Autopilot generated implementation Calls the code generated from autopilot XML file.
#include "std.h"
#include "generated/autopilot_core_ap.h"
#include "generated/airframe.h"
#include "state.h"
Functions
void autopilot_generated_init (void)
void autopilot_generated_periodic (void)
void autopilot_generated_on_rc_frame (void)
void autopilot_generated_set_mode (uint8_t new_autopilot_mode)
void autopilot_generated_SetModeHandler (float new_autopilot_mode)
AP mode setting handler.
void autopilot_generated_set_motors_on (bool motors_on)
Detailed Description
Autopilot generated implementation Calls the code generated from autopilot XML file.
Definition in file autopilot_generated.h.
Function Documentation
autopilot_generated_init()
void autopilot_generated_init (void) extern
Definition at line 41 of file autopilot_generated.c.
References autopilot, autopilot_arming_init(), foo, and pprz_autopilot::mode.
Referenced by autopilot_init().
autopilot_generated_on_rc_frame()
void autopilot_generated_on_rc_frame (void) extern
Definition at line 92 of file autopilot_generated.c.
References autopilot, autopilot_arming_check_motors_on(), commands, foo, pprz_autopilot::kill_throttle, pprz_autopilot::motors_on, radio_control, radio_control_get(), RADIO_YAW, and RadioControl::values.
Referenced by autopilot_on_rc_frame().
autopilot_generated_periodic()
void autopilot_generated_periodic (void) extern
Definition at line 50 of file autopilot_generated.c.
References autopilot, autopilot_in_flight(), pprz_autopilot::detect_ground_once, foo, pprz_autopilot::ground_detected, and pprz_autopilot::mode.
Referenced by autopilot_periodic().
autopilot_generated_set_mode()
void autopilot_generated_set_mode (uint8_t new_autopilot_mode) extern
Definition at line 77 of file autopilot_generated.c.
References autopilot, FALSE, foo, and pprz_autopilot::mode.
Referenced by autopilot_generated_SetModeHandler(), and autopilot_set_mode().
autopilot_generated_set_motors_on()
void autopilot_generated_set_motors_on (bool motors_on) extern
Definition at line 85 of file autopilot_generated.c.
References AP_MODE_KILL, autopilot, autopilot_arming_set(), foo, pprz_autopilot::mode, and pprz_autopilot::motors_on.
Referenced by autopilot_force_motors_on().
autopilot_generated_SetModeHandler()
void autopilot_generated_SetModeHandler (float mode) extern
AP mode setting handler.
FIXME generated something else for this?
Definition at line 71 of file autopilot_generated.c.
References autopilot_generated_set_mode(), and mode.
Referenced by autopilot_SetModeHandler().