Paparazzi UAS: sw/airborne/firmwares/rover/guidance/rover_guidance_steering.c File Reference
rover_guidance_steering.c File Reference
#include "firmwares/rover/guidance/rover_guidance_steering.h"
#include "generated/airframe.h"
#include "generated/autopilot_core_guidance.h"
#include "autopilot.h"
#include "state.h"
#include "filters/pid.h"
Macros
#define AUTOPILOT_CORE_GUIDANCE_C
#define ROVER_GUIDANCE_POS_KP 1.f
Mandatory dependencies header.
#define ROVER_GUIDANCE_HEADING_KP 1.f
#define ROVER_GUIDANCE_SPEED_KP 10.f
#define ROVER_GUIDANCE_SPEED_KI 100.f
#define ROVER_GUIDANCE_MAX_POS_ERR 10.f
#define ROVER_GUIDANCE_MAX_SPEED 10.f
#define ROVER_GUIDANCE_PROXIMITY_DISTANCE 2.f
Functions
void rover_guidance_steering_init (void)
INIT function.
void rover_guidance_steering_periodic (void)
void rover_guidance_steering_heading_ctrl (float omega)
CTRL functions.
void rover_guidance_steering_speed_ctrl (void)
void rover_guidance_steering_setpoints (struct EnuCoor_f pos_sp, float *heading_sp)
void rover_guidance_steering_pid_reset (void)
PID RESET function.
void rover_guidance_steering_kill (void)
void rover_guidance_steering_set_speed_pgain (float pgain)
void rover_guidance_steering_set_speed_igain (float igain)
Variables
rover_ctrl guidance_control
static struct PID_f rover_pid
static float time_step
Macro Definition Documentation
AUTOPILOT_CORE_GUIDANCE_C
#define AUTOPILOT_CORE_GUIDANCE_C
Definition at line 23 of file rover_guidance_steering.c.
ROVER_GUIDANCE_HEADING_KP
#define ROVER_GUIDANCE_HEADING_KP 1.f
Definition at line 41 of file rover_guidance_steering.c.
ROVER_GUIDANCE_MAX_POS_ERR
#define ROVER_GUIDANCE_MAX_POS_ERR 10.f
Definition at line 53 of file rover_guidance_steering.c.
ROVER_GUIDANCE_MAX_SPEED
#define ROVER_GUIDANCE_MAX_SPEED 10.f
Definition at line 57 of file rover_guidance_steering.c.
ROVER_GUIDANCE_POS_KP
#define ROVER_GUIDANCE_POS_KP 1.f
Mandatory dependencies header.
Definition at line 37 of file rover_guidance_steering.c.
ROVER_GUIDANCE_PROXIMITY_DISTANCE
#define ROVER_GUIDANCE_PROXIMITY_DISTANCE 2.f
Definition at line 61 of file rover_guidance_steering.c.
ROVER_GUIDANCE_SPEED_KI
#define ROVER_GUIDANCE_SPEED_KI 100.f
Definition at line 49 of file rover_guidance_steering.c.
ROVER_GUIDANCE_SPEED_KP
#define ROVER_GUIDANCE_SPEED_KP 10.f
Definition at line 45 of file rover_guidance_steering.c.
Function Documentation
rover_guidance_steering_heading_ctrl()
void rover_guidance_steering_heading_ctrl (float omega)
CTRL functions.
Definition at line 98 of file rover_guidance_steering.c.
References BoundDelta, BoundSpeed, rover_ctrl::cmd, sr_cmd_t::delta, DRIVE_SHAFT_DISTANCE, foo, guidance_control, and stateGetHorizontalSpeedNorm_f().
rover_guidance_steering_init()
void rover_guidance_steering_init (void)
INIT function.
Steering rover guidance EXT FUNCTIONS.
Definition at line 71 of file rover_guidance_steering.c.
References rover_ctrl::cmd, sr_cmd_t::delta, foo, guidance_control, rover_ctrl::heading_kp, init_pid_f(), rover_ctrl::kf, rover_ctrl::ki, rover_ctrl::kp, MAX_PPRZ, rover_ctrl::pos_kp, ROVER_GUIDANCE_HEADING_KP, ROVER_GUIDANCE_POS_KP, ROVER_GUIDANCE_SPEED_KI, ROVER_GUIDANCE_SPEED_KP, rover_pid, sr_cmd_t::speed, rover_ctrl::speed_error, SR_MEASURED_KF, rover_ctrl::throttle, and time_step.
rover_guidance_steering_kill()
void rover_guidance_steering_kill (void)
Definition at line 156 of file rover_guidance_steering.c.
References rover_ctrl::cmd, sr_cmd_t::delta, guidance_control, and sr_cmd_t::speed.
rover_guidance_steering_periodic()
void rover_guidance_steering_periodic (void)
Definition at line 90 of file rover_guidance_steering.c.
References foo.
rover_guidance_steering_pid_reset()
void rover_guidance_steering_pid_reset (void)
PID RESET function.
Definition at line 151 of file rover_guidance_steering.c.
References reset_pid_f(), and rover_pid.
rover_guidance_steering_set_speed_igain()
void rover_guidance_steering_set_speed_igain (float igain)
Definition at line 168 of file rover_guidance_steering.c.
References guidance_control, rover_ctrl::ki, rover_ctrl::kp, rover_pid, set_gains_pid_f(), and PID_f::sum.
rover_guidance_steering_set_speed_pgain()
void rover_guidance_steering_set_speed_pgain (float pgain)
Definition at line 162 of file rover_guidance_steering.c.
References guidance_control, rover_ctrl::ki, rover_ctrl::kp, rover_pid, and set_gains_pid_f().
rover_guidance_steering_setpoints()
void rover_guidance_steering_setpoints (struct EnuCoor_f pos_sp, float * heading_sp)
Definition at line 118 of file rover_guidance_steering.c.
References rover_ctrl::cmd, float_vect2_norm(), foo, guidance_control, rover_ctrl::heading_kp, rover_ctrl::heading_sp, rover_ctrl::omega_sp, rover_ctrl::pos_kp, FloatEulers::psi, ROVER_GUIDANCE_MAX_POS_ERR, ROVER_GUIDANCE_MAX_SPEED, ROVER_GUIDANCE_PROXIMITY_DISTANCE, sr_cmd_t::speed, stateGetNedToBodyEulers_f(), stateGetPositionEnu_f(), VECT2_COPY, and VECT2_DIFF.
rover_guidance_steering_speed_ctrl()
void rover_guidance_steering_speed_ctrl (void)
Definition at line 109 of file rover_guidance_steering.c.
References BoundThrottle, rover_ctrl::cmd, get_pid_f(), guidance_control, rover_ctrl::kf, rover_pid, sr_cmd_t::speed, rover_ctrl::speed_error, stateGetHorizontalSpeedNorm_f(), rover_ctrl::throttle, time_step, and update_pid_f().
Variable Documentation
guidance_control
rover_ctrl guidance_control
Definition at line 65 of file rover_guidance_steering.c.
Referenced by rover_guidance_steering_heading_ctrl(), rover_guidance_steering_init(), rover_guidance_steering_kill(), rover_guidance_steering_set_speed_igain(), rover_guidance_steering_set_speed_pgain(), rover_guidance_steering_setpoints(), and rover_guidance_steering_speed_ctrl().
rover_pid
struct PID_f rover_pid static
Definition at line 67 of file rover_guidance_steering.c.
Referenced by rover_guidance_steering_init(), rover_guidance_steering_pid_reset(), rover_guidance_steering_set_speed_igain(), rover_guidance_steering_set_speed_pgain(), and rover_guidance_steering_speed_ctrl().
time_step
float time_step static
Definition at line 68 of file rover_guidance_steering.c.
Referenced by rover_guidance_steering_init(), and rover_guidance_steering_speed_ctrl().