Paparazzi UAS: sw/airborne/firmwares/rover/autopilot_firmware.h File Reference
autopilot_firmware.h File Reference
Rover specific autopilot interface and initialization.
#include "std.h"
#include "autopilot.h"
Functions
void autopilot_firmware_init (void)
Init function.
Detailed Description
Rover specific autopilot interface and initialization.
Definition in file autopilot_firmware.h.
Function Documentation
void autopilot_firmware_init (void)
Init function.
Definition at line 114 of file autopilot_firmware.c.
References ap_electrical, autopilot_in_flight_counter, autopilot_mode_auto2, Electrical::bat_critical, Electrical::bat_low, Electrical::charge, Electrical::current, DefaultPeriodic, Electrical::energy, MODE_AUTO2, register_periodic_telemetry(), send_airspeed(), send_desired(), send_energy(), send_estimator(), send_fp(), send_fp_min(), send_mode(), send_rotorcraft_cmd(), send_rotorcraft_rc(), send_status(), and Electrical::vsupply.
Referenced by autopilot_init().