Paparazzi UAS: sw/airborne/firmwares/rover/autopilot_generated.c File Reference
autopilot_generated.c File Reference
Generated autopilot implementation.
#include "firmwares/rotorcraft/autopilot_generated.h"
#include "autopilot.h"
#include "subsystems/radio_control.h"
#include "subsystems/commands.h"
#include "subsystems/actuators.h"
#include "subsystems/settings.h"
#include "subsystems/datalink/telemetry.h"
#include "generated/settings.h"
Macros
#define AUTOPILOT_CORE_AP_C
Functions
void autopilot_generated_init (void)
void autopilot_generated_periodic (void)
void autopilot_generated_SetModeHandler (float mode)
AP mode setting handler.
void autopilot_generated_set_mode (uint8_t new_autopilot_mode)
void autopilot_generated_set_motors_on (bool motors_on)
void autopilot_generated_on_rc_frame (void)
Detailed Description
Generated autopilot implementation.
Definition in file autopilot_generated.c.
Macro Definition Documentation
#define AUTOPILOT_CORE_AP_C
Definition at line 27 of file autopilot_generated.c.
Function Documentation
void autopilot_generated_init (void)
Definition at line 41 of file autopilot_generated.c.
References autopilot, and pprz_autopilot::mode.
void autopilot_generated_on_rc_frame (void)
Definition at line 99 of file autopilot_generated.c.
References ap_electrical, and copy_from_to_fbw().
void autopilot_generated_periodic (void)
Definition at line 50 of file autopilot_generated.c.
References autopilot, autopilot_in_flight(), pprz_autopilot::detect_ground_once, pprz_autopilot::ground_detected, inter_mcu_received_ap, link_mcu_send(), and pprz_autopilot::mode.
void autopilot_generated_set_mode (uint8_t new_autopilot_mode)
Definition at line 77 of file autopilot_generated.c.
References autopilot, and pprz_autopilot::mode.
void autopilot_generated_set_motors_on (bool motors_on)
Definition at line 85 of file autopilot_generated.c.
References ap_ahrs_is_aligned(), AP_MODE_KILL, autopilot, pprz_autopilot::mode, and pprz_autopilot::motors_on.
void autopilot_generated_SetModeHandler (float mode)
AP mode setting handler.
FIXME generated something else for this?
Definition at line 71 of file autopilot_generated.c.
References autopilot_generated_set_mode().