Paparazzi UAS: sw/airborne/firmwares/rover/guidance/rover_guidance_steering.h File Reference
rover_guidance_steering.h File Reference
#include "std.h"
#include <math.h>
#include "math/pprz_geodetic_float.h"
#include "generated/airframe.h"
Data Structures
struct sr_cmd_t
Steering rover guidance STRUCTURES.
struct rover_ctrl
Macros
#define MAX_DELTA 15.0
Generated airframe.h from airframe.xml.
#define MIN_DELTA MAX_DELTA
#define MAX_CMD_SHUT 0
#define MIN_CMD_SHUT 0
#define MAX_SPEED 999.0
#define MIN_SPEED 0.2
#define DRIVE_SHAFT_DISTANCE 0.25
#define SR_MEASURED_KF 10
#define BoundDelta(delta)
MACROS.
#define BoundSpeed(speed)
#define BoundThrottle(throttle) TRIM_PPRZ((int)throttle)
#define GetCmdFromDelta(delta)
#define GetCmdFromThrottle(throttle) (autopilot_throttle_killed() ? 0 : TRIM_PPRZ((int)throttle))
#define SetAPThrottleFromCommands(void)
Functions
void rover_guidance_steering_init (void)
Steering rover guidance EXT FUNCTIONS.
void rover_guidance_steering_periodic (void)
void rover_guidance_steering_heading_ctrl (float omega)
CTRL functions.
void rover_guidance_steering_speed_ctrl (void)
void rover_guidance_steering_setpoints (struct EnuCoor_f pos_sp, float *heading_sp)
void rover_guidance_steering_pid_reset (void)
PID RESET function.
void rover_guidance_steering_kill (void)
void rover_guidance_steering_set_speed_pgain (float pgain)
void rover_guidance_steering_set_speed_igain (float igain)
Variables
rover_ctrl guidance_control
Data Structure Documentation
sr_cmd_t
struct sr_cmd_t
Steering rover guidance STRUCTURES.
Definition at line 102 of file rover_guidance_steering.h.
Data Fields
float delta
float speed
rover_ctrl
struct rover_ctrl
Definition at line 108 of file rover_guidance_steering.h.
Data Fields
sr_cmd_t cmd
float heading_kp
float heading_sp heading setpoint
float kf
float ki
float kp
float omega_sp omega setpoint
float pos_kp
float speed_error
float throttle
Macro Definition Documentation
BoundDelta
#define BoundDelta (delta)
Value:
                          (delta < -MIN_DELTA ? -MIN_DELTA : \
                          (delta >  MAX_DELTA ?  MAX_DELTA : \
                           delta))
MACROS.
Definition at line 138 of file rover_guidance_steering.h.
BoundSpeed
#define BoundSpeed (speed)
Value:
                          (speed <  MIN_SPEED ? MIN_SPEED : \
                          (speed >  MAX_SPEED ? MAX_SPEED : \
                           speed))
Definition at line 143 of file rover_guidance_steering.h.
BoundThrottle
#define BoundThrottle (throttle) TRIM_PPRZ((int)throttle)
Definition at line 148 of file rover_guidance_steering.h.
DRIVE_SHAFT_DISTANCE
#define DRIVE_SHAFT_DISTANCE 0.25
Definition at line 89 of file rover_guidance_steering.h.
GetCmdFromDelta
#define GetCmdFromDelta (delta)
Value:
                                             (delta >= 0 ? delta/MAX_DELTA * (MAX_PPRZ - (int)MAX_CMD_SHUT) : \
                                             delta/MIN_DELTA * (MAX_PPRZ - (int)MIN_CMD_SHUT))
Definition at line 151 of file rover_guidance_steering.h.
GetCmdFromThrottle
#define GetCmdFromThrottle (throttle) (autopilot_throttle_killed() ? 0 : TRIM_PPRZ((int)throttle))
Definition at line 155 of file rover_guidance_steering.h.
MAX_CMD_SHUT
#define MAX_CMD_SHUT 0
Definition at line 73 of file rover_guidance_steering.h.
MAX_DELTA
#define MAX_DELTA 15.0
Generated airframe.h from airframe.xml.
fun: SetActuatorsFromCommands
var: commands
var: hardware and construction parameters Global variables definitions
Definition at line 62 of file rover_guidance_steering.h.
MAX_SPEED
#define MAX_SPEED 999.0
Definition at line 81 of file rover_guidance_steering.h.
MIN_CMD_SHUT
#define MIN_CMD_SHUT 0
Definition at line 76 of file rover_guidance_steering.h.
MIN_DELTA
#define MIN_DELTA MAX_DELTA
Definition at line 65 of file rover_guidance_steering.h.
MIN_SPEED
#define MIN_SPEED 0.2
Definition at line 84 of file rover_guidance_steering.h.
SetAPThrottleFromCommands
#define SetAPThrottleFromCommands (void)
Value:
    { \
    autopilot.throttle = commands[COMMAND_THROTTLE]; \
  }
Definition at line 158 of file rover_guidance_steering.h.
SR_MEASURED_KF
#define SR_MEASURED_KF 10
Definition at line 95 of file rover_guidance_steering.h.
Function Documentation
rover_guidance_steering_heading_ctrl()
void rover_guidance_steering_heading_ctrl (float omega) extern
CTRL functions.
Definition at line 98 of file rover_guidance_steering.c.
References BoundDelta, BoundSpeed, rover_ctrl::cmd, sr_cmd_t::delta, DRIVE_SHAFT_DISTANCE, foo, guidance_control, and stateGetHorizontalSpeedNorm_f().
rover_guidance_steering_init()
void rover_guidance_steering_init (void) extern
Steering rover guidance EXT FUNCTIONS.
Steering rover guidance EXT FUNCTIONS.
Definition at line 71 of file rover_guidance_steering.c.
References rover_ctrl::cmd, sr_cmd_t::delta, foo, guidance_control, rover_ctrl::heading_kp, init_pid_f(), rover_ctrl::kf, rover_ctrl::ki, rover_ctrl::kp, MAX_PPRZ, rover_ctrl::pos_kp, ROVER_GUIDANCE_HEADING_KP, ROVER_GUIDANCE_POS_KP, ROVER_GUIDANCE_SPEED_KI, ROVER_GUIDANCE_SPEED_KP, rover_pid, sr_cmd_t::speed, rover_ctrl::speed_error, SR_MEASURED_KF, rover_ctrl::throttle, and time_step.
rover_guidance_steering_kill()
void rover_guidance_steering_kill (void) extern
Definition at line 156 of file rover_guidance_steering.c.
References rover_ctrl::cmd, sr_cmd_t::delta, guidance_control, and sr_cmd_t::speed.
rover_guidance_steering_periodic()
void rover_guidance_steering_periodic (void) extern
Definition at line 90 of file rover_guidance_steering.c.
References foo.
rover_guidance_steering_pid_reset()
void rover_guidance_steering_pid_reset (void) extern
PID RESET function.
Definition at line 151 of file rover_guidance_steering.c.
References reset_pid_f(), and rover_pid.
rover_guidance_steering_set_speed_igain()
void rover_guidance_steering_set_speed_igain (float igain) extern
Definition at line 168 of file rover_guidance_steering.c.
References guidance_control, rover_ctrl::ki, rover_ctrl::kp, rover_pid, set_gains_pid_f(), and PID_f::sum.
rover_guidance_steering_set_speed_pgain()
void rover_guidance_steering_set_speed_pgain (float pgain) extern
Definition at line 162 of file rover_guidance_steering.c.
References guidance_control, rover_ctrl::ki, rover_ctrl::kp, rover_pid, and set_gains_pid_f().
rover_guidance_steering_setpoints()
void rover_guidance_steering_setpoints (struct EnuCoor_f pos_sp, float * heading_sp) extern
Definition at line 118 of file rover_guidance_steering.c.
References rover_ctrl::cmd, float_vect2_norm(), foo, guidance_control, rover_ctrl::heading_kp, rover_ctrl::heading_sp, rover_ctrl::omega_sp, rover_ctrl::pos_kp, FloatEulers::psi, ROVER_GUIDANCE_MAX_POS_ERR, ROVER_GUIDANCE_MAX_SPEED, ROVER_GUIDANCE_PROXIMITY_DISTANCE, sr_cmd_t::speed, stateGetNedToBodyEulers_f(), stateGetPositionEnu_f(), VECT2_COPY, and VECT2_DIFF.
rover_guidance_steering_speed_ctrl()
void rover_guidance_steering_speed_ctrl (void) extern
Definition at line 109 of file rover_guidance_steering.c.
References BoundThrottle, rover_ctrl::cmd, get_pid_f(), guidance_control, rover_ctrl::kf, rover_pid, sr_cmd_t::speed, rover_ctrl::speed_error, stateGetHorizontalSpeedNorm_f(), rover_ctrl::throttle, time_step, and update_pid_f().
Variable Documentation
guidance_control
rover_ctrl guidance_control extern
Definition at line 65 of file rover_guidance_steering.c.
Referenced by rover_guidance_steering_heading_ctrl(), rover_guidance_steering_init(), rover_guidance_steering_kill(), rover_guidance_steering_set_speed_igain(), rover_guidance_steering_set_speed_pgain(), rover_guidance_steering_setpoints(), and rover_guidance_steering_speed_ctrl().