Paparazzi UAS: sw/airborne/modules/sensors/rpm_sensor.c File Reference
rpm_sensor.c File Reference
#include "modules/sensors/rpm_sensor.h"
#include "mcu_periph/pwm_input.h"
#include "modules/energy/electrical.h"
#include "modules/core/abi.h"
#include "filters/low_pass_filter.h"
#include "modules/datalink/telemetry.h"
Macros
#define RPM_FILTER_TAU RPM_SENSOR_PERIODIC_PERIOD
Functions
static void rpm_sensor_send_motor (struct transport_tx *trans, struct link_device *dev)
void rpm_sensor_init (void)
void rpm_sensor_periodic (void)
uint16_t rpm_sensor_get_rpm (void)
Variables
static struct FirstOrderLowPass rpm_lp
uint16_t rpm
Detailed Description
Author
Freek van Tienen freek.nosp@m..v.t.nosp@m.ienen.nosp@m.@gma.nosp@m.il.co.nosp@m.m RPM sensor based on time difference between pulses
Definition in file rpm_sensor.c.
Macro Definition Documentation
RPM_FILTER_TAU
#define RPM_FILTER_TAU RPM_SENSOR_PERIODIC_PERIOD
Definition at line 36 of file rpm_sensor.c.
Function Documentation
rpm_sensor_get_rpm()
uint16_t rpm_sensor_get_rpm (void)
Definition at line 75 of file rpm_sensor.c.
References foo, get_pwm_input_period_in_usec(), and RPM_PULSE_PER_RND.
Referenced by rpm_sensor_periodic(), and stabilization_attitude_run().
rpm_sensor_init()
void rpm_sensor_init (void)
Definition at line 54 of file rpm_sensor.c.
References DefaultPeriodic, foo, init_first_order_low_pass(), register_periodic_telemetry(), rpm, RPM_FILTER_TAU, rpm_lp, and rpm_sensor_send_motor().
rpm_sensor_periodic()
void rpm_sensor_periodic (void)
Definition at line 65 of file rpm_sensor.c.
References ACT_FEEDBACK_RPM_SENSOR_ID, foo, act_feedback_t::idx, act_feedback_t::act_feedback_set_t::rpm, act_feedback_t::rpm, rpm_lp, rpm_sensor_get_rpm(), act_feedback_t::set, and update_first_order_low_pass().
rpm_sensor_send_motor()
static void rpm_sensor_send_motor (struct transport_tx * trans, struct link_device * dev) static
Definition at line 47 of file rpm_sensor.c.
References Electrical::current, dev, electrical, foo, and rpm.
Referenced by rpm_sensor_init().
Variable Documentation
rpm
uint16_t rpm
Definition at line 33 of file rpm_sensor.c.
Referenced by actuators_dshot_arch_commit(), actuators_uavcan_send_esc(), DshotErpsSetFromRpm(), esc_msg_send(), rpm_sensor_init(), and rpm_sensor_send_motor().
rpm_lp
struct FirstOrderLowPass rpm_lp static
Definition at line 32 of file rpm_sensor.c.
Referenced by rpm_sensor_init(), and rpm_sensor_periodic().