Paparazzi UAS: sw/airborne/modules/sensors/rpm_sensor.h File Reference
rpm_sensor.h File Reference
#include "std.h"
Macros
#define RPM_PULSE_PER_RND 14
Functions
void rpm_sensor_init (void)
void rpm_sensor_periodic (void)
uint16_t rpm_sensor_get_rpm (void)
Detailed Description
Author
Freek van Tienen freek.nosp@m..v.t.nosp@m.ienen.nosp@m.@gma.nosp@m.il.co.nosp@m.m RPM sensor based on time difference between pulses
Definition in file rpm_sensor.h.
Macro Definition Documentation
RPM_PULSE_PER_RND
#define RPM_PULSE_PER_RND 14
Definition at line 33 of file rpm_sensor.h.
Function Documentation
rpm_sensor_get_rpm()
uint16_t rpm_sensor_get_rpm (void) extern
Definition at line 75 of file rpm_sensor.c.
References foo, get_pwm_input_period_in_usec(), and RPM_PULSE_PER_RND.
Referenced by rpm_sensor_periodic(), and stabilization_attitude_run().
rpm_sensor_init()
void rpm_sensor_init (void) extern
Definition at line 54 of file rpm_sensor.c.
References DefaultPeriodic, foo, init_first_order_low_pass(), register_periodic_telemetry(), rpm, RPM_FILTER_TAU, rpm_lp, and rpm_sensor_send_motor().
rpm_sensor_periodic()
void rpm_sensor_periodic (void) extern
Definition at line 65 of file rpm_sensor.c.
References ACT_FEEDBACK_RPM_SENSOR_ID, foo, act_feedback_t::idx, act_feedback_t::act_feedback_set_t::rpm, act_feedback_t::rpm, rpm_lp, rpm_sensor_get_rpm(), act_feedback_t::set, and update_first_order_low_pass().