Paparazzi UAS: sw/airborne/modules/multi/rssi.h File Reference
rssi.h File Reference
#include <inttypes.h>
Data Structures
struct rssi_info_
Functions
void rssi_init (void)
void set_rssi (uint8_t _ac_id, int8_t _rssi, int8_t _tx_strength)
struct rssi_info_ get_rssi (uint8_t _ac_id)
void parse_rssi_dl (uint8_t *buf)
Variables
uint8_t rssi_acs_idx
uint8_t rssi_acs_id []
struct rssi_info_ rssi_acs []
Detailed Description
Author
Kirk Scheper stores received rssi values for communication protocols that support it
Definition in file rssi.h.
Data Structure Documentation
rssi_info_
struct rssi_info_
Definition at line 31 of file rssi.h.
Data Fields
uint8_t ac_id
int8_t rssi
int8_t tx_strength
Function Documentation
get_rssi()
struct rssi_info_ get_rssi (uint8_t _ac_id) extern
Definition at line 90 of file rssi.c.
References foo, rssi_acs, and rssi_acs_id.
parse_rssi_dl()
void parse_rssi_dl (uint8_t * buf) extern
Definition at line 65 of file rssi.c.
References foo, and set_rssi().
rssi_init()
void rssi_init (void) extern
Definition at line 52 of file rssi.c.
References ABI_BROADCAST, rssi_info_::ac_id, ev, foo, NB_ACS_ID, rssi_acs, rssi_acs_id, rssi_acs_idx, and rssi_cb().
set_rssi()
void set_rssi (uint8_t _ac_id, int8_t _rssi, int8_t _tx_strength) extern
Definition at line 77 of file rssi.c.
References rssi_info_::ac_id, foo, NB_ACS, rssi_info_::rssi, rssi_acs, rssi_acs_id, rssi_acs_idx, and rssi_info_::tx_strength.
Referenced by parse_rssi_dl(), and rssi_cb().
Variable Documentation
rssi_acs
struct rssi_info_ rssi_acs[] extern
Definition at line 42 of file rssi.c.
Referenced by get_rssi(), rssi_init(), and set_rssi().
rssi_acs_id
uint8_t rssi_acs_id[] extern
Definition at line 43 of file rssi.c.
Referenced by get_rssi(), rssi_init(), and set_rssi().
rssi_acs_idx
uint8_t rssi_acs_idx extern
Definition at line 41 of file rssi.c.
Referenced by rssi_init(), and set_rssi().