Paparazzi UAS: sw/airborne/modules/multi/rssi.c File Reference
rssi.c File Reference
#include "modules/multi/rssi.h"
#include "modules/datalink/datalink.h"
#include "pprzlink/messages.h"
#include "modules/core/abi.h"
#include "generated/airframe.h"
Macros
#define NB_ACS_ID 256
#define NB_ACS 24
Functions
static void rssi_cb (uint8_t sender_id, uint8_t _ac_id, int8_t _tx_strength, int8_t _rssi)
void rssi_init ()
void parse_rssi_dl (uint8_t *buf)
void set_rssi (uint8_t _ac_id, int8_t _tx_strength, int8_t _rssi)
struct rssi_info_ get_rssi (uint8_t _ac_id)
Variables
uint8_t rssi_acs_idx
struct rssi_info_ rssi_acs [NB_ACS]
uint8_t rssi_acs_id [NB_ACS_ID]
abi_event ev
Detailed Description
Author
Kirk Scheper stores received rssi values for communication protocols that support it
Definition in file rssi.c.
Macro Definition Documentation
NB_ACS
#define NB_ACS 24
Definition at line 38 of file rssi.c.
NB_ACS_ID
#define NB_ACS_ID 256
Definition at line 35 of file rssi.c.
Function Documentation
get_rssi()
struct rssi_info_ get_rssi (uint8_t _ac_id)
Definition at line 90 of file rssi.c.
References foo, rssi_acs, and rssi_acs_id.
parse_rssi_dl()
void parse_rssi_dl (uint8_t * buf)
Definition at line 65 of file rssi.c.
References foo, and set_rssi().
rssi_cb()
static void rssi_cb (uint8_t sender_id, uint8_t _ac_id, int8_t _tx_strength, int8_t _rssi) static
Definition at line 47 of file rssi.c.
References foo, and set_rssi().
Referenced by rssi_init().
rssi_init()
void rssi_init (void)
Definition at line 52 of file rssi.c.
References ABI_BROADCAST, rssi_info_::ac_id, ev, foo, NB_ACS_ID, rssi_acs, rssi_acs_id, rssi_acs_idx, and rssi_cb().
set_rssi()
void set_rssi (uint8_t _ac_id, int8_t _tx_strength, int8_t _rssi)
Definition at line 77 of file rssi.c.
References rssi_info_::ac_id, foo, NB_ACS, rssi_info_::rssi, rssi_acs, rssi_acs_id, rssi_acs_idx, and rssi_info_::tx_strength.
Referenced by parse_rssi_dl(), and rssi_cb().
Variable Documentation
ev
abi_event ev
Definition at line 45 of file rssi.c.
Referenced by onTransferReceived(), rssi_init(), shouldAcceptTransfer(), and uavcan_bind().
rssi_acs
struct rssi_info_ rssi_acs[NB_ACS]
Definition at line 42 of file rssi.c.
Referenced by get_rssi(), rssi_init(), and set_rssi().
rssi_acs_id
uint8_t rssi_acs_id[NB_ACS_ID]
Definition at line 43 of file rssi.c.
Referenced by get_rssi(), rssi_init(), and set_rssi().
rssi_acs_idx
uint8_t rssi_acs_idx
Definition at line 41 of file rssi.c.
Referenced by rssi_init(), and set_rssi().