Paparazzi UAS: sw/airborne/arch/linux/rt_priority.h File Reference
rt_priority.h File Reference
Functions to obtain rt priority or set the nice level.
#include <pthread.h>
#include <stdio.h>
#include <sys/resource.h>
#include <unistd.h>
#include <sys/syscall.h>
Functions
static int get_rt_prio (int prio)
static int set_nice_level (int level)
Detailed Description
Functions to obtain rt priority or set the nice level.
Definition in file rt_priority.h.
Function Documentation
get_rt_prio()
static int get_rt_prio (int prio) inline static
Definition at line 32 of file rt_priority.h.
References foo.
Referenced by i2c_thread(), pipe_thread(), sys_time_thread_main(), uart_thread(), and udp_thread().
set_nice_level()
static int set_nice_level (int level) inline static
Definition at line 69 of file rt_priority.h.
References foo.
Referenced by cv_async_thread(), and video_thread_function().