Paparazzi UAS: sw/airborne/modules/core/rtos_mon.c File Reference
rtos_mon.c File Reference
#include "modules/core/sys_mon.h"
#include "modules/core/sys_mon_rtos.h"
#include "modules/datalink/downlink.h"
Functions
void init_sysmon (void)
Init system monitoring.
void periodic_report_sysmon (void)
Report system status.
void periodic_sysmon (void)
Analyse periodic calls Should be run at the highest frequency.
void event_sysmon (void)
Analyse event calls.
Variables
struct rtos_monitoring rtos_mon
Detailed Description
Author
Gautier Hattenberger RTOS monitoring tool
Definition in file rtos_mon.c.
Function Documentation
event_sysmon()
void event_sysmon (void)
Analyse event calls.
Definition at line 65 of file rtos_mon.c.
init_sysmon()
void init_sysmon (void)
Init system monitoring.
Definition at line 32 of file rtos_mon.c.
References foo, rtos_mon, and rtos_mon_init_arch().
periodic_report_sysmon()
void periodic_report_sysmon (void)
Report system status.
Definition at line 43 of file rtos_mon.c.
References rtos_monitoring::core_free_memory, rtos_monitoring::cpu_load, rtos_monitoring::cpu_time, DefaultChannel, DefaultDevice, foo, get_sys_time_float(), rtos_monitoring::heap_fragments, rtos_monitoring::heap_free_memory, rtos_monitoring::heap_largest, rtos_mon, rtos_mon_periodic_arch(), and rtos_monitoring::thread_counter.
periodic_sysmon()
void periodic_sysmon (void)
Analyse periodic calls Should be run at the highest frequency.
Definition at line 63 of file rtos_mon.c.
Variable Documentation
rtos_mon
struct rtos_monitoring rtos_mon
Definition at line 30 of file rtos_mon.c.
Referenced by init_sysmon(), periodic_report_sysmon(), and rtos_mon_periodic_arch().