Paparazzi UAS: sw/airborne/modules/radio_control/sbus_dual.h File Reference
sbus_dual.h File Reference
Radio control via two SBUS receivers.
#include "modules/radio_control/sbus_common.h"
Functions
void sbus_dual_init (void)
RC init function.
void sbus_dual_event (void)
RC event function.
Variables
struct Sbus sbus1 sbus2
SBUS struct.
Detailed Description
Radio control via two SBUS receivers.
Definition in file sbus_dual.h.
Function Documentation
sbus_dual_event()
void sbus_dual_event (void) extern
RC event function.
Definition at line 82 of file sbus_dual.c.
References foo, Sbus::frame_available, RadioControl::frame_cpt, Sbus::pulses, radio_control, RADIO_CONTROL_SBUS_DUAL_ID, RadioControl::radio_ok_cpt, RC_OK, sbus2, sbus_dual_decode_event(), RadioControl::status, and RadioControl::time_since_last_frame.
sbus_dual_init()
void sbus_dual_init (void) extern
RC init function.
Definition at line 64 of file sbus_dual.c.
References DefaultPeriodic, foo, RadioControl::nb_channel, radio_control, RC2_POLARITY_GPIO_PIN, RC2_POLARITY_GPIO_PORT, RC_POLARITY_GPIO_PIN, RC_POLARITY_GPIO_PORT, register_periodic_telemetry(), sbus2, sbus_common_init(), SBUS_NB_CHANNEL, and send_sbus().
Variable Documentation
sbus2
struct Sbus sbus1 sbus2 extern
SBUS struct.
Definition at line 49 of file sbus_dual.c.
Referenced by sbus_dual_decode_event(), sbus_dual_event(), and sbus_dual_init().