Paparazzi UAS: sw/airborne/subsystems/radio_control/sbus.c File Reference
sbus.c File Reference
Single SBUS radio_control.
#include "subsystems/radio_control.h"
#include "subsystems/radio_control/sbus.h"
#include <BOARD_CONFIG>
#include "subsystems/datalink/telemetry.h"
Macros
#define RC_POLARITY_GPIO_PORT 0
#define RC_POLARITY_GPIO_PIN 0
Functions
static void send_sbus (struct transport_tx *trans, struct link_device *dev)
void radio_control_impl_init (void)
static void sbus_decode_event (void)
void radio_control_impl_event (void(*_received_frame_handler)(void))
RC event function with handler callback.
Variables
struct Sbus sbus
SBUS struct.
Detailed Description
Single SBUS radio_control.
Definition in file sbus.c.
Macro Definition Documentation
#define RC_POLARITY_GPIO_PIN 0
Definition at line 35 of file sbus.c.
Referenced by radio_control_impl_init().
#define RC_POLARITY_GPIO_PORT 0
Definition at line 32 of file sbus.c.
Referenced by radio_control_impl_init().
Function Documentation
void radio_control_impl_event (void(*)(void) _received_frame_handler)
RC event function with handler callback.
PPM frames are normalized using the IIR filter.
Definition at line 72 of file sbus.c.
References Sbus::frame_available, RadioControl::frame_cpt, Sbus::pulses, radio_control, RadioControl::radio_ok_cpt, Sbus::rc_lost, RC_OK, RC_REALLY_LOST, sbus, sbus_decode_event(), RadioControl::status, and RadioControl::time_since_last_frame.
void radio_control_impl_init (void)
Definition at line 54 of file sbus.c.
References DefaultPeriodic, RC_POLARITY_GPIO_PIN, RC_POLARITY_GPIO_PORT, register_periodic_telemetry(), sbus, sbus_common_init(), and send_sbus().
static void sbus_decode_event (void) inline static
Definition at line 67 of file sbus.c.
References sbus, and sbus_common_decode_event().
Referenced by radio_control_impl_event().
static void send_sbus (struct transport_tx * trans, struct link_device * dev) static
Definition at line 45 of file sbus.c.
References RadioControl::frame_rate, Sbus::ppm, radio_control, sbus, and SBUS_NB_CHANNEL.
Referenced by radio_control_impl_init().
Variable Documentation
struct Sbus sbus
SBUS struct.
Definition at line 39 of file sbus.c.
Referenced by radio_control_impl_event(), radio_control_impl_init(), sbus_decode_event(), and send_sbus().