Paparazzi UAS: sw/airborne/modules/radio_control/sbus.h File Reference
sbus.h File Reference
Radio control via single SBUS receiver.
#include "modules/radio_control/sbus_common.h"
Functions
void sbus_init (void)
RC init function.
void sbus_event (void)
RC event function.
Variables
struct Sbus sbus
SBUS struct.
Detailed Description
Radio control via single SBUS receiver.
Definition in file sbus.h.
Function Documentation
sbus_event()
void sbus_event (void) extern
RC event function.
Definition at line 74 of file sbus.c.
References foo, Sbus::frame_available, RadioControl::frame_cpt, Sbus::pulses, radio_control, RADIO_CONTROL_SBUS_ID, RadioControl::radio_ok_cpt, Sbus::rc_failsafe, Sbus::rc_lost, RC_OK, RC_REALLY_LOST, sbus, sbus_decode_event(), RadioControl::status, and RadioControl::time_since_last_frame.
sbus_init()
void sbus_init (void) extern
RC init function.
Definition at line 55 of file sbus.c.
References DefaultPeriodic, foo, RadioControl::nb_channel, radio_control, RC_POLARITY_GPIO_PIN, RC_POLARITY_GPIO_PORT, register_periodic_telemetry(), sbus, sbus_common_init(), SBUS_NB_CHANNEL, and send_sbus().
Variable Documentation
sbus
struct Sbus sbus extern
SBUS struct.
Definition at line 40 of file sbus.c.
Referenced by sbus_decode_event(), sbus_event(), sbus_init(), and send_sbus().