Paparazzi UAS: sw/airborne/arch/stm32/peripherals/sc18is600_arch.c File Reference
sc18is600_arch.c File Reference
#include "peripherals/sc18is600.h"
#include <stm32/rcc.h>
#include <stm32/spi.h>
#include <stm32/exti.h>
#include <stm32/misc.h>
#include <stm32/dma.h>
#include <stm32/gpio.h>
Macros
#define Sc18Is600_Cmd_Write 0x00
#define Sc18Is600_Cmd_Read 0x01
#define Sc18Is600_Cmd_Read_After_Write 0x02
#define Sc18Is600_Cmd_Write_After_Write 0x03
#define Sc18Is600_Cmd_Read_Buffer 0x06
#define Sc18Is600_Cmd_Write_To_Reg 0x20
#define Sc18Is600_Cmd_Read_From_Reg 0x21
#define Sc18Is600_Cmd_Power_Down 0x30
#define ReadI2CStatReg()
Functions
void exti2_irq_handler (void)
void dma1_c4_irq_handler (void)
static void sc18is600_setup_SPI_DMA (uint8_t _len)
void sc18is600_arch_init (void)
void sc18is600_transmit (uint8_t addr, uint8_t len)
void sc18is600_receive (uint8_t addr, uint8_t len)
void sc18is600_tranceive (uint8_t addr, uint8_t len_tx, uint8_t len_rx)
void sc18is600_write_to_register (uint8_t addr, uint8_t value)
void sc18is600_read_from_register (uint8_t addr)
Macro Definition Documentation
ReadI2CStatReg
#define ReadI2CStatReg ()
Value:
    {        \
    sc18is600.priv_tx_buf[0] = Sc18Is600_Cmd_Read_From_Reg; \
    sc18is600.priv_tx_buf[1] = Sc18Is600_I2CStat; \
    sc18is600.priv_tx_buf[2] = 0;     \
    Sc18Is600Select();          \
    sc18is600_setup_SPI_DMA(3);       \
  }
Definition at line 206 of file sc18is600_arch.c.
Sc18Is600_Cmd_Power_Down
#define Sc18Is600_Cmd_Power_Down 0x30
Definition at line 18 of file sc18is600_arch.c.
Sc18Is600_Cmd_Read
#define Sc18Is600_Cmd_Read 0x01
Definition at line 12 of file sc18is600_arch.c.
Sc18Is600_Cmd_Read_After_Write
#define Sc18Is600_Cmd_Read_After_Write 0x02
Definition at line 13 of file sc18is600_arch.c.
Sc18Is600_Cmd_Read_Buffer
#define Sc18Is600_Cmd_Read_Buffer 0x06
Definition at line 15 of file sc18is600_arch.c.
Sc18Is600_Cmd_Read_From_Reg
#define Sc18Is600_Cmd_Read_From_Reg 0x21
Definition at line 17 of file sc18is600_arch.c.
Sc18Is600_Cmd_Write
#define Sc18Is600_Cmd_Write 0x00
Definition at line 11 of file sc18is600_arch.c.
Sc18Is600_Cmd_Write_After_Write
#define Sc18Is600_Cmd_Write_After_Write 0x03
Definition at line 14 of file sc18is600_arch.c.
Sc18Is600_Cmd_Write_To_Reg
#define Sc18Is600_Cmd_Write_To_Reg 0x20
Definition at line 16 of file sc18is600_arch.c.
Function Documentation
dma1_c4_irq_handler()
void dma1_c4_irq_handler (void) extern
Definition at line 242 of file sc18is600_arch.c.
References foo, Sc18Is600::i2c_status, Sc18Is600::priv_rx_buf, Sc18Is600::priv_tx_buf, Sc18Is600::rx_len, sc18is600, Sc18Is600_Cmd_Read_Buffer, sc18is600_setup_SPI_DMA(), Sc18Is600ReadingBuffer, Sc18Is600ReadingI2CStat, Sc18Is600ReadRegister, Sc18Is600Receive, Sc18Is600Select, Sc18Is600SendingRequest, Sc18Is600TransactionComplete, Sc18Is600Transcieve, Sc18Is600Transmit, Sc18Is600Unselect, Sc18Is600WaitingForI2C, Sc18Is600WriteRegister, Sc18Is600::status, and Sc18Is600::transaction.
exti2_irq_handler()
void exti2_irq_handler (void) extern
Definition at line 215 of file sc18is600_arch.c.
References foo, ReadI2CStatReg, RESET, sc18is600, Sc18Is600ReadingI2CStat, Sc18Is600ReadRegister, Sc18Is600Receive, Sc18Is600Transcieve, Sc18Is600Transmit, Sc18Is600WaitingForI2C, Sc18Is600WriteRegister, Sc18Is600::status, and Sc18Is600::transaction.
sc18is600_arch_init()
void sc18is600_arch_init (void)
Definition at line 25 of file sc18is600_arch.c.
References foo, GPIOB, GPIOD, and Sc18Is600Unselect.
Referenced by sc18is600_init().
sc18is600_read_from_register()
void sc18is600_read_from_register (uint8_t addr)
Definition at line 195 of file sc18is600_arch.c.
References Sc18Is600::priv_tx_buf, sc18is600, Sc18Is600_Cmd_Read_From_Reg, sc18is600_setup_SPI_DMA(), Sc18Is600ReadRegister, Sc18Is600Select, Sc18Is600SendingRequest, Sc18Is600::status, and Sc18Is600::transaction.
sc18is600_receive()
void sc18is600_receive (uint8_t addr, uint8_t len)
Definition at line 164 of file sc18is600_arch.c.
sc18is600_setup_SPI_DMA()
static void sc18is600_setup_SPI_DMA (uint8_t _len) inline static
Definition at line 101 of file sc18is600_arch.c.
References foo, Sc18Is600::priv_rx_buf, Sc18Is600::priv_tx_buf, and sc18is600.
Referenced by dma1_c4_irq_handler(), sc18is600_read_from_register(), sc18is600_tranceive(), sc18is600_transmit(), and sc18is600_write_to_register().
sc18is600_tranceive()
void sc18is600_tranceive (uint8_t addr, uint8_t len_tx, uint8_t len_rx)
Definition at line 169 of file sc18is600_arch.c.
References foo, Sc18Is600::priv_tx_buf, Sc18Is600::rx_len, sc18is600, Sc18Is600_Cmd_Read_After_Write, sc18is600_setup_SPI_DMA(), Sc18Is600Select, Sc18Is600SendingRequest, Sc18Is600Transcieve, Sc18Is600::status, and Sc18Is600::transaction.
sc18is600_transmit()
void sc18is600_transmit (uint8_t addr, uint8_t len)
Definition at line 151 of file sc18is600_arch.c.
References Sc18Is600::priv_tx_buf, sc18is600, Sc18Is600_Cmd_Write, sc18is600_setup_SPI_DMA(), Sc18Is600Select, Sc18Is600SendingRequest, Sc18Is600Transmit, Sc18Is600::status, and Sc18Is600::transaction.
sc18is600_write_to_register()
void sc18is600_write_to_register (uint8_t addr, uint8_t value)
Definition at line 183 of file sc18is600_arch.c.
References Sc18Is600::priv_tx_buf, sc18is600, Sc18Is600_Cmd_Write_To_Reg, sc18is600_setup_SPI_DMA(), Sc18Is600Select, Sc18Is600SendingRequest, Sc18Is600WriteRegister, Sc18Is600::status, and Sc18Is600::transaction.