Paparazzi UAS: sw/airborne/modules/ctrl/scheduling_indi_simple.h File Reference
scheduling_indi_simple.h File Reference
#include "generated/airframe.h"
#include "firmwares/rotorcraft/stabilization/stabilization_indi_simple.h"
Functions
void ctrl_eff_scheduling_init (void)
Initialises periodic loop;.
void ctrl_eff_scheduling_periodic (void)
Periodic function that interpolates between gain sets depending on the scheduling variable.
Variables
int32_t use_scheduling
Function Documentation
ctrl_eff_scheduling_init()
void ctrl_eff_scheduling_init (void) extern
Initialises periodic loop;.
Definition at line 92 of file eff_scheduling_nederdrone.c.
References foo, g_forward, g_hover, and INDI_G_SCALING.
ctrl_eff_scheduling_periodic()
void ctrl_eff_scheduling_periodic (void) extern
Periodic function that interpolates between gain sets depending on the scheduling variable.
Definition at line 108 of file eff_scheduling_nederdrone.c.
References act_pref, foo, IndiVariables::g1, g_forward, g_hover, guidance_indi_specific_force_gain, indi, INDI_SCHEDULING_LOWER_BOUND_G1, FloatRates::p, FloatRates::q, FloatRates::r, schdule_control_effectiveness(), sched_ratio_tip_props, stateGetAirspeed_f(), stateGetNedToBodyEulers_f(), trim_elevator, trim_flaps, and use_scheduling.
Variable Documentation
use_scheduling
int32_t use_scheduling extern
Definition at line 67 of file eff_scheduling_nederdrone.c.
Referenced by ctrl_eff_scheduling_periodic(), and schdule_control_effectiveness().