Paparazzi UAS: sw/airborne/modules/loggers/sdlogger_spi_direct.h File Reference
sdlogger_spi_direct.h File Reference
#include "pprzlink/pprzlink_device.h"
#include "peripherals/sdcard_spi.h"
Data Structures
struct sdlogger_spi_periph
Macros
#define SDLOGGER_BUFFER_SIZE 128
Enumerations
enum SDLoggerStatus {
SDLogger_UnInit , SDLogger_Error , SDLogger_Initializing , SDLogger_RetreivingIndex ,
SDLogger_Ready , SDLogger_Logging , SDLogger_LoggingFinalBlock , SDLogger_StoppedLogging ,
SDLogger_GettingIndexForUpdate , SDLogger_UpdatingIndex , SDLogger_GettingIndexForDownload , SDLogger_Downloading
}
Functions
void sdlogger_spi_direct_init (void)
sdlogger_spi_direct_init Initialize the logger and SD Card.
void sdlogger_spi_direct_periodic (void)
sdlogger_spi_direct_periodic Periodic function called at module frequency
void sdlogger_spi_direct_start (void)
void sdlogger_spi_direct_stop (void)
void sdlogger_spi_direct_index_received (void)
sdlogger_spi_direct_index_received Callback from SD Card when block at index location is received.
void sdlogger_spi_direct_multiwrite_written (void)
sdlogger_spi_direct_multiwrite_written Called when a multiwrite is complete.
void sdlogger_spi_direct_command (void)
int sdlogger_spi_direct_check_free_space (struct sdlogger_spi_periph *p, long *fd, uint16_t len)
void sdlogger_spi_direct_put_byte (struct sdlogger_spi_periph *p, long fd, uint8_t data)
void sdlogger_spi_direct_put_buffer (struct sdlogger_spi_periph *p, long fd, uint8_t *data, uint16_t len)
void sdlogger_spi_direct_send_message (void *p, long fd)
int sdlogger_spi_direct_char_available (void *p)
uint8_t sdlogger_spi_direct_get_byte (void *p)
Variables
struct sdlogger_spi_periph sdlogger_spi
Detailed Description
Author
Bart Slinger SPI SD Logger that saves pprzlog messages to SD Card.
Definition in file sdlogger_spi_direct.h.
Data Structure Documentation
sdlogger_spi_periph
struct sdlogger_spi_periph
Definition at line 49 of file sdlogger_spi_direct.h.
Data Fields
uint8_t buffer[SDLOGGER_BUFFER_SIZE]
uint8_t command
struct link_device device
uint8_t do_log
uint32_t download_address
uint8_t download_id
uint32_t download_length
uint8_t idx
uint8_t last_completed
uint32_t log_len
uint32_t next_available_address
uint16_t sdcard_buf_idx
enum SDLoggerStatus status
Macro Definition Documentation
SDLOGGER_BUFFER_SIZE
#define SDLOGGER_BUFFER_SIZE 128
Definition at line 29 of file sdlogger_spi_direct.h.
Enumeration Type Documentation
SDLoggerStatus
enum SDLoggerStatus
Enumerator
SDLogger_UnInit
SDLogger_Error
SDLogger_Initializing
SDLogger_RetreivingIndex
SDLogger_Ready
SDLogger_Logging
SDLogger_LoggingFinalBlock
SDLogger_StoppedLogging
SDLogger_GettingIndexForUpdate
SDLogger_UpdatingIndex
SDLogger_GettingIndexForDownload
SDLogger_Downloading
Definition at line 34 of file sdlogger_spi_direct.h.
Function Documentation
sdlogger_spi_direct_char_available()
int sdlogger_spi_direct_char_available (void * p) extern
Definition at line 467 of file sdlogger_spi_direct.c.
References foo, and p.
Referenced by sdlogger_spi_direct_init().
sdlogger_spi_direct_check_free_space()
int sdlogger_spi_direct_check_free_space (struct sdlogger_spi_periph * p, long * fd, uint16_t len) extern
Definition at line 422 of file sdlogger_spi_direct.c.
References p, SDLOGGER_BUFFER_SIZE, and SDLogger_Logging.
Referenced by sdlogger_spi_direct_init().
sdlogger_spi_direct_command()
void sdlogger_spi_direct_command (void) extern
Definition at line 400 of file sdlogger_spi_direct.c.
References sdlogger_spi_periph::command, sdlogger_spi_periph::download_id, sdlogger_spi_periph::download_length, foo, LOGGER_LED_ON, sdcard1, sdlogger_spi_periph::sdcard_buf_idx, SDCard_Idle, sdcard_spi_read_block(), SDLogger_Downloading, SDLogger_GettingIndexForDownload, sdlogger_spi, sdlogger_spi_direct_index_received(), sdlogger_spi_periph::status, and SDCard::status.
sdlogger_spi_direct_get_byte()
uint8_t sdlogger_spi_direct_get_byte (void * p) extern
Definition at line 472 of file sdlogger_spi_direct.c.
References foo, and p.
Referenced by sdlogger_spi_direct_init().
sdlogger_spi_direct_index_received()
void sdlogger_spi_direct_index_received (void) extern
sdlogger_spi_direct_index_received Callback from SD Card when block at index location is received.
Definition at line 289 of file sdlogger_spi_direct.c.
References sdlogger_spi_periph::download_address, sdlogger_spi_periph::download_id, sdlogger_spi_periph::download_length, foo, SDCard::input_buf, sdlogger_spi_periph::last_completed, sdlogger_spi_periph::log_len, LOGGER_LED_OFF, sdlogger_spi_periph::next_available_address, SDCard::output_buf, SD_BLOCK_SIZE, sdcard1, sdlogger_spi_periph::sdcard_buf_idx, sdcard_spi_read_block(), sdcard_spi_write_block(), SDLogger_Downloading, SDLogger_GettingIndexForDownload, SDLogger_GettingIndexForUpdate, SDLogger_Ready, SDLogger_RetreivingIndex, sdlogger_spi, SDLogger_UpdatingIndex, and sdlogger_spi_periph::status.
Referenced by sdlogger_spi_direct_command(), and sdlogger_spi_direct_periodic().
sdlogger_spi_direct_init()
void sdlogger_spi_direct_init (void) extern
sdlogger_spi_direct_init Initialize the logger and SD Card.
Definition at line 120 of file sdlogger_spi_direct.c.
References sdlogger_spi_periph::buffer, sdlogger_spi_periph::command, sdlogger_spi_periph::device, sdlogger_spi_periph::do_log, sdlogger_spi_periph::download_address, sdlogger_spi_periph::download_id, sdlogger_spi_periph::download_length, foo, sdlogger_spi_periph::idx, sdlogger_spi_periph::last_completed, sdlogger_spi_periph::log_len, sdlogger_spi_periph::next_available_address, sdcard1, sdlogger_spi_periph::sdcard_buf_idx, sdcard_spi_init(), SDLogger_Initializing, sdlogger_spi, sdlogger_spi_direct_char_available(), sdlogger_spi_direct_check_free_space(), sdlogger_spi_direct_get_byte(), sdlogger_spi_direct_put_buffer(), sdlogger_spi_direct_put_byte(), sdlogger_spi_direct_send_message(), and sdlogger_spi_periph::status.
sdlogger_spi_direct_multiwrite_written()
void sdlogger_spi_direct_multiwrite_written (void) extern
sdlogger_spi_direct_multiwrite_written Called when a multiwrite is complete.
Data stored in the logger buffer is then moved to the SD Card buffer, which is now available again.
Definition at line 385 of file sdlogger_spi_direct.c.
References sdlogger_spi_periph::buffer, sdlogger_spi_periph::idx, sdlogger_spi_periph::log_len, SDCard::output_buf, sdcard1, sdlogger_spi_periph::sdcard_buf_idx, and sdlogger_spi.
Referenced by sdlogger_spi_direct_periodic(), and sdlogger_spi_direct_put_byte().
sdlogger_spi_direct_periodic()
void sdlogger_spi_direct_periodic (void) extern
sdlogger_spi_direct_periodic Periodic function called at module frequency
Definition at line 162 of file sdlogger_spi_direct.c.
References autopilot_get_motors_on(), DefaultPeriodic, sdlogger_spi_periph::device, sdlogger_spi_periph::do_log, sdlogger_spi_periph::download_address, sdlogger_spi_periph::download_length, fd, foo, SDCard::input_buf, LOGGER_LED_OFF, LOGGER_LED_ON, sdlogger_spi_periph::next_available_address, SDCard::output_buf, pprzlog_tp, SD_BLOCK_SIZE, sdcard1, sdlogger_spi_periph::sdcard_buf_idx, SDCard_Idle, SDCard_MultiWriteIdle, sdcard_spi_multiwrite_next(), sdcard_spi_multiwrite_start(), sdcard_spi_multiwrite_stop(), sdcard_spi_periodic(), sdcard_spi_read_block(), SDLogger_Downloading, SDLogger_GettingIndexForUpdate, SDLogger_Initializing, SDLogger_Logging, SDLogger_LoggingFinalBlock, SDLogger_Ready, SDLogger_RetreivingIndex, sdlogger_spi, sdlogger_spi_direct_index_received(), sdlogger_spi_direct_multiwrite_written(), SDLogger_StoppedLogging, SDLogger_UpdatingIndex, sdlogger_spi_periph::status, and SDCard::status.
sdlogger_spi_direct_put_buffer()
void sdlogger_spi_direct_put_buffer (struct sdlogger_spi_periph * p, long fd, uint8_t * data, uint16_t len) extern
Definition at line 454 of file sdlogger_spi_direct.c.
References fd, p, and sdlogger_spi_direct_put_byte().
Referenced by sdlogger_spi_direct_init().
sdlogger_spi_direct_put_byte()
void sdlogger_spi_direct_put_byte (struct sdlogger_spi_periph * p, long fd, uint8_t data) extern
Definition at line 434 of file sdlogger_spi_direct.c.
References SDCard::output_buf, p, sdcard1, SDCard_MultiWriteIdle, sdcard_spi_multiwrite_next(), SDLOGGER_BUFFER_SIZE, sdlogger_spi_direct_multiwrite_written(), and SDCard::status.
Referenced by sdlogger_spi_direct_init(), and sdlogger_spi_direct_put_buffer().
sdlogger_spi_direct_send_message()
void sdlogger_spi_direct_send_message (void * p, long fd) extern
Definition at line 462 of file sdlogger_spi_direct.c.
References foo, and p.
Referenced by sdlogger_spi_direct_init().
sdlogger_spi_direct_start()
void sdlogger_spi_direct_start (void) extern
Definition at line 282 of file sdlogger_spi_direct.c.
sdlogger_spi_direct_stop()
void sdlogger_spi_direct_stop (void) extern
Definition at line 283 of file sdlogger_spi_direct.c.
Variable Documentation
sdlogger_spi
struct sdlogger_spi_periph sdlogger_spi extern
Definition at line 114 of file sdlogger_spi_direct.c.
Referenced by sdlogger_spi_direct_command(), sdlogger_spi_direct_index_received(), sdlogger_spi_direct_init(), sdlogger_spi_direct_multiwrite_written(), and sdlogger_spi_direct_periodic().