Paparazzi UAS: sw/airborne/modules/loggers/sdlog_chibios.h File Reference
sdlog_chibios.h File Reference
#include "std.h"
#include "modules/loggers/sdlog_chibios/sdLog.h"
#include "pprzlink/pprzlink_device.h"
Data Structures
struct chibios_sdlog
chibios_sdlog structure
Macros
#define DEST_INFO_MSG_ALL 0
#define DEST_INFO_MSG_FLIGHT_RECORDER 1
#define DEST_INFO_MSG_PPRZLOG 2
Functions
void sdlog_chibios_init (void)
void sdlog_chibios_finish (bool flush)
void chibios_sdlog_init (struct chibios_sdlog *sdlog, FileDes *file)
init chibios_sdlog structure
void logger_log_msg_up (uint8_t *buf)
Variables
FileDes pprzLogFile
struct chibios_sdlog chibios_sdlog
Data Structure Documentation
chibios_sdlog
struct chibios_sdlog
chibios_sdlog structure
Definition at line 58 of file sdlog_chibios.h.
Data Fields
struct link_device device Generic device interface.
FileDes * file
Macro Definition Documentation
DEST_INFO_MSG_ALL
#define DEST_INFO_MSG_ALL 0
Definition at line 42 of file sdlog_chibios.h.
DEST_INFO_MSG_FLIGHT_RECORDER
#define DEST_INFO_MSG_FLIGHT_RECORDER 1
Definition at line 43 of file sdlog_chibios.h.
DEST_INFO_MSG_PPRZLOG
#define DEST_INFO_MSG_PPRZLOG 2
Definition at line 44 of file sdlog_chibios.h.
Function Documentation
chibios_sdlog_init()
void chibios_sdlog_init (struct chibios_sdlog * sdlog, FileDes * file) extern
init chibios_sdlog structure
Definition at line 178 of file sdlog_chibios.c.
References foo, null_byte_function(), null_function(), sdlog_check_free_space(), sdlog_send(), sdlog_transmit(), and sdlog_transmit_buffer().
Referenced by flight_recorder_init(), and thd_startlog().
logger_log_msg_up()
void logger_log_msg_up (uint8_t * buf) extern
Definition at line 382 of file sdlog_chibios.c.
References DEST_INFO_MSG_ALL, DEST_INFO_MSG_PPRZLOG, fd, foo, msg, and pprzLogFile.
sdlog_chibios_finish()
void sdlog_chibios_finish (bool flush) extern
Definition at line 213 of file sdlog_chibios.c.
References chibios_sdlog_status, foo, pprzLogFile, SDLOG_STOPPED, and sdLogFinish().
Referenced by thdUsbStorage().
sdlog_chibios_init()
void sdlog_chibios_init (void) extern
Definition at line 193 of file sdlog_chibios.c.
References chibios_sdlog_status, DefaultPeriodic, foo, preflight_check_register(), register_periodic_telemetry(), SDLOG_STOPPED, send_sdlog_status(), thd_startlog(), and usbStorageStartPolling().
Variable Documentation
chibios_sdlog
struct chibios_sdlog chibios_sdlog extern
Definition at line 83 of file sdlog_chibios.c.
pprzLogFile
FileDes pprzLogFile extern
Definition at line 81 of file sdlog_chibios.c.
Referenced by logger_log_msg_up(), sdlog_chibios_finish(), and thd_startlog().