Paparazzi UAS: sw/airborne/modules/sensors/sensors_hitl.h File Reference
sensors_hitl.h File Reference
#include "std.h"
Macros
#define PRIMARY_GPS GPS_SIM
Functions
void sensors_hitl_init (void)
void sensors_hitl_periodic (void)
void sensors_hitl_event (void)
void sensors_hitl_parse_HITL_IMU (uint8_t *buf)
void sensors_hitl_parse_HITL_GPS (uint8_t *buf)
void sensors_hitl_parse_HITL_AIR_DATA (uint8_t *buf)
void imu_feed_gyro_accel (void)
void imu_feed_mag (void)
void gps_feed_value (void)
Variables
bool gps_has_fix
Macro Definition Documentation
PRIMARY_GPS
#define PRIMARY_GPS GPS_SIM
Definition at line 27 of file sensors_hitl.h.
Function Documentation
gps_feed_value()
void gps_feed_value (void) extern
Definition at line 32 of file gps_sim_nps.c.
References LlaCoor_i::alt, GpsState::course, GpsState::ecef_pos, GpsState::ecef_vel, fdm, GpsState::fix, foo, get_sys_time_usec(), GPS_FIX_3D, GPS_FIX_NONE, gps_has_fix, gps_nps, GPS_SIM_ID, GPS_VALID_COURSE_BIT, GPS_VALID_HMSL_BIT, GPS_VALID_POS_ECEF_BIT, GPS_VALID_POS_LLA_BIT, GPS_VALID_VEL_ECEF_BIT, GPS_VALID_VEL_NED_BIT, GpsState::gspeed, GpsState::hacc, GpsState::hmsl, GpsState::last_3dfix_ticks, GpsState::last_3dfix_time, GpsState::last_msg_ticks, GpsState::last_msg_time, LlaCoor_i::lat, GpsState::lla_pos, LlaCoor_i::lon, ltp_def_from_ecef_d(), NpsFdm::ltp_to_body_eulers, sys_time::nb_sec, sys_time::nb_sec_rem, ned_of_ecef_vect_d(), GpsState::ned_vel, GpsState::num_sv, GpsState::pacc, GpsState::pdop, DoubleEulers::psi, GpsState::sacc, sensors, GpsState::speed_3d, NpsFdm::time, GpsState::tow, GpsState::vacc, GpsState::valid_fields, GpsState::week, EcefCoor_i::x, NedCoor_i::x, EcefCoor_i::y, NedCoor_i::y, EcefCoor_i::z, and NedCoor_i::z.
Referenced by nps_autopilot_run_step().
imu_feed_gyro_accel()
void imu_feed_gyro_accel (void) extern
Definition at line 50 of file imu_nps.c.
References ImuNps::accel, ImuNps::accel_available, ImuNps::gyro, ImuNps::gyro_available, imu_nps, RATES_ASSIGN, sensors, and VECT3_COPY.
Referenced by nps_autopilot_run_step().
imu_feed_mag()
void imu_feed_mag (void) extern
Definition at line 61 of file imu_nps.c.
References imu_nps, ImuNps::mag, ImuNps::mag_available, sensors, and VECT3_COPY.
Referenced by nps_autopilot_run_step().
sensors_hitl_event()
void sensors_hitl_event (void) extern
Definition at line 200 of file sensors_hitl.c.
References ImuHitl::accel, ImuHitl::accel_available, DlCheckAndParse(), foo, get_sys_time_usec(), ImuHitl::gyro, ImuHitl::gyro_available, imu_hitl, IMU_NPS_ID, ImuHitl::mag, ImuHitl::mag_available, sensors_hitl_dl_buffer, sensors_hitl_msg_available, and sensors_hitl_tp.
sensors_hitl_init()
void sensors_hitl_init (void) extern
Definition at line 52 of file sensors_hitl.c.
References ImuHitl::accel_available, ACCEL_FLOAT_OF_BFP, accel_neutral, accel_scale_f, foo, gps_has_fix, ImuHitl::gyro_available, gyro_scale_f, imu_hitl, IMU_NPS_ID, imu_set_defaults_accel(), imu_set_defaults_gyro(), imu_set_defaults_mag(), ImuHitl::mag_available, MAG_FLOAT_OF_BFP, mag_scale_f, RATE_FLOAT_OF_BFP, and sensors_hitl_tp.
sensors_hitl_parse_HITL_AIR_DATA()
void sensors_hitl_parse_HITL_AIR_DATA (uint8_t * buf) extern
Definition at line 177 of file sensors_hitl.c.
References AIRSPEED_NPS_ID, BARO_SIM_SENDER_ID, foo, get_sys_time_usec(), and INCIDENCE_NPS_ID.
sensors_hitl_parse_HITL_GPS()
void sensors_hitl_parse_HITL_GPS (uint8_t * buf) extern
Definition at line 110 of file sensors_hitl.c.
References LlaCoor_i::alt, GpsState::course, GpsState::ecef_vel, GpsState::fix, foo, get_sys_time_usec(), GPS_FIX_3D, GPS_FIX_NONE, gps_has_fix, gps_hitl, GPS_SIM_ID, GPS_VALID_COURSE_BIT, GPS_VALID_HMSL_BIT, GPS_VALID_POS_LLA_BIT, GPS_VALID_VEL_ECEF_BIT, GPS_VALID_VEL_NED_BIT, GpsState::gspeed, GpsState::hacc, GpsState::hmsl, GpsState::last_3dfix_ticks, GpsState::last_3dfix_time, GpsState::last_msg_ticks, GpsState::last_msg_time, LlaCoor_i::lat, GpsState::lla_pos, LlaCoor_i::lon, ltp_def_from_lla_i(), sys_time::nb_sec, sys_time::nb_sec_rem, ned_of_ecef_vect_i(), GpsState::ned_vel, GpsState::num_sv, GpsState::pacc, GpsState::pdop, GpsState::sacc, GpsState::speed_3d, GpsState::tow, GpsState::vacc, GpsState::valid_fields, VECT3_FLOAT_OF_CM, GpsState::week, EcefCoor_i::x, NedCoor_i::x, EcefCoor_i::y, NedCoor_i::y, EcefCoor_i::z, and NedCoor_i::z.
sensors_hitl_parse_HITL_IMU()
void sensors_hitl_parse_HITL_IMU (uint8_t * buf) extern
Definition at line 86 of file sensors_hitl.c.
References ImuHitl::accel, ImuHitl::accel_available, foo, ImuHitl::gyro, ImuHitl::gyro_available, imu_hitl, ImuHitl::mag, ImuHitl::mag_available, RATES_ASSIGN, and VECT3_ASSIGN.
sensors_hitl_periodic()
void sensors_hitl_periodic (void) extern
Definition at line 75 of file sensors_hitl.c.
References electrical, foo, and Electrical::vsupply.
Variable Documentation
gps_has_fix
bool gps_has_fix extern
Definition at line 30 of file gps_sim_nps.c.
Referenced by gps_feed_value(), gps_nps_init(), on_WORLD_ENV(), sensors_hitl_init(), and sensors_hitl_parse_HITL_GPS().