Paparazzi UAS: sw/airborne/modules/core/settings.c File Reference
settings.c File Reference
Persistent settings interface.
#include "modules/core/settings.h"
#include "generated/settings.h"
#include "generated/airframe.h"
#include "pprzlink/messages.h"
#include "pprzlink/dl_protocol.h"
Functions
void settings_init (void)
int32_t settings_store (void)
store settings marked as persistent to flash
int32_t settings_clear (void)
clear all persistent settings from flash
void settings_parse_msg_SETTING (struct link_device *dev, struct transport_tx *trans, uint8_t *buf)
void settings_parse_msg_GET_SETTING (struct link_device *dev, struct transport_tx *trans, uint8_t *buf)
Variables
struct PersistentSettings pers_settings
bool settings_store_flag
flag for setting feedback.
bool settings_clear_flag
Detailed Description
Persistent settings interface.
Definition in file settings.c.
Function Documentation
settings_clear()
int32_t settings_clear (void)
clear all persistent settings from flash
Returns
0 on success
Definition at line 80 of file settings.c.
References persistent_clear(), and settings_clear_flag.
Referenced by autopilot_clear_settings().
settings_init()
void settings_init (void)
Definition at line 46 of file settings.c.
References foo, pers_settings, and persistent_read().
Referenced by cc2500_settings_init(), and main_init().
settings_parse_msg_GET_SETTING()
void settings_parse_msg_GET_SETTING (struct link_device * dev, struct transport_tx * trans, uint8_t * buf)
Definition at line 118 of file settings.c.
References dev, foo, msg, and val.
settings_parse_msg_SETTING()
void settings_parse_msg_SETTING (struct link_device * dev, struct transport_tx * trans, uint8_t * buf)
Definition at line 95 of file settings.c.
References dev, foo, and msg.
settings_store()
int32_t settings_store (void)
store settings marked as persistent to flash
Returns
0 on success
Definition at line 60 of file settings.c.
References foo, pers_settings, persistent_write(), and settings_store_flag.
Referenced by autopilot_store_settings().
Variable Documentation
pers_settings
struct PersistentSettings pers_settings
Definition at line 34 of file settings.c.
Referenced by settings_init(), and settings_store().
settings_clear_flag
bool settings_clear_flag
Definition at line 43 of file settings.c.
Referenced by autopilot_clear_settings(), and settings_clear().
settings_store_flag
bool settings_store_flag
flag for setting feedback.
if TRUE, was stored sucessfully. Also settings still need a variable, pure function call not possible yet.
Definition at line 41 of file settings.c.
Referenced by autopilot_store_settings(), and settings_store().