Paparazzi UAS: sw/airborne/firmwares/setup/setup_actuators.c File Reference
setup_actuators.c File Reference
#include "generated/periodic_telemetry.h"
#include "generated/airframe.h"
#include "generated/settings.h"
#include "generated/modules.h"
#include "modules/datalink/datalink.h"
#include "modules/datalink/downlink.h"
#include "modules/datalink/pprz_dl.h"
#include "mcu.h"
#include "mcu_periph/sys_time.h"
#include "led.h"
#include "modules/actuators/actuators.h"
Macros
#define MODULES_C
#define PERIODIC_C_MAIN
#define IdOfMsg(x) (x[1])
Functions
static void main_init (void)
static void main_periodic (void)
static void main_event (void)
int main (void)
void dl_parse_msg (struct link_device *dev, struct transport_tx *trans, uint8_t *buf)
Should be called when chars are available in dl_buffer.
Macro Definition Documentation
IdOfMsg
#define IdOfMsg (x) (x[1])
Definition at line 116 of file setup_actuators.c.
MODULES_C
#define MODULES_C
Definition at line 25 of file setup_actuators.c.
PERIODIC_C_MAIN
#define PERIODIC_C_MAIN
Definition at line 30 of file setup_actuators.c.
Function Documentation
dl_parse_msg()
void dl_parse_msg (struct link_device * dev, struct transport_tx * trans, uint8_t * buf)
Should be called when chars are available in dl_buffer.
Definition at line 118 of file setup_actuators.c.
References DefaultChannel, DefaultDevice, foo, IdOfMsg, LED_TOGGLE, and val.
Referenced by intermcu_event().
main()
int main (void)
Definition at line 56 of file setup_actuators.c.
References main_event(), main_init(), main_periodic(), and sys_time_check_and_ack_timer().
main_event()
static void main_event (void) inline static
Definition at line 108 of file setup_actuators.c.
References foo, mcu_event(), and pprz_dl_event().
Referenced by main().
main_init()
static void main_init (void) inline static
Definition at line 70 of file setup_actuators.c.
References actuators_init(), datalink_init(), downlink_init(), foo, mcu_init(), pprz_dl_init(), and sys_time_register_timer().
Referenced by main().
main_periodic()
static void main_periodic (void) inline static
Definition at line 89 of file setup_actuators.c.
References DefaultChannel, DefaultDevice, foo, and LED_PERIODIC.
Referenced by main().