Paparazzi UAS: sw/airborne/modules/core/shell.h File Reference
shell.h File Reference
#include "modules/core/shell_arch.h"
Typedefs
typedef void() shell_cmd_t(shell_stream_t *stream, int argc, const char *const argv[])
Command handler.
Functions
void shell_init (void)
Init shell.
void shell_add_entry (char *cmd_name, shell_cmd_t *cmd)
Add new shell entry.
Detailed Description
Author
Alexandre Bustico alexa.nosp@m.ndre.nosp@m..bust.nosp@m.ico@.nosp@m.enac..nosp@m.fr Simple debug shell
Definition in file shell.h.
Typedef Documentation
shell_cmd_t
typedef void() shell_cmd_t(shell_stream_t *stream, int argc, const char *const argv[])
Command handler.
Definition at line 37 of file shell.h.
Function Documentation
shell_add_entry()
void shell_add_entry (char * cmd_name, shell_cmd_t * cmd) extern
Add new shell entry.
maximum number of entry might be limited, see specific implementations
Add new shell entry.
Definition at line 91 of file shell_arch.c.
References foo.
Referenced by imu_init(), rtos_mon_init_arch(), and sys_time_init().
shell_init()
void shell_init (void) extern
Init shell.
Definition at line 29 of file shell.c.
References shell_init_arch().