Paparazzi UAS: sw/airborne/modules/ctrl/shift_tracking.h File Reference
shift_tracking.h File Reference
#include "std.h"
Data Structures
struct shift_tracking_t
Macros
#define shift_tracking_SetKp(_v) { shift_tracking.kp = _v; shift_tracking_update_gains(); }
hndlers for gains update
#define shift_tracking_SetKd(_v) { shift_tracking.kd = _v; shift_tracking_update_gains(); }
#define shift_tracking_SetKi(_v) { shift_tracking.ki = _v; shift_tracking_update_gains(); }
Functions
void shift_tracking_init (void)
init function
void shift_tracking_run (float *shift)
run function
void shift_tracking_reset (void)
reset function
void shift_tracking_update_gains (void)
Variables
struct shift_tracking_t shift_tracking
Detailed Description
Author
Gautier Hattenberger gauti.nosp@m.er.h.nosp@m.atten.nosp@m.berg.nosp@m.er@en.nosp@m.ac.f.nosp@m.r
pilot the nav shift variable to track an offset trajectory based on the POSITION_ESTIMATE ABI message
Definition in file shift_tracking.h.
Data Structure Documentation
shift_tracking_t
struct shift_tracking_t
Definition at line 34 of file shift_tracking.h.
Data Fields
float kd derivative gain
float ki integral gain
float kp proportional gain
float shift shift command
Macro Definition Documentation
shift_tracking_SetKd
#define shift_tracking_SetKd (_v) { shift_tracking.kd = _v; shift_tracking_update_gains(); }
Definition at line 64 of file shift_tracking.h.
shift_tracking_SetKi
#define shift_tracking_SetKi (_v) { shift_tracking.ki = _v; shift_tracking_update_gains(); }
Definition at line 65 of file shift_tracking.h.
shift_tracking_SetKp
#define shift_tracking_SetKp (_v) { shift_tracking.kp = _v; shift_tracking_update_gains(); }
hndlers for gains update
Definition at line 63 of file shift_tracking.h.
Function Documentation
shift_tracking_init()
void shift_tracking_init (void) extern
init function
Definition at line 108 of file shift_tracking.c.
References shift_tracking_private::dir, dir, float_vect3_normalize(), FLOAT_VECT3_ZERO, foo, get_pos(), init_pid_f(), shift_tracking_t::kd, shift_tracking_t::ki, shift_tracking_t::kp, shift_tracking_private::pid, shift_tracking_private::pos, shift_tracking_private::pos_ev, shift_tracking_private::shift, shift_tracking_t::shift, shift_tracking, SHIFT_TRACKING_ID, SHIFT_TRACKING_KD, SHIFT_TRACKING_KI, SHIFT_TRACKING_KP, stp, FloatVect3::x, FloatVect3::y, and FloatVect3::z.
shift_tracking_reset()
void shift_tracking_reset (void) extern
reset function
reset integral and offset command
Definition at line 127 of file shift_tracking.c.
References shift_tracking_private::pid, reset_pid_f(), shift_tracking_private::shift, shift_tracking_t::shift, shift_tracking, and stp.
shift_tracking_run()
void shift_tracking_run (float * shift) extern
run function
should be called in flight plan pre_call
Parameters
[out] shift pointer to the navigation shift to control
Definition at line 136 of file shift_tracking.c.
References shift_tracking_private::dir, foo, nav_dt, shift_tracking_private::pid, shift_tracking_private::pos, shift_tracking_private::shift, shift_tracking_t::shift, shift_tracking, SHIFT_TRACKING_MAXSHIFT, stp, update_pid_f(), FloatVect3::x, and FloatVect3::y.
shift_tracking_update_gains()
void shift_tracking_update_gains (void) extern
Definition at line 163 of file shift_tracking.c.
References shift_tracking_t::kd, shift_tracking_t::ki, shift_tracking_t::kp, shift_tracking_private::pid, set_gains_pid_f(), shift_tracking, and stp.
Variable Documentation
shift_tracking
struct shift_tracking_t shift_tracking extern
Definition at line 75 of file shift_tracking.c.
Referenced by shift_tracking_init(), shift_tracking_reset(), shift_tracking_run(), and shift_tracking_update_gains().