Paparazzi UAS: sw/airborne/arch/sim/mcu_periph/sys_time_arch.c File Reference
sys_time_arch.c File Reference
Handling of sys_time in sim.
#include "mcu_periph/sys_time.h"
#include "std.h"
Functions
void sys_tick_handler (void)
void sys_time_arch_init (void)
uint32_t get_sys_time_usec (void)
Get the time in microseconds since startup.
uint32_t get_sys_time_usec100 (void)
Get the time in 100microseconds since startup.
uint32_t get_sys_time_msec (void)
Get the time in milliseconds since startup.
void sys_time_usleep (uint32_t us)
Sleep.
void sys_time_msleep (uint32_t ms)
Sleep.
Detailed Description
Handling of sys_time in sim.
Definition in file sys_time_arch.c.
Function Documentation
get_sys_time_msec()
uint32_t get_sys_time_msec (void)
Get the time in milliseconds since startup.
Returns
milliseconds since startup as uint32_t
Definition at line 52 of file sys_time_arch.c.
References msec_of_cpu_ticks(), sys_time::nb_sec, and sys_time::nb_sec_rem.
get_sys_time_usec()
uint32_t get_sys_time_usec (void)
Get the time in microseconds since startup.
WARNING: overflows after 70min!
Returns
microseconds since startup as uint32_t
WARNING: overflows after 71min34seconds!
Returns
current system time as uint32_t
Definition at line 40 of file sys_time_arch.c.
References sys_time::nb_sec, sys_time::nb_sec_rem, and usec_of_cpu_ticks().
get_sys_time_usec100()
uint32_t get_sys_time_usec100 (void)
Get the time in 100microseconds since startup.
WARNING: overflows after 7000min!
Returns
100microseconds since startup as uint32_t
Get the time in 100microseconds since startup.
WARNING: overflows after 7000min!
Returns
100microseconds since startup as uint32_t
WARNING: overflows after 7000 minutes!
Returns
current system time as uint32_t
Definition at line 46 of file sys_time_arch.c.
References sys_time::nb_sec, sys_time::nb_sec_rem, and usec_of_cpu_ticks().
sys_tick_handler()
void sys_tick_handler (void)
Definition at line 58 of file sys_time_arch.c.
References sys_time_timer::cb, sys_time::cpu_ticks_per_sec, sys_time_timer::duration, sys_time_timer::elapsed, sys_time_timer::end_time, sys_time_timer::in_use, sys_time::nb_sec, sys_time::nb_sec_rem, sys_time::nb_tick, sys_time::resolution_cpu_ticks, SYS_TIME_NB_TIMER, and sys_time::timer.
Referenced by nps_autopilot_run_systime_step().
sys_time_arch_init()
void sys_time_arch_init (void)
Definition at line 33 of file sys_time_arch.c.
References sys_time::cpu_ticks_per_sec, foo, sys_time::resolution, and sys_time::resolution_cpu_ticks.
sys_time_msleep()
void sys_time_msleep (uint32_t ms)
Sleep.
Parameters
ms milliseconds
Definition at line 80 of file sys_time_arch.c.
References foo, and sys_time_usleep().
sys_time_usleep()
void sys_time_usleep (uint32_t us)
Sleep.
Parameters
us microseconds
Sleep.
using intermediate 64 bits variable to avoid wrapping
max sleep time is around 10 days (2^32 / CH_CFG_ST_FREQUENCY) at 10kHz
Definition at line 78 of file sys_time_arch.c.