Paparazzi UAS: sw/airborne/arch/sim/mcu_periph/sys_time_arch.h File Reference
sys_time_arch.h File Reference
Simulator timing functions.
#include "std.h"
#include "mcu_periph/sys_time.h"
Functions
void sys_tick_handler (void)
static uint32_t get_sys_time_usec (void)
Get the time in microseconds since startup.
static uint32_t get_sys_time_usec100 (void)
Get the time in 100microseconds since startup.
static uint32_t get_sys_time_msec (void)
Get the time in milliseconds since startup.
Detailed Description
Simulator timing functions.
Definition in file sys_time_arch.h.
Function Documentation
get_sys_time_msec()
static uint32_t get_sys_time_msec (void) inline static
Get the time in milliseconds since startup.
Returns
milliseconds since startup as uint32_t
Definition at line 60 of file sys_time_arch.h.
References msec_of_cpu_ticks(), sys_time::nb_sec, and sys_time::nb_sec_rem.
get_sys_time_usec()
static uint32_t get_sys_time_usec (void) inline static
Get the time in microseconds since startup.
Returns
microseconds since startup as uint32_t
Definition at line 40 of file sys_time_arch.h.
References sys_time::nb_sec, sys_time::nb_sec_rem, and usec_of_cpu_ticks().
get_sys_time_usec100()
static uint32_t get_sys_time_usec100 (void) inline static
Get the time in 100microseconds since startup.
Returns
100microseconds since startup as uint32_t
Definition at line 50 of file sys_time_arch.h.
References sys_time::nb_sec, sys_time::nb_sec_rem, and usec_of_cpu_ticks().
sys_tick_handler()
void sys_tick_handler (void) extern
Definition at line 39 of file sys_time_arch.c.
References sys_time_timer::cb, sys_time::cpu_ticks_per_sec, sys_time_timer::duration, sys_time_timer::elapsed, sys_time_timer::end_time, foo, sys_time_timer::in_use, LED_TOGGLE, sys_time::nb_sec, sys_time::nb_sec_rem, sys_time::nb_tick, sys_time::resolution_cpu_ticks, SYS_TIME_NB_TIMER, and sys_time::timer.