Paparazzi UAS: sw/airborne/modules/core/slcan.h File Reference
slcan.h File Reference
#include <inttypes.h>
#include <stdbool.h>
#include "mcu_periph/can.h"
#include "core/threads.h"
Data Structures
struct slcan_t
Macros
#define SLCAN_CMD_BUF_LEN (2*64+15)
Functions
void slcan_init (void)
void slcan_event (void)
Detailed Description
Author
Fabien-B fabie.nosp@m.n-b@.nosp@m.githu.nosp@m.b.co.nosp@m.m SLCAN interface. CAN over serial link. See https://www.canusb.com/files/can232_v3.pdf Useful for using DroneCAN GUI over serial USB.
Definition in file slcan.h.
Data Structure Documentation
slcan_t
struct slcan_t
Definition at line 36 of file slcan.h.
Data Fields
struct pprzaddr_can can_if
uint8_t cmd_buf[SLCAN_CMD_BUF_LEN]
uint8_t cmd_buf_idx
struct link_device * dev
pprz_mutex_t mtx
struct pprzcan_frame rx_frame
bool send_rx
bool timestamp
uint8_t tx_buf[SLCAN_CMD_BUF_LEN]
Macro Definition Documentation
SLCAN_CMD_BUF_LEN
#define SLCAN_CMD_BUF_LEN (2*64+15)
Definition at line 34 of file slcan.h.
Function Documentation
slcan_event()
void slcan_event (void)
Definition at line 63 of file slcan.c.
References b, slcan_t::cmd_buf, slcan_t::cmd_buf_idx, slcan_t::dev, slcan, SLCAN_CMD_BUF_LEN, and slcan_handle_cmd().
slcan_init()
void slcan_init (void)
Definition at line 53 of file slcan.c.
References slcan_t::can_if, pprzaddr_can::can_ifindex, can_register_callback(), slcan_t::cmd_buf_idx, slcan_t::dev, foo, slcan_t::mtx, pprz_mtx_init(), slcan, slcan_can_rx_cb(), and slcan_t::timestamp.