Paparazzi UAS: sw/airborne/modules/sonar/sonar_adc.h File Reference
sonar_adc.h File Reference
Driver for an sonar rangfinder sensor when used via an ADC channel.
#include "std.h"
Data Structures
struct SonarADC
Functions
void sonar_adc_init (void)
void sonar_adc_periodic (void)
Reading Read ADC value to update sonar measurement.
void sonar_adc_report (void)
Debug report Option to send debug informative values over telemetry.
Variables
struct SonarADC sonar_adc
Detailed Description
Driver for an sonar rangfinder sensor when used via an ADC channel.
Driver module for an analog rangefinder sensor connected to an ADC channel.
This module reads the ADC values from a rangefinder sensor and converts those values to a distance in meters or fractions thereof.
Options include:
Using a low-pass filter to smooth the distance output
Updating AGL (Above Ground Level) in the state with the distance value.
Rotation compensation, which compensates the AGL distance based on the current attitude of the aircraft.
Use sensor simulation SITL (Software In The Loop).
Sending periodic telemetry debug messages with the raw ADC value and the calculated distance.
Definition in file sonar_adc.h.
Data Structure Documentation
SonarADC
struct SonarADC
Definition at line 41 of file sonar_adc.h.
Data Fields
float distance Distance measured in meters.
uint16_t raw raw measuread non scaled range value from sensor
float scale Scaling factor to convert raw value to a distance in SI unit (meters)
bool update_agl Do or don't update AGL ABI message.
Function Documentation
sonar_adc_init()
void sonar_adc_init (void) extern
Definition at line 121 of file sonar_adc.c.
References adc_buf_channel(), DEFAULT_AV_NB_SAMPLE, DefaultPeriodic, SonarADC::distance, foo, init_butterworth_2_low_pass(), SonarADC::raw, register_periodic_telemetry(), SonarADC::scale, sonar_adc, sonar_adc_buf, SONAR_ADC_LOWPASS_TAU, SONAR_ADC_SCALE, sonar_adc_send_sonar(), sonar_filt, SonarADC::update_agl, and USE_SONAR_ADC_AGL.
sonar_adc_periodic()
void sonar_adc_periodic (void) extern
Reading Read ADC value to update sonar measurement.
Definition at line 145 of file sonar_adc.c.
References AGL_SONAR_ADC_ID, adc_buf::av_nb_sample, SonarADC::distance, foo, get_sys_time_usec(), FloatEulers::phi, SonarADC::raw, SonarADC::scale, sonar_adc, sonar_adc_buf, SONAR_ADC_MAX_RANGE, SONAR_ADC_MIN_RANGE, SONAR_ADC_OFFSET, SONAR_ADC_RAW_OFFSET, sonar_adc_report(), sonar_filt, stateGetNedToBodyEulers_f(), stateGetPositionEnu_f(), adc_buf::sum, FloatEulers::theta, SonarADC::update_agl, update_butterworth_2_low_pass(), and EnuCoor_f::z.
sonar_adc_report()
void sonar_adc_report (void) extern
Debug report Option to send debug informative values over telemetry.
Definition at line 207 of file sonar_adc.c.
References DefaultChannel, DefaultDevice, SonarADC::distance, foo, SonarADC::raw, and sonar_adc.
Referenced by sonar_adc_periodic().
Variable Documentation
sonar_adc
struct SonarADC sonar_adc extern
Definition at line 107 of file sonar_adc.c.
Referenced by sonar_adc_init(), sonar_adc_periodic(), sonar_adc_report(), sonar_adc_send_sonar(), and sonar_pwm_read().