Paparazzi UAS: sw/airborne/modules/sonar/sonar_bebop.h File Reference
sonar_bebop.h File Reference
Parrot Bebop Sonar driver.
#include "std.h"
Data Structures
struct SonarBebop
Functions
void sonar_bebop_init (void)
void sonar_bebop_event (void)
Variables
struct SonarBebop sonar_bebop
Detailed Description
Parrot Bebop Sonar driver.
Definition in file sonar_bebop.h.
Data Structure Documentation
SonarBebop
struct SonarBebop
Definition at line 32 of file sonar_bebop.h.
Data Fields
bool available New data available.
float distance Distance measured in meters.
uint16_t meas Raw ADC value.
uint16_t offset Sonar offset in ADC units.
Function Documentation
sonar_bebop_event()
void sonar_bebop_event (void) extern
Definition at line 146 of file sonar_bebop.c.
References AGL_SONAR_ADC_ID, SonarBebop::available, DefaultChannel, DefaultDevice, SonarBebop::distance, foo, get_sys_time_usec(), SonarBebop::meas, FloatEulers::phi, sonar_bebop, sonar_mutex, stateGetNedToBodyEulers_f(), and FloatEulers::theta.
sonar_bebop_init()
void sonar_bebop_init (void) extern
Definition at line 113 of file sonar_bebop.c.
References SonarBebop::available, spi_transaction::dss, foo, init_median_filter_f(), spi_transaction::input_buf, spi_transaction::input_length, SonarBebop::meas, mode, SonarBebop::offset, spi_transaction::output_buf, spi_transaction::output_length, pulse_transition_counter, spi_transaction::select, sonar_bebop, sonar_bebop_read(), sonar_bebop_spi_d, sonar_bebop_spi_t, sonar_bebop_spike_timer, sonar_filt, sonar_mutex, SPIDss8bit, SPISelectUnselect, SPITransDone, spi_transaction::status, and SysTimeTimerStart.
Variable Documentation
sonar_bebop
struct SonarBebop sonar_bebop extern
Definition at line 103 of file sonar_bebop.c.
Referenced by sonar_bebop_event(), sonar_bebop_init(), and sonar_bebop_read().