Paparazzi UAS: sw/airborne/modules/sonar/sonar_vl53l1x.h File Reference
sonar_vl53l1x.h File Reference
#include "peripherals/vl53l1x_api.h"
Data Structures
struct sonar_vl53l1x_dev
Functions
void sonar_vl53l1x_init (void)
void sonar_vl53l1x_read (void)
void sonar_vl53l1x_event (void)
Variables
struct sonar_vl53l1x_dev sonar_vl53l1x
Data Structure Documentation
sonar_vl53l1x_dev
struct sonar_vl53l1x_dev
Definition at line 28 of file sonar_vl53l1x.h.
Data Fields
VL53L1_Dev_t dev
int16_t offset_mm
uint8_t read_state
Function Documentation
sonar_vl53l1x_event()
void sonar_vl53l1x_event (void) extern
Definition at line 118 of file sonar_vl53l1x.c.
References sonar_vl53l1x_dev::dev, foo, sonar_vl53l1x, sonar_vl53l1x_publish(), and VL53L1X_NonBlocking_ReadDataEvent().
sonar_vl53l1x_init()
void sonar_vl53l1x_init (void) extern
Definition at line 90 of file sonar_vl53l1x.c.
References sonar_vl53l1x_dev::dev, foo, VL53L1_Dev_t::i2c_p, VL53L1_Dev_t::i2c_trans, sonar_vl53l1x_dev::offset_mm, i2c_transaction::slave_addr, sonar_vl53l1x, SONAR_VL53L1X_DISTANCEMODE, SONAR_VL53L1X_I2C_ADDR, SONAR_VL53L1X_INTERMEASUREMENT_MS, SONAR_VL53L1X_OFFSET, SONAR_VL53L1X_TIMINGBUDGET_MS, and VL53L1X_BootDevice().
sonar_vl53l1x_read()
void sonar_vl53l1x_read (void) extern
Definition at line 104 of file sonar_vl53l1x.c.
References sonar_vl53l1x_dev::dev, foo, sonar_vl53l1x, sonar_vl53l1x_publish(), stateGetPositionEnu_f(), VL53L1X_NonBlocking_IsIdle(), VL53L1X_NonBlocking_RequestData(), and EnuCoor_f::z.
Variable Documentation
sonar_vl53l1x
struct sonar_vl53l1x_dev sonar_vl53l1x extern
Definition at line 72 of file sonar_vl53l1x.c.
Referenced by sonar_vl53l1x_event(), sonar_vl53l1x_init(), sonar_vl53l1x_publish(), and sonar_vl53l1x_read().