Paparazzi UAS: sw/airborne/modules/sonar/sonar_pwm.h File Reference
sonar_pwm.h File Reference
#include "std.h"
Data Structures
struct SonarPwm
Functions
void sonar_pwm_init (void)
void sonar_pwm_read (void)
Variables
struct SonarPwm sonar_pwm
Data Structure Documentation
SonarPwm
struct SonarPwm
Definition at line 42 of file sonar_pwm.h.
Data Fields
float distance Distance measured.
float offset offset
uint16_t raw raw PWM value
float scale scale to convert raw to a real distance
Function Documentation
sonar_pwm_init()
void sonar_pwm_init (void) extern
Definition at line 109 of file sonar_pwm.c.
References init_median_filter_f(), SonarPwm::offset, SonarPwm::raw, SonarPwm::scale, sonar_filt, SONAR_MEDIAN_SIZE, SONAR_OFFSET, sonar_pwm, and SONAR_SCALE.
sonar_pwm_read()
void sonar_pwm_read (void) extern
Definition at line 120 of file sonar_pwm.c.
References AGL_SONAR_PWM_ID, DefaultChannel, DefaultDevice, SonarADC::distance, SonarPwm::distance, foo, get_pwm_input_duty_in_usec(), get_sys_time_usec(), SonarPwm::offset, FloatEulers::phi, SonarPwm::raw, SonarPwm::scale, sonar_adc, sonar_filt, SONAR_MAX_RANGE, SONAR_MIN_RANGE, sonar_pwm, SONAR_PWM_OFFSET, stateGetNedToBodyEulers_f(), stateGetPositionEnu_f(), FloatEulers::theta, update_median_filter_f(), and EnuCoor_f::z.
Variable Documentation
sonar_pwm
struct SonarPwm sonar_pwm extern
Definition at line 106 of file sonar_pwm.c.
Referenced by sonar_pwm_init(), and sonar_pwm_read().