Paparazzi UAS: sw/airborne/modules/sonar/sonar_vl53l1x.c File Reference
sonar_vl53l1x.c File Reference
#include "sonar_vl53l1x.h"
#include "mcu_periph/i2c.h"
#include "peripherals/vl53l1x_nonblocking.h"
#include "modules/core/abi.h"
#include "modules/datalink/downlink.h"
Macros
#define SONAR_VL53L1X_I2C_ADDR VL53L1_DEFAULT_ADDRESS
#define SONAR_VL53L1X_OFFSET 0
#define SONAR_VL53L1X_TIMINGBUDGET_MS 100
#define SONAR_VL53L1X_DISTANCEMODE 2
#define SONAR_VL53L1X_INTERMEASUREMENT_MS SONAR_VL53L1X_TIMINGBUDGET_MS
Functions
static void sonar_vl53l1x_publish (uint16_t range_mm)
void sonar_vl53l1x_init (void)
void sonar_vl53l1x_read (void)
void sonar_vl53l1x_event (void)
Variables
struct sonar_vl53l1x_dev sonar_vl53l1x
Macro Definition Documentation
SONAR_VL53L1X_DISTANCEMODE
#define SONAR_VL53L1X_DISTANCEMODE 2
Definition at line 57 of file sonar_vl53l1x.c.
SONAR_VL53L1X_I2C_ADDR
#define SONAR_VL53L1X_I2C_ADDR VL53L1_DEFAULT_ADDRESS
Definition at line 37 of file sonar_vl53l1x.c.
SONAR_VL53L1X_INTERMEASUREMENT_MS
#define SONAR_VL53L1X_INTERMEASUREMENT_MS SONAR_VL53L1X_TIMINGBUDGET_MS
Definition at line 65 of file sonar_vl53l1x.c.
SONAR_VL53L1X_OFFSET
#define SONAR_VL53L1X_OFFSET 0
Definition at line 42 of file sonar_vl53l1x.c.
SONAR_VL53L1X_TIMINGBUDGET_MS
#define SONAR_VL53L1X_TIMINGBUDGET_MS 100
Definition at line 51 of file sonar_vl53l1x.c.
Function Documentation
sonar_vl53l1x_event()
void sonar_vl53l1x_event (void)
Definition at line 118 of file sonar_vl53l1x.c.
References sonar_vl53l1x_dev::dev, foo, sonar_vl53l1x, sonar_vl53l1x_publish(), and VL53L1X_NonBlocking_ReadDataEvent().
sonar_vl53l1x_init()
void sonar_vl53l1x_init (void)
Definition at line 90 of file sonar_vl53l1x.c.
References sonar_vl53l1x_dev::dev, foo, VL53L1_Dev_t::i2c_p, VL53L1_Dev_t::i2c_trans, sonar_vl53l1x_dev::offset_mm, i2c_transaction::slave_addr, sonar_vl53l1x, SONAR_VL53L1X_DISTANCEMODE, SONAR_VL53L1X_I2C_ADDR, SONAR_VL53L1X_INTERMEASUREMENT_MS, SONAR_VL53L1X_OFFSET, SONAR_VL53L1X_TIMINGBUDGET_MS, and VL53L1X_BootDevice().
sonar_vl53l1x_publish()
static void sonar_vl53l1x_publish (uint16_t range_mm) static
Definition at line 75 of file sonar_vl53l1x.c.
References AGL_VL53L1X_ID, DefaultChannel, DefaultDevice, foo, get_sys_time_usec(), sonar_vl53l1x_dev::offset_mm, and sonar_vl53l1x.
Referenced by sonar_vl53l1x_event(), and sonar_vl53l1x_read().
sonar_vl53l1x_read()
void sonar_vl53l1x_read (void)
Definition at line 104 of file sonar_vl53l1x.c.
References sonar_vl53l1x_dev::dev, foo, sonar_vl53l1x, sonar_vl53l1x_publish(), stateGetPositionEnu_f(), VL53L1X_NonBlocking_IsIdle(), VL53L1X_NonBlocking_RequestData(), and EnuCoor_f::z.
Variable Documentation
sonar_vl53l1x
struct sonar_vl53l1x_dev sonar_vl53l1x
Definition at line 72 of file sonar_vl53l1x.c.
Referenced by sonar_vl53l1x_event(), sonar_vl53l1x_init(), sonar_vl53l1x_publish(), and sonar_vl53l1x_read().