Paparazzi UAS: sw/airborne/modules/spektrum_soft_bind/spektrum_soft_bind_ap.h File Reference
spektrum_soft_bind_ap.h File Reference
#include "std.h"
Functions
void spektrum_soft_bind_init (void)
void spektrum_soft_bind_click (bool val)
void send_spektrum_bind (void)
Variables
bool bind_soft_value
Detailed Description
Author
Kevin van Hecke Puts Spektrum in binding mode through software
Definition in file spektrum_soft_bind_ap.h.
Function Documentation
send_spektrum_bind()
void send_spektrum_bind (void)
Definition at line 62 of file spektrum_soft_bind_ap.c.
References foo, LED_OFF, LED_ON, RADIO_CONTROL_POWER_OFF, RADIO_CONTROL_POWER_ON, RADIO_CONTROL_POWER_PIN, RADIO_CONTROL_POWER_PORT, sys_time_usleep(), and UART_INIT.
Referenced by spektrum_soft_bind_click().
spektrum_soft_bind_click()
void spektrum_soft_bind_click (bool val) extern
Definition at line 50 of file spektrum_soft_bind_ap.c.
References bind_soft_value, intermcu_send_spektrum_bind(), send_spektrum_bind(), and val.
spektrum_soft_bind_init()
void spektrum_soft_bind_init (void) extern
Definition at line 28 of file spektrum_soft_bind.c.
Variable Documentation
bind_soft_value
bool bind_soft_value extern
Definition at line 49 of file spektrum_soft_bind_ap.c.
Referenced by spektrum_soft_bind_click().