Paparazzi UAS: sw/airborne/modules/spektrum_soft_bind/spektrum_soft_bind_ap.c File Reference
spektrum_soft_bind_ap.c File Reference
#include "modules/spektrum_soft_bind/spektrum_soft_bind_ap.h"
#include "modules/intermcu/intermcu_ap.h"
#include "led.h"
#include "mcu.h"
#include "modules/radio_control/radio_control.h"
#include "mcu_periph/sys_time_arch.h"
#include "mcu_periph/uart.h"
#include "mcu_periph/gpio.h"
Macros
#define _UART_INIT(i) i ## _init()
#define UART_INIT(i) _UART_INIT(i)
Functions
void spektrum_soft_bind_init (void)
void spektrum_soft_bind_click (bool val)
void send_spektrum_bind (void)
Variables
bool bind_soft_value
Detailed Description
Author
Kevin van Hecke Puts Spektrum in binding mode through software
Definition in file spektrum_soft_bind_ap.c.
Macro Definition Documentation
_UART_INIT
#define _UART_INIT (i) i ## _init()
Definition at line 46 of file spektrum_soft_bind_ap.c.
UART_INIT
#define UART_INIT (i) _UART_INIT(i)
Definition at line 47 of file spektrum_soft_bind_ap.c.
Function Documentation
send_spektrum_bind()
void send_spektrum_bind (void)
Definition at line 62 of file spektrum_soft_bind_ap.c.
References foo, LED_OFF, LED_ON, RADIO_CONTROL_POWER_OFF, RADIO_CONTROL_POWER_ON, RADIO_CONTROL_POWER_PIN, RADIO_CONTROL_POWER_PORT, sys_time_usleep(), and UART_INIT.
Referenced by spektrum_soft_bind_click().
spektrum_soft_bind_click()
void spektrum_soft_bind_click (bool val)
Definition at line 50 of file spektrum_soft_bind_ap.c.
References bind_soft_value, intermcu_send_spektrum_bind(), send_spektrum_bind(), and val.
spektrum_soft_bind_init()
void spektrum_soft_bind_init (void)
Definition at line 41 of file spektrum_soft_bind_ap.c.
Variable Documentation
bind_soft_value
bool bind_soft_value
Definition at line 49 of file spektrum_soft_bind_ap.c.
Referenced by spektrum_soft_bind_click().