Paparazzi UAS: sw/airborne/firmwares/rotorcraft/stabilization/stabilization_direct.h File Reference
stabilization_direct.h File Reference
Dummy stabilization for rotorcrafts.
#include "math/pprz_algebra_int.h"
#include "firmwares/rotorcraft/stabilization.h"
Functions
void stabilization_direct_init (void)
void stabilization_direct_read_rc (void)
void stabilization_direct_run (bool in_flight, struct StabilizationSetpoint *sp, struct ThrustSetpoint *thrust, int32_t *cmd)
void stabilization_direct_enter (void)
Variables
struct Int32Rates stabilization_direct_rc_cmd
Detailed Description
Dummy stabilization for rotorcrafts.
Doesn't actually do any stabilization, just directly passes the RC commands along.
Definition in file stabilization_direct.h.
Function Documentation
stabilization_direct_enter()
void stabilization_direct_enter (void) extern
Definition at line 52 of file stabilization_direct.c.
References INT_RATES_ZERO, and stabilization_direct_rc_cmd.
Referenced by stabilization_mode_changed().
stabilization_direct_init()
void stabilization_direct_init (void) extern
Definition at line 38 of file stabilization_direct.c.
References INT_RATES_ZERO, and stabilization_direct_rc_cmd.
stabilization_direct_read_rc()
void stabilization_direct_read_rc (void) extern
Definition at line 43 of file stabilization_direct.c.
References Int32Rates::p, Int32Rates::q, Int32Rates::r, radio_control_get(), RADIO_PITCH, RADIO_ROLL, RADIO_YAW, and stabilization_direct_rc_cmd.
Referenced by rc_cb().
stabilization_direct_run()
void stabilization_direct_run (bool in_flight, struct StabilizationSetpoint * sp, struct ThrustSetpoint * thrust, int32_t * cmd) extern
Variable Documentation
stabilization_direct_rc_cmd
struct Int32Rates stabilization_direct_rc_cmd extern
Definition at line 36 of file stabilization_direct.c.
Referenced by stabilization_direct_enter(), stabilization_direct_init(), stabilization_direct_read_rc(), and stabilization_direct_run().