Paparazzi UAS: sw/airborne/firmwares/rotorcraft/stabilization/stabilization_attitude_quat_float.h File Reference
stabilization_attitude_quat_float.h File Reference
Rotorcraft attitude stabilization in quaternion float version.
#include "generated/airframe.h"
#include "firmwares/rotorcraft/stabilization/stabilization_attitude.h"
#include "firmwares/rotorcraft/stabilization/stabilization_attitude_common_float.h"
#include "firmwares/rotorcraft/stabilization/stabilization_attitude_ref_quat_float.h"
Macros
#define STABILIZATION_ATTITUDE_GAIN_NB 1
#define STABILIZATION_ATTITUDE_GAIN_IDX_DEFAULT 0
#define stabilization_attitude_quat_float_SetOmegaP(_val)
#define stabilization_attitude_quat_float_SetOmegaQ(_val)
#define stabilization_attitude_quat_float_SetOmegaR(_val)
Functions
void stabilization_attitude_quat_float_init (void)
void stabilization_attitude_gain_schedule (uint8_t idx)
Variables
struct FloatAttitudeGains stabilization_gains []
struct AttRefQuatFloat att_ref_quat_f
Detailed Description
Rotorcraft attitude stabilization in quaternion float version.
Definition in file stabilization_attitude_quat_float.h.
Macro Definition Documentation
STABILIZATION_ATTITUDE_GAIN_IDX_DEFAULT
#define STABILIZATION_ATTITUDE_GAIN_IDX_DEFAULT 0
Definition at line 42 of file stabilization_attitude_quat_float.h.
STABILIZATION_ATTITUDE_GAIN_NB
#define STABILIZATION_ATTITUDE_GAIN_NB 1
Definition at line 38 of file stabilization_attitude_quat_float.h.
stabilization_attitude_quat_float_SetOmegaP
#define stabilization_attitude_quat_float_SetOmegaP (_val)
Value:
    {      \
    attitude_ref_quat_float_set_omega_p(&att_ref_quat_f, _val);  \
  }
Definition at line 54 of file stabilization_attitude_quat_float.h.
stabilization_attitude_quat_float_SetOmegaQ
#define stabilization_attitude_quat_float_SetOmegaQ (_val)
Value:
    {      \
    attitude_ref_quat_float_set_omega_q(&att_ref_quat_f, _val);  \
  }
Definition at line 57 of file stabilization_attitude_quat_float.h.
stabilization_attitude_quat_float_SetOmegaR
#define stabilization_attitude_quat_float_SetOmegaR (_val)
Value:
    {      \
    attitude_ref_quat_float_set_omega_r(&att_ref_quat_f, _val);  \
  }
Definition at line 60 of file stabilization_attitude_quat_float.h.
Function Documentation
stabilization_attitude_gain_schedule()
void stabilization_attitude_gain_schedule (uint8_t idx) extern
Definition at line 195 of file stabilization_attitude_quat_float.c.
References att_ref_quat_f, attitude_ref_quat_float_schedule(), gain_idx, idx, and STABILIZATION_ATTITUDE_GAIN_NB.
stabilization_attitude_quat_float_init()
void stabilization_attitude_quat_float_init (void) extern
Definition at line 161 of file stabilization_attitude_quat_float.c.
References att_ref_quat_f, attitude_ref_quat_float_init(), attitude_ref_quat_float_schedule(), body_rate_d, DefaultPeriodic, FLOAT_EULERS_ZERO, float_quat_identity(), FLOAT_RATES_ZERO, foo, last_body_rate, p, phi_ddgain, phi_dgain, phi_dgain_d, phi_igain, phi_pgain, psi_ddgain, psi_dgain, psi_dgain_d, psi_igain, psi_pgain, register_periodic_telemetry(), send_ahrs_ref_quat(), send_att(), send_att_ref(), stab_att_sp_euler, stab_att_sp_quat, stabilization_att_sum_err_quat, STABILIZATION_ATTITUDE_GAIN_IDX_DEFAULT, STABILIZATION_ATTITUDE_GAIN_NB, stabilization_gains, theta_ddgain, theta_dgain, theta_dgain_d, theta_igain, theta_pgain, and VECT3_ASSIGN.
Variable Documentation
att_ref_quat_f
struct AttRefQuatFloat att_ref_quat_f extern
Definition at line 42 of file stabilization_attitude_quat_float.c.
Referenced by send_ahrs_ref_quat(), send_att_ref(), stabilization_attitude_enter(), stabilization_attitude_gain_schedule(), stabilization_attitude_quat_float_init(), and stabilization_attitude_run().
stabilization_gains
struct FloatAttitudeGains stabilization_gains[] extern
Definition at line 42 of file stabilization_attitude_euler_float.c.
Referenced by stabilization_attitude_euler_float_init(), stabilization_attitude_euler_int_init(), stabilization_attitude_quat_float_init(), stabilization_attitude_run(), and stabilization_attitude_run().