Paparazzi UAS: sw/airborne/firmwares/rotorcraft/stabilization/stabilization_attitude_quat_int.h File Reference
stabilization_attitude_quat_int.h File Reference
#include "firmwares/rotorcraft/stabilization/stabilization_attitude.h"
#include "firmwares/rotorcraft/stabilization/stabilization_attitude_common_int.h"
#include "firmwares/rotorcraft/stabilization/stabilization_attitude_ref_quat_int.h"
#include "math/pprz_algebra_int.h"
Macros
#define stabilization_attitude_quat_int_SetOmegaP(_val)
#define stabilization_attitude_quat_int_SetOmegaQ(_val)
#define stabilization_attitude_quat_int_SetOmegaR(_val)
#define stabilization_attitude_quat_int_SetZetaP(_val)
#define stabilization_attitude_quat_int_SetZetaQ(_val)
#define stabilization_attitude_quat_int_SetZetaR(_val)
Functions
void stabilization_attitude_quat_int_init (void)
Variables
struct AttRefQuatInt att_ref_quat_i
Macro Definition Documentation
stabilization_attitude_quat_int_SetOmegaP
#define stabilization_attitude_quat_int_SetOmegaP (_val)
Value:
    {   \
    attitude_ref_quat_int_set_omega_p(&att_ref_quat_i, _val);   \
  }
Definition at line 36 of file stabilization_attitude_quat_int.h.
stabilization_attitude_quat_int_SetOmegaQ
#define stabilization_attitude_quat_int_SetOmegaQ (_val)
Value:
    {   \
    attitude_ref_quat_int_set_omega_q(&att_ref_quat_i, _val);   \
  }
Definition at line 39 of file stabilization_attitude_quat_int.h.
stabilization_attitude_quat_int_SetOmegaR
#define stabilization_attitude_quat_int_SetOmegaR (_val)
Value:
    {   \
    attitude_ref_quat_int_set_omega_r(&att_ref_quat_i, _val);   \
  }
Definition at line 42 of file stabilization_attitude_quat_int.h.
stabilization_attitude_quat_int_SetZetaP
#define stabilization_attitude_quat_int_SetZetaP (_val)
Value:
    {    \
    attitude_ref_quat_int_set_zeta_p(&att_ref_quat_i, _val);    \
  }
Definition at line 46 of file stabilization_attitude_quat_int.h.
stabilization_attitude_quat_int_SetZetaQ
#define stabilization_attitude_quat_int_SetZetaQ (_val)
Value:
    {    \
    attitude_ref_quat_int_set_zeta_q(&att_ref_quat_i, _val);    \
  }
Definition at line 49 of file stabilization_attitude_quat_int.h.
stabilization_attitude_quat_int_SetZetaR
#define stabilization_attitude_quat_int_SetZetaR (_val)
Value:
    {    \
    attitude_ref_quat_int_set_zeta_r(&att_ref_quat_i, _val);    \
  }
Definition at line 52 of file stabilization_attitude_quat_int.h.
Function Documentation
stabilization_attitude_quat_int_init()
void stabilization_attitude_quat_int_init (void) extern
Definition at line 147 of file stabilization_attitude_quat_int.c.
References att_ref_quat_i, attitude_ref_quat_int_init(), DefaultPeriodic, foo, int32_quat_identity(), register_periodic_telemetry(), send_ahrs_ref_quat(), send_att(), send_att_ref(), and stabilization_att_sum_err_quat.
Variable Documentation
att_ref_quat_i
struct AttRefQuatInt att_ref_quat_i extern
Definition at line 77 of file stabilization_attitude_quat_int.c.
Referenced by send_ahrs_ref_quat(), send_att_ref(), stabilization_attitude_enter(), stabilization_attitude_quat_int_init(), and stabilization_attitude_run().