Paparazzi UAS: sw/airborne/firmwares/rotorcraft/stabilization/stabilization_attitude_euler_float.h File Reference
stabilization_attitude_euler_float.h File Reference
Rotorcraft attitude stabilization in euler float version.
#include "firmwares/rotorcraft/stabilization/stabilization_attitude.h"
#include "firmwares/rotorcraft/stabilization/stabilization_attitude_common_float.h"
Functions
void stabilization_attitude_euler_float_init (void)
Variables
struct FloatAttitudeGains stabilization_gains
struct FloatEulers stabilization_att_sum_err
Detailed Description
Rotorcraft attitude stabilization in euler float version.
Definition in file stabilization_attitude_euler_float.h.
Function Documentation
stabilization_attitude_euler_float_init()
void stabilization_attitude_euler_float_init (void) extern
Definition at line 98 of file stabilization_attitude_euler_float.c.
References att_ref_euler_f, attitude_ref_euler_float_init(), FloatAttitudeGains::d, FloatAttitudeGains::dd, DefaultPeriodic, FLOAT_EULERS_ZERO, foo, FloatAttitudeGains::i, FloatAttitudeGains::p, register_periodic_telemetry(), send_att(), send_att_ref(), stabilization_att_sum_err, stabilization_gains, and VECT3_ASSIGN.
Variable Documentation
stabilization_att_sum_err
struct FloatEulers stabilization_att_sum_err extern
Definition at line 43 of file stabilization_attitude_euler_float.c.
stabilization_gains
struct FloatAttitudeGains stabilization_gains extern
Definition at line 42 of file stabilization_attitude_euler_float.c.