Paparazzi UAS: sw/airborne/firmwares/rotorcraft/stabilization/stabilization_attitude_euler_int.h File Reference
stabilization_attitude_euler_int.h File Reference
#include "firmwares/rotorcraft/stabilization/stabilization_attitude.h"
#include "firmwares/rotorcraft/stabilization/stabilization_attitude_common_int.h"
Functions
void stabilization_attitude_euler_int_init (void)
Variables
struct Int32Eulers stabilization_att_sum_err
Function Documentation
stabilization_attitude_euler_int_init()
void stabilization_attitude_euler_int_init (void) extern
Definition at line 128 of file stabilization_attitude_euler_int.c.
References att_ref_euler_i, attitude_ref_euler_int_init(), Int32AttitudeGains::d, Int32AttitudeGains::dd, DefaultPeriodic, Int32AttitudeGains::ffd, foo, Int32AttitudeGains::i, INT_EULERS_ZERO, Int32AttitudeGains::p, register_periodic_telemetry(), send_att(), send_att_ref(), stab_att_sp_euler, stabilization_att_sum_err, STABILIZATION_ATTITUDE_PHI_FFDGAIN, STABILIZATION_ATTITUDE_PSI_FFDGAIN, STABILIZATION_ATTITUDE_THETA_FFDGAIN, stabilization_gains, and VECT3_ASSIGN.
Variable Documentation
stabilization_att_sum_err
struct Int32Eulers stabilization_att_sum_err extern
Definition at line 43 of file stabilization_attitude_euler_float.c.
Referenced by send_att(), send_att(), stabilization_attitude_enter(), stabilization_attitude_euler_float_init(), stabilization_attitude_euler_int_init(), and stabilization_attitude_run().