Paparazzi UAS: sw/airborne/firmwares/rotorcraft/stabilization/stabilization_rate.h File Reference
stabilization_rate.h File Reference
Rate stabilization for rotorcrafts.
#include "firmwares/rotorcraft/stabilization.h"
#include "modules/radio_control/radio_control.h"
#include "math/pprz_algebra_float.h"
Macros
#define STABILIZATION_RATE_DEADBAND_P 0
#define STABILIZATION_RATE_DEADBAND_Q 0
#define STABILIZATION_RATE_DEADBAND_R 200
#define ROLL_RATE_DEADBAND_EXCEEDED(_rc)
#define PITCH_RATE_DEADBAND_EXCEEDED(_rc)
#define YAW_RATE_DEADBAND_EXCEEDED(_rc)
#define RC_RATE_P RADIO_ROLL
#define RC_RATE_Q RADIO_PITCH
#define RC_RATE_R RADIO_YAW
Functions
void stabilization_rate_init (void)
Initialize rate controller.
void stabilization_rate_run (bool in_flight, struct StabilizationSetpoint *rate_sp, struct ThrustSetpoint *thrust, int32_t *cmd)
Run indi rate interface from the "stabilization_rate_run" function.
void stabilization_rate_enter (void)
Reset rate controller.
struct StabilizationSetpoint stabilization_rate_read_rc (struct RadioControl *rc)
Variables
struct FloatRates stabilization_rate_gain
struct FloatRates stabilization_rate_igain
Detailed Description
Rate stabilization for rotorcrafts.
Control loops for angular velocity.
Definition in file stabilization_rate.h.
Macro Definition Documentation
PITCH_RATE_DEADBAND_EXCEEDED
#define PITCH_RATE_DEADBAND_EXCEEDED (_rc)
Value:
  (_rc->values[RADIO_PITCH] >  STABILIZATION_RATE_DEADBAND_Q || \
   _rc->values[RADIO_PITCH] < -STABILIZATION_RATE_DEADBAND_Q)
Definition at line 49 of file stabilization_rate.h.
RC_RATE_P
#define RC_RATE_P RADIO_ROLL
Definition at line 64 of file stabilization_rate.h.
RC_RATE_Q
#define RC_RATE_Q RADIO_PITCH
Definition at line 65 of file stabilization_rate.h.
RC_RATE_R
#define RC_RATE_R RADIO_YAW
Definition at line 66 of file stabilization_rate.h.
ROLL_RATE_DEADBAND_EXCEEDED
#define ROLL_RATE_DEADBAND_EXCEEDED (_rc)
Value:
  (_rc->values[RADIO_ROLL] >  STABILIZATION_RATE_DEADBAND_P || \
   _rc->values[RADIO_ROLL] < -STABILIZATION_RATE_DEADBAND_P)
Definition at line 45 of file stabilization_rate.h.
STABILIZATION_RATE_DEADBAND_P
#define STABILIZATION_RATE_DEADBAND_P 0
Definition at line 36 of file stabilization_rate.h.
STABILIZATION_RATE_DEADBAND_Q
#define STABILIZATION_RATE_DEADBAND_Q 0
Definition at line 39 of file stabilization_rate.h.
STABILIZATION_RATE_DEADBAND_R
#define STABILIZATION_RATE_DEADBAND_R 200
Definition at line 42 of file stabilization_rate.h.
YAW_RATE_DEADBAND_EXCEEDED
#define YAW_RATE_DEADBAND_EXCEEDED (_rc)
Value:
  (_rc->values[RADIO_YAW] >  STABILIZATION_RATE_DEADBAND_R || \
   _rc->values[RADIO_YAW] < -STABILIZATION_RATE_DEADBAND_R)
Definition at line 53 of file stabilization_rate.h.
Function Documentation
stabilization_rate_enter()
void stabilization_rate_enter (void) extern
Reset rate controller.
Definition at line 1375 of file stabilization_andi.c.
References FLOAT_RATES_ZERO, stabilization_indi_enter(), and stabilization_rate_sum_err.
Referenced by stabilization_mode_changed().
stabilization_rate_init()
void stabilization_rate_init (void) extern
Initialize rate controller.
Definition at line 92 of file stabilization_rate.c.
References DefaultPeriodic, FLOAT_RATES_ZERO, foo, RATES_ASSIGN, register_periodic_telemetry(), send_rate(), send_rate(), stabilization_rate_gain, stabilization_rate_igain, STABILIZATION_RATE_IGAIN_P, STABILIZATION_RATE_IGAIN_Q, STABILIZATION_RATE_IGAIN_R, stabilization_rate_sp, stabilization_rate_sp, and stabilization_rate_sum_err.
stabilization_rate_read_rc()
struct StabilizationSetpoint stabilization_rate_read_rc (struct RadioControl * rc) extern
Definition at line 1395 of file stabilization_andi.c.
References FLOAT_RATES_ZERO, foo, MAX_PPRZ, PITCH_RATE_DEADBAND_EXCEEDED, RC_RATE_MAX, RC_RATE_P, RC_RATE_Q, RC_RATE_R, ROLL_RATE_DEADBAND_EXCEEDED, stab_sp_from_rates_f(), STABILIZATION_INDI_MAX_RATE, THROTTLE_STICK_DOWN_FROM_RC, and YAW_RATE_DEADBAND_EXCEEDED.
Referenced by rc_cb().
stabilization_rate_run()
void stabilization_rate_run (bool in_flight, struct StabilizationSetpoint * rate_sp, struct ThrustSetpoint * thrust, int32_t * cmd) extern
Run indi rate interface from the "stabilization_rate_run" function.
Definition at line 1380 of file stabilization_andi.c.
References FLOAT_RATES_ZERO, foo, MAX_PPRZ, MAX_SUM_ERR, FloatRates::p, FloatRates::q, FloatRates::r, RATES_ADD, RATES_BOUND_CUBE, RATES_DIFF, RATES_SDIV, stab_sp_to_rates_f(), stabilization_indi_rate_run(), stabilization_rate_fb_cmd, stabilization_rate_gain, stabilization_rate_igain, stabilization_rate_sp, stabilization_rate_sp, stabilization_rate_sum_err, stateGetBodyRates_f(), th_sp_to_thrust_i(), and THRUST_AXIS_Z.
Referenced by stabilization_run().
Variable Documentation
stabilization_rate_gain
struct FloatRates stabilization_rate_gain extern
Definition at line 70 of file stabilization_rate.c.
Referenced by stabilization_rate_init(), and stabilization_rate_run().
stabilization_rate_igain
struct FloatRates stabilization_rate_igain extern
Definition at line 71 of file stabilization_rate.c.
Referenced by stabilization_rate_init(), and stabilization_rate_run().