Paparazzi UAS: sw/airborne/firmwares/rotorcraft/stabilization/stabilization_attitude_plane_pid.c File Reference
stabilization_attitude_plane_pid.c File Reference
Basic fixed-wing attitude stabilization in euler float version.
#include "generated/airframe.h"
#include "firmwares/rotorcraft/stabilization/stabilization_attitude_plane_pid.h"
#include "std.h"
#include "paparazzi.h"
#include "math/pprz_algebra_float.h"
#include "state.h"
#include "modules/datalink/telemetry.h"
Macros
#define MAX_SUM_ERR 200
Functions
static void send_att (struct transport_tx *trans, struct link_device *dev)
void stabilization_attitude_plane_pid_init (void)
void stabilization_attitude_plane_pid_enter (void)
void stabilization_attitude_plane_pid_run (bool in_flight, struct StabilizationSetpoint *sp, struct ThrustSetpoint *thrust, int32_t *cmd)
Variables
struct PlaneAttitudeGains stab_plane_gains
struct FloatEulers stab_plane_att_sum_err
static struct FloatEulers stab_att_sp_euler
float stab_plane_att_cmd [COMMANDS_NB]
Detailed Description
Basic fixed-wing attitude stabilization in euler float version.
Definition in file stabilization_attitude_plane_pid.c.
Macro Definition Documentation
MAX_SUM_ERR
#define MAX_SUM_ERR 200
Definition at line 100 of file stabilization_attitude_plane_pid.c.
Function Documentation
send_att()
static void send_att (struct transport_tx * trans, struct link_device * dev) static
Definition at line 46 of file stabilization_attitude_plane_pid.c.
References Stabilization::cmd, dev, foo, FloatRates::p, FloatEulers::phi, FloatEulers::psi, FloatRates::q, FloatRates::r, stab_att_sp_euler, stab_plane_att_cmd, stab_plane_att_sum_err, stabilization, stateGetBodyRates_f(), stateGetNedToBodyEulers_f(), and FloatEulers::theta.
Referenced by stabilization_attitude_plane_pid_init().
stabilization_attitude_plane_pid_enter()
void stabilization_attitude_plane_pid_enter (void)
Definition at line 95 of file stabilization_attitude_plane_pid.c.
References FLOAT_EULERS_ZERO, and stab_plane_att_sum_err.
Referenced by control_mixing_heewing_attitude_plane_enter().
stabilization_attitude_plane_pid_init()
void stabilization_attitude_plane_pid_init (void)
Definition at line 71 of file stabilization_attitude_plane_pid.c.
References PlaneAttitudeGains::d, DefaultPeriodic, FLOAT_EULERS_ZERO, foo, PlaneAttitudeGains::i, PlaneAttitudeGains::p, register_periodic_telemetry(), send_att(), stab_plane_att_sum_err, stab_plane_gains, and VECT3_ASSIGN.
stabilization_attitude_plane_pid_run()
void stabilization_attitude_plane_pid_run (bool in_flight, struct StabilizationSetpoint * sp, struct ThrustSetpoint * thrust, int32_t * cmd)
Definition at line 102 of file stabilization_attitude_plane_pid.c.
References PlaneAttitudeGains::d, EULERS_ADD, EULERS_BOUND_CUBE, EULERS_DIFF, EULERS_SDIV, FLOAT_EULERS_ZERO, FLOAT_RATES_ZERO, foo, PlaneAttitudeGains::i, MAX_PPRZ, MAX_SUM_ERR, PlaneAttitudeGains::p, FloatEulers::phi, RATES_DIFF, stab_att_sp_euler, stab_plane_att_cmd, stab_plane_att_sum_err, stab_plane_gains, stab_sp_to_eulers_f(), stateGetBodyRates_f(), stateGetNedToBodyEulers_f(), th_sp_to_thrust_i(), FloatEulers::theta, THRUST_AXIS_X, FloatVect3::x, and FloatVect3::y.
Referenced by control_mixing_heewing_attitude_plane(), and control_mixing_heewing_nav_run().
Variable Documentation
stab_att_sp_euler
struct FloatEulers stab_att_sp_euler static
Definition at line 39 of file stabilization_attitude_plane_pid.c.
Referenced by send_att(), and stabilization_attitude_plane_pid_run().
stab_plane_att_cmd
float stab_plane_att_cmd[COMMANDS_NB]
Definition at line 41 of file stabilization_attitude_plane_pid.c.
Referenced by send_att(), and stabilization_attitude_plane_pid_run().
stab_plane_att_sum_err
struct FloatEulers stab_plane_att_sum_err
Definition at line 37 of file stabilization_attitude_plane_pid.c.
Referenced by send_att(), stabilization_attitude_plane_pid_enter(), stabilization_attitude_plane_pid_init(), and stabilization_attitude_plane_pid_run().
stab_plane_gains
struct PlaneAttitudeGains stab_plane_gains
Definition at line 36 of file stabilization_attitude_plane_pid.c.
Referenced by stabilization_attitude_plane_pid_init(), and stabilization_attitude_plane_pid_run().