Paparazzi UAS: sw/airborne/firmwares/rotorcraft/stabilization/stabilization_indi_hinf.c File Reference
stabilization_indi_hinf.c File Reference
#include "firmwares/rotorcraft/stabilization/stabilization_indi.h"
#include "math/pprz_algebra_float.h"
#include "autopilot.h"
Functions
struct FloatRates stabilization_indi_rate_controller (struct FloatRates rates, struct FloatRates sp)
Angular acceleration controller based on Hinfinity.
struct FloatRates WEAK stabilization_indi_attitude_controller (struct FloatQuat att, struct FloatQuat att_sp, struct FloatRates rates_ff)
Angular rate controller based on Hinfinity.
Variables
static struct FloatRates rate_state
static struct FloatRates att_state
static float Ap = STABILIZATION_INDI_HINF_Ap
static float Bp = STABILIZATION_INDI_HINF_Bp
static float Cp = STABILIZATION_INDI_HINF_Cp
static float Dp = STABILIZATION_INDI_HINF_Dp
static float Ad = STABILIZATION_INDI_HINF_Ad
static float Bd = STABILIZATION_INDI_HINF_Bd
static float Cd = STABILIZATION_INDI_HINF_Cd
static float Dd = STABILIZATION_INDI_HINF_Dd
Function Documentation
stabilization_indi_attitude_controller()
struct FloatRates WEAK stabilization_indi_attitude_controller (struct FloatQuat att, struct FloatQuat att_sp, struct FloatRates rates_ff)
Angular rate controller based on Hinfinity.
Default PD angular rate controller.
Takes the current attitude filtered state and setpoint and compute the desired rates. Can be redefined elsewhere to use an other control scheme.
Definition at line 70 of file stabilization_indi_hinf.c.
References Ap, Indi_gains::att, att_state, autopilot_in_flight(), Bp, Cp, Dp, float_quat_inv_comp_norm_shortest(), float_quat_tilt_twist(), FLOAT_RATES_ZERO, foo, indi_gains, FloatRates::p, FloatRates::q, FloatRates::r, Indi_gains::rate, and RATES_ADD.
stabilization_indi_rate_controller()
struct FloatRates stabilization_indi_rate_controller (struct FloatRates rates, struct FloatRates sp)
Angular acceleration controller based on Hinfinity.
Default PD angular acceleration controller.
Takes the current rates filtered state and setpoint and compute the desired acceleration.
Definition at line 43 of file stabilization_indi_hinf.c.
References Ad, autopilot_in_flight(), Bd, Cd, Dd, FLOAT_RATES_ZERO, foo, indi_gains, FloatRates::p, FloatRates::q, FloatRates::r, Indi_gains::rate, rate_state, and RATES_DIFF.
Variable Documentation
Ad
float Ad = STABILIZATION_INDI_HINF_Ad static
Definition at line 34 of file stabilization_indi_hinf.c.
Ap
float Ap = STABILIZATION_INDI_HINF_Ap static
Definition at line 29 of file stabilization_indi_hinf.c.
att_state
struct FloatRates att_state static
Definition at line 26 of file stabilization_indi_hinf.c.
Referenced by control_error_attitude(), control_error_rate(), and stabilization_indi_attitude_controller().
Bd
float Bd = STABILIZATION_INDI_HINF_Bd static
Definition at line 35 of file stabilization_indi_hinf.c.
Bp
float Bp = STABILIZATION_INDI_HINF_Bp static
Definition at line 30 of file stabilization_indi_hinf.c.
Cd
float Cd = STABILIZATION_INDI_HINF_Cd static
Definition at line 36 of file stabilization_indi_hinf.c.
Cp
float Cp = STABILIZATION_INDI_HINF_Cp static
Definition at line 31 of file stabilization_indi_hinf.c.
Dd
float Dd = STABILIZATION_INDI_HINF_Dd static
Definition at line 37 of file stabilization_indi_hinf.c.
Dp
float Dp = STABILIZATION_INDI_HINF_Dp static
Definition at line 32 of file stabilization_indi_hinf.c.
rate_state
struct FloatRates rate_state static
Definition at line 25 of file stabilization_indi_hinf.c.
Referenced by stabilization_indi_rate_controller().