Paparazzi UAS: sw/airborne/firmwares/rotorcraft/stabilization/stabilization_direct.c File Reference
stabilization_direct.c File Reference
Dummy stabilization for rotorcrafts.
#include "firmwares/rotorcraft/stabilization.h"
#include "firmwares/rotorcraft/stabilization/stabilization_direct.h"
#include "modules/radio_control/radio_control.h"
#include "generated/airframe.h"
#include "generated/modules.h"
Functions
void stabilization_direct_init (void)
void stabilization_direct_read_rc (void)
void stabilization_direct_enter (void)
void stabilization_direct_run (bool in_flight UNUSED, struct StabilizationSetpoint *sp UNUSED, struct ThrustSetpoint *thrust UNUSED, int32_t *cmd UNUSED)
Variables
struct Int32Rates stabilization_direct_rc_cmd
Detailed Description
Dummy stabilization for rotorcrafts.
Doesn't actually do any stabilization, just directly passes the RC commands along.
Definition in file stabilization_direct.c.
Function Documentation
stabilization_direct_enter()
void stabilization_direct_enter (void)
Definition at line 52 of file stabilization_direct.c.
References INT_RATES_ZERO, and stabilization_direct_rc_cmd.
Referenced by stabilization_mode_changed().
stabilization_direct_init()
void stabilization_direct_init (void)
Definition at line 38 of file stabilization_direct.c.
References INT_RATES_ZERO, and stabilization_direct_rc_cmd.
stabilization_direct_read_rc()
void stabilization_direct_read_rc (void)
Definition at line 43 of file stabilization_direct.c.
References Int32Rates::p, Int32Rates::q, Int32Rates::r, radio_control_get(), RADIO_PITCH, RADIO_ROLL, RADIO_YAW, and stabilization_direct_rc_cmd.
Referenced by rc_cb().
stabilization_direct_run()
void stabilization_direct_run (bool in_flight UNUSED, struct StabilizationSetpoint *sp UNUSED, struct ThrustSetpoint *thrust UNUSED, int32_t *cmd UNUSED)
Definition at line 57 of file stabilization_direct.c.
References foo, Int32Rates::p, Int32Rates::q, Int32Rates::r, stabilization_direct_rc_cmd, th_sp_to_thrust_i(), and THRUST_AXIS_Z.
Referenced by stabilization_run().
Variable Documentation
stabilization_direct_rc_cmd
struct Int32Rates stabilization_direct_rc_cmd
Definition at line 36 of file stabilization_direct.c.
Referenced by stabilization_direct_enter(), stabilization_direct_init(), stabilization_direct_read_rc(), and stabilization_direct_run().