Paparazzi UAS: sw/airborne/modules/stereocam/stereocam.h File Reference
stereocam.h File Reference
interface to the TU Delft serial stereocam
#include "pprzlink/pprz_transport.h"
#include "math/pprz_algebra_float.h"
Data Structures
struct stereocam_t
Functions
void stereocam_init (void)
void stereocam_event (void)
void state2stereocam (void)
Detailed Description
interface to the TU Delft serial stereocam
Definition in file stereocam.h.
Data Structure Documentation
stereocam_t
struct stereocam_t
Definition at line 34 of file stereocam.h.
Data Fields
struct FloatRMat body_to_cam IMU to stereocam rotation.
struct link_device * device The device which is uses for communication.
bool msg_available If we received a message.
struct pprz_transport transport The transport layer (PPRZ)
Function Documentation
state2stereocam()
void state2stereocam (void) extern
Definition at line 216 of file stereocam.c.
References stereocam_t::body_to_cam, stereocam_t::device, float_rmat_mult(), foo, stateGetNedToBodyEulers_f(), stereocam, and stereocam_t::transport.
stereocam_event()
void stereocam_event (void) extern
Definition at line 202 of file stereocam.c.
References stereocam_t::device, foo, stereocam_t::msg_available, stereocam, stereocam_msg_buf, stereocam_parse_msg(), and stereocam_t::transport.
stereocam_init()
void stereocam_init (void) extern
Definition at line 95 of file stereocam.c.
References stereocam_t::body_to_cam, float_rmat_of_eulers, foo, InitMedianFilterVect3Float, MEDIAN_DEFAULT_SIZE, medianfilter, STEREO_BODY_TO_STEREO_PHI, STEREO_BODY_TO_STEREO_PSI, STEREO_BODY_TO_STEREO_THETA, stereocam, and stereocam_t::transport.