Paparazzi UAS: sw/airborne/modules/stereocam/nav_line_avoid/stereo_avoid.h File Reference
stereo_avoid.h File Reference
Functions
void stereo_avoid_init (void)
void stereo_avoid_run (void)
Variables
int stereo_avoid_vision_adjust_factor
Function Documentation
stereo_avoid_init()
void stereo_avoid_init (void) extern
Definition at line 42 of file stereo_avoid.c.
References avoid_navigation_data, init_avoid_navigation(), and AvoidNavigationStruct::stereo_bin.
stereo_avoid_run()
void stereo_avoid_run (void) extern
Definition at line 49 of file stereo_avoid.c.
References avoid_navigation_data, counter, foo, heading, NormAngleRad, FloatEulers::psi, run_avoid_navigation_onvision(), stateGetNedToBodyEulers_f(), stateGetPositionEnu_f(), and AvoidNavigationStruct::stereo_bin.
Variable Documentation
stereo_avoid_vision_adjust_factor
int stereo_avoid_vision_adjust_factor extern