Paparazzi UAS: sw/airborne/modules/stereocam/nav_line_avoid/stereo_avoid_sim.c File Reference
stereo_avoid_sim.c File Reference
#include "stereo_avoid.h"
#include "avoid_navigation.h"
#include "state.h"
#include "std.h"
Macros
#define NormAngleRad(x)
Normalize a degree angle between 0 and 359.
Functions
void stereo_avoid_init (void)
void stereo_avoid_run (void)
void stereo_avoid_start (void)
void stereo_avoid_stop (void)
Macro Definition Documentation
NormAngleRad
#define NormAngleRad (x)
Value:
    { \
    int dont_loop_forever = 0;  \
    while ((x < (-M_PI)) && ++dont_loop_forever) x += (2 * M_PI); \
    while ((x >= (M_PI)) && ++dont_loop_forever) x -= (2 * M_PI); \
  }
Normalize a degree angle between 0 and 359.
Definition at line 46 of file stereo_avoid_sim.c.
Function Documentation
stereo_avoid_init()
void stereo_avoid_init (void)
Definition at line 35 of file stereo_avoid_sim.c.
References avoid_navigation_data, init_avoid_navigation(), and AvoidNavigationStruct::stereo_bin.
stereo_avoid_run()
void stereo_avoid_run (void)
Definition at line 53 of file stereo_avoid_sim.c.
References avoid_navigation_data, counter, foo, heading, NormAngleRad, FloatEulers::psi, run_avoid_navigation_onvision(), stateGetNedToBodyEulers_f(), stateGetPositionEnu_f(), and AvoidNavigationStruct::stereo_bin.
stereo_avoid_start()
void stereo_avoid_start (void)
Definition at line 112 of file stereo_avoid_sim.c.
stereo_avoid_stop()
void stereo_avoid_stop (void)
Definition at line 117 of file stereo_avoid_sim.c.