Paparazzi UAS: sw/airborne/arch/stm32/mcu_arch.c File Reference
mcu_arch.c File Reference
STM32 architecture
stm32 arch dependant microcontroller initialisation functions.
#include "mcu.h"
#include <BOARD_CONFIG>
#include <inttypes.h>
#include <libopencm3/stm32/gpio.h>
#include <libopencm3/stm32/rcc.h>
#include <libopencm3/stm32/timer.h>
#include <libopencm3/stm32/flash.h>
#include <libopencm3/cm3/scb.h>
#include <libopencm3/stm32/rtc.h>
#include <libopencm3/stm32/pwr.h>
#include "std.h"
Functions
void mcu_arch_init (void)
Initialize the specific archittecture functions.
uint32_t timer_get_frequency (uint32_t timer_peripheral)
Get Timer clock frequency (before prescaling) Only valid if using the internal clock for the timer.
Detailed Description
stm32 arch dependant microcontroller initialisation functions.
Definition in file mcu_arch.c.
Function Documentation
mcu_arch_init()
void mcu_arch_init (void)
Initialize the specific archittecture functions.
Definition at line 213 of file mcu_arch.c.
References foo, and PRINT_CONFIG_MSG().
timer_get_frequency()
uint32_t timer_get_frequency (uint32_t timer_peripheral)
Get Timer clock frequency (before prescaling) Only valid if using the internal clock for the timer.
Currently implemented for STM32F1x and STM32F405xx/407xx STM32F415xx/417xx. Not valid for STM32F42xxx and STM32F43xxx.
Parameters
[in] timer_peripheral Unsigned int32. Timer register address base
Returns
Unsigned int32. Timer base frequency
Definition at line 311 of file mcu_arch.c.
References foo.
Referenced by adc_init_rcc(), ppm_arch_init(), pwm_input_set_timer(), and set_servo_timer().