Paparazzi UAS: sw/airborne/arch/stm32/mcu_periph/can_arch.h File Reference
can_arch.h File Reference
STM32 architecture
Handling of CAN hardware for STM32.
Functions
void can_hw_init (void)
void can_event (void)
Detailed Description
Handling of CAN hardware for STM32.
Definition in file can_arch.h.
Function Documentation
can_event()
void can_event (void)
Definition at line 250 of file can_arch.c.
References can_arch_periph::addr, can1_arch_s, CAN_NB_CALLBACKS_MAX, foo, can_arch_periph::new_rxframe, and can_arch_periph::rxframe.
can_hw_init()
void can_hw_init (void)
Definition at line 71 of file can_arch.c.
References can1_arch_s, can_init(), can_arch_periph::can_initialized, can_start(), can_arch_periph::canport, foo, GPIO8, GPIO9, GPIO_AF9, gpio_set(), GPIOB, NVIC_CAN1_RX_IRQ_PRIO, and NVIC_USB_LP_CAN_RX0_IRQ_PRIO.
Referenced by can_init().