Paparazzi UAS: sw/airborne/arch/stm32/mcu_periph/sys_time_arch.h File Reference
sys_time_arch.h File Reference
STM32 architecture
STM32 timing functions.
#include "mcu_periph/sys_time.h"
#include <libopencm3/stm32/gpio.h>
#include <libopencm3/stm32/rcc.h>
#include <libopencm3/cm3/systick.h>
#include "std.h"
Functions
static uint32_t get_sys_time_usec (void)
Get the time in microseconds since startup.
static uint32_t get_sys_time_usec100 (void)
Get the time in 100microseconds since startup.
static uint32_t get_sys_time_msec (void)
Get the time in milliseconds since startup.
Detailed Description
STM32 timing functions.
Definition in file sys_time_arch.h.
Function Documentation
get_sys_time_msec()
static uint32_t get_sys_time_msec (void) inline static
Get the time in milliseconds since startup.
Returns
milliseconds since startup as uint32_t
Definition at line 70 of file sys_time_arch.h.
References foo, msec_of_cpu_ticks(), sys_time::nb_sec, and sys_time::nb_sec_rem.
get_sys_time_usec()
static uint32_t get_sys_time_usec (void) inline static
Get the time in microseconds since startup.
WARNING: overflows after 70min!
Returns
microseconds since startup as uint32_t
Definition at line 47 of file sys_time_arch.h.
References foo, sys_time::nb_sec, sys_time::nb_sec_rem, and usec_of_cpu_ticks().
get_sys_time_usec100()
static uint32_t get_sys_time_usec100 (void) inline static
Get the time in 100microseconds since startup.
WARNING: overflows after 7000min!
Returns
100microseconds since startup as uint32_t
Definition at line 59 of file sys_time_arch.h.
References foo, sys_time::nb_sec, sys_time::nb_sec_rem, and usec_of_cpu_ticks().