Paparazzi UAS: sw/airborne/arch/stm32/mcu_periph/rng_arch.c File Reference
rng_arch.c File Reference
#include "mcu_periph/rng.h"
#include <libopencm3/stm32/rcc.h>
#include <libopencm3/stm32/rng.h>
Functions
void rng_init (void)
void rng_deinit (void)
bool rng_get (uint32_t *rand_nr)
uint32_t rng_wait_and_get (void)
Variables
uint32_t last
Function Documentation
void rng_deinit (void)
Definition at line 40 of file rng_arch.c.
References TRNGStop().
bool rng_get (uint32_t * rand_nr)
Definition at line 47 of file rng_arch.c.
References last, TRNGClearErrors(), and TRNGGenerate().
void rng_init (void)
Definition at line 33 of file rng_arch.c.
References last, rng_wait_and_get(), and TRNGStart().
uint32_t rng_wait_and_get (void)
Definition at line 61 of file rng_arch.c.
References last, and TRNGGenerate().
Variable Documentation
uint32_t last
Definition at line 31 of file rng_arch.c.
Referenced by drop_ball(), rng_get(), rng_init(), rng_wait_and_get(), TRIG_ISR(), UpdateSensorLatency(), and UpdateSensorLatency_Single().