Paparazzi UAS: sw/airborne/arch/stm32/uart_tunnel.c File Reference
uart_tunnel.c File Reference
#include <BOARD_CONFIG>
#include "mcu.h"
#include "mcu_periph/sys_time.h"
#include "mcu_periph/gpio.h"
#include "led.h"
Macros
#define A_PORT GPIOA
#define A_RX_PIN GPIO10
#define A_RX_PORT A_PORT
#define A_TX_PIN GPIO9
#define A_TX_PORT A_PORT
#define B_PORT GPIOA
#define B_RX_PIN GPIO3
#define B_RX_PORT B_PORT
#define B_TX_PIN GPIO2
#define B_TX_PORT B_PORT
Functions
static void main_periodic (void)
static void main_event (void)
void Delay (volatile uint32_t nCount)
int main (void)
Macro Definition Documentation
#define A_PORT GPIOA
Definition at line 29 of file uart_tunnel.c.
#define A_RX_PIN GPIO10
Definition at line 30 of file uart_tunnel.c.
Referenced by main(), and main_event().
#define A_RX_PORT A_PORT
Definition at line 31 of file uart_tunnel.c.
Referenced by main(), and main_event().
#define A_TX_PIN GPIO9
Definition at line 32 of file uart_tunnel.c.
Referenced by main(), and main_event().
#define A_TX_PORT A_PORT
Definition at line 33 of file uart_tunnel.c.
Referenced by main(), and main_event().
#define B_PORT GPIOA
Definition at line 36 of file uart_tunnel.c.
#define B_RX_PIN GPIO3
Definition at line 37 of file uart_tunnel.c.
Referenced by main(), and main_event().
#define B_RX_PORT B_PORT
Definition at line 38 of file uart_tunnel.c.
Referenced by main(), and main_event().
#define B_TX_PIN GPIO2
Definition at line 39 of file uart_tunnel.c.
Referenced by main(), and main_event().
#define B_TX_PORT B_PORT
Definition at line 40 of file uart_tunnel.c.
Referenced by main(), and main_event().
Function Documentation
void Delay (volatile uint32_t nCount)
Definition at line 46 of file uart_tunnel.c.
int main (void)
Definition at line 51 of file uart_tunnel.c.
References A_RX_PIN, A_RX_PORT, A_TX_PIN, A_TX_PORT, B_RX_PIN, B_RX_PORT, B_TX_PIN, B_TX_PORT, gpio_clear(), gpio_setup_input_pullup(), gpio_setup_output(), main_event(), main_periodic(), mcu_init(), sys_time_check_and_ack_timer(), and sys_time_register_timer().
static void main_event (void) inline static
Definition at line 85 of file uart_tunnel.c.
References A_RX_PIN, A_RX_PORT, A_TX_PIN, A_TX_PORT, B_RX_PIN, B_RX_PORT, B_TX_PIN, B_TX_PORT, foo, gpio_clear(), gpio_get(), gpio_set(), LED_OFF, and LED_ON.
Referenced by main(), nps_autopilot_run_step(), and thd_ap().
static void main_periodic (void) inline static
Definition at line 80 of file uart_tunnel.c.
References LED_PERIODIC.
Referenced by main().