Paparazzi UAS: gpio_ext_functions Struct Reference
gpio_ext_functions Struct Reference
#include <gpio_ext_common.h>
Data Fields
void(* setup_output)(uint32_t port, uint32_t gpios)
void(* setup_input)(uint32_t port, uint32_t gpios)
uint32_t(* get)(uint32_t port, uint32_t gpios)
void(* set)(uint32_t port, uint32_t gpios)
void(* clear)(uint32_t port, uint32_t gpios)
void(* toggle)(uint32_t port, uint32_t gpios)
Detailed Description
Definition at line 34 of file gpio_ext_common.h.
Field Documentation
clear
void(* gpio_ext_functions::clear) (uint32_t port, uint32_t gpios)
Definition at line 39 of file gpio_ext_common.h.
Referenced by __wrap_gpio_clear().
get
uint32_t(* gpio_ext_functions::get) (uint32_t port, uint32_t gpios)
Definition at line 37 of file gpio_ext_common.h.
Referenced by __wrap_gpio_get().
set
void(* gpio_ext_functions::set) (uint32_t port, uint32_t gpios)
Definition at line 38 of file gpio_ext_common.h.
Referenced by __wrap_gpio_set().
setup_input
void(* gpio_ext_functions::setup_input) (uint32_t port, uint32_t gpios)
Definition at line 36 of file gpio_ext_common.h.
Referenced by __wrap_gpio_setup_input().
setup_output
void(* gpio_ext_functions::setup_output) (uint32_t port, uint32_t gpios)
Definition at line 35 of file gpio_ext_common.h.
Referenced by __wrap_gpio_setup_output().
toggle
void(* gpio_ext_functions::toggle) (uint32_t port, uint32_t gpios)
Definition at line 40 of file gpio_ext_common.h.
Referenced by __wrap_gpio_toggle().
The documentation for this struct was generated from the following file:
sw/airborne/modules/gpio_ext/gpio_ext_common.h