Paparazzi UAS: sw/airborne/modules/switching/switch_uart.h File Reference
switch_uart.h File Reference
#include "std.h"
Macros
#define switch_uart_SwitchUartChannel(X) ({switch_uart_channel=X;drop_ball(switch_uart_channel); false;})
Functions
void drop_ball (uint8_t number)
void periodic_switch_uart (void)
Variables
uint8_t switch_uart_channel
uint8_t switch_uart_status
Detailed Description
Author
Freek van Tienen Module for dropping balls using UART
Definition in file switch_uart.h.
Macro Definition Documentation
switch_uart_SwitchUartChannel
#define switch_uart_SwitchUartChannel (X) ({switch_uart_channel=X;drop_ball(switch_uart_channel); false;})
Definition at line 31 of file switch_uart.h.
Function Documentation
drop_ball()
void drop_ball (uint8_t number) extern
Definition at line 44 of file switch_uart.c.
References drop_string, DROP_STRINGLEN, foo, last, and uart_put_byte().
periodic_switch_uart()
void periodic_switch_uart (void) extern
Definition at line 36 of file switch_uart.c.
References foo, switch_uart_status, uart_char_available(), and uart_getch().
Variable Documentation
switch_uart_channel
uint8_t switch_uart_channel extern
Definition at line 29 of file switch_uart.c.
switch_uart_status
uint8_t switch_uart_status extern
Definition at line 30 of file switch_uart.c.
Referenced by periodic_switch_uart().