Paparazzi UAS: sw/airborne/modules/system_identification/sys_id_auto_doublets.c File Reference
sys_id_auto_doublets.c File Reference
#include "std.h"
#include "modules/system_identification/sys_id_auto_doublets.h"
#include "modules/system_identification/sys_id_doublet.h"
#include "modules/system_identification/pprz_doublet.h"
#include "mcu_periph/sys_time.h"
#include "generated/airframe.h"
Macros
#define SYS_ID_AUTO_DOUBLETS_TIME 0.5
#define SYS_ID_AUTO_DOUBLETS_INTERVAL 5.0
#define SYS_ID_AUTO_DOUBLETS_REPEATS 5
Functions
void perform_sys_id_auto_doublets (uint8_t actuator_index)
void sys_id_auto_doublets_on_deactivation (void)
void init_sys_id_auto_doublets (void)
void periodic_sys_id_auto_doublets (void)
void sys_id_auto_doublets_on_activation (uint8_t active)
Variables
uint8_t sys_id_auto_doublets_actuators [SYS_ID_AUTO_DOUBLETS_N_ACTUATORS] = SYS_ID_AUTO_DOUBLETS_ACTUATORS
int16_t sys_id_auto_doublets_amplitude [SYS_ID_AUTO_DOUBLETS_N_ACTUATORS] = SYS_ID_AUTO_DOUBLETS_AMPLITUDE
float sys_id_auto_doublets_time = SYS_ID_AUTO_DOUBLETS_TIME
float sys_id_auto_doublets_interval_time = SYS_ID_AUTO_DOUBLETS_INTERVAL
int8_t sys_id_auto_doublets_n_repeat = SYS_ID_AUTO_DOUBLETS_REPEATS
bool sys_id_auto_doublets_activated = false
uint8_t sys_id_auto_doublets_n_doublets
float sys_id_auto_doublets_start_time_s
float sys_id_auto_doublets_timer
uint8_t sys_id_auto_doublets_counter
Detailed Description
Author
Dennis van Wijngaarden D.C.v.nosp@m.anWi.nosp@m.jngaa.nosp@m.rden.nosp@m.@tude.nosp@m.lft..nosp@m.nl Module that automatically runs a doublet program for the rotating wing drone
Definition in file sys_id_auto_doublets.c.
Macro Definition Documentation
SYS_ID_AUTO_DOUBLETS_INTERVAL
#define SYS_ID_AUTO_DOUBLETS_INTERVAL 5.0
Definition at line 53 of file sys_id_auto_doublets.c.
SYS_ID_AUTO_DOUBLETS_REPEATS
#define SYS_ID_AUTO_DOUBLETS_REPEATS 5
Definition at line 57 of file sys_id_auto_doublets.c.
SYS_ID_AUTO_DOUBLETS_TIME
#define SYS_ID_AUTO_DOUBLETS_TIME 0.5
Definition at line 49 of file sys_id_auto_doublets.c.
Function Documentation
init_sys_id_auto_doublets()
void init_sys_id_auto_doublets (void)
Definition at line 79 of file sys_id_auto_doublets.c.
References foo, sys_id_auto_doublets_counter, sys_id_auto_doublets_n_doublets, sys_id_auto_doublets_n_repeat, sys_id_auto_doublets_start_time_s, and sys_id_auto_doublets_timer.
perform_sys_id_auto_doublets()
void perform_sys_id_auto_doublets (uint8_t actuator_index) inline
Definition at line 119 of file sys_id_auto_doublets.c.
References doublet_amplitude, doublet_length_s, foo, sys_id_auto_doublets_actuators, sys_id_auto_doublets_amplitude, sys_id_auto_doublets_time, sys_id_doublet_activate_handler(), and sys_id_doublet_axis_handler().
Referenced by periodic_sys_id_auto_doublets(), and sys_id_auto_doublets_on_activation().
periodic_sys_id_auto_doublets()
void periodic_sys_id_auto_doublets (void)
Definition at line 87 of file sys_id_auto_doublets.c.
References foo, get_sys_time_float(), perform_sys_id_auto_doublets(), sys_id_auto_doublets_activated, sys_id_auto_doublets_counter, sys_id_auto_doublets_interval_time, sys_id_auto_doublets_n_doublets, sys_id_auto_doublets_n_repeat, sys_id_auto_doublets_on_deactivation(), sys_id_auto_doublets_start_time_s, and sys_id_auto_doublets_timer.
sys_id_auto_doublets_on_activation()
void sys_id_auto_doublets_on_activation (uint8_t active)
Definition at line 135 of file sys_id_auto_doublets.c.
References get_sys_time_float(), perform_sys_id_auto_doublets(), sys_id_auto_doublets_activated, sys_id_auto_doublets_on_deactivation(), sys_id_auto_doublets_start_time_s, and sys_id_auto_doublets_timer.
sys_id_auto_doublets_on_deactivation()
void sys_id_auto_doublets_on_deactivation (void) inline
Definition at line 159 of file sys_id_auto_doublets.c.
References doublet_amplitude, sys_id_auto_doublets_activated, sys_id_auto_doublets_counter, sys_id_auto_doublets_timer, and sys_id_doublet_activate_handler().
Referenced by periodic_sys_id_auto_doublets(), and sys_id_auto_doublets_on_activation().
Variable Documentation
sys_id_auto_doublets_activated
bool sys_id_auto_doublets_activated = false
Definition at line 67 of file sys_id_auto_doublets.c.
Referenced by periodic_sys_id_auto_doublets(), sys_id_auto_doublets_on_activation(), and sys_id_auto_doublets_on_deactivation().
sys_id_auto_doublets_actuators
uint8_t sys_id_auto_doublets_actuators[SYS_ID_AUTO_DOUBLETS_N_ACTUATORS] = SYS_ID_AUTO_DOUBLETS_ACTUATORS
Definition at line 60 of file sys_id_auto_doublets.c.
Referenced by perform_sys_id_auto_doublets().
sys_id_auto_doublets_amplitude
int16_t sys_id_auto_doublets_amplitude[SYS_ID_AUTO_DOUBLETS_N_ACTUATORS] = SYS_ID_AUTO_DOUBLETS_AMPLITUDE
Definition at line 61 of file sys_id_auto_doublets.c.
Referenced by perform_sys_id_auto_doublets().
sys_id_auto_doublets_counter
uint8_t sys_id_auto_doublets_counter
Definition at line 74 of file sys_id_auto_doublets.c.
Referenced by init_sys_id_auto_doublets(), periodic_sys_id_auto_doublets(), and sys_id_auto_doublets_on_deactivation().
sys_id_auto_doublets_interval_time
float sys_id_auto_doublets_interval_time = SYS_ID_AUTO_DOUBLETS_INTERVAL
Definition at line 64 of file sys_id_auto_doublets.c.
Referenced by periodic_sys_id_auto_doublets().
sys_id_auto_doublets_n_doublets
uint8_t sys_id_auto_doublets_n_doublets
Definition at line 70 of file sys_id_auto_doublets.c.
Referenced by init_sys_id_auto_doublets(), and periodic_sys_id_auto_doublets().
sys_id_auto_doublets_n_repeat
int8_t sys_id_auto_doublets_n_repeat = SYS_ID_AUTO_DOUBLETS_REPEATS
Definition at line 65 of file sys_id_auto_doublets.c.
Referenced by init_sys_id_auto_doublets(), and periodic_sys_id_auto_doublets().
sys_id_auto_doublets_start_time_s
float sys_id_auto_doublets_start_time_s
Definition at line 72 of file sys_id_auto_doublets.c.
Referenced by init_sys_id_auto_doublets(), periodic_sys_id_auto_doublets(), and sys_id_auto_doublets_on_activation().
sys_id_auto_doublets_time
float sys_id_auto_doublets_time = SYS_ID_AUTO_DOUBLETS_TIME
Definition at line 63 of file sys_id_auto_doublets.c.
Referenced by perform_sys_id_auto_doublets().
sys_id_auto_doublets_timer
float sys_id_auto_doublets_timer
Definition at line 73 of file sys_id_auto_doublets.c.
Referenced by init_sys_id_auto_doublets(), periodic_sys_id_auto_doublets(), sys_id_auto_doublets_on_activation(), and sys_id_auto_doublets_on_deactivation().