Paparazzi UAS: sw/airborne/modules/system_identification/sys_id_wave.h File Reference
sys_id_wave.h File Reference
#include "paparazzi.h"
Functions
void sys_id_wave_init (void)
void sys_id_wave_run (void)
void sys_id_wave_axis_handler (uint8_t axis)
uint8_t sys_id_wave_running (void)
void sys_id_wave_frequency_hz_set (float frequency_hz_set)
void sys_id_wave_lag_rad_set (float lag_rad_set)
void sys_id_wave_activate_handler (uint8_t activate)
void sys_id_wave_add_values (bool motors_on, bool override_on, pprz_t in_cmd[])
Variables
uint8_t wave_active
uint8_t wave_axis
pprz_t wave_amplitude
float frequency_hz_
float lag_rad_
Detailed Description
Author
Alessandro Collicelli System excitation pure sine wave
This is the module implementation for a sine wave input. Use sys_id_wave by adding the module to your airframe file and adding the following line to the top of the <command_laws> section of your airframe file:
<call fun="sys_id_wave_add_values(autopilot_get_motors_on(),FALSE,values)">
In the GCS you can then start and stop the wave, change wave frequency. Documentation of the specific options can be found in the module xml file.
Definition in file sys_id_wave.h.
Function Documentation
sys_id_wave_activate_handler()
void sys_id_wave_activate_handler (uint8_t activate) extern
Definition at line 100 of file sys_id_wave.c.
References foo, frequency_hz_, get_sys_time_float(), lag_rad_, start_wave(), stop_wave(), wave_active, wave_init(), and wave_s.
sys_id_wave_add_values()
void sys_id_wave_add_values (bool motors_on, bool override_on, pprz_t in_cmd[]) extern
Definition at line 159 of file sys_id_wave.c.
References ACTIVE_WAVE_AXES, current_wave_values, foo, MAX_PPRZ, and WAVE_NB_AXES.
sys_id_wave_axis_handler()
void sys_id_wave_axis_handler (uint8_t axis) extern
Definition at line 110 of file sys_id_wave.c.
References foo, wave_axis, and WAVE_NB_AXES.
sys_id_wave_frequency_hz_set()
void sys_id_wave_frequency_hz_set (float frequency_hz_set) extern
Definition at line 123 of file sys_id_wave.c.
References foo, frequency_hz_, get_sys_time_float(), lag_rad_, wave_init(), and wave_s.
sys_id_wave_init()
void sys_id_wave_init (void) extern
Definition at line 136 of file sys_id_wave.c.
References DefaultPeriodic, foo, frequency_hz_, get_sys_time_float(), lag_rad_, register_periodic_telemetry(), send_wave(), set_current_wave_values(), wave_init(), and wave_s.
sys_id_wave_lag_rad_set()
void sys_id_wave_lag_rad_set (float lag_rad_set) extern
Definition at line 129 of file sys_id_wave.c.
References foo, frequency_hz_, get_sys_time_float(), lag_rad_, wave_init(), and wave_s.
sys_id_wave_run()
void sys_id_wave_run (void) extern
Definition at line 144 of file sys_id_wave.c.
References get_sys_time_float(), set_current_wave_values(), stop_wave(), wave_active, wave_is_running(), wave_s, and wave_update().
sys_id_wave_running()
uint8_t sys_id_wave_running (void) extern
Definition at line 118 of file sys_id_wave.c.
References wave_active.
Variable Documentation
frequency_hz_
float frequency_hz_ extern
Definition at line 60 of file sys_id_wave.c.
Referenced by sys_id_wave_activate_handler(), sys_id_wave_frequency_hz_set(), sys_id_wave_init(), and sys_id_wave_lag_rad_set().
lag_rad_
float lag_rad_ extern
Definition at line 61 of file sys_id_wave.c.
Referenced by sys_id_wave_activate_handler(), sys_id_wave_frequency_hz_set(), sys_id_wave_init(), and sys_id_wave_lag_rad_set().
wave_active
uint8_t wave_active extern
Definition at line 57 of file sys_id_wave.c.
Referenced by send_wave(), set_current_wave_values(), start_wave(), stop_wave(), sys_id_wave_activate_handler(), sys_id_wave_run(), and sys_id_wave_running().
wave_amplitude
pprz_t wave_amplitude extern
Definition at line 59 of file sys_id_wave.c.
Referenced by send_wave(), and set_current_wave_values().
wave_axis
uint8_t wave_axis extern
Definition at line 47 of file sys_id_wave.h.
Referenced by send_wave(), set_current_wave_values(), and sys_id_wave_axis_handler().