Paparazzi UAS: sw/airborne/modules/core/sys_mon.h File Reference
sys_mon.h File Reference
System monitoring common header return cpu load, average exec time, ...
#include "std.h"
Functions
void init_sysmon (void)
Init system monitoring.
void periodic_report_sysmon (void)
Report system status.
void periodic_sysmon (void)
Analyse periodic calls Should be run at the highest frequency.
void event_sysmon (void)
Analyse event calls.
Detailed Description
System monitoring common header return cpu load, average exec time, ...
System monitoring return cpu load, average exec time, ...
Definition in file sys_mon.h.
Function Documentation
event_sysmon()
void event_sysmon (void)
Analyse event calls.
Store event calls total time and number of calls between two periodic calls
Definition at line 65 of file rtos_mon.c.
References event_timer, foo, min_time_event, n_event, sum_time_event, SysTimeTimer, and SysTimeTimerStart.
init_sysmon()
void init_sysmon (void)
Init system monitoring.
Definition at line 32 of file rtos_mon.c.
References SysMon::cpu_load, SysMon::cpu_time, SysMon::event_number, foo, min_time_event, n_event, n_periodic, SysMon::periodic_cycle, SysMon::periodic_cycle_max, SysMon::periodic_cycle_min, SysMon::periodic_time, SysMon::periodic_time_max, SysMon::periodic_time_min, periodic_timer, rtos_mon, rtos_mon_init_arch(), sum_cycle_periodic, sum_n_event, sum_time_event, sum_time_periodic, and sys_mon.
periodic_report_sysmon()
void periodic_report_sysmon (void)
Report system status.
Report system status at low frequency
Definition at line 43 of file rtos_mon.c.
References rtos_monitoring::core_free_memory, SysMon::cpu_load, rtos_monitoring::cpu_load, SysMon::cpu_time, rtos_monitoring::cpu_time, DefaultChannel, DefaultDevice, SysMon::event_number, foo, get_sys_time_float(), rtos_monitoring::heap_fragments, rtos_monitoring::heap_free_memory, rtos_monitoring::heap_largest, n_periodic, SysMon::periodic_cycle, SysMon::periodic_cycle_max, SysMon::periodic_cycle_min, SysMon::periodic_time, SysMon::periodic_time_max, SysMon::periodic_time_min, rtos_mon, rtos_mon_periodic_arch(), sum_cycle_periodic, sum_n_event, sum_time_periodic, sys_mon, and rtos_monitoring::thread_counter.
periodic_sysmon()
void periodic_sysmon (void)
Analyse periodic calls Should be run at the highest frequency.
Estimate periodic task cycle time
Definition at line 63 of file rtos_mon.c.
References foo, min_time_event, n_event, n_periodic, periodic_cycle, SysMon::periodic_cycle_max, SysMon::periodic_cycle_min, SysMon::periodic_time_max, SysMon::periodic_time_min, periodic_timer, sum_cycle_periodic, sum_n_event, sum_time_event, sum_time_periodic, sys_mon, SysTimeTimer, and SysTimeTimerStart.