Paparazzi UAS: sw/airborne/modules/system_identification/sys_id_chirp.h File Reference
sys_id_chirp.h File Reference
#include "paparazzi.h"
Functions
void sys_id_chirp_init (void)
void sys_id_chirp_run (void)
void sys_id_chirp_activate_handler (uint8_t activate)
void sys_id_chirp_axis_handler (uint8_t axis)
void sys_id_chirp_fstart_handler (float fstart)
void sys_id_chirp_fstop_handler (float fstop)
void sys_id_chirp_add_values (bool motors_on, bool override_on, pprz_t in_cmd[])
Variables
uint8_t chirp_active
pprz_t chirp_amplitude
float chirp_noise_stdv_onaxis_ratio
float chirp_noise_stdv_offaxis
float chirp_fstart_hz
float chirp_fstop_hz
float chirp_length_s
uint8_t chirp_axis
Function Documentation
void sys_id_chirp_activate_handler (uint8_t activate)
Definition at line 122 of file sys_id_chirp.c.
References chirp, chirp_active, CHIRP_EXPONENTIAL, CHIRP_FADEIN, chirp_fstart_hz, chirp_fstop_hz, chirp_init(), chirp_length_s, get_sys_time_float(), start_chirp(), and stop_chirp().
void sys_id_chirp_add_values (bool motors_on, bool override_on, pprz_t in_cmd[])
Definition at line 194 of file sys_id_chirp.c.
References ACTIVE_CHIRP_AXES, CHIRP_NB_AXES, current_chirp_values, and MAX_PPRZ.
void sys_id_chirp_axis_handler (uint8_t axis)
Definition at line 134 of file sys_id_chirp.c.
References chirp_axis, and CHIRP_NB_AXES.
void sys_id_chirp_fstart_handler (float fstart)
Definition at line 141 of file sys_id_chirp.c.
References chirp_fstart_hz, and chirp_fstop_hz.
void sys_id_chirp_fstop_handler (float fstop)
Definition at line 148 of file sys_id_chirp.c.
References chirp_fstart_hz, and chirp_fstop_hz.
void sys_id_chirp_init (void)
Definition at line 157 of file sys_id_chirp.c.
References chirp, CHIRP_EXPONENTIAL, CHIRP_FADEIN, chirp_fstart_hz, chirp_fstop_hz, chirp_init(), chirp_length_s, CHIRP_NB_AXES, current_chirp_values, DefaultPeriodic, filters, get_sys_time_float(), init_first_order_low_pass(), init_random(), register_periodic_telemetry(), send_chirp(), and set_current_chirp_values().
void sys_id_chirp_run (void)
Definition at line 178 of file sys_id_chirp.c.
References chirp, chirp_active, chirp_is_running(), chirp_update(), get_sys_time_float(), set_current_chirp_values(), and stop_chirp().
Variable Documentation
uint8_t chirp_active
Definition at line 60 of file sys_id_chirp.c.
Referenced by send_chirp(), set_current_chirp_values(), start_chirp(), stop_chirp(), sys_id_chirp_activate_handler(), and sys_id_chirp_run().
pprz_t chirp_amplitude
Definition at line 62 of file sys_id_chirp.c.
Referenced by send_chirp(), and set_current_chirp_values().
uint8_t chirp_axis
Definition at line 61 of file sys_id_chirp.c.
Referenced by send_chirp(), set_current_chirp_values(), and sys_id_chirp_axis_handler().
float chirp_fstart_hz
Definition at line 65 of file sys_id_chirp.c.
Referenced by send_chirp(), sys_id_chirp_activate_handler(), sys_id_chirp_fstart_handler(), sys_id_chirp_fstop_handler(), and sys_id_chirp_init().
float chirp_fstop_hz
Definition at line 66 of file sys_id_chirp.c.
Referenced by send_chirp(), sys_id_chirp_activate_handler(), sys_id_chirp_fstart_handler(), sys_id_chirp_fstop_handler(), and sys_id_chirp_init().
float chirp_length_s
Definition at line 67 of file sys_id_chirp.c.
Referenced by sys_id_chirp_activate_handler(), and sys_id_chirp_init().
float chirp_noise_stdv_offaxis
Definition at line 64 of file sys_id_chirp.c.
Referenced by send_chirp(), and set_current_chirp_values().
float chirp_noise_stdv_onaxis_ratio
Definition at line 63 of file sys_id_chirp.c.
Referenced by send_chirp(), and set_current_chirp_values().