Paparazzi UAS: sw/airborne/modules/system_identification/sys_id_doublet.h File Reference
sys_id_doublet.h File Reference
#include "paparazzi.h"
Functions
void sys_id_doublet_init (void)
void sys_id_doublet_run (void)
void sys_id_doublet_activate_handler (uint8_t activate)
void sys_id_doublet_axis_handler (uint8_t axis)
void sys_id_doublet_mod_handler (uint8_t mode)
uint8_t sys_id_doublet_running (void)
void sys_id_doublet_add_values (bool motors_on, bool override_on, pprz_t in_cmd[])
Variables
uint8_t doublet_active
pprz_t doublet_amplitude
float doublet_length_s
float doublet_extra_waiting_time_s
uint8_t doublet_axis
uint8_t doublet_mode
Function Documentation
sys_id_doublet_activate_handler()
void sys_id_doublet_activate_handler (uint8_t activate) extern
Definition at line 111 of file sys_id_doublet.c.
References doublet, doublet_active, doublet_extra_waiting_time_s, doublet_init(), doublet_length_s, doublet_mode, foo, get_sys_time_float(), radio_control, start_doublet(), stop_doublet(), and RadioControl::values.
Referenced by perform_sys_id_auto_doublets(), sys_id_auto_doublets_on_deactivation(), and sys_id_doublet_run().
sys_id_doublet_add_values()
void sys_id_doublet_add_values (bool motors_on, bool override_on, pprz_t in_cmd[]) extern
sys_id_doublet_axis_handler()
void sys_id_doublet_axis_handler (uint8_t axis) extern
Definition at line 129 of file sys_id_doublet.c.
References doublet_axis, foo, and SYS_ID_DOUBLET_NB_AXES.
Referenced by perform_sys_id_auto_doublets().
sys_id_doublet_init()
void sys_id_doublet_init (void) extern
Definition at line 140 of file sys_id_doublet.c.
References current_doublet_values, DefaultPeriodic, doublet, doublet_extra_waiting_time_s, doublet_init(), doublet_length_s, doublet_mode, foo, get_sys_time_float(), register_periodic_telemetry(), send_doublet(), set_current_doublet_values(), and SYS_ID_DOUBLET_NB_AXES.
sys_id_doublet_mod_handler()
void sys_id_doublet_mod_handler (uint8_t mode) extern
Definition at line 136 of file sys_id_doublet.c.
References doublet_mode, and mode.
sys_id_doublet_run()
void sys_id_doublet_run (void) extern
Definition at line 152 of file sys_id_doublet.c.
References doublet, doublet_active, doublet_is_running(), doublet_update(), foo, get_sys_time_float(), radio_control, set_current_doublet_values(), stop_doublet(), sys_id_doublet_activate_handler(), and RadioControl::values.
sys_id_doublet_running()
uint8_t sys_id_doublet_running (void) extern
Definition at line 107 of file sys_id_doublet.c.
References doublet_active.
Variable Documentation
doublet_active
uint8_t doublet_active extern
Definition at line 59 of file sys_id_doublet.c.
Referenced by send_doublet(), set_current_doublet_values(), start_doublet(), stop_doublet(), sys_id_doublet_activate_handler(), sys_id_doublet_run(), and sys_id_doublet_running().
doublet_amplitude
pprz_t doublet_amplitude extern
Definition at line 64 of file sys_id_doublet.c.
Referenced by perform_sys_id_auto_doublets(), send_doublet(), set_current_doublet_values(), and sys_id_auto_doublets_on_deactivation().
doublet_axis
uint8_t doublet_axis extern
Definition at line 62 of file sys_id_doublet.c.
Referenced by send_doublet(), set_current_doublet_values(), and sys_id_doublet_axis_handler().
doublet_extra_waiting_time_s
float doublet_extra_waiting_time_s extern
Definition at line 66 of file sys_id_doublet.c.
Referenced by sys_id_doublet_activate_handler(), and sys_id_doublet_init().
doublet_length_s
float doublet_length_s extern
Definition at line 65 of file sys_id_doublet.c.
Referenced by perform_sys_id_auto_doublets(), sys_id_doublet_activate_handler(), and sys_id_doublet_init().
doublet_mode
uint8_t doublet_mode extern
Definition at line 60 of file sys_id_doublet.c.
Referenced by send_doublet(), sys_id_doublet_activate_handler(), sys_id_doublet_init(), and sys_id_doublet_mod_handler().