Paparazzi UAS: sw/airborne/modules/core/sys_mon_rtos.h File Reference
sys_mon_rtos.h File Reference
System monitoring for RTOS targets return cpu load, average exec time, ...
#include "core/sys_mon.h"
Data Structures
struct rtos_monitoring
Macros
#define RTOS_MON_MAX_THREADS 20
#define RTOS_MON_NAME_LEN 5
#define RTOS_MON_THREAD_NAMES (RTOS_MON_MAX_THREADS * RTOS_MON_NAME_LEN)
Functions
void rtos_mon_init_arch (void)
void rtos_mon_periodic_arch (void)
Variables
struct rtos_monitoring rtos_mon
Detailed Description
System monitoring for RTOS targets return cpu load, average exec time, ...
Definition in file sys_mon_rtos.h.
Data Structure Documentation
rtos_monitoring
struct rtos_monitoring
Definition at line 46 of file sys_mon_rtos.h.
Data Fields
uint32_t core_free_memory core free memory in bytes
uint8_t cpu_load global CPU/MCU load in %
float cpu_time
uint32_t heap_fragments Number of fragments in the heap.
uint32_t heap_free_memory Total fragmented free memory in the heap.
uint32_t heap_largest Largest free block in the heap.
uint8_t thread_counter number of threads
uint16_t thread_free_stack[RTOS_MON_MAX_THREADS] individual thread free stack in bytes
uint16_t thread_load[RTOS_MON_MAX_THREADS] individual thread load in centi-percent (10*%)
uint8_t thread_name_idx length of the string in thread_names buffer
char thread_names[RTOS_MON_THREAD_NAMES+1] string of thread names / identifiers
Macro Definition Documentation
RTOS_MON_MAX_THREADS
#define RTOS_MON_MAX_THREADS 20
Definition at line 36 of file sys_mon_rtos.h.
RTOS_MON_NAME_LEN
#define RTOS_MON_NAME_LEN 5
Definition at line 40 of file sys_mon_rtos.h.
RTOS_MON_THREAD_NAMES
#define RTOS_MON_THREAD_NAMES (RTOS_MON_MAX_THREADS * RTOS_MON_NAME_LEN)
Definition at line 43 of file sys_mon_rtos.h.
Function Documentation
rtos_mon_init_arch()
void rtos_mon_init_arch (void) extern
Definition at line 162 of file rtos_mon_arch.c.
References foo, and shell_add_entry().
Referenced by init_sysmon().
rtos_mon_periodic_arch()
void rtos_mon_periodic_arch (void) extern
Definition at line 171 of file rtos_mon_arch.c.
References rtos_monitoring::core_free_memory, rtos_monitoring::cpu_load, foo, get_stack_free(), rtos_monitoring::heap_fragments, rtos_monitoring::heap_free_memory, rtos_monitoring::heap_largest, rtos_mon, RTOS_MON_MAX_THREADS, RTOS_MON_NAME_LEN, rtos_monitoring::thread_counter, rtos_monitoring::thread_free_stack, rtos_monitoring::thread_load, rtos_monitoring::thread_name_idx, rtos_monitoring::thread_names, and thread_p_time.
Referenced by periodic_report_sysmon().
Variable Documentation
rtos_mon
struct rtos_monitoring rtos_mon extern
Definition at line 30 of file rtos_mon.c.
Referenced by init_sysmon(), periodic_report_sysmon(), and rtos_mon_periodic_arch().