Paparazzi UAS: sw/airborne/modules/system_identification/sys_id_auto_doublets.h File Reference
sys_id_auto_doublets.h File Reference
#include "std.h"
Functions
void init_sys_id_auto_doublets (void)
void periodic_sys_id_auto_doublets (void)
void sys_id_auto_doublets_on_activation (uint8_t active)
Variables
bool sys_id_auto_doublets_activated
Detailed Description
Author
Dennis van Wijngaarden D.C.v.nosp@m.anWi.nosp@m.jngaa.nosp@m.rden.nosp@m.@tude.nosp@m.lft..nosp@m.nl Module that automatically runs a doublet program for the rotating wing drone
Definition in file sys_id_auto_doublets.h.
Function Documentation
init_sys_id_auto_doublets()
void init_sys_id_auto_doublets (void) extern
Definition at line 79 of file sys_id_auto_doublets.c.
References foo, sys_id_auto_doublets_counter, sys_id_auto_doublets_n_doublets, sys_id_auto_doublets_n_repeat, sys_id_auto_doublets_start_time_s, and sys_id_auto_doublets_timer.
periodic_sys_id_auto_doublets()
void periodic_sys_id_auto_doublets (void) extern
Definition at line 87 of file sys_id_auto_doublets.c.
References foo, get_sys_time_float(), perform_sys_id_auto_doublets(), sys_id_auto_doublets_activated, sys_id_auto_doublets_counter, sys_id_auto_doublets_interval_time, sys_id_auto_doublets_n_doublets, sys_id_auto_doublets_n_repeat, sys_id_auto_doublets_on_deactivation(), sys_id_auto_doublets_start_time_s, and sys_id_auto_doublets_timer.
sys_id_auto_doublets_on_activation()
void sys_id_auto_doublets_on_activation (uint8_t active) extern
Definition at line 135 of file sys_id_auto_doublets.c.
References get_sys_time_float(), perform_sys_id_auto_doublets(), sys_id_auto_doublets_activated, sys_id_auto_doublets_on_deactivation(), sys_id_auto_doublets_start_time_s, and sys_id_auto_doublets_timer.
Variable Documentation
sys_id_auto_doublets_activated
bool sys_id_auto_doublets_activated extern
Definition at line 67 of file sys_id_auto_doublets.c.
Referenced by periodic_sys_id_auto_doublets(), sys_id_auto_doublets_on_activation(), and sys_id_auto_doublets_on_deactivation().