Paparazzi UAS: sw/airborne/modules/system_identification/sys_id_chirp.c File Reference
sys_id_chirp.c File Reference
#include "std.h"
#include "sys_id_chirp.h"
#include "pprz_chirp.h"
#include "modules/datalink/telemetry.h"
#include "generated/airframe.h"
#include "mcu_periph/sys_time.h"
#include "filters/low_pass_filter.h"
#include "math/pprz_random.h"
Macros
#define SYS_ID_CHIRP_AXES {COMMAND_ROLL,COMMAND_PITCH,COMMAND_YAW,COMMAND_THRUST}
#define SYS_ID_CHIRP_ENABLED TRUE
#define SYS_ID_CHIRP_USE_NOISE TRUE
#define SYS_ID_CHIRP_NB_AXES sizeof SYS_ID_ACTIVE_CHIRP_AXES / sizeof SYS_ID_ACTIVE_CHIRP_AXES[0]
Functions
static void set_current_chirp_values (void)
static void send_chirp (struct transport_tx *trans, struct link_device *dev)
static void start_chirp (void)
static void stop_chirp (void)
void sys_id_chirp_activate_handler (uint8_t activate)
uint8_t sys_id_chirp_running (void)
void sys_id_chirp_axis_handler (uint8_t axis)
void sys_id_chirp_fstart_handler (float fstart)
void sys_id_chirp_fstop_handler (float fstop)
void sys_id_chirp_fade_in_activate_handler (uint8_t fade_in)
void sys_id_chirp_exponential_activate_handler (uint8_t exponential)
void sys_id_chirp_init (void)
void sys_id_chirp_run (void)
void sys_id_chirp_add_values (bool UNUSED motors_on, bool UNUSED override_on, pprz_t UNUSED in_cmd[])
Variables
static struct chirp_t chirp
uint8_t chirp_active = FALSE
uint8_t chirp_axis = 0
pprz_t chirp_amplitude = 0
float chirp_noise_stdv_onaxis_ratio = 0.1
float chirp_noise_stdv_offaxis = 200
float chirp_fstart_hz = 1.0f
float chirp_fstop_hz = 5.0f
float chirp_length_s = 20
uint8_t chirp_fade_in = false
uint8_t chirp_exponential = false
static const int8_t SYS_ID_ACTIVE_CHIRP_AXES [] = SYS_ID_CHIRP_AXES
static struct FirstOrderLowPass filters [SYS_ID_CHIRP_NB_AXES]
static pprz_t current_chirp_values [SYS_ID_CHIRP_NB_AXES]
Detailed Description
Author
Joost Meulenbeld System identification chirp
Definition in file sys_id_chirp.c.
Macro Definition Documentation
SYS_ID_CHIRP_AXES
#define SYS_ID_CHIRP_AXES {COMMAND_ROLL,COMMAND_PITCH,COMMAND_YAW,COMMAND_THRUST}
Definition at line 39 of file sys_id_chirp.c.
SYS_ID_CHIRP_ENABLED
#define SYS_ID_CHIRP_ENABLED TRUE
Definition at line 43 of file sys_id_chirp.c.
SYS_ID_CHIRP_NB_AXES
#define SYS_ID_CHIRP_NB_AXES sizeof SYS_ID_ACTIVE_CHIRP_AXES / sizeof SYS_ID_ACTIVE_CHIRP_AXES[0]
Definition at line 79 of file sys_id_chirp.c.
SYS_ID_CHIRP_USE_NOISE
#define SYS_ID_CHIRP_USE_NOISE TRUE
Definition at line 47 of file sys_id_chirp.c.
Function Documentation
send_chirp()
static void send_chirp (struct transport_tx * trans, struct link_device * dev) static
Definition at line 115 of file sys_id_chirp.c.
References chirp, chirp_active, chirp_amplitude, chirp_axis, chirp_exponential, chirp_fade_in, chirp_fstart_hz, chirp_fstop_hz, chirp_noise_stdv_offaxis, chirp_noise_stdv_onaxis_ratio, current_chirp_values, chirp_t::current_frequency_hz, dev, foo, and chirp_t::percentage_done.
Referenced by sys_id_chirp_init().
set_current_chirp_values()
static void set_current_chirp_values (void) static
Definition at line 87 of file sys_id_chirp.c.
References chirp, chirp_active, chirp_amplitude, chirp_axis, chirp_noise_stdv_offaxis, chirp_noise_stdv_onaxis_ratio, current_chirp_values, chirp_t::current_value, filters, foo, rand_gaussian(), SYS_ID_CHIRP_NB_AXES, and update_first_order_low_pass().
Referenced by start_chirp(), stop_chirp(), sys_id_chirp_init(), and sys_id_chirp_run().
start_chirp()
static void start_chirp (void) static
Definition at line 123 of file sys_id_chirp.c.
References chirp, chirp_active, chirp_reset(), get_sys_time_float(), set_current_chirp_values(), and TRUE.
Referenced by sys_id_chirp_activate_handler().
stop_chirp()
static void stop_chirp (void) static
Definition at line 130 of file sys_id_chirp.c.
References chirp, chirp_active, chirp_reset(), FALSE, get_sys_time_float(), and set_current_chirp_values().
Referenced by sys_id_chirp_activate_handler(), and sys_id_chirp_run().
sys_id_chirp_activate_handler()
void sys_id_chirp_activate_handler (uint8_t activate)
Definition at line 137 of file sys_id_chirp.c.
References chirp, chirp_active, chirp_exponential, chirp_fade_in, chirp_fstart_hz, chirp_fstop_hz, chirp_init(), chirp_length_s, foo, get_sys_time_float(), radio_control, start_chirp(), stop_chirp(), and RadioControl::values.
Referenced by sys_id_chirp_run().
sys_id_chirp_add_values()
void sys_id_chirp_add_values (bool UNUSED motors_on, bool UNUSED override_on, pprz_t UNUSED in_cmd[])
Definition at line 251 of file sys_id_chirp.c.
References current_chirp_values, foo, MAX_PPRZ, SYS_ID_ACTIVE_CHIRP_AXES, and SYS_ID_CHIRP_NB_AXES.
sys_id_chirp_axis_handler()
void sys_id_chirp_axis_handler (uint8_t axis) extern
Definition at line 161 of file sys_id_chirp.c.
References chirp_axis, foo, and SYS_ID_CHIRP_NB_AXES.
sys_id_chirp_exponential_activate_handler()
void sys_id_chirp_exponential_activate_handler (uint8_t exponential) extern
Definition at line 187 of file sys_id_chirp.c.
References chirp_exponential, and foo.
sys_id_chirp_fade_in_activate_handler()
void sys_id_chirp_fade_in_activate_handler (uint8_t fade_in) extern
Definition at line 182 of file sys_id_chirp.c.
References chirp_fade_in.
sys_id_chirp_fstart_handler()
void sys_id_chirp_fstart_handler (float fstart) extern
Definition at line 168 of file sys_id_chirp.c.
References chirp_fstart_hz, chirp_fstop_hz, and foo.
sys_id_chirp_fstop_handler()
void sys_id_chirp_fstop_handler (float fstop) extern
Definition at line 175 of file sys_id_chirp.c.
References chirp_fstart_hz, chirp_fstop_hz, and foo.
sys_id_chirp_init()
void sys_id_chirp_init (void)
Definition at line 192 of file sys_id_chirp.c.
References chirp, chirp_exponential, chirp_fade_in, chirp_fstart_hz, chirp_fstop_hz, chirp_init(), chirp_length_s, current_chirp_values, DefaultPeriodic, filters, foo, get_sys_time_float(), init_first_order_low_pass(), init_random(), register_periodic_telemetry(), send_chirp(), set_current_chirp_values(), and SYS_ID_CHIRP_NB_AXES.
sys_id_chirp_run()
void sys_id_chirp_run (void)
Definition at line 213 of file sys_id_chirp.c.
References chirp, chirp_active, chirp_is_running(), chirp_update(), foo, get_sys_time_float(), radio_control, set_current_chirp_values(), stop_chirp(), sys_id_chirp_activate_handler(), and RadioControl::values.
sys_id_chirp_running()
uint8_t sys_id_chirp_running (void)
Definition at line 156 of file sys_id_chirp.c.
References chirp_active.
Variable Documentation
chirp
struct chirp_t chirp static
Definition at line 64 of file sys_id_chirp.c.
Referenced by chirp_init(), chirp_is_running(), chirp_reset(), chirp_update(), send_chirp(), set_current_chirp_values(), start_chirp(), stop_chirp(), sys_id_chirp_activate_handler(), sys_id_chirp_init(), and sys_id_chirp_run().
chirp_active
uint8_t chirp_active = FALSE
Definition at line 65 of file sys_id_chirp.c.
Referenced by send_chirp(), set_current_chirp_values(), start_chirp(), stop_chirp(), sys_id_chirp_activate_handler(), sys_id_chirp_run(), and sys_id_chirp_running().
chirp_amplitude
pprz_t chirp_amplitude = 0
Definition at line 67 of file sys_id_chirp.c.
Referenced by send_chirp(), and set_current_chirp_values().
chirp_axis
uint8_t chirp_axis = 0
Definition at line 66 of file sys_id_chirp.c.
Referenced by send_chirp(), set_current_chirp_values(), and sys_id_chirp_axis_handler().
chirp_exponential
uint8_t chirp_exponential = false
Definition at line 75 of file sys_id_chirp.c.
Referenced by send_chirp(), sys_id_chirp_activate_handler(), sys_id_chirp_exponential_activate_handler(), and sys_id_chirp_init().
chirp_fade_in
uint8_t chirp_fade_in = false
Definition at line 74 of file sys_id_chirp.c.
Referenced by send_chirp(), sys_id_chirp_activate_handler(), sys_id_chirp_fade_in_activate_handler(), and sys_id_chirp_init().
chirp_fstart_hz
float chirp_fstart_hz = 1.0f
Definition at line 70 of file sys_id_chirp.c.
Referenced by send_chirp(), sys_id_chirp_activate_handler(), sys_id_chirp_fstart_handler(), sys_id_chirp_fstop_handler(), and sys_id_chirp_init().
chirp_fstop_hz
float chirp_fstop_hz = 5.0f
Definition at line 71 of file sys_id_chirp.c.
Referenced by send_chirp(), sys_id_chirp_activate_handler(), sys_id_chirp_fstart_handler(), sys_id_chirp_fstop_handler(), and sys_id_chirp_init().
chirp_length_s
float chirp_length_s = 20
Definition at line 72 of file sys_id_chirp.c.
Referenced by sys_id_chirp_activate_handler(), and sys_id_chirp_init().
chirp_noise_stdv_offaxis
float chirp_noise_stdv_offaxis = 200
Definition at line 69 of file sys_id_chirp.c.
Referenced by send_chirp(), and set_current_chirp_values().
chirp_noise_stdv_onaxis_ratio
float chirp_noise_stdv_onaxis_ratio = 0.1
Definition at line 68 of file sys_id_chirp.c.
Referenced by send_chirp(), and set_current_chirp_values().
current_chirp_values
pprz_t current_chirp_values[SYS_ID_CHIRP_NB_AXES] static
Definition at line 85 of file sys_id_chirp.c.
Referenced by send_chirp(), set_current_chirp_values(), sys_id_chirp_add_values(), and sys_id_chirp_init().
filters
struct FirstOrderLowPass filters[SYS_ID_CHIRP_NB_AXES] static
Definition at line 82 of file sys_id_chirp.c.
Referenced by image_labeling(), set_current_chirp_values(), and sys_id_chirp_init().
SYS_ID_ACTIVE_CHIRP_AXES
const int8_t SYS_ID_ACTIVE_CHIRP_AXES[] = SYS_ID_CHIRP_AXES static
Definition at line 78 of file sys_id_chirp.c.
Referenced by sys_id_chirp_add_values().