Paparazzi UAS: sw/airborne/modules/multi/tcas.c File Reference
tcas.c File Reference
Collision avoidance library.
#include "multi/tcas.h"
#include "state.h"
#include "firmwares/fixedwing/nav.h"
#include "generated/flight_plan.h"
#include "modules/datalink/downlink.h"
Macros
#define TCAS_TAU_TA 2*CARROT
#define TCAS_TAU_RA CARROT
#define TCAS_DMOD 10.
#define TCAS_ALIM 15.
#define TCAS_DT_MAX 1500
#define TCAS_HUGE_TAU 100*TCAS_TAU_TA
#define TCAS_IsInside() ((ddh < Square(tcas_dmod) && ddv < Square(2*tcas_alim)) ? 1 : 0)
Functions
void callTCAS (void)
void tcas_init (void)
void parseTcasResolve (uint8_t *buf)
void parseTcasRA (uint8_t *buf)
static enum tcas_resolve tcas_test_direction (uint8_t id)
void tcas_periodic_task_1Hz (void)
void tcas_periodic_task_4Hz (void)
Variables
float tcas_alt_setpoint
float tcas_tau_ta
float tcas_tau_ra
float tcas_dmod
float tcas_alim
uint8_t tcas_status
enum tcas_resolve tcas_resolve
uint8_t tcas_ac_RA
struct tcas_ac_status tcas_acs_status [NB_ACS]
Detailed Description
Collision avoidance library.
Definition in file tcas.c.
Macro Definition Documentation
TCAS_ALIM
#define TCAS_ALIM 15.
Definition at line 56 of file tcas.c.
TCAS_DMOD
#define TCAS_DMOD 10.
Definition at line 52 of file tcas.c.
TCAS_DT_MAX
#define TCAS_DT_MAX 1500
Definition at line 60 of file tcas.c.
TCAS_HUGE_TAU
#define TCAS_HUGE_TAU 100*TCAS_TAU_TA
Definition at line 63 of file tcas.c.
TCAS_IsInside
#define TCAS_IsInside () ((ddh < Square(tcas_dmod) && ddv < Square(2*tcas_alim)) ? 1 : 0)
Definition at line 68 of file tcas.c.
TCAS_TAU_RA
#define TCAS_TAU_RA CARROT
Definition at line 48 of file tcas.c.
TCAS_TAU_TA
#define TCAS_TAU_TA 2*CARROT
Definition at line 44 of file tcas.c.
Function Documentation
callTCAS()
void callTCAS (void)
Definition at line 65 of file tcas.c.
References tcas_alt_setpoint, TCAS_RA, tcas_status, and v_ctl_altitude_setpoint.
Referenced by navigation_task().
parseTcasRA()
void parseTcasRA (uint8_t * buf)
Definition at line 95 of file tcas.c.
References dl_buffer, foo, tcas_ac_status::resolve, tcas_acs_status, and ti_acs_id.
parseTcasResolve()
void parseTcasResolve (uint8_t * buf)
Definition at line 87 of file tcas.c.
References foo, tcas_ac_status::resolve, tcas_acs_status, and ti_acs_id.
tcas_init()
void tcas_init (void)
Definition at line 70 of file tcas.c.
References foo, ground_alt, NB_ACS, RA_NONE, tcas_ac_status::resolve, tcas_ac_status::status, tcas_ac_RA, tcas_acs_status, tcas_alim, TCAS_ALIM, tcas_alt_setpoint, tcas_dmod, TCAS_DMOD, TCAS_NO_ALARM, tcas_status, tcas_tau_ra, TCAS_TAU_RA, tcas_tau_ta, and TCAS_TAU_TA.
tcas_periodic_task_1Hz()
void tcas_periodic_task_1Hz (void)
Definition at line 117 of file tcas.c.
References acInfo::ac_id, acInfoGetPositionEnu_f(), acInfoGetVelocityEnu_f(), DefaultChannel, DefaultDevice, foo, gps, ground_alt, acInfo::itow, NB_ACS, RA_CLIMB, RA_DESCEND, RA_LEVEL, RA_NONE, tcas_ac_status::resolve, stateGetHorizontalSpeedDir_f(), stateGetHorizontalSpeedNorm_f(), stateGetPositionEnu_f(), stateGetPositionUtm_f(), stateGetSpeedEnu_f(), tcas_ac_status::status, status, tcas_ac_RA, tcas_acs_status, TCAS_DT_MAX, TCAS_HUGE_TAU, TCAS_IsInside, TCAS_NO_ALARM, TCAS_RA, tcas_resolve, tcas_status, TCAS_TA, tcas_tau_ra, tcas_tau_ta, tcas_test_direction(), ti_acs, ti_acs_id, GpsState::tow, EnuCoor_f::x, EnuCoor_f::y, and EnuCoor_f::z.
tcas_periodic_task_4Hz()
void tcas_periodic_task_4Hz (void)
Definition at line 236 of file tcas.c.
References acInfoGetPositionEnu_f(), foo, ground_alt, Min, nav_altitude, RA_CLIMB, RA_DESCEND, RA_LEVEL, RA_NONE, stateGetPositionUtm_f(), tcas_ac_RA, tcas_alim, tcas_alt_setpoint, TCAS_RA, and tcas_status.
tcas_test_direction()
static enum tcas_resolve tcas_test_direction (uint8_t id) inline static
Definition at line 103 of file tcas.c.
References acInfoGetPositionEnu_f(), foo, RA_CLIMB, RA_DESCEND, stateGetPositionEnu_f(), tcas_alim, and EnuCoor_f::z.
Referenced by tcas_periodic_task_1Hz().
Variable Documentation
tcas_ac_RA
uint8_t tcas_ac_RA
Definition at line 40 of file tcas.c.
Referenced by tcas_init(), tcas_periodic_task_1Hz(), and tcas_periodic_task_4Hz().
tcas_acs_status
struct tcas_ac_status tcas_acs_status[NB_ACS]
Definition at line 41 of file tcas.c.
Referenced by parseTcasRA(), parseTcasResolve(), tcas_init(), and tcas_periodic_task_1Hz().
tcas_alim
float tcas_alim
Definition at line 36 of file tcas.c.
Referenced by tcas_init(), tcas_periodic_task_4Hz(), and tcas_test_direction().
tcas_alt_setpoint
float tcas_alt_setpoint
Definition at line 35 of file tcas.c.
Referenced by callTCAS(), tcas_init(), and tcas_periodic_task_4Hz().
tcas_dmod
float tcas_dmod
Definition at line 36 of file tcas.c.
Referenced by tcas_init().
tcas_resolve
enum tcas_resolve tcas_resolve
Definition at line 39 of file tcas.c.
Referenced by tcas_periodic_task_1Hz().
tcas_status
uint8_t tcas_status
Definition at line 38 of file tcas.c.
Referenced by callTCAS(), tcas_init(), tcas_periodic_task_1Hz(), and tcas_periodic_task_4Hz().
tcas_tau_ra
float tcas_tau_ra
Definition at line 36 of file tcas.c.
Referenced by tcas_init(), and tcas_periodic_task_1Hz().
tcas_tau_ta
float tcas_tau_ta
Definition at line 36 of file tcas.c.
Referenced by tcas_init(), and tcas_periodic_task_1Hz().