Paparazzi UAS: sw/airborne/modules/multi/tcas.h File Reference
tcas.h File Reference
Collision avoidance library.
#include "std.h"
#include "pprzlink/messages.h"
#include "generated/airframe.h"
#include "modules/multi/traffic_info.h"
Data Structures
struct tcas_ac_status
Macros
#define TCAS_NO_ALARM 0
#define TCAS_TA 1
#define TCAS_RA 2
Enumerations
enum tcas_resolve { RA_NONE , RA_LEVEL , RA_CLIMB , RA_DESCEND }
Functions
void tcas_init (void)
void tcas_periodic_task_1Hz (void)
void tcas_periodic_task_4Hz (void)
void callTCAS (void)
void parseTcasResolve (uint8_t *buf)
void parseTcasRA (uint8_t *buf)
Variables
float tcas_alt_setpoint
float tcas_tau_ta
float tcas_tau_ra
float tcas_dmod
float tcas_alim
uint8_t tcas_status
enum tcas_resolve tcas_resolve
uint8_t tcas_ac_RA
struct tcas_ac_status tcas_acs_status [NB_ACS]
Detailed Description
Collision avoidance library.
Definition in file tcas.h.
Data Structure Documentation
tcas_ac_status
struct tcas_ac_status
Definition at line 49 of file tcas.h.
Data Fields
enum tcas_resolve resolve
uint8_t status
Macro Definition Documentation
TCAS_NO_ALARM
#define TCAS_NO_ALARM 0
Definition at line 40 of file tcas.h.
TCAS_RA
#define TCAS_RA 2
Definition at line 42 of file tcas.h.
TCAS_TA
#define TCAS_TA 1
Definition at line 41 of file tcas.h.
Enumeration Type Documentation
tcas_resolve
enum tcas_resolve
Enumerator
RA_NONE
RA_LEVEL
RA_CLIMB
RA_DESCEND
Definition at line 43 of file tcas.h.
Function Documentation
callTCAS()
void callTCAS (void) extern
Definition at line 65 of file tcas.c.
References tcas_alt_setpoint, TCAS_RA, tcas_status, and v_ctl_altitude_setpoint.
Referenced by navigation_task().
parseTcasRA()
void parseTcasRA (uint8_t * buf) extern
Definition at line 95 of file tcas.c.
References dl_buffer, foo, tcas_ac_status::resolve, tcas_acs_status, and ti_acs_id.
parseTcasResolve()
void parseTcasResolve (uint8_t * buf) extern
Definition at line 87 of file tcas.c.
References foo, tcas_ac_status::resolve, tcas_acs_status, and ti_acs_id.
tcas_init()
void tcas_init (void) extern
Definition at line 70 of file tcas.c.
References foo, ground_alt, NB_ACS, RA_NONE, tcas_ac_status::resolve, tcas_ac_status::status, tcas_ac_RA, tcas_acs_status, tcas_alim, TCAS_ALIM, tcas_alt_setpoint, tcas_dmod, TCAS_DMOD, TCAS_NO_ALARM, tcas_status, tcas_tau_ra, TCAS_TAU_RA, tcas_tau_ta, and TCAS_TAU_TA.
tcas_periodic_task_1Hz()
void tcas_periodic_task_1Hz (void) extern
Definition at line 117 of file tcas.c.
References acInfo::ac_id, acInfoGetPositionEnu_f(), acInfoGetVelocityEnu_f(), DefaultChannel, DefaultDevice, foo, gps, ground_alt, acInfo::itow, NB_ACS, RA_CLIMB, RA_DESCEND, RA_LEVEL, RA_NONE, tcas_ac_status::resolve, stateGetHorizontalSpeedDir_f(), stateGetHorizontalSpeedNorm_f(), stateGetPositionEnu_f(), stateGetPositionUtm_f(), stateGetSpeedEnu_f(), tcas_ac_status::status, status, tcas_ac_RA, tcas_acs_status, TCAS_DT_MAX, TCAS_HUGE_TAU, TCAS_IsInside, TCAS_NO_ALARM, TCAS_RA, tcas_resolve, tcas_status, TCAS_TA, tcas_tau_ra, tcas_tau_ta, tcas_test_direction(), ti_acs, ti_acs_id, GpsState::tow, EnuCoor_f::x, EnuCoor_f::y, and EnuCoor_f::z.
tcas_periodic_task_4Hz()
void tcas_periodic_task_4Hz (void) extern
Definition at line 236 of file tcas.c.
References acInfoGetPositionEnu_f(), foo, ground_alt, Min, nav_altitude, RA_CLIMB, RA_DESCEND, RA_LEVEL, RA_NONE, stateGetPositionUtm_f(), tcas_ac_RA, tcas_alim, tcas_alt_setpoint, TCAS_RA, and tcas_status.
Variable Documentation
tcas_ac_RA
uint8_t tcas_ac_RA extern
Definition at line 40 of file tcas.c.
Referenced by tcas_init(), tcas_periodic_task_1Hz(), and tcas_periodic_task_4Hz().
tcas_acs_status
struct tcas_ac_status tcas_acs_status[NB_ACS] extern
Definition at line 41 of file tcas.c.
Referenced by parseTcasRA(), parseTcasResolve(), tcas_init(), and tcas_periodic_task_1Hz().
tcas_alim
float tcas_alim
Definition at line 38 of file tcas.h.
tcas_alt_setpoint
float tcas_alt_setpoint extern
Definition at line 35 of file tcas.c.
Referenced by callTCAS(), tcas_init(), and tcas_periodic_task_4Hz().
tcas_dmod
float tcas_dmod
Definition at line 38 of file tcas.h.
tcas_resolve
enum tcas_resolve tcas_resolve extern
Definition at line 39 of file tcas.c.
Referenced by tcas_periodic_task_1Hz().
tcas_status
uint8_t tcas_status extern
Definition at line 38 of file tcas.c.
Referenced by callTCAS(), tcas_init(), tcas_periodic_task_1Hz(), and tcas_periodic_task_4Hz().
tcas_tau_ra
float tcas_tau_ra
Definition at line 38 of file tcas.h.
tcas_tau_ta
float tcas_tau_ta extern
Definition at line 36 of file tcas.c.
Referenced by tcas_init(), and tcas_periodic_task_1Hz().