Paparazzi UAS: sw/airborne/modules/range_finder/teraranger_one.h File Reference
teraranger_one.h File Reference
#include "std.h"
Data Structures
struct TeraRanger
Functions
void teraranger_init (void)
void teraranger_periodic (void)
void teraranger_event (void)
void teraranger_downlink (void)
Variables
struct TeraRanger teraranger
Detailed Description
Author
Gautier Hattenberger gauti.nosp@m.er.h.nosp@m.atten.nosp@m.berg.nosp@m.er@en.nosp@m.ac.f.nosp@m.r Driver for the TeraRanger One range finder (I2C)
Definition in file teraranger_one.h.
Data Structure Documentation
TeraRanger
struct TeraRanger
Definition at line 31 of file teraranger_one.h.
Data Fields
bool data_available
float dist scaled distance in m
float offset offset in m
uint16_t raw raw distance in mm
Function Documentation
teraranger_downlink()
void teraranger_downlink (void) extern
Definition at line 143 of file teraranger_one.c.
References DefaultChannel, DefaultDevice, TeraRanger::dist, foo, TeraRanger::raw, and teraranger.
teraranger_event()
void teraranger_event (void) extern
Definition at line 114 of file teraranger_one.c.
References AGL_TERARANGER_ONE_ID, i2c_transaction::buf, TeraRanger::data_available, TeraRanger::dist, foo, get_sys_time_usec(), I2CTransDone, I2CTransFailed, I2CTransSuccess, TeraRanger::offset, TeraRanger::raw, i2c_transaction::status, teraranger, teraranger_crc8(), and teraranger_i2c_trans.
teraranger_init()
void teraranger_init (void) extern
Definition at line 95 of file teraranger_one.c.
References TeraRanger::data_available, TeraRanger::dist, I2CTransDone, TeraRanger::offset, TeraRanger::raw, i2c_transaction::status, teraranger, teraranger_i2c_trans, and TERARANGER_ONE_OFFSET.
teraranger_periodic()
void teraranger_periodic (void) extern
Definition at line 106 of file teraranger_one.c.
References foo, i2c_receive(), I2CTransDone, i2c_transaction::status, teraranger_i2c_trans, and TERARANGER_ONE_I2C_ADDR.
Variable Documentation
teraranger
struct TeraRanger teraranger extern
Definition at line 90 of file teraranger_one.c.
Referenced by teraranger_downlink(), teraranger_event(), and teraranger_init().