Paparazzi UAS: sw/airborne/modules/lidar/tfmini_nps.c File Reference
tfmini_nps.c File Reference
simulation of a lidar
#include "tfmini.h"
#include "state.h"
#include "pprzlink/messages.h"
#include "modules/datalink/downlink.h"
#include "modules/core/abi.h"
#include "modules/datalink/telemetry.h"
Macros
#define LIDAR_MIN_RANGE 0.1
#define LIDAR_MAX_RANGE 12.0
Functions
static void tfmini_send_lidar (struct transport_tx *trans, struct link_device *dev)
Downlink message lidar.
void tfmini_init (void)
Initialization function.
void tfmini_event (void)
Lidar event function Receive bytes from the UART port and parse them.
void sim_overwrite_lidar (void)
void setLidarDistance_f (float distance)
Set the distance of the lidar This function is used in NPS to set the distance of the lidar.
void tfmini_send_abi (void)
Variables
struct TFMini tfmini
Detailed Description
simulation of a lidar
Definition in file tfmini_nps.c.
Macro Definition Documentation
LIDAR_MAX_RANGE
#define LIDAR_MAX_RANGE 12.0
Definition at line 37 of file tfmini_nps.c.
LIDAR_MIN_RANGE
#define LIDAR_MIN_RANGE 0.1
Definition at line 36 of file tfmini_nps.c.
Function Documentation
setLidarDistance_f()
void setLidarDistance_f (float distance)
Set the distance of the lidar This function is used in NPS to set the distance of the lidar.
Definition at line 123 of file tfmini_nps.c.
References TFMini::distance, foo, LIDAR_MAX_RANGE, tfmini, and tfmini_send_abi().
Referenced by sim_overwrite_lidar().
sim_overwrite_lidar()
void sim_overwrite_lidar (void)
Definition at line 82 of file tfmini_nps.c.
References ServoLidar::angle, distance_to_wall(), foo, gps, GpsState::lla_pos, ned_of_lla_point_i(), p, FloatEulers::psi, servoLidar, setLidarDistance_f(), stateGetNedOrigin_i(), stateGetNedToBodyEulers_f(), stateIsLocalCoordinateValid(), WallSystem::wall_count, wall_system, WallSystem::walls, FloatVect2::x, and FloatVect2::y.
Referenced by tfmini_event().
tfmini_event()
void tfmini_event (void)
Lidar event function Receive bytes from the UART port and parse them.
Definition at line 74 of file tfmini_nps.c.
References sim_overwrite_lidar().
tfmini_init()
void tfmini_init (void)
Initialization function.
Definition at line 63 of file tfmini_nps.c.
References DefaultPeriodic, TFMini::device, TFMini::distance, foo, register_periodic_telemetry(), tfmini, and tfmini_send_lidar().
tfmini_send_abi()
void tfmini_send_abi (void)
Definition at line 134 of file tfmini_nps.c.
References AGL_LIDAR_TFMINI_ID, TFMini::distance, foo, and tfmini.
Referenced by setLidarDistance_f().
tfmini_send_lidar()
static void tfmini_send_lidar (struct transport_tx * trans, struct link_device * dev) static
Downlink message lidar.
Definition at line 47 of file tfmini_nps.c.
References dev, TFMini::distance, foo, TFMini::mode, TFMini::parse_status, status, and tfmini.
Referenced by tfmini_init().
Variable Documentation
tfmini
struct TFMini tfmini
Definition at line 39 of file tfmini_nps.c.
Referenced by setLidarDistance_f(), tfmini_init(), tfmini_send_abi(), and tfmini_send_lidar().