Paparazzi UAS: sw/airborne/modules/lidar/tfmini.c File Reference
tfmini.c File Reference
driver for the TFMini lidar
#include "tfmini.h"
#include "mcu_periph/uart.h"
#include "modules/core/abi.h"
#include "state.h"
#include "pprzlink/messages.h"
#include "modules/datalink/downlink.h"
#include "modules/datalink/telemetry.h"
Macros
#define LIDAR_OFFSET 0.0f
#define LIDAR_HEIGHT 0.0f
Functions
static void tfmini_send_lidar (struct transport_tx *trans, struct link_device *dev)
Downlink message lidar.
void tfmini_init (void)
Initialization function.
void tfmini_event (void)
Lidar event function Receive bytes from the UART port and parse them.
void tfmini_parse (uint8_t byte)
Parse the lidar bytes 1 by 1.
void tfmini_send_abi (void)
Variables
static float lidar_offset
static float lidar_height
struct TFMini tfmini
Detailed Description
driver for the TFMini lidar
Definition in file tfmini.c.
Macro Definition Documentation
LIDAR_HEIGHT
#define LIDAR_HEIGHT 0.0f
Definition at line 47 of file tfmini.c.
LIDAR_OFFSET
#define LIDAR_OFFSET 0.0f
Definition at line 42 of file tfmini.c.
Function Documentation
tfmini_event()
void tfmini_event (void)
Lidar event function Receive bytes from the UART port and parse them.
Definition at line 102 of file tfmini.c.
References TFMini::device, TFMini::parse_status, tfmini, TFMINI_INITIALIZE, and tfmini_parse().
tfmini_init()
void tfmini_init (void)
Initialization function.
Definition at line 77 of file tfmini.c.
References TFMini::compensate_rotation, DefaultPeriodic, TFMini::device, TFMini::distance, foo, TFMini::is_rover, LIDAR_HEIGHT, lidar_height, LIDAR_OFFSET, lidar_offset, TFMini::parse_status, register_periodic_telemetry(), TFMini::strength, tfmini, TFMINI_PARSE_HEAD, tfmini_send_lidar(), and TFMini::update_agl.
tfmini_parse()
void tfmini_parse (uint8_t byte)
Parse the lidar bytes 1 by 1.
Definition at line 113 of file tfmini.c.
References byte, TFMini::compensate_rotation, TFMini::distance, foo, TFMini::is_rover, lidar_height, lidar_offset, TFMini::mode, TFMini::parse_crc, TFMini::parse_status, FloatEulers::phi, TFMini::raw_dist, TFMini::raw_mode, TFMini::raw_strength, stateGetNedToBodyEulers_f(), TFMini::strength, tfmini, TFMINI_INITIALIZE, TFMINI_PARSE_BYTE7, TFMINI_PARSE_CHECKSUM, TFMINI_PARSE_DIST_H, TFMINI_PARSE_DIST_L, TFMINI_PARSE_HEAD, TFMINI_PARSE_HEAD2, TFMINI_PARSE_MODE, TFMINI_PARSE_STRENGTH_H, TFMINI_PARSE_STRENGTH_L, tfmini_send_abi(), and FloatEulers::theta.
Referenced by tfmini_event().
tfmini_send_abi()
void tfmini_send_abi (void)
Definition at line 217 of file tfmini.c.
References AGL_LIDAR_TFMINI_ID, TFMini::distance, foo, get_sys_time_usec(), tfmini, and TFMini::update_agl.
Referenced by tfmini_parse().
tfmini_send_lidar()
static void tfmini_send_lidar (struct transport_tx * trans, struct link_device * dev) static
Downlink message lidar.
Definition at line 63 of file tfmini.c.
References dev, TFMini::distance, foo, TFMini::mode, TFMini::parse_status, status, and tfmini.
Referenced by tfmini_init().
Variable Documentation
lidar_height
float lidar_height static
Definition at line 51 of file tfmini.c.
Referenced by tfmini_init(), and tfmini_parse().
lidar_offset
float lidar_offset static
Definition at line 50 of file tfmini.c.
Referenced by tfmini_init(), and tfmini_parse().
tfmini
struct TFMini tfmini
Initial value:
= {
  .parse_status = TFMINI_INITIALIZE
}
Definition at line 53 of file tfmini.c.
Referenced by tfmini_event(), tfmini_init(), tfmini_parse(), tfmini_send_abi(), and tfmini_send_lidar().