Paparazzi UAS: sw/airborne/modules/lidar/tfmini.h File Reference
tfmini.h File Reference
driver for the TFMini lidar
#include "std.h"
#include "mcu_periph/i2c.h"
#include "math/pprz_algebra_float.h"
Data Structures
struct TFMini
Enumerations
enum TFMiniParseStatus {
TFMINI_INITIALIZE , TFMINI_PARSE_HEAD , TFMINI_PARSE_HEAD2 , TFMINI_PARSE_DIST_L ,
TFMINI_PARSE_DIST_H , TFMINI_PARSE_STRENGTH_L , TFMINI_PARSE_STRENGTH_H , TFMINI_PARSE_MODE ,
TFMINI_PARSE_BYTE7 , TFMINI_PARSE_CHECKSUM
}
Functions
void tfmini_init (void)
Initialization function.
void tfmini_event (void)
Lidar event function Receive bytes from the UART port and parse them.
void tfmini_send_abi (void)
void tfmini_parse (uint8_t byte)
Parse the lidar bytes 1 by 1.
Variables
struct TFMini tfmini
Detailed Description
driver for the TFMini lidar
Definition in file tfmini.h.
Data Structure Documentation
TFMini
struct TFMini
Definition at line 48 of file tfmini.h.
Data Fields
bool compensate_rotation
struct link_device * device
float distance
bool is_rover
uint8_t mode
uint8_t parse_crc
enum TFMiniParseStatus parse_status
uint16_t raw_dist
uint8_t raw_mode
uint16_t raw_strength
uint16_t strength
bool update_agl
Enumeration Type Documentation
TFMiniParseStatus
enum TFMiniParseStatus
Enumerator
TFMINI_INITIALIZE
TFMINI_PARSE_HEAD
TFMINI_PARSE_HEAD2
TFMINI_PARSE_DIST_L
TFMINI_PARSE_DIST_H
TFMINI_PARSE_STRENGTH_L
TFMINI_PARSE_STRENGTH_H
TFMINI_PARSE_MODE
TFMINI_PARSE_BYTE7
TFMINI_PARSE_CHECKSUM
Definition at line 35 of file tfmini.h.
Function Documentation
tfmini_event()
void tfmini_event (void) extern
Lidar event function Receive bytes from the UART port and parse them.
Definition at line 102 of file tfmini.c.
References TFMini::device, TFMini::parse_status, sim_overwrite_lidar(), tfmini, TFMINI_INITIALIZE, and tfmini_parse().
tfmini_init()
void tfmini_init (void) extern
Initialization function.
Definition at line 77 of file tfmini.c.
References TFMini::compensate_rotation, DefaultPeriodic, TFMini::device, TFMini::distance, foo, TFMini::is_rover, LIDAR_HEIGHT, lidar_height, LIDAR_OFFSET, lidar_offset, TFMini::parse_status, register_periodic_telemetry(), TFMini::strength, tfmini, TFMINI_PARSE_HEAD, tfmini_send_lidar(), tfmini_send_lidar(), and TFMini::update_agl.
tfmini_parse()
void tfmini_parse (uint8_t byte) extern
Parse the lidar bytes 1 by 1.
Definition at line 113 of file tfmini.c.
References byte, TFMini::compensate_rotation, TFMini::distance, foo, TFMini::is_rover, lidar_height, lidar_offset, TFMini::mode, TFMini::parse_crc, TFMini::parse_status, FloatEulers::phi, TFMini::raw_dist, TFMini::raw_mode, TFMini::raw_strength, stateGetNedToBodyEulers_f(), TFMini::strength, tfmini, TFMINI_INITIALIZE, TFMINI_PARSE_BYTE7, TFMINI_PARSE_CHECKSUM, TFMINI_PARSE_DIST_H, TFMINI_PARSE_DIST_L, TFMINI_PARSE_HEAD, TFMINI_PARSE_HEAD2, TFMINI_PARSE_MODE, TFMINI_PARSE_STRENGTH_H, TFMINI_PARSE_STRENGTH_L, tfmini_send_abi(), and FloatEulers::theta.
Referenced by tfmini_event().
tfmini_send_abi()
void tfmini_send_abi (void) extern
Definition at line 217 of file tfmini.c.
References AGL_LIDAR_TFMINI_ID, TFMini::distance, foo, get_sys_time_usec(), tfmini, and TFMini::update_agl.
Referenced by setLidarDistance_f(), and tfmini_parse().
Variable Documentation
tfmini
struct TFMini tfmini extern
Definition at line 53 of file tfmini.c.
Referenced by setLidarDistance_f(), tfmini_event(), tfmini_init(), tfmini_parse(), tfmini_send_abi(), tfmini_send_lidar(), and tfmini_send_lidar().