Paparazzi UAS: sw/airborne/modules/sensors/thd_test.h File Reference
thd_test.h File Reference
Functions
void thd_test_init (void)
void thd_test_periodic (void)
void thd_test_event (void)
void thd_test_syracuse_restart (float s)
Variables
float thd_test_start_value
Detailed Description
Author
fab fab@g.nosp@m.ithu.nosp@m.b.com A module to test threads functionnalities, like threads, mutexes, semaphores and so on.
Definition in file thd_test.h.
Function Documentation
thd_test_event()
void thd_test_event (void) extern
thd_test_init()
void thd_test_init (void) extern
Definition at line 69 of file thd_test.c.
References bsem, foo, joined, mtx, pprz_bsem_init(), pprz_mtx_init(), PPRZ_NORMAL_PRIO, pprz_thread_create(), test_thd(), and thd_handle.
thd_test_periodic()
void thd_test_periodic (void) extern
Definition at line 79 of file thd_test.c.
References bsem, DefaultChannel, DefaultDevice, foo, joined, msg, mtx, pprz_bsem_signal(), pprz_mtx_trylock(), pprz_mtx_unlock(), pprz_thread_tryjoin(), syracuse, and thd_handle.
thd_test_syracuse_restart()
void thd_test_syracuse_restart (float s)
Definition at line 48 of file thd_test.c.
References DefaultChannel, DefaultDevice, foo, joined, mtx, pprz_mtx_trylock(), pprz_mtx_unlock(), PPRZ_NORMAL_PRIO, pprz_thread_create(), s, syracuse, test_thd(), thd_handle, and thd_test_start_value.
Variable Documentation
thd_test_start_value
float thd_test_start_value extern
Definition at line 32 of file thd_test.c.
Referenced by thd_test_syracuse_restart().