Paparazzi UAS: sw/airborne/modules/core/threads.h File Reference
threads.h File Reference
#include "stdbool.h"
#include "modules/core/threads_arch.h"
#include "stdint.h"
#include <stddef.h>
Typedefs
typedef struct pprzMutex pprz_mutex_t
typedef struct pprzBSem pprz_bsem_t
Functions
int pprz_mtx_init (pprz_mutex_t *mtx)
int pprz_mtx_lock (pprz_mutex_t *mtx)
int pprz_mtx_trylock (pprz_mutex_t *mtx)
Performs a nonblocking lock on the mutex.
int pprz_mtx_unlock (pprz_mutex_t *mtx)
void pprz_bsem_init (pprz_bsem_t *bsem, bool taken)
void pprz_bsem_wait (pprz_bsem_t *bsem)
int pprz_bsem_wait_timeout (pprz_bsem_t *bsem, float timeout)
Wait on semaphore no more than timeout.
void pprz_bsem_signal (pprz_bsem_t *bsem)
int pprz_thread_create (pprz_thread_t *thread, size_t size, const char *name, uint8_t prio, void(*func)(void *), void *arg) THREADS_ATTRIBUTES
Creates a new thread whose stack is dynamically allocated.
void pprz_thread_exit (void *retval) THREADS_ATTRIBUTES
Exit the current thread.
int pprz_thread_join (pprz_thread_t *thread, void **retval) THREADS_ATTRIBUTES
Wait for the thread to terminate.
int pprz_thread_tryjoin (pprz_thread_t *thread, void **retval) THREADS_ATTRIBUTES
Performs a nonblocking join with the thread.
Typedef Documentation
pprz_bsem_t
typedef struct pprzBSem pprz_bsem_t
Definition at line 22 of file threads.h.
pprz_mutex_t
typedef struct pprzMutex pprz_mutex_t
Definition at line 21 of file threads.h.
Function Documentation
pprz_bsem_init()
void pprz_bsem_init (pprz_bsem_t * bsem, bool taken)
Definition at line 39 of file threads_arch.c.
References pprzBSem::bsem, bsem, foo, pprzBSem::mtx, pprzBSem::sem, and pprzBSem::value.
Referenced by amt22_init(), humid_sht_init_i2c(), i2c_chibios_submit(), i2c_linux_submit(), spi_submit(), thd_test_init(), and uavcanInitIface().
pprz_bsem_signal()
void pprz_bsem_signal (pprz_bsem_t * bsem)
Definition at line 57 of file threads_arch.c.
References pprzBSem::bsem, bsem, foo, pprzBSem::mtx, pprzBSem::sem, val, and pprzBSem::value.
Referenced by amt22_periodic(), handle_spi_thd(), humid_sht_thd(), i2c_thread(), thd_test_periodic(), uavcan_request(), uavcan_response(), and uavcan_transfer().
pprz_bsem_wait()
void pprz_bsem_wait (pprz_bsem_t * bsem)
Definition at line 43 of file threads_arch.c.
References pprzBSem::bsem, bsem, foo, pprzBSem::sem, and pprzBSem::value.
Referenced by amt22_thd(), test_thd(), and uavcan_tx().
pprz_bsem_wait_timeout()
int pprz_bsem_wait_timeout (pprz_bsem_t * bsem, float timeout)
Wait on semaphore no more than timeout.
Parameters
timeout in seconds
Returns
0 on success
Definition at line 47 of file threads_arch.c.
References pprzBSem::bsem, bsem, foo, get_sys_time_float(), pprzBSem::sem, timeout, and pprzBSem::value.
Referenced by humid_sht_periodic_i2c(), i2c_blocking_submit(), and spi_blocking_transceive().
pprz_mtx_init()
int pprz_mtx_init (pprz_mutex_t * mtx)
Definition at line 18 of file threads_arch.c.
References foo, pprzMutex::mtx, and mtx.
Referenced by amt22_init(), copilot_init(), gec_transport_init(), rc_uavcan_init(), slcan_init(), syslink_dl_init(), thd_test_init(), tunnel_uavcan_init_periph(), and uavcanInitIface().
pprz_mtx_lock()
int pprz_mtx_lock (pprz_mutex_t * mtx)
Definition at line 23 of file threads_arch.c.
References foo, pprzMutex::mtx, and mtx.
Referenced by amt22_get_position(), amt22_get_turns(), amt22_read(), copilot_parse_cam_payload_dl(), copilot_parse_cam_snapshot_dl(), copilot_parse_copilot_status_dl(), copilot_periodic(), handle_raw(), slcan_can_rx_cb(), syslink_check_free_space(), syslink_send_message(), test_thd(), tunnel_uavcan_char_available(), tunnel_uavcan_check_free_space(), tunnel_uavcan_get_byte(), tunnel_uavcan_put_buffer(), tunnel_uavcan_send_message(), uavcan_request(), uavcan_response(), uavcan_transfer(), and uavcan_tx().
pprz_mtx_trylock()
int pprz_mtx_trylock (pprz_mutex_t * mtx)
Performs a nonblocking lock on the mutex.
Returns
0 if successful
Definition at line 28 of file threads_arch.c.
References foo, pprzMutex::mtx, and mtx.
Referenced by rc_uavcan_cb(), rc_uavcan_event(), thd_test_periodic(), thd_test_syracuse_restart(), and tunnel_uavcan_cb().
pprz_mtx_unlock()
int pprz_mtx_unlock (pprz_mutex_t * mtx)
Definition at line 32 of file threads_arch.c.
References foo, pprzMutex::mtx, and mtx.
Referenced by amt22_get_position(), amt22_get_turns(), amt22_read(), copilot_parse_cam_payload_dl(), copilot_parse_cam_snapshot_dl(), copilot_parse_copilot_status_dl(), copilot_periodic(), handle_raw(), rc_uavcan_cb(), rc_uavcan_event(), slcan_can_rx_cb(), test_thd(), thd_test_periodic(), thd_test_syracuse_restart(), tunnel_uavcan_cb(), tunnel_uavcan_char_available(), tunnel_uavcan_check_free_space(), tunnel_uavcan_get_byte(), tunnel_uavcan_send_message(), uavcan_request(), uavcan_response(), uavcan_transfer(), and uavcan_tx().
pprz_thread_create()
int pprz_thread_create (pprz_thread_t * thread, size_t size, const char * name, uint8_t prio, void(*)(void *) func, void * arg)
Creates a new thread whose stack is dynamically allocated.
Parameters
[in] size size of the stack. Unused on linux at the moment.
[in] prio the priority level for the new thread. Unused on linux at the moment. NORMALPRIO
[in] pf the thread function
[in] arg an argument passed to the thread function. It can be NULL.
[out] thread pointer to a pprz_thread_t that will be writen with the handle to the thread
Returns
Return 0 on success, or a platform dependant error code.
@api
Definition at line 62 of file threads_arch.c.
References stub_arg::arg, foo, stub_arg::func, and stub().
Referenced by amt22_init(), humid_sht_init_i2c(), thd_test_init(), thd_test_syracuse_restart(), and uavcanInitIface().
pprz_thread_exit()
void pprz_thread_exit (void * retval)
Exit the current thread.
Parameters
[out] retval The thread's return value
Definition at line 70 of file threads_arch.c.
References foo.
Referenced by test_thd().
pprz_thread_join()
int pprz_thread_join (pprz_thread_t * thread, void ** retval)
Wait for the thread to terminate.
Note
Warning ! This is a blocking function, do not use it in the main AP thread !
Parameters
[in] thread The thread to be joined
[out] retval The thread's return value will be written to the variable pointed by retval
Definition at line 75 of file threads_arch.c.
References foo.
Referenced by pprz_thread_tryjoin().
pprz_thread_tryjoin()
int pprz_thread_tryjoin (pprz_thread_t * thread, void ** retval)
Performs a nonblocking join with the thread.
Parameters
[in] thread The thread to be joined
[out] retval The thread's return value will be written to the variable pointed by retval. must not be used if this fuction did not returned 0.
Returns
0 if the thread successfully joined.
Definition at line 81 of file threads_arch.c.
References foo, and pprz_thread_join().
Referenced by thd_test_periodic().