Paparazzi UAS: sw/airborne/modules/helicopter/throttle_curve.h File Reference
throttle_curve.h File Reference
#include "std.h"
#include "paparazzi.h"
#include "generated/airframe.h"
Data Structures
struct curve_t
struct throttle_curve_t
Functions
void throttle_curve_init (void)
Initialize the default throttle curve values.
void throttle_curve_run (pprz_t in_cmd[], uint8_t autopilot_mode)
Run the throttle curve and generate the output throttle and pitch This depends on the FMODE(flight mode) and TRHUST command.
void nav_throttle_curve_set (uint8_t mode)
Set a specific throttle curve based on the mode given with this function.
Variables
struct throttle_curve_t throttle_curve
Detailed Description
Author
C. De Wagter and Freek van Tienen Throttle Curve Mixers
Definition in file throttle_curve.h.
Data Structure Documentation
curve_t
struct curve_t
Definition at line 35 of file throttle_curve.h.
Data Fields
int16_t collective[THROTTLE_POINTS_NB] The collective points in the curve.
uint8_t nb_points The number of points in the curve.
uint16_t rpm[THROTTLE_POINTS_NB] RPM points in the curve.
uint16_t throttle[THROTTLE_POINTS_NB] Throttle points in the curve.
throttle_curve_t
struct throttle_curve_t
Definition at line 43 of file throttle_curve.h.
Data Fields
int32_t coll_trim Collective trim.
int16_t collective Output collective of the throttle curve.
struct curve_t curves[THROTTLE_CURVES_NB] Throttle/pitch curves.
uint8_t mode Flight mode.
uint8_t nav_mode Nav Flight mode.
uint8_t nb_curves The number of throttle/pitch curves.
uint16_t rpm Output RPM of the throttle curve.
float rpm_err_sum Summed RPM error.
float rpm_fb_i
float rpm_fb_p RPM feedback p gain.
uint16_t rpm_meas RPM measured.
bool rpm_measured Whenever the RPM is measured.
uint16_t throttle Output thrust(throttle) of the throttle curve.
int32_t throttle_trim RPM feedback i gain.
Function Documentation
nav_throttle_curve_set()
void nav_throttle_curve_set (uint8_t mode)
Set a specific throttle curve based on the mode given with this function.
Definition at line 218 of file throttle_curve.c.
References foo, mode, throttle_curve_t::nav_mode, and throttle_curve.
throttle_curve_init()
void throttle_curve_init (void) extern
Initialize the default throttle curve values.
Definition at line 87 of file throttle_curve.c.
References act_feedback_cb(), act_feedback_ev, throttle_curve_t::coll_trim, curve_t::collective, throttle_curve_t::collective, throttle_curve_t::curves, DefaultPeriodic, foo, throttle_curve_t::mode, throttle_curve_t::nav_mode, register_periodic_telemetry(), throttle_curve_t::rpm_err_sum, throttle_curve_t::rpm_fb_i, throttle_curve_t::rpm_fb_p, throttle_curve_t::rpm_measured, curve_t::throttle, throttle_curve_t::throttle, throttle_curve, THROTTLE_CURVE_ACT_FEEDBACK_ID, THROTTLE_CURVE_RPM_FB_I, THROTTLE_CURVE_RPM_FB_P, throttle_curve_send_telem(), and throttle_curve_t::throttle_trim.
throttle_curve_run()
void throttle_curve_run (pprz_t in_cmd[], uint8_t autopilot_mode)
Run the throttle curve and generate the output throttle and pitch This depends on the FMODE(flight mode) and TRHUST command.
Definition at line 125 of file throttle_curve.c.
References AP_MODE_FAILSAFE, AP_MODE_NAV, autopilot_get_motors_on(), cmds, throttle_curve_t::coll_trim, throttle_curve_t::collective, throttle_curve_t::curves, foo, MAX_PPRZ, throttle_curve_t::mode, mode, throttle_curve_t::nav_mode, radio_control, throttle_curve_t::rpm, throttle_curve_t::rpm_err_sum, throttle_curve_t::rpm_fb_i, throttle_curve_t::rpm_fb_p, throttle_curve_t::rpm_meas, throttle_curve_t::rpm_measured, throttle_curve_t::throttle, throttle_curve, THROTTLE_CURVE_RPM_INC_LIMIT, THROTTLE_CURVE_SWITCH_VAL, throttle_curve_t::throttle_trim, and RadioControl::values.
Variable Documentation
throttle_curve
struct throttle_curve_t throttle_curve extern
Definition at line 68 of file throttle_curve.c.
Referenced by act_feedback_cb(), nav_throttle_curve_set(), throttle_curve_init(), throttle_curve_run(), and throttle_curve_send_telem().