Paparazzi UAS: sw/airborne/arch/chibios/mcu_periph/timerDmaCache.h File Reference
timerDmaCache.h File Reference
#include <ch.h>
#include <hal.h>
#include <string.h>
#include "mcu_periph/hal_stm32_dma.h"
Data Structures
struct TimerDmaCache
Functions
void timerDmaCache_cache (TimerDmaCache *tdcp, const DMADriver *fromDma, const stm32_tim_t *fromTim)
void timerDmaCache_restore (const TimerDmaCache *tdcp, DMADriver *toDma, stm32_tim_t *toTim)
Data Structure Documentation
TimerDmaCache
struct TimerDmaCache
Definition at line 10 of file timerDmaCache.h.
Data Fields
DMA_Stream_TypeDef DMA_regs
stm32_tim_t TIM_regs
Function Documentation
timerDmaCache_cache()
void timerDmaCache_cache (TimerDmaCache * tdcp, const DMADriver * fromDma, const stm32_tim_t * fromTim)
Definition at line 9 of file timerDmaCache.c.
References foo.
Referenced by initCache().
timerDmaCache_restore()
void timerDmaCache_restore (const TimerDmaCache * tdcp, DMADriver * toDma, stm32_tim_t * toTim)
Definition at line 17 of file timerDmaCache.c.
References foo, and rccEnableAndReset().
Referenced by startCapture().