Paparazzi UAS: sw/airborne/modules/tlsf/tlsf_malloc.h File Reference
tlsf_malloc.h File Reference
Dynamic memory allocation based on TLSF library.
#include "modules/tlsf/tlsf_malloc_arch.h"
Data Structures
struct tlsf_stat_t
Typedefs
typedef struct _tlsf_memory_heap_t tlsf_memory_heap_t
Functions
void tlsf_init_heaps (void)
void * tlsf_malloc_r (tlsf_memory_heap_t *heap, size_t bytes)
void * tlsf_memalign_r (tlsf_memory_heap_t *heap, size_t align, size_t bytes)
void * tlsf_realloc_r (tlsf_memory_heap_t *heap, void *ptr, size_t size)
void tlsf_free_r (tlsf_memory_heap_t *heap, void *ptr)
void tlsf_stat_r (tlsf_memory_heap_t *heap, struct tlsf_stat_t *stat)
void * tlsf_get_heap_addr (const tlsf_memory_heap_t *heap)
int tlsf_check_r (tlsf_memory_heap_t *heap)
Detailed Description
Dynamic memory allocation based on TLSF library.
Similar to malloc with allocation time in O(1).
Generic arch independant API
Definition in file tlsf_malloc.h.
Data Structure Documentation
tlsf_stat_t
struct tlsf_stat_t
Definition at line 55 of file tlsf_malloc.h.
Data Fields
size_t mfree free memory available
size_t mused used memory
Typedef Documentation
tlsf_memory_heap_t
typedef struct _tlsf_memory_heap_t tlsf_memory_heap_t
Definition at line 40 of file tlsf_malloc.h.
Function Documentation
tlsf_check_r()
int tlsf_check_r (tlsf_memory_heap_t * heap)
Definition at line 137 of file tlsf_malloc_arch.c.
References foo, _tlsf_memory_heap_t::mtx, and _tlsf_memory_heap_t::tlsf.
tlsf_free_r()
void tlsf_free_r (tlsf_memory_heap_t * heap, void * ptr) extern
Definition at line 119 of file tlsf_malloc_arch.c.
References foo, _tlsf_memory_heap_t::mtx, and _tlsf_memory_heap_t::tlsf.
Referenced by msgqueue_send_timeout().
tlsf_get_heap_addr()
void * tlsf_get_heap_addr (const tlsf_memory_heap_t * heap) extern
Definition at line 90 of file tlsf_malloc_arch.c.
References _tlsf_memory_heap_t::tlsf.
Referenced by msgqueue_pop_timeout(), and msgqueue_send_timeout().
tlsf_init_heaps()
void tlsf_init_heaps (void) extern
Definition at line 74 of file tlsf_malloc_arch.c.
References error_cb, foo, HEAP_CCM, and HEAP_CCM_SIZE.
tlsf_malloc_r()
void * tlsf_malloc_r (tlsf_memory_heap_t * heap, size_t bytes) extern
Definition at line 95 of file tlsf_malloc_arch.c.
References foo, _tlsf_memory_heap_t::mtx, and _tlsf_memory_heap_t::tlsf.
Referenced by msgqueue_copy_send_timeout().
tlsf_memalign_r()
void * tlsf_memalign_r (tlsf_memory_heap_t * heap, size_t align, size_t bytes) extern
Definition at line 103 of file tlsf_malloc_arch.c.
References foo, _tlsf_memory_heap_t::mtx, and _tlsf_memory_heap_t::tlsf.
tlsf_realloc_r()
void * tlsf_realloc_r (tlsf_memory_heap_t * heap, void * ptr, size_t size) extern
Definition at line 111 of file tlsf_malloc_arch.c.
References foo, _tlsf_memory_heap_t::mtx, and _tlsf_memory_heap_t::tlsf.
tlsf_stat_r()
void tlsf_stat_r (tlsf_memory_heap_t * heap, struct tlsf_stat_t * stat) extern
Definition at line 127 of file tlsf_malloc_arch.c.
References foo, _tlsf_memory_heap_t::mtx, stat_tlsf_walker(), and _tlsf_memory_heap_t::tlsf.