Paparazzi UAS: sw/airborne/modules/multi/traffic_info.c File Reference
traffic_info.c File Reference
#include "modules/multi/traffic_info.h"
#include "generated/airframe.h"
#include "generated/flight_plan.h"
#include "modules/datalink/datalink.h"
#include "modules/datalink/telemetry.h"
#include "pprzlink/dl_protocol.h"
#include "pprzlink/messages.h"
#include "state.h"
#include "math/pprz_geodetic_utm.h"
#include "math/pprz_geodetic_wgs84.h"
Functions
static void send_acinfo_lla (struct transport_tx *trans, struct link_device *dev)
void traffic_info_init (void)
static void update_geoid_height (void)
Update estimate of the geoid height Requires an available hsml and/or lla measurement, if not available value isn't updated.
bool parse_acinfo_dl (uint8_t *buf)
Parse all datalink or telemetry messages that contain global position of other acs Messages currently handled: Telemetry (vehicle -> ground or vehicle -> vehicle): GPS_SMALL, GPS, GPS_LLA Datalink (ground -> vehicle): ACINFO, ACINFO_LLA.
void set_ac_info_utm (uint8_t id, uint32_t utm_east, uint32_t utm_north, uint32_t alt, uint8_t utm_zone, uint16_t course, uint16_t gspeed, uint16_t climb, uint32_t itow)
Set Aircraft info.
void set_ac_info_lla (uint8_t id, int32_t lat, int32_t lon, int32_t alt, int16_t course, uint16_t gspeed, int16_t climb, uint32_t itow)
Set Aircraft info.
void acInfoCalcPositionUtm_i (uint8_t ac_id)
void acInfoCalcPositionLla_i (uint8_t ac_id)
void acInfoCalcPositionEnu_i (uint8_t ac_id)
void acInfoCalcPositionUtm_f (uint8_t ac_id)
void acInfoCalcPositionLla_f (uint8_t ac_id)
void acInfoCalcPositionEnu_f (uint8_t ac_id)
void acInfoCalcVelocityEnu_i (uint8_t ac_id)
void acInfoCalcVelocityEnu_f (uint8_t ac_id)
void traffic_info_log_start (void)
void traffic_info_log_stop (void)
Variables
uint8_t ti_acs_idx
uint8_t ti_acs_id [NB_ACS_ID]
struct acInfo ti_acs [NB_ACS]
int32_t geoid_height
Detailed Description
Author
Kirk Scheper Information relative to the other aircrafts. Keeps track of other aircraft in airspace
Definition in file traffic_info.c.
Function Documentation
send_acinfo_lla()
static void send_acinfo_lla (struct transport_tx * trans, struct link_device * dev) static
Definition at line 65 of file traffic_info.c.
References LlaCoor_f::alt, LlaCoor_i::alt, course, dev, foo, gps, LlaCoor_f::lat, LlaCoor_i::lat, LogFileIsOpen, LogWrite, LlaCoor_f::lon, LlaCoor_i::lon, msg, pprzLogFile, stateGetHorizontalSpeedDir_f(), stateGetHorizontalSpeedNorm_f(), stateGetPositionEnu_f(), stateGetPositionLla_f(), stateGetPositionLla_i(), stateGetSpeedEnu_f(), GpsState::tow, EnuCoor_f::x, EnuCoor_f::y, and EnuCoor_f::z.
Referenced by traffic_info_init().
update_geoid_height()
static void update_geoid_height (void) static
Update estimate of the geoid height Requires an available hsml and/or lla measurement, if not available value isn't updated.
Definition at line 120 of file traffic_info.c.
References LlaCoor_i::alt, foo, geoid_height, gps, GPS_VALID_HMSL_BIT, GPS_VALID_POS_LLA_BIT, GpsState::hmsl, LlaCoor_i::lat, GpsState::lla_pos, LlaCoor_i::lon, GpsState::valid_fields, and wgs84_ellipsoid_to_geoid_i().
Referenced by acInfoCalcPositionLla_f(), acInfoCalcPositionLla_i(), acInfoCalcPositionUtm_f(), and acInfoCalcPositionUtm_i().
Variable Documentation
geoid_height
int32_t geoid_height
Definition at line 62 of file traffic_info.c.
Referenced by acInfoCalcPositionLla_f(), acInfoCalcPositionLla_i(), acInfoCalcPositionUtm_f(), acInfoCalcPositionUtm_i(), traffic_info_init(), and update_geoid_height().