Paparazzi UAS: sw/airborne/filters/transport_delay_types.h File Reference
transport_delay_types.h File Reference
Transport delay filter type definitions and array operations.
#include "std.h"
#include "paparazzi.h"
#include "filters/transport_delay.h"
Functions
static void init_transport_delay_array (uint8_t n, struct TransportDelay td_array[restrict n], const uint8_t delay_samples[restrict n], float initial_value[restrict n])
Initialize an array of TransportDelay structures.
static void update_transport_delay_array (uint8_t n, struct TransportDelay td_array[restrict n], const float input_array[restrict n])
Update an array of TransportDelay structures with input values.
static void reset_transport_delay_array (const uint8_t n, struct TransportDelay td_array[restrict n], const float initial_value[restrict n])
Reset an array of TransportDelay structures to specific initial values.
static void get_transport_delay_array (const uint8_t n, const struct TransportDelay td_array[restrict n], float output_array[restrict n])
Get output values from an array of TransportDelay structures.
Detailed Description
Transport delay filter type definitions and array operations.
Definition in file transport_delay_types.h.
Function Documentation
get_transport_delay_array()
static void get_transport_delay_array (const uint8_t n, const struct TransportDelay td_array[restrict n], float output_array[restrict n]) inline static
Get output values from an array of TransportDelay structures.
Parameters
[in] n Number of TransportDelay structures in the array.
[in] td_array Array of TransportDelay structures to get outputs from.
[out] output_array Array to store the output values for each TransportDelay structure.
Definition at line 80 of file transport_delay_types.h.
References foo, and get_transport_delay().
Referenced by stabilization_andi_run().
init_transport_delay_array()
static void init_transport_delay_array (uint8_t n, struct TransportDelay td_array[restrict n], const uint8_t delay_samples[restrict n], float initial_value[restrict n]) inline static
Initialize an array of TransportDelay structures.
Parameters
[in] n Number of TransportDelay structures in the array.
[in,out] td_array Array of TransportDelay structures to initialize.
[in] delay_samples Array of delay samples for each TransportDelay structure.
[in] initial_value Array of initial values to fill the buffers.
Definition at line 38 of file transport_delay_types.h.
References foo, and init_transport_delay().
Referenced by stabilization_andi_init().
reset_transport_delay_array()
static void reset_transport_delay_array (const uint8_t n, struct TransportDelay td_array[restrict n], const float initial_value[restrict n]) inline static
Reset an array of TransportDelay structures to specific initial values.
Parameters
[in] n Number of TransportDelay structures in the array.
[in,out] td_array Array of TransportDelay structures to reset.
[in] initial_value Array of initial values to reset the buffers to.
Definition at line 66 of file transport_delay_types.h.
References foo, and reset_transport_delay().
Referenced by stabilization_andi_enter().
update_transport_delay_array()
static void update_transport_delay_array (uint8_t n, struct TransportDelay td_array[restrict n], const float input_array[restrict n]) inline static
Update an array of TransportDelay structures with input values.
Parameters
[in] n Number of TransportDelay structures in the array.
[in,out] td_array Array of TransportDelay structures to update.
[in] input_array Array of input values for each TransportDelay structure.
Definition at line 52 of file transport_delay_types.h.
References foo, and update_transport_delay().
Referenced by stabilization_andi_run().