Paparazzi UAS: sw/airborne/arch/lpc21/modules/sensors/trig_ext_hw.h File Reference
trig_ext_hw.h File Reference
#include "std.h"
Macros
#define TRIG_EXT_EDGE_RISING 1
falling/rising edge
#define TRIG_EXT_EDGE_FALLING 0
Functions
void TRIG_ISR (void)
void trig_ext_init (void)
Variables
uint32_t trigger_t0
uint32_t delta_t0
volatile bool trig_ext_valid
Macro Definition Documentation
#define TRIG_EXT_EDGE_FALLING 0
Definition at line 10 of file trig_ext_hw.h.
#define TRIG_EXT_EDGE_RISING 1
falling/rising edge
Definition at line 9 of file trig_ext_hw.h.
Function Documentation
void trig_ext_init (void)
Definition at line 26 of file trig_ext_hw.c.
References PPM_CCR_CRF, PPM_CCR_CRI, PPM_CCR_CRR, PPM_PINSEL, PPM_PINSEL_BIT, PPM_PINSEL_VAL, T0CCR, and trig_ext_valid.
Referenced by trigger_ext_init().
void TRIG_ISR (void)
Definition at line 30 of file trigger_ext_hw.c.
References delta_t0, last, msec_of_cpu_ticks(), PPM_CR, trig_ext_valid, TRIGGER_CR, trigger_delta_t0, trigger_ext_valid, and trigger_t0.
Referenced by TIMER0_ISR().
Variable Documentation
uint32_t delta_t0
Definition at line 9 of file trig_ext_hw.c.
Referenced by TRIG_ISR(), and trigger_ext_periodic().
volatile bool trig_ext_valid
Definition at line 10 of file trig_ext_hw.c.
Referenced by trig_ext_init(), TRIG_ISR(), and trigger_ext_periodic().
uint32_t trigger_t0
Definition at line 8 of file trig_ext_hw.c.