Paparazzi UAS: sw/simulator/scilab/q3d/fonts/ttx2scilab.c File Reference
ttx2scilab.c File Reference
#include <glib.h>
Macros
#define BUF_LEN 16384
Functions
static void on_start_element (GMarkupParseContext *context, const gchar *element_name, const gchar **attribute_names, const gchar **attribute_values, gpointer user_data, GError **error)
static void on_text (GMarkupParseContext *context, const gchar *text, gsize text_len, gpointer user_data, GError **error)
static void on_error (GMarkupParseContext *context, GError *error, gpointer user_data)
int main (int rgc, char **argv)
Macro Definition Documentation
BUF_LEN
#define BUF_LEN 16384
Function Documentation
main()
int main (int rgc, char ** argv)
Definition at line 24 of file ttx2scilab.c.
References BUF_LEN, foo, on_error(), on_start_element(), and on_text().
on_error()
static void on_error (GMarkupParseContext * context, GError * error, gpointer user_data) static
Definition at line 76 of file ttx2scilab.c.
Referenced by main().
on_start_element()
static void on_start_element (GMarkupParseContext * context, const gchar * element_name, const gchar ** attribute_names, const gchar ** attribute_values, gpointer user_data, GError ** error) static
Definition at line 47 of file ttx2scilab.c.
References foo.
Referenced by main().
on_text()
static void on_text (GMarkupParseContext * context, const gchar * text, gsize text_len, gpointer user_data, GError ** error) static
Definition at line 66 of file ttx2scilab.c.
Referenced by main().