Paparazzi UAS: sw/airborne/modules/digital_cam/uart_cam_ctrl.c File Reference
uart_cam_ctrl.c File Reference
Control the camera via uart to chdk-ptp.
#include "uart_cam_ctrl.h"
#include "generated/airframe.h"
#include "modules/digital_cam/dc.h"
#include "modules/datalink/telemetry.h"
#include <BOARD_CONFIG>
#include "modules/digital_cam/catia/protocol.h"
#include "state.h"
Macros
#define CameraLinkDev (&((CAMERA_LINK).device))
#define CameraLinkTransmit(c) CameraLinkDev->put_byte(CameraLinkDev->periph, 0, c)
#define CameraLinkChAvailable() CameraLinkDev->char_available(CameraLinkDev->periph)
#define CameraLinkGetch() CameraLinkDev->get_byte(CameraLinkDev->periph)
#define THUMB_MSG_SIZE MORA_PAYLOAD_MSG_SIZE
#define THUMB_COUNT 10
Functions
void digital_cam_uart_event (void)
static void send_thumbnails (struct transport_tx *trans, struct link_device *dev)
void digital_cam_uart_init (void)
void digital_cam_uart_periodic (void)
void dc_send_command (uint8_t cmd)
Send Command To Camera.
Variables
union dc_shot_union dc_shot_msg
union mora_status_union mora_status_msg
int digital_cam_uart_status = 0
int digital_cam_uart_thumbnails = 0
static uint8_t thumbs [THUMB_COUNT][THUMB_MSG_SIZE]
static uint8_t thumb_pointer = 0
Detailed Description
Control the camera via uart to chdk-ptp.
Retrieve thumbnails
Definition in file uart_cam_ctrl.c.
Macro Definition Documentation
CameraLinkChAvailable
#define CameraLinkChAvailable () CameraLinkDev->char_available(CameraLinkDev->periph)
Definition at line 51 of file uart_cam_ctrl.c.
CameraLinkDev
#define CameraLinkDev (&((CAMERA_LINK).device))
Definition at line 49 of file uart_cam_ctrl.c.
CameraLinkGetch
#define CameraLinkGetch () CameraLinkDev->get_byte(CameraLinkDev->periph)
Definition at line 52 of file uart_cam_ctrl.c.
CameraLinkTransmit
#define CameraLinkTransmit (c) CameraLinkDev->put_byte(CameraLinkDev->periph, 0, c)
Definition at line 50 of file uart_cam_ctrl.c.
THUMB_COUNT
#define THUMB_COUNT 10
Definition at line 60 of file uart_cam_ctrl.c.
THUMB_MSG_SIZE
#define THUMB_MSG_SIZE MORA_PAYLOAD_MSG_SIZE
Definition at line 59 of file uart_cam_ctrl.c.
Function Documentation
dc_send_command()
void dc_send_command (uint8_t cmd)
Send Command To Camera.
Definition at line 141 of file uart_cam_ctrl.c.
References LlaCoor_i::alt, State::alt_agl_f, dc_shot_union::bin, dc_shot_union::data, DC_OFF, DC_ON, dc_photo_nr, dc_send_command_common(), dc_send_shot_position(), DC_SHOOT, dc_shot_msg, DC_TALLER, DC_WIDER, LlaCoor_i::lat, LlaCoor_i::lon, MORA_SHOOT, MORA_SHOOT_MSG_SIZE, MoraHeader, MoraPutUint8, MoraTrailer, Int32Eulers::phi, POS_BFP_OF_REAL, Int32Eulers::psi, state, stateGetHorizontalSpeedDir_i(), stateGetHorizontalSpeedNorm_i(), stateGetNedToBodyEulers_i(), stateGetPositionLla_i(), and Int32Eulers::theta.
digital_cam_uart_event()
void digital_cam_uart_event (void)
Definition at line 65 of file uart_cam_ctrl.c.
References mora_status_union::bin, CameraLinkChAvailable, CameraLinkGetch, mora_status_union::data, digital_cam_uart_status, MORA_PAYLOAD, MORA_PAYLOAD_MSG_SIZE, mora_protocol, MORA_STATUS, mora_status_msg, MORA_STATUS_MSG_SIZE, mora_transport::msg_id, mora_transport::msg_received, parse_mora(), mora_transport::payload, mora_status_union::mora_status_struct::shots, thumb_pointer, and thumbs.
digital_cam_uart_init()
void digital_cam_uart_init (void)
Definition at line 116 of file uart_cam_ctrl.c.
References DefaultPeriodic, digital_cam_uart_thumbnails, foo, register_periodic_telemetry(), send_thumbnails(), serial_init(), THUMB_COUNT, THUMB_MSG_SIZE, and thumbs.
digital_cam_uart_periodic()
void digital_cam_uart_periodic (void)
Definition at line 133 of file uart_cam_ctrl.c.
References dc_periodic().
send_thumbnails()
static void send_thumbnails (struct transport_tx * trans, struct link_device * dev) static
Definition at line 91 of file uart_cam_ctrl.c.
References dev, digital_cam_uart_thumbnails, foo, MORA_BUFFER_EMPTY, MoraHeader, MoraTrailer, THUMB_COUNT, THUMB_MSG_SIZE, thumb_pointer, and thumbs.
Referenced by digital_cam_uart_init().
Variable Documentation
dc_shot_msg
union dc_shot_union dc_shot_msg
Definition at line 54 of file uart_cam_ctrl.c.
Referenced by dc_send_command().
digital_cam_uart_status
int digital_cam_uart_status = 0
Definition at line 56 of file uart_cam_ctrl.c.
Referenced by digital_cam_uart_event().
digital_cam_uart_thumbnails
int digital_cam_uart_thumbnails = 0
Definition at line 58 of file uart_cam_ctrl.c.
Referenced by digital_cam_uart_init(), and send_thumbnails().
mora_status_msg
union mora_status_union mora_status_msg
Definition at line 55 of file uart_cam_ctrl.c.
Referenced by digital_cam_uart_event().
thumb_pointer
uint8_t thumb_pointer = 0 static
Definition at line 62 of file uart_cam_ctrl.c.
Referenced by digital_cam_uart_event(), and send_thumbnails().
thumbs
uint8_t thumbs[THUMB_COUNT][THUMB_MSG_SIZE] static
Definition at line 61 of file uart_cam_ctrl.c.
Referenced by digital_cam_uart_event(), digital_cam_uart_init(), and send_thumbnails().