Paparazzi UAS: sw/airborne/modules/datalink/uart_print.h File Reference
uart_print.h File Reference
#include "mcu_periph/uart.h"
#include "mcu_periph/usb_serial.h"
#include "pprzlink/pprzlink_device.h"
Macros
#define _PrintString(out_fun, s)
#define _PrintHex(out_fun, c)
#define _PrintHex16(out_fun, c)
#define _PrintHex32(out_fun, c)
#define UsbSPrintHex(c) _PrintHex(VCOM_putchar, c)
#define UsbSPrintHex16(c) _PrintHex16(VCOM_putchar, c)
#define UsbSPrintString(s) _PrintString(VCOM_putchar, s)
Functions
static void print_string (struct link_device *dev, char *s)
static void print_hex (struct link_device *dev, uint8_t c)
static void print_hex16 (struct link_device *dev, uint16_t c)
static void print_hex32 (struct link_device *dev, uint32_t c)
Macro Definition Documentation
_PrintHex
#define _PrintHex (out_fun, c)
Value:
    {     \
    const uint8_t hex[16] = { '0', '1', '2', '3', '4', '5', '6', '7',   \
                              '8', '9', 'A', 'B', 'C', 'D', 'E', 'F' }; \
    uint8_t high = (c & 0xF0)>>4;   \
    uint8_t low  = c & 0x0F;        \
    out_fun(hex[high]);             \
    out_fun(hex[low]);              \
  }
Definition at line 47 of file uart_print.h.
_PrintHex16
#define _PrintHex16 (out_fun, c)
Value:
    {    \
    uint8_t high16 = (uint8_t)(c>>8); \
    uint8_t low16  = (uint8_t)(c);    \
    _PrintHex(out_fun, high16);       \
    _PrintHex(out_fun, low16);        \
  }
Definition at line 67 of file uart_print.h.
_PrintHex32
#define _PrintHex32 (out_fun, c)
Value:
    {        \
    uint16_t high32 = (uint16_t)(c>>16);  \
    uint16_t low32  = (uint16_t)(c);      \
    _PrintHex16(out_fun, high32);         \
    _PrintHex16(out_fun, low32);          \
  }
Definition at line 82 of file uart_print.h.
_PrintString
#define _PrintString (out_fun, s)
Value:
    {  \
    uint8_t i = 0;                  \
    while (s[i]) {                  \
      out_fun(s[i]);                \
      i++;                          \
    }                               \
  }
Definition at line 30 of file uart_print.h.
UsbSPrintHex
#define UsbSPrintHex (c) _PrintHex(VCOM_putchar, c)
Definition at line 160 of file uart_print.h.
UsbSPrintHex16
#define UsbSPrintHex16 (c) _PrintHex16(VCOM_putchar, c)
Definition at line 161 of file uart_print.h.
UsbSPrintString
#define UsbSPrintString (s) _PrintString(VCOM_putchar, s)
Definition at line 162 of file uart_print.h.
Function Documentation
print_hex()
static void print_hex (struct link_device * dev, uint8_t c) inline static
Definition at line 56 of file uart_print.h.
References dev, and foo.
Referenced by print_hex16().
print_hex16()
static void print_hex16 (struct link_device * dev, uint16_t c) inline static
Definition at line 74 of file uart_print.h.
References dev, foo, and print_hex().
Referenced by print_hex32().
print_hex32()
static void print_hex32 (struct link_device * dev, uint32_t c) inline static
Definition at line 89 of file uart_print.h.
References dev, foo, and print_hex16().
print_string()
static void print_string (struct link_device * dev, char * s) inline static
Definition at line 38 of file uart_print.h.
References dev, and s.