Paparazzi UAS: sw/airborne/modules/digital_cam/uart_cam_ctrl.h File Reference
uart_cam_ctrl.h File Reference
Digital Camera Control Over UART with download of thumbnails over the PAYLOAD message.
#include "modules/digital_cam/dc.h"
Functions
void digital_cam_uart_init (void)
void digital_cam_uart_periodic (void)
void digital_cam_uart_event (void)
Variables
int digital_cam_uart_thumbnails
int digital_cam_uart_status
Detailed Description
Digital Camera Control Over UART with download of thumbnails over the PAYLOAD message.
Provides the control of a camera over serial, typically connected to a computer which has full control of all camera functions via USB, including downloading of digital thumbnails
The required initialization (digital_cam_uart_init()) and periodic process.
Definition in file uart_cam_ctrl.h.
Function Documentation
digital_cam_uart_event()
void digital_cam_uart_event (void) extern
Definition at line 65 of file uart_cam_ctrl.c.
References mora_status_union::bin, CameraLinkChAvailable, CameraLinkGetch, mora_status_union::data, digital_cam_uart_status, MORA_PAYLOAD, MORA_PAYLOAD_MSG_SIZE, mora_protocol, MORA_STATUS, mora_status_msg, MORA_STATUS_MSG_SIZE, mora_transport::msg_id, mora_transport::msg_received, parse_mora(), mora_transport::payload, mora_status_union::mora_status_struct::shots, thumb_pointer, and thumbs.
digital_cam_uart_init()
void digital_cam_uart_init (void) extern
Definition at line 116 of file uart_cam_ctrl.c.
References DefaultPeriodic, digital_cam_uart_thumbnails, foo, register_periodic_telemetry(), send_thumbnails(), serial_init(), THUMB_COUNT, THUMB_MSG_SIZE, and thumbs.
digital_cam_uart_periodic()
void digital_cam_uart_periodic (void) extern
Definition at line 133 of file uart_cam_ctrl.c.
References dc_periodic().
Variable Documentation
digital_cam_uart_status
int digital_cam_uart_status extern
Definition at line 56 of file uart_cam_ctrl.c.
Referenced by digital_cam_uart_event().
digital_cam_uart_thumbnails
int digital_cam_uart_thumbnails extern
Definition at line 58 of file uart_cam_ctrl.c.
Referenced by digital_cam_uart_init(), and send_thumbnails().