Paparazzi UAS: sw/airborne/modules/uavcan/uavcan_allocator.h File Reference
uavcan_allocator.h File Reference
#include "inttypes.h"
Data Structures
struct uavcan_unique_id_t
struct uavcan_node_mapping_t
Functions
struct uavcan_node_mapping_t * uavcan_get_node_id_mapping (const uint8_t id)
void request_node_info (struct uavcan_iface_t *iface, uint8_t destination_node_id)
void uavcan_allocator_init (void)
void uavcan_allocator_periodic (void)
Data Structure Documentation
uavcan_unique_id_t
struct uavcan_unique_id_t
Definition at line 16 of file uavcan_allocator.h.
Data Fields
uint8_t data[16]
uint8_t len
uavcan_node_mapping_t
struct uavcan_node_mapping_t
Definition at line 21 of file uavcan_allocator.h.
Data Fields
uint8_t allocated_id
struct uavcan_unique_id_t unique_id
Function Documentation
request_node_info()
void request_node_info (struct uavcan_iface_t * iface, uint8_t destination_node_id)
Definition at line 244 of file uavcan_allocator.c.
References foo, transfer(), and uavcan_request().
Referenced by node_status_cb().
uavcan_allocator_init()
void uavcan_allocator_init (void)
Definition at line 256 of file uavcan_allocator.c.
References foo, id_alloc_ev, id_alloc_uavcan_cb(), node_info_ev, node_info_resp_cb(), and uavcan_bind().
Referenced by uavcan_init().
uavcan_allocator_periodic()
void uavcan_allocator_periodic (void)
uavcan_get_node_id_mapping()
struct uavcan_node_mapping_t * uavcan_get_node_id_mapping (const uint8_t id)
Definition at line 42 of file uavcan_allocator.c.
References uavcan_node_mapping_t::allocated_id, foo, UAVCAN_MAX_NODES, and uavcan_node_ids.
Referenced by findFreeNodeID(), get_free_id_mapping(), node_info_resp_cb(), and node_status_cb().