Paparazzi UAS: sw/airborne/modules/uavcan/uavcan_reporting.h File Reference
uavcan_reporting.h File Reference
Functions
void uavcan_init_reporting (void)
Function Documentation
uavcan_init_reporting()
void uavcan_init_reporting (void)
Definition at line 27 of file uavcan_reporting.c.
References ac_can_name, ac_can_name_len, AC_CAN_NAME_PREFIX, foo, Min, node_info_cb(), node_info_ev, node_status_cb(), node_status_ev, and uavcan_bind().
Referenced by uavcan_init().