Paparazzi UAS: sw/airborne/modules/meteo/lib_ukf_wind_estimator/UKF_Wind_Estimator.c File Reference
UKF_Wind_Estimator.c File Reference
#include "UKF_Wind_Estimator.h"
Functions
static real32_T xnrm2_f (int32_T n, const real32_T x[147], int32_T ix0)
static void xgeqrf_f (real32_T A[147], real32_T tau[7])
static void qr_e (const real32_T A[147], real32_T Q[147], real32_T R[49])
static real32_T xnrm2 (int32_T n, const real32_T x[120], int32_T ix0)
static void xgeqrf (real32_T A[120], real32_T tau[6])
static void qr (const real32_T A[120], real32_T Q[120], real32_T R[36])
static void mrdivide (real32_T A[42], const real32_T B_0[36])
static void h (const real32_T x[7], const real32_T q[4], real32_T y[6])
static void RungeKutta (const real32_T x[7], real32_T dt, const real32_T u[6], real32_T xi[7])
void UKF_Wind_Estimator_step (void)
void UKF_Wind_Estimator_initialize (void)
Variables
ukf_init_type ukf_init
ukf_params_type ukf_params
DW ukf_DW
ExtU ukf_U
ExtY ukf_Y
Function Documentation
h()
static void h (const real32_T x[7], const real32_T q[4], real32_T y[6]) static
Definition at line 821 of file UKF_Wind_Estimator.c.
References foo, and scale.
Referenced by ballistic_touchdown_run(), check_inside(), check_line(), geo_mag_cb(), geo_mag_cb(), geo_mag_cb(), geo_mag_cb(), geo_mag_cb(), geo_mag_cb(), geo_mag_event(), georeference_filter(), georeference_project(), get_avg_disparity(), gvf_parametric_control_2D(), init_gazebo(), mag_calib_update_field(), nps_fdm_set_temperature(), pressure_abs_cb(), qr_code_spi_link_periodic(), rtp_packet_send(), send_jevois_mavlink_visual_target(), snake_up_and_down(), stereocam_parse_msg(), UKF_Wind_Estimator_step(), and undistort_image_func().
mrdivide()
static void mrdivide (real32_T A[42], const real32_T B_0[36]) static
Definition at line 706 of file UKF_Wind_Estimator.c.
References A, foo, and s.
Referenced by UKF_Wind_Estimator_step().
qr()
static void qr (const real32_T A[120], real32_T Q[120], real32_T R[36]) static
Definition at line 576 of file UKF_Wind_Estimator.c.
References A, foo, and xgeqrf().
Referenced by UKF_Wind_Estimator_step().
qr_e()
static void qr_e (const real32_T A[147], real32_T Q[147], real32_T R[49]) static
Definition at line 247 of file UKF_Wind_Estimator.c.
References A, foo, and xgeqrf_f().
Referenced by UKF_Wind_Estimator_step().
RungeKutta()
static void RungeKutta (const real32_T x[7], real32_T dt, const real32_T u[6], real32_T xi[7]) static
Definition at line 917 of file UKF_Wind_Estimator.c.
References foo.
Referenced by UKF_Wind_Estimator_step().
UKF_Wind_Estimator_initialize()
void UKF_Wind_Estimator_initialize (void)
Definition at line 2098 of file UKF_Wind_Estimator.c.
Referenced by init_calculator().
UKF_Wind_Estimator_step()
void UKF_Wind_Estimator_step (void)
Definition at line 1088 of file UKF_Wind_Estimator.c.
References ExtU::accel, ukf_init_tag::alpha, ExtU::aoa, ukf_init_tag::beta, DW::Delay1_DSTATE, DW::Delay_DSTATE, ukf_params_tag::dt, foo, h(), K, ukf_init_tag::ki, lambda, mrdivide(), p, ukf_init_tag::P0, DW::P_not_empty, ExtY::Pout, ukf_params_tag::Q, ExtU::q, qr(), qr_e(), ukf_params_tag::R, ExtU::rates, RungeKutta(), ExtU::sideslip, ukf_DW, ukf_init, ukf_params, ukf_U, ukf_Y, ExtU::va, ExtU::vk, ukf_init_tag::x0, DW::x_not_empty, and ExtY::xout.
Referenced by wind_estimator_step().
xgeqrf()
static void xgeqrf (real32_T A[120], real32_T tau[6]) static
Definition at line 412 of file UKF_Wind_Estimator.c.
References A, f, foo, g, and xnrm2().
Referenced by qr().
xgeqrf_f()
static void xgeqrf_f (real32_T A[147], real32_T tau[7]) static
Definition at line 83 of file UKF_Wind_Estimator.c.
References A, f, foo, g, and xnrm2_f().
Referenced by qr_e().
xnrm2()
static real32_T xnrm2 (int32_T n, const real32_T x[120], int32_T ix0) static
Definition at line 377 of file UKF_Wind_Estimator.c.
References foo, and scale.
Referenced by xgeqrf().
xnrm2_f()
static real32_T xnrm2_f (int32_T n, const real32_T x[147], int32_T ix0) static
Definition at line 48 of file UKF_Wind_Estimator.c.
References foo, and scale.
Referenced by xgeqrf_f().
Variable Documentation
ukf_DW
DW ukf_DW
Definition at line 27 of file UKF_Wind_Estimator.c.
Referenced by init_calculator(), and UKF_Wind_Estimator_step().
ukf_init
ukf_init_type ukf_init
Definition at line 23 of file UKF_Wind_Estimator.c.
Referenced by init_calculator(), UKF_Wind_Estimator_step(), and wind_estimator_step().
ukf_params
ukf_params_type ukf_params
Definition at line 24 of file UKF_Wind_Estimator.c.
Referenced by init_calculator(), UKF_Wind_Estimator_step(), wind_estimator_periodic(), wind_estimator_Set_Q_VA(), wind_estimator_Set_Q_VA_SCALE(), wind_estimator_Set_Q_WIND(), wind_estimator_Set_R_AOA(), wind_estimator_Set_R_GS(), wind_estimator_Set_R_SSA(), wind_estimator_Set_R_VA(), and wind_estimator_step().
ukf_U
ExtU ukf_U
Definition at line 30 of file UKF_Wind_Estimator.c.
Referenced by init_calculator(), UKF_Wind_Estimator_step(), wind_estimator_periodic(), and wind_estimator_step().
ukf_Y
ExtY ukf_Y
Definition at line 33 of file UKF_Wind_Estimator.c.
Referenced by init_calculator(), UKF_Wind_Estimator_step(), and wind_estimator_step().