Paparazzi UAS: sw/airborne/boards/umarim/baro_board.c File Reference
baro_board.c File Reference
#include "std.h"
#include "baro_board.h"
#include "subsystems/sensors/baro.h"
#include "peripherals/ads1114.h"
#include "subsystems/abi.h"
#include "led.h"
Macros
#define BARO_ABS_ADS ads1114_1
#define UMARIM_BARO_SENS 0.0274181
#define BARO_STARTUP_COUNTER 200
Functions
void baro_init (void)
void baro_periodic (void)
void umarim_baro_event (void)
Variables
uint16_t startup_cnt
Macro Definition Documentation
#define BARO_ABS_ADS ads1114_1
Definition at line 37 of file baro_board.c.
Referenced by baro_periodic(), and umarim_baro_event().
#define BARO_STARTUP_COUNTER 200
Definition at line 46 of file baro_board.c.
Referenced by baro_init().
#define UMARIM_BARO_SENS 0.0274181
Definition at line 42 of file baro_board.c.
Referenced by umarim_baro_event().
Function Documentation
void baro_init (void)
Definition at line 49 of file baro_board.c.
References ads1114_init(), apogee_baro, BARO_STARTUP_COUNTER, LED_OFF, MPL3115_I2C_ADDR, mpl3115_init(), and startup_cnt.
void baro_periodic (void)
Definition at line 58 of file baro_board.c.
References ads1114_read(), apogee_baro, BARO_ABS_ADS, Mpu60x0_I2c::config, Mpl3115::data_available, imu_apogee, Mpu60x0Config::initialized, LED_ON, LED_TOGGLE, mpl3115_periodic(), MPL_PRESCALER, ImuApogee::mpu, and startup_cnt.
void umarim_baro_event (void)
Definition at line 75 of file baro_board.c.
References Ads1114Event, Ads1114GetValue, BARO_ABS_ADS, BARO_BOARD_SENDER_ID, get_sys_time_usec(), startup_cnt, and UMARIM_BARO_SENS.
Variable Documentation
uint16_t startup_cnt
Definition at line 47 of file baro_board.c.