Paparazzi UAS: sw/airborne/modules/com/usb_serial_stm32.h File Reference
usb_serial_stm32.h File Reference
header for serial over USB modules
#include "mcu_periph/usb_serial.h"
Functions
void init_usb_serial (void)
Init module, call VCOM_init() from here.
void periodic_usb_serial (void)
Periodic function in case you needed to send data periodically like telemetry Note that the data are sent once the buffer is full, not immediately.
void event_usb_serial (void)
Call VCOM_poll() from module event function.
void usb_serial_parse_packet (int c)
Parse data from buffer Note that the function receives int, not char Because we want to be able to catch -1 in case no more data were available.
Detailed Description
header for serial over USB modules
Definition in file usb_serial_stm32.h.
Function Documentation
event_usb_serial()
void event_usb_serial (void)
Call VCOM_poll() from module event function.
Definition at line 126 of file usb_serial_stm32_example1.c.
References cmd_avail, cmd_execute(), ReadUsbBuffer(), usb_serial_parse_packet(), VCOM_check_available(), VCOM_event(), and VCOM_getchar().
init_usb_serial()
void init_usb_serial (void)
Init module, call VCOM_init() from here.
Definition at line 44 of file usb_serial_stm32_example1.c.
References cmd_avail, cmd_idx, run, and VCOM_init().
periodic_usb_serial()
void periodic_usb_serial (void)
Periodic function in case you needed to send data periodically like telemetry Note that the data are sent once the buffer is full, not immediately.
Definition at line 55 of file usb_serial_stm32_example2.c.
References big_buffer, run, and VCOM_putchar().
usb_serial_parse_packet()
void usb_serial_parse_packet (int c)
Parse data from buffer Note that the function receives int, not char Because we want to be able to catch -1 in case no more data were available.
Definition at line 58 of file usb_serial_stm32_example1.c.
References cmd_avail, cmd_buf, cmd_idx, foo, prompt, run, VCOM_putchar(), and VCOM_send_message().
Referenced by event_usb_serial(), and ReadUsbBuffer().