Paparazzi UAS: sw/airborne/firmwares/setup/usb_tunnel.c File Reference
usb_tunnel.c File Reference
USB tunnel application.
#include "std.h"
#include "mcu.h"
#include "mcu_periph/sys_time.h"
#include "led.h"
#include "mcu_periph/uart.h"
#include "mcu_periph/usb_serial.h"
Macros
#define BLINK_MIN 100
minimum LED blink on time in ms
Functions
static void tunnel_event (void)
int main (void)
Detailed Description
USB tunnel application.
This creates a USB serial port that connects to one of the UARTs. This enables you to e.g. configure the gps receiver or the modem without removing it.
Definition in file usb_tunnel.c.
Macro Definition Documentation
#define BLINK_MIN 100
minimum LED blink on time in ms
Definition at line 50 of file usb_tunnel.c.
Referenced by tunnel_event().
Function Documentation
int main (void)
Definition at line 88 of file usb_tunnel.c.
References led_init(), mcu_init(), mcu_int_enable, sys_time_init(), tunnel_event(), VCOM_allow_linecoding(), VCOM_event(), and VCOM_init().
static void tunnel_event (void) inline static
Definition at line 52 of file usb_tunnel.c.
References BLINK_MIN, fd, get_sys_time_msec(), LED_OFF, LED_ON, uart_char_available(), uart_check_free_space(), uart_getch(), uart_put_byte(), VCOM_check_available(), VCOM_check_free_space(), VCOM_getchar(), and VCOM_putchar().
Referenced by main().