Paparazzi UAS: sw/airborne/modules/loggers/sdlog_chibios/usbStorage.h File Reference
usbStorage.h File Reference
#include <ch.h>
Functions
void usbStorageStartPolling (void)
void usbStorageStop (void)
void usbStorageWaitForDeconnexion (void)
bool usbStorageIsItRunning (void)
void usbStorage_enable_usb_storage (float e)
Variables
float usb_storage_status
Function Documentation
usbStorage_enable_usb_storage()
void usbStorage_enable_usb_storage (float e) extern
Definition at line 171 of file usbStorage.c.
References foo, SDLOG_USB_VBUS_PIN, SDLOG_USB_VBUS_PORT, and usb_storage_status.
usbStorageIsItRunning()
bool usbStorageIsItRunning (void)
Definition at line 163 of file usbStorage.c.
References isRunning.
Referenced by thd_startlog().
usbStorageStartPolling()
void usbStorageStartPolling (void)
Definition at line 76 of file usbStorage.c.
References foo, thdUsbStorage(), and usbStorageThreadPtr.
Referenced by sdlog_chibios_init().
usbStorageStop()
void usbStorageStop (void)
Definition at line 92 of file usbStorage.c.
References foo, and usbStorageThreadPtr.
usbStorageWaitForDeconnexion()
void usbStorageWaitForDeconnexion (void)
Definition at line 84 of file usbStorage.c.
References foo, and usbStorageThreadPtr.
Variable Documentation
usb_storage_status
float usb_storage_status extern
Definition at line 48 of file usbStorage.c.
Referenced by thdUsbStorage(), and usbStorage_enable_usb_storage().