Paparazzi UAS: sw/airborne/modules/decawave/uwb_positioning.h File Reference
uwb_positioning.h File Reference
#include "std.h"
Macros
#define PRIMARY_GPS GPS_UWB
Functions
void uwb_positioning_update_ekf_q (float v)
settings handler
void uwb_positioning_update_ekf_r_dist (float v)
void uwb_positioning_update_ekf_r_speed (float v)
void uwb_positioning_init (void)
void uwb_positioning_periodic (void)
void uwb_positioning_range_periodic (void)
void uwb_positioning_report (void)
void uwb_positioning_reset_heading_ref (void)
Reset reference heading to current heading AHRS/INS should be aligned before calling this function.
void uwb_range (uint16_t id)
Weak empty implementation.
Variables
bool uwb_positioning_use_ekf
enable EKF filtering
float uwb_positioning_ekf_q
process and measurements noise
float uwb_positioning_ekf_r_dist
float uwb_positioning_ekf_r_speed
Detailed Description
Author
Gautier Hattenberger UWB positioning from anchor measurements.
Definition in file uwb_positioning.h.
Macro Definition Documentation
PRIMARY_GPS
#define PRIMARY_GPS GPS_UWB
Definition at line 54 of file uwb_positioning.h.
Function Documentation
uwb_positioning_init()
void uwb_positioning_init (void) extern
Definition at line 465 of file uwb_positioning.c.
References ABI_BROADCAST, UwbPositioning::anchor_ranging_idx, UwbPositioning::anchors, GpsState::cacc, GpsState::comp_id, Anchor::distance, UwbPositioning::ekf_range, ekf_range_init(), UwbPositioning::ekf_running, GpsState::fix, foo, GPS_FIX_NONE, UwbPositioning::gps_uwb, GPS_UWB_ID, Anchor::id, ids, init_median_filter_f(), UwbPositioning::initial_heading, LlaCoor_i::lat, UwbPositioning::ltp_def, ltp_def_from_lla_i(), UwbPositioning::mf, GpsState::pacc, GpsState::pdop, Anchor::pos, UwbPositioning::pos, pos_x, pos_y, pos_z, UwbPositioning::raw_dist, GpsState::sacc, UwbPositioning::speed, Anchor::time, trilateration_init(), Anchor::updated, UwbPositioning::updated, uwb_positioning, uwb_positioning_ekf_q, uwb_positioning_ekf_r_dist, uwb_positioning_ekf_r_speed, UWB_POSITIONING_INITIAL_HEADING, UWB_POSITIONING_NB_ANCHORS, UWB_POSITIONING_USE_EKF, uwb_positioning_use_ekf, uwb_ranging_cb(), uwb_ranging_ev, EnuCoor_f::x, EnuCoor_f::y, and EnuCoor_f::z.
uwb_positioning_periodic()
void uwb_positioning_periodic (void) extern
Definition at line 521 of file uwb_positioning.c.
References UwbPositioning::ekf_range, ekf_range_get_pos(), ekf_range_get_speed(), ekf_range_predict(), UwbPositioning::ekf_running, foo, gps_periodic_check(), UwbPositioning::gps_uwb, log_started, UwbPositioning::pos, pprzLogFile, process_data(), UwbPositioning::speed, uwb_positioning, and uwb_positioning_use_ekf.
uwb_positioning_range_periodic()
void uwb_positioning_range_periodic (void) extern
Definition at line 552 of file uwb_positioning.c.
References UwbPositioning::anchor_ranging_idx, UwbPositioning::anchors, foo, uwb_positioning, UWB_POSITIONING_NB_ANCHORS, and uwb_range().
uwb_positioning_report()
void uwb_positioning_report (void) extern
Definition at line 558 of file uwb_positioning.c.
References UwbPositioning::anchors, DefaultChannel, DefaultDevice, Anchor::distance, foo, UwbPositioning::pos, UwbPositioning::raw_dist, UwbPositioning::speed, uwb_positioning, EnuCoor_f::x, EnuCoor_f::y, and EnuCoor_f::z.
uwb_positioning_reset_heading_ref()
void uwb_positioning_reset_heading_ref (void) extern
Reset reference heading to current heading AHRS/INS should be aligned before calling this function.
Definition at line 415 of file uwb_positioning.c.
References foo, UwbPositioning::initial_heading, FloatEulers::psi, stateGetNedToBodyEulers_f(), and uwb_positioning.
uwb_positioning_update_ekf_q()
void uwb_positioning_update_ekf_q (float v) extern
settings handler
Definition at line 579 of file uwb_positioning.c.
References UwbPositioning::ekf_range, ekf_range_update_noise(), uwb_positioning, uwb_positioning_ekf_q, uwb_positioning_ekf_r_dist, and uwb_positioning_ekf_r_speed.
uwb_positioning_update_ekf_r_dist()
void uwb_positioning_update_ekf_r_dist (float v) extern
Definition at line 585 of file uwb_positioning.c.
References UwbPositioning::ekf_range, ekf_range_update_noise(), uwb_positioning, uwb_positioning_ekf_q, uwb_positioning_ekf_r_dist, and uwb_positioning_ekf_r_speed.
uwb_positioning_update_ekf_r_speed()
void uwb_positioning_update_ekf_r_speed (float v) extern
Definition at line 591 of file uwb_positioning.c.
References UwbPositioning::ekf_range, ekf_range_update_noise(), uwb_positioning, uwb_positioning_ekf_q, uwb_positioning_ekf_r_dist, and uwb_positioning_ekf_r_speed.
uwb_range()
void uwb_range (uint16_t id)
Weak empty implementation.
Definition at line 433 of file pdec.c.
References pdec_target_cmd_payload::dst_id, and pdec_range().
Referenced by uwb_positioning_range_periodic().
Variable Documentation
uwb_positioning_ekf_q
float uwb_positioning_ekf_q extern
process and measurements noise
Definition at line 187 of file uwb_positioning.c.
Referenced by uwb_positioning_init(), uwb_positioning_update_ekf_q(), uwb_positioning_update_ekf_r_dist(), and uwb_positioning_update_ekf_r_speed().
uwb_positioning_ekf_r_dist
float uwb_positioning_ekf_r_dist extern
Definition at line 188 of file uwb_positioning.c.
Referenced by uwb_positioning_init(), uwb_positioning_update_ekf_q(), uwb_positioning_update_ekf_r_dist(), and uwb_positioning_update_ekf_r_speed().
uwb_positioning_ekf_r_speed
float uwb_positioning_ekf_r_speed extern
Definition at line 189 of file uwb_positioning.c.
Referenced by uwb_positioning_init(), uwb_positioning_update_ekf_q(), uwb_positioning_update_ekf_r_dist(), and uwb_positioning_update_ekf_r_speed().
uwb_positioning_use_ekf
bool uwb_positioning_use_ekf extern
enable EKF filtering
Definition at line 186 of file uwb_positioning.c.
Referenced by check_and_compute_data(), uwb_positioning_init(), and uwb_positioning_periodic().