Paparazzi UAS: sw/airborne/modules/computer_vision/video_capture.h File Reference
video_capture.h File Reference
#include <stdbool.h>
Functions
void video_capture_init (void)
void video_capture_shoot (void)
void video_capture_start_capture (void)
void video_capture_stop_capture (void)
Variables
bool video_capture_take_shot
bool video_capture_record_video
Function Documentation
video_capture_init()
void video_capture_init (void) extern
Definition at line 68 of file video_capture.c.
References cv_add_to_device(), foo, save_dir, VIDEO_CAPTURE_FPS, video_capture_func(), and VIDEO_CAPTURE_PATH.
video_capture_shoot()
void video_capture_shoot (void) extern
Definition at line 100 of file video_capture.c.
References video_capture_take_shot.
Referenced by dc_send_command().
video_capture_start_capture()
void video_capture_start_capture (void) extern
Definition at line 106 of file video_capture.c.
References video_capture_record_video.
video_capture_stop_capture()
void video_capture_stop_capture (void) extern
Definition at line 110 of file video_capture.c.
References video_capture_record_video.
Variable Documentation
video_capture_record_video
bool video_capture_record_video extern
Definition at line 57 of file video_capture.c.
Referenced by video_capture_func(), video_capture_start_capture(), and video_capture_stop_capture().
video_capture_take_shot
bool video_capture_take_shot extern
Definition at line 56 of file video_capture.c.
Referenced by video_capture_func(), and video_capture_shoot().