Paparazzi UAS: sw/airborne/modules/computer_vision/lib/v4l/virt2phys.h File Reference
virt2phys.h File Reference
#include <sys/types.h>
#include <unistd.h>
Data Structures
struct physmem
Functions
int check_contiguity (unsigned long vaddr, pid_t pid, struct physmem *pmem, size_t size)
Data Structure Documentation
physmem
struct physmem
Definition at line 7 of file virt2phys.h.
Data Fields
unsigned long paddr
size_t size
Function Documentation
check_contiguity()
int check_contiguity (unsigned long vaddr, pid_t pid, struct physmem * pmem, size_t size)
Definition at line 111 of file virt2phys.c.
References fd, foo, open_pagemap(), PAGE_MASK, PAGE_SIZE, and virt2phys().
Referenced by v4l2_init().