Paparazzi UAS: sw/airborne/peripherals/vl53l1_platform.c File Reference
vl53l1_platform.c File Reference
#include "vl53l1_platform.h"
#include <string.h>
#include <time.h>
#include <math.h>
#include <assert.h>
Functions
int8_t VL53L1_WriteMulti (VL53L1_DEV dev, uint16_t index, uint8_t *pdata, uint32_t count)
VL53L1_WriteMulti() definition.
int8_t VL53L1_ReadMulti (VL53L1_DEV dev, uint16_t index, uint8_t *pdata, uint32_t count)
VL53L1_ReadMulti() definition.
int8_t VL53L1_WrByte (VL53L1_DEV dev, uint16_t index, uint8_t data)
VL53L1_WrByte() definition.
int8_t VL53L1_WrWord (VL53L1_DEV dev, uint16_t index, uint16_t data)
VL53L1_WrWord() definition.
int8_t VL53L1_WrDWord (VL53L1_DEV dev, uint16_t index, uint32_t data)
VL53L1_WrDWord() definition.
int8_t VL53L1_RdByte (VL53L1_DEV dev, uint16_t index, uint8_t *data)
VL53L1_RdByte() definition.
int8_t VL53L1_RdWord (VL53L1_DEV dev, uint16_t index, uint16_t *data)
VL53L1_RdWord() definition.
int8_t VL53L1_RdDWord (VL53L1_DEV dev, uint16_t index, uint32_t *data)
VL53L1_RdDWord() definition.
Function Documentation
VL53L1_RdByte()
int8_t VL53L1_RdByte (VL53L1_DEV dev, uint16_t index, uint8_t * pdata)
VL53L1_RdByte() definition.
To be implemented by the developer
Definition at line 89 of file vl53l1_platform.c.
References dev, and VL53L1_ReadMulti().
Referenced by VL53L1X_BootState(), VL53L1X_CheckForDataReady(), VL53L1X_GetDistanceMode(), VL53L1X_GetDistanceThresholdWindow(), VL53L1X_GetInterruptPolarity(), VL53L1X_GetRangeStatus(), VL53L1X_GetROI_XY(), VL53L1X_GetROICenter(), VL53L1X_SetDistanceThreshold(), VL53L1X_SetInterruptPolarity(), and VL53L1X_SetROI().
VL53L1_RdDWord()
int8_t VL53L1_RdDWord (VL53L1_DEV dev, uint16_t index, uint32_t * pdata)
VL53L1_RdDWord() definition.
To be implemented by the developer
Definition at line 102 of file vl53l1_platform.c.
References dev, foo, and VL53L1_ReadMulti().
Referenced by VL53L1X_GetInterMeasurementInMs(), and VL53L1X_GetXtalk().
VL53L1_RdWord()
int8_t VL53L1_RdWord (VL53L1_DEV dev, uint16_t index, uint16_t * pdata)
VL53L1_RdWord() definition.
To be implemented by the developer
Definition at line 94 of file vl53l1_platform.c.
References dev, foo, and VL53L1_ReadMulti().
Referenced by VL53L1X_GetAmbientPerSpad(), VL53L1X_GetAmbientRate(), VL53L1X_GetDistance(), VL53L1X_GetDistanceThresholdHigh(), VL53L1X_GetDistanceThresholdLow(), VL53L1X_GetInterMeasurementInMs(), VL53L1X_GetOffset(), VL53L1X_GetSensorId(), VL53L1X_GetSigmaThreshold(), VL53L1X_GetSignalPerSpad(), VL53L1X_GetSignalRate(), VL53L1X_GetSignalThreshold(), VL53L1X_GetSpadNb(), VL53L1X_GetTimingBudgetInMs(), and VL53L1X_SetInterMeasurementInMs().
VL53L1_ReadMulti()
int8_t VL53L1_ReadMulti (VL53L1_DEV dev, uint16_t index, uint8_t * pdata, uint32_t count)
VL53L1_ReadMulti() definition.
To be implemented by the developer
Definition at line 53 of file vl53l1_platform.c.
References dev, foo, i2c_blocking_transceive(), and I2C_BUF_LEN.
Referenced by VL53L1_RdByte(), VL53L1_RdDWord(), VL53L1_RdWord(), and VL53L1X_GetResult().
VL53L1_WrByte()
int8_t VL53L1_WrByte (VL53L1_DEV dev, uint16_t index, uint8_t data)
VL53L1_WrByte() definition.
To be implemented by the developer
Definition at line 64 of file vl53l1_platform.c.
References dev, and VL53L1_WriteMulti().
Referenced by VL53L1X_ClearInterrupt(), VL53L1X_SensorInit(), VL53L1X_SetDistanceMode(), VL53L1X_SetDistanceThreshold(), VL53L1X_SetI2CAddress(), VL53L1X_SetInterruptPolarity(), VL53L1X_SetROI(), VL53L1X_SetROICenter(), VL53L1X_StartRanging(), VL53L1X_StartTemperatureUpdate(), and VL53L1X_StopRanging().
VL53L1_WrDWord()
int8_t VL53L1_WrDWord (VL53L1_DEV dev, uint16_t index, uint32_t data)
VL53L1_WrDWord() definition.
To be implemented by the developer
Definition at line 78 of file vl53l1_platform.c.
References dev, foo, and VL53L1_WriteMulti().
Referenced by VL53L1X_SetInterMeasurementInMs().
VL53L1_WriteMulti()
int8_t VL53L1_WriteMulti (VL53L1_DEV dev, uint16_t index, uint8_t * pdata, uint32_t count)
VL53L1_WriteMulti() definition.
To be implemented by the developer
Definition at line 43 of file vl53l1_platform.c.
References dev, foo, i2c_blocking_transmit(), and I2C_BUF_LEN.
Referenced by VL53L1_WrByte(), VL53L1_WrDWord(), and VL53L1_WrWord().
VL53L1_WrWord()
int8_t VL53L1_WrWord (VL53L1_DEV dev, uint16_t index, uint16_t data)
VL53L1_WrWord() definition.
To be implemented by the developer
Definition at line 69 of file vl53l1_platform.c.
References dev, foo, and VL53L1_WriteMulti().
Referenced by VL53L1X_SetDistanceMode(), VL53L1X_SetDistanceThreshold(), VL53L1X_SetOffset(), VL53L1X_SetSigmaThreshold(), VL53L1X_SetSignalThreshold(), VL53L1X_SetTimingBudgetInMs(), and VL53L1X_SetXtalk().