Paparazzi UAS: sw/airborne/modules/wedgebug/wedgebug_opencv.h File Reference
wedgebug_opencv.h File Reference
#include "modules/computer_vision/lib/vision/image.h"
#include "modules/wedgebug/wedgebug.h"
Functions
int save_image_gray (struct image_t *img, char *myString)
int save_image_color (struct image_t *img, char *myString)
int save_image_HM (struct image_t *img, char *myString, int const heatmap)
int SBM_OCV (struct image_t *img_disp, const struct image_t *img_left, const struct image_t *img_right, const int ndisparities, const int SADWindowSize, const bool cropped)
int opening_OCV (struct image_t *img_input, const struct image_t *img_output, const int SE_size, const int iteration)
int closing_OCV (struct image_t *img_input, const struct image_t *img_output, const int SE_size, const int iteration)
int dilation_OCV (struct image_t *img_input, const struct image_t *img_output, const int SE_size, const int iteration)
int erosion_OCV (struct image_t *img_input, const struct image_t *img_output, const int SE_size, const int iteration)
int sobel_OCV (struct image_t *img_input, const struct image_t *img_output, const int kernel_size, const int thr)
Detailed Description
Author
Ralph Rudi schmidt ralph.nosp@m..r.s.nosp@m.chmid.nosp@m.t@ou.nosp@m.tlook.nosp@m..com OpenCV functions to be used for the wedebug.
Definition in file wedgebug_opencv.h.
Function Documentation
int closing_OCV (struct image_t * img_input, const struct image_t * img_output, const int SE_size, const int iteration)
Definition at line 304 of file wedgebug_opencv.cpp.
References image_t::buf, image_t::h, IMAGE_GRAYSCALE, IMAGE_INT16, transfer(), image_t::type, and image_t::w.
Referenced by background_processes(), and background_processes_16bit().
int dilation_OCV (struct image_t * img_input, const struct image_t * img_output, const int SE_size, const int iteration)
Definition at line 330 of file wedgebug_opencv.cpp.
References image_t::buf, image_t::h, IMAGE_GRAYSCALE, IMAGE_INT16, transfer(), image_t::type, and image_t::w.
Referenced by background_processes(), and background_processes_16bit().
int erosion_OCV (struct image_t * img_input, const struct image_t * img_output, const int SE_size, const int iteration)
Definition at line 355 of file wedgebug_opencv.cpp.
References image_t::buf, image_t::h, IMAGE_GRAYSCALE, IMAGE_INT16, transfer(), image_t::type, and image_t::w.
Referenced by background_processes_16bit().
int opening_OCV (struct image_t * img_input, const struct image_t * img_output, const int SE_size, const int iteration)
Definition at line 277 of file wedgebug_opencv.cpp.
References image_t::buf, image_t::h, IMAGE_GRAYSCALE, IMAGE_INT16, transfer(), image_t::type, and image_t::w.
Referenced by background_processes(), and background_processes_16bit().
int save_image_color (struct image_t * img, char * myString)
Definition at line 94 of file wedgebug_opencv.cpp.
References image_t::buf, image_t::h, and image_t::w.
int save_image_gray (struct image_t * img, char * myString)
Definition at line 69 of file wedgebug_opencv.cpp.
References image_t::buf, image_t::h, IMAGE_GRAYSCALE, IMAGE_INT16, image_t::type, and image_t::w.
Referenced by background_processes(), background_processes_16bit(), and wedgebug_periodic().
int save_image_HM (struct image_t * img, char * myString, int const heatmap)
Definition at line 116 of file wedgebug_opencv.cpp.
References image_t::buf, image_t::h, IMAGE_GRAYSCALE, IMAGE_INT16, image_t::type, and image_t::w.
Referenced by background_processes(), background_processes_16bit(), and wedgebug_periodic().
int SBM_OCV (struct image_t * img_disp, const struct image_t * img_left, const struct image_t * img_right, const int ndisparities, const int SADWindowSize, const bool cropped)
Definition at line 168 of file wedgebug_opencv.cpp.
References image_t::buf, image_t::h, crop_t::h, IMAGE_GRAYSCALE, IMAGE_INT16, post_disparity_crop_rect(), image_t::type, image_t::w, crop_t::w, crop_t::x, and crop_t::y.
Referenced by background_processes(), and background_processes_16bit().
int sobel_OCV (struct image_t * img_input, const struct image_t * img_output, const int kernel_size, const int thr)
Definition at line 380 of file wedgebug_opencv.cpp.
References image_t::buf, image_t::h, IMAGE_GRAYSCALE, IMAGE_INT16, scale, transfer(), image_t::type, and image_t::w.
Referenced by background_processes(), and background_processes_16bit().