Paparazzi UAS: sw/airborne/modules/wedgebug/wedgebug_opencv.cpp File Reference
wedgebug_opencv.cpp File Reference
#include "wedgebug_opencv.h"
#include <opencv2/core/core.hpp>
#include <opencv2/imgproc/imgproc.hpp>
#include <opencv2/imgproc/types_c.h>
#include <opencv2/imgcodecs/imgcodecs.hpp>
#include <opencv2/calib3d/calib3d.hpp>
#include <iostream>
#include <stdint.h>
Functions
int transfer (const Mat *from, const image_t *to)
int save_image_gray (struct image_t *img, char *myString)
int save_image_color (struct image_t *img, char *myString)
int save_image_HM (struct image_t *img, char *myString, int const heatmap)
int SBM_OCV (struct image_t *img_disp, const struct image_t *img_left, const struct image_t *img_right, const int ndisparities, const int SADWindowSize, const bool cropped)
int opening_OCV (struct image_t *img_input, const struct image_t *img_output, const int SE_size, const int iteration)
int closing_OCV (struct image_t *img_input, const struct image_t *img_output, const int SE_size, const int iteration)
int dilation_OCV (struct image_t *img_input, const struct image_t *img_output, const int SE_size, const int iteration)
int erosion_OCV (struct image_t *img_input, const struct image_t *img_output, const int SE_size, const int iteration)
int sobel_OCV (struct image_t *img_input, const struct image_t *img_output, const int kernel_size, const int thr)
Function Documentation
closing_OCV()
int closing_OCV (struct image_t * img_input, const struct image_t * img_output, const int SE_size, const int iteration)
Definition at line 304 of file wedgebug_opencv.cpp.
References foo, IMAGE_GRAYSCALE, IMAGE_INT16, and transfer().
Referenced by background_processes(), and background_processes_16bit().
dilation_OCV()
int dilation_OCV (struct image_t * img_input, const struct image_t * img_output, const int SE_size, const int iteration)
Definition at line 330 of file wedgebug_opencv.cpp.
References foo, IMAGE_GRAYSCALE, IMAGE_INT16, and transfer().
Referenced by background_processes(), and background_processes_16bit().
erosion_OCV()
int erosion_OCV (struct image_t * img_input, const struct image_t * img_output, const int SE_size, const int iteration)
Definition at line 355 of file wedgebug_opencv.cpp.
References foo, IMAGE_GRAYSCALE, IMAGE_INT16, and transfer().
Referenced by background_processes_16bit().
opening_OCV()
int opening_OCV (struct image_t * img_input, const struct image_t * img_output, const int SE_size, const int iteration)
Definition at line 277 of file wedgebug_opencv.cpp.
References foo, IMAGE_GRAYSCALE, IMAGE_INT16, and transfer().
Referenced by background_processes(), and background_processes_16bit().
save_image_color()
int save_image_color (struct image_t * img, char * myString)
Definition at line 94 of file wedgebug_opencv.cpp.
References foo.
save_image_gray()
int save_image_gray (struct image_t * img, char * myString)
Definition at line 69 of file wedgebug_opencv.cpp.
References foo, IMAGE_GRAYSCALE, and IMAGE_INT16.
Referenced by background_processes(), background_processes_16bit(), and wedgebug_periodic().
save_image_HM()
int save_image_HM (struct image_t * img, char * myString, int const heatmap)
Definition at line 116 of file wedgebug_opencv.cpp.
References foo, IMAGE_GRAYSCALE, and IMAGE_INT16.
Referenced by background_processes(), background_processes_16bit(), and wedgebug_periodic().
SBM_OCV()
int SBM_OCV (struct image_t * img_disp, const struct image_t * img_left, const struct image_t * img_right, const int ndisparities, const int SADWindowSize, const bool cropped)
Definition at line 168 of file wedgebug_opencv.cpp.
References image_t::buf, foo, image_t::h, crop_t::h, IMAGE_GRAYSCALE, IMAGE_INT16, img_cropped_info, img_left, img_right, post_disparity_crop_rect(), image_t::w, crop_t::w, crop_t::x, and crop_t::y.
Referenced by background_processes(), and background_processes_16bit().
sobel_OCV()
int sobel_OCV (struct image_t * img_input, const struct image_t * img_output, const int kernel_size, const int thr)
Definition at line 380 of file wedgebug_opencv.cpp.
References foo, IMAGE_GRAYSCALE, IMAGE_INT16, scale, and transfer().
Referenced by background_processes(), and background_processes_16bit().
transfer()
int transfer (const Mat * from, const image_t * to)
Definition at line 40 of file wedgebug_opencv.cpp.
References image_t::buf, foo, IMAGE_GRAYSCALE, IMAGE_INT16, and image_t::type.
Referenced by actuators_uavcan_actuator_status_cb(), actuators_uavcan_device_temperature_cb(), actuators_uavcan_esc_status_cb(), airspeed_uavcan_cb(), closing_OCV(), dilation_OCV(), erosion_OCV(), fuelcell_uavcan_cb(), get_transfer_id(), gps_uavcan_cb(), id_alloc_uavcan_cb(), mag_uavcan_cb(), mag_uavcan_cb2(), node_info_cb(), node_info_resp_cb(), node_status_cb(), onTransferReceived(), opening_OCV(), power_uavcan_battery_cb(), power_uavcan_circuit_cb(), range_sensor_uavcan_cb(), rc_uavcan_cb(), request_node_info(), sobel_OCV(), tunnel_uavcan_cb(), uavcan_broadcast(), uavcan_request(), uavcan_response(), and uavcan_transfer().