Paparazzi UAS: sw/airborne/modules/meteo/wind_estimator.h File Reference
wind_estimator.h File Reference
Wind Estimator based on generated library from Matlab.
#include "std.h"
#include "math/pprz_algebra_float.h"
Data Structures
struct WindEstimator
Functions
void wind_estimator_init (void)
void wind_estimator_periodic (void)
void wind_estimator_event (void)
void wind_estimator_Set_R_GS (float _v)
void wind_estimator_Set_R_VA (float _v)
void wind_estimator_Set_R_AOA (float _v)
void wind_estimator_Set_R_SSA (float _v)
void wind_estimator_Set_Q_VA (float _v)
void wind_estimator_Set_Q_WIND (float _v)
void wind_estimator_Set_Q_VA_SCALE (float _v)
Variables
struct WindEstimator wind_estimator
Detailed Description
Wind Estimator based on generated library from Matlab.
Original Simulink files available at https://github.com/enacuavlab/UKF_Wind_Estimation
Definition in file wind_estimator.h.
Data Structure Documentation
WindEstimator
struct WindEstimator
Definition at line 35 of file wind_estimator.h.
Data Fields
struct FloatVect3 airspeed airspeed vector in body frame
bool data_available new data available
float q_va noise associated to airspeed vector model
float q_va_scale noise associated to airspeed scale factor model
float q_wind noise associated to wind vector model
float r_aoa noise associated to angle of attack measurement
float r_gs noise associated to ground speed measurement
float r_ssa noise associated to sideslip angle measurement
float r_va noise associated to airspeed norm measurement
bool reset reset filter flag
struct FloatVect3 wind wind vector in NED frame
Function Documentation
wind_estimator_event()
void wind_estimator_event (void) extern
Definition at line 411 of file wind_estimator.c.
References WindEstimator::data_available, DefaultChannel, DefaultDevice, foo, send_wind_estimator(), stateSetHorizontalWindspeed_f(), stateSetVerticalWindspeed_f(), WindEstimator::wind, wind_estimator, FloatVect3::x, FloatVect3::y, and FloatVect3::z.
wind_estimator_init()
void wind_estimator_init (void) extern
Definition at line 464 of file wind_estimator.c.
References counter, DefaultPeriodic, foo, init_calculator(), pprzLogFile, register_periodic_telemetry(), send_wind_estimator(), and thd_windestimate().
wind_estimator_periodic()
void wind_estimator_periodic (void) extern
Definition at line 292 of file wind_estimator.c.
References ExtU::accel, ACCELS_FLOAT_OF_BFP, ExtU::aoa, DefaultChannel, DefaultDevice, ukf_params_tag::dt, float_rmat_vmult(), foo, get_sys_time_msec(), init_calculator(), msg, FloatRates::p, FloatRates::q, ExtU::q, FloatQuat::qi, FloatQuat::qx, FloatQuat::qy, FloatQuat::qz, FloatRates::r, ExtU::rates, WindEstimator::reset, ExtU::sideslip, stateGetAccelBody_i(), stateGetAccelNed_f(), stateGetAirspeed_f(), stateGetAngleOfAttack_f(), stateGetBodyRates_f(), stateGetNedToBodyEulers_f(), stateGetNedToBodyQuat_f(), stateGetNedToBodyRMat_f(), stateGetSideslip_f(), stateGetSpeedNed_f(), time_step_before, ukf_params, ukf_U, ExtU::va, VECT3_ADD, ExtU::vk, wind_estimator, wind_estimator_step(), NedCoor_f::x, NedCoor_f::y, and NedCoor_f::z.
wind_estimator_Set_Q_VA()
void wind_estimator_Set_Q_VA (float _v) extern
Definition at line 528 of file wind_estimator.c.
References foo, MAT_EL, ukf_params_tag::Q, WindEstimator::q_va, ukf_params, and wind_estimator.
wind_estimator_Set_Q_VA_SCALE()
void wind_estimator_Set_Q_VA_SCALE (float _v) extern
Definition at line 544 of file wind_estimator.c.
References foo, MAT_EL, ukf_params_tag::Q, WindEstimator::q_va_scale, ukf_params, and wind_estimator.
wind_estimator_Set_Q_WIND()
void wind_estimator_Set_Q_WIND (float _v) extern
Definition at line 536 of file wind_estimator.c.
References foo, MAT_EL, ukf_params_tag::Q, WindEstimator::q_wind, ukf_params, and wind_estimator.
wind_estimator_Set_R_AOA()
void wind_estimator_Set_R_AOA (float _v) extern
Definition at line 516 of file wind_estimator.c.
References foo, MAT_EL, ukf_params_tag::R, WindEstimator::r_aoa, ukf_params, and wind_estimator.
wind_estimator_Set_R_GS()
void wind_estimator_Set_R_GS (float _v) extern
Definition at line 502 of file wind_estimator.c.
References foo, MAT_EL, ukf_params_tag::R, WindEstimator::r_gs, ukf_params, and wind_estimator.
wind_estimator_Set_R_SSA()
void wind_estimator_Set_R_SSA (float _v) extern
Definition at line 522 of file wind_estimator.c.
References foo, MAT_EL, ukf_params_tag::R, WindEstimator::r_ssa, ukf_params, and wind_estimator.
wind_estimator_Set_R_VA()
void wind_estimator_Set_R_VA (float _v) extern
Definition at line 510 of file wind_estimator.c.
References foo, MAT_EL, ukf_params_tag::R, WindEstimator::r_va, ukf_params, and wind_estimator.
Variable Documentation
wind_estimator
struct WindEstimator wind_estimator extern
Definition at line 125 of file wind_estimator.c.
Referenced by init_calculator(), send_wind_estimator(), wind_estimator_event(), wind_estimator_periodic(), wind_estimator_Set_Q_VA(), wind_estimator_Set_Q_VA_SCALE(), wind_estimator_Set_Q_WIND(), wind_estimator_Set_R_AOA(), wind_estimator_Set_R_GS(), wind_estimator_Set_R_SSA(), wind_estimator_Set_R_VA(), and wind_estimator_step().