Paparazzi UAS: sw/airborne/modules/meteo/wind_estimation_quadrotor.h File Reference
wind_estimation_quadrotor.h File Reference
Data Structures
struct wind_estimation_quadrotor_params
Functions
void wind_estimation_quadrotor_init (void)
void wind_estimation_quadrotor_periodic (void)
void wind_estimation_quadrotor_stop (void)
void wind_estimation_quadrotor_start (void)
void wind_estimation_quadrotor_report (void)
float wind_estimation_quadrotor_SetQva (float Q_va)
float wind_estimation_quadrotor_SetQw (float Q_w)
float wind_estimation_quadrotor_SetR (float R)
Variables
struct wind_estimation_quadrotor_params we_quad_params
Detailed Description
Author
Gautier Hattenberger gauti.nosp@m.er.h.nosp@m.atten.nosp@m.berg.nosp@m.er@en.nosp@m.ac.f.nosp@m.r Wind estimation from quadrotor motion
Definition in file wind_estimation_quadrotor.h.
Data Structure Documentation
wind_estimation_quadrotor_params
struct wind_estimation_quadrotor_params
Definition at line 29 of file wind_estimation_quadrotor.h.
Data Fields
float Q_va model noise on airspeed
float Q_w model noise on wind
float R measurement noise (ground speed)
Function Documentation
wind_estimation_quadrotor_init()
void wind_estimation_quadrotor_init (void) extern
Definition at line 98 of file wind_estimation_quadrotor.c.
References linear_kalman_filter::A, linear_kalman_filter::B, linear_kalman_filter::C, DefaultPeriodic, wind_estimation_quadrotor::filter, foo, linear_kalman_filter_init(), linear_kalman_filter::Q, wind_estimation_quadrotor_params::Q_va, wind_estimation_quadrotor_params::Q_w, linear_kalman_filter::R, wind_estimation_quadrotor_params::R, register_periodic_telemetry(), send_wind(), wind_estimation_quadrotor::status, we_dt, we_quad, WE_QUAD_CMD_SIZE, WE_QUAD_MEAS_SIZE, we_quad_params, WE_QUAD_Q_VA, WE_QUAD_Q_W, WE_QUAD_R, WE_QUAD_STATE_SIZE, WE_QUAD_STATUS_IDLE, and wind_estimation_quadrotor_reset().
wind_estimation_quadrotor_periodic()
void wind_estimation_quadrotor_periodic (void) extern
Definition at line 133 of file wind_estimation_quadrotor.c.
References AIRSPEED_WE_QUAD_ID, eas_from_tas(), wind_estimation_quadrotor::filter, float_rmat_transp_vmult(), float_vect2_norm(), foo, linear_kalman_filter_predict(), linear_kalman_filter_update(), MAT33_ELMT, PPRZ_ISA_GRAVITY, stateGetNedToBodyRMat_f(), stateGetSpeedNed_f(), stateSetHorizontalWindspeed_f(), we_quad, WE_QUAD_CMD_SIZE, WE_QUAD_MEAS_SIZE, WE_QUAD_VA_X, WE_QUAD_VA_Y, WE_QUAD_W_X, WE_QUAD_W_Y, linear_kalman_filter::X, NedCoor_f::x, and NedCoor_f::y.
wind_estimation_quadrotor_report()
void wind_estimation_quadrotor_report (void) extern
Definition at line 208 of file wind_estimation_quadrotor.c.
References DefaultChannel, DefaultDevice, wind_estimation_quadrotor::filter, foo, we_quad, WE_QUAD_STATE_SIZE, and linear_kalman_filter::X.
wind_estimation_quadrotor_SetQva()
float wind_estimation_quadrotor_SetQva (float Q_va) extern
Definition at line 184 of file wind_estimation_quadrotor.c.
References wind_estimation_quadrotor::filter, linear_kalman_filter::Q, wind_estimation_quadrotor_params::Q_va, we_quad, and we_quad_params.
wind_estimation_quadrotor_SetQw()
float wind_estimation_quadrotor_SetQw (float Q_w) extern
Definition at line 192 of file wind_estimation_quadrotor.c.
References wind_estimation_quadrotor::filter, linear_kalman_filter::Q, wind_estimation_quadrotor_params::Q_w, we_quad, and we_quad_params.
wind_estimation_quadrotor_SetR()
float wind_estimation_quadrotor_SetR (float R) extern
Definition at line 200 of file wind_estimation_quadrotor.c.
References wind_estimation_quadrotor::filter, linear_kalman_filter::R, wind_estimation_quadrotor_params::R, we_quad, and we_quad_params.
wind_estimation_quadrotor_start()
void wind_estimation_quadrotor_start (void) extern
Definition at line 178 of file wind_estimation_quadrotor.c.
References wind_estimation_quadrotor::status, we_quad, WE_QUAD_STATUS_RUN, and wind_estimation_quadrotor_reset().
wind_estimation_quadrotor_stop()
void wind_estimation_quadrotor_stop (void) extern
Definition at line 169 of file wind_estimation_quadrotor.c.
References foo, stateSetHorizontalWindspeed_f(), wind_estimation_quadrotor::status, we_quad, and WE_QUAD_STATUS_IDLE.
Variable Documentation
we_quad_params
struct wind_estimation_quadrotor_params we_quad_params extern
Definition at line 87 of file wind_estimation_quadrotor.c.
Referenced by wind_estimation_quadrotor_init(), wind_estimation_quadrotor_SetQva(), wind_estimation_quadrotor_SetQw(), and wind_estimation_quadrotor_SetR().