Paparazzi UAS: sw/airborne/modules/meteo/wind_gfi.h File Reference
wind_gfi.h File Reference
#include "std.h"
Enumerations
enum pcf_stat {
PCF_IDLE , PCF_SET_OE_LSB , PCF_READ_LSB , PCF_SET_OE_MSB ,
PCF_READ_MSB
}
Functions
void wind_gfi_init (void)
void wind_gfi_periodic (void)
void wind_gfi_event (void)
Enumeration Type Documentation
pcf_stat
enum pcf_stat
Enumerator
PCF_IDLE
PCF_SET_OE_LSB
PCF_READ_LSB
PCF_SET_OE_MSB
PCF_READ_MSB
Definition at line 6 of file wind_gfi.h.
Function Documentation
wind_gfi_event()
void wind_gfi_event (void)
Definition at line 72 of file wind_gfi.c.
References i2c_transaction::buf, DefaultChannel, DefaultDevice, foo, i2c_receive(), i2c_transmit(), I2CTransDone, I2CTransSuccess, pcf_direction, PCF_I2C_DEV, PCF_IDLE, PCF_READ_LSB, PCF_READ_MSB, PCF_SET_OE_LSB, PCF_SET_OE_MSB, PCF_SLAVE_ADDR, pcf_status, pcf_trans, i2c_transaction::status, and ZERO_OFFSET_DEGREES.
wind_gfi_init()
void wind_gfi_init (void)
Definition at line 57 of file wind_gfi.c.
References I2CTransDone, PCF_IDLE, pcf_status, pcf_trans, and i2c_transaction::status.
wind_gfi_periodic()
void wind_gfi_periodic (void)
Definition at line 63 of file wind_gfi.c.
References i2c_transaction::buf, i2c_transmit(), PCF_I2C_DEV, PCF_SET_OE_LSB, PCF_SLAVE_ADDR, pcf_status, and pcf_trans.