Paparazzi UAS: sw/airborne/math/wls/wls_alloc.h File Reference
wls_alloc.h File Reference
#include "generated/airframe.h"
#include "modules/datalink/telemetry.h"
Data Structures
struct WLS_t
Macros
#define WLS_N_U_MAX 6
active set algorithm for control allocation
#define WLS_N_V_MAX 4
Functions
void send_wls_v (char *name, struct WLS_t *WLS_p, struct transport_tx *trans, struct link_device *dev)
void send_wls_u (char *name, struct WLS_t *WLS_p, struct transport_tx *trans, struct link_device *dev)
void wls_alloc (struct WLS_t *WLS_p, float **B, float *u_guess, float *W_init, int imax)
active set algorithm for control allocation
Data Structure Documentation
WLS_t
struct WLS_t
Definition at line 66 of file wls_alloc.h.
Data Fields
float gamma_sq
int iter
int nu
int nv
float PC
float SC
float u[WLS_N_U_MAX]
float u_max[WLS_N_U_MAX]
float u_min[WLS_N_U_MAX]
float u_pref[WLS_N_U_MAX]
float v[WLS_N_V_MAX]
float Wu[WLS_N_U_MAX]
float Wv[WLS_N_V_MAX]
Macro Definition Documentation
WLS_N_U_MAX
#define WLS_N_U_MAX 6
active set algorithm for control allocation
Takes the control objective and max and min inputs from pprz and calculates the inputs that will satisfy most of the control objective, subject to the weighting matrices Wv and Wu
The dimension of the input vectors u and v are defined at compilation time and must be large enough for all the considered cases.
Parameters
u The control output vector
v The control objective vector
B The control effectiveness matrix
n_u Length of u
n_v Lenght of v
u_guess Initial value for u
W_init Initial working set, if known
Wv Weighting on different control objectives
Wu Weighting on different controls
up Preferred control vector
gamma_sq Preference of satisfying control objective over desired control vector (sqare root of gamma)
imax Max number of iterations
n_u Length of u (the number of actuators)
n_v Lenght of v (the number of control objectives)
Returns
Number of iterations: (imax+1) means it ran out of iterations
Definition at line 60 of file wls_alloc.h.
WLS_N_V_MAX
#define WLS_N_V_MAX 4
Definition at line 64 of file wls_alloc.h.
Function Documentation
send_wls_u()
void send_wls_u (char * name, struct WLS_t * WLS_p, struct transport_tx * trans, struct link_device * dev) extern
Definition at line 71 of file wls_alloc.c.
References dev, and foo.
Referenced by send_wls_u_oneloop(), and send_wls_u_stab().
send_wls_v()
void send_wls_v (char * name, struct WLS_t * WLS_p, struct transport_tx * trans, struct link_device * dev) extern
Definition at line 61 of file wls_alloc.c.
References dev, and foo.
Referenced by send_wls_v_oneloop(), and send_wls_v_stab().
wls_alloc()
void wls_alloc (struct WLS_t * WLS_p, float ** B, float * u_guess, float * W_init, int imax) extern
active set algorithm for control allocation
Takes the control objective and max and min inputs from pprz and calculates the inputs that will satisfy most of the control objective, subject to the weighting matrices Wv and Wu
Parameters
WLS_p Struct that contains most of the WLS parameters
B The control effectiveness matrix
u_guess Initial value for u
W_init Initial working set, if known
imax Max number of iterations
Definition at line 119 of file wls_alloc.c.
References A, alpha, B, b, foo, lambda, p, qr_solve_wrapper(), and UNUSED.
Referenced by guidance_indi_run(), oneloop_andi_run(), stabilization_andi_run(), and stabilization_indi_rate_run().