Paparazzi UAS: sw/airborne/modules/ins/xsens700.h File Reference
xsens700.h File Reference
Parser for the Xsens protocol.
#include "std.h"
#include "math/pprz_algebra_float.h"
#include "math/pprz_geodetic_float.h"
#include "math/pprz_geodetic_int.h"
#include "xsens_parser.h"
Data Structures
struct XsensTime
struct Xsens
Functions
void xsens700_init (void)
void xsens700_periodic (void)
void parse_xsens700_msg (void)
Variables
struct Xsens xsens700
Detailed Description
Parser for the Xsens protocol.
Definition in file xsens700.h.
Data Structure Documentation
XsensTime
struct XsensTime
Definition at line 42 of file xsens.h.
Data Fields
int8_t day
int8_t hour
int8_t min
int8_t month
int32_t nanosec
int8_t sec
int16_t year
Xsens
struct Xsens
Definition at line 52 of file xsens.h.
Data Fields
struct FloatVect3 accel
bool accel_available
struct FloatEulers euler
struct FloatRates gyro
bool gyro_available
struct LlaCoor_f lla_f
struct FloatVect3 mag
bool mag_available
volatile bool new_attitude
struct XsensParser parser
struct FloatQuat quat
struct XsensTime time
uint16_t time_stamp
struct FloatVect3 vel NED velocity in m/s.
Function Documentation
parse_xsens700_msg()
void parse_xsens700_msg (void) extern
Definition at line 141 of file xsens700.c.
References Xsens::accel, Xsens::euler, foo, GPS_FIX_2D, GPS_FIX_3D, GPS_FIX_NONE, GPS_NB_CHANNELS, GPS_VALID_HMSL_BIT, GPS_VALID_VEL_NED_BIT, Xsens::gyro, XsensParser::id, LlaCoor_f::lat, LED_TOGGLE, XsensParser::len, Xsens::lla_f, LlaCoor_f::lon, Min, XsensParser::msg_buf, sys_time::nb_sec, sys_time::nb_sec_rem, Xsens::new_attitude, offset, FloatRates::p, Xsens::parser, FloatEulers::phi, FloatEulers::psi, FloatRates::q, FloatRates::r, FloatEulers::theta, TRUE, Xsens::vel, wgs84_ellipsoid_to_geoid_f(), FloatVect3::x, xsens700, xsens_errorcode, xsens_gps_arm_x, xsens_gps_arm_y, xsens_gps_arm_z, xsens_msg_statusword, FloatVect3::y, and FloatVect3::z.
Referenced by ins_xsens700_event().
xsens700_init()
void xsens700_init (void) extern
Definition at line 53 of file xsens700.c.
References Xsens::parser, XsensParser::status, UNINIT, xsens700, xsens_configured, xsens_msg_statusword, and xsens_time_stamp.
Referenced by ins_xsens700_init().
xsens700_periodic()
void xsens700_periodic (void) extern
Definition at line 71 of file xsens700.c.
References foo, xsens_ask_message_rate(), xsens_configured, XsensHeader, and XsensTrailer.
Variable Documentation
xsens700
struct Xsens xsens700 extern
Definition at line 49 of file xsens700.c.
Referenced by handle_ins_msg(), ins_xsens700_event(), parse_xsens700_msg(), update_state_interface(), and xsens700_init().