Paparazzi UAS: sw/airborne/modules/ins/xsens.h File Reference
xsens.h File Reference
Parser for the Xsens protocol.
#include "std.h"
#include "math/pprz_algebra_float.h"
#include "math/pprz_geodetic_float.h"
#include "math/pprz_geodetic_int.h"
#include "xsens_parser.h"
Data Structures
struct XsensTime
struct Xsens
Functions
void xsens_init (void)
void xsens_periodic (void)
void parse_xsens_msg (void)
Variables
struct Xsens xsens
Detailed Description
Parser for the Xsens protocol.
Definition in file xsens.h.
Data Structure Documentation
XsensTime
struct XsensTime
Definition at line 42 of file xsens.h.
Data Fields
int8_t day
int8_t hour
int8_t min
int8_t month
int32_t nanosec
int8_t sec
int16_t year
Xsens
struct Xsens
Definition at line 52 of file xsens.h.
Data Fields
struct FloatVect3 accel
bool accel_available
struct FloatEulers euler
struct FloatRates gyro
bool gyro_available
struct LlaCoor_f lla_f
struct FloatVect3 mag
bool mag_available
volatile bool new_attitude
struct XsensParser parser
struct FloatQuat quat
struct XsensTime time
uint16_t time_stamp
struct FloatVect3 vel NED velocity in m/s.
Function Documentation
parse_xsens_msg()
void parse_xsens_msg (void) extern
Definition at line 184 of file xsens.c.
References Xsens::accel, Xsens::accel_available, LlaCoor_f::alt, XsensTime::day, DefaultChannel, DefaultDevice, Xsens::euler, foo, gps, GPS_FIX_3D, GPS_FIX_NONE, GPS_NB_CHANNELS, GPS_VALID_HMSL_BIT, GPS_VALID_POS_LLA_BIT, GPS_VALID_VEL_NED_BIT, Xsens::gyro, Xsens::gyro_available, XsensTime::hour, XsensParser::id, LlaCoor_f::lat, LED_ON, LED_TOGGLE, LLA_BFP_OF_REAL, Xsens::lla_f, LlaCoor_f::lon, Xsens::mag, Xsens::mag_available, Min, XsensTime::min, XsensTime::month, XsensParser::msg_buf, XsensTime::nanosec, Xsens::new_attitude, offset, FloatRates::p, Xsens::parser, FloatEulers::phi, FloatEulers::psi, FloatRates::q, FloatQuat::qi, Xsens::quat, FloatQuat::qx, FloatQuat::qy, FloatQuat::qz, FloatRates::r, XsensTime::sec, FloatEulers::theta, Xsens::time, Xsens::time_stamp, TRUE, GpsState::valid_fields, Xsens::vel, wgs84_ellipsoid_to_geoid_i(), FloatVect3::x, xsens, xsens_declination, xsens_errorcode, xsens_gps_arm_x, xsens_gps_arm_y, xsens_gps_arm_z, xsens_msg_status, xsens_output_mode, xsens_output_settings, FloatVect3::y, XsensTime::year, and FloatVect3::z.
Referenced by imu_xsens_event(), and ins_xsens_event().
xsens_init()
void xsens_init (void) extern
Definition at line 113 of file xsens.c.
References Xsens::parser, XsensParser::status, UNINIT, xsens, xsens_configured, xsens_msg_status, XSENS_OUTPUT_MODE, xsens_output_mode, XSENS_OUTPUT_SETTINGS, xsens_output_settings, and xsens_time_stamp.
Referenced by imu_xsens_init(), and ins_xsens_init().
xsens_periodic()
void xsens_periodic (void) extern
Definition at line 124 of file xsens.c.
References foo, xsens_configured, xsens_declination, xsens_output_mode, and xsens_output_settings.
Variable Documentation
xsens
struct Xsens xsens extern
Definition at line 109 of file xsens.c.
Referenced by handle_ins_msg(), handle_ins_msg(), imu_xsens_event(), ins_xsens_event(), parse_xsens_msg(), update_state_interface(), xsens_init(), and xsens_parser_func().