var group__math__orientation__representation =
[
    [ "Raw mag_hmc5843.xml file:", "module__mag_hmc5843.html#module_xml__mag_hmc5843", null ],
    [ "Raw mag_hmc58xx.xml file:", "module__mag_hmc58xx.html#module_xml__mag_hmc58xx", null ],
    [ "Raw mag_micromag_fw.xml file:", "module__mag_micromag_fw.html#module_xml__mag_micromag_fw", null ],
    [ "Raw pbn.xml file:", "module__pbn.html#module_xml__pbn", null ],
    [ "Raw trigger_ext.xml file:", "module__trigger_ext.html#module_xml__trigger_ext", null ],
    [ "Raw MPPT.xml file:", "module__mppt.html#module_xml__mppt", null ],
    [ "Raw airborne_ant_track.xml file:", "module__airborne_ant_track.html#module_xml__airborne_ant_track", null ],
    [ "Raw bat_checker.xml file:", "module__bat_checker.html#module_xml__bat_checker", null ],
    [ "Raw configure_actuators_mkk_v2.xml file:", "module__configure_actuators_mkk_v2.html#module_xml__configure_actuators_mkk_v2", null ],
    [ "Raw demo_module.xml file:", "module__demo_module.html#module_xml__demo_module", null ],
    [ "Raw deploy_sonar_buoy.xml file:", "module__deploy_sonar_buoy.html#module_xml__deploy_sonar_buoy", null ],
    [ "Raw enose.xml file:", "module__enose.html#module_xml__enose", null ],
    [ "Raw flight_time.xml file:", "module__flight_time.html#module_xml__flight_time", null ],
    [ "Raw gain_scheduling.xml file:", "module__gain_scheduling.html#module_xml__gain_scheduling", null ],
    [ "Raw gas_engine_idle.xml file:", "module__gas_engine_idle.html#module_xml__gas_engine_idle", null ],
    [ "Raw generic_com.xml file:", "module__generic_com.html#module_xml__generic_com", null ],
    [ "Raw geo_mag.xml file:", "module__geo_mag.html#module_xml__geo_mag", null ],
    [ "Raw gps_i2c.xml file:", "module__gps_i2c.html#module_xml__gps_i2c", null ],
    [ "Raw gsm.xml file:", "module__gsm.html#module_xml__gsm", null ],
    [ "Raw gumstix_qr_code_spi_link.xml file:", "module__gumstix_qr_code_spi_link.html#module_xml__gumstix_qr_code_spi_link", null ],
    [ "Raw hott_telemetry.xml file:", "module__hott_telemetry.html#module_xml__hott_telemetry", null ],
    [ "Raw lcd_dogm.xml file:", "module__lcd_dogm.html#module_xml__lcd_dogm", null ],
    [ "Raw led_safety_status.xml file:", "module__led_safety_status.html#module_xml__led_safety_status", null ],
    [ "Raw light.xml file:", "module__light.html#module_xml__light", null ],
    [ "Raw max3100.xml file:", "module__max3100.html#module_xml__max3100", null ],
    [ "Raw openlog.xml file:", "module__openlog.html#module_xml__openlog", null ],
    [ "Raw osd_max7456.xml file:", "module__osd_max7456.html#module_xml__osd_max7456", null ],
    [ "Raw poles.xml file:", "module__poles.html#module_xml__poles", null ],
    [ "Raw px4flow.xml file:", "module__px4flow.html#module_xml__px4flow", null ],
    [ "Raw send_imu_mag_current.xml file:", "module__send_imu_mag_current.html#module_xml__send_imu_mag_current", null ],
    [ "Raw servo_switch.xml file:", "module__servo_switch.html#module_xml__servo_switch", null ],
    [ "Raw sonar_adc.xml file:", "module__sonar_adc.html#module_xml__sonar_adc", null ],
    [ "Raw vehicle_interface_datalink.xml file:", "module__vehicle_interface_datalink.html#module_xml__vehicle_interface_datalink", null ],
    [ "OrientationReps", "structOrientationReps.html", [
      [ "eulers_f", "structOrientationReps.html#a2f18ced65428f3d06b94d6f33e4e00c8", null ],
      [ "eulers_i", "structOrientationReps.html#ae5c1f10412db95ffca8c6f309997ac2a", null ],
      [ "quat_f", "structOrientationReps.html#af08d1a1987ca1989e45279a961bfc072", null ],
      [ "quat_i", "structOrientationReps.html#a67db4b57551efc60a23d304820aa6292", null ],
      [ "rmat_f", "structOrientationReps.html#a9a12faf04660fa348b0d5e474051c2fc", null ],
      [ "rmat_i", "structOrientationReps.html#ac3014e532f5ca710919668e1dd48c791", null ],
      [ "status", "structOrientationReps.html#a74e63a71a7d35e89ea968c2e2c0b7369", null ]
    ] ],
    [ "ORREP_EULER_F", "group__math__orientation__representation.html#ga5ca8cd93a67e7ddcd8534f523961edaf", null ],
    [ "ORREP_EULER_I", "group__math__orientation__representation.html#ga4bf5cf32d339495bd9ea2d6ba91ad712", null ],
    [ "ORREP_QUAT_F", "group__math__orientation__representation.html#ga92513ffc4921e8b22fc7a65a583a79c1", null ],
    [ "ORREP_QUAT_I", "group__math__orientation__representation.html#ga449d2dae2d46b5827d1b53db7eb9c8f9", null ],
    [ "ORREP_RMAT_F", "group__math__orientation__representation.html#gafca38fd6b6fcbe2c1887ba34a628efb2", null ],
    [ "ORREP_RMAT_I", "group__math__orientation__representation.html#gaaa0eaf3eb87be02a80d6d1d47349f8dd", null ],
    [ "orienationCheckValid", "group__math__orientation__representation.html#ga6b55b77641f1a911a919a4d579932514", null ],
    [ "orientationCalcEulers_f", "group__math__orientation__representation.html#ga8b8bf1c74adb971f399f0dd4f84d9388", null ],
    [ "orientationCalcEulers_i", "group__math__orientation__representation.html#gaa07c68d2ea52188413c8c90ce48b73c8", null ],
    [ "orientationCalcQuat_f", "group__math__orientation__representation.html#ga33edf7d5bd278bed617fb5aa88559dc2", null ],
    [ "orientationCalcQuat_i", "group__math__orientation__representation.html#gaa411e2093feec3fef9e18c4a52b74c38", null ],
    [ "orientationCalcRMat_f", "group__math__orientation__representation.html#ga3394d93b976378bb5c9ddea8d7960eeb", null ],
    [ "orientationCalcRMat_i", "group__math__orientation__representation.html#ga8d3a2d675e2693d1780d587cd392d96a", null ],
    [ "orientationGetEulers_f", "group__math__orientation__representation.html#gaaae3838d0b45682d48257d5dbfff3030", null ],
    [ "orientationGetEulers_i", "group__math__orientation__representation.html#gae05f220bbbdaafcbe11bc2d1fb622f39", null ],
    [ "orientationGetQuat_f", "group__math__orientation__representation.html#ga4bc38966bac43e1f55b2f042d8f2e411", null ],
    [ "orientationGetQuat_i", "group__math__orientation__representation.html#ga86b153b2106a638cef8e314125c47306", null ],
    [ "orientationGetRMat_f", "group__math__orientation__representation.html#gadad1660d6ec48c67423b76622ce80b51", null ],
    [ "orientationGetRMat_i", "group__math__orientation__representation.html#ga4d3e785c7decf12ad0331c6ec207ded7", null ],
    [ "orientationSetEulers_f", "group__math__orientation__representation.html#ga7c6b7dc05095bcaba232c62358335d81", null ],
    [ "orientationSetEulers_i", "group__math__orientation__representation.html#gaa4f947a03eec17840ac5e6157b12a01f", null ],
    [ "orientationSetQuat_f", "group__math__orientation__representation.html#ga35d21d17eb2d2ef8352f0aceb8ad7001", null ],
    [ "orientationSetQuat_i", "group__math__orientation__representation.html#ga8a3e395362b89b24cee7c3dd6dddb03c", null ],
    [ "orientationSetRMat_f", "group__math__orientation__representation.html#ga2c06304a23d68ae280c1cc5f4f01386a", null ],
    [ "orientationSetRMat_i", "group__math__orientation__representation.html#gad65752ee2fd524adefea88180fac375d", null ]
];