var onboard_modules =
[
    [ "List of available modules", "onboard_modules.html#modules_list", [
      [ "Adcs modules", "onboard_modules.html#modules_category_adcs", null ],
      [ "Benchmark modules", "onboard_modules.html#modules_category_benchmark", null ],
      [ "Cam_Control modules", "onboard_modules.html#modules_category_cam_control", null ],
      [ "Cartography modules", "onboard_modules.html#modules_category_cartography", null ],
      [ "Core modules", "onboard_modules.html#modules_category_core", null ],
      [ "Datalink modules", "onboard_modules.html#modules_category_datalink", null ],
      [ "Digital_Cam modules", "onboard_modules.html#modules_category_digital_cam", null ],
      [ "Gps modules", "onboard_modules.html#modules_category_gps", null ],
      [ "Ins modules", "onboard_modules.html#modules_category_ins", null ],
      [ "Loggers modules", "onboard_modules.html#modules_category_loggers", null ],
      [ "Meteo modules", "onboard_modules.html#modules_category_meteo", null ],
      [ "Mission modules", "onboard_modules.html#modules_category_mission", null ],
      [ "Multi modules", "onboard_modules.html#modules_category_multi", null ],
      [ "Nav modules", "onboard_modules.html#modules_category_nav", null ],
      [ "Sensors modules", "onboard_modules.html#modules_category_sensors", null ],
      [ "Misc modules", "onboard_modules.html#modules_category_misc", null ]
    ] ],
    [ "Generic ADC", "module__adc_generic.html", null ],
    [ "Max11040 ADC", "module__max11040.html", null ],
    [ "MCP355X ADC driver (SPI)", "module__mcp355x.html", null ],
    [ "Flight benchmark", "module__flight_benchmark.html", null ],
    [ "Benchmark", "module__i2c_abuse_test.html", null ],
    [ "Give comparable with IMU Health information", "module__imu_quality_assessment.html", null ],
    [ "Camera control for fixedwing", "module__cam_point.html", null ],
    [ "Camera control on roll axis only", "module__cam_roll.html", null ],
    [ "Camera control to point a segment", "module__cam_segment.html", null ],
    [ "Camera control for rotorcraft", "module__rotorcraft_cam.html", null ],
    [ "Cartography sweeping pattern for navigation", "module__cartography.html", null ],
    [ "Photogrammetry navigation functions", "module__photogrammetry_calculator.html", null ],
    [ "PWM measurement", "module__pwm_meas.html", null ],
    [ "System monitor", "module__sys_mon.html", null ],
    [ "Trigger Ext", "module__trig_test.html", null ],
    [ "Extra datalink (PPRZ transport)", "module__extra_dl.html", null ],
    [ "A simple MAVLINK decoder", "module__mavlink_decoder.html", null ],
    [ "Digi Xtend RSSI PWM Module", "module__xtend_rssi.html", null ],
    [ "Digital camera control (trigger using GPIO)", "module__digital_cam.html", null ],
    [ "Trigger Digital Camera (I2C)", "module__digital_cam_i2c.html", null ],
    [ "Digital camera control (trigger using servo)", "module__digital_cam_servo.html", null ],
    [ "HackHD control", "module__hackhd.html", null ],
    [ "Ublox gps (uart)", "module__gps_ubx_uart.html", null ],
    [ "Ublox GPS autoconfiguration", "module__gps_ubx_ucenter.html", null ],
    [ "CHimu (SPI)", "module__ahrs_chimu_spi.html", null ],
    [ "CHimu (UART)", "module__ahrs_chimu_uart.html", null ],
    [ "Altitude filter", "module__alt_filter.html", null ],
    [ "ArduIMU v2", "module__ins_arduimu.html", null ],
    [ "ArduIMU v2", "module__ins_arduimu_basic.html", null ],
    [ "VectorNav VN100 (SPI)", "module__ins_vn100.html", null ],
    [ "XSens", "module__ins_xsens.html", null ],
    [ "XSens MTiG", "module__ins_xsens_mtig_uart0.html", null ],
    [ "XSens MTi", "module__ins_xsens_mti_uart0.html", null ],
    [ "Logs to a csv file (only for linux)", "module__file_logger.html", null ],
    [ "Connect to external High-Speed SD-logger via SPI", "module__high_speed_logger_spi_link.html", null ],
    [ "Charge sensor", "module__charge_sens.html", null ],
    [ "Sharp GP2Y1010AU dust sensor", "module__dust_gp2y.html", null ],
    [ "Geiger counter sensor", "module__geiger_counter.html", null ],
    [ "DigiPicco humidity sensor", "module__humid_dpicco.html", null ],
    [ "HIH-4030 humidity sensor", "module__humid_hih.html", null ],
    [ "TronSens HTM-B71 humidity sensor (I2C)", "module__humid_htm_b71.html", null ],
    [ "ACAM Picocap capacitance sensor", "module__humid_pcap01.html", null ],
    [ "SHTxx humidity sensor", "module__humid_sht.html", null ],
    [ "Sensirion SHT25 humidity sensor (I2C)", "module__humid_sht_i2c.html", null ],
    [ "Infrared MLX sensor", "module__ir_mlx.html", null ],
    [ "Light Solar", "module__light_solar.html", null ],
    [ "Light Temt", "module__light_temt.html", null ],
    [ "Data acquisition board used by Meteo France", "module__meteo_france_daq.html", null ],
    [ "PTU board from Meteo France (pressure, temperature, humidity)", "module__mf_ptu.html", [
      [ "Module configuration options", "module__mf_ptu.html#configuration", [
        [ "Raw adc_generic.xml file:", "module__adc_generic.html#module_xml__adc_generic", null ],
        [ "Raw max11040.xml file:", "module__max11040.html#module_xml__max11040", null ],
        [ "Raw mcp355x.xml file:", "module__mcp355x.html#module_xml__mcp355x", null ],
        [ "Raw flight_benchmark.xml file:", "module__flight_benchmark.html#module_xml__flight_benchmark", null ],
        [ "Raw i2c_abuse_test.xml file:", "module__i2c_abuse_test.html#module_xml__i2c_abuse_test", null ],
        [ "Raw imu_quality_assessment.xml file:", "module__imu_quality_assessment.html#module_xml__imu_quality_assessment", null ],
        [ "Raw cam_point.xml file:", "module__cam_point.html#module_xml__cam_point", null ],
        [ "Raw cam_roll.xml file:", "module__cam_roll.html#module_xml__cam_roll", null ],
        [ "Raw cam_segment.xml file:", "module__cam_segment.html#module_xml__cam_segment", null ],
        [ "Raw rotorcraft_cam.xml file:", "module__rotorcraft_cam.html#module_xml__rotorcraft_cam", null ],
        [ "Raw cartography.xml file:", "module__cartography.html#module_xml__cartography", null ],
        [ "Raw photogrammetry_calculator.xml file:", "module__photogrammetry_calculator.html#module_xml__photogrammetry_calculator", null ],
        [ "Raw pwm_meas.xml file:", "module__pwm_meas.html#module_xml__pwm_meas", null ],
        [ "Raw sys_mon.xml file:", "module__sys_mon.html#module_xml__sys_mon", null ],
        [ "Raw trig_test.xml file:", "module__trig_test.html#module_xml__trig_test", null ],
        [ "Raw extra_dl.xml file:", "module__extra_dl.html#module_xml__extra_dl", null ],
        [ "Raw mavlink_decoder.xml file:", "module__mavlink_decoder.html#module_xml__mavlink_decoder", null ],
        [ "Raw xtend_rssi.xml file:", "module__xtend_rssi.html#module_xml__xtend_rssi", null ],
        [ "Raw digital_cam.xml file:", "module__digital_cam.html#module_xml__digital_cam", null ],
        [ "Raw digital_cam_i2c.xml file:", "module__digital_cam_i2c.html#module_xml__digital_cam_i2c", null ],
        [ "Raw digital_cam_servo.xml file:", "module__digital_cam_servo.html#module_xml__digital_cam_servo", null ],
        [ "Raw hackhd.xml file:", "module__hackhd.html#module_xml__hackhd", null ],
        [ "Raw gps_ubx_uart.xml file:", "module__gps_ubx_uart.html#module_xml__gps_ubx_uart", null ],
        [ "Raw gps_ubx_ucenter.xml file:", "module__gps_ubx_ucenter.html#module_xml__gps_ubx_ucenter", null ],
        [ "Raw ahrs_chimu_spi.xml file:", "module__ahrs_chimu_spi.html#module_xml__ahrs_chimu_spi", null ],
        [ "Raw ahrs_chimu_uart.xml file:", "module__ahrs_chimu_uart.html#module_xml__ahrs_chimu_uart", null ],
        [ "Raw alt_filter.xml file:", "module__alt_filter.html#module_xml__alt_filter", null ],
        [ "Raw ins_arduimu.xml file:", "module__ins_arduimu.html#module_xml__ins_arduimu", null ],
        [ "Raw ins_arduimu_basic.xml file:", "module__ins_arduimu_basic.html#module_xml__ins_arduimu_basic", null ],
        [ "Raw ins_vn100.xml file:", "module__ins_vn100.html#module_xml__ins_vn100", null ],
        [ "Raw ins_xsens.xml file:", "module__ins_xsens.html#module_xml__ins_xsens", null ],
        [ "Raw ins_xsens_MTiG_Uart0.xml file:", "module__ins_xsens_mtig_uart0.html#module_xml__ins_xsens_mtig_uart0", null ],
        [ "Raw ins_xsens_MTi_Uart0.xml file:", "module__ins_xsens_mti_uart0.html#module_xml__ins_xsens_mti_uart0", null ],
        [ "Raw file_logger.xml file:", "module__file_logger.html#module_xml__file_logger", null ],
        [ "Raw high_speed_logger_spi_link.xml file:", "module__high_speed_logger_spi_link.html#module_xml__high_speed_logger_spi_link", null ],
        [ "Raw charge_sens.xml file:", "module__charge_sens.html#module_xml__charge_sens", null ],
        [ "Raw dust_gp2y.xml file:", "module__dust_gp2y.html#module_xml__dust_gp2y", null ],
        [ "Raw geiger_counter.xml file:", "module__geiger_counter.html#module_xml__geiger_counter", null ],
        [ "Raw humid_dpicco.xml file:", "module__humid_dpicco.html#module_xml__humid_dpicco", null ],
        [ "Raw humid_hih.xml file:", "module__humid_hih.html#module_xml__humid_hih", null ],
        [ "Raw humid_htm_b71.xml file:", "module__humid_htm_b71.html#module_xml__humid_htm_b71", null ],
        [ "Raw humid_pcap01.xml file:", "module__humid_pcap01.html#module_xml__humid_pcap01", null ],
        [ "Raw humid_sht.xml file:", "module__humid_sht.html#module_xml__humid_sht", null ],
        [ "Raw humid_sht_i2c.xml file:", "module__humid_sht_i2c.html#module_xml__humid_sht_i2c", null ],
        [ "Raw ir_mlx.xml file:", "module__ir_mlx.html#module_xml__ir_mlx", null ],
        [ "Raw light_solar.xml file:", "module__light_solar.html#module_xml__light_solar", null ],
        [ "Raw light_temt.xml file:", "module__light_temt.html#module_xml__light_temt", null ],
        [ "Raw meteo_france_DAQ.xml file:", "module__meteo_france_daq.html#module_xml__meteo_france_daq", null ],
        [ "Configure Options", "module__mf_ptu.html#configure", null ],
        [ "Airframe file section", "module__mf_ptu.html#af_section", null ],
        [ "Raw mf_ptu.xml file:", "module__mf_ptu.html#module_xml__mf_ptu", null ]
      ] ]
    ] ],
    [ "LM75 temparature sensor", "module__temp_lm75.html", null ],
    [ "Temp Tcouple Adc", "module__temp_tcouple_adc.html", null ],
    [ "Hygrosens TEMOD-I2C-Rx temperature sensor", "module__temp_temod.html", null ],
    [ "Temp Tmp102", "module__temp_tmp102.html", null ],
    [ "Wind Gfi", "module__wind_gfi.html", null ],
    [ "Windturbine", "module__windturbine.html", null ],
    [ "Interface for mission control of fixed wing aircraft", "module__mission_fw.html", null ],
    [ "Interface for mission control of rotorcraft", "module__mission_rotorcraft.html", null ],
    [ "Follow a certain AC_ID trough remote GPS", "module__follow.html", null ],
    [ "Formation flight control", "module__formation_flight.html", null ],
    [ "Potential fields collision avoidance", "module__potential.html", null ],
    [ "TCAS collision avoidance", "module__tcas.html", null ],
    [ "Takeoff functions for bungee takeoff", "module__nav_bungee_takeoff.html", null ],
    [ "Catapult", "module__nav_catapult.html", null ],
    [ "Fixedwing Navigation in a cube towards a center", "module__nav_cube.html", null ],
    [ "Compute the dropping point for a fixedwing aircraft", "module__nav_drop.html", null ],
    [ "Make a flower navigation pattern", "module__nav_flower.html", null ],
    [ "gps landing system", "module__nav_gls.html", null ],
    [ "Fixedwing navigation along a line with nice U-turns", "module__nav_line.html", null ],
    [ "navigate along a border line (line 1-2) with turns in the same direction", "module__nav_line_border.html", null ],
    [ "Fly along a line", "module__nav_line_osam.html", null ],
    [ "Smooth navigation to wp_a along an arc (around wp_cd), a segment (from wp_rd to wp_ta) and a second arc (around wp_ca)", "module__nav_smooth.html", null ],
    [ "Fixedwing navigation in a spiral/helix", "module__nav_spiral.html", null ],
    [ "Disc Survey", "module__nav_survey_disc.html", null ],
    [ "Polygon survey from OSAM", "module__nav_survey_poly_osam.html", null ],
    [ "Survey a polygon with a fixedwing", "module__nav_survey_polygon.html", null ],
    [ "Zamboni pattern survey for fixedwings", "module__nav_survey_zamboni.html", null ],
    [ "Copy of nav line with altitude changes at every sweep", "module__nav_vertical_raster.html", null ],
    [ "Angle of Attack using internal ADC", "module__aoa_adc.html", null ],
    [ "Airspeed sensor (ADC)", "module__airspeed_adc.html", null ],
    [ "ADS1114 airspeed sensor", "module__airspeed_ads1114.html", null ],
    [ "Airspeed AMSYS (I2C)", "module__airspeed_amsys.html", null ],
    [ "Airspeed ETS (I2C)", "module__airspeed_ets.html", null ],
    [ "OTF! airspeed/flow angle sensor", "module__airspeed_otf.html", null ],
    [ "SRF08 ultrasonic range meter", "module__alt_srf08.html", null ],
    [ "MS5534a barometer (SPI)", "module__baro_ms5534a.html", null ],
    [ "Baro AMSYS (I2C)", "module__baro_amsys.html", null ],
    [ "Bosch BMP085 pressure sensor", "module__baro_bmp.html", null ],
    [ "Baro ETS (I2C)", "module__baro_ets.html", null ],
    [ "Baro sensortechnics HCA (I2C)", "module__baro_hca.html", null ],
    [ "Baro MPL3115A2 (I2C)", "module__baro_mpl3115.html", null ],
    [ "Baro MS5611 (I2C)", "module__baro_ms5611_i2c.html", null ],
    [ "Baro MS5611 (SPI)", "module__baro_ms5611_spi.html", null ],
    [ "VTI SCP1000 pressure sensor (SPI)", "module__baro_scp.html", null ],
    [ "VTI SCP1000 pressure sensor (I2C)", "module__baro_scp_i2c.html", null ],
    [ "Simulated barometer", "module__baro_sim.html", null ],
    [ "EzOSD Current sensor (I2C)", "module__ezcurrent.html", null ],
    [ "Infrared sensor using ADC", "module__infrared_adc.html", null ],
    [ "I2C Infrared sensor", "module__infrared_i2c.html", [
      [ "Module functions", "module__infrared_i2c.html#functions", [
        [ "Raw temp_lm75.xml file:", "module__temp_lm75.html#module_xml__temp_lm75", null ],
        [ "Raw temp_tcouple_adc.xml file:", "module__temp_tcouple_adc.html#module_xml__temp_tcouple_adc", null ],
        [ "Raw temp_temod.xml file:", "module__temp_temod.html#module_xml__temp_temod", null ],
        [ "Raw temp_tmp102.xml file:", "module__temp_tmp102.html#module_xml__temp_tmp102", null ],
        [ "Raw wind_gfi.xml file:", "module__wind_gfi.html#module_xml__wind_gfi", null ],
        [ "Raw windturbine.xml file:", "module__windturbine.html#module_xml__windturbine", null ],
        [ "Raw mission_fw.xml file:", "module__mission_fw.html#module_xml__mission_fw", null ],
        [ "Raw mission_rotorcraft.xml file:", "module__mission_rotorcraft.html#module_xml__mission_rotorcraft", null ],
        [ "Raw follow.xml file:", "module__follow.html#module_xml__follow", null ],
        [ "Raw formation_flight.xml file:", "module__formation_flight.html#module_xml__formation_flight", null ],
        [ "Raw potential.xml file:", "module__potential.html#module_xml__potential", null ],
        [ "Raw tcas.xml file:", "module__tcas.html#module_xml__tcas", null ],
        [ "Raw nav_bungee_takeoff.xml file:", "module__nav_bungee_takeoff.html#module_xml__nav_bungee_takeoff", null ],
        [ "Raw nav_catapult.xml file:", "module__nav_catapult.html#module_xml__nav_catapult", null ],
        [ "Raw nav_cube.xml file:", "module__nav_cube.html#module_xml__nav_cube", null ],
        [ "Raw nav_drop.xml file:", "module__nav_drop.html#module_xml__nav_drop", null ],
        [ "Raw nav_flower.xml file:", "module__nav_flower.html#module_xml__nav_flower", null ],
        [ "Raw nav_gls.xml file:", "module__nav_gls.html#module_xml__nav_gls", null ],
        [ "Raw nav_line.xml file:", "module__nav_line.html#module_xml__nav_line", null ],
        [ "Raw nav_line_border.xml file:", "module__nav_line_border.html#module_xml__nav_line_border", null ],
        [ "Raw nav_line_osam.xml file:", "module__nav_line_osam.html#module_xml__nav_line_osam", null ],
        [ "Raw nav_smooth.xml file:", "module__nav_smooth.html#module_xml__nav_smooth", null ],
        [ "Raw nav_spiral.xml file:", "module__nav_spiral.html#module_xml__nav_spiral", null ],
        [ "Raw nav_survey_disc.xml file:", "module__nav_survey_disc.html#module_xml__nav_survey_disc", null ],
        [ "Raw nav_survey_poly_osam.xml file:", "module__nav_survey_poly_osam.html#module_xml__nav_survey_poly_osam", null ],
        [ "Raw nav_survey_polygon.xml file:", "module__nav_survey_polygon.html#module_xml__nav_survey_polygon", null ],
        [ "Raw nav_survey_zamboni.xml file:", "module__nav_survey_zamboni.html#module_xml__nav_survey_zamboni", null ],
        [ "Raw nav_vertical_raster.xml file:", "module__nav_vertical_raster.html#module_xml__nav_vertical_raster", null ],
        [ "Raw AOA_adc.xml file:", "module__aoa_adc.html#module_xml__aoa_adc", null ],
        [ "Define Options", "module__airspeed_adc.html#define", null ],
        [ "Raw airspeed_adc.xml file:", "module__airspeed_adc.html#module_xml__airspeed_adc", null ],
        [ "Raw airspeed_ads1114.xml file:", "module__airspeed_ads1114.html#module_xml__airspeed_ads1114", null ],
        [ "Raw airspeed_amsys.xml file:", "module__airspeed_amsys.html#module_xml__airspeed_amsys", null ],
        [ "Raw airspeed_ets.xml file:", "module__airspeed_ets.html#module_xml__airspeed_ets", null ],
        [ "Raw airspeed_otf.xml file:", "module__airspeed_otf.html#module_xml__airspeed_otf", null ],
        [ "Raw alt_srf08.xml file:", "module__alt_srf08.html#module_xml__alt_srf08", null ],
        [ "Raw baro_MS5534A.xml file:", "module__baro_ms5534a.html#module_xml__baro_ms5534a", null ],
        [ "Raw baro_amsys.xml file:", "module__baro_amsys.html#module_xml__baro_amsys", null ],
        [ "Raw baro_bmp.xml file:", "module__baro_bmp.html#module_xml__baro_bmp", null ],
        [ "Raw baro_ets.xml file:", "module__baro_ets.html#module_xml__baro_ets", null ],
        [ "Raw baro_hca.xml file:", "module__baro_hca.html#module_xml__baro_hca", null ],
        [ "Raw baro_mpl3115.xml file:", "module__baro_mpl3115.html#module_xml__baro_mpl3115", null ],
        [ "Raw baro_ms5611_i2c.xml file:", "module__baro_ms5611_i2c.html#module_xml__baro_ms5611_i2c", null ],
        [ "Raw baro_ms5611_spi.xml file:", "module__baro_ms5611_spi.html#module_xml__baro_ms5611_spi", null ],
        [ "Raw baro_scp.xml file:", "module__baro_scp.html#module_xml__baro_scp", null ],
        [ "Raw baro_scp_i2c.xml file:", "module__baro_scp_i2c.html#module_xml__baro_scp_i2c", null ],
        [ "Raw baro_sim.xml file:", "module__baro_sim.html#module_xml__baro_sim", null ],
        [ "Raw ezcurrent.xml file:", "module__ezcurrent.html#module_xml__ezcurrent", null ],
        [ "Raw infrared_adc.xml file:", "module__infrared_adc.html#module_xml__infrared_adc", null ],
        [ "Init Functions", "module__infrared_i2c.html#init_functions", null ],
        [ "Event Functions", "module__infrared_i2c.html#event_functions", null ],
        [ "Periodic Functions", "module__infrared_i2c.html#periodic_functions", null ]
      ] ],
      [ "Files", "module__infrared_i2c.html#files", [
        [ "Header Files", "module__infrared_i2c.html#headers", null ],
        [ "Source Files", "module__infrared_i2c.html#sources", null ],
        [ "Raw infrared_i2c.xml file:", "module__infrared_i2c.html#module_xml__infrared_i2c", null ]
      ] ]
    ] ],
    [ "hmc5843 magnetometer", "module__mag_hmc5843.html", null ],
    [ "HMC58xx magnetometer", "module__mag_hmc58xx.html", null ],
    [ "Micromag magnetometer", "module__mag_micromag_fw.html", null ],
    [ "Pressure Board Navarro", "module__pbn.html", null ],
    [ "External trigger", "module__trigger_ext.html", null ],
    [ "Maximum Power Point Tracker", "module__mppt.html", null ],
    [ "Airborne Antenna tracker", "module__airborne_ant_track.html", null ],
    [ "Battery checker module", "module__bat_checker.html", null ],
    [ "Configure Mikrokopter MKK v2", "module__configure_actuators_mkk_v2.html", null ],
    [ "Demo module", "module__demo_module.html", null ],
    [ "Toggle two gpio pins (Lisa)", "module__deploy_sonar_buoy.html", null ],
    [ "Chemical Enose sensor", "module__enose.html", null ],
    [ "Flight time calculator", "module__flight_time.html", null ],
    [ "Gain set interpolation", "module__gain_scheduling.html", null ],
    [ "Gas Engine Idle", "module__gas_engine_idle.html", null ],
    [ "Generic com", "module__generic_com.html", null ],
    [ "GeoMagnetic field vector", "module__geo_mag.html", null ],
    [ "U-blox GPS (I2C)", "module__gps_i2c.html", null ],
    [ "GSM module", "module__gsm.html", null ],
    [ "QR code gumstix interface", "module__gumstix_qr_code_spi_link.html", null ],
    [ "Graupner HOTT telemetry control module", "module__hott_telemetry.html", null ],
    [ "EA DOG-M163 LCD (SPI)", "module__lcd_dogm.html", null ],
    [ "LED safety indicator", "module__led_safety_status.html", null ],
    [ "Navigation leds", "module__light.html", null ],
    [ "MAX3100 SPI/Uart converter", "module__max3100.html", null ],
    [ "Openlog on-board data logger", "module__openlog.html", null ],
    [ "MAX7456 driver (SPI)", "module__osd_max7456.html", null ],
    [ "Navigate around two poles", "module__poles.html", null ],
    [ "PX4FLOW optical flow sensor", "module__px4flow.html", null ],
    [ "Enables sending of IMU_MAG_CURRENT_CALIBRATION message", "module__send_imu_mag_current.html", null ],
    [ "Servo switch", "module__servo_switch.html", null ],
    [ "Sonar ADC driver", "module__sonar_adc.html", null ],
    [ "Vehicule Interface over Datalink", "module__vehicle_interface_datalink.html", null ]
];